### PR TITLE
Kafka-5206: Remove use of aggSerde in RocksDBSessionStore.

### PR DESCRIPTION
**Pull request by ghost**
RocksDBSessionStore wasn't properly using the default aggSerde if no Serde was supplied.

### CODE REVIEW

**Comment by ghost** [comment]
@dguy I assume you will be assigned to review this because it deals with state stores. I think it is pretty straight forward and could be considered a bug so I was hoping to draw more attention to this as its been a couple days. Let me know if I should create a jira for this.

**Review by dguy — APPROVED** [review]
LGTM

**Comment by dguy** [comment]
@guozhangwang can you please review and merge

**Comment by guozhangwang** [comment]
Thanks @KyleWinkelman for the find! I made another pass over other store impls just to make sure that `store serdes` are used not the raw `keySerde` or `agg/valueSerde`, and it seems KAFKA-5205/5206 are the only issues. But if there are other similar issues please let @dguy and myself know.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and cherry-picked to 0.10.2.

**Pull request closed without merging**
