### PR TITLE
Fixing KAFKA-10094

### PR DESCRIPTION
**Pull request by mtillu**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mtillu** [comment]
PTAL @jghoman

**Review by jghoman — APPROVED** [review]

**Comment by ijuma** [comment]
ok to test

**Comment by mtillu** [comment]
PTAL @jghoman  - Looks like all tests have passed and we are ready for a merge.

**Comment by jghoman** [comment]
Thanks for the contribution, @mtillu !

**Comment by ijuma** [comment]
Thanks for the contribution! Can we please follow the guidelines as described here for future contributions?

https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes

In particular, the PR/commit title should be "KAFKA-10094: In MirrorSourceConnector replace two-step assignment with single call".

Also, we generally include a "Reviewers: " line in the commit message @jghoman.

Thanks once again.

**Comment by mtillu** [comment]
> Thanks for the contribution! Can we please follow the guidelines as described here for future contributions?
> 
> https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes
> 
> In particular, the PR/commit title should be "KAFKA-10094: In MirrorSourceConnector replace two-step assignment with single call".
> 
> Also, we generally include a "Reviewers: " line in the commit message @jghoman.
> 
> Thanks once again.

Thanks for the pointers Ismael, I will!

**Pull request merged**
