### PR TITLE
KAFKA-5737. KafkaAdminClient thread should be daemon

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6790/
Test FAILed (JDK 8 and Scala 2.12).

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by cmccabe** [comment]
Jenkins environment error:
```
Caused: java.io.IOException: Failed to create a temporary directory in /tmp
	at hudson.FilePath$17.invoke(FilePath.java:1375)
```

**Comment by cmccabe** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6805/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6808/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6794/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
Merged to trunk and 0.11.0.

**Pull request closed without merging**
