### PR TITLE
MINOR: Update to Scala 2.11.12 (part 2)

### PR DESCRIPTION
**Pull request by ijuma**
Missed a few places in the previous commit.

### CODE REVIEW

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
SUCCESS 
 8059 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8059 tests run, 5 skipped, 0 failed.
--none--

**Comment by ijuma** [comment]
Merged to trunk and 1.0 branches.

**Comment by asfgit** [comment]
FAILURE
 7951 tests run, 5 skipped, 1 failed.
--none--

**Pull request closed without merging**
