### PR TITLE
MINOR: Reflection free implementation of `defaultKerberosRealm`

### PR DESCRIPTION
**Pull request by ijuma**
The existing implementation triggers warnings in Java 9+ and relies
on internal classes that vary depending on the JDK provider. The proposed
implementation fixes these issues and it's more concise.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rajinisivaram — APPROVED** [review]
@ijuma Thanks for the PR, LGTM

**Comment by ijuma** [comment]
retest this please

**Comment by guozhangwang** [comment]
LGTM, we just need to fix the failing test first.

**Comment by ijuma** [comment]
@guozhangwang I don't think the failures are related, they fail without the change too.

**Comment by guozhangwang** [comment]
That's what I meant, we just need to get https://github.com/apache/kafka/pull/6982 in.

**Comment by ijuma** [comment]
Thanks.

**Comment by ijuma** [comment]
One build passed, one failed due to flaky:

> org.apache.kafka.connect.integration.ExampleConnectIntegrationTest.testSourceConnector

Merging to trunk.

**Pull request merged**
