### PR TITLE
KAFKA-10341: Add 2.6.0 to system tests and streams upgrade tests

### PR DESCRIPTION
**Pull request by rhauch**
BTW, `tests/kafkatest/version.py` was already modified to define the 2.6.0 version constants for the system tests, but these variables were never used. Thus, no need to modify that file.

Based upon #8378 (for 2.5)

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rhauch** [comment]
Just kicked off a build of the Streams system tests (e.g., `TC_PATHS=tests/kafkatest/tests/streams/streams_upgrade_test.py`) using this PR: 
https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4082/

and a full system test run using this PR: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4083/

**Review by mjsax — APPROVED** [review]
Thanks @rhauch! LGTM assuming Jenkins and system tests passed.

**Comment by rhauch** [comment]
Thanks, @mjsax

The streams-only system test run (https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4082/) passed. The other was interrupted by a Jenkins restart. I'll restart the full system test run tomorrow AM.

**Comment by rhauch** [comment]
Green builds on JDK 11 and 14, and two unrelated failures (known flaky integration tests, not system tests) on JDK 8:
```
Test Result (2 failures / +1)
    org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[false]
    org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[true]
```

I started a second run of all system tests with this branch: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4088/

**Comment by rhauch** [comment]
The [second run|https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4088] with all of the system tests had [two failures|http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2020-08-04--001.1596577078--rhauch--kafka-10341--f0164cbb3/report.html]:
```
Module: kafkatest.tests.core.round_trip_fault_test 
Class:  RoundTripFaultTest 
Method: test_round_trip_workload_with_broker_partition

Module: kafkatest.tests.client.consumer_test
Class:  OffsetValidationTest
Method: test_static_consumer_bounce 
Arguments: {   "bounce_mode": "all",   "clean_shutdown": true,   "num_bounces": 5,   "static_membership": false }
```
These have been somewhat flaky recently on the 2.6 branch (at least), but they are not directly affected by this PR.

**Pull request merged**
