### PR TITLE
MINOR: Upgrade version of Gradle entreprise to 3.14.1 & custom user data Gradle plugin to 1.11.1

### PR DESCRIPTION
**Pull request by bmscomp**
In the current minor pull request : 

- Upgrading Gradle entreprise to version  3.14.1
- Upgrade custom user data Gradle plugin to version 1.11.1

The main motivation from this upgrade is to keep up to date this important tool for capturing build scans to get more deeply insights 

To get more information about the the release notes of this version please check: https://plugins.gradle.org/plugin/com.gradle.enterprise/3.14.1

Release notes for custom user data Gradle plugin to 1.11.1: 
https://plugins.gradle.org/plugin/com.gradle.common-custom-user-data-gradle-plugin/1.11.1

Notice that those upgrades are too minor true, but they will allow to use latest stable version available to prevent a drastic changes in the future upgrade of related tools and libraries 

Notice there is no breaking changes 

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by divijvaidya — APPROVED** [review]

**Comment by divijvaidya** [comment]
The last test run had an OOM. Restarting the CI.

**Comment by divijvaidya** [comment]
CI has a compilation error which is fixed by https://github.com/apache/kafka/pull/14126. Please rebase from trunk and we can start the CI run again.

**Comment by bmscomp** [comment]
@divijvaidya  I just made a rebase, wait to see the build results

**Comment by bmscomp** [comment]
There is much tests that fails on the current build

**Comment by bmscomp** [comment]
@divijvaidya  The build now looks far better

**Comment by divijvaidya** [comment]
Unrelated failures
```
[Build / JDK 11 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14131/6/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/Build___JDK_11_and_Scala_2_13___testThreadPoolResize__/)
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsWithCustomForwardingAdminIntegrationTest.testReplicateSourceDefault()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14131/6/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsWithCustomForwardingAdminIntegrationTest/Build___JDK_8_and_Scala_2_12___testReplicateSourceDefault__/)
[Build / JDK 8 and Scala 2.12 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14131/6/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/Build___JDK_8_and_Scala_2_12___testThreadPoolResize__/)
[Build / JDK 17 and Scala 2.13 / org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest.testMultipleServerMechanisms()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14131/6/testReport/junit/org.apache.kafka.common.security.authenticator/SaslAuthenticatorTest/Build___JDK_17_and_Scala_2_13___testMultipleServerMechanisms__/)
[Build / JDK 17 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14131/6/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/Build___JDK_17_and_Scala_2_13___testThreadPoolResize__/)
[Build / JDK 17 and Scala 2.13 / org.apache.kafka.controller.QuorumControllerTest.testBalancePartitionLeaders()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14131/6/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/Build___JDK_17_and_Scala_2_13___testBalancePartitionLeaders__/)
[Build / JDK 17 and Scala 2.13 / org.apache.kafka.trogdor.coordinator.CoordinatorTest.testTaskRequestWithOldStartMsGetsUpdated()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14131/6/testReport/junit/org.apache.kafka.trogdor.coordinator/CoordinatorTest/Build___JDK_17_and_Scala_2_13___testTaskRequestWithOldStartMsGetsUpdated__/)
[Build / JDK 20 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14131/6/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/Build___JDK_20_and_Scala_2_13___testThreadPoolResize__/)
```

**Pull request merged**
