### PR TITLE
MINOR: Support versions with 3 segments in _kafka_jar_versions

### PR DESCRIPTION
**Pull request by ijuma**
The bump from 0.11.1.0-SNAPSHOT to 1.0.0-SNAPSHOT broke a couple
of system tests:

* TestVerifiableProducer.test_simple_run
* KafkaVersionTest.test_multi_version

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6387/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6372/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
@rajinisivaram, maybe you could review this. The two system tests that use this method passed locally and I'm running them in Jenkins now.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6498/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6483/
Test PASSed (JDK 8 and Scala 2.12).

**Review by dguy — APPROVED** [review]
Thanks @ijuma, LGTM. Verified all the regexes work and the system tests passed.

**Comment by ijuma** [comment]
Thanks for the review @dguy, merging to trunk.

**Pull request closed without merging**
