### PR TITLE
KAFKA-18290: Remove deprecated methods of FeatureUpdate

### PR DESCRIPTION
**Pull request by LoganZhuZzz**
*Remove deprecated methods*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@LoganZhuZzz could you please fix the conflicts?

**Comment by LoganZhuZzz** [comment]
> could you please fix the conflicts?

@chia7712 Sorry, I didn’t see it earlier, but it’s already been handled.

**Comment by chia7712** [comment]
the failed test is traced by https://issues.apache.org/jira/browse/KAFKA-15474

**Comment by chia7712** [comment]
@LoganZhuZzz Could you please update the admin docs too? https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java#L1448

**Comment by LoganZhuZzz** [comment]
> Could you please update the admin docs too?

Thank you for pointing that out! I’ve updated the admin docs to reflect the changes. 
Could you please give me some suggestions? @chia7712

**Comment by chia7712** [comment]
@LoganZhuZzz please fix the conflicts.

**Comment by chia7712** [comment]
the failed test is traced by https://issues.apache.org/jira/browse/KAFKA-15474

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
