### PR TITLE
KAFKA-3931: Fix transient failures in pattern subscription tests

### PR DESCRIPTION
**Pull request by vahidhashemian**
Full credit for figuring out the cause of these failures goes to @hachikuji.

### CODE REVIEW

**Comment by vahidhashemian** [comment]
@ijuma @guozhangwang I reverted part of the other commit and used a different fix. I could not reproduce the failures locally with this update. Not sure yet what made the previous code act inconsistently, but I thought this might get the builds pass, and I'll try to figure that out in the meantime.

**Comment by vahidhashemian** [comment]
cc @ewencp @hachikuji

**Comment by vahidhashemian** [comment]
The new fix that I mentioned in my earlier comment adds [minimal changes](https://github.com/apache/kafka/compare/2ff9550...ce01d72#diff-03237b1458dba015b275a7875232d3ec) (go to `Files Changed` tab and find `SubscriptionState.java`) to the original `SubscriptionState.java`.

IMO, the implementation is more readable in what I proposed ([here](https://github.com/apache/kafka/pull/1572/files#diff-03237b1458dba015b275a7875232d3ec)) in the merged pull request, but that solution seems to bring some inconsistency (causing intermittent test failures) that I still have no explanation for.

**Comment by ijuma** [comment]
@vahidhashemian, have you been able to figure out what is the difference in behaviour between this and the code that is currently in trunk?

**Comment by vahidhashemian** [comment]
@ijuma I have just started looking at the logs between the two. I'll share if I find anything interesting.

**Comment by ijuma** [comment]
Thanks.

**Comment by hachikuji** [comment]
Reverting the change may be a little extreme until we understand the cause of the failure (I actually preferred the use of the enum). I haven't been able to reproduce the failure locally in order to debug, but I can try on jenkins.

**Comment by ijuma** [comment]
@hachikuji, yeah, that's why no-one merged this yet. However, the failures happen often enough that it's affecting other PRs. If we can't get to the bottom of it soon, we may have to either revert the original PR or merge this one.

**Comment by vahidhashemian** [comment]
The only way I have been able to get either of the three pattern tests to fail has been running them together. I disable all other tests and let these three to be the remaining active tests. Running single tests has not resulted in  a failure for me so far.

**Comment by hachikuji** [comment]
@vahidhashemian I think I see what's going on. It looks like there's a race condition with the initial metadata fetch and the initial rebalance. We don't actually ensure that the metadata is fresh before joining initially, but we request the metadata update. If that metadata update arrives while the rebalance is still pending (for example, when the join group is still inflight), then we will lose track of the fact that we need to rebalance again to reflect the change to the topic subscription. This seems to be a general problem that we haven't considered before. Any metadata update which changes the topic subscriptions and arrives with a rebalance in progress will essentially be ignored.

**Comment by hachikuji** [comment]
A quick fix which doesn't address the problem completely, but which should get the tests passing again would be to do something like this in `ConsumerCoordinator.ensurePartitionAssignment()`:

``` java
        if (subscriptions.partitionsAutoAssigned()) {
            if (subscriptions.hasPatternSubscription())
                client.ensureFreshMetadata();
            ensureActiveGroup();
        }
```

**Comment by vahidhashemian** [comment]
@hachikuji Thanks a lot for the explanation and the suggested fix. I tested it a bit and could not reproduce the failures anymore. Should I update this PR with this fix? Or you'll create a new PR? Thanks.

**Comment by hachikuji** [comment]
@vahidhashemian I think it makes sense to do it here. I'll open another JIRA to make sure we solve the general problem, but I think this is a necessary part of the solution.

**Comment by vahidhashemian** [comment]
@hachikuji Sounds good. Then I'll go ahead and update this PR. Thanks.

**Comment by hachikuji** [comment]
FYI, here's a link to the JIRA: https://issues.apache.org/jira/browse/KAFKA-3949.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and 0.10.0 branch.

**Pull request closed without merging**
