### PR TITLE
MINOR: Fix typo at StreamsConfig javadoc

### PR DESCRIPTION
**Pull request by ilayaperumalg**

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Retest this please, thanks!

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6043/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6028/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
This is already covered in latest release. Closing for now.

**Pull request closed without merging**
