### PR TITLE
KAFKA-5742 support ZK chroot in system tests

### PR DESCRIPTION
**Pull request by xvrl**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6828/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6814/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ewencp — APPROVED** [review]
@xvrl this lgtm, how far back do we want this back ported?

**Comment by xvrl** [comment]
@ewencp Having it in the 0.11.0 branch would be nice. There are some minor merge conflicts to resolve to backport it, but I have a patch ready for that branch if needed.

**Comment by ewencp** [comment]
LGTM, if you can file the 0.11 JIRA I'll commit that as well.

**Pull request closed without merging**
