### PR TITLE
KAFKA-3838 zkClient and Zookeeper version bump

### PR DESCRIPTION
**Pull request by mangas**

### CODE REVIEW

**Comment by mangas** [comment]
@ijuma here's the PR for trunk

**Comment by ijuma** [comment]
I started a systems test Jenkins build:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/68/console

**Comment by ijuma** [comment]
The systems tests passed. @mangas, can you update `ops.html` which currently mentions ZooKeeper 3.4.6 and zkclient 0.7?

**Comment by mangas** [comment]
@ijuma changed ops.html and security.html

**Comment by ijuma** [comment]
Thanks @mangas, LGTM. Ran the tests locally and they passed.

For reference, I'll mention here that @fpj said that the upgrade sounded fine in the original PR https://github.com/apache/kafka/pull/1504#issuecomment-226109213 .

Merged to trunk.

**Comment by mangas** [comment]
@ijuma thanks for your help, how soon is the next release?

**Comment by ijuma** [comment]
Thanks for the contribution! We don't know when the next release will take place yet.

**Comment by junrao** [comment]
Hmm, with this patch, I got the following error when running ./gradlew clean jar

FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':core:compile'.
  > java.lang.UnsupportedOperationException (no error message)

**Comment by mangas** [comment]
@junrao make sure you have access to maven central when running that as gradle will need to connect to fetch the latest jars that won't exist in the local cache. If you're behind a firewall that might happen, you may want to use another connection or look for the proper proxy configuration

**Pull request closed without merging**
