### PR TITLE
MINOR: Hygiene fixes in KafkaFutureImpl

### PR DESCRIPTION
**Pull request by viktorsomogyi**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by vahidhashemian — APPROVED** [review]
LGTM, thanks for the patch!

**Review by akatona84 — APPROVED** [review]

**Review by omkreddy — APPROVED** [review]
@viktorsomogyi Thanks for the PR. LGTM.

**Comment by ijuma** [comment]
@omkreddy the commit message has the following:

```
Change-Id: Ia44c6c659418bbed5367645b814725365daba820
```

What's that?

**Comment by viktorsomogyi** [comment]
@ijuma that is a Gerrit change-id,  needed for another repo. A git hook generates it for me and although it is harmless I fixed it in my git so my newer PRs doesn't contain it.

**Pull request merged**
