### PR TITLE
KAFKA-4754: Correctly parse '=' characters in command line overrides

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by omkreddy** [comment]
LGTM

**Comment by cmccabe** [comment]
Could you add another test case?

LGTM (non-binding) aside from that.

**Comment by granthenke** [comment]
@cmccabe What should I test thats not covered?

**Comment by cmccabe** [comment]
Test values with multiple equals signs, not just one.  Test cases where you have --key= but no value (if that's not already covered by existing cases).  Test corner cases like "-=" as the entire flag.

**Comment by omkreddy** [comment]
Closing, as this fixed in #5630

**Pull request closed without merging**
