### PR TITLE
MINOR: Fix the TBRLMMRestart test.

### PR DESCRIPTION
**Pull request by kamalcph**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kamalcph** [comment]
@abhijeetk88 @satishd @showuon 

This is a regression after #14127 patch.

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the fix! I'll merge it immediately once CI build completed.

**Review by satishd — APPROVED** [review]
Thanks @kamalcph for the PR. LGTM.

**Comment by satishd** [comment]
There are a few test failures that are unrelated to this change. Merging to trunk and 3.6 branches.

**Pull request merged**
