### PR TITLE
MINOR: Enable "abort previous builds" for PRs

### PR DESCRIPTION
**Pull request by ijuma**
When a new commit is pushed to a PR, we should abort the build
and start a new one instead of queuing one build per commit.
This reduces wasted resources and provides the desired feedback
faster (since we only care about the build results for the last
commit in the PR).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
@omkreddy @showuon Can you please review this?

**Review by showuon — COMMENTED** [review]
Nice new jenkins feature! Thanks for bringing it to Kafka. But, I'm afraid if we enable it, it'll be difficult to find out which commit breaks the build if it mixes many commits. Like previously, we figured out there's performance regression after a specific commit looks irrelevant: https://github.com/apache/kafka/pull/11873#issuecomment-1064230020 . 
Thoughts?

**Comment by ijuma** [comment]
@showuon This only affects commits within a PR, so I don't think your concern applies here. Let me know if I misunderstood your point.

**Review by showuon — APPROVED** [review]
LGTM! The PR build really needs this feature! Thanks.

**Comment by ijuma** [comment]
I verified that the build was aborted as expected when there's a new commit:

image

**Comment by showuon** [comment]
Cool! Thank you!

**Pull request merged**
