### PR TITLE
KAFKA-17283: Integration test for share group heartbeat

### PR DESCRIPTION
**Pull request by apoorvmittal10**
The PR adds integration test for share group. The PR should be reveiwed and merged post PR: #16786 .

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by AndrewJSchofield — APPROVED** [review]
lgtm

**Comment by chia7712** [comment]
@apoorvmittal10 Could you please take a look at failed tests: `testGroupCoordinatorChange` and `testShareGroupHeartbeatWithMultipleMembers`?

**Comment by apoorvmittal10** [comment]
> @apoorvmittal10 Could you please take a look at failed tests: `testGroupCoordinatorChange` and `testShareGroupHeartbeatWithMultipleMembers`?

Yes, the current PR is dependent on https://github.com/apache/kafka/pull/16786. Once 16786 is merged then tests will start passing. I will rebase the PR once dependent PR is merged.

**Comment by apoorvmittal10** [comment]
@chia7712 @omkreddy Build passed with unrelated tests failure.

**Review by omkreddy — APPROVED** [review]
@apoorvmittal10 Thanks for the PR. LGTM

**Pull request merged**
