### PR TITLE
MINOR: Fixes for adding new DSL naming page

### PR DESCRIPTION
**Pull request by bbejeck**
Added re-direct for new page and added link to `Developer Guide` page

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @mjsax @ableegoldman 

companion PR to one submitted to kafka-site https://github.com/apache/kafka-site/pull/248

**Comment by bbejeck** [comment]
Will cherry-pick this PR to 2.4 once merged

**Review by ableegoldman — APPROVED** [review]
LGTM, thanks for the quick fix!

**Review by mjsax — APPROVED** [review]

**Comment by bbejeck** [comment]
Merged #7899 into trunk

**Comment by bbejeck** [comment]
cherry-picked to 2.4

**Pull request merged**
