### PR TITLE
MINOR: Fix Transient test failure SslTransportLayerTest.testNetworkThreadTimeRecorded

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@rajinisivaram Observing below transient test failure after recent changes

```
[2018-09-01 19:33:57,370] TRACE About to close the idle connection from 127.0.0.1:57234-127.0.0.1:57235 due to being idle for 5018 millis (org.apache.kafka.common.network.Selector:705)
[2018-09-01 19:33:57,371] DEBUG [SslTransportLayer channelId=127.0.0.1:57234-127.0.0.1:57235 key=sun.nio.ch.SelectionKeyImpl@f179795] Failed to send SSL Close message (org.apache.kafka.common.network.SslTransportLayer:180)
java.io.IOException: Remaining data in the network buffer, can't send SSL close message.
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:165)
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:830)
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:107)
	at org.apache.kafka.common.network.Selector.doClose(Selector.java:836)
	at org.apache.kafka.common.network.Selector.close(Selector.java:820)
	at org.apache.kafka.common.network.Selector.maybeCloseOldestConnection(Selector.java:708)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
	at org.apache.kafka.common.network.NioEchoServer.run(NioEchoServer.java:156)
[2018-09-01 19:33:57,729] DEBUG Connection with localhost/127.0.0.1 disconnected (org.apache.kafka.common.network.Selector:575)
java.io.EOFException: EOF during read
	at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:569)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:117)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:360)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:321)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at org.apache.kafka.common.network.SslTransportLayerTest$4.conditionMet(SslTransportLayerTest.java:707)
	at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:269)
	at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:256)
	at org.apache.kafka.common.network.SslTransportLayerTest.testNetworkThreadTimeRecorded(SslTransportLayerTest.java:703)

java.lang.AssertionError: Condition not met within timeout 15000. Timed out waiting for a message to receive from echo server

	at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:278)
	at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:256)
	at org.apache.kafka.common.network.SslTransportLayerTest.testNetworkThreadTimeRecorded(SslTransportLayerTest.java:703)
```

**Comment by rajinisivaram** [comment]
@omkreddy Thanks for the PR. Are you able to recreate this issue? It wasn't clear from the exception above if this was just idle time being too low or whether there is some other issue causing receive not to succeed and idle timeout was hit as a result.

**Comment by omkreddy** [comment]
@rajinisivaram test is consistently failing on my machine with 5 sec idle time.  I am not able to reproduce  with 10 sec idle time.

**Review by rajinisivaram — APPROVED** [review]
@omkreddy Thanks for the PR, LGTM. Merging to trunk.

**Pull request merged**
