### PR TITLE
MINOR: move some client methods to new ClientUtils

### PR DESCRIPTION
**Pull request by ableegoldman**
Moves three "types" of methods:

1) `getXXXClientId`
2) `XXXClientMetrics`
3) `fetchEndOffsets`

### CODE REVIEW

**Comment by ableegoldman** [comment]
cc/ @vvcephei

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
Test this please

**Comment by vvcephei** [comment]
Test this please

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
test this please

**Pull request merged**
