### PR TITLE
MINOR: Make the constructor of InMemoryKeyValueLoggedStore public 

### PR DESCRIPTION
**Pull request by hashangayasri**
Make the constructor of InMemoryKeyValueLoggedStore public so that it can be re-used by custom (in-memory) stores

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
@hashangayasri  The constructor is package private on purpose, because this class is part of package `internals` and not part of the public API but an internal implementation that might change at any point in time. Can you elaborate on your use case? It seem not to be safe with regards to upgrading to extend this class.

**Comment by hashangayasri** [comment]
@mjsax Yes, but still the interface this implements is public and as the class itself is public. Also, the other related class - InMemoryKeyValueStore has a public constructor already. Note that I've only made the constructor of InMemoryKeyValueLoggedStore public. 

As for the use case, I made an in memory store (logging and none logging by using InMemoryKeyValueLoggedStore and InMemoryKeyValueStore respectively) by wrapping these stores. Almost all the code from the already implemented stores can be reused for mine. Since I'm re using the already implemented stores, my extra code is very short.

The purpose for the new store is to introduce object deduplication before serialisation and log compaction since my state is large and serialisation takes more than 60% of CPU time when profiled.

As for reusing classes in the internal package - as long as the classes implement the public interface, it'll work for me.

**Comment by mjsax** [comment]
Thanks for explaining you use case. I am still not sure, if you should inherit from those classes thought. Note, that they might get change (even in a bug fix release) without notices, because they are not part of public API.

\cc @guozhangwang @bbejeck @vvcephei WDYT?

**Comment by guozhangwang** [comment]
Note that since this class belongs to `internals` package, even making its constructor as public does not mean we are guaranteeing it is a public interface now and we will not change its signature / implementation later on. So I'm fine with this change as long as @hashangayasri 's aware of this and is OK with it.

**Comment by hashangayasri** [comment]
Thank you for the quick responses.

@mjsax Although it's not ideal, I think in my case, inheriting from it is better than the alternative - copying the code to make a new class esp since my additions are extremely minimal compared to the original class.

@guozhangwang Since I'm only wrapping the init method from the StateStore interface and the constructor for creating the object, any change in the signature or the implementation would be okay for me as long as the class does what its name implies. My code would break if the constructor is changed, but that's the expected behaviour.

(The pull request was closed by mistake)

**Comment by hashangayasri** [comment]
Thank you for the quick responses.

@mjsax Although it's not ideal, I think in my case, inheriting from it is better than the alternative - copying the code to make a new class esp since my additions are extremely minimal compared to the original class.

@guozhangwang Since I'm only wrapping the init method from the StateStore interface and the constructor for creating the object, any change in the signature or the implementation would be okay for me as long as the class does what its name implies. My code would break if the constructor is changed, but that's the expected behaviour.

**Comment by mjsax** [comment]
@hashangayasri Not sure why you closed and reopened this PR? Did you try to trigger Jenkins? If yes, note, that you can leave a comment "Retest this please." to trigger Jenkins to re-run the build.

**Comment by mjsax** [comment]
Thanks for the PR @hashangayasri.

Merged to `trunk`.

**Pull request merged**
