### PR TITLE
KAFKA-5566: fix unit test shouldAllowToQueryAfterThreadDied

### PR DESCRIPTION
**Pull request by enothereska**
Ensure only one thread dies, not both.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5960/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5945/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by enothereska** [comment]
@dguy @mjsax I believe this was the problem.

**Review by dguy — APPROVED** [review]
Thanks @enothereska, LGTM

**Comment by dguy** [comment]
Merged to trunk and cherry-picked to 0.11.0

**Pull request closed without merging**
