### PR TITLE
Reducing code duplication in DefaultEventHandler

### PR DESCRIPTION
**Pull request by lazyval**
No functionality was changed -- just removed code duplication & [get advantage of case class copy method](http://stackoverflow.com/questions/7249396/how-to-clone-a-case-class-instance-and-change-just-one-field-in-scala).

### CODE REVIEW

**Comment by lazyval** [comment]
Interestingly enough tests are passing locally: 

```
BUILD SUCCESSFUL

Total time: 11 mins 22.28 secs
```

Is this flicky tests on CI env?

**Comment by granthenke** [comment]
This is the failure:

> kafka.api.ConsumerBounceTest > testSeekAndCommitWithBrokerFailures FAILED
>     kafka.common.KafkaException: Socket server failed to bind to localhost:54667: Address already in use.
>         at kafka.network.Acceptor.openServerSocket(SocketServer.scala:281)

This may be related to open file handles. The unit tests have a lot of them. Not sure if they are leaking. There have been some discussions here:
- [KAFKA-2398](https://issues.apache.org/jira/browse/KAFKA-2398)
- [Kafka Unit Test Failures on a Mac](http://search-hadoop.com/m/uyzND1hazyw1XiDyH1/Kafka+Unit+Test+Failures+on+a+Mac&subj=Kafka+Unit+Test+Failures+on+a+Mac)
- [KAFKA-1782](https://issues.apache.org/jira/browse/KAFKA-1782)

**Comment by lazyval** [comment]
@granthenke what's my actions on this then? Errors seems to be unrelated to changes, I've made

oh, and by the way your home page does not work: 

database error 2015-08-08 02-16-29

**Comment by granthenke** [comment]
I agree. I would try to re-submit the pull request. The contributing docs say this:

[Contributing Code Changes](https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes)

> Despite our efforts, Kafka may have flaky tests at any given point, which may cause a build to fail. Unfortunately, it's not currently possible to restart the build by issuing a command... A workaround is to close and reopen the PR. If the failure is unrelated to your pull request and you have been able to run the tests locally successfully, please mention it in the pull request.

**Comment by b-goyal** [comment]
No functionality was changed -- just removed code duplication & [get advantage of case class copy method](http://stackoverflow.com/questions/7249396/how-to-clone-a-case-class-instance-and-change-just-one-field-in-scala).

**Pull request closed without merging**
