### PR TITLE
KAFKA-5476: Implement a system test that creates network partitions

### PR DESCRIPTION
**Pull request by cmccabe**
KAFKA-5476: Implement a system test that creates network partitions

### CODE REVIEW

**Comment by cmccabe** [comment]
Right now, this pull request incorporates KAFKA-5484, since that is needed to test it.  The goal is to get KAFKA-5484 committed first, though. See https://github.com/apache/kafka/pull/3389

The general approach here is to use iptables to create network partitions.  We create DENY rules in iptables which prevent nodes in one partition from talking to nodes in another.  However, it is still possible for the controller node to talk to nodes in any partition, and it is still possible for the nodes to talk to the internet.

There are three tests included here: a unit test of NetworkFracture, a sanity test which tests that NetworkFracture actually does fracture the network, and a producer/consumer test that verifies that we are robust in the face of network partitions.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5599/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5585/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5804/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5818/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
Just checking, is this ready for review?

**Comment by cmccabe** [comment]
This is superseded by https://github.com/apache/kafka/pull/3726

**Pull request closed without merging**
