### PR TITLE
KAFKA-2990: add explicit ConcurrentMap type annotation to fix NoSuchMethodError in Pool

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by ijuma** [comment]
In my opinion, this is not a bug. There is no guarantee that compiling with 1.8 will work when executed with 1.7. Having said that, it's a tiny change and could be justified on its own merits (ie expose the interface, not the implementation). So LGTM.

**Comment by ewencp** [comment]
LGTM

**Comment by ijuma** [comment]
Can you fix the PR title though? There is no cast in your code, just a type annotation (casts are unsafe, type annotation are not).

**Comment by hachikuji** [comment]
@ijuma I saw these errors when running ducktape tests, so if we're not supporting it, then we should make sure that ducktape vms use 1.8 jdk when running tests.

**Comment by ijuma** [comment]
@hachikuji, you're supposed  to compile Kafka with Java 7 (and you can run with both 7 and 8, 8 recommended).

**Comment by ewencp** [comment]
@hachikuji @ijuma This is something that we check in `build.sh` in muckrake, but which I don't think is validated anywhere for kafka tests because we just assume the version built in the checked out copy will work, but the VMs install JDK7.

We should probably add validation of of the build version of java somewhere. I think 7/8 issues have happened a few times. I just always stick to the minimum Java version supported, which also prevents accidental use of newer libraries during development, but I know not everyone likes doing that. Another option is building separately within each VM, but that's annoyingly expensive. Beyond having some preflight check for tests to check java version, I'm not sure there's a great solution.

**Comment by ijuma** [comment]
Adding a check sounds good to me. I think people often don't do it because they're not aware that it can cause issues.

**Comment by hachikuji** [comment]
If Java 7 is needed to build, then we should document that requirement. We also have checks in the gradle file which are specific to Java 8 (doclint in particular), so it's not unreasonable for users to assume it's supported.

**Comment by ijuma** [comment]
@hachikuji Filed https://github.com/apache/kafka/pull/677 for the documentation side. Regarding the Java 8 doclint code in Gradle, we do have a Java 8 build in Jenkins, but it both compiles and runs with Java 8 (this helps ensure that our code also compiles with Java 8 making it easy to move to that version when the time comes).

**Comment by ijuma** [comment]
By the way, this will no longer be an issue when Java 9 is released in 2017:

http://openjdk.java.net/jeps/247

;)

**Pull request closed without merging**
