### PR TITLE
MINOR: Fix version in environment setup

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
I tested the fix by running Streams' upgrade tests. Before they were failing.

**Comment by cadonna** [comment]
Call for review @abbccdda @ableegoldman @mjsax @vvcephei @bbejeck @guozhangwang

**Comment by bbejeck** [comment]
Thanks for the fix @cadonna LGTM.  Can you add the link for the passing system tests to the comments?

**Review by vvcephei — APPROVED** [review]
LGTM. Thanks!

**Comment by vvcephei** [comment]
http://testing.confluent.io/confluent-kafka-branch-builder-system-test-results/?prefix=2019-06-26--001.1561552929--cadonna--fix_version_211_upgrade--2dabfde/

http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2019-06-26--001.1561552929--cadonna--fix_version_211_upgrade--2dabfde/report.html

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
Waiting for a green build to complete for merging

**Review by guozhangwang — APPROVED** [review]

**Comment by bbejeck** [comment]
retest this please

**Review by abbccdda — APPROVED** [review]

**Comment by bbejeck** [comment]
Merged #7004 into 2.2

**Comment by bbejeck** [comment]
Thanks for the fix @cadonna!

**Pull request merged**
