### PR TITLE
Commits the Gradle wrapper jar/properties file

### PR DESCRIPTION
**Pull request by valdisrigdon**
Per the Gradle user guide, https://docs.gradle.org/current/userguide/gradle_wrapper.html,
it's recommended that these are committed into version control. 

This allows for out-of-the-box running of `gradlew` or `gradlew.bat`.

### CODE REVIEW

**Comment by ewencp** [comment]
These are intentionally omitted to avoid them leaking into the source releases, which is not permitted by Apache rules. Check the mailing list for a couple of previous discussions around this issue.

**Comment by matzew** [comment]
should this PR be closed ?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5456/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5471/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by ewencp** [comment]
Closing as this is intentional.

**Pull request closed without merging**
