### PR TITLE
MINOR: Consolidate Topic classes

### PR DESCRIPTION
**Pull request by ijuma**
During the 0.11.0.0 cycle, a Java version of the class
was introduced so that Streams could use it. Given that
it includes the bulk of the functionality of the Scala
version of the class, it makes sense to consolidate them.

While doing this, I noticed that one of the tests for
the Java class (`shouldThrowOnInvalidTopicNames`) was
broken as it only checked if the first topic name in
the list was invalid.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji or @guozhangwang.

**Comment by ijuma** [comment]
Failure is unrelated (fixed by https://github.com/apache/kafka/pull/3042), will run the PR builder again just to be sure.

**Comment by ijuma** [comment]
retest this please

**Comment by guozhangwang** [comment]
LGTM!

**Comment by guozhangwang** [comment]
BTW I have not seen this before, is this new?

```

kafka.metrics.MetricsTest > testBrokerTopicMetricsUnregisteredAfterDeletingTopic FAILED
    java.lang.AssertionError: Topic metrics exists after deleteTopic
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at kafka.metrics.MetricsTest.testBrokerTopicMetricsUnregisteredAfterDeletingTopic(MetricsTest.scala:89)
```

**Comment by ijuma** [comment]
Thanks for the review @guozhangwang. That failure is explained and fixed here https://github.com/apache/kafka/pull/3042

**Pull request closed without merging**
