### PR TITLE
KAFKA-2072: Add StopReplica request/response to o.a.k.common.requests

### PR DESCRIPTION
**Pull request by dajac**
This PR adds StopReplica request and response as it is required by @ijuma for KAFKA-2411. Migration of core module is addressed a separate PR (#141).

@ijuma Could you review it? @gwenshap Could you take a look as well?

### CODE REVIEW

**Comment by dajac** [comment]
Failure is not related to this one.

```
kafka.consumer.MetricsTest > testMetricsLeak FAILED
```

**Comment by dajac** [comment]
@ijuma Thank you for the review. I think that I have addressed most of your comments.

**Comment by ijuma** [comment]
LGTM. As this doesn't change any running code, it's low-risk.

**Comment by junrao** [comment]
Thanks for the patch. LGTM.

**Pull request closed without merging**
