### PR TITLE
MINOR: Implement `toString` in some Validator instances

### PR DESCRIPTION
**Pull request by ijuma**
This is used in the generated config table. Also fix a couple
of typos in the process.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @rajinisivaram.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5749/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5763/
Test PASSed (JDK 7 and Scala 2.11).

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Merging to trunk and 0.11.0.

**Pull request closed without merging**
