### PR TITLE
KAFKA-12613: Inconsistencies between Kafka Config and Log Config

### PR DESCRIPTION
**Pull request by dongjinleekr**
Here is how I fixed the inconsistencies:

- `log.index.size.max.bytes` (`segment.index.bytes`): `KafkaConfig` seems right. (`atLeast(4)`)
- `log.flush.interval.messages` (`flush.messages`): `KafkaConfig` seems right. (`atLeast(0)`)
- `log.cleaner.delete.retention.ms`, `log.cleaner.min.compaction.lag.ms`, `log.cleaner.max.compaction.lag.ms`, `log.cleaner.min.cleanable.ratio`, `log.message.timestamp.difference.max.ms`:  `LogConfig` seems right. (i.e., Validation is omitted in `KafkaConfig`)

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
Here is some reproduction:

Before: the user can dynamically set `log.cleaner.min.cleanable.ratio` to -1.0, which is disallowed in Log configuration:

before

After: if the user tries to set `log.cleaner.min.cleanable.ratio` to -1.0, an error occurs:

after

**Comment by dongjinleekr** [comment]
Here is a reproduction:

Before (2.7.0): the user can dynamically set `log.cleaner.min.cleanable.ratio` to -1.0, which is disallowed in Log configuration:

before

After: if the user tries to set `log.cleaner.min.cleanable.ratio` to -1.0, an error occurs:

after

**Comment by dongjinleekr** [comment]
@hachikuji @ijuma It seems like this one is already a little bit late for 2.7.1, 2.8.0. Isnt't it?

**Comment by dongjinleekr** [comment]
@guozhangwang @kkonstantine Could you have a look? I think this issue should be addressed in 3.0.0.

**Comment by dongjinleekr** [comment]
@rajinisivaram Could you have a look?

**Comment by dongjinleekr** [comment]
Rebased onto the latest trunk.

**Comment by dongjinleekr** [comment]
@kowshik @rajinisivaram Could you kindly have a look? :bowing_man:

**Review by mimaison — APPROVED** [review]
Thanks for the PR! LGTM

**Pull request merged**
