### PR TITLE
KAFKA-16605: Fix the flaky LogCleanerParameterizedIntegrationTest

### PR DESCRIPTION
**Pull request by kamalcph**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by johnnychhsu** [comment]
nice fix! crystal clear solution :)

**Review by showuon — APPROVED** [review]
So even if the log start offset is updated, the log deletion might still not completed. OK, makes to me. Thanks for the fix.

**Comment by showuon** [comment]
Re-triggering CI build: https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-15787/3/

**Comment by kamalcph** [comment]
Opened #15793 to port it to v3.7 branch.

**Pull request merged**
