### PR TITLE
KAFKA-5695; Test DeleteRecordsRequest in AuthorizerIntegrationTest

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6512/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6498/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
Thanks for improving the tests! Conflicts need to be fixed though.

**Comment by lindong28** [comment]
@ijuma Thanks for the review! I have rebased the patch and resolved conflicts.

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Pull request closed without merging**
