### PR TITLE
MINOR: KIP-160 docs

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
This only contain very minor doc changes as most of KIP-160 changes will be replaced by KIP-182.

**Comment by guozhangwang** [comment]
ping @bbejeck @jedichien @dguy @mjsax to review

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
