### PR TITLE
HOT_FIX: Changes needed to correct cherry-pick

### PR DESCRIPTION
**Pull request by bbejeck**
Fixes needed to correct changes from cherry-pick to `2.1`

I ran all streams tests

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM!

**Review by mjsax — APPROVED** [review]
LGTM (assuming Jenkins passes).

**Review by vvcephei — APPROVED** [review]
LGTM as well.

**Comment by mjsax** [comment]
Know flaky test failed on Java8: https://issues.apache.org/jira/browse/KAFKA-7937
Java11 passed.

Retest this please.

**Comment by bbejeck** [comment]
Java 11 passed, Java 8 failed with `kafka.admin.ResetConsumerGroupOffsetTest.testResetOffsetsNotExistingGroup`

retest this please

**Comment by bbejeck** [comment]
Merged #6414 into `2.1`

**Pull request merged**
