### PR TITLE
MINOR: remove unnecessary main method in ProducerConfig

### PR DESCRIPTION
**Pull request by yx9o**
Change:
Move the main test of ProducerConfig to ProducerConfigTest

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by m1a2st — COMMENTED** [review]
Hello @yx9o, Thanks for this PR, but this main method is not unnessary, we shouldn't remove it.

**Comment by yx9o** [comment]
> Hello @yx9o, Thanks for this PR, but this main method is not unnessary, we shouldn't remove it.

Thank you for your reply. I see that the main method is mainly used for testing. May I ask why it is not put into the Test class? Is there any special consideration?

**Comment by m1a2st** [comment]
In build gradle, there are some generator using this main class
https://github.com/apache/kafka/blob/24689dc6ab8f94ba4e7f33f1e874c06d8e29efa1/build.gradle#L1200

**Comment by yx9o** [comment]
Thanks for the guide, I will close it.

**Pull request closed without merging**
