### PR TITLE
[DOCS] KAFKA-4130: Link to Varnish architect notes is broken

### PR DESCRIPTION
**Pull request by oscerd**
Hi all,

The PR is related to 

https://issues.apache.org/jira/browse/KAFKA-4130

Thanks,
Andrea

### CODE REVIEW

**Comment by sslavic** [comment]
LGTM

**Comment by oscerd** [comment]
Is there any interest around this PR?

**Comment by hachikuji** [comment]
@oscerd This seems to have gotten lost in the noise. If you reopen it, I will merge.

**Comment by oscerd** [comment]
No problemi. Reopened :-)

**Comment by oscerd** [comment]
I closed the PR to cut the queue a bit

**Comment by hachikuji** [comment]
LGTM. Merging to trunk and 0.10.1.

**Pull request closed without merging**
