### PR TITLE
KAFKA-8723: Increase timeout on LeaderElectionCommandTest

### PR DESCRIPTION
**Pull request by stanislavkozlovski**

### CODE REVIEW

**Comment by stanislavkozlovski** [comment]
We have seen this test fail sometimes, like in https://issues.apache.org/jira/browse/KAFKA-8723, due to a timeout

```
15:52:26 kafka.admin.LeaderElectionCommandTest > testAllTopicPartition STARTED*15:53:08* kafka.admin.LeaderElectionCommandTest.testAllTopicPartition failed, log available in /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk8-scala2.11@2/core/build/reports/testOutput/kafka.admin.LeaderElectionCommandTest.testAllTopicPartition.test.stdout
*15:53:08* 15:53:08 kafka.admin.LeaderElectionCommandTest > testAllTopicPartition FAILED
*15:53:08* kafka.common.AdminCommandFailedException: Timeout waiting for election results
*15:53:08* at kafka.admin.LeaderElectionCommand$.electLeaders(LeaderElectionCommand.scala:133)
15:53:08 at kafka.admin.LeaderElectionCommand$.run(LeaderElectionCommand.scala:88)
```
That was from the 28th of July

Two JIRAs related to the same timeout issue in the test:
https://issues.apache.org/jira/browse/KAFKA-8785 (10th August)
https://issues.apache.org/jira/browse/KAFKA-8541 (14th June, 31st July)

I think it makes sense to increase the default 30s timeout to a minute. It shouldn't slow down the test as I imagine we rarely hit it.

cc @abbccdda @bbejeck @hachikuji @jsancio

**Comment by jsancio** [comment]
Thanks @stanislavkozlovski. Looks good to me. It is surprising that 30 seconds it not long enough to do manual leader election on the CI machines.

**Comment by stanislavkozlovski** [comment]
It's very rare as you can see. It's only failed 4 times in the last 3 months

**Review by jsancio — APPROVED** [review]
LGTM! Thanks @stanislavkozlovski

**Comment by stanislavkozlovski** [comment]
cc @hachikuji would you have time to review this?

**Comment by stanislavkozlovski** [comment]
Friendly ping @hachikuji @ijuma @cmccabe 👋

**Comment by stanislavkozlovski** [comment]
It is likely https://issues.apache.org/jira/browse/KAFKA-8962 fixed this flaky test. I will close this PR for now

**Pull request closed without merging**
