### PR TITLE
MINOR: Use ApiUtils' methods static imported consistently.

### PR DESCRIPTION
**Pull request by dongxuwang**
Because there have been using the static import methods of ApiUtils, it is not necessary to import the whole ApiUtils which also keeps the consistency.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — APPROVED** [review]
@dongxuwang Thanks for your patch. LGTM

**Comment by chia7712** [comment]
There are similar issues in ```KafkaStreams```, ```Materialized```, ```SessionWindows```, ```SlidingWindows```, ```TimeWindows```,  ```ProcessorContextImpl``` and ```Stores```. Could you fix them as well?

**Comment by dongxuwang** [comment]
Sorry, didn't check others. Let me see and will push them on this branch.

**Comment by dongxuwang** [comment]
@chia7712 Hi Ping, can you help take a look, thanks.

**Review by chia7712 — APPROVED** [review]
@dongxuwang Thanks for your patch. LGTM

**Pull request merged**
