### PR TITLE
KAFKA-5542: Improve Java doc for LeaderEpochFileCache.endOffsetFor()

### PR DESCRIPTION
**Pull request by benstopford**

### CODE REVIEW

**Comment by benstopford** [comment]
cc @junrao

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5831/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5845/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by junrao** [comment]
@benstopford : Thanks for the patch. LGTM

**Pull request closed without merging**
