### PR TITLE
KAFKA-4613: Treat null-key records the same way for joins and aggreations

### PR DESCRIPTION
**Pull request by jeyhunkarimov**

### CODE REVIEW

**Comment by mjsax** [comment]
Can you please have a look at the corresponding tests. I am wondering why there is no test for this that needs an update, too -- I guess we should add a test.

**Comment by jeyhunkarimov** [comment]
@mjsax thanks for review. I have added some tests. 
Basically, I added some tuples with `null` values to respective test classes. However I got failing tests from `KtableSourceTest` class. So, I had to remove `null` keys from `KtableSource.process` as otherwise the tests were failing. However, the important point is that, now that we changed `KtableSource.process`, the changes to `KTableKTableLeftJoin`, `KTableKTableJoin` and etc. does not matter. So, even if we throw exception  (when we encounter null keys) in corresponding classes, the null keys will be eliminated in `KtableSource` class.

**Comment by mjsax** [comment]
Overall looks good to me. I am wondering, if we should collect some metrics about dropped records? \cc @guozhangwang @enothereska @dguy

**Comment by guozhangwang** [comment]
Thanks @jeyhunkarimov , the patch itself looks promising to me.

I think we need to think a bit more whether we should be "dropping records" or "raise exception" for all cases. To me the former makes sense if users would only put null key by mistake and hence would not care about those records. But I have not seen much of these scenarios so would want to hear other's opinion: @dguy @enothereska 

If we go with the "dropping records" direction, then I think we should add a metric for this case. Note we already have a thread-level "skippedRecordsSensor", and this processorNode-level sensor should add it as its parent.

**Comment by jeyhunkarimov** [comment]
@guozhangwang , You are right. Maybe we could add additional configuration parameter regarding this ambiguity. In any case, please ping me once you reach some decision. Thanks.

**Comment by enothereska** [comment]
I think we can proceed with this PR, and then add a JIRA about adding metrics. That might require a quick KIP that shouldn't delay this. LGTM

**Comment by enothereska** [comment]
Nice, LGTM.

**Comment by dguy** [comment]
@guozhangwang - interesting question. Maybe this should be something that is configurable? I'm not 100% sure, but i'm not a big fan of silently dropping the messages (even if they are recorded via metrics). The null keys could indicate problems with upstream producers - surely someone wants to know there are issues? For some apps users wont care and will be happy to drop the records, for others it might be important to stop processing.

**Comment by mjsax** [comment]
@enothereska I don't think we need a KIP for the metrics -- we are using an existing sensor that is used to track records that get dropped because of negative timestamps.

Or do you suggest to use a new sensor for track this?

About configuration: I am always a big fan of that! But for we, we really would need a KIP, as we add a new parameter. Question is also, what should be the default. Maybe for this PR, we use the conservative default and throw and exception. As a follow up with a KIP, we introduce a new configuration to enable dropping plus adding the sensor. WDYT?

**Comment by guozhangwang** [comment]
Thanks for your feedbacks @enothereska @dguy , how about fire-and-update then: accepting this change with the java doc API change indicating null-keys will be ignored if they are not mentioned yet; file another JIRA for metrics as a follow-up. And then see how user's like it or complain about it.

**Comment by guozhangwang** [comment]
@jeyhunkarimov Could you make a pass over `KStream` and `KTable` interface and see if the involved functions as already indicate that null-keyed records will be dropped? If not please update them accordingly.

**Comment by jeyhunkarimov** [comment]
@guozhangwang Sure. 
Please assign the follow-up JIRA to me.

**Comment by jeyhunkarimov** [comment]
@guozhangwang Just to be sure, did you mean checking only join related APIs of `KStream/KTable` or all applicable APIs? So, are we going to treat `drop-null `behaviour to all APIs? For example, I see that flatmap (`KStreamFlatMapProcessor`) does not check for `null`. So, if we try to behave similar (avoid `null` keys) in all `Processors` I think we should avoid code replication.

**Comment by guozhangwang** [comment]
@jeyhunkarimov Let's not keep enlarging the scope of this PR, and only restrict to joins.

**Comment by mjsax** [comment]
@jeyhunkarimov `null` checks are only required for operators that require partitioning (like aggregates and joins). For operators like map etc, it does not matter if key is `null` or not.

The Jira is really about to get consistent behavior for joins and aggregates.

**Comment by dguy** [comment]
It makes me a bit uneasy just dropping the null records as it might mask bugs in user code. My preference would be:
1. In this PR consistently throw exceptions.
2. In another PR make it configurable

**Comment by jeyhunkarimov** [comment]
I don't know why some of tests fails, I just added some comments to `KTable`, rebased and pushed. (Previous commit passed without any problem)

**Comment by dguy** [comment]
@jeyhunkarimov there are some transient failures in the kafka core build. Not related to this PR.

**Comment by mjsax** [comment]
retest this please

**Comment by guozhangwang** [comment]
> It makes me a bit uneasy just dropping the null records as it might mask bugs in user code

The reason we changed aggregation logic to ignore null keys (it was raising exception as well before) was discussed here: https://github.com/apache/kafka/pull/1472#discussion-diff-66519952

Thinking about it a bit more, I feel the rationale back then was not very thoughtful: if aggregation is following a repartition, then it should not expect any null keys, as otherwise repartitioning would make no sense; but it could also be not following a repartition, in which case it could happen to see null keys. So I agree with you about making the behavior to be "throwing exception" as the default behavior, but currently since we do not have any finer grained exception handler, this would mean that the error will be thrown all the way out of the instance, where users already have limited options but to close the whole instance.

So from an operability perspective, I'd suggest 1) for now we still ignore the record for both join and aggregation, and log a warning when doing so, 2) add the dropping record metrics as a followup; 3) when we add the finer exception handling mechanism, change the "global default" behavior back to throw exception, which could be caught at the operator level and users can then react more efficiently. WDYT?

**Comment by mjsax** [comment]
Sound reasonable to me. I would even allow the user to configure default behavior.

**Comment by mjsax** [comment]
What about `GlobalKTable` -- I believe, it did not exists when the Jira was created.
\cc @dguy 
@guozhangwang I would love to get this into `0.10.2` -- I guess we could have a follow up PR for `GlobalKTable`, too, if you just want to merge it as is.

**Comment by dguy** [comment]
actually @mjsax, `GlobalKTable` might just work. It uses the same `KTableSource` so that behaviour is consistent. Also the KStream-GlobalKTable joins re-use the: `KStreamKTableJoinProcessor` so that behaviour should be consistent also

**Comment by guozhangwang** [comment]
@jeyhunkarimov Could you make a pass on the `join` and `aggregation` APIs of KTable and KStream and make sure they are updated? After that we can merge this PR.

**Comment by miguno** [comment]
Btw, thanks a lot @jeyhunkarimov for contributing this PR! 👍

**Comment by mjsax** [comment]
@dguy Thanks for clarification! Great that we can reuse code, so we do not need to worry about consistency.

@jeyhunkarimov Please also have a look at `KStream#table()`, `KStream#stream()` and `KStream#globalTable`, as well as `GlobalKTable`. You need to rebase first (we updated many JavaDocs recently)

**Comment by jeyhunkarimov** [comment]
@mjsax @guozhangwang it seems the APIs are already updated, so I reverted my changes.

**Comment by guozhangwang** [comment]
@jeyhunkarimov What I meant for javadocs updates is to include this semantic in it as well. For example, in `KStream.join` we had the following comments:

```
* If an {@link KStream} input record key or value is {@code null} the record will not be included in the join
* operation and thus no output record will be added to the resulting {@link KStream}.
```

But we do not similar explanations in `KTable.join` operator.

Maybe we can do it in a follow-up pass after it is merged, cc @mjsax .

**Comment by jeyhunkarimov** [comment]
I updated the APIs.

**Comment by mjsax** [comment]
JavaDoc updates are not correct. But I can do a follow up PR to fix it.

**Comment by guozhangwang** [comment]
Merged to trunk and 0.10.2.

**Pull request closed without merging**
