### PR TITLE
KAFKA-8410: Revert Part 1: processor context bounds (#8414)

### PR DESCRIPTION
**Pull request by vvcephei**
This reverts commit 29e08fd2c2d3349ba5cbd8fe5a9d35a0cea02b85.
There turned out to be more than expected problems with adding the parameter list.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Hey @mjsax @cadonna @apurvam ,

Due to https://github.com/confluentinc/kafka-streams-examples/pull/330, it seems wise just to pull this change while we consider alternatives, WDYT?

**Comment by vvcephei** [comment]
Oh, also note that I used `git revert` on the original commit and then searched the codebase for the strings `ProcessorContext<` and `ProcessorContext[` to find any other usages of the parameter list in Java or in Scala.

**Comment by vvcephei** [comment]
11:
* org.apache.kafka.streams.integration.GlobalKTableIntegrationTest.shouldKStreamGlobalKTableLeftJoin

14:
* org.apache.kafka.streams.integration.StandbyTaskEOSIntegrationTest.surviveWithOneTaskAsStandby[exactly_once]

8:
* kafka.integration.MetricsDuringTopicCreationDeletionTest.testMetricsDuringTopicCreateDelete
* kafka.integration.MetricsDuringTopicCreationDeletionTest.testMetricsDuringTopicCreateDelete
* org.apache.kafka.streams.integration.QueryableStateIntegrationTest.shouldAllowConcurrentAccesses

I don't think any of those are related, and each build had different failures.

Nevertheless,
restest this please

**Comment by apurvam** [comment]
I'd favor a quick revert.

**Comment by vvcephei** [comment]
The only failing test this time was org.apache.kafka.streams.integration.GlobalKTableIntegrationTest.shouldKStreamGlobalKTableLeftJoin, which is already under investigation.

**Review by mjsax — APPROVED** [review]
Thanks. Feel free to merge if you feel confident about Jenkins.

**Comment by vvcephei** [comment]
Thanks, @mjsax !

**Pull request merged**
