### PR TITLE
Menu order in Streams docs incorrect

### PR DESCRIPTION
**Pull request by joel-hamill**
https://issues.apache.org/jira/browse/KAFKA-6419

Related: https://github.com/apache/kafka-site/pull/115

### CODE REVIEW

**Comment by joel-hamill** [comment]
ping @guozhangwang

**Comment by guozhangwang** [comment]
@joel-hamill I think we should change the other way around: instead of changing the next / previous arrows, we should change the menu order itself to

```
Introduction -> Run Demo App -> Tutorial -> Developer Guide -> Concepts
```

Also I noticed two minor issues: 1) the last sub-section of `Developer Guide`, `https://kafka.apache.org/10/documentation/streams/developer-guide/app-reset-tool.html`, its next link is pointing back to `Developer Guide` again, but it should be pointing to `Concepts`.

2) the `Architecture` and `Upgrade Guide` after `Concepts` are not shown in this sub-nav bar, we should add them into the bar as well. cc @derrickdoo

**Comment by joel-hamill** [comment]
@guozhangwang re https://github.com/apache/kafka/pull/4390#issuecomment-355851092:
@joel-hamill I think we should change the other way around: instead of changing the next / previous arrows, we should change the menu order itself to

Introduction -> Run Demo App -> Tutorial -> Developer Guide -> Concepts
>> I don't think it makes sense to have Concepts as the final topic in the series. As a reader, you'd probably want to know about Concepts up front, way before developer guide or tutorials. how about:
`Introduction -> Concepts -> Run Demo App -> Tutorial -> Developer Guide` cc @miguno 

Also I noticed two minor issues: 1) the last sub-section of Developer Guide, https://kafka.apache.org/10/documentation/streams/developer-guide/app-reset-tool.html, its next link is pointing back to Developer Guide again, but it should be pointing to Concepts.
>> Fixed

the Architecture and Upgrade Guide after Concepts are not shown in this sub-nav bar, we should add them into the bar as well. cc @derrickdoo
>> I think this is a known issue.

**Comment by joel-hamill** [comment]
@guozhangwang i have added navigation to upgrade and architecture, rearranged headers, and fix previous/next links: https://github.com/apache/kafka/pull/4390/commits/fb0fd272241b7933dab105d3fe6d55d84efa0255

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
> I don't think it makes sense to have Concepts as the final topic in the series. As a reader, you'd probably want to know about Concepts up front, way before developer guide or tutorials. how about:
> Introduction -> Concepts -> Run Demo App -> Tutorial -> Developer Guide cc @miguno

I personally think we can put Architecture after Tutorial, but I am also fine with this ordering.

Left a minor comment on the dependency versions, otherwise lgtm.

**Comment by guozhangwang** [comment]
LGTM! Merged to trunk.

**Pull request closed without merging**
