### PR TITLE
KAFKA-6274: Use topic plus dash as prefix of auto-generated state store names

### PR DESCRIPTION
**Pull request by guozhangwang**
Use `topic-` as the prefix of the auto-generated state store name.

Also add a unit test for this functionality. 

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by tedyu** [comment]
lgtm

**Review by mjsax — APPROVED** [review]
LGTM

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
Merged to trunk and 1.0

**Pull request closed without merging**
