### PR TITLE
KAFKA-3729: Revert adding Serde auto-config

### PR DESCRIPTION
**Pull request by mjsax**
Merged PRs were not backward compatible. Need to revert for 2.3 release. Ticket reopened with more details.

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @tedyu @ijuma @guozhangwang

**Comment by tedyu** [comment]
+1

**Comment by mjsax** [comment]
Call for review @ijuma @guozhangwang

**Review by guozhangwang — APPROVED** [review]
Thanks @mjsax

**Pull request merged**
