### PR TITLE
MINOR: Add deleteDir for streams quickstart test

### PR DESCRIPTION
**Pull request by mumrah**
Add a `deleteDir` directive to the temporary dir we create during the streams/quickstart archetype test in the Jenkinsfile

### CODE REVIEW

**Comment by cadonna** [comment]
@mumrah, error message

```
[2020-09-24T01:46:33.204Z] Cleaning up test-streams-archetype
No such property: deleteDir for class: groovy.lang.Binding
```
in build 

https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-9328/2/pipeline/8

seems related.

**Comment by chia7712** [comment]
Maybe we should clean the folder before testing archetype? I just worry the clean is not executed if the job is aborted.

**Comment by mjsax** [comment]
@mumrah -- do you still want to get this done? Or should we close this PR?

**Comment by mjsax** [comment]
Closing as stale.

**Pull request closed without merging**
