### PR TITLE
KAFKA-7192: Wipe out state store if EOS is turned on and checkpoint file does not exist

### PR DESCRIPTION
**Pull request by mjsax**
Follow up PR to #5657. Fixes buggy back port.

### CODE REVIEW

**Comment by mjsax** [comment]
Call for reviews @guozhangwang @bbejeck @vvcephei 

Triggered system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2077/

**Comment by mjsax** [comment]
Build not compatible with Java10 or Java7...

System test passed. Retriggered as: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2079/

**Comment by mjsax** [comment]
System test passed. Re-triggered as https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2081/

**Review by bbejeck — APPROVED** [review]
Thanks for the fix @mjsax LGTM

**Pull request merged**
