### PR TITLE
KAFKA-9455; Consider using TreeMap for in-memory stores of Streams

### PR DESCRIPTION
**Pull request by highluck**
https://issues.apache.org/jira/browse/KAFKA-9455

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by highluck** [comment]
@guozhangwang 

Please tell me if I misunderstand
thank you ! :)

**Comment by vvcephei** [comment]
test this please

**Comment by highluck** [comment]
@vvcephei 
May I ask for a review?
Thank you!

**Comment by guozhangwang** [comment]
The code change looks okay to me. I'm wondering if we should let this branch to be tested under our current benchmarks before merging, or we can just merge it and then see its effectiveness in the benchmarks? WDYT @vvcephei @mjsax

**Comment by vvcephei** [comment]
Just managed to dig deep enough into my review backlog to encounter this PR. Sorry, all, for the delay.

It sounds like this whole idea is a performance improvement, so it seems dubious to consider merging it without any benchmarks at all. Personally, I'd like to see a JMH benchmark for this kind of thing before we bother with the fullly integrated benchmark suite.

Another concern is the thread safety angle. After some brief reading on TreeMap vs ConcurrentSkipListMap, it seems like TreeMap isn't completely unsafe. If you have a single writer and multiple readers, TreeMap should be mostly ok, except that it can throw a ConcurrentModificationException if the map is modified by the writer while readers are iterating over it. To what extent are we willing to tolerate ConcurrentModificationExceptions in IQ?

I'm also a little unclear on whether we need a memory barrier or not. It seems like this ticket is more about researching the issues and benchmarking than just mechanically swapping one implementation for the other.

**Pull request closed without merging**
