### PR TITLE
check for null timestamp rather than value in hashcode

### PR DESCRIPTION
**Pull request by andrewstevenson**

### CODE REVIEW

**Comment by andrewstevenson** [comment]
The contribution is my original work and that you license the work to the project under the project's open source license.

**Comment by shikhar** [comment]
LGTM. Thanks for the fix @andrewstevenson 

cc @ewencp

**Comment by ewencp** [comment]
LGTM, the failure is an unrelated streams transient failure. Connect tests are passing fine. Thanks @andrewstevenson!

**Comment by ewencp** [comment]
Oops, missed that this was supposed to be attached to a JIRA https://issues.apache.org/jira/browse/KAFKA-4334

**Comment by andrewstevenson** [comment]
No problem. Our unit tests caught it over the weekend.

**Pull request closed without merging**
