### PR TITLE
KAFKA-5483: Shutdown of scheduler should come after LogManager

### PR DESCRIPTION
**Pull request by mimaison**
Close the scheduler after all components using it have been shutdown

@hachikuji Can you have a look ?

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. I think the fix is a little more involved. I haven't checked all the cases, but one example in `ReplicaManager`:

```scala
def startup() {
    // start ISR expiration thread
    // A follower can lag behind leader for up to config.replicaLagTimeMaxMs x 1.5 before it is removed from ISR
    scheduler.schedule("isr-expiration", maybeShrinkIsr _, period = config.replicaLagTimeMaxMs / 2, unit = TimeUnit.MILLISECONDS)
    scheduler.schedule("isr-change-propagation", maybePropagateIsrChanges _, period = 2500L, unit = TimeUnit.MILLISECONDS)
  }
```

We would want to stop these tasks in `ReplicaManager.shutdown` (which we don't seem to do) if we want to avoid an exception from being thrown after the scheduler is shutdown. We should look for other cases where there are tasks that are executed periodically.

**Comment by ijuma** [comment]
Having a second look, it seems like we are using `scheduleAtFixedRate`, so the above case may be OK. We should verify that all are OK though.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5765/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5751/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by hachikuji** [comment]
@mimaison Thanks for the patch. As Ismael said, this does seem a little trickier than reordering the scheduler shutdown. For example, it seems problematic for the shutdown logic in `LogManager` to have to contend with any of the background scheduled tasks. A few alternatives come to mind:

1. Maybe the scheduler needs to add support for removing a scheduled task? Then we can remove the tasks manually before proceeding with shutdown logic.
2. The exceptional case from the JIRA shows that the event which caused the unexpected call to `schedule` was a response from a replica fetch request. Maybe there is a way to add a check somewhere in that path to see if the broker is shutting down.
3. Maybe instead of raising an exception when we receive a call to `schedule`, we should just log a warning?

There might be other options as well.

**Comment by mimaison** [comment]
Thanks for the feedback !
I got dragged into other tasks but I'll have another look

**Pull request closed without merging**
