### PR TITLE
KAFKA-8545: Remove legacy ZkUtils

### PR DESCRIPTION
**Pull request by ijuma**
ZkUtils is not used by the broker, has been deprecated since
2.0.0 and it was never intended as a public API. We should
remove it along with `AdminUtils` methods that rely on it.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
@junrao any concerns?

**Review by mumrah — APPROVED** [review]
LGTM. I still see a couple of comment references to ZkUtils (like in KafkaZkClient).

**Comment by ijuma** [comment]
@mumrah I pushed an additional commit that removes references to `ZkUtils`.

**Comment by ijuma** [comment]
Build is green, merging to master.

**Pull request merged**
