### PR TITLE
Revert "KAFKA-9705 part 1: add KIP-590 request header fields (#9144)"

### PR DESCRIPTION
**Pull request by abbccdda**
This reverts commit 21dc5231ce9c7398c7ede4dbefa2f2202e06b2d4. As we no longer use initial principals, it makes sense to revert on trunk and 2.7 as well.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by abbccdda** [comment]
retest this please

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by abbccdda** [comment]
retest this please

**Comment by abbccdda** [comment]
test this

**Comment by abbccdda** [comment]
retest this

**Pull request merged**
