### PR TITLE
Update KafkaLog4jAppender.java adding SaslMechanism as an option

### PR DESCRIPTION
**Pull request by jemaiah**
to be able to use kafka with Sasl/Plain  we need to ba able to set saslMechanism from kafka log4j options

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5853/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5868/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5869/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5854/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by mimaison** [comment]
Considering the age of this PR and that KIP-719 to deprecate the log4j appender has been voted, I'll close this PR.

**Pull request closed without merging**
