### PR TITLE
KAFKA-3191: Improve offset committing JavaDoc in KafkaConsumer

### PR DESCRIPTION
**Pull request by kunickiaj**
Added an example clarifying the correct way to use explicit offsets with commitSync().

### CODE REVIEW

**Comment by hachikuji** [comment]
@kunickiaj The example looks reasonable (indeed it seems to be the same one from my blog). It might also be worth adding a comment on the commit methods themselves.

**Comment by kunickiaj** [comment]
Happy add the following to the commitSync(Map) method:

> To avoid re-processing the last message read if a consumer is restarted, the committed offset should be the next message your application should consume, i.e. lastProcessedMessageOffset + 1.

If you think other methods should have a note, which, and what information should be added?

**Comment by hachikuji** [comment]
Yeah, that works. Probably the same comment should be added to commitAsync(Map,OffsetCommitCallback).

**Comment by kunickiaj** [comment]
Updated.

**Comment by hachikuji** [comment]
LGTM

**Comment by ewencp** [comment]
LGTM. Double committing to 0.9.0 and trunk since this is a simple doc change and will be helpful to those using 0.9.0.1 too.

**Pull request closed without merging**
