### PR TITLE
MINOR: Update consumer javadocs

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by omkreddy** [comment]
@hachikuji updated the javadocs based on current behavior.

currently, seek, seekToBeginning, seekToEnd, pause and resume methods throws IllegalStateException if we pass unassigned partitions as input  and position() throws IllegalArgumentException. 

may be we should throw IllegalArgumentException in all methods. not sure if it is worth to change.

**Comment by omkreddy** [comment]
@hachikuji Please take a look at this minor PR.

**Comment by hachikuji** [comment]
@omkreddy Thanks for the patch. It looks like we're a little inconsistent at the moment. We raise `IllegalArgumentException` from `position()`. Do you think we should change that to be `IllegalStateException` as well?

**Comment by omkreddy** [comment]
@omkreddy  yes,  to make it consistent with other methods we can throw IllegalStateException. Updated the PR. Please take a look.

**Comment by omkreddy** [comment]
test failure is not related to this PR.

**Review by hachikuji — APPROVED** [review]
LGTM, thanks for the patch!

**Pull request merged**
