### PR TITLE
Kafka 13888 new fields

### PR DESCRIPTION
**Pull request by lqjack**
* create file if not exist
update lastCaughtUpTimestamp
update lastFetchTimestamp
*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by hachikuji** [comment]
@lqjack Can you merge with trunk please?

**Comment by niket-goel** [comment]
Hey @lqjack . Thanks for raising this PR. The PR https://github.com/apache/kafka/pull/12206 has now been merged to trunk. Can you please update your PR with the latest code so we can iterate on it?

**Comment by ijuma** [comment]
@lqjack Are you still planning to work on this? If we don't hear from you in the next couple of days, then someone else may pick it up and drive it forward.

**Comment by niket-goel** [comment]
The following PR https://github.com/apache/kafka/pull/12508 implements this functionality. This PR can be closed.

**Comment by jsancio** [comment]
@lqjack I am closing the PR. It looks like this issue was fixed by https://github.com/apache/kafka/pull/12206 and https://github.com/apache/kafka/pull/12508

**Pull request closed without merging**
