### PR TITLE
Fixes #8198 KStreams testing docs use non-existent method pipe

### PR DESCRIPTION
**Pull request by ouertani**
*More detailed description of your change,
Minor fix of #8198 https://github.com/apache/kafka-site/pull/210

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [X ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by vvcephei — APPROVED** [review]
Thanks!

**Comment by dongjinleekr** [comment]
LGTM. Is there anyone who can merge this PR?

cc/ @hachikuji @bbejeck

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
Merged #6678 into trunk

**Comment by bbejeck** [comment]
Thanks for the contribution @ouertani!

**Comment by bbejeck** [comment]
cherry-picked to 2.3, 2.2, 2.1, 2.0 and 1.1

**Comment by dongjinleekr** [comment]
Congrats, @ouertani! :)

**Pull request merged**
