### PR TITLE
KAFKA-13792: Fix wrong package name in Scala test files

### PR DESCRIPTION
**Pull request by yeoncheol-jang**
- Fix wrong package name in `QuorumImplementation` and `UncleanLeaderElectionTest` files.
- import classes

[Related Jira ticket](https://issues.apache.org/jira/browse/KAFKA-13792)

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by yeoncheol-jang** [comment]
@omkreddy Hello. I am not sure tagging you here but if you are available, please review this.

**Comment by dengziming** [comment]
In fact, we set package name to `kafka.integration` intentionally, they are just put into the directories. In scala, package name can be different from there directories.

**Comment by yeoncheol-jang** [comment]
@dengziming Thank you for the review!

Maybe this is silly question and just wondering that putting into different directories intentionally, what’s the advantage?

For me, using clear names are looking more natural.

**Comment by dengziming** [comment]
> what’s the advantage

set to this because we have integration test and unit test, you can find that we have 2 subdirs in the `test` dir.

**Comment by yeoncheol-jang** [comment]
> > what’s the advantage
> 
> set to this because we have integration test and unit test, you can find that we have 2 subdirs in the `test` dir.

Thanks for letting me know:)

**Pull request closed without merging**
