### PR TITLE
MINOR: Verify mocks in all WorkerTest tests and don't unnecessarily mockStatic the Plugins class.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@kkonstantine @rhauch @ijuma Not sure if this will address KAFKA-5141, but in the process of taking a quick look at it I noticed some brokenness in this test. First, I found that `verifyAll()` was not being called in a few tests. Not strictly wrong, but we were missing some intended checks.

After adding those, I noticed that some mocks were actually being created *after* `replayAll()`, which is incorrect. Fixed those up, a few other missing pieces that fell out of those changes (mainly missing expectations).

I also had to remove some expectations because of mocking of the classloader modifications -- we were marking some calls as expected, but since the classloaders aren't really swapped out, we shouldn't expect them. And in fact we were missing a few as well. I'm not sure if it is better to do things this way (where I've now noted what we would expect but don't see) or to just swap out the classloader. In practice a new MockClassLoader is put in place for every test anyway, so it's relatively safe (and I have verified that just removing mockStatic on the `Plugins` class works fine).

There's also a bit of reorganization in some methods to make the order of operations on the mocks a bit clearer.

This should go on both trunk and 0.11.0.

**Review by kkonstantine — APPROVED** [review]
@ewencp thanks for the fixes. The cleanup makes sense. 

I noticed actual expectations being removed only in one place and that seems justified. I'm curious to see whether the missing verifies will resolve flakiness in this test as well.

**Review by rhauch — APPROVED** [review]
These changes seem to make sense to me.

**Comment by ewencp** [comment]
@ijuma @hachikuji If either of you could do a quick review and commit, hopefully this will also improve test stability.

**Review by ijuma — APPROVED** [review]
Thanks, LGTM. I think it would be good to replace the commented out assertions with real ones, but that can be done subsequently as this PR improves the stability of the build now.

**Pull request closed without merging**
