### PR TITLE
KAFKA-2588 ReplicaManager partitionCount metric should actually be re…

### PR DESCRIPTION
**Pull request by granthenke**
…plicaCount

### CODE REVIEW

**Comment by guozhangwang** [comment]
test this.

**Comment by guozhangwang** [comment]
@granthenke Could you update the documentation as well?

**Comment by hachikuji** [comment]
Thanks for the patch. I'm going to close this for now since it requires a KIP, but please consider reopening if you (or anyone else) has time to submit a proposal. (The change does seem reasonable to me for what it's worth.)

**Comment by b-goyal** [comment]
…plicaCount

**Comment by b-goyal** [comment]
…plicaCount

**Comment by b-goyal** [comment]
…plicaCount

**Comment by b-goyal** [comment]
…plicaCount

**Comment by b-goyal** [comment]
…plicaCount

**Comment by b-goyal** [comment]
…plicaCount

**Pull request closed without merging**
