### PR TITLE
MINOR: remove unnecessary if check

### PR DESCRIPTION
**Pull request by khaireddine120**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by eneveu** [comment]
Removing that unnecessary `if` check is nice, but the commit history in your PR is kind of weird. You have 10 commits for a one-line change. I think you could rewrite it and rebase on top of "trunk" to have a single simple commit.

A few links on how to do that:
- https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
- https://github.com/mockito/mockito/wiki/Using-git-to-prepare-your-PR-to-have-a-clean-history

You will probably need to do a force push after this, to update the PR with your single commit.

**Comment by khaireddine120** [comment]
thanks @eneveu, i'll recheck this

**Comment by khaireddine120** [comment]
Hi  @eneveu, i used this command `git commit --amend --no-edit`
but i don't know if it fix the issue

**Comment by eneveu** [comment]
I think `git commit --amend --no-edit` won't help much here.

You want to do an interactive rebase, to combine all of your commits into one simple commit on top of trunk.

**Pull request closed without merging**
