### PR TITLE
HOTFIX: Move Conusmed to o.a.k.streams.kstream

### PR DESCRIPTION
**Pull request by guozhangwang**
`Consumed` was mis-placed. I've moved it to `kstream` and added one statement in the upgrade guide.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@mjsax @bbejeck @vvcephei

**Review by mjsax — APPROVED** [review]
LGTM.

Should we backport this? Not sure...

**Comment by guozhangwang** [comment]
I think we cannot... since otherwise the upgrade from 1.1.0 to 1.1.1 will require code changes.

**Review by bbejeck — APPROVED** [review]
Thanks, @guozhangwang  LGMT

**Pull request merged**
