### PR TITLE
MINOR: Fixes for streams system tests

### PR DESCRIPTION
**Pull request by bbejeck**
This PR fixes some regressions introduced into streams system tests and sets the upgrade tests to ignore until PR #4636 is merged as it has the fixes for the upgrade tests.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
system test kicked off and passed https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1723/

**Comment by bbejeck** [comment]
@dguy @guozhangwang @mjsax @vvcephei

**Comment by bbejeck** [comment]
failed for exceeded rate limit for repository

retest this please

**Comment by guozhangwang** [comment]
Thanks @bbejeck ! LGTM.

**Pull request merged**
