### PR TITLE
MINOR:  exchange redundant Collections.addAll with parameterized constructor

### PR DESCRIPTION
**Pull request by wlsc**
This issue is a rework to the outdated ticket created earlier (https://github.com/apache/kafka/pull/2707). This issue was created because original branch was already removed.

Basic static analysis. What was accomplished:
- exchanged redundant Collections.addAll with parameterized constructor
- exchange manual copy to collection with Collections.addAll call

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/306/

**Review by guozhangwang — APPROVED** [review]

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/351/

**Comment by wlsc** [comment]
retest this please

**Comment by guozhangwang** [comment]
Thanks @wlsc ! Merged to trunk.

**Pull request merged**
