### PR TITLE
MINOR: Change deprecated 'scala.collection.JavaConverters' to 'scala.jdk.CollectionConverters'

### PR DESCRIPTION
**Pull request by dongjinleekr**
... with fixing typo, removing redundant method parameters, unused Throwables, and unused test methods.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by chia7712** [comment]
@dongjinleekr Thanks for your effort. nit: It would be better to avoid changing unrelated code in order to make this patch small but tough :)

**Comment by dongjinleekr** [comment]
@chia7712 Great. I will separate the other commits into independent PR to make the commit clear. Stay tuned! :smile:

**Comment by dongjinleekr** [comment]
Hi @chia7712,

I separated the other commits into this PR: https://github.com/apache/kafka/pull/9457

+1. Congratulations on becoming a committer. :smile:

**Comment by ijuma** [comment]
I don't think this PR will work with Scala 2.12. See https://github.com/scala/scala-collection-compat/issues/346

**Comment by dongjinleekr** [comment]
Closing for it won't work with Scala 2.12.

**Pull request closed without merging**
