### PR TITLE
KAFKA-9587: Producer configs are omitted in the documentation

### PR DESCRIPTION
**Pull request by dongjinleekr**
I found this glitch while working on another issue.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by kkonstantine** [comment]
Not sure why you think this is a glitch in the doc. These two properties are optional (have defaults) and the suggested settings in the example don't seem to be particularly more appropriate than the default values. I'm not suggesting that users won't find it useful to often change these values. But the purpose of this brief example in the javadoc is not in my opinion to list all the common options, but to provide a minimal example. 

I suggest closing this PR without merging. Wdyt @dongjinleekr ?

**Review by kkonstantine — COMMENTED** [review]
I accidentally deleted my previous comment, so I'm adding it here again. 

I'm not sure this is a doc bug. The properties mentioned are optional (they have reasonable defaults). I agree that several users might choose to set those properties to a different value. But it seems that if we list values in this doc other than the default ones we might suggest that the examples are more common or appropriate. 

Since this example is not meant to list explicitly every available property, I feel we could still keep these two configs out of the example. Wdyt @dongjinleekr ?

**Comment by dongjinleekr** [comment]
Hi @kkonstantine, thanks for reviewing the PR. First, Congratulations on becoming a committer. 😃

I reviewed this issue a little bit more. As I described in the Jira issue, `retries` was removed from documentation in c3e7c0b (2.1.0) and `linger.ms` also did in 975b680 (2.2.0).

I agree that those two properties are optional with default values, so listing those values in documentation may confuse. However, the current documentation is also confusing, especially for the beginners - It doesn't mention that why `retries` set to 0 and `linger.ms` to 1 millisecond.

How about this? **Instead of restoring those two properties, adding statements on why they are set as the documentation (i.e., default value).** By doing so, we can avoid both confusion.

How do you think?

**Comment by kkonstantine** [comment]
Hi @dongjinleekr and thank you! 😊

The links that you mention are quite indicative I think! (especially https://github.com/apache/kafka/commit/975b680bcd74661eeecf21052f6185cd637bbeda has a message to explain why these examples were removed)

Then, if someone reads the actual docs will find, as you point out, good explanations of the current defaults. For example:  
1. For `retries`: _The default value for the producer's retries config was changed to Integer.MAX_VALUE, as we introduced delivery.timeout.ms in KIP-91, which sets an upper bound on the total time between sending a record and receiving acknowledgement from the broker. By default, the delivery timeout is set to 2 minutes._
2. For `linger.ms`: _This setting defaults to 0 (i.e. no delay). Setting linger.ms=5, for example, would have the effect of reducing the number of requests sent but would add up to 5ms of latency to records sent in the absence of load._

I think the javadoc will be easier to maintain if it keeps the examples simple and not very specific. wdyt?

**Comment by dongjinleekr** [comment]
@kkonstantine

> I think the javadoc will be easier to maintain if it keeps the examples simple and not very specific.

Yes, I totally agree. But the fact I would like to point out is that, **the beginners who mainly read this documentation don't know how `retries` and `linger.ms` are decided, nor it doesn't explicitly mention it.**

What I am proposing now is fixing the explanation like the following, not the code snippet:

Before:
> If the request fails, the producer can automatically retry, though since we have specified retries as 0 it won't.

After:
> If the request fails, the producer can automatically retry. Though in the example above, since we have not specified `retries` it falls back to its default value, 0, so it won't.

Before:
> ... in the code snippet above, likely all 100 records would be sent in a single request since we set our linger time to 1 millisecond.

After:
> ... in the code snippet above, likely all 100 records would be sent in a single request since we did not set `linger.ms`, our linger time fallbacks to its default value, 1 millisecond.

Does it make sense? (Yes, It is a modified approach from my initial PR. :smile:)

**Comment by kkonstantine** [comment]
@dongjinleekr it was hard for me to understand to which changes you were referring to without an updated commit. 

Please submit an update to this PR so that we can review the actual changes that are proposed. 
A thing to keep in mind is that current defaults are: 
linger.ms: 0
retries: Integer.MAX_VALUE

Based on that, I agree that the current javadoc in the `KafkaProducer` class is stale at the points you mention, but also your suggestions above need to be modified.

**Comment by dongjinleekr** [comment]
Rebased onto the latest trunk and I reviewed the problem more carefully and here is the summary:

1. As @kkonstantine stated, [the default value of `retries` config is `Integer.MAX_VALUE`](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/ProducerConfig.java#L289); however, the documentation still states that **'though since we have specified <code>retries</code> as 0 it won't.'** It seems like `props.put("retries", 0);` was removed mistakenly from example code snippet in commit c3e7c0b (2.1.0).

2. The default value of `linger.ms` config is 0; however, the current documentation states that **we set our linger time to 1 millisecond**. `props.put("linger.ms", 1);` was removed from example code snippet in commit 975b680 (2.2.0), for the example code of that times violates `delivery.timeout.ms` (30000) >= `linger.ms` (1) + `request.timeout.ms` (30000 by default). However, it should not have be removed since removing `delivery.timeout.ms` only was enough - `delivery.timeout.ms` defaults to 120000. In conclusion, it seems like `props.put("linger.ms", 1);` was also removed mistakenly.

cc for the reviewers of commit c3e7c0b and 975b680. @ijuma @guozhangwang @hachikuji

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by dongjinleekr** [comment]
Rebased onto the latest trunk.

@bbejeck Could you kindly include this PR into the 2.7.0 plan?

**Comment by dongjinleekr** [comment]
Rebased onto the latest trunk. cc/ @kkonstantine @bbejeck

**Review by kkonstantine — APPROVED** [review]
LGTM
Thanks @dongjinleekr

**Comment by kkonstantine** [comment]
Merged to trunk and `2.7` given that this can be considered a doc bugfix.

**Pull request merged**
