### PR TITLE
KAFKA-10599: Implement basic CLI tool for feature versioning system

### PR DESCRIPTION
**Pull request by kowshik**
[KIP-584]: Cherry pick PR #9409 implementing a basic CLI tool for feature versioning system, into AK 2.7 release branch.

### CODE REVIEW

**Comment by kowshik** [comment]
cc @abbccdda @junrao: This cherry-pick PR is ready for review.

**Comment by abbccdda** [comment]
retest this please

**Comment by kowshik** [comment]
@abbccdda I'm not sure whats going on, there is a maven error in the CI run. Would you be able to please trigger a retest ?

**Comment by junrao** [comment]
This is probably due to https://github.com/apache/kafka/pull/9453. Just merged that PR to 2.7.

**Comment by junrao** [comment]
retest this please

**Comment by junrao** [comment]
test this please

**Comment by junrao** [comment]
ok to test

**Comment by junrao** [comment]
@kowshik : Maybe you can rebase this PR to trigger another test.

**Comment by kowshik** [comment]
@junrao Good idea. I've done a rebase now on top of latest `2.7` branch.

**Review by junrao — APPROVED** [review]
@kowshik : Thanks for the PR. LGTM

**Pull request merged**
