### PR TITLE
KAFKA-13152: Add cache size metrics

### PR DESCRIPTION
**Pull request by vamossagar12**
Adds the new DEBUG metric `cache-size-bytes-total`

### CODE REVIEW

**Review by ableegoldman — APPROVED** [review]
LGTM -- now that it's DEBUG I'm not too concerned with the potential for perf issues, so we can get this into 3.4 🙂

**Comment by ableegoldman** [comment]
@vamossagar12 let me know when all the tests finish running and I'll merge this

**Comment by vamossagar12** [comment]
> @vamossagar12 let me know when all the tests finish running and I'll merge this

Thanks @ableegoldman . Oh weirdthe JDK 11/17 finished over friday itself. The other ones are still running.

**Comment by ableegoldman** [comment]
Yeah that's weird...it might be stuck, triggered a new build, hopefully this one doesn't take days to finish 😄

**Comment by vamossagar12** [comment]
@ableegoldman , looks like the tests ran this time. Error seem unrelated to this change.

**Comment by ableegoldman** [comment]
Merged to trunk -- we'll have everything but the new input buffer config from this KIP done in 3.4 it looks like 🙂

**Pull request merged**
