### PR TITLE
KAFKA-12679: Handle lock exceptions in state updater 

### PR DESCRIPTION
**Pull request by lucasbru**
In this change, we enable backing off when the state directory
is still locked during initialization of a task. When the state
directory is locked, the task is reinserted into the
initialization queue. We will reattempt to acquire the lock
after the next round of polling.

Tested through a new unit test.

NOTE: This is a stacked PR on previous PRs. 
Please only review the latest commit.

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lucasbru** [comment]
@cadonna Could you have a look?

**Comment by lucasbru** [comment]
Let's not merge this yet.

**Comment by lucasbru** [comment]
Okay, I revised the change and it is ready for review.

**Comment by cadonna** [comment]
@lucasbru Could you please resolve the merge conflicts that I introduced by merging your PR #12904?

**Comment by cadonna** [comment]
Build failures are not related:
```
Build / JDK 17 and Scala 2.13 / kafka.network.SocketServerTest.processNewResponseException()
Build / JDK 17 and Scala 2.13 / org.apache.kafka.streams.integration.SmokeTestDriverIntegrationTest.[1] true
Build / JDK 11 and Scala 2.13 / org.apache.kafka.common.record.MemoryRecordsBuilderTest.[5] magic=1, bufferOffset=0, compressionType=gzip
Build / JDK 11 and Scala 2.13 / org.apache.kafka.common.record.MemoryRecordsBuilderTest.[7] magic=0, bufferOffset=0, compressionType=snappy
Build / JDK 11 and Scala 2.13 / org.apache.kafka.common.record.MemoryRecordsBuilderTest.[8] magic=1, bufferOffset=0, compressionType=snappy
Build / JDK 11 and Scala 2.13 / org.apache.kafka.common.record.MemoryRecordsBuilderTest.[10] magic=0, bufferOffset=0, compressionType=lz4
Build / JDK 11 and Scala 2.13 / org.apache.kafka.common.record.MemoryRecordsBuilderTest.[19] magic=2, bufferOffset=15, compressionType=gzip
Build / JDK 11 and Scala 2.13 / org.apache.kafka.common.record.MemoryRecordsBuilderTest.[23] magic=0, bufferOffset=15, compressionType=lz4
Build / JDK 11 and Scala 2.13 / kafka.server.MultipleListenersWithAdditionalJaasContextTest.testProduceConsume()
```

**Comment by andrashatvani** [comment]
@lucasbru @cadonna in which version will this be integrated?

**Comment by cadonna** [comment]
@andrashatvani Do you mean the state updater?
I am currently working on enabling the state updater by default on trunk. We plan to officially release it in 3.6.
However, you can already test it in 3.4 and 3.5 by setting the internal config `__state.updater.enabled__` to true. Note that we recently found and [fixed a bug](https://github.com/apache/kafka/pull/13829) in the state updater. The fix is only on trunk.

**Comment by andrashatvani** [comment]
@cadonna I got here from https://issues.apache.org/jira/browse/KAFKA-12679 which often causes `Failed to lock the state directory for task` errors and thus service outages, this is the fix I'm hoping for and looking forward to.
I could work it around by reducing `num.stream.threads` to `1`, but that's a bold restriction and shouldn't be necessary.

**Comment by cadonna** [comment]
This PR solves the issue for the state updater not for the current initialisation logic without the state updater.

**Comment by burpeenerd** [comment]
> @andrashatvani Do you mean the state updater? I am currently working on enabling the state updater by default on trunk. We plan to officially release it in 3.6. However, you can already test it in 3.4 and 3.5 by setting the internal config `__state.updater.enabled__` to true. Note that we recently found and [fixed a bug](https://github.com/apache/kafka/pull/13829) in the state updater. The fix is only on trunk.

@cadonna Hi, is it still planned to release new state updater als default with upcoming 3.6? (could not find any mentioning on the release planning site).

**Comment by cadonna** [comment]
@marcmesh Unfortunately, we did not manage to enable the state updater by default in 3.6. You can enable it with the internal `__state.updater.enabled__` set to true. However, be aware that we found a couple of bugs recently. You can track the work to enable the state updater by default under https://github.com/apache/kafka/pull/13927.

One [bug fix](https://github.com/apache/kafka/pull/14265) is still open.

**Comment by a-dudko** [comment]
We are using version 3.9.1 now and we see plenty of the logs like
`stream-thread [service-e7c3de52-cf29-49c3-8f9d-1eea119ea532-StreamThread-1] Encountered lock exception. Reattempting locking the state in the next iteration.`
with the following stacktrace
```
org.apache.kafka.streams.errors.LockException: stream-thread [service-e7c3de52-cf29-49c3-8f9d-1eea119ea532-StreamThread-1] task [1_42] Failed to lock the state directory for task 1_42
	at org.apache.kafka.streams.processor.internals.StateManagerUtil.registerStateStores(StateManagerUtil.java:97)
	at org.apache.kafka.streams.processor.internals.StreamTask.initializeIfNeeded(StreamTask.java:266)
	at org.apache.kafka.streams.processor.internals.TaskManager.addTaskToStateUpdater(TaskManager.java:1016)
	at org.apache.kafka.streams.processor.internals.TaskManager.addTasksToStateUpdater(TaskManager.java:1001)
	at org.apache.kafka.streams.processor.internals.TaskManager.checkStateUpdater(TaskManager.java:915)
	at org.apache.kafka.streams.processor.internals.StreamThread.checkStateUpdater(StreamThread.java:1191)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnceWithoutProcessingThreads(StreamThread.java:999)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:713)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:672)
```

which are eventually followed by an ERROR like
`stream-thread [service-e7c3de52-cf29-49c3-8f9d-1eea119ea532-StreamThread-1] standby-task [1_42] Failed to acquire lock while closing the state store for STANDBY task 1_42`

Both were introduced in current PR. Are we missing some other fix or is there smth wrong with the config on our side?

**Comment by cadonna** [comment]
Both should actually be harmless.
The first is just an info because the lock on the state directory of the task could still be taken by a different stream thread on the same Streams client. That might happen if one stream thread wants to initialize the task before another stream thread hasn't closed the same task. The second is written to the log if the lock could not been acquired before the task is moved away from the stream thread. The might happen if two rebalances happen quite fast one after the other. 

Besides the log messages, do you see other weird behavior like lag that does not decrease for those tasks? 

Actually, 3.9.1 already contains the backlog mechanism to acquire the log (https://github.com/apache/kafka/pull/17116 and https://github.com/apache/kafka/pull/17209), so I am wondering why you say you see plenty of the first before you see the second.

**Comment by a-dudko** [comment]
@cadonna actually not all _"Reattempting..."_ info logs are followed by the error meaning it is mostly resolved correctly afterwards, so sorry for the misleading comment. So some part of them is followed by the error. We don't see any issues in the service's behavior, but the presence of error level logs became concerning for us

**Comment by cadonna** [comment]
Yeah, I understand. The issue is that not being able to acquire the log when closing a task might be an error in other situations. Downgrading the log message to a WARN or INFO might need some more thinking. \cc @lucasbru @aliehsaeedii @mjsax

**Comment by lucasbru** [comment]
@cadonna could we just check if the state store is even open before attempting to grab the lock to close it?

**Comment by cadonna** [comment]
@lucasbru that sounds like a good idea.

**Comment by a-dudko** [comment]
@lucasbru @cadonna do you have some changes planned related to the issue I described? These error logs keep triggering our alerting system unfortunately

**Comment by lucasbru** [comment]
@a-dudko could you file a JIRA?

**Pull request merged**
