### PR TITLE
KAFKA-3187: Make kafka-acls.sh help messages more generic.

### PR DESCRIPTION
**Pull request by SinghAsDev**

### CODE REVIEW

**Comment by SinghAsDev** [comment]
@gwenshap mind taking a look at this trivial patch.

**Comment by gwenshap** [comment]
I'm afraid it makes our documentation more confusing. I think examples are clearer when they are more specific. If you have other principal types in mind, maybe add another example?

**Comment by SinghAsDev** [comment]
@gwenshap yea, however there is no principal type that has to be there for an authorizer implementation. But, I see your point on specific examples can be helpful. I will change text bit more so that user is used only for example.

**Comment by SinghAsDev** [comment]
@gwenshap added the user examples back and added notes on principalType.

**Comment by gwenshap** [comment]
LGTM

**Comment by gwenshap** [comment]
Thanks for the help improvement :)

**Pull request closed without merging**
