### PR TITLE
KAFKA-4232: make MemoryRecords.writable volatile.

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by becketqin** [comment]
@ijuma Will you be able to review this?

**Comment by ijuma** [comment]
Thanks for the PR. I'm wondering if it's enough to make this field `volatile`. What about `buffer`?

**Comment by ijuma** [comment]
Also, while you're changing the producer, can you remove `Sender.clientId`, which seems unused?

**Comment by ijuma** [comment]
After looking at it a bit more, I think `buffer` should be `volatile` as well.

**Comment by ijuma** [comment]
Also, can we add a comment on both of these variables explaining that they are used by both `sender` and `user` threads while the other variables are only used by the `user` thread?

**Comment by becketqin** [comment]
@ijuma Yes, buffer should be volatile as well. I feel it is a little too much to explain the external usage of the variables. I added comments saying that those variables may be read and written by different threads so we need to make them volatile.

**Comment by ijuma** [comment]
Looking at this even more, it seems like there are other issues.

In the case where we call `close` from the `Sender` thread (which used to be the only behaviour before but now only happens some of the time), we call `compressor.close()`, which invokes `bufferStream.buffer()`. But the buffer returned there is in a non-volatile variable that gets updated when the buffer needs to be expanded while writing data from the user thread. Seems like that `buffer` also needs to be volatile.

Seems like the concurrency strategy for the new producer hasn't really been thought through.

**Comment by ijuma** [comment]
Becket pointed out in the JIRA that we synchronize on the same `deque` before calling `tryAppend` or `close`, so we don't need any of the volatiles in this PR.

**Pull request closed without merging**
