### PR TITLE
MINOR: Do not end Javadoc comments with `**/`

### PR DESCRIPTION
**Pull request by eneveu**
From https://blog.joda.org/2012/11/javadoc-coding-standards.html :

> Use the standard style for Javadoc comments
> Javadoc only requires a `/**` at the start and a `*/` at the end.
> [...]
> Do not use `**/` at the end of the Javadoc.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by eneveu** [comment]
Note: I have more meaningful improvements coming for the Javadocs, but I'm starting with small stylistic changes to get those out of the way first as a baseline.

**Comment by eneveu** [comment]
retest this please

**Comment by mjsax** [comment]
@eneveu -- Thanks for the PR. Seems it's outdated. Would you like to update it so we can merge it?

**Comment by mjsax** [comment]
Closing this stale PR in favor of https://github.com/apache/kafka/pull/14540

**Pull request closed without merging**
