### PR TITLE
KAFKA-6145: Add unit tests for assignments of only stateless tasks

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @ableegoldman @vvcephei

**Review by vvcephei — APPROVED** [review]
Looks great! Thanks for the additional coverage.

**Comment by vvcephei** [comment]
Test this please

**Comment by vvcephei** [comment]
Unrelated test failures:


org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[false] 
org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[true]

**Pull request merged**
