### PR TITLE
KAFKA-7438: Replace Easymock & Powermock with Mockito in RocksDBMetricsRecorderGa…

### PR DESCRIPTION
**Pull request by bachmanity1**
Replace Easymock & Powermock with Mockito in RocksDBMetricsRecorderGaugesTest.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bachmanity1** [comment]
@cadonna @divijvaidya can you please review this? Thanks!

**Review by divijvaidya — APPROVED** [review]
Looks good!

Weird that we are not tracking this test at https://issues.apache.org/jira/browse/KAFKA-14133 or https://issues.apache.org/jira/browse/KAFKA-14132. This takes us one step closer to getting rid of easy mock and powermock dependency.

**Comment by bachmanity1** [comment]
> Weird that we are not tracking this test at https://issues.apache.org/jira/browse/KAFKA-14133 or https://issues.apache.org/jira/browse/KAFKA-14132.

Looking at the state of ticket KAFKA-14133 gives an impression that work on the replacement of Easymock with Mockito is almost over, but based on the latest state of the `trunk` branch it looks like there are still quite many test classes (not listed in the ticket) that use Easymock.

**Comment by clolov** [comment]
This is an interesting find. That list was compiled quite sometime ago, but given this information I will go and recheck again - maybe my search was faulty ¯\\\_(ツ)\_/¯

**Comment by bachmanity1** [comment]
@clolov I've compiled the list of test classes that use Easymock but are not listed in the ticket https://issues.apache.org/jira/browse/KAFKA-14133#:~:text=Hi%20Christo%20Lolov%20%2C%C2%A0,kafka/pull/14142)

**Review by clolov — APPROVED** [review]
Looks great to me, thank you for doing this and bringing to my attention the gap in that ticket! Feel free to join in with moving the rest of those files across should you have the want and spare bandwidth 😊

**Pull request merged**
