### PR TITLE
KAFKA-3371: ClientCompatibilityTest system test failing

### PR DESCRIPTION
**Pull request by enothereska**
@becketqin have a look if this looks reasonable to you. Thanks.

### CODE REVIEW

**Comment by enothereska** [comment]
The string change makes the test pass, but more is needed to actually meet the exact spec of what the test is about. So the PR is WiP and I'll add more changes to it soon.

**Comment by enothereska** [comment]
@ijuma @ewencp @granders could you have a look, thanks. Note this PR is just about fixing the failure a subsequent one will update the tests to include the 0.10 scenario.

**Comment by granders** [comment]
@enothereska 
These changes look good, and tests pass.

However, given that we periodically run equivalent tests in 0.9.0.X branch, it is probably fine just to drop these two tests from trunk altogether.

**Comment by enothereska** [comment]
@granders Ok, removed these two tests from trunk. New compatibility tests are now part of KAFKA-3188. Thanks.

**Comment by granders** [comment]
LGTM

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
