### PR TITLE
HOTFIX: do not call partitioner if num partitions is non-positive

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
And then in `KafkaProducer`, a more informative exception

```
IllegalArgumentException(String.format("Invalid partition given with record: %d is not in the range [0...%d].", partition, lastPartition));
```

will be thrown.

**Comment by guozhangwang** [comment]
@ijuma @hachikuji @dguy @enothereska

**Comment by dguy** [comment]
@guozhangwang - looks like the test failures might be related? Possibly just test setup, but...

**Comment by enothereska** [comment]
3 failures

**Comment by guozhangwang** [comment]
@dguy @enothereska You are right, I will fix them.

**Comment by guozhangwang** [comment]
@dguy @enothereska Unit test fixed.

**Comment by dguy** [comment]
LGTM

**Comment by enothereska** [comment]
LGTM

**Comment by guozhangwang** [comment]
Thanks for the reviews. I'm not adding more unit test cases for this hotfix since it was covered already with the modified ones I think.

Merged to trunk and 0.10.1.

**Pull request closed without merging**
