### PR TITLE
KAFKA-6997 : Exclude test-sources.jar when $INCLUDE_TEST_JARS is FALSE

### PR DESCRIPTION
**Pull request by mageshn**
Exclude test-sources.jar when $INCLUDE_TEST_JARS is FALSE

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rayokota — APPROVED** [review]
LGTM

**Review by kkonstantine — APPROVED** [review]
Makes sense to me. Could we get a custom build on system test builder? LGTM otherwise.

**Review by wicknicks — APPROVED** [review]
Nice. Thanks! LGTM.

**Review by rhauch — APPROVED** [review]
Thanks for catching this needle in the haystack! LGTM!

**Review by ewencp — APPROVED** [review]
LGTM once tests come back clean

**Comment by mageshn** [comment]
@ewencp it says "Closed with unmerged commits"

**Comment by ewencp** [comment]
It was merged, I still use the old merge script because it does a bunch of stuff automatically (formatting the commit message, closing JIRA, etc), the only drawback is that github isn't aware that the content was squashed and rebased.

**Pull request closed without merging**
