### PR TITLE
KAFKA 8382: Add TimestampedSessionStore

### PR DESCRIPTION
**Pull request by highluck**
https://issues.apache.org/jira/browse/KAFKA-8382

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by highluck** [comment]
@mjsax @guozhangwang @bbejeck 
Can I ask for your opinion? thanks !

**Comment by highluck** [comment]
@mjsax 
Can I ask for your opinion? thanks !

**Comment by mjsax** [comment]
We are focusing on the 2.5 release atm. Also, adding this type of store is not high priority (we originally suggested it in the KIP, but during the implementation we realized that we don't need it for the DSL, and we did not add it for that reason).

It's still unclear, for which use case this store would be useful. I'll try to get to a review eventually, but it does not seem to be high priority in my review list.

Hence, adding this store implies zero changes to the DSL code.

**Comment by highluck** [comment]
@mjsax
Thank you! 

Thank you for your explanation!

**Comment by highluck** [comment]
@mjsax 
Is there a possibility that the task will be reflected?
We'll follow up if possible.

**Comment by mjsax** [comment]
I am not aware of any particular use-case that needs this feature atm. If you really want to work on it, feel free to do and we will try to review the PR. But it would be low priority. -- Thus, it might be a better time investment to work on something else? -- Or do you have a use-case that needs this feature?

**Comment by highluck** [comment]
@mjsax 
Let me know when you need it.
thank you!

**Comment by mjsax** [comment]
Thanks @highluck. Closing this PR for now.

**Pull request closed without merging**
