### PR TITLE
MINOR: Add user overridden test logging events

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by ijuma** [comment]
@guozhangwang, can you please update the `Common build options` section of the `Readme`? The code changes look good.

**Comment by guozhangwang** [comment]
Thanks @ijuma , updated the readme file.

**Comment by ijuma** [comment]
Thanks, LGTM. Merging to trunk and 0.10.0.

**Comment by guozhangwang** [comment]
Thanks @ijuma , I have modified the apache Jenkins accordingly:

```
kafka-trunk-jdk7
kafka-trunk-jdk8
kafka-0.10.0-jdk7
kafka-trunk-git-pr-jdk7
```

**Pull request closed without merging**
