### PR TITLE
KAFKA-6390: Update ZooKeeper to 3.4.11, Gradle and other minor updates

### PR DESCRIPTION
**Pull request by ijuma**
Updates:
- Gradle, gradle plugins and maven artifact updated
- Bug fix updates for ZooKeeper, Jackson, EasyMock and Snappy

Not updated:
- RocksDB as it often causes issues, so better done separately
- args4j as our test coverage is weak and the update was a
feature release

Also fixed scala-reflect version to match scala-library.

Release notes for ZooKeeper 3.4.11:
https://zookeeper.apache.org/doc/r3.4.11/releasenotes.html

A notable fix is improved handling of UnknownHostException:
https://issues.apache.org/jira/browse/ZOOKEEPER-2614

Manually tested that IntelliJ import and build still works.
Relying on existing test suite otherwise.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @rajinisivaram and cc @junrao and @theduderog for `UnknownHostException` improvement.

**Comment by junrao** [comment]
@ijuma : Thanks for the patch. LGTM. I will let you merge it after PR 4351.

**Comment by ijuma** [comment]
Retest this please

**Review by theduderog — COMMENTED** [review]
Thanks, @ijuma

**Pull request merged**
