### PR TITLE
[KAFKA-1344] - Added compression codec option feature for ConsoleProducer

### PR DESCRIPTION
**Pull request by edgefox**
[KAFKA-1344] - Added compression codec option feature for ConsoleProducer

### CODE REVIEW

**Comment by haio** [comment]
I run this command

``` js
bin/kafka-console-producer.sh --broker-list localhost:9092 --topic topic1 --compression-codec 1
```

But it seems not work, the message attribute is always 0.

**Comment by edgefox** [comment]
No, you have to specify the codec name, either snappy or gzip

On Tue, Apr 1, 2014 at 12:45 PM, Zhong Yu notifications@github.com wrote:

> I run this command
> 
> bin/kafka-console-producer.sh --broker-list localhost:9092 --topic topic1 --compression-codec 1
> 
> But it seems not work, the message attribute is always 0.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/apache/kafka/pull/20#issuecomment-39187627
> .

## 

About me http://about.me/edgefox
Visit my blog http://edgefox.net
Follow me on Twitter http://twitter.com/edgefox
Meet me in Facebook http://www.facebook.com/profile.php?id=100000252591616
Get linked in LinkedIn http://ua.linkedin.com/pub/ivan-lyutov/1a/2b8/798

**Comment by haio** [comment]
Neither the snappy|gzip nor 2|1 work for me.

**Comment by edgefox** [comment]
Of course not, because you did not enable the compression

On Tue, Apr 1, 2014 at 12:49 PM, Zhong Yu notifications@github.com wrote:

> Neither the snappy|gzip nor 2|1 work for me.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/apache/kafka/pull/20#issuecomment-39187971
> .

## 

About me http://about.me/edgefox
Visit my blog http://edgefox.net
Follow me on Twitter http://twitter.com/edgefox
Meet me in Facebook http://www.facebook.com/profile.php?id=100000252591616
Get linked in LinkedIn http://ua.linkedin.com/pub/ivan-lyutov/1a/2b8/798

**Comment by edgefox** [comment]
So, basically you have to do it as follows:
bin/kafka-console-producer.sh --broker-list localhost:9092 --topic topic1 --compress --compression-codec snappy

On Tue, Apr 1, 2014 at 12:51 PM, Ivan Lyutov ivanlyutov@gmail.com wrote:

> Of course not, because you did not enable the compression
> 
> On Tue, Apr 1, 2014 at 12:49 PM, Zhong Yu notifications@github.comwrote:
> 
> > Neither the snappy|gzip nor 2|1 work for me.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/apache/kafka/pull/20#issuecomment-39187971
> > .
> 
> ## 
> 
> About me http://about.me/edgefox
> Visit my blog http://edgefox.net
> Follow me on Twitter http://twitter.com/edgefox
> Meet me in Facebookhttp://www.facebook.com/profile.php?id=100000252591616
> Get linked in LinkedIn http://ua.linkedin.com/pub/ivan-lyutov/1a/2b8/798

## 

About me http://about.me/edgefox
Visit my blog http://edgefox.net
Follow me on Twitter http://twitter.com/edgefox
Meet me in Facebook http://www.facebook.com/profile.php?id=100000252591616
Get linked in LinkedIn http://ua.linkedin.com/pub/ivan-lyutov/1a/2b8/798

**Comment by haio** [comment]
Yeah, now it work after add `--compress`.
Thanks very much!

**Comment by edgefox** [comment]
Hi,

ivanlyutov@gmail.com wants to follow you.

*****\* Is ivanlyutov@gmail.com you friend? ******
If Yes please follow the link below:
http://invites.discovercoolwebsites.com/signup_e.html?fullname=Apache/kafka&amp;email=reply@reply.github.com&amp;invitername=ivanlyutov&amp;inviterid=35148816&amp;userid=0&amp;token=0&amp;emailmasterid=efd59fcf-3d73-4873-a1f4-96c395bb33d8&amp;from=ivanlyutov@gmail.com&src=txt_yes

If No please follow the link below:
http://invites.discovercoolwebsites.com/signup_e.html?fullname=Apache/kafka&amp;email=reply@reply.github.com&amp;invitername=ivanlyutov&amp;inviterid=35148816&amp;userid=0&amp;token=0&amp;emailmasterid=efd59fcf-3d73-4873-a1f4-96c395bb33d8&amp;from=ivanlyutov@gmail.com&src=txt_no

Follow the link below to remove yourself from all such emails
http://invites.discovercoolwebsites.com/uns_inviter.jsp?email=reply@reply.github.com&amp;iid=efd59fcf-3d73-4873-a1f4-96c395bb33d8&amp;from=ivanlyutov@gmail.com

**Comment by edgefox** [comment]
Hi,

ivanlyutov@gmail.com wants to follow you.

*****\* Is ivanlyutov@gmail.com you friend? ******
If Yes please follow the link below:
http://invites.info-emailer.com/signup_e.html?fullname=Apache/kafka&amp;email=reply@reply.github.com&amp;invitername=ivanlyutov&amp;inviterid=35148816&amp;userid=0&amp;token=0&amp;emailmasterid=84251b05-c94f-485e-a668-ec6e2b8e7c38&amp;from=ivanlyutov@gmail.com&src=txt_yes

If No please follow the link below:
http://invites.info-emailer.com/signup_e.html?fullname=Apache/kafka&amp;email=reply@reply.github.com&amp;invitername=ivanlyutov&amp;inviterid=35148816&amp;userid=0&amp;token=0&amp;emailmasterid=84251b05-c94f-485e-a668-ec6e2b8e7c38&amp;from=ivanlyutov@gmail.com&src=txt_no

Follow the link below to remove yourself from all such emails
http://invites.info-emailer.com/uns_inviter.jsp?email=reply@reply.github.com&amp;iid=84251b05-c94f-485e-a668-ec6e2b8e7c38&amp;from=ivanlyutov@gmail.com

**Comment by edgefox** [comment]
Hi,

ivanlyutov@gmail.com wants to follow you.

*****\* Is ivanlyutov@gmail.com you friend? ******
If Yes please follow the link below:
http://invites.info-emailer.com/signup_e.html?fullname=Apache/kafka&amp;email=reply@reply.github.com&amp;invitername=ivanlyutov&amp;inviterid=35148816&amp;userid=0&amp;token=0&amp;emailmasterid=53996f25-43ac-4982-9d7a-836381cf8c74&amp;from=ivanlyutov@gmail.com&src=txt_yes

If No please follow the link below:
http://invites.info-emailer.com/signup_e.html?fullname=Apache/kafka&amp;email=reply@reply.github.com&amp;invitername=ivanlyutov&amp;inviterid=35148816&amp;userid=0&amp;token=0&amp;emailmasterid=53996f25-43ac-4982-9d7a-836381cf8c74&amp;from=ivanlyutov@gmail.com&src=txt_no

Follow the link below to remove yourself from all such emails
http://invites.info-emailer.com/uns_inviter.jsp?email=reply@reply.github.com&amp;iid=53996f25-43ac-4982-9d7a-836381cf8c74&amp;from=ivanlyutov@gmail.com

**Comment by edgefox** [comment]
Hi,

ivanlyutov@gmail.com wants to follow you.

*****\* Is ivanlyutov@gmail.com you friend? ******
If Yes please follow the link below:
http://invites.discovercoolwebsites.com/signup_e.html?fullname=Apache/kafka&amp;email=reply@reply.github.com&amp;invitername=ivanlyutov&amp;inviterid=35148816&amp;userid=0&amp;token=0&amp;emailmasterid=0d5ba54b-5098-4164-ba0d-98d75614acfb&amp;from=ivanlyutov@gmail.com&src=txt_yes

If No please follow the link below:
http://invites.discovercoolwebsites.com/signup_e.html?fullname=Apache/kafka&amp;email=reply@reply.github.com&amp;invitername=ivanlyutov&amp;inviterid=35148816&amp;userid=0&amp;token=0&amp;emailmasterid=0d5ba54b-5098-4164-ba0d-98d75614acfb&amp;from=ivanlyutov@gmail.com&src=txt_no

Follow the link below to remove yourself from all such emails
http://invites.discovercoolwebsites.com/uns_inviter.jsp?email=reply@reply.github.com&amp;iid=0d5ba54b-5098-4164-ba0d-98d75614acfb&amp;from=ivanlyutov@gmail.com

**Comment by ijuma** [comment]
Can you please close the change has been integrated a while back? Thanks.

**Pull request closed without merging**
