### PR TITLE
KAFKA-18305: validate controller.listener.names is not in inter.broker.listener.name for kcontrollers

### PR DESCRIPTION
**Pull request by kevin-wu24**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cmccabe** [comment]
Should we have an exception for cases where the inter broker listener was not explicitly set, but configured as a default?

**Comment by mumrah** [comment]
@kevin-wu24 do we have a JIRA for this one?

**Comment by kevin-wu24** [comment]
> @kevin-wu24 do we have a JIRA for this one?

Filed https://issues.apache.org/jira/browse/KAFKA-18305

**Review by cmccabe — APPROVED** [review]
LGTM

**Pull request merged**
