### PR TITLE
MINOR: Fix system test test_upgrade_to_cooperative_rebalance

### PR DESCRIPTION
**Pull request by cadonna**
Log messages were changed in the AssignorConfiguration (https://github.com/apache/kafka/pull/11490) that are
also used for verification in system test
StreamsCooperativeRebalanceUpgradeTest.test_upgrade_to_cooperative_rebalance.

This commit fixes the test and adds comments to the log messages
that point to the test that needs to be updated in case of
changes to the log messages.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @showuon, @ableegoldman

**Comment by cadonna** [comment]
The system test passes locally with this fix.

**Comment by dajac** [comment]
@cadonna Could we mention the commit which changed it in the description?

**Review by vvcephei — APPROVED** [review]
Thanks, @cadonna !

**Comment by dajac** [comment]
@cadonna LGTM. Could you cherry-pick it to 3.1 as well? Thanks.

**Review by showuon — APPROVED** [review]
LGTM! Sorry that I didn't know the log message is also used in system tests. And thanks for adding comment above the message, which will prevent this issue happened again. Thank you.

**Comment by showuon** [comment]
> @cadonna LGTM. Could you cherry-pick it to 3.1 as well? Thanks.

I agree this PR to be cherry-pick into 3.1 branch since it'll also affect 3.1. Thank you.

**Comment by showuon** [comment]
> @cadonna Could we mention the commit which changed it in the description?

This issue is caused by the PR https://github.com/apache/kafka/pull/11490 changed log message. Thank you.

**Comment by cadonna** [comment]
@showuon It happened to all of us at least once.

**Comment by cadonna** [comment]
> 

@dajac Yes, I will cherry-pick it!

**Comment by cadonna** [comment]
Test failures are unrelated since only comments were added to the production code and the system tests are not executed during a build.

**Comment by cadonna** [comment]
Cherry-picked to 3.1

**Pull request merged**
