### PR TITLE
KAFKA-5579 check for null.

### PR DESCRIPTION
**Pull request by jcustenborder**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6019/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6004/
Test PASSed (JDK 8 and Scala 2.12).

**Review by rhauch — APPROVED** [review]
LGTM

**Comment by rhauch** [comment]
@ewencp, this is a very simple change and is ready to be merged. Thanks!

**Comment by ewencp** [comment]
LGTM, thanks!

**Pull request closed without merging**
