### PR TITLE
KAFKA-13722: code cleanup after deprecated StateStore.init() was removed

### PR DESCRIPTION
**Pull request by mjsax**
We remove the deprecated overload of StateStore.init() and thus do not need to cast any longer. This PR removes all unnecessary casts, and additionally cleans ups all related classed to reduce warnings.

### CODE REVIEW

**Comment by mjsax** [comment]
Java 17 passed.

Java 23:
```
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroupsDeprecatedConsumerGroupState(String, String).quorum=kraft.groupProtocol=consumer
Found 1 flaky test failures:
FLAKY ⚠️  TransactionsTest > testFailureToFenceEpoch(String, String, boolean).quorum=kraft.groupProtocol=classic.isTV2Enabled=true
```

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by mjsax** [comment]
Java 23:
```
Found 1 test failures:
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroupsDeprecatedConsumerGroupState(String, String).quorum=kraft.groupProtocol=consumer
```

**Comment by mjsax** [comment]
Java 17 passed.

Java 23:
```
Found 3 test failures:
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroupsDeprecatedConsumerGroupState(String, String).quorum=kraft.groupProtocol=consumer
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroups(String, String).quorum=kraft.groupProtocol=consumer
FAILED ❌ UserClientIdQuotaTest > testThrottledRequest(String, String).quorum=kraft.groupProtocol=consumer
Found 1 flaky test failures:
FLAKY ⚠️  AbstractCoordinatorTest > testWakeupAfterSyncGroupReceived()
```

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `4.0` branch.

**Pull request merged**
