### PR TITLE
KAFKA-12283 Flaky Test RebalanceSourceConnectorsIntegrationTest#testM…

### PR DESCRIPTION
**Pull request by chia7712**
issue: https://issues.apache.org/jira/browse/KAFKA-12283

Increment protocol has three issues:

## case 0: the revocation algorithm produces uneven distributions

**Assignments:** 

- "W0" -> 8 connectors/tasks
- "W1" -> 8 connectors/tasks
- (New) "W2" -> 0 connectors/tasks

**Revoked (trunk)**

- "W0" -> 2 connectors/tasks
- "W1" -> 2 connectors/tasks

**Revoked (patch)**

- "W0" -> 2 connectors/tasks
- "W1" -> 3 connectors/tasks

## case 1: the revocation algorithm is NOT based on completed assignments (with new submissions)

**Assignments:** 

- (Unassigned-> 4 connectors/tasks)
- "W0" -> 4 connectors/tasks

**Revoked (trunk)**

- "W0" -> 2 connectors/tasks

## case 2: the revocation algorithm is based on out-of-date workers

**Assignments** 
- "W0" -> 16 connectors/tasks

**Revoked** (there are 2 workers so 8 connectors/tasks are revoked)
- "W0" -> 8 connectors/tasks
- (new) "W1"

**Reassign** (there is another new worker so the reassignment is based on "three" workers rather than "two" workers)
- "W0" -> 8 connectors/tasks
- (new) "W1" -> 4 connectors/tasks
- (new) "W2" -> 4 connectors/tasks

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@ramesh-muthusamy Could you take a look? thanks!

**Comment by chia7712** [comment]
close this PR as there are different issues for the flaky

**Comment by ramesh-muthusamy** [comment]
Hi Chia,

I will check this .

Thanks
Ramesh

**Comment by ramesh-muthusamy** [comment]
@chia7712 i will check this , can you let me know if this is the JIRA for the same . KAFKA-12283

**Pull request closed without merging**
