### PR TITLE
KAFKA-2874: shutdown ZK process reliably

### PR DESCRIPTION
**Pull request by miguno**

### CODE REVIEW

**Comment by ijuma** [comment]
@fpj What do you think?

**Comment by fpj** [comment]
LGTM. Note though that we've only changed send TERM in the 3.5 and 3.6 branches (check ZOOKEEPER-2079).

Also, a slightly better approach might be to remember the process id rather grepping, but maybe you don't want to do this change in this jira.

**Comment by miguno** [comment]
> LGTM. Note though that we've only changed send TERM in the 3.5 and 3.6 branches (check ZOOKEEPER-2079).

Yes, that's why I made the note on possible side effects yes/no in the JIRA ticket, @fpj.

> Also, a slightly better approach might be to remember the process id rather grepping, but maybe you don't want to do this change in this jira.

Exactly.  Switching to pid-tracking (and one can debate whether that's a good idea in the first place) would also require changing e.g. the Kafka start/stop scripts.  Hence I wanted to be minimally invasive with this PR with regards to the existing implementation.

**Comment by ijuma** [comment]
Yeah, pid tracking would be good to discuss in a separate JIRA (I also thought of that).

**Comment by miguno** [comment]
PS:  Reading [ZOOKEEPER-2079](https://issues.apache.org/jira/browse/ZOOKEEPER-2079) I noticed that change was from SIGKILL (`-9`) to SIGTERM, whereas in our case we move from SIGINT (not as harsh as SIGKILL) to SIGTERM.

**Comment by fpj** [comment]
@miguno 

> > Reading ZOOKEEPER-2079 I noticed that change was from SIGKILL (-9) to SIGTERM, whereas in our case we move from SIGINT (not as harsh as SIGKILL) to SIGTERM.

yes, I meant to say that the branch of zk that kafka currently uses sends sigkill, which is 3.4.

**Comment by miguno** [comment]
@fpj: Ah, sorry.  So that means going from SIGINT to SIGTERM (SIGTERM is also less harsh then SIGKILL) should not be a problem then.

**Comment by junrao** [comment]
Thanks for the patch. LGTM

**Pull request closed without merging**
