### PR TITLE
KAFKA-4690: Return new error code for DeleteTopicRequest when topic deletion disabled.

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vahidhashemian** [comment]
Is it possible to have a unit test for this?

**Comment by omkreddy** [comment]
@vahidhashemian Thanks for the review. Added a  test.

@ijuma  Pls take a look when you get a chance

**Review by vahidhashemian — APPROVED** [review]
Thanks for addressing my feedback. LGTM.

**Comment by hachikuji** [comment]
@omkreddy I may have missed it, but is there a KIP for this? Won't we have to bump the protocol version?

**Comment by omkreddy** [comment]
@hachikuji Currently delete topic requests will time-out when topic deletion is disabled. With this change older version java admin clients will get UnknownServerException.  

Will it be fine, If we raise one of the existing exception (INVALID_REQUEST) ?
I am fine with writing small KIP to bump the protocol version.

**Comment by omkreddy** [comment]
Closing this in-favor of https://github.com/apache/kafka/pull/3960

**Pull request closed without merging**
