### PR TITLE
KAFKA-3100; Broker.createBroker should work if json is version > 2 and still compatible

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Tests pass locally

**Comment by ijuma** [comment]
We need to backport this to the 0.9.0 branch as well.

**Comment by granthenke** [comment]
This patch is definitely an improvement, and LGTM.

Longer term we likely want to define zookeeper compatibility a bit more concretely. 

Currently `ZkUtils.registerBrokerInZk` still sets host, port, and jmx_port for V2 json even though V2 only uses endpoints. That makes sense for compatibility if the V1 option would be tried when any other version is seen. I suspect when we add a V3 or V4 we would also maintain writing the older fields for V1 & V2 in `ZkUtils.registerBrokerInZk`. It could make sense to have the parsing logic in `Broker.createBroker` (or anything reading Json from Zookeeper) try all known versions in descending order from the version received from ZK. but perhaps that logic is too loose. 

A generic function to capture whatever rule is defined such as `parseVersionedJson` could take functions for each versions and return the successful result or fail. Rough pseudo code for examples sake:

``` scala
def parseVersionedJson[T](json: String, versionedParsers: Map[Int, String => T]): T = {
  Json.parseFull(json) match {
    case Some(m) =>
      val fields = m.asInstanceOf[Map[String, Any]]
      val version = fields("version").asInstanceOf[Int]
      if(versionedParsers.contains(version)) {
        versionedParsers(version)(json)
      } else {
        val parsers = versionedParsers.toSeq.sortBy(_._1)
        // loop over parsers trying to parse, error if all fail
        ...
      }
    case None =>
      throw new RuntimeException(s"Could not parse json string: $json")
  }
}
```

**Comment by granthenke** [comment]
We should also be sure to update this wiki https://cwiki.apache.org/confluence/display/KAFKA/Kafka+data+structures+in+Zookeeper with the new broker version.

**Comment by ijuma** [comment]
I agree that something like that would be worth exploring in a JIRA about making our ZK code more consistent with regards to compatibility handling. Since this PR is also for 0.9.0.1, I think it's fine to keep it simple.

**Comment by ijuma** [comment]
Thanks for the heads-up with regards to the wiki @granthenke, updated it.

**Comment by junrao** [comment]
Thanks for the patch. LGTM

**Comment by junrao** [comment]
Double committed to 0.9.0 and trunk.

**Comment by junrao** [comment]
@ijuma : Also, let's remember to update the upgrade doc in trunk after 0.9.0.1 is released.

**Comment by ijuma** [comment]
@junrao Do you mean once we bump the broker registration version in ZK for KIP-36? I thought that was the natural time to mention in the upgrade notes that need to go via 0.9.0.1 first for people using old clients. KIP-36 itself mentions this in the upgrade section, so that will help ensure we don't forget. Or did I misunderstand you?

**Comment by junrao** [comment]
@ijuma : Yes, KIP-36 is the right place to update the upgrade doc.

**Pull request closed without merging**
