### PR TITLE
KAFKA-12600: Remove deprecated config value `default` for client config `client.dns.lookup`

### PR DESCRIPTION
**Pull request by ijuma**
The config has been deprecated since Kafka 2.6 (released ~1 year before
3.0), but it was the default before it got deprecated. As such, it's
reasonably unlikely that people would have set it explicitly.

Given the confusing `default` name even though it's _not_ the default, I
think we should remove it in 3.0.

Also remove `ClientDnsLookup.DEFAULT` (not public API), which unlocks
a number of code simplications.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
@ijuma Makes sense to remove it. Should we remove `DEFAULT` from the `ClientDnsLookup` enum as well? Or do we have to keep it for something else?

**Comment by ijuma** [comment]
@dajac Yes, we can definitely remove it! Done.

**Review by dajac — APPROVED** [review]
LGTM, assuming tests pass. Thanks!

**Comment by ijuma** [comment]
Unrelated failure that passed on retry:

> Build / JDK 11 / testResponseIncludesLeaderEpoch()

**Pull request merged**
