### PR TITLE
KAFKA-17193: Pin all external GitHub Actions to the specific git hash

### PR DESCRIPTION
**Pull request by mimaison**
As per https://infra.apache.org/github-actions-policy.html all actions not from the `apache/*`, `github/*` and `actions/*` namespaces must be pinned to a specific git hash.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
according to the discussion (https://github.com/apache/kafka/pull/16915#discussion_r1725350586), should we use `tag` instead of `git hash`? it seems they are all "verified creator".

**gradle/actions/setup-gradle**
https://github.com/marketplace/actions/build-with-gradle

**aquasecurity/trivy-action**
https://github.com/marketplace/actions/aqua-security-trivy

**docker/setup-qemu-action**
https://github.com/marketplace/actions/docker-setup-qemu

**docker/setup-buildx-action**
https://github.com/marketplace/actions/docker-setup-buildx

**docker/login-action**
https://github.com/marketplace/actions/docker-login

**Comment by mimaison** [comment]
The recommendation from https://github.com/apache/kafka/pull/16915#discussion_r1725350586 comes from GitHub. I followed the recommendations from Apache INFRA: https://infra.apache.org/github-actions-policy.html:

> You MAY use all actions internal to the apache/*, github/* and actions/* namespaces without restrictions.
>
> You MUST pin all external actions to the specific git hash (SHA1) of the action that has been reviewed for use by the project. For instance, you MUST pin foobar/baz-action@8843d7f92416211de9ebb963ff4ce28125932878.

**Review by chia7712 — APPROVED** [review]
> I followed the recommendations from Apache INFRA: https://infra.apache.org/github-actions-policy.html:

Got it. Don't Fight the INFRA :)

**Comment by mumrah** [comment]
Thanks for the patch @mimaison! I missed that second point in the INFRA policy.

**Pull request merged**
