### PR TITLE
MINOR: Delete KafkaCSVMetricsReporter

### PR DESCRIPTION
**Pull request by ijuma**
All classes/traits are private and unused.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by divijvaidya — APPROVED** [review]
Code removal PRs are always my favourite ones!

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
unrelated to this PR, but it seems `KafkaMetricsReporterMBean` has unused method `startReporter` and `stopReporter` after this gets merged. Maybe we should deprecate `KafkaMetricsReporterMBean` (and `KafkaMetricsReporter`) with new Java interface. WDYT?

**Comment by ijuma** [comment]
Perhaps this is actually a public interface from the days when these things didn't follow a consistent pattern (before I got involved with the project). For example:

https://users.kafka.apache.narkive.com/2b0VBWUX/monitoring-kafka-metrics

So, we probably need a KIP and the removal may have to wait for 4.0.

**Comment by ijuma** [comment]
I will close this for now and file a JIRA.

**Comment by chia7712** [comment]
> I will close this for now and file a JIRA.

Have you opened the jira? If not, I'd like to open a jira for it

**Pull request closed without merging**
