### PR TITLE
MINOR: improve stabilty of ProcessorStateManagerTest

### PR DESCRIPTION
**Pull request by mjsax**
This PR addressed the following test failure:
```
java.lang.AssertionError:
Expected: a string starting with "process-state-manager-test Failed to write offset checkpoint file to ["
but: was "[AdminClient clientId=adminclient-874] Connection to node -1 (localhost/127.0.0.1:8080) could not be established. Broker may not be available."
```

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman

This should be cherry-picked to `2.2` (maybe also further back) for which the error was observed: https://builds.apache.org/blue/organizations/jenkins/kafka-2.2-jdk8/detail/kafka-2.2-jdk8/1/tests/

**Review by vvcephei — APPROVED** [review]
LGTM. Sorry for the brittle test, @mjsax .

**Review by bbejeck — APPROVED** [review]
Thanks for the fix @mjsax LGTM

**Review by guozhangwang — APPROVED** [review]
LGTM.

**Comment by guozhangwang** [comment]
Also cherry-picked to 2.2

**Pull request merged**
