### PR TITLE
KAFKA-13875 Adjusted the output the topic describe output to include TopicID & se…

### PR DESCRIPTION
**Pull request by Moovlin**
…gment.bytes

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [X] Verify design and implementation 
- [X] Verify test coverage and CI build status
- [X] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Moovlin** [comment]
There are no code changes in this PR. It's an update to the quickstart.html file so I think these tests failures can be ignored. This is only my second PR so please let me know if I have to do something different.

**Review by Kvicii — APPROVED** [review]

**Comment by dengziming** [comment]
It's OK to add topicId in the docs, the segment.bytes property is not intended to be printed, this seems to be a small bug: KAFKA-13718

**Comment by Moovlin** [comment]
@dengziming I went ahead and updated the PR to remove the segment.bytes property from the sample output. I was going back and forth on if it should be removed since what the user will see vs. what we display would be different but given that this is a known bug & (at least according to the linked Jira) should be an noob friendly bug I think it makes sense to remove it as well. If I have time, I will try and take a crack at KAFKA-13718.

**Comment by dengziming** [comment]
Yes, there is no perfect solution for this currently, I think we should first fix KAFKA-13718 and decide whether we should always print `segment.bytes`, and then we can merge this PR.
According to the comments of KAFKA-13718, this bug has been around for a long time, so we'd better make it bug-compatible.

**Comment by Moovlin** [comment]
My understanding of the statement "so we'd better make it [the PR] bug-compatible" means we should add back in the segment.bytes for the time being while the we in the community figure out what we would like to do with KAFKA-13718. Is that correct? 

I also took a look at KAFKA-13718 but I'm unsure of where the numbers we're seeing are propagating from & how to adjust defaults. I'll reach out in the Jira about it but just sharing as a heads up.

**Comment by Moovlin** [comment]
@dengziming I went and submitted a PR for KAFKA-13718 which has since been merged into trunk. The PR (12246) keeps the kafka-topics.sh command from printing the segment.bytes values when describing the topic. Because of this, when end users now follow the quickstart, what they see and what they get should be the same from as the docs. Thanks so much.

**Comment by showuon** [comment]
@Moovlin , IIRC, even if there's no any overridden configs, the `configs:` column will still be displayed. Could you confirm it by running the command once with the latest code? Thank you.

**Comment by Moovlin** [comment]
@showuon You were correct. I went and added the "Configs:" column to the quickstart output. Great catch!

**Review by showuon — APPROVED** [review]
LGTM!

**Pull request merged**
