### PR TITLE
Minor: Remove unnecessary calls to getInetAddress() and getPort() in …

### PR DESCRIPTION
**Pull request by attila-s**
…BlockingChannel

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

Ran unit tests in SyncProducerTest, and they passed.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by asasvari** [comment]
retest this please

**Comment by asasvari** [comment]
@viktorsomogyi can you please review it

**Comment by asasvari** [comment]
retest this please

**Review by viktorsomogyi — APPROVED** [review]
Looks good, thanks for the PR.

**Comment by chia7712** [comment]
@attila-s Thanks for your effort. Sorry that I'm going to close this PR since ```BlockingChannel.scala``` was removed by https://github.com/apache/kafka/commit/cc4dce94af8b19a796eeb7a9be78640739cb1a48

**Pull request closed without merging**
