### PR TITLE
the rate calculation is wrong somehow, will make some heavy read and write log stop compaction

### PR DESCRIPTION
**Pull request by lisa2lisa**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Nice catch. Would you be able to resubmit this with trunk as the target branch? And would you be able to include a test?

Maybe we want to include this in 1.0.0 @guozhangwang @hachikuji

**Comment by ijuma** [comment]
In `groupSegmentBySize`, we should probably change the following two to call `toLong` as well:

```scala
      var logSize = segs.head.size
      var indexSize = segs.head.index.sizeInBytes
```

**Comment by hachikuji** [comment]
Thanks for the fix. LGTM. I'll merge this under https://issues.apache.org/jira/browse/KAFKA-6030 and incorporate @ijuma's suggestion. We can do a test case in a follow-up.

**Comment by lisa2lisa** [comment]
For sure, will create a PR to trunk

**Pull request closed without merging**
