### PR TITLE
KAFKA-1548 Refactor the "replica_id" in requests

### PR DESCRIPTION
**Pull request by baluchicken**

### CODE REVIEW

**Comment by baluchicken** [comment]
@guozhangwang @gwenshap  plz review

**Comment by guozhangwang** [comment]
Looks reasonable to me overall. cc @hachikuji

**Comment by hachikuji** [comment]
@guozhangwang Should we make similar changes in `o.a.k.c.requests` or is this only for the old consumer?

**Comment by guozhangwang** [comment]
hmm good question, I created the JIRA only for the old consumer but maybe we can refactor it for both. @baluchicken could you check if `o.a.k.c.requests` on the client side need to be refactored as well?

**Comment by baluchicken** [comment]
Yeah, sure

**Comment by baluchicken** [comment]
@guozhangwang I don't think the `o.a.k.c.requests` need refactoring, but I am pretty new to this, and I have to learn a lot about the code.

**Comment by guozhangwang** [comment]
I looked through the client side code and I think we do not need to add the `describe` yet until we are about to remove the old server side code. So I'm happy to merge it if @hachikuji agreed.

**Comment by baluchicken** [comment]
@hachikuji how should I proceed with this one?

**Comment by hachikuji** [comment]
@baluchicken Apologies for the delay. From what I can tell, the JIRA is about improving the ability to distinguish between offset/fetch requests from replicas and those from consumers. Only we no longer use the scala FetchRequest or OffsetFetchRequest objects on the broker, so it may make more sense to make these changes in the new request objects instead.

**Comment by ijuma** [comment]
Just noticed this. As @hachikuji said, the Scala classes are mostly not used and will be removed once the old clients are removed. Changes, if required, should focus on the Java classes.

**Comment by ijuma** [comment]
Shall we close this PR then?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6568/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6553/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
Closing for cleanup.

**Pull request closed without merging**
