### PR TITLE
KAFKA-14133: Replace EasyMock with Mockito in streams tests

### PR DESCRIPTION
**Pull request by clolov**
Batch 6 of the tests detailed in https://issues.apache.org/jira/browse/KAFKA-14133 which use EasyMock and need to be moved to Mockito.

### CODE REVIEW

**Comment by clolov** [comment]
Three points for this pull request:
* I have left `mock()` instead of `@Mock` where abstracting it wouldn't have proved easy.
* I have used `lenient()` with some strict stubs because otherwise Mockito complains we do not use that code in some tests. I chose to not break the abstraction.
* If I have deleted expectations that’s because Mockito said they are not used.

**Comment by clolov** [comment]
@cadonna for visibility

**Comment by clolov** [comment]
Tagging @divijvaidya for visibility as well :)

**Comment by clolov** [comment]
Hello @wcarlson5 👋. Divij Vaidya mentioned he worked on a couple of pull requests and you reviewed them so I was hoping you would be willing to go over this one to get https://issues.apache.org/jira/browse/KAFKA-14133 over the line!

**Review by cadonna — APPROVED** [review]
@clolov Thanks for the PR!

LGTM!

**Comment by cadonna** [comment]
Build failures are unrelated:
```
Build / JDK 11 and Scala 2.13 / kafka.controller.ControllerIntegrationTest.testPartitionReassignmentToBrokerWithOfflineLogDir()
Build / JDK 8 and Scala 2.12 / org.apache.kafka.common.network.SslTransportLayerTest.[1] tlsProtocol=TLSv1.2, useInlinePem=false
Build / JDK 8 and Scala 2.12 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsWithCustomForwardingAdminIntegrationTest.testReplicationIsCreatingTopicsUsingProvidedForwardingAdmin()
Build / JDK 8 and Scala 2.12 / org.apache.kafka.controller.QuorumControllerTest.testSnapshotSaveAndLoad()
```

**Comment by clolov** [comment]
Thank you very much for the review and merge!

**Pull request merged**
