### PR TITLE
KAFKA-2516: Rename o.a.k.client.tools to o.a.k.tools

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by gwenshap** [comment]
@granthenke Per @ewencp comment in the JIRA, this changes user-facing behavior (kinda - but users will need to know that the class location changed). Can you update the relevant section in the docs as part of this PR?

**Comment by guozhangwang** [comment]
@granthenke Do you mind if I take over the docs change if you are busy recently? As we have a tight 0.9.0 release timeline we want to resolve blocker issues asap.

**Comment by granthenke** [comment]
Not at all,  go ahead. I can get to it tomorrow otherwise.

**Comment by guozhangwang** [comment]
Tomorrow is actually good enough :) I will leave it to you then.

**Comment by gwenshap** [comment]
Pinging for doc update :)

**Comment by granthenke** [comment]
See PR #337. Sorry for not updating sooner. Github shows the relationship on my side.

**Pull request closed without merging**
