### PR TITLE
MINOR: fix unstable FanoutIntegrationTest

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Test failed with
```
org.apache.kafka.streams.errors.StreamsException: org.apache.kafka.streams.errors.ProcessorStateException: state directory [/tmp/kafka-streams/fanout-integration-test] doesn't exist and couldn't be created
```

Note, this PR is for `1.0` branch -- we remove this test in `trunk`.

Call for review @bbejeck @dguy @guozhangwang

**Review by guozhangwang — APPROVED** [review]

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Pull request merged**
