### PR TITLE
KAFKA-7453: Expire registered channels not selected within idle timeout

### PR DESCRIPTION
**Pull request by rajinisivaram**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM

**Review by junrao — APPROVED** [review]
@rajinisivaram : Thanks for the patch. LGTM

**Comment by rajinisivaram** [comment]
@ijuma @junrao Thanks for the reviews, merging to trunk.

**Comment by rajinisivaram** [comment]
Also merged to 2.0 and 1.1.

**Pull request merged**
