### PR TITLE
KAFKA-15853: Move KafkaConfig properties definition out of core

### PR DESCRIPTION
**Pull request by OmniaGM**
Moving KafkaConfig props out of core. The pr is big however it's mostly renaming the props to match Java constant patterns and switching to `org.apache.kafka.server.config.KafkaConfig` instead of the object companion `kafka.server.KafkaConfig`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by nizhikov** [comment]
Hello @OmniaGM 

I think this PR still too big for one change.

Can we split it?
We can start with LogConfiguration:

```
  /** ********* Log Configuration ***********/
  val NumPartitionsProp = "num.partitions"
  val LogDirsProp = LogConfigPrefix + "dirs"
  val LogDirProp = LogConfigPrefix + "dir"
  val LogSegmentBytesProp = ServerTopicConfigSynonyms.serverSynonym(TopicConfig.SEGMENT_BYTES_CONFIG)
....

```

and replication configuration:

```
  /** ********* Replication configuration ***********/
  val ControllerSocketTimeoutMsProp = "controller.socket.timeout.ms"
  val DefaultReplicationFactorProp = "default.replication.factor"
  val ReplicaLagTimeMaxMsProp = "replica.lag.time.max.ms"
  val ReplicaSocketTimeoutMsProp = "replica.socket.timeout.ms"
  val ReplicaSocketReceiveBufferBytesProp = "replica.socket.receive.buffer.bytes"
...
```

**Comment by nizhikov** [comment]
Hello @OmniaGM 

Are you be able to split this PR in several to simplify review and merge?
My jira https://issues.apache.org/jira/browse/KAFKA-14588 blocked by migration `KafkaConfig` from `core` so I want to help you with these changes somehow. 

If you have no time to split - I can offer my help with this.

**Comment by OmniaGM** [comment]
> Hello @OmniaGM 
> 
> 
> 
> Are you be able to split this PR in several to simplify review and merge?
> 
> My jira https://issues.apache.org/jira/browse/KAFKA-14588 blocked by migration `KafkaConfig` from `core` so I want to help you with these changes somehow. 
> 
> 
> 
> If you have no time to split - I can offer my help with this.

Start doing this but will be continue this after the Kafka Summit London.

**Comment by nizhikov** [comment]
@OmniaGM 

> Start doing this but will be continue this after the Kafka Summit London.

Great! Don't hesitate to ask for assistance if you need any help.

**Comment by OmniaGM** [comment]
Am going to close this one as it drifted away from the approach we took to break the configs out.

**Comment by nizhikov** [comment]
@OmniaGM Are you still working on moving KafkaConfig out of core? 
Can you, please, show me PR's you are currently working on regarding KafkaConfig?

**Comment by OmniaGM** [comment]
> @OmniaGM Are you still working on moving KafkaConfig out of core? Can you, please, show me PR's you are currently working on regarding KafkaConfig?

I was about to open a pr for this :) I have two local prs left then we can call this jira done

**Pull request closed without merging**
