### PR TITLE
KAFKA-13323 Fixed variable name in KafkaConsumer

### PR DESCRIPTION
**Pull request by vijaykriishna**
KAFKA-13323 Fixed variable name in KafkaConsumer

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by Kvicii — COMMENTED** [review]
hi, I want to know why this html file is modified?

**Comment by hachikuji** [comment]
@vijaykriishna Thanks, the variable name fix LGTM. It does look a little strange to modify the one html snippet as part of this patch. Would it make sense to split that out into a separate PR? Maybe it makes sense to add that change to https://github.com/apache/kafka/pull/11542 instead.

**Comment by hachikuji** [comment]
I went ahead and reverted the unrelated change in `docs/streams/developer-guide/processor-api.html` so that we can get the easy name fix checked in.

**Review by hachikuji — APPROVED** [review]
LGTM

**Pull request merged**
