### PR TITLE
KAFKA-16954: fix consumer close to release assignment in background

### PR DESCRIPTION
**Pull request by lianetm**
Cherry-picking 2 commits required for fixing KAFKA-16954 for 3.8 (fix consumer close to release assignment in background)

### CODE REVIEW

**Comment by lianetm** [comment]
Hey @lucasbru , here is the PR cherry-picking only the required changes for 3.8 for the consumer close fix. The conflicts were due to this client cleanup commit https://github.com/apache/kafka/commit/79ea7d6122ac4dbc1441e9efbddae44b1a9c93f9 that is not in 3.8 (and it's not needed), so I left it out. Thanks!

**Comment by lianetm** [comment]
Build completed with 4 unrelated failures:

> Build / JDK 8 and Scala 2.12 / testSyncTopicConfigs() – org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationExactlyOnceTest
> Build / JDK 8 and Scala 2.12 / testTaskRequestWithOldStartMsGetsUpdated() – org.apache.kafka.trogdor.coordinator.CoordinatorTest
> Build / JDK 21 and Scala 2.13 / "testNoConsumeWithDescribeAclViaSubscribe(String).quorum=kraft" – kafka.api.DelegationTokenEndToEndAuthorizationWithOwnerTest
> Build / JDK 21 and Scala 2.13 / testDescribeQuorumReplicationSuccessful [1] Type=Raft-Isolated, MetadataVersion=4.0-IV0,Security=PLAINTEXT – org.apache.kafka.tools.MetadataQuorumCommandTest

**Review by lucasbru — APPROVED** [review]
LGTM, thanks!

**Comment by lucasbru** [comment]
@jlprat Fix for blocker KAFKA-16954 merged to 3.8 branch

**Comment by jlprat** [comment]
Thanks @lucasbru , closed the Jira issue as well.

**Pull request merged**
