### PR TITLE
HOTFIX: timeout issue in Remove thread

### PR DESCRIPTION
**Pull request by wcarlson5**
timeout is a duration not a point in time

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wcarlson5** [comment]
@cadonna @ableegoldman Can I get a look at this?

@vvcephei This will need to be picked to 2.8 as well

**Review by cadonna — APPROVED** [review]
Thanks for the quick fix!

Just one comment about the title. I guess "HOTFIX: " would be better than "Minor:".

For the rest, LGTM!

**Review by ableegoldman — APPROVED** [review]
Nice catch,  LGTM

**Comment by ableegoldman** [comment]
One unrelated flaky test failure ([KAFKA-12283](https://issues.apache.org/jira/browse/KAFKA-12283)): `connect.integration.RebalanceSourceConnectorsIntegrationTest.testMultipleWorkersRejoining`

**Comment by wcarlson5** [comment]
@ableegoldman Can we cherry pick to 2.8 as well?

**Comment by cadonna** [comment]
This decision should be taken by @vvcephei since he drives the 2.8 release.

**Comment by vvcephei** [comment]
Thanks @wcarlson5. Yes, please cherry-pick it to 2.8.

**Comment by ableegoldman** [comment]
Cherrypicked to 2.8 cc @vvcephei

**Pull request merged**
