### PR TITLE
KAFKA-18041: Update key for storing global consumer instance id for consistency

### PR DESCRIPTION
**Pull request by bbejeck**
This PR updates the key for storing the KIP-714 client instance id for the global consumer to follow a more consistent pattern of the other embedded Kafka Streams consumer clients. 

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
Thanks Bill. LGTM.

**Comment by mjsax** [comment]
I think we should only have this in 4.0, and not cherry-pick to older branches? Even if we don't have a public contract about the key format, it's kinda breaking change? Should we call it out in the upgrade docs (maybe extend this PR to update the docs right away -- otherwise it might slip)?

**Comment by bbejeck** [comment]
> Should we call it out in the upgrade docs (maybe extend this PR to update the docs right away -- otherwise it might slip)?

Yes good idea

**Comment by bbejeck** [comment]
@mjsax updated PR to include upgrade note about the change in key for the global consumer

**Comment by bbejeck** [comment]
Merged #17869 into trunk

**Pull request merged**
