### PR TITLE
MINOR: Make VerifiableProducer in system tests lookup security configuration dynamically instead of at construction.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@apovzner @granders Minor follow up from the previous patch for verifiable producer. I've kicked off tests here: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/409 and they look like they should finish up cleanly. The failed tests were for MM and were due to the fact that the MM test creates the verifiable producer immediately in the `__init__` method, before the security config is set on Kafka. This just makes the lookup dynamic so we don't have to wait to instantiate the service.

We may want to follow this approach more generally too -- this gets rid of the annoying pattern of having to instantiate all services in the test itself as long as the services like ZK and Kafka properly handle setting the security protocol after instantiation. I think we want this anyway because any test where we'd want to shutdown, modify settings, and start up with new security configs would require this as well.

**Comment by ewencp** [comment]
@gwenshap, @guozhangwang, @junrao If any of you can look, this needs another committer to review as well. Very trivial patch.

**Comment by granders** [comment]
@ewencp Makes sense - this looks good to me

**Comment by apovzner** [comment]
looks good to me too

**Comment by ijuma** [comment]
@gwenshap can you please review this?

**Pull request closed without merging**
