### PR TITLE
MINOR: Add entityType for metadata record definitions

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
As title

*Summary of testing strategy (including rationale)*
QA

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
Hello, @cmccabe PTAL.

**Review by chia7712 — COMMENTED** [review]
@dengziming thanks for this patch. I feel there are other missed entity type. for example:

1. https://github.com/apache/kafka/blob/trunk/clients/src/main/resources/common/message/DeleteTopicsRequest.json#L34
2. https://github.com/apache/kafka/blob/trunk/clients/src/main/resources/common/message/BeginQuorumEpochResponse.json#L33
3. https://github.com/apache/kafka/blob/trunk/clients/src/main/resources/common/message/BrokerHeartbeatRequest.json#L24
4. https://github.com/apache/kafka/blob/trunk/clients/src/main/resources/common/message/BrokerRegistrationRequest.json#L24
5. https://github.com/apache/kafka/blob/trunk/clients/src/main/resources/common/message/EndQuorumEpochRequest.json#L33

Could you fix them in this PR? thanks!

**Comment by dengziming** [comment]
@chia7712 Thank you for your comments, I checked all the files in `clients` module and fixed them, PTAL.

**Review by chia7712 — APPROVED** [review]
@dengziming thanks for this patch. LGTM

**Pull request merged**
