### PR TITLE
KAFKA-8403: Suppress needs a Materialized variant

### PR DESCRIPTION
**Pull request by dongjinleekr**
cc/ @vvcephei @mjsax

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
This is a public API change and would require a KIP. Btw: you should always assign the ticket to yourself before you start working on it.

**Comment by dongjinleekr** [comment]
@mjsax Thanks for the swift reply. Sure, I will submit the KIP and open the discussion thread soon!

**Comment by dongjinleekr** [comment]
Retest this please

**Comment by dongjinleekr** [comment]
retest this please

**Comment by mjsax** [comment]
Closing this PR due to inactivity on the KIP discussion.

**Pull request closed without merging**
