### PR TITLE
MINOR: remove commented out code and System.out.println

### PR DESCRIPTION
**Pull request by dguy**
Remove commented out code and System.out.println from KTableKTableJoinIntegrationTest

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang @mjsax @enothereska - i'm guessing the commented out code etc wasn't intentionally left?

**Comment by mjsax** [comment]
Yes. Thanks.

LGTM.

**Comment by enothereska** [comment]
LGTM

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk.

**Pull request closed without merging**
