### PR TITLE
MINOR: Add shebang to gradlewAll

### PR DESCRIPTION
**Pull request by akatona84**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by akatona84** [comment]
@ijuma could you approve this change pls?

Python based build executor died because of it:
```
OSError: [Errno 8] Exec format error: './gradlewAll'
```

**Comment by akatona84** [comment]
@granthenke , could you take a look as well? Thanks!

**Review by viktorsomogyi — APPROVED** [review]

**Comment by viktorsomogyi** [comment]
@ijuma would you please quickly review this small pr?

**Comment by akatona84** [comment]
@ijuma I've added the same shebang as gradlew has to gradlewAll. Could you check it pls? 🥺  🎅  🎄 😄

**Comment by akatona84** [comment]
@omkreddy , @ijuma 
could you take a look? pretty small change, pretty pls :)

**Comment by viktorsomogyi** [comment]
@mimaison would you please check this quickly? (I think the test failures are unrelated as this only affects the command line)

**Review by mimaison — APPROVED** [review]
LGTM

**Pull request merged**
