### PR TITLE
[KAFKA-7033] Modify AbstractOptions's timeoutMs as Long type

### PR DESCRIPTION
**Pull request by darionyaphet**
[KAFKA-7033 | Modify AbstractOptions's timeoutMs as Long type](https://issues.apache.org/jira/browse/KAFKA-7033)

Currently AbstractOptions's timeoutMs is Integer and using Long to represent timeout Millisecond maybe better .

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by stanislavkozlovski** [comment]
2147483647 (the max value of an Integer) milliseconds are equivalent to 24.85 days. This is beyond a practical maximum value in my opinion - I believe an integer is enough

**Comment by darionyaphet** [comment]
Hi @Enether actually timeout ms value using Long maybe looks better ?

**Comment by stanislavkozlovski** [comment]
Why do you think so?

**Comment by darionyaphet** [comment]
when we calculation the timeout point, use current time + timeout interval , and current time is Long .

**Comment by OneCricketeer** [comment]
> and current time is Long

So? The point trying to be made is that do you really expect your operations to be longer than 24.85 days?

**Pull request closed without merging**
