### PR TITLE
Bump dev version to 2.6.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by rhauch**
As part of the 2.6.0 release, we need to bump the dev version of the `2.6` branch to 2.6.1.

### CODE REVIEW

**Comment by rhauch** [comment]
Successful build on JDK 11. JDK 8 build timed out, and several test failures on JDK 14.

Retest this please.

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by rhauch** [comment]
retest this please

**Comment by rhauch** [comment]
The JDK 11 and 14 builds didn't seem to run (IIUC reported on other branches and PRs, too). However, none of these are really impacted by this change of the version number.

**Pull request merged**
