### PR TITLE
MINOR: add KStream merge operator

### PR DESCRIPTION
**Pull request by ymatsuda**
@guozhangwang 

Added KStreamBuilder.merge(KStream...).

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM.

**Comment by deinspanjer** [comment]
I am trying to use this method and find it a bit ugly because it expects a vararg of a generic type.
This means if you have a collection of KStreams you want to feed to it, your only option is to cast the return of a call to collection.toArray() and add an @SuppressWarnings("unchecked") annotation:

`KStream<MyKey, MessageValue<? extends MyValue> merged = builder.merge( ( KStream<MyKey, MessageValue<? extends MyValue> [] ) collection.toArray() );`

It would be a lot simpler if there was a version of merge that just accepted Collection<KStream>.

**Comment by guozhangwang** [comment]
@deinspanjer Hmm, how about using this function:

```
<T> T[] toArray(T[] a);
```

More specifically, you can call `collection.toArray(new KStream<..>[](collection.size()))`. This may be still awkward but maintains the strong typing in the DSL.

**Comment by deinspanjer** [comment]
When I tried to use `new KStream<...>[0]`, I get a Java error about trying to create a generic array.
I'm not familiar with the syntax you list above.  Did you mean `new KStream<...>[collection.size()]`?  If so, then it throws that generic array error.

**Comment by guozhangwang** [comment]
Hmm, not sure why you get this error. You can take a look at this PR I had, in which I used the same function for generic typed arrays (line 205):

https://github.com/apache/kafka/pull/2320/files#diff-9206771d07b1c049d5fb68f854e40e86

**Pull request closed without merging**
