### PR TITLE
Rename streams tutorial and quickstart

### PR DESCRIPTION
**Pull request by joel-hamill**
Changed these topic titles:
- Write your own Streams Applications -> Tutorial: Write a Streams Application
- Play with a Streams Application -> Run the Streams Demo Application

### CODE REVIEW

**Comment by joel-hamill** [comment]
ping @miguno

**Comment by joel-hamill** [comment]
ping @guozhangwang

**Comment by guozhangwang** [comment]
LGTM. cc @miguno

**Review by miguno — APPROVED** [review]

**Comment by guozhangwang** [comment]
Merged to trunk, and cherry-picked to 1.0

**Pull request closed without merging**
