### PR TITLE
KAFKA-2643: Run mirror maker ducktape tests with SSL and SASL

### PR DESCRIPTION
**Pull request by rajinisivaram**
Run tests with SSL, SASL_PLAINTEXT and SASL_SSL. Same security protocol is used for source and target Kafka.

### CODE REVIEW

**Comment by rajinisivaram** [comment]
Mirrormaker tests passed with all protocols - http://jenkins.confluent.io/job/kafka_system_tests_branch_builder/211/

**Comment by ijuma** [comment]
Thanks @rajinisivaram. @granders, can you please review this?

**Comment by granders** [comment]
Thanks @rajinisivaram, this looks good to me

**Comment by benstopford** [comment]
LGTM.

**Comment by ijuma** [comment]
@gwenshap @junrao Any of you available to review and potentially merge this? @granders and @benstopford reviewed it 6 days ago.

**Comment by gwenshap** [comment]
sorry for the delay! checking.

**Comment by ijuma** [comment]
@gwenshap no worries about the delay, thanks for checking!

**Pull request closed without merging**
