### PR TITLE
KAFKA-9477 Document RoundRobinAssignor as an option for partition.assignment.strategy

### PR DESCRIPTION
**Pull request by arodoni**
JIRA: https://issues.apache.org/jira/browse/KAFKA-9477

Summary: Add RoundRobinAssignor as an option to consumer configs

@joel-hamill

### CODE REVIEW

**Comment by mjsax** [comment]
\cc @hachikuji @cmccabe For review.

**Comment by cmccabe** [comment]
LGTM

**Comment by cmccabe** [comment]
Can you please add line breaks to avoid going over 100 characters in each line?  Looks good aside from that.

**Comment by arodoni** [comment]
@cmccabe @hachikuji Could you please review the latest changes, approve, and merge them? Thank you.

**Comment by cmccabe** [comment]
LGTM

**Comment by chia7712** [comment]
@cmccabe 

seems this patch causes the checkstyle error.

```
> Task :clients:checkstyleMain
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:106:109: '+' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:107:72: '+' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:108:75: '+' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:109:77: '+' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:110:73: '+' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:112:80: '+' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:113:77: '+' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:115:80: '+' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] C:\Users\chia7712\kafka\clients\src\main\java\org\apache\kafka\clients\consumer\ConsumerConfig.java:116:74: '+' is not preceded with whitespace. [WhitespaceAround]
```

**Comment by mjsax** [comment]
The jenkins build should have detected this -- did we merge this even if the build failed?

**Pull request merged**
