### PR TITLE
KAFKA-6481: Improving performance of the function ControllerChannelManager.addUpd…

### PR DESCRIPTION
**Pull request by gitlw**
…ateMetadataRequestForBrokers

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gitlw** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/266/

**Comment by gitlw** [comment]
@onurkaraman Can you please review this patch? The failed tests above does not seem to be related to my change. I've run "gradle testAll" locally, and all tests passed successfully.

**Comment by gitlw** [comment]
@becketqin Can you please take a look at this PR? Thanks.

**Comment by junrao** [comment]
@gitlw : Thanks for the patch. LGTM

**Pull request closed without merging**
