### PR TITLE
KAFKA-4269: Follow up for 0.10.1 branch -update topic subscriptions for regex 

### PR DESCRIPTION
**Pull request by bbejeck**

### CODE REVIEW

**Comment by bbejeck** [comment]
@guozhangwang  follow-up PR posted

**Comment by guozhangwang** [comment]
LGTM. Merged to 0.10.1.

**Comment by guozhangwang** [comment]
@bbejeck could you manually close this PR since it cannot be auto-closed for non-trunk comparisons?

**Comment by bbejeck** [comment]
Manually closing this PR since it cannot be auto-closed for non-trunk comparisons.

/cc @guozhangwang

**Pull request closed without merging**
