### PR TITLE
KAFKA-5838. Speed up running system tests in docker a bit with better…

### PR DESCRIPTION
**Pull request by cmccabe**
… sshd options

### CODE REVIEW

**Review by norwood — APPROVED** [review]
😍 ⏩

**Comment by ijuma** [comment]
Thanks for the PR. Should we do the same in `vagrant/base.sh`?

**Comment by ewencp** [comment]
Yeah, unfortunately these types of changes need to be duplicated across both configs.

Also, we should have a test run (or 5) of the full suite. Last time we made ssh faster a bunch of tests broke since it exposed various race conditions in the tests...

**Comment by cmccabe** [comment]
> Thanks for the PR. Should we do the same in vagrant/base.sh?

Fixed, thanks

**Comment by cmccabe** [comment]
> Also, we should have a test run (or 5) of the full suite. Last time we made ssh faster a bunch of tests broke since it exposed various race conditions in the tests...

I'll run the full system test suite.

**Comment by ijuma** [comment]
Seems like we lost the vagrant/base.sh changes.

**Pull request closed without merging**
