### PR TITLE
KAFKA-9244: Update FK reference should unsubscribe old FK

### PR DESCRIPTION
**Pull request by mjsax**
Call for review @vvcephei @bellemare

### CODE REVIEW

**Review by bellemare — APPROVED** [review]
Wow. Thanks. Excellent catch!

**Comment by bellemare** [comment]
@mjsax Is this going to go out with 2.4?

**Comment by ijuma** [comment]
Is this a regression?

**Comment by ijuma** [comment]
Is this a regression?

**Comment by vvcephei** [comment]
Looks right to me. Thanks for the fix and the test, @mjsax!

There was some kind of gradle exception in the build. 

Retest this, please.

**Review by vvcephei — APPROVED** [review]

**Comment by mjsax** [comment]
@ijuma Foreign key join is a newly added feature in 2.4.0 -- hence, it's technically not a regression. However, we would ship a broker feature if we don't include this fix in 2.4.0 because there is no workaround. Thoughts?

While investigating this issue, I also discovered another bug in FK join operator: https://issues.apache.org/jira/browse/KAFKA-9248 -- However, for this other bug a workaround exists and thus it's not critical to get a fix into 2.4.0.

**Comment by ijuma** [comment]
Can we get this merged today so that @omkreddy can release a new RC tomorrow?

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.4`. \cc @omkreddy

**Pull request merged**
