### PR TITLE
MINOR: Fix ambiguous log message in RecordCollector

### PR DESCRIPTION
**Pull request by kawamuray**
When producing fails in Kafka Streams, it gives an error like below:

```
Error sending record: null
```

by this line: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/processor/internals/RecordCollector.java#L59

This isn't not making sense because of:
- Practically metadata is always null when exception != null : https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/internals/RecordBatch.java#L107-L109
- It's quite misleading as we would interpret it like "Kafka Streams attempted to send 'null' as a record" which isn't in fact

As I find a PR #873  as the origin of the above line I changed it to instantiate callback on each send in order to log destination topic at least.

### CODE REVIEW

**Comment by kawamuray** [comment]
@guozhangwang PTAL.

**Comment by guozhangwang** [comment]
This is a good find @kawamuray . As for its fix, instead of creating a callback object each time and potentially creating lots of short-lived objects (some may move to old-gen if it last too long?), I think we'd better fix 

https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/internals/RecordBatch.java#L107-L109

by returning the RecordMetadata still if `exception != null` but without the timestamp and offset values. cc @ijuma as it touches the producer internals.

**Comment by ijuma** [comment]
@guozhangwang that seems consistent with https://github.com/apache/kafka/pull/1015/files#diff-0436bd6994adccd181bfe6d02555cbc2R781
It's probably a good idea to include an upgrade note as some people may assume that if `metadata` is not `null`, then the `exception` is `null`.

**Comment by guozhangwang** [comment]
Thanks for the pointer @ijuma .

**Comment by kawamuray** [comment]
>  creating lots of short-lived objects (some may move to old-gen if it last too long?),

I'd say this is relatively very small cost that all `KafkaProducer` users should accept.
In terms of short-lived objects there are already lots of objects created during producing record, which makes a callback object relatively smaller than them.
Indeed they could live much longer than we expect during potentially long `linger.ms` or maybe during retrying due to the broker failure but still we can't say that instantiating callback on each send could be the point of optimization to reduce GC pressure I guess.

> by returning the RecordMetadata still if exception != null but without the timestamp and offset values. 

I agree with that this could be a better interface but since the current behavior was there even as of 0.8.X, I have concern to change it now.
It is not declared as an interface signature explicitly but I'd say most users implicitly expecting `metadata` is null when producing failed.
This change breaks behavior compatibility if a user wrote a code like below, which shouldn't be considered as solved just by leaving an upgrade note.

``` java
producer.send(..., (metadata, exception) -> {
    if (metadata == null) {
        // Error handling
    }
});
```

So my opinion is, even though we want to make that change eventually, that should be done with the next major version release(0.11.X).

Thoughts?

**Comment by guozhangwang** [comment]
@kawamuray Fair enough. Let's keep this API as is.

BTW could you close / re-open the PR to re-trigger another Jenkins job? The failure case is related to an issue which we believe already resolved, so just trying to double check.

**Comment by kawamuray** [comment]
Done! Thanks for review.

**Comment by guozhangwang** [comment]
Merged to both trunk and 0.10.0.

**Pull request closed without merging**
