### PR TITLE
MINOR: Add Jenkinsfile to 2.2

### PR DESCRIPTION
**Pull request by vvcephei**
Add a Jenkinsfile for the 2.2 branch so PRs can be built

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
See also #9471 and #9472 

@ijuma @jolshan @mumrah , are any of you able to review this as well?

**Review by jolshan — APPROVED** [review]
Correct scala and java versions are being used. LGTM

**Review by omkreddy — APPROVED** [review]
@vvcephei  thanks for the PR. LGTM

**Comment by vvcephei** [comment]
Thanks for the reviews!

**Pull request merged**
