### PR TITLE
HOTFIX: Set version of jgit to avoid unsupported version error

### PR DESCRIPTION
**Pull request by cadonna**
A new version of JGit that is used by grgit that is used by gradle
causes the following error:

org/eclipse/jgit/storage/file/FileRepositoryBuilder has been compiled
by a more recent version of the Java Runtime (class file version 55.0),
this version of the Java Runtime only recognizes class file versions
up to 52.0

The reason is that version 6.0.0.202111291000-r of JGrit was compiled
with a newer Java version than Java 8, probably Java 11.

Explicitly setting the version of JGrit in gradle to 5.12.0.202106070339-r fixes
the issue.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by dajac — APPROVED** [review]
LGTM

**Comment by cadonna** [comment]
Grgit issue: https://github.com/ajoberstar/grgit/issues/341

**Comment by ijuma** [comment]
An alternative is to set the jgit version explicitly. Something like:

```java
    // Override jgit dependency used by grgit and spotless as we appear to auto resolve to 
    // 5.13.0.202109080827-r and the latest version requires java 9.
    // Requires force=true to be used in spotless as reported by ./gradlew buildEnvironment.
    classpath("org.eclipse.jgit:org.eclipse.jgit:$versions.jgit") { force = true }
```

**Review by AlexanderStohr — APPROVED** [review]

**Review by AlexanderStohr — APPROVED** [review]

**Review by mumrah — APPROVED** [review]
Applied this locally and tested it out. Worked great, thanks @cadonna.

It is a little odd that this happened in my environment without my pulling any new changes. Was that the case for you as well? Our grgit and spotless versions are pinned, so we shouldn't be pulling any new dependencies. 🤔 

Either way, this change LGTM to unblock trunk

**Comment by cadonna** [comment]
@mumrah This issue was caused because grgit 4.1.0 uses the latest JGit version and not a pinned one. For spotless it might be similar.
I noticed this issue when a couple of our Jenkins job failed since they build Kafka from scratch. But I also know that some colleagues had build issues without changing anything.

**Comment by cadonna** [comment]
The test failures are unrelated. The PR for Java 8 which showed the issue passed.

**Comment by cadonna** [comment]
Cherry-picked to 3.1

**Comment by cadonna** [comment]
Cherry-picked to 3.0

**Pull request merged**
