### PR TITLE
MINOR: Fix incorrect versions in ConsumerGroupDescribeResponse schema

### PR DESCRIPTION
**Pull request by antonagestam**
See discussion in https://github.com/apache/kafka/pull/14124#discussion_r1320822476

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kirktrue** [comment]
Thanks for the PR @antonagestam!

Does it make sense (or is it even possible) to write a test case that verifies the correctness of this change?

Thanks!

**Comment by antonagestam** [comment]
@kirktrue [I was pondering that as well](https://github.com/apache/kafka/pull/14124#discussion_r1336283242). It seems attractive because it's certainly possible to automate, however I'm not sure how common mistakes like this are.

Would that make sense as a follow-up task? I don't know how eager I would be to contribute that myself, to be completely honest about my intentions.

**Comment by antonagestam** [comment]
@kirktrue Related to that, I think it'd make sense to enforce this as well: https://github.com/apache/kafka/pull/13680, as it allows slightly less parser complexity. Since we're talking about linting schemas that is :)

**Comment by dajac** [comment]
Good find and thanks for the PR! I am not sure how we could write an unit test for this one. However, I think that we should at minimum improve the generator to verify this. It should not possible to use a version for a field which is not in the main version range. I think that we could handle this [here](https://github.com/apache/kafka/blob/trunk/generator/src/main/java/org/apache/kafka/message/StructSpec.java#L39). @antonagestam Would you be interested by trying to do this? We could do this in a separate PR.

**Review by dajac — APPROVED** [review]
LGTM, good catch!

**Comment by dajac** [comment]
I have opened https://issues.apache.org/jira/browse/KAFKA-15518 to improve the generator for this particular case.

**Comment by antonagestam** [comment]
@dajac Thank you for merging this. As already hinted at, I don't think it's too likely I'll get around to looking into implementing some enforcing mechanism for this.

**Pull request merged**
