### PR TITLE
MINOR: Upgrade Jackson to 2.9.6

### PR DESCRIPTION
**Pull request by ijuma**
Upgrade strongly recommended due to security fixes for
`jackson-databind` (same as ones in 2.7.9.4 and 2.8.11.2).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
LGTM

**Comment by mjsax** [comment]
Should this be cherry-picked to `2.0`, too?

**Comment by ijuma** [comment]
Yes, I will cherry-pick to every branch using Jackson 2.9.x.

**Comment by ijuma** [comment]
I have merged to trunk and cherry-picked to 2.0, 1.1 and 1.0.

**Pull request merged**
