### PR TITLE
MINOR: Remove redundant error log in ChannelBuilder

### PR DESCRIPTION
**Pull request by RivenSun2**
Modify the error log level in SaslChannelBuilder

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by RivenSun2** [comment]
The two exceptions thrown in the `SaslClientAuthenticator.createSaslClient()` method, whether the exception information can be distinguished.
Because when the JDK prints the stack, there will be an operation like "common frames omitted", and sometimes I can't tell which line of code the exception is thrown from.
`SaslServerAuthenticator.createSaslServer()` method is the same as above.

```
2022-08-18 15:09:55.080[][WARN][kafka-producer-network-thread | producer-2][NetworkClient][Producer clientId=producer-2] Bootstrap broker *.*.*.*:9889 (id: -3 rack: null) disconnected
2022-08-18 15:09:55.081[][WARN][asyncmq-11-topic testTopic | group testGroup-pull-0][NetworkClient][Consumer clientId=consumer-testTopic_testGroup-1, groupId=testGroup] Error connecting to node *.*.*.*:9889 (id: -1 rack: null)
java.io.IOException: Channel could not be created for socket java.nio.channels.SocketChannel[closed]
        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:348)
        at org.apache.kafka.common.network.Selector.registerChannel(Selector.java:329)
        at org.apache.kafka.common.network.Selector.connect(Selector.java:256)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:981)
        at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1152)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1040)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:549)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:227)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:258)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:483)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1262)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1231)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
        at us.zoom.mq.client.impl.kafka.ConsumerClient.poll(ConsumerClient.java:192)
        at us.zoom.mq.client.worker.PullWorker.run(PullWorker.java:149)
        at us.zoom.commons.threadpool.ZoomRunnable.run(ZoomRunnable.java:61)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
        at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:240)
        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:338)
        ... 22 common frames omitted
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to create SaslClient with mechanism PLAIN
```

**Comment by RivenSun2** [comment]
Hi @showuon  could you help review this PR?
Thanks.

**Review by showuon — COMMENTED** [review]
@RivenSun2 , thanks for the PR. I agree it is not good to print out 2 identical exceptions. I'm thinking we should remove this `info`/`warn` log. That is, the exception in `buildChannel` will be caught and print out the error log with stack trace here in the end (like what you saw in your log):
https://github.com/apache/kafka/blob/150fd5b0b18c4761d8f7d7ba9a480aa9f622024f/clients/src/main/java/org/apache/kafka/common/network/Selector.java#L337-L348

So, why can't we remove the line here:
`log.info("Failed to create channel due to ", e);`
WDYT?

It also exists in plaintextChannelBuilder and SSLChannelBuilder. Thanks.

**Comment by RivenSun2** [comment]
Hi @showuon  Thanks for your reply.
I agree with you that the error stack does get printed in the upper layer. The log printing here is a little redundant.
If you think that the two similar lines I mentioned above can be optimized (distinguish the details of the exception thrown in the two places), I can resubmit a PR to improve.
Thanks.

**Review by showuon — APPROVED** [review]
LGTM!

**Comment by showuon** [comment]
> If you think that the two similar lines I mentioned above can be optimized (distinguish the details of the exception thrown in the two places), I can resubmit a PR to improve.

I think that's fine. This PR should already improve the log output a lot.

Let's wait for the jenkins build. Thanks.

**Comment by RivenSun2** [comment]
Hi @showuon   Can this PR be merged into the trunk?
Thanks.

**Comment by showuon** [comment]
Thanks for the reminder!
Failed tests are unrelated:
```
    Build / JDK 11 and Scala 2.13 / kafka.network.DynamicConnectionQuotaTest.testDynamicListenerConnectionCreationRateQuota()
    Build / JDK 8 and Scala 2.12 / kafka.network.ConnectionQuotasTest.testListenerConnectionRateLimitWhenActualRateAboveLimit()
```

**Pull request merged**
