### PR TITLE
KAFKA-8091; Use commitSync to check connection failure in listener update test

### PR DESCRIPTION
**Pull request by rajinisivaram**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rajinisivaram** [comment]
Builds passed, but rerunning once more since this was a flaky test

**Comment by rajinisivaram** [comment]
retest this please

**Review by omkreddy — APPROVED** [review]
Thanks for the PR. LGTM

**Comment by rajinisivaram** [comment]
@omkreddy Thanks for the review, merging to trunk and 2.2. Test failures are unrelated.

**Pull request merged**
