### PR TITLE
KAFKA-17399: Apply LambdaValidator to code base

### PR DESCRIPTION
**Pull request by xijiu**
There are many validator impl used to offer the custom `toString`. However, the impl is a bit ugly so we should consider decorating them by `LambdaValidator`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@xijiu could you please fix the build error?

**Comment by xijiu** [comment]
> @xijiu could you please fix the build error?

@chia7712   It's my fault, I should add the `@SuppressWarnings("unchecked")` annotation when I perform forced type conversion, like this:
```
@SuppressWarnings("unchecked")
final List<String> aliases = (List<String>) value;
```
I have fiexd it, PTAL

**Comment by chia7712** [comment]
@xijiu Could you please rebase code?

**Comment by xijiu** [comment]
> @xijiu Could you please rebase code?

@chia7712 
Yeap, I have already rebased the branch.

**Pull request merged**
