### PR TITLE
MINOR: Finished exposing the broker config

### PR DESCRIPTION
**Pull request by enothereska**
This was left over from KIP-104. Thanks to @ijuma for pointing out.

### CODE REVIEW

**Comment by enothereska** [comment]
@ijuma have a look when you can, thanks.

**Comment by ijuma** [comment]
Thanks @enothereska, can we add a simple unit test? LGTM otherwise.

**Comment by enothereska** [comment]
@ijuma I added a simple check, still thinking of what more to add at this level since there is testing at the sensor level.

**Comment by enothereska** [comment]
Known failure being worked on: org.apache.kafka.streams.integration.QueryableStateIntegrationTest.shouldNotMakeStoreAvailableUntilAllStoresAvailable[1]

**Comment by ijuma** [comment]
@enothereska, the test I had in mind is to verify that `MetricConfig` had the right recording level if the broker config is set. That is what has changed in this PR. Before this PR, the information was not propagated to that class. I agree that the sensor tests are the right place to verify that the recording level is used in the right way.

**Comment by enothereska** [comment]
Thanks @ijuma I added a test as you suggested.

**Comment by enothereska** [comment]
Known issue `pure virtual method called` not related to PR.
Known streams issues not related to PR:
`org.apache.kafka.streams.integration.KStreamRepartitionJoinTest.shouldCorrectlyRepartitionOnJoinOperations[0]`
`org.apache.kafka.streams.integration.KStreamRepartitionJoinTest.shouldCorrectlyRepartitionOnJoinOperations[1]`
`org.apache.kafka.streams.integration.QueryableStateIntegrationTest.queryOnRebalance[0]`

**Comment by enothereska** [comment]
Needs to go to 0.10.2 as well please.

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM. Merging to trunk and 0.10.2 (as it's a follow-up to KIP-105).

**Comment by ijuma** [comment]
For the record, I did some minor style and test clean-ups before merging.

**Comment by enothereska** [comment]
Thanks @ijuma

**Pull request closed without merging**
