### PR TITLE
KAFKA-6070: add ipaddress and enum34 dependencies to docker image

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Review by aayars — APPROVED** [review]

**Review by ewencp — APPROVED** [review]
Not really sure why these pop up but it looks fine to me if we need them.

Is this only for trunk? And it sounded like it happened when developing a specific test, do we know why the requirements seem to have changed?

**Comment by ijuma** [comment]
@lindong28 one of the failures in this PR seem to be related to the JBOD work:

```text
kafka.common.AdminCommandFailedException: Failed to alter dir for my-topic-0-100
	at kafka.admin.ReassignPartitionsCommand.$anonfun$alterReplicaLogDirsIgnoreReplicaNotAvailable$1(ReassignPartitionsCommand.scala:568)
```

Can you please file a JIRA and take a look? Thanks!

**Comment by lindong28** [comment]
@ijuma Sure. I opened https://issues.apache.org/jira/browse/KAFKA-6078.

According to the stack trace, the test failed due to UnknownServerException. I am not able to look further into this because we don't have the actual exception on the server. Do you see repeated failure of this test in other pull request? I would like to gauge how likely it is to reproduce this failure.

I think this test may have failed due to non-JBDO issues since shouldExecuteThrottledReassignment, which does not touch the JBDO logic, also failed.

**Comment by ijuma** [comment]
@lindong28, if you can't reproduce it locally, we can wait and see if it happens again. Thanks for filing the JIRA.

**Comment by cmccabe** [comment]
> Is this only for trunk? And it sounded like it happened when developing a specific test, do we know why the requirements seem to have changed?

I think it makes sense to backport this to the 1.x branch as well.

It's a transitive requirement of pycrypto.  I don't know why this issue came up now and not earlier.  My best guess is that something changed in the Ubuntu base image so that whatever was providing it accidentally earlier no longer is.  We do an "apt-get update" in the Dockerfile, so what's there can change from time to time.

**Comment by cmccabe** [comment]
retest this please

**Comment by cmccabe** [comment]
retest this please

**Comment by ijuma** [comment]
Merging to trunk and 1.0 branches.

**Pull request closed without merging**
