### PR TITLE
MINOR: Improve Join integration test coverage, PART II

### PR DESCRIPTION
**Pull request by guozhangwang**
1. Replaced KStreamKTableJoinIntegrationTest with the abstract based StreamTableJoinIntegrationTest. Added details on per-step verifications.
2. Minor renaming on GlobalKTableIntegrationTest.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@mjsax @bbejeck

**Review by dguy — APPROVED** [review]
Thanks @guozhangwang, LGTM

**Review by bbejeck — APPROVED** [review]
thanks @guozhangwang LGTM

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
