### PR TITLE
HOTFIX: Fix compilation error for JDK 21 caused by this-escape warning

### PR DESCRIPTION
**Pull request by linzihao1999**
Fix compilation error for JDK 21 caused by this-escape warning.
Related to #14708

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by linzihao1999** [comment]
@dajac Hi, the CI build is passed.

**Comment by dajac** [comment]
Thanks for the patch. I actually don’t know if making those classes final is fine. We need @ableegoldman to weight in here.

**Comment by ijuma** [comment]
We should ideally only make the relevant methods final, did that not work for some reason?

**Comment by linzihao1999** [comment]
Yes, making the relevant methods final is better, and pass the CI build.

**Review by dajac — APPROVED** [review]
LGTM, thanks!

**Comment by dajac** [comment]
I’ll merge it to unblock other builds. @ableegoldman I let you double check it.

**Pull request merged**
