### PR TITLE
MINOR: Fix consumer and producer to actually support metrics recording level

### PR DESCRIPTION
**Pull request by ijuma**
Also add tests and a few clean-ups.

### CODE REVIEW

**Comment by ijuma** [comment]
@enothereska, it looks like this was an oversight?

**Comment by enothereska** [comment]
Good catch @ijuma I forgot to implement this. LGTM

**Comment by ijuma** [comment]
Review by @hachikuji.

**Comment by ijuma** [comment]
Rebased and fixed conflicts.

**Comment by ijuma** [comment]
@rajinisivaram maybe you can review this one? It should be straightforward.

**Comment by hachikuji** [comment]
@ijuma Sorry for the delay. Looking now.

**Review by hachikuji — APPROVED** [review]
Thanks for the patch. LGTM

**Pull request closed without merging**
