### PR TITLE
MINOR: add timeouts to streams integration tests

### PR DESCRIPTION
**Pull request by cmccabe**
Add timeouts to streams integration tests. Hopefully this will fix the Jenkins hangs we have been
seeing.

### CODE REVIEW

**Comment by divijvaidya** [comment]
How about extending all our tests with "AbstractKafkaUnitTest" (or something similar) and adding this timeout rule over there? I can see other use cases where such a base class would be helpful such as adding info level log messages before/after each test etc.

Similarly  adding it to `IntegrationTestHarness` for integration tests in the core code?

**Comment by divijvaidya** [comment]
Another suggestion: We can potentially use `@Timeout` directly annotated on the class just like we do in `QuorumControllerTest`

**Comment by cmccabe** [comment]
> How about extending all our tests with "AbstractKafkaUnitTest" (or something similar) and adding this timeout rule over there? I can see other use cases where such a base class would be helpful such as adding info level log messages before/after each test etc. Similarly adding it to IntegrationTestHarness for integration tests in the core code?

Test inheritance is an anti-pattern because it tightly couples the implementation of many unrelated things. We see this a lot .. changing one method in `QuorumTestHarness` can lead to chaos since many things inherit from it. We certainly would not want to have to change the inheritance hierachy to set a different timeout, for example.

> Another suggestion: We can potentially use @Timeout directly annotated on the class just like we do in QuorumControllerTest

We cannot use `@Timeout` because streams is still using an older version of JUnit that does not support it

**Review by mumrah — APPROVED** [review]
Looks fine to me, @cmccabe. Is there a JIRA to track updating streams to use the newer JUnit? Then we could use the annotation as @divijvaidya suggests.

**Comment by cmccabe** [comment]
> Is there a JIRA to track updating streams to use the newer JUnit? Then we could use the annotation as @divijvaidya suggests

https://issues.apache.org/jira/browse/KAFKA-7342

**Pull request merged**
