### PR TITLE
HOTFIX: fix CI compile error

### PR DESCRIPTION
**Pull request by TaiJuWu**
*More detailed description of your change,
The Ci error show [here](https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-16525/1/pipeline)

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by C0urante** [comment]
@apoorvmittal10 @omkreddy @dajac @rreddy-22 PTAL

**Review by chia7712 — COMMENTED** [review]
@TaiJuWu thanks for this quick fix. Please adjust the indent

**Comment by TaiJuWu** [comment]
> @TaiJuWu thanks for this quick fix. Please adjust the indent

Done.

**Review by chia7712 — APPROVED** [review]
LGTM and `SimpleAssignorTest` pass on my local

**Review by C0urante — APPROVED** [review]

**Comment by C0urante** [comment]
The `SimpleAssignorTest` suite has passed in CI for both applicable builds (see logs) and compilation has passed for all 4 builds. Merging to unblock building on trunk; we can follow up with a new PR if other changes are necessary.

**Comment by apoorvmittal10** [comment]
Thanks for the fix @TaiJuWu @chia7712 @C0urante. Parallel merges and the build passed on other PRs.

**Comment by showuon** [comment]
Thanks for the fix fix @TaiJuWu ! Nice job!

**Pull request merged**
