### PR TITLE
KAFKA-5748 Fix console producer to set timestamp and partition

### PR DESCRIPTION
**Pull request by rancp**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6857/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6843/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
Thanks for the PR. In Kafka, we target trunk and the committer can cherry-pick to older branches via the merge script. Also, maybe we want to print the headers too?

**Comment by rancp** [comment]
Sounds good, let me make the changes

**Pull request closed without merging**
