### PR TITLE
Add s390x build stage

### PR DESCRIPTION
**Pull request by Nayana-ibm**
Adding s390x build stage. Uses Jdk11 and scala 2.13

### CODE REVIEW

**Comment by mimaison** [comment]
Thanks @Nayana-ibm for the PR. Changes to Jenkinsfile are only applied if they are from a committer. I'll open another PR with your changes and see if it works.

**Comment by mimaison** [comment]
I opened https://github.com/apache/kafka/pull/11929

**Comment by Nayana-ibm** [comment]
Keeping this PR open for any new updates

**Comment by Nayana-ibm** [comment]
Tracking through https://github.com/apache/kafka/pull/15644
Closing this.

**Pull request closed without merging**
