### PR TITLE
MINOR: add warning when offset topic is not replicated properly

### PR DESCRIPTION
**Pull request by enothereska**
Added a warning, otherwise this problem is hard to debug if you haven't followed the latest KIP closely.

### CODE REVIEW

**Comment by enothereska** [comment]
@ijuma @ewencp please have a look, thanks.
Apologies for previous trunk merge, was a mistake a few days ago.

**Comment by omkreddy** [comment]
+1

**Comment by enothereska** [comment]
@ijuma I changed message type to error and adjusted message.

**Review by ijuma — APPROVED** [review]
Thanks, LGTM.

**Pull request closed without merging**
