### PR TITLE
MINOR: Check null keys in KTableSource

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
Review by @enothereska @mjsax @dguy

**Comment by dguy** [comment]
LGTM

**Comment by mjsax** [comment]
+1

**Comment by guozhangwang** [comment]
Jenkins failure are transient and tracked in other JIRA: https://issues.apache.org/jira/browse/KAFKA-3865

**Comment by guozhangwang** [comment]
Merged to both trunk and 0.10.0.

**Pull request closed without merging**
