### PR TITLE
KAFKA-16064: Improve ControllerApisTest

### PR DESCRIPTION
**Pull request by wernerdv**
Refactoring ControllerApiTest to close an instance of ControllerApis in a tearDown method.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wernerdv** [comment]
The tests passed
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-15091/1/testReport/kafka.server/ControllerApisTest/

**Review by divijvaidya — APPROVED** [review]
Looks good!

**Comment by divijvaidya** [comment]
I have verified that the test is successful in CI: https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-15091/1/testReport/kafka.server/ControllerApisTest/

**Comment by divijvaidya** [comment]
@wernerdv I observed that this is your firs contribution to Apache Kafka. Congratulations! Hopefully, first of many more to come.

**Comment by wernerdv** [comment]
@divijvaidya thank you very much. This is only the beginning :)

**Pull request merged**
