### PR TITLE
KAFKA-3121: Remove aggregatorSupplier and add Reduce functions

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@ymatsuda

**Comment by guozhangwang** [comment]
This only contains the first component of KAFKA-3121, the rest will be discussed / finished after KAFKA-3066.

**Comment by guozhangwang** [comment]
Unit tests passed locally.

**Comment by ymatsuda** [comment]
lgtm

**Pull request closed without merging**
