### PR TITLE
MINOR: disable flaky Streams EOS integration tests

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by hachikuji** [comment]
LGTM

**Comment by mjsax** [comment]
I am just running locally to test a potential fix. If if does not fail within 100 runs it seems to be stable. Usually it fails about 1 out of 30 runs. Should take about 1h to verify.

**Comment by hachikuji** [comment]
@mjsax Thanks. I'll hold off merging for now.

**Comment by mjsax** [comment]
Closing this as https://github.com/apache/kafka/pull/3273 got merged.

**Review by guozhangwang — APPROVED** [review]
Merged to trunk and 0.11.0.

**Pull request closed without merging**
