### PR TITLE
KAFKA-2797: Only run rat when in the .git repository since it require s the .gitignore to generate the list of files to ignore

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by fpj** [comment]
@ewencp this doesn't quite work for me, check this out:

```
./gradlew build
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.8/userguide/gradle_daemon.html.
Building project 'core' with Scala version 2.10.5
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:rat FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':rat'.
> No value has been specified for property 'excludes'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.607 secs
```

**Comment by ewencp** [comment]
@fpj Sorry, I pushed an update when I found the same problem. Did you try the newest version? 

I ended up testing by using git archive to generate a separate tar file without the .git directory and in both the git and tar versions ran `gradlew test`. The .git one properly ran rat (which you can see in the log) and the tar one just skipped it and ran all the tests successfully.

**Comment by fpj** [comment]
@ewencp I took the RC artifact and applied your changes to test it. Running `gradle` works, but not `./gradlew build` or `./gradlew test`. 

I only see one commit here: 79c6cac. How many commits should I be seeing in this PR?

**Comment by fpj** [comment]
@ewencp OK, I got it, it works for me now. +1, LGTM.

**Pull request closed without merging**
