### PR TITLE
KAFKA-16082 Avoid resuming future replica if current replica is in the same directory

### PR DESCRIPTION
**Pull request by gaurav-narula**
Cherry picks #15136 to 3.7 branch. Depends on #15776 being cherry-picked first.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gaurav-narula** [comment]
CC: @soarez @chia7712

**Comment by chia7712** [comment]
#15776 is merged so please rebase code :)

**Comment by gaurav-narula** [comment]
@chia7712 Rebased. PTAL :)

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
The failed streams tests is fixed by https://github.com/apache/kafka/commit/6e998cffdd33e343945877ccee1fec8337c7d57d

**Pull request merged**
