### PR TITLE
Minor: Fix typos in KafkaConsumer docs

### PR DESCRIPTION
**Pull request by jeffwidman**

### CODE REVIEW

**Comment by jeffwidman** [comment]
Updated with fixes from #2179 and squashed into a single commit

**Comment by jeffwidman** [comment]
What else needs to be done to get this merged? I squashed in #2179 per @hachikuji request

**Comment by hachikuji** [comment]
LGTM. Sorry for the delay, this got a little buried.

**Comment by jeffwidman** [comment]
Thanks!

**Pull request closed without merging**
