### PR TITLE
MINOR: Fix GH Gradle caching

### PR DESCRIPTION
**Pull request by mumrah**
In order for Gradle to restore the cache, it needs to use the same workflow ID. This PR consolidates trunk and PRs builds to both use the CI build.

### CODE REVIEW

**Comment by mumrah** [comment]
We can see the results of caching in this PR since the trunk build is using the workflow "CI", and that's the name of the new consolidated workflow. 

image

Previous builds had times over 10 minutes for compile + validate.

**Comment by chia7712** [comment]
@mumrah Thanks for this patch. Could you please add changes to make check failed (checkstyle or spotless)? just double-check :smile:

**Comment by mumrah** [comment]
@chia7712 I added a checkstyle error to QuorumController.java. Looking at the builds, I see 

```
> Task :metadata:spotlessJava
Build cache key for task ':metadata:spotlessJava' is de99ce4fc5115b570333262fceca564f
Task ':metadata:spotlessJava' is not up-to-date because:
  No history is available.
The input changes require a full rebuild for incremental task ':metadata:spotlessJava'.
Not incremental: removing prior outputs
```

whereas the unaltered "raft" module shows

```
> Task :raft:spotlessJava FROM-CACHE
Build cache key for task ':raft:spotlessJava' is 5b8dafab1ff3d3bb62c7fc9be5b01598
Task ':raft:spotlessJava' is not up-to-date because:
  No history is available.
Loaded cache entry for task ':raft:spotlessJava' with cache key 5b8dafab1ff3d3bb62c7fc9be5b01598
Resolve mutations for :raft:spotlessJavaCheck (Thread[Execution worker Thread 3,5,main]) started.
:raft:spotlessJavaCheck (Thread[Execution worker Thread 3,5,main]) started.

> Task :raft:spotlessJavaCheck UP-TO-DATE
Caching disabled for task ':raft:spotlessJavaCheck' because:
  Caching has not been enabled for the task
Task ':raft:spotlessJavaCheck' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Resolve mutations for :raft:spotlessCheck (Thread[Execution worker Thread 3,5,main]) started.
:raft:spotlessCheck (Thread[Execution worker Thread 3,5,main]) started.

> Task :raft:spotlessCheck UP-TO-DATE
Skipping task ':raft:spotlessCheck' as it has no actions.
Resolve mutations for :server-common:spotlessJava (Thread[Execution worker Thread 3,5,main]) started.
:server-common:spotlessJava (Thread[Execution worker Thread 3,5,main]) started.
```

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
