### PR TITLE
KAFKA-12633: Remove deprecated APIs in TopologyTestDriver

### PR DESCRIPTION
**Pull request by guozhangwang**
As well as related test classes.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
ping @vvcephei for reviews.

**Review by vvcephei — APPROVED** [review]
Thanks for pulling these out, @guozhangwang !

**Comment by vvcephei** [comment]
Looks like there are some related test failures, though.

**Comment by guozhangwang** [comment]
> Looks like there are some related test failures, though.

Thanks! I have fixed the unit test, will merge after confirming green builds locally.

**Pull request merged**
