### PR TITLE
KAFKA-12862: Update Scala fmt library and apply fixes

### PR DESCRIPTION
**Pull request by jlprat**
Updates the scala fmt to the latest stable version
Applies all the style fixes (all source code changes are done by scala
fmt)
Removes setting about dangling parentheses as `true` is already the
default

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
Sorry to almost always point at you @ijuma If you would have time, could you take a look at this one? Maybe it's worth change the scala fmt config instead of leaving these deafults.

**Comment by ijuma** [comment]
Looks like the formatting changes are on the streams scala module. cc @mjsax @vvcephei @guozhangwang

**Comment by jlprat** [comment]
Noted, I will ping them when touching that area.

**Comment by jlprat** [comment]
Any chance any of you has time to check this? cc @mjsax @vvcephei @guozhangwang 

Thanks!

**Comment by jlprat** [comment]
@cadonna maybe you can look at this one if you have some time. Thanks!

**Comment by jlprat** [comment]
Rebased to resolve conflicts

**Review by vvcephei — APPROVED** [review]
Thanks, @jlprat !

**Comment by vvcephei** [comment]
It looks like there's a new conflict. Hopefully, we can merge soon after you fix the conflict this time.

By the way, can you let me know the command you used to apply the format? I've been accustomed to using Spotless Scala in this repo; I didn't know about Scala fmt until just now.

**Comment by jlprat** [comment]
Thanks for the review @vvcephei !
Actually, the spotless task executes the scalafmt in this gradle config, this means running `./gradlew spotlessScalaCheck` will analyze all Scala files and complain about violations in the code. Then running `./gradlew :spotlessScalaApply` will fix any formatting discrepancies.
Alternatively, one can configure IntelliJ or VS Code to run scalafmt and it will pick the existing configuration in the kafka repo.

**Comment by jlprat** [comment]
As new code has been added I need to re-run scalafmt for those. Pushing those changes in a second.

**Comment by jlprat** [comment]
Something went wrong during the build, can someone re-trigger the build in Jenkins?

Failure was:
> [2021-07-27T14:23:53.802Z] FAILURE: Build failed with an exception.
[2021-07-27T14:23:53.802Z] 
[2021-07-27T14:23:53.802Z] * What went wrong:
[2021-07-27T14:23:53.802Z] Execution failed for task ':storage:unitTest'.
[2021-07-27T14:23:53.802Z] > Process 'Gradle Test Executor 68' finished with non-zero exit value 1
[2021-07-27T14:23:53.802Z]   This problem might be caused by incorrect test process configuration.
[2021-07-27T14:23:53.802Z]   Please refer to the test execution section in the User Manual at https://docs.gradle.org/7.1.1/userguide/java_testing.html#sec:test_execution

**Comment by jlprat** [comment]
Hi @vvcephei feel free to review the tiny commit to fix the code that has been committed since the PR was created.
Also test failure seems unrelated

**Comment by jlprat** [comment]
I just closed and opened the PR to re-trigger Jenkins build.

**Comment by jlprat** [comment]
Pinging @vvcephei
Would you be able to merger this before more commits get in the way and we need another rebase?
Thanks a ton!

**Comment by jlprat** [comment]
Thanks @cadonna !

**Pull request merged**
