### PR TITLE
MINOR: Add timeout to testRenegotiation.

### PR DESCRIPTION
**Pull request by SinghAsDev**

### CODE REVIEW

**Comment by SinghAsDev** [comment]
This test hangs on slow machines, and so blocks testing. Would appreciate if you can take a quick look @gwenshap . This issue was raised in Kafka-3148 as well. Adding timeout will ensure that tests executions do not get blocked due to this particular test, while we work on finding fix for the hang. Note that we have renegotiations turned off for `SslTransportLayer`, so this test failure should not really be categorized as critical.

**Comment by gwenshap** [comment]
Thank you for tackling our failing tests. This is awesome!

I think you could use org.apache.kafka.test.TestUtils.checkForConditions() which already implements pretty much what you implemented here? It allows you to set your own timeout or use a default.

**Comment by SinghAsDev** [comment]
@gwenshap addressed your feedback and the only test failure is not related. Mind reviewing this again?

**Comment by chia7712** [comment]
@SinghAsDev Thanks for your patch. The related code was removed by https://github.com/apache/kafka/commit/f4e9c84c52fbb7ec6a4ca50c9ac35cacbd0df082 so I'm going to close this PR.

**Pull request closed without merging**
