### PR TITLE
MINOR: Remove unreachable if-else block in ReplicaManager.scala

### PR DESCRIPTION
**Pull request by drawxy**
After this #13107 PR,  an if-else block became unreachable. We need remove it and make the code clean.

### CODE REVIEW

**Review by divijvaidya — APPROVED** [review]

**Comment by divijvaidya** [comment]
@drawxy can you please fix the failing compilation. Otherwise looks good.

**Comment by showuon** [comment]
I can see there are thousands of lines changes. Is that expected?

**Comment by drawxy** [comment]
> I can see there are thousands of lines changes. Is that expected?

Hi @showuon , sorry for involving tens of commits by rebasing the wrong branch.

**Comment by drawxy** [comment]
> @drawxy can you please fix the failing compilation. Otherwise looks good.

Already fixed by rebasing the trunk branch. @divijvaidya, can you please help to merge this PR, thanks!

**Review by showuon — APPROVED** [review]
LGTM!

**Comment by drawxy** [comment]
Hi @divijvaidya and @showuon, I have resolved the compilation issue, but there are still some failed unit test cases, which are not involved by this PR. Should I mitigate them all? I am new here and need your helps, thanks again :)

**Comment by showuon** [comment]
Failed tests are unrelated.

**Comment by showuon** [comment]
Thanks for the contribution, @drawxy !

**Pull request merged**
