### PR TITLE
KAFKA-2423: Introduce Scalastyle

### PR DESCRIPTION
**Pull request by rchiang**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@ijuma @TolerableCoder could we consider extending the already added scalafmt to core than adding another framework?

**Comment by rchiang** [comment]
I just gave it a try in my tree, where I removed the "streams/" prefix from the spotless task in build.gradle:
- `gradle spotlessCheck` shows quite a few violations in core
- `./gradlew spotlessApply` cleaned up a bunch of code just fine (and builds of course)

I'm fine with having the change to build.gradle to let scalafmt work on core as well as streams.

I'm not sure how you want to handle all the `spotlessApply` cleanup (one separate fix or several).

**Comment by guozhangwang** [comment]
@TolerableCoder Thanks for taking a step towards this end! To me I think extending the existing scalafmt to core is good. About handling all the code cleanup. I'd suggest doing that in a single PR since otherwise it would leave the branch in a "unclean" state. One caveat is though, if the change is very large it may affect other PRs trying to be cherry-picked to older branches. But if we believe this is the right thing to do AND the right timing to do, we may just bite the bullet.

**Comment by rchiang** [comment]
Okay, I'll open a new PR with all the changes and we can determine whether it looks too big or not.

**Pull request closed without merging**
