### PR TITLE
MINOR: Modified System.getProperty("line.separator") to java.lang.System.lineSeparator()

### PR DESCRIPTION
**Pull request by TaiJuWu**
As title

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@TaiJuWu thanks for your contribution. Could you fix https://github.com/apache/kafka/blob/trunk/tools/src/main/java/org/apache/kafka/tools/TopicCommand.java#L776 also?

**Comment by TaiJuWu** [comment]
> @TaiJuWu thanks for your contribution. Could you fix https://github.com/apache/kafka/blob/trunk/tools/src/main/java/org/apache/kafka/tools/TopicCommand.java#L776 also?

Sure.

**Review by soarez — COMMENTED** [review]
Thank you for the changes.

Is there a reason to prefer the `java.lang.` prefix?

There are other uses of `System.getProperty("line.separator")`, should those be changed too?

* clients/src/main/java/org/apache/kafka/common/utils/Shell.java
* clients/src/main/java/org/apache/kafka/common/utils/Utils.java
* tools/src/main/java/org/apache/kafka/tools/ClientMetricsCommand.java
* core/src/main/scala/kafka/admin/ConsumerGroupCommand.scala
* connect/file/src/test/java/org/apache/kafka/connect/file/FileStreamSinkTaskTest.java

**Comment by TaiJuWu** [comment]
> Thank you for the changes.
> 
> Is there a reason to prefer the `java.lang.` prefix?

There is no special reason, Removing prefix is ok.
Following other code, Removing this prefix, thanks for your remind. 

> 
> There are other uses of `System.getProperty("line.separator")`, should those be changed too?
> 
> * clients/src/main/java/org/apache/kafka/common/utils/Shell.java
> * clients/src/main/java/org/apache/kafka/common/utils/Utils.java
> * tools/src/main/java/org/apache/kafka/tools/ClientMetricsCommand.java
> * core/src/main/scala/kafka/admin/ConsumerGroupCommand.scala
> * connect/file/src/test/java/org/apache/kafka/connect/file/FileStreamSinkTaskTest.java

These are removed if you pull the newest trunk branch.

**Review by chia7712 — APPROVED** [review]
LGTM. will merge it if @soarez approves it

**Review by soarez — APPROVED** [review]
LGTM thanks for the changes

**Comment by chia7712** [comment]
re-trigger QA since some builds get terminated

**Comment by chia7712** [comment]
@TaiJuWu Could you please rebase code to trigger QA again?

**Comment by chia7712** [comment]
@TaiJuWu could you please rebase code to include https://github.com/apache/kafka/pull/15801

**Comment by TaiJuWu** [comment]
> @TaiJuWu could you please rebase code to include #15801

Done.

**Pull request merged**
