### PR TITLE
KAFKA-4263: fix flaky test QueryableStateIntegrationTest.concurrentAccess

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @bbejeck @dguy @guozhangwang 

Note: first commit is code cleanup only. Second commit is actual fix (setting correct breakpoints you can reproduce the race condition)

1. let Producer only write a single input record
2. enter main test while-loop (this will spin forever, as long as producer is thread is stopped)
3. put break point into `StreamsThread` to suppress any further output
4. unblock producer thread and let if finish all its iterations
5. test while-loop will terminate and final "all key test" will run and fail (we produced a single record only and thus only one key is in the store).

On Jenkins this can happen if the `StreamThread` has a very long pause while the main test thread and producer thread both make regular progress.

The fix makes sure, that all keys are in the store before we start any test and thus this race condition is resolved.

**Comment by dguy** [comment]
@mjsax - the test failed in one of the runs above

**Comment by mjsax** [comment]
Ah. I guess, we need to wait for both stores...

Updated this.

**Comment by mjsax** [comment]
Retest this please.

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
The explanation makes sense, will wait for the Jenkins to pass.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and 1.1.0.

**Pull request closed without merging**
