### PR TITLE
KAFKA-14572: Fix ZK dependency in EmbeddedKafkaCluster

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by cmccabe** [comment]
Hmm, looks like this PR is further along than mine. Maybe I don't need this one. #17016

**Comment by bbejeck** [comment]
> Hmm, looks like this PR is further along than mine. Maybe I don't need this one

@cmccabe yes #17016 is very close - it's building now - if we get a green build I was going to merge.  I noticed some diffs with how you updated the `EmbeddedKafkaCluster` I can take those on in a follow-up PR.  WDYT?

**Comment by OmniaGM** [comment]
> > Hmm, looks like this PR is further along than mine. Maybe I don't need this one
> 
> @cmccabe yes #17016 is very close - it's building now - if we get a green build I was going to merge. I noticed some diffs with how you updated the `EmbeddedKafkaCluster` I can take those on in a follow-up PR. WDYT?

Are we going to apply the same approach to the `EmbeddedKafkaCluster` in connect as well?

**Comment by bbejeck** [comment]
> > > Hmm, looks like this PR is further along than mine. Maybe I don't need this one
> > 
> > 
> > @cmccabe yes #17016 is very close - it's building now - if we get a green build I was going to merge. I noticed some diffs with how you updated the `EmbeddedKafkaCluster` I can take those on in a follow-up PR. WDYT?
> 
> Are we going to apply the same approach to the `EmbeddedKafkaCluster` in connect as well?

@OmniaGM I'm not sure - but it would make sense to me, but I'm not as familiar with the connect plans

**Comment by cmccabe** [comment]
Closing since #17016 already accomplished this. Thanks, all.

**Comment by cmccabe** [comment]
> @OmniaGM : Are we going to apply the same approach to the EmbeddedKafkaCluster in connect as well?

I believe Connect's version of `EmbeddedKafkaCluster` was already updated to KRaft in KAFKA-14569. So nothing more to do there.

**Comment by cmccabe** [comment]
> @bbejeck : I noticed some diffs with how you updated the EmbeddedKafkaCluster I can take those on in a follow-up PR. WDYT?

I think the way you did it, where you used `KafkaClusterTestKit`, is better than what I did :) I was just being lazy by using the Scala test harness. `KafkaClusterTestKit` is actually the better way since it will be easier to configure in the future, and doesn't drag in all that scala stuff.

Feel free to grab any code from my PR that still looks useful, though. (Keep in mind that I didn't really get to the point of testing it, though.)

**Pull request closed without merging**
