### PR TITLE
[MINOR] Improve runtime / storage / metrics / config parts

### PR DESCRIPTION
**Pull request by asdf2014**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify documentation (including upgrade notes)
- [x] Verify test coverage and CI build status

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/324/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/361/

**Comment by asdf2014** [comment]
Hi, @ijuma @guozhangwang . PTAL.

**Comment by guozhangwang** [comment]
There is a checkstyle failure:

```
11:26:42 :connect:runtime:checkstyleMain[ant:checkstyle] [ERROR] /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk9-scala2.12/connect/runtime/src/main/java/org/apache/kafka/connect/cli/ConnectDistributed.java:29: Using the '.*' form of import should be avoided - org.apache.kafka.connect.storage.*. [AvoidStarImport]
```

**Comment by asdf2014** [comment]
@guozhangwang Thank you for comment. Already fixed.

**Comment by guozhangwang** [comment]
retest this please

**Comment by asdf2014** [comment]
@guozhangwang Fixed conflicts.

**Comment by asdf2014** [comment]
@guozhangwang Fixed conflicts and rebased those commits onto trunk branch. PTAL.

**Comment by guozhangwang** [comment]
Jenkins failures from `org.apache.kafka.connect.runtime.WorkerSinkTaskThreadedTest.testAssignmentPauseResume`
seem related:

```
Error Message

org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
```

**Comment by asdf2014** [comment]
@guozhangwang Finally, all checks have passed. PTAL.

**Comment by guozhangwang** [comment]
Merged to trunk. Thanks @asdf2014

**Comment by asdf2014** [comment]
@guozhangwang You are welcome :D

**Pull request merged**
