### PR TITLE
 MINOR: Add missing imports to 'Hello Kafka Streams' examples

### PR DESCRIPTION
**Pull request by wojda**
Without those imports examples does not compile.

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM! Thanks @wojda

**Comment by guozhangwang** [comment]
retest this please

**Review by mjsax — APPROVED** [review]
Thanks for the patch @wojda 

LGTM.

**Comment by guozhangwang** [comment]
Cherry-picked to 1.0 and 1.1.

**Pull request merged**
