### PR TITLE
KAFKA-7741: Reword Streams dependency workaround docs

### PR DESCRIPTION
**Pull request by vvcephei**
Avoid mentioning unreleased versions in the docs.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@guozhangwang or @mjsax , please take a look at this tweak to the docs, based on feedback.

Rendered:
ak-updated-docs-2 0

**Review by mjsax — APPROVED** [review]

**Comment by mjsax** [comment]
@vvcephei We should do a PR again `kafka-site`, too -- otherwise, the current web page is not updated.

**Comment by mjsax** [comment]
Retest this please.

**Review by bbejeck — APPROVED** [review]

**Comment by mjsax** [comment]
Retest this please.

**Review by guozhangwang — APPROVED** [review]

**Pull request merged**
