### PR TITLE
KAFKA-3563: Maintain MessageAndMetadata constructor compatibility

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM. In addition to the compatibility argument, It's weird to use default arguments before parameters without defaults.

**Comment by SinghAsDev** [comment]
LGTM!

**Comment by granthenke** [comment]
cc @gwenshap @ewencp

**Comment by granthenke** [comment]
@gwenshap @ewencp @guozhangwang @junrao 
ping for review

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
