### PR TITLE
HOTFIX: Renamed tests to match expected suffix

### PR DESCRIPTION
**Pull request by enothereska**
@ewencp @gwenshap @granders could you have a look please? Thanks.

### CODE REVIEW

**Comment by ewencp** [comment]
@enothereska These look fine, they are being discovered now. I did a quick scan for others we may have messed up the naming for and one more shows up -- tests/kafkatest//tests/consumer_rolling_upgrade.py. Want to just roll that into this fix as well?

**Comment by enothereska** [comment]
@ewencp sure, done.

**Comment by ewencp** [comment]
@enothereska Oops, don't think we want to move `produce_consume_validate.py`. It is (perhaps confusingly) in `tests/` but is a base class for tests -- moving it breaks a bunch of imports that use it and removes a bunch of tests.

**Comment by enothereska** [comment]
Good catch @ewencp thanks!

**Comment by ewencp** [comment]
Great, LGTM!

**Pull request closed without merging**
