### PR TITLE
MINOR: disable zookeeper.sasl.client to avoid false error

### PR DESCRIPTION
**Pull request by chia7712**
Zookeeper connection always does SASL checks currently. That behavior produces false warnings to kafka log. For example:

### using PLAINTEXT
```
[2021-11-05 11:39:33,738] INFO Opening socket connection to server caijiapngdeiMac/192.168.50.178:19516. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
```

### using SASL_PLAINTEXT with `java.security.auth.login.config`
```
[2021-11-05 11:52:37,130] ERROR [ZooKeeperClient Kafka server] Auth failed. (kafka.zookeeper.ZooKeeperClient)
```

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mimaison — APPROVED** [review]
Thanks, LGTM

**Comment by ijuma** [comment]
Any reason why this wasn't merged?

**Comment by chia7712** [comment]
> Any reason why this wasn't merged?

will merge it if QA pass :)

**Comment by chia7712** [comment]
```
Build / JDK 11 and Scala 2.13 / kafka.api.PlaintextAdminIntegrationTest.testReplicaCanFetchFromLogStartOffsetAfterDeleteRecords()
```
```
Build / JDK 8 and Scala 2.12 / kafka.api.PlaintextAdminIntegrationTest.testReplicaCanFetchFromLogStartOffsetAfterDeleteRecords()
```

unrelated error. Will merge it.

**Pull request merged**
