### PR TITLE
MINOR; Increase log level of some rare events

### PR DESCRIPTION
**Pull request by jsancio**
To help debug KRaft's behavior this change increases the log level of some rare messages to INFO level.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by hachikuji** [comment]
Upgrading the error messages is probably fair, but do we really need the backoff messages at INFO level? Seems like they have potential to be noisy.

**Comment by jsancio** [comment]
> Upgrading the error messages is probably fair, but do we really need the backoff messages at INFO level? Seems like they have potential to be noisy.

Okay. I'll revert the change to the send request backoff but I think we should keep the candidate backoff as that is "rare" and would help us debug election delays. What do you think?

**Comment by hachikuji** [comment]
> Okay. I'll revert the change to the send request backoff but I think we should keep the candidate backoff as that is "rare" and would help us debug election delays. What do you think?

Yeah, that one is probably fine. One message per election attempt seems ok.

**Review by hachikuji — APPROVED** [review]
LGTM

**Review by hachikuji — APPROVED** [review]

**Pull request merged**
