### PR TITLE
KAFKA-10787: Apply spotless to `clients` 

### PR DESCRIPTION
**Pull request by gongxuanzhang**
This PR is sub PR from https://github.com/apache/kafka/pull/16097.
It is part of a series of changes to progressively apply [spotless plugin(import-order)] across all modules. In this step, the plugin is activated in the 
* stream:test-utils
* streams:upgrade-system-tests-0100

## Module and history 

> Please see the table below for the historical changes related to applying the Spotless plugin

| module        | apply |  related PR  |
| -------------- | ------------------- | ------------------- |
| :clients | ✅   | https://github.com/apache/kafka/pull/16393 |
| :connect:api | ✅    | https://github.com/apache/kafka/pull/16299 |
| :connect:basic-auth-extension | ✅    | https://github.com/apache/kafka/pull/16299 |
| :connect:file | ✅    | https://github.com/apache/kafka/pull/16299 |
| :connect:json | ✅   | https://github.com/apache/kafka/pull/16299 |
| :connect:mirror | ✅   | https://github.com/apache/kafka/pull/16299 |
| :connect:mirror-client | ✅   | https://github.com/apache/kafka/pull/16299 |
| :connect:runtime | ❌    | future |
| :connect:test-plugins | ✅   | https://github.com/apache/kafka/pull/16299 |
| :connect:transforms | ✅   | https://github.com/apache/kafka/pull/16299 |
| :core | ✅    | https://github.com/apache/kafka/pull/16392 |
| :examples |  ✅    | https://github.com/apache/kafka/pull/16296 |
| :generator |  ✅     | https://github.com/apache/kafka/pull/16296 |
| :group-coordinator:group-coordinator-api | ✅   | https://github.com/apache/kafka/pull/16298 |
| :group-coordinator | ✅  | https://github.com/apache/kafka/pull/16298 |
| :jmh-benchmarks |  ✅     | https://github.com/apache/kafka/pull/16296 |
| :log4j-appender |  ✅     | https://github.com/apache/kafka/pull/16296 |
| :metadata | ✅     | https://github.com/apache/kafka/pull/16297 |
| :server | ✅     | https://github.com/apache/kafka/pull/16297 |
| :shell |  ✅     | https://github.com/apache/kafka/pull/16296 |
| :storage | ✅     | https://github.com/apache/kafka/pull/16297 |
| :storage:storage-api | ✅     | https://github.com/apache/kafka/pull/16297 |
| :streams | ❌     | future |
| :streams:examples |  ✅   | https://github.com/apache/kafka/pull/16378 |
| :streams:streams-scala | ✅    | https://github.com/apache/kafka/pull/16378 |
| :streams:test-utils |  ✅     | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-0100 |  ✅     | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-0101 | ✅    | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-0102 | ✅    | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-0110 | ✅    | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-10 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-11 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-20 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-21 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-22 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-23 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-24 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-25 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-26 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-27 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-28 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-30 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-31 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-32 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-33 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-34 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-35 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-36 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :streams:upgrade-system-tests-37 | ✅   | https://github.com/apache/kafka/pull/16357 |
| :trogdor |  ✅       | https://github.com/apache/kafka/pull/16296 |
| :raft |  ✅    | https://github.com/apache/kafka/pull/16278 |
| :server-common | ✅    | https://github.com/apache/kafka/pull/16172 |
| :transaction-coordinator | ✅    | https://github.com/apache/kafka/pull/16172 |
| :tools |  ✅   |  https://github.com/apache/kafka/pull/16262  |
| :tools:tools-api | ✅   | https://github.com/apache/kafka/pull/16262 |

## How to test:
We can run `./gradlew spotlessCheck`  check for code that does not meet requirements. 
If we get report that error , we can run `./gradlew spotlessApply` to review my code.
In this PR, all change(exclude `build.gradle`) ` by `spotlessApply`

### CODE REVIEW

**Comment by chia7712** [comment]
@gongxuanzhang please rebase code

**Comment by gongxuanzhang** [comment]
@chia7712  complete, thanks your review

**Comment by chia7712** [comment]
@gongxuanzhang could you add `generated-test` to `targetExclude` to fix the build error?

**Comment by gongxuanzhang** [comment]
@chia7712  I update it. ignore generated code

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
@chia7712 I'm coming into this late, but please check in the mailing list before doing large reformattings like we are doing here. It causes a bunch of merge conflicts for work in progress, makes cherry-picks for older branches harder and so on. I see the value of the change, but we should seek broader alignment for things that impact many of the developers.

**Comment by chia7712** [comment]
> I see the value of the change, but we should seek broader alignment for things that impact many of the developers.

sorry for large conflicts. We tried to minimize the conflicts by making changes to "imports" only. It seems to me those conflicts are not hard to fix as they are unrelated to "behavior". Also, I have seen many conflicts about the imports before when those import rules are not there. In short, I agree that will cause some panic for a while and I'm sorry, but the benefit is that we can see fewer imports changes caused by each developers' IDE in the future

**Pull request merged**
