### PR TITLE
MINOR: update test_broker_type_bounce_at_start to match trunk

### PR DESCRIPTION
**Pull request by vvcephei**
Ignore a flaky test in 0.10.2 that is also ignored in trunk.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@mjsax @guozhangwang @bbejeck ,

As ironic as it feels, I'm proposing to "fix" this flaky test by ignoring it. This is what we have done in trunk.

I think that we should re-write the test so that it's not flaky in trunk and then backport it.

However, until we do this, I'd prefer to just ignore the test so that we can take failing 0.10.2 system tests more seriously.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3808/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by mjsax** [comment]
If we ignore the test, can you create a JIRA to track that the test is disabled.

Beside this, why the rewrite?

**Comment by vvcephei** [comment]
Ah, I updated the test to match trunk, including the ignore.

If you'd rather just add the ignore, I can do that as well.

**Comment by vvcephei** [comment]
the system tests pass: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1995

**Comment by vvcephei** [comment]
@mjsax: created https://issues.apache.org/jira/browse/KAFKA-7493

**Comment by mjsax** [comment]
> Ah, I updated the test to match trunk, including the ignore.

Than I don't understand `trunk` either :) -- I leave it to @guozhangwang to make a call.

**Comment by guozhangwang** [comment]
I agree `test_broker_type_bounce_at_start` should be re-write since the current test coverage is really shallow and it's not worth maintaining it.

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3810/
Test PASSed (JDK 7 and Scala 2.10).

**Comment by vvcephei** [comment]
@mjsax : I've updated this PR to avoid unnecessary dead code and just ignore the relevant test.
cc @bbejeck for a second review.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3811/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by mjsax** [comment]
Retest this please (I give it one try...) -- the change is unrelated to failing unit tests.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3812/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by vvcephei** [comment]
@mjsax : there was another unrelated failure:

* org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses[0]
* org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses[1]

It's a subset of prior unrelated failures:

* org.apache.kafka.streams.integration.QueryableStateIntegrationTest.queryOnRebalance[0]
* org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses[0]
* org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses[1]

**Comment by vvcephei** [comment]
retest this, please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3813/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by vvcephei** [comment]
retest this, please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3814/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by vvcephei** [comment]
retest this, please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3815/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by mjsax** [comment]
`QueryableStateIntegrationTest` is know to be flaky in older branched :( Merging as-is without green build. Disabling a system test is no risk.

**Comment by vvcephei** [comment]
Thanks @mjsax !

**Pull request merged**
