### PR TITLE
KAFKA-3352: Avoid DNS reverse lookups

### PR DESCRIPTION
**Pull request by ijuma**
By using `getHostString` (introduced in Java 7) instead of `getHostName`.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji and @gwenshap. Tests pass locally.

**Comment by hachikuji** [comment]
LGTM

**Comment by ijuma** [comment]
@hachikuji, I added a test.

**Comment by granthenke** [comment]
LGTM

**Comment by gwenshap** [comment]
LGTM

**Pull request closed without merging**
