### PR TITLE
Update dependencies.gradle

### PR DESCRIPTION
**Pull request by shubhamsingh002**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by hachikuji** [comment]
@shubhamsingh002 Can you clarify your intent here? The upgrade to log4j 2 is not compatible and we are not planning to release from 0.10 in any case as far as I know.

**Comment by hachikuji** [comment]
I am going to go ahead and close this. Please feel free to reopen after you have updated the description to explain what you are trying to do.

**Comment by FireBurn** [comment]
Can we replace with reload4j 

https://reload4j.qos.ch/ it fixes the bugs of log4j1, is written by the same developer and doesn't have api changes like log4j2

**Comment by FireBurn** [comment]
I've raised https://github.com/apache/kafka/pull/11743 to switch to reload4j

**Pull request closed without merging**
