### PR TITLE
Git ignore idea's specific /out/ and .DS_Store.

### PR DESCRIPTION
**Pull request by SinghAsDev**

### CODE REVIEW

**Comment by SinghAsDev** [comment]
@ewencp mind taking a look at this trivial patch.

**Comment by granthenke** [comment]
FYI #479 and the discussion on that jira is related to this. That pull requests covers both of these.

**Comment by SinghAsDev** [comment]
Thanks for the pointer @granthenke, I was not aware of it. Will close this and review #479 then.

**Comment by granthenke** [comment]
@SinghAsDev This patch may be the preferred approach by the community, but I wanted to point out #479 since small updates like this was my motivation for the larger refactor.

**Comment by SinghAsDev** [comment]
I am fine with anything, if this patch is small enough and fine with committers then I can reopen it. Will wait for response from @ewencp or @ijuma.

**Pull request closed without merging**
