### PR TITLE
KAFKA-18218: Trogdor system test can't find coordinator

### PR DESCRIPTION
**Pull request by TaiJuWu**
JIRA: https://issues.apache.org/jira/browse/KAFKA-18218

https://github.com/apache/kafka/pull/18000 make output as console instead of log so we need to update e2e.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by TaiJuWu** [comment]
Run on my local

Before
```
====================================================================================================
SESSION REPORT (ALL TESTS)
ducktape version: 0.12.0
session_id:       2024-12-11--001
run time:         3 minutes 51.182 seconds
tests run:        3
passed:           0
flaky:            0
failed:           3
ignored:          0
====================================================================================================
test_id:    kafkatest.tests.core.consume_bench_test.ConsumeBenchTest.test_consume_bench.topics=.consume_bench_topic.0-5.0-4.metadata_quorum=ISOLATED_KRAFT.use_new_coordinator=False
status:     FAIL
run time:   1 minute 16.785 seconds


    TimeoutError("coordinator on ducker11 didn't finish startup")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ducktape/tests/runner_client.py", line 350, in _do_run
    self.setup_test()
  File "/usr/local/lib/python3.7/dist-packages/ducktape/tests/runner_client.py", line 402, in setup_test
    self.test.setup()
  File "/usr/local/lib/python3.7/dist-packages/ducktape/tests/test.py", line 74, in setup
    self.setUp()
  File "/opt/kafka-dev/tests/kafkatest/tests/core/consume_bench_test.py", line 42, in setUp
    self.trogdor.start()
  File "/usr/local/lib/python3.7/dist-packages/ducktape/services/service.py", line 265, in start
    self.start_node(node, **kwargs)
  File "/opt/kafka-dev/tests/kafkatest/services/trogdor/trogdor.py", line 139, in start_node
    self._start_coordinator_node(node)
  File "/opt/kafka-dev/tests/kafkatest/services/trogdor/trogdor.py", line 149, in _start_coordinator_node
    TrogdorService.COORDINATOR_LOG, node)
  File "/opt/kafka-dev/tests/kafkatest/services/trogdor/trogdor.py", line 175, in _start_trogdor_daemon
    err_msg=("%s on %s didn't finish startup" % (daemon_name, node.name)))
  File "/usr/local/lib/python3.7/dist-packages/ducktape/cluster/remoteaccount.py", line 754, in wait_until
    allow_fail=True) == 0, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ducktape/utils/util.py", line 58, in wait_until
    raise TimeoutError(err_msg() if callable(err_msg) else err_msg) from last_exception
ducktape.errors.TimeoutError: coordinator on ducker11 didn't finish startup

----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.consume_bench_test.ConsumeBenchTest.test_multiple_consumers_random_group_topics.metadata_quorum=ISOLATED_KRAFT.use_new_coordinator=True.group_protocol=classic
status:     FAIL
run time:   1 minute 16.715 seconds
```

After
```
====================================================================================================
SESSION REPORT (ALL TESTS)
ducktape version: 0.12.0
session_id:       2024-12-11--001
run time:         6 minutes 28.818 seconds
tests run:        3
passed:           3
flaky:            0
failed:           0
ignored:          0
====================================================================================================
test_id:    kafkatest.tests.core.consume_bench_test.ConsumeBenchTest.test_consume_bench.topics=.consume_bench_topic.0-5.0-4.metadata_quorum=ISOLATED_KRAFT.use_new_coordinator=False
status:     PASS
run time:   2 minutes 11.688 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.consume_bench_test.ConsumeBenchTest.test_multiple_consumers_random_group_topics.metadata_quorum=ISOLATED_KRAFT.use_new_coordinator=True.group_protocol=classic
status:     PASS
run time:   2 minutes 6.059 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.consume_bench_test.ConsumeBenchTest.test_two_consumers_specified_group_topics.metadata_quorum=ISOLATED_KRAFT.use_new_coordinator=True.group_protocol=consumer
status:     PASS
run time:   2 minutes 10.593 seconds
----------------------------------------------------------------------------------------------------
```

**Comment by chia7712** [comment]
@TaiJuWu thanks for this quick fix

**Comment by m1a2st** [comment]
Thanks for @TaiJuWu quick fix.

**Review by m1a2st — APPROVED** [review]

**Review by frankvicky — APPROVED** [review]

**Review by chia7712 — APPROVED** [review]

**Comment by TaiJuWu** [comment]
Even if apply this patch, `NetworkDegradeTest` still fail since `Starting agent process` appear in `log` instead of `stdout`.
File jira https://issues.apache.org/jira/browse/KAFKA-18277

**Pull request merged**
