### PR TITLE
FIX: Modify test config to reduce time to task assignment w/o warm-up tasks

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
System test run is ongoing.

**Comment by cadonna** [comment]
Here the jenkins job:
https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4602/console

Apparently, there are issues with the upload of the results. I repeated the system tests 10 times and there were no failures.

**Review by ableegoldman — APPROVED** [review]
This would certainly be my preference. If it seems to help, maybe we should try this out to begin with, and then if we do still see occasional failures we can pull out the heavier fixes. But IMHO if a simple config adjustment is sufficient, let's do it 🙂

**Comment by cadonna** [comment]
Test failure are known to be flaky:

```
Build / JDK 16 and Scala 2.13 / kafka.api.ConsumerBounceTest.testCloseDuringRebalance()
Build / JDK 16 and Scala 2.13 / kafka.api.ConsumerBounceTest.testCloseDuringRebalance()
Build / JDK 8 and Scala 2.12 / kafka.api.ConsumerBounceTest.testCloseDuringRebalance()
```

**Comment by cadonna** [comment]
Cherry-picked to 3.0

**Pull request merged**
