### PR TITLE
MINOR: clean up unneeded `@SuppressWarnings` on Streams module

### PR DESCRIPTION
**Pull request by jlprat**
Remove unneeded `@SuppressWarnings("unchecked")` in source and test
Remove unneeded `@SuppressWarnings("deprecated")` in source and test

Several of those annotations were either never needed, or the code that force its introduction is already gone.
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
cc. @mjsax as you were doing a PR touching similar things recently, maybe you want to review this one as well?
Also pinging @vvcephei as he was reviewing that PR I was referring to.

**Review by mjsax — APPROVED** [review]
LGTM. Rerunning Jenkins to make sure it passes.

(I remove some annotation in the passed [as it was suggested by IntelliJ], but the build failed later with checkstyle errors -- need to make sure we don't break anything by accident.)

**Comment by jlprat** [comment]
Failures seem to be:
> RaftClusterTest.testCreateClusterAndCreateAndManyTopicsWithManyPartitions()

And

> SmokeTestDriverIntegrationTest.shouldWorkWithRebalance


While doing this PR, I also encountered a similar thing you mention @mjsax , somehow IntelliJ needed less `@SuppressWarnings` as `javac`. It seems all the ones I removed weren't really needed.

**Comment by jlprat** [comment]
@mjsax Could you restart the build? Last time it failed with the `1` exit code

**Comment by jlprat** [comment]
Unless the CI is still broken, of course

**Review by showuon — APPROVED** [review]
LGTM! And @jlprat , yes, I've checked, your exit code 1 is a known issue and I've opened KAFKA-12892 to track it and PR https://github.com/apache/kafka/pull/10820 is ready to bypass it. Thanks

**Comment by jlprat** [comment]
Thanks for the review and the ticket + PR to fix the issue @showuon!

**Comment by jlprat** [comment]
As far as I understand, problem with the failing builds has been solved, is there any way I can run again the Jenkins build? Or only committers can do it?
cc @mjsax (thanks in advance)

**Comment by showuon** [comment]
@jlprat , you can merge with trunk branch to trigger jenkins build again if you want. Thanks.

**Review by chia7712 — APPROVED** [review]
LGTM. the failed tests are related to this patch (I re-run them on my local. It seems they are flaky). Merge it to trunk

**Comment by jlprat** [comment]
Thanks @mjsax , @showuon  and @chia7712 for the reviews!

**Pull request merged**
