### PR TITLE
KAFKA-6607: Commit correct offsets for transactional input data

### PR DESCRIPTION
**Pull request by mjsax**
Port of #8040 to `trunk` -- the only real difference is the missing check of we are in pending shutdown and a task is not found -- in `trunk` we always create all new task hence this check is not necessary.

\cc @guozhangwang

### CODE REVIEW

**Review by guozhangwang — APPROVED** [review]
LGTM! In trunk we can be stricter and throw illegal-state since we should always have the tasks at hand still.

**Comment by mjsax** [comment]
Rebased this PR to resolve merge conflicts.

**Comment by mjsax** [comment]
Java 8 passed.
Java 11: `kafka.api.ConsumerBounceTest.testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup`

Retest this please.

**Comment by mjsax** [comment]
Java 8:
```
kafka.admin.DeleteConsumerGroupsTest.testDeleteWithMixOfSuccessAndError
kafka.admin.DescribeConsumerGroupTest.testDescribeGroupWithShortInitializationTimeout
kafka.admin.ResetConsumerGroupOffsetTest.testResetOffsetsAllTopicsAllGroups
kafka.admin.DescribeConsumerGroupTest.testDescribeGroupMembersWithShortInitializationTimeout
kafka.admin.DeleteConsumerGroupsTest.testDeleteCmdWithMixOfSuccessAndError
```

Java 11: `kafka.admin.DescribeConsumerGroupTest.testDescribeGroupWithShortInitializationTimeout`

Those are different test than in the run before. Merging this.

**Pull request merged**
