### PR TITLE
MINOR: Update "Java Version" section

### PR DESCRIPTION
**Pull request by ijuma**
Use the latest information from LinkedIn and mention that the latest
released version is recommended from a security perspective.

### CODE REVIEW

**Comment by ijuma** [comment]
@toddpalino thanks for the updated LinkedIn usage information. Would you mind checking this PR?

**Comment by granthenke** [comment]
LGTM

**Comment by guozhangwang** [comment]
LGTM, merged to trunk. @ijuma feel free to recompile and pushed to kafka-site.

**Comment by toddpalino** [comment]
Now that I review this, I realize there's some information that I didn't give you (I'm going to blame it on the way our configs are split up right now). The actual tuning we're using is:

```
-Xmx6g -Xms6g -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MetaspaceSize=96m -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
```

The Metaspace settings replace the PermGen settings that were previously valid (PermGen no longer exists in Java 8). The G1HeapRegionSize setting we found was needed because there were many 3-5 MB allocations (which are considered humongous). This would periodically cause a full GC cycle that could take very long (12-50 seconds), impacting the cluster. This is likely due to our message and batch sizes.

**Pull request closed without merging**
