### PR TITLE
MINOR: Add text and link to blog in announcement template email

### PR DESCRIPTION
**Pull request by jlprat**
The blog is "new" compared to the existence of the announcement email template. I added a section for the blog in the template so nobody forgets about it.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
Hi @soarez if you have some time this is a quick one

**Review by soarez — APPROVED** [review]
LGTM

**Comment by soarez** [comment]
Thanks for the change

**Comment by jlprat** [comment]
No need to wait for CI as it only changes a template file in python

**Pull request merged**
