### PR TITLE
MINIOR: Remove accidentally logs

### PR DESCRIPTION
**Pull request by OmniaGM**
This logs was added during the troubleshooting for some flaky tests and was pushed by mistake in #15354

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by OmniaGM** [comment]
cc: @jolshan can you merge this when you have a moment please?

**Review by soarez — APPROVED** [review]
LGTM. Thanks for fixing.

**Review by jolshan — APPROVED** [review]

**Review by mimaison — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
this is backported to 3.7 https://github.com/apache/kafka/commit/c5b524f0d73ba80c576585299cc3cf9ae0a7fcab

**Pull request merged**
