### PR TITLE
MINOR Remove triage label in nightly job

### PR DESCRIPTION
**Pull request by mumrah**
This patch adds a nightly job which removes the "triage" label from PRs which have been reviewed.

### CODE REVIEW

**Comment by mumrah** [comment]
@gharris1727 another followup

**Comment by mumrah** [comment]
@chia7712 could you take a look at this? The workflow to remove the "triage" label isn't running automatically and this PR should fix it.

**Comment by mumrah** [comment]
Actually I'm realizing now this might not work. Since `pull_request_review` runs the workflow definition from the PR, it will require approval before running. However, for some reason the API call is failing on these approvals

```
$ gh api --method POST \
              -H 'Accept: application/vnd.github+json' \
              -H 'X-GitHub-Api-Version: 2022-11-28' \
              /repos/apache/kafka/actions/runs/12356775485/approve
{
  "message": "This run is not from a fork pull request",
  "documentation_url": "https://docs.github.com/rest/actions/workflow-runs#approve-a-workflow-run-for-a-fork-pull-request",
  "status": "403"
}
gh: This run is not from a fork pull request (HTTP 403)
```

I was able to approve the workflow in the UI, but not using the API. Maybe this is a bug in the `pull_request_review` event handling 🤷‍♂️

**Comment by mumrah** [comment]
Ok @chia7712, _now_ it's ready for review 😄. I rewrote this workflow to run as a cron job rather than trying to react to the `pull_request_review` event.

**Review by jolshan — APPROVED** [review]

**Review by chia7712 — APPROVED** [review]

**Comment by mumrah** [comment]
It works 🎉 https://github.com/apache/kafka/actions/runs/12405547852/job/34632606547

**Pull request merged**
