### PR TITLE
MINOR: additional check to follower fetch handling

### PR DESCRIPTION
**Pull request by edoardocomar**
add check to KafkaApis, add unit test specific to follower fetch
developed with @mimaison
backport to 0.10.2 of #4433

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by edoardocomar** [comment]
Hi @rajinisivaram backport as requested! ciao

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3784/
Test FAILed (JDK 7 and Scala 2.10).

**Review by rajinisivaram — APPROVED** [review]
@edoardocomar @mimaison Thanks for the PR, LGTM. Will merge after builds complete.

**Comment by edoardocomar** [comment]
JDK 7 and Scala 2.10 : ERROR: No tool found matching GRADLE_3_4_RC_2_HOME

JDK 9 and Scala 2.12 - ERROR: No tool found matching GRADLE_3_4_RC_2_HOME

JDK 7 and Scala 2.11 - Streams test errors due to errors accessing files.
(and BTW the testsuite passes for me locally on my Mac)

**Comment by rajinisivaram** [comment]
retest this please

**Comment by rajinisivaram** [comment]
Will try again to see if at least one build works, otherwise will build locally.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3785/
Test PASSed (JDK 7 and Scala 2.10).

**Comment by rajinisivaram** [comment]
JDK 9 not supported for 0.10.2, JDK 8 builds seems to be having unrelated issues in streams tests. Merging to 0.10.2 since tests have passed in the other two builds.

**Pull request merged**
