### PR TITLE
MINOR: Update version to 0.9.0.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
Trivial patch, but it was suggested I leave it open for some discussion. Right now we're running into some internal Jenkins issues because we have changes to this branch which are still being called "0.9.0.0" and cause downstream issues in our schema-registry code. This is difficult/annoying to fix without Kafka making a clear distinction between versions and when code should be considered a SNAPSHOT (which can also cause builds to break, but at least is expected).

Another alternative would be to change this to 0.9.0.1 immediately instead of 0.9.0.1-SNAPSHOT, although personally I prefer starting to be more careful about marking code that isn't released and should not be considered stable as such.

/cc @junrao @gwenshap @ijuma

**Comment by gwenshap** [comment]
We usually self-commit the version bumps :) Anyway, LGTM.

**Comment by ijuma** [comment]
LGTM. Do we need to update the release process wiki page to mention that the `SNAPSHOT` needs to be removed before creating the RC?

https://cwiki.apache.org/confluence/display/KAFKA/Release+Process

**Comment by ewencp** [comment]
Review all the things

@gwenshap I actually filed this for the purpose of discussion since we seem to only have been using -SNAPSHOT on trunk, and I the number of patches going into 0.9.0.1 (assuming it happens) is actually substantial compared to previous release.

**Comment by ewencp** [comment]
@ijuma: Added a quick note to that wiki. Agree we should further refine those instructions so the whole process avoids multiple versions of the code with release-style version numbers.

**Comment by ijuma** [comment]
@ewencp looks good, thanks.

**Comment by guozhangwang** [comment]
LGTM, and +1 on changing now than later.

**Comment by ijuma** [comment]
@ewencp, can you please close this since it's been integrated (PRs that don't target trunk have to be closed manually sadly).

**Pull request closed without merging**
