### PR TITLE
MINOR: fix quotes for consistent rendering

### PR DESCRIPTION
**Pull request by mihbor**
“ as opposed to " don't render consistently across browsers. On current Kafka website they render correctly in Firefox but not Chrome (â€œrunsâ€) - charset issue?

### CODE REVIEW

**Comment by ijuma** [comment]
cc @enothereska @guozhangwang

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5394/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5379/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and 0.11.0.

**Pull request closed without merging**
