### PR TITLE
KAFKA-12672: Added config for raft testing server

### PR DESCRIPTION
**Pull request by bbejeck**
Adding a property to the `raft/config/kraft.properties` for running the raft test server in development.

For testing I ran `./bin/test-kraft-server-start.sh --config config/kraft.properties` and validated the test server started running with a throughput test.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Don't you need to update the multi-node-quorum section? https://github.com/apache/kafka/tree/trunk/raft#run-multi-node-quorum

**Comment by bbejeck** [comment]
@ijuma updated README

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Merged to trunk and cherry-picked to 2.8.

**Pull request merged**
