### PR TITLE
KAFKA-14626: Kafka Consumer Coordinator does not cleanup all metrics after shutdown

### PR DESCRIPTION
**Pull request by yufeiyan1220**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by philipnee** [comment]
Thanks for the PR and the issue @yufeiyan1220 - I wonder if the clean up is necessary, as the metrics will be closed upon the client closing. Willing to hear what others say.

**Comment by yufeiyan1220** [comment]
> Thanks for the PR and the issue @yufeiyan1220 - I wonder if the clean up is necessary, as the metrics will be closed upon the client closing. Willing to hear what others say.

I found that problem when I tried to create and close consumer frequently. Just like the test case I have made in `KafkaConsumerTest.java`, these consumer coordinator metrics are still present if I does not close  these metrics explicitly. I think most of users might not try to create and close consumer frequently, but there is a potential for memory leak actually.

**Comment by philipnee** [comment]
Seems like we aren't particularly consistent at removing these metrics and sensors, fetcher would be another example.  Mind making the clean up more comprehensive?

**Comment by yufeiyan1220** [comment]
> Seems like we aren't particularly consistent at removing these metrics and sensors, fetcher would be another example. Mind making the clean up more comprehensive?

Never mind. I think it should be better to make the metric removal logic consistent. Let me take some time to look for these cases.

**Comment by yufeiyan1220** [comment]
> Seems like we aren't particularly consistent at removing these metrics and sensors, fetcher would be another example. Mind making the clean up more comprehensive?

I have made the change that is ensure all metrics about consumer are removed after shutting down. When it comes to producer, I found that all producer metrics are already closed, so I don't need to add more stuff for producer.

**Comment by philipnee** [comment]
hey @cmccabe - would you have time to take a look at this?

**Review by guozhangwang — COMMENTED** [review]
I made a pass and it looks good to me! I think it's appropriate to close the sensors in its corresponding `close` function.

One concern I have though, is that there's a `throttleTimeSensor` created inside fetcher, but is be recorded inside the `NetworkClient / Selector`. In consumer's closing ordering, we close the `fetcher` first (and hence its sensors) and then the `client`. Hence there's a possible race condition if we add the logic to close the throttle sensor in the fetcher, where the `throttleTimeSensor` is closed when fetcher is closed, but the unclosed network client still tries to record it.

After checking the history, I think we did in this way today just to respect the history that this sensor/metric has the group name as `fetcher-manager` but it really just be inside the network client / selector. So I think we can just add the close logic inside the network client with the `if` condition if it is not `null`.

Otherwise, LGTM! Good job @yufeiyan1220

**Comment by philipnee** [comment]
Thanks @guozhangwang - A comment I have here is, would it be more convenient to close/remove all the metrics and sensors in the Metrics class upon closing instead of relying on these sub metrics to remove the metrics/sensors? It seems fine to just remove the registered sensros and metrics upon closing the Metrics obj.

**Comment by guozhangwang** [comment]
The concern I had is that, the same metrics registry object is used across multiple nested classes, while some of those classes may be closed and re-created along the lifetime of the client, and if we only try to close the metrics registry once upon closing the client, we may miss those events.

**Comment by guozhangwang** [comment]
@yufeiyan1220 just following up on this PR. Do you want to address the latest comment, I'm thinking if we can just move `throttleTimeSensor` to the Selector while keeping its group name a special case to avoid breaking compatibility?

**Comment by yufeiyan1220** [comment]
> throttleTimeSensor

Sorry for my late reply because I am busy doing some other work.... Yeah, I am ready to do it now.
I found that `throttleTimeSensor` uses `FetcherMetricsRegistry` as creation parameter. Which one is better to move `throttleTimeSensor` into `NetworkClient`, with `FetcherMetricsRegistry` as the parameter to create `throttleTimeSensor` within the `NetworkClient`, or just a removal logic when closing the `NetworkClient`?

**Pull request closed without merging**
