### PR TITLE
KAFKA-16954: fix consumer close to release assignment in background

### PR DESCRIPTION
**Pull request by lianetm**
This PR fixes consumer close to avoid updating the subscription state object in the app thread. Now the close simply triggers an UnsubscribeEvent that is handled in the background to trigger callbacks, clear assignment, and send leave heartbeat. Note that after triggering the event, the unsubscribe will continuously process background events until the event completes, to ensure that it allows for callbacks to run in the app thread.

The logic around what happens if the unsubscribe fails remain unchanged: close will log, keep the first exception and carry on.  

It also removes the redundant LeaveOnClose event (it used to do the the exact same thing as the UnsubscribeEvent, both  calling membershipMgr.leaveGroup).

### CODE REVIEW

**Comment by lianetm** [comment]
Hey @lucasbru , this is the follow-up fix for the related race around close updating the subscription state in the app thread. PTAL. Thanks!
cc. @dajac

**Comment by lianetm** [comment]
@jlprat we would need this blocker into 3.8. Note this is not production-ready code since KIP-848 in only going out as Preview in 3.8 (so pushing this fix for a race condition affecting consumer close that we discovered, to make KIP-848 preview better). Makes sense? Thanks!

**Comment by jlprat** [comment]
Is there any way to have this merged before we start making RCs for 3.8.0?

**Comment by lucasbru** [comment]
@lianetm The general idea looks good to me, but we have a lot of failing integration tests with this change.

**Comment by lianetm** [comment]
Hey @lucasbru , solved. Issue was that all those integration tests do close with zero timeout, and in that scenario the legacy logic does not propagate a timeout exception while leaving the group (and I was propagating it here). The legacy logic just triggers the leave and waits if it has time. If it doesn't, it just logs a warn [here](https://github.com/apache/kafka/blob/09b4ef416aa54a4e65b297f7e6b47a04e88556f5/clients/src/main/java/org/apache/kafka/clients/consumer/internals/AbstractCoordinator.java#L1130-L1141)). So I just did the same on the new consumer. Tried several of the integration test files that were failing and they pass locally now. I'm running them all now while the build here completes. Thanks!

**Comment by lianetm** [comment]
Hey @lucasbru , build completed with 6 unrelated test failures:

> Build / JDK 8 and Scala 2.12 / testReplicateFromLatest() – org.apache.kafka.connect.mirror.integration.IdentityReplicationIntegrationTest
> Build / JDK 8 and Scala 2.12 / testCleanerThreadShutdown() – kafka.log.remote.RemoteIndexCacheTest
> Build / JDK 21 and Scala 2.13 / testFenceMultipleBrokers() – org.apache.kafka.controller.QuorumControllerTest
> Build / JDK 21 and Scala 2.13 / testTaskRequestWithOldStartMsGetsUpdated() – org.apache.kafka.trogdor.coordinator.CoordinatorTest
> Build / JDK 21 and Scala 2.13 / testAlterSinkConnectorOffsetsOverriddenConsumerGroupId() – org.apache.kafka.connect.integration.OffsetsApiIntegrationTest
> Build / JDK 21 and Scala 2.13 / testMigrateTopicDeletions [9] Type=ZK, MetadataVersion=4.0-IV0,Security=PLAINTEXT – kafka.zk.ZkMigrationIntegrationTest

Thanks!

**Review by lucasbru — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
