### PR TITLE
MINOR: A few cleanups in BrokerToControllerChannelManager

### PR DESCRIPTION
**Pull request by dajac**
I made a few edits to make the code style more consistent while reading that file.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
Maybe we can use the file in checkstyle/checkstyle.xml to force scala code style, but this is a big change and should be done with the approval of at least 3 PMC members. 🤔

**Comment by dajac** [comment]
@showuon Could you review this one? The changes are trivial.

**Comment by showuon** [comment]
I'll check later.

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the cleanup.

**Comment by showuon** [comment]
Failed tests are unrelated:
```
    Build / JDK 17 and Scala 2.13 / org.apache.kafka.streams.integration.PurgeRepartitionTopicIntegrationTest.shouldRestoreState
    Build / JDK 17 and Scala 2.13 / org.apache.kafka.streams.integration.PurgeRepartitionTopicIntegrationTest.shouldRestoreState
    Build / JDK 8 and Scala 2.12 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationSSLTest.testReplication()
    Build / JDK 8 and Scala 2.12 / org.apache.kafka.connect.integration.ExampleConnectIntegrationTest.testSinkConnector
    Build / JDK 8 and Scala 2.12 / kafka.api.PlaintextEndToEndAuthorizationTest.testNoConsumeWithoutDescribeAclViaSubscribe()
    Build / JDK 8 and Scala 2.12 / org.apache.kafka.streams.integration.PurgeRepartitionTopicIntegrationTest.shouldRestoreState
    Build / JDK 8 and Scala 2.12 / org.apache.kafka.streams.integration.NamedTopologyIntegrationTest.shouldAllowRemovingAndAddingNamedTopologyToRunningApplicationWithMultipleNodesAndResetsOffsets
    Build / JDK 11 and Scala 2.13 / org.apache.kafka.streams.integration.PurgeRepartitionTopicIntegrationTest.shouldRestoreState
```

**Pull request merged**
