### PR TITLE
MINOR: Remove GroupMetadataManager#isGroupOpenForProducer unused method

### PR DESCRIPTION
**Pull request by m1a2st**
I found GroupMetadataManager#isGroupOpenForProducer didn't use in project, thus we should remove it.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
I retriggered the CI build as it was aborted

**Comment by m1a2st** [comment]
@jlprat, Thanks for your triggered, I will check this problem

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by jlprat** [comment]
@m1a2st there might not be anything for you to check. Let us wait for CI to finish (some hours) then we can see if your change can be merged :)
Thanks for the PR!

**Comment by chia7712** [comment]
```
/home/jenkins/jenkins-agent/workspace/Kafka: No space left on device
```
@m1a2st  today is not your day

**Comment by chia7712** [comment]
The failed tests pass on my local and I believe they are unrelated to this PR. will merge it

**Pull request merged**
