### PR TITLE
KAFKA-17451: Remove deprecated consumer#committed

### PR DESCRIPTION
**Pull request by mingyen066**
* Remove deprecated `consumer#committed`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@mingyen066 Could you please add this change to `upgrade.html`?

**Comment by mingyen066** [comment]
> @mingyen066 Could you please add this change to upgrade.html?

Change added

**Comment by chia7712** [comment]
@mingyen066 could you please rebase code?

**Comment by mingyen066** [comment]
rebased

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
