### PR TITLE
KAFKA-5412: Using connect-console-sink/source.properties raises an exception related to "file" property not found

### PR DESCRIPTION
**Pull request by ppatierno**

### CODE REVIEW

**Review by rhauch — APPROVED** [review]
Looks great, @ppatierno. Thanks for the contribution!

**Comment by ppatierno** [comment]
@ijuma @rhauch wouldn't it be useful having this merged for the 0.11.0.0 release ? I have just see the vote for the RC1 this morning. What do you think ?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5466/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by ppatierno** [comment]
Retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5467/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5452/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
@ppatierno at this point, only blockers would be reason for spinning a new RC. I'll leave it to @ewencp to make that call for this PR.

**Comment by ppatierno** [comment]
@ijuma ok thanks. Just asking as a newbie contributor on the project ;)

**Comment by ewencp** [comment]
Yeah, this isn't really a blocker since it is an example, and in fact it looks like if it was a regression then it happened over a year ago!

But the fix LGTM, thanks for the contribution @ppatierno!

**Pull request closed without merging**
