### PR TITLE
KAFKA-10559: Not letting TimeoutException shutdown the app during internal topic validation

### PR DESCRIPTION
**Pull request by vamossagar12**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ableegoldman** [comment]
LGTM

Looks like the Java 8 build may have stalled? The Java 11 & 15 builds both passed a while ago

**Comment by mjsax** [comment]
Thanks for the PR @vamossagar12!

No ideal to just remove the test instead of adjusting them, but we can do this in a follow up PR. @ableegoldman told me she will take care of it.

Merged to `trunk` and cherry-picked to `2.7` branch.

**Comment by mjsax** [comment]
Follow up PR: https://github.com/apache/kafka/pull/9446

**Comment by vamossagar12** [comment]
Thanks @mjsax . I thought these were time out related tests so ended up removing them. Thanks for the feedback :)

**Comment by mjsax** [comment]
Well, that are timeout related: they checked if we send the shut-down signal. After the change, they should check if the `TimeoutException` is thrown and only kills the local thread. :)

**Pull request merged**
