### PR TITLE
MINOR: Exclude PULL_REQUEST_TEMPLATE.md from rat checks

### PR DESCRIPTION
**Pull request by ijuma**
### Committer Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
FAILURE
 4020 tests run, 1 skipped, 1 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8067 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Pull request closed without merging**
