### PR TITLE
KAFKA-12359: Update Jetty to 11

### PR DESCRIPTION
**Pull request by dongjinleekr**
1. Add new dependency for Jetty 11.

  - javax.ws.rs:jsr311-api:1.1.1
  - jakarta.servlet:jakarta.servlet-api:5.0.0

2. Update the Java EE related dependency names. (see: [#1](https://webtide.com/renaming-from-javax-to-jakarta/) [#2](https://wiki.eclipse.org/Jakarta_EE_Maven_Coordinates))

  - javax.activation:activation:1.1.1 -> com.sun.activation:javax.activation:1.2.0
  - javax.ws.rs:javax.ws.rs-api 2.1.1 -> jakarta.ws.rs:jakarta.ws.rs-api 3.0.0.
  - javax.xml.bind:jaxb-api:2.3.0 -> jakarta.xml.bind:jakarta.xml.bind-api:2.3.0

3. Change all `javax.ws.rs.*` imports into `jakarta.ws.rs.*`.

4. Make Jackson to be compatible with new Jakarta API.

  - Add jakarta classifier to jackson-jaxrs-json-provider for compatibility with jakarta.ws.rs-api. (see: [here](https://stackoverflow.com/questions/26207252/messagebodywriter-not-found-for-media-type-application-json))
  - Add org.glassfish.jersey.media:jersey-media-json-jackson:3.0.1 dependency for registering jackson as a `MessageBodyWriter`.

5. Upgrade jersey from 2.31 to 3.0.1.
6. Upgrade Jetty to 11.0.2 and apply the API changes.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
The first commit addresses the [Java 11 Migration (KAFKA-12358)](https://issues.apache.org/jira/browse/KAFKA-12358) issue. If the community decides to migrate into Java 11, I will separate it into an independent PR.

**Comment by dongjinleekr** [comment]
For those who are curious about how the Jetty 11 upgrade would be, here is the latest draft with Jetty 11.0.2.

**Comment by ijuma** [comment]
We are not planning to upgrade to Java 11 any time soon. Can you please submit a PR for the latest Jetty version that supports Java 8 still?

**Comment by dongjinleekr** [comment]
For those who are interested in this issue, here is some context:

As you can see in the table below (from [here](https://www.eclipse.org/jetty/)), the change between Jetty 9.4 and Jetty 11 is not only Servlet versions; it involves Servlet version, package namespace, API changes, and related dependencies. For this reason, Upgrading Jetty from 9.4 is never a simple task but a complicated one that requires lots of changes, tests, etc.

Eclipse-Jetty-The-Eclipse-Foundation

The problem is: **the current 9.4's End of Life seems not a too distant future**; For instance, [Jetty 9.2 reached the end of life in March 2018](https://www.eclipse.org/lists/jetty-announce/msg00116.html), and [9.3 also did in February 2020](https://www.eclipse.org/lists/jetty-announce/msg00140.html) (i.e., in two years). 9.3 also dropped Java 7 support from before its final release. Although the Jetty team does not mention it explicitly, the community seems to expect it to reach the EOL in 2022 when Jetty 10.x and 11.x becomes stable and widespread. If this thing happens, we should also migrate to Jetty 11, along with Java 11.

I agree with @ijuma that it is too early to discuss this issue. However, I think we have enough reason to recognize this problem. **I will keep my eyes on Jetty 9.4's EOL issue and as soon as it becomes certain, I will reopen the PR.**

+1. For those who hope to test Kafka Connect on Servlet 5: I will start providing a preview soon like [log4j2 appender](http://home.apache.org/~dongjin/post/apache-kafka-log4j2-support/).

**Comment by tommyk-gears** [comment]
Any update on this? Jetty 9.4 will not reach EOL until the last Webtide customer has migrated away from it (which may take forever more or less). It did however reach "End of community support" back in June 2022. Even Jetty 11 that this PR is migrating _to_ has already reached "End of community support".
My gut feeling is that Jakarta EE 9+ has gained some good traction over last years (at least in the echo system at our company kafka-connect is the only thing still holding on to Java EE 8 afaik).

References:
Jetty 9.4 EOCS: https://github.com/jetty/jetty.project/issues/7958
Jetty 11 EOCS: https://github.com/jetty/jetty.project/issues/10485

**Comment by cshannon** [comment]
I started a new [thread](https://lists.apache.org/thread/p4qbqh8r77h4khn3yoof2b0gbq3wbc5q) on the dev list about this. I think it's very important to upgrade for Kafka 4.0 as many libraries have moved away from javax namespace. Would it be possible to re-open and update this PR?

**Pull request closed without merging**
