### PR TITLE
KAFKA-4932: Update docs for KIP-206

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei 

Note: I also updated "Custom Serde" section in addition. This need to get into `2.1` branch, too.

Did not find any relevant docs for consumer/producer to update. Did I miss them? \cc @hachikuji

**Comment by mjsax** [comment]
Call for review @JimGalasyn

**Review by bbejeck — APPROVED** [review]
Thanks @mjsax LGTM

**Review by ewencp — APPROVED** [review]
LGTM

**Review by guozhangwang — APPROVED** [review]

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.1` branch.

**Pull request merged**
