### PR TITLE
KAFKA-13128: wait for all keys to be fully processed in #shouldQueryStoresAfterAddingAndRemovingStreamThread

### PR DESCRIPTION
**Pull request by ableegoldman**
This test is flaky due to waiting on all records to be processed for only a single key before issuing IQ lookups and asserting whether data was found. See [this comment](https://issues.apache.org/jira/browse/KAFKA-13128?focusedCommentId=17385841&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17385841) for full analysis on how this happened

Should be cherrypicked to 3.0 (test fix to help stabilize the build @kkonstantine ) and to 2.8

### CODE REVIEW

**Comment by ableegoldman** [comment]
cc @PhilHardwick @cadonna @wcarlson5 @lct45 @vvcephei

**Comment by PhilHardwick** [comment]
Thank so much for fixing this - your change is what I had intended for this test!

**Review by PhilHardwick — APPROVED** [review]

**Review by wcarlson5 — APPROVED** [review]
LGTM, would we want to add threads after producing the records too?

**Comment by ableegoldman** [comment]
@wcarlson5 yeah I think we can flesh this test out even more, but I'm going to merge this fix for now so we can help stabilize the 3.0 release branch (and because we actually got a fully green build for once 🥳 )

Maybe one of us can just tack that on to some other small PR

**Comment by ableegoldman** [comment]
Merged to trunk and cherrypicked back to 2.8 and 3.0 (test fix @kkonstantine )

**Pull request merged**
