### PR TITLE
MINOR: Ensure `ignorable` is a boolean value.

### PR DESCRIPTION
**Pull request by alecthomas**

### CODE REVIEW

**Review by tombentley — APPROVED** [review]

**Comment by dajac** [comment]
@alecthomas Thanks for the patch. How have you found this? Does it cause any failures?

**Comment by alecthomas** [comment]
It does yes. I found it because I'm looking at generating encoders/decoders from these files.

**Review by chia7712 — APPROVED** [review]
@alecthomas thanks for your patch. LGTM

**Comment by chia7712** [comment]
> Does it cause any failures?

According to source code (https://github.com/FasterXML/jackson-databind/blob/2.10/src/main/java/com/fasterxml/jackson/databind/deser/std/NumberDeserializers.java#L242), it should be fine to use "true" (string type). However, I like consistent value (boolean type) :)

**Comment by dajac** [comment]
> > Does it cause any failures?
> 
> According to source code (https://github.com/FasterXML/jackson-databind/blob/2.10/src/main/java/com/fasterxml/jackson/databind/deser/std/NumberDeserializers.java#L242), it should be fine to use "true" (string type). However, I like consistent value (boolean type) :)

Sounds good, thanks for the clarification.

**Review by dajac — APPROVED** [review]

**Comment by chia7712** [comment]
```
Build / JDK 11 and Scala 2.13 / kafka.server.RaftClusterTest.testCreateClusterAndCreateAndManyTopicsWithManyPartitions()
org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationSSLTest.testReplicationWithEmptyPartition()
Build / JDK 8 and Scala 2.12 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationSSLTest.testReplication()
```

unrelated error

**Pull request merged**
