### PR TITLE
MINOR: don't throw CommitFailedException during suspendTasksAndState

### PR DESCRIPTION
**Pull request by dguy**

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang @mjsax as discussed offline. We don't need to throw `CommitFailedException` during `onPartitionsRevoked`

**Review by mjsax — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
retest this please.

**Review by guozhangwang — APPROVED** [review]
Merged to trunk with a TODO comment.

**Pull request closed without merging**
