### PR TITLE
MINOR: Add NullPayloadGenerator to Trogdor

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by cmccabe** [comment]
Failed test is `kafka.api.CustomQuotaCallbackTest.testCustomQuotaCallback`, not related

**Comment by cmccabe** [comment]
retest this please

**Comment by apovzner** [comment]
LGTM

**Review by rajinisivaram — APPROVED** [review]
@cmccabe Thanks for the PR, LGTM.

**Comment by rajinisivaram** [comment]
Merging to trunk.

**Pull request merged**
