### PR TITLE
KAFKA-5006: Improve thrown exception

### PR DESCRIPTION
**Pull request by guozhangwang**
1. Only log an ERROR on the first encountered exception from the callback.

2. Wrap the exception message with the first thrown message information, and throw the exception whenever `checkException` is called.

Therefore, for the `store.put` call, it will throw a `KafkaException` with the error message a bit more intuitive.

### CODE REVIEW

**Comment by guozhangwang** [comment]
@xvrl @enothereska @dguy @mjsax for reviews.

**Review by mjsax — COMMENTED** [review]
Can we add a test for this? Or do you think it's not worth testing?

**Comment by guozhangwang** [comment]
I think it does not worth adding a new test for this.

Also note that although `store.put` may still throw a `KafkaException` or `StreamException`, since it is not documented in javadocs users should not expect to capture them at all in their own code, especially `try-catch` all exceptions like:

```
try {
    store.put(key, value);
catch (Exception e) {   // or even catch (Throwable t)
    // handle them..
}
```

cc @xvrl

**Comment by xvrl** [comment]
@guozhangwang just because it's not documented doesn't mean people will not catch them. Typically users will want to make their code resilient against any exception they've encountered in practice. Especially if they experience undocumented exception, they will be more likely to act defensively and try to catch anything. Can we at least document under what circumstances they might encounter streams or Kafka exception and what the user is expected to do in those cases?

**Comment by guozhangwang** [comment]
@xvrl Some of my thoughts:

1) As discussed offline, currently the Kafka clients javadoc only documents exceptions that users need to expect and catch themselves (e.g. `producer.abortTransaction` only document `ProducerFencedException`, thought it can also throw `KafkaException` which could only be possible due to a bug). We can debate whether this is a good pattern in practice or not, but currently Streams is following the same pattern as we do for clients.

2) For the specific case of `store#put/delete/etc` throwing `KafkaException`, I agree that there are different options we have; for example we can choose to completely abstract such exceptions from users to only "remember" the exception at the lower level, and skip the user-facing APIs and only throw it in a higher-level inner class, e.g. `StreamTask` or even higher-level `StreamThread`. Doing so would make the code more complicated but maybe worth doing, and that is why we have this umbrella story of https://issues.apache.org/jira/browse/KAFKA-5156 trying to keep track of all such cases and let people discuss what are the best approach.

3) Nevertheless, we should not ever encourage users to apply the `try-catch-Throwable` or `try-catch-Exception` pattern; though admittedly we also do that on some inner classes this is not a good design pattern and should be avoid as much as possible. With that in mind I think documenting the exception in javadoc is OK, and we can discuss if we want to do even further as proposed in 2) above in a separate PR.

**Comment by guozhangwang** [comment]
@dguy Could you take a final look at this PR?

**Comment by dguy** [comment]
retest this please

**Review by dguy — APPROVED** [review]
Thanks @guozhangwang, LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6201/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6185/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
retest this please.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6268/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6252/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
@dguy ping.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6484/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6469/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by dguy** [comment]
@guozhangwang, i already LGTM! Feel fee to merge

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
