### PR TITLE
MINOR: Fix log entry in FetchSessionHandler to specify throttle correctly

### PR DESCRIPTION
**Pull request by rajinisivaram**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by dajac — APPROVED** [review]
LGTM, thanks!

**Review by omkreddy — APPROVED** [review]

**Comment by cmccabe** [comment]
LGTM

**Comment by rajinisivaram** [comment]
retest this please

**Comment by rajinisivaram** [comment]
@dajac @omkreddy @cmccabe Thanks for the review, merging to trunk.

**Pull request merged**
