### PR TITLE
MINOR: Fixed ConsumerRecord constructor javadoc

### PR DESCRIPTION
**Pull request by sslavic**
Refactoring of ConsumerRecord made in https://github.com/apache/kafka/commit/0699ff2ce60abb466cab5315977a224f1a70a4da#diff-fafe8d3a3942f3c6394927881a9389b2 left ConsumerRecord constructor javadoc inconsistent with implementation.

This patch fixes ConsumerRecord constructor javadoc to be inline with implementation.

### CODE REVIEW

**Comment by ijuma** [comment]
A minor comment, LGTM otherwise.

**Comment by sslavic** [comment]
Made it explicit in ConsumerRecord constructor key parameter javadoc that null key is allowed, as suggested by @ijuma.

**Comment by guozhangwang** [comment]
retest this please (for the asfbot)

**Comment by ijuma** [comment]
@sslavic, I've been told by Apache Infra that you can retrigger a build by closing and reopening the PR. Would you help us test this by doing it please?

**Comment by sslavic** [comment]
@ijuma it worked, job was triggered https://builds.apache.org/job/kafka-trunk-git-pr/57/
But IMO that's not as nice as adding a comment, request to retest.

**Comment by ijuma** [comment]
@sslavic thanks. I agree that this is not ideal. It's just a workaround for now until we have a better way. See https://issues.apache.org/jira/browse/BUILDS-102

**Comment by sslavic** [comment]
@ijuma one thing which remains to be consistent - core tests fail for javadoc PR :)
I don't see from build log which test was it that failed.

**Comment by ijuma** [comment]
Frustrating!

**Comment by guozhangwang** [comment]
@sslavic @ijuma There is no specific test failure, all I can tell is that seems to be a transient build failure. Anyways, this LGTM.

kafka.KafkaTest > testGetKafkaConfigFromArgs PASSED

kafka.server.LogRecoveryTest > testHWCheckpointNoFailuresSingleLogSegment PASSED
:core:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':core:test'.
  > Process 'Gradle Test Executor 2' finished with non-zero exit value 1

**Comment by guozhangwang** [comment]
@sslavic Just to be consistent with the commit message title:

https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes#ContributingCodeChanges-PullRequest

Could you change your title to MINOR: .... ?

**Comment by sslavic** [comment]
@guozhangwang done. will do same for my other PRs

**Comment by guozhangwang** [comment]
LGTM.

**Comment by b-goyal** [comment]
Refactoring of ConsumerRecord made in https://github.com/apache/kafka/commit/0699ff2ce60abb466cab5315977a224f1a70a4da#diff-fafe8d3a3942f3c6394927881a9389b2 left ConsumerRecord constructor javadoc inconsistent with implementation.

This patch fixes ConsumerRecord constructor javadoc to be inline with implementation.

**Pull request closed without merging**
