### PR TITLE
MINOR: Add retry for CI

### PR DESCRIPTION
**Pull request by ex172000**
There are many flaky tests(see PR14814), adding retry can improve the test robustness.

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Note that The CI configuration already sets retries, we don't need a CI server configuration.

**Comment by ex172000** [comment]
> Thanks for the PR. Note that The CI configuration already sets retries, we don't need a CI server configuration.

Is the CI retry a global setting? It might make more sense if we just retry the failed ones from gradle?

**Comment by dajac** [comment]
Thanks for the PR. The Jenkins file already sets those settings to retry failed tests in cradle. See here: https://github.com/apache/kafka/blob/95f41d59b389b6f25000b7bc4ddb948cfdb90448/Jenkinsfile#L32.

I think that the confusion comes from the fact that the retired tests are still reported as failures. I am looking into improving this here: https://github.com/apache/kafka/pull/14743.

**Comment by ex172000** [comment]
> Thanks for the PR. The Jenkins file already sets those settings to retry failed tests in cradle. See here:
> 
> https://github.com/apache/kafka/blob/95f41d59b389b6f25000b7bc4ddb948cfdb90448/Jenkinsfile#L32
> 
> .
> I think that the confusion comes from the fact that the retired tests are still reported as failures. I am looking into improving this here: #14743.

Thank you @dajac for the explaination. That makes sense. Do you mind review #14829, looks like they are really flaky

**Comment by mimaison** [comment]
So should we close this PR and work on getting https://github.com/apache/kafka/pull/14862 merged instead?

**Pull request closed without merging**
