### PR TITLE
MINOR: Move streams-exmaples source files under src folder

### PR DESCRIPTION
**Pull request by guozhangwang**
Also remove some unused imports.

### CODE REVIEW

**Comment by guozhangwang** [comment]
streams-examples.jar was empty before.

@fpj @enothereska @ymatsuda Ping for reviews.

**Comment by guozhangwang** [comment]
Unit tests passed locally.

**Comment by ijuma** [comment]
LGTM

**Comment by ewencp** [comment]
@guozhangwang Running `./gradlew streams:test streams:examples:test` results in checkstyle failures here:

```
:streams:examples:checkstyleMain
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/JsonPOJODeserializer.java:19:1: Disallowed import - com.fasterxml.jackson.databind.ObjectMapper.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/JsonPOJOSerializer.java:20:1: Disallowed import - com.fasterxml.jackson.databind.ObjectMapper.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/JsonTimestampExtractor.java:20:1: Disallowed import - com.fasterxml.jackson.databind.JsonNode.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:20:1: Disallowed import - com.fasterxml.jackson.databind.JsonNode.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:21:1: Disallowed import - com.fasterxml.jackson.databind.node.JsonNodeFactory.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:22:1: Disallowed import - com.fasterxml.jackson.databind.node.ObjectNode.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:29:1: Disallowed import - org.apache.kafka.connect.json.JsonSerializer.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:30:1: Disallowed import - org.apache.kafka.connect.json.JsonDeserializer.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:95: 'method def modifier' have incorrect indentation level 28, expected level should be one of the following: 20, 24.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:97: 'member def type' have incorrect indentation level 32, expected level should be one of the following: 24, 28.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:97: 'method def' child have incorrect indentation level 32, expected level should be one of the following: 24, 28.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:99: 'method def' child have incorrect indentation level 32, expected level should be one of the following: 24, 28.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:102: 'method def rcurly' have incorrect indentation level 28, expected level should be one of the following: 20, 24.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview/PageViewUntypedJob.java:103: 'object def rcurly' have incorrect indentation level 24, expected level should be one of the following: 16, 20.
[ant:checkstyle] /Users/ewencp/kafka.git/streams/examples/src/main/java/org/apache/kafka/streams/examples/wordcount/WordCountProcessorJob.java:66:33: Array brackets at illegal position.
```

**Comment by guozhangwang** [comment]
@ewencp Thanks, will fix.

**Comment by guozhangwang** [comment]
@ewencp Ping again.

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
