### PR TITLE
MINOR: Put state args in correct order named repartition test

### PR DESCRIPTION
**Pull request by bbejeck**
Another system test that needs to be updated with states in the correct order

Kicked off another branch builder https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2252/

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @guozhangwang, @mjsax, and @vvcephei one last system test fix

**Review by guozhangwang — APPROVED** [review]
LGTM!

**Comment by bbejeck** [comment]
thanks @guozhangwang! Please don't merge this yet as the branch builder failed, I need to look into it more.

**Comment by bbejeck** [comment]
@guozhangwang 
Updated this to name the `state-store` which sets the name for the changelog topic.
  
Kicked off branch builder with 25 repeats and all tests passed 
http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2019-01-13--001.1547421420--bbejeck--MINOR_put_state_args_in_correct_order_named_repartition_test--7fff2ae/report.html

This is ready for merging now

**Comment by bbejeck** [comment]
thanks @guozhangwang!

**Pull request merged**
