### PR TITLE
MINOR: fix flaky Streams EOS system test

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @bbejeck @vvcephei

**Comment by mjsax** [comment]
We cannot guarantee that each instance gets a partitions from topic "data" assigned, thus, we need to change the expected message -- it's good enough to wait for processing 500 messages from any topic.

Triggered system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1479/

**Comment by mjsax** [comment]
This needs to be back ported to `1.1`, too.

**Review by guozhangwang — APPROVED** [review]
LGTM！Please feel free to merge after confirming the issue is fixed in system tests.

**Comment by mjsax** [comment]
Retest this please.

System test passed (repeat 10x). Will merge after green Jenkins build.

**Review by bbejeck — APPROVED** [review]

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `1.1` branch.

**Pull request merged**
