### PR TITLE
KAFKA-7833: Add StateStore name conflict check in InternalTopologyBuilder

### PR DESCRIPTION
**Pull request by chebbyChefNEQ**
*Summary of testing strategy (including rationale)
* Added two tests that calls `addGlobalStore` and `addStateStore` in two different orders
* Added check for name conflict with a global store in the `addStateStore` path

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Thanks for the PR. I looked into the code and the check to verify if names are overlapping is actually in `InternalTopologyBuilder` -- thus, the fix should there.

In `InternalTopologyBuilderTest`, there is already `shouldNotAllowToAddStoresWithSameName` - - but it only covers the case for two "regular" store. The bug is really for adding a regular store and global store with the same name. Seems, we also lack a test for adding two global stores with the same names.

Also note, that for adding a regular store first, and afterwards a global store, there seems to be not bug atm -- only if the global store is added first and the regular store second the issue is there. Thus, we should test both combinations.

Does this make sense?

**Comment by chebbyChefNEQ** [comment]
@mjsax Makes sense. I'll push out the change tonight 👍

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by chebbyChefNEQ** [comment]
@mjsax I might have misread something somewhere. How do I trigger test explicitly? https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes seems to suggest that tests are automatically triggered on PRs.

**Comment by mjsax** [comment]
Thanks for pointing it out. The info is not correct any more. I just updated the wiki.

ASF infra team decided to protect Jenkins and now builds need to be triggered by committers.

**Comment by mjsax** [comment]
Thanks for the PR! Merged to `trunk` and cherry-picked to `2.6` branch.

**Pull request merged**
