### PR TITLE
HOTFIX: Hotfix streams smoke test

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
I can confirm that sometimes system tests fail because the previous timeout was too close to completion time. Doubling to be safe.

**Comment by ijuma** [comment]
Thanks for the PR, LGTM.

**Comment by ijuma** [comment]
Merged to trunk. The change didn't merge cleanly in the 0.10.1 branch. @enothereska, would you like to submit the same change to 0.10.1 as well?

**Comment by enothereska** [comment]
@ijuma thanks. Probably there is no need to put in 0.10.1, but I can submit I suppose.

**Comment by ijuma** [comment]
@enothereska, we run system test builds for 0.10.1 on a nightly basis, so it would be good to avoid transient failures in that branch too.

**Comment by enothereska** [comment]
Ok @ijuma https://github.com/apache/kafka/pull/2154 Thanks.

**Pull request closed without merging**
