### PR TITLE
MINOR Fix conditional in Update Test Catalog workflow

### PR DESCRIPTION
**Pull request by mumrah**
This is another GHA bool/string issue.

### CODE REVIEW

**Comment by mumrah** [comment]
Verified that we don't publish after a timeout here https://github.com/mumrah/kafka/actions/runs/12448556752/job/34753637314

**Comment by mumrah** [comment]
Here we can see it uploading the test catalog in the absence of a timeout https://github.com/mumrah/kafka/actions/runs/12448950063

**Comment by mumrah** [comment]
@chia7712 or @mimaison PTAL if you can. At the moment, our trunk CI is not updating the test catalog due to this bug

**Review by chia7712 — APPROVED** [review]
If I recall correctly, we have encountered this issue before. :laughing:

**Comment by mumrah** [comment]
@chia7712 yes we have (for the composite workflows). It seems like booleans do not exist in a few parts of GHA :-/

**Pull request merged**
