### PR TITLE
MINOR: fix HTML

### PR DESCRIPTION
**Pull request by mjsax**
Call for review @abbccdda @guozhangwang 

This should go to 2.6 and I will also do a PR for kafka-site if necessary

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM!

**Comment by guozhangwang** [comment]
The kafka-site has already been updated, so yes you do need to have a separate PR for it :P

**Comment by mjsax** [comment]
Found one more tiny issue. Will merge if no objections raise.

kafka-site PR: https://github.com/apache/kafka-site/pull/283

**Review by abbccdda — APPROVED** [review]

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.6`.

**Pull request merged**
