### PR TITLE
MINOR: Fixed docs regarding caching default

### PR DESCRIPTION
**Pull request by ableegoldman**
The current docs are out of date regarding the default caching state.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ableegoldman** [comment]
@guozhangwang @bbejeck @mjsax @vvcephei

**Review by bbejeck — APPROVED** [review]
Nice catch! LGTM.

**Comment by bbejeck** [comment]
\cc @vvcephei

**Review by guozhangwang — APPROVED** [review]

**Comment by bbejeck** [comment]
will merge once jenkins passes

**Comment by bbejeck** [comment]
Java 11 failed with `kafka.server.LogOffsetTest.testGetOffsetsBeforeNow` 

retest this please

**Comment by bbejeck** [comment]
Thanks @ableegoldman!

Merged #6375 to trunk

**Pull request merged**
