### PR TITLE
MINOR: Add documentation of error handling logic added in 1.1.0

### PR DESCRIPTION
**Pull request by farmdawgnation**
Adds documentation of exception handling logic recently introduced into Kafka Streams.

### CODE REVIEW

**Comment by farmdawgnation** [comment]
@mjsax Documentation as requested. Let me know if I need something else.

/cc @dguy @guozhangwang

**Comment by mjsax** [comment]
Thanks a lot!

We should also list the new config in "API changes" section in `doc/streams/upgrade-guide.html`

**Comment by guozhangwang** [comment]
Note that in trunk (which should be for the coming `1.1.x` release) we have not yet added the umbrella section for `1.1.0` yet. I.e. we should have one paragraph at the beginning for

```

    <p>
        If you want to upgrade from 1.0.x to 1.1.0 you need to do the following....
    </p>
```

And then a separate section for

```
<h3><a id="streams_api_changes_110" href="#streams_api_changes_110">Streams API changes in 1.1.0</a></h3>

....

<p> Updates in <code>StreamsConfig</code>: </p>

...

```

Where in the `Updates in <code>StreamsConfig</code>` section we could list the newly added config.

**Comment by guozhangwang** [comment]
I have created https://github.com/apache/kafka/pull/4338 for another KIP that I have worked on, which adds the section for 1.1.0 release.

We can rebase and fill in the related changes in your KIP after this PR is merged

**Comment by farmdawgnation** [comment]
Okay, in the 8 days since I opened this PR the structure of the developer guide has totally changed.
I'm trying to patch my changes into the new format but there's nothing in the README about getting a working documentation site locally for testing, so I have no idea of what I'm doing is anywhere close to correct.

Both of these combine into a pretty frustrating situation.

Can someone point me to information how to get the doc site to work and/or add it to the README?

**Comment by mjsax** [comment]
Sorry for the big change @farmdawgnation ... I was not aware it this other PR myself. We are just heavily ramping up the docs for Kafka Streams atm...

You can deploy a local Apache web server to test the doc changes as describe in the wiki: https://cwiki.apache.org/confluence/display/KAFKA/Setup+Kafka+Website+on+Local+Apache+Server

**Comment by guozhangwang** [comment]
@farmdawgnation Sorry for the inconvenience the refactoring have brought in, myself also had a docs PR that needs to be rebased after that one.

Maybe it is easier for you to just create a new PR from the current new trunk?

**Comment by farmdawgnation** [comment]
Yeah that’s what I’ll do. Sorry for the delay. I’ve been sick. Hope to pick
this up again this week.

**Comment by farmdawgnation** [comment]
Closing this PR to redo it.

**Pull request closed without merging**
