### PR TITLE
MINOR: Improve test of log messages for dropped records

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @xdgrulez @mjsax

**Review by abbccdda — COMMENTED** [review]
Are we just trying to ensure the log message level is warning?

**Comment by cadonna** [comment]
@abbccdda Yes, that is important for that particular log messages since the corresponding metric `dropped-records` aggregates all dropped records. There is also PR #10897 that sets the log messages for dropped records due to expired windows to log level `DEBUG`.

**Review by showuon — APPROVED** [review]
LGTM! I was thinking that we can further filter the expected message in appender event stream, and assert not empty, but I think that doesn't make it better. :)
Thank you!

**Review by abbccdda — APPROVED** [review]
Makes sense, LGTM!

**Comment by cadonna** [comment]
Test failures are unrelated.

**Pull request merged**
