### PR TITLE
MINOR: Apply extra serialized rsync step to both parallel and serial paths

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@enothereska @ijuma @hachikuji @dguy Pinging all the folks annoyed by environmental issues. We should still fix the nightlies to do parallel vagrant up and I'm not sure why it's not enabled yet, but this makes the rsync fix work for both paths. I tested myself on AWS with both parallel and serial cluster up.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6155/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6139/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ijuma — APPROVED** [review]
LGTM if the system tests pass with this change.

**Comment by ewencp** [comment]
Fired off a job [here](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/989/), though given the massive failures from https://issues.apache.org/jira/browse/KAFKA-5608, who knows whether it'll be meaningful or not...

**Review by enothereska — APPROVED** [review]

**Comment by enothereska** [comment]
The system test didn't go through, but the patch looks reasonable.

**Comment by ijuma** [comment]
The system test run failed during rsync so that's a bit concerning. I restarted it.

**Comment by ewencp** [comment]
I believe [this](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/992) is the job you started. All the failures appear to be related to [the JmxTool issues](https://github.com/apache/kafka/pull/3547). However, now that that issue has been resolved, I've restarted the job once again after rebasing against the latest trunk, running how [here](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/997/).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6188/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6172/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by ewencp** [comment]
System tests [have passed](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/997/) now that the other patch went through, so committing and cherry-picking all the way back to 0.10.0

**Pull request closed without merging**
