### PR TITLE
KAFKA-1595; remove global lock from json parser

### PR DESCRIPTION
**Pull request by resetius**

### CODE REVIEW

**Comment by resetius** [comment]
This PR just removes global lock.
It can help to speed up the controller.
I recommend to use this patch together with https://github.com/apache/kafka/pull/2213

**Comment by ijuma** [comment]
Thanks for the PR. Can you please elaborate on why it's safe to remove the global lock?

**Comment by resetius** [comment]
Previously we used a global object `JSON`, now we create `JSON` on each `parseFull`. I think it can be done w/o locks.

**Comment by ijuma** [comment]
Have you measured the cost of creating a new parser each time? A change like this requires a few benchmarks to motivate it.

**Comment by resetius** [comment]
Reasonable. I'll try to do some benchmarks.

**Comment by resetius** [comment]
I got a strange memleak inside `new JSON`. Now I use `ThreadLocal` and assume that kafka uses constant number of threads. But of course a better solution is to use some modern json parser like json4s.

**Pull request closed without merging**
