### PR TITLE
KAFKA-18017: Fix call order for HB error and group manager

### PR DESCRIPTION
**Pull request by lianetm**
Fix to ensure that the group manager is notified about HB errors only after having propagated the error to the app thread via en ErrorEvent. This is to ensure that the app thread is aware of the error if ever there is an ongoing unsubscribe operation processing background events in the app thread.

### CODE REVIEW

**Comment by lianetm** [comment]
Hello @chia7712 , any chance you could take a look at this small fix? Thanks!

**Comment by chia7712** [comment]
@lianetm Thanks for the patch. The fix makes sense to me. Could you open a JIRA for it since it's a bug fix? Additionally, should we also fix `onFailure`? It similarly completes the ongoing unsubscribe before sending an `ErrorEvent`.

https://github.com/apache/kafka/blob/18199028a672fd973ac37bf26316994babc2a6da/clients/src/main/java/org/apache/kafka/clients/consumer/internals/AbstractHeartbeatRequestManager.java#L308

**Comment by lianetm** [comment]
Hi @chia7712, added the fix and test to the onFailure path too, good catch. Thanks for the review!

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
