### PR TITLE
MINOR: Introduced bnd to get kafka-clients OSGi compliant

### PR DESCRIPTION
**Pull request by rlenferink**

### CODE REVIEW

**Comment by rlenferink** [comment]
triggering builds

**Comment by rlenferink** [comment]
Build for JDK 9 failed, no space left with jenkins

> 08:54:36 Caused by: java.io.IOException: No space left on device
> 08:54:36 	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
> 08:54:36 	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:332)
> 08:54:36 	at com.esotericsoftware.kryo.io.Output.flush(Output.java:154)
 
EDIT: Looking at other Pull Requests, it is a problem with Jenkins

**Comment by rlenferink** [comment]
@hachikuji ping

**Comment by guozhangwang** [comment]
retest this please

**Comment by rlenferink** [comment]
@guozhangwang seems like all tests passed, can this be merged ?

**Pull request closed without merging**
