### PR TITLE
KAFKA-17369: Remove Reflections from logging and update licenses

### PR DESCRIPTION
**Pull request by gharris1727**
This is a follow up to #16604 to clean up some logging configurations and sync the licenses.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gharris1727** [comment]
I merged the other PR too eagerly. I verified the license changes with the steps in https://issues.apache.org/jira/browse/KAFKA-12622 .

PTAL @C0urante @mimaison @divijvaidya Thanks!

**Review by mimaison — APPROVED** [review]
LGTM

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by gharris1727** [comment]
Test failures appear unrelated, especially as this is a logging and license change.

**Pull request merged**
