### PR TITLE
KAFKA-15769: Fix wrong log with exception

### PR DESCRIPTION
**Pull request by GOODBOY008**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@dengziming PTAL , Thank you~

**Comment by divijvaidya** [comment]
Hi @GOODBOY008, thank you for the PR. 

Could you please help me understand the motivation of the PR? I observed that you have changed the logging such that instead of complete stack trace, we are only logging the message. Isn't printing the full stack trace more helpful for debugging?

**Comment by GOODBOY008** [comment]
@divijvaidya Thank you for your quick review. I made these changes just because these log with exception is not right way. 

In presence of multiple parameters, if the last argument in a logging statement is an exception, then SLF4J will presume that the user wants the last argument to be treated as an exception instead of a simple parameter:
```

logger.error("{}, {}! An exception occurred!", 
  "Hello", 
  "World", 
  new Exception("Custom exception"));
```
In the above snippet, the String message will be formatted based on the passed object details. We’ve used curly braces as placeholders for String parameters passed to the method.

In this case, the output will be:

```
ERROR packageName.NameOfTheClass - Hello, World! An exception occurred!
java.lang.Exception: Custom exception 
  at packageName.NameOfTheClass.methodName(NameOfTheClass.java:lineNo)
```
Just like kafka source code right case:
image

**Comment by divijvaidya** [comment]
I understand what you are saying but another way to solve it is to treat the last argument as actual exception i.e. remove any parameterized reference to it. e.g.

Before this PR:
```
logger.error("{}, {}! An exception occurred!", 
  "Hello", 
  new Exception("Custom exception"));
```

After this PR:

```
logger.error("{}! An exception occurred!", 
  "Hello", 
  new Exception("Custom exception"));
```

This is preferred because this retains the full stack trace in the log.

**Comment by GOODBOY008** [comment]
> I understand what you are saying but another way to solve it is to treat the last argument as actual exception i.e. remove any parameterized reference to it. e.g.
> 
> Before this PR:
> 
> ```
> logger.error("{}, {}! An exception occurred!", 
>   "Hello", 
>   new Exception("Custom exception"));
> ```
> 
> After this PR:
> 
> ```
> logger.error("{}! An exception occurred!", 
>   "Hello", 
>   new Exception("Custom exception"));
> ```
> 
> This is preferred because this retains the full stack trace in the log.

Ok, I will update by log exception with full stack trace.

**Review by hudeqi — APPROVED** [review]
LGTM, Can you check in the code base if there are other cases like this?

**Comment by GOODBOY008** [comment]
> LGTM, Can you check in the code base if there are other cases like this?

Yes , I'm willing to check all code like this.

**Comment by GOODBOY008** [comment]
@hudeqi I had check all ,there is no other cases like this.

**Review by divijvaidya — APPROVED** [review]

**Comment by divijvaidya** [comment]
Test failures are flaky and unrelated to this change.

**Pull request merged**
