### PR TITLE
KAFKA-5464: Follow up. Increase poll timeout

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Compare: https://github.com/apache/kafka/pull/3439#discussion_r125845931

\cc @ijuma @guozhangwang @dguy @enothereska @bbejeck 

Needs to go into `trunk`, `0.11.0` and `0.10.2`. Thx.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5929/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5914/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ijuma — APPROVED** [review]
LGTM, thanks. Are there any objections from the other reviewers?

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
LGTM.

**Comment by guozhangwang** [comment]
Merged to trunk, 0.11.0, 0.10.2.

**Pull request closed without merging**
