### PR TITLE
KAFKA-5413: Port fix to 0.10.2 branch

### PR DESCRIPTION
**Pull request by kelvinrutt**
Port KAFKA-5413 to the 0.10.2 branch

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3766/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5551/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5565/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by junrao** [comment]
@kelvinrutt : Thanks a lot for the patch. LGTM

**Comment by junrao** [comment]
Merged to 0.10.2.

**Comment by ijuma** [comment]
@kelvinrutt, can you please close this PR as it has been merged? (the auto-close only works if the target branch is `trunk`).

**Pull request closed without merging**
