### PR TITLE
KAFKA-8611 / KIP-221 documentation

### PR DESCRIPTION
**Pull request by lkokhreidze**
Added KIP-221 documentation

Screen Shot 2020-04-27 at 11 03 43 AM

Screen Shot 2020-04-27 at 10 56 37 AM

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lkokhreidze** [comment]
call for review @vvcephei @mjsax

**Comment by lkokhreidze** [comment]
test this please

**Comment by mjsax** [comment]
@lkokhreidze Did PR shows a conflict. Can you rebase it?

Btw: did you see the follow up question on the mailing list?

**Comment by lkokhreidze** [comment]
Hi @mjsax 

I've rebased the branch.
Do you mean comment by Guozhang in the voting thread? If not, I missed it and can't find anything new in the DISCUSS thread. Can you point me where was it asked?

**Comment by mjsax** [comment]
Yes, on the voting thread: I proposed to also deprecate `through()` via KIP-221 and Guozhang replied. But it's your KIP and I don't want to "hijack" it :) -- I am willing to do the follow up PR, if you agree on the change (I can also update the KIP itself). But won't do it without your consensus :)

**Comment by lkokhreidze** [comment]
Hi @mjsax 
Yup, see it now. I was the victim of my own email filter and missed your email :)
I responded in the voting thread and I created ticket for it https://issues.apache.org/jira/browse/KAFKA-10003 I may have time to work on it sometime next week but if you get there sooner I won't mind at all :) so gtg from my side and thanks for the info :)

**Pull request merged**
