### PR TITLE
MINOR: Improve GlobalKTable docs

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @miguno @JimGalasyn

**Review by JimGalasyn — APPROVED** [review]
LGTM

**Review by bbejeck — APPROVED** [review]
LGTM

**Review by miguno — APPROVED** [review]

**Review by vvcephei — APPROVED** [review]
LGTM. This is much clearer about the (lack of) guarantees.

**Comment by guozhangwang** [comment]
Cherry-picked to 2.1 as well since we do not have a 2.1.1 yet.

**Pull request merged**
