### PR TITLE
KAFKA-4090: Validate SSL connection in client

### PR DESCRIPTION
**Pull request by belugabehr**
Issue has been around for a while.  Will post update on JIRA.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gmcquillan** [comment]
Hey -- has there been any movement on this? Is there anything I can do to help push this forward? This is a constant source of frustration for my teams.

**Comment by belugabehr** [comment]
I documented my work on the ticket as well.  It got very little attention from the Kafka Dev Team and seems to be pretty out of date now (merge conflicts).  Will need someone internal to the project to take this baton and run with it.

https://issues.apache.org/jira/browse/KAFKA-4090

**Comment by finaut** [comment]
> I documented my work on the ticket as well. It got very little attention from the Kafka Dev Team and seems to be pretty out of date now (merge conflicts). Will need someone internal to the project to take this baton and run with it.
> 
> https://issues.apache.org/jira/browse/KAFKA-4090

It's hard to understand why such a serious error is being ignored. It's been reported many times in different forms. Without a fix for this, I can't see how it's possible to consider Kafka as Enterprise ready technology.

**Comment by showuon** [comment]
Sorry that this issue didn't get much attention. I went through all the discussions in JIRA, it looks like we had 3 solutions so far:
1. [KIP-498](https://cwiki.apache.org/confluence/display/KAFKA/KIP-498%3A+Add+client-side+configuration+for+maximum+response+size+to+protect+against+OOM)
2. PR: https://github.com/apache/kafka/pull/5940
3. this PR.

If possible, @belugabehr , could you help me understand why your solution is better than the other 2? Also, could you please help rebase with the latest code? I'll take a look these days. Thank you very much.

**Pull request closed without merging**
