### PR TITLE
KAFKA-3908; Set ReceiveBufferSize for socket used by Processor

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by lindong28** [comment]
SRE should be able to control the receive buffer size of sockets that are used to receive request from clients, for the same reason set receive buffer size for all other sockets in the server and client. However, we currently only set the send buffer size of this socket.

**Comment by ijuma** [comment]
Thanks for the PR. I think you meant to say `ReceiveBufferSize` in the title.

**Comment by lindong28** [comment]
@ijuma Yeah you are right. Fixed now.

**Comment by ijuma** [comment]
@lindong28, we call `serverChannel.socket().setReceiveBufferSize(recvBufferSize)` in `openServerSocket`. The documentation says:

``` java
     * Sets a default proposed value for the SO_RCVBUF option for sockets
     * accepted from this <tt>ServerSocket</tt>. The value actually set
     * in the accepted socket must be determined by calling
     * {@link Socket#getReceiveBufferSize()} after the socket
     * is returned by {@link #accept()}.
```

Have you verified that your change has an impact?

**Comment by lindong28** [comment]
@ijuma Thanks for the quick review. I have verified that my change has an impact.

**Comment by ijuma** [comment]
@lindong28 Thanks. Can we have a test then? It seems like the javadoc I quoted is not correct.

**Comment by lindong28** [comment]
@ijuma Sure, I will add a test for it..

**Pull request closed without merging**
