### PR TITLE
KAFKA-5708: jackson upgrade (2.8.5 -> 2.9.1)

### PR DESCRIPTION
**Pull request by dejan2609**
**_Prologue:_** PR #3116

**_Jackson release notes:_**
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9

**_Note:_** you may want to wait for [Jackson 2.9.1 release ](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.1)

@ewencp: FYI

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6596/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6581/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ewencp — COMMENTED** [review]
@dejan2609 With the dependency versioning fixed this LGTM. When's the release of 2.9.1 expected? We're not in a rush since 1.0.0 is where this change would go and it isn't scheduled until [October sometime](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=71764913). But I'd also like to make sure we don't lose track of this -- if it might be some time, we might want to tie this to a JIRA and mark it blocker for 1.0.0 since the patch itself is trivial.

**Comment by dejan2609** [comment]
@ewencp By the looks of Jackson 2.8 patch cadence I guess that 2.9.1 is due to in a month or so. 
I took the liberty to create related JIRA ticket: https://issues.apache.org/jira/browse/KAFKA-5708

**Comment by ijuma** [comment]
FYI, https://github.com/apache/kafka/pull/3619 includes a number of version bumps including Jackson.

**Comment by ijuma** [comment]
I will remove Jackson from #3619.

**Comment by ijuma** [comment]
There you go https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.1

**Comment by dejan2609** [comment]
Thanx @ijuma, I'll change and rebase my commit asap.

**Comment by dejan2609** [comment]
Note: my initial intention was to remove version forcing for `jackson-annotations`; however it seems that `jackson-databind 2.9.x` still can't resolve correct version for `jackson-annotations`.
I reported issue here: https://github.com/FasterXML/jackson-databind/issues/1763 (**_jackson-databind 2.9.1 is using jackson-annotations 2.9.0_**)

All-in-all: I opt to keep version forcing and just bump jackson version.

**Comment by dejan2609** [comment]
@ewencp, @ijuma: please review.

**Review by ijuma — APPROVED** [review]
LGTM, merged to trunk.

**Pull request closed without merging**
