### PR TITLE
KAFKA-7692: Fix ProduceStateManager SequenceNumber overflow.

### PR DESCRIPTION
**Pull request by mingaliu**
This is to fix Kafka 7692. The problem is at ProducerStateManager:Append(), 
it has those lines:
updatedEntry.addBatch(epoch, lastSeq, lastOffset, lastSeq - firstSeq, lastTimestamp)
and 
val firstOffset = lastOffset - (lastSeq - firstSeq)
However, lastSeq can wrap around and smaller than firstSeq. This will cause some exception later on (described in the JIRA 7692)

Test: Verified with local unitest and in our daily operation.

### CODE REVIEW

**Comment by ijuma** [comment]
Cc @hachikuji

**Review by hachikuji — COMMENTED** [review]
Thanks for the PR. The fix looks good. It would be helpful to have a test case while overflows the sequence number.

**Comment by mingaliu** [comment]
@hachikuji Thanks for the comments. I updated the PR with unitest.

**Comment by mingaliu** [comment]
Tested multiple times and succeed locally, the jenkins  is due to other random test failure. @hachikuji , please review.  Thanks!

**Comment by mingaliu** [comment]
Please review or sign off, @junrao , @hachikuji , thanks!

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch!

**Pull request merged**
