### PR TITLE
KAFKA-9409: Supplement immutability of ClusterConfigState class in Connect

### PR DESCRIPTION
**Pull request by belugabehr**
The class claims to be immutable, but there are some mutable features of this class.
Increase the immutability of it and add a little cleanup:

* Pre-initialize size of ArrayList
* Remove superfluous syntax
* Use ArrayList instead of LinkedList since the list is created once

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rondagostino — COMMENTED** [review]
LGTM

**Comment by kkonstantine** [comment]
ok to test

**Comment by kkonstantine** [comment]
jdk8: 1 flaky failure:  `EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[true]`
jdk11: didn't start
jdk14: success

**Review by kkonstantine — APPROVED** [review]
LGTM

**Pull request merged**
