### PR TITLE
MINOR: remove unneccessary public keyword from ProducerInterceptor/ConsumerInterceptor interface

### PR DESCRIPTION
**Pull request by KahnCheny**
remove unneccessary public keyword from ProducerInterceptor interface

### CODE REVIEW

**Review by showuon — COMMENTED** [review]
@KahnCheny , thanks for the PR. LGTM! Could you also remove the `public` keyword in `ConsumerInterceptor` ? Thank you.

**Comment by KahnCheny** [comment]
> @KahnCheny , thanks for the PR. LGTM! Could you also remove the `public` keyword in `ConsumerInterceptor` ? Thank you.

 Of course.

**Review by showuon — APPROVED** [review]
LGTM! @KahnCheny , thanks for the PR!

**Comment by KahnCheny** [comment]
Thanks

**Comment by KahnCheny** [comment]
jenkins pr-merge passes?

**Comment by showuon** [comment]
@KahnCheny , it looks like you made some change after I approved this PR. Now, there are 162 files changed. Could you check again? Thanks.

**Comment by KahnCheny** [comment]
merge trunk will be automatically updated, so I  submit a new PR, Thanks
for your and re-review ?
https://github.com/apache/kafka/pull/10801

Luke Chen ***@***.***> 于2021年6月1日周二 下午7:59写道：

**Pull request closed without merging**
