### PR TITLE
KAFKA-4322 StateRestoreCallback begin and end indication

### PR DESCRIPTION
**Pull request by markcshelton**
This adds a begin and end callback to StateRestoreCallback.

The contribution is my original work and I license the work to Apache Kafka under the Kafka's open source license.

### CODE REVIEW

**Comment by markcshelton** [comment]
Build failed for unknown reason

**Comment by markcshelton** [comment]
Build failed for unknown reason

**Comment by markcshelton** [comment]
Build failed for unknown reason

**Comment by markcshelton** [comment]
Build has been executing for 50 min on H18?

**Review by mjsax — COMMENTED** [review]
I like this overall. However, I am not sure about `StateRestoreCallbackContext`. Should it get split into an interface and default implementation?

\cc @guozhangwang

**Comment by guozhangwang** [comment]
I left some comments on the ticket itself.

**Comment by guozhangwang** [comment]
Closing for cleanup.

**Pull request closed without merging**
