### PR TITLE
TRIVIAL: Improve Admin Documentation

### PR DESCRIPTION
**Pull request by dongjinleekr**
This PR is a follow-up of #7087, fixing typos, styles, etc.

cc/ @big-andy-coates @ijuma

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
retest this please

**Comment by dongjinleekr** [comment]
Rebased onto the latest trunk.

**Comment by dongjinleekr** [comment]
retest this please

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by dongjinleekr** [comment]
Rebased onto the latest trunk.

cc/ @omkreddy

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by dongjinleekr** [comment]
Retest this please.

**Review by omkreddy — APPROVED** [review]
@dongjinleekr Thanks for the PR. LGTM.

**Pull request closed without merging**
