### PR TITLE
Kafka 2167

### PR DESCRIPTION
**Pull request by nssalian**
Changed ZkUtils.scala for KAFKA-2167

### CODE REVIEW

**Comment by nssalian** [comment]
@gwenshap could you please review this when you get a chance?
It's been here for a while

**Comment by ijuma** [comment]
@nssalian, it may be a good idea to fix your commits so that there isn't a "Revert" commit in the pull request.

**Comment by guozhangwang** [comment]
@nssalian Could you submit a patch against trunk instead following the review tool process:

https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes#ContributingCodeChanges-PullRequest

**Comment by guozhangwang** [comment]
Closing for cleanup.

**Pull request closed without merging**
