### PR TITLE
KAFKA-6157: Fix repeated words words in JavaDoc and comments. 

### PR DESCRIPTION
**Pull request by efeg**

### CODE REVIEW

**Comment by efeg** [comment]
retest this please

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 7173 tests run, 1 skipped, 1 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8050 tests run, 5 skipped, 0 failed.
--none--

**Comment by efeg** [comment]
retest this please

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8050 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8050 tests run, 5 skipped, 0 failed.
--none--

**Comment by becketqin** [comment]
Thanks for the patch LGTM.

**Pull request closed without merging**
