### PR TITLE
MINOR: Switch ZK client logging to INFO

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by junrao** [comment]
@ijuma : Thanks for the patch. LGTM. I will let you merge it.

**Comment by ijuma** [comment]
Will merge to 0.11.0 and trunk. Since this file is not exercised by unit and integration tests, I won't wait for Jenkins to complete.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5609/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5623/
Test PASSed (JDK 7 and Scala 2.11).

**Pull request closed without merging**
