### PR TITLE
KAFKA-7785: move internal DefaultPartitionGrouper

### PR DESCRIPTION
**Pull request by highluck**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by highluck** [comment]
@mjsax 
Would this be what you want?
thanks!

**Comment by ableegoldman** [comment]
Seems like we have two seemingly identical tickets & PRs for this -- https://github.com/apache/kafka/pull/10380
cc @guozhangwang @highluck

**Comment by guozhangwang** [comment]
@mjsax if you can review and merge @highluck 's PR let's do it, I can rebase the other afterwards.

**Comment by mjsax** [comment]
I think we should have only one PR -- not sure why you did pick it up Guozhang? The ticket was clearly assigned to @highluck 

@highluck -- the ticket is about _removing_ the config completely -- cf @guozhangwang PR.

**Comment by highluck** [comment]
@mjsax 
If so, can I proceed?

**Comment by mjsax** [comment]
@highluck Feel free to proceed (it would be somewhat double work, but I don't want to "take it away" from you). Happy to merge your PR instead of Guozhang's.

**Comment by highluck** [comment]
@mjsax 
thanks
I've updated the code

**Review by guozhangwang — APPROVED** [review]
LGTM! I think I can close the other PR while merging this one.

**Comment by highluck** [comment]
@guozhangwang 
thanks review 
@mjsax ping
Sorry to be busy, but please review! thanks!

**Comment by highluck** [comment]
@guozhangwang 
May I ask for a merge?

**Comment by guozhangwang** [comment]
Merged to trunk, thanks @highluck !

**Pull request merged**
