### PR TITLE
KAFKA-9127: don't create StreamThreads for global-only topology (2.4)

### PR DESCRIPTION
**Pull request by ableegoldman**
Copy of [pull/8540](https://github.com/apache/kafka/pull/8540) targeted at 2.4

### CODE REVIEW

**Comment by ableegoldman** [comment]
@vvcephei

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
retest this please

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
test this please

**Comment by ableegoldman** [comment]
@vvcephei  Both Java 11 builds passed, Java 8 failed with flaky 
`DynamicBrokerReconfigurationTest.testAddRemoveSaslListeners`
`BranchedMultiLevelRepartitionConnectedTopologyTest.testTopologyBuild`

(the Streams one is not related, it was converted to a unit test to reduce flakiness but that PR was not backported to 2.4)

**Comment by vvcephei** [comment]
Thanks @ableegoldman ! Merging...

**Pull request merged**
