### PR TITLE
KAFKA-8208: Change paper link directly to ASM

### PR DESCRIPTION
**Pull request by bbejeck**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @mjsax @MichaelDrogalis

**Comment by bbejeck** [comment]
\cc @JimGalasyn

**Comment by JimGalasyn** [comment]
cc @londoncalling

**Review by londoncalling — APPROVED** [review]
LGTM!

**Review by mjsax — APPROVED** [review]

**Comment by bbejeck** [comment]
Merged #6572 into trunk

**Comment by mjsax** [comment]
@bbejeck If the link is broken in older release, we should cherry-pick this to older branches, too. Otherwise, we get the broken link again when we do a bug fix release.

**Comment by bbejeck** [comment]
cherry-picked to 2.2 and 2.1

**Pull request merged**
