### PR TITLE
HOTFIX: renamed test so it is picked up by ducktape

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
@ewencp @mjsax or @guozhangwang

**Review by mjsax — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by enothereska** [comment]
Test passed: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/718/

**Review by guozhangwang — APPROVED** [review]
Merged to trunk and 0.10.2.

**Pull request closed without merging**
