### PR TITLE
Improving Fetch Session Caching for KAFKA-10558

### PR DESCRIPTION
**Pull request by ahuang98**
Fetch session cache performance is currently a blocker for increasing cache size.

[Edit 9/28] With commit f528df6, now following the original cache eviction logic. The following benchmark data for sessions_lastUsed has been updated to reflect this change. 

#### @lbradstreet
- JMH benchmark to log performance improvements
- making `EvictableKey`'s `compareTo` method faster
- restructuring of `tryEvict` [Edit 9/28 - partially reverted] 
- ~~restructuring of `touch`~~ [Edit 9/28 - reverted]
    - ~~`evictableBy` treemaps changed to store unprivileged and privileged sessions respectively~~

#### ahuang98
 - `sessions` turned into LinkedHashMap (from mutable.HashMap) to absorb function of `lastUsed`
    - entries in `sessions` are now ordered by the time the session was last touched
 -  ~~`evictableBy` treemaps renamed to `unprivilegedSessions` and `privilegedSesions`~~ [Edit 9/28 - reverted]
 - [Edit 9/28] `evictableByAll` updated to store only unprivileged sessions that have been touched > `evictionMs` after their creation
    - previously stored privileged sessions that had been touched > `evictionMs` after their creation as well, which was unnecessary as `evictEntry` was only ever called on `evictableByAll` if the new session was unprivileged (and unprivileged can never evict unstale privileged sessions)

## Testing
 - Unit test
    - ~~assertion in `testSessionCache` currently commented out due to misunderstanding of cache eviction behavior~~ [Edit 9/28 - reverted]
    - [Edit 9/28] new test added called `testSessionCacheEvictionRules`, which continues where `testSessionCache` left off, testing more combinations of [privileged, unprivileged], [smaller, larger], [stale, unstale] sessions trying to evict each other
 - JMH benchmark
    - [Edit 9/28] after reverting back to original cache eviction logic (and updating benchmark to include the case when fetch session size stays the same and when fetch session size increases), the benchmark was rerun on an aws ec2 instance with 5 warmup and 5 measurement iterations. It shows that the performance of the optimized code with cache size 5000 is better than performance of trunk with cache size 1000. The table below highlights a portion of the results (cache size 2000 removed for brevity). 

| benchPrivileged | cacheSize | cacheUtilization | fetchSessionAddedPartitions | newSession | numEvictableEntries | percentPrivileged | Mode | Cnt | sessions_lastUsed Score | sessions_lastUsed Error | trunk Score | trunk Error | Units |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| FALSE | 1000 | 99 | FALSE | FALSE | 0 | 10 | avgt | 5 | 2684.031 | 310.096 | 4436.728 | 91.48 | ns/op |
| FALSE | 1000 | 99 | FALSE | FALSE | 1 | 10 | avgt | 5 | 2611.156 | 261.744 | 4364.698 | 459.283 | ns/op |
| FALSE | 1000 | 99 | FALSE | FALSE | 10 | 10 | avgt | 5 | 2592.409 | 226.455 | 4342.929 | 11.88 | ns/op |
| FALSE | 1000 | 99 | FALSE | TRUE | 0 | 10 | avgt | 5 | 1135.636 | 226.186 | 2338.599 | 51.281 | ns/op |
| FALSE | 1000 | 99 | FALSE | TRUE | 1 | 10 | avgt | 5 | 1090.842 | 187.019 | 2244.938 | 16.262 | ns/op |
| FALSE | 1000 | 99 | FALSE | TRUE | 10 | 10 | avgt | 5 | 1205.874 | 163.137 | 2366.496 | 49.18 | ns/op |
| FALSE | 1000 | 99 | TRUE | FALSE | 0 | 10 | avgt | 5 | 2914.277 | 291.322 | 4636.73 | 85.494 | ns/op |
| FALSE | 1000 | 99 | TRUE | FALSE | 1 | 10 | avgt | 5 | 2795.851 | 320.944 | 4739.525 | 60.319 | ns/op |
| FALSE | 1000 | 99 | TRUE | FALSE | 10 | 10 | avgt | 5 | 2758.375 | 395.131 | 4565.73 | 123.265 | ns/op |
| FALSE | 1000 | 99 | TRUE | TRUE | 0 | 10 | avgt | 5 | 1138.057 | 215.631 | 2481.799 | 42.688 | ns/op |
| FALSE | 1000 | 99 | TRUE | TRUE | 1 | 10 | avgt | 5 | 1153.209 | 160.686 | 2361.695 | 223.737 | ns/op |
| FALSE | 1000 | 99 | TRUE | TRUE | 10 | 10 | avgt | 5 | 1167.731 | 156.937 | 2462.849 | 311.975 | ns/op |
| FALSE | 1000 | 100 | FALSE | FALSE | 0 | 10 | avgt | 5 | 2536.62 | 253.821 | 4429.647 | 129.688 | ns/op |
| FALSE | 1000 | 100 | FALSE | FALSE | 1 | 10 | avgt | 5 | 2552.363 | 290.637 | 4403.863 | 94.2 | ns/op |
| FALSE | 1000 | 100 | FALSE | FALSE | 10 | 10 | avgt | 5 | 2719.227 | 226.613 | 4490.728 | 451.676 | ns/op |
| FALSE | 1000 | 100 | FALSE | TRUE | 0 | 10 | avgt | 5 | 2020.613 | 237.905 | 4063.931 | 2124.466 | ns/op |
| FALSE | 1000 | 100 | FALSE | TRUE | 1 | 10 | avgt | 5 | 1887.49 | 277.308 | 3644.97 | 39.779 | ns/op |
| FALSE | 1000 | 100 | FALSE | TRUE | 10 | 10 | avgt | 5 | 1924.926 | 162.053 | 3794.089 | 65.17 | ns/op |
| FALSE | 1000 | 100 | TRUE | FALSE | 0 | 10 | avgt | 5 | 2854.754 | 254.033 | 4715.486 | 351.3 | ns/op |
| FALSE | 1000 | 100 | TRUE | FALSE | 1 | 10 | avgt | 5 | 2836.238 | 87.322 | 4562.898 | 366.507 | ns/op |
| FALSE | 1000 | 100 | TRUE | FALSE | 10 | 10 | avgt | 5 | 2896.398 | 179.845 | 4636.409 | 74.467 | ns/op |
| FALSE | 1000 | 100 | TRUE | TRUE | 0 | 10 | avgt | 5 | 1965.438 | 174.204 | 3683.458 | 54.7 | ns/op |
| FALSE | 1000 | 100 | TRUE | TRUE | 1 | 10 | avgt | 5 | 2006.538 | 138.899 | 3575.06 | 292.394 | ns/op |
| FALSE | 1000 | 100 | TRUE | TRUE | 10 | 10 | avgt | 5 | 1973.776 | 150.744 | 3680.105 | 311.529 | ns/op |
| FALSE | 5000 | 99 | FALSE | FALSE | 0 | 10 | avgt | 5 | 3814.783 | 308.839 | 7263.359 | 3569.287 | ns/op |
| FALSE | 5000 | 99 | FALSE | FALSE | 1 | 10 | avgt | 5 | 4032 | 327.804 | 6755.35 | 4460.69 | ns/op |
| FALSE | 5000 | 99 | FALSE | FALSE | 10 | 10 | avgt | 5 | 3943.826 | 303.445 | 6834.419 | 4304.774 | ns/op |
| FALSE | 5000 | 99 | FALSE | TRUE | 0 | 10 | avgt | 5 | 1741.143 | 25.107 | 3277.982 | 370.198 | ns/op |
| FALSE | 5000 | 99 | FALSE | TRUE | 1 | 10 | avgt | 5 | 1811.051 | 19.183 | 3075.932 | 355.452 | ns/op |
| FALSE | 5000 | 99 | FALSE | TRUE | 10 | 10 | avgt | 5 | 1755.726 | 62.321 | 3202.241 | 447.799 | ns/op |
| FALSE | 5000 | 99 | TRUE | FALSE | 0 | 10 | avgt | 5 | 4277.164 | 400.039 | 7695.309 | 4712.432 | ns/op |
| FALSE | 5000 | 99 | TRUE | FALSE | 1 | 10 | avgt | 5 | 4495.467 | 149.012 | 7157.815 | 5084.501 | ns/op |
| FALSE | 5000 | 99 | TRUE | FALSE | 10 | 10 | avgt | 5 | 4328.287 | 258.009 | 7284.502 | 4784.208 | ns/op |
| FALSE | 5000 | 99 | TRUE | TRUE | 0 | 10 | avgt | 5 | 1827.201 | 33.735 | 3252.389 | 331.854 | ns/op |
| FALSE | 5000 | 99 | TRUE | TRUE | 1 | 10 | avgt | 5 | 1812.893 | 96.06 | 3285.954 | 528.586 | ns/op |
| FALSE | 5000 | 99 | TRUE | TRUE | 10 | 10 | avgt | 5 | 1846.243 | 36.486 | 3205.397 | 699.758 | ns/op |
| FALSE | 5000 | 100 | FALSE | FALSE | 0 | 10 | avgt | 5 | 4030.801 | 302.56 | 7420.729 | 4290.428 | ns/op |
| FALSE | 5000 | 100 | FALSE | FALSE | 1 | 10 | avgt | 5 | 4012.937 | 532.884 | 6674.48 | 4269.636 | ns/op |
| FALSE | 5000 | 100 | FALSE | FALSE | 10 | 10 | avgt | 5 | 3950.678 | 361.499 | 6705.533 | 4174.262 | ns/op |
| FALSE | 5000 | 100 | FALSE | TRUE | 0 | 10 | avgt | 5 | 2963.612 | 356.913 | 5272.88 | 2960.224 | ns/op |
| FALSE | 5000 | 100 | FALSE | TRUE | 1 | 10 | avgt | 5 | 2950.102 | 365.079 | 5305.482 | 3082.805 | ns/op |
| FALSE | 5000 | 100 | FALSE | TRUE | 10 | 10 | avgt | 5 | 2988.179 | 482.812 | 5298.415 | 2916.132 | ns/op |
| FALSE | 5000 | 100 | TRUE | FALSE | 0 | 10 | avgt | 5 | 4449.98 | 288.919 | 7265.341 | 4296.304 | ns/op |
| FALSE | 5000 | 100 | TRUE | FALSE | 1 | 10 | avgt | 5 | 4310.16 | 280.63 | 7131.075 | 4212.237 | ns/op |
| FALSE | 5000 | 100 | TRUE | FALSE | 10 | 10 | avgt | 5 | 4493.523 | 335.859 | 6915.28 | 3832.782 | ns/op |
| FALSE | 5000 | 100 | TRUE | TRUE | 0 | 10 | avgt | 5 | 3111.5 | 324.112 | 6333.948 | 4655.366 | ns/op |
| FALSE | 5000 | 100 | TRUE | TRUE | 1 | 10 | avgt | 5 | 2851.528 | 387.506 | 5346.191 | 2603.39 | ns/op |
| FALSE | 5000 | 100 | TRUE | TRUE | 10 | 10 | avgt | 5 | 2919.653 | 576.149 | 5214.732 | 3531.086 | ns/op |
| TRUE | 1000 | 99 | FALSE | FALSE | 0 | 10 | avgt | 5 | 2312.858 | 308.792 | 4346.396 | 128.141 | ns/op |
| TRUE | 1000 | 99 | FALSE | FALSE | 1 | 10 | avgt | 5 | 2328.731 | 235.691 | 4336.846 | 111.44 | ns/op |
| TRUE | 1000 | 99 | FALSE | FALSE | 10 | 10 | avgt | 5 | 2193.93 | 223.112 | 4281.69 | 70.832 | ns/op |
| TRUE | 1000 | 99 | FALSE | TRUE | 0 | 10 | avgt | 5 | 985.672 | 202.489 | 2069.452 | 21.386 | ns/op |
| TRUE | 1000 | 99 | FALSE | TRUE | 1 | 10 | avgt | 5 | 951.886 | 229.803 | 1897.69 | 25.66 | ns/op |
| TRUE | 1000 | 99 | FALSE | TRUE | 10 | 10 | avgt | 5 | 1004.162 | 180.472 | 2041.772 | 988.194 | ns/op |
| TRUE | 1000 | 99 | TRUE | FALSE | 0 | 10 | avgt | 5 | 2454.62 | 312.529 | 4638.253 | 1152.913 | ns/op |
| TRUE | 1000 | 99 | TRUE | FALSE | 1 | 10 | avgt | 5 | 2418.724 | 283.855 | 4497.284 | 120.397 | ns/op |
| TRUE | 1000 | 99 | TRUE | FALSE | 10 | 10 | avgt | 5 | 2488.191 | 255.307 | 4613.689 | 87.091 | ns/op |
| TRUE | 1000 | 99 | TRUE | TRUE | 0 | 10 | avgt | 5 | 1007.288 | 216.32 | 1953.663 | 29.537 | ns/op |
| TRUE | 1000 | 99 | TRUE | TRUE | 1 | 10 | avgt | 5 | 1048.985 | 103.433 | 2046.502 | 27.578 | ns/op |
| TRUE | 1000 | 99 | TRUE | TRUE | 10 | 10 | avgt | 5 | 1015.368 | 222.078 | 2069.779 | 73.225 | ns/op |
| TRUE | 1000 | 100 | FALSE | FALSE | 0 | 10 | avgt | 5 | 2446.628 | 465.894 | 4290.631 | 106.343 | ns/op |
| TRUE | 1000 | 100 | FALSE | FALSE | 1 | 10 | avgt | 5 | 2368.934 | 191.767 | 4408.351 | 400.138 | ns/op |
| TRUE | 1000 | 100 | FALSE | FALSE | 10 | 10 | avgt | 5 | 2187.27 | 266.959 | 4337.202 | 1056.462 | ns/op |
| TRUE | 1000 | 100 | FALSE | TRUE | 0 | 10 | avgt | 5 | 1808.21 | 185.681 | 3314.848 | 46.05 | ns/op |
| TRUE | 1000 | 100 | FALSE | TRUE | 1 | 10 | avgt | 5 | 1760.174 | 328.793 | 3567.172 | 324.826 | ns/op |
| TRUE | 1000 | 100 | FALSE | TRUE | 10 | 10 | avgt | 5 | 1813.038 | 179.371 | 3693.324 | 1729.497 | ns/op |
| TRUE | 1000 | 100 | TRUE | FALSE | 0 | 10 | avgt | 5 | 2589.964 | 302.064 | 4481.754 | 116.27 | ns/op |
| TRUE | 1000 | 100 | TRUE | FALSE | 1 | 10 | avgt | 5 | 2494.971 | 132.901 | 4646.743 | 360.485 | ns/op |
| TRUE | 1000 | 100 | TRUE | FALSE | 10 | 10 | avgt | 5 | 2436.427 | 213.211 | 4619.616 | 60.566 | ns/op |
| TRUE | 1000 | 100 | TRUE | TRUE | 0 | 10 | avgt | 5 | 1805.541 | 304.33 | 3410.814 | 46.948 | ns/op |
| TRUE | 1000 | 100 | TRUE | TRUE | 1 | 10 | avgt | 5 | 1789.231 | 189.852 | 3719.754 | 1531.788 | ns/op |
| TRUE | 1000 | 100 | TRUE | TRUE | 10 | 10 | avgt | 5 | 1820.644 | 374.211 | 3678.374 | 2205.007 | ns/op |
| TRUE | 5000 | 99 | FALSE | FALSE | 0 | 10 | avgt | 5 | 3632.39 | 71.731 | 7780.043 | 4472.378 | ns/op |
| TRUE | 5000 | 99 | FALSE | FALSE | 1 | 10 | avgt | 5 | 3453.896 | 83.615 | 8024.723 | 3659.888 | ns/op |
| TRUE | 5000 | 99 | FALSE | FALSE | 10 | 10 | avgt | 5 | 3599.063 | 121.679 | 8023.747 | 7665.474 | ns/op |
| TRUE | 5000 | 99 | FALSE | TRUE | 0 | 10 | avgt | 5 | 1452.063 | 12.308 | 2834.844 | 313.411 | ns/op |
| TRUE | 5000 | 99 | FALSE | TRUE | 1 | 10 | avgt | 5 | 1414.658 | 53.679 | 2704.824 | 867.343 | ns/op |
| TRUE | 5000 | 99 | FALSE | TRUE | 10 | 10 | avgt | 5 | 1398.966 | 35.347 | 2415.716 | 319.988 | ns/op |
| TRUE | 5000 | 99 | TRUE | FALSE | 0 | 10 | avgt | 5 | 3764.004 | 111.786 | 7171.521 | 4100.908 | ns/op |
| TRUE | 5000 | 99 | TRUE | FALSE | 1 | 10 | avgt | 5 | 4008.96 | 1740.722 | 7149.942 | 3353.829 | ns/op |
| TRUE | 5000 | 99 | TRUE | FALSE | 10 | 10 | avgt | 5 | 4154.255 | 62.851 | 7300.532 | 4600.59 | ns/op |
| TRUE | 5000 | 99 | TRUE | TRUE | 0 | 10 | avgt | 5 | 1473.955 | 61.37 | 2647.384 | 332.358 | ns/op |
| TRUE | 5000 | 99 | TRUE | TRUE | 1 | 10 | avgt | 5 | 1553.625 | 53.221 | 2499.667 | 300.683 | ns/op |
| TRUE | 5000 | 99 | TRUE | TRUE | 10 | 10 | avgt | 5 | 1543.222 | 76.352 | 2460.593 | 235.534 | ns/op |
| TRUE | 5000 | 100 | FALSE | FALSE | 0 | 10 | avgt | 5 | 3754.874 | 119.507 | 6970.279 | 4022.109 | ns/op |
| TRUE | 5000 | 100 | FALSE | FALSE | 1 | 10 | avgt | 5 | 3647.742 | 304.06 | 6940.627 | 3860.939 | ns/op |
| TRUE | 5000 | 100 | FALSE | FALSE | 10 | 10 | avgt | 5 | 3439.3 | 129.355 | 6828.86 | 4131.018 | ns/op |
| TRUE | 5000 | 100 | FALSE | TRUE | 0 | 10 | avgt | 5 | 2696.908 | 430.534 | 4997.008 | 3003.618 | ns/op |
| TRUE | 5000 | 100 | FALSE | TRUE | 1 | 10 | avgt | 5 | 2771.329 | 473.938 | 5318.634 | 4470.219 | ns/op |
| TRUE | 5000 | 100 | FALSE | TRUE | 10 | 10 | avgt | 5 | 2705.752 | 470.954 | 5613.541 | 4797.361 | ns/op |
| TRUE | 5000 | 100 | TRUE | FALSE | 0 | 10 | avgt | 5 | 3822.819 | 193.345 | 7438.494 | 3789.759 | ns/op |
| TRUE | 5000 | 100 | TRUE | FALSE | 1 | 10 | avgt | 5 | 3746.639 | 49.862 | 7971.087 | 5128.819 | ns/op |
| TRUE | 5000 | 100 | TRUE | FALSE | 10 | 10 | avgt | 5 | 3748.738 | 71.739 | 7821.017 | 4253.262 | ns/op |
| TRUE | 5000 | 100 | TRUE | TRUE | 0 | 10 | avgt | 5 | 2788.768 | 406.061 | 4998.906 | 3045.562 | ns/op |
| TRUE | 5000 | 100 | TRUE | TRUE | 1 | 10 | avgt | 5 | 2588.279 | 419.307 | 4868.152 | 2795.423 | ns/op |
| TRUE | 5000 | 100 | TRUE | TRUE | 10 | 10 | avgt | 5 | 2548.178 | 305.607 | 5582.232 | 6591.964 | ns/op |

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ahuang98** [comment]
retest this please

**Comment by ahuang98** [comment]
PR needs more work and testing

**Comment by kamalcph** [comment]
@ahuang98 @lbradstreet 

We are also having this issue when FetchConsumer requests scale beyond 50k requests per second. What's the current status of this patch? Thanks!

**Comment by kamalcph** [comment]
gentle reminder

**Pull request closed without merging**
