### PR TITLE
KAFKA-5563: Moved comparison of connector name from url against name …

### PR DESCRIPTION
**Pull request by soenkeliebau**
…from config to own function and added check to create connector call.

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 8082 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8082 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8082 tests run, 5 skipped, 0 failed.
--none--

**Review by ewencp — APPROVED** [review]
@soenkeliebau Sorry for the delay, looks like a good improvement and much better to centralize and standardize these validation checks. Thanks for the improvement! Merging to trunk for 1.1.

**Pull request closed without merging**
