### PR TITLE
KAFKA-9068: Fix incorrect JavaDocs for `Stores.xxxSessionStore(...)`

### PR DESCRIPTION
**Pull request by zealiard**
@mjsax https://stackoverflow.com/questions/58426767/what-happens-if-session-window-ends-before-retention-period-and-inactivity-gap-e

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Thanks for the PR @zealiard! LGTM.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.4` and `2.3`.

Tried to cherry pick to `2.2` but got conflict -- seems not be worth to resolve the conflict but sufficient to fix in 2.4 and 2.3.

**Comment by mjsax** [comment]
@zealiard -- Do you have a Jira account so we can assign the ticket to you?

**Comment by zealiard** [comment]
Thanks for the review @mjsax 
My Jira username is `zealiard`.

**Pull request merged**
