### PR TITLE
MINOR: remove NewTopic#NO_PARTITIONS and NewTopic#NO_REPLICATION_FACT…

### PR DESCRIPTION
**Pull request by chia7712**
The constants used to represent no_partition and no_replica are important factor in creating topic. Hence, we should have consistent reference to code base.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by abbccdda** [comment]
retest this please

**Comment by abbccdda** [comment]
got 2/3 in previous run

**Review by abbccdda — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
@abbccdda thanks for reviews!

**Comment by chia7712** [comment]
```
org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest > shouldUpgradeFromEosAlphaToEosBeta[true] FAILED
```

unrelated failure. retest this please

**Pull request merged**
