### PR TITLE
KAFKA-5414: Revert "KAFKA-5327: ConsoleConsumer should manually commi…

### PR DESCRIPTION
**Pull request by hachikuji**
…t offsets for records that are returned in receive()"

This reverts commit d7d1196a0b542adb46d22eeb5b6d12af950b64c9.

### CODE REVIEW

**Comment by hachikuji** [comment]
cc @ijuma @guozhangwang

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by hachikuji** [comment]
Merging to trunk and 0.11.0

**Comment by guozhangwang** [comment]
That was my bad overlooking this when merging it. Thanks for the catch @hachikuji . cc @huxihx 

As a hindsight, I'm wondering how the current behavior would not affect the system test usage, as it may auto commit to an offset whose messages have not been printed out on the console (this was what the PR is trying to fix)?

**Comment by guozhangwang** [comment]
As for the correct fix of KAFKA-5327, maybe we should manually call `commit` inside the console consumer periodically while turning off the auto-commit config.

**Comment by ijuma** [comment]
@guozhangwang Do you think @hachikuji's suggestion to change max.poll.records won't work?

**Comment by guozhangwang** [comment]
I did not see his suggestion on KAFKA-5327 before. That should be sufficient.

**Pull request closed without merging**
