### PR TITLE
MINOR: Fix small warning on javadoc and scaladoc

### PR DESCRIPTION
**Pull request by jlprat**
Escape the `>` character in javadoc
Escape the `$` character when part of `${}` in scaladoc as this is the
way to reference a variable

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
While testing if all tasks were working for https://github.com/apache/kafka/pull/11025, I realized some warnings were printed for the JavaDoc and ScalaDoc.
There are still some more present in the ScalaDoc:
* Ambiguous references (but this has no real solution as the ScalaDoc semantically refers to both
* Links to JavaDoc do not really work. Any time a Java class is referenced within a ScalaDoc, the target link can't be found. This results in the resulting documentation not linking to anything.

**Comment by mjsax** [comment]
Thanks for the PR!

**Comment by jlprat** [comment]
Thank you for reviewing and merging!

**Comment by mjsax** [comment]
Quite time between the holidays makes it possible to go through the backlog and get small wins merged :) -- Better (very!) late, than never.

**Pull request merged**
