### PR TITLE
KAFKA-7223: document suppression buffer metrics

### PR DESCRIPTION
**Pull request by vvcephei**
Document the new metrics added in #5795 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Excerpt of processor node metrics:
processor-node

New intro for state store metrics:
state-store-1

Relevant new metrics:
state-store-2

Question: It doesn't seem like the suppression metrics fit in that well with the other state store metrics. Should I just make it a separate section, and possibly merge them in the future when there is some overlap?

**Comment by vvcephei** [comment]
@guozhangwang @bbejeck , can you take a look at this when you have a chance?

**Comment by guozhangwang** [comment]
@vvcephei let's use a separate section for suppression buffers.

**Review by bbejeck — APPROVED** [review]
LGTM modulo @guozhangwang's comment about a separate section

**Comment by vvcephei** [comment]
Ok @guozhangwang @bbejeck ,

I've moved the buffer metrics to another table:

buffer1

Also removed it from the list of store types:
state-store-3

Lastly, I happened to notice that there's some markdown syntax that got into this file, so I've fixed it by replacing double-backticks with `<code>` elements.

**Review by guozhangwang — APPROVED** [review]
LGTM!

**Pull request merged**
