### PR TITLE
MINOR: Use `withClassLoader` in a couple more places

### PR DESCRIPTION
**Pull request by ijuma**
Instead of try/finally.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
cc @satishd

**Review by rondagostino — APPROVED** [review]
LGTM -- thanks!

**Review by satishd — APPROVED** [review]
Thanks @ijuma for the PR. LGTM.

**Comment by rondagostino** [comment]
Test failures are unrelated -- they either pass locally on this branch or they also fail locally on trunk (not sure why that would be, but still unrelated to this change).  Merging

**Pull request merged**
