### PR TITLE
Minor: fix javadocs of StreamsConfig and ValueTransformerWithKey

### PR DESCRIPTION
**Pull request by chia7712**
Those doc errors are explicit.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Retest this please

**Review by mjsax — APPROVED** [review]
Thanks for the patch @chia7712 !

LGTM.

**Comment by chia7712** [comment]
> Retest this please

done

**Comment by mjsax** [comment]
@chia7712 The term "retest this please" triggers a new Jenkins builds. It was not addressed to you :)

Merging this this `trunk`. Thanks a lot for the patch!

**Pull request merged**
