### PR TITLE
KAFKA-5905: Remove deprecated PrincipalBuilder and DefaultPrincipalBuilder

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
Raised this PR, incase we want remove deprecated claases in 2.0.0

**Comment by ijuma** [comment]
My suggestion is to only remove things that have been deprecated in 0.11.0 or older. One year seems like the minimum we should provide for users to migrate.

**Comment by omkreddy** [comment]
@ijuma yes, makes sense. We can review this at appropriate time.

**Comment by ijuma** [comment]
@omkreddy I believe we removed these classes for 3.0 via a different PR. Can you please confirm and close, if that is the case?

**Comment by omkreddy** [comment]
yeah, will close this.

**Pull request closed without merging**
