### PR TITLE
KAFKA-4585: Lower the Minimum Required ACL Permission of OffsetFetch (KIP-163)

### PR DESCRIPTION
**Pull request by vahidhashemian**
Details can be found in the [KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-163%3A+Lower+the+Minimum+Required+ACL+Permission+of+OffsetFetch).

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6718/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6703/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
@ewencp Could you review this PR?

**Comment by ewencp** [comment]
LGTM, thanks!

**Pull request closed without merging**
