### PR TITLE
KAKFA-3599: Move WindowStoreUtils to package "internals"

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
@guozhangwang @miguno @enothereska Please review.

**Comment by ijuma** [comment]
Thanks for the PR. I think the PR title would be better as `KAFKA-3599: Remove unused WindowStoreUtils` or something along those lines.

**Comment by mjsax** [comment]
Ups. It should not get removed, but moved to different package... Just fixed this.

**Comment by ijuma** [comment]
OK :)

**Comment by miguno** [comment]
LGTM

**Comment by guozhangwang** [comment]
LGTM overall. Could your rebase this PR?

**Comment by mjsax** [comment]
@guozhangwang Done.

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
