### PR TITLE
MINOR: s390x Stage

### PR DESCRIPTION
**Pull request by mimaison**
Copy of https://github.com/apache/kafka/pull/11899

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Nayana-ibm** [comment]
@mimaison s390x build fails with 
`ERROR: JAVA_HOME is set to an invalid directory: /home/jenkins/tools/java/latest11`

We have installed java on nodes at /usr/lib/jvm/java-11-openjdk-s390x/bin/java . In this case, we shouldn't be using `{  jdk 'jdk_11_latest'  } `for s390x? Please let me know

**Comment by mimaison** [comment]
Unit tests are now passing. Before pushing this further I'd like to get some agreement from the community about supporting different platforms. See https://lists.apache.org/thread/4ffpspc59cnzqbgjf3l50ykcvyp7vwtv

**Comment by Nayana-ibm** [comment]
@mimaison Any update on approval? When this PR will get merged?

**Comment by mimaison** [comment]
@Nayana-ibm I started a discussion on the mailing list, see https://lists.apache.org/thread/mfcc5pcky8xh0lfr173m0lm4fgvc6td1

**Comment by Nayana-ibm** [comment]
@mimaison Any update on this? ETA?

**Comment by mimaison** [comment]
@Nayana-ibm There is no ETA. We need the community to agree on how to manage hardware platforms. See the discussion thread: https://lists.apache.org/thread/mfcc5pcky8xh0lfr173m0lm4fgvc6td1

**Comment by Nayana-ibm** [comment]
@mimaison If there are build failures or platform specific issues for s390x , we can look into/debug those.

**Comment by Nayana-ibm** [comment]
@mimaison Any update on this please?

**Comment by mimaison** [comment]
We've had issues with the ARM and PowerPC builds. See https://lists.apache.org/thread/opk7o1tn7m0vzyqzhzkvgpf4xwst4qm6

So holding off merging this until we decide what to do with non-x86 platforms.

**Comment by Nayana-ibm** [comment]
@mimaison Any update on this please?

**Comment by Nayana-ibm** [comment]
Any update on this ?

**Comment by mimaison** [comment]
No updates, so I'm going to close this draft PR for now.

**Pull request closed without merging**
