### PR TITLE
KAFKA-10888: Revert #12049 f7db603

### PR DESCRIPTION
**Pull request by vvcephei**
Benchmarking indicates that #12049 was responsible for a 10% performance regression in the Producer. We are not sure why, but reverting the commit shows a return to nominal performance, so there is a strong indication that this one commit is indeed the culprit.

Results:
Commit: e3202b9999 (the parent of the problematic commit)
TPut: **118k±1k**

Commit: f7db6031b8 (#12049)
TPut: **106k±1k**

(every commit that we have tested from trunk after f7db6031b8 is also around **106k**)

This PR, reverting f7db6031b8
TPut: **116k±1k**

We propose to first revert the commit in question and then re-introduce the feature later, rather than trying to debug and fix the feature in trunk. The longer this commit stays live, the more code will be based on it, and the harder it will be in the future to extract, debug, or fix it.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
There is already a new conflict, which seems to support the argument to revert as soon as possible. I'll rebase and update this PR.

**Comment by vvcephei** [comment]
Pinging @artemlivshits and @junrao for reviews of this revert.

**Comment by vvcephei** [comment]
Also cc @guozhangwang , @ableegoldman , @bbejeck : I had to partially revert some of your changes that had been based on top of the problematic commit. I'm not sure whether you'll want to take a quick look.

**Comment by guozhangwang** [comment]
Thanks @vvcephei , I agree it's better to first revert and then re-introduce the feature after we got the root cause of the perf regression.

**Comment by guozhangwang** [comment]
Made a pass on just my PR regarding the streams partitioner, LGTM.

**Comment by jolshan** [comment]
I'm a little confused by the results here. 
> Results:
Commit: https://github.com/apache/kafka/commit/e3202b99999ef4c63aab2e5ab049978704282792 (the parent of the problematic commit)
TPut: 118k±1k
Commit: https://github.com/apache/kafka/commit/f7db6031b84a136ad0e257df722b20faa7c37b8a (https://github.com/apache/kafka/pull/12049)
TPut: 106k±1k
(every commit that we have tested from trunk after https://github.com/apache/kafka/commit/f7db6031b84a136ad0e257df722b20faa7c37b8a is also around 106k)
This PR, reverting https://github.com/apache/kafka/commit/f7db6031b84a136ad0e257df722b20faa7c37b8a
TPut: 116k±1k

it seems like reverting this commit doesn't help that much to improve perf. I'm also wondering what benchmark you are running here.

**Comment by ijuma** [comment]
@vvcephei @guozhangwang Please hold off reverting this until we have had a chance to review.

**Comment by YiDing-Duke** [comment]
@artemlivshits can you review this revert when get a chance?

**Comment by jolshan** [comment]
Can we also share more details about the benchmark that was run?

**Comment by artemlivshits** [comment]
I'm out of office till the end of the week, I can take a look next week.  Instead of revert, can we consider setting `partitioner.class=org.apache.kafka.clients.producer.internals.DefaultPartitioner` in producer config?  This should restore old behavior.  Reverting and re-introducing the change may result in a bunch of merge churn.

**Comment by vvcephei** [comment]
Thanks, all. If we can simply set the default back to the old behavior, then I agree it's nicer than reverting.

Also, of course, I have no intention of hitting "merge" unless we agree it's the right thing to do. I just wanted to raise the priority of this issue before it impacts Kafka users or becomes hopelessly entangled in later commits.

**Comment by vvcephei** [comment]
Hey @jolshan , let me share those details with you offline. I would like to publish the benchmarks at some point, but now is not the time.

**Comment by junrao** [comment]
Hmm, just changing partitioner.class is not enough. We also need to change the config doc, revert the deprecation of DefaultPartitioner, and revert https://issues.apache.org/jira/browse/KAFKA-13880

**Comment by vvcephei** [comment]
No need to revert, since this is being fixed in https://github.com/apache/kafka/pull/12365

**Pull request closed without merging**
