### PR TITLE
[KAFKA-8328] Kafka smooth expansion

### PR DESCRIPTION
**Pull request by lordcheng10**
When expanding the kafka cluster, the new follower will read the data from the earliest offset. This can result in a large amount of historical data being read from the disk, putting a lot of pressure on the disk and affecting the performance of the kafka service, for example, the producer write latency will increase. In general, kafka's original expansion mechanism has the following problems:
          1. The new follower will put a lot of pressure on the disk;
          2. Causes the producer write latency to increase;
          3. Causes the consumer read latency to increase;
       In order to solve these problems, we have proposed a solution for smooth expansion. The main idea of ​​the scheme is that the newly added follower reads data from the HW position, and when the newly added follower reads the data to a certain time threshold or data size threshold, the follower enters the ISR queue. . Since the new follower reads data from the HW location, most of the data read is in the operating system's cache, so it does not put pressure on the disk and does not affect the performance of the kafka service, thus solving the above problems.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3832/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3833/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3834/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3835/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3836/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3837/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3838/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3839/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3840/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3842/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3844/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3846/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3847/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3848/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3849/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3850/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3853/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3854/
Test PASSed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3856/
Test PASSed (JDK 7 and Scala 2.10).

**Comment by stanislavkozlovski** [comment]
Hey @lordcheng10, thanks for showing interest in the project!

Are you aware of our contributing guidelines? https://kafka.apache.org/contributing

Since this work can be classified as a major change, a better approach would be to first open up a KIP and initiate discussions with the mailing list.

I also see you're targeting the `0.10` version branch and I'm afraid we do not actively develop that version anymore.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3857/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by lordcheng10** [comment]
> Hey @lordcheng10, thanks for showing interest in the project!
> 
> Are you aware of our contributing guidelines? https://kafka.apache.org/contributing
> 
> Since this work can be classified as a major change, a better approach would be to first open up a KIP and initiate discussions with the mailing list.
> 
> I also see you're targeting the `0.10` version branch and I'm afraid we do not actively develop that version anymore.

Ok, I tried to merge this improvement to the trunk version. Currently my improved version is only tested successfully in JDK 7 and Scala 2.10 environment. JDK 8 and Scala 2.11 test environment encountered some problems in the process of testing the stream module. I have found out that some test cases may have bugs, but these fixes are not merged into version 0.10. I suspect that my test failure in the JDK 8 and Scala 2.11 test environment is related to these bugs.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3858/
Test PASSed (JDK 7 and Scala 2.10).

**Comment by lordcheng10** [comment]
> Hey @lordcheng10, thanks for showing interest in the project!
> 
> Are you aware of our contributing guidelines? https://kafka.apache.org/contributing
> 
> Since this work can be classified as a major change, a better approach would be to first open up a KIP and initiate discussions with the mailing list.
> 
> I also see you're targeting the `0.10` version branch and I'm afraid we do not actively develop that version anymore.

@stanislavkozlovski  Thank you for your attention , I will tried to merge this improvement to the trunk version. Currently my improved version is only tested successfully in JDK 7 and Scala 2.10 environment. JDK 8 and Scala 2.11 test environment encountered some problems in the process of testing the stream module. I have found out that some test cases may have bugs, but these fixes are not merged into version 0.10. I suspect that my test failure in the JDK 8 and Scala 2.11 test environment is related to these bugs.

**Review by wy96f — COMMENTED** [review]
This pr is a major change. If the new follower just fetches data from the hw position, finally the data in each replica is not consistent(i.e. the new follower only reserves data since join and other replicas reserves data for default 7 days). What if the new follower becomes leader of partition and users want seek back to a point before new follower join?

I think you can just set the topic log.retention.hours to a few hours and set a throttle before partition moving. Once finished, you can restore settings. In this way, fewer data need to be transferred and the throttle makes sure the business is not affected. I will prefer the operational way to fix the problem rather than breaking kafka semantics.

**Comment by lordcheng10** [comment]
> This pr is a major change. If the new follower just fetches data from the hw position, finally the data in each replica is not consistent(i.e. the new follower only reserves data since join and other replicas reserves data for default 7 days). What if the new follower becomes leader of partition and users want seek back to a point before new follower join?
> 
> I think you can just set the topic log.retention.hours to a few hours and set a throttle before partition moving. Once finished, you can restore settings. In this way, fewer data need to be transferred and the throttle makes sure the business is not affected. I will prefer the operational way to fix the problem rather than breaking kafka semantics.

In our actual environment, the data is generally retained for 36 hours. And kafka is a semi-storage framework and should not retain data for too long.

**Comment by lordcheng10** [comment]
> Hey @lordcheng10, thanks for showing interest in the project!
> 
> Are you aware of our contributing guidelines? https://kafka.apache.org/contributing
> 
> Since this work can be classified as a major change, a better approach would be to first open up a KIP and initiate discussions with the mailing list.
> 
> I also see you're targeting the `0.10` version branch and I'm afraid we do not actively develop that version anymore.

look forward to your reply，KIP url:  https://cwiki.apache.org/confluence/display/SHARDINGSPHERE/KIP-477%3AKafka+smooth+expansion

**Pull request closed without merging**
