### PR TITLE
MINOR: Update release script with new remote, better error handling, correct mvn deploy profile

### PR DESCRIPTION
**Pull request by ewencp**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/340/

**Comment by ewencp** [comment]
A bunch of simple fixes I had to make to get things working for 1.0.1-rc0.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/368/

**Review by ijuma — APPROVED** [review]
LGTM

**Review by dguy — APPROVED** [review]
LGTM

**Pull request closed without merging**
