### PR TITLE
KAFKA-2491; update ErrorMapping with new consumer errors

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by ijuma** [comment]
We don't want to update `exceptionToCode`?

**Comment by hachikuji** [comment]
@ijuma I think ErrorMapping will be eliminated in KAFKA-1929 in favor of the client-side Errors. Until then, @junrao wanted to keep them in sync.

**Comment by ijuma** [comment]
Yes, I understand. I just wasn't clear what it meant to be kept in sync (is it just adding comments as in the PR or to update `exceptionToCode` as well).

**Comment by hachikuji** [comment]
Maybe we can hold off on this and I can just knock out KAFKA-1929 instead.

**Comment by ijuma** [comment]
That would be nice. In any case, I did verify that the comments added in the PR are correct. :)

**Pull request closed without merging**
