### PR TITLE
KAFKA-5725: More failure testing

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6687/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by enothereska** [comment]
cc @dguy thanks

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6702/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by dguy** [comment]
Thanks @enothereska, looks like a very worthwhile addition. Have you ran the system test?

**Comment by enothereska** [comment]
thanks @dguy I did start it, and there were failures: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1032/console which didn't happen when I ran locally. Could be a real issue, investigating.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6739/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6724/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
This is a real issue that is being tracked by KAFKA-5733. We can mark 5725 blocked by that ticket for now. Will try to resolve 5733 and then merge this one afterwards.

**Comment by guozhangwang** [comment]
One interesting issue though, is that bouncing a broker does trigger a rebalance that triggers the issue in KAFKA-5733 during restoration, which is not expected in Streams. @enothereska could you investigate a bit more on the test logs and see why it triggers the rebalance?

**Comment by enothereska** [comment]
@guozhangwang will do. In one scenario we kill the coordinator broker. Won't that always trigger a rebalance when new coordinator comes up?

**Comment by guozhangwang** [comment]
Even killing the coordinator should normally not trigger a rebalance: the consumer will detect the coordinator is dead, and try to re-discover the coordinator. It will falls in that loop until a new coordinator can be found.

The first request that this consumer will send to the new coordinator is always a heartbeat request not a join request, if the new coordinator is still bootstrapping the consumer group from the internal topics it will return a `Loading In Progress` error code and the consumer will backoff and retry. After it completes loads it will handle the heartbeat request, and if everything looks okay it should return a `Good` error code in the response, and the consumer will just proceed fetching and no rebalance will trigger. Only if the new coordinator returns a fatal error code like `Invalid Member Id` the consumer will then re-join the group to trigger a rebalance. But that is not expected in this system test.

**Comment by enothereska** [comment]
I'll check further, thanks!

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6863/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6849/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by enothereska** [comment]
System test passes: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1041/ cc @dguy this is probably ready to go now that the problem has been fixed. Thanks.

**Review by dguy — APPROVED** [review]
Thanks @enothereska, LGTM

**Comment by dguy** [comment]
merged to trunk

**Pull request closed without merging**
