### PR TITLE
KAFKA-17593; [1/N] Introduce re2j dependency

### PR DESCRIPTION
**Pull request by dajac**
This patch is the first of a series of patches to introduce support for server side regular expression. It introduces the re2j dependency.

Co-authored-by: Lianet Magrans <lmagrans@confluent.io>

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lianetm** [comment]
We are just missing the lic file right? https://github.com/apache/kafka/blob/898a878c258a022a5cbf4fca5b5e5a1ce56cbc27/licenses/re2j-GO

**Comment by dajac** [comment]
@lianetm Good catch! Fixed!

**Review by lianetm — APPROVED** [review]
Thanks! LGTM

**Comment by chia7712** [comment]
Out of curiosity, if I recall correctly, Google's RE2 is not fully compatible with Java regex. Could this cause issues if the `Consumer` accepts Java `Pattern`, allowing users to use unsupported regex features?

**Comment by dajac** [comment]
> Out of curiosity, if I recall correctly, Google's RE2 is not fully compatible with Java regex. Could this cause issues if the `Consumer` accepts Java `Pattern`, allowing users to use unsupported regex features?

That's right. `Pattern` will keep working on the client side via the existing `subscribe(Pattern)` api. We will deprecate it at some point. The server side one will be used via `subscribe(SubscriptionPattern)`. `SubscriptionPattern` is defined [here](https://cwiki.apache.org/confluence/display/KAFKA/KIP-848%3A+The+Next+Generation+of+the+Consumer+Rebalance+Protocol#KIP848:TheNextGenerationoftheConsumerRebalanceProtocol-NewSubscriptionPatternclass). This avoids the compatibility issue but users will have to migrate from the old one to the new one.

**Pull request merged**
