### PR TITLE
KAFKA-3789: Upgrade Snappy to fix snappy decompression errors

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. I wonder if we can extend our compression tests to include some data generated by the C snappy library?

**Comment by ijuma** [comment]
Maybe even an example including this pattern that doesn't seem to happen with the Java library.

**Comment by granthenke** [comment]
@ijuma I had considered adding a test. And I agree tests to make sure there are no issues in the future are good. But I wonder if Kafka is the right place for these tests. I think its more appropriate for snappy-java or the clients using the c bindings to have integration tests that ensure they are working. The issue didn't occur when using the Kafka jvm clients. 

snappy-java added a unit test to ensure this issue doesn't happen again: https://github.com/xerial/snappy-java/commit/60cc0c2e1d1a76ae2981d0572a5164fcfdfba5f1

**Comment by ijuma** [comment]
IMO, Snappy-java would be the best place, followed by Kafka (we support many clients, not just the Java one) and last the other clients.

The issue is that we keep getting regressions when upgrading snappy-java (even when it's a patch release update), so I was trying to think of ways of reducing the risk. Otherwise, we may end up not upgrading again due to the risk.

**Comment by ijuma** [comment]
I did some code archeology and the regression in snappy-java happened in May 2015 (I bisected): https://github.com/xerial/snappy-java/commit/ac168dfdce76fb077403973a2716f1def839db7e

The issue has been in Kafka since November 2015: https://github.com/apache/kafka/commit/8f6ffe1c28d43bebf1cef7198c1e154a2adc92c3

There are some plans to run the Kafka system tests with other clients and that would hopefully show issues like this. In the meantime, we should probably avoid upgrading the Snappy library (even if they added a test for this particular issue).

LGTM, merging to trunk and 0.10.0.

**Comment by ijuma** [comment]
Ran the tests locally and they passed (the PR build had transient failures).

**Pull request closed without merging**
