### PR TITLE
MINOR: Update TestLogCleaning tool to use java consumer

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@ijuma  Manually tested the changes against a running broker. Pls take a look when you get a chance.

**Comment by ijuma** [comment]
Do we want to keep this? What is the use case?

**Comment by omkreddy** [comment]
Main use case is to run stress tests against a kafka cluster configured for log compaction.
It can be used to verify compaction after any major code changes. 
I agree that, we are not using this tool for regular testing. But I think, its a useful tool for testing.

**Comment by hachikuji** [comment]
Just my two cents, but I'm not fond of these standalone testing tools. To provide more value, it needs to get run automatically. If the testing is valuable, would it make sense to integrate this with our system tests?

**Comment by ijuma** [comment]
Yeah, that's what I was going to say. If it's useful, we should run it regularly.

**Comment by omkreddy** [comment]
Yes, its makes sense to integrate with system systems.  will integrate with system systems and raise a new PR.

**Pull request closed without merging**
