### PR TITLE
KAFKA-7273 Clarification on mutability of headers passed to Converter…

### PR DESCRIPTION
**Pull request by gunnarmorling**
…#fromConnectData()

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@rhauch, hey there; perhaps you could pull this in for the next release? Minor JavaDoc clarification.

**Comment by gunnarmorling** [comment]
@rhauch, ping?

**Comment by rhauch** [comment]
Thanks, @gunnarmorling. We're past code freeze for AK 2.4, so I've been holding off on this until we're past that so that this can be backported. It is a relatively benign change, but not important enough to request a fix.

I could merge this to `trunk` now, but it seems like we'd want to backport this small improvement.

**Review by rhauch — APPROVED** [review]
LGTM. Thanks, @gunnarmorling.

**Comment by rhauch** [comment]
Retest this, please.

**Comment by rhauch** [comment]
Retest this please

**Comment by rhauch** [comment]
This PR only includes one small JavaDoc changes, and the test failures are completely unrelated.

**Pull request merged**
