### PR TITLE
Add compute() to InMemoryKeyValueStore

### PR DESCRIPTION
**Pull request by gowthamgutha**
Should also be added to the KeyValueStore interface (at least as default method).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jtechpro** [comment]
@ableegoldman Could you check why is this failing?

**Comment by ableegoldman** [comment]
I suspect it's just some flaky tests but results are cleared up: retest this, please.

Can I ask why you'd like to add a compute method though? Is there a JIRA for this? If you need additional functionality with the built-in stores it's best to write your own custom store -- you can just copy the InMemoryKeyValueStore code and add whatever methods you like.

**Comment by gowthamgutha** [comment]
@ableegoldman Thanks for the reply.

I just wanted to compute() a value atomically on the InMemoryKeyValueStore. Because, although get() and put() are thread-safe.. I don't want to have stale updates.. We are actually trying to delegate the tasks to another thread which will also be trying to access the state store.. 

In one thread, I might get a value using get() and do some processing and by the time I put, some other thread might have called put() which results in the value wrote by the other thread to be overridden by the current thread.

Since, the parallelism in Kafka is actually limited to per partition, and there is (and could be) a need to delegate tasks to other threads (which might also make use of state stores), I have added this.

Regards,
Gowtham

**Comment by ableegoldman** [comment]
I see. I'm not sure it would be appropriate to add this to the actual InMemoryKeyValueStore -- for one thing, it's part of the internal package and not the public API, so technically you wouldn't even be able to access this method if using Streams "as intended." For another, thing this seems to be specific to your use case and not generally helpful for the built-in store to have. 

Streams does allow you to write your own custom store for exactly this kind of purpose, which can be just the InMemoryKeyValueStore code + compute method as you have here. This can then be plugged in where the built-in store would normally be used and wouldn't require any code changes to the library.

**Comment by gowthamgutha** [comment]
@ableegoldman But, if we are using the state stores (for ex, InMemoryKeyValueStore) directly, we will be accessing the get() and put(). So compute() seems to be as important as both of them.

**Comment by ableegoldman** [comment]
InMemoryKeyValueStore is in the internal package so technically you should not be using it directly. The API in not stable and the store may be changed, massively refactored, or even removed entirely at any time.

You are of course free to use Streams however you wish but be aware you might be getting into trouble down the line. You could even fork your own and make changes such as this if you're intent on using it this way, it just seems like overkill compared to the provided method of achieving this (plug-in custom store)

**Comment by mjsax** [comment]
A change like this would require a KIP. Closing this PR for now.

**Pull request closed without merging**
