### PR TITLE
KAFKA-12609: Rewrite ListOffsets using AdminApiDriver

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
See here: https://github.com/apache/kafka/pull/10275#issuecomment-806331897

*Summary of testing strategy (including rationale)*
1. add a unit test for `ListOffsetsHandler`
2. existing test in `KafkaAdminClientTest`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
Helli @dajac , are you interested in reviewing this PR, the current `ListOffsets` implementation is very complex and can be simplified tremendously if we use `AdminApiDriver` created by @hachikuji .

**Comment by dajac** [comment]
@dengziming Sure. I have added it to my review backlog.

**Comment by dajac** [comment]
@dengziming Sorry for the delay on this one. I wanted to get https://github.com/apache/kafka/pull/10760 merge first before tackling this one. Could you rebase your PR to include those changes?

**Comment by dengziming** [comment]
Thank you @dajac I will check #10760 soon.

**Pull request closed without merging**
