### PR TITLE
KAFKA-6188; Fix windows clean log fail caused shut down

### PR DESCRIPTION
**Pull request by theidexisted**
During debugging, I find that delete or rename a file before close it is illegal on windows, so I changed the function `deleteSegment` to add a direct close handle operation.

I have manually test it on windows, the change seems very straightforward, please review it.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bubbercn** [comment]
Code around
https://github.com/apache/kafka/blob/5ca08daea029ea1042214d3bf30f18bd8f6cc060/core/src/main/scala/kafka/log/Log.scala#L1986
still misses the fix, we may need to fix that as well.

**Comment by theidexisted** [comment]
JDK 11 and Scala 2.12

**Comment by theidexisted** [comment]
JDK 8 and Scala 2.11

**Comment by keithn** [comment]
be nice to see this finished, seems like kafka on windows isn't viable without this fix?

**Comment by theidexisted** [comment]
@keithn Yes, when the  log cleaning event is  trigger, Kafka server will shut down(The default time is 168 hours after the first start up) due to file renaming exception.

**Comment by avivrosiqp** [comment]
What's the status with this one? Seems as the bug still exists in latest version of Kafka on Windows (2.2.1) but Bug KAFKA-6188 in Jira is shown as resolved. Also this PR, which suppose to fix it is still open...

**Comment by theidexisted** [comment]
@avivrosiqp  Seems the community is not  interested in this bug. So sad.

**Comment by keithn** [comment]
@prehistoric-penguin Seems weird that there is zero priority on this issue,  It seems mission critical (ie, it just doesn't work without a fix ).   Convinced me to abandon using Kafka.   If the core team aren't interested in getting this working on windows after providing all the tools to get it running on windows then hard to believe other critical problems won't get addressed quickly.  Hard to work out what parts of Kafka people actually care about and will fix.

**Comment by theidexisted** [comment]
@keithn Kafka doesn't support Windows officially, so there are several bugs on Windows, I don't suggest run Kafka on Windows personally. Linux is always the first choice to deploy a service.

**Comment by keithn** [comment]
But they distribute it with windows support and don't make it obvious that windows isn't really supported "officially".  It wasn't until I started reading issues that I started seeing it wasn't officially supported.

**Comment by gzinger** [comment]
Not sure if this PR was ever merged. If yes, which release I need to download to get the fix?
If not, please reconsider. We really need to support Windows for some of our clients whom Linux and container are not the options. And without this fix the whole system is not really functional.

**Comment by theidexisted** [comment]
> Not sure if this PR was ever merged. If yes, which release I need to download to get the fix?
> If not, please reconsider. We really need to support Windows for some of our clients whom Linux and container are not the options. And without this fix the whole system is not really functional.

It's so sad that this PR is never been reviewed or mentioned.

Microsoft have maintained a [Kafka branch](https://github.com/microsoft/kafka), seems they have already fixed this issue, please take a look.

**Comment by Ikxyz** [comment]
You tried your best man nice job... it's a shame they refuse to give these issues the right amount of attention it deserves... Glad Microsoft stepped up

Thanks for all the help

**Comment by MPeli** [comment]
It seems that a lot of people are struggling with this issue. See https://stackoverflow.com/q/45599625/1200885

I was wondering whether @hachikuji, @dajac or @cmccabe could reconsider merging this pull request.

**Comment by theidexisted** [comment]
> It seems that a lot of people are struggling with this issue. See https://stackoverflow.com/q/45599625/1200885
> 
> I was wondering whether @hachikuji, @dajac or @cmccabe could reconsider merging this pull request.

@MPeli 
I would recommend that using Linux to run Kafka Server, to make our Kafka cluster reliable and robust. Windows haven't been officially supported to run Kafka Server, the effort to run it would be too high that it even couldn't be correctly estimated.

**Pull request closed without merging**
