### PR TITLE
Fix to run hadoop-consumer with hadoop 2

### PR DESCRIPTION
**Pull request by mvalleavila**
Changes to use hadoop-core-1.2.1.jar in hadoop-consumer
Changes to import from maven the packages needed to run hadoop-consumer in HDFS

### CODE REVIEW

**Comment by mvalleavila** [comment]
Error in pull request. Closing pull request

**Comment by b-goyal** [comment]
Changes to use hadoop-core-1.2.1.jar in hadoop-consumer
Changes to import from maven the packages needed to run hadoop-consumer in HDFS

**Comment by b-goyal** [comment]
Changes to use hadoop-core-1.2.1.jar in hadoop-consumer
Changes to import from maven the packages needed to run hadoop-consumer in HDFS

**Comment by b-goyal** [comment]
Changes to use hadoop-core-1.2.1.jar in hadoop-consumer
Changes to import from maven the packages needed to run hadoop-consumer in HDFS

**Comment by b-goyal** [comment]
Changes to use hadoop-core-1.2.1.jar in hadoop-consumer
Changes to import from maven the packages needed to run hadoop-consumer in HDFS

**Comment by b-goyal** [comment]
Changes to use hadoop-core-1.2.1.jar in hadoop-consumer
Changes to import from maven the packages needed to run hadoop-consumer in HDFS

**Pull request closed without merging**
