### PR TITLE
MINOR: Remove Diamond and code code Alignment

### PR DESCRIPTION
**Pull request by highluck**
Remove Diamond and code code Alignment

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by abbccdda — COMMENTED** [review]
Thanks for the cleanup. Not sure we need to have this as a standalone PR though as we could do the cleanup when we actually touch these files, let @vvcephei make a call.

**Review by vvcephei — APPROVED** [review]
Hey @highluck , I'm really sorry; I didn't see this PR until just now.

Thanks for the cleanup. If you want to rebase, I can give it another look and merge it.

**Comment by highluck** [comment]
@vvcephei 
code update!

**Comment by vvcephei** [comment]
Ok to test

**Review by vvcephei — APPROVED** [review]
Thanks @highluck ; just waiting on tests.

**Comment by highluck** [comment]
@vvcephei retest this please

**Comment by highluck** [comment]
@vvcephei 
Could you please check again?

**Comment by abbccdda** [comment]
retest this please

**Review by abbccdda — APPROVED** [review]
LGTM

**Pull request merged**
