### PR TITLE
KAFKA-16923  New Unit Test for stripDotPathComponents method

### PR DESCRIPTION
**Pull request by ardada2468**
I have written 1 new unit test and modified another unit test.

Created new test: **testStripDotPathComponents**

- Tests the stripDotPathComponents found in CommandUtils
- Ensures that the method works as expected (in case of future changes to the method)

### CODE REVIEW

**Comment by ardada2468** [comment]
only shell/src/test/java/org/apache/kafka/shell/command/CommandUtilsTest.java file has been changed to incorporate 1 more unit test

**Comment by chia7712** [comment]
@ardada2468 As you have filed a jira, please add jira number to the title. for example: `KAFKA-16923 New Unit Test for stripDotPathComponents method`

**Comment by ardada2468** [comment]
@chia7712  do you know why I am getting the the following error: 

[2024-06-14T23:21:59.290Z] [Checks API] No suitable checks publisher found.

on Jenkins?  I would appreciate it if you could guide me through this.

**Comment by chia7712** [comment]
> [2024-06-14T23:21:59.290Z] [Checks API] No suitable checks publisher found.

don't worry about that. That is unrelated to your PR :)

**Review by chia7712 — COMMENTED** [review]
LGTM

**Pull request merged**
