### PR TITLE
KAFKA-9465: Enclose consumer call with catching InvalidOffsetException

### PR DESCRIPTION
**Pull request by tedyu**
In maybeUpdateStandbyTasks, the try block encloses restoreConsumer.poll and record handling.
Since InvalidOffsetException is thrown by restoreConsumer.poll, we should enclose this call in the try block.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Thanks for the PR @tedyu -- that makes sense.

\cc @guozhangwang @vvcephei Can we just merge this or would it introduce additional conflicts with the refactoring you are working on atm?

**Comment by guozhangwang** [comment]
In the cleaned up branch `maybeUpdateStandbyTasks` does not exist anymore as it is moved into ChangelogReader; the handling logic of InvalidOffset is outside of the buffering logic already. So I'd suggest we do not merge this PR for now until the cleanup base is merged back to trunk.

**Comment by mjsax** [comment]
@tedyu @guozhangwang The cleanup on `trunk` is done. What is the status of this PR and ticket? Still valid? Or implicitly fixed by the refactoring?

**Comment by guozhangwang** [comment]
I just checked the current trunk this issue is already resolved.

**Comment by mjsax** [comment]
Thanks @guozhangwang. I resolve the Jira ticket. Closing this PR.

**Pull request closed without merging**
