### PR TITLE
KAFKA-4480: Report an error in 'kafka-configs' command if the config to be removed does not exist

### PR DESCRIPTION
**Pull request by vahidhashemian**

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM, and merged to trunk.

**Comment by ijuma** [comment]
Wouldn't it be better to fail the whole operation? That seems safer in my opinion.

**Comment by guozhangwang** [comment]
I think it is still safe to proceed the operation while filtering out the invalid config. I remember we did the same in some other console admin tools but I am not sure if it is still the case.

**Comment by ijuma** [comment]
@guozhangwang, there is no way to revert an incorrect delete. If someone mistyped one config, there could be other issues in the command. It's much safer to fail the whole operation and let the user retry the whole thing. I can't think of a scenario where it's actually helpful to do a partial delete. Can you?

**Comment by guozhangwang** [comment]
I think I agree. We could do a follow-up of this PR.

**Comment by ijuma** [comment]
Sounds good. @vahidhashemian, would you mind submitting a follow-up? Thanks!

**Comment by vahidhashemian** [comment]
Definitely, I'll work on submitting a follow-up PR to fail the command in case of such user errors.

**Pull request closed without merging**
