### PR TITLE
HOT_FIX: Update javadoc since imports added

### PR DESCRIPTION
**Pull request by bbejeck**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
Ok to test.

**Review by vvcephei — APPROVED** [review]
Thanks for the quick fix, @bbejeck . I'm +1 assuming a green build.

**Review by mjsax — APPROVED** [review]
Thanks @bbejeck!

**Comment by ableegoldman** [comment]
@bbejeck tests passed, can we merge this?

**Comment by bbejeck** [comment]
Merged #8817 into trunk.

**Pull request merged**
