### PR TITLE
KAFKA-13200: Fix MirrorMaker2 connector version

### PR DESCRIPTION
**Pull request by mimaison**
Use the Kafka version instead of hardcoding it to 1.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ryannedolan** [comment]
Does this have any impact on users as they upgrade? So far the MM connectors are mostly agnostic to what version of Kafka they interact with, and I'm wondering if syncing the versions like this would imply otherwise.

**Comment by mimaison** [comment]
This should not have an impact. As far as I can tell the version is only externally visible when querying `/connector-plugins`.

When we have a bunch of Connect clusters with different versions, it's nice to know immediately what's running. I also helps identifying the version of the runtime (as in most cases it's the same as the connectors). The FileStream connectors expose the real version too but they are often removed for security reasons.

**Review by showuon — COMMENTED** [review]
@mimaison , LGTM! Just one question: Should we also change the version in tasks? (i.e. `MirrorCheckpointTask`, `MirrorHeartbeatTask`, `MirrorSourceTask`)

**Comment by mimaison** [comment]
@showuon Good point, updated!

**Comment by dongjinleekr** [comment]
Cool. So... the version info in the headers will be changed from 1 to 3.1.0, 3.1.0, ... etc. Do I understand correctly?

**Comment by mimaison** [comment]
> Cool. So... the version info in the headers will be changed from 1 to 3.1.0, 3.1.0, ... etc. Do I understand correctly?

Yes, with this change, this will report the Kafka version, for example 3.1.0 instead of 1

**Review by tombentley — APPROVED** [review]
LGTM.

**Pull request merged**
