### PR TITLE
KAFKA-16408: Fix handling of '--version' or '--help' for GetOffsetShell

### PR DESCRIPTION
**Pull request by wernerdv**
Added call CommandLineUtils#maybePrintHelpOrVersion before check required args.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wernerdv** [comment]
@gharris1727 Hello. Please, take a look.

**Comment by chia7712** [comment]
@wernerdv could you please attach the new console output from `./bin/kafka-get-offsets.sh --version`

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by wernerdv** [comment]
> @wernerdv could you please attach the new console output from `./bin/kafka-get-offsets.sh --version`

Yes, sure.
```
./bin/kafka-get-offsets.sh --version
3.8.0-SNAPSHOT
```

**Comment by chia7712** [comment]
```sh
./gradlew cleanTest :tools:test --tests MetadataQuorumCommandTest.testDescribeQuorumReplicationSuccessful --tests MetadataQuorumCommandTest.testDescribeQuorumStatusSuccessful --tests DescribeConsumerGroupTest.testDescribeExistingGroupWithNoMembers :storage:test --tests TransactionsWithTieredStoreTest.testFencingOnSend :metadata:test --tests QuorumControllerTest.testFenceMultipleBrokers :trogdor:test --tests CoordinatorTest.testTaskRequestWithOldStartMsGetsUpdated :connect:mirror:test --tests DedicatedMirrorIntegrationTest.testMultiNodeCluster --tests MirrorConnectorsIntegrationBaseTest.testSyncTopicConfigs :core:test --tests LogDirFailureTest.testIOExceptionDuringLogRoll --tests LogDirFailureTest.testIOExceptionDuringCheckpoint --tests LogDirFailureTest.testProduceErrorFromFailureOnCheckpoint --tests ZkMigrationIntegrationTest.testMigrateTopicDeletions --tests ReplicaManagerTest.testRemoteFetchExpiresPerSecMetric
```
those failed tests pass on my local. will merge it tomorrow

**Comment by chia7712** [comment]
backport to 3.7 by https://github.com/apache/kafka/commit/0ebdc37ee7a77b4ef4be4dd8496db8b6b0abcc55

**Pull request merged**
