### PR TITLE
MINOR: add jenkins.sh to fix PR branch builder

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @ewencp @ijuma

**Review by ijuma — APPROVED** [review]
LGTM, thanks. Will wait for Jenkins to complete.

**Comment by mjsax** [comment]
@ijuma failing tests are unrelated. Should we retest? All builds/tests did start, so `jenkins.sh` works. Should be good enough imho.

**Review by ijuma — APPROVED** [review]
Thanks, LGTM.

**Comment by ijuma** [comment]
Merged to 0.10.2. Please close the PR.

**Comment by mjsax** [comment]
Thanks @ijuma!

**Pull request closed without merging**
