### PR TITLE
HOTFIX: fix paths in streams index

### PR DESCRIPTION
**Pull request by dguy**

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang @ijuma - also needs to go to 0.11.0

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by dguy** [comment]
Merged to trunk and cherry picked to 0.11.0

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5967/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5952/
Test PASSed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
