### PR TITLE
Added safe deserialization impl

### PR DESCRIPTION
**Pull request by rhauch**

### CODE REVIEW

**Comment by rhauch** [comment]
@ewencp Please review.

**Comment by ewencp** [comment]
I don't see a reason this change should break anything, but just in case I kicked of the Connect system tests against this branch [here](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1003).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6265/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6249/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ewencp — APPROVED** [review]
LGTM

**Comment by ilatypov** [comment]
Blacklisting is a poor defense against known and unknown abuses of class constructors.  I apologize for criticizing without offering a better fix.  I see newer JDKs come with a programmatic object input filter configuration, as well as with a run-time java.security configuration, both of which were requested by JEP 290.

https://docs.oracle.com/javase/10/core/serialization-filtering1.htm

Is it possible to have a sensible white list in Kafka?  I know very little about it, sorry.  I was thinking that perhaps the existing solution can be changed from blacklisting to whitelisting, so that the defense does not depend on JEP 290.

**Pull request closed without merging**
