### PR TITLE
KAFKA-3448: add % character to ipv6 regex

### PR DESCRIPTION
**Pull request by soumyajit-sahu**
IPV6 address can contain % character

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the pull request.

There are a couple more places where this needs to be updated:
- kafka.cluster.EndPoint.uriParseExp
- Utils.HOST_PORT_PATTERN

Also, can you please add a test to `UtilsTest` and `BrokerEndPointTest`?

**Comment by soumyajit-sahu** [comment]
Thanks @ijuma for guiding me there. I will try to add the unit test soon.

**Comment by ijuma** [comment]
@soumyajit-sahu, are you still planning to add unit tests?

**Comment by soumyajit-sahu** [comment]
@ijuma , sorry for the delay. My unfamiliarity with Scala language might be a hindrance here. Could someone else help with the test cases updates. Also, it would be nice to consolidate the regex in one place in code (instead of at 3 places).
E.g. Windows IPV6 address that was failing before: fe80::d415:51c8:6018:38a2%3

**Comment by ijuma** [comment]
I'll try to help with the tests. Have you tested using an IP address like the one you posted that it behaves as you expect? Do I understand correctly that the aim is to define the network interface to bind to?

**Comment by soumyajit-sahu** [comment]
Thanks @ijuma The ipv6 addresses could contain a "%" character to mention the zone index. I have mentioned the wikipedia link in the JIRA https://issues.apache.org/jira/browse/KAFKA-3448.

The createBrokerEndPoint() method was failing before the change as it couldn't parse the ipv6 (with % character) appropriately. I got the KafkaException("Unable to parse " + connectionString + " to a broker endpoint"). This change fixed that on my machine.

```
/**
   * BrokerEndPoint URI is host:port or [ipv6_host]:port
   * Note that unlike EndPoint (or listener) this URI has no security information.
   */
  def parseHostPort(connectionString: String): Option[(String, Int)] = {
    connectionString match {
      case uriParseExp(host, port) => try Some(host, port.toInt) catch { case e: NumberFormatException => None }
      case _ => None
    }
  }

  /**
   * BrokerEndPoint URI is host:port or [ipv6_host]:port
   * Note that unlike EndPoint (or listener) this URI has no security information.
   */
  def createBrokerEndPoint(brokerId: Int, connectionString: String): BrokerEndPoint = {
    parseHostPort(connectionString).map { case (host, port) => new BrokerEndPoint(brokerId, host, port) }.getOrElse {
      throw new KafkaException("Unable to parse " + connectionString + " to a broker endpoint")
    }
  }
```

I was also able to add the test cases you had suggested. Hope they explain the matter.

**Comment by ijuma** [comment]
@soumyajit-sahu Thanks for adding the tests. The question was whether you tested that the broker works correctly (you can produce to and consume from it) with link-local IPv6 addresses after your change (I understand that we won't fail during validation, but I was looking for a bit more than that).

**Comment by ijuma** [comment]
Also, I just noticed that this PR targets the 0.9.0 branch. It should target trunk instead.

**Comment by soumyajit-sahu** [comment]
@ijuma Yes, I was able to produce and consume after this change on the machine that had % character in its ipv6 address.
I will close this PR, and open a new one targeting trunk.

**Comment by soumyajit-sahu** [comment]
New PR (targeting trunk) submitted: https://github.com/apache/kafka/pull/1305

**Pull request closed without merging**
