### PR TITLE
MINOR: Add another common error case for CorruptRecordException's error message

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@hachikuji @ijuma @gwenshap Simple message change to add another case that pops up periodically and usually isn't obvious to the user.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6116/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6131/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
retest this please

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

We have a KIP in progress for not reusing this error code for the null key in compacted topic, but it makes sense to include this simple change until that change is ready.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6135/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6151/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ewencp** [comment]
@ijuma Thanks, I had missed that KIP. At first I was thinking that we shouldn't make this change if the exception was going to change anyway, especially if changing to an incompatible type in order to make it non-retriable (as opposed to, e.g., using a subclass with a clearer message). Then I saw this will only be done for ProduceRequestV3+, so even in newer clients we'd get the old exception if talking with older brokers, so the extra info is still useful. So I'll commit this since it seems to be useful regardless of what happens to KIP-135.

But then I wonder about making this change for ProduceRequestV3 given we released that version already such that we still return CorruptRecordException. Is that just stale in the KIP at this point since it didn't make it into 0.11? Or would we just be ok with what is technically an incompatibility since a user would have to reasonably handle non-retriable exceptions anyway?

**Comment by ijuma** [comment]
Yes, the KIP is stale since it didn't make it into 0.11. The JBOD KIP is bumping the produce request version again, so we could use that for the next release.

**Pull request closed without merging**
