### PR TITLE
HOTFIX: fix even/odd rows for upgrade.from config

### PR DESCRIPTION
**Pull request by ableegoldman**
Minor followup to https://github.com/apache/kafka/pull/7825, should be cherry-picked to 2.4

### CODE REVIEW

**Review by bbejeck — APPROVED** [review]
LGTM.  @ableegoldman did you render this locally to confirm?

**Comment by ableegoldman** [comment]
No...but I noticed in [another PR](https://github.com/apache/kafka/pull/7831#discussion_r357802528) that several other configs also break this even/odd pattern, yet as far as we could tell there are no visible effects.
(That said, it does seem good to avoid breaking it further -- and note that we actually need to cherry-pick [this PR](https://github.com/apache/kafka/pull/7825) to 2.4 first, then apply this fix on top)

**Comment by bbejeck** [comment]
Merged #7837 into trunk.

**Comment by bbejeck** [comment]
cherry-picked to 2.4

**Pull request merged**
