### PR TITLE
MINOR: Avoid unnecessary tuple allocations in index binary search

### PR DESCRIPTION
**Pull request by ijuma**
Also tweaked it the computation to be more inline with standard
binary search implementations.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Not ready for review yet.

**Comment by ijuma** [comment]
retest this please

**Comment by chia7712** [comment]
@ijuma Is this still active? the method ```binarySearch``` is a hot method so this optimization LGTM

**Comment by ijuma** [comment]
Closing this for now.

**Comment by ijuma** [comment]
@chia7712 Please check #13024 for a PR that achieves the same thing as this one tried to do.

**Pull request closed without merging**
