### PR TITLE
MINOR: update DEFAULT_FIX_VERSION to 1.1.2 in kafka-merge-pr.py

### PR DESCRIPTION
**Pull request by lindong28**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Not sure if we need this, I think the workflow should be to use the merge script from trunk generally.

**Review by mjsax — APPROVED** [review]

**Comment by lindong28** [comment]
@ijuma You are right. Thanks for pointing this out. Now looking at the kafka-merge-pr.py, it shows that the `DEFAULT_FIX_VERSION ` is only needed for the trunk branch, which in turn suggests that we do not need to change `DEFAULT_FIX_VERSION` for bug fix release. I slightly modified the release process to clarify this. 

See https://cwiki.apache.org/confluence/pages/diffpagesbyversion.action?pageId=34840886&selectedPageVersions=140&selectedPageVersions=141.

**Comment by lindong28** [comment]
Thanks for your review @mjsax. I closed the PR since it seems not necessary for non-trunk branch.

**Comment by ijuma** [comment]
Thanks for updating the release process instructions.

**Pull request closed without merging**
