### PR TITLE
KAFKA-5457: MemoryRecordsBuilder.hasRoomFor should account for record headers

### PR DESCRIPTION
**Pull request by apurvam**

### CODE REVIEW

**Comment by apurvam** [comment]
cc @hachikuji @ijuma

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5367/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5382/
Test PASSed (JDK 7 and Scala 2.11).

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the fix!

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM. I also removed `DefaultRecord.sizeInBytes` that did not take headers before merging to trunk and 0.11.0.

**Pull request closed without merging**
