### PR TITLE
KAFKA-9634: Add note about thread safety of ConfigProvider

### PR DESCRIPTION
**Pull request by tombentley**
Fixes KAFKA-9634.

### CODE REVIEW

**Comment by tombentley** [comment]
Any chance of code reivew @rajinisivaram, @kkonstantine, @hachikuji?

**Review by kkonstantine — APPROVED** [review]
That's a good observation @tombentley. Thanks for the PR!
This LGTM

Yet, since I'd like to backport, I'll hold off from merging at the moment, to make sure first I won't interfere with a couple of release candidates that are outstanding (currently for `2.5.0` and `2.4.1`)

**Comment by kkonstantine** [comment]
ok to test

**Comment by tombentley** [comment]
@kkonstantine are you able to merge this now or are you still waiting for 2.5.0?

**Comment by kkonstantine** [comment]
2.5 is still in RC generation and testing phase and only blockers are considered for merging on that version branch. Best to wait for this non-urgent PR, which would be nice to backport. 

I'll keep track of this and a few other PRs to merge once we go out of code freeze again soon. Thanks for the reminder.

**Comment by kkonstantine** [comment]
One irrelevant test failure on jdk11. Will merge this documentation change, since it's zero risk. 
Thanks for improving the docs with this useful note @tombentley !

**Comment by kkonstantine** [comment]
Merged to `trunk` and backported to `2.5, 2.4, 2.3, 2.2, 2.1` and `2.0`

**Pull request merged**
