### PR TITLE
KAFKA-13785: [Emit final][4/N] add time ordered store factory

### PR DESCRIPTION
**Pull request by lihaosky**
### Description
Add factory to create time ordered store supplier

### Testing
Added new unit test

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by guozhangwang — COMMENTED** [review]
Hi @lihaosky thanks for the PR, overall it looks good but I'm wondering if it is intentional to add it to a public API (Stores). I left some comments in the KIP discussion.

**Comment by lihaosky** [comment]
Hi @guozhangwang , I didn't realize `Stores` is public API and may need KIP for it 😛 . I can create an internal factory to do this.

**Review by guozhangwang — APPROVED** [review]
LGTM!

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request merged**
