### PR TITLE
MINOR: remove duplicate map in StoreChangelogReader

### PR DESCRIPTION
**Pull request by mjsax**
This is a follow up to #5013. The end offset for each partition is already maintained correctly in `endOffsets` within `initialize()`; thus, the introduced `updatedEndOffsets` is redundant -- we missed this during review. Thanks to @guozhangwang for pointing out.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @ConcurrencyPractitioner @bbejeck @vvcephei

**Comment by guozhangwang** [comment]
retest this please

**Review by guozhangwang — APPROVED** [review]
LGTM assuming the jenkins test passed.

Need to cherry-pick to 2.0

**Review by vvcephei — APPROVED** [review]

**Comment by mjsax** [comment]
Retest this please

**Review by bbejeck — APPROVED** [review]

**Comment by mjsax** [comment]
Retest this please

**Comment by mjsax** [comment]
Test failures are unrelated... I try one last time...

retest this please

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.0`.

**Pull request merged**
