### PR TITLE
HOTFIX: ProducerPerformanceTest should not use mutable default arguments

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
Mutable default arguments are shared by all instances (if not overridden). In this case, the `settings` argument was being modified for SSL in one of the quota tests (or another like it), which caused the SSL configuration to mistakenly propagate to the throttling tests, which use plaintext.

**Comment by hachikuji** [comment]
Test run with quota tests executing before throttling tests: http://testing.confluent.io/confluent-kafka-branch-builder-system-test-results/?prefix=2016-10-01--001.1475363113--hachikuji--hotfix-producer-perf-service--4666586/.

**Review by apurvam — APPROVED** [review]
Looks good to me. 

Looks like `jmx_attributes` suffered the same problem and is being fixed in this PR as well. It would be good to call that out in the description.

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
