### PR TITLE
KAFKA-9034 Tolerate spaces in $JAVA_HOME

### PR DESCRIPTION
**Pull request by sebwills**
This allows kafka tools to work on Cygwin where $JAVA_HOME typically contains a space (e.g. "C:\Program Files\Java\jdkXXX")

### CODE REVIEW

**Review by rondagostino — COMMENTED** [review]
Thanks for the PR, @sebwills  -- LGTM

**Review by chia7712 — APPROVED** [review]
```bash
JAVA_MAJOR_VERSION=$($JAVA -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p')
```

There is another similar code in the ```kafka-run-class.sh```. Should it be fixed also?

**Comment by sebwills** [comment]
> ```shell
> ```shell
> JAVA_MAJOR_VERSION=$($JAVA -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p')
> ```
> 
> 
> There is another similar code in the kafka-run-class.sh. Should it be fixed also?
> ```

Good spot. Yes, it should be. I've updated, and tested it on Cygwin to confirm.

What is the process for getting this PR merged now?

**Review by omkreddy — APPROVED** [review]
@sebwills Thanks for the PR. LGTM

**Pull request closed without merging**
