### PR TITLE
KAFKA-8745: DumpLogSegments doesn't show keys, when the message is null

### PR DESCRIPTION
**Pull request by wushujames**
Make sure to show the message key, even when the message value is null.

This changes the output of one of the tools. Is the output of the tool considered a public API? Does this need a discussion or a KIP?

Testing: Ran the tool on a compacted topic. Previously, the tool did not show any message keys for tombstone messages (messages where the value is null). Now, the tool shows message keys.

### CODE REVIEW

**Comment by guozhangwang** [comment]
@wushujames The failure on test `kafka.server.DescribeLogDirsRequestTest.testDescribeLogDirsRequest` seems relevant.

**Comment by guozhangwang** [comment]
The output of the tool is considered as a public API change, yes, but I think this is more like a bug fix than changing a previous bug-free public API. The change lgtm, could you take a look at the failing test and see if it exposed some concerns?

**Comment by wushujames** [comment]
@guozhangwang: I checked out trunk and ran the `kafka.server.DescribeLogDirsRequestTest.testDescribeLogDirsRequest` code in a loop. It appears to be a flaky test. I got about a 50% PASS ratio.

I don't see any JIRA for the flaky test. Should I open one?

In the meantime, I've merged in the latest trunk into this PR. The tests have started. We'll see if they pass or not.

**Comment by wushujames** [comment]
2 builds passed. The remaining one failed for the following tests:

- kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevels

- kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevelsCanResetLoggerToCurrentRoot

which are different than the previously test failures, and seem unrelated to my change. It looks like flaky tests to me.

@guozhangwang , is this safe to merge?

**Review by mimaison — APPROVED** [review]
Nice find! LGTM

**Comment by guozhangwang** [comment]
@wushujames yeah I think you are right, it is not relevant.

Could you add a new test under `DumpLogSegmentsTest` for this behavior change also?

**Comment by wushujames** [comment]
@guozhangwang: Added a test, and did some refactoring. The tests pass. My Scala isn't very good, but hopefully I got the Scala-isms right. Can you re-review? Thanks.

**Comment by wushujames** [comment]
retest this please

**Comment by wushujames** [comment]
2 builds successful, and the 3rd build timed out.  @guozhangwang , what do you think? Okay to merge?

**Review by guozhangwang — APPROVED** [review]
LGTM! thanks @wushujames

**Pull request merged**
