### PR TITLE
Testing PR build scan

### PR DESCRIPTION
**Pull request by mumrah**
Just open for testing

### CODE REVIEW

**Comment by mumrah** [comment]
@chia7712 looks like it worked! 

Here is one of the reports for this PR (coming from my fork): https://ge.apache.org/s/icjmgcm6xszvy

I see one issue I'll file a fix for shortly.

**Comment by chia7712** [comment]
> I see one issue I'll file a fix for shortly.

Did you mean this issue: https://github.com/apache/kafka/actions/runs/10776195209/job/29882369035 ?

```
Run actions/download-artifact@v4
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: build-scan-test-11
        Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
        For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```

**Comment by chia7712** [comment]
> Did you mean this issue: https://github.com/apache/kafka/actions/runs/10776195209/job/29882369035 ?

It seems the `CI Complete` always tries to download the test result even though the PR does not run the test. I guess that can be fixed by merging #17105 which enable test by default.

**Comment by mumrah** [comment]
@chia7712 #17105 and #17140 will fix the failing "CI Complete" actions

**Pull request closed without merging**
