### PR TITLE
MINOR: Upgrade ducktape to 0.7.5

### PR DESCRIPTION
**Pull request by kkonstantine**
Upgrade to the latest version of ducktape (0.7.5)
Safe to upgrade branches that already have 0.7.1 (that is 1.0 and ahead)

Tested by running all system tests with version 0.7.5 of ducktape

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kkonstantine** [comment]
@ewencp @ijuma @cmccabe 
ducktape update proceeded smoothly. I believe we can merge back to 1.0 that is the earliest branch using ducktape 0.7.1

**Comment by cmccabe** [comment]
LGTM

**Comment by cmccabe** [comment]
Backported to 2.1.  I'm not sure if we should backport further unless we decide to make a release for one of those older branches.

**Comment by kkonstantine** [comment]
Thanks for backporting @cmccabe 
Here's a reason to backport even further: this PR affects the system tests that run in every version branch rather than the actual release itself. These system tests run frequently, regardless of release plans.

I noticed that ducktape 0.7.1 was present as far as Kafka v1.0 I believe it's a trivial commit so it seems reasonable to me to backport up to v1.0. The PR that will use ducktape 0.7.5 that was merged here is: https://github.com/apache/kafka/pull/6158 and I believe we should merge heap dump support in system tests also at least as far back as v1.0. 

Hope this background helps a bit.

**Comment by ewencp** [comment]
Cherry-picking to 2.0, 1.1, and 1.0. Some older branches need another minor update to pin the pip version, which for some reason looks like it was only backported to 2.0 but leaves ducker in a broken state.

**Pull request merged**
