### PR TITLE
MINOR: Fix regex on connector path param in ConnectorsResource

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@hachikuji @shikhar @kkonstantine This slipped in with https://github.com/apache/kafka/pull/2096 where I was thinking the regex would simply require at least one character, but the default regex, `[^/]+` already does that. Instead, this was more liberal and would match even `/` characters, which meant it was matching a bunch of patterns previously handled by other methods. This resulted in 405 Method Not Supported errors because the routing was targeting the wrong methods.

**Comment by kkonstantine** [comment]
LGTM

**Comment by shikhar** [comment]
LGTM, the utility of supporting DELETE for such connector names seems limited anyway, since #2096 prevents them from being created.

**Comment by hachikuji** [comment]
LGTM

**Pull request closed without merging**
