### PR TITLE
Minor: Add JUnit Foundation for setting default junit timeouts

### PR DESCRIPTION
**Pull request by mumrah**
This patch adds the JUnit Foundation library which does annotation munging to set a default timeout value for JUnit tests.

### CODE REVIEW

**Comment by mumrah** [comment]
After some experimenting, I confirmed this will only set the timeout value for `@Test` annotations that do not have the `timeout` param set. As such, this will effectively override class level `@Rule` timeouts.

**Comment by ijuma** [comment]
Why not use @Rule?

**Comment by mumrah** [comment]
@ijuma with this we can avoid having to include a timeout `@Rule` in each test file. Since it's controlled via system property, we can also change it at runtime which could be useful for people running on slower machines.

**Comment by mumrah** [comment]
retest this please

**Comment by ijuma** [comment]
The Java agent is what gives me pause...

**Comment by mumrah** [comment]
Doesn't look like this will work after all. 

The JUnit Foundation agent intercepts the actual test running and doesn't seem to conform to normal JUnit behavior. E.g., test classes which inherit from an abstract test class and do not have any declared methods with a `@Test` annotation will fail to initialize. Also, as mentioned above it does not play well with JUnit `@Rule`.

I also tried using a custom JUnit `RunListener` to try and modify the annotations on the fly, but it seems like modifying the annotation in the listener is too late in the test lifecycle. 

Closing this.

**Pull request closed without merging**
