### PR TITLE
MINOR: Upgrade to Gradle 8.1

### PR DESCRIPTION
**Pull request by ijuma**
Release notes:
https://docs.gradle.org/8.1/release-notes.html

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bmscomp** [comment]
I think it's enough to use a `bin` distribution type instead  instead of `all`  one for Gradle wrapper

**Comment by divijvaidya** [comment]
A new big fix release is available 8.1.1 and the release notes mention: "We recommend users upgrade to 8.1.1 instead of 8.1."

I would suggest to discard this PR and instead review https://github.com/apache/kafka/pull/13625

**Comment by ijuma** [comment]
It's a little odd to create a new PR instead of simply updating the one that's open...

**Comment by bmscomp** [comment]
@ijuma  Apologies, may be it's more wise to close the one I created and keep updating this one, I'll update my pull request since it contains also some Gradle plugin upgrades

**Comment by ijuma** [comment]
In the future, please try to work with the contributor who submitted a PR instead of creating your own. In this case, I went ahead and merged your PR and closed this one.

**Comment by bmscomp** [comment]
@ijuma  Yes of course, I'll do that , this is the first PR ever for me in this repo, I'll keep learning from all of you

**Comment by divijvaidya** [comment]
Thank you for making this is a teaching moment @ijuma. I will try to do better reviews, keeping in mind your suggestion in future.

**Pull request closed without merging**
