### PR TITLE
MINOR: clean up unused methods in core utils

### PR DESCRIPTION
**Pull request by jlprat**
Inspired by https://github.com/apache/kafka/pull/13170 I decided to check some other core utils classes and remove some unused methods.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
@mimaison I took inspiration from your PR to clean up some more unused methods

**Review by machi1990 — APPROVED** [review]
lgtm, thanks.

While we are at it, can we fix the typo in https://github.com/apache/kafka/blob/ea68b65345e0ca295609d56f914dc5bbc760af11/core/src/main/scala/kafka/utils/PasswordEncoder.scala#L39 as the variable should read: `EncryptedPasswordProp`

**Comment by jlprat** [comment]
Thanks @machi1990 I fixed the typo as well

**Review by machi1990 — APPROVED** [review]
LGTM, thanks @jlprat

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR

**Comment by jlprat** [comment]
All test failures seem to be unrelated to the change.

**Pull request merged**
