### PR TITLE
KAFKA-7856: Fix vulnerability CWE-331

### PR DESCRIPTION
**Pull request by tbaldo**
fix vulnerability pointed by CWE.
Cryptographic Issues by Insufficient Entropy (CWE-331 - Flaw medium,SANS
TOP 25)
This change should be promoted to new versions.

### CODE REVIEW

**Comment by cmccabe** [comment]
I don't see how this is a vulnerability.  The random number generator is only being used to adjust the jitter which is added to the credential refresh period.  An attacker doesn't gain anything by guessing this sequence of numbers, as best as I can tell.

**Comment by vasartori** [comment]
hi @cmccabe 
This [security flaw](https://cwe.mitre.org/data/definitions/331.html) is a low vulnerability but if you submit kafka client to security scan (like [veracode](https://www.veracode.com/) ) a flaw will be appointed.
But this small issue has a "plus" in your security score because it is listed in top 25 of CWE/SANS Most Dangerous Software Errors (http://cwe.mitre.org/top25/)

**Comment by cmccabe** [comment]
Static analysis tools are not perfect and they often warn about things which are not real problems.  In this particular case, I don't see why the random numbers used for random delays need to be cryptographically secure.  Can you explain how this is a vulnerability?

**Comment by tbaldo** [comment]
Hi @cmccabe 
I agree with you. Static analysis is not very reliable.
Maybe the subtitle is not accurate. I think this could be fix cryptographic issue, not a vulnerability.
See the report show to us. https://imgur.com/a/HCradBj.

Another alternative is use the method setSeed from Random class. What do you think about this approach?

**Comment by cmccabe** [comment]
> Maybe the subtitle is not accurate. I think this could be fix cryptographic issue, not a vulnerability

I'm not sure I follow.  What's the cryptographic issue here?

> Another alternative is use the method setSeed from Random class. What do you think about this approach?

The JavaDoc for `Random#Random` says:
> Creates a new random number generator. This constructor sets the seed of the random number generator to a value very likely to be distinct from any other invocation of this constructor.

Why would we need to initialize the seed on our own here?

**Comment by tbaldo** [comment]
> Why would we need to initialize the seed on our own here? 
>
Because the number generated by Random has a low entropy and when we add setSeed the number is less predictable.
When we use SecureRandom (in PR) the number generate has more digits and entropy is better.

Use SecureRandom has low performance? This will impact in kafka?

**Comment by cmccabe** [comment]
> Because the number generated by Random has a low entropy and when we add setSeed the number is less predictable.

`Random#Random` already seeds the RNG with the current time.  From the jdk8 source code:

```
    /**
     * Creates a new random number generator. This constructor sets
     * the seed of the random number generator to a value very likely
     * to be distinct from any other invocation of this constructor.
     */
    public Random() {
        this(seedUniquifier() ^ System.nanoTime());
    }
```

Re-seeding it with the time will not help.

> When we use SecureRandom (in PR) the number generate has more digits and entropy is better.

You haven't explained why we need more entropy here.

**Comment by cmccabe** [comment]
There seems to be no security issue here.

**Pull request closed without merging**
