### PR TITLE
MINOR: fix flaky QueryableStateIntegrationTest

### PR DESCRIPTION
**Pull request by mjsax**
Test `#concurrentAccesses()` fails regularly on `0.11.0` branch, so I compared the test code with current `trunk` version and back ported all changes. Hope this will stabilize the test.

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman

**Review by bbejeck — APPROVED** [review]
Thanks for the cleanup @mjsax LGTM

**Comment by mjsax** [comment]
Tests passed. Will trigger couple of reruns to make sure the test is stable.

Retest this please.

**Comment by mjsax** [comment]
Tests passed again. Will trigger couple of reruns to make sure the test is stable.

Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Test failed again:
```
java.lang.AssertionError: Condition not met within timeout 120000. Did not receive all 202 records from topic output-concurrent-4
	at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:274)
	at org.apache.kafka.streams.integration.utils.IntegrationTestUtils.waitUntilMinValuesRecordsReceived(IntegrationTestUtils.java:286)
	at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.waitUntilAtLeastNumRecordProcessed(QueryableStateIntegrationTest.java:1022)
	at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses(QueryableStateIntegrationTest.java:451)
```

Will investigate further.

**Comment by mjsax** [comment]
Failed with
```
Exception in thread "queryable-state-4-c251bd5d-1379-4e0d-9cd7-2f73592474fb-StreamThread-72" org.apache.kafka.streams.errors.ProcessorStateException: task [2_0] Failed to flush state store windowed-word-count-store-stream-concurrent-4
	at org.apache.kafka.streams.processor.internals.ProcessorStateManager.flush(ProcessorStateManager.java:318)
	at org.apache.kafka.streams.processor.internals.AbstractTask.flushState(AbstractTask.java:194)
	at org.apache.kafka.streams.processor.internals.StreamTask.flushState(StreamTask.java:316)
	at org.apache.kafka.streams.processor.internals.StreamTask$1.run(StreamTask.java:287)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:201)
	at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:282)
	at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:276)
	at org.apache.kafka.streams.processor.internals.AssignedTasks$1.apply(AssignedTasks.java:335)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.applyToRunningTasks(AssignedTasks.java:428)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.commit(AssignedTasks.java:327)
	at org.apache.kafka.streams.processor.internals.StreamThread.commitAll(StreamThread.java:724)
	at org.apache.kafka.streams.processor.internals.StreamThread.maybeCommit(StreamThread.java:707)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndPunctuate(StreamThread.java:657)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:513)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:482)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:459)
Caused by: org.apache.kafka.streams.errors.ProcessorStateException: Error while executing flush from store windowed-word-count-store-stream-concurrent-4-201903170000
	at org.apache.kafka.streams.state.internals.RocksDBStore.flushInternal(RocksDBStore.java:372)
	at org.apache.kafka.streams.state.internals.RocksDBStore.flush(RocksDBStore.java:363)
	at org.apache.kafka.streams.state.internals.Segments.flush(Segments.java:144)
	at org.apache.kafka.streams.state.internals.RocksDBSegmentedBytesStore.flush(RocksDBSegmentedBytesStore.java:123)
	at org.apache.kafka.streams.state.internals.WrappedStateStore$AbstractStateStore.flush(WrappedStateStore.java:78)
	at org.apache.kafka.streams.state.internals.MeteredSegmentedBytesStore.flush(MeteredSegmentedBytesStore.java:122)
	at org.apache.kafka.streams.state.internals.WrappedStateStore$AbstractStateStore.flush(WrappedStateStore.java:78)
	at org.apache.kafka.streams.state.internals.CachingWindowStore.flush(CachingWindowStore.java:124)
	at org.apache.kafka.streams.processor.internals.ProcessorStateManager.flush(ProcessorStateManager.java:316)
	... 15 more
Caused by: org.rocksdb.RocksDBException: Ä
	at org.rocksdb.RocksDB.flush(Native Method)
	at org.rocksdb.RocksDB.flush(RocksDB.java:1642)
	at org.apache.kafka.streams.state.internals.RocksDBStore.flushInternal(RocksDBStore.java:370)
	... 23 more
```

Seems to be RocksDB issue for older branches.

Retest this please.

**Comment by mjsax** [comment]
Retest this please

**Comment by mjsax** [comment]
Java7 timed out:
```
15:28:30 org.apache.kafka.streams.integration.QueryableStateIntegrationTest > concurrentAccesses FAILED
15:28:30     java.lang.AssertionError: Condition not met within timeout 120000. Did not receive all 202 records from topic output-concurrent-windowed-4
15:28:30         at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:274)
15:28:30         at org.apache.kafka.streams.integration.utils.IntegrationTestUtils.waitUntilMinValuesRecordsReceived(IntegrationTestUtils.java:286)
15:28:30         at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.waitUntilAtLeastNumRecordProcessed(QueryableStateIntegrationTest.java:1022)
15:28:30         at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses(QueryableStateIntegrationTest.java:452)
```

Java8 passed.

Retest this please.

**Comment by mjsax** [comment]
Similar error. @guozhangwang Do you think it's ok to merge this even if only Java8 passes?

Retest this please.

**Comment by mjsax** [comment]
Java7:
```
00:41:29 org.apache.kafka.streams.integration.QueryableStateIntegrationTest > concurrentAccesses FAILED
00:41:29     java.lang.AssertionError: Condition not met within timeout 120000. Did not receive all 202 records from topic output-concurrent-windowed-4
00:41:29         at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:274)
00:41:29         at org.apache.kafka.streams.integration.utils.IntegrationTestUtils.waitUntilMinValuesRecordsReceived(IntegrationTestUtils.java:286)
00:41:29         at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.waitUntilAtLeastNumRecordProcessed(QueryableStateIntegrationTest.java:1022)
00:41:29         at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses(QueryableStateIntegrationTest.java:452)
```
and
```
00:45:26 org.apache.kafka.streams.KafkaStreamsTest > testStateThreadClose FAILED
00:45:26     java.lang.AssertionError: Condition not met within timeout 10000. Thread never stopped.
00:45:26         at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:274)
00:45:26         at org.apache.kafka.streams.KafkaStreamsTest.testStateThreadCloseHelper(KafkaStreamsTest.java:126)
00:45:26         at org.apache.kafka.streams.KafkaStreamsTest.testStateThreadClose(KafkaStreamsTest.java:161)
```

Java8:
```
00:33:23 org.apache.kafka.streams.integration.QueryableStateIntegrationTest > concurrentAccesses FAILED
00:33:23     java.lang.AssertionError: Condition not met within timeout 120000. Did not receive all 202 records from topic output-concurrent-4
00:33:23         at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:274)
00:33:23         at org.apache.kafka.streams.integration.utils.IntegrationTestUtils.waitUntilMinValuesRecordsReceived(IntegrationTestUtils.java:286)
00:33:23         at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.waitUntilAtLeastNumRecordProcessed(QueryableStateIntegrationTest.java:1022)
00:33:23         at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses(QueryableStateIntegrationTest.java:451)
```
and
```
23:44:34 kafka.server.LogRecoveryTest > testHWCheckpointWithFailuresSingleLogSegment FAILED
23:44:34     java.lang.AssertionError: Timing out after 30000 ms since a new leader that is different from 1 was not elected for partition new-topic-0, leader is Some(1)
23:44:34         at kafka.utils.TestUtils$.fail(TestUtils.scala:333)
23:44:34         at kafka.utils.TestUtils$$anonfun$waitUntilLeaderIsElectedOrChanged$8.apply(TestUtils.scala:808)
23:44:34         at kafka.utils.TestUtils$$anonfun$waitUntilLeaderIsElectedOrChanged$8.apply(TestUtils.scala:798)
23:44:34         at scala.Option.getOrElse(Option.scala:121)
23:44:34         at kafka.utils.TestUtils$.waitUntilLeaderIsElectedOrChanged(TestUtils.scala:798)
23:44:34         at kafka.server.LogRecoveryTest.testHWCheckpointWithFailuresSingleLogSegment(LogRecoveryTest.scala:152)
```

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Java7 passed. 

Java8:
```
10:58:01 org.apache.kafka.streams.integration.QueryableStateIntegrationTest > concurrentAccesses FAILED
10:58:01     java.lang.AssertionError: Condition not met within timeout 120000. Did not receive all 202 records from topic output-concurrent-4
10:58:01         at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:274)
10:58:01         at org.apache.kafka.streams.integration.utils.IntegrationTestUtils.waitUntilMinValuesRecordsReceived(IntegrationTestUtils.java:286)
10:58:01         at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.waitUntilAtLeastNumRecordProcessed(QueryableStateIntegrationTest.java:1022)
10:58:01         at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.concurrentAccesses(QueryableStateIntegrationTest.java:451)
```

We got both Java version to pass at some point. Merging this now.

**Pull request merged**
