### PR TITLE
MINOR: Remove version in the uses page

### PR DESCRIPTION
**Pull request by guozhangwang**
This is contributed by Hao Chen.

### CODE REVIEW

**Comment by guozhangwang** [comment]
This is contributed as of https://github.com/apache/kafka-site/pull/49. Please make sure the contributor is set to its author when merging. cc @gwenshap @ijuma

**Comment by guozhangwang** [comment]
Also added the changes made in https://github.com/apache/kafka-site/pull/18/files.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5463/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5448/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ijuma — APPROVED** [review]
LGTM, I'll let you merge @guozhangwang.

**Comment by guozhangwang** [comment]
Merged to trunk and 0.11.0.

**Pull request closed without merging**
