### PR TITLE
KAFKA-17392: Remove whitelist option in ConsoleConsumerOptions

### PR DESCRIPTION
**Pull request by mingyen066**
As title. Additionally, I found some code related to `whitelist` in `ReplicaVerificationTool`. However, since the tool will be removed in 5.0 [1], I won't make any changes to the tool.

[1] [[KAFKA-17074] Remove ReplicaVerificationTool](https://issues.apache.org/jira/browse/KAFKA-17074)

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by m1a2st — COMMENTED** [review]
@mingyen066, Thanks for your PR, There are some test is error in `ConsoleConsumerOptionsTest` with `--whitelist` argument, You should check these fail test

**Comment by mingyen066** [comment]
> @mingyen066, Thanks for your PR, There are some test is error in `ConsoleConsumerOptionsTest` with `--whitelist` argument, You should check these fail test

thanks @m1a2st. I accidentally used test `ConsoleConsumerTest` incorrectly.

**Comment by mingyen066** [comment]
> @mingyen066, Thanks for your PR, There are some test is error in `ConsoleConsumerOptionsTest` with `--whitelist` argument, You should check these fail test

The code related to whitelist has already been removed.

**Review by chia7712 — COMMENTED** [review]
@mingyen066 thanks for this patch. Could you please add docs to https://github.com/apache/kafka/blob/trunk/docs/upgrade.html#L35

**Comment by mingyen066** [comment]
> @mingyen066 thanks for this patch. Could you please add docs to https://github.com/apache/kafka/blob/trunk/docs/upgrade.html#L35

@chia7712 Thanks for reviewing PR. The information about the removal of the `--whitelist` option has already been added to the docs.

**Pull request merged**
