### PR TITLE
HOTFIX: Convert exception to warning since clearly it is happening.

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
@norwood @guozhangwang

**Comment by ewencp** [comment]
Is this really what we would want? Just looking at that code snippet, the state transition is invalid. It seems like the right thing to do is throw the exception and kill whatever thread/process is doing something wrong. Obviously it's not ideal that we've got a path that can do an invalid transition, but is just warning about it a good idea?

**Comment by enothereska** [comment]
@ewencp right now the code is not written with clear state transitions in mind, we'll get there, but we're not there yet.

**Comment by ewencp** [comment]
@enothereska What's your preference then? This is easily committable as the change is trivial, I guess we're just backing out the addition of the exceptions from KAFKA-3637? Given that there's something more that needs to be thought through here, do we prefer `warn` so it's a soft error or `error` so we see bug reports from more variations of the issue (we have at least a couple of different variations of incorrect/unexpected transitions already reported)?

**Comment by enothereska** [comment]
Let's keep it as `warn` since it's a soft error only, so keep as is. Thank you @ewencp

**Comment by ewencp** [comment]
OK then, LGTM to address the regression in behavior. @enothereska I assume there is/will be some follow up JIRA?

**Comment by enothereska** [comment]
Yes, thank you.

**Pull request closed without merging**
