### PR TITLE
KAFKA-9088: Consolidate InternalMockProcessorContext and MockInternalProcessorContext

### PR DESCRIPTION
**Pull request by pierDipi**
KAFKA-9088: Consolidate InternalMockProcessorContext and MockInternalProcessorContext

Merge `InternalMockProcessorContext` into `MockInternalProcessorContext`
and replace all `InternalMockProcessorContext` usages by
`MockInternalProcessorContext`.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by pierDipi** [comment]
Call for review @cadonna @mjsax @bbejeck @guozhangwang

**Comment by cadonna** [comment]
@pierDipi Many thanks for this PR!

I did a quick first pass and here are my first comments/questions:

- Is there a specific reason why you rejected the option to replace `MockInternalProcessorContext` and `InternalMockProcessorContext` with an `EasyMock` mock? Using `EasyMock` would make the mock independent from productive code and it would free us from maintaining a full-blown self-made mock. Maybe some utility methods that provide some common setups for a `EasyMock` mock for the `InternalProcessorContext` would suffice here.
- I realized now that `InternalProcessorContext` extends `AbstractProcessorContext` in the current code base. IMO this is not a good idea because a mock should be as independent as possible from productive code since you want to isolate the code under test as much as possible from other productive code. I am aware that this class hierarchy is actually not your fault because you took this hierarchy over from the current code base.
- You modified `MockProcessorContext`. This is a user-facing API. The API and the behaviour of the `MockProcessorContext` must stay the same. If this is not possible, a KIP is needed. For more information see https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals
- All the builds failed because of checkstyle issues. Please review our coding guidelines under https://kafka.apache.org/coding-guide and execute `./gradlew streams:checkstyleMain streams:checkstyleTest` to check code style conformity. The code style mistakes that are not found by checkstyle will be mentioned during the review of the PR.

Looking forward to your contributions!

**Comment by pierDipi** [comment]
@cadonna Thanks for the quick response.

If I understand correctly with the `EasyMock` way we replace all `InternalMockProcessorContext` and `MockInternalProcessorContext` usages.
For example, in the test method [`KTableSuppressProcessorTest#zeroTimeLimitShouldImmediatelyEmit`](https://github.com/apache/kafka/blob/trunk/streams/src/test/java/org/apache/kafka/streams/kstream/internals/suppress/KTableSuppressProcessorTest.java) we would have something like the following: 
```java
    @Test
    public void zeroTimeLimitShouldImmediatelyEmit() {
        final Harness<String, Long> harness = new Harness<>(untilTimeLimit(ZERO, unbounded()), String(), Long());
        final String storeName = "test-store";
        final InternalProcessorContext context = EasyMock.mock(InternalProcessorContext.class);
        final StreamsConfig streamsConfig = new QuietStreamsConfig(new Properties() {
            {
                put(StreamsConfig.APPLICATION_ID_CONFIG, "");
                put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "");
            }
        });
        final MetricConfig metricConfig = new MetricConfig();
        metricConfig.recordLevel(Sensor.RecordingLevel.DEBUG);
        final String threadId = Thread.currentThread().getName();
        final StreamsMetricsImpl metrics = new StreamsMetricsImpl(
                new Metrics(metricConfig),
                threadId,
                streamsConfig.getString(StreamsConfig.BUILT_IN_METRICS_VERSION_CONFIG)
        );
        final Serde<?> keySerde = String();
        final Serde<?> valueSerde = Long();
        final StateStore buffer =
                new InMemoryTimeOrderedKeyValueBuffer.Builder<>(storeName, keySerde, valueSerde)
                .withLoggingDisabled()
                .build();
        EasyMock.expect(context.metrics()).andReturn(metrics).anyTimes();
        EasyMock.expect(context.taskId()).andReturn(EasyMock.mock(TaskId.class)).anyTimes();
        EasyMock.expect(context.currentNode()).andReturn(new ProcessorNode("testNode")).anyTimes();
        EasyMock.expect(context.getStateStore(storeName)).andReturn(buffer).anyTimes();
        context.register(EasyMock.anyObject(), EasyMock.anyObject());
        EasyMock.expectLastCall().anyTimes();
        // ...
        // ...
        EasyMock.replay(context);
        buffer.init(context, buffer);
        harness.processor.init(context);
        final String key = "hey";
        final Change<Long> value = ARBITRARY_CHANGE;
        context.forward(key, value);
        EasyMock.replay(context);
        harness.processor.process(key, value);
        // ...
        // ... 
    }
```
This should be done for each `InternalMockProcessorContext` and `MockInternalProcessorContext` usage trying to extract some common mock setup, right?

**Comment by cadonna** [comment]
@pierDipi Yes, that would be the main idea. Before you dive into coding, please have a look at https://issues.apache.org/jira/browse/KAFKA-8630 that is related to this issue. I never tried to make a EasyMock mock available in a public interface as required in KAFKA-8630. Let's discuss about this aspect in ticket KAFKA-9088. Maybe try to code some examples to get some insights. Looking forward to your results.

**Comment by mjsax** [comment]
@pierDipi Do you have an Jira account so we can assign the ticket to you?

**Comment by pierDipi** [comment]
@mjsax My username is `pierDipi`.

**Comment by pierDipi** [comment]
Close in favor of #7718

**Pull request closed without merging**
