### PR TITLE
KAFKA-3872: Reduce log cleaner buffer size to 2 MB

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
@ijuma could you have a look? Thanks.

**Comment by ijuma** [comment]
LGTM if the tests pass.

**Comment by guozhangwang** [comment]
@ijuma @enothereska LGTM. This PR build seems stalled but not on any specific test case. Maybe we can trigger a bunch of Jenkins jobs and see if it re-occurs?

**Comment by ijuma** [comment]
@guozhangwang seems like the build took too long for some reason. It's unrelated to this PR though as the streams tests didn't actually run.

**Comment by ijuma** [comment]
Running the tests locally and if they pass, I will merge.

**Comment by ijuma** [comment]
Merged to trunk.

**Pull request closed without merging**
