### PR TITLE
KAFKA-17340 correct the docs of `allow.auto.create.topics`

### PR DESCRIPTION
**Pull request by lushilin**
…o.create.topics=false when using brokers older than 0.11.0

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lushilin** [comment]
@guozhangwang @ijuma @junrao please take a look,thks

**Comment by jsancio** [comment]
@lushilin please update the jira ID. KAFKA-17305 describes a different issue.

**Comment by guozhangwang** [comment]
@lushilin , as @jsancio said :) Otherwise, LGTM.

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
@lushilin thanks for your contribution

**Pull request merged**
