### PR TITLE
KAFKA-18080: Replace DelayedItem by Long type

### PR DESCRIPTION
**Pull request by Yunyung**
Remove `DelayedItem` and update the code accordingly.

JIRA: https://issues.apache.org/jira/browse/KAFKA-18080

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@Yunyung Could you please remove DelayedItem directly? the only use case is ` PartitionFetchState` and so we can pass `dueMs: Option[Long]` instead of `delay Option[DelayedItem]`. The method `isDelayed` can be replaced by following code.

```scala
def isDelayed: Boolean = dueMs.map(_ - Time.SYSTEM.milliseconds).exists(_ > 0)
```

**Comment by Yunyung** [comment]
Thank you! I removed `DelayedItem` and updated the only use case, `PartitionFetchState`, accordingly.

**Comment by Yunyung** [comment]
Fix the typo I found in the code comment for `PartitionFetchState`.

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
