### PR TITLE
MINOR: Increase zk connection timeout in tests for client created in `KafkaServer`

### PR DESCRIPTION
**Pull request by ijuma**
We had already made this change to the client created in `ZooKeeperTestHarness`.
I last saw this failure when `SaslPlaintextTopicMetadataTest.testAliveBrokerListWithNoTopics`
was executed in Jenkins.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji.

Link to failure: https://jenkins.confluent.io/job/kafka-0.10.1/97/testReport/kafka.integration/SaslPlaintextTopicMetadataTest/testAliveBrokerListWithNoTopics/

**Comment by hachikuji** [comment]
LGTM. Do we need to adjust the zk session timeout as well or do you think this is only affecting the initial connection?

**Comment by ijuma** [comment]
I wondered about that, but since I haven't yet seen failures due to the session timeout, I didn't change it.

**Comment by hachikuji** [comment]
@ijuma Makes sense. I'll go ahead and merge this.

**Pull request closed without merging**
