### PR TITLE
KAFKA-13722: Refactor Kafka Streams store interfaces

### PR DESCRIPTION
**Pull request by mjsax**
Refactor Segments and TimestampedSegments to not use old ProcessorContext any longer.

### CODE REVIEW

**Review by cadonna — APPROVED** [review]
Thanks for the PR, @mjsax !

LGTM!

**Comment by mjsax** [comment]
Java 23:
```
FAILED ❌ UserQuotaTest > testThrottledProducerConsumer(String, String).quorum=kraft.groupProtocol=consumer
FAILED ❌ UserQuotaTest > testQuotaOverrideDelete(String, String).quorum=kraft.groupProtocol=classic
FAILED ❌ UserQuotaTest > testQuotaOverrideDelete(String, String).quorum=kraft.groupProtocol=consumer
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroups(String, String).quorum=kraft.groupProtocol=consumer
Found 1 flaky test failures:
FLAKY ⚠️  TransactionsWithTieredStoreTest > "testBumpTransactionalEpochWithTV2Enabled(String, String, boolean).quorum=kraft, groupProtocol=classic, isTV2Enabled=true"
```

Java 17:
```
Found 1 test failures:
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroups(String, String).quorum=kraft.groupProtocol=consumer
Found 1 flaky test failures:
FLAKY ⚠️  TransactionsWithTieredStoreTest > testFailureToFenceEpoch(String, String, boolean).quorum=kraft.groupProtocol=consumer.isTV2Enabled=true
```

**Comment by mjsax** [comment]
Java 17 passed.

Java 23:
```
Found 1 test failures:
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroups(String, String).quorum=kraft.groupProtocol=consumer
Found 2 flaky test failures:
FLAKY ⚠️  TransactionsWithTieredStoreTest > "testBumpTransactionalEpochWithTV2Enabled(String, String, boolean).quorum=kraft, groupProtocol=consumer, isTV2Enabled=true"
FLAKY ⚠️  UserQuotaTest > testQuotaOverrideDelete(String, String).quorum=kraft.groupProtocol=consumer
```

**Comment by mjsax** [comment]
Java 23:
```
Found 3 test failures:
FAILED ❌ UserQuotaTest > testQuotaOverrideDelete(String, String).quorum=kraft.groupProtocol=consumer
FAILED ❌ PlaintextConsumerCallbackTest > testGetPositionOfNewlyAssignedPartitionOnPartitionsAssignedCallback(String, String).quorum=kraft.groupProtocol=consumer
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroupsDeprecatedConsumerGroupState(String, String).quorum=kraft.groupProtocol=consumer
Found 1 flaky test failures:
FLAKY ⚠️  TransactionsWithTieredStoreTest > testReadCommittedConsumerShouldNotSeeUndecidedData(String, String).quorum=kraft.groupProtocol=consumer
```

**Comment by mjsax** [comment]
We know that `PlaintextAdminIntegrationTest` is flaky -- different test failed for the last two runs. Merging.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `4.0`.

**Pull request merged**
