### PR TITLE
MINOR: Reduced severity for "skipping records" falling out of time windows

### PR DESCRIPTION
**Pull request by xdgrulez**
Reduced severity for "skipping records" falling out of time windows/segments from "warn" to "debug" since this is, as mjsax called it on Slack, actually "regular processing", and we have metrics for skipped records anyway since Kafka Streams 2.0 (https://cwiki.apache.org/confluence/display/KAFKA/KIP-274%3A+Kafka+Streams+Skipped+Records+Metrics).

Using severity "warn" or "info" results in lots of unnecessarily cluttered logs like this - even though the skipping is actually the intended processing behavior:
{"@timestamp":"2021-06-17T19:04:44.194Z","@version":"1","message":"Skipping record for expired segment.","logger_name":"org.apache.kafka.streams.state.internals.AbstractRocksDBSegmentedBytesStore","thread_name":"prod.devices.manufacturing.pt.streamingetl.v3-5f937ad9-7f89-41c5-b4ba-591dabe838fd-StreamThread-1","level":"WARN","level_value":30000,"dd.service":"streaming-etl","dd.env":"prod","dd.span_id":"3790604313083202822","dd.trace_id":"2039260532201528974","dd.version":"1.0.0-20210616-master.4"}
{"@timestamp":"2021-06-17T19:04:44.194Z","@version":"1","message":"Skipping record for expired segment.","logger_name":"org.apache.kafka.streams.state.internals.AbstractRocksDBSegmentedBytesStore","thread_name":"prod.devices.manufacturing.pt.streamingetl.v3-5f937ad9-7f89-41c5-b4ba-591dabe838fd-StreamThread-1","level":"WARN","level_value":30000,"dd.service":"streaming-etl","dd.env":"prod","dd.span_id":"3790604313083202822","dd.trace_id":"2039260532201528974","dd.version":"1.0.0-20210616-master.4"}
{"@timestamp":"2021-06-17T19:04:44.194Z","@version":"1","message":"Skipping record for expired segment.","logger_name":"org.apache.kafka.streams.state.internals.AbstractRocksDBSegmentedBytesStore","thread_name":"prod.devices.manufacturing.pt.streamingetl.v3-5f937ad9-7f89-41c5-b4ba-591dabe838fd-StreamThread-1","level":"WARN","level_value":30000,"dd.service":"streaming-etl","dd.env":"prod","dd.span_id":"3790604313083202822","dd.trace_id":"2039260532201528974","dd.version":"1.0.0-20210616-master.4"}
{"@timestamp":"2021-06-17T19:04:44.194Z","@version":"1","message":"Skipping record for expired segment.","logger_name":"org.apache.kafka.streams.state.internals.AbstractRocksDBSegmentedBytesStore","thread_name":"prod.devices.manufacturing.pt.streamingetl.v3-5f937ad9-7f89-41c5-b4ba-591dabe838fd-StreamThread-1","level":"WARN","level_value":30000,"dd.service":"streaming-etl","dd.env":"prod","dd.span_id":"3790604313083202822","dd.trace_id":"2039260532201528974","dd.version":"1.0.0-20210616-master.4"}
{"@timestamp":"2021-06-17T19:04:44.194Z","@version":"1","message":"Skipping record for expired segment.","logger_name":"org.apache.kafka.streams.state.internals.AbstractRocksDBSegmentedBytesStore","thread_name":"prod.devices.manufacturing.pt.streamingetl.v3-5f937ad9-7f89-41c5-b4ba-591dabe838fd-StreamThread-1","level":"WARN","level_value":30000,"dd.service":"streaming-etl","dd.env":"prod","dd.span_id":"3790604313083202822","dd.trace_id":"2039260532201528974","dd.version":"1.0.0-20210616-master.4"}

### CODE REVIEW

**Review by cadonna — COMMENTED** [review]
Thank you for the PR, @xdgrulez !

To make it more explicit and avoid that we inadvertently change the level back to `warn`, could you add some unit tests?

Here an example: 
https://github.com/apache/kafka/blob/c3475081c5e8228e9bd3a45022a93d61e542f72e/streams/src/test/java/org/apache/kafka/streams/kstream/internals/KStreamSessionWindowAggregateProcessorTest.java#L381 

You can verify the level with something like this:
```
assertThat(
    appender.getEvents().stream()
        .filter(e -> e.getLevel().equals("DEBUG"))
        .map(Event::getMessage)
        .collect(Collectors.toList()),
    hasItem(<the log message to verify>)
);

```

**Comment by cadonna** [comment]
FYI: I opened PR #10920 to improve the unit tests for the log messages for the other types of dropped records.

**Review by showuon — COMMENTED** [review]
IMO, we can change from `WARN` to `INFO`, not to `DEBUG` because
1. As described, this is "regular processing", so it should not be `WARN` log
2. It might be helpful for some users who already get used to check the skipping record logs. Change to INFO can still find the logs (if log level is not changed), and won't trigger unnecessary `WARN` alert to users.

What do you think?

**Comment by cadonna** [comment]
@showuon I think one of the reasons to use `DEBUG` is no decrease the log messages which woiuld not be the case with `INFO`.

**Comment by xdgrulez** [comment]
> @showuon I think one of the reasons to use `DEBUG` is no decrease the log messages which woiuld not be the case with `INFO`.

Absolutely - we had a big influx of these WARN messages in our logs and I would prefer not to have them in INFO either. I mean it's just annoying ;-)

(+ sorry for not having time yet to write the tests...)

**Comment by ableegoldman** [comment]
I completely agree that these are too frequent to warrant even being at INFO, however it's unfortunate to lose this information entirely as @showuon pointed out. Can we still keep track of the skipped records and instead just log a summary warning every 1,000 records (or something), like we do elsewhere?

**Comment by mjsax** [comment]
Btw: I am just realizing that we actually log the `key` and thus leak user data into the logs. We must fix this. Thus, we should either switch to `TRACE` level (we consider `TRACE` ok, and have other places where we log user data in `TRACE`), or remove user data from the log message.

**Comment by ableegoldman** [comment]
Hey @xdgrulez , this PR has a number of test failures. It looks like there are quite a few tests that are verifying the existence of this specific message, and failing because the logs default to INFO. Can you look into those and then run the full set of streams tests once you think you've fixed everything to make sure no new failures have come up since then? 
Thanks!

**Comment by xdgrulez** [comment]
Hi,

will do that as soon as I have some time - and sorry for not finding time yet…

If anyone else would have some more time on her/his hand - you basically just would have to spot all tests checking for the respective warn log messages and change them to debug…

Best, Ralph

**Comment by xdgrulez** [comment]
Hi,

I've fixed the tests now - on my local machine, the complete :streams:test suite is now working perfectly fine again :)

Best regards,
Ralph

**Comment by ableegoldman** [comment]
Hey @xdgrulez , sorry for the delay! Somehow your last response slipped past me. It seems like there have been some conflicting changes merged recently, can you rebase/pull to fix these conflicts?

Also, WDYT about [this](https://github.com/apache/kafka/pull/10897#issuecomment-868900284)? I've actually seen a number of users asking questions about these log lines recently, so I wonder if it might still be useful to include them higher than DEBUG, albeit infrequently.

**Comment by xdgrulez** [comment]
Hi @ableegoldman I think it would be good to have a less frequent output on e.g. INFO :) I won't have a lot of time to look into this in the near future, so please take this over :)

**Comment by mjsax** [comment]
@xdgrulez -- if you are still interested in working on this, it would be great. The PR would needs to be rebased/updated though (or just close this one an open a new PR?)

**Comment by xdgrulez** [comment]
Hi Matthias,

I don't really have time but I'd like to get this done anyway ;)

I think reopening a new PR would be more sensible... the change is too old.

Best,
Ralph


Am So., 6. Feb. 2022 um 21:24 Uhr schrieb Matthias J. Sax <
***@***.***>:

**Comment by mjsax** [comment]
Thanks for getting back. Closing this PR.

**Pull request closed without merging**
