### PR TITLE
MINOR: tidy up spacing for ConsumerGroupCommand related to KAFKA-1476 …

### PR DESCRIPTION
**Pull request by christian-posta**
https://issues.apache.org/jira/browse/KAFKA-1476

Let me know if these kind of contributions should have their own requisite JIRA opened in advance.

Cheers..

### CODE REVIEW

**Comment by christian-posta** [comment]
@gwenshap @junrao i've seen a couple of PRs fail because of this error (long-running tests?).

**Comment by christian-posta** [comment]
Would love to have this committed when someone has time :)

**Comment by christian-posta** [comment]
please review @gwenshap ?

**Comment by gwenshap** [comment]
Docs are good, tidy spaces are cool.
You mentioned PRs fail because of an error and I'm not sure what failed and which error? Do we have tests that rely on the exact spaces in the output?

**Comment by christian-posta** [comment]
So there are no tests that depend on the structure of the output (ie comma
or tab delimited sequence tests, etc). There was a period of a couple weeks
were builds would fail (without failing tests) because overall duration of
the build surpassed some high watermark 120mins). When I rebased a few days
ago and ran again everything finished within expected time (though I can't
explain why that is... I noticed other PRs saw the same behavior -- no
failed tests but build marked as failed bacause they took too long) AFAICT
things are good to go.

On Monday, March 7, 2016, Gwen (Chen) Shapira notifications@github.com
wrote:

> Docs are good, tidy spaces are cool.
> You mentioned PRs fail because of an error and I'm not sure what failed
> and which error? Do we have tests that rely on the exact spaces in the
> output?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apache/kafka/pull/945#issuecomment-193558295.

## 

_Christian Posta_
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by gwenshap** [comment]
LGTM

**Pull request closed without merging**
