### PR TITLE
MINOR: Remove FanoutIntegrationTest.java

### PR DESCRIPTION
**Pull request by guozhangwang**
This test has been completely subsumed by the coverage of reset integration test, and hence can be removed.

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by mjsax** [comment]
I am not sure if `ResteIntegrationTest` subsumed this. We split one stream but we write it also into an intermediate topic before one branch get's processed. If you think this is sufficient, LGTM.

**Comment by asfgit** [comment]
SUCCESS 
 8051 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8051 tests run, 5 skipped, 0 failed.
--none--

**Comment by guozhangwang** [comment]
> I am not sure if ResteIntegrationTest subsumed this. We split one stream but we write it also into an intermediate topic before one branch get's processed. If you think this is sufficient, LGTM.

I think that is sufficient. What do you think is missing from that integration test that is covered in this one?

**Comment by mjsax** [comment]
@guozhangwang Not sure -- just wanted to bring it up to double check.

**Comment by guozhangwang** [comment]
@dguy could you give a look as well? WDYT about the coverage.

**Comment by dguy** [comment]
@guozhangwang i think it is ok t remove this integration test. We have unit tests that already cover `mapValues` sufficiently and we have other tests that cover `to` and using the same input stream that is mapped etc and sent to a different output topic

**Review by dguy — APPROVED** [review]
LGTM

**Review by mjsax — APPROVED** [review]
LGTM

**Comment by mjsax** [comment]
Retest this please.

**Comment by asfgit** [comment]
SUCCESS 
 8056 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8056 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7949 tests run, 5 skipped, 1 failed.
--none--

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
