### PR TITLE
KAFKA-2170: Fixes for Windows

### PR DESCRIPTION
**Pull request by soumyajit-sahu**
This PR is to revive the older PR https://github.com/apache/kafka/pull/154 made by @mpoindexter (Mike Poindexter). I have replicated his work over the new code base.
This lets 6 LogTest unit tests to pass on Windows.

### CODE REVIEW

**Comment by abhit011** [comment]
@soumyajit-sahu , does there exist any binary package/release for the same fix.
I am facing some issues building kafka on windows.. So if you can pass this fix binary packages. I will dload and see if your commit fixes the issue that I am facing at my end.... 

Abhi

**Comment by guysmoilov** [comment]
The build log is already gone, any way to rerun and see what the failures were? 
Maybe needs another merge from trunk?

**Comment by soumyajit-sahu** [comment]
The build fails with a timeout. Not sure how to get rid of that.
**Build timed out (after 180 minutes)**. Marking the build as failed.
Build was aborted

**Comment by necromancersecret** [comment]
Guys ??? 
Can i find the complete windows build for the same.. I am facing issues in compiling the build on windows

Abhi

**Comment by abhit011** [comment]
Did any one has the binaries for the same release? I am facing issues in compiling the build 

Abhi

**Comment by MPeli** [comment]
Hi, I have created a new pull request. See #12331

**Pull request closed without merging**
