### PR TITLE
MINOR: improve Store parameter checks

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @dguy @bbejeck @guozhangwang

**Comment by dguy** [comment]
retest this please

**Comment by bbejeck** [comment]
Thanks @mjsax LGTM.

**Review by dguy — APPROVED** [review]
Nice one @mjsax! LGTM

**Comment by dguy** [comment]
merged to trunk. Sorry i tried to cherry-pick to 1.0 but i failed on the branch name and it didn't work.

**Pull request closed without merging**
