### PR TITLE
KAFKA-2680: Use IBM ConfigFile class to load jaas config if IBM JDK

### PR DESCRIPTION
**Pull request by rajinisivaram**
Use IBM ConfigFile class with IBM JDK since JavaLoginConfig provided by SUN provider is not included with IBM JDK.

### CODE REVIEW

**Comment by ijuma** [comment]
Why not use `getConfiguration()` like we do for the SASL code?

**Comment by rajinisivaram** [comment]
I would have liked to use `getConfiguration()` to load the configuration specified using the System property `java.security.auth.login.config`. But `kafka.admin.ZkSecurityMigrator` has two ways of specifying the config file, the system property is overridden by an option. I wasn't sure why the option is required and didn't want to break it. 

I was also worried about changing the current behaviour because of `Configuration.setConfiguration(null)` at the end of the method `isZkSecurityEnabled` with the comment `Tests fail if we don't reset the login configuration. It is unclear what is actually triggering this bug.`.

**Comment by ijuma** [comment]
I think we should remove that option in `ZkSecurityMigrator` and just leave the system property. I believe that is what @junrao had suggested in the PR too. @fpj, is there a strong reason to allow a different way of specifying the JAAS file? I know that it's a bit nicer for command-line users, but If we do that, we need to implement JDK-specific code like @rajinisivaram did in this PR. And using the system property is consistent across broker, clients and tools.

**Comment by ijuma** [comment]
@rajinisivaram, also keep in mind that if the option is set, `ZkSecurityMigrator` sets the system property (which is needed for the ZK client to work properly).

**Comment by fpj** [comment]
@ijuma @rajinisivaram 

> is there a strong reason to allow a different way of specifying the JAAS file?

It is just to enable a uniform way of passing parameters. Removing it and allowing it to be set strictly via a system property also works. Note that the system property has priority over the command-line option in the case both are set.

**Comment by rajinisivaram** [comment]
@fpj It feels slightly confusing to have a command line argument which is quietly ignored when the system property is set. If you have no objection, I will remove the argument. Otherwise, as @ijuma has pointed out, I can still assume in `JaasUtils` that the configuration is obtained from the system property since it is being set in `ZkSecurityMigrator`.

**Comment by gwenshap** [comment]
I think we all agree that the argument can be removed.

**Comment by fpj** [comment]
@rajinisivaram I don't object to removing the argument, but help me understand what is confusing about it. Are you concerned about configuration errors due to the two ways of setting it? If you could explain the scenario you're worried about, I'd appreciate.

> command line argument which is quietly ignored 

I wouldn't say that the command-line argument is ignored, instead it has lower precedence, so you need to set at least one. 

> the system property is overridden by an option

Maybe this comment is stale at this point, but we currently don't really override when the system property is set. If the system property is set, then the command-line option is ignored.

**Comment by rajinisivaram** [comment]
@fpj At the moment if you have an environment variable KAFKA_OPTS set which specifies a Jaas config file using the system property (as we do), and the migration tool is run using kafka-run-class.sh, the command line argument to specify the config file is ignored. It doesn't give any warnings or errors and you need to go and look into docs/code to figure out why the command line arg was not used. It can be easily fixed with a warning, so not necessarily a big issue.

I was going to submit an updated PR, but the tests added today for ZK auth are failing intermittently. I think it is related to the reloading of `Configuration` in tests. I will wait until that is fixed before updating this.

**Comment by junrao** [comment]
@rajinisivaram : Yes, we can remove the command line option for JAAS file. Could you update your PR? Thanks,

**Comment by rajinisivaram** [comment]
Rebased, removed command line option for Jaas config in `ZkSecurityMigrator`. Switched to using `Configuration.getConfiguration()` in `isZkSecurityEnabled` so that it works on any JDK.

**Comment by ijuma** [comment]
Thanks Rajini. Do the tests pass if you remove the setConfiguration(null) call in isZKSecurityEnabled?

**Comment by rajinisivaram** [comment]
@ijuma  Yes, tests do pass without the `setConfiguration(null)` in `isZkSecurityEnabled`. I have removed it and pushed an update.

**Comment by ijuma** [comment]
Great, thanks.

**Comment by junrao** [comment]
I got the following two errors when running the unit tests locally.

kafka.zk.ZKEphemeralTest > testOverlappingSessions[0] FAILED
    org.scalatest.junit.JUnitTestFailedError: Secure access not enabled
        at org.scalatest.junit.AssertionsForJUnit$class.newAssertionFailedException(AssertionsForJUnit.scala:102)
        at org.scalatest.junit.JUnitSuite.newAssertionFailedException(JUnitSuite.scala:79)
        at org.scalatest.Assertions$class.fail(Assertions.scala:1328)
        at org.scalatest.junit.JUnitSuite.fail(JUnitSuite.scala:79)
        at kafka.zk.ZKEphemeralTest.setUp(ZKEphemeralTest.scala:61)

kafka.security.auth.ZkAuthorizationTest > testIsZkSecurityEnabled FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at kafka.security.auth.ZkAuthorizationTest.testIsZkSecurityEnabled(ZkAuthorizationTest.scala:56)

**Comment by rajinisivaram** [comment]
@junrao The tests weren't failing for me, but that could be due to the order in which they are run. I have added `setConfiguration(null)` to the setup methods. In case they still fail for you, can you let me which JDK you are using and whether the tests fail when run on their own? Thanks.

**Comment by junrao** [comment]
Thanks for the patch. LGTM

**Pull request closed without merging**
