### PR TITLE
KAFKA-5690: Add support to list ACLs for a given principal (KIP-357)

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@lindong28 @junrao  This is a minor PR for [KIP-357: Add support to list ACLs per principal](https://cwiki.apache.org/confluence/display/KAFKA/KIP-357%3A++Add+support+to+list+ACLs+per+principal)
Appreciate your votes and review for this KIP/PR.

**Review by lindong28 — APPROVED** [review]
Thanks for the patch! LGTM.

**Comment by lindong28** [comment]
Merged to trunk.

**Comment by lindong28** [comment]
It seems that the vote for the KIP has not passed. I will revert this commit..

**Comment by omkreddy** [comment]
@lindong28 Thanks for the review.  vote has passed now.

**Comment by lindong28** [comment]
Thanks for the update @omkreddy. Merged to trunk.

**Pull request closed without merging**
