### PR TITLE
KAFKA-16280: Expose method to determine metric measurability (KIP-1019)

### PR DESCRIPTION
**Pull request by apoorvmittal10**
The PR implements the changes defined in [KIP-1019](https://cwiki.apache.org/confluence/display/KAFKA/KIP-1019%3A+Expose+method+to+determine+Metric+Measurability) which exposes method to check if metric is of type Measurable.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by AndrewJSchofield — APPROVED** [review]

**Comment by AndrewJSchofield** [comment]
Tiny nit. It's KIP-1019 I think, not KIP-109.

**Comment by apoorvmittal10** [comment]
> Tiny nit. It's KIP-1019 I think, not KIP-109.

Corrected the description. Thanks @AndrewJSchofield.

**Review by mjsax — APPROVED** [review]
LGTM -- retriggered Jenkins (failure seems unrelated, but want to sanify check) -- Can merge afterwards.

**Comment by apoorvmittal10** [comment]
> LGTM -- retriggered Jenkins (failure seems unrelated, but want to sanify check) -- Can merge afterwards.

Thanks @mjsax. I can see unrelated tests failures as well and green on jdk 17.

**Pull request merged**
