### PR TITLE
KAFKA-2438: add maxParallelForks to build.gradle to speedup tests.

### PR DESCRIPTION
**Pull request by harshach**

### CODE REVIEW

**Comment by gwenshap** [comment]
OMG. This is so awesome. Our testsuite now runs in under 5 minutes on my laptop, with no failures.

I'm going to commit this and hope that this won't break anything on Apache infrastructure (they should be aware that people will try to parallelize their tests, right?)

LGTM++

**Comment by harshach** [comment]
Thanks for the quick merge @gwenshap . Hopefully it won't break apache infra builds :)

**Comment by ijuma** [comment]
Well done @harshach, a very nice improvement. I didn't realise that our test suite could be run in parallel without issues. Nice surprise. :)

**Comment by ijuma** [comment]
By the way, the kafka-trunk build succeeded and it took half the time:

https://builds.apache.org/view/All/job/Kafka-trunk/589/

The PR build had two failures though (see @asfbot comment above).

I think we need to watch out to see if this causes some tests to be less stable. We may have to increase time outs in some cases. And we may also consider not using all available cores in Jenkins if multiple jobs are executed at the same time.

**Pull request closed without merging**
