### PR TITLE
MINOR: Add integration tag to AdminFenceProducersIntegrationTest

### PR DESCRIPTION
**Pull request by edoardocomar**
Add @Tag("integration") to AdminFenceProducersIntegrationTest

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by edoardocomar** [comment]
@C0urante @jolshan I missed this tag - I do not intend to backport though !

**Review by C0urante — APPROVED** [review]

**Comment by C0urante** [comment]
@edoardocomar considering this is a test-only change and it will likely make it easier for us to vet RCs, is there a strong reason not to backport?

**Comment by edoardocomar** [comment]
@C0urante  it was only not to make noise on the release(s). Quite happy to cherry-pick

**Comment by edoardocomar** [comment]
I just thought we're past the deadline and making noise for such a small change was not worth it. Of course I'd prefer to have consistent code for this test class

**Comment by C0urante** [comment]
👍 I think it makes sense to cherry-pick

**Comment by jlprat** [comment]
It makes sense to cherry pick this one to 3.8 for sure.
Thanks!

**Pull request merged**
