### PR TITLE
MINOR: Remove deprecated assertThat method usage from KafkaLog4jAppenderTest

### PR DESCRIPTION
**Pull request by omkreddy**
- Replace `Assert.assertThat` with `MatcherAssert.assertThat`.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@ijuma Hotfix to fix the compilation issues in KafkaLog4jAppenderTest, This was due to Junit usage and changes in  #6216 and #6248

**Review by rajinisivaram — APPROVED** [review]
@omkreddy Thanks for the PR, LGTM

**Comment by ijuma** [comment]
Thanks, looks like the two PRs were merged somewhat concurrently. Will merge this now since it's just a compilation fix and that part has succeeded.

**Review by ijuma — APPROVED** [review]
LGTM

**Pull request merged**
