### PR TITLE
KAFKA-14595 ReassignPartitionsCommandArgsTest rewritten in java

### PR DESCRIPTION
**Pull request by nizhikov**
This PR is part of #13247 
It includes `ReassignPartitionsCommandArgsTest` rewritten in java.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by tledkov — APPROVED** [review]
The patch is OK with me.
New java-test looks similar to the removed scala-test.

**Review by gharris1727 — APPROVED** [review]
@nizhikov Thanks for the migration! This looks reasonable to me, but I don't have much familiarity in this area.

@mimaison or @ijuma I'll delay merging this until next week, just comment if you want more time to review this.

**Comment by mimaison** [comment]
Thanks. I'm busy with other priorities this week. Feel free to merge.

**Comment by nizhikov** [comment]
Hello @gharris1727 Thanks for the review. Are you ready to merge this PR?

**Comment by nizhikov** [comment]
Hello @gharris1727 
Is there anything I can do to get this PR merged?

**Comment by gharris1727** [comment]
The test failures in CI appear unrelated, and `tools:test` passes for me locally.

**Comment by gharris1727** [comment]
Thanks @nizhikov for your patience, and thanks for keeping people notified about this PR. Too many PRs like this one are left stale due to limited committer bandwidth.

**Comment by nizhikov** [comment]
@gharris1727 Thank you very much!

**Pull request merged**
