### PR TITLE
ConfigDef experimentation - support List<T> and Map<String, T>

### PR DESCRIPTION
**Pull request by shikhar**

### CODE REVIEW

**Comment by shikhar** [comment]
* Currently, the only collection type supported by `ConfigDef` is `Type.LIST` and the values must be strings. Use-cases have come up with connectors for richer configuration, like defining maps.

* It would not be that hard to just add a new `Type.MAP` for string-string maps. However I think we should instead be working towards evolving `ConfigDef` to support array and map types that can compose some other existing primitive value type to avoid additional parsing burden on `ConfigDef` clients. This PR is a pass at how we could do that, by adding a new `ConfigType` interface that is implemented by the existing `ConfigDef.Type` enum, as well as the new `ArrayType` and `MapType`. Most existing uses of `ConfigDef.Type` (e.g. in `ConfigDef` constructors) are then changed to expect `ConfigType`, for which `ConfigDef.Type` enumerators continue to be valid values.

* We need to support Java properties files for configuration so a flattened string representation is the lowest-common denominator. But Connect for example that provides a REST API and accepts configuration as JSON. Users could specify maps and arrays as JSON objects and arrays, which could be flattened by Connect before being parsed by `ConfigDef`. I can also imagine Connect being able to also support `.json` configuration files in addition to `.properties`.

The end goal would be to evolve `ConfigDef` to support richer JSON-style configuration from the user's perspective.

ping @ewencp @hachikuji @ijuma @kkonstantine for thoughts.

**Comment by shikhar** [comment]
Another approach to consider would be to define the new  `MapType` and `ListType` in  the `connect-api` module instead of in `ConfigDef`, which is in the `clients` module.

If we do this in conjunction with supporting `.json` configuration for Connect, we could then choose to avoid dealing with flattened representations and messy escaping logic entirely.

**Comment by ijuma** [comment]
I think what you are suggesting is similar to https://github.com/typesafehub/config (used by Akka and other Lightbend projects). I used that library quite a bit in the past and I thought it worked well. 

However, I think there are some who feel that it's good to keep the structure of configs flat and simple. This starts to break down in more complex cases where one wants to, for example, configure a consumer used by streams or configure streams used by another app (and potentially the consumer used by streams). We have basic support for prefixes, but the property file format is verbose for such cases.

**Comment by shikhar** [comment]
`ConfigDef` is used by Kafka in relatively simpler ways than we need for `Connect`. Only Connect uses the recommender/validator/dependents/etc business, which is a somewhat contorted API. A better direction may be for Connect to move away from `ConfigDef`, and utilize the Connect data API, i.e. `Struct` `Schema`s for configs, with validation and recommendations using hooks. This would also allow JSON to be used with the existing `Converter` infra, which is a good fit given we have a REST API.

**Pull request closed without merging**
