### PR TITLE
Kafka-4722 : Add application.id to StreamThread name

### PR DESCRIPTION
**Pull request by sharad-develop**
Kafka-4722 : Add application.id to StreamThread name

### CODE REVIEW

**Comment by sharad-develop** [comment]
"retest this please"

**Comment by sharad-develop** [comment]
"retest this please"

**Comment by sharad-develop** [comment]
trigger re-test

**Comment by sharad-develop** [comment]
retest this please

**Comment by mjsax** [comment]
This PR has over 80+ unrelated commits and has conflict. Can you please rebase to current trunk to it only contains the relevant commits for this PR. Thanks.

**Comment by mjsax** [comment]
@sharad-develop Are you still working on this?

**Comment by sharad-develop** [comment]
This fixes Kafka-4722 . Will rebase

**Comment by sharad-develop** [comment]
Re-opening to rebase

**Pull request closed without merging**
