### PR TITLE
KAFKA-14570: Add missing closing parenthesis symbol

### PR DESCRIPTION
**Pull request by iamazy**
[KAFKA-14570](https://issues.apache.org/jira/browse/KAFKA-14570) There should add missing closing parenthesis symbol for problem description.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by iamazy** [comment]
@ijuma please take a look.

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR

**Comment by mimaison** [comment]
@iamazy Thanks for fixing this. For small issues like this you don't need to open a Jira, you can just open a PR and put `MINOR` in the title, for example https://github.com/apache/kafka/commit/6b5e9e989b7a1f8c387a79dea0117e52401853e1

**Comment by iamazy** [comment]
> @iamazy Thanks for fixing this. For small issues like this you don't need to open a Jira, you can just open a PR and put `MINOR` in the title, for example [6b5e9e9](https://github.com/apache/kafka/commit/6b5e9e989b7a1f8c387a79dea0117e52401853e1)

@mimaison Got it, Thanks you!

**Pull request merged**
