### PR TITLE
KAFKA-5050 add ldap authentication support on PlainSaslServer

### PR DESCRIPTION
**Pull request by nihed**
This feature will provide a way to add ldap authentication on PlainSaslServer. 
Our Jaas Server configuration will be : 
KafkaServer {
            org.apache.kafka.common.security.plain.PlainLdapLoginModule REQUIRED
            username="cent"
            password="redhat"
            source="ldap"
            ldap_user_template="uid={0},ou=People,dc=srv,dc=world"
            ldap_url="ldap://192.168.15.247:389";
};

I tested my code with existing tests and everything looks good. I will create another ticket later to add new unit tests.

### CODE REVIEW

**Comment by rajinisivaram** [comment]
I think it will be better to do this on top of KIP-86 (PR #2022). A new callback handler can be defined for LDAP without changing `PlainSaslServer`. It will be easy to configure LDAP by specifying a different callback handler.

**Comment by wdm01github** [comment]
Can I get the compiled files? thanks

dongmingw@139.com

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 4712 tests run, 0 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 4020 tests run, 1 skipped, 2 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 4020 tests run, 1 skipped, 2 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 4020 tests run, 1 skipped, 2 failed.
--none--

**Pull request closed without merging**
