### PR TITLE
KAFKA-9533: Revert  ValueTransform forwards `null` 

### PR DESCRIPTION
**Pull request by bbejeck**
This reverts commit a41d3d86c13a55a75e67b1635bc74361ebe6d7af.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @vvcephei for review

**Review by mjsax — COMMENTED** [review]
LGTM.

Should the title include the Jira name instead of being label "minor"

**Review by mjsax — COMMENTED** [review]
LGTM.

Should the title include the Jira name instead of being label "minor"

**Comment by bbejeck** [comment]
>Should the title include the Jira name instead of being label "minor"

Agreed and updated.  Thanks for the review @mjsax.

**Comment by bbejeck** [comment]
>Should the title include the Jira name instead of being label "minor"

Agreed and updated.  Thanks for the review @mjsax.

**Review by vvcephei — APPROVED** [review]
Thanks @bbejeck !

**Comment by bbejeck** [comment]
merged #8167 into trunk

**Pull request merged**
