### PR TITLE
MINOR: Doc changes for KIP-324

### PR DESCRIPTION
**Pull request by bbejeck**
Documentation changes for adding KIP-324 `AdminClient.metrics()`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
@guozhangwang, @mjsax, @vvcephei 

\cc @JimGalasyn

**Review by mjsax — COMMENTED** [review]
Should we add anything to Streams upgrade notes, too? Ie, "newly added AdminClient metrics" are now exposed in Kafka Streams metrics" ?

**Comment by bbejeck** [comment]
>Should we add anything to Streams upgrade notes, too? Ie, "newly added AdminClient metrics" are now exposed in Kafka Streams metrics" ?

I agree and I've updated per comments.

**Review by mjsax — APPROVED** [review]

**Review by vvcephei — APPROVED** [review]

**Comment by bbejeck** [comment]
retest this please

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.1`

**Pull request merged**
