### PR TITLE
MINOR: fix typo in TransactionLog JavaDoc

### PR DESCRIPTION
**Pull request by lambdaliu**
a minor fix typo in TransactionLog JavaDoc

### CODE REVIEW

**Comment by lambdaliu** [comment]
retest this please

**Review by vahidhashemian — APPROVED** [review]
LGTM. Thanks you for the PR.

**Comment by ijuma** [comment]
The PR description was good, but the merged commit's message was not. @vahidhashemian please try to follow the usual commit message conventions when merging.

**Comment by vahidhashemian** [comment]
Will do @ijuma; sorry about missing updating the message.

**Pull request merged**
