### PR TITLE
MINOR: Code cleanup in StreamsResetter

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei

**Review by bbejeck — APPROVED** [review]
Thanks @mjsax LGTM

**Comment by bbejeck** [comment]
retest this please

**Review by vvcephei — APPROVED** [review]
LGTM. Thanks for the separate code-cleanup PR.

**Comment by mjsax** [comment]
Java11: https://builds.apache.org/job/kafka-pr-jdk11-scala2.12/535/
```
Test Result (14 failures / -1)

kafka.admin.ResetConsumerGroupOffsetTest.testResetOffsetsNotExistingGroup
kafka.api.CustomQuotaCallbackTest.testCustomQuotaCallback
kafka.api.PlaintextConsumerTest.testLowMaxFetchSizeForRequestAndPartition
kafka.api.SaslMultiMechanismConsumerTest.testCoordinatorFailover
kafka.api.SaslPlainPlaintextConsumerTest.testCoordinatorFailover
kafka.api.SaslSslAdminClientIntegrationTest.testAclDescribe
kafka.api.SaslSslAdminClientIntegrationTest.testLegacyAclOpsNeverAffectOrReturnPrefixed
kafka.api.SaslSslConsumerTest.testCoordinatorFailover
kafka.api.SslConsumerTest.testCoordinatorFailover
kafka.tools.MirrorMakerIntegrationTest.testCommaSeparatedRegex
org.apache.kafka.streams.integration.RepartitionWithMergeOptimizingIntegrationTest.shouldSendCorrectRecords_OPTIMIZED
org.apache.kafka.streams.integration.ResetIntegrationTest.shouldNotAllowToResetWhenInputTopicAbsent
org.apache.kafka.streams.integration.ResetIntegrationWithSslTest.testReprocessingFromScratchAfterResetWithIntermediateUserTopic
org.apache.kafka.streams.integration.SuppressionIntegrationTest.shouldSuppressIntermediateEventsWithRecordLimit
```

Java8:
```
kafka.api.PlaintextConsumerTest.testCoordinatorFailover
kafka.api.SslConsumerTest.testCoordinatorFailover
```

Retest this please

**Review by guozhangwang — APPROVED** [review]

**Pull request merged**
