### PR TITLE
KAFKA-6371 Fix DelayedFetch toString

### PR DESCRIPTION
**Pull request by mayt**

### CODE REVIEW

**Comment by ijuma** [comment]
Good catch, can you please use string interpolation which would have made this more obvious?

**Comment by ijuma** [comment]
Ah, this was already fixed in 0.11.0. We can fix this in the 0.10.2 branch, but no releases are planned from that branch.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3781/
Test PASSed (JDK 7 and Scala 2.10).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3782/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by mayt** [comment]
Yes this is no longer an issue in 0.11.0 or greater. That's unfortunate but lets let this in to 0.10.2 anyways.

**Comment by guozhangwang** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3783/
Test FAILed (JDK 7 and Scala 2.10).

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the PR.

**Comment by mayt** [comment]
Thank you!

**Pull request merged**
