### PR TITLE
MINOR: Eliminate PID terminology from non test code

### PR DESCRIPTION
**Pull request by ijuma**
Producer id is used instead.

Also refactored TransactionLog schema code to follow
our naming convention and to have better structure.

### CODE REVIEW

**Comment by ijuma** [comment]
@hachikuji, what do you think?

**Comment by guozhangwang** [comment]
LGTM.

**Comment by ijuma** [comment]
Thanks for the review @guozhangwang, rebased against trunk and fixed a trivial conflict. @hachikuji, let me know if you'd like to review this as well or if I should go ahead and merge it.

**Comment by ijuma** [comment]
Added a tiny commit that removes unnecessary casts in `TransactionLog` (use `getLong` and similar instead of `get`+`asInstanceOf`).

**Review by hachikuji — APPROVED** [review]
Thanks for cleaning up the rest of this. LGTM

**Comment by hachikuji** [comment]
Merging to trunk

**Pull request closed without merging**
