### PR TITLE
MINOR: Used in-built TimeUnit conversion function

### PR DESCRIPTION
**Pull request by kamalcph**

### CODE REVIEW

**Comment by kamalcph** [comment]
cc @ijuma @mjsax

**Comment by ijuma** [comment]
retest this please

**Comment by kamalcph** [comment]
@ijuma 
I forgot to check the testcase. `testSimpleRate` is failed. I'll fix and ping you.

**Comment by kamalcph** [comment]
@ijuma 

The `TimeUnit.convert` function returns the value in `long` which results in loss of numeric precision. Next time, I will make sure to run all the test cases before submitting a pull request. Closing, this one as it's error prone.

**Pull request closed without merging**
