### PR TITLE
KAFKA-9747: Creating connect reconfiguration URL safely

### PR DESCRIPTION
**Pull request by akatona84**
* URL wasn't urlencoded when forwarded reconfiguration to leader connect worker
* handling previously swallowed errors in connect RestClient

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by akatona84** [comment]
Thanks @urbandan for investigating this issue with me and creating the fix. Could you take a look?

**Review by urbandan — APPROVED** [review]
LGTM, thanks @akatona84

**Review by viktorsomogyi — APPROVED** [review]
@mimaison would you please review this?

**Comment by akatona84** [comment]
@kkonstantine , @rhauch could you take a look on this minor fix with big impact? Thx!

**Comment by akatona84** [comment]
I'm not sure who puts these lines in the final commit message, but pls make sure that put Daniel in it too:
```
Co-authored-by: Daniel Urban <durban@cloudera.com>
```

**Comment by mimaison** [comment]
Thanks for the PR, it looks good. Is it possible to add a test for it?

**Comment by akatona84** [comment]
> Thanks for the PR, it looks good. Is it possible to add a test for it?

@mimaison , Thanks for the review, unfortunately that code part where the restclient  is used, not unit tested at all. It would need more effort to fully understand how the distributed herder could be tested better.

**Comment by dadufour** [comment]
Any chance to have it in a 2.7.2?

**Comment by mimaison** [comment]
@akatona84 Thanks for the fix and sorry again for the delay merging it.

@dadufour At this point, it's unlikely there will be a 2.7.2 release. I've backported it to 2.8 so it will be in the 2.8.1 release.

**Comment by dadufour** [comment]
Thanks for the feedback

**Comment by scholzj** [comment]
@mimaison Will this also get into the 3.0.x release stream? I know it is probably late for 3.0.0 which already has RCs, so that is fine. But it would be nice to have it in 3.0.1 (if there ever is a 3.0.1 of course).

**Comment by mimaison** [comment]
@scholzj Yes that's the plan, I'll do it when merging into 3.0 reopens

**Comment by scholzj** [comment]
Great, thanks.

**Comment by mimaison** [comment]
Applied to 3.0: https://github.com/apache/kafka/commit/9218b8cc5f10a1fb79c74e9a49ab36fd51e68916

**Pull request merged**
