### PR TITLE
KAFKA-9175: Update MirrorMaker 2 topic/partition metrics

### PR DESCRIPTION
**Pull request by mimaison**
Fix issue in `PartitionMetrics` which caused all topic-partition metrics to use the same sensors. Switched the byte and record metrics to `Meter` so they expose both a Rate and Count for consistency with other Kafka metrics (and monitoring).

Co-authored-by: Mickael Maison <mickael.maison@gmail.com>
Co-authored-by: Edoardo Comar <ecomar@uk.ibm.com>

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ryannedolan — APPROVED** [review]
thanks!!

**Comment by mimaison** [comment]
@omkreddy https://issues.apache.org/jira/browse/KAFKA-9175 is potentially a blocker for 2.4 as it really prevents users from monitoring MirrorMaker 2 and hence running it for production use cases.

**Comment by omkreddy** [comment]
> @omkreddy https://issues.apache.org/jira/browse/KAFKA-9175 is potentially a blocker for 2.4 as it really prevents users from monitoring MirrorMaker 2 and hence running it for production use cases.

Sounds good. Please set the JIRA version to 2.4 and commit to trunk and 2.4 branch.

**Review by omkreddy — APPROVED** [review]
Thanks for the PR. LGTM.

**Pull request merged**
