### PR TITLE
MINOR: Port fix to other StoreQueryIntegrationTests

### PR DESCRIPTION
**Pull request by wcarlson5**
https://github.com/apache/kafka/pull/11129 fixed one of the tests, This ports the fix to the others as well

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wcarlson5** [comment]
@vvcephei @patrickstuedi  @ableegoldman Can I get a +1 to use the same fix for the other tests in this file?

**Review by vvcephei — CHANGES_REQUESTED** [review]
Thanks, @wcarlson5 !

Sadly, there's a checkstyle failure in your change, though:

```
[2021-07-31T03:04:50.832Z] [ant:checkstyle] [ERROR] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-11153/streams/src/test/java/org/apache/kafka/streams/integration/StoreQueryIntegrationTest.java:74:15: Unused import - org.hamcrest.Matchers.matchesRegex. [UnusedImports]
```

Can you fix that, then we can merge?

**Comment by wcarlson5** [comment]
@vvcephei looks like it is working now

EDIT: nvm odd failure, I don't think that should be a failure. Trying to reproduce locally

`java.lang.AssertionError: Unexpected exception thrown while getting the value from store.
Expected: is one of {<a string containing "Cannot get state store source-table because the stream thread is PARTITIONS_ASSIGNED, not RUNNING">, <a string containing "The state store, source-table, may have migrated to another instance">}
     but: was "Cannot get state store source-table because the stream thread is PARTITIONS_ASSIGNED, not RUNNING"
`

**Review by vvcephei — APPROVED** [review]
Thanks for the fix, @wcarlson5 !

**Pull request merged**
