### PR TITLE
MINOR: Make topic config a section, with TOC entry.

### PR DESCRIPTION
**Pull request by tombentley**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5888/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by omkreddy** [comment]
+1

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5873/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by vahidhashemian** [comment]
This seems to be a duplicate: https://github.com/apache/kafka/pull/3415

**Comment by tombentley** [comment]
@vahidhashemian indeed it is.

**Pull request closed without merging**
