### PR TITLE
KAFKA-2361: unit test failure in ProducerFailureHandlingTest.testNotE…

### PR DESCRIPTION
**Pull request by jinxing64**
same issue with KAFKA-1999, so I want to fix it
https://issues.apache.org/jira/browse/KAFKA-1999

### CODE REVIEW

**Comment by jinxing64** [comment]
@junrao find this uncaught exception in 0.8.2, I think it is the same issue with KAFKA-1999， please review.

**Comment by guozhangwang** [comment]
@ZoneMayor Did you saw this issue still in trunk, or only in 0.8.2?

**Comment by jinxing64** [comment]
@guozhangwang 
https://issues.apache.org/jira/browse/KAFKA-2361?filter=-3
it is only in 0.8.2, this issue is fixed in 0.9.0, but still exists in 0.8.2

**Comment by guozhangwang** [comment]
@ZoneMayor Usually we would only back-port very critical bug fixes to the older versions. Since we are releasing 0.9.0.0 very soon, I would recommend just upgrading to the newer version after it is released.

**Comment by jinxing64** [comment]
running: ./gradlew test ， I often got testNotEnoughReplicasAfterBrokerShutdown failed, that's why I try to fix this, and take it as a start to contribute codes

**Comment by jinxing64** [comment]
@guozhangwang , do I need to close this ?

**Comment by guozhangwang** [comment]
@ZoneMayor Thanks for your interests in contributing! I feel your pains, as I often am bothered by transient failures a lot myself.. There are some other transient failures that are not fixed even in trunk yet, do you want to pick up some from the following list and close this PR?

https://issues.apache.org/jira/browse/KAFKA-2054

**Comment by b-goyal** [comment]
same issue with KAFKA-1999, so I want to fix it
https://issues.apache.org/jira/browse/KAFKA-1999

**Pull request closed without merging**
