### PR TITLE
KAFKA-2620: Introduce Scalariform

### PR DESCRIPTION
**Pull request by granthenke**
This is a WIP. There will likely need to be discussion around a rule set we want to use and if we actually want to include this in the build. This could also be used as a one time rebase. 

This commit does not include the actual formatting changes. To see what effect the patch has run
`gradle formatScala`

### CODE REVIEW

**Comment by guozhangwang** [comment]
@granthenke Would you like to continue working on this JIRA and PR?

**Comment by ijuma** [comment]
I think we may want to use scalafmt instead as it supports a maxColumn setting:

http://scalameta.org/scalafmt/#FAQ/Troubleshooting

**Comment by ijuma** [comment]
Closing as this has been inactive for a while.

**Comment by b-goyal** [comment]
This is a WIP. There will likely need to be discussion around a rule set we want to use and if we actually want to include this in the build. This could also be used as a one time rebase. 

This commit does not include the actual formatting changes. To see what effect the patch has run
`gradle formatScala`

**Pull request closed without merging**
