### PR TITLE
KAFKA-8913: Document topic based configs & ISR settings for Streams apps

### PR DESCRIPTION
**Pull request by vinothchandar**
- Documented how to set topic based configs
  - Documented how to achieve MIN_IN_SYNC_REPLICAS_CONFIG = 2 for reliable apps

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vinothchandar** [comment]
Copy pasted these onto kafka-site and the site seems to work fine. 

### See box at the end of picture 

Screen Shot 2019-09-17 at 5 17 18 PM

### See right after "Same applied to ...." 

Screen Shot 2019-09-17 at 5 17 08 PM


@mjsax Please take a look.. Also can you provide guidance on 
- backporting to older kafka releases? 
- Also sending a PR to kafka-site repo?

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.3`, `2.2`, `2.1`, and `2.0` (seems to be sufficient for me).

If you want the update on the website immediately, please do a PR against kafka-site -- otherwise, it would be effective only when we do a release an update the webpage. You would need to do the update for each release.

**Comment by vinothchandar** [comment]
@mjsax thanks! To clarify, the next AK release will only update the latest version's doc right? we still need to update older releases? 

if not, I am happy to wait for the release.

**Comment by mjsax** [comment]
Yes. If we release 2.3.1 only 2.3 docs are updated. If we release 2.4.0 only new 2.4 docs are added. Hence, a PR for the webpage should just update all versions for simplicity as we don't know exactly when a bug-fix release might update older docs.

**Pull request merged**
