### PR TITLE
MINOR: StopReplicaResp and StopReplicaReq Test should cover all available version

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
Accidently found that the test case in `StopReplicaRespTest` and `StopReplicaReqTest` didn't cover all versions.

*Summary of testing strategy (including rationale)*
QA

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by dajac — APPROVED** [review]
Good catch! LGTM.

**Comment by dajac** [comment]
I've re-triggered Jenkins. I will merge once we have a clean run.

**Comment by dengziming** [comment]
Failures seem unrelated to this pr.

**Review by chia7712 — APPROVED** [review]

**Comment by chia7712** [comment]
@dengziming Nice patch!

**Pull request merged**
