### PR TITLE
MINOR: fix streams_broker_compatibility_test.py

### PR DESCRIPTION
**Pull request by chia7712**
related to #10573 

the log message was changed and so the system test can't capture expected message.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
```
jdk_version="openjdk:8" \
TC_PATHS="tests/kafkatest/tests/streams/streams_broker_compatibility_test.py::StreamsBrokerCompatibility.test_fail_fast_on_incompatible_brokers_if_eos_beta_enabled" \
/bin/bash tests/docker/run_tests.sh
```

all pass

截圖 2021-05-05 下午4 36 41

**Review by ableegoldman — APPROVED** [review]
Yet another broken system test due to the extremely fragile habit of searching for specific log messages 😞  I hope sometime in the not too far future someone is able to put some time into rethinking how we do system tests so they're more resilient to no-op changes like logging.

Anyways, thanks for catching this! That was my oversight -- LGTM

**Comment by ableegoldman** [comment]
@chia7712 I'm just going to go ahead and merge this so we can get the system tests fixed ASAP. Hope you don't mind, and thank you again for the PR

**Comment by chia7712** [comment]
>  I'm just going to go ahead and merge this so we can get the system tests fixed ASAP. Hope you don't mind

thanks for merging this patch :)

**Pull request merged**
