### PR TITLE
MINOR: Java8 cleanup

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna 

This should be cherry-picked to `2.2`.

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
Java 8 and Java 11 failed on `kafka.api.ConsumerBounceTest.testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup`

retest this please

**Comment by mjsax** [comment]
Rebased

**Review by guozhangwang — APPROVED** [review]
Thanks @mjsax

**Comment by mjsax** [comment]
Created tickets for failing Java11 tests. Java8 passed.

Retest this please.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.2`.

**Pull request merged**
