### PR TITLE
KAFKA-15671:Fix NoSuchFileException from Files.walk

### PR DESCRIPTION
**Pull request by hudeqi**
As describe from: https://issues.apache.org/jira/browse/KAFKA-15671

### CODE REVIEW

**Comment by hudeqi** [comment]
I will trigger CI test repeatedly to confirm that this flaky test will not fail again.

**Comment by hudeqi** [comment]
@divijvaidya This flaky test caused by Files.walk would occasionally fail when I ran it locally repeatedly. After modifying this PR, the local repeated execution has become normal in my local env, and it has not appeared in the CI test now.

**Review by divijvaidya — APPROVED** [review]
Thank you for quickly fixing this. Looks good.

**Comment by divijvaidya** [comment]
Unrelated test failures:
```
[Build / JDK 21 and Scala 2.13 / integration.kafka.server.FetchFromFollowerIntegrationTest.testRackAwareRangeAssignor(String).quorum=zk](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/integration.kafka.server/FetchFromFollowerIntegrationTest/Build___JDK_21_and_Scala_2_13___testRackAwareRangeAssignor_String__quorum_zk/)
[Build / JDK 21 and Scala 2.13 / org.apache.kafka.tiered.storage.integration.ReassignReplicaShrinkTest.executeTieredStorageTest(String).quorum=kraft](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.tiered.storage.integration/ReassignReplicaShrinkTest/Build___JDK_21_and_Scala_2_13___executeTieredStorageTest_String__quorum_kraft/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.common.network.SslTransportLayerTest.[2] tlsProtocol=TLSv1.2, useInlinePem=true](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.common.network/SslTransportLayerTest/Build___JDK_11_and_Scala_2_13____2__tlsProtocol_TLSv1_2__useInlinePem_true/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationBaseTest.testReplicateSourceDefault()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationBaseTest/Build___JDK_11_and_Scala_2_13___testReplicateSourceDefault__/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationBaseTest.testSyncTopicConfigs()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationBaseTest/Build___JDK_11_and_Scala_2_13___testSyncTopicConfigs__/)
[Build / JDK 11 and Scala 2.13 / kafka.server.DescribeClusterRequestTest.testDescribeClusterRequestExcludingClusterAuthorizedOperations(String).quorum=kraft](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/kafka.server/DescribeClusterRequestTest/Build___JDK_11_and_Scala_2_13___testDescribeClusterRequestExcludingClusterAuthorizedOperations_String__quorum_kraft/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.streams.integration.EOSUncleanShutdownIntegrationTest.shouldWorkWithUncleanShutdownWipeOutStateStore[exactly_once_v2]](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.streams.integration/EOSUncleanShutdownIntegrationTest/Build___JDK_11_and_Scala_2_13___shouldWorkWithUncleanShutdownWipeOutStateStore_exactly_once_v2_/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.streams.integration.IQv2StoreIntegrationTest.verifyStore[cache=true, log=true, supplier=ROCKS_KV, kind=DSL]](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.streams.integration/IQv2StoreIntegrationTest/Build___JDK_11_and_Scala_2_13___verifyStore_cache_true__log_true__supplier_ROCKS_KV__kind_DSL_/)
[Build / JDK 17 and Scala 2.13 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationExactlyOnceTest.testReplication()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationExactlyOnceTest/Build___JDK_17_and_Scala_2_13___testReplication__/)
[Build / JDK 17 and Scala 2.13 / kafka.coordinator.transaction.ProducerIdManagerTest.[1] error=UNKNOWN_SERVER_ERROR](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/kafka.coordinator.transaction/ProducerIdManagerTest/Build___JDK_17_and_Scala_2_13____1__error_UNKNOWN_SERVER_ERROR/)
[Build / JDK 17 and Scala 2.13 / org.apache.kafka.controller.QuorumControllerTest.testBalancePartitionLeaders()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/Build___JDK_17_and_Scala_2_13___testBalancePartitionLeaders__/)
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.streams.integration.EosIntegrationTest.shouldWriteLatestOffsetsToCheckpointOnShutdown[exactly_once_v2, processing threads = false]](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.streams.integration/EosIntegrationTest/Build___JDK_8_and_Scala_2_12___shouldWriteLatestOffsetsToCheckpointOnShutdown_exactly_once_v2__processing_threads___false_/)
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.streams.integration.EosIntegrationTest.shouldWriteLatestOffsetsToCheckpointOnShutdown[at_least_once, processing threads = true]](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.streams.integration/EosIntegrationTest/Build___JDK_8_and_Scala_2_12___shouldWriteLatestOffsetsToCheckpointOnShutdown_at_least_once__processing_threads___true_/)
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.streams.integration.RestoreIntegrationTest.shouldInvokeUserDefinedGlobalStateRestoreListener()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14622/4/testReport/junit/org.apache.kafka.streams.integration/RestoreIntegrationTest/Build___JDK_8_and_Scala_2_12___shouldInvokeUserDefinedGlobalStateRestoreListener__/)
```

**Pull request merged**
