### PR TITLE
KAFKA-8175: The broker block some minutes may occur expired error message for a period of time

### PR DESCRIPTION
**Pull request by huangyiminghappy**
As described in  (https://issues.apache.org/jira/browse/KAFKA-8175).  
if one of the node is block in the cluster,and when the client can not send updateMetaData to the antother node,the client will print much log like `org.apache.kafka.common.errors.TimeoutException: Expiring 1062 record(s) for kafka_test_111-8: 23967 ms has passed since batch creation plus linger timeFri Mar 29 11:34:14 CST 2019
` . in someTimes the controller can not  find the broker is down is offline soon,then client's batches can not send to the offline node,and also can not trigger the update metaData.so we need to check the connection's read state,if it not ready in the config time,close the channel,and trigger update the metaData
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by soenkeliebau** [comment]
Hi @huangyiminghappy 

it looks like your changes to the constructors of NetworkClient broke compilation, which is why the tests could not be run.

More broadly, I have to admit that I can't fully follow the reasoning for this change - but that may be me :)

Can you please elaborate some more on the motivation for this, especially after the changes made in [KIP-91](https://cwiki.apache.org/confluence/display/KAFKA/KIP-91+Provide+Intuitive+User+Timeouts+in+The+Producer)?

**Comment by huangyiminghappy** [comment]
> Can you please elaborate some more on the motivation for this, especially after the changes made in [KIP-91](https://cwiki.apache.org/confluence/display/KAFKA/KIP-91+Provide+Intuitive+User+Timeouts+in+The+Producer)?

thank you reply very much,i have seen the code about delivery.timeout.ms,i think the expiredBatches can not trigger update the  metaData,  add the connectionReadTimeout which can solve when the broker block,and the producer print for along time expiredBatches logs,and can not update the metadata in time.

**Comment by soenkeliebau** [comment]
It looks like the code still fails to build, I think that is due to a missing import statement in KafkaAdminClient. Even after fixing that though, there are a lot of test failures due to casting failures in the constructor.
Can you please have another look at your code and ensure that it compiles and all tests pass?
Regarding the actual changes, I'll leave it to someone more knowledgeable of this area of the code to comment on them.

**Comment by huangyiminghappy** [comment]
> It looks like the code still fails to build, I think that is due to a missing import statement in KafkaAdminClient. Even after fixing that though, there are a lot of test failures due to casting failures in the constructor.
> Can you please have another look at your code and ensure that it compiles and all tests pass?
> Regarding the actual changes, I'll leave it to someone more knowledgeable of this area of the code to comment on them.

thanks

**Pull request closed without merging**
