### PR TITLE
KAFKA-5611; AbstractCoordinator should handle wakeup raised from onJoinComplete

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Review by ijuma — COMMENTED** [review]
Thanks for the PR, the changes seem reasonable. I saw the following code:

```java
try {
            Set<TopicPartition> assigned = new HashSet<>(subscriptions.assignedPartitions());
            listener.onPartitionsAssigned(assigned);
        } catch (WakeupException | InterruptException e) {
            throw e;
        } catch (Exception e) {
            log.error("User provided listener {} for group {} failed on partition assignment",
                    listener.getClass().getName(), groupId, e);
        }
```

But the documentation of `onPartitionsAssigned` doesn't mention that it can throw either of these exceptions and why. It would be good to take the chance to improve that so that the contract is clearer. Same for `onPartitionsRevoked`.

**Comment by hachikuji** [comment]
@ijuma Thanks for taking a look. I added a few comments in ConsumerRebalanceListener on the propagation of wakeups/interrupts. Let me know if they seem reasonable.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6365/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6350/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ijuma — APPROVED** [review]
Thanks for the updates, LGTM.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6375/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6360/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by hachikuji** [comment]
I will merge to trunk and 0.11.0 but leave the issue open to give the user a chance to confirm the fix.

**Comment by yueqiongqiu** [comment]
after applied https://github.com/apache/kafka/pull/3571 on version 0.10.2.0, we encountered an infinite loop occurs in ConsumerCoordinator.java:
java.lang.IllegalStateException: Coordinator selected invalid assignment protocol: null
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:208)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:339)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:305)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:286)

for some reason, the ConsumerCoordinator's resetGeneration() is called, and the protocol of generation is set to null.
then in method joinGroupIfNeeded() of org.apache.kafka.clients.consumer.internals.AbstractCoordinator.java ,onJoinComplete() method throws an IllegalStateException, 
and the resetJoinGroupFuture() method will never has the chance to be call:

> 

            if (future.succeeded()) {
                onJoinComplete(generation.generationId, generation.memberId, generation.protocol, future.value());

                // We reset the join group future only after the completion callback returns. This ensures
                // that if the callback is woken up, we will retry it on the next joinGroupIfNeeded.
                resetJoinGroupFuture();
                needsJoinPrepare = true;

> 

the joinFuture is not clear to null, JoinGroupRequest will not be sent in the next loop

is this an issue?

**Pull request closed without merging**
