### PR TITLE
MINOR: Compatibility and upgrade tests for 0.11.0.x

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by enothereska** [comment]
LGTM. I'll open a separate one for streams.

**Comment by ijuma** [comment]
We can only merge this after 0.11.0.0 is uploaded to S3. cc @ewencp

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5768/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5754/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ewencp** [comment]
@enothereska @ijuma I've uploaded the 0.11 artifacts, but can we also make this change `vagrant/base.sh` grab from the s3 bucket `kafka-packages` instead of using `kafka-packages-$version` for everything? I've uploaded all the artifacts to that bucket. It's a pain to have to create a new bucket for each new release... and since we are using the public mirrors in the other script, we could also just use them in `vagrant/base.sh` if people prefer that.

Also, you both have access to do this :)

**Comment by ijuma** [comment]
@ewencp, thanks. Yes, I think I'll use the public mirrors for consistency with the other script.

**Comment by ijuma** [comment]
Actually, I decided to use the new S3 bucket for now. The docker build uses a hardcoded mirror, so I'd prefer to avoid that until we have a solution that gets the packages from a random mirror.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5783/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5769/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ewencp — COMMENTED** [review]
This all looks good to me assuming we're getting a clean test run.

**Comment by ijuma** [comment]
I ran all the tests modified by this PR:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder/944/

They passed.

**Comment by enothereska** [comment]
LGTM, when is this going in? Ah, just did.

**Pull request closed without merging**
