### PR TITLE
KAFKA-4818: Implement transactional producer

### PR DESCRIPTION
**Pull request by mjsax**
add public API for transactions
 - add new Producer methods to interface
 - add new Producer and Consumer config parameters

We want to add the API early to break the dependency for Streams EoS implementation and allow for parallel development.

### CODE REVIEW

**Comment by ijuma** [comment]
How does it help to merge these methods with empty implementations? It seems like anyone can just include that in the branch that they're working on?

**Comment by mjsax** [comment]
Yes. But we would like to merge Streams stuff in parallel to core stuff (ie, some Streams stuff before core stuff got merged).

**Comment by mjsax** [comment]
\cc @apurvam @hachikuji @guozhangwang

**Comment by apurvam** [comment]
We synced offline. We think it makes sense to put these APIs along with the new versions of the various RPCs into trunk, so that we can submit the transactional code incrementally directly into AK. 

We will have a bunch of dead code, but as long as the top level API Methods throw 'UnsupportedOperationException' it shouldn't cause too much confusion.

**Comment by apurvam** [comment]
Having this in AK first would also enable smaller and more frequent PRs, which are easier to review.

**Comment by ijuma** [comment]
I definitely see the value of having the protocol classes. I still don't get the point of extending KafkaProducer with 5 methods that all throw UOE. This is trivial to do it in the branch that needs and code that actually needs to call these methods can't work until the UOE is replaced by an actual implementation. What am I missing?

**Comment by hachikuji** [comment]
I think the main thing we want to get in is the request/response implementations. I'm fine merging the producer API stubs later.

**Comment by apurvam** [comment]
Yes, we can merge the API's once we have real implementations. The RPCs are more important.

**Comment by ijuma** [comment]
Sounds good to me.

**Comment by mjsax** [comment]
I created a new JIRA for this. Closing this PR for now.

**Pull request closed without merging**
