### PR TITLE
KAFKA-6728 Kafka Connect Header Null Pointer Exception

### PR DESCRIPTION
**Pull request by tedyu**
Guard against potential null recordHeader in WorkerSinkTask#convertHeadersFor

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rhauch — APPROVED** [review]
~~LGTM. Thanks!~~

~~@hachikuji, would you mind merging back to the `1.1` branch?~~

See below.

**Comment by rhauch** [comment]
@tedyu actually, WorkerSourceTask has a similar problem and should be corrected. 

And, this change will remove the null header value from the headers array, whereas we probably should keep it.

**Comment by tedyu** [comment]
bq. we probably should keep it.

When recordHeader is null, what should be put in the result ?
Once you confirm, I will apply the change to both classes.

**Comment by tedyu** [comment]
Looking at Headers#add :
```
     * @param key            the header's key; may not be null
```

**Comment by tedyu** [comment]
@rhauch
Should I close this PR ?

**Pull request closed without merging**
