### PR TITLE
MINOR: Updating files with release 2.6.1

### PR DESCRIPTION
**Pull request by mimaison**
Waiting for artifacts to appear in maven before merging

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
Artifacts are now in maven: https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.6.1/

**Review by bbejeck — APPROVED** [review]

**Comment by mimaison** [comment]
If I understand correctly, the system tests are failing because 2.6.1 is not in https://s3-us-west-2.amazonaws.com/kafka-packages

How do I push the artifacts there? The Release Process wiki page has no details and only mentions:
> Upload the new release and kafka-stream-x.x.x-test.jar to S3 bucket "kafka-packages"

**Comment by mimaison** [comment]
@bbejeck @mjsax @vvcephei  Can you comment on https://github.com/apache/kafka/pull/9844#issuecomment-757859210? Thanks

**Comment by mjsax** [comment]
Not 100% sure, but it seems `2.6.1` artifacts are in this bucket already:
```
<Contents>
<Key>kafka-streams-2.6.1-test.jar</Key>
<LastModified>2021-01-12T22:11:48.000Z</LastModified>
<ETag>"f1653fec3db75c3275a7f8b6346395a6"</ETag>
<Size>1986566</Size>
<StorageClass>STANDARD</StorageClass>
</Contents>
```

If I log into AWS and browse to the S3 bucket, I see: `Last Modified: January 12, 2021, 14:11:48 (UTC-08:00)` -- seems it was uploaded today.

**Review by mjsax — APPROVED** [review]

**Pull request merged**
