### PR TITLE
MINOR: Use distinct consumer groups in dynamic listener tests

### PR DESCRIPTION
**Pull request by rajinisivaram**
Dynamic listener tests should use distinct consumer groups to ensure there are no committed offsets.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rajinisivaram** [comment]
@hachikuji Saw this failure in the jenkins build: https://builds.apache.org/job/kafka-trunk-jdk9/538/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/testAddRemoveSslListener/. Can you review the fix please? Thanks.

**Comment by rajinisivaram** [comment]
retest this please

**Comment by hachikuji** [comment]
@rajinisivaram Just to clarify, is the failure caused by duplicate writes or duplicate reads? I think I can see how the producer might add duplicates with a listener change, but I guess it shouldn't affect the consumer?

**Comment by rajinisivaram** [comment]
@hachikuji Thanks for the review. You are right, that was just a very bad fix. The issue was duplicate reads and I think that was because the test was reusing the same consumer group with a second consumer and the first one could have committed some offsets before the broker was restarted. I have updated the test to use distinct consumer groups and reverted the previous change.

**Comment by hachikuji** [comment]
@rajinisivaram I agree that it's a bit dangerous in this test case to use the same groupId. It seems we could even use the simple consumer and disable auto commits to take group state totally out of the picture. That said, and I may be being a bit slow here, but how are the duplicates explained by this?

**Comment by rajinisivaram** [comment]
@hachikuji Removing auto-commit should also work, I have updated the code, but left the groups in there.

I think the scenario is:
  1. we create a new listener, produce and consume some messages on topic using first consumer
  2. we shutdown and restart the servers. the servers use ephemeral ports, so they get new ports this time and the first consumer can no longer connect to the servers
  3. we produce and consume some more messages on topic using a second pair of producer/consumer that use the new server ports. The consumer is created with auto-offset-reset `latest`. If the group is reused, this requires 1) to have not committed at all or committed the last offset. Anything in between could result in the second consumer consuming some of the messages produced in 1).

**Review by hachikuji — APPROVED** [review]
@rajinisivaram Thanks for the explanation. It makes sense. The fix LGTM.

**Pull request merged**
