### PR TITLE
KAFKA-7482: LeaderAndIsrRequest should be sent to the shutting down broker

### PR DESCRIPTION
**Pull request by junrao**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by junrao** [comment]
@onurkaraman : Could you review this? Thanks.

**Comment by enothereska** [comment]
@junrao is there a guarantee that the shutting down broker would be able to process this request? If not, wouldn't this make the behavior unpredicatable (sometimes the request is processed, sometimes it's not and both cases need to be considered)? Thanks.

**Comment by junrao** [comment]
@enothereska : There is no strong guarantee for the shutting down broker to process the LeaderAndIsr request. We can probably tighten this up in the future. The shutting down broker may remain alive for some time after the controlled shutdown because of things like log flushing. Being able to change the leader on the shutting down broker sooner will help the clients.

**Comment by junrao** [comment]
@lindong28 : Not sure if Onur is available. Could you help review this too? Thanks.

**Review by lindong28 — APPROVED** [review]
Thanks @junrao. LGTM.

**Pull request merged**
