### PR TITLE
KAFKA-4157: Transient system test failure in replica_verification_tes…

### PR DESCRIPTION
**Pull request by granthenke**
…t.test_replica_lags

### CODE REVIEW

**Comment by granthenke** [comment]
The test, which failed regularly, now has passed regularly in my system test runs.

cc @granders @ijuma @hachikuji @SinghAsDev

**Comment by ijuma** [comment]
Good find, LGTM.

Interestingly, we don't have failures for this test in our Jenkins instance. Did you reproduce it locally?

**Comment by granthenke** [comment]
I can reproduce it regularly in my environment. 

My job is also run via a Jenkins job, but its a bit different in that that it deploys on "existing hardware" via Vagrant as opposed to spinning up AWS clusters. In my setup the hardware is 11 m4.xlarge nodes and rhel7.1 OS. I think the main difference is that I run ducktape on one of the nodes as opposed to on Jenkins. 

At some point I would like to contribute back the "existing hardware" Vagrant code and the multi OS setup scripts.

_Side note_: I didn't open a jira for this since its unique to my setup, but if you run ducktape on a worker node it fails because the grep logic to kill processes will find an kill the parent ducktape process.

**Comment by SinghAsDev** [comment]
LGTM!

**Comment by ijuma** [comment]
Thanks, merged to trunk and 0.10.0 branches.

**Pull request closed without merging**
