### PR TITLE
KAFKA-2651; Remove deprecated config alteration from TopicCommand

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by granthenke** [comment]
I think we are keeping deprecated things around for a bit longer since 0.10 is so close to 0.9, but I could be wrong. cc @gwenshap

**Comment by gwenshap** [comment]
yeah, I wouldn't remove it right now.

Lets review the PR and merge it into trunk as soon as I do the last merge of trunk into 0.10.0. Should be tomorrow :)

**Comment by ewencp** [comment]
0.10.0.0 has been released, should we revisit this? I also wonder if we need to be a bit more careful removing deprecated features in 0.10.1.0 since this is probably a bit shorter of a timeframe than people would normally expect for deprecation + removal. Normally I would expect removal of deprecated features to happen on major releases, but the quick succession from 0.9 to 0.10 kinda broke that approach for anything deprecated in 0.9.

Regardless of the decision, it might be nice to start marking these deprecation bugs in JIRA with the fix version as soon as they are filed based on the major version bump, and mark them as blockers by default so they can easily be included in a release and don't just get lost.

**Comment by omkreddy** [comment]
@ewencp  AFAIK we will be removing the deprecated features in next major release(0.11.0.0). If all agree then, I will update the fix version accordingly.

cc @ijuma

**Comment by ijuma** [comment]
I filed https://issues.apache.org/jira/browse/KAFKA-3763 for removing deprecated APIs in 0.11.0.

Personally, I don't see a lot of value in filing separate JIRAs as it will never be exhaustive and one needs to search the code when the time comes anyway. However, for cases where we already have a PR (like this one), then it makes sense to have a separate JIRA. I would suggest linking such JIRAs to KAFKA-3763.

**Comment by ewencp** [comment]
Sounds fine to me.

**Pull request closed without merging**
