### PR TITLE
MINOR; Replace gt and lt char with html encoding

### PR DESCRIPTION
**Pull request by jsancio**
Use `&gt;` and `&lt;` instead of `>` and `<` to properly render the characters in HTML.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@jsancio thanks for this patch. Should we fix following similar error?

https://github.com/apache/kafka/blob/trunk/docs/ops.html#L3842
https://github.com/apache/kafka/blob/trunk/docs/ops.html#L3845
https://github.com/apache/kafka/blob/trunk/docs/ops.html#L4249

**Comment by jsancio** [comment]
Thanks @chia7712 . I fixed those encoding issues.
> https://github.com/apache/kafka/blob/trunk/docs/ops.html#L4249

I couldn't find anything wrong with that line. Did you mean to link to another line? Or did I miss something?

**Comment by chia7712** [comment]
> I couldn't find anything wrong with that line. Did you mean to link to another line? Or did I miss something?

`</code>true</code>` -> `<code>true</code>`

**Comment by jsancio** [comment]
> > I couldn't find anything wrong with that line. Did you mean to link to another line? Or did I miss something?
> 
> `</code>true</code>` -> `<code>true</code>`

Thanks @chia7712 . Done.

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
