### PR TITLE
KAFKA-15387: Remove Connect's deprecated task configurations endpoint

### PR DESCRIPTION
**Pull request by yashmayya**
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-970%3A+Deprecate+and+remove+Connect%27s+redundant+task+configurations+endpoint
- https://issues.apache.org/jira/browse/KAFKA-15387
- https://github.com/apache/kafka/pull/14361
- This patch removes Connect's deprecated task configurations endpoint as outlined in KIP-970.

### CODE REVIEW

**Comment by mimaison** [comment]
Hi @yashmayya, will you be able to complete this PR before feature freeze? Thanks

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR

**Comment by chia7712** [comment]
@yashmayya @mimaison Apologies for the noise on this PR. We're discussing the API compatibility upgrade path and noticed this PR removes public APIs deprecated in 3.7. Since we plan to declare [3.7, 3.9] as API compatible with 4.0, should we delay the removal until 5.0? Please correct me if I've misunderstood anything. Also, please join the discussion 

https://lists.apache.org/thread/9hm3sfc1hjowpgydjhzsqovjg3mvksxs

**Comment by yashmayya** [comment]
@chia7712 I wasn't aware that we had a "3 prior releases" rule regarding deprecation and removal of public APIs. I thought that major releases were fair game for removing any previously deprecated API. I don't have any strong objections to reverting this if that's the consensus, it's a pretty minor Connect REST API that already has an equivalent replacement though.

**Comment by chia7712** [comment]
@yashmayya thanks for your response. I have added your response to the mail thread.

**Pull request merged**
