### PR TITLE
KAFKA-8938: Improve allocations during Struct validation in ConnectSchema

### PR DESCRIPTION
**Pull request by amcrn**
Summary: Struct value validation in Kafka Connect can be optimized
to avoid creating an Iterator when the expectedClasses list is of
size 1. This is a meaningful enhancement for high throughput
connectors.

This contribution is my original work and I license the work to the
project under the project's open source license.

Stack Trace from the Couchbase Kafka Connector:

```
* java.util.Collections.singletonIterator(Object)
* java.util.Collections$SingletonList.iterator()
* org.apache.kafka.connect.data.ConnectSchema.validateValue(String, Schema, Object)
* org.apache.kafka.connect.data.Struct.put(Field, Object)
* org.apache.kafka.connect.data.Struct.put(String, Object)
* com.couchbase.connect.kafka.handler.source.DefaultSchemaSourceHandler.buildValue(SourceHandlerParams, CouchbaseSourceRecord$Builder)
```

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by amcrn** [comment]
retest this please

**Comment by amcrn** [comment]
retest this please

**Comment by amcrn** [comment]
retest this please

**Comment by amcrn** [comment]
retest this please

**Comment by amcrn** [comment]
Looks like Jenkins build process is having issues. This is a pretty straightforward change. @guozhangwang / @ijuma would you mind reviewing? Thanks!

**Comment by amcrn** [comment]
retest this please

**Comment by amcrn** [comment]
retest this please

**Comment by amcrn** [comment]
@guozhangwang Would you mind taking a look? Thanks!

**Comment by kkonstantine** [comment]
ok to test

**Review by kkonstantine — APPROVED** [review]
Recent test runs we both green. 
Thanks for the fix @amcrn !

LGTM

**Pull request merged**
