### PR TITLE
HOTFIX: Hotfix for trunk failing

### PR DESCRIPTION
**Pull request by enothereska**
Disable 3 tests that need rethinking.

### CODE REVIEW

**Comment by enothereska** [comment]
@mjsax @dguy have a look. Basically this reverts some of the tests in https://github.com/apache/kafka/pull/3449

**Comment by enothereska** [comment]
Superseded by https://github.com/apache/kafka/pull/3493

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5910/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5925/
Test PASSed (JDK 7 and Scala 2.11).

**Pull request closed without merging**
