### PR TITLE
KAFKA-14588 [4/N] ConfigCommandTest rewritten in java

### PR DESCRIPTION
**Pull request by nizhikov**
This is third part of https://github.com/apache/kafka/pull/15417 refactoring.
PR intention - split big PR in parts to simplify review.
PR contains`ConfigCommandTest` rewritten in java

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by nizhikov** [comment]
Hello @chia7712 

This is third part of KAFKA-14588. It contains huge `ConfigCommandTest` rewritten in java.
I can try to move only subset of tests to make patches smaller.

Please, tell my what do you think?

**Comment by nizhikov** [comment]
New tests passes on CI. PR ready for review.

**Comment by chia7712** [comment]
> I can try to move only subset of tests to make patches smaller.

yep, that is good idea. Also, please try to migrate to the `ClusterTest`. I haven't dug in ConfigCommandTest, and I hope the new test infra won't obstruct you from migration.

**Comment by nizhikov** [comment]
Hello @chia7712 

Looks like we are ready to replace whole scala version of `ConfigCommandTest` with the java one.
Changes are reviewable now.
Can you, please, take a look?

**Comment by nizhikov** [comment]
Hello @chia7712 
We have only two PR's regarding the tests left.
This and #15848 

Let's move on and finish command tests! :)

**Comment by chia7712** [comment]
Sure. Will take a look today!

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by nizhikov** [comment]
@chia7712 
Thank you very much for review and merge!

**Pull request merged**
