### PR TITLE
KAFKA-7157: Fix handling of nulls in TimestampConverter

### PR DESCRIPTION
**Pull request by rayokota**
This is based on the PR from @Nimfadora, with some minor cleanup: https://github.com/apache/kafka/pull/6446

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rhauch** [comment]
retest this please

**Review by rhauch — APPROVED** [review]
Thanks for the cleanup, @rayokota. And thanks for the original PR, @Nimfadora.

LGTM, pending a green build. (I restarted the build since there were no previous build results; not sure why that was.)

**Comment by hamzanasirr** [comment]
Hi, from where can I see how to implement this in a connector? Or is it done in the usual way?

**Comment by kkonstantine** [comment]
@hamzanasirr not sure what are you looking to implement. This was a fix to a transformation (aka SMT).

**Comment by hamzanasirr** [comment]
> @hamzanasirr not sure what are you looking to implement. This was a fix to a transformation (aka SMT).

Hi @KKonstantine,
I am using this SMT in one of my projects. I am using this on a date column to convert it to Date datatype from milliseconds coming in the form of string or int. But when it's null, it throws NPE. Even though it should not as it is fixed.

That's why I asked if, to implement this fix, do I need to add any additional config in my sink properties file?

Note: I am using the sink connector of MongoDB.

**Comment by ake1234** [comment]
I'm also using this SMT but its throws null pointer exception for null timestamp values. Can someone help us how to implement this changes.

**Pull request merged**
