### PR TITLE
MINOR: fix JavaDocs warnings

### PR DESCRIPTION
**Pull request by mjsax**
- add some missing annotations for deprecated methods

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @bbejeck @dguy @guozhangwang @miguno

**Comment by mjsax** [comment]
This should go into `1.0` release...

**Review by miguno — APPROVED** [review]

**Review by dguy — APPROVED** [review]
Thanks @mjsax, LGTM

**Comment by dguy** [comment]
merged to trunk

**Pull request closed without merging**
