### PR TITLE
MINOR: add a getOrCreate function to KRPC collections

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by chia7712** [comment]
What is the purpose of this new method? Should we add ```getOrCreate``` to ```ImplicitLinkedHashMultiCollection``` as well?

**Comment by cmccabe** [comment]
Looks like Jenkins is flaking out a bit.
```
FATAL: Unable to delete script file /tmp/jenkins3984496192919521109.sh
java.io.EOFException
```
Will re-push to get a clean test run.

**Comment by cmccabe** [comment]
> What is the purpose of this new method? Should we add getOrCreate to ImplicitLinkedHashMultiCollection as well?

The purpose is to make it easy to access map elements by their keys.  An example might help:

```
int brokerId = 2;
Broker broker = brokerCollection.getOrCreate(brokerId);
```

Unfortunately, we can't add this to `ImplicitLinkedHashMultiCollection` because only the generated code has the notion of keys.  In `ImplicitLinkedHashMultiCollection`, we just have elements which is more awkward to deal with.

**Comment by ijuma** [comment]
Why is it the case that non generated code doesn't know about keys? It seems pretty awkward to implement methods like this that are not related to the the protocol

**Comment by cmccabe** [comment]
> Why is it the case that non generated code doesn't know about keys?

It's a `Collection` rather than a `Map`.  Collections don't have a key type and value type-- they just have an element type.  So if you want to remove something from a `Set`, for example, you have to supply a Set element (even if some of the fields in the set element you supply will be ignored for the purpose of lookup, which is likely.)

This is more efficient in terms of memory used, but a little less intuitive for Java programmers in some cases.  I kind of regret making this tradeoff now, since I think many Java programmers are not familiar with interacting with `Set`, and just want a Map`.  If I get some time I could redo it, but it would take some time to do.

>  It seems pretty awkward to implement methods like this that are not related to the the protocol

It is related to the protocol, in that the protocol definition determines which fields are part of the key and which are part of the value.  As I said, I could redo this to create separate classes for the Key and Value, which would be slightly more elegant and slightly less efficient.  But I think for the time being we should accept this PR since it makes dealing with these collections much nicer.

**Comment by chia7712** [comment]
> int brokerId = 2;
Broker broker = brokerCollection.getOrCreate(brokerId);

+1 to this pattern and I hope this PR can get merged :)

**Pull request closed without merging**
