### PR TITLE
MINOR: Fix missing wait_until import from bad cherry-pick

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6597/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6612/
Test FAILed (JDK 7 and Scala 2.11).

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ewencp** [comment]
One system test failed, but it is an unrelated transient failure so I am going to go ahead and commit.

**Pull request closed without merging**
