### PR TITLE
KAFKA-5210:Application Reset Tool does not need to seek for internal topics

### PR DESCRIPTION
**Pull request by bharatviswa504**
@mjsax @dguy @guozhangwang Could you please review the changes.

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
LGTM.

Call for final review and merging @guozhangwang

**Comment by mjsax** [comment]
Retest this please.

**Review by dguy — APPROVED** [review]
Thanks @bharatviswa504 LGTM

**Comment by guozhangwang** [comment]
LGTM! Merged to trunk.

**Pull request closed without merging**
