### PR TITLE
MINOR: Refactor admin client helpers for checking leader and ISR

### PR DESCRIPTION
**Pull request by jsancio**
### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jsancio** [comment]
cc @mumrah @hachikuji @soondenana

**Comment by soondenana** [comment]
LGTM. Assuming that the methods that go moved as same as is, no logic got changed.

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch cleanup.

**Comment by jsancio** [comment]
@soondenana and @hachikuji, thanks for the reviews and merge!

**Pull request merged**
