### PR TITLE
KAFKA-10084: Fix EosTestDriver end offset

### PR DESCRIPTION
**Pull request by vvcephei**
Check the uncommitted end offset after the committed end offset,
so we can be sure never to miss a pending end-transaction marker.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
I ran the system tests, and they pass:
```
================================================================================
test_id:    kafkatest.tests.streams.streams_eos_test.StreamsEosTest.test_failure_and_recovery_complex.processing_guarantee=exactly_once
status:     PASS
run time:   13 minutes 14.424 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.streams.streams_eos_test.StreamsEosTest.test_failure_and_recovery_complex.processing_guarantee=exactly_once_beta
status:     PASS
run time:   13 minutes 12.365 seconds
--------------------------------------------------------------------------------
```

**Comment by vvcephei** [comment]
Hey @mjsax , thanks for the help on this. Can you take a look at the PR?

**Comment by vvcephei** [comment]
oh, great:
```
00:14:19.016 > Task :streams:checkstyleTest
00:14:19.017 [ant:checkstyle] [ERROR] /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.13/streams/src/test/java/org/apache/kafka/streams/tests/EosTestDriver.java:47:8: Unused import - java.util.HashSet. [UnusedImports]
00:14:19.017 [ant:checkstyle] [ERROR] /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.13/streams/src/test/java/org/apache/kafka/streams/tests/EosTestDriver.java:55:8: Unused import - java.util.Set. [UnusedImports]
```

**Review by mjsax — APPROVED** [review]
LGTM.

**Comment by vvcephei** [comment]
All test failures were unrelated (looks like some new flaky tests)
```
    kafka.server.GssapiAuthenticationTest.testServerAuthenticationFailure
    org.apache.kafka.clients.consumer.CooperativeStickyAssignorTest.testReassignmentWithRandomSubscriptionsAndChanges
    org.apache.kafka.clients.consumer.CooperativeStickyAssignorTest.testReassignmentWithRandomSubscriptionsAndChanges
    org.apache.kafka.clients.consumer.StickyAssignorTest.testReassignmentWithRandomSubscriptionsAndChanges
    org.apache.kafka.clients.consumer.StickyAssignorTest.testReassignmentWithRandomSubscriptionsAndChanges
```

**Comment by vvcephei** [comment]
cherry-picked to 2.6

**Pull request merged**
