### PR TITLE
MINOR: Remove unused `AdminUtils.fetchTopicMetadataFromZk` methods

### PR DESCRIPTION
**Pull request by ijuma**
These are internal methods with no tests and since we now have an `AdminClient`,
we should remove them.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5503/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5488/
Test PASSed (JDK 8 and Scala 2.12).

**Review by hachikuji — APPROVED** [review]
Nice find! LGTM.

**Comment by hachikuji** [comment]
Merging to trunk.

**Comment by ewangchong** [comment]
https://github.com/search?q=AdminUtils.fetchTopicMetadataFromZk&type=Code&utf8=%E2%9C%93

There are 456 codes are using this method, why it is removed as an unused method?

**Comment by ijuma** [comment]
@ewangchong I replied to the same question in the JIRA you filed (KAFKA-6545).

**Pull request closed without merging**
