### PR TITLE
MINOR: more logs for empty assignment

### PR DESCRIPTION
**Pull request by guozhangwang**
We find that brokers may send empty assignment for some members unexpectedly, and would need more logs investigating this issue.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@vvcephei @abbccdda

**Comment by guozhangwang** [comment]
test this please

**Review by vvcephei — APPROVED** [review]
lgtm, although I lack the context to know how spammy these warnings might be during normal operations.

**Comment by guozhangwang** [comment]
Cherry-picked to 2.5.

**Pull request merged**
