### PR TITLE
KAFKA-4439: NetworkClient: create a builder class to encapsulate ctor arguments

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by ijuma** [comment]
We don't typically use builders in Kafka for things like this. There are some pros and cons and it would be good to get some other opinions, what do you think @hachikuji? I wish Java supported named arguments. :)

**Comment by cmccabe** [comment]
Thanks for taking a look at this, @ijuma.  I think the builder pattern makes a lot of sense for scenarios where there is a large (and growing) number of arguments to a constructor.   See http://www.javaworld.com/article/2074938/core-java/too-many-parameters-in-java-methods-part-3-builder-pattern.html for a pretty good discussion.  Joshua Bloch discusses this in depth in Effective Java, in his second item, which makes it as close to canonical good Java style as you're likely to get ;)

**Comment by hachikuji** [comment]
I have mixed feelings. Constructing the `NetworkClient` _is_ kind of painful at the moment, but there's only a handful of places where we do it and it's not exposed to users, so the overall win seems small. I do like having the names present since then I don't have to cross-reference the constructor to find out which parameter is which.  Maybe if we're going to go this far, then we ought to build the `Selector` inside `NetworkClient.Builder` as well.

**Comment by ijuma** [comment]
Thanks for the reference @cmccabe. the article does a reasonable job of listing the pros and cons. 

One of the cases where builders are a bit of a mixed bag is if a large number of parameters is mandatory. In that case, it's not possible to use the pattern of passing mandatory parameters to the builder's constructor without defeating the point of using a builder in the first place. So you end up introducing a new failure scenario: someone forgets to set a mandatory parameter. Furthermore, if you introduce a new parameter, you won't get a compiler error as you would for the constructor with lots of parameters case.

**Comment by cmccabe** [comment]
> One of the cases where builders are a bit of a mixed bag is if a large number of parameters is mandatory.

Hmm.  More than half of these parameters are optional.  socketSendBuffer, socketReceiveBuffer, maxInFlightRequestsPerConnection, requestTimeoutMs, and the time implementation could all have sensible defaults that don't need to be changed in most unit tests.  But we're forced to specify them every time, currently.  It also adds cognitive overhead to writing new code since you have to look up what the sensible default would be, or find another invocation to copy/paste and hope they got it right.

> In that case, it's not possible to use the pattern of passing mandatory parameters to the builder's constructor without defeating the point of using a builder in the first place. So you end up introducing a new failure scenario: someone forgets to set a mandatory parameter. Furthermore, if you introduce a new parameter, you won't get a compiler error as you would for the constructor with lots of parameters case.

The bug caused by failing to set a required builder parameter is immediately obvious and caught by even the most trivial unit test.  If a parameter is mandatory, you just check for it when constructing the object and throw an exception if it is not set.  In contrast, constructors with huge numbers of parameters can lead to subtle bugs that might not be found for a very long time.  To quote Joshua Bloch: "Long sequences of identically typed parameters can cause subtle bugs. If the client accidentally reverses two such parameters, the compiler won’t complain, but the program will misbehave at runtime (Item 40)."  This is a much bigger type safety hole than required parameters.

Also, since this is Java we're talking about, everything is nullable anyway... and if you look at the existing API, you'll see that we make use of this fact (the MetadataUpdater and Metadata constructor parameters can't simultaneously be set-- one needs to be null.)  So you don't have type-safety here currently.

By my count, we create a NetworkClient in 9 different places in the code, once tests are included.  That seems like a large number to me.  As you said, it's very painful and frustrating to add a new constructor parameter to all those different places.  I would also add that the chances of making a mistake are very high-- is the 7th parameter receive buffer size or send buffer size?  etc.  There are some places in the code where I feel like someone might have already made this mistake-- I don't understand why some unit tests are setting explicit socket buffer sizes, when they would be better served by letting linux auto-size the buffer, for example.

Ultimately, if Java10 gets named parameters, or if there's some other solution to this issue, we can always refactor this code later, since it's a private API :)

**Pull request closed without merging**
