### PR TITLE
KAFKA-17860: Remove log4j-appender module

### PR DESCRIPTION
**Pull request by frankvicky**
JIRA: [KAFKA-17860](https://issues.apache.org/jira/browse/KAFKA-17860)

Since we are migrating to `log4j2`, we have to remove the `log4j-appender` module due to it being deprecated and its dependency on the clients module.

https://github.com/apache/kafka/blob/2d896d9130f121e75ccba2d913bdffa358cf3867/build.gradle#L3354-L3375

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@frankvicky please update `upgrade.html`

**Comment by ppkarwasz** [comment]
Would you be willing to replace `log4j-appender` with a refactored version of the [Log4j Core 2.x `Kafka` appender](https://logging.apache.org/log4j/2.x/manual/appenders/message-queue.html#KafkaAppender)?

Currently the appender is deprecated and planned to be removed in Log4j 3.x, mostly because of the [outstanding issues](https://github.com/apache/logging-log4j2/issues/2066) and the lack of Kafka experts in the Logging PMC.

Personally, I am not even sure if `ProducerRecord<byte[], byte[]>` is the right kind of object to be sent to Kafka.

**Comment by chia7712** [comment]
hi @ppkarwasz 

Thanks for the suggestion. Could you please consider sharing this information on the dev channel ([dev@kafka.apache.org](mailto:dev@kafka.apache.org))? It would be great to see how many users are interested in having this appender :)

**Comment by ppkarwasz** [comment]
Thanks, I opened a [thread on `dev@kafka`](https://lists.apache.org/thread/9logy8yv3v3tom8kd45sq01nl2qfxcx7).

**Pull request merged**
