### PR TITLE
KAFKA-3448: Support zone index in IPv6 regex

### PR DESCRIPTION
**Pull request by soumyajit-sahu**
When an address is written textually, the zone index is appended to the address, separated by a percent sign (%). The actual syntax of zone indices depends on the operating system.

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks. It would be good to have some tests where`%` is used incorrectly. For example, what if it appears multiple times or if a `:` appears after it (but before a `]`).

**Comment by soumyajit-sahu** [comment]
It doesn't look like those cases will be possible in real scenario. The % sign is a separator only bound to occur once, and the characters following the % would either be numerals (on Windows) or 'eth'+numeral (on Linux). Below is the rule for it to occur:

# 

When an address is written textually, the zone index is appended to the address, separated by a percent sign (%). The actual syntax of zone indices depends on the operating system:

the Microsoft Windows IPv6 stack uses numeric zone indices, e.g., fe80::3%1. The index is determined by the interface number;
most Unix-like systems (e.g., BSD, Linux, OS X) use the interface name as a zone index: fe80::3%eth0.
alternatively, on BSD based operating systems (including OS X), a numeric zone index can be used in the second 16-bit word, e.g.: fe80:1::3

**Comment by ijuma** [comment]
The reason we validate is to catch mistakes. If we assume people won't make mistakes, we don't need any validation. :) I am aware that `%` should only appear once, that's why I suggested the IP address should fail validation if it appears multiple times.

**Comment by soumyajit-sahu** [comment]
I agree, but if we want to cover all grounds, then we should use a standard library to help us parse the IPV6 addresses. Something like https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/InetAddressValidator.html.

Let me know what you think, and I could try to incorporate it.

**Comment by granthenke** [comment]
This looks related to #1269. In that pull request @peterableda was changing the regex due to a challenge parsing ports with IPv6 support. The most relevant comment is [here](https://github.com/apache/kafka/pull/1269#discussion_r61752746). Just an FYI in case some coordination is needed between the patches.

**Comment by ijuma** [comment]
@soumyajit-sahu, I agree that it would be nicer to use a third-party library that did it all for us. However, the Kafka project is very strict about adding any dependency to the `clients` module. So, I don't think we can do that.

Having thought about this some more, I think it's OK to include the PR as is. The additional complexity in the regex is probably not worth it. We already allow some invalid IPs by having a single regex for both IPv4 and IPv6.

Can you please update the PR title to:

``` text
KAFKA-3448: Support zone index in IPv6 regex
```

And edit the PR description to be:

``` text
When an address is written textually, the zone index is appended to the address, separated by a percent sign (%). The actual syntax of zone indices depends on the operating system.
```

Once your contribution is merged, the commit title will be the PR title and the commit message will be the PR description (and hence why it's important to make them specific and descriptive).

Once you do that, I'll merge the PR.

**Comment by ijuma** [comment]
LGTM

**Pull request closed without merging**
