### PR TITLE
KAFKA-2072 [WIP]: Add StopReplica request/response to o.a.k.common.requests and replace the usage in core module 

### PR DESCRIPTION
**Pull request by dajac**
Migration is done but this PR will need to be rebased on #110. I have copied some code (ef669a5) for now.

I'd appreciate feedback on it mainly around how I handle things in the ControllerChannelManager. I have introduced a new 'sendRequest' method for o.a.k.common.requests and kept the old one for compatibility reason. We'll be able to remove the old one in the future when migration of all requests and responses to o.a.k.common.requests is completed.

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for this @dajac.

There is ongoing work to remove usage of BlockingChannel in ControllerChannelManager. That work is done on top of the SSL/TLS one.

I think it would make sense to finish that first before doing this one.

**Comment by dajac** [comment]
@ijuma I have looked at your PR. I think that it will be quite easy to rebase on top of it. Do you know when it will be finished? Otherwise, would it be possible to do it the other way around, get this one in first as it is smaller?

**Comment by dajac** [comment]
Sorry for the failed build. I'll take at it later today.

**Comment by dajac** [comment]
Failures are not related to the changes that I did in this PR. I've got same failures (which happen randomly) in trunk.

**Comment by ijuma** [comment]
@dajac An updated patch for the SSL/TLS work was just posted[1]. I hope this can be merged quite quickly as there have been several rounds of review and it has been agreed that non blocker issues can be addressed in subsequent PRs.

Once that is merged, then the patch to remove `BlockingChannel` in `ControllerChannelManager` and `KafkaServer` is ready for review. I will create a separate ticket for replacing `SimpleConsumer` with `NetworkClient` in `AbstractFetcherThread` as that is a bigger piece of work.

[1] https://reviews.apache.org/r/33620

**Comment by dajac** [comment]
@ijuma Ok, I can rebase this PR on KAFKA-2411 when it gets merged. It shouldn't impact it to much.

Do you plan to migrate the `SyncProducer` as well?

**Comment by ijuma** [comment]
@dajac Regarding `SyncProducer`, not as part of the security work since there is no plan to support SSL/TLS for the Scala consumers and producers.

**Comment by dajac** [comment]
Closing it for now as it depends on KAFKA-2411. I'll re-open it when KAFKA-2411 is finished.

**Comment by ijuma** [comment]
@dajac, it turns out that I need https://github.com/dajac/kafka/commit/28f64252ec7a670b50522ebee05820031c160ae4 for KAFKA-2411 in order to use `NetworkClient` for the requests (`Selector` wasn't good enough for our needs). Is it OK if I cherry-pick that into my branch (you will remain as the author of the change)?

**Comment by dajac** [comment]
@ijuma You can cherry-pick it or I can also do a PR with this part to keep the link to KAFKA-2072 if you prefer. As you like.

**Comment by ijuma** [comment]
@dajac I am happy either way, so I'll leave it up to you. :) If you create a PR with only that commit, I will review it. We will still need a committer to review it and merge it though.

**Comment by dajac** [comment]
@ijuma Ok. I just opened PR (#170) with this part.

**Comment by b-goyal** [comment]
Migration is done but this PR will need to be rebased on #110. I have copied some code (ef669a5) for now.

I'd appreciate feedback on it mainly around how I handle things in the ControllerChannelManager. I have introduced a new 'sendRequest' method for o.a.k.common.requests and kept the old one for compatibility reason. We'll be able to remove the old one in the future when migration of all requests and responses to o.a.k.common.requests is completed.

**Comment by b-goyal** [comment]
Migration is done but this PR will need to be rebased on #110. I have copied some code (ef669a5) for now.

I'd appreciate feedback on it mainly around how I handle things in the ControllerChannelManager. I have introduced a new 'sendRequest' method for o.a.k.common.requests and kept the old one for compatibility reason. We'll be able to remove the old one in the future when migration of all requests and responses to o.a.k.common.requests is completed.

**Comment by b-goyal** [comment]
Migration is done but this PR will need to be rebased on #110. I have copied some code (ef669a5) for now.

I'd appreciate feedback on it mainly around how I handle things in the ControllerChannelManager. I have introduced a new 'sendRequest' method for o.a.k.common.requests and kept the old one for compatibility reason. We'll be able to remove the old one in the future when migration of all requests and responses to o.a.k.common.requests is completed.

**Comment by b-goyal** [comment]
Migration is done but this PR will need to be rebased on #110. I have copied some code (ef669a5) for now.

I'd appreciate feedback on it mainly around how I handle things in the ControllerChannelManager. I have introduced a new 'sendRequest' method for o.a.k.common.requests and kept the old one for compatibility reason. We'll be able to remove the old one in the future when migration of all requests and responses to o.a.k.common.requests is completed.

**Pull request closed without merging**
