### PR TITLE
KAFKA-2485; Allow producer performance to take properties from a file…

### PR DESCRIPTION
**Pull request by lindong28**
… via --consumer.config command line parameter

### CODE REVIEW

**Comment by ewencp** [comment]
LGTM

**Comment by onurkaraman** [comment]
Your patch only applies the change when using the new producer. Was this intentional?
Also you apply the file configs first and then let ProducerPerformance potentially override some configs.

**Comment by lindong28** [comment]
@onurkaraman Thanks! This is not intentional. I just fixed it. 

I intentionally applied the configs first. This is to preserve the existing user interface of producer performance tool. If there is ever conflicts between config file and command line option, I think command line option should take precedence -- user should be able to easily modify the command line option and be confident it takes effect.

**Comment by onurkaraman** [comment]
LGTM

**Comment by lindong28** [comment]
@gwenshap Do you have time to review and commit this patch? It has got two LGTM from non-committers. Thanks!

**Pull request closed without merging**
