### PR TITLE
KAFKA-3134: Fix missing value.deserializer error during KafkaConsumer…

### PR DESCRIPTION
**Pull request by happymap**
… initialization

### CODE REVIEW

**Comment by happymap** [comment]
@guozhangwang Please take a look at it. The exception happens when initializing KafkaConsumer object with a null keySerializer and a non-null valueSerializer. Thanks.

**Comment by ijuma** [comment]
Thanks for the PR, good catch. Can you please add a test?

Also, we should merge this to the 0.9.0 branch as well.

**Comment by granthenke** [comment]
Ah, nice catch. +1 to a unit test.

**Comment by happymap** [comment]
Unit test added. @ijuma Should I create another PR to cherrypick commits to 0.9.0 branch?

**Comment by ijuma** [comment]
@happymap The committer should be able to cherry-pick the commit to 0.9.0 so you don't need to create another PR.

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
