### PR TITLE
MINOR: Add Jenkinsfile to 2.3

### PR DESCRIPTION
**Pull request by vvcephei**
Add a Jenkinsfile for the 2.3 branch so PRs can be built

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
See also #9471 

@ijuma @jolshan @mumrah , are any of you able to review this as well?

**Comment by jolshan** [comment]
The versions look correct to me.

**Comment by jolshan** [comment]
Woo hoo! Tests all pass. LGTM

**Review by jolshan — APPROVED** [review]
Yay! All the tests passed. LGTM

**Review by omkreddy — APPROVED** [review]
LGTM

**Comment by vvcephei** [comment]
Thanks for the reviews!

**Pull request merged**
