### PR TITLE
KAFKA-3941: Delay eviction listener in InMemoryKeyValueLoggedStore after restoration

### PR DESCRIPTION
**Pull request by guozhangwang**
Also move the initialization that restores from changelog to inner stores.

### CODE REVIEW

**Comment by guozhangwang** [comment]
Review by @norwood @dguy @mjsax @enothereska .

**Comment by enothereska** [comment]
@guozhangwang The refactoring to the inner stores looks good. However, I'm having a hard time understanding how the restoration process originally failed and what exactly is currently fixing it. Perhaps additional comments around that code and/or an integration test that exposes the problem would help?

**Comment by guozhangwang** [comment]
@enothereska I have updated the JIRA descrption: https://issues.apache.org/jira/browse/KAFKA-3941, please let me know if it looks easier to understand now.

**Comment by enothereska** [comment]
Thanks, looks better. LGTM, if you think it's important to add a test feel free to do so. LGTM.

**Comment by norwood** [comment]
i tested this locally with an inmemory store and it seems to be working 🔂

**Pull request closed without merging**
