### PR TITLE
Update DelayedFetch.scala

### PR DESCRIPTION
**Pull request by arcz**
Fix typo

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by ijuma** [comment]
Thanks for the pull request. I think this is no longer an issue in trunk. Would you mind closing the PR please? (we can't do it ourselves without asking Apache Infra for help).

**Comment by arcz** [comment]
Sure, no problem :)

**Comment by ijuma** [comment]
Thanks!

**Pull request closed without merging**
