### PR TITLE
KAFKA-3174: Change Crc32 to use java.util.zip.CRC32

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by becketqin** [comment]
The failed test is irrelevant.

**Comment by ijuma** [comment]
Thanks for the PR @becketqin. It would be good to have some details of the performance tests you've done with Java 7 and Java 8.

**Comment by becketqin** [comment]
@ijuma Do you mean adding it to the comments or update the ticket description? I did not test Java 1.7 CRC32 performance. I only tested the one we used to use and the CRC32 performance in Java 1.8.

**Comment by ijuma** [comment]
@becketqin I added a comment to the JIRA. Maybe we continue the conversation there.

**Comment by ijuma** [comment]
This is less important since message format 2 is using CRC32C. I'm going to close this, but feel free to reopen if you think we should still consider this change.

**Pull request closed without merging**
