### PR TITLE
KAFKA-3654: Config validation should validate both common and connector specific configurations

### PR DESCRIPTION
**Pull request by Ishiihara**

### CODE REVIEW

**Comment by Ishiihara** [comment]
@ewencp Can you take a look?

**Comment by ewencp** [comment]
@Ishiihara Basic fix looks fine, but I'm surprised this doesn't affect unit tests at all? Given that it doesn't today, that probably means we should add a simple test where it does.

**Comment by Ishiihara** [comment]
@ewencp Added unit tests. PTAL.

**Comment by ewencp** [comment]
LGTM. We have a bit of technical debt in duplicating code in the test that we could probably just reuse from the validation code, but I'm not sure its worth jumping through hoops to do that since the AbstractHerder is already mocked out of that test and that's the code we'd need to reuse.

**Pull request closed without merging**
