### PR TITLE
0.10.2

### PR DESCRIPTION
**Pull request by sjmittal**
Fixes related to handling of MAX_POLL_INTERVAL_MS_CONFIG deadlock and CommitFailedException

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Can you please target trunk?

**Comment by sjmittal** [comment]
Done.

https://github.com/apache/kafka/pull/2642/

**Comment by mjsax** [comment]
As you replaced this with https://github.com/apache/kafka/pull/2642 can you please close this PR. Thx.

**Comment by sjmittal** [comment]
Closed because #2642 is created.

**Pull request closed without merging**
