### PR TITLE
KAFKA-3170: Set default fetch_min_bytes in new consumer to 1

### PR DESCRIPTION
**Pull request by rajinisivaram**
Set default to 1 instead of 1024, this matches the existing doc and feels like a better default value. Have run the unit tests with the change.

### CODE REVIEW

**Comment by ijuma** [comment]
@jkreps added the doc for fetch.min.bytes and touched the code for it in https://github.com/apache/kafka/commit/0699ff2ce60abb466cab5315977a224f1a70a4da although the value of 1024 was set in a previous commit.

And cc @hachikuji

**Comment by hachikuji** [comment]
LGTM. The 1024 actually goes back a little further: c24740c7b0f6a6e7c66659da786a346650b76766.

**Comment by ijuma** [comment]
@rajinisivaram It would be good to add a note to the upgrade notes documentation page.

**Comment by granthenke** [comment]
+1 to the change. +1 to the docs note. If this is planned for 9.0.1 there is is "Notable changes in 0.9.0.1" section in the docs this can be added to.

**Comment by rajinisivaram** [comment]
@ijuma @granthenke Thank you for the reviews. I have added a note in upgrade.html.

**Comment by ijuma** [comment]
cc @guozhangwang

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and cherry-picked to 0.9.0.

**Comment by jkreps** [comment]
Yeah late to this party but defaulting to anything > 1 is definitely confusing and bad, this is the right fix. Not sure why it was that way, if I did it I plead insanity. :-)

**Pull request closed without merging**
