### PR TITLE
HOTFIX add the hyper link for storage

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
ping @derrickdoo for review and @dguy for merging. This should go into trunk and 0.11.0.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6522/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6508/
Test PASSed (JDK 8 and Scala 2.12).

**Review by enothereska — APPROVED** [review]

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
Thanks @dguy , merged to trunk and 0.11.0.

**Pull request closed without merging**
