### PR TITLE
KAFKA-15802: Validate remote segment state before fetching index

### PR DESCRIPTION
**Pull request by jeqo**
Cherrypick from https://github.com/apache/kafka/pull/14727 into trunk

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jeqo** [comment]
cc @satishd

**Review by satishd — APPROVED** [review]
Thanks @jeqo for the PR. LGTM.

**Comment by satishd** [comment]
There are a few unrelated test failures, merging it to trunk.

**Comment by mimaison** [comment]
Is the work complete? If so can we close [KAFKA-15802](https://issues.apache.org/jira/browse/KAFKA-15802)?

**Pull request merged**
