### PR TITLE
[MINOR] Better estimate size of cache

### PR DESCRIPTION
**Pull request by ableegoldman**
Currently we consider the size of the cache to be the sum of its (doubly-linked) LRUNodes, where we include the next/prev references in our estimate. This completely ignores the other two main data structures of NamedCache, the cache Map and dirtyKeys Set. If we are going to count references we should at least also account for these data structures.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ableegoldman** [comment]
Note that this still does not end up enforcing a hard limit on the cache, as during flush() we create two more Lists (entries and deleted), at least one of which is as large as dirtyKeys. When (or if) we end up wanting to strictly bound the memory we can evict earlier to account for these. I left them out of the calculation here because they're short-lived and only exist when we've already hit the cache size anyway

@bbejeck @cadonna @mjsax @abbccdda @vvcephei @guozhangwang

**Comment by ableegoldman** [comment]
Test failures noted, waiting to patch them up until we agree this is the way to calculate cache size since there are a lot of them...

**Comment by guozhangwang** [comment]
The failed unit tests seem relevant?

**Comment by guozhangwang** [comment]
The failed unit tests seem relevant?

Also just to confirm: this is this just a lower estimate of how references are stored in `ConcurrentSkipListMap` and `LinkedHashSet` right?

**Comment by ableegoldman** [comment]
> The failed unit tests seem relevant?

Failures are definitely related. I just want to make sure we're on the same page before investing time to fix all 18 of them ;)

**Comment by ableegoldman** [comment]
> Also just to confirm: this is this just a lower estimate of how references are stored in `ConcurrentSkipListMap` and `LinkedHashSet` right?

Yeah...I was thinking it would be reasonable to ignore the overhead of the data structures themselves since we really can't be certain, but on second thought if we're counting references we really should account for them even if it's just a rough estimate.

**Pull request closed without merging**
