### PR TITLE
MINOR: Some logging improvements for debugging replication

### PR DESCRIPTION
**Pull request by hachikuji**
A few small logging improvements which help debugging replication issues.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
LGTM

**Comment by hachikuji** [comment]
retest this please

**Comment by hachikuji** [comment]
@rajinisivaram Would you mind reviewing when you have a chance?

**Review by rajinisivaram — APPROVED** [review]
@hachikuji Thanks for the PR, LGTM

**Comment by rajinisivaram** [comment]
Merging to trunk.

**Pull request merged**
