### PR TITLE
MINOR: Manually ported changes in 8c3c9548b636cdf760d2537afe115942d13bc003 

### PR DESCRIPTION
**Pull request by granders**
Porting manually to 0.9.0 (no cherry-pick due to conflicts)

This will allow concurrent system test runs on the same machine

### CODE REVIEW

**Comment by granders** [comment]
@guozhangwang Pinging for review

Running tests here:
http://jenkins.confluent.io/job/kafka_systest_branch_builder2/14

**Comment by granders** [comment]
@guozhangwang Tests pass in branch builder:
http://jenkins.confluent.io/job/kafka_systest_branch_builder2/15/console

**Comment by ijuma** [comment]
The job launched by Geoff was successful.

**Comment by guozhangwang** [comment]
LGTM. Merged to 0.9.0.

**Pull request merged**
