### PR TITLE
MINOR Mark PlaintextAdminIntegrationTest#testShareGroups as flaky

### PR DESCRIPTION
**Pull request by mumrah**
Looks like this regressed in #16842

### CODE REVIEW

**Review by AndrewJSchofield — APPROVED** [review]
I agree this has become flaky.

**Review by rondagostino — APPROVED** [review]
LGTM, thanks!

**Comment by chia7712** [comment]
This test isn't flaky, as it consistently fails no matter how many retries we attempt, correct? If that's the case, we should disable it rather than quarantine it, since it still breaks our CI.

**Comment by mumrah** [comment]
It is actually flaky, just extremely so https://ge.apache.org/scans/tests?search.names=CI%20workflow%2CGit%20repository&search.rootProjectNames=kafka&search.tags=github%2Ctrunk&search.tasks=quarantinedTest%2Ctest&search.timeZoneId=America%2FNew_York&search.values=CI%2Chttps:%2F%2Fgithub.com%2Fapache%2Fkafka&tests.container=kafka.api.PlaintextAdminIntegrationTest&tests.test=testShareGroups(String)%5B1%5D

However, I wouldn't object to disabling it until a fix is made

**Comment by chia7712** [comment]
> It is actually flaky, just extremely so https://ge.apache.org/scans/tests?search.names=CI%20workflow%2CGit%20repository&search.rootProjectNames=kafka&search.tags=github%2Ctrunk&search.tasks=quarantinedTest%2Ctest&search.timeZoneId=America%2FNew_York&search.values=CI%2Chttps:%2F%2Fgithub.com%2Fapache%2Fkafka&tests.container=kafka.api.PlaintextAdminIntegrationTest&tests.test=testShareGroups(String)%5B1%5D

oh, you are right. It is flaky ... it was always failed on my local

**Pull request merged**
