### PR TITLE
MINOR: Fixed default streams state dir location.

### PR DESCRIPTION
**Pull request by Malakhit**
Co-authored-by: Mickael Maison <mickael.maison@gmail.com>
Co-authored-by: Simon Clark <simonc6r@gmail.com>

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Malakhit** [comment]
Test failure was due to rate limiting by the looks of it.

**Comment by harshach** [comment]
+1

**Comment by mjsax** [comment]
This was just reported as https://github.com/apache/kafka/pull/5441 -- will cherry-pick to older branches.

**Comment by mjsax** [comment]
Cherry-picked to `2.0`, `1.1`, and `1.0` (did conflict with `0.11.0` -- will do a new PR)

**Comment by mjsax** [comment]
Just realizing that https://github.com/apache/kafka/pull/5441 is a different issue...

**Comment by mjsax** [comment]
Updates to kafka-site: https://github.com/apache/kafka-site/pull/159

**Pull request merged**
