### PR TITLE
MINOR: WorkerUtils#topicDescriptions must unwrap exceptions properly

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Review by stanislavkozlovski — APPROVED** [review]
Thanks for the PR Colin, LGTM

**Comment by ijuma** [comment]
Would it be possible to add a test?

**Comment by cmccabe** [comment]
I added a unit test.

**Comment by cmccabe** [comment]
retest this please

**Comment by cmccabe** [comment]
retest this please

**Review by stanislavkozlovski — APPROVED** [review]
LGTM once the tests pass

**Comment by stanislavkozlovski** [comment]
retest this please

**Comment by cmccabe** [comment]
The test failure is a connect integration test.  It is not related to this (connect doesn't use this code)
`19:51:19 > Task :connect:runtime:integrationTest FAILED`

**Review by ijuma — APPROVED** [review]
LGTM

**Pull request merged**
