### PR TITLE
KAFKA-3464: Add system tests for Connect with Kafka security enabled

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@gwenshap @granders Simple addition to existing tests to make sure Connect works with all security settings. Not sure if we actually want to include all the variants -- 1 secure version might be enough.

**Comment by ewencp** [comment]
Oh, also, this could actually be double committed if we want -- it cherry-picks cleanly.

**Comment by gwenshap** [comment]
I don't have a strong opinion about all the variants.

Do we have a branch-builder test that passed?

**Comment by ijuma** [comment]
If you want a single non-plaintext security protocol, you could go for SASL_SSL as that exercises both SASL and SSL (although it doesn't exercise SSL client authentication).

**Comment by granders** [comment]
@ewencp 
Somewhat surprisingly I'm seeing a number of test failures here in the branch builder:
https://jenkins.confluent.io/job/system-test-kafka-branch-builder/398/console

**Comment by ewencp** [comment]
@granders Turns out the seemingly innocuous change to `SecurityConfig` actually changed the output a bit by removing a leading `\n`, which meant two configs ended up on the same line and broke some config files if they didn't have the necessary newline before concatenating. While we really should just insert the security config via templating, since we seem to already be manually stringifying and concatenating in a bunch of tests I simply added the newline characters back in and have validated locally that the Connect security tests continue to pass and a MM test with security enabled also passes.

I also reduced the test to only do `PLAINTEXT` and `SASL_SSL` as @ijuma suggested. I think it's better to avoid a ton of extra variants here since we don't expect any difference between the different modes, we just care that the options are actually passed properly to producers/consumers.

I kicked off a new test build here: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/404/

**Comment by ewencp** [comment]
@gwenshap System tests passed 160/161, and the failure looks unrelated. Care to merge?

**Comment by gwenshap** [comment]
LGTM

**Pull request closed without merging**
