### PR TITLE
KAFKA-3409: handle CommitFailedException in MirrorMaker

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
cc @becketqin @SinghAsDev @ijuma 

This is not significantly different from Ashish's patch, but I've added a log statement to give users more guidance if they see this occurring regularly. I think there's more we could be doing internally to mitigate this problem. For example, maybe it makes sense to set a default max.poll.records. Also we currently just block in the send loop after polling the records in receive(), but we probably should abort that loop immediately when the session timeout expires since we'll have no chance of committing offsets anyway. We _could_ try to tackle some of this in this patch, but I'm thinking of opening a separate JIRA since a bigger change will be harder to get into 0.10. Thoughts?

**Comment by ijuma** [comment]
@hachikuji, filing a separate JIRA for the additional improvements sounds good to me.

**Comment by ijuma** [comment]
LGTM

**Comment by SinghAsDev** [comment]
Looks good @hachikuji !

**Comment by guozhangwang** [comment]
LGTM.

**Comment by guozhangwang** [comment]
Merged to trunk and 0.10.0.

**Pull request closed without merging**
