### PR TITLE
Minor: add valueChangingOperation and mergeNode to StreamsGraphNode#toString

### PR DESCRIPTION
**Pull request by tedyu**
This PR adds valueChangingOperation and mergeNode to StreamsGraphNode#toString

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by bbejeck — APPROVED** [review]
Thanks, @tedyu.  Could we add `keyChangingOperation` to this as well?  Otherwise LGTM.

**Comment by bbejeck** [comment]
\cc @guozhangwang @mjsax

**Comment by bbejeck** [comment]
Thanks for the update @tedyu!

**Comment by mjsax** [comment]
Not sure what we want to include in `toString()` -- what about `repartitionRequired` and `hasWrittenToTopology` -- what is the reason to exclude them @bbejeck

**Comment by bbejeck** [comment]
> what is the reason to exclude them @bbejeck

@mjsax just a subjective decision on my part, I didn't feel they were required.  But thinking more about it if we include one of those fields, we should add all of them, so I'm okay with it.

**Comment by guozhangwang** [comment]
@bbejeck the changes seem not including `valueChangingOperation` part?

**Comment by bbejeck** [comment]
> @bbejeck the changes seem not including valueChangingOperation part?

Not sure I follow, as `valueChangingOperation` is included in the `toString`

**Review by guozhangwang — APPROVED** [review]
LGTM.

**Pull request merged**
