### PR TITLE
KAFKA-5557: Using a logPrefix inside the StreamPartitionAssignor

### PR DESCRIPTION
**Pull request by ppatierno**
Added logPrefix for avoiding stream thread name formatting replicated more times

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5900/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5885/
Test PASSed (JDK 8 and Scala 2.12).

**Review by mjsax — APPROVED** [review]
LGTM. Call for second review and merging @guozhangwang @dguy

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk.

**Pull request closed without merging**
