### PR TITLE
MINOR: Serialize response in KafkaApisTest

### PR DESCRIPTION
**Pull request by dajac**
Every request used in KafkaApiTests is serialized before hitting KafkaApis. This ensure that backward compatibility is handled correctly, especially ignorable fields. We don't do the same for the responses though. I think that we should do it because KafkaApis is the layer responsible for ensuring that responses are correct from a version perspective. 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mimaison — APPROVED** [review]
LGTM!

**Comment by mimaison** [comment]
@dajac Can we rebase this PR?

**Comment by dajac** [comment]
@mimaison Will do.

**Comment by dajac** [comment]
@mimaison Could you take a look at the last commit? I had to fix a few more tests when merging trunk.

**Review by mimaison — APPROVED** [review]

**Pull request merged**
