### PR TITLE
KAFKA-4535: http://kafka.apache.org/quickstart Step 8  missing  argument

### PR DESCRIPTION
**Pull request by auroraxlh**
consumer missing argument
This patch corrects the error.
Signed-off-by: aurora777 <xin.lihua1@zte.com.cn>

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. `--new-consumer` should not be needed as of 0.10.1. Can you please elaborate why you think this needs to be added?

**Comment by auroraxlh** [comment]
Try again use the newest version ,problem not exist
I used the old version(0.10.0.1)
the version used 
--zookeeper localhost:2181
not 
----bootstrap-server localhost:9092

problem not exist

i think i made a confused scenario

**Comment by guozhangwang** [comment]
@aurora777 Could you close this PR then? And you can create a new PR against the 0.10.0 branch.

**Comment by auroraxlh** [comment]
@guozhangwang got it

**Comment by ijuma** [comment]
As far as I can tell, the quickstart for 0.10.0.1 has the right instructions too:

https://kafka.apache.org/0100/documentation.html#quickstart

**Comment by auroraxlh** [comment]
@ijuma yeah,
thank you

**Pull request closed without merging**
