### PR TITLE
KAFKA-3896: Unstable test KStreamRepartitionJoinTest.shouldCorrectlyRepartitionOnJoinOperations

### PR DESCRIPTION
**Pull request by dguy**
@ijuma i checked the cases where this test has failed and it seems to always be on the verification of the left join. I've ran this test plenty of times and i can't get it to fail. However in the interest of having stable builds, i've removed just the part of the test that is failing (which happens to be the last verification).
Thanks,
Damian

### CODE REVIEW

**Comment by ijuma** [comment]
@dguy Any idea why it would fail? Is it a timing issue?

**Comment by dguy** [comment]
It must be timing on the slow build boxes. I've not seen it fail locally and i've ran it repeatedly as part of the build and individually

**Comment by ijuma** [comment]
@dguy mentioned offline that the code paths the leftJoin is executing are covered by other tests, and hence why he suggested removing the test. I am not too familiar with the code, so I'll let @guozhangwang review it.

My take is that it's important to understand how a slow build box could cause the incorrect result and if there's a way to make the test more robust, that would probably be better (my opinion is not as well-informed @dguy's and hence why I'll defer to whatever @guozhangwang thinks).

**Comment by guozhangwang** [comment]
@dguy which test case do you think covers this last verification already?

BTW I have also seen that no records or fewer-than-expected messages were produced in the integration tests, even after 30 / 60 seconds: https://issues.apache.org/jira/browse/KAFKA-3882. So I think parallel running integration stream tests may some time stall completely.

**Comment by dguy** [comment]
@guozhangwang the repartition logic is covered by all of the other verifications in that test. The leftJoin is covered by JoinIntegrationTest.
I've ran the build repeatedly on my maxed (100%) laptop and I have yet to get any failures.

**Comment by ijuma** [comment]
It is a bit puzzling why this seems to happen relatively often in Jenkins, another instance here: https://builds.apache.org/job/kafka-trunk-git-pr-jdk7/4400/

**Comment by dguy** [comment]
@guozhangwang @ijuma - i've changed the JoinWindow to 1 day  (from 1 minute) and this looks like it has fixed the issue. I checked the previous failures on Jenkins and this test was taking around 1.5 to over 3 minutes - so a 1 minute JoinWindow for this test was too small. 
I've ran it without fail on jenkins https://jenkins.confluent.io/job/kafka-trunk-debug/  (the one failure wasn't a test failure).

**Comment by guozhangwang** [comment]
Thanks for the investigation @dguy , the reasoning is reasonable to me.

LGTM and merged to trunk.

**Pull request closed without merging**
