### PR TITLE
MINOR: cleanup and add tests to StateDirectoryTest

### PR DESCRIPTION
**Pull request by ableegoldman**
Adds tests for edge conditions of `listAllTaskDirectories`
Also includes some minor cleanup of the StateDirectoryTest class

### CODE REVIEW

**Comment by ableegoldman** [comment]
call for review @cadonna @guozhangwang

**Review by guozhangwang — APPROVED** [review]
All the added tests are checking empty array, so not converting to sets are okay.

**Comment by guozhangwang** [comment]
test this please

**Comment by ableegoldman** [comment]
@guozhangwang can you trigger the tests again?

**Comment by guozhangwang** [comment]
test this please

**Pull request merged**
