### PR TITLE
KAFKA-4100: ensure 'fields' and 'fieldsByName' are not null for Struct schemas

### PR DESCRIPTION
**Pull request by shikhar**

### CODE REVIEW

**Comment by shikhar** [comment]
cc @ewencp for review

**Comment by ewencp** [comment]
@shikhar Change looks good. Test? Also, technically we have `SchemaBuilder` implement `Schema` as well, so you could potentially run into similar issues with that class if no fields had been added. In fact, you could probably fix both just by fixing the same issue in `SchemaBuilder`'s constructor since then the empty field list would be carried over to `ConnectSchema`'s constructor.

**Comment by shikhar** [comment]
thanks @ewencp, addressed comment

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
