### PR TITLE
KAFKA-6883: Add toUpperCase support to sasl.kerberos.principal.to.local rule (KIP-309)

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by omkreddy** [comment]
retest this please

**Review by rajinisivaram — APPROVED** [review]
@omkreddy Thanks for the PR, LGTM

**Comment by rajinisivaram** [comment]
retest this please

**Comment by omkreddy** [comment]
retest this please

**Comment by omkreddy** [comment]
Thanks for the review. Test failures are not related. Merging to trunk.

**Pull request closed without merging**
