### PR TITLE
Hotfix: fixed instable Streams application reset integration test

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
@ijuma

**Comment by enothereska** [comment]
LGTM

**Comment by ijuma** [comment]
Jenkins build failed on an unrelated test. Started another run here: https://jenkins.confluent.io/job/kafka-branch-builder/70/

**Comment by ijuma** [comment]
This test passed, although the run had unrelated failures (other Streams tests). All tests passed when I ran them locally.

**Pull request closed without merging**
