### PR TITLE
MINOR: (docs) in section, not at section

### PR DESCRIPTION
**Pull request by mihbor**
See https://english.stackexchange.com/questions/158981/at-this-section-vs-in-this-section and https://forum.wordreference.com/threads/at-in-within-the-section-we-can-find.374188/

### CODE REVIEW

**Comment by ijuma** [comment]
cc @enothereska @guozhangwang

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5395/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5380/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
LGTM.

**Comment by guozhangwang** [comment]
Merged to trunk / 0.11.0.

**Pull request closed without merging**
