### PR TITLE
MINOR: Redirected the creation of new Thread to KafkaThread class.

### PR DESCRIPTION
**Pull request by kamalcph**
- removed `newThread` & `daemonThread` methods from the Utils.

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5337/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5352/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
Merged to trunk.

**Pull request closed without merging**
