### PR TITLE
KAFKA-2770: Catch and ignore WakeupException for commit upon closing

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
ping @becketqin @hachikuji @granders for reviews.

**Comment by hachikuji** [comment]
LGTM. One minor note: I think the rethrow in commitOffsets() might not be needed since the isShuttingDown flag is used to break out of the loop. However, I actually prefer to keep it that way since it maintains the invariant that wakeups are guaranteed to reach the poll loop.

**Comment by guozhangwang** [comment]
Admittedly this is not the most elegant way of patching this issue, as I feel the new / old consumer's usage pattern is quite different and tricky to be unified, and a better solution would be a new MM class that only uses new clients, but that may be worth another ticket.

**Comment by granders** [comment]
@guozhangwang Have you verified that the corresponding system test passes with this change?

**Comment by guozhangwang** [comment]
Not yet, could you let me know which test case I should verify against? And how often it was reproducible before (I think it is timing dependent)?

**Comment by granders** [comment]
@guozhangwang You'll need to update the `@ignore` annotation for this particular test so it only ignores the `clean_shutdown: false, new_consumer: true` case

you can run with:
`ducktape tests/kafkatest/tests/mirror_maker_test.py::TestMirrorMakerService.test_bounce --parameters '{"clean_shutdown":true, "new_consumer":true}'`

This test failed for me on every run, but the process hang tended not to manifest until after a few bounces.

**Comment by gwenshap** [comment]
LGTM.

I'll merge after you remove the "@ignore" flag from the test

**Comment by guozhangwang** [comment]
@granders @hachikuji The integration test now passes with no data loss (tested 3 times, and previously it breaks every time). The fix is not optimal such that it maintains a separate offset map for new consumer to commit, as mentioned above the optimal solution would be not unifying the interfaces of old / new consumers and re-work MM with only the new clients.

**Comment by granders** [comment]
@guozhangwang This looks good to me. Probably good for @hachikuji  to take a quick look since he is more familiar with the new consumer.

Also, it would be good to verify the hard bounce test case (it sounds like only the clean bounce was verified)

**Comment by hachikuji** [comment]
@guozhangwang Only question I have is whether we should be clearing the offset map on rebalances? If we don't clear it, wouldn't that cause us to commit offsets from older generations?

**Comment by guozhangwang** [comment]
@hachikuji Good point. Instead of clearing on rebalance, I would prefer clearing right after each commit since that is simpler.

**Comment by hachikuji** [comment]
@guozhangwang Yep, that works too. LGTM.

**Comment by guozhangwang** [comment]
Merged to both trunk and 0.9.0 branch.

**Pull request closed without merging**
