### PR TITLE
KAFKA-5876: Apply InvalidStateStorePartitionException for Interactive Queries

### PR DESCRIPTION
**Pull request by vitojeng**
follow-up #8200

KAFKA-5876's PR break into multiple parts, this PR is part 4 - apply InvalidStateStorePartitionException

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vitojeng** [comment]
@ableegoldman Please take a look :)

**Review by ableegoldman — APPROVED** [review]
This was an easy one. Nice 😄 

LGTM, and test failures are only in the constantly flaky RaftClusterTest.

**Comment by ableegoldman** [comment]
Merged to trunk

**Comment by vitojeng** [comment]
@ableegoldman Thanks. :)

**Comment by ableegoldman** [comment]
Hey @vitojeng , was this the final PR for KIP-216? If not is the next one available yet? No rush, just want to make sure you haven't been waiting on reviews this whole time 🙂 

edit: I copied over the list of exceptions on the KIP to the ticket description and marked those I could find PRs for as done. Please let me know if I missed any (to answer my question above, it seems there are three exceptions/PRs remaining, is that correct?)

**Comment by vitojeng** [comment]
@ableegoldman Thanks for your concern, KIP-216 still in progress. 🙂 
It's really busy in the last two weeks, some bad things continue to happen in Taiwan.
I will stick to it until KIP-216 is completed. 💪

> Please let me know if I missed any (to answer my question above, it seems there are three exceptions/PRs remaining, is that correct?)

Yes, you are right. The three exceptions are the most important part in KIP-216, IMO.
I wish to submit the next PR in next week.

**Comment by ableegoldman** [comment]
No worries! Take care of yourself first, KIP-216 can wait for you 🙂  I just wanted to check in and mostly, make sure you don't need anything from my end. I'll keep an eye out for the next parts whenever they're ready

**Pull request merged**
