### PR TITLE
KAFKA-6891: send.buffer.bytes should be allowed to set -1 in KafkaConnect

### PR DESCRIPTION
**Pull request by garyparrot**
### What changes were proposed in this pull request?

Fix the incorrect valid range of the following Kafka connect configs: [send.buffer.bytes](https://kafka.apache.org/documentation/#connectconfigs_send.buffer.bytes) and [receive.buffer.bytes](https://kafka.apache.org/documentation/#connectconfigs_receive.buffer.bytes).

image

Currently, the valid values start from `0`, although the documentation states `-1` is also a valid value.

### How was this patch tested?

Add relevant unit test to `DistributedConfigTest`.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@garyparrot nice catch. It is not only typo but also incorrect validation. the `atLeast(0)` disables users to input `-1` for socket buffer. Hence, this PR is fixing a `bug` rather than a `typo`. If this is related to a bug, could you file a JIRA with new topic and description. That can help reader in the future to trace similar issue. thanks

**Comment by garyparrot** [comment]
@chia7712 Thanks for your opinion. Indeed this issue should be treated as a bug (The contribution guide has addressed this, sorry I am not familiar with the rules here). 

I find this issue has already been mentioned at [KAFKA-6891](https://issues.apache.org/jira/browse/KAFKA-6891). I have self-assigned that issue and updated the description. 

Please take another look, thanks.

**Review by chia7712 — APPROVED** [review]
LGTM. thanks for this contribution.

**Comment by chia7712** [comment]
@garyparrot could you rebase PR to trigger QA again?

**Comment by chia7712** [comment]
linked to stale PR (#4995)

**Comment by garyparrot** [comment]
Sure thing.

**Comment by chia7712** [comment]
@garyparrot could you merge trunk to trigger QA again?

**Comment by chia7712** [comment]
```
[2023-03-20T05:31:14.475Z] BUILD SUCCESSFUL in 1h 44m 21s
[2023-03-20T05:31:14.475Z] 224 actionable tasks: 120 executed, 104 up-to-date
```

the tests pass. will merge it later

**Comment by chia7712** [comment]
@garyparrot thanks for this contribution

**Pull request merged**
