### PR TITLE
MINOR: Improve log4j on stream thread and stream process

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
ping @xvrl @dguy @mjsax @enothereska . I will try to merge this into 0.10.2 as well if possible.

**Review by mjsax — APPROVED** [review]

**Review by dguy — APPROVED** [review]
LGTM

**Comment by enothereska** [comment]
LGTM

**Review by hachikuji — APPROVED** [review]
LGTM

**Pull request closed without merging**
