### PR TITLE
MINOR: fixed StickyAssignor javadoc

### PR DESCRIPTION
**Pull request by mimaison**
StickyAssignor javadoc has a bunch of formatting issues which make it pretty hard to read:
http://kafka.apache.org/0110/javadoc/org/apache/kafka/clients/consumer/StickyAssignor.html

cc @vahidhashemian

### CODE REVIEW

**Review by ijuma — COMMENTED** [review]
Thanks for the PR, it does look horrible at the moment. Is there a reason why you are using `<div>` instead of `<p>`? It seems like the latter is what's typically used in javadocs.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6772/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by mimaison** [comment]
No particular reasons, if `<p>` is more common, I'll switch to it

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6775/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6760/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by vahidhashemian** [comment]
Thanks @mimaison. I agree with @ijuma; it does look horrible now.
It looks great with your patch.

**Comment by mimaison** [comment]
@ijuma are you happy with this change ?

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM. I think there are a few places where we could probably add a paragraph to make the spacing a bit more even, but this is already such a huge improvement so I just went ahead and merged it to trunk.

**Pull request closed without merging**
