### PR TITLE
MINOR: Dependency updates for Scala libraries for improved Scala 3.0 support

### PR DESCRIPTION
**Pull request by jlprat**
Release notes:
* Scala 2.12.14: https://github.com/scala/scala/releases/tag/v2.12.14
* Scala Logging: https://github.com/lightbend/scala-logging/releases/tag/v3.9.3
* Scala Collection Compat:
  *  https://github.com/scala/scala-collection-compat/releases/tag/v2.3.1
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.3.2
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.0
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.1
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.2
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.3
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.4
* Scala Java8 Compat:
  * https://github.com/scala/scala-java8-compat/releases/tag/v1.0.0-RC1
  * https://github.com/scala/scala-java8-compat/releases/tag/v1.0.0

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
cc @ijuma Could you please review this PR, as you were the one reviewing this for the last time?
Thanks in advance

**Comment by ijuma** [comment]
Thanks for the PR. Can you please include links to the various release notes? We typically look through them to understand if there's anything to be worried about.

**Comment by jlprat** [comment]
Sure thing, let me fetch them and link them here:
* Spotless: Unfortunately there is no release notes to be found
* Scala 2.12.14: https://github.com/scala/scala/releases/tag/v2.12.14
* Scala Logging: https://github.com/lightbend/scala-logging/releases/tag/v3.9.3
* Scala Collection Compat:
  *  https://github.com/scala/scala-collection-compat/releases/tag/v2.3.1
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.3.2
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.0
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.1
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.2
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.3
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.4
* Scala Java8 Compat:
  * https://github.com/scala/scala-java8-compat/releases/tag/v1.0.0-RC1
  * https://github.com/scala/scala-java8-compat/releases/tag/v1.0.0
* ~Snappy:~ 
  * ~https://github.com/xerial/snappy-java/releases/tag/1.1.8.2~
  * ~https://github.com/xerial/snappy-java/releases/tag/1.1.8.3~
  * ~https://github.com/xerial/snappy-java/releases/tag/1.1.8.4~

**Comment by ijuma** [comment]
The snappy update doesn't seem related to Scala. Maybe that should be a separate PR.

**Comment by jlprat** [comment]
You are right, I should have skipped it. Fix pushed

**Comment by jlprat** [comment]
@ijuma You can review now

**Comment by ijuma** [comment]
JDK 8 and Scala 2.12 has two unrelated failures.

**Comment by jlprat** [comment]
Thanks a lot for the review @ijuma !

**Pull request merged**
