### PR TITLE
KAFKA-4440: Make producer RecordMetadata non-final

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@jjkoshy Could you take a look at this PR?

**Comment by ewencp** [comment]
Not moving this out of 0.10.2.0 yet because the patch itself is extremely trivial, just a matter of the implications of making the change. @guozhangwang @jjkoshy can we get a +1/-1 on this and get it committed?

**Comment by guozhangwang** [comment]
I'm +0 to this change, and I think this is a follow-up of another JIRA reviewed by @jjkoshy , so leaving it to him to decide.

**Comment by jjkoshy** [comment]
Apologies for the late review - I think this change is fine; although I'm +0 as well. For the `Producer/ConsumerRecord` extensibility the thought was that you could insert additional fields (say if you wanted to envelope your payload with other information such as producing IP or guid, etc. without exposing that directly to the application). `RecordMetadata` on the other hand is derived from a broker response, so in the absence of a broker-side on-response interceptor I'm unclear on how it could be used. It would help if you could summarize how this would actually be used.

**Comment by rajinisivaram** [comment]
@jjkoshy We have a reactive API on top of the Java producer/consumer. The API adds additional metadata to producer record (to track the record later in the flow) and record metadata (to match the result to the record that was sent - this is the metadata that was added to the producer record). We extend consumer record as well to be able to track and commit the record later in the flow. At the moment, all three are done using delegation since the classes were final. It would be nice to be able to subclass instead, especially since the other two were changed to non-final. At the moment, there is only one non-final class in o.a.k.c.producer/o.a.k.c.consumer and that is `RecordMetadata`. While it made sense to keep all classes final in the API, there seems to be less value in keeping just this one class final.

Having said that, there is nothing wrong with delegation and I wasn't considering submitting a PR until I saw the change to the other two. So I wouldn't be too concerned if this was not committed. If the change is not in 0.10.2.0, we are unlikely to use it anyway.

**Comment by rajinisivaram** [comment]
Closing this PR based on earlier discussions here.

**Pull request closed without merging**
