### PR TITLE
KAFKA-15723: KRaft support in ListOffsetsRequestTest

### PR DESCRIPTION
**Pull request by linzihao1999**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
It looks like this breaks `ListOffsetsRequestWithRemoteStoreTest`. See the test results: https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-15047/2/testReport/

**Comment by mimaison** [comment]
@linzihao1999 Are you able to follow up and update this PR? No worries if you can't, just let us know and we'll reassign [KAFKA-15723](https://issues.apache.org/jira/browse/KAFKA-15723). Thanks

**Comment by linzihao1999** [comment]
@mimaison Sorry for stale this issue. I am busy this period, so feel free to reassign.

**Comment by mimaison** [comment]
Ok, no worries. So I'll close this PR and I'll open a new one marking you as co-author.

**Pull request closed without merging**
