### PR TITLE
KAFKA-8602: Separate PR for 2.3 branch

### PR DESCRIPTION
**Pull request by bbejeck**
This PR is from the original work by @cadonna in #7008.  Due to incompatible changes in trunk that should not get cherry-picked back, a separate PR is required for this bug fix

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @guozhangwang @mjsax @vvcephei @ableegoldman @abbccdda for reviews.

**Comment by bbejeck** [comment]
Java 11 failed with
```
23:02:54 stderr: fatal: unable to connect to github.com:
23:02:54 github.com: Temporary failure in name resolution
```

**Review by mjsax — APPROVED** [review]
LGTM.

**Comment by bbejeck** [comment]
retest this please

**Comment by bbejeck** [comment]
Java 8 passed, Java 11 failed with 
```
23:16:49 stderr: fatal: unable to connect to github.com:
23:16:49 github.com: Temporary failure in name resolution
```

**Comment by bbejeck** [comment]
retest this please

**Comment by bbejeck** [comment]
Merged #7092 into 2.3

**Comment by bbejeck** [comment]
cherry-picked to 2.2 and 2.1

**Pull request merged**
