### PR TITLE
MINOR: Updated KafkaZkClient.pathExists() to use ExistsRequest

### PR DESCRIPTION
**Pull request by mimaison**
rather than using GetDataRequest

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by asfgit** [comment]
FAILURE
 8067 tests run, 5 skipped, 2 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8067 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7275 tests run, 1 skipped, 0 failed.
--none--

**Comment by ijuma** [comment]
Failures are unrelated. Merging to trunk.

**Pull request closed without merging**
