### PR TITLE
KAFKA-15360: Include dirs in BrokerRegistration 

### PR DESCRIPTION
**Pull request by soarez**
Include OnlineDirs and OfflineDirs as part of the broker registration request.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by soarez** [comment]
cc @rondagostino

**Comment by soarez** [comment]
@cmccabe @pprovenzano this builds on [KAFKA-15451](https://github.com/apache/kafka/pull/14368) (#14368). Please take a look.

**Comment by pprovenzano** [comment]
So, I think here we just want to set the list of directory UUIDs that we know about and assume they are online. We can later set a known directory to offline with our first heartbeat. Since there can be directories that the controller knows about and the broker doesn't we will need to reconcile those first.

**Comment by soarez** [comment]
I don't think I understand your comment/suggestion. The broker can only know UUIDs for directories that are online. If they are offline the directory ID cannot be read. What should be done differently and why?

**Comment by pprovenzano** [comment]
> I don't think I understand your comment/suggestion. The broker can only know UUIDs for directories that are online. If they are offline the directory ID cannot be read. What should be done differently and why?

Sorry,  this I saw the same heartbeat code that is in https://github.com/apache/kafka/pull/14368 and was wondering why? I missed the code that actually sends the registration.

**Comment by pprovenzano** [comment]
LGTM

**Review by cmccabe — APPROVED** [review]
LGTM

**Comment by cmccabe** [comment]
Committed, thanks!

**Comment by dajac** [comment]
This PR has introduces a compilation error (JDK 8 and Scala 2.12):

```
> Task :core:compileScala

[Error] /home/jenkins/workspace/Kafka_kafka-pr_PR-14392/core/src/main/scala/kafka/server/BrokerLifecycleManager.scala:305:49: value incl is not a member of scala.collection.immutable.Set[org.apache.kafka.common.Uuid]
```

**Pull request closed without merging**
