### PR TITLE
HOTFIX: Added another broker to smoke test

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
@guozhangwang please have a look. Thanks.

**Comment by enothereska** [comment]
PR solves one problem, but seems there are others. Do not merge yet.

**Comment by guozhangwang** [comment]
retest this please

**Comment by enothereska** [comment]
org.apache.kafka.streams.integration.ResetIntegrationTest > testReprocessingFromScratchAfterResetWithoutIntermediateUserTopic STARTED
Build timed out (after 180 minutes). Marking the build as aborted. 

Not related to this PR.

**Comment by enothereska** [comment]
The unit tests have nothing to do with this PR.

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
