### PR TITLE
KAFKA-7564: Expose single task details in Trogdor

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
This PR adds a new "/coordinator/tasks/{taskId}" endpoint which fetches details for a single task

### CODE REVIEW

**Comment by stanislavkozlovski** [comment]
Hey @cmccabe, could you review this one?

**Comment by cmccabe** [comment]
LGTM.  Thanks, @stanislavkozlovski

**Comment by cmccabe** [comment]
retest this please

**Comment by stanislavkozlovski** [comment]
retest this please

**Pull request merged**
