### PR TITLE
KAFKA-5246: Remove backdoor that allows any client to produce to internal topics

### PR DESCRIPTION
**Pull request by big-andy-coates**
removing unused `AdminUtils.AdminClientId`, as its a security hole.

@ijuma @guozhangwang would appreciate a review please =)

I state the contribution is my own work and I license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Not sure I would call this a security hole. In a secure cluster, ACLs would be used to determine who can write to internal topics, right?

Having said that, if there is no good use case for allowing this, it may be a good idea to disallow it. It is technically a breaking change to the protocol, which means a KIP is required. @junrao, do you know why this was allowed in the first place?

**Comment by big-andy-coates** [comment]
@ijuma thanks for taking a look. You're right, ACLs could be used to restrict this. Though in a cluster that wasn't locked down, allowing anyone to produce to the __consumer_offsets topic could cause unexpected behaviour.

I guess the question is mostly why such a back door exists in the first place. 

If we are to remove it, it seems a shame that a three line code change to remove an undocumented backdoor requires a KIP!

Assuming we want to plug this hole, are we sure we want the overhead of going down that route?  

@junrao any background and opinions much appreciated!

**Comment by big-andy-coates** [comment]
@ijuma  @junrao friendly bump...

**Comment by junrao** [comment]
@datalorax : Thanks for the patch.

This is added in https://issues.apache.org/jira/browse/KAFKA-1580 with the intention of allowing the admin to manually fix the data in internal topics like __consumer_offsets. It seems that in those cases, it's better to let the admin issue commitOffsetRequest instead of producing to the internal topics directly. 

So, I agree that it seems it's better to remove this logic. @jjkoshy : Since you suggested this change, what do you think?

**Comment by jjkoshy** [comment]
@junrao I actually think it helps to leave open the _option_ of directly producing to internal topics. While it is true that a user could send an `OffsetCommitRequest`, we have in the past also used the facility to emit tombstones. It also allows manually emitting group state (should you wish to do that) into the topic. So in short, IMO I don't think this backdoor should be removed.

**Comment by big-andy-coates** [comment]
Hummm... OK. Given that this can be locked down using ACLs, I guess there is no harm in leaving this in. Let's close this then. Thanks all.

**Pull request closed without merging**
