### PR TITLE
KAFKA-2676: Fix incorrect package name in tests

### PR DESCRIPTION
**Pull request by kichristensen**
Also fixed a couple of other tests with the same issue.

This is my original work and I license the work to the project under the project's open source license

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Can you please also fix AdminClientTest?

**Comment by kichristensen** [comment]
Sure. I've just updated the pull request

**Comment by ijuma** [comment]
Can you please rename the JIRA and PR to better reflect the code change?

Code change LGTM.

**Comment by kichristensen** [comment]
@ijuma I've changed the title of the pull request, but I can't change the title in JIRA, seems like I don't have permission to do so

**Comment by ijuma** [comment]
@kichristensen Thanks, I fixed the JIRA.

LGTM.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and 0.9.0.

**Pull request closed without merging**
