### PR TITLE
MINOR: Add toString to various Kafka Metrics classes

### PR DESCRIPTION
**Pull request by ijuma**
This was useful while debugging a JDK 16 test failure, I noticed these
were missing.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
@dajac any reason not to do this?

**Comment by dajac** [comment]
@ijuma I can't think of any reason not to do this. This seems reasonable to have.

**Review by dajac — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Failures are unrelated.

**Pull request merged**
