### PR TITLE
KAFKA-16448 [WIP]: Add Kafka Streams exception handler for exceptions occuring during processing

### PR DESCRIPTION
**Pull request by loicgreffier**
This PR aims to bring a ProcessingExceptionHandler to Kafka Streams in order to deal with exceptions that occur during processing.

Jira: https://issues.apache.org/jira/browse/KAFKA-16448.

### Contributors

@Dabz 
@sebastienviale
@loicgreffier

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
@loicgreffier Thanks for the PR!
A 1700 lines PR is quite hard to review. 
Could you please split this PR into multiple smaller ones? 
300-500 lines is a good upper bound for the size.

**Comment by loicgreffier** [comment]
@cadonna Understood

**Comment by loicgreffier** [comment]
This PR is currently being divided into multiples PRs:
- PR 1: https://github.com/apache/kafka/pull/16090
- PR 2: https://github.com/apache/kafka/pull/16092
- PR 3: https://github.com/apache/kafka/pull/16093

**Comment by loicgreffier** [comment]
Closing this outdated PR

**Pull request closed without merging**
