### PR TITLE
KAFKA-8713 KIP-581: Add new conf serialize.accept.optional.null in connect-json

### PR DESCRIPTION
**Pull request by pan3793**
See details on KAFKA-8713 and KIP-581

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rayokota** [comment]
The fix is not quite correct.  You need to conditionally call `struct.getWithoutDefault(field.name())`.  You should also add a test using a struct.  See the corresponding fix for the JSON Schema converter in https://github.com/confluentinc/schema-registry/pull/2326

**Comment by FX-HAO** [comment]
may I ask if there's any progress?

**Comment by fuxinhao-crypto** [comment]
@rayokota sorry for bothering you. I'm trying to maintain my own version of `JsonConverter`. I just copied the code and pasted it to a new class `JsonConverter`. and I replaced the following line  

https://github.com/a0x8o/kafka/blob/283d07f9d2577e78b7aab7a419818cf9cda19d0a/connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java#L664

to 

```java
obj.set(field.name(), this.convertToJson(field.schema(), struct.getWithoutDefault(field.name())));
```

Then I changed my debezium config to 

```
        ...
        "key.converter": "org.apache.kafka.connect.json.MyJsonConverter",
        "key.converter.schemas.enabled": true,
        "value.converter": "org.apache.kafka.connect.json.MyJsonConverter",
        "value.converter.schemas.enabled": true,
```

but seems it still does not work. I still got default value with an nullable field.
 do u know why? what else do I need to do?

**Comment by blueberrysugarhigh** [comment]
> @rayokota sorry for bothering you. I'm trying to maintain my own version of `JsonConverter`. I just copied the code and pasted it to a new class `JsonConverter`. and I replaced the following line
> 
> https://github.com/a0x8o/kafka/blob/283d07f9d2577e78b7aab7a419818cf9cda19d0a/connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java#L664
> 
> to
> 
> ```java
> obj.set(field.name(), this.convertToJson(field.schema(), struct.getWithoutDefault(field.name())));
> ```
> 
> Then I changed my debezium config to
> 
> ```
>         ...
>         "key.converter": "org.apache.kafka.connect.json.MyJsonConverter",
>         "key.converter.schemas.enabled": true,
>         "value.converter": "org.apache.kafka.connect.json.MyJsonConverter",
>         "value.converter.schemas.enabled": true,
> ```
> 
> but seems it still does not work. I still got default value with an nullable field. do u know why? what else do I need to do?

Have you been able to make this work ? I just ran into the same issue. I upgraded my schema registry version and tried using the configuration in the connector, but it still was showing the wrong data.

**Comment by rayokota** [comment]
@blueberrysugarhigh , sorry I'm not the author of this PR and I haven't tried it myself.

**Comment by mimaison** [comment]
This has been implemented in https://github.com/apache/kafka/pull/13419. Closing this PR.

**Pull request closed without merging**
