### PR TITLE
KAFKA-4497: Fix the ByteBufferMessageSet.filterInto

### PR DESCRIPTION
**Pull request by becketqin**
There seems a few bugs in `ByteBufferMessageSet.filterInto`, including incorrect offsets, messages read and retained. This patch fixes them and added unit test.

### CODE REVIEW

**Comment by becketqin** [comment]
cc @junrao @hachikuji @ijuma

**Comment by hachikuji** [comment]
@becketqin Thanks. I think I've addressed the same issues in KAFKA-4390 if you want to take a look. I think that patch is getting close to merging, so we may not need to commit this. What do you think?

**Comment by becketqin** [comment]
@hachikuji That makes sense. I'll just merge the fix to 0.10.1 then.

**Comment by becketqin** [comment]
Closing the PR as the fix will be included in KAFKA-4390

**Pull request closed without merging**
