### PR TITLE
KAFKA-10514: Fix unit test for state directory cleanup

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @chia7712 @vvcephei @mjsax @guozhangwang @abbccdda

**Review by chia7712 — APPROVED** [review]

**Comment by vvcephei** [comment]
Test failure was unrelated:
```
Build / JDK 11 / org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[true]
```

**Review by vvcephei — APPROVED** [review]
Thanks @cadonna !

**Comment by vvcephei** [comment]
Cherry-picked to 2.6

**Pull request merged**
