### PR TITLE
MINOR: Remove unsed code in clients:common:errors

### PR DESCRIPTION
**Pull request by ex172000**
There are many unused codes in the exceptions, which lowered the coverage rate by a lot.
Removing to improve the readability and coverage. Tested with compilation and testing in local env.

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
Hi @ex172000 thanks for the PR.
These methods might be indeed not used within the Kafka codebase. However, they are part of the public APIs and removing these methods might break source/binary compatibility.
For this reason I don't think we should remove those from the codebase.

**Comment by ex172000** [comment]
> Hi @ex172000 thanks for the PR. These methods might be indeed not used within the Kafka codebase. However, they are part of the public APIs and removing these methods might break source/binary compatibility. For this reason I don't think we should remove those from the codebase.

Thanks for the reminder @jlprat . I agree it could break backward compatibility. But for features deprecated, we can remove the unused code, right? Maybe we should still take a look at these methods since 4.0 is on the horizon

**Comment by jlprat** [comment]
Correct, deprecated methods and classes can be removed in `4.0.0` (but we are not yet preparing this release) as long as they have been deprecated for a year (if my memory serves right the amount of time was a year)

**Comment by ex172000** [comment]
> Correct, deprecated methods and classes can be removed in `4.0.0` (but we are not yet preparing this release) as long as they have been deprecated for a year (if my memory serves right the amount of time was a year)

ACK, thanks for the info. I will close this change and see if we have anything that's marked deprecated long enough

**Pull request closed without merging**
