### PR TITLE
MINOR: follow up on Streams EOS system tests

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
\cc @bbejeck

**Comment by mjsax** [comment]
EOS system test still fail (but differently) after last PR (not sure why system tests passed on branch builder on #4572).

One issue might be incorrect topic name in verification step (fixed in this PR). Also added more debug statements to get better insight.

Triggered system test: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1304/

**Comment by mjsax** [comment]
1304 passed. Retriggered https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1305/

**Review by bbejeck — APPROVED** [review]
Thanks, @mjsax LGTM

**Review by guozhangwang — APPROVED** [review]
LGTM. Assuming the sysouts are not necessary and will be removed.

**Comment by mjsax** [comment]
I want to keep the sysouts -- if the test fails, it's useful information. Or do you object?

**Comment by guozhangwang** [comment]
> I want to keep the sysouts -- if the test fails, it's useful information. Or do you object?

Ah I see. Sounds good.

**Comment by mjsax** [comment]
Merging this to `trunk` only for now to see if the tests pass tonight. Will cherry-pick to `1.1` later.

**Comment by mjsax** [comment]
EOS system tests passed on `trunk` last night. Cherry-picked this on `1.1` branch.

**Pull request merged**
