### PR TITLE
KAFKA-2335; fix comment about thread safety

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by eribeiro** [comment]
+1. English is not my native language, but I think it LGTM.

**Comment by ewencp** [comment]
+1

**Comment by hachikuji** [comment]
Yeah, that's a good suggestion. I'll update.

**Comment by guozhangwang** [comment]
LGTM. @hachikuji do you want to try the 

python kafka-merge-pr.py

to merge yourself?

**Pull request closed without merging**
