### PR TITLE
MINOR: set scala version automatically based on gradle.properties

### PR DESCRIPTION
**Pull request by akatona84**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by akatona84** [comment]
@ijuma , @omkreddy 
could you review it please?

I added these lines because when scala version is overridden in the gradle.properties then the classpath is not constructed properly, `dependant-libs-2.12.10` doesn't exist.

**Comment by ijuma** [comment]
Thanks for the PR. This looks like a good change. Since we don't have tests for this, it requires manual testing. @omkreddy, do you think you could review and test this?

**Comment by akatona84** [comment]
retest this please

**Review by omkreddy — APPROVED** [review]
@akatona84 Thanks for the PR. LGTM.

**Pull request closed without merging**
