### PR TITLE
MINOR: fix imports in AdminFenceProducersIntegrationTest

### PR DESCRIPTION
**Pull request by jolshan**
The config files were moved after the 3.7 release.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by jlprat** [comment]
Hi @jolshan I believe this same patch should be applied to the 3.8 branch. Am I right?

**Review by mimaison — APPROVED** [review]
LGTM

**Comment by edoardocomar** [comment]
@jlprat no this is not needed for 3.8

**Comment by jlprat** [comment]
Thanks! @edoardocomar

**Comment by edoardocomar** [comment]
@jolshan if you agree, please add this commit to your PR
https://github.com/apache/kafka/pull/16326 
to tag the integration test as such

**Comment by edoardocomar** [comment]
I tested this fix too LGTM - thanks @jolshan

**Review by edoardocomar — APPROVED** [review]

**Comment by jolshan** [comment]
@edoardocomar I can add the commit but it will also restart the build. Given this shouldn't alter code, I'm not sure if we still want to run all the tests.

**Comment by jolshan** [comment]
We had one version fail to build anyway, so I pushed the new commit. Should be good to merge once the job is done.

**Pull request merged**
