### PR TITLE
MINOR: Javadoc typo

### PR DESCRIPTION
**Pull request by astubbs**

### CODE REVIEW

**Comment by enothereska** [comment]
LGTM, @astubbs could you prefix title with `MINOR: Javadoc...`. Thanks.

**Comment by astubbs** [comment]
How's that?

**Comment by enothereska** [comment]
Oops. there is a mix up with the previous commit of peek. You have to rebase or merge your branch with trunk.

**Comment by astubbs** [comment]
Moved here: https://github.com/apache/kafka/pull/4079/commits

**Pull request closed without merging**
