### PR TITLE
MINOR: Bump zstd-jni from 1.5.6-5 to 1.5.6-6

### PR DESCRIPTION
**Pull request by olegbonar**
This is the closest we have to release notes:
https://github.com/luben/zstd-jni/compare/v1.5.6-5...v1.5.6-6

### CODE REVIEW

**Comment by olegbonar** [comment]
@mimaison may I ask you to review this?

**Comment by jlprat** [comment]
hi @olegbonar, can you add the release notes for this version?

**Comment by olegbonar** [comment]
@jlprat, I would happily do it. Could you point me out to it?

**Comment by jlprat** [comment]
I think this is the best we can have for this project. https://github.com/luben/zstd-jni/compare/v1.5.6-4...v1.5.6-5

You can edit your PR description with this link.

**Comment by olegbonar** [comment]
@jlprat done

**Review by jlprat — APPROVED** [review]
Thanks @olegbonar.
LGTM, I'll confirm that the tests failures are unrelated and I'll merge.

**Comment by jlprat** [comment]
Tests passed on GH CI, and the 2 failures in Jenkins CI were known flaky tests.

**Pull request merged**
