### PR TITLE
TRIVIAL: Remove unused parameters, exceptions, comments, etc.

### PR DESCRIPTION
**Pull request by dongjinleekr**
This is a bulk of trivial glitches I found while working on the other issues.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
@dajac Excuse me, could you have a look when you are free? I found the last one (`DefaultQuotaCallback#quotaMetricTags`) while working on [KAFKA-13341](https://issues.apache.org/jira/browse/KAFKA-13341). The static client-id quota is removed in 3.0.0 but still remains in the comments. (see: [KAFKA-13430](https://issues.apache.org/jira/browse/KAFKA-13430))

**Comment by mimaison** [comment]
Thanks @dongjinleekr for the cleanup. It looks like you missed some changes in `DumpLogSegments.scala`:
```
[Error] /Users/mickael/github/kafka/core/src/main/scala/kafka/tools/DumpLogSegments.scala:62: too many arguments (found 7, expected 6) for method dumpLog: (file: java.io.File, printContents: Boolean, nonConsecutivePairsForLogFilesMap: scala.collection.mutable.Map[String,List[(Long, Long)]], isDeepIteration: Boolean, parser: kafka.tools.DumpLogSegments.MessageParser[_, _], skipRecordMetadata: Boolean): Unit
[Error] /Users/mickael/github/kafka/core/src/main/scala/kafka/tools/DumpLogSegments.scala:66: too many arguments (found 5, expected 4) for method dumpTimeIndex: (file: java.io.File, indexSanityOnly: Boolean, verifyOnly: Boolean, timeIndexDumpErrors: kafka.tools.DumpLogSegments.TimeIndexDumpErrors): Unit
```

**Comment by dongjinleekr** [comment]
@mimaison Here is the fix; redundant parameters to call `DumpLogSegments#[dumpLog, dumpTimeIndex]` in `DumpLogSegments#main` also had to be removed. After removing it, it works like a charm.

I am still curious why the scala compiler has been past this, explicit syntax errors. It may be related to `DumpLogSegments.dumpTimeIndex( ... Int.MaxValue)` I removed earlier, but I can't be certain yet.

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request merged**
