### PR TITLE
KAFKA-4907: message.timestamp.difference.max.ms should not be applied to log compacted topic if user did not set the property.

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by becketqin** [comment]
@junrao @ijuma I took a shot to fix this. Not sure if there is a better way to do this. 

Another option is to to just change the default message.timestamp.difference.max.ms back to Long.MaxValue, because that was only a optimization, but it seems already introduced a few issues.

**Comment by ijuma** [comment]
Thanks @becketqin. I'm not sure the additional complexity is worth the optimisation, but let's see what @junrao says.

**Comment by junrao** [comment]
@becketqin : Thanks for the patch. Sorry for late review. It does seem that this adds quite a bit complexity and will be a bit hard to reason about. So, I agree that the easiest thing is to just revert the changes in KAFKA-4340 and default message.timestamp.difference.max.ms back to Long.MaxValue. Without KAFKA-4340, in the worse case, it seems that every other segment could be rolled with just a single message in it. It's not ideal, but probably won't break things immediately. The users can always explicitly override the config if desired. Do you think you could submit a patch to default message.timestamp.difference.max.ms back to Long.MaxValue in the next few days for the 0.11.0.0 release?

**Comment by becketqin** [comment]
@junrao Yes, I agree that the easiest thing to do is to change the default value of `message.timestamp.difference.max.ms` to Long.MaxValue. I'll do that. Looking at KAFKA-4340, most the of part can leave as is, I think we just need to change the default value to be Long.MaxValue. I'll submit a patch shortly.

**Comment by hachikuji** [comment]
Closing this since the issue was resolved as "won't fix." Please reopen if this was a mistake.

**Pull request closed without merging**
