### PR TITLE
MINOR: Make JmxMixin wait for the monitored process to be listening on the JMX port before launching JmxTool

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@ijuma @apurvam This addresses a race condition with JmxTool and the process it is monitoring. Since JmxTool doesn't handle failure particularly well, if we see enough lag in the monitored process listening on the JMX port, JmxTool just craps out. Something like this will appear in the log:

```
{'ConsoleConsumer-0-139872609774672-worker-1': TimeoutError('ubuntu@worker3: Jmx tool took too long to start',)}
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/system-test-kafka/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.6.0-py2.7.egg/ducktape/tests/runner_client.py", line 123, in run
    data = self.run_test()
  File "/var/lib/jenkins/workspace/system-test-kafka/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.6.0-py2.7.egg/ducktape/tests/runner_client.py", line 176, in run_test
    return self.test_context.function(self.test)
  File "/var/lib/jenkins/workspace/system-test-kafka/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.6.0-py2.7.egg/ducktape/mark/_mark.py", line 321, in wrapper
    return functools.partial(f, *args, **kwargs)(*w_args, **w_kwargs)
  File "/var/lib/jenkins/workspace/system-test-kafka/kafka/tests/kafkatest/tests/connect/connect_test.py", line 118, in test_file_source_and_sink
    self.consumer_validator.run()
  File "/var/lib/jenkins/workspace/system-test-kafka/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.6.0-py2.7.egg/ducktape/services/service.py", line 290, in run
    self.wait()
  File "/var/lib/jenkins/workspace/system-test-kafka/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.6.0-py2.7.egg/ducktape/services/background_thread.py", line 70, in wait
    raise Exception(str(self.worker_errors))
Exception: {'ConsoleConsumer-0-139872609774672-worker-1': TimeoutError('ubuntu@worker3: Jmx tool took too long to start',)}
```

Although often times JmxTool is being run via a BackgroundThread so this cause is sometimes hidden by another error message that is reported as the cause of the failure (usually that the service using it didn't start up quickly enough).

The fix is to just validate that we can connect to the port before ever launching JmxTool. I didn't include it here, but I tested that by adding an extra `sleep 10` to console consumer's launch command (with a couple of other tweaks required because console consumer also waits for the first line of output before starting JMX), I could consistently reproduce the issue. Then, adding in this fix with a sufficiently long timeout fixed the issue.

I tested that in ducker, and I've kicked off https://jenkins.confluent.io/job/system-test-kafka-branch-builder/938/ just to validate that we're not missing the nc dependency on the AMIs we execute on.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5699/
Test PASSed (JDK 8 and Scala 2.12).

**Review by apurvam — COMMENTED** [review]
This change makes sense. Thanks!

We also have a `sleep(1)` in `produce_consume_validate.py` which was added to get around this race condition. Perhaps we can remove it along with this patch. The specific line is https://github.com/apache/kafka/blob/trunk/tests/kafkatest/tests/produce_consume_validate.py#L67

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5720/
Test PASSed (JDK 7 and Scala 2.11).

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Review by apurvam — APPROVED** [review]
LGTM! thanks!

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5706/
Test PASSed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
