### PR TITLE
MINOR; Fix KRaft metadata version system tests

### PR DESCRIPTION
**Pull request by jsancio**
The latest metadata version is now 3.7. Fix the KRaft upgrade system test to upgrade to that version instead of 3.6.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jsancio** [comment]
I started a system test build for this branch. I'll report back when it finishes.

**Review by mumrah — APPROVED** [review]
Thanks @jsancio the change LGTM pending a successful system test run

**Comment by jsancio** [comment]
Thanks for the review @mumrah . The system test failed because the 3.3.x version was not current. Fixed and rerunning the system tests.

**Comment by jsancio** [comment]
System tests are green.
```
================================================================================
SESSION REPORT (ALL TESTS)
ducktape version: 0.8.14
session_id:       2023-11-09--001
run time:         10 minutes 45.434 seconds
tests run:        12
passed:           12
flaky:            0
failed:           0
ignored:          0
================================================================================
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_isolated_mode_upgrade.from_kafka_version=3.3.2.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   3 minutes 22.675 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_combined_mode_upgrade.from_kafka_version=3.1.2.metadata_quorum=COMBINED_KRAFT
status:     PASS
run time:   3 minutes 26.013 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_isolated_mode_upgrade.from_kafka_version=3.1.2.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   3 minutes 34.273 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_isolated_mode_upgrade.from_kafka_version=3.2.3.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   3 minutes 56.827 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_combined_mode_upgrade.from_kafka_version=3.2.3.metadata_quorum=COMBINED_KRAFT
status:     PASS
run time:   3 minutes 8.597 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_isolated_mode_upgrade.from_kafka_version=3.5.1.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   3 minutes 17.410 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_isolated_mode_upgrade.from_kafka_version=dev.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   3 minutes 13.048 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_isolated_mode_upgrade.from_kafka_version=3.4.1.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   3 minutes 52.438 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_combined_mode_upgrade.from_kafka_version=3.3.2.metadata_quorum=COMBINED_KRAFT
status:     PASS
run time:   3 minutes 3.473 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_combined_mode_upgrade.from_kafka_version=3.4.1.metadata_quorum=COMBINED_KRAFT
status:     PASS
run time:   2 minutes 52.462 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_combined_mode_upgrade.from_kafka_version=3.5.1.metadata_quorum=COMBINED_KRAFT
status:     PASS
run time:   3 minutes 1.467 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.kraft_upgrade_test.TestKRaftUpgrade.test_combined_mode_upgrade.from_kafka_version=dev.metadata_quorum=COMBINED_KRAFT
status:     PASS
run time:   3 minutes 35.485 seconds
--------------------------------------------------------------------------------
```

**Comment by jolshan** [comment]
I think we shouldn't have removed 3.3.1 generally. I've addressed it in a PR I opened a while ago. 
https://github.com/apache/kafka/pull/14641

**Comment by jolshan** [comment]
Oh I see we don't seem to test 3.3.1. I guess I can remove that from my change then 👍

**Pull request merged**
