### PR TITLE
KAFKA-5957: Prevent second deallocate if response for aborted batch returns

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by ijuma** [comment]
@rajinisivaram, do you remember why `completed` is an `AtomicBoolean` in the following commit?

https://github.com/apache/kafka/commit/05b1ebd9ea6ca36a77269c71d598a7f613b277ba#diff-d40f2124414371535f2f1e47089eb71dR53

It seems like it's only ever accessed/mutated by the Sender thread. @hachikuji and I wanted to make sure we were not missing anything while discussing a potential alternative solution to the issue fixed by this PR.

**Comment by rajinisivaram** [comment]
@ijuma I don't remember, but looking at the code, it looks like I was just being extra cautious (unnecessarily).

**Review by apurvam — APPROVED** [review]
Thanks for the patch, LGTM! 

I think the observation elsewhere is correct: the batch can only be completed in the sender thread, and there is no need to keep additional state for completion: If a response comes back after the batch is removed from the `incomplete` set, it can be ignored (or at least we know we don't need to update its final state, or remove it from the `incomplete` set).

However, I think the other simplification can be a future patch (not for 1.0.0), while this should be merged into 1.0.0 sooner rather than later.

**Review by ijuma — APPROVED** [review]
LGTM, thanks. Merging to trunk. Can we please file a JIRA for the simplification we discussed in the PR?

**Pull request closed without merging**
