### PR TITLE
org.apache.kafka.streams.errors.StreamsException: Failed to rebalance

### PR DESCRIPTION
**Pull request by l16h7n1n6s**
<p>I am running the below simple example in kafka streams and i got a weird exception which i cannot handle</p>

```
      [ Properties props = new Properties();
        props.put(StreamsConfig.APPLICATION_ID_CONFIG, "streams-pipe");
        props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "192.168.1.3:9092");
        props.put(StreamsConfig.KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass());
        props.put(StreamsConfig.VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass());
        // setting offset reset to earliest so that we can re-run the demo code with the same pre-loaded data
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");

        KStreamBuilder builder = new KStreamBuilder();

        builder.stream("streams-file-input").to("streams-pipe-output");

        KafkaStreams streams = new KafkaStreams(builder, props);
        streams.start();

        // usually the stream application would be running forever,
        // in this example we just let it run for some time and stop since the input data is finite.
        Thread.sleep(5000L);

        streams.close();](url)](url)
```

`Exception in thread "StreamThread-1" org.apache.kafka.streams.errors.StreamsException: Failed to rebalance at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:299)
            at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:218)
        Caused by: org.apache.kafka.streams.errors.ProcessorStateException: Error while creating the state manager`

### CODE REVIEW

**Comment by mjsax** [comment]
This seems not to be a valid PR -- if you want to report a bug, please subscribe to Kafka mailing list (see https://kafka.apache.org/contact.html). @guozhangwang @miguno @enothereska @dguy

**Comment by guozhangwang** [comment]
@stathmarxis I assume you are reporting a problem, not contributing a PR to ASF Kafka, right? The reported issue in your case is likely to be this one: https://issues.apache.org/jira/browse/KAFKA-3559 and we are actively working on this.

**Comment by mjsax** [comment]
@guozhangwang @stathmarxis Should this PR get closed?

**Comment by guozhangwang** [comment]
Only the author or apache can close such PRs. Could you file an Apache Infra ticket to ask them close this? Example: https://issues.apache.org/jira/browse/INFRA-11185

**Comment by mjsax** [comment]
Requested to close via https://issues.apache.org/jira/browse/INFRA-12322

**Comment by gmcdonald** [comment]
closed, thanks

**Pull request closed without merging**
