### PR TITLE
MINOR: revert initial principal PR

### PR DESCRIPTION
**Pull request by abbccdda**
Need to make sure 2.7 doesn't bump the request header unexpectedly.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by abbccdda** [comment]
@bbejeck @hachikuji

**Review by hachikuji — APPROVED** [review]
LGTM assuming the build is ok. Can we do the same thing for trunk?

**Comment by hachikuji** [comment]
@bbejeck FYI, this should be considered a blocker for 2.7.

**Comment by hachikuji** [comment]
@abbccdda On second thought, we should just target trunk here and pick into 2.7 like usual.

**Comment by abbccdda** [comment]
Cool, will do it against trunk

**Comment by abbccdda** [comment]
Reopening this PR to merge to 2.7

**Pull request closed without merging**
