### PR TITLE
KAFKA-5707: TopicCommand and ConfigCommand should remove useless `--force` option.

### PR DESCRIPTION
**Pull request by huxihx**
TopicCommand and ConfigCommand should remove useless `--force` option.

### CODE REVIEW

**Comment by huxihx** [comment]
@ijuma Please review this minor change. Thank you.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6598/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6583/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by omkreddy** [comment]
LGTM

**Comment by ijuma** [comment]
Thanks for the PR. This change will break scripts that are using the `--force` option. We could deprecate for the next release and remove in a subsequent major release, but we might have to add it back if we re-introduce a confirmation prompt at some point.

**Comment by huxihx** [comment]
@ijuma So you mean it's not a bug right now, don't you? Will cancel this PR if we still want to keep it.

**Comment by ijuma** [comment]
The options don't have any effect at the moment, but they had effect in previous releases. So, scripts may be using then. I would say it's not a bug.

**Pull request closed without merging**
