### PR TITLE
KAFKA-8944: Fixed KTable compiler warning.

### PR DESCRIPTION
**Pull request by huxihx**
https://issues.apache.org/jira/browse/KAFKA-8944

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @bbejeck @vvcephei @abbccdda

**Comment by huxihx** [comment]
retest this please.

**Comment by bbejeck** [comment]
Java 11/2.12 build timed out
Java 11/2.13 failed with `ERROR: Error cloning remote repo 'origin'`
Java 8/2.11 failed with 
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create GC thread. Out of system resources.
```

retest this please

**Review by bbejeck — APPROVED** [review]
Thanks for the patch @huxihx.  I checked out the PR and confirmed that compiler warning is gone and the `streams-scala` tests run.

**Comment by mjsax** [comment]
@huxihx Can you rebase this PR to resolve the merge conflicts?

**Comment by huxihx** [comment]
@mjsax Please review again. Thanks

**Comment by bbejeck** [comment]
Merged 7393 into trunk.

**Pull request merged**
