### PR TITLE
KAFKA-5410: Fix taskClass() method name in Connector and flush() signature in SinkTask

### PR DESCRIPTION
**Pull request by ppatierno**

### CODE REVIEW

**Comment by ppatierno** [comment]
Retest this please

**Comment by ppatierno** [comment]
Retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5390/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5375/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ppatierno** [comment]
@guozhangwang can you take a look at this really trivial PR. It's just a simple error in the not updated doc after some code change. Thanks !

**Review by ewencp — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request closed without merging**
