### PR TITLE
KAFKA-2618; Disable SSL renegotiation for 0.9.0.0

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
@rajinisivaram, can you please review this?

**Comment by harshach** [comment]
+1

**Comment by ijuma** [comment]
Thanks for the review Harsha. Feel free to merge it. :)

**Comment by rajinisivaram** [comment]
@ijuma Your code looks good to me. My only question is whether it would make sense to have a configuration option to turn renegotiation on/off and leave that off by default. Presumably many Kafka users would never want to turn on SSL renegotiation, while we would like to enable server-initiated renegotiation pretty soon. We have an HAProxy in front of Kafka to meet our security requirements and hence the need for renegotiation support.

**Comment by ijuma** [comment]
@rajinisivaram presumably you'd need to fix the bugs with renegotiation first? I agree that a config would probably be a good idea, but it doesn't seem like we can get it in for 0.9.0.0 given the other things that need to be done.

**Comment by rajinisivaram** [comment]
@ijuma yes, agreed that config option is not required until bugs are fixed and renegotiation becomes usable.

**Comment by ijuma** [comment]
OK, great. You filed a JIRA ticket about fixing the issues with renegotiation, I think you can add the config as part of that change if you like.

**Comment by junrao** [comment]
Thanks for the patch. LGTM

**Pull request closed without merging**
