### PR TITLE
KAFKA-12203 Migrate connect:mirror-client module to JUnit 5

### PR DESCRIPTION
**Pull request by chia7712**
issue: https://issues.apache.org/jira/browse/KAFKA-12203

Only changes the imports and the dependencies.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
@chia7712 Given the test results for the last build, I think you can merge this, right?

**Comment by chia7712** [comment]
> Given the test results for the last build, I think you can merge this, right?

It produces some failed tests but they pass on my local. I want to check QA again :)

**Comment by ijuma** [comment]
The failed Streams tests seem unrelated, but they seem to be failing very often.

**Comment by chia7712** [comment]
```
org.apache.kafka.streams.integration.AdjustStreamThreadCountTest.shouldAddAndRemoveStreamThreadsWhileKeepingNamesCorrect
```

It is traced by #9888 and #9887

**Pull request merged**
