### PR TITLE
Adjustments to docs to make them work with latest template

### PR DESCRIPTION
**Pull request by derrickdoo**
- Change introduction.html to be a partial like all the other doc content sections
- Fix typo with include statement for the footer of docs
- Stop embedding the full Streams documentation inside of documentation.html now that we're treating it as a separate section.

### CODE REVIEW

**Comment by guozhangwang** [comment]
@derrickdoo Feel free to close this PR as it has been incorporated in another one.

**Comment by guozhangwang** [comment]
@derrickdoo ping again.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6267/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6251/
Test FAILed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
