### PR TITLE
KAFKA-4800: Streams State transition ASCII diagrams need fixing and polishing

### PR DESCRIPTION
**Pull request by cvaliente**
added \<pre> tags to not break javadoc display of the ASCII diagrams.
see broken ascii here:
https://kafka.apache.org/0102/javadoc/org/apache/kafka/streams/KafkaStreams.State.html

fix can be checked with gradle :streams:javadoc and then checking streams/build/docs/javadoc/org/apache/kafka/streams/KafkaStreams.State.html

I also fixed the diagram in StreamThread.java however currently no javadoc is generated for that one (since it's internal)

@enothereska please have a look

### CODE REVIEW

**Comment by enothereska** [comment]
LGTM. @mjsax ?

**Review by mjsax — APPROVED** [review]
LGTM.

**Comment by enothereska** [comment]
@guozhangwang @ijuma any of you could check this in? Thanks.

**Comment by guozhangwang** [comment]
LGTM. Merged to 0.10.2 and trunk.

**Pull request closed without merging**
