### PR TITLE
MINOR Use new Develocity API key

### PR DESCRIPTION
**Pull request by mumrah**
Use the new secret provided by the apache GitHub org.

### CODE REVIEW

**Comment by mumrah** [comment]
Ran it using a temporary `pull_request` trigger here https://github.com/apache/kafka/actions/runs/12374369064/job/34536734813?pr=18229

**Comment by mimaison** [comment]
How did we get the new key?

**Comment by mumrah** [comment]
The key is managed by ASF Infra as a GitHub organization level secret. Prior to this patch, I was parsing the access key that is normally passed to Gradle (`GE_ACCESS_TOKEN`) which wasn't quite correct. After chatting with Infra, they have provisioned a separate key that's just for API access and added it as the `DV_API_ACCESS` secret.

**Review by mimaison — APPROVED** [review]
LGTM

**Comment by mimaison** [comment]
> After chatting with Infra, they have provisioned a separate key that's just for API access and added it as the DV_API_ACCESS secret.

Is there an INFRA jira?

**Comment by mumrah** [comment]
> Is there an INFRA jira?

No, it happened via the ASF Slack.

**Pull request merged**
