### PR TITLE
KAFKA-12694 Avoid schema mismatch DataException when validating default values

### PR DESCRIPTION
**Pull request by Naros**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Naros** [comment]
@C0urante @rhauch , could either of you review this to see if its acceptable?

**Comment by C0urante** [comment]
Hmm... I'm wondering if this might break existing setups. Since the `SchemaBuilder` class does implement the `Schema` interface, it's currently possible to do something like this:

```java
import org.apache.kafka.connect.data.Schema;
import org.apache.kafka.connect.data.SchemaBuilder;
import org.apache.kafka.connect.data.Struct;

SchemaBuilder builder = SchemaBuilder.struct()
    .field("f1", Schema.BOOLEAN_SCHEMA);

Struct defaultValue = new Struct(builder);
defaultValue.put("f1", true);

Schema schema = builder.defaultValue(defaultValue).build();
```

Validation currently uses the equality method of the `Struct`'s schema: https://github.com/apache/kafka/blob/87b24025cedf08c550a180819b2a5a2dbb75f020/connect/api/src/main/java/org/apache/kafka/connect/data/ConnectSchema.java#L247
which in this case is a `SchemaBuilder` instance that doesn't have an overridden `equals` method, so I think the change proposed here might cause the above example to start to fail.

A naive solution could be to modify the validation to be something like `if (!schema.equals(struct.schema()))` but that may introduce other edge cases. Can you provide a brief example of what sort of connector code ran into this bug in the first place? That might help guide the path forward.

**Comment by hjwalt** [comment]
I encountered this same problem with debezium postgresql connector, where when the connector is set up with precise decimal handling, will use a struct for its numeric value. When a default value is present, the connector fails.

[Here](https://issues.redhat.com/browse/DBZ-3816) are the details I provided to Debezium team.

**Comment by gunnarmorling** [comment]
Hey @C0urante,

```
Struct defaultValue = new Struct(builder);
```

Initializing a `Struct` with a builder rather than a `Schema` seems to be an odd thing to do, no? Here's an example for triggering the exception we ran into, without the proposed change:

```java
SchemaBuilder builder = SchemaBuilder.struct()
    .field("f1", Schema.BOOLEAN_SCHEMA);

Struct defaultValue = new Struct(builder.build()); // the Struct receives a schema, not a builder
defaultValue.put("f1", true);

builder.defaultValue(defaultValue)
     .build();
```

I think ultimately this exposes sort of a gap in the KC schema API, as there's a recursive relationship between struct and schema in the default value case. The suggested change should improve the situation though for the IMO more common case where a `Struct` is initialized with a `Schema` rather than a `SchemaBuilder`.

@C0urante, @rhauch, any thoughts?

**Comment by C0urante** [comment]
Hey Gunnar! Sorry for the delay.

> Initializing a Struct with a builder rather than a Schema seems to be an odd thing to do, no?

Indeed it is rather odd, but it's still possible at the moment and I've definitely seen it in use (intentionally or otherwise...) in at least one fairly large and popular code base. If we can avoid breaking projects that use this pattern (strange as it is) I think that'd be best.

I haven't spent too much time thinking about a clean solution but it's at least possible to satisfy both cases with the following:
- The change proposed in this PR
- The change I proposed above where the order of schemas in the comparison in `ConnectSchema::validateValue` is reversed
- The `ConnectSchema::equals` method is altered to accept any `Schema` instance and only operate on the public methods exposed by the `Schema` interface instead of internal variables for comparison of the schemas' fields, key schema, and value schema

I've verified this locally with the following two test cases:

```java
    @Test
    public void testDefaultValueStructSchema() {
        SchemaBuilder builder = SchemaBuilder.struct()
            .field("f1", Schema.BOOLEAN_SCHEMA);

        Struct defaultValue = new Struct(builder.build()); // the Struct receives a schema, not a builder
        defaultValue.put("f1", true);

        builder.defaultValue(defaultValue)
            .build();
    }

    @Test
    public void testDefaultValueStructSchemaBuilder() {
        SchemaBuilder builder = SchemaBuilder.struct()
            .field("f1", Schema.BOOLEAN_SCHEMA);

        Struct defaultValue = new Struct(builder);
        defaultValue.put("f1", true);

        builder.defaultValue(defaultValue).build();
    }
```

This would be fairly involved for such a small bug so hopefully there's something less invasive out there, but at least it's possible to favor one use case without compromising the other.

As an alternative, could the connector use the `SchemaBuilder` when instantiating the `Struct` object, instead of calling `build` and using a `ConnectSchema`?

**Comment by urbandan** [comment]
I would propose a 4th option as well: changing the ConnectSchema#validateValue method to use a different logic for Struct default values:
1. Use the Schema methods
2. Ignore optional and default value

The benefit would be that it wouldn't change the existing equals logic, existing code utilizing SchemaBuilder would keep working, and it would fix the ambiguity around optionality and default being part of the schema check (while in reality, they should belong to the field, and not the schema).

I have a working change with this 4th option, please  let me know if this logic is acceptable, and I'll submit a PR.

**Comment by C0urante** [comment]
@urbandan I don't think I follow what you mean by "Use the Schema methods"; it might be easier to illustrate with a code snippet?

I'm not really in favor of removing the validation for optional and default values. It's important for values to adhere to their schemas and may cause some headaches downstream if we don't make an effort to ensure that.

**Comment by urbandan** [comment]
@C0urante I was thinking of something similar to the ConnectSchema#equals, but only expecting Schema instances, and using the methods instead of the fields:
```
public static boolean structEffectiveEquals(Schema schema, Schema other) {
        if (schema.type() != Type.STRUCT || other.type() != Type.STRUCT) {
            throw new DataException("Only struct schemas can be effectively compared");
        }
        boolean result = Objects.equals(schema.version(), other.version()) &&
                Objects.equals(schema.name(), other.name()) &&
                Objects.equals(schema.doc(), other.doc()) &&
                Objects.equals(schema.fields(), other.fields()) &&
                Objects.equals(schema.parameters(), other.parameters());
        if (!result) {
            return false;
        }
        if (schema.type() == Type.MAP) {
            if (!Objects.equals(schema.keySchema(), other.keySchema())) {
                return false;
            }
        }
        if (schema.type() == Type.MAP || schema.type() == Type.ARRAY) {
            return Objects.equals(schema.valueSchema(), other.valueSchema());
        }
        return true;
    }
```
I understand that skipping optional field might be wrong (maybe it should be added in this logic as well), But at the same time, removing the cycle from the SchemaBuilder->default->Struct->ConnectSchema would be important here. I think that having a SchemaBuilder instance referenced by a Struct is going to lead to weird and unexpected issues with this API.

Alternatively, what if we introduce a schemaless StructBuilder to eliminate the cycle? The SchemaBuilder and ConnectSchema can be changed to accept a StructBuilder for the default value of a struct type. Then, ConnectSchema#defaultValue would instantiate a proper Struct with the data provided by the StructBuilder, and the schema set as ConnectSchema itself.
We can deprecate the old defaultValue methods, and support both for a while.

**Comment by C0urante** [comment]
Hi @urbandan, thanks for clarifying the point about using `Schema` methods. Agreed that this would be helpful.

I think we should try to keep validation of optionality if possible, and right now I don't see a case where this really breaks things. It seems like if we tweak `ConnectSchema::equals` to use the `Schema` interface methods, that should be sufficient to retain this validation without too much work?

I'd rather not change the API surface here since that would require a KIP and manual action on the part of developers in order to address what is ultimately a bug in the current API.

**Comment by urbandan** [comment]
@C0urante I'm also hesitant to change the API, but I think this part of the API is broken. If we tweak ConnectSchema::equals to use the Schema interface methods, then setting the default value on the SchemaBuilder will work, but then Struct::equals will stop working on default values.
Assume that ConnectSchema::equals uses the Schema methods, and we write this code:

```
SchemaBuilder builder = SchemaBuilder.struct()
    .field("f1", Schema.BOOLEAN_SCHEMA);
Struct defaultValue = new Struct(builder);
defaultValue.put("f1", true);

Schema finalSchema = builder.defaultValue(defaultValue).build();
Struct anotherValue = new Struct(finalSchema);
anotherValue.put("f1", true);

assertEquals(defaultValue, anotherValue);
assertEquals(anotherValue, defaultValue);
```

The first assert fails (defaultValue has a SchemaBuilder instance as the schema, which doesn't have an equals override, so defaultValue.schema.equals(anotherValue.schema) is false).
The second assert never exits, it's infinite recursion (anotherValue has a ConnectSchema instance as the schema, which checks the default value for equality, which then checks the schema equality, and so on).

To me, the tweak doesn't seem like a proper fix.

**Comment by C0urante** [comment]
@urbandan I've given the "tweak" fix (i.e., altering `ConnectSchema::equals` to use interface methods and accept any `Schema` instance during equality checking) a shot locally and, although a small additional change is necessary for `assertEquals(defaultValue, anotherValue)` to pass, there was no infinite loop during `assertEquals(anotherValue, defaultValue)` (which I suspect boiled down to the fact that, eventually, we performed an equality check for two schemas that were referentially equal and thus were able to short-circuit the rest of the `equals` method).

My `ConnectSchema::equals` method looked like this:

```java
public class ConnectSchema {
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Schema)) return false;
        Schema schema = (Schema) o;
        boolean matches = Objects.equals(this.isOptional(), schema.isOptional()) &&
                Objects.equals(this.version(), schema.version()) &&
                Objects.equals(this.name(), schema.name()) &&
                Objects.equals(this.doc(), schema.doc()) &&
                Objects.equals(this.type(), schema.type()) &&
                Objects.equals(this.parameters(), schema.parameters()) &&
                Objects.deepEquals(this.defaultValue(), schema.defaultValue());
        if (!matches)
            return false;

        switch (type) {
            case ARRAY:
                return Objects.equals(this.valueSchema(), schema.valueSchema());
            case MAP:
                return Objects.equals(this.keySchema(), schema.keySchema())
                        && Objects.equals(this.valueSchema(), schema.valueSchema());
            case STRUCT:
                return Objects.equals(this.fields, schema.fields());
            default:
                return true;
        }
    }
}
```

And the only additional change that was necessary to make `assertEquals(defaultValue, anotherValue)` pass was implement `SchemaBuilder::equals`:

```java
public class SchemaBuilder {
    @Override
    public boolean equals(Object o) {
        return this == o || build().equals(o);
    }

    @Override
    public int hashCode() {
        return build().hashCode();
    }
}
```

**Comment by urbandan** [comment]
@C0urante Yes, you are right about the short-circuit, but it is caused by the defaultValue ref equals. Which means that my previous code works with your latest proposal, but this one doesn't (infinite loop):

```
SchemaBuilder builder1 = SchemaBuilder.struct()
    .field("f1", Schema.BOOLEAN_SCHEMA);
Struct defaultValue1 = new Struct(builder);
defaultValue1.put("f1", true);

SchemaBuilder builder2 = SchemaBuilder.struct()
    .field("f1", Schema.BOOLEAN_SCHEMA);
Struct defaultValue2 = new Struct(builder);
defaultValue2.put("f1", true);

assertEquals(builder1, builder2);
```

**Comment by C0urante** [comment]
Ah thanks @urbandan, that helps. It's worth noting that the latest example test case is probably missing calls to actually set the default value for the schema builder instances? (Things pass without those.)

This has me thinking more and more about KAFKA-3910, which deals with the lack of support for recursive schemas in Connect. IMO this is a deficiency not in the API we provide, but in the implementation. And if we address that flaw, then we should probably be able to kill two birds with one stone--both the lack of support for recursive schemas, and the current issues with specifying a default value for struct schemas.

I've prototyped a solution that seeks to address both, which can be found on a personal branch here: https://github.com/C0urante/kafka/commit/e4a595c5dc4ee5ab3185fb7603130dcc0773677d

Not only does it pass with [every test case discussed here so far](https://github.com/C0urante/kafka/blob/e4a595c5dc4ee5ab3185fb7603130dcc0773677d/connect/api/src/test/java/org/apache/kafka/connect/data/SchemaBuilderTest.java#L41-L102), it also passes with a [rudimentary test case for recursive structs](https://github.com/C0urante/kafka/blob/e4a595c5dc4ee5ab3185fb7603130dcc0773677d/connect/api/src/test/java/org/apache/kafka/connect/data/SchemaBuilderTest.java#L126-L161), and for [more-involved combinations of comparisons between built and unbuilt schemas that come with default struct values](https://github.com/C0urante/kafka/blob/e4a595c5dc4ee5ab3185fb7603130dcc0773677d/connect/api/src/test/java/org/apache/kafka/connect/data/SchemaBuilderTest.java#L104-L123).

There's at least one `TODO` item in it and we'd certainly want to add more test coverage, but I'm optimistic that this can satisfy everyone's use cases without requiring changes to the Connect API or breaking existing setups.

What do you think?

**Comment by urbandan** [comment]
@C0urante sorry for the mixup in the exaple code, I did miss those setter calls.
Thank you for the info and the code, I will check your solution. This problem does sound like something that cannot be easily fixed as a simple bug.

**Comment by urbandan** [comment]
@C0urante Thanks for the prototype, went through the change and left a few comments. Overall, I think your solution would solve this issue as well. On the other hand, I still think that the current API (even with your solution included) is still ambiguous, and the mix of mutable and immutable data will cause some tricky bugs in dependent code bases.
Still, your solution would be a nice improvement compared to the current situation, and I don't expect any API changes going through anytime soon :)

**Comment by C0urante** [comment]
Opened https://github.com/apache/kafka/pull/13433 to address this (and cyclic schema support)

**Comment by urbandan** [comment]
Thanks a lot @C0urante, will review that one!

**Pull request closed without merging**
