### PR TITLE
KAFKA-2423: Expand scalafmt coverage to core

### PR DESCRIPTION
**Pull request by rchiang**
Change spotless target to find all scala files.

Also submit code changes from the output of "./gradlew spotlessApply".  Build and ran all unit tests.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
It is indeed very large PR.. maybe we should consider splitting it? cc @ijuma @hachikuji

**Comment by hachikuji** [comment]
Did anything change here other than the formatting?

**Comment by ijuma** [comment]
First question is whether there is consensus we want to do this. Backporting to older branches will be much harder and git blame will become less useful.

**Comment by guozhangwang** [comment]
@ijuma @hachikuji yeah that's what I've said in the older PR: `if we think now is the right timing`, plus we agree on the format rules to be applied. If we conclude it is not the good time or not have a consensus it is also fine, and what I'd like to avoid is just silently drop it on the floor.

**Comment by hachikuji** [comment]
This discussion should probably go on the dev list. I'm personally +1 for adding scalastyle, but a bit on the fence about scalafmt. Having some consistency in the code can be a good thing as long as it doesn't interrupt usual flow.

**Comment by rchiang** [comment]
Okay, I've thought about this a little more.  I'll send my discussions to the dev discussion list and we can continue from there.

**Pull request closed without merging**
