### PR TITLE
KAFKA-4035: AclCommand should allow Describe operation on groups

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by harshach** [comment]
@omkreddy is this backward compatible. What happens to the clients that are on older versions are they going to get any auth exceptions

**Comment by omkreddy** [comment]
@harshach AFAIK There are no compatibility issues. Current AclCommand does't support to add Describe operation on Group Resource. This is a valid combination and we are already handling this combination.
https://github.com/omkreddy/kafka/blob/trunk/core/src/main/scala/kafka/server/KafkaApis.scala#L854

**Comment by junrao** [comment]
@omkreddy : Thanks for the patch. LGTM. Could you rebase?

**Comment by omkreddy** [comment]
@junrao rebased the PR.

**Comment by harshach** [comment]
+1

**Comment by harshach** [comment]
Thanks @omkreddy  merged into trunk

**Pull request closed without merging**
