### PR TITLE
KAFKA-17625: Removing explicit ZK test parameterizations

### PR DESCRIPTION
**Pull request by kevin-wu24**
This PR removes ZK test parameterizations from ducktape by: 
* Removing `zk` from `quorum.all_non_upgrade`
* Removing `quorum.zk` from `@matrix` and `@parametrize` annotations
* Changing usages of `quorum.all` to `quorum.all_kraft`
* Deleting `message_format_change_test.py`

The default `metadata_quorum` value still needs to be changed to KRaft rather than ZK, but this will be done in a follow-up PR.
 
This approach was discussed here: https://github.com/apache/kafka/pull/17601#issuecomment-2445457973

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by cmccabe — APPROVED** [review]
LGTM.

Can you do a test run before we commit?

**Review by chia7712 — APPROVED** [review]

**Comment by kirktrue** [comment]
There is some overlap between this PR and #17669. I'll wait until this PR is merged since it's of #17669.

**Comment by kevin-wu24** [comment]
> LGTM.
> 
> Can you do a test run before we commit?

Test run link: https://confluent-open-source-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/trunk/2024-11-03--001.dd014527-7eb8-49c7-9360-d611877e39d7--1730687030--kevin-wu24--remove-ducktape-ZK-parameterizations--296031f65a/report.html

**Comment by cmccabe** [comment]
LGTM, thanks. Committed.

**Pull request merged**
