### PR TITLE
KAFKA-5787: StoreChangelogReader needs to restore partitions that were added post initialization

### PR DESCRIPTION
**Pull request by dguy**
If a task fails during initialization due to a LockException, its changelog partitions are not immediately added to the StoreChangelogReader as the thread doesn't hold the lock. However StoreChangelogReader#restore will be called and it sets the initialized flag. On a subsequent successfull call to initialize the new tasks the partitions are added to the StoreChangelogReader, however as it is already initialized these new partitions will never be restored. So the task would remain in a non-running state forever.

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang backport of https://github.com/apache/kafka/pull/3736

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
0.11.0 branch does not work with Scala 2.12 version.

LGTM.

**Comment by dguy** [comment]
merged to 0.11

**Pull request closed without merging**
