### PR TITLE
KAFKA-12219: Potential race condition in InMemoryKeyValueStore

### PR DESCRIPTION
**Pull request by dongjinleekr**
A simple but serious problem, what I found while working on #8117.

cc/ @ableegoldman @bbejeck @guozhangwang 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by guozhangwang — APPROVED** [review]
LGTM.

**Comment by guozhangwang** [comment]
Re-triggered the unit tests. @dongjinleekr please ping me if they pass, and if not please look if it is related.

**Comment by dongjinleekr** [comment]
@guozhangwang The test failed again. And I just rebased the branch to the latest trunk.

**Comment by guozhangwang** [comment]
Actually it seems JDK8/11 passed. I'm going to merge the PR now.

**Comment by ableegoldman** [comment]
Thanks @dongjinleekr -- looks like this should be cherrypicked back to the 2.7 branch, since that's when the `reverseRange`/`reverseAll` methods were added. Does that sound right?

**Comment by ableegoldman** [comment]
Cherrypicked to 2.7

**Pull request merged**
