### PR TITLE
KAFKA-9165: Fix jersey warnings in Trogdor

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by cmccabe** [comment]
Note that this isn't fixing any functionality, just using a workaround to get rid of a warning message that is confusing to users (and possibly a bug in jersey)

**Review by stanislavkozlovski — APPROVED** [review]
LGTM.

The idiomatic way to solve this, [as recommended by a Jersey developer](https://github.com/eclipse-ee4j/jersey/issues/3700#issuecomment-424596364), is with a new interface which has not been merged since 2018 - https://github.com/eclipse-ee4j/jersey/pull/3820

**Comment by stanislavkozlovski** [comment]
`JDK 11 and Scala 2.13 — FAILURE 11220 tests run, 61 skipped, 0 failed.`
Others passed.

rebuild this please

**Review by mumrah — COMMENTED** [review]
Can we register our resources as classes rather than instances? This might avoid the need to add the two resource binders.

**Comment by cmccabe** [comment]
@mumrah : The issue with registering as classes rather than as instances is that we need to be able to (for example) run integration tests in parallel.  My understanding is that using a class effectively requires a singleton, and singletons are bad.

(Edit: to clarify, Jersey will create a new instance of the provided class by default, but the new instance wouldn't be able to get a reference to the Coordinator / Agent without making the latter a singleton.  That's what I meant by saying that this would make it hard to run tests in parallel, etc.)

**Comment by cmccabe** [comment]
@stanislavkozlovski: thanks for looking into alternate APIs.  Unfortunately, I don't think the one you mentioned will work for us here.  The reason is because the `CoordinatorRestResource` and `AgentRestResource` need to have a reference to the `Coordinator` and the `Agent`, respectively.  Again, it is about avoiding singletons (aka global variables).  Also, of course, the API hasn't been merged into Jersey yet, as you noted. :)

**Comment by mumrah** [comment]
Ok, thanks for the clarification @cmccabe 👍

**Review by mumrah — APPROVED** [review]

**Pull request merged**
