### PR TITLE
Remove Scala procedure syntax

### PR DESCRIPTION
**Pull request by joan38**
This removes the Scala procedure syntax from the codebase as this is deprecated since Scala 2.11:
https://github.com/scala/scala/pull/3076

Let me know your thoughts.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by joan38** [comment]
This is ready to go. I will rebase once I have a first feedback.

**Comment by joan38** [comment]
@guozhangwang @debasishg Any thoughts on this?

**Comment by guozhangwang** [comment]
cc @ijuma for reviews.

**Comment by ijuma** [comment]
Thanks for the PR. I think we eventually want to do something like this, but it's a bit invasive as it makes it harder to backport changes to previous branches and it introduces conflicts to in-progress PRs. It may make sense to discuss the usage of scalafix in the project and which rules we want to apply, etc. There is a JIRA for using scalastyle, but we never took that to completion.

**Comment by joan38** [comment]
Note this is not introducing scalafix (yet). I'm waiting on 0.6 to be released to get some stuff sorted out.
See the similar PR about formatting that introduces Scalafmt: https://github.com/apache/kafka/pull/4965

> makes it harder to backport changes to previous branches and it introduces conflicts to in-progress PRs

Is this a reason strong enough to continue using a deprecated language feature that we will have to remove anyway at some point when it will be completely dropped? Do you have any suggestions on how can we do better?

**Comment by ijuma** [comment]
In this case, the feature itself is harmless and the benefit is small, so it's lower priority than some of the other things we have to do for the upcoming release.

For the scalafmt PR, we probably need to discuss it in the mailing list since it's even more disruptive and people have strong feelings when it comes to stuff like that.

**Comment by joan38** [comment]
@ijuma I see, let's keep this PR open until I manage to add scalafix so that it will add more value like linting and automatic refactoring with other potential rules.

> people have strong feelings when it comes to stuff like that

Indeed this is why Scalafmt would remove these feelings since there would be a rule settled for everyone. Personally I have no preference except consistency across the codebase and the peace of mind of not having to think about that because it will be taken care by a tool.
I will send a message to the mailing list then?

**Pull request closed without merging**
