### PR TITLE
MINOR: corrected unit tests in AbstractConfigTest.java- fixed invalid assertions

### PR DESCRIPTION
**Pull request by sanketfajage**
Corrected unit tests.

### CODE REVIEW

**Comment by ijuma** [comment]
ok to test

**Review by chia7712 — APPROVED** [review]
@sanketfajage Thanks for contribution. LGTM. nit: Could you revise the title to describe what this PR changed?

**Comment by chia7712** [comment]
@sanketfajage Could you rebase code to trigger QA again ( I believe those failed tests are unrelated to you PR. )

**Comment by chia7712** [comment]
@sanketfajage Thanks for your patch. Merge it to trunk.

**Pull request merged**
