### PR TITLE
MINOR: some small style fixes to RoundRobinPartitioner

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by cmccabe** [comment]
* Use `@Override` annotation where appropriate
* Avoid using typecasts where they aren't needed
* Move some variables that are only used in a single test case into that test case
* Make some test fields static and final where appropriate

**Comment by cmccabe** [comment]
retest this please

**Comment by cmccabe** [comment]
retest this please

**Review by gwenshap — APPROVED** [review]
LGTM. Merging.

**Pull request closed without merging**
