### PR TITLE
MINOR: ConsumerGroupCommand should always show partitions in ascending order

### PR DESCRIPTION
**Pull request by huxihx**
Currently, ConsumerGroupCommand shows in ascending order for partitions with active consumer assigned, but failed to do so for partitions without consumer assigned. The behavior should keep same.

### CODE REVIEW

**Comment by huxihx** [comment]
@ijuma Please review this patch. Thanks.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6657/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6642/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by huxihx** [comment]
@ijuma Could you take some time to review this minor patch. Thanks.

**Comment by huxihx** [comment]
@ewencp Could you take some time to review this minor change? Thanks.

**Comment by huxihx** [comment]
@ijuma Sorry to bother you. Could you help review this PR. Thanks.

**Comment by huxihx** [comment]
@guozhangwang Please take some time to review this minor change. Thanks.

**Comment by ijuma** [comment]
@huxihx thanks for your contribution. Some friendly feedback: there's no need to ping committers repeatedly every few days. We receive a lot of contributions and we have to prioritise at times. If there is a reason why a particular PR needs to be reviewed quickly, it's good to share that. Otherwise, it would help if the pings were not so frequent. Thanks!

**Comment by huxihx** [comment]
@ijuma Sorry for the impatience. Feel free to review the patch then :)

**Comment by huxihx** [comment]
@ijuma  Since this PR did not get responded for nearly a month, do you think you could take some time to review it? Thank you.

**Comment by huxihx** [comment]
@ijuma Could you take some time to review this "old" patch? Thanks.

**Comment by huxihx** [comment]
@ijuma Could you help take some time to review this patch? Thanks.

**Comment by huxihx** [comment]
@guozhangwang Please take some time to review this minor change. Thank you!

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/290/

**Pull request closed without merging**
