### PR TITLE
KAFKA-15500: Correct SslPrincipalMapper.java

### PR DESCRIPTION
**Pull request by rykovsi**
Correct this "&" to "&&"

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mimaison — APPROVED** [review]
Good catch! Thanks for the PR

**Comment by divijvaidya** [comment]
Thank you submitting this fix @rykovsi. I was wondering if we could add a unit test in `SslPrincipalMapperTest` that would fail with the bug and pass after this is fixed. It would help us detect such bugs in future.

**Comment by mimaison** [comment]
In this case `&` is treated as logical AND. I think the only difference with `&&` is that `&`  always executes the right side expression even if the left side expression is false. So in this case I'm not sure you can write a test that differentiates `&` and `&&`.

**Comment by divijvaidya** [comment]
> In this case `&` is treated as logical AND. I think the only difference with `&&` is that `&` always executes the right side expression even if the left side expression is false. So in this case I'm not sure you can write a test that differentiates `&` and `&&`.

You are right. I was mistaken in thinking that this is a bug.

**Review by divijvaidya — APPROVED** [review]

**Pull request merged**
