### PR TITLE
KAFKA-2784: swallow exceptions when mirror maker exits.

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by ijuma** [comment]
This needs to be rebased (if it's still relevant).

**Comment by guozhangwang** [comment]
@becketqin Could you rebase?

**Comment by becketqin** [comment]
@guozhangwang Rebased.

**Comment by ijuma** [comment]
@ewencp or @gwenshap, maybe one of you could take a look?

**Comment by gwenshap** [comment]
LGTM

**Pull request closed without merging**
