### PR TITLE
HOTFIX: KAFKA-4245 follow up: remove gradle wrapper, fix file headers so Rat checks pass, and move Travis cluster file into travis directory.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@ijuma @harshach Not sure if it's better to do the incremental cleanup or revert the original commit, but this at least gets us back to a buildable state so other PRs can get through.

**Comment by ijuma** [comment]
@ewencp, thanks for the PR. I think I'd revert the original PR as we really should ensure all system tests are still running and that the renames are really needed before merging it.

I'll defer to you though as you know this area of the code best. If you think we should rather merge this PR, it LGTM.

**Comment by raghavgautam** [comment]
@ewencp  @ijuma Renames are needed to split tests into smaller parts that finish in 50 mins. We will need support from ducktape to be able to run only a subset of tests at a time.

**Comment by ijuma** [comment]
@raghavgautam, my take is that we should make the changes to ducktape instead of the ad-hoc renames. For example, how does someone choose where to add a system test given all these numbered folders? And how do we know if we're going over the 50 minutes threshold? I think these questions need to be answered before the code gets merged as we rely heavily on system tests to maintain Kafka's quality.

**Comment by raghavgautam** [comment]
@ijuma A new should tests should always be added to highest numbered folder of the category. If that crosses 50mins then we need to create a new split. It will become clear when we see that a split is exceeding allotted time. As of now we are not running any systems tests with CI, this will get us started.

We can also get it pushed to 90 mins by requesting travis-ci support.
http://mail-archives.apache.org/mod_mbox/storm-dev/201609.mbox/%3CCAEWm%3DvLCJSGaBh_n5ot4qx3%3DHcZF%2BP6YLK804Vxv9WqORJ5buA%40mail.gmail.com%3E

**Comment by ewencp** [comment]
@raghavgautam Think about how junit test runners work. They can parallelize things but don't require the user to think about how to do it. Also, a number of issues with the current approach: why is 50 minutes the magic number? What if Travis is OK with it and I want faster turnaround time on my builds? Do we have to move all the files around again just to get that? (That actually messes with any regression tracking since the test name changes...) Why couldn't the number of workers be parameterized and independent of the test directories? What about when we add the parallel test runner and test runners that get tests utilizing a smaller # of workers per test might be able to execute their share faster? What about tests that are parameterized a lot and therefore generate a larger number of tests than can possibly complete in 50 minutes (i.e. your granularity is a single test file, so if that exceeds your limit we have to jump through hoops to break it up, even if it's a single test; things like upgrade tests could easily grow to this size over time).

I think everyone agrees with the benefit of having this run more cheaply via docker and in Travis. The point we were trying to make is that this seems to be tackling half of that problem at the wrong level, and a real fix in ducktape doesn't seem particularly hard to implement afaict -- we just need to be able to tell the test runner to run 1/N of the tests. For tests with significant skew in their run times this isn't perfects, but I think extreme skew isn't currently a problem based on one of the recent runs of the tests:

```
run time:   1 minute 26.478 seconds
run time:   1 minute 17.462 seconds
run time:   1 minute 13.152 seconds
run time:   1 minute 11.517 seconds
run time:   3 minutes 22.656 seconds
run time:   4 minutes 3.564 seconds
run time:   2 minutes 17.735 seconds
run time:   2 minutes 56.852 seconds
run time:   2 minutes 1.193 seconds
run time:   1 minute 27.590 seconds
run time:   1 minute 28.929 seconds
run time:   1 minute 21.704 seconds
run time:   1 minute 19.239 seconds
run time:   1 minute 19.475 seconds
run time:   1 minute 8.848 seconds
run time:   1 minute 9.727 seconds
run time:   58.353 seconds
run time:   4 minutes 4.386 seconds
run time:   3 minutes 28.579 seconds
run time:   4 minutes 7.194 seconds
run time:   3 minutes 23.305 seconds
run time:   4 minutes 5.578 seconds
run time:   3 minutes 23.704 seconds
run time:   3 minutes 27.036 seconds
run time:   1 minute 52.993 seconds
run time:   1 minute 54.279 seconds
run time:   3 minutes 33.738 seconds
run time:   2 minutes 41.959 seconds
run time:   2 minutes 46.583 seconds
run time:   2 minutes 48.635 seconds
run time:   2 minutes 34.647 seconds
run time:   2 minutes 36.345 seconds
run time:   3 minutes 19.114 seconds
run time:   3 minutes 7.234 seconds
run time:   2 minutes 59.615 seconds
run time:   2 minutes 44.359 seconds
run time:   3 minutes 12.010 seconds
run time:   2 minutes 54.265 seconds
run time:   2 minutes 50.329 seconds
run time:   2 minutes 25.543 seconds
run time:   2 minutes 21.472 seconds
run time:   2 minutes 45.048 seconds
run time:   2 minutes 33.803 seconds
run time:   2 minutes 25.486 seconds
run time:   2 minutes 12.680 seconds
run time:   3 minutes 17.429 seconds
run time:   2 minutes 51.080 seconds
run time:   1 minute 48.421 seconds
run time:   1 minute 46.060 seconds
run time:   1 minute 48.615 seconds
run time:   1 minute 50.001 seconds
run time:   1 minute 49.252 seconds
run time:   1 minute 50.841 seconds
run time:   1 minute 50.041 seconds
run time:   1 minute 48.096 seconds
run time:   1 minute 49.070 seconds
run time:   1 minute 50.450 seconds
run time:   2 minutes 32.046 seconds
run time:   2 minutes 40.350 seconds
run time:   2 minutes 31.691 seconds
run time:   4 minutes 33.744 seconds
run time:   2 minutes 40.261 seconds
run time:   2 minutes 33.413 seconds
run time:   2 minutes 36.139 seconds
run time:   2 minutes 33.918 seconds
run time:   2 minutes 40.102 seconds
run time:   2 minutes 26.993 seconds
run time:   2 minutes 35.516 seconds
run time:   2 minutes 20.583 seconds
run time:   2 minutes 20.942 seconds
run time:   39.155 seconds
run time:   33.767 seconds
run time:   1 minute 35.288 seconds
run time:   1 minute 26.314 seconds
run time:   7 minutes 16.865 seconds
run time:   6 minutes 45.721 seconds
run time:   45.091 seconds
run time:   36.107 seconds
run time:   44.022 seconds
run time:   32.760 seconds
run time:   4 minutes 57.939 seconds
run time:   4 minutes 49.608 seconds
run time:   4 minutes 41.317 seconds
run time:   5 minutes 12.797 seconds
run time:   6 minutes 13.303 seconds
run time:   5 minutes 53.096 seconds
run time:   5 minutes 32.047 seconds
run time:   5 minutes 1.909 seconds
run time:   5 minutes 52.398 seconds
run time:   5 minutes 47.677 seconds
run time:   5 minutes 56.097 seconds
run time:   5 minutes 51.267 seconds
run time:   5 minutes 29.588 seconds
run time:   5 minutes 30.075 seconds
run time:   4 minutes 25.970 seconds
run time:   3 minutes 59.555 seconds
run time:   3 minutes 59.812 seconds
run time:   3 minutes 21.584 seconds
run time:   3 minutes 54.765 seconds
run time:   3 minutes 30.930 seconds
run time:   3 minutes 33.147 seconds
run time:   2 minutes 51.613 seconds
run time:   2 minutes 55.407 seconds
run time:   2 minutes 44.094 seconds
run time:   2 minutes 36.971 seconds
run time:   2 minutes 17.542 seconds
run time:   2 minutes 59.762 seconds
run time:   2 minutes 35.139 seconds
run time:   2 minutes 27.489 seconds
run time:   2 minutes 13.965 seconds
run time:   4 minutes 21.659 seconds
run time:   3 minutes 18.422 seconds
run time:   3 minutes 57.947 seconds
run time:   2 minutes 51.433 seconds
run time:   3 minutes 1.435 seconds
run time:   2 minutes 30.426 seconds
run time:   3 minutes 0.461 seconds
run time:   2 minutes 13.082 seconds
run time:   4 minutes 24.012 seconds
run time:   4 minutes 28.016 seconds
run time:   4 minutes 37.973 seconds
run time:   5 minutes 15.677 seconds
run time:   4 minutes 55.313 seconds
run time:   4 minutes 14.683 seconds
run time:   1 minute 4.788 seconds
run time:   54.019 seconds
run time:   47.676 seconds
run time:   35.649 seconds
run time:   1 minute 6.269 seconds
run time:   3 minutes 46.375 seconds
run time:   39.454 seconds
run time:   3 minutes 26.591 seconds
run time:   1 minute 6.925 seconds
run time:   1 minute 8.306 seconds
run time:   1 minute 7.225 seconds
run time:   1 minute 49.315 seconds
run time:   1 minute 8.341 seconds
run time:   1 minute 5.927 seconds
run time:   4 minutes 57.674 seconds
run time:   4 minutes 53.961 seconds
run time:   2 minutes 8.771 seconds
run time:   1 minute 19.463 seconds
run time:   1 minute 13.163 seconds
run time:   1 minute 11.615 seconds
run time:   1 minute 14.742 seconds
run time:   1 minute 2.697 seconds
run time:   1 minute 2.896 seconds
run time:   1 minute 3.343 seconds
run time:   30.654 seconds
run time:   31.303 seconds
run time:   30.292 seconds
run time:   1 minute 5.159 seconds
run time:   1 minute 5.071 seconds
run time:   1 minute 3.062 seconds
run time:   1 minute 5.660 seconds
run time:   1 minute 3.915 seconds
run time:   23.293 seconds
run time:   48.826 seconds
run time:   33.216 seconds
run time:   54.188 seconds
run time:   53.678 seconds
run time:   50.347 seconds
run time:   39.377 seconds
run time:   33.001 seconds
run time:   39.404 seconds
run time:   2 minutes 30.910 seconds
run time:   3 minutes 13.247 seconds
run time:   3 minutes 3.950 seconds
run time:   3 minutes 20.105 seconds
run time:   2 minutes 46.542 seconds
run time:   2 minutes 33.847 seconds
run time:   2 minutes 4.769 seconds
run time:   2 minutes 41.445 seconds
run time:   2 minutes 24.158 seconds
run time:   2 minutes 23.049 seconds
run time:   2 minutes 22.113 seconds
run time:   2 minutes 7.447 seconds
run time:   2 minutes 6.671 seconds
run time:   1 minute 47.663 seconds
run time:   1 minute 49.481 seconds
run time:   2 minutes 33.217 seconds
run time:   2 minutes 17.497 seconds
run time:   2 minutes 43.017 seconds
run time:   1 minute 55.640 seconds
run time:   2 minutes 9.047 seconds
run time:   2 minutes 18.682 seconds
run time:   2 minutes 45.342 seconds
run time:   2 minutes 27.309 seconds
run time:   2 minutes 58.701 seconds
run time:   2 minutes 6.613 seconds
run time:   2 minutes 16.261 seconds
run time:   1 minute 20.478 seconds
run time:   1 minute 23.283 seconds
run time:   1 minute 31.832 seconds
run time:   1 minute 36.718 seconds
run time:   1 minute 29.031 seconds
run time:   1 minute 34.799 seconds
run time:   1 minute 35.577 seconds
run time:   1 minute 36.781 seconds
run time:   2 minutes 23.662 seconds
run time:   1 minute 30.640 seconds
run time:   1 minute 32.362 seconds
run time:   1 minute 33.569 seconds
run time:   1 minute 41.230 seconds
run time:   2 minutes 35.585 seconds
run time:   1 minute 14.770 seconds
run time:   1 minute 17.781 seconds
run time:   1 minute 18.566 seconds
run time:   1 minute 21.047 seconds
run time:   2 minutes 4.988 seconds
run time:   1 minute 14.254 seconds
run time:   1 minute 16.412 seconds
run time:   1 minute 16.589 seconds
run time:   1 minute 24.525 seconds
run time:   2 minutes 12.364 seconds
run time:   3 minutes 33.805 seconds
```

However, what it does reveal is that there are some parameterized tests that seem to take longer than others, so a decent breakdown that still has a trivial implementation assuming tests are approximately equal would have to take every 1/Nth test rather than take blocks of 1/N tests.

See [this ducktape PR](https://github.com/confluentinc/ducktape/pull/154) as an example of what I'm suggesting, which would remove all the changes required within the tests themselves and just require adding the `--subset=X --subsets=10` parameters when invoking ducktape, isolating any choices about how Travis runs the tests to the Travis-specific files (although we'd still be hard coding the choice of 10 test runners/Travis env matrix parameters into those files).

**Comment by ijuma** [comment]
Your suggested ducktape change sounds good to me @ewencp.

**Comment by harshach** [comment]
@raghavgautam @ewencp @ijuma trying to merge the conversations from here https://github.com/apache/kafka/pull/2064 . My bad on merging the gradlew script. We should add this to .gitignore.

1.  I think we are good with the changes proposed to ducktape. Can you merge this in?
2. @raghavgautam will post a new PR to use the changes proposed with ducktape PR.

Once the @raghavgautam PRs ready with the changes proposed here . I think that can be merged in right?

**Comment by ijuma** [comment]
So, I think it would be better to revert the original commit because it will make it clearer in the history that the renames were not intended. We can then do a PR that takes advantage of the ducktape changes. If we do incremental updates, it will be less clear to people reading the history.

Either way, we need to merge this PR or revert the original commit urgently because people are currently blocked due to the RAT failures.

**Comment by ijuma** [comment]
I filed https://github.com/apache/kafka/pull/2187 as an alternative to this PR. Because local builds are failing for several days, either this or that need to be merged today. I'll wait for the West Coast to wake up though.

**Comment by ewencp** [comment]
I went ahead and merged https://github.com/apache/kafka/pull/2187 to revert this for now so we can unblock folks from getting stuff committed to trunk. I'm going to close this PR. @raghavgautam Can you use that patch as a base and file a follow up to address some of those issues? There are other ducktape related changes I'm going to try to get merged in with a new release of ducktape. I'd like to also continue following up on our discussion about how best split up tests in that ducktape PR.

**Pull request closed without merging**
