### PR TITLE
MINOR:Updated Rabobank description

### PR DESCRIPTION
**Pull request by manjuapu**
@dguy Please review

### CODE REVIEW

**Comment by dguy** [comment]
hi @manjuapu, can you rebase to resolve the conflict?

**Comment by manjuapu** [comment]
@dguy resolved conflicts

**Comment by dguy** [comment]
Thanks @manjuapu, LGTM

**Comment by dguy** [comment]
Hi @manjuapu, i merged to trunk, but i couldn't cherry-pick to 0.11.0 due to conflicts that i wasn't sure how to resolve. I think the image for new york times may have a different name. Could you please raise a PR against 0.11.0? Thanks

**Pull request closed without merging**
