### PR TITLE
MINOR: Clean up in DeleteConsumerGroupTest even if test fails

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by rajinisivaram** [comment]
@ijuma Can you take a look, please? Thank you...

**Comment by ijuma** [comment]
LGTM, thanks.

**Comment by rajinisivaram** [comment]
@ijuma Thank you for the review, merging to trunk.

**Comment by rajinisivaram** [comment]
@ijuma Should I merge to 0.11.0 as well? It is an issue only if the test fails, so perhaps not necessary?

**Comment by ijuma** [comment]
Since this is completely safe, it's OK to backport to 0.11.0 as well.

**Comment by rajinisivaram** [comment]
@ijuma Thanks, merging to both...

**Pull request closed without merging**
