### PR TITLE
MINOR: Fix DSL typo in streams docs

### PR DESCRIPTION
**Pull request by milindmantri**
Minor typo.

### CODE REVIEW

**Comment by milindmantri** [comment]
cc: @bbejeck

**Review by cadonna — APPROVED** [review]
Thanks for the PR, @milindmantri !

LGTM!

Could you open a PR with the same change against https://github.com/apache/kafka-site in https://github.com/apache/kafka-site/blob/322c407ca9786962480d35ce3b9fe58c8e30f8aa/32/streams/developer-guide/dsl-topology-naming.html so that the AK website is updated before the next release?

**Comment by milindmantri** [comment]
> Thanks for the PR, @milindmantri !
> 
> LGTM!
> 
> Could you open a PR with the same change against https://github.com/apache/kafka-site in https://github.com/apache/kafka-site/blob/322c407ca9786962480d35ce3b9fe58c8e30f8aa/32/streams/developer-guide/dsl-topology-naming.html so that the AK website is updated before the next release?

Indeed. Will do :)

**Comment by milindmantri** [comment]
@cadonna, thanks for the review!

I'm thinking if it is required to duplicate changes in both places, is it possible to automate this? What would it take to maintain consistency across?

I can work on it if it can save some work for any docs related changes. 
I may be missing some pointers on the docs change related process here, sorry for that.

**Comment by cadonna** [comment]
The issue is that some doc changes are specific to the next release and should only exist in apache/kafka until the release is released. During the release those changes are then copied to apache/kafka-site and consequently shown on the AK webiste. Other changes -- like typos -- can immediately go to both repos because they do not depend on the release.

**Comment by milindmantri** [comment]
@cadonna, I looked into this. My initial idea was that adding a `docs-typo`-like label to a PR would trigger (after merge) a workflow/action on `kafka-site` that creates a PR there. I'm not sure about the directory mapping from `apache/kafka` to `apache/kafka-site`, but this can be explored.

Does this resonate with you? Can you think of another way or how this can be improved?

Is this even worth exploring further, considering the number/rate of PRs that are for docs related typos?

**Comment by cadonna** [comment]
Thanks for the idea!

To get more information about the directory mapping you can consult the release process wiki: https://cwiki.apache.org/confluence/display/KAFKA/Release+Process . There are two parts that describe how docs are released, one is section "Website update process" and the other is the item "Update the website:" under section "After the vote passes".

If you have tested your idea, feel free to propose it on the dev mailing list.

**Pull request merged**
