### PR TITLE
MINOR Enable transaction system tests for KRaft in 3.0

### PR DESCRIPTION
**Pull request by mumrah**

### CODE REVIEW

**Comment by mumrah** [comment]
http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2021-07-30--001.system-test-kafka-branch-builder--1627678032--mumrah--3.0-reenable-transaction-system-test--e3e41966f/report.html

```
====================================================================================================
SESSION REPORT (ALL TESTS)
ducktape version: 0.8.8
session_id:       2021-07-30--001
run time:         63 minutes 52.509 seconds
tests run:        96
passed:           96
failed:           0
ignored:          0
====================================================================================================
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 46.003 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 47.281 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 1.223 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 41.791 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 44.978 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 34.124 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 33.833 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 38.241 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 40.300 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 38.104 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 41.586 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 44.409 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 22.630 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 21.230 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 28.701 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 27.307 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 42.780 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 41.547 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 44.827 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 34.438 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 34.883 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 27.595 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 29.980 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 35.665 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 17.905 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 47.290 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 26.216 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 19.159 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 27.114 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 21.286 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 18.688 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 14.771 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 45.658 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 24.870 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 48.948 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 43.362 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 49.662 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 36.899 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 31.130 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 42.058 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 35.698 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 44.421 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 42.003 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 44.789 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 23.806 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 22.250 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 22.556 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 28.802 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 43.849 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 40.997 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 42.259 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 42.997 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 35.313 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 25.756 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 33.486 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 25.749 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   3 minutes 4.643 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 12.901 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   3 minutes 9.839 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 43.734 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 25.982 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 59.332 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 6.974 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 25.061 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 55.758 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 48.091 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 54.388 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 43.944 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 52.581 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 34.309 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 36.129 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 44.279 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 36.858 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 35.463 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 46.130 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 46.046 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 21.907 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   1 minute 26.274 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 22.790 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=clean_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 27.811 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 46.707 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 41.467 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 48.875 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 45.626 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 38.682 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 26.457 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 35.561 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=brokers.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 29.737 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 23.271 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 23.205 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 44.374 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=False.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   2 minutes 16.620 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 21.253 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=REMOTE_KRAFT
status:     PASS
run time:   1 minute 23.467 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=False.metadata_quorum=ZK
status:     PASS
run time:   2 minutes 8.894 seconds
----------------------------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.transactions_test.TransactionsTest.test_transactions.failure_mode=hard_bounce.bounce_target=clients.check_order=True.use_group_metadata=True.metadata_quorum=ZK
status:     PASS
run time:   1 minute 28.287 seconds
----------------------------------------------------------------------------------------------------
```

**Comment by rondagostino** [comment]
There are other tests we disabled when we didn't have transaction/idempotent producer support in KRaft.  Do we want to enable them here?

In `replication_test.py`, the first test at the top, where `enable_idempotence` is True:
```
    @cluster(num_nodes=7)
    @matrix(failure_mode=["clean_shutdown", "hard_shutdown", "clean_bounce", "hard_bounce"],
            broker_type=["leader"],
            security_protocol=["PLAINTEXT"],
            enable_idempotence=[True])
```

In `streams_smoke_test.py`, the exactly-once tests:
```
    @matrix(processing_guarantee=['exactly_once', 'exactly_once_v2'], crash=[True, False])
```

In `produce_bench_test.py`, the transaction test at the end:
```
    @cluster(num_nodes=8)
    def test_produce_bench_transactions(self, metadata_quorum=quorum.zk):
```


In `group_mode_transactions_test.py`:
```
    @cluster(num_nodes=10)
    @matrix(failure_mode=["hard_bounce", "clean_bounce"],
            bounce_target=["brokers", "clients"])
    def test_transactions(self, failure_mode, bounce_target, metadata_quorum=quorum.zk):
```

**Review by hachikuji — APPROVED** [review]
LGTM. I agree it would be good to enable the tests that Ron mentioned as well. I'll leave it to you to decide whether to do that here or in a separate patch.

**Comment by mumrah** [comment]
Opening a follow-on PR for the additional tests mentioned by @rondagostino

**Pull request merged**
