### PR TITLE
KAFKA-9589: Fixed bug in V2 log validator tests

### PR DESCRIPTION
**Pull request by leonardge**
In this PR, we fixed a test that is written but not ran.
JIRA here: https://issues.apache.org/jira/browse/KAFKA-9589

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
ok to test

**Comment by leonardge** [comment]
Why is the CI failing?

**Comment by stanislavkozlovski** [comment]
JDK 8 failed with
```
06:01:27 #
06:01:27 # There is insufficient memory for the Java Runtime Environment to continue.
06:01:27 # Cannot create GC thread. Out of system resources.
```

May be an intermittent issue.

retest this please

**Comment by leonardge** [comment]
retest this please

**Comment by leonardge** [comment]
Hi @ijuma it will be great if you can re start the tests. Thanks!

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
retest this please

**Comment by leonardge** [comment]
The tests that are failing doesn't seem to be relevant to my change which are the following:
- kafka.api.TransactionsTest.testBumpTransactionalEpoch
- org.apache.kafka.streams.integration.QueryableStateIntegrationTest.shouldAllowConcurrentAccesses
- kafka.integration.MetricsDuringTopicCreationDeletionTest.testMetricsDuringTopicCreateDelete

**Comment by leonardge** [comment]
QueryableStateIntegrationTest.shouldAllowConcurrentAccesses JIRA:
https://issues.apache.org/jira/browse/KAFKA-9798

MetricsDuringTopicCreationDeletionTest.testMetricsDuringTopicCreateDelete JIRA:
https://issues.apache.org/jira/browse/KAFKA-8706

@ijuma It will be great if you can provide me some pointers on what should I do in this case? Thanks for your help!

**Comment by leonardge** [comment]
Hi @ijuma @hachikuji , it will be nice if you can take a look at this PR.

**Comment by ijuma** [comment]
retest this please

**Review by ijuma — APPROVED** [review]
LGTM

**Pull request merged**
