### PR TITLE
MINOR: fix @link tag in javadoc

### PR DESCRIPTION
**Pull request by tang7526**
fix warning: @link: reference not found

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@tang7526 thanks for your patch. Could you fix other docs error also?

```
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/kstream/Joined.scala:42: warning: Could not find any member to link for "Serde".
  /**
  ^
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/kstream/Joined.scala:24: warning: Could not find any member to link for "org.apache.kafka.streams.kstream.Joined".
  /**
  ^
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/kstream/Joined.scala:24: warning: Could not find any member to link for "Serde".
  /**
  ^
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/kstream/Grouped.scala:37: warning: Could not find any member to link for "Serde".
  /**
  ^
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/kstream/Grouped.scala:24: warning: Could not find any member to link for "Serde".
  /**
  ^
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/kstream/Consumed.scala:68: warning: Could not find any member to link for "Topology.AutoOffsetReset".
  /**
  ^
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/kstream/Consumed.scala:55: warning: Could not find any member to link for "TimestampExtractor".
  /**
  ^
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/kstream/Consumed.scala:45: warning: Could not find any member to link for "Serde".
  /**
  ^
/home/chia7712/kafka/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala/StreamsBuilder.scala:157: warning: Could not find any member to link for "org.apache.kafka.streams.errors.TopologyException".
  /**
  ^
44 warnings

```

**Comment by chia7712** [comment]
@tang7526 You have to add (java) streams module to streams-scala docs so it can find the class/methods reference.

```
  javadoc {
+    include "**/org/apache/kafka/streams/**"
    include "**/org/apache/kafka/streams/scala/**"
  }
```

**Comment by chia7712** [comment]
@tang7526 Could you revert the scald docs changes? The changes of Javadocs LGTM

**Comment by tang7526** [comment]
> @tang7526 Could you revert the scald docs changes? The changes of Javadocs LGTM

Done

**Comment by chia7712** [comment]
@tang7526 How about using import for this issue? Other references in Javadocs use import also.

**Comment by tang7526** [comment]
> @tang7526 How about using import for this issue? Other references in Javadocs use import also.
Done

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
