### PR TITLE
KAFKA-13917: Avoid calling lookupCoordinator() in tight loop

### PR DESCRIPTION
**Pull request by viktorsomogyi**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by viktorsomogyi** [comment]
@mimaison would you please review this short change if you get some time? (the tests seem to be flaky)

**Review by divijvaidya — APPROVED** [review]
LGTM!

**Comment by viktorsomogyi** [comment]
@hachikuji would you please review this small PR?

**Review by akatona84 — APPROVED** [review]

**Review by showuon — APPROVED** [review]
LGTM! Thanks.

**Comment by showuon** [comment]
Failed tests are unrelated:
```
    Build / JDK 11 and Scala 2.13 / org.apache.kafka.controller.QuorumControllerTest.testConfigurationOperations()
    Build / JDK 17 and Scala 2.13 / kafka.admin.TopicCommandIntegrationTest.testDescribeAtMinIsrPartitions(String).quorum=kraft
    Build / JDK 17 and Scala 2.13 / kafka.controller.ControllerIntegrationTest.testPartitionReassignmentToBrokerWithOfflineLogDir()
```

**Comment by ijuma** [comment]
Do we need to backport this? Also cc @guozhangwang @dajac since this code has gone through a few iterations.

**Comment by showuon** [comment]
+1 to backport this change to 3.2. Let me know if necessary. Thanks.

**Pull request merged**
