### PR TITLE
MINOR: Enable testUpdateFeaturesWithForwarding

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
This test was removed in #11667 since UpdateFeatures is not properly handled in KRaft mode, now we can bring it back since UpdateFeatures is properly handled after #12036.

*Summary of testing strategy (including rationale)*
No

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
ping @mumrah

**Comment by divijvaidya** [comment]
Looks good to me!

**Review by divijvaidya — APPROVED** [review]

**Review by showuon — APPROVED** [review]
LGTM

**Comment by showuon** [comment]
@dengziming , could you rebase this branch to the latest trunk branch? I'd like to check the test result. Thanks.

**Comment by dengziming** [comment]
> could you rebase this branch to the latest trunk branch? I'd like to check the test result. Thanks.

Thank you @showuon , I have rebased this PR onto trunk.

**Comment by showuon** [comment]
Let's wait for the test results :)

**Comment by showuon** [comment]
Failed test is unrelated.
```
Build / JDK 11 and Scala 2.13 / org.apache.kafka.connect.integration.ExactlyOnceSourceIntegrationTest.testConnectorBoundary
```

**Pull request merged**
