### PR TITLE
MINOR: Fix flaky test shouldQuerySpecificActivePartitionStores

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @vvcephei

**Review by guozhangwang — APPROVED** [review]
Did a quick check. LGTM.

**Comment by guozhangwang** [comment]
@cadonna LMK if we can cherry-pick this one to 2.7 immediately or should we wait for#9681

**Comment by cadonna** [comment]
@guozhangwang Do you want me to open a PR to cherry-pick #9681 to 2.7 or do you want you cherry-pick it directly to 2.7?

**Comment by guozhangwang** [comment]
Cherry-picked to 2.7

**Pull request merged**
