### PR TITLE
MINOR: improve license header check by providing head file instead of (prefix) header regex

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Checking license header with regex prefix is weak. It is better to check the full header via a given header file.

**Comment by ewencp** [comment]
@mjsax In principle, seems like a fair change. A couple of thoughts:

1. Is there a significant benefit to this? It seems the copyrights that it standardized mostly just had slight variants that aren't all that significant -- mostly just longer line widths. These changes admittedly don't affect git history in any significant way since they are just copyrights, but it's still a huge change (tied with some actual code changes as described in the next item).
2. We have quite a few unrelated changes in imports in the patch. Normally I wouldn't worry about these since IDEs do this automatically and the scope is usually pretty limited, but this touches a *lot* of files. I think it's fine to change it, I'm primarily worried about how this will end up impacting a bunch of other in-flight PRs.
3. If we merge this, maybe we should give folks a heads up on the -dev list? IDE settings are probably how we got the 3 or 4 different variants of the header already.

**Comment by mjsax** [comment]
1) The point is, that currently only a regex prefix is checked. Thus, a file might contain not the full license header and the build would succeed. After the regex which checks only the first few words matches you can put anything into the header... (it's not about formatting).

For example, this header passed the build:
```
/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * foo bar
 */
```

2) I did not pay attention to import reordering... I can revert those if required.

3) This seems like a good idea -- as the header file is provided by the PR, people can easily c&p into their IDE setting.

**Comment by mjsax** [comment]
@ewencp 
Updated and rebased yesterday. Reverted all import reordering to limit scope to only touch license headers.

**Comment by mjsax** [comment]
@ewencp Rebased again.

**Comment by hachikuji** [comment]
For the sake of argument, I wonder if it would be sufficient to improve the regex. I get the point that users could put arbitrary text below the first line, but it would still have to pass committer review to be checked in. For example, maybe we could add "http://www.apache.org/licenses/LICENSE-2.0" to the regex? 

Also, if we decide this is a good idea, we should probably do the same thing for the scala and python code.

**Comment by mjsax** [comment]
Maybe you could improve the regex. But what's the advantage compared to using the file?

Agreed about Scala and Python -- but maybe a new PR for that?

**Comment by mjsax** [comment]
@ewencp @hachikuji Rebased this.

**Comment by ewencp** [comment]
LGTM

**Comment by guozhangwang** [comment]
Congrats @mjsax !

**Pull request closed without merging**
