### PR TITLE
KAFKA-3754 Add GC log retention policy to limit size of log

### PR DESCRIPTION
**Pull request by rnpridgeon**
Add a default log retention policy to keep GC logs from growing too large

### CODE REVIEW

**Comment by rnpridgeon** [comment]
Changed the settings to 10 files, 100m each since my previous settings were quite small

**Comment by ijuma** [comment]
Thanks for the PR. How were the numbers chosen?

**Comment by rnpridgeon** [comment]
There wasn't exactly a scientific approach taken to get to this value, 1 GB just seemed like a safe size as a default value. It's large enough to cover a relatively large window of time yet small enough to mitigate concerns about disk exhaustion. 

GC logs have been seen to grow at roughly 50MB at day within a moderately utilized production cluster. At this rate 1GB seems a bit much but during times of duress when the jvm is actively performing GC the rate may rise. 

I'm definitely open to any suggestion anyone may have though.

**Comment by cristim** [comment]
In #1652 we also have 1 GB(10x100MB), and the author mentioned that's pretty much a standard also in the Hadoop ecosystem.

I'm not a big fan of it, but storage is cheap nowadays.

It would be nice if rotated logs could be compressed, but it turns out compression is not trivial to do in log4j just yet, unless using some extensions.

**Review by ijuma — APPROVED** [review]
Thanks, LGTM.

**Pull request closed without merging**
