### PR TITLE
MINOR: kafkatest - adding whitelist for interbroker sasl configs

### PR DESCRIPTION
**Pull request by brianbushree**
forgot to include this line in https://github.com/apache/kafka/pull/7018

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rajinisivaram — COMMENTED** [review]
@brianbushree Thanks for the PR. Can we add a method to `ListenerSecurityConfig` and use that rather than duplicate the checks that need to be kept consistent?

**Review by rajinisivaram — APPROVED** [review]
@brianbushree Thanks for the PR, LGTM. Have we run some SASL system tests with these changes? Don't need a full run, but it will be good to run some tests that use SASL listeners.

**Comment by brianbushree** [comment]
@rajinisivaram still need to do some validation on my end. let me run some tests before we merge

**Comment by brianbushree** [comment]
@rajinisivaram the tests seem fine to me ( http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2019-07-19--001.1563561379--brianbushree--interbroker-sasl-fix--4bfb6ff/report.html )

there was one failure but it seems unrelated:
```
[2019-07-19 17:43:07,405] WARN Client session timed out, have not heard from server in 30008ms for sessionid 0x0 (org.apache.zookeeper.ClientCnxn)
Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:259)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:255)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:113)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1833)
	at kafka.admin.TopicCommand$ZookeeperTopicService$.apply(TopicCommand.scala:288)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:54)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
```

**Comment by rajinisivaram** [comment]
@brianbushree Thanks for running the test, merging to trunk.

**Pull request merged**
