### PR TITLE
MINOR: Improve TransactionIndex.sanityCheck() message

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5741/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5755/
Test PASSed (JDK 7 and Scala 2.11).

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by hachikuji** [comment]
Seemed no harm merging this to 0.11.0 as well, so I did so.

**Pull request closed without merging**
