### PR TITLE
HOTFIX: special handling first ever triggered punctuate

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@apovzner Could you check it this fixed your issue?

**Comment by apovzner** [comment]
I see that the first punctuate() is called right away on startup, not after the scheduled interval. Is this an intended behavior.

Otherwise, the code works. I see only very rarely that punctuate() is called about 10 times at the same time. The pattern is normally: first punctuate() is called, and then the next time punctuate() is called, it is called one after another several times. After that, one punctuate() is called every 'interval'. It is not a consistent behavior.

**Comment by apovzner** [comment]
I got it now. If the punctuate() is triggered based on event time, then the behavior I describe above makes sense. 

If the intended behavior is to call punctuate() in the beginning first, not after 'interval', then LGTM.

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
