### PR TITLE
MINOR: Typo in comments makes debug confusing

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
@guozhangwang @dguy this is a silly typo, but confusing to people debugging. Thanks to @xvrl for reporting.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5663/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5677/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by guozhangwang** [comment]
I found this issue a few days ago in https://github.com/apache/kafka/pull/3354/files which has been merged.

**Pull request closed without merging**
