### PR TITLE
MINOR: Remove unused CONSUMER_APIS and PRODUCER_APIS

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji.

**Comment by ewencp** [comment]
LGTM

**Comment by gwenshap** [comment]
I hope @hachikuji can also shed light on what was the intent of those originally. Just curiosity on my part :)

**Comment by ijuma** [comment]
They were added as part of KAFKA-3600 and became unused due to KIP-97.

**Comment by apurvam** [comment]
LGTM!

**Comment by hachikuji** [comment]
One more in `WorkerGroupMember` to remove.

**Comment by hachikuji** [comment]
@gwenshap Before the client compatibility KIP, the idea was to raise an exception whenever the the broker didn't support the set of APIs we needed. So we used these lists to validate the APIs needed by the client when connecting to a new broker. In the client compatibility KIP, the logic was changed to do API version checking lazily (when we first try to use the API). Then we don't need these lists!

**Comment by ijuma** [comment]
I merged @hachikuji's PR as it removed one list that I missed and as a reward for all the reviews he's doing. :)

**Pull request closed without merging**
