### PR TITLE
KAFKA-14091: Leader proactively aborting tasks from lost workers in rebalance in EOS mode

### PR DESCRIPTION
**Pull request by vamossagar12**

### CODE REVIEW

**Comment by vamossagar12** [comment]
@C0urante , I created a draft PR based on the approach I outlined here: https://issues.apache.org/jira/browse/KAFKA-14091?filter=-1#:~:text=added%20a%20comment%20%2D-,06/Mar/23%2012%3A37,-%2D%20edited

I am not very happy with this though. I feel I am exposing too much of state (worker -> herder -> member -> coordinator -> assignor). The assignor ideally doesn't care for the herder but for me to be able to fence out the open transactions from lost tasks, I need herder.

The other approach that I was thinking that could be used is to extend the ExtendedAssignment to include lost tasks? This way, the rebalanceListener in DistributedHerder would have access to the the lostTasks in `onAssigned` method and should be able to kill those transactions. This way, it fits in nicely into the current scheme. But would it be too invasive (i.e need a KIP? 

Let me know what you think :)

**Comment by vamossagar12** [comment]
@yashmayya , @gharris1727 would you also be able to chime on this.
@C0urante bumping this one again :)

**Comment by gharris1727** [comment]
@vamossagar12 I don't think this is the right approach.

1. In the original design, hanging transactions blocking the global offsets topic was considered in detail, and the solution was accepted at the time to be per-connector offsets topics. I think this was in part that the framework couldn't make the right tradeoff of when to abort transactions in a way that was good enough for any use-case.

2. Aborting transactions proactively on losing the task assignment treats every rebalance as a failure scenario, and does not permit the task to perform a clean end-of-lifetime-commit, which is explicitly handled via the (internal) TransactionBoundaryManager::shouldCommitFinalTransaction, and is used in all of the different transaction boundary modes.

3. Fencing zombie source tasks is a very expensive and blocking operation, and it may delay rebalances that otherwise complete nearly instantly. I'm not sure how the cluster would react to assignments taking a significant amount of time to compute, but I don't think it would be more available and better behaved than it is now.

3. This compromises the interface of the IncrementalCooperativeAssignor significantly. Previously, it only had an effect via the return value of performAssignment, and now it would have a side-effect for the (mutable) passed-in Coordinator.

4. This puts a solution to a problem in one implementation of an interface (IncrementalCooperativeAssignor) and not another (EagerAssignor). Since this isn't an Incremental-specific problem, why is the solution only present in incremental mode?

I'm not convinced that this problem needs solving, as users already have an alternative to the global offsets topic.

**Comment by C0urante** [comment]
Thanks @vamossagar12 for the PR and @gharris1727 for the review.

I filed this ticket because, although there is a workaround available right now in the form of per-connector offsets topics, it'd still be nice if we could find a way to prevent hanging transactions on the global offsets topic from blocking worker startup, since that could be a bit of a pain if users are running Connect with tooling to automatically restart suddenly-killed workers.

That said, I share Greg's concerns about the viability of the approach in this PR, and would like to see them addressed before reviewing. I don't have time to help find a better design (which is part of the reason I filed this ticket but did not self-assign it), but maybe you could discuss this with some of your colleagues if you'd like a hand?

**Comment by vamossagar12** [comment]
hi @C0urante , @gharris1727 . Thanks for the comments. As I mentioned in my comment [here](https://github.com/apache/kafka/pull/13376#issuecomment-1485855388), this is not an approach that I want to proceed with myself because of the unnecessary state that is being exposed. 
I had proposed another solution but I wasn't/am not sure if it needs a KIP. Nonetheless, I would take a look.

**Comment by vamossagar12** [comment]
> @vamossagar12 I don't think this is the right approach.

> 1. In the original design, hanging transactions blocking the global offsets topic was considered in detail, and the solution was accepted at the time to be per-connector offsets topics. I think this was in part that the framework couldn't make the right tradeoff of when to abort transactions in a way that was good enough for any use-case.

I agree but then if somebody does still use the global offsets topic, this issue remains for them. I thought it might still be useful to fix this. For example, it automatic topic creation is disabled in some environments/enterprises, so whenever a new connector is created a new offsets topic request needs to raised which could be a hassle at times.
> 2. Aborting transactions proactively on losing the task assignment treats every rebalance as a failure scenario, and does not permit the task to perform a clean end-of-lifetime-commit, which is explicitly handled via the (internal) TransactionBoundaryManager::shouldCommitFinalTransaction, and is used in all of the different transaction boundary modes.

Yeah, in that sense, it's expensive but I have tried to do it only when we detect there are missing workers during a rebalance. So, what you are saying is definitely applicable when workers are coming up and down very frequently.
> 3. Fencing zombie source tasks is a very expensive and blocking operation, and it may delay rebalances that otherwise complete nearly instantly. I'm not sure how the cluster would react to assignments taking a significant amount of time to compute, but I don't think it would be more available and better behaved than it is now.

I see. I am not fully aware of how costly it is, but I feel that's a price we would have to pay at some point when using global offsets topic. Otherwise, there would always be Zombis lingering around.
> 4. This compromises the interface of the IncrementalCooperativeAssignor significantly. Previously, it only had an effect via the return value of performAssignment, and now it would have a side-effect for the (mutable) passed-in Coordinator.

Agreed, plz check my comment [here](https://github.com/apache/kafka/pull/13376#issuecomment-1487939356) 
> 5. This puts a solution to a problem in one implementation of an interface (IncrementalCooperativeAssignor) and not another (EagerAssignor). Since this isn't an Incremental-specific problem, why is the solution only present in incremental mode?
Yeah I had assumed that Incremental is more prevalent and hence thought would try to fix it there first. Can always extend it for Eager.

**Comment by vamossagar12** [comment]
Closing this PR. The ticket is assigned to Sudesh.

**Pull request closed without merging**
