### PR TITLE
MINOR: Fix JavaDocs warnings

### PR DESCRIPTION
**Pull request by mjsax**
Fix JavaDocs Warning:
```
> Task :streams:javadoc
11:19:51 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.12/streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java:158: warning - invalid usage of tag <
11:19:51 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.12/streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java:164: warning - invalid usage of tag <
11:19:51 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.12/streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java:164: warning - invalid usage of tag >
11:19:51 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.12/streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java:169: warning - invalid usage of tag >
11:19:51 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.12/streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java:174: warning - invalid usage of tag >
11:19:51 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.12/streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java:174: warning - invalid usage of tag <
11:19:51 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.12/streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java:105: warning - invalid usage of tag >
11:19:52 7 warnings
```

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman

**Review by bbejeck — APPROVED** [review]
Thanks for the cleanup! LGTM

**Comment by guozhangwang** [comment]
LGTM! Please feel free to merge after jenkins.

**Comment by mjsax** [comment]
Found more in core... \cc @hachikuji

**Comment by mjsax** [comment]
Java11 failed with know flaky test: https://issues.apache.org/jira/browse/KAFKA-7965
Java8 passed.

Retest this please.

**Comment by bbejeck** [comment]
Merged #6435 into trunk

**Pull request merged**
