### PR TITLE
MINOR: Update LinkedIn JVM tuning settings

### PR DESCRIPTION
**Pull request by ijuma**
This is a follow-up as the previous update was missing some changes.

### CODE REVIEW

**Comment by ijuma** [comment]
Data provided by @toddpalino (thanks!). @guozhangwang, can you please review and merge?

**Comment by darionyaphet** [comment]
this JVM turning config is use to JDK 8 ?

**Comment by ijuma** [comment]
@darionyaphet, that's right. The paragraph before the change says:

"LinkedIn is currently running JDK 1.8 u5..."

**Comment by toddpalino** [comment]
LGTM

**Comment by guozhangwang** [comment]
LGTM. Merged to both trunk and 0.9.0.

**Comment by darionyaphet** [comment]
@guozhangwang  Since kafka 0.9 not support JDK 7 ?

**Comment by ijuma** [comment]
@darionyaphet Kafka 0.9 supports JDK 7, there is a paragraph in the Java version section that says:

"If you decide to use the G1 collector (the current default) and you are still on JDK 1.7, make sure you are on u51 or newer"

**Pull request closed without merging**
