### PR TITLE
KAFKA-14093: Use single-worker Connect cluster when testing fenced leader recovery

### PR DESCRIPTION
**Pull request by C0urante**
Largely copied from [Jira](https://issues.apache.org/jira/browse/KAFKA-14093):

The Javadoc for the `testFencedLeaderRecovery` test case calls out that it uses a one-node cluster, and the [check we do](https://github.com/apache/kafka/blob/679e9e0cee67e7d3d2ece204a421ea7da31d73e9/connect/runtime/src/test/java/org/apache/kafka/connect/integration/ExactlyOnceSourceIntegrationTest.java#L493-L494) to make sure that the leader is up and running (and has had a chance to instantiate its transactional producer for the config topic) relies on that fact. However, we don't reduce the cluster size to one in the test, so right now it's running with the default of three workers.

As a result, it's possible that the readiness check we're doing hits a follower worker and passes before the leader has had a chance to finish startup.

These changes fix that issue by ensuring that the test runs with only a single worker. In addition, the transactional producers brought up for testing are given meaningful client IDs so that they can be easily distinguished from the producers brought up by the embedded Connect cluster.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by tombentley — APPROVED** [review]
Thanks @C0urante, this makes sense and this test is passing consistently for me locally.

**Review by mimaison — APPROVED** [review]
LGTM

**Comment by mimaison** [comment]
@jsancio I'm backporting this to 3.3

**Comment by C0urante** [comment]
Thanks guys!

**Pull request merged**
