### PR TITLE
KAFKA-9490: Fix generics for Grouped

### PR DESCRIPTION
**Pull request by mjsax**
Call for review @guozhangwang @vvcephei

### CODE REVIEW

**Review by vvcephei — APPROVED** [review]
Thanks for the quick fix, @mjsax!

**Comment by mjsax** [comment]
Java 11:
```
kafka.api.ConsumerBounceTest.testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup
org.apache.kafka.streams.kstream.internals.KStreamImplTest.shouldSupportTriggerMaterializedWithKTableFromKStream
```

For the second failure, the error is:
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at org.apache.kafka.streams.kstream.internals.KStreamImplTest.lambda$asMap$229(KStreamImplTest.java:2960)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamImplTest.asMap(KStreamImplTest.java:2960)
	at org.apache.kafka.streams.kstream.internals.KStreamImplTest.
```

This is a new test that was merged recently via https://github.com/apache/kafka/pull/7989 (but the build was green; also re-run the test locally and it passed) -- we also have a follow up PR https://github.com/apache/kafka/pull/8027 (in case there is a real issue, we can fix it there -- did not create a ticket for that reason).

Java 8 timed out.

Retest this please.

**Comment by mjsax** [comment]
Java 11:
```
kafka.admin.ReassignPartitionsClusterTest.shouldListReassignmentsTriggeredByZk
kafka.admin.ResetConsumerGroupOffsetTest.testResetOffsetsExportImportPlan
kafka.api.SaslSslConsumerTest.testCoordinatorFailover
```

Java 8:
```
kafka.admin.ResetConsumerGroupOffsetTest.testResetOffsetsAllTopicsAllGroups
kafka.api.SaslOAuthBearerSslEndToEndAuthorizationTest.testProduceConsumeTopicAutoCreateTopicCreateAcl
kafka.api.SslAdminIntegrationTest.testSynchronousAuthorizerAclUpdatesBlockRequestThreads
```

Retest this please.

**Review by andrewchoi5 — APPROVED** [review]

**Comment by mjsax** [comment]
Java 8:
```
org.apache.kafka.clients.admin.KafkaAdminClientTest.testDefaultApiTimeoutOverride
kafka.admin.DescribeConsumerGroupTest.testDescribeGroupMembersWithShortInitializationTimeout
```

Java 11:
```
kafka.admin.DescribeConsumerGroupTest.testDescribeGroupWithShortInitializationTimeout
kafka.admin.ResetConsumerGroupOffsetTest.testResetOffsetsExportImportPlan
```

Every test passed in at least one test run. Merging.

**Pull request merged**
