### PR TITLE
HOTFIX: use .equals to compare HostInfo in StreamsMetadataState

### PR DESCRIPTION
**Pull request by ableegoldman**
Hotfix for patching this in older branches

### CODE REVIEW

**Comment by ableegoldman** [comment]
cc @mjsax

**Comment by mjsax** [comment]
Retest this please.

**Comment by ableegoldman** [comment]
Wow, all tests passed on the first try! cc @mjsax

**Comment by mjsax** [comment]
Merged to `2.5` and cherry-picked to `2.4`.

It's fixed in `trunk` and `2.6` via #8900

**Pull request merged**
