### PR TITLE
HOTFIX: disable flaky system tests

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
\cc @enothereska @ijuma @guozhangwang @dguy @bbejeck

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5933/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5918/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
Is the jenkins failure related?

```
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5918/testReport/junit/org.apache.kafka.streams.integration/QueryableStateIntegrationTest/shouldAllowToQueryAfterThreadDied/
```

**Comment by guozhangwang** [comment]
Also could you point me to the JIRA ticket tracking this flaky test? Do we know / have any theory about its flakiness?

**Comment by guozhangwang** [comment]
And also is it related to this commit? https://github.com/apache/kafka/commit/0046a881d389878bbb673c2591c06fd667923964, if yes do we still need this?

**Comment by mjsax** [comment]
Test failure is not related (I created a new JIRA for the failing test -- happened on many build already: https://issues.apache.org/jira/browse/KAFKA-5566

We don't have a JIRA for the flaky system tests.

It's not related to https://github.com/apache/kafka/commit/0046a881d389878bbb673c2591c06fd667923964 that is about unit tests (not system tests)

**Comment by mjsax** [comment]
Btw: this should also go into `0.11.0` -- it's also flaky there.

**Comment by mjsax** [comment]
Retest this please.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5942/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5927/
Test FAILed (JDK 8 and Scala 2.12).

**Review by enothereska — APPROVED** [review]

**Comment by enothereska** [comment]
@dguy @guozhangwang we need to disable and check. It's failing pretty much every night for a week now.

**Review by dguy — APPROVED** [review]
Thanks @mjsax, LGTM

**Comment by dguy** [comment]
Merged to trunk & cherry-picked to 0.11.0

**Pull request closed without merging**
