### PR TITLE
MINOR: Remove unused compressionType parameter from TestUtils.produceMessages

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@ijuma trivial change to pass compressionType config correctly in TestUtils.produceMessages method.  Currently none of the tests are using compressionType parameter. we can also cleanup by removing unused compressionType parameter.

**Comment by ijuma** [comment]
Thanks for the PR. Hmm, this is a bit odd, has this changed recently?

**Comment by omkreddy** [comment]
I think this was there since old client changes.  Previously TestUtils.sendMessages  method with compressionType was used in old consumer related tests.  This was removed as part of old producer changes, migrated to produceMessages method.

**Comment by ijuma** [comment]
@omkreddy Makes sense. If we never use the parameter, we should probably remove it.

**Comment by omkreddy** [comment]
@ijuma  Removed the unused parameter. Updated the PR.

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
