### PR TITLE
KAFKA-17972: Set all tests inheriting from QuorumTestHarness to KRaft

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by chia7712** [comment]
Out of curiosity, what is the next if we have a zk-only list?

1. migrate the tests to Kraft if the tests are required by Kraft too
2. Remove the tests if the bugs happen in Kraft only (similar to https://github.com/apache/kafka/pull/17670#discussion_r1835131970)

Thanks

**Comment by cmccabe** [comment]
> Out of curiosity, what is the next if we have a zk-only list?

There are some things that don't need to be tested any more, because they're gone. For example, there are a bunch of tests of "topics in deleting state" which can go, because deleting state is gone.

There are probably some tests that need to be migrated to KRaft, but haven't been yet. Depending on how many of them there are, we may need to put a `@Disable` on some of these and create a follow-up JIRA so that we can unblock the broader zk removal effort.

**Comment by cmccabe** [comment]
I split the fix of MetricsTest out to #17744

**Comment by cmccabe** [comment]
Remove `MetadataRequestBetweenDifferentIbpTest.scala` in #17745

**Comment by cmccabe** [comment]
Convert `DescribeLogDirsRequestTest` : #17746

**Comment by cmccabe** [comment]
another fix here https://github.com/apache/kafka/pull/17757

**Comment by cmccabe** [comment]
Fixing `FetchRequestDownConversionConfigTest` here : https://github.com/apache/kafka/pull/17759

**Comment by cmccabe** [comment]
Convert `ConsumerTopicCreationTest`  : https://github.com/apache/kafka/pull/17760/files

**Comment by cmccabe** [comment]
Convert `AddPartitionsToTxnRequestServerTest` https://github.com/apache/kafka/pull/17762

**Comment by cmccabe** [comment]
Created https://github.com/apache/kafka/pull/17765 for fixing the tests inheriting from `RebootstrapTest`

**Comment by cmccabe** [comment]
Convert `RackAwareAutoTopicCreationTest` to KRaft: https://github.com/apache/kafka/pull/17766

**Comment by cmccabe** [comment]
Convert `ProduceRequestTest ` : https://github.com/apache/kafka/pull/17780

**Comment by cmccabe** [comment]
Convert `GssapiAuthenticationTest` : https://github.com/apache/kafka/pull/17786/files

**Comment by cmccabe** [comment]
Convert SaslClientsWithInvalidCredentialsTest.scala to KRaft https://github.com/apache/kafka/pull/17803

**Comment by cmccabe** [comment]
remove `SaslPlainPlaintextConsumerTest.testZkAclsDisabled`: https://github.com/apache/kafka/pull/17902

**Comment by cmccabe** [comment]
For fixing `DynamicBrokerReconfigurationTest`  : https://github.com/apache/kafka/pull/17905

**Comment by cmccabe** [comment]
Remove some ZK tests here https://github.com/apache/kafka/pull/17913/files

**Comment by cmccabe** [comment]
Fix `ConsumerBounceTest` here: https://github.com/apache/kafka/pull/17997

**Comment by cmccabe** [comment]
It looks like isKRaftTest was removed in #18166 , so we no longer need this PR. I'll close it. Thanks, everyone!

**Pull request closed without merging**
