### PR TITLE
KAFKA-3926: Transient test failures -  confirm all expected topics added/removed in createStream…

### PR DESCRIPTION
**Pull request by bbejeck**
…Tasks call versus simply asserting createStreamTasks method called.

### CODE REVIEW

**Comment by bbejeck** [comment]
Updated the test to use the `waitForCondition` method to confirm that all added/removed topics are accounted for in the `StreamThread.createStreamTask` method call.  Previously, the test was only asserting that the `createStreamTask` method was being called.  This could cause transient failures as sometimes there may be more than one call to `createStreamTask` .  Also increased the time limit waiting for the rebalance to occur.

**Comment by guozhangwang** [comment]
The Jenkins failures are due to other issues that we are working on right now.

Maybe we can keep using the default timeout 15 seconds for now? Or do you have any specific reasons to bump them up to 90 seconds?

**Comment by bbejeck** [comment]
> Maybe we can keep using the default timeout 15 seconds for now? Or do you have any specific reasons to bump them up to 90 seconds?

@guozhangwang 

No, I was just being overly conservative/aggressive in trying to prevent transient failures.  I'll set it back to use default of 15 seconds.

**Comment by guozhangwang** [comment]
LGTM and merged to trunk.

**Pull request closed without merging**
