### PR TITLE
MINOR: Upgrade jqwik to version 1.8.3

### PR DESCRIPTION
**Pull request by bmscomp**
This minor pull request consist of upgrading version of `jqwik` library to version `1.8.0` that brings some bug fixing and some enhancements, upgrading the version now will make future upgrades easier 

For breaking changes: 
- We are not using `ArbitraryConfiguratorBase`, so there is no overriding of `configure` method
- We are not using `TypeUsage.canBeAssignedTo(TypeUsage)` 
- No breaking is related to `@Provide` and `@ForAll` usage no Exception `CannotFindArbitraryException` is thrown during tests running
- No usage of `StringArbitrary.repeatChars(0.0)`
- We are not affected by the removal of method `TypeArbitrary.use(Executable)`
- We are not affected by the removal  or methods `ActionChainArbitrary.addAction(action) ` and  `ActionChainArbitrary.addAction(weight, action)`

For more details check the release notes: https://jqwik.net/release-notes.html#180 

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by yashmayya — APPROVED** [review]
LGTM, thanks @bmscomp! @divijvaidya would you be able to take a look?

**Comment by divijvaidya** [comment]
Restarting the build since many tests were failing.

**Comment by yashmayya** [comment]
The previous build had 11 test failures with no new failures and none of the failures were related to this test dependency upgrade - https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-14365/1/tests.

**Comment by mimaison** [comment]
@bmscomp Can you rebase to resolve the conflict? Thanks

**Comment by bmscomp** [comment]
@mimaison  Rebase done and conflicts are resolved

**Comment by mimaison** [comment]
@yashmayya @divijvaidya I'll let you finish the review. Thanks

**Comment by chia7712** [comment]
the last version of `jqwik` is 1.8.3. Maybe we should rebase the code with 1.8.3, and then merge it if there is no related failure.

**Comment by bmscomp** [comment]
@chia7712 Jqwik version is updated to 1.8.3 and conflicts are resolved

**Comment by chia7712** [comment]
```
[2024-03-02T21:51:02.002Z] kafka.api.PlaintextAdminIntegrationTest.testElectPreferredLeaders(String)[2] failed, log available in /home/jenkins/workspace/Kafka_kafka-pr_PR-14365/core/build/reports/testOutput/kafka.api.PlaintextAdminIntegrationTest.testElectPreferredLeaders(String)[2].test.stdout
[2024-03-02T21:51:02.002Z] 
[2024-03-02T21:51:02.002Z] Gradle Test Run :core:test > Gradle Test Executor 94 > PlaintextAdminIntegrationTest > testElectPreferredLeaders(String) > testElectPreferredLeaders(String).quorum=kraft FAILED
[2024-03-02T21:51:02.002Z]     org.opentest4j.AssertionFailedError: Timed out waiting for leader to become Some(0). Last metadata lookup returned leader = Some(1) ==> expected: <true> but was: <false>
[2024-03-02T21:51:02.002Z]         at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
[2024-03-02T21:51:02.002Z]         at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
[2024-03-02T21:51:02.002Z]         at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
[2024-03-02T21:51:02.002Z]         at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
[2024-03-02T21:51:02.002Z]         at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
[2024-03-02T21:51:02.002Z]         at kafka.utils.TestUtils$.waitForLeaderToBecome(TestUtils.scala:2116)
[2024-03-02T21:51:02.002Z]         at kafka.utils.TestUtils$.assertLeader(TestUtils.scala:2079)
[2024-03-02T21:51:02.002Z]         at kafka.api.PlaintextAdminIntegrationTest.changePreferredLeader$1(PlaintextAdminIntegrationTest.scala:1439)
[2024-03-02T21:51:02.002Z]         at kafka.api.PlaintextAdminIntegrationTest.testElectPreferredLeaders(PlaintextAdminIntegrationTest.scala:1501)
```
https://issues.apache.org/jira/browse/KAFKA-8458

```
[2024-03-03T00:18:55.732Z] kafka.server.ReplicaManagerTest.testRemoteFetchExpiresPerSecMetric() failed, log available in /home/jenkins/workspace/Kafka_kafka-pr_PR-14365/core/build/reports/testOutput/kafka.server.ReplicaManagerTest.testRemoteFetchExpiresPerSecMetric().test.stdout
[2024-03-03T00:18:55.732Z] 
[2024-03-03T00:18:55.732Z] Gradle Test Run :core:test > Gradle Test Executor 95 > ReplicaManagerTest > testRemoteFetchExpiresPerSecMetric() FAILED
[2024-03-03T00:18:55.732Z]     org.opentest4j.AssertionFailedError: The ExpiresPerSec value is not incremented. Current value is: 0
[2024-03-03T00:18:55.732Z]         at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
[2024-03-03T00:18:55.732Z]         at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
[2024-03-03T00:18:55.732Z]         at kafka.server.ReplicaManagerTest.testRemoteFetchExpiresPerSecMetric(ReplicaManagerTest.scala:4174)
```
https://issues.apache.org/jira/browse/KAFKA-13530

those failed tests are flaky since there are jira already. Also, they pass on my local. so +1 to this PR and I will merge it tomorrow if there is no objection

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
