### PR TITLE
MINOR: Fix the generation extraction util

### PR DESCRIPTION
**Pull request by guozhangwang**
A previous PR #10149 changed the log context from AbstractCoordinator to ConsumerCoordinator.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@ableegoldman @cadonna

**Review by wcarlson5 — APPROVED** [review]

**Review by mjsax — APPROVED** [review]

**Review by chia7712 — APPROVED** [review]
@guozhangwang Thanks for this fix. +1 

Sorry that I didn't notice this issue :(

**Review by ableegoldman — APPROVED** [review]
Ah, good catch. Thanks for the quick fix

**Comment by guozhangwang** [comment]
> Sorry that I didn't notice this issue :(

No worries!! :)

**Pull request merged**
