### PR TITLE
KAFKA-6640; Improve efficiency of KafkaAdminClient.describeTopics()

### PR DESCRIPTION
**Pull request by lindong28**
Currently in KafkaAdminClient.describeTopics(), for each topic in the request, a complete map of cluster and errors will be constructed for every topic and partition. This unnecessarily increases the complexity of describeTopics() to O(n^2). This patch improves the complexity to O(n).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
cc @cmccabe

**Comment by ijuma** [comment]
Looks like a good find, if this looks good to Colin, I can merge.

**Comment by lindong28** [comment]
@cmccabe Do you have time to review this patch? Thanks

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch.

**Comment by cmccabe** [comment]
LGTM

**Comment by lindong28** [comment]
@hachikuji @cmccabe Thanks for the review!

**Pull request merged**
