### PR TITLE
KAFKA-2514: change default JVM options in kafka-run-class.sh.

### PR DESCRIPTION
**Pull request by omkreddy**
GC is set to G1 collector.

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by ijuma** [comment]
One question: should we be setting lower values for -XX:MaxGCPauseMillis and -XX:InitiatingHeapOccupancyPercent? The Confluent docs recommend "-XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35".

**Comment by omkreddy** [comment]
Yes, we can set them. I will update the PR.

**Comment by junrao** [comment]
LGTM

**Comment by b-goyal** [comment]
GC is set to G1 collector.

**Pull request closed without merging**
