### PR TITLE
KAFKA-2348; Drop support for Scala 2.9

### PR DESCRIPTION
**Pull request by ijuma**
`testAll` passed locally.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by ewencp** [comment]
+1 tested `uploadArchivesAll` too

**Comment by ijuma** [comment]
@gwenshap or @guozhangwang, any chance one of you could merge this? It's a simple change and it has been reviewed by a couple of people.

**Comment by guozhangwang** [comment]
LGTM.

**Comment by b-goyal** [comment]
`testAll` passed locally.

**Pull request closed without merging**
