### PR TITLE
MINOR: fix omitted 'next.' in interactive queries documentation

### PR DESCRIPTION
**Pull request by dongjinleekr**
This is the counterpart of [kafka-site PR](https://github.com/apache/kafka-site/pull/247).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by dongjinleekr** [comment]
Rebased onto the latest trunk + fix duplicated `next`.

Before: `<span class="n">value</span><span class="o">);</span>`
After: `<span class="n">next</span><span class="o">.</span><span class="na">value</span><span class="o">);</span>`

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by guozhangwang** [comment]
Cherry-picked to 2.5 as well.

**Pull request merged**
