### PR TITLE
KAFKA-16640: Replace TestUtils#resource by scala.util.Using

### PR DESCRIPTION
**Pull request by frankvicky**
Check all uses of `TestUtils#resource` and replace with `scala.util.Using`

- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by xvrl** [comment]
it looks like this change is silently suppressing all errors in tests that were updated, since we don't check the resulting Try for failures.

**Comment by jolshan** [comment]
@chia7712 I will file a ticket for this. I just tested by including a assertEquals(1, 2) in a `Using` block and the test still passed.

**Comment by jolshan** [comment]
https://issues.apache.org/jira/browse/KAFKA-18100

**Comment by ijuma** [comment]
> It looks like this change is silently suppressing all errors in tests that were updated, since we don't check the resulting Try for failures.

Ouch! A bunch of tests were broken as a result of this. It's really critical to make sure tests still fail when making updates like this one.

**Comment by frankvicky** [comment]
Oops, I will take a look

**Comment by chia7712** [comment]
Sorry for the trouble. I’ll take over the Jira. Thanks!

**Comment by chia7712** [comment]
#17954 will correct the usage of `Using`.

**Pull request merged**
