### PR TITLE
MINOR: Fix kafkatest/__init__.py to use dev0 instead of SNAPSHOT

### PR DESCRIPTION
**Pull request by lbradstreet**
Fixes the system tests.

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by ijuma** [comment]
@lbradstreet have you verified that the system test passes after this change?

**Comment by lbradstreet** [comment]
Yes. I confirmed via `TC_PATHS="tests/kafkatest/sanity_checks/test_kafka_version.py::KafkaVersionTest" bash tests/docker/run_tests.sh ` now passes, where it previously failed. Thanks for the commit message improvement - I'll use that style in the future.

**Comment by ijuma** [comment]
Thanks.

**Pull request merged**
