### PR TITLE
KAFKA-15206: Fix the flaky RemoteIndexCacheTest.testClose test

### PR DESCRIPTION
**Pull request by kamalcph**
It is possible that the Shutdownable thread never ran in the CI so the test is failing

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kamalcph** [comment]
@divijvaidya @showuon 

Would you please review this minor change?

**Comment by nikramakrishnan** [comment]
Thanks for the change, @kamalcph! Just for my knowledge, why is there a possibility that the Shutdownable thread never ran in the CI for this test?

**Comment by kamalcph** [comment]
> Thanks for the change, @kamalcph! Just for my knowledge, why is there a possibility that the Shutdownable thread never ran in the CI for this test?

Due to resource constraint, `ShutdownableThread#run` might be called later than the `ShutdownableThread#close` method.

**Review by nikramakrishnan — APPROVED** [review]
Thanks, I understand the change now. LGTM!

**Comment by divijvaidya** [comment]
Nice fix @kamalcph! A few questions:
1. Why did we create a new test file. Can't we add the tests to existing `ShutdownableThreadTest` https://github.com/apache/kafka/blob/trunk/core/src/test/scala/unit/kafka/utils/ShutdownableThreadTest.scala ?
2. If the cleaner thread wasn't even started, are our really testing correct behaviour? For example, when we validate that cleaner shouldn't have deleted something, we would happily think that cleaner ran but didn't delete stuff whereas in reality, it may never have run at all. Should we instead add a wait loop in our setup for cache in the test to ensure that cleaner starts running?

**Comment by kamalcph** [comment]
Thanks for the review!

> If the cleaner thread wasn't even started, are our really testing correct behaviour? For example, when we validate that cleaner shouldn't have deleted something, we would happily think that cleaner ran but didn't delete stuff whereas in reality, it may never have run at all. Should we instead add a wait loop in our setup for cache in the test to ensure that cleaner starts running?

The RemoteIndexCache (RIC) and RemoteIndexCacheTest (RICT) are in different packages, so we cannot introduce a new package-private method in the RIC to overwrite it in RICT to ensure that the cleaner-thread started. Also, the ShutdownableThread is widely used by various module, so not changing the behavior of the thread.

1. The ShutdownableThread source code is in Java, so thought to write the new unit tests in java.
2. In this test, we don't expect any entries to expire. The test fails 2% of time which mean the remaining 98% of time, the cleaner-thread ran. In the assertion, we ensure that the cleaner-thread is closing correctly for both the cases.

**Comment by showuon** [comment]
If the root cause of the flaky test is the `ShutdownableThreadTest` is not running, could we add `TestUtils.waitUntilTrue(() => cache.cleanerThread.isStarted)` before we invoke `cache.close()`? 

I saw there's a method to check thread isRunning, but it's actually checking the thread is `not closing`. Maybe we can add a method to check the `ShutdownableThread#isStarted` value?

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the fix.

**Review by divijvaidya — APPROVED** [review]

**Comment by showuon** [comment]
Failed tests are unrelated.

**Pull request merged**
