### PR TITLE
KAFKA-16226; Reduce synchronization between producer threads (#15323)

### PR DESCRIPTION
**Pull request by msn-tldr**
**NOTE** this cherry-picks fix https://github.com/apache/kafka/pull/14522 into 3.7

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by msn-tldr** [comment]
@hachikuji / @ijuma can you help in merging this?

The test failures on jenkins are flaky and unrelated.

**Comment by ijuma** [comment]
Test failures are the same as the 3.7 branch.

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

This is a clean cherry-pick from master.

**Comment by msn-tldr** [comment]
@ijuma thanks!

**Pull request merged**
