### PR TITLE
KAFKA-2170, KAFKA-1194: Fixes for Windows

### PR DESCRIPTION
**Pull request by mpoindexter**
This branch fixes several Windows specific issues, both in the code and in the tests.  With these changes the whole test suite passes on my Windows machine.  I found the following issues that were relevant in Jira: KAFKA-2170 and KAFKA-1194, but there may be some others.  I also have a branch with these changes done against 0.8.2.1 if there's any interest in merging to the 0.8 series.

### CODE REVIEW

**Comment by mpoindexter** [comment]
I ran the failing test on both Mac and Windows with my changes and it does not reproduce.  I also looked at the code of the failing test, and it does not seem like it's related to my changes

**Comment by clumsy** [comment]
Hi @mpoindexter, I'd like to see this patch fixing the problem finally.
Looks like @asfbot is a bot and won't tell us any details here, more over that their jenkins doesn't keep whole build history. I cannot check what was wrong with that particular build.
Do you have any details as to what exactly has gone wrong?
Was it test failing or a merge conflict (as is usually the case with those jenkins builds)?

**Comment by mpoindexter** [comment]
It was a test failure (can't remember exactly which test).  I looked at the failing test and it did not seem related to my changes as far as I could tell, and I could not reproduce the test failure in my environment.

**Comment by clumsy** [comment]
@mpoindexter why not amend this commit (without changing anything) so that a new build is triggered? We will be able see if anything fails in the new build.

**Comment by clumsy** [comment]
ok, @mpoindexter, now who do we need to kill so that fix is merged?

**Comment by mpoindexter** [comment]
@clumsy Wish I knew!  I really don't know much of anything about Kafka, but KAFKA-1194 is making a few things difficult for me so I figured I'd take a stab at fixing it.

**Comment by clumsy** [comment]
@mpoindexter Try reaching out project members on Apache Kafka's issue tracker, this KAFKA-1194 in particular.

**Comment by ewencp** [comment]
@mpoindexter Sorry this sat for so long without comment. It needs updates to bring it up to date with trunk, but if we get an updated patch I'd be happy to review, test, and merge.

**Comment by mpoindexter** [comment]
I'm not working on the project that uses Kafka on Windows any more at the moment, so if anyone else wants to run with this my patch might provide a good starting point.  I've pinged some of my old colleagues, I think they are interested in moving this along, and at some point they will probably submit a new PR with an updated patch.  If and when that happens I'll link to it here.

**Comment by MPeli** [comment]
Hi, I have created a new pull request. See #12331

**Pull request closed without merging**
