### PR TITLE
KAFKA-10199: Add missing catch for lock exception

### PR DESCRIPTION
**Pull request by cadonna**
The state directory throws a lock exception during intitialisation if a task state directory is still locked by the stream thread that previously owned
the task. When this happens Streams catches the lock exception, ignores the exception, and tries to initialize the task in the next exception.

In the state updater code path we missed to catch the lock exception when Streams recycles a task. That leads to the lock exception thrown to the exception handler which is unexpected and leads to test failures.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lucasbru** [comment]
No unit test a la `shouldRetryInitializationWhenLockExceptionInStateUpdater` for this?

**Comment by cadonna** [comment]
Good point! Will add the unit test!

**Review by lucasbru — APPROVED** [review]
lgtm, thanks!

**Comment by lucasbru** [comment]
build failures are unrelated

**Pull request merged**
