### PR TITLE
MINOR: need to update system test version after version bump

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by guozhangwang — APPROVED** [review]
Thanks!

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Actually, why do we need this version?

**Comment by ijuma** [comment]
According to https://github.com/apache/kafka/commit/a1ca07d3163b8be05056347e9403bcd6a36d535a#diff-503f218d646c10f484fdc9d6315bf2e3R18, there is only one place in the system tests that need updating. It would be good if that were really the case. If not, then we should update that comment to be correct so that people don't miss it in future updates.

**Comment by mjsax** [comment]
Kafka Streams system tests use this. Will update `gradle.properties` accordingly and update this PR.

**Review by rajinisivaram — APPROVED** [review]
@mjsax Thanks for the PR, LGTM

**Comment by rajinisivaram** [comment]
Merging to trunk.

**Pull request merged**
