### PR TITLE
KAFKA-7693: Fix SequenceNumber overflow in client TransactionManager.

### PR DESCRIPTION
**Pull request by mingaliu**
This is to fix KAFKA-7693. The bug is found during operating the Kafka cluster. 
The problem is SequenceNumber is Int and should wrap around when it hit the int.MaxValue.
The bug here is it doesn't wrap around and become negative and throw the Exception mentioned in the JIRA-7693.

Verified in the unitest and our daily testing environment.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Cc @hachikuji

**Comment by ijuma** [comment]
Thanks for the PR. Would it be possible to add a test for this?

**Comment by mingaliu** [comment]
@ijuma Thanks for the comments, I added the unitest, please review again.

**Comment by mingaliu** [comment]
Tested multiple times and succeed locally, this is due to other random test failure. @ijuma, @hachikuji , please review.

**Comment by mingaliu** [comment]
Please review or sign off, @junrao , @hachikuji , thanks!

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the fix!

**Pull request merged**
