### PR TITLE
KAFKA-9225: Bump rocksdb 5.18.3 to 5.18.4

### PR DESCRIPTION
**Pull request by jiameixie**
Bump rocksdb 5.18.3 to 5.18.4 that supports all platforms.
Issues about this version are https://github.com/facebook/rocksdb/pull/6497
and https://github.com/facebook/rocksdb/issues/6188

Change-Id: I3febec8e36550edcb7f88839cc1e2b2a54984564
Signed-off-by: Jiamei Xie <jiamei.xie@arm.com>

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ableegoldman** [comment]
@jiameixie Thanks for following up! Have you tested this out and verified that it now works with your architecture?

**Comment by mjsax** [comment]
Retest this please

**Review by mjsax — APPROVED** [review]
@guozhangwang @vvcephei I guess it's fine to bump RocksDB bug fix version?

Assuming all tests pass, LGTM. We should also run system tests before merging.

**Comment by ableegoldman** [comment]
Streams system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3832

edit: original run ([#3829](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3829)) failed with some environmental error, kicked off a new run ([#3831](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3831))
edit 2: someone killed the second run ([#3831](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3831)) so let's try this a third time with [#3832](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3832)

**Comment by jiameixie** [comment]
@ableegoldman yes, I have tested it on ARM. It works fine.

**Comment by ableegoldman** [comment]
Three system tests failed, [results here](http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2020-03-13--001.1584085918--jiameixie--rocksdb--71cf5c2/report.html)

Two are confirmed to be failing already (the `StreamsEOStest`) and a quick glimpse at the third (`test_standby_tasks_rebalance`) seems highly unlikely to be related to this PR, and probably also flaky beforehand. cc/ @mjsax

**Comment by mjsax** [comment]
Merged to `trunk`.

Thanks for the fix @jiameixie

**Pull request merged**
