### PR TITLE
Update quickstart.html

### PR DESCRIPTION
**Pull request by tony9527167**
Fix v2.4.x~v2.5.x console producer script doesn't supports  `--bootstrap-server` option.
We should use `--broker-list` instead.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rondagostino — COMMENTED** [review]
The `--bootstrap-server` option was added via KAFKA-8507 in v2.5.0.  This seems to go backwards and revert that change.  Is there a justification for this revert on trunk?

**Comment by showuon** [comment]
In the quickstart, the 1st step we described is to download V2.5.0, and the following steps work well in V2.5.0. @tonytony2020 , could you try again with V2.5.0? Thanks.

**Comment by hachikuji** [comment]
I'm going to go ahead and close this. If we have missed something, please reopen and let us know.

**Comment by tony9527167** [comment]
> In the quickstart, the 1st step we described is to download V2.5.0, and the following steps work well in V2.5.0. @tonytony2020 , could you try again with V2.5.0? Thanks.

Everything works well on v2.5.0, ignore me and this issue.

**Pull request closed without merging**
