### PR TITLE
KAFKA-13618;`Exptected` rename to `Expected`

### PR DESCRIPTION
**Pull request by Kvicii**
BatchAccumulator `Exptected` rename to `Expected`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Kvicii** [comment]
@showuon hi, cloud you help me.
PTAL

**Review by mimaison — APPROVED** [review]
Thanks for the PR, LGTM

**Comment by mimaison** [comment]
Thanks @Kvicii 
For such small changes you don't need to create a JIRA. Just prefix your commit with `MINOR: `.

**Comment by Kvicii** [comment]
@mimaison  OK

**Pull request merged**
