### PR TITLE
KAFKA-16410: kafka-leader-election / LeaderElectionCommand doesn't set exit code on error

### PR DESCRIPTION
**Pull request by brandboat**
https://issues.apache.org/jira/browse/KAFKA-16410

as title, set exit code on error in LeaderElectionCommand.java

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@brandboat thanks for this patch.

Can you change the line#291 (
https://github.com/apache/kafka/blob/trunk/tools/src/test/java/org/apache/kafka/tools/LeaderElectionCommandTest.java#L291) to use `mainNoExit` instead of `main`? The `exit` could break the CI if we forgot to set exit procedure.

**Comment by brandboat** [comment]
> Can you change the line#291 (
https://github.com/apache/kafka/blob/trunk/tools/src/test/java/org/apache/kafka/tools/LeaderElectionCommandTest.java#L291) to use mainNoExit instead of main? The exit could break the CI if we forgot to set exit procedure.

Oops, that was something I missed, thanks for the reminder :smiley:

**Review by chia7712 — APPROVED** [review]
LGTM

will merge it if QA pass

**Comment by chia7712** [comment]
cherry-pick to 3.7. see https://github.com/apache/kafka/commit/3ea2acf60f2eea31d6ebbb667b8542defb1e6332

**Pull request merged**
