### PR TITLE
KAFKA-6102: Consolidate MockTime implementations between connect and …

### PR DESCRIPTION
**Pull request by cmccabe**
…clients

### CODE REVIEW

**Review by rhauch — APPROVED** [review]
LGTM. Thanks!

**Comment by asfgit** [comment]
FAILURE
 8067 tests run, 5 skipped, 2 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 8067 tests run, 5 skipped, 2 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 8067 tests run, 5 skipped, 2 failed.
--none--

**Comment by cmccabe** [comment]
retest this please

**Comment by rhauch** [comment]
@hachikuji this looks great and is ready for a merge. Would you mind?

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the cleanup.

**Pull request closed without merging**
