### PR TITLE
KAFKA-2254: Use double quote to prevent globbing and word splitting in shell scripts

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6865/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6879/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by omkreddy** [comment]
retest this please

**Comment by omkreddy** [comment]
retest this please

**Comment by omkreddy** [comment]
cc @ijuma  minor improvements to the shell scripts based on https://www.shellcheck.net/

**Comment by omkreddy** [comment]
@hachikuji  Can you review this minor PR when you get a chance

**Comment by omkreddy** [comment]
@hachikuji @ijuma pinging for review

**Pull request closed without merging**
