### PR TITLE
MINOR: Fix link to old doc in quickstart

### PR DESCRIPTION
**Pull request by cadonna**
In Kafka's quickstart a link points to the 2.5 Kafka Streams demo.
This PR fixes this link.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for reviews: @bbejeck

**Comment by cadonna** [comment]
Once merged, the commit needs to be cherry-picked to 3.2.

**Review by showuon — APPROVED** [review]
LGTM! We should make it right, although I checked the link in the current documentation, and they are the correct link.

**Comment by cadonna** [comment]
@showuon Thanks! They are correct in the current documentation probably because the release manager fixed the link manually in the kafka-site repo. The doc is copied over from the kafka repo to the kafka-site repo for each release. If we fix it here it should be fixed once and for all.

**Comment by cadonna** [comment]
Cherry-picked to 3.2

**Comment by bbejeck** [comment]
Thanks for the fix @cadonna

**Pull request merged**
