### PR TITLE
KAFKA-16251: Fix for not sending heartbeat while fenced

### PR DESCRIPTION
**Pull request by lianetm**
Fix to ensure that a consumer that has been fenced by the coordinator stops sending heartbeats while it is on the FENCED state releasing its assignment (waiting for the onPartitionsLost callback to complete). Once the callback completes, the member transitions to JOINING and it's then when it should resume sending heartbeats again.

### CODE REVIEW

**Comment by lianetm** [comment]
Hey @lucasbru, could you take a look at this small fix? Thanks!

**Comment by lianetm** [comment]
Also @mjsax this is a very small one, closely related to the protocol, might be interesting.

**Review by lucasbru — APPROVED** [review]
LGTM, thanks!

**Comment by lucasbru** [comment]
@lianetm could you merge again, seems master was broken at the time of the last merge so we did not get a test run

**Comment by lianetm** [comment]
Test failures seem unrelated to me. The `testAutoCommitOnClose` failing on the consumer integration tests has been reported flaky independently of this PR , tracked with [KAFKA-16167](https://issues.apache.org/jira/browse/KAFKA-16167)

**Comment by lucasbru** [comment]
What about 

```
testPerPartitionLagMetricsWhenReadCommitted(String, String).quorum=kraft+kip848.groupProtocol=consumer – kafka.api.PlaintextConsumerTest
```

It has a 100% pass rate out of 65 builds on trunk in the last 7 days.. maybe you can check the logs to see if it's related. I'll retrigger the CI build

**Comment by lianetm** [comment]
Last build failed, so I rebased to trigger it again with the latest and take another look at the logs. I had missed `testPerPartitionLagMetricsWhenReadCommitted`, took a look at the logs and the failure was due to timeout to consume. I don't see a relationship with the changes here given that it's only concerning the fenced state to not send HB. Ran it locally repeatedly for a while, successfully. I will take another look when the build completes.

**Comment by lianetm** [comment]
Broken builds were just fixed in trunk. Merged latest changes here.

**Pull request merged**
