### PR TITLE
KAFKA-3387: Update GetOffsetShell tool to not rely on old producer

### PR DESCRIPTION
**Pull request by SinghAsDev**

### CODE REVIEW

**Comment by SinghAsDev** [comment]
@gwenshap ping for review. I have verified this using the system test added as part of KAFKA-3380.

**Comment by gwenshap** [comment]
Sorry, I'm super confused.
From what I see, the getOffsetTool never used the old producer (or can you point me to the line in the code where it does?), but after your change it uses the new Producer even if you have an "useOldProducer" flag?

**Comment by gwenshap** [comment]
ok, I got it. The old producer is actually hiding in client utils.

Any special reason we are keeping it around as an option? When do we expect users to use this?

**Comment by SinghAsDev** [comment]
@gwenshap the tools uses `ClientUtils.fetchTopicMetadata` on line 111, which uses old producer, https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/client/ClientUtils.scala#L55.

**Comment by SinghAsDev** [comment]
Same timing :). No specific reason, just wanted to be consistent with other tools, where we did not remove old producer, but just made new producer as default option. Once we plan to remove old producer, we can remove all usages of old producer. That is my thought, I am happy to remove it if you think that is the way to go.

**Comment by gwenshap** [comment]
If we have both options, perhaps the system test should test both?

**Comment by SinghAsDev** [comment]
Yea, that sounds fair. I will update the test. Thanks!

**Comment by SinghAsDev** [comment]
@gwenshap updated and tested.

**Comment by SinghAsDev** [comment]
The test, `org.apache.kafka.connect.runtime.WorkerSourceTaskTest.testCommit` failure is not related.

**Comment by gwenshap** [comment]
I'm very sorry to run you around, but I thought about it a bit more:
Users of GetOffset currently don't know that it is using a producer (since we are using it internally for a very accidental method), so having --old-producer configuration will just confuse everyone.

Lets just get rid of the use of old producer completely. We will still be consistent since this tool hides the use of producer from the user...

**Comment by SinghAsDev** [comment]
@gwenshap that is a good point, but this raises a question that should it be hidden. To use new producer against a secure Kafka installation, user will have to specify security configs in producer.config file. Irrespective of whether we want to hide producer from user or not, another question is that if it is OK to remove old producer from one tool while keeping it in other tools? Maybe we should keep it around till we completely remove old-producer? If you still think old-producer is not worth keeping around in this tool, I will update the PR.

**Comment by gwenshap** [comment]
I don't see any producer config or security here?
https://cwiki.apache.org/confluence/display/KAFKA/System+Tools#SystemTools-GetOffsetShell

**Comment by gwenshap** [comment]
In general, we are keeping the old producer in console-producer and mirrormaker because those tools "produce", and users may care about how they produce.

GetOffsetShell doesn't produce, it just uses a method that was conveniently available in the producer and someone didn't take good care in encapsulation and dependencies when writing this tool.

Ideally, we will refactor getTopicMetadata in the new clients (or into common, most likely) so this tool will not depend on a producer at all.

**Comment by ijuma** [comment]
Closing this as the code no longer uses a producer.

**Pull request closed without merging**
