### PR TITLE
KAFKA-4564: follow up hotfix for system test

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
This is a follow up to #2837 
After introducing new exception `BrokerNotFoundException` we missed to update the corresponding system test.

Call for review @enothereska @dguy @guozhangwang

**Comment by mjsax** [comment]
System test passed: https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/272/

**Comment by enothereska** [comment]
LGTM

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Pull request closed without merging**
