### PR TITLE
MINOR: fix record time in shouldWipeOutStandbyStateDirectoryIfCheckpointIsMissing

### PR DESCRIPTION
**Pull request by wcarlson5**
Prevents cleaner thread from occasionally deleting segments

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wcarlson5** [comment]
@mjsax  I extracted the fix

**Review by mjsax — APPROVED** [review]
LGTM. Will merge after Jenkins passed and cherry-pick to older branches.

**Comment by showuon** [comment]
LGTM! Thanks for the fix, @wcarlson5 . And all tests passed!

**Comment by mjsax** [comment]
@showuon -- I just see you comment now after merging. Did not add you as reviewer in the commit message. Sorry about that.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.7` and `2.6` branches.

**Pull request merged**
