### PR TITLE
KAFKA-12509 Tighten up StateDirectory thread locking

### PR DESCRIPTION
**Pull request by ketulgupta1995**
Modified LockAndOwner class to have Thread reference instead of just name

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ketulgupta1995** [comment]
@ableegoldman could you review this

**Review by ableegoldman — APPROVED** [review]
LGTM, thanks for the PR

**Comment by ableegoldman** [comment]
Just some known flaky test failures: `RaftClusterTest.testCreateClusterAndCreateListDeleteTopic()` and the timeout we've been seeing lately

**Comment by ableegoldman** [comment]
Merged to trunk

**Pull request merged**
