### PR TITLE
HOTFIX: Check hasNext in KStreamWindowReduce

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
Also renaming the processor to correctly reflect the operator name. Review by @enothereska @dguy @mjsax

**Comment by dguy** [comment]
LGTM

**Comment by mjsax** [comment]
+1

**Comment by guozhangwang** [comment]
Jenkins failures are transient and tracked in other JIRAs.

**Comment by guozhangwang** [comment]
Merged to trunk. And cherry-picked to 0.10.0

**Pull request closed without merging**
