### PR TITLE
MINOR: increase timeout values in streams tests

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@guozhangwang  couple of tests are consistently failing on my machine. increasing the wait timeout helped to pass the tests.

**Comment by guozhangwang** [comment]
I cannot reproduce the failure on my local box ..  @omkreddy you mentioned is that it is "consistently" failing on his machine, and it worries me if it is really flakiness or some unit test bugs.

After increased the timeout to 10s, you have not seen it any more?

**Comment by omkreddy** [comment]
@guozhangwang These tests are failing  most of the times when i ran ```./gradlew clean :streams:test```.   After increasing the timeouts, I am not able to reproduce the failures. I ran multiple times.  maybe slow machine is causing the timeouts.

If you see no harm, we can merge this PR.

**Review by guozhangwang — COMMENTED** [review]
Sounds good. LGTM.

**Pull request merged**
