### PR TITLE
KAFKA-5055: Kafka Streams skipped-records-rate sensor bug

### PR DESCRIPTION
**Pull request by dpoldrugo**
Fix as described in the [KAFKA-5055 Jira comment](https://issues.apache.org/jira/browse/KAFKA-5055?focusedCommentId=15990086&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15990086).

@mjsax @guozhangwang take a look

### CODE REVIEW

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by guozhangwang** [comment]
retest this please.

**Comment by mjsax** [comment]
@dpoldrugo Can you try to rebase this PR to latest `trunk` -- I hope this allows us to get three green builds.

**Comment by dpoldrugo** [comment]
@mjsax done

**Review by mjsax — APPROVED** [review]
LGTM.

Thanks for rebasing -- seems it fixed the build problems :)

**Review by guozhangwang — APPROVED** [review]
Merged to trunk.

**Pull request closed without merging**
