### PR TITLE
KAFKA-12828 Remove deprecated methods in KeyQueryMetadata

### PR DESCRIPTION
**Pull request by HorizonNet**
*Remove the deprecated `getActiveHost()`, `getStandbyHosts()` and `getPartition()` methods in `KeyQueryMetadata`*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
We can remove deprecated APIs only after keeping them for at least one year, plus only in a major release. Cannot merge this PR. Closing it for now -- feel free to re-open when we announce that the next release will be 4.0.

**Comment by mjsax** [comment]
@HorizonNet -- We are ready for this PR. The 3.9 release branch was cut, and `trunk` is `4.0-SNAPSHOT` now. Feel free to re-open this PR and we can review and merge it (also please assign the Jira ticket to yourself if you want to pick up this work item).

**Comment by abhi-ksolves** [comment]
Hi @mjsax 
I have created the new PR(https://github.com/apache/kafka/pull/16747)

**Comment by HorizonNet** [comment]
@mjsax Thanks for the information. Seems like I'm unable to reopen the PR. I can restore the branch, but not reopen the PR itself.

**Comment by mjsax** [comment]
@abhi-ksolves @HorizonNet -- Can you two figure out who is working on this? We should avoid double work.

I believe the Jira ticket was unassigned, and @abhi-ksolves did assign it now? So if there is no objection from you @HorizonNet I would go ahead an review the new PR?

In general, we should first assign Jira ticket to ensure we know who is doing what to avoid redundant work (maybe it was pre-mature from @abhi-ksolves to take this ticket, even if it was unassigned, given that there was this old PR, even if the PR was closed).

Well, water down the bridge. -- There is a long list of similar tickets, to remove deprecated APIs for the 4.0 release, so I hope that @HorizonNet can find some other interesting ticket to pick up?

I am very sorry for all this confusion... We highly appreciate that you contribute to Kafka @HorizonNet, and I don't want to disregard the effort you put into this PR. It just seems simplest to just move forward with the new PR?

**Pull request closed without merging**
