### PR TITLE
kafkatest: Match and compare `*-SNAPSHOT` versions in KafkaVersionTest

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
The `KafkaVersionTest` consistently fails with the following error:
```
[WARNING - 2018-11-25 16:41:50,917 - util - is_version - lineno:71]: <ducktape.cluster.cluster.ClusterNode object at 0x7fd5d0bd0b50>: kafka version mismatch: expected ['2.1.1-SNAPSHOT'], actual set([u'2.1.1']), ps line 18996 ?  
```
We should extend the version check to support snapshot versions

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. When did this start failing?

**Comment by ijuma** [comment]
This code did work with SNAPSHOT before, it even says so in the code, so I'm trying to understand when it broke. Or if it's detecting a real problem.

**Comment by stanislavkozlovski** [comment]
Judging by the regex, it never pasted the full `2.1.1-SNAPSHOT` string, it only took `2.1.1`.

This means that the line here https://github.com/apache/kafka/blob/7fadf0a11ddb2451adc66e1b179b84b050ad3f4f/tests/kafkatest/sanity_checks/test_kafka_version.py#L57 (DEV_BRANCH.vstring) has been passing it a non `-SNAPSHOT` version to compare, in which case it would pass.

I couldn't track how the `vstring` gets created. It's from this variable https://github.com/apache/kafka/blob/7fadf0a11ddb2451adc66e1b179b84b050ad3f4f/tests/kafkatest/version.py#L62 and the `vstring` comes from the `LooseVersion` class in python's `distutils` package

**Comment by lbradstreet** [comment]
Hmm. The original regexes seem to work for me, so there may be something else going on here.

```
  import re                                                                                                                                                                                                                                     
  print re.findall("kafka_[0-9]+\.[0-9]+-([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)", "kafka_2.11-0.11.0.0-SNAPSHOT.jar")                                                                                                                                 
  print re.findall("kafka_[0-9]+\.[0-9]+-([0-9]+\.[0-9]+\.[0-9]+)[\.-][a-zA-z]", "kafka_2.11-1.0.0-SNAPSHOT.jar")                                                                                                                               
  print re.findall("kafka-[a-z]+-([0-9]+\.[0-9]+\.[0-9]+)[\.-][a-zA-z]", "kafka-streams-1.0.0-SNAPSHOT.jar")                                                                                                                                    
  print re.findall("kafka-[a-z]+-([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)", "kafka-streams-1.0.0.0-SNAPSHOT.jar")                                                                                                                                       
```
```
['0.11.0.0']
['1.0.0']
['1.0.0']
['1.0.0.0']
```

**Comment by ijuma** [comment]
I remembered testing all of them manually, so I was surprised to hear that they didn't work. Thanks @lbradstreet for verifying this. :)

**Comment by lbradstreet** [comment]
I think I have a better idea about what is going on. I now understand what @stanislavkozlovski was saying.

The regexes do match the SNAPSHOT versions, however they only capture the base version without the SNAPSHOT.

When these are compared to the supplied version `2.1.1-SNAPSHOT`, `2.1.1-SNAPSHOT` != `2.1.1`.

**Comment by lbradstreet** [comment]
I think a regex like this:

`re.findall("kafka_[0-9]+\.[0-9]+-([0-9]+\.[0-9]+\.[0-9]+[\.-][a-zA-z]*)", "kafka_2.11-1.0.0-SNAPSHOT.jar")`
->
`['1.0.0-SNAPSHOT']` might be better (regex is not quite right since it won't detect non snapshot versions correctly).

 I'm not sure when we started passing in a `-SNAPSHOT` version to compare to.

**Comment by stanislavkozlovski** [comment]
That's what I meant :) 
The new regexes should match both with -snapshot and without, since we're using a zero-or-one quantifier `?` for the `-SNAPSHOT` regex matching group and then concatenating both groups'

**Comment by ijuma** [comment]
I think someone broke the code basically. It is intentional that we end up without the SNAPSHOT at the end.

**Comment by ijuma** [comment]
Maybe the return of `KafkaVersion("dev")` has changed, not sure.

**Comment by lbradstreet** [comment]
Traced the version back, and this was the offending commit: https://github.com/apache/kafka/commit/4cca418c6d15d00d31e43b20b447c1ea0e9f03c5#diff-525be40744fd314e5c3cc5511377835dL25.

The version should have been '2.1.1.dev0'.

Should I open a PR against the 2.1 branch? I'm not sure how those branches usually get managed.

**Comment by lbradstreet** [comment]
New fix in this PR https://github.com/apache/kafka/pull/5955.

**Comment by ijuma** [comment]
If the problem is just in that branch, then yes, PR to the relevant branch.

**Comment by stanislavkozlovski** [comment]
I see, that makes sense and explains why we hadn't hit it before. Thanks for investigating @lbradstreet !

**Pull request closed without merging**
