### PR TITLE
MINOR: Remove deprecated alterConfigs method

### PR DESCRIPTION
**Pull request by tang7526**
Remove deprecated alterConfigs method

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. I am not sure if we can remove this method yet. @hachikuji do I remember correctly a conversation where you mentioned that the replacement doesn't cover certain use cases? Related to configs for pluggable components perhaps.

**Comment by ijuma** [comment]
We should file a JIRA for this. Even if we decide not to do this for 3.0, we can track that information and set 4.0 as the target.

**Comment by chia7712** [comment]
https://issues.apache.org/jira/browse/KAFKA-17610 is opened.

**Comment by mimaison** [comment]
This has been done in https://github.com/apache/kafka/pull/18002, closing.

**Pull request closed without merging**
