### PR TITLE
MINOR: Upgrade jetty-server to 9.4.44.v20210927

### PR DESCRIPTION
**Pull request by dajac**
Release notes: https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.44.v20210927

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by showuon** [comment]
@dajac , I saw you're working on the same issue as me. could you check this PR: https://github.com/apache/kafka/pull/11656 ? That also upgrade some other libraries with vulnerability. Thanks.

**Review by rajinisivaram — APPROVED** [review]
@dajac Thanks for the PR, LGTM

**Comment by dajac** [comment]
@showuon Thanks for letting me know. I will take a look at your PR. In the mean time, I will merge this one because we need the upgraded jetty version for something else.

**Comment by showuon** [comment]
@dajac , no problem. Thank you!

**Pull request merged**
