### PR TITLE
KAFKA-Junit3 Misusage

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@guozhangwang Can you take a look at this? I addressed the issue with the failing tests from the existing patch that was in RB. It turns out that fixing this does seem to fix the SocketServerTest failures on OS X, so I'd like to get this committed ASAP. On commit, we should be careful to make sure Alexander Pakulov gets credit since he did all the hard work.

**Comment by ijuma** [comment]
@ewen you can amend the author in your commit and then it just works. The merge script also allows this to be overridden so that's another way.

**Comment by hachikuji** [comment]
@guozhangwang I think we need to reopen this issue. Some of the tests are no longer running (e.g. ConsumerTest). I think we need the `@Test` annotation on all of the test cases for this to work.

**Comment by guozhangwang** [comment]
Thanks @hachikuji, I saw you have already re-opened the JIRA, let's use another PR to resolve the follow-up problems. BTW are you working on that?

**Comment by ewencp** [comment]
@guozhangwang @hachikuji I'm looking at this right now, I'm just going to take a diff of the output before and after the patch to find the tests that are missing the annotation.

**Pull request closed without merging**
