### PR TITLE
KAFKA-4176: Only call printStream.flush for System.out

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
Ping @bbejeck @mjsax @enothereska @dguy for reviews.

Originally even for `System.out` the `close` call will be triggered, which may be blocking if people called `System.out.print..` somewhere else.

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
For my own clarity I wanted to see where I went awry.  When `print()` is called the constructor call `KeyValuePrinter<>(keySerde, valSerde, streamName)` is used which delegates to `this(System.out, keySerde, valueSerde, streamName);` in the KeyValuePrinter class.  Since `System.out` is not null the boolean flag is never set and when `close()` is called on the processor `System.out` is closed as well. 

@guozhangwang  thanks for fixing.

**Comment by dguy** [comment]
LGTM

**Pull request closed without merging**
