### PR TITLE
MINOR: Add fast_commit to ext4 tuning docs

### PR DESCRIPTION
**Pull request by moscicky**
This PR adds `fast_commit` tuning option to EXT4 notes. We have found this options be the most performant for EXT4 filesystem. The details of our analysis and findings are described in a [blogpost](https://blog.allegro.tech/2024/03/kafka-performance-analysis.html).

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by moscicky** [comment]
@mimaison perhaps you could take a look and review?

**Comment by mimaison** [comment]
Thanks for the PR!
From the articles you mentioned, it seems it makes sense to mention this setting in our docs.

However I personally don't have experience with it, so my only concern is whether this is true for all workloads? If we're unsure, we can say something like we do for data=writeback, i.e.: `seems to significantly reduce latency`

**Comment by moscicky** [comment]
@mimaison Haven't tested it against all kind of workloads, so the wording you propose seems reasonable. Changed it according to your suggestion.

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request merged**
