### PR TITLE
KAFKA-17326: The LIST_OFFSET request is removed from the "Api Keys" page

### PR DESCRIPTION
**Pull request by m1a2st**
Jira: https://issues.apache.org/jira/browse/KAFKA-17326
If the last version is unstable, but it has stable version, it should be show on the html.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@m1a2st thanks for this patch. Could you please add "unstable version" to LIST_OFFSET and then generate the html with your fix? That can prove your PR does fix it.

**Comment by m1a2st** [comment]
Yes, If unstable version is true, the result is 
CleanShot 2024-08-14 at 19 49 43@2x

**Comment by chia7712** [comment]
@m1a2st thanks for tests, but what I wan to test is the LIST_OFFSET should be in the html file even though its last version is unstable

**Comment by m1a2st** [comment]
Hi @chia7712, I already test again, and result include both "unstable version is false" and "unstable version is true but have other version"
CleanShot 2024-08-14 at 22 17 52@2x

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
