### PR TITLE
Duplicate method; The QuotaUtils one is used.

### PR DESCRIPTION
**Pull request by afshing**
It seems like [this PR](https://github.com/apache/kafka/pull/8768) moved the implementation to QuotaUtils, but didn't remove this implementation

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by jolshan — APPROVED** [review]
thanks for cleaning this up!

**Comment by jolshan** [comment]
@afshing -- can you link the commit that moved the code in your description?

**Comment by afshing** [comment]
> @afshing -- can you link the commit that moved the code in your description?

Oh! I missed that link. Added now. 
@jolshan do you know why the CI is failing? it seems all the tests are passed, but it fails in "Recording test results" step

**Comment by jolshan** [comment]
Hey @afshing -- the place to view the test results is on the tests tab. The default page really only tells you if the workflow is done. -- see
https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-15066/5/tests

The test results look pretty good so I will let this build finish and double check, but otherwise, this should be good to merge.

**Comment by afshing** [comment]
@jolshan it seems like the build for JDK 11 passed, and the other three are failed by some unrelated (flaky?) tests.
Should I keep trying the CI pipeline?

**Comment by jolshan** [comment]
Hey @afshing -- unfortunately fully green kafka builds are not super common. But we are working on it! Given your change, I think we are ok to merge.

**Comment by jolshan** [comment]
Given the nature of the change, I merged this as a MINOR commit. But if you plan to contribute more in the future, please consider filing a JIRA ticket and using the name of the ticket (ie KAFKA-XYZ) in the title of the PR.

Thanks for fixing this!

**Pull request merged**
