### PR TITLE
KAFKA-5543: Remove all partition metrics when a topic is deleted

### PR DESCRIPTION
**Pull request by apurvam**

### CODE REVIEW

**Comment by apurvam** [comment]
cc @junrao @hachikuji

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5826/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5812/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by apurvam** [comment]
The test failures are for the new assertions I added. Very strange since they pass locally.

**Comment by ijuma** [comment]
I merged @lindong28's commit (https://github.com/apache/kafka/commit/a16475eb333b0205b74b817237cba187862e61e7) before I saw this. However, this improves the code, so we should rebase and merge it too.

**Comment by ijuma** [comment]
@apurvam they are probably not passing because some other test is not cleaning up properly perhaps.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5852/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5837/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by apurvam** [comment]
It looks like the bug has already been fixed on trunk. Will fix these tests after I am back.

**Comment by ijuma** [comment]
@apurvam, maybe you want to revive this.

**Comment by apurvam** [comment]
ack. I want to settle into a groove with the main projects and then start spending time on clearing my backlog.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6377/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6362/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
@apurvam shall we revive this? It's good to avoid memory leaks (even if small).

**Comment by apurvam** [comment]
ack @ijuma . I should have some time in the next week and half.

**Pull request closed without merging**
