### PR TITLE
KAFKA-3050: Acceptor allows hostnames surrounded by whitespaces

### PR DESCRIPTION
**Pull request by Zixxy**

### CODE REVIEW

**Comment by arunmahadevan** [comment]
The Kafka config parsing code already seems to trim white spaces. See - https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java#L197
Not sure why do we need to trim again.

**Comment by Zixxy** [comment]
Issue 3050 affected 0.8.2.1 version. This code fixed bug on that branch, but no new release planned for 0.8.2 so I pushed it to master. With this config, in master this doesn't seem to have sense. Should I push it to that branch?

**Comment by arunmahadevan** [comment]
I see similar code (trim) in 0.8.2.1 as well.
https://github.com/apache/kafka/blob/0.8.2.1/clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java#L143

Maybe its failing in some other code path ? I am not able to replicate that issue by adding space after the hostname.

**Comment by Zixxy** [comment]
Try to replicate it in 0.8.2.1 branch, for me without that trim it throws exactly the same exception as Navin reported in jira.

**Comment by arunmahadevan** [comment]
yes, it fails in 0.8.2.1 branch. apparently it was not trimming all the values, but seems to have got fixed in the trunk.

**Comment by hachikuji** [comment]
Closing this since the issue was already fixed. Please reopen if you think this was a mistake.

**Pull request closed without merging**
