### PR TITLE
KAFKA-3086: Remove unused method.

### PR DESCRIPTION
**Pull request by j-nowak**

### CODE REVIEW

**Comment by ijuma** [comment]
Users can use pass a custom `message.handler` class that could be affected by this change. Are we OK with removing without a deprecation period? Thoughts @junrao?

Also, if we do remove it, we should add a note to the upgrade notes for the next release as part of this PR.

**Comment by gwenshap** [comment]
The custom handler does not exist in 0.8.2, so this will only affect users who implemented it on 0.9.0.

I would prefer to remove it now (with an upgrade note). Those who use it will understand, since they must have noticed this method is never called.

**Comment by ijuma** [comment]
Sounds good.

**Comment by j-nowak** [comment]
I added an upgrade note. Is it ok or should I reformulate it?

**Comment by ijuma** [comment]
@Mszak, that list is for 0.9.0.0, I think you want to add this one under 0.9.0.1.

**Comment by ijuma** [comment]
Or alternatively maybe just mention in the note that it applies to 0.9.0.1 and later.

**Comment by granthenke** [comment]
A recent patch in trunk added a "Notable changes in 0.9.0.1" section to [upgrade.html](https://github.com/apache/kafka/blob/trunk/docs/upgrade.html#L51) could this just be added to that list?

Otherwise LGTM.

**Comment by ijuma** [comment]
That sounds good @granthenke.

**Comment by guozhangwang** [comment]
LGTM. Leaving for @ijuma to take another look.

**Comment by ijuma** [comment]
LGTM.

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
