### PR TITLE
KAFKA-5529 Use only KafkaProducer in ConsoleProducer

### PR DESCRIPTION
**Pull request by evis**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. We can only this when we are ready to remove the ability to use the old producer in `ConsoleProducer`. And that can only happen in a major release of Apache Kafka.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5761/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5747/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by omkreddy** [comment]
Closing as this fixed in #5045

**Pull request closed without merging**
