### PR TITLE
KAFKA-12293: remove JCenter and Bintray repositories mentions out of build gradle scripts (sunset is announced for those repositories)

### PR DESCRIPTION
**Pull request by dejan2609**
Related jira ticket: 
https://issues.apache.org/jira/browse/KAFKA-12293 **_Remove JCenter and Bintray repositories mentions out of Gradle build (sunset is announced for those repositories)_**

Some related external links:
- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter
- https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure

Note: at the moment I am not sure about Kafka releasing process (i.e. publishing to global public repositories). If Kafka exclusively  publishes to JCenter then this solution should be expanded. `update: could not find release process related gradle parts`

FYI @ijuma

### CODE REVIEW

**Comment by dejan2609** [comment]
This PR is ready for a review.
FYI @ewencp and @ijuma

**Comment by dejan2609** [comment]
(note: I just force-pushed once more in order to remove phrase `[Work in progress]` out of the git commit message... **_now_** PR is ready ready for a review... for real 😃)

**Comment by ewencp** [comment]
I actually don't watch this much anymore, but what is the replacement? References were added intentionally because some dependencies weren't available in maven central. Has everything migrated over to central?

And what's the backporting plan?

**Comment by dejan2609** [comment]
@ewencp thing is that JFrog (company behind JCenter repository) simply decided to pull the plug on May 01st 2021. (a short notice decision, I dear to say). 

So, it seems that Maven central is a fine (only ?) alternative after May 01st and luckily it seems that kafka project now builds as expected **_without_** JCenter; herewith two examples:
-  `./gradlew --refresh-dependencies --info` (dependencies refresh shows that Maven Central  has it all... with a little help of a Gradle plugin portal :smiley:  )
-  `./gradlew clean test jar releaseTarGz` (all test + jars +binary releases combined into one, big execution... only handful of test failed, so I assume that we are good to go):

```
ClientIdQuotaTest > testThrottledProducerConsumer() PASSED

ClientIdQuotaTest > testQuotaOverrideDelete() PASSED

ClientIdQuotaTest > testThrottledRequest() PASSED

3214 tests completed, 15 failed, 7 skipped

> Task :core:test FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':connect:runtime:test'.
> There were failing tests. See the report at: file:///home/dejan/IdeaProjects/kafka/connect/runtime/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':core:test'.
> There were failing tests. See the report at: file:///home/dejan/IdeaProjects/kafka/core/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 38m 29s
252 actionable tasks: 252 executed
```

**Comment by dejan2609** [comment]
Update: JFrog partially reversed their decision (first they declared something on Feb 3rd and then changed their mind on Feb 8th).

Now they decided to serve artifacts via JCenter until **_February 1st 2022_** (but they will stop receiving **new** artifacts after March 31st 2021). https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure

Herewith a new schedule:
> - _**March 31st, 2021  | No more submissions will be accepted to JCenter**_
> - _**May 01st 2021 | JCenter REST API and UI will be sunsetted**_
> - **_February 1st, 2022  | JCenter will no longer be available for non-Artifactory clients_**

**Comment by andrewegel** [comment]
At the time of my comment here, jcenter is throwing 500s to my kafka build processes: https://status.bintray.com/incidents/ctv4bdfz08bg

Now is a good as time as any to take this change to remove this project's dependence on the jcenter service.

**Comment by ijuma** [comment]
@dejan2609 can you please resolve the conflict?

**Comment by dejan2609** [comment]
@ijuma Done (conflict solved / branch force-pushed).

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by ijuma** [comment]
I tried backporting to 2.8 and the older Gradle plugin versions in that branch were not available in Maven central. We should probably wait a few months and see how things develop before backporting to older branches.

**Comment by JoeCqupt** [comment]
> I tried backporting to 2.8 and the older Gradle plugin versions in that branch were not available in Maven central. We should probably wait a few months and see how things develop before backporting to older branches.

is it  time to merge this pr to 2.8 ?  @ijuma 

first time build branch 2.8 will get a failure cause by "https://dl.bintray.com/content/netflixoss/external-gradle-plugins/" 502

**Comment by mdshadabin** [comment]
> 

i still see issue with kafka 2.8.0 

few days back i  have downloaded kafka 2.8.0 source code (from https://kafka.apache.org/downloads ) and build binaries (following https://github.com/apache/kafka/tree/2.8) . Although build is successful after changing gradle plugin url in gradle/buildscript.gradle   (Since url 'https://dl.bintray.com/content/netflixoss/external-gradle-plugins/'  is down i have changed to url 'https://plugins.gradle.org/m2/' )  but unit
[index.html.zip](https://github.com/apache/kafka/files/7808015/index.html.zip)
 test is falling. I have attached unit test result.


My env details:
============
Gradle 6.8.3

java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)

Scala code runner version 2.13.0

**Comment by ewencp** [comment]
@mdshadabin as mentioned by @ijuma above, this hasn't been backported to older releases yet. Unit tests are sometimes flaky, so might just be due to that. At this point it would probably make most sense to file PRs against older branches since it's not guaranteed to be a trivial backport. From there we can use the normal CI infra to validate.

**Comment by mdshadabin** [comment]
Thanks @ewencp  ,

I have switched to Kafka 3.0.0, i always see a few unit test failures.
Download Kafka source code from official side and follow git hub to build and run unit test. 

Below is link to access : build log, unit test log and unit test report.
https://drive.google.com/drive/folders/1lMUgETBNUS6ncEkfD5SU4E3JbqR8wHD4?usp=sharing  


Note: please download the unit test folder, inside that index.html file have a test report. Click on any failing unit test it will show you call stack.


Are these 1% failures expected?
Is it possible to make it 100% successful?

**Pull request merged**
