### PR TITLE
KAFKA-3356: Remove ConsumerOffsetChecker

### PR DESCRIPTION
**Pull request by mimaison**

### CODE REVIEW

**Comment by ijuma** [comment]
Has anyone evaluated whether all functionality from `ConsumerOffsetChecker ` is also present in `ConsumerGroupCommand`? It would be good to post such a summary in the JIRA to validate this removal. This was the main reason why I didn't remove it along with other deprecated items.

**Comment by mimaison** [comment]
Good point, I added to the JIRA a short description of each tools' features: https://issues.apache.org/jira/browse/KAFKA-3356?focusedCommentId=16009693&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16009693

**Comment by mimaison** [comment]
@ijuma Will this land in 1.0 ? Should I rebase ?
The 2 missing features are minor but if you think they are necessary then we can start working on them

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6826/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6840/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
We should mention the removal in the upgrade notes.

**Comment by mimaison** [comment]
Sure, I'll update the PR in a bit

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by hachikuji** [comment]
retest this please

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
