### PR TITLE
MINOR: Optimize KTable-KTable join value getter supplier

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@mjsax @dguy I think we need to have some agreement on the coding style after all :) Please share your opinions. Although it is not a critical path I tend to agree that it is still more efficient.

**Comment by dguy** [comment]
It is more efficient, but efficiency really doesn't matter for this part of the code. It will have no impact on the runtime performance of streams. I'd prefer to see the code simplified to:
```
final List<String> stores = Arrays.asList(storeNames1);
Collections.addAll(stores, storeNames2);
return stores.toArray(new String[stores.size()]);
```

**Comment by mjsax** [comment]
As mentioned on the original PR, the current code mixing `ArrayList` plus `for`-loops is something I am not a fan of. Thus, the PR make sense to me.

At the same time I agree with @dguy that this is not on the critical code path and his suggestion makes sense.

My view is, either use plain arrays and for loop (what this PR does), or use collections and no for loops (what Damian suggest). (It's of course quite subjective).

@kamilszymanski WDYT?

**Comment by ddd-workshop** [comment]
I applied @dguy suggestions and optimized for readability (although there is still a petty performance-wise optimization present since Collections.addAll uses a for loop under the hood).

**Comment by kamilszymanski** [comment]
I applied @dguy suggestions and optimized for readability (although there is still a petty performance-wise optimization present since Collections.addAll uses a for loop under the hood).

**Pull request merged**
