### PR TITLE
KAFKA-4603 Command parsed error, change all OptionParser constructor 

### PR DESCRIPTION
**Pull request by auroraxlh**
KAFKA-4603 the command parsed error
Using "new OptionParser" might result in parse error

Change all the OptionParser constructor in Kafka into "new OptionParser(false)"

### CODE REVIEW

**Comment by auroraxlh** [comment]
@guozhangwang @amethystic @ewencp

**Comment by auroraxlh** [comment]
@guozhangwang @amethystic @ewencp could you cc this PR?

**Comment by auroraxlh** [comment]
@ijuma   hi, could you take a look at this PR?

**Comment by auroraxlh** [comment]
@mjsax @ewencp @dguy,can you take a look at this PR?

**Comment by auroraxlh** [comment]
@mjsax @ewencp @dguy @guozhangwang  ,can you take a look at this PR? It relates to issue：KAFKA-4603 ,It's too long to almost forget 
The issue is still “IN PROGRESS”
I just want to finish it properly
thx

**Review by dguy — COMMENTED** [review]
If i understand correctly, this will prevent abbreviations being used for options? Which seems like a good thing. Would be nice if we could somehow test it

**Comment by dguy** [comment]
FYI - the test failures are unrelated

**Comment by guozhangwang** [comment]
@auroraxlh From the JIRA ticket it seems you are trying to solve relatively separate two issues:

1) `zookeeper.connection` actually passing its value to `zookeeper.connection.timeout`, which is incorrect.

2) abbreviations are allowed in all the command tools because of `new OptionParser()`.

You has fixed 1) in https://github.com/apache/kafka/pull/2322, while for 2) I'm not sure how much of a risk to allow abbreviations, and since it may change the behavior of all command tools (say if someone is using it with abbreviations in his operational tool-suite this change will suddenly break their code), could you elaborate a bit on the actual risk and better motivate this change?

**Comment by auroraxlh** [comment]
@guozhangwang hi,it was a little a little complicated.
1. In  #2322    missed docs/security.html 
2. changing OptionParser() to OptionParser(false)  to disable abbreviations. 
    The abbreviations function of OptionParser is not fit for kafka
    As described in the doc of Jopt Simple : You can abbreviate long options, so long as the abbreviation is unique.But most of Kafka command  has  duplicate prefix, OptionParser will parse  options in order, many times the results are not satisfactory.


    For example:
[root@xx15 bin]# ./kafka-console-producer.sh -r
r is not a recognized option
[root@xx15 bin]# ./kafka-console-producer.sh -t
t is not a recognized option
[root@xx15 bin]# ./kafka-console-producer.sh -v
Option value-serializer requires an argument
[root@xx15 bin]# ./kafka-console-producer.sh -k
Option key-serializer requires an argument
[root@xx15 bin]# ./kafka-console-producer.sh -s
s is not a recognized option


If  there are repeat options,the result is confused

**Comment by guozhangwang** [comment]
@auroraxlh Thanks for the explanation! Its motivation is much more clear to me.

Could you rebase the PR and fix if there are any unit test failures from Jenkins and then I will make a final pass and merge?

**Comment by auroraxlh** [comment]
@guozhangwang  I found all "new OptionParser" that I could find, and changed them.
Please review  changes.
Thanks!

**Comment by auroraxlh** [comment]
@guozhangwang @dguy  :How to deal with this situation?
There are two test failure in:
org.apache.kafka.streams.integration.ResetIntegrationTest.testReprocessingFromScratchAfterResetWithIntermediateUserTopic
org.apache.kafka.streams.integration.ResetIntegrationTest.testReprocessingFromScratchAfterResetWithoutIntermediateUserTopic



Option (* = required)                 Description                              
---------------------                 -----------                              
* --application-id <String: id>       The Kafka Streams application ID         
                                        (application.id).                      
--bootstrap-servers <String: urls>    Comma-separated list of broker urls with 
                                        format: HOST1:PORT1,HOST2:PORT2        
                                        (default: localhost:9092)              
--dry-run                             Display the actions that would be        
                                        performed without executing the reset  
                                        commands.                              
--input-topics <String: list>         Comma-separated list of user input       
                                        topics. For these topics, the tool will
                                        reset the offset to the earliest       
                                        available offset.                      
--intermediate-topics <String: list>  Comma-separated list of intermediate user
                                        topics (topics used in the through()   
                                        method). For these topics, the tool    
                                        will skip to the end.                  
--zookeeper <String: url>             Zookeeper url with format: HOST:POST     
                                        (default: localhost:2181)              
ERROR: bootstrap-server is not a recognized option

**Comment by dguy** [comment]
retest this please

**Comment by dguy** [comment]
@auroraxlh you need no change the cli argument in `ResetIntegrationTest` it currently has `--bootstrap-server` but with your change it should be `--bootstrap-servers`

**Comment by auroraxlh** [comment]
@dguy I did not change the parameters, but when i changed the usage of OptionParser It asks exact arguments.
The Application Reset Tool ,in StreamsResetter.java,the arguments is "bootstrap-servers",but in test case is  "bootstrap-server"
As described above, there will be something wrong, if there is another arguments like "bootstrap-server****",the command will not recognize the recognize.
The two test case can report the error information exactly  just because of luck for that there is no another argument begin with “bootstrap-server”.

**Comment by dguy** [comment]
@auroraxlh you need to update the arguments in the test `ResetIntegrationTest` so that it passes the correct argument, i.e., `bootstrap-servers`

**Comment by auroraxlh** [comment]
@dguy @guozhangwang ,got it,Thanks!
Could you take a look at this again? All checks have passed.

**Review by dguy — APPROVED** [review]
LGTM

**Review by guozhangwang — APPROVED** [review]
Merged to trunk and 0.11.0.

**Pull request closed without merging**
