### PR TITLE
MINOR: Remove clients/out directory

### PR DESCRIPTION
**Pull request by ijuma**
It was committed inadvertently.

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
FAILURE
 7942 tests run, 5 skipped, 1 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8050 tests run, 5 skipped, 0 failed.
--none--

**Comment by rajinisivaram** [comment]
@ijuma Thanks for the PR. Build failures are unrelated, merging to trunk.

**Pull request closed without merging**
