### PR TITLE
KAFKA-6825: Make StreamsConfig#DEFAULT_PRODUCTION_EXCEPTION_HANDLER_CLASS_CONFIG public

### PR DESCRIPTION
**Pull request by guozhangwang**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
Should be merged into 1.1 as well.

**Review by mjsax — APPROVED** [review]
LGTM

**Comment by mjsax** [comment]
Retest this please

**Comment by guozhangwang** [comment]
Thanks @mjsax Cherry-picked to 1.1 as well.

**Pull request merged**
