### PR TITLE
KAFKA-2698: Add paused() method to o.a.k.c.c.Consumer

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
rebased from #403

**Comment by onurkaraman** [comment]
LGTM

**Comment by becketqin** [comment]
LGTM. @hachikuji Should we run a quick KIP on this?

**Comment by hachikuji** [comment]
@becketqin We could if we have to. I talked with @guozhangwang and we were thinking it might be small enough and obvious enough to not require a KIP. What do you think?

**Comment by granthenke** [comment]
LGTM

**Comment by becketqin** [comment]
@hachikuji Fair enough. We can probably skip the KIP.

**Comment by guozhangwang** [comment]
@hachikuji `Build timed out (after 120 minutes). Marking the build as failed.` in Jenkins, is this transient in local machine?

**Comment by hachikuji** [comment]
@guozhangwang I rebased again just to be safe and it builds fine locally. Maybe we can let Jenkins have another shot at it.

**Comment by guozhangwang** [comment]
LGTM, merged to trunk on behalf of @thomaslee

**Pull request closed without merging**
