### PR TITLE
MINOR: Set log level for producer internals to trace for transactions test

### PR DESCRIPTION
**Pull request by apurvam**
We need this to debug most issues with the transactions system test.

### CODE REVIEW

**Comment by apurvam** [comment]
cc @hachikuji

**Comment by hachikuji** [comment]
Thanks for the patch. I wonder if we can make this mechanism more general and allow any test case to provide custom logging overrides. For example, we can add a "loggers" variable to the environment and let the template iterate over them.

**Comment by apurvam** [comment]
Let's do that in a following PR, especially since this seems to be the first need for this. 

Also, we need these logs to debug any transactions test failure, so it's best to get this in early.

**Comment by apurvam** [comment]
For now, I change the name of the template variable to `producer_internals_log_level`. This is more general and can be used in other tests without confusion. Also, I don't think adding `consumer_internals` and something similar would be too big a deal. After all how many modules would we realistically want to turn on individually that it merits a more general solution?

**Comment by hachikuji** [comment]
@apurvam Come on 😜, it's not that much extra work. something like this ought to do the trick:
```
{% if loggers is defined %}
{% for logger, log_level in loggers.iteritems() %}
log4j.logger.{{ logger }}={{ log_level }}
{% endfor %}
{% endif %}
```
Then add this:
```
self.loggers = { "org.apache.kafka.clients.producer": "TRACE" }
```
Then we'll easily be able to change logging in the future for any test case!

**Comment by apurvam** [comment]
Ah. That is easy. Updated the PR and also tested it locally: It prints trace level logging for the producer internals. 

Thanks for the suggestion!

**Comment by hachikuji** [comment]
Thanks for the patch. LGTM

**Pull request closed without merging**
