### PR TITLE
KAFKA-7353; Connect logs 'this' for anonymous inner classes

### PR DESCRIPTION
**Pull request by kevin-laff**
Replace 'this' reference in anonymous inner class logs to out class's 'this'

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bschena** [comment]
@wicknicks @rhauch @ewencp @kkonstantine could you please review this for @kevin-laff?

**Review by rhauch — APPROVED** [review]
@kevin-laff, thanks for the fixes and for catching these discrepancies! LGTM.

**Review by wicknicks — APPROVED** [review]
Thanks for the fixes. LGTM.

**Comment by rhauch** [comment]
@ewencp, would you mind giving it a final review and merging? This modifies #3639, which was backported.

**Review by ewencp — APPROVED** [review]
LGTM, merging to trunk, 2.0, 1.1, and 1.0, which is as far back as I think #3696 was backported

**Pull request closed without merging**
