### PR TITLE
KAFKA-15721: KRaft support in DeleteTopicsRequestWithDeletionDisabledTest

### PR DESCRIPTION
**Pull request by wernerdv**
updated to support KRaft

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wernerdv** [comment]
Hello, @jolshan
Please, take a look.

The changes are similar to #15086.

Tests passed
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-15124/4/testReport/kafka.server/DeleteTopicsRequestWithDeletionDisabledTest/

**Comment by wernerdv** [comment]
@mimaison take a look, please.

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR

**Comment by jolshan** [comment]
Sorry I don't seem to get notified for tags until the PR gets merged. I need to look at my notification settings 😅

**Pull request merged**
