### PR TITLE
KAFKA-12914: StreamSourceNode should return `null` topic name for pattern subscription

### PR DESCRIPTION
**Pull request by mjsax**
Call for review @cadonna

### CODE REVIEW

**Review by showuon — APPROVED** [review]
LGTM! Just a thought that do you think it's better to return empty set when null?

**Comment by mjsax** [comment]
> Just a thought that do you think it's better to return empty set when null?

For `SourceGraphNode` we either set `topicName` or `pattern` `null`, and we also return `null` for the pattern case if `topicName` is used and `pattern is `null`. So I thought it might be better aligned to just return `null` if `topicName` is `null`, too. But I don't have a strong opinion.

As an afterthought, it might even be better to change both return types to `Optional` ?

**Comment by showuon** [comment]
> As an afterthought, it might even be better to change both return types to `Optional` ?

Sounds good!

**Comment by cadonna** [comment]
`Optional` sounds good but it would substantially increase the size of this fix which is actually not required.

On the other hand, I am not sure if we do not have other related NPE lurking in the code that should be found by changing to `Optional`. For example, I could not find a null check for https://github.com/apache/kafka/blob/45d7440c1577b838d4584d3860e5c4d691446f3f/streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/TableSourceNode.java#L86

**Comment by mjsax** [comment]
What do you propose @cadonna ? Also happy to do a follow up PR (but not sure if necessary)? It's all just internal code so we can change at will. Happy to merge as-is, or change to `Optional` in this or a follow up PR...

**Review by cadonna — APPROVED** [review]
@mjsax , I am saying that the PR is fine as it is because it fixes the bug described in the ticket. If you want to avoid potentially lurking bugs, you could change it to `Optional`. But that can be done in a follow-up PR. Your call.

**Comment by mjsax** [comment]
Update the PR to change the return type to Optional. If no objections are raised and Jenkins passed, I plan to merge this next week.

**Review by guozhangwang — APPROVED** [review]
LGTM.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.8` branch.

**Pull request merged**
