### PR TITLE
KAFKA-3355: Fix GetOffsetShell doesn't work with SASL enabled Kafka

### PR DESCRIPTION
**Pull request by murong00**
As described in [JIRA: KAFKA-3355](https://issues.apache.org/jira/browse/KAFKA-3355), i fixed this issue for kafka 0.10.1.1 in production systems, hoping it may help users with this version.

### CODE REVIEW

**Comment by mgarmes** [comment]
HI @murong00 , 
I guess your PR is the same as https://github.com/apache/kafka/pull/2891 !!
Bests

**Comment by omkreddy** [comment]
@ijuma  Can we review this before removing old consumer code? or Are we going to remove GetOffsetShell?

**Comment by ijuma** [comment]
Yes, #2891 was submitted first, so let's try to get that in instead. Also it builds on public APIs instead of the Scala AdminClient.

**Comment by ijuma** [comment]
Actually #3051 is the one that builds on public APIs, but that requires a KIP. So, maybe it makes sense to go with #2891 first and then do #3051.

**Comment by ijuma** [comment]
Hmm, on second thought, we should probably go with a reduced version of #3051 since #2891 adds methods to the Scala AdminClient that we don't want to add.

**Pull request closed without merging**
