### PR TITLE
KAFKA-2878: Guard against OutOfMemory in Kafka broker 

### PR DESCRIPTION
**Pull request by rajinisivaram**
Sanity check array size in requests before allocation

### CODE REVIEW

**Comment by SinghAsDev** [comment]
I too ran into the issue. The changes look good to me. Thanks @rajinisivaram

**Comment by ijuma** [comment]
Seems like a good change. Probably a good idea to backport it to the 0.9.0 branch. @junrao, maybe you could review this?

**Comment by junrao** [comment]
Thanks for the patch. The changes look reasonably. Could you explain a bit more how you run into this issue? The consumer library should always send requests with the correct array size.

**Comment by rajinisivaram** [comment]
@junrao We ran into the issue when we upgraded one of our clusters to the latest version of Kafka from a version (built from trunk) that was a couple of months old. One of the clients was using an old client jar where the schema was no longer valid. This is not an issue when the client jars are at the right level, but we want to guard against large memory allocations that can result in denial-of-service since our servers are on the public internet.

**Comment by junrao** [comment]
Thanks for the patch. LGTM. Since this shouldn't happen on releases jars, we will commit this to trunk.

**Comment by ijuma** [comment]
@junrao what's our policy with regards to denial of service security issues (like this one)? With the security work and quotas, people may think that the broker can be protected against misbehaving clients. From that perspective, I'd say that we would want to backport this to 0.9.0. But perhaps we think it's too soon to offer such guarantees.

**Comment by junrao** [comment]
Good point. I doubled committed to 0.9.0 branch.

**Comment by ijuma** [comment]
Thanks.

**Comment by rajinisivaram** [comment]
@junrao Thank you. Is there plan to use the Apache Security Team or other private channels to report security defects in Kafka? Since 0.9.0.0 has been released, it may be useful to have a security contact for Kafka here - http://www.apache.org/security/projects.html?

**Comment by junrao** [comment]
@rajinisivaram : Could you just submit jiras?

**Comment by rajinisivaram** [comment]
@junrao Long term it will be good to have a channel to report security vulnerabilities without impacting secure installations before a fix is available. But for now, we can submit JIRAs and see how it goes.

**Pull request closed without merging**
