### PR TITLE
KAFKA-6210: IllegalArgumentException if 1.0.0 is used for inter.broker.protocol.version or log.message.format.version

### PR DESCRIPTION
**Pull request by ijuma**
Added unit test for ApiVersion and testApiVersions from
Scala to Java.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @rajinisivaram

**Comment by rajinisivaram** [comment]
retest this please

**Review by rajinisivaram — APPROVED** [review]
Thanks for the PR, LGTM

**Comment by asfgit** [comment]
SUCCESS 
 8068 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 8068 tests run, 5 skipped, 1 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7960 tests run, 5 skipped, 1 failed.
--none--

**Comment by ijuma** [comment]
Test failures are unrelated.

**Comment by ijuma** [comment]
Merging to trunk and 1.0 branches.

**Pull request closed without merging**
