### PR TITLE
[KAFKA-7087] Add preferred leader report to describe

### PR DESCRIPTION
**Pull request by viktorsomogyi**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by viktorsomogyi** [comment]
@asasvari @smurakozi @andrasbeni would you please review it?

**Comment by omkreddy** [comment]
Since tools are considered as public API, we may need to write short KIP for this.

**Comment by stanislavkozlovski** [comment]
@viktorsomogyi do you plan on continuing with this? I think this is a useful flag to have

**Comment by viktorsomogyi** [comment]
@stanislavkozlovski sorry for the late reply. Please feel free to pick it up. Nowadays I have my hands full with other stuff.

**Pull request closed without merging**
