### PR TITLE
MINOR: Give correct instructions for retaining previous unclear leader election behaviour

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
@rajinisivaram, maybe you can review this trivial change. cc @astubbs

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6253/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6237/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
Merging to trunk and 0.11.0.

**Comment by kamalcph** [comment]
@ijuma

I have opened a PR for this one 19 days ago. No one reviewed it.

https://github.com/apache/kafka/pull/3481

**Comment by ijuma** [comment]
@Kamal15, I was on holiday when that was posted and I missed it. Sorry about that.

**Comment by kamalcph** [comment]
@ijuma
It's ok.

**Pull request closed without merging**
