### PR TITLE
MINOR: streams memory management docs

### PR DESCRIPTION
**Pull request by dguy**
update streams memory management docs

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang @enothereska @bbejeck same as https://github.com/apache/kafka/pull/3604 but with minor tweaks to make it 0.11.0 (StreamBuilder -> KStreamBuilder)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6604/
Test PASSed (JDK 7 and Scala 2.11).

**Review by enothereska — APPROVED** [review]

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6589/
Test PASSed (JDK 8 and Scala 2.12).

**Review by bbejeck — APPROVED** [review]

**Comment by guozhangwang** [comment]
LGTM!

**Comment by dguy** [comment]
merged to 0.11

**Pull request closed without merging**
