### PR TITLE
KAFKA-3378; Follow-up to ensure we `finishConnect` for immediately connected keys

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
@llowrey spotted a problem in #1094, this PR is an attempt at fixing that.

Review by @llowrey and @junrao.

**Comment by llowrey** [comment]
My load tests pass with this change and fail without it.

**Comment by ijuma** [comment]
Thanks for checking @llowrey.

**Comment by junrao** [comment]
Thanks for the patch. LGTM.

**Pull request closed without merging**
