### PR TITLE
KAFKA-4590: SASL/SCRAM system tests

### PR DESCRIPTION
**Pull request by rajinisivaram**
Runs sanity test and one replication test using SASL/SCRAM.

### CODE REVIEW

**Comment by rajinisivaram** [comment]
Started a system test run here: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/658/

**Comment by rajinisivaram** [comment]
System test run https://jenkins.confluent.io/job/system-test-kafka-branch-builder/658/ has three unrelated failures - one replication test (KAFKA-4558) and two stream tests. The SASL/SCRAM tests from this PR have passed.

**Review by ewencp — APPROVED** [review]
This LGTM, but probably @ijuma or @junrao should also take a look. One question I have is if replication test is the best test to use for validating interbroker protocol -- I think that one is relatively expensive and we probably have cheaper tests that at lest validate that data is replicated. Since we're already parameterizing for interbroker protocol there it's probably not a big deal, but would be good to think about this for efficiency reasons.

**Comment by rajinisivaram** [comment]
@ewencp Thank you for the review. Since we are only adding one test (apart from the minimal sanity test) for each new mechanism, replication test felt like a good one since it does a few authentications during restarts. To reduce the time, I am using SCRAM-SHA-256 for client and SCRAM-SHA-512 for inter-broker. So that should test the two protocols as well as the co-existence of both protocols with just one test.

**Comment by ijuma** [comment]
@rajinisivaram, how about changing the following to only test `PLAINTEXT` and `SASL_SSL`?

```python
@matrix(failure_mode=["clean_shutdown", "hard_shutdown", "clean_bounce", "hard_bounce"],
             broker_type=["leader"],
             security_protocol=["PLAINTEXT", "SSL", "SASL_PLAINTEXT", "SASL_SSL"])```

We already do that for `broker_type=["controller"]` and it would "make space" for the new variations added in this PR.

**Review by ijuma — APPROVED** [review]
LGTM, thanks. Can we run the replication tests in the branch builder (since that is the only thing that changed since the last run) to make sure it's all OK still?

**Comment by rajinisivaram** [comment]
@ijuma Thank you for the review. Started test run of replication tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/174/. Will keep an eye on it and add an update later.

**Comment by ijuma** [comment]
System test passed, merged to trunk and 0.10.2.

**Pull request closed without merging**
