### PR TITLE
KAFKA-4901: Make ProduceRequest thread-safe

### PR DESCRIPTION
**Pull request by ijuma**
A more conservative version of the change for the 0.10.2
branch.

Trunk commit: 1659ca1773596b.

### CODE REVIEW

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
The tests that failed are known transient failures that have been fixed in trunk.

**Comment by junrao** [comment]
@ijuma : Thanks for the patch. LGTM. I will let you merge it into 0.10.2.

**Comment by ijuma** [comment]
Thanks, merged to 0.10.2.

**Pull request closed without merging**
