### PR TITLE
KAFKA-17046: Upgrade netty version to 4.1.111.Final

### PR DESCRIPTION
**Pull request by ulysses-you**
The diff with netty 4.1.110.Final is:
https://github.com/netty/netty/compare/netty-4.1.110.Final...netty-4.1.111.Final

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by m1a2st — COMMENTED** [review]
I think that need to update `LICENSE-binary` netty version

**Comment by ulysses-you** [comment]
thank you @m1a2st , update `LICENSE-binary` to the latest version.

**Comment by m1a2st** [comment]
LGTM, Gentle ping @chia7712, PTAL, Thanks

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
@ulysses-you could you please rebase code to trigger QA again?

**Comment by ulysses-you** [comment]
thank you @chia7712  for the reminder, rebased.

**Review by m1a2st — APPROVED** [review]

**Comment by ulysses-you** [comment]
thank you @m1a2st @chia7712 !

**Pull request merged**
