### PR TITLE
KAFKA-4810: Kafka Connect SchemaBuilder unset fields validation fix

### PR DESCRIPTION
**Pull request by vitaly-pushkar**
https://issues.apache.org/jira/browse/KAFKA-4810
> Currently SchemaBuilder is strict when checking that certain fields have not been set yet (e.g. version, name, doc). It just checks that the field is null. This is intended to protect the user from buggy code that overwrites a field with different values, but it's a bit too strict currently. In generic code for converting schemas (e.g. Converters) you will sometimes initialize a builder with these values (e.g. because you get a SchemaBuilder for a logical type, which sets name & version), but then have generic code for setting name & version from the source schema.

Changed the validation method to not only check if a field is null but also to check if the new value that is being set is the same as the current value of the field.

@ewencp

### CODE REVIEW

**Comment by vitaly-pushkar** [comment]
How come tests on two different JDK and Scala versions don't pass for different reasons and one does pass?

**Comment by vitaly-pushkar** [comment]
@ewencp haven't found a way to rebuild, so had to come up with a commit to push to trigger it 😞 
Anyways, check it, please and tell me if I can make it better :)

**Review by ewencp — COMMENTED** [review]
@vitaly-pushkar This looks good. Perhaps a couple of tests in `SchemaBuilderTest` to validate the behavior?

(If you're up for it as well, I noticed when reviewing this that we don't validate that when we add a field of the same name doesn't exist yet.)

**Comment by ewencp** [comment]
Actually, I take back my comment on validation that we don't use the same field name, seems that is separately being tracked in KAFKA-4855.

**Pull request closed without merging**
