### PR TITLE
Adding ability to provide a prefix for the destination topic name. This ...

### PR DESCRIPTION
**Pull request by pedersen**
...can be used to allow two clusters to mirror to each other without causing a loop.

### CODE REVIEW

**Comment by saahn** [comment]
Is there any reason why this PR has not yet been merged? It's a very simple but useful feature

**Comment by guozhangwang** [comment]
@becketqin Could you take a look and see if this is a valid feature to add?

**Comment by becketqin** [comment]
@saahn I am wondering if this can be done by having a custom message handler? It seems a not ideal to introduce a configuration that can be achieved by another designed feature. The prefix sounds like a pretty specific configuration for mirroring. It is essentially sending messages to another topic, which is one of the use case that message handler is designed for. So it might be better if we can leverage the current design without introducing an additional configuration which is to address a specific need.

**Comment by soenkeliebau** [comment]
The same functionality can be achieved by using a custome message handler, yes.
There is an example implementation available [here](https://github.com/opencore/mirrormaker_topic_rename/blob/master/src/main/java/com/opencore/RenameTopicHandler.java). 
Also, with MirrorMaker 2.0 drawing close to being finished, I think this can be closed.

**Comment by hachikuji** [comment]
Closing this since it is addressed by MM2. Please reopen if you believe it is still valuable.

**Pull request closed without merging**
