### PR TITLE
KAFKA-16894: Define group.version=2

### PR DESCRIPTION
**Pull request by AndrewJSchofield**
This PR defines version 2 of the group.version feature. It will control the availability of share groups.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by apoorvmittal10 — APPROVED** [review]
Thanks for the PR. LGTM!

**Comment by omkreddy** [comment]
There are few test failures

**Comment by AndrewJSchofield** [comment]
I'm researching whether what I'm trying to do here is even possible. Should have answers shortly.

**Comment by AndrewJSchofield** [comment]
@omkreddy We need KIP-1014 (under discussion) to do this. I'll leave this PR in draft state for now. We need to find another way to turn KIP-932 on and off for now.

**Pull request closed without merging**
