### PR TITLE
MINOR: Fix duplicate condition in ReadOnlyWindowStoreStub

### PR DESCRIPTION
**Pull request by wernerdv**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wernerdv** [comment]
@showuon PTAL

**Comment by wernerdv** [comment]
@chia7712 Could you take a look at the minor fixes?

**Review by m1a2st — APPROVED** [review]
LGTM

**Review by chia7712 — APPROVED** [review]
LGTM

open https://issues.apache.org/jira/browse/KAFKA-17854 for more tests

**Pull request merged**
