### PR TITLE
MINOR; Provide lowest and highest supported versions alongside with the schema in the auto-generated protocol

### PR DESCRIPTION
**Pull request by dajac**
At the moment, the only way available to get the supported versions of a Message is to look at the number of defined schemas, assuming that the lowest version is 0. This PR adds static constants with the versions alongside with the schemas.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
@cmccabe What do you think about adding those?

**Review by abbccdda — COMMENTED** [review]
I think we need a small KIP, since it is public facing.

**Comment by ijuma** [comment]
This is internal, so doesn't need a KIP. But I think there's a PR that does this already: https://github.com/apache/kafka/pull/7226/files

Can you check @dajac?

**Comment by dajac** [comment]
@ijuma Indeed, it looks similar except that that PR works only for `REQUEST` or `RESPONSE` types. In my case, I wanted to have a way to get versions for a `DATA` type to avoid having to do this: https://github.com/apache/kafka/pull/8897/files#diff-bad29ccb1aba700e1badeff62f1a86b7R47.

We may be able to generalize the idea or to define a registry for `DATA` types. Thoughts?

**Comment by cmccabe** [comment]
Yeah, this doesn't need a KIP, as @ijuma said.

Looking at the use-case here, I'm +1 on this change.  LGTM.

By the way, #9002 adds the concept of pluggable message type enums.  But I think that's overkill for what you're doing here.

**Comment by cmccabe** [comment]
I think this is not a duplicate of #7226, since as @dajac said, that one is more about simplying `ApiKeys.java`, whereas @dajac 's use case is for a non-request type.

**Pull request merged**
