### PR TITLE
KAFKA-2820: Remove log threshold on appender in tools-log4j.properties

### PR DESCRIPTION
**Pull request by granders**
Removed a config in tools-log4j.properties which prevented certain service classes from logging at TRACE level.

### CODE REVIEW

**Comment by granders** [comment]
I tested this by setting `log_level = "TRACE"` in `mirror_maker.py` and running the following test with and without the update to `tools-log4j.properties`:

```
ducktape tests/kafkatest/tests/mirror_maker_test.py::TestMirrorMakerService.test_simple_end_to_end --parameters '{"new_consumer": false}'
```

TRACE level logging is visible in mirror maker log with this change, but only DEBUG level logging is visible without it, which is expected.

**Comment by ewencp** [comment]
@granders Should we get rid of other instances of this?

```
$ git grep [.]Threshold
tests/kafkatest/services/performance/templates/tools_log4j.properties:log4j.appender.FILE.Threshold=debug
tests/kafkatest/services/templates/connect_log4j.properties:log4j.appender.FILE.Threshold=debug
tests/kafkatest/services/templates/tools_log4j.properties:log4j.appender.FILE.Threshold=debug
```

**Comment by granders** [comment]
@ewencp Aha! Very good point sir

**Comment by gwenshap** [comment]
LGTM

**Pull request closed without merging**
