### PR TITLE
KAFKA-5123 Refactor ZkUtils readData* methods

### PR DESCRIPTION
**Pull request by baluchicken**

### CODE REVIEW

**Comment by baluchicken** [comment]
@ijuma if you have time can you please review

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6209/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
Thanks for the PR. Note that we are in the process of introducing a new `ZookeeperClient` (https://github.com/apache/kafka/pull/3427/files), so probably best not to submit new `ZkUtils` refactoring PRs.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6193/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by baluchicken** [comment]
Okey, I will try to understand how the new Zk client which uses vanilla zk api works, and maybe help in the refactor after the merge:)

**Pull request closed without merging**
