### PR TITLE
KAFKA-15556: Remove NetworkClientDelegate methods isUnavailable, maybeThrowAuthFailure, and tryConnect

### PR DESCRIPTION
**Pull request by Phuc-Hong-Tran**
Change:

*Refactored `AbstractFetch` so only `Fetcher` will check for node status when creating fetch requests.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Phuc-Hong-Tran** [comment]
@kirktrue, Can I have a review for this PR? Thanks in advance.

**Comment by Phuc-Hong-Tran** [comment]
@philipnee PTAL, the context for this one is here: https://github.com/apache/kafka/pull/14406#discussion_r1338972414

**Comment by philipnee** [comment]
thanks. seems like all test aborted, let me reopen the pr to trigger the tests

**Comment by Phuc-Hong-Tran** [comment]
hm let's me try again, the ci failed to start it seems

**Comment by Phuc-Hong-Tran** [comment]
@philipnee do you think I should close this one and open a new PR instead? the ci doesn't seem to restart after we close and re-open this PR

**Pull request closed without merging**
