### PR TITLE
KAFKA-13590: rename InternalTopologyBuilder#topicGroups

### PR DESCRIPTION
**Pull request by sayantanu-dey**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Kvicii** [comment]
@sayantanu-dey hi, I wonder where the name came from, it's really a good name in context.

**Comment by sayantanu-dey** [comment]
> @sayantanu-dey hi, I wonder where the name came from, it's really a good name in context.

@Kvicii hi, thanks, I just saw that the function was returning the Map of subtopology to TopicInfo, so I thought of having that as the name :)

**Review by Kvicii — COMMENTED** [review]
I think it's an appropriate name

**Review by ableegoldman — APPROVED** [review]
Awesome, thanks for picking this up! All test failures are unrelated or priorly flaky, will go ahead with the merge

**Pull request merged**
