### PR TITLE
KAFKA-10787: Apply spotless to `raft`  module

### PR DESCRIPTION
**Pull request by gongxuanzhang**
This PR is sub PR from https://github.com/apache/kafka/pull/16097.
It is part of a series of changes to progressively apply [spotless plugin(import-order)] across all modules. In this step, the plugin is activated in the`raft` module.

## Module and history 

> Please see the table below for the historical changes related to applying the Spotless plugin

| module        | apply |  related PR  |
| -------------- | ------------------- | ------------------- |
| :clients | ❌    | future |
| :connect:api | ✅    | https://github.com/apache/kafka/pull/16299 |
| :connect:basic-auth-extension | ✅    | https://github.com/apache/kafka/pull/16299 |
| :connect:file | ✅    | https://github.com/apache/kafka/pull/16299 |
| :connect:json | ✅   | https://github.com/apache/kafka/pull/16299 |
| :connect:mirror | ✅   | https://github.com/apache/kafka/pull/16299 |
| :connect:mirror-client | ✅   | https://github.com/apache/kafka/pull/16299 |
| :connect:runtime | ❌    | future |
| :connect:test-plugins | ✅   | https://github.com/apache/kafka/pull/16299 |
| :connect:transforms | ✅   | https://github.com/apache/kafka/pull/16299 |
| :core | ❌    | future |
| :examples |  ✅    | https://github.com/apache/kafka/pull/16296 |
| :generator |  ✅     | https://github.com/apache/kafka/pull/16296 |
| :group-coordinator:group-coordinator-api | ✅   | https://github.com/apache/kafka/pull/16298 |
| :group-coordinator | ✅  | https://github.com/apache/kafka/pull/16298 |
| :jmh-benchmarks |  ✅     | https://github.com/apache/kafka/pull/16296 |
| :log4j-appender |  ✅     | https://github.com/apache/kafka/pull/16296 |
| :metadata | ✅     | https://github.com/apache/kafka/pull/16297 |
| :server | ✅     | https://github.com/apache/kafka/pull/16297 |
| :shell |  ✅     | https://github.com/apache/kafka/pull/16296 |
| :storage | ✅     | https://github.com/apache/kafka/pull/16297 |
| :storage:storage-api | ✅     | https://github.com/apache/kafka/pull/16297 |
| :streams | ❌    | future |
| :streams:examples |  ❌   | future |
| :streams:streams-scala | ❌    | future |
| :streams:test-utils | ❌    | future |
| :streams:upgrade-system-tests-0100 | ❌    | future |
| :streams:upgrade-system-tests-0101 | ❌    | future |
| :streams:upgrade-system-tests-0102 | ❌    | future |
| :streams:upgrade-system-tests-0110 | ❌    | future |
| :streams:upgrade-system-tests-10 | ❌    | future |
| :streams:upgrade-system-tests-11 | ❌    | future |
| :streams:upgrade-system-tests-20 | ❌    | future |
| :streams:upgrade-system-tests-21 | ❌    | future |
| :streams:upgrade-system-tests-22 | ❌    | future |
| :streams:upgrade-system-tests-23 | ❌    | future |
| :streams:upgrade-system-tests-24 | ❌    | future |
| :streams:upgrade-system-tests-25 | ❌    | future |
| :streams:upgrade-system-tests-26 | ❌    | future |
| :streams:upgrade-system-tests-27 | ❌    | future |
| :streams:upgrade-system-tests-28 | ❌    | future |
| :streams:upgrade-system-tests-30 | ❌    | future |
| :streams:upgrade-system-tests-31 | ❌    | future |
| :streams:upgrade-system-tests-32 | ❌    | future |
| :streams:upgrade-system-tests-33 | ❌    | future |
| :streams:upgrade-system-tests-34 | ❌    | future |
| :streams:upgrade-system-tests-35 | ❌    | future |
| :streams:upgrade-system-tests-36 | ❌    | future |
| :streams:upgrade-system-tests-37 | ❌    | future |
| :trogdor |  ✅       | https://github.com/apache/kafka/pull/16296 |
| :raft |  ✅    | https://github.com/apache/kafka/pull/16278 |
| :server-common | ✅    | https://github.com/apache/kafka/pull/16172 |
| :transaction-coordinator | ✅    | https://github.com/apache/kafka/pull/16172 |
| :tools |  ✅   |  https://github.com/apache/kafka/pull/16262  |
| :tools:tools-api | ✅   | https://github.com/apache/kafka/pull/16262 |

## How to test:
We can run `./gradlew spotlessCheck`  check for code that does not meet requirements. 
If we get report that error , we can run `./gradlew spotlessApply` to review my code.
In this PR, all change(exclude `build.gradle`) ` by `spotlessApply`

### CODE REVIEW

**Comment by chia7712** [comment]
@gongxuanzhang could you please the conflicts? BTW, it would be easy to apply the spotless to small/inactive modules first. For example: `log4j-appender`, `trogdor`, `jmh-benchmarks`, `examples`, `shell`, `generator`

**Comment by gongxuanzhang** [comment]
> @gongxuanzhang could you please the conflicts? BTW, it would be easy to apply the spotless to small/inactive modules first. For example: `log4j-appender`, `trogdor`, `jmh-benchmarks`, `examples`, `shell`, `generator`

Right,next PR will apply all of these modules.

**Comment by chia7712** [comment]
@gongxuanzhang please rebase code to fix spotless check :)

**Comment by chia7712** [comment]
@gongxuanzhang you need to fix it again :)

**Comment by gongxuanzhang** [comment]
> @gongxuanzhang you need to fix it again :)

Ok,I'll fix it periodically before merging

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
