### PR TITLE
MINOR: Ensure consumer calls poll() if requests are outstanding

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
cc @ijuma @onurkaraman 

See https://issues.apache.org/jira/browse/KAFKA-4753. It would be good to get this into 0.10.2 as well.

**Comment by ijuma** [comment]
Thanks for the PR, LGTM.

**Comment by onurkaraman** [comment]
I think the patch itself is okay.

I avoided providing the patch because I wanted us to focus instead on solving the real problem of the user-driven fetches. I hope that doesn't get de-prioritized with this mitigation patch.

**Comment by ijuma** [comment]
Because this behaviour regressed in 0.10.2, it makes sense to merge the mitigation ASAP. Larger changes can still be explored, but those will take longer to discuss and implement.

**Comment by hachikuji** [comment]
Merging to trunk and 0.10.2

**Pull request closed without merging**
