### PR TITLE
KAFKA-12930,KAFKA-12929: Deprecate Java 8 and Scala 2.12

### PR DESCRIPTION
**Pull request by ijuma**
Update the readme to note the deprecation. We will also mention the deprecation
in the downloads page when the release is done.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by kkonstantine — APPROVED** [review]
LGTM!

**Review by dajac — APPROVED** [review]
LGTM

**Review by jsancio — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Cherry-picking to 3.0 as well.

**Pull request merged**
