### PR TITLE
KAFKA-8209: Wrong link for KStreams DSL in core concepts doc

### PR DESCRIPTION
**Pull request by bbejeck**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
\cc @MichaelDrogalis

**Comment by MichaelDrogalis** [comment]
👍

**Review by mjsax — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
\cc @JimGalasyn

**Comment by JimGalasyn** [comment]
cc @londoncalling

**Review by londoncalling — APPROVED** [review]
LGTM!

**Comment by bbejeck** [comment]
Merged #6564 into trunk

**Comment by mjsax** [comment]
@bbejeck If the link is broken in older release, we should cherry-pick this to older branches, too. Otherwise, we get the broken link again when we do a bug fix release.

**Comment by bbejeck** [comment]
cherry-picked to 2.2, 2.1, 2.0, 1.1 and 1.0

**Pull request merged**
