### PR TITLE
MINOR: Remove unnecessary license generation code in wrapper.gradle

### PR DESCRIPTION
**Pull request by ijuma**
Newer versions of Gradle handle this automatically.

Credit to @granthenke for the tip.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@ijuma  For testing, I removed `gradlew` and ran `gradle wrapper`. The newly generated `gradlew`  does not have license header. not sure if this is the expected behavior.

**Comment by ijuma** [comment]
@omkreddy Are you sure? The diff for `gradlew` in this PR is after I did the same.

**Comment by ijuma** [comment]
If you look at older branches, we were generating two license headers:

https://github.com/apache/kafka/commit/c19266accbe46ba3fde9d40ee17313e631037463#diff-36ffbd2ea7085cf19547193a7faf30c8

**Review by omkreddy — APPROVED** [review]
@ijuma Thanks for the PR. LGTM.   earlier I was using older version of gradle (5.1.1) to generate wrapper.  it was working with 5.6.2

**Comment by ijuma** [comment]
Makes sense. Thanks for being diligent!

**Pull request merged**
