### PR TITLE
KAFKA-13988:Fix mm2 auto.offset.reset=latest not working

### PR DESCRIPTION
**Pull request by Justinwins**
see https://issues.apache.org/jira/projects/KAFKA/issues/KAFKA-13988?filter=allopenissues

I bumped into the same issue in production env, and i worked around in this way (as PR ).

With `topicPartitionOffsets.forEach(consumer::seek);`,  mm2 seeks all topic partitions even though there have been no commits 
in mm2-offset topic .For example, if A-0 is a topic parition in source target , and mm2 has never synced it before; then mm2 will seek to 0 for A-0, and sync from 0 .

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Justinwins** [comment]
@ryannedolan  could you take a look at this issue ?

**Review by yuz10 — APPROVED** [review]

**Comment by electrical** [comment]
We are hitting the same issue while we want to switch from MM1 to MM2.
Would be great to see this fixed so we can switch over

Thanks!

**Comment by electrical** [comment]
@yuz10 are you able to ping someone to get this moving forward? This must be blocking a lot of people of upgrading existing installs.

Thanks.

**Comment by lvillaca** [comment]
> @yuz10 are you able to ping someone to get this moving forward? This must be blocking a lot of people of upgrading existing installs.
> 
> Thanks.

Our project is also interested in this fix, it's a major issue for us as with the legacy version (for which this feature worked fine) we could not propagate offsets. Thanks!

**Comment by C0urante** [comment]
Superseded by https://github.com/apache/kafka/pull/14567

**Pull request closed without merging**
