### PR TITLE
MINOR:Update versions for streams upgrade tests 1.1

### PR DESCRIPTION
**Pull request by bbejeck**
This is a port of https://github.com/apache/kafka/pull/5605 for the 1.1 branch 

Passing system test on branch builder https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1950/ and 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
@guozhangwang @mjsax @vvcephei

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
LGTM assuming jenkins passed.

**Comment by bbejeck** [comment]
retest this please

**Comment by guozhangwang** [comment]
retest this please

**Comment by mjsax** [comment]
@bbejeck You need to rebase this -- the tests failures are not flaky but due to a bad cherry-pick into 1.1 branch. The fix for this was merged today into 1.1.

**Comment by bbejeck** [comment]
rebased this

**Comment by mjsax** [comment]
Retest this please

Test failure unrelated: `kafka.server.ReplicationQuotasTest.shouldThrottleOldSegments`

**Review by mjsax — APPROVED** [review]
LGTM.

(assuming Jenkins passes)

**Comment by guozhangwang** [comment]
retest this please

**Pull request merged**
