### PR TITLE
KAFKA-3625: TopologyTestDriver must process output for wall-clock-time punctuations and on close()

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
@bbejeck

**Review by guozhangwang — APPROVED** [review]
Nice catch. LGTM (assuming jenkins succeed).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/227/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/230/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/232/

**Comment by mjsax** [comment]
Updates this.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/264/

**Comment by guozhangwang** [comment]
retest this please

**Review by bbejeck — APPROVED** [review]
Thanks, @mjsax LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/280/

**Comment by guozhangwang** [comment]
LGTM.

**Comment by mjsax** [comment]
Retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/309/

**Review by dguy — APPROVED** [review]

**Comment by mjsax** [comment]
Retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/335/

**Comment by guozhangwang** [comment]
I ran and passed unit test locally.

**Comment by guozhangwang** [comment]
retest this please

**Comment by mjsax** [comment]
Rebased. Latest `trunk` seems to be more stable.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `1.1` branch.

**Pull request merged**
