### PR TITLE
MINOR: Enable topic deletion in test configs

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@ijuma  By-default topic deletion is enabled in kafka configs.  It is good to have same default config in tests also.

**Comment by ijuma** [comment]
Agreed. Do we have any tests with the config disabled?

**Comment by omkreddy** [comment]
Only the recently added test ```DeleteTopicsRequestWithDeletionDisabledTest``` is using this flag.

**Comment by omkreddy** [comment]
retest this please

**Comment by omkreddy** [comment]
@ijuma  Can we merge this PR?

**Review by ijuma — APPROVED** [review]
LGTM

**Pull request merged**
