### PR TITLE
MINOR: Log the reason for coordinator discovery failure

### PR DESCRIPTION
**Pull request by vvcephei**
Adds the exception in the case of logging the "Coordinator discovery failed" message.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Hey @hachikuji , Can you take a quick look at this? You were the last to edit this block.

I was debugging a system test failure, and I see a situation where the broker appears completely healthy, but the Streams consumer just prints `Coordinator discovery failed, refreshing metadata` for several minutes before the test times out.

I didn't see any way to get more information on what exactly the failure was, so I'd like to add the actual causing exception to the log line. Since it's a debug log, this _seems_ ok, but I'm interested in feedback.

Thanks!

**Comment by vvcephei** [comment]
The java 14 test failure is unrelated and fixed in https://github.com/apache/kafka/pull/8748

**Review by abbccdda — APPROVED** [review]

**Comment by vvcephei** [comment]
Java 11 build timed out.

**Comment by vvcephei** [comment]
Thanks for the review, @abbccdda !

**Pull request merged**
