### PR TITLE
MINOR: Remove duplicate definition about 'the' from kafka project

### PR DESCRIPTION
**Pull request by wenbingshen**
As the title.Here is a duplicate definition about 'the'?

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@wenbingshen thanks for your patch. Could you fix all similar issues? see attachment.

截圖 2021-03-22 下午1 43 29

**Comment by wenbingshen** [comment]
> @wenbingshen thanks for your patch. Could you fix all similar issues? see attachment.
> 
> 截圖 2021-03-22 下午1 43 29

@chia7712 Thanks for your comments.I searched the kafka project and fixed all the duplicate definition about 'the'.Please review again.

**Review by chia7712 — COMMENTED** [review]
nit: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java#L1026

**Comment by wenbingshen** [comment]
> nit: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java#L1026

Very sorry. I'm always too careless. Thanks for your pointing. :)

**Comment by chia7712** [comment]
> Very sorry. I'm always too careless. Thanks for your pointing. 

Don't worry :)

**Comment by wenbingshen** [comment]
> > Very sorry. I'm always too careless. Thanks for your pointing.
> 
> Don't worry :)

Thanks. :)

**Review by chia7712 — APPROVED** [review]
@wenbingshen thanks for patch. LGTM :)

**Pull request merged**
