### PR TITLE
MINOR: add retry to system test curl commands

### PR DESCRIPTION
**Pull request by vvcephei**
Adds a retry to curl, using the built-in exponential backoff mechanism.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Recently, I have seen a few remote (aws-over-vagrant) system tests fail during setup due to this error:

```
    worker15: + curl -O https://s3-us-west-2.amazonaws.com/kafka-packages/kafka_2.11-1.1.1.tgz
    worker15:   % Total    % Received % Xferd  Average
    worker15:  Speed   Time    Time     Time  
    worker15: Current
    worker15:                                  Dload  Upload   Total   Spent    Left  
    worker15: Speed
  0     0    0     0    0     0      0      0 --:--:--
    worker15:  --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--
    worker15: :--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--   
    worker15:   0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:-
    worker15: -     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--   
    worker15:   0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--
    worker15:      0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--    
    worker15:  0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:-- 
    worker15:     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:-- 
    worker15:     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--   
    worker15:   0
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
    worker15: curl: (35) Unknown SSL protocol error 
    worker15: in connection to s3-us
    worker15: -west-2.amazonaws.com:443 
```

The problem is transient, so it seems to be an issue with the SSL negotiation on the server side. Some reading has suggested it could also be due to networking issues when running inside of containers, or over VPNs, etc., etc.

I didn't find anything obvious we could do about it, so it seems worthwhile to at least attempt to avoid failing the whole run over a transient non-problem.

**Comment by vvcephei** [comment]
System test meta run: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4001/console

**Comment by kkonstantine** [comment]
@vvcephei `--retry-all-error` is not an option that the current curl version recognizes. The system tests fail early on that error.

**Review by kkonstantine — COMMENTED** [review]
@vvcephei `--retry-all-error` is not an option that the current curl version recognizes. The system tests fail early on that error.

**Comment by vvcephei** [comment]
Ah, Thanks @kkonstantine ,

I see that now:
```
17:42:20     worker5: + curl --retry-all-errors --retry 5 -s -L https://s3-us-west-2.amazonaws.com/kafka-packages/jdk-8u202-linux-x64.tar.gz -o /tmp/jdk-8u202-linux-x64.tar.gz
17:42:20     worker5: curl: option --retry-all-error
17:42:20     worker5: s: is unknown
17:42:20     worker5: curl: try 'curl --help' or 'c
17:42:20     worker5: url --manual' for more information
```

**Comment by vvcephei** [comment]
new run: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4002/

**Comment by vvcephei** [comment]
Looks like that one worked: http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2020-07-01--001.1593607328--vvcephei--minor-vagrant-curl-retry--8532458b7/report.html

**Review by abbccdda — APPROVED** [review]
LGTM

**Comment by abbccdda** [comment]
Failed tests should be non-related as we only change on system test run.

**Review by kkonstantine — APPROVED** [review]
LGTM. Thanks @vvcephei

**Comment by vvcephei** [comment]
Thanks @kkonstantine and @abbccdda !

**Pull request merged**
