### PR TITLE
MINOR: log reason for fatal error in locking state dir

### PR DESCRIPTION
**Pull request by vvcephei**
Log the reason for fatal errors while locking the state directory.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
LGTM.

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
waiting for the build to finish for merging

**Comment by vvcephei** [comment]
Thanks, all!

**Comment by vvcephei** [comment]
Unrelated test failures:

kafka.log.LogCleanerIntegrationTest.testIsThreadFailed
https://builds.apache.org/job/kafka-pr-jdk8-scala2.11/25913/

kafka.api.SaslGssapiSslEndToEndAuthorizationTest.testNoDescribeProduceOrConsumeWithoutTopicDescribeAcl
https://builds.apache.org/job/kafka-pr-jdk11-scala2.13/2710/

Retest this, please.

**Comment by ableegoldman** [comment]
We should cherry-pick this back if possible, maybe back to 2.2?

**Comment by vvcephei** [comment]
Yeah, that would be very nice. Thanks for the doing the archaeology, @ableegoldman !

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.4`, `2.3`, and `2.2` branches.

**Comment by vvcephei** [comment]
Thanks @mjsax , @bbejeck , and @ableegoldman !

**Pull request merged**
