### PR TITLE
KAFKA-7369; Handle retriable errors in AdminClient list groups API

### PR DESCRIPTION
**Pull request by hachikuji**
We should retry when possible if ListGroups fails due to a retriable error (e.g. coordinator loading).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cmccabe** [comment]
LGTM

**Review by guozhangwang — APPROVED** [review]
LGTM

@hachikuji this is not in the scope of this PR, but looking into the `handleResponse()` functions lots of them seem to not follow the throw-and-let-it-handled-by-Call patten, e.g.

DescribeTopicsResult#handleResponse
CreateAclsResult#handleResponse

Should we make a pass over these and make sure they are all covered in a separate PR?

**Comment by hachikuji** [comment]
@guozhangwang Yeah, good call. I'll make a pass and create JIRAs if they don't already exist.

**Comment by omkreddy** [comment]
@hachikuji recently I raised a similar PR  #5578 to handle retraible errors in consumer group related API. Pls take a look.

**Pull request merged**
