### PR TITLE
KAFKA-6225: Adds an option to consume continuously

### PR DESCRIPTION
**Pull request by astubbs**

### CODE REVIEW

**Comment by astubbs** [comment]
IMO this should actually be the default behaviour but it’s an “interface” change. This or setting the timeout to max int and exposing it as configurable.

**Comment by astubbs** [comment]
I think the build failed on jenkins due to this infinite loop warning from FindBugs: https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/8934/findbugsResult/ . And indeed it is an infinite loop by design.
The other option could be to make the timeout in ConsumerPerformance configurable at the cli... Atm it’s hard coded to stop consuming if their haven’t been any new messages in 1 second.

**Comment by astubbs** [comment]
It was pointed out the old consumer code path was invalid due to the iterator pattern that I hadn''t noticed (as opposed to the new consumer poll pattern). It's an option to just remove it from the old consumer code path.

**Comment by rootex-** [comment]
Please check out this PR https://github.com/apache/kafka/pull/4818, gonna be merged soon. And KIP-281: https://cwiki.apache.org/confluence/display/KAFKA/KIP-281%3A+ConsumerPerformance%3A+Increase+Polling+Loop+Timeout+and+Make+It+Reachable+by+the+End+User , and also https://issues.apache.org/jira/browse/KAFKA-6743

**Comment by themaxempire23** [comment]
Hello is this still an issue?

**Pull request closed without merging**
