### PR TITLE
MINOR; Fix UpdateMetadataRequestTest.testVersionLogic's assertions

### PR DESCRIPTION
**Pull request by dajac**
`UpdateMetadataRequestTest.testVersionLogic`'s assertions must verify the deserialized request.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
@chia7712 Could you take a look at this one please?

**Review by chia7712 — APPROVED** [review]
Thanks for this patch. LGTM

**Comment by dajac** [comment]
retest this please

**Comment by dajac** [comment]
ok to test

**Comment by dajac** [comment]
Test failures not related, merging to trunk.

**Pull request merged**
