### PR TITLE
KAFKA-5994: Log ClusterAuthorizationException for all ClusterAction requests

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@hachikuji @ijuma  This PR  raises ClusterAuthorizationException for LeaderAndIsrRequest, StopReplicaRequest, UpdateMetadataRequest  requests incase of cluster permission issues . We are currently doing this in ControlledShutdownRequest, WriteTxnMarkersRequest requests. This will help us to debug cluster permission issues during server startup.

**Comment by omkreddy** [comment]
@hachikuji Please take a look at this PR.

**Comment by ijuma** [comment]
@omkreddy, isn't this in the authorizer log either way?

**Comment by omkreddy** [comment]
@ijuma  yes, all denials will be logged in authorizer log. 

Normally ClusterAction permission issues will come up only during Cluster deployment/expansion.
So these error logs (server.log) will useful to quickly identify the  server startup issues .

As of now, we are already logging for couple of requests. Since all above are inter-broker requests , I thought it will be good to log permission issues in server.log for all ClusterAction requests.

**Comment by omkreddy** [comment]
@ijuma  @hachikuji  What do you think about this minor change?

**Comment by omkreddy** [comment]
@hachikuji any thoughts on this PR.

**Review by rajinisivaram — APPROVED** [review]
@omkreddy Thanks for the PR, LGTM. The PR needs rebasing.

**Comment by omkreddy** [comment]
@rajinisivaram Thanks for the review. Updated the PR. Please take a look.

**Review by rajinisivaram — APPROVED** [review]
@omkreddy Thanks for updating, LGTM

**Pull request closed without merging**
