### PR TITLE
MINOR: Rename and change package of async ZooKeeper classes

### PR DESCRIPTION
**Pull request by ijuma**
- kafka.controller.ZookeeperClient -> kafka.zookeeper.ZooKeeperClient
- kafka.controller.ControllerZkUtils -> kafka.zk.KafkaZkClient
- kafka.controller.ZkData -> kafka.zk.ZkData
- Renamed various fields to match new names and for consistency
- A few clean-ups in ZkData
- Document intent

### CODE REVIEW

**Comment by ijuma** [comment]
cc @onurkaraman

**Comment by ijuma** [comment]
With regards to `KafkaControllerZkUtils`, I was thinking we could call it `KafkaZkClient` and move it to the `utils` package. The idea being that we should always use `KafkaZkClient` in our codebase which provides Kafka-specific methods while `ZooKeeperClient` is a generic ZooKeeperClient with support for pipelining. If you agree @onurkaraman, I could include it in this PR or we could do it in a separate one.

**Comment by onurkaraman** [comment]
@ijuma the suggestion sounds fine to me.

`ZkData.scala` should also probably move into the `utils` package.

A high-level review on the PR: you should do a case-sensitive search on `ZookeeperClient` and `zookeeperClient` since it looks like there are a few stragglers.

**Comment by ijuma** [comment]
About `KafkaControllerZkUtils`, I'm having second thoughts about having a monolithic class instead of per component, so leaving that for another PR.

**Comment by onurkaraman** [comment]
I agree that `KafkaControllerZkUtils` probably needs some more thought. So I think it's best for this PR to be whatever is there now in addition to moving ZkData.scala to `utils`.

**Comment by ijuma** [comment]
I think we should leave `ZkData` for another PR too. :) @junrao, does this seem OK to you?

**Comment by junrao** [comment]
@ijuma : Thanks for the patch. The patch looks good. Could we also move kafka.controller.KafkaControllerZkUtils to kafka.zk.KafkaZkClient and kafka.controller.ZkData to kafka.zk.ZkData? KafkaControllerZkUtils references classes like LeaderIsrAndControllerEpoch, which is in controller. But that may be ok for now.

**Comment by ijuma** [comment]
@junrao OK, let's do that as a first step. Updated the PR.

**Comment by junrao** [comment]
@ijuma : Thanks for the patch. LGTM. Just one minor comment. Should kafka.zookeeper.ZooKeeperClient be kafka.zk.ZooKeeperClient to be consistent with others? Once that's addressed, you can merge the PR.

**Comment by ijuma** [comment]
@junrao I wanted to keep `ZooKeeperClient` separate from `KafkaZkClient`. The former is a general ZooKeeper client that doesn't have Kafka specific logic. It could be in its own library/module, but we use a package for simplicity. It should not depend on any other package aside from `utils`.

`KafkaZkClient`, on the other hand, adds methods specific to `Kafka` and should not be in the same package. I agree that the difference between `kafka.zk` and `kafka.zookeeper` packages is not obvious, so happy to take suggestions if you or @onurkaraman have them.

**Comment by omkreddy** [comment]
LGTM

**Comment by junrao** [comment]
@ijuma : Thanks for the explanation. We can keep the patch as it is then. LGTM

**Pull request closed without merging**
