### PR TITLE
KAFKA-3522: TopologyTestDriver should only return custom stores via untyped getStateStore() method

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna @abbccdda

**Review by ableegoldman — APPROVED** [review]
LGTM but build failed with some git error?

**Comment by mjsax** [comment]
Java8 failed. Java11 passed. Retest this please.

**Review by bbejeck — APPROVED** [review]
Thanks for the quick turnaround on this @mjsax LGTM

**Comment by bbejeck** [comment]
waiting on green jenkins to merge

**Comment by bbejeck** [comment]
Merged #6756 to trunk

**Pull request merged**
