### PR TITLE
add toString method

### PR DESCRIPTION
**Pull request by chenzhongyu11**
The toString method is missing.

### CODE REVIEW

**Comment by showuon** [comment]
@chenzhongyu11 , thanks for the PR. Could you elaborate more about why we should add `toString` into  `SyncGroupResponse` class? Did you see any issues? Thanks.

**Comment by chenzhongyu11** [comment]
> @chenzhongyu11 , thanks for the PR. Could you elaborate more about why we should add `toString` into `SyncGroupResponse` class? Did you see any issues? Thanks.
In the code below，syncResponse will be printed as ‘org.apache.kafka.common.requests.SyncGroupResponse@770d3326’.So, I added the toString method to SyncGroupResponse, just like any other protocol.

image

**Comment by dajac** [comment]
@chenzhongyu11 Thanks for the PR. I see that the issue is already fixed in trunk. Is that correct? 2.5 is pretty old, I don’t think that we will ever release a minor release for it. Did you consider upgrading your client?

**Comment by showuon** [comment]
Thanks for @dajac 's reminder. Yes, this was already fixed in the latest client. Thanks.

**Comment by chenzhongyu11** [comment]
> @chenzhongyu11 Thanks for the PR. I see that the issue is already fixed in trunk. Is that correct? 2.5 is pretty old, I don’t think that we will ever release a minor release for it. Did you consider upgrading your client?

 Thanks for replying to me.I also reviewed the code for latest branch.I will close this pr.

**Pull request closed without merging**
