### PR TITLE
KAFKA-15594: Add version 3.6 to Kafka Streams system tests

### PR DESCRIPTION
**Pull request by mjsax**
Needs to be cherry-picked to `3.7` branch

### CODE REVIEW

**Review by wcarlson5 — APPROVED** [review]

**Comment by mjsax** [comment]
Triggered system test run: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/6021/

**Comment by mjsax** [comment]
System test run failed due to buggy test setup. New PR to fix it: https://github.com/apache/kafka/pull/15157

**Comment by mjsax** [comment]
Merged #15157 and rebased this PR afterwards.

Re-triggered system test run: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/6025/

**Comment by mjsax** [comment]
A few tests failed: `streams_standby_replica_test` (both runs) and multiple `streams_cooperative_rebalance_upgrade_test` (0.11, 1.0, 1.1, 2.2, 2.3) plus:

```
Module: kafkatest.tests.streams.streams_upgrade_test
Class:  StreamsUpgradeTest
Method: test_rolling_upgrade_with_2_bounces
Arguments:
{
  "from_version": "3.5.1",
  "to_version": "3.8.0-SNAPSHOT"
}
```
and
```
Module: kafkatest.tests.streams.streams_upgrade_test
Class:  StreamsUpgradeTest
Method: test_rolling_upgrade_with_2_bounces
Arguments:
{
  "from_version": "3.6.0",
  "to_version": "3.8.0-SNAPSHOT"
}
```

Re-triggered to check for flakiness: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/6030/

**Comment by mjsax** [comment]
Other system test fixed got merged. Rebased this PR and retriggered system test run: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/6037/

**Comment by mjsax** [comment]
Only `streams.streams_standby_replica_test` failed -- we know that it's broken and have already a PR to fix it: https://github.com/apache/kafka/pull/15217

Not sure why Jenkins did fail though -- retriggered.

**Comment by mjsax** [comment]
`trunk` was broken -- rebased. Also re-triggered system tests just to be sure: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/6038/

**Comment by mjsax** [comment]
On `StreamsStandbyTask ` failed, which was fixed recently via https://github.com/apache/kafka/pull/15217. Merging.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `3.7` branch.

**Pull request merged**
