### PR TITLE
KAFKA-7224: [WIP] Persistent Suppress [WIP]

### PR DESCRIPTION
**Pull request by vvcephei**
WIP - no need to review. I'm just getting a copy of this onto github.

I'll call for reviews once I think it's ready.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rthadaniplume** [comment]
@vvcephei Is there any progress on the PR, it seems like its been a while since the last update. Anything I can do to pick this up and continue? Currently the 15 minute suppression given our volume of data will definitely cause memory bottlenecks. I have 2 choices implement my own processor that does the suppression in the persistent kv store which I'd rather not do or the second one is to get this working by contributing to this PR.

**Comment by marcospassos** [comment]
Hey guys, we are on the same page as @rthadaniplume here. Some news on this?

**Comment by vvcephei** [comment]
Hey @rthadaniplume and @marcospassos ,

Sorry for the slow reply. I didn't realized I'd left the PR open and the ticket in progress. I intended to shelve this work until there was some concrete ask for it.

After the implementation in this PR, I ran some benchmarks, and I found that the performance with rocksdb-backed suppression was _absolutely terrible_ I think it was like two orders of magnitude slower. Much slower even than regular rocksdb-backed persistent store operations. The key problem was that the suppression buffer relies on scans, and scans in RocksDB are absurdly slow. I looked into rocksdb optimizations, but didn't find anything remotely promising.

It might be the case that you'd be fine with a huge performance penalty in exchange for the "final result" semantics, but it seems like it would have to be a very niche use case: low throughput (so the performance is tolerable) but large amounts of intermediate results (so that the in-memory buffer wouldn't be sufficient).

I wasn't confident that such a use case would actually exist, and on the other hand, it felt like a massive potential for frustration to drop such a poor-performing component into the codebase, even if I were to pepper the javadocs with warnings about it. So I decided just to pause work on it pending more information. If you want to take it over and see if you can find a way to implement it that works for you, you're more than welcome to, @rthadaniplume ! I'd be happy to provide advice, reviews, whatever you need.

The PR is so out-of-date that it's probably unrecoverable at this point, so I'll just close it. We should continue this discussion on the ticket. I'll copy this comment over there. Sorry for the lack of information.

-John

**Comment by vvcephei** [comment]
Note, I've closed this PR to indicate that I don't plan to continue work on it. However, the final state of it was functional, so if someone wanted to pick up where I left off, you could use it as inspiration. Although, at this point, I'd recommend just re-implmenting the same changes on the current trunk, which has changed substantially since this work was done.

**Comment by Maatary** [comment]
Would be nice to have someone resume on this. Feature is very critical and important. It would solve a rather very critical scenario, especially if implemented together with https://cwiki.apache.org/confluence/display/KAFKA/KIP-424%3A+Allow+suppression+of+intermediate+events+based+on+wall+clock+time

**Pull request closed without merging**
