### PR TITLE
MINOR: Add Jenkinsfile to 2.1

### PR DESCRIPTION
**Pull request by vvcephei**
Add a Jenkinsfile for the 2.1 branch so PRs can be built

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
This is the last one.

See also #9471 and #9472 and #9474 

@ijuma @jolshan @mumrah , are any of you able to review this as well?

**Review by jolshan — APPROVED** [review]
LGTM

**Review by omkreddy — APPROVED** [review]
LGTM

**Comment by vvcephei** [comment]
Thanks for the reviews, all!

**Pull request merged**
