### PR TITLE
Add 3.5.0 and 3.4.1 to system tests

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by showuon — APPROVED** [review]
Thanks for helping adding 3.4.1. :)

**Comment by mimaison** [comment]
@mjsax @vvcephei Can you upload the 3.5.0 artifacts to the Confluent S3 bucket as per the [release instructions](https://cwiki.apache.org/confluence/display/KAFKA/Release+Process#ReleaseProcess-Afterthevotepasses)? And verify the 3.4.1 artifacts are there too

**Comment by mimaison** [comment]
I still don't see the packages in the S3 bucket, so re-pinging @mjsax @vvcephei

**Comment by mjsax** [comment]
Sorry for the delay. Uploaded. Can you verify?

**Comment by mimaison** [comment]
Thanks @mjsax, I can now see 3.5.0 and 3.4.1 in https://s3-us-west-2.amazonaws.com/kafka-packages

**Pull request merged**
