### PR TITLE
KAFKA-6145: KIP 441 remove balance factor

### PR DESCRIPTION
**Pull request by ableegoldman**
Removes this config and its usage from the balanced assignor (effectively setting it to 1)

### CODE REVIEW

**Comment by ableegoldman** [comment]
@vvcephei @cadonna

**Review by vvcephei — APPROVED** [review]
LGTM. Thanks, @ableegoldman !

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
test this please

**Comment by vvcephei** [comment]
Failing test org.apache.kafka.streams.integration.GlobalKTableIntegrationTest.shouldKStreamGlobalKTableLeftJoin is already under investigation.

**Pull request merged**
