### PR TITLE
MINOR: Improve topic management instructions for Kafka Streams examples

### PR DESCRIPTION
**Pull request by miguno**

### CODE REVIEW

**Comment by miguno** [comment]
Please review any of @enothereska @guozhangwang @mjsax, with Cc: to @ijuma

**Review by mjsax — APPROVED** [review]
LGTM

**Comment by enothereska** [comment]
LGTM

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by ijuma** [comment]
Is this just for trunk or also 0.10.2?

**Comment by ijuma** [comment]
Merged to trunk and 0.10.2 since it merged cleanly and it's just doc updates.

**Comment by miguno** [comment]
Thanks @ijuma.  Yes, it should go (have gone) into trunk and 0.10.2 -- just what you did. :-)

**Pull request closed without merging**
