### PR TITLE
MINOR: Store metrics scope, total metrics

### PR DESCRIPTION
**Pull request by guozhangwang**
1. Rename metrics scope of rocksDB window and session stores; also modify the store metrics accordingly with guidance on its correlations to `metricsScope`.

2. Add the missing `total` metrics for per-thread, per-task, per-node and per-store sensors.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
One thing yet to be added is in the upgrade section, I will wait and see if RC0 2.0 made it or not: if RC0 succeeds, I will add it to 2.1 upgrade section. Otherwise I'll do it in piggybacked 2.0 branch.

@mjsax @vvcephei @bbejeck

**Review by bbejeck — APPROVED** [review]
Thanks @guozhangwang LGTM

**Review by vvcephei — APPROVED** [review]
LGTM! I suppose we'll mention in the release notes that we changed the rocksdb store metric names?

**Comment by guozhangwang** [comment]
> LGTM! I suppose we'll mention in the release notes that we changed the rocksdb store metric names?

yes, that's my plan as commented above.

**Review by mjsax — APPROVED** [review]
LGMT.

**Pull request merged**
