### PR TITLE
MINOR: Small logging fixes in AbstractCoordinator

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
@vahidhashemian @omkreddy Can you take a look at this tiny PR? Thanks

**Comment by mimaison** [comment]
retest this please

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch.

**Comment by hachikuji** [comment]
retest this please

**Pull request merged**
