### PR TITLE
KAFKA-14035: Fix NPE caused by missing null check in SnapshottableHashTable::mergeFrom()

### PR DESCRIPTION
**Pull request by niket-goel**
Also adds a simple test case that fails without the check

### CODE REVIEW

**Review by hachikuji — APPROVED** [review]
Thanks, LGTM

**Comment by iblislin** [comment]
Hi,

I still ran into the issue of NPE on a 3.3.1 cluster with 3 nodes.

The actual line throwing the NPE is here: https://github.com/apache/kafka/blob/3.3.1/metadata/src/main/java/org/apache/kafka/timeline/SnapshottableHashTable.java#L125

But I cannot speak in Java, no idea about the root cause.

The traceback:
```
kafka-k3-1  | [2023-01-04 06:23:20,276] ERROR Encountered fatal fault: exception while renouncing leadership (org.apache.kafka.server.fault.ProcessExitingFaultHandler)
kafka-k3-1  | java.lang.NullPointerException
kafka-k3-1  |   at org.apache.kafka.timeline.SnapshottableHashTable$HashTier.mergeFrom(SnapshottableHashTable.java:125)
kafka-k3-1  |   at org.apache.kafka.timeline.Snapshot.mergeFrom(Snapshot.java:68)
kafka-k3-1  |   at org.apache.kafka.timeline.SnapshotRegistry.deleteSnapshot(SnapshotRegistry.java:236)
kafka-k3-1  |   at org.apache.kafka.timeline.SnapshotRegistry$SnapshotIterator.remove(SnapshotRegistry.java:67)
kafka-k3-1  |   at org.apache.kafka.timeline.SnapshotRegistry.revertToSnapshot(SnapshotRegistry.java:214)
kafka-k3-1  |   at org.apache.kafka.controller.QuorumController.renounce(QuorumController.java:1232)
kafka-k3-1  |   at org.apache.kafka.controller.QuorumController.access$3300(QuorumController.java:150)
kafka-k3-1  |   at org.apache.kafka.controller.QuorumController$QuorumMetaLogListener.lambda$handleLeaderChange$3(QuorumController.java:1076)
kafka-k3-1  |   at org.apache.kafka.controller.QuorumController$QuorumMetaLogListener.lambda$appendRaftEvent$4(QuorumController.java:1101)
kafka-k3-1  |   at org.apache.kafka.controller.QuorumController$ControlEvent.run(QuorumController.java:496)
```

**Comment by iblislin** [comment]
There are related discussions on StackOverflow: https://stackoverflow.com/questions/74679400.

**Comment by hoangphuocbk** [comment]
@iblislin, I had same problem. Did your solution work?

**Comment by iblislin** [comment]
@hoangphuocbk yeah, that patch works fine for me. I have a kraft cluster with that patch eanbled up for 45 days already.

**Comment by showuon** [comment]
@iblislin @hoangphuocbk , this issue will be fixed in v3.4.1 and v3.5.0 via this patch: https://github.com/apache/kafka/pull/13653 . Thanks for reporting.

**Pull request merged**
