### PR TITLE
MINOR: Fix JavaDoc for StreamsConfig.PROCESSING_GUARANTEE_CONFIG

### PR DESCRIPTION
**Pull request by leigh-perry**
The contribution is my original work and I license the work to the project under the project's open source licence.

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
LGTM.

Thanks for the PR!

**Review by mjsax — APPROVED** [review]
LGTM.

Thanks for the PR!

Call for merging @guozhangwang @dguy

**Review by dguy — APPROVED** [review]
Thanks @leigh-perry, LGTM

**Comment by dguy** [comment]
merged to trunk

**Pull request closed without merging**
