### PR TITLE
MINOR: Bump trunk to 3.9.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by jlprat**
Update trunk to 3.9.0-SNAPSHOT if this is going to be the next version or not, it's still unclear.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mimaison — APPROVED** [review]
LGTM!
The plan was to have 4.0 after 3.8. But as there's still a bit of discussion on the dev list, I guess it's ok to bump to 3.9 (at least for now), so you can carry on with the release. It's easy to bump to 4.0 later.

**Review by chia7712 — APPROVED** [review]

**Comment by jlprat** [comment]
All tests failures seem unrelated and actually pass on my machine.

**Comment by jolshan** [comment]
Hmmm. I'm not sure I follow the reasoning for bumping to 3.9 rather than 4.0.

**Comment by jlprat** [comment]
Hi @jolshan 
According to KIP-1012 (https://cwiki.apache.org/confluence/display/KAFKA/KIP-1012%3A+The+need+for+a+Kafka+3.8.x+release) we agreed to have a version in the 3.x series with feature parity on KRaft-Zookeeper. KIP-853 (https://cwiki.apache.org/confluence/display/KAFKA/KIP-853%3A+KRaft+Controller+Membership+Changes) and KIP-966 (https://cwiki.apache.org/confluence/display/KAFKA/KIP-966%3A+Eligible+Leader+Replicas) were identified as must haves. These two, are right now not done and it's not clear we could get them in before code freeze.

For this reason I decided to err on the side precaution and consider there will be a 3.9.0. If we manage to get the desired parity we can always change it to 4.0.0.

Let me know if you have further questions.

**Pull request merged**
