### PR TITLE
Minor: warn if the TGT cannot be renewed.

### PR DESCRIPTION
**Pull request by harshach**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR @harshach. Can you please explain the reason to decrease the log level to warning here?

**Comment by gwenshap** [comment]
@ijuma This makes sense to me - when we log this, everything is still working... we just warn that once the ticket expires, we can no longer renew it again.

**Comment by ijuma** [comment]
@gwenshap That's reasonable. However, we log errors in a number of cases where we fail to refresh (and exit the thread) even though everything is still working (after all, we try to renew a while before expiry as a general rule). So, what makes those other cases different? I guess in this case the expiry could be well into the future, which is indeed different.

LGTM then.

**Comment by harshach** [comment]
@ijuma my bad didn't see your comment earlier. what @gwenshap said :). good to merge than?

**Comment by ijuma** [comment]
Sure, merged to trunk.

**Pull request closed without merging**
