### PR TITLE
KAFKA-4523; Fix crash at shutdown due to the group coordinator attemp…

### PR DESCRIPTION
**Pull request by steveniemitz**
…ting to write to a closed log.

Solution: shut down the group manager before shutting down the log manager to ensure that any delayed operations are done.

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR, this makes sense to me. @hachikuji, does this seem OK to you too?

**Comment by hachikuji** [comment]
Yes, LGTM. Thanks for the patch!

**Comment by steveniemitz** [comment]
hmm, looks like jenkins jammed up here, as well as what looks like a spurious break on 2.12.  Is there a way I can re-kick it?

**Comment by ijuma** [comment]
A bit difficult to test this directly, so LGTM as it is. Merging to trunk.

**Pull request closed without merging**
