### PR TITLE
KAFKA-3817 Follow-up: Avoid forwarding old value if it is null in KTableRepartition

### PR DESCRIPTION
**Pull request by guozhangwang**
Also handle Null value in SmokeTestUtil.

### CODE REVIEW

**Comment by guozhangwang** [comment]
Ping @granders @mjsax @dguy for reviews.

**Comment by guozhangwang** [comment]
Jenkins failure are un-related and is tracked in a separate JIRA.

**Comment by dguy** [comment]
LGTM

**Comment by guozhangwang** [comment]
Merged to trunk and 0.10.0.

**Comment by ijuma** [comment]
@guozhangwang, the agreed process is that we should add a JUnit test whenever a system test uncovers a bug that was not caught by a JUnit test. Is there a reason why that wasn't done here? If not, can we file a JIRA for that please?

**Comment by ijuma** [comment]
Thanks for fixing the system test failure by the way. :)

**Comment by guozhangwang** [comment]
@ijuma Yes I'm working on that right now, while I'm making a pass of all the streams unit tests. I merged this fix just to unblock system test Jenkins build.

**Comment by ijuma** [comment]
Awesome, thanks.

**Pull request closed without merging**
