### PR TITLE
KAFKA-8162: IBM JDK Class not found error when handling SASL

### PR DESCRIPTION
**Pull request by edoardocomar**
Attempt to load the IBM internal class but fallback on loading the Sun
class if the IBM one is not found.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by edoardocomar** [comment]
The JDK11 test is unrelated to my change

**Comment by edoardocomar** [comment]
@vahidhashemian want to take a look ?

**Comment by ijuma** [comment]
Can you please provide context on why this is needed? Please include it as a comment in the code too.

**Comment by edoardocomar** [comment]
@ijuma the reason is this open issue
 https://issues.apache.org/jira/browse/KAFKA-8162
caused by the fact that different IBM jdk versions seem to include different `KrbException` implementations

I added a code comment

**Review by mimaison — APPROVED** [review]

**Review by mimaison — COMMENTED** [review]
Oops did not mean to approve but I'm not able to undo =)

**Comment by edoardocomar** [comment]
@ijuma did I clarify the issue enough ?

**Comment by edoardocomar** [comment]
bump @ijuma @rajinisivaram @vahidhashemian

**Comment by ijuma** [comment]
@mimaison you are a committer now, so you can review and merge this. :)

**Comment by mimaison** [comment]
I had completely forgotten this PR! I'll check with @edoardocomar if this change is still valid with the latest IBM JDK and merge it if so.
Thanks for finally following up 👍

**Comment by edoardocomar** [comment]
@mimaison  I just looked at this and with IBM's jdk 8.0.6.0 the correct class to load is `com.ibm.security.krb5.KrbException` not the `.internal` one

**Comment by mimaison** [comment]
retest this please

**Comment by mimaison** [comment]
Tests failures are unrelated, merging

**Pull request merged**
