### PR TITLE
MINOR: Upgrade rocksdb to 5.14.2

### PR DESCRIPTION
**Pull request by guozhangwang**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@mjsax @bbejeck @vvcephei

**Comment by mjsax** [comment]
Can we run system tests?

**Comment by guozhangwang** [comment]
System test passed: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1841/

**Review by mjsax — APPROVED** [review]
LGTM.

**Review by bbejeck — APPROVED** [review]
LGTM

**Pull request merged**
