### PR TITLE
KAFKA-9408: Use StandardCharsets UTF-8 instead of UTF-8 Name

### PR DESCRIPTION
**Pull request by belugabehr**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
Good cleanup. +1 for this PR. However, are there any other places where `"UTF-8"` literals used?

**Comment by belugabehr** [comment]
I came across this by doing a text search across the project.  This was the
only hit.  I won't swear by it, but I believe this is the only place.

**Comment by rondagostino** [comment]
@belugabehr A quick search shows "UTF-8" occurring in `SocketServerTest`, `LogCleanerTest`, and `TransactionsTest`

**Comment by belugabehr** [comment]
@rondagostino I must had set my filters for non-test code.  I'll take a look.

**Comment by belugabehr** [comment]
@rondagostino  There ya go!

**Review by rondagostino — COMMENTED** [review]
LGTM assuming tests pass

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by ijuma** [comment]
ok to test

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
One job passed, one failed with two unrelated flakes:

> org.apache.kafka.connect.mirror.MirrorConnectorsIntegrationTest.testReplication
> org.apache.kafka.streams.integration.BranchedMultiLevelRepartitionConnectedTopologyTest.testTopologyBuild

**Pull request merged**
