### PR TITLE
MINOR: Fix streams broker compatibility test.

### PR DESCRIPTION
**Pull request by dguy**
Change the string in the test condition to the one that is logged

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dguy** [comment]
System test results: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1312/console
@mjsax, @guozhangwang, @bbejeck  - i need this for 1.1

**Review by bbejeck — APPROVED** [review]
Thanks @dguy LGTM

**Review by guozhangwang — APPROVED** [review]
LGTM. I think this is due to https://issues.apache.org/jira/browse/KAFKA-6289

**Comment by dguy** [comment]
merged to trunk and 1.1

**Comment by mjsax** [comment]
This PR does not seem to be correct. Cf. https://github.com/apache/kafka/pull/4594

We are looking for the wrong error message with this change that comes from a test consumer, but not from an internal KafkaStreams consumer.

**Pull request closed without merging**
