### PR TITLE
KAFKA-3713; Close `compressor` to fix memory leak

### PR DESCRIPTION
**Pull request by ijuma**
This fixes test_producer_throughput with compression_type=snappy.

Also: added heap dump on out of memory error to `producer_performance.py` and corrected the upgrade note related to the change in buffer size for compression streams.

### CODE REVIEW

**Comment by ijuma** [comment]
Verified that `test_producer_throughput` passes with these changes.

cc @gwenshap @guozhangwang @junrao

**Comment by gwenshap** [comment]
LGTM. Thank you!

**Comment by gwenshap** [comment]
I merged to trunk and to 0.10.0. I'm not sure if we need it for 0.9.0 too.

**Comment by ijuma** [comment]
I was thinking about 0.9.0 too, it would have to be a separate PR with just the compressor close change.

**Pull request closed without merging**
