### PR TITLE
[MINOR] Renaming the `Abortable_Transaction` error to `Transaction_Abortable`

### PR DESCRIPTION
**Pull request by sjhajharia**
This is a follow-up to [this](https://github.com/apache/kafka/pull/15486) PR which introduced the new `ABORTABLE_TRANSACTION` error as a part of KIP-890 efforts. However on further discussion, we seem to gain consensus that the error should be rather named as `TRANSACTION_ABORTABLE`. 
This PR aims to address the same. There are no changes in the code apart from that.

### References
JIRA: https://issues.apache.org/jira/browse/KAFKA-16314
Original PR: https://github.com/apache/kafka/pull/15486

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by sjhajharia** [comment]
Requesting review from @jolshan (reviewer of the parent PR)

**Review by soarez — COMMENTED** [review]
Should these variables be renamed too in `core/src/test/scala/unit/kafka/server/AddPartitionsToTxnManagerTest.scala`?

* `abortableTransaction1ErrorResponse`
* `abortableTransaction2ErrorResponse`
* `expectedAbortableTransaction1ErrorsHigherVersion`
* `expectedAbortableTransaction1ErrorsLowerVersion`
* `expectedAbortableTransaction2ErrorsHigherVersion`
* `expectedAbortableTransaction2ErrorsLowerVersion`
* `preConvertedAbortableTransaction1Errors`
* `preConvertedAbortableTransaction2Errors`

**Comment by sjhajharia** [comment]
Thanks for the review @soarez 
I have updated the variable names in the test.

**Review by soarez — APPROVED** [review]
Thanks for the changes. LGTM

**Review by chia7712 — APPROVED** [review]
LGTM

maybe we should align the naming for KIP-890

ABORTABLE_TRANSACTION -> TRANSACTION_ABORTABLE

**Review by jolshan — APPROVED** [review]
Thanks. I will update the KIP as well to match this change. 👍

**Comment by chia7712** [comment]
the failed tests pass on my machine, so I'm going to merge it.
```sh
./gradlew cleanTest :streams:test --tests EOSUncleanShutdownIntegrationTest.shouldWorkWithUncleanShutdownWipeOutStateStore :tools:test --tests MetadataQuorumCommandTest.testDescribeQuorumReplicationSuccessful --tests MetadataQuorumCommandTest.testDescribeQuorumStatusSuccessful :storage:test --tests TransactionsWithTieredStoreTest.testBumpTransactionalEpoch --tests TransactionsWithTieredStoreTest.testAbortTransactionTimeout :metadata:test --tests QuorumControllerTest.testFenceMultipleBrokers --tests QuorumControllerTest.testBalancePartitionLeaders :trogdor:test --tests CoordinatorTest.testTaskRequestWithOldStartMsGetsUpdated :connect:mirror:test --tests MirrorConnectorsIntegrationSSLTest.testReplicateSourceDefault --tests MirrorConnectorsWithCustomForwardingAdminIntegrationTest.testSyncTopicConfigs --tests MirrorConnectorsIntegrationTransactionsTest.testSyncTopicConfigs :core:test --tests DelegationTokenEndToEndAuthorizationWithOwnerTest.testNoConsumeWithDescribeAclViaSubscribe --tests PlaintextAdminIntegrationTest.testAlterReplicaLogDirs --tests DelegationTokenEndToEndAuthorizationWithOwnerTest.testCreateTokenForOtherUserFails --tests ConsumerBounceTest.testConsumptionWithBrokerFailures --tests ReplicaManagerTest.testRemoteFetchExpiresPerSecMetric --tests LogDirFailureTest.testIOExceptionDuringLogRoll --tests LogDirFailureTest.testIOExceptionDuringCheckpoint --tests DynamicBrokerReconfigurationTest.testTrustStoreAlter :clients:test --tests KafkaConsumerTest.testWakeupWithFetchDataAvailable
```

**Comment by sjhajharia** [comment]
Thank you @chia7712 @jolshan @soarez for the review and merge.

**Pull request merged**
