### PR TITLE
KAFKA-14800: Bump snappy-java version to 1.1.9.1

### PR DESCRIPTION
**Pull request by jujoramos**
Extra Release Details: 
- https://github.com/google/snappy/releases/tag/1.1.9
- https://github.com/xerial/snappy-java/releases/tag/v1.1.9.1

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by divijvaidya — APPROVED** [review]
Hi @jujoramos 
The change itself looks good but the tests are failing. I verified that `UnitTest` passed locally for me and for `IntegrationTest` the only two failures locally are unrelated to your code change:

```
ConsumerBounceTest. testClose()
PlaintextAdminIntegrationTest. testReplicaCanFetchFromLogStartOffsetAfterDeleteRecords(String).quorum=kraft
```

Hence, this looks good to ship!

**Comment by jujoramos** [comment]
@divijvaidya : awesome, thanks for the update!. Will you be able to merge this as I don't have committer privileges on the project?

**Comment by divijvaidya** [comment]
> @divijvaidya : awesome, thanks for the update!. Will you be able to merge this as I don't have committer privileges on the project?

Sorry, I don't have committer privilege as well. We will have to wait for a committer to look into this.

**Review by mimaison — APPROVED** [review]
Thanks for the PR! LGTM

**Pull request merged**
