### PR TITLE
HOTFIX: Replace JDK download and fix missing argument in Vagrant provisioning script

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
This combines two separate fixes. The first has to do with the downloads for the JDK no longer being available, so we need to provide replacements elsewhere. This part of the patch should probably be backported to at least 0.11.0 and 0.10.2, but pretty much as far back as is reasonable.

The other issue was just introduced late yesterday but will cause all provisioning to fail so system tests won't even run.

**Comment by hachikuji** [comment]
LGTM

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
LGTM.

**Pull request closed without merging**
