### PR TITLE
[MINOR] KAFKA-7207: Make -rate & -total metrics documentation consistent

### PR DESCRIPTION
**Pull request by KevinLiLu**
https://issues.apache.org/jira/browse/KAFKA-7207

Some sections of the `Monitoring` metrics documentation list out the `-total` metrics, and some sections do not list them out. We should make them consistent and list out the missing `-total` metrics.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rajinisivaram — APPROVED** [review]
@KevinLiLu Thanks for the PR, LGTM.

**Comment by KevinLiLu** [comment]
@rajinisivaram Thanks for reviewing! Did you intentionally leave this approved but un-merged?

**Comment by KevinLiLu** [comment]
@rajinisivaram @guozhangwang bumping this as it has not been merged yet?

**Comment by rajinisivaram** [comment]
@KevinLiLu Thanks for the PR, merging to trunk.

**Pull request merged**
