### PR TITLE
MINOR: Enable the TransactionsBounceTest

### PR DESCRIPTION
**Pull request by apurvam**
I'll let this have multiple runs on the branch builder to see if it fails, and investigate if so.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5735/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5721/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by apurvam** [comment]
Retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5736/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5722/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by apurvam** [comment]
Retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5744/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5730/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by apurvam** [comment]
the transactions bounce test didn't fail in the previous runs.

**Comment by apurvam** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5733/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5747/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by apurvam** [comment]
cc @ijuma @hachikuji 

The test succeeded 8 times in a row. It was never really unstable to begin with, so I think we should enable it to see if there are real issues.

**Comment by hachikuji** [comment]
Sounds good to me. What do you think @ijuma?

**Comment by ijuma** [comment]
Sounds good.

**Comment by hachikuji** [comment]
Merging to trunk.

**Comment by hachikuji** [comment]
Merging for real now.

**Pull request closed without merging**
