### PR TITLE
[DO NOT MERGE] Reenable flaky EosBetaUpgradeIntegrationTest

### PR DESCRIPTION
**Pull request by ableegoldman**
Debugging for KAFKA-10017

### CODE REVIEW

**Comment by ableegoldman** [comment]
Test this please

**Comment by ableegoldman** [comment]
Retest this please

**Comment by mjsax** [comment]
Retest this please.

**Comment by abbccdda** [comment]
Jenkins is being crappy again

**Comment by guozhangwang** [comment]
@ableegoldman jenkins did fail on it, I've opened the url on my browser and would keep it in case it gets garbage collected before you get to see them. If you are already investigating lmk.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Pull request closed without merging**
