### PR TITLE
KAFKA-3522: add missing guards for TimestampedXxxStore

### PR DESCRIPTION
**Pull request by mjsax**
Follow up to #6152 and #6173

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman

**Comment by mjsax** [comment]
Rebased this. Call for review.

**Review by vvcephei — APPROVED** [review]
Looks right to me. Thanks!

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
Merged #6356 into trunk

**Pull request merged**
