### PR TITLE
KAFKA-9545: Fix Flaky Test `RegexSourceIntegrationTest.testRegexMatchesTopicsAWhenDeleted`

### PR DESCRIPTION
**Pull request by ashwinpankaj**
RegexSourceIntegrationTest.testRegexMatchesTopicsAWhenDeleted does not wait to ensure that test-topic-A is deleted. The second assignment condition times out in 15sec.

We should wait for the topic to be deleted (default timeout = 30sec) and then check the assignment.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by wcarlson5 — APPROVED** [review]
LGTM

**Comment by ashwinpankaj** [comment]
> LGTM

Thanks @wcarlson5 !! - can you please merge this commit ?

**Comment by wcarlson5** [comment]
Yeah was just waiting for the build

**Comment by cadonna** [comment]
@wcarlson5 @ashwinpankaj This fix does not seem to unflake the test. If I run it multiple times locally I get a failure after a couple of runs. I reopened the ticket.

**Comment by ashwinpankaj** [comment]
> @wcarlson5 @ashwinpankaj This fix does not seem to unflake the test. If I run it multiple times locally I get a failure after a couple of runs. I reopened the ticket.

ack - I did run this few times in the IDE, will take a look. Thanks

**Pull request merged**
