### PR TITLE
MINOR: Add wait condition for state RUNNING to avoid flakiness

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @mjsax @ableegoldman @abbccdda @cpettitt-confluent

**Review by cpettitt-confluent — APPROVED** [review]
LGTM.

It seems that the two benefits of this patch are: 1) getting a more accurate error message if the streams app did not transition to running in the 30 second timeout, 2) effectively extending the test timeout from 30 seconds to between 30-60 seconds.

**Review by abbccdda — APPROVED** [review]
LGTM!

**Comment by cadonna** [comment]
In JDK 8/Scala 2.11, the following tests failed:
```
kafka.api.SaslOAuthBearerSslEndToEndAuthorizationTest.testNoDescribeProduceOrConsumeWithoutTopicDescribeAcl
org.apache.kafka.streams.integration.KTableKTableForeignKeyJoinIntegrationTest.doLeftJoinFromRightThenDeleteRightEntity
```

Retest this, please

**Comment by mjsax** [comment]
Java 8 passed.

Java 11 / 2.12: `kafka.api.SaslSslAdminClientIntegrationTest.testCreateTopicsResponseMetadataAndConfig`
Java 11 / 2.13:  `kafka.api.ConsumerBounceTest.testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup`

**Comment by cadonna** [comment]
@mjsax Should we also cherry-pick this PR to 2.4 and 2.3?

**Pull request merged**
