### PR TITLE
MINOR: Wait for tasks to terminate to avoid exception in test teardown

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by rajinisivaram** [comment]
Fix for the failure of tearDown after `kafka.api.ConsumerBounceTest.testCloseDuringRebalance`  in https://builds.apache.org/job/kafka-trunk-jdk8/1780/:

```
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1691)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1585)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1565)
	at kafka.api.IntegrationTestHarness.$anonfun$tearDown$2(IntegrationTestHarness.scala:99)
	at kafka.api.IntegrationTestHarness.$anonfun$tearDown$2$adapted(IntegrationTestHarness.scala:99)
```

**Comment by rajinisivaram** [comment]
@hachikuji Can you review, please? Thank you...

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5877/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5892/
Test PASSed (JDK 7 and Scala 2.11).

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM. I'll leave it to you if you want to merge now or wait for @hachikuji (who's on holiday this week).

**Comment by rajinisivaram** [comment]
@ijuma Thank you for the review. I will merge it since it occasionally causes test failures. If @hachikuji has any suggestions, I will do it as a separate PR.

**Review by hachikuji — COMMENTED** [review]
LGTM

**Pull request closed without merging**
