### PR TITLE
KAFKA-10449: Add some important parameter desc in connect-distributed.properties

### PR DESCRIPTION
**Pull request by tinawenqiao**
…rties.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by tinawenqiao** [comment]
In WokerConfig.java we found that REST_HOST_NAME_CONFIG(rest.host.name) and REST_PORT_CONFIG(rest.port) were deprecated. And some new configuration parameters are introduced such as LISTENERS_CONFIG(listeners), REST_ADVERTISED_LISTENER_CONFIG(rest.advertised.listener),ADMIN_LISTENERS_CONFIG(admin.listeners) but not list in the sample conf file.

**Comment by mimaison** [comment]
Thanks for the PR @tinawenqiao.

It would be nice to also mention `rest.port` and `rest.host.name` are deprecated in their descriptions. Could you add something like:
`DEPRECATED: only used when listeners is not set. Use listeners instead. ` to their descriptions in `WorkerConfigs`?

Thanks

**Comment by tinawenqiao** [comment]
> Thanks for the PR @tinawenqiao.
> 
> It would be nice to also mention `rest.port` and `rest.host.name` are deprecated in their descriptions. Could you add something like:
> `DEPRECATED: only used when listeners is not set. Use listeners instead. ` to their descriptions in `WorkerConfigs`?
> 
> Thanks

Thanks for your notice. A new patch is ready.

**Comment by mimaison** [comment]
@tinawenqiao It looks like you made a mistake when rebasing your branch, can you ensure the PR only contains your diff? Thanks

**Comment by tinawenqiao** [comment]
> @tinawenqiao It looks like you made a mistake when rebasing your branch, can you ensure the PR only contains your diff? Thanks

Sorry for the mistake. A clean patch is submit. Is it ok now?

**Comment by mimaison** [comment]
Thanks for the update, it looks much better.

I should have been clearer, I meant to update the documentation text of these settings, not just the comments in `WorkerConfigs`.

For example in https://github.com/apache/kafka/pull/9235/files#diff-5664ddd985065623bab1870e031ce4f3fcfee0bc4951e41b6b0e1584cd32fa2dR153, we could do something like:
```java
private static final String REST_HOST_NAME_DOC
    = "Hostname for the REST API. If this is set, it will only bind to this interface. Deprecated, only used when listeners is not set. Use listeners instead.";
```

**Comment by tinawenqiao** [comment]
> Thanks for the update, it looks much better.
> 
> I should have been clearer, I meant to update the documentation text of these settings, not just the comments in `WorkerConfigs`.
> 
> For example in https://github.com/apache/kafka/pull/9235/files#diff-5664ddd985065623bab1870e031ce4f3fcfee0bc4951e41b6b0e1584cd32fa2dR153, we could do something like:
> 
> ```java
> private static final String REST_HOST_NAME_DOC
>     = "Hostname for the REST API. If this is set, it will only bind to this interface. Deprecated, only used when listeners is not set. Use listeners instead.";
> ```

Doc desc has been added.

**Comment by tinawenqiao** [comment]
> > Thanks for the update, it looks much better.
> > I should have been clearer, I meant to update the documentation text of these settings, not just the comments in `WorkerConfigs`.
> > For example in https://github.com/apache/kafka/pull/9235/files#diff-5664ddd985065623bab1870e031ce4f3fcfee0bc4951e41b6b0e1584cd32fa2dR153, we could do something like:
> > ```java
> > private static final String REST_HOST_NAME_DOC
> >     = "Hostname for the REST API. If this is set, it will only bind to this interface. Deprecated, only used when listeners is not set. Use listeners instead.";
> > ```
> 
> Doc desc has been added.

@mimaison is it ok now?

**Review by mimaison — APPROVED** [review]

**Pull request merged**
