### PR TITLE
KAFKA-2838: Allow comma in super users, allow comma in CLI authz prop…

### PR DESCRIPTION
**Pull request by Parth-Brahmbhatt**
…erties.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by junrao** [comment]
Thanks for the patch. Could you update docs/security.html as well for the changes in using ; for super users and the description in--authorizer-properties?

**Comment by junrao** [comment]
Thanks for the patch. LGTM. I will make the doc changes separately.

**Comment by Parth-Brahmbhatt** [comment]
Sorry I just saw you comment about security.html, Should i open a new jira or just push it as a minor fix?

**Comment by junrao** [comment]
@Parth-Brahmbhatt : No worries. Already pushed the doc changes.

**Comment by junrao** [comment]
@Parth-Brahmbhatt : Currently, AclCommand uses inconsistent conventions.

For principals, we take 
--allow-principal User:Bob --allow-principal User:Alice

For other options like hosts, we take
 --allow-hosts Host1,Host2

Would it be better to change all options to the format of the former?

**Comment by Parth-Brahmbhatt** [comment]
@junrao Yes, I will file a jira and make changes.

**Comment by junrao** [comment]
@Parth-Brahmbhatt : Thanks. Could you do it today so that we can include that in 0.9.0.0? It will be harder to change that once we release it.

**Comment by Parth-Brahmbhatt** [comment]
@junrao  Sure, I will get it done in next couple of hours.

**Pull request closed without merging**
