### PR TITLE
HOTFIX: bump system test versions

### PR DESCRIPTION
**Pull request by ableegoldman**
Bumped kafkatest/version.py to 2.2.3-SNAPSHOT
Updated versions following instructions in streams_upgrade_test.py

### CODE REVIEW

**Comment by mjsax** [comment]
Can we trigger a system test run for this PR?

**Review by bbejeck — APPROVED** [review]
Thanks for the fix @ableegoldman.  LGTM pending system test run.

**Comment by ableegoldman** [comment]
All Streams system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3649

**Comment by ableegoldman** [comment]
System tests passed (for reference the failure rate before this PR was 100%)

**Comment by bbejeck** [comment]
Merged #7835 into 2.2

**Comment by bbejeck** [comment]
Thanks for the fix @ableegoldman!

**Pull request merged**
