### PR TITLE
KIP-267: add MockProcessorContext

### PR DESCRIPTION
**Pull request by vvcephei**
Add support for authors of Processor, Transformer, and ValueTransformer implementations to write unit tests.

We verify this component via unit tests.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
This PR is a work in progress provided to flesh out the discussion on https://cwiki.apache.org/confluence/display/KAFKA/KIP-267%3A+Add+Processor+Unit+Test+Support+to+Kafka+Streams+Test+Utils

**Comment by vvcephei** [comment]
The unit test is just a rough example; I am planning to add many more once we settle on a design.

**Comment by vvcephei** [comment]
TODO: add MockProcessorContext to the testing documentation: https://github.com/apache/kafka/blob/trunk/docs/streams/developer-guide/testing.html

**Comment by guozhangwang** [comment]
@vvcephei Is this PR still valid?

**Comment by vvcephei** [comment]
@guozhangwang No, I'd forgotten about this wip PR and just opened a new one after the kip discussion.

**Pull request closed without merging**
