### PR TITLE
KAFKA-3002: Make available to specify hostname with Uppercase at broker list

### PR DESCRIPTION
**Pull request by sasakitoa**
Make available to specify hostname with Uppercase at broker list

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by granthenke** [comment]
This is similar to KAFKA-2735 (#415) and KAFKA-2272. This looks good to me, but we should make sure their aren't more cases of this. It would be great to consolidate the common regex's, and write a unit test or two as well. I'm not opposed to that being in a separate jira.

**Comment by ijuma** [comment]
Definitely, I thought KAFKA-2757 was for that (it should probably mention the regex under `Utils` too.

**Comment by sasakitoa** [comment]
Thanks for advice, @ijuma and @granthenke.
I think that this problem should be also handled at KAFKA-2757, too.
I will comment to KAFKA-2757, and close this PR.

**Comment by ijuma** [comment]
@sasakitoa Please leave this open. It's a simple fix that can be merged before someone gets around to KAFKA-2757.

**Comment by sasakitoa** [comment]
Thanks.

**Comment by ewencp** [comment]
@sasakitoa How about an update to the corresponding unit tests in `o.a.k.common.utils.UtilsTest`? Should just be a matter of adding one more example that uses capitals.

**Comment by sasakitoa** [comment]
@ewencp Thank you for advice.
I added unit tests for capitals.

**Pull request closed without merging**
