### PR TITLE
[2.2 branch] KAFKA-8398 Prevent NPE when trying to forceUnmap

### PR DESCRIPTION
**Pull request by jaikiran**
The commit here includes a simple change to fix a NPE that reported in https://issues.apache.org/jira/browse/KAFKA-8398

### CODE REVIEW

**Comment by jaikiran** [comment]
Failures don't look related and both jobs failed early in the run with OOM errors which appear environmental issues

**Comment by jaikiran** [comment]
Any reviewers willing to review and merge this trivial PR, please?

**Comment by jaikiran** [comment]
@ijuma, Sorry to ping directly - would you be able to help with reviewing this trivial change and help with the merge? I was hoping this fix will get into some release of Kafka, since in one of the projects, we run into this very regularly and the exceptions flood the log files.

**Comment by jaikiran** [comment]
Closing this since there appears to be no interest in this.

**Comment by ijuma** [comment]
Revived via #8983.

**Pull request closed without merging**
