### PR TITLE
MINOR: Remove duplicate definition of transactional.id.expiration.ms config

### PR DESCRIPTION
**Pull request by stanislavkozlovski**

### CODE REVIEW

**Comment by stanislavkozlovski** [comment]
The same config was already defined here:
https://github.com/apache/kafka/blob/e213608127696dd742752bbc57da209e8eade0f2/core/src/main/scala/kafka/server/KafkaConfig.scala#L1284

cc @bob-barrett @hachikuji @apurvam

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
I noticed that we have a `TransactionIdExpirationMsDoc`. That should probably be renamed to follow the naming convention of the config.

**Review by apurvam — APPROVED** [review]
LGTM, thanks!

**Comment by stanislavkozlovski** [comment]
@ijuma good catch, it seems like we had an unused `TransactionIdExpirationMsDoc` variable.
I liked that explanation, so I merged both into the one that is used.

cc @apurvam

**Review by bob-barrett — APPROVED** [review]
LGTM! Thanks for cleaning this up

**Pull request merged**
