### PR TITLE
add example to send customized message by using serializer

### PR DESCRIPTION
**Pull request by microwishing**
based on 0.8.2.2. anyone can help?

### CODE REVIEW

**Comment by gwenshap** [comment]
This PR seems to accidentally try to merge trunk into 0.8.2 branch. Due to the hundreds of files this changes, its impossible to review.

Can you close this and open as PR to the correct branch?

**Comment by granthenke** [comment]
@microwishing Can you please close this pull request as soon as possible?

Once you update your example to be against trunk, you can re-open and we will review. In the mean time this is slowing down others builds and reviews, as many Jenkins jobs are being trigger/backed up.

**Comment by ijuma** [comment]
@microwishing, can you please close this PR? It's been generated incorrectly.

**Comment by stumped2** [comment]
Closing PR as requested at https://issues.apache.org/jira/browse/INFRA-10795

**Pull request closed without merging**
