### PR TITLE
MINOR: Remove redundant try block in LogCleaner

### PR DESCRIPTION
**Pull request by dhruvilshah3**

### CODE REVIEW

**Comment by ijuma** [comment]
@stanislavkozlovski did you mean to have a `catch/finally` there or was the `try` block left behind accidentally?

**Comment by stanislavkozlovski** [comment]
@ijuma that is a left over
Thanks for removing this @dhruvilshah3 !

**Review by stanislavkozlovski — APPROVED** [review]

**Comment by dhruvilshah3** [comment]
@ijuma could we merge this change?

**Review by ijuma — APPROVED** [review]
LGTM

**Pull request merged**
