### PR TITLE
KAFKA-4064 Add support for infinite endpoints for range queries in Kafka Streams KV stores

### PR DESCRIPTION
**Pull request by theduderog**
@guozhangwang 

I had to fix the bug with in-memory ranges being exclusive and RocksDB being inclusive to get meaningful tests to work.

### CODE REVIEW

**Comment by dguy** [comment]
@theduderog you have a checkstyle failure

**Comment by dguy** [comment]
After seeing the API changes, i'm wondering if it would be better if we have a single function `range(Range<K> range)` - and have a class sth like:

```
class Range<K>
   K from;
   K to;
   ...
   static <K> from(K key) ...
   static <K> until(K key) ..
  // etc
```

It at least means we can support everything with a single method on the `KeyValuStore` interface. 
Interested in hearing what @guozhangwang @miguno @enothereska @mjsax think

**Comment by miguno** [comment]
I don't have a strong opinion.

I see the benefits of a single `range(Range<K> range)` method.  Its drawback is that users have to construct a new instance of `Range<K>` every time, which is more cumbersome in terms of using the API.

So:

``` java
store.rangeFrom(3)
```

versus

``` java
store.range(Range.from(3))
```

Perhaps a question to ask is:  Would we need a separate `Range` class because we expect to add more functions than what `rangeFrom(K)` and `rangeUntil(K)` would cover?

**Comment by theduderog** [comment]
cc @ijuma as well

**Comment by ijuma** [comment]
I prefer the method taking a Range personally (it is why I suggested that offline when the discussion was taking place). It is easy to add convenience methods later, if necessary, but hard to remove methods from the interface.

**Comment by guozhangwang** [comment]
There are some jenkins failures that seems related to the changes.

**Comment by theduderog** [comment]
@guozhangwang I'll fix those.  What you think about the API?

**Comment by dguy** [comment]
@theduderog - sorry we haven't progressed this at all. Besides the conflicts. I'm in favor of the API as I mentioned above (Obviously!) @enothereska @mjsax @guozhangwang - thoughts?

**Comment by enothereska** [comment]
Yeah good idea. Let's push to get this in asap. @theduderog could you resolve the conflict and then we can take it from there. Sorry for the delay.

**Comment by mjsax** [comment]
ping @theduderog

**Comment by theduderog** [comment]
retest this please

**Comment by theduderog** [comment]
Is `range()` supposed to be inclusive or exclusive of the endpoint? So for, this PR makes them all inclusive.

The [docs say inclusive](https://github.com/apache/kafka/blob/a4413fc8a42b0222107cad20835e4461141c2ea2/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlyKeyValueStore.java#L46), the [RocksDB implementation is inclusive](https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDBStore.java#L488), but the [InMemory implementation is exclusive](https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryKeyValueStoreSupplier.java#L158).

Not to mentioned that J[ava SortedSet.subSet](https://docs.oracle.com/javase/7/docs/api/java/util/SortedSet.html#subSet%28E,%20E%29) defaults to exclusive and seems like the more natural choice so it's likely what users expect.

**Comment by guozhangwang** [comment]
Re: `range()` I think we can make it consistent as inclusive everywhere, the `InMemoryStore`'s range function seems to be a bug itself. Could you fix it along with this PR?

Re: API, I think I also agree with @dguy and @ijuma on the new `Range` class that

```
class Range<K>
   private K from;
   private K to;
   ...
   static <K> from(K key) ...
   static <K> until(K key) ..
   static <K> range(K keyFrom, K keyUtil) ..
```

which could be generalized later. At the same time we can keep the current function and reimplemented as `Range.range(..)`.

**Comment by guozhangwang** [comment]
Made a pass over the implementation, LGTM overall.

**Comment by theduderog** [comment]
retest this please

**Comment by guozhangwang** [comment]
@theduderog `retest this` does not work for apache repos just FYI :P

**Comment by theduderog** [comment]
thanks, @guozhangwang.  it may have just been a coincidence but it seemed to kick off right after i added that comment

**Comment by guozhangwang** [comment]
@theduderog Could you file a KIP for this API change as well?

**Review by dguy — COMMENTED** [review]
I thought we were going to have a single `range` method that takes a `Range` class?

**Comment by theduderog** [comment]
@dguy I'll switch to that for the KIP

**Comment by mjsax** [comment]
Closing this PR due to inactivity.

**Comment by vvcephei** [comment]
FYI, this was implemented in #11120

**Pull request closed without merging**
