### PR TITLE
Cross compile to Scala 2.12.0-RC2

### PR DESCRIPTION
**Pull request by leachbj**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. A couple of things:
- 2.12.0 final was published to Maven recently, so it makes sense to depend on that directly.
- 2.12 requires Java 8 while Kafka requires Java 7 so we need to ensure that this change doesn't cause issues when building with Java 7. Have you tested that?

**Comment by leachbj** [comment]
Currently all the dependent libraries are only available as compiled against RC2, I suspect people will start working on publishing 2.12.0 binaries but until then I figured it was better to get something going than wait.  Kafka is a transient dependency in reactive-kafka (via scalatest-embedded-kafka) so they can't be published until Kafka is.

When building I get `target is deprecated: -target:jvm-1.7 is deprecated, forcing use of jvm-1.8`, kafka with 2.12 will also have to be java8 (whereas the 2.11 version is fine with java7).  I would expect the 'release' version of kafka would continue to the be the 2.11 version but the full range of artifacts for 2.10, 2.11 and 2.12 be published so dependencies can be satisfied.

**Comment by ijuma** [comment]
I suggest we close this until we figure out a solution for `trunk` (#2113). Once we have that, we can discuss if backporting makes sense.

**Comment by leachbj** [comment]
Makes sense.

**Pull request closed without merging**
