### PR TITLE
MINOR: Add missing log argument

### PR DESCRIPTION
**Pull request by tombentley**

### CODE REVIEW

**Comment by tombentley** [comment]
@hachikuji @cmccabe @mumrah this fixes a very trivial pb with a log.trace, please could one of you review?

**Review by chia7712 — APPROVED** [review]
@tombentley thanks for your patch. LGTM

**Comment by ijuma** [comment]
Let's cherry-pick this to 2.8 as well.

**Comment by chia7712** [comment]
> Let's cherry-pick this to 2.8 as well.

will copy that.

**Comment by chia7712** [comment]
push this PR to trunk and 2.8

**Pull request merged**
