### PR TITLE
[KAFKA-14133] Migrate EasyMock to Mockito in GlobalStateStoreProviderTest, KeyValue…

### PR DESCRIPTION
**Pull request by olalamichelle**
…IteratorFacadeTest, KeyValueSegmentTest, TopologyMetadataTest

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by clolov** [comment]
Hello! I believe the people who expressed an interest in picking up these tests are @yashmayya and @bachmanity1 on https://issues.apache.org/jira/browse/KAFKA-14133. Could you please have a conversation on who will own them?

**Comment by yashmayya** [comment]
@olalamichelle - thanks for the contribution and @clolov - thanks for the mention! I'd already finished the Mockito test migrations that I'd picked up and indicated on https://issues.apache.org/jira/browse/KAFKA-14133 locally but held off on raising PRs since we seem to be especially short on reviewer bandwidth right now 😅 

However, this appears to be among the first set of contributions to Apache Kafka by @olalamichelle and I'd be happy to transfer ownership of migrating these tests 🙂

**Comment by olalamichelle** [comment]
Hi @yashmayya, sorry I didn't realize that lots of these tests were already assigned and even already had PRs. Thank you so much for transferring ownership to me! 
Btw, @yashmayya ..@clolov It seems that I do not have edit permissions to the ticket https://issues.apache.org/jira/browse/KAFKA-14133. Could either of you assign the related tasks to me? Thanks!

**Comment by divijvaidya** [comment]
> It seems that I do not have edit permissions to the ticket

@olalamichelle what is your JIRA Id? Have you created one using https://selfserve.apache.org/jira-account.html as mentioned here: https://kafka.apache.org/contributing.html

**Comment by clolov** [comment]
There has been no activity on this or related pull requests for over a month. As detailed in https://github.com/apache/kafka/pull/14255 I will close them and take over the work.

**Pull request closed without merging**
