### PR TITLE
KAFKA-3636: change default max session timeout to 5 minutes

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM. cc @ijuma 

EDIT: I was not careful, the patch was actually modifying the wrong config.

**Comment by hachikuji** [comment]
@ijuma @guozhangwang Increase the default to 5 minutes and updated the correct config this time.

**Comment by onurkaraman** [comment]
LGTM

**Comment by ijuma** [comment]
LGTM

**Pull request closed without merging**
