### PR TITLE
HOTFIX: reduce log verbosity on commit

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @dguy @enothereska @bbejeck @guozhangwang @ijuma 

This is a hotfix for 0.11.

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by enothereska** [comment]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5636/
Test PASSed (JDK 7 and Scala 2.11).

**Review by ijuma — APPROVED** [review]
LGTM, thanks. Merging to trunk and 0.11.0.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5622/
Test PASSed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
