### PR TITLE
MINOR: exchanged addAll/putAll with parametrized constructor

### PR DESCRIPTION
**Pull request by wlsc**
Basic static analysis was done here.

I've exchanged all addAll/putAll methods that were stand right after creation of each particular HashSet/HashMap with parametric constructor of HashSet/HashMap.

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by ijuma** [comment]
Can you please resolve the merge conflict?

**Comment by wlsc** [comment]
@ijuma yes, sure! now it's ready

**Comment by wlsc** [comment]
@ijuma any updates regarding this PR? I can not merge it now anymore, because I've removed the branch for it. 

If it possible that you can merge it, that would be very nice!

**Comment by guozhangwang** [comment]
This is a good PR to have. I'm wondering if we should rebase / merge it as is?

It is not a Streams PR though.

**Comment by mjsax** [comment]
I am +1. @wlsc can you update the PR to current `trunk` ?

**Comment by wlsc** [comment]
@guozhangwang @mjsax sure, I would address it as soon as possible (maybe even tonight)

**Comment by wlsc** [comment]
@guozhangwang @mjsax hey, sorry for inconvenience, but the branch for this issue was already removed. Thus, I cannot make a merge with current trunk. I've created another issue from current trunk.

Please check this ticket https://github.com/apache/kafka/pull/4521

**Pull request closed without merging**
