### PR TITLE
HOTFIX: use explicit version in upgrade.html

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by guozhangwang** [comment]
Merged to trunk and cherry-picked to 0.10.2.

**Comment by lindong28** [comment]
@guozhangwang I am not able to open `upgrade.html` using webbrowser (e.g. chrome, firefox) after this patch. Do you know how to fix this?

**Comment by guozhangwang** [comment]
@lindong28 Sure! It is written here:

https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Website+Documentation+Changes

search for `If you want to check out the edits on the web docs..`

**Comment by lindong28** [comment]
@guozhangwang Thanks!

**Pull request closed without merging**
