### PR TITLE
MINOR: enable KRaft in LogOffsetTest

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by cmccabe** [comment]
Rebased

**Review by dengziming — APPROVED** [review]
These tests all passed when I run them locally.
I have a small question, do you think we can replace EasyMock with Mockito in this test since this is a small change, or it's better to do that in a separate PR?

**Comment by cmccabe** [comment]
I think we should replace Mockito in a separate PR. Otherwise it might be hard to see which changes are related to that and which are related to KRaft.

**Comment by cmccabe** [comment]
merged into #12155

**Pull request closed without merging**
