### PR TITLE
MINOR: set trace logging for zookeeper upgrade test

### PR DESCRIPTION
**Pull request by apurvam**
This adds logging which will hopefully help root cause https://issues.apache.org/jira/browse/KAFKA-4574.

### CODE REVIEW

**Comment by apurvam** [comment]
I am trying to run this code on jenkins branch builder to see if it has the desired effect, but there seem to be issues with Jenkins right now and over the weekend.

**Comment by apurvam** [comment]
@ewencp what am I doing wrong here? I tried multiple permutations (visible from the commit history), but with the current version, only the info logs are produced.

**Comment by ewencp** [comment]
@apurvam I think this might be confusion over when the logs are *generated* vs *collected*. If I'm reading the log4j configs properly, I think the issue might be that in most other cases we set the log level, but it's applied to a root logger that affects a log file that is always collected, whereas in this case I think you might have some settings adjusted for logs that are only ending up in log files that are not being collected by default (as per the `collect_default` settings).

**Comment by apurvam** [comment]
Thanks @ewencp I will try to explicitly set these logs for collection and see if it works.

**Comment by apurvam** [comment]
Cleaning up my older PRs, closing this out since the test is question is stable after KIP-101 was merged, and no longer needs additional logging to debug.

**Pull request closed without merging**
