### PR TITLE
KAFKA-4645: Improve test coverage of ProcessorTopology

### PR DESCRIPTION
**Pull request by dguy**
the toString method prints the topology, but had no tests making sure it works and/or doesn't cause exceptions

### CODE REVIEW

**Comment by dguy** [comment]
@enothereska @mjsax @guozhangwang

**Comment by enothereska** [comment]
LGTM thanks!

**Comment by enothereska** [comment]
@dguy could you retrigger the tests (perhaps merge with latest trunk too)?

**Comment by dguy** [comment]
retest this please

**Review by mjsax — APPROVED** [review]
LGTM

**Review by guozhangwang — APPROVED** [review]

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
