### PR TITLE
MINOR: Update Scala 2.11 to 2.11.12

### PR DESCRIPTION
**Pull request by ijuma**
The main change is Java 9 support.

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8052 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7944 tests run, 5 skipped, 1 failed.
--none--

**Comment by ijuma** [comment]
Review by @rajinisivaram

**Comment by ijuma** [comment]
retest this please

**Review by rajinisivaram — APPROVED** [review]
LGTM, feel free to merge after builds pass.

**Comment by asfgit** [comment]
SUCCESS 
 8057 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8057 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7949 tests run, 5 skipped, 1 failed.
--none--

**Comment by ijuma** [comment]
Test failure is unrelated and we have a PR for it (error metrics need special handling during shutdown). Merging to trunk and 1.0.

**Pull request closed without merging**
