### PR TITLE
KAFKA-4517: Remove deprecated shell script

### PR DESCRIPTION
**Pull request by jeffwidman**
Remove the kafka-consumer-offset-checker.sh script completely since it
was already deprecated in Kafka9

Currently it's quite confusing to new Kafka operators that this script
exists because it seems to do exactly what they want for checking
offsets, only to later realize they should instead use
kafka-consumer-groups.sh script

### CODE REVIEW

**Comment by guozhangwang** [comment]
Thanks for the PR.

Usually we need to wait for a couple of major release cycles after deprecating a client / tool / etc before removing it, and also starting a DISCUSS email thread on kafka-dev before doing it. For example the old Scala consumer client. Would you like to start one discussion thread on the mailing list?

**Comment by jeffwidman** [comment]
There was a somewhat similar discussion on the associated JIRA ticket, and I think someone marked this as relevant for the Kafka 11 release. 

So I'm happy to start an email thread if needed, but I'm a little uncertain whether the non-email discussions regarding this should happen here on github or over on JIRA?

**Comment by guozhangwang** [comment]
Yeah that is right. There were no hard-stone rules about how we should discuss about deprecations. Lately we are doing it more often in mailing list since it is most visible in the community. As for this specific deprecation, I think people would likely come to consensus quickly so shouldn't be much overhead.

**Comment by jeffwidman** [comment]
Posted to the mailing list, no one piped up against, and @gwenshap expressed support for it.

**Comment by jeffwidman** [comment]
Closing in favor of https://github.com/apache/kafka/pull/3036

**Pull request closed without merging**
