### PR TITLE
MINOR: fix typo in SnapshotWriter

### PR DESCRIPTION
**Pull request by wenbingshen**
I think the author wants to use ‘for a' here.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
There are also many other occurrence of fora in the project

**Comment by wenbingshen** [comment]
> There are also many other occurrence of fora in the project

Thanks for your commont.What does fora stand for here?

**Comment by dengziming** [comment]
I guess "fora" means "for a" here.

**Comment by wenbingshen** [comment]
> I guess "fora" means "for a" here.

I think you're right. Thank you for your comments.

**Pull request closed without merging**
