### PR TITLE
KAFKA-3359 Parallel log-recovery of un-flushed segments on startup

### PR DESCRIPTION
**Pull request by ghost**
Did not find any tests for the method. Will be adding them

### CODE REVIEW

**Comment by granthenke** [comment]
@vamsi-subhash Thanks for the contribution.

Can you please open a jira to describe/track this work and update the PR to include it in the title? This PR also adds a few new configurations which warrants, at a minimum, a discussion in the Kafka dev mailing list. From there a small [KIP](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals) may be suggested too.

**Comment by ghost** [comment]
Hi Grant,
Here is the JIRA https://issues.apache.org/jira/browse/KAFKA-3359

The JIRA has the details. I have replied to the kafka-dev mailing list on the pull request mail thread with details. Please review and let me know of the comments. Thanks.

**Comment by ghost** [comment]
@granthenke 
Reg. the tests, The jenkins build timed-out while running the tests and the tests passed till then. 
I didn't get any replies on the mailing list yet. Can you once look at the JIRA and comment?

**Comment by vvcephei** [comment]
Hello,

It seems like this PR stalled. I'll close it out for now, but if you or anyone else want to resume this work, please feel free to re-open it (or start a new one)!

Thanks,
John

**Pull request closed without merging**
