### PR TITLE
KAFKA-4057: Allow to specify the request version and replica ID in ka…

### PR DESCRIPTION
**Pull request by mimaison**
…fka.javaapi.FetchRequest
- Added new arguments for versionId and replicaId in the constructor instead of using hardcoded values

### CODE REVIEW

**Comment by ijuma** [comment]
What is the use case for this? We intend to remove these classes, so it would be good to understand how they are being used.

**Comment by mimaison** [comment]
I see this class as a helper until FetchRequest is converted to the new Java format. Once that's done, yes we should definitively remove it. 

Until then, we use it to create FetchRequests from Java code to perform some custom logic. Prior to 0.10, the hardcoded version was not an issue but now with the multiple versions, without this it's really a pain to create FetchRequests.

As the FetchRequest work (see KAFKA-2066) seems to have staled, I thought we could use this tiny enhancement in the meantime.

**Comment by ijuma** [comment]
Are you aware of `org.apache.kafka.common.requests.FetchRequest`? I guess you're saying you use `kafka.javaapi.FetchRequest` with the simple consumer?

**Comment by mimaison** [comment]
In our case, it's a little more complicated as we've added some extra logic around KafkaApis. But I think yes you are right, with the simple consumer you might run into the same issue and not be able to specify the request version.

I thought the change was "generic" enough to be useful till the old fetch format gets replaced. If that's not the case, that's perfectly fine.

**Comment by mimaison** [comment]
Any chance to get this merge or is it not needed ?

**Comment by ijuma** [comment]
The tricky thing is maintaining source and binary compatibility. Code calling this class from Java would break after your change.

**Comment by mimaison** [comment]
No worries, I'll close the PR and JIRA

**Pull request closed without merging**
