### PR TITLE
KAFKA-15991: Fix flaky test testGroupIdNotNullAndValid

### PR DESCRIPTION
**Pull request by cadonna**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by lucasbru — APPROVED** [review]
LGTM, thanks

**Comment by cadonna** [comment]
@lucasbru This PR is ready to merge (the builds are acceptable). Should I wait for https://github.com/apache/kafka/pull/14930 and close this since this is also solved that? Or should we just merge this as a temporary fix (at the cost of merge conflicts)?

**Comment by lucasbru** [comment]
@cadonna  If you have more comments on #14930, please feel free to merge this, I will anyways have conflicts with every single CTR/KIP-848 PR.

Instead, if #14930 is good to go, lets merge it.

**Comment by cadonna** [comment]
Not needed anymore since https://github.com/apache/kafka/pull/14930 got merged.

**Pull request closed without merging**
