### PR TITLE
KAFKA-3474: add metrics to track replica fetcher timeouts

### PR DESCRIPTION
**Pull request by junrao**

### CODE REVIEW

**Comment by becketqin** [comment]
LGTM.

**Comment by ijuma** [comment]
Cc @gwenshap

**Comment by ijuma** [comment]
@junrao This doesn't merge cleanly anymore after https://github.com/apache/kafka/commit/b94a7812beeb840926871df84838f35ca7b76ffe

**Comment by ijuma** [comment]
@junrao, do we want to revive this PR?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6548/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6563/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by vvcephei** [comment]
Hi @junrao ,

It seems like this PR stalled. I'll close it out for now, but if you or anyone else want to resume this work, please feel free to re-open it (or start a new one)!

Thanks,
John

**Pull request closed without merging**
