### PR TITLE
KAFKA-5073: Kafka Streams stuck rebalancing after exception thrown in rebalance listener

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Bug got introduced here: https://github.com/apache/kafka/commit/afeadbef50ee8cb5c23de26c1b2a5ad2c7ad941e#diff-045aeaddb4232a85a8560186b4901e69L575

Call for review @enothereska @dguy (\cc @xvrl )

**Comment by ijuma** [comment]
It would be good to have a test for this.

**Comment by enothereska** [comment]
Test would be good. Otherwise LGTM. Thanks.

**Comment by enothereska** [comment]
It might be hard to do a test for this btw, could open a JIRA for now and proceed with this PR.

**Comment by mjsax** [comment]
I agree with @enothereska. I had the though of adding a test before opening the PR but it turned out to be quite complex to get right -- the code base is hard to test for this part. I created a JIRA: https://issues.apache.org/jira/browse/KAFKA-5085

Would be good to get `trunk` fixed soon.

**Review by enothereska — APPROVED** [review]

**Comment by mjsax** [comment]
Call for review and merging @guozhangwang

**Review by guozhangwang — APPROVED** [review]
Merged to trunk.

**Pull request closed without merging**
