### PR TITLE
MINOR: Fix typos for doc

### PR DESCRIPTION
**Pull request by berg223**
**More detailed description of your change**

Fix some typos  for documents

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by berg223** [comment]
sorry for that commit so many changes. Please review https://github.com/apache/kafka/pull/13882 first or just review https://github.com/apache/kafka/pull/13883/commits/587d168f9498c2eb0a3eab5f4f69d4f2ae92a38e . When that PR is merged then the rest change will be only in doc module.

**Comment by divijvaidya** [comment]
please rebase with trunk, #13882 has been merged

**Comment by divijvaidya** [comment]
Also, @xiaocairush is it possible to automate testing for these spell typos in checkstyle of some other build plugin? What tool did you use to find these?

**Comment by berg223** [comment]
@divijvaidya I'm using a tool called [typos](https://github.com/crate-ci/typos). And it can be integrated with GitHub Actions. But I'm sure if it's a good practice to intergrate with repo.

**Comment by berg223** [comment]
Besides, how do you ensure there is not some people work on the same issue simultaneously in jira when the issue is not assigned. Seems like I need a jira account to assign issue to myself?

**Review by divijvaidya — APPROVED** [review]

**Comment by divijvaidya** [comment]
> Besides, how do you ensure there is not some people work on the same issue simultaneously in jira when the issue is not assigned. Seems like I need a jira account to assign issue to myself?

Yes, we use JIRA and you can create one using the instruction at https://kafka.apache.org/contributing

> I'm using a tool called [typos](https://github.com/crate-ci/typos). And it can be integrated with GitHub Actions. But I'm sure if it's a good practice to intergrate with repo.

Yeah, perhaps not with github actions. I am hoping checkstyle comes up with something similar. I honestly haven't looked into automated spell checks before.

**Pull request merged**
