### PR TITLE
KAFKA-2877: handle request timeout in sync group

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by benstopford** [comment]
LGTM - ssl_rolling_upgrade_test.py, which had previously been intermittently failing, passed 5 times in a row so looks this is likely the fix it needs cc @rajinisivaram

**Comment by hachikuji** [comment]
@benstopford: After talking with @guozhangwang, it seems like it might make more sense to convert this error on the server side. I've updated the patch to return REBALANCE_IN_PROGRESS instead for this case, which is already handled on the client.

**Comment by ijuma** [comment]
Do we want to backport this to the 0.9.0 branch?

**Comment by hachikuji** [comment]
@ijuma I think we should. The bug is fairly significant and the fix is simple.

**Comment by guozhangwang** [comment]
LGTM.

**Pull request closed without merging**
