### PR TITLE
KAFKA-8765: Remove interface annotations in Streams API

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna @abbccdda

**Review by cadonna — APPROVED** [review]
Thank you @mjsax 
LGTM

**Comment by mjsax** [comment]
Java 11 / 2.13 passed.

Java 11 / 2.12 and Java8 failed (results are not available any longer)

Retest this please.

**Review by guozhangwang — APPROVED** [review]
LGTM!

**Comment by mjsax** [comment]
Java 8 passed.

Java 11 / 2.12: `testDescribeLogDirsRequest` (already fixed -- will rebase this PR)

Java 11 / 2.13 failed with env issue.

**Pull request merged**
