### PR TITLE
MINOR: added logging feature for ConfigEntry

### PR DESCRIPTION
**Pull request by ppatierno**
Added toString() ovveride to ConfigEntry for logging

### CODE REVIEW

**Comment by omkreddy** [comment]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6191/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6175/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM. Merging to trunk and 0.11.0.

**Comment by ijuma** [comment]
For future PRs, can you please fix your Git configuration so that the author field is correct? It's `ppatierno <ppatierno@live.com>` at the moment.

**Comment by ppatierno** [comment]
@ijuma thanks. I have updated Git config for next PRs. It will be `Paolo Patierno <ppatierno@live.com>`

**Pull request closed without merging**
