### PR TITLE
MINOR: Define the term tombstone, since it's used elsewhere in the docs

### PR DESCRIPTION
**Pull request by tombentley**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5878/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5863/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by omkreddy** [comment]
+1

**Comment by ianwsperber** [comment]
Can this be merged? I have yet to find official documentation that clearly defines a message with a `null` value as a tombstone, though that is clearly the usage. It would be nice to have this document to refer to. Thank you!

**Comment by tombentley** [comment]
@omkreddy the term tombstone is still not defined in the docs, so any chance you could merge this?

**Review by omkreddy — APPROVED** [review]
@tombentley Thanks for the PR. LGTM.

**Pull request merged**
