### PR TITLE
MINOR: Review change to block.on.buffer.full config

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by ijuma** [comment]
Can you explain the reasoning for this change @granthenke?

**Comment by granthenke** [comment]
The configuration for block.on.buffer.full was changed from a default of `true` to `false` during [KAFKA-2120](https://issues.apache.org/jira/browse/KAFKA-2120). With a brief search through code reviews and discussions I couldn't find why it was changed. 

@MayureshGharat @jjkoshy Can you help provide some insight?

If this was intended to be changed, this patch should update the docs and include a warning in the 0.9 upgrade notes. Otherwise we may want to change back to a value of `true` (as this PR currently does)

Currently the block.on.buffer.full docs read as follows:

> When our memory buffer is exhausted we must either stop accepting new records (block) or throw errors. **By default this setting is true** and we block, however in some scenarios blocking is not desirable and it is better to immediately give an error. Setting this to false will accomplish that: the producer will throw a BufferExhaustedException if a recrord is sent and the buffer space is full.

**Comment by granthenke** [comment]
@ijuma I was typing up a comment to start the discussion. You are just too fast. :)

**Comment by granthenke** [comment]
@jholoman pointed this issue out (Thanks!). He may have some comment on the impact it has/had.

**Comment by jholoman** [comment]
Sure, I have some concerns with changing the default w/out documenting. My understanding is that having this set to false and not handling the BufferExhaustedException could lead to data loss.

**Comment by MayureshGharat** [comment]
@granthenke The property block.on.buffer.full is no longer used as per kafka-2120 and was supposed to be removed in future releases. This will require some changes to the KafkaProducer code. I am not sure if this is the right time to remove this property. If yes, I can get a patch ready for the same. 

P.S: Kafka-2120 deprecates few other properties as well. We can also get rid of those if we are fine with it.

**Comment by granthenke** [comment]
@MayureshGharat Thanks for the response. I will need to dig in a bit to understand the change. We definitely need to update docs if its not being used anymore. Its also referenced in the current javadoc:
- https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java#L122
- https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java#L423

If this has been deprecated, nothing in the documentation indicated that, and provides the alternative. The  `@deprected` tag will only trigger for those using the variable, but many will likely configure with a file or raw strings.

**Comment by ijuma** [comment]
@granthenke it is used like so:

``` java
if (userProvidedConfigs.containsKey(ProducerConfig.BLOCK_ON_BUFFER_FULL_CONFIG)) {
                log.warn(ProducerConfig.BLOCK_ON_BUFFER_FULL_CONFIG + " config is deprecated and will be removed soon. " +
                        "Please use " + ProducerConfig.MAX_BLOCK_MS_CONFIG);
                boolean blockOnBufferFull = config.getBoolean(ProducerConfig.BLOCK_ON_BUFFER_FULL_CONFIG);
                if (blockOnBufferFull) {
                    this.maxBlockTimeMs = Long.MAX_VALUE;
                } else if (userProvidedConfigs.containsKey(ProducerConfig.METADATA_FETCH_TIMEOUT_CONFIG)) {
                    log.warn(ProducerConfig.METADATA_FETCH_TIMEOUT_CONFIG + " config is deprecated and will be removed soon. " +
                            "Please use " + ProducerConfig.MAX_BLOCK_MS_CONFIG);
                    this.maxBlockTimeMs = config.getLong(ProducerConfig.METADATA_FETCH_TIMEOUT_CONFIG);
                } else {
                    this.maxBlockTimeMs = config.getLong(ProducerConfig.MAX_BLOCK_MS_CONFIG);
                }
            } 
```

And the default value for `maxBlockTimeMs` is `60 * 1000`.

**Comment by granthenke** [comment]
@MayureshGharat Looking a bit further the default for max.block.ms (the replacement for block.on.buffer.full) is set to 60 seconds. Which means the default behavior is close to the old default for block.on.buffer.full which was `true`. Was there a reason, even if deprecated, block.on.buffer.full was changed to false? 

It's probably valuable to  update the 0.9 upgrade docs to tell users that they need to handle `BufferExhaustedException` exception now by default.

**Comment by granthenke** [comment]
@ijuma and I are simultaneously commenting today. :)

@ijuma I see that. This is close to the old behavior but not exactly the same if 60 seconds passes. So users will get an exception they may not have been expecting before. I think, at a minimum, we should document it both in the code and on the site docs.

**Comment by MayureshGharat** [comment]
@granthenke Users will get a TimeoutException from BufferPool.allocate ( no more BuffereExhaustException) : 
**throw new TimeoutException("Failed to allocate memory within the configured max blocking time");**

We decided to deprecate it since we wanted to get rid of the property and basically make it simple to the end-users to rely on only two properties going forward : 
1) max.block.ms
2) request.timeout.ms

The users will get warning when they try to use the deprecated properties. But once we remove these deprecated properties, we need to update the docs to reflect the change.

**Comment by granthenke** [comment]
@MayureshGharat Is there somewhere I, and any user of a KafkaProducer, can learn about this change and the new exceptions they should handle (in the callback?) and the exceptions they no longer need to handle?  

The properties are deprecated and behavior has changed. I think we need to update the site docs and java docs now. I can open a jira to track that.

**Comment by MayureshGharat** [comment]
@granthenke AFAIK, I don't think there are docs representing that info. The users need to handle the TimeoutException which they should have been doing earlier as well. The only thing is now they do not have to care about BufferExhaustException.
 Can you open a jira. I can work on it right away.

**Comment by granthenke** [comment]
Thanks @MayureshGharat! I created [KAFKA-3393](https://issues.apache.org/jira/browse/KAFKA-3393) to track that.

**Comment by granthenke** [comment]
Closing this since its now tracked by #1060

**Pull request closed without merging**
