### PR TITLE
MINOR: Use `forEach` and `ifPresent` to simplify Scala code

### PR DESCRIPTION
**Pull request by ijuma**
* Use `forEach` instead of `asScala.foreach` for Java Iterables.
* Use `ifPresent` instead of `asScala.foreach` for Java Optionals.
* Use `forEach` instead of `entrySet.forEach` for Java maps.
* Keep `asScala.foreach` for `Properties` as the Scala implementation
has a better interface (keys and values are of type `String`).
* A few clean-ups: unnecessary `()`, `{}`, `new`, etc.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Unrelated flaky failures:

> org.apache.kafka.connect.mirror.MirrorConnectorsIntegrationTest.testReplication
> org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[true]
>

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
Similar Streams failures again, doesn't seem related:

> org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[false]
> org.apache.kafka.streams.integration.QueryableStateIntegrationTest.shouldAllowConcurrentAccesses

**Review by omkreddy — APPROVED** [review]
@ijuma Thanks for the PR. LGTM.

**Pull request merged**
