### PR TITLE
KAFKA-2507: Replace ControlledShutdown{Request,Response} with o.a.k.c…

### PR DESCRIPTION
**Pull request by granthenke**
….requests equivalent

### CODE REVIEW

**Comment by ijuma** [comment]
We are still using `kafka.api.ControlledShutdownRequest` in `KafkaServer` right?

**Comment by granthenke** [comment]
Yes, but this is only in the version compatibility code for inter broker communication, not in kafkaApis. I think removing that falls under [KAFKA-2075](https://issues.apache.org/jira/browse/KAFKA-2075): Validate that all kafka.api requests has been removed and clean up compatibility code.

**Comment by ijuma** [comment]
The intent of KAFKA-2075 (I filed it) was to replace all usages. We can change the scope if it makes things easier though.

**Comment by ijuma** [comment]
This is blocked by https://github.com/apache/kafka/pull/649

**Comment by granthenke** [comment]
@ijuma I will see if I can remove all usages.

**Comment by granthenke** [comment]
@ijuma Digging in a bit further. We can't make this migration without breaking inter.broker.protocol.version for ControlledShutdownRequest. Since clientId (required by the new protocol header) was not added to the old ControlledShutdownRequest until 0.9.0 (v1). The v0 Request is not compatible with the o.a.k.c requests. We would not be able to support inter.broker.protocol.version for 0.8 versions if we make this change.

I could do the KafkaApis migration by "hacking" some special handling together in RequestChannel. But that would not remove the needed code in KafkaServer and I am not sure thats worth it.

So then the question is when can inter.broker.protocol.version break? How many versions back do we support? (I may need to open a jira to define or document that)

**Comment by ijuma** [comment]
@granthenke Yes, I ran into the same issue while trying to migrate controlled shutdown to `Selector`/`NetworkClient` (and that is why the BlockingChannel implementation still exists).

I am not sure what the policy is regarding how many versions we support. It may be worth sending an email to the mailing list asking about this.

**Comment by granthenke** [comment]
Closing for now pending the compatibility discussion.

**Pull request closed without merging**
