### PR TITLE
MINOR: Improve log4j on stream thread and stream process

### PR DESCRIPTION
**Pull request by enothereska**
Cherry pick from https://github.com/apache/kafka/pull/2685

### CODE REVIEW

**Comment by enothereska** [comment]
@ijuma or @ewencp or @gwenshap could you have a look? Thanks.

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by enothereska** [comment]
kafka.server.SaslSslReplicaFetchTest.testReplicaFetcherThread failed, not related to PR

**Comment by ijuma** [comment]
Merged to 0.10.2, please close the PR.

**Pull request closed without merging**
