### PR TITLE
MINOR: Clean leaking resource in ShareConsumerTest

### PR DESCRIPTION
**Pull request by frankvicky**
We currently do not clean up resources (e.g., producer and consumer) when tests fail. This PR aims to address this issue.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@frankvicky Could you please point out where we might have forgotten to close the consumer or producer?

**Comment by frankvicky** [comment]
Hi @chia7712 
https://github.com/apache/kafka/blob/9f27d997c3ef2f353e2fea3735006b1c1b677cac/core/src/test/java/kafka/test/api/ShareConsumerTest.java#L1258

Before #18053 , this assertion might fail and lead to leaking producer and consumer.

**Comment by chia7712** [comment]
It appears that the issue is not only related to the consumer but also requires us to close the thread pool. Could you please refactor that test case to ensure all resources get closed?

**Comment by frankvicky** [comment]
To ensure that all resources are closed properly during this refactoring, adjustments to the helper method are necessary. The original logic for creating resources was encapsulated within the helper method, so I extracted the resource creation process into the test case. This ensures that the test case uses `try-with-resources` first before passing the resources into the helper method.

**Comment by AndrewJSchofield** [comment]
@frankvicky The latest build had some test failures which could be related. Please investigate.

**Review by apoorvmittal10 — APPROVED** [review]
Thanks for the PR. Apart failing build, changes LGTM!

**Comment by frankvicky** [comment]
Hi @AndrewJSchofield @apoorvmittal10 
I forgot to revert the changes after finishing the local tests, which caused the test to fail. 
It has now been fixed.

https://github.com/apache/kafka/compare/bd2fe95382a114d24cf7e3d3489495c23d23a23c..e836097f1ab5184b54f4645de61cbe4da5af433f

**Comment by frankvicky** [comment]
This issue is invalid after #18105

**Pull request closed without merging**
