### PR TITLE
MINOR: Don't imply that ConsumerGroupCommand won't work with non-Java clients

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@hachikuji @ijuma

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6256/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6272/
Test PASSed (JDK 7 and Scala 2.11).

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Pull request closed without merging**
