### PR TITLE
MINOR: Print offset and size in sendFetches

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
This is from an observation I had while debugging a fetcher case from the log4j entries. It would help a lot if we can log the partition fetch starting offset and size. cc @hachikuji

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by hachikuji** [comment]
@guozhangwang Note that we do print the fetch offsets in `createFetchRequests`, but the level is TRACE. We could also just bump that up to DEBUG. I'm not sure how useful the fetch size is since it comes straight from configuration.

**Comment by guozhangwang** [comment]
@hachikuji sounds good. I agree fetch size is less important. I will bump up the `createFetchRequests` log to DEBUG.

**Comment by guozhangwang** [comment]
@hachikuji Merged after bumping up TRACE to DEBUG in `createFetchRequests`.

**Pull request closed without merging**
