### PR TITLE
KAFKA-8424: replace ListGroups request/response with automated protocol

### PR DESCRIPTION
**Pull request by abbccdda**
As title suggested.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Let's run the system tests before we merge this please.

**Comment by abbccdda** [comment]
@ijuma Sounds good!

**Comment by abbccdda** [comment]
Retest this please

**Comment by abbccdda** [comment]
Verified system test pass: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2673/

**Comment by abbccdda** [comment]
Retest this please

**Comment by abbccdda** [comment]
@ijuma Mind taking another look?

**Comment by abbccdda** [comment]
@ijuma Could you take another look?

**Comment by abbccdda** [comment]
@cmccabe Could you take a look?

**Comment by abbccdda** [comment]
Retest this please

**Comment by abbccdda** [comment]
Retest this please

**Comment by cmccabe** [comment]
Can you re-add the comment about the three possible error codes to ListGroupsResponse?

LGTM once that's added

Thanks, @abbccdda .

**Comment by cmccabe** [comment]
Since the last change was just a comment, and the relevant tests passed previously, will commit.

**Pull request merged**
