### PR TITLE
MINOR: fix checkstyle failures

### PR DESCRIPTION
**Pull request by SinghAsDev**
@guozhangwang could you take a look at this. These failures are a bit annoying as it never leads to a successful build.

### CODE REVIEW

**Comment by guozhangwang** [comment]
@SinghAsDev which gradle command failed on your machine?

**Comment by SinghAsDev** [comment]
@guozhangwang I ran "gradle clean build -x test"

**Comment by ijuma** [comment]
There's something weird going on here. I run checkstyle all the time and I don't get these failures. Are you sure you are not overriding the checkstyle settings in some way?

**Comment by guozhangwang** [comment]
@SinghAsDev I reran your command locally and it works fine. Did you override the checkstyle.xml somehow?

**Comment by SinghAsDev** [comment]
Interesting, I can reproduce this each time.

```
[asingh@asingh-MBP:~]$git clone https://github.com/Apache/kafka
Cloning into 'kafka'...
remote: Counting objects: 33077, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 33077 (delta 19), reused 1 (delta 1), pack-reused 32962
Receiving objects: 100% (33077/33077), 22.98 MiB | 6.21 MiB/s, done.
Resolving deltas: 100% (17086/17086), done.
Checking connectivity... done.
[asingh@asingh-MBP:~]$cd kafka/
[asingh@asingh-MBP:~/kafka]$ls
CONTRIBUTING.md     Vagrantfile     config          doap_Kafka.rdf      gradlew         scala.gradle        tools
HEADER          bin         contrib         docs            gradlew.bat     settings.gradle     vagrant
LICENSE         build.gradle        copycat         examples        kafka-merge-pr.py   streams         wrapper.gradle
NOTICE          checkstyle      core            gradle          kafka-patch-review.py   system_test
README.md       clients         dev-utils       gradle.properties   log4j-appender      tests
[asingh@asingh-MBP:~/kafka]$gradle clean build -x test
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/docs/2.1/userguide/gradle_daemon.html.
Building project 'core' with Scala version 2.10.5
:clean UP-TO-DATE
:clients:clean UP-TO-DATE
:contrib:clean UP-TO-DATE
:copycat:clean UP-TO-DATE
:core:clean UP-TO-DATE
:examples:clean UP-TO-DATE
:log4j-appender:clean UP-TO-DATE
:streams:clean UP-TO-DATE
:tools:clean UP-TO-DATE
:contrib:hadoop-consumer:clean UP-TO-DATE
:contrib:hadoop-producer:clean UP-TO-DATE
:copycat:api:clean UP-TO-DATE
:copycat:file:clean UP-TO-DATE
:copycat:json:clean UP-TO-DATE
:copycat:runtime:clean UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:check
:build
:clients:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: /Users/asingh/kafka/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:clients:processResources UP-TO-DATE
:clients:classes
:clients:determineCommitId UP-TO-DATE
:clients:createVersionFile
:clients:jar
:clients:javadoc
:clients:javadocJar
:clients:srcJar
:clients:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: /Users/asingh/kafka/clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
:clients:processTestResources
:clients:testClasses
:clients:testJar
:clients:signArchives SKIPPED
:clients:assemble
:clients:checkstyleMain
[ant:checkstyle] /Users/asingh/kafka/clients/src/main/java/org/apache/kafka/common/network/SSLChannelBuilder.java:73: method call child at indentation level 12 not at correct indentation, 16
[ant:checkstyle] /Users/asingh/kafka/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java:107: method call child at indentation level 16 not at correct indentation, 20
[ant:checkstyle] /Users/asingh/kafka/clients/src/main/java/org/apache/kafka/common/security/kerberos/Login.java:355: method def throws at indentation level 12 not at correct indentation, 8
:clients:checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clients:checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///Users/asingh/kafka/clients/build/reports/checkstyle/main.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.968 secs
```

**Comment by ijuma** [comment]
It could be a Gradle version problem? Is there a reason why you are using `gradle` instead of `gradlew` which handles versioning correctly?

**Comment by SinghAsDev** [comment]
It works fine with gradlew, however, the styling errors caught look legitimate to me. What do you guys think?

**Comment by ijuma** [comment]
Given the merge conflicts that this would cause, I think we should only go in this direction if we are also interested in changing the checkstyle rules to match.

**Comment by guozhangwang** [comment]
From the logs it seems you are using Gradle 2.1, could you try at least Gradle 2.4 to see if it is still the case (we have just upgraded the default version to 2.8 by @ijuma).

**Comment by SinghAsDev** [comment]
@ijuma you are correct, this will lead to merge conflicts. Given that it is not an issue with correct gradle version, and we document to use ./gradlew anyways, I will go ahead and close this. Thanks for your time @guozhangwang and @ijuma

**Pull request closed without merging**
