### PR TITLE
KAFKA-2756: Use request version Id instead of latest version Id to parse the corresponding response.

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
This patch is submitted by Matthew Bruce.

**Comment by guozhangwang** [comment]
LGTM.

**Comment by StarWindMoonCloud** [comment]
Does it has any functionality impact?
Which release version is the change included?

**Comment by guozhangwang** [comment]
@StarWindMoonCloud It is included in the latest 0.9.0.0 release. It should not have any functionality impact: its previous behavior is incorrect of always using its latest version, while the right behavior should be using the version of the request. The only request version bump is introduced in 0.9.0.0.

**Pull request closed without merging**
