### PR TITLE
[MINOR] refactor return value

### PR DESCRIPTION
**Pull request by khaireddine120**
remove if clause to return boolean value

### CODE REVIEW

**Comment by khaireddine120** [comment]
Hi @mjsax , there is a problem in some check, how can i force to check another time ?

**Comment by mjsax** [comment]
> there is a problem in some check, how can i force to check another time ?

Not sure what you mean by this? Can you elaborate?

**Comment by guozhangwang** [comment]
retest this please

**Comment by khaireddine120** [comment]
Hi @mjsax, i think that i should put 'retest this please' like  @guozhangwang  did :)
Is it right ?

**Review by guozhangwang — APPROVED** [review]

**Comment by mjsax** [comment]
@khaireddine120 Ah. Yes. You can re-trigger the Jenkins build by putting a comment like this. Thanks for the PR!

**Pull request merged**
