### PR TITLE
HOTFIX: ClassCastException in request logging

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
cc @cmccabe @ewencp @ijuma 

When TRACE logging is enabled, we see this:
```
[2017-02-17 23:09:49,444] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ClassCastException: Expected request with type class scala.runtime.Nothing$, but found class org.apache.kafka.common.requests.ApiVersionsRequest
    at kafka.network.RequestChannel$Request.body(RequestChannel.scala:118)
    at kafka.network.RequestChannel$Request.requestDesc(RequestChannel.scala:111)
    at kafka.network.RequestChannel$Request.updateRequestMetrics(RequestChannel.scala:169)
    at kafka.network.Processor$$anonfun$processCompletedSends$1.apply(SocketServer.scala:532)
    at kafka.network.Processor$$anonfun$processCompletedSends$1.apply(SocketServer.scala:528)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at kafka.network.Processor.processCompletedSends(SocketServer.scala:528)
    at kafka.network.Processor.run(SocketServer.scala:434)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by cmccabe** [comment]
LGTM (non-binding)

**Comment by ewencp** [comment]
LGTM, and I assume tests will pass since this wasn't being exercised. Not sure if it's worth adding a test specifically for this, though it seems like we might want to also turn on trace logging during tests or something like that since that's the only way to exercise all code paths like this.

**Comment by hachikuji** [comment]
@ewencp Yeah, agreed. I'll add a JIRA to do that since I'm pretty sure this is not the first time we've had a bug which only affected logging.

**Comment by ijuma** [comment]
@hachikuji, thanks for fixing this. I filed a JIRA for the logging thing a while back due to a similar incident.

**Comment by hachikuji** [comment]
@ijuma No worries. I probably should have tried at least one of the sanity system tests prior to merging.

**Pull request closed without merging**
