### PR TITLE
MINOR: only log error when rack aware assignment is enabled

### PR DESCRIPTION
**Pull request by lihaosky**
This log can appear in constructor. Only log it when RackAwareTaskAssignor is enabled.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by lucasbru — APPROVED** [review]
lgtm, thanks!

**Comment by lihaosky** [comment]
cc @showuon

**Comment by mjsax** [comment]
Thanks for the quick fix! -- Merged to `trunk` and cherry-picked to `3.6` branch -- RC2 was already created. Not sure if there will be an RC3...

**Comment by showuon** [comment]
Thanks for the fix!

**Pull request merged**
