### PR TITLE
MINOR: Convert Stream-StreamJoin Integration Test to TTD

### PR DESCRIPTION
**Pull request by bbejeck**
Convert `StreamStreamJoinIntegrationTest`  to TTD for more stable testing.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping 1 of @mjsax, @vvcephei, @cadonna, and @ableegoldman for review

**Review by mjsax — APPROVED** [review]
LGTM (assuming Jenkins passes). Feel free to merge when build is green.

**Comment by bbejeck** [comment]
Java 8 and Java 11/2.13 passed
Java 11/2.12 timed out `Build timed out (after 270 minutes). Marking the build as aborted.`

retest this please

**Comment by bbejeck** [comment]
Merged #7752 into trunk.

**Comment by bbejeck** [comment]
cherry-picked to 2.4

**Pull request merged**
