### PR TITLE
[Don't merge]KAFKA-16812: The tools-related tests are slow

### PR DESCRIPTION
**Pull request by TaiJuWu**
Related: KAFKA-16812

*More detailed description of your change,

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
Just a quick suggestion. It would be nice to figure out the bottleneck first. For example, maybe there are some redundant tests or incorrect configs.

**Comment by TaiJuWu** [comment]
We can get test report from 
`tools/build/test-results/test/TEST-org.apache.kafka.tools.TopicCommandIntegrationTest.xml`

We find this bottleneck is `setup` so we can merge a small tests to a large one.

**Comment by chia7712** [comment]
@TaiJuWu As TopicCommandIntegrationTest is a large test, could you please try to file multiple PRs to move it to TopicCommandTest with new test infra and refactor (you described) ?

**Comment by TaiJuWu** [comment]
> @TaiJuWu As TopicCommandIntegrationTest is a large test, could you please try to file multiple PRs to move it to TopicCommandTest with new test infra and refactor (you described) ?

Sure.

**Pull request closed without merging**
