### PR TITLE
KAFKA-3483: Restructure ducktape tests to simplify running subsets of…

### PR DESCRIPTION
**Pull request by granthenke**
… tests

### CODE REVIEW

**Comment by granthenke** [comment]
@benstopford Thoughts on this?

I have not been able to verify completely due to setup issues in my environment. But will work on running all the tests to validate the change.

**Comment by ijuma** [comment]
Cc @granders

**Comment by granthenke** [comment]
Thanks @ijuma. Thats who I meant. :)

**Comment by granthenke** [comment]
@granders Any thoughts?

**Comment by granders** [comment]
@granthenke Thanks for the PR -  the overall organization is looking great! 
Just a few observations:
- like `kafka_test.py`, `produce_consume_validate.py` is shared by multiple tests, so it probably doesn't belong under client - you can probably restore to its original location.
- there are some broken import statements caused by the shuffle - restoring `produce_consume_validate.py` to original location will probably be enough

One way to check that you're on the right track is to list the tests picked up by test discovery mechanism in both trunk and your branch. A necessary condition for success is that the collection of tests picked up should match between branches:

```
cd kafka
ducktape tests/ --collect-only  # compare (apache/kafka) trunk vs your branch

# you may want to clean out .pyc files etc when you move stuff around:
# find . | grep -E "(__pycache__|\.pyc$)" | xargs rm -rf
```

When I try this in your branch, I only pick up 62 tests out of ~160. This is most likely caused the broken imports I mentioned.

Once imports are fixed, we can run the tests in branch builder to make sure that tests can still pick up the templates they need. The layout looks right, but it will be good to validate this.

**Comment by granthenke** [comment]
@granders Thanks for the review! I am absolutely a ducktape and python noob. So I really appreciate the detailed feedback.

**Comment by granders** [comment]
np :) btw, are you planning to double-commit this to 0.10.0?

**Comment by granthenke** [comment]
I would be happy to see it be double committed...but thats up to the committers (cc @gwenshap)

**Comment by granthenke** [comment]
@granders I update the pull request. I needed to move 2 files from clients that were used in other tests and rebase on trunk. Once I did that, I ran the commands you suggested in this branch and trunk:

```
find . | grep -E "(__pycache__|\.pyc$)" | xargs rm -rf
ducktape tests --collect-only
```

Both outputted `Collected 158 tests:...`

**Comment by gwenshap** [comment]
With the delay in release, we'll be merging trunk into 0.10.0 on weekly basis, so don't worry about double commits.

**Comment by granders** [comment]
@granthenke thanks, I kicked off a test run on your branch
https://jenkins.confluent.io/job/system-test-kafka-branch-builder/403/console

**Comment by ewencp** [comment]
Test run looks good (there was a transient failure, but number of tests is fine), reorg looks mostly good to me. @granthenke is there a reason things like `consumer_group_command_test.py` and `get_offset_shell_test.py` should be under `core` instead of `tools`? Not sure exactly how you wanted to break these down, but `core` struck me as being the name for core broker tests, whereas tools would cover things like CLI tools. Something like MM is a case where I'm not sure where it should live...

But otherwise, this LGTM

**Comment by granthenke** [comment]
@ewencp My intent was to match the module structure. The log4-appender tests use VerifiableLog4jAppender which is in the tools module. The other pieces under tools are shared among the tests so I did not put them in the tools folder.

**Comment by ewencp** [comment]
@granthenke Oh, duh, my bad for missing that. In that case, LGTM.

**Pull request closed without merging**
