### PR TITLE
Increase default Xmx for console commands.

### PR DESCRIPTION
**Pull request by allenxiang**
Increase default Xmx for console commands from 256M to 1024M.

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Which command needs this much memory?

**Comment by allenxiang** [comment]
kafka-consumer-groups needs more than 256M. I believe 512M should work, but I guess nowadays developers' computers have way more memory than 512M. So just put 1024M there since it does not hurt anything.

**Comment by ijuma** [comment]
Thanks. True about laptops, but Docker containers often have a limited amount of memory.

**Comment by allenxiang** [comment]
Good point. I've updated my pull request to only change Xms for kafka-consumer-groups.sh from 256M to 512M.

**Pull request closed without merging**
