### PR TITLE
KAFKA-2866: Bump up commons-collections version to 3.2.2 to address a…

### PR DESCRIPTION
**Pull request by granthenke**
… security flaw

### CODE REVIEW

**Comment by granthenke** [comment]
This is not a huge deal since its only in test dependencies. But since we publish test jars in maven and the fix is easy...I figure we should fix it.

**Comment by ijuma** [comment]
Do we know which dependencies are bringing this transitively?

**Comment by granthenke** [comment]
This is brought in via `org.apache.hadoop:hadoop-minikdc:2.7.1`. 

[HADOOP-12577](https://issues.apache.org/jira/browse/HADOOP-12577) should fix this in `2.7.2`. When `2.7.2` is released we can upgrade minikdc and remove this addition.

**Comment by ijuma** [comment]
I'd probably just wait for minikdc 2.7.2 (seems like it will be out soon https://github.com/apache/hadoop/commit/97a98b640d1c2d6fc84ac8ac5cad7e7e1b9dbd14) since the issue only affects test jars and we are not publishing new test jars so soon anyway.

**Pull request closed without merging**
