### PR TITLE
MINOR: Close the producer batch data stream when the batch gets full to free up compression buffers, etc.

### PR DESCRIPTION
**Pull request by apurvam**

### CODE REVIEW

**Comment by apurvam** [comment]
cc @ijuma

**Comment by apurvam** [comment]
Actually, I am going to add another commit to this to address some of Jun's comments. So don't review / merge yet!

**Comment by apurvam** [comment]
This is open for review again.

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Pull request closed without merging**
