### PR TITLE
KAFKA-16329 : Remove deprecated classes in streams

### PR DESCRIPTION
**Pull request by muralibasani**
Resolves https://issues.apache.org/jira/browse/KAFKA-16329

Remove deprecated classes as mentioned in the Jira ticket.

### Committer Checklist (excluded from commit message)
- [X] Verify design and implementation 
- [X] Verify test coverage and CI build status
- [X] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Any reason why you did a single PR for two tickets? It's cleaner if a PR does not fix multiple tickets (also easier to review if PRs are smaller).

**Comment by muralibasani** [comment]
> Any reason why you did a single PR for two tickets? It's cleaner if a PR does not fix multiple tickets (also easier to review if PRs are smaller).

@mjsax I interpreted it differently when you mentioned that both tickets should be worked together in the description of ticket.
Indeed it's cleaner with smaller PRs.
Will split this one today.

**Comment by muralibasani** [comment]
> > Any reason why you did a single PR for two tickets? It's cleaner if a PR does not fix multiple tickets (also easier to review if PRs are smaller).
> 
> @mjsax I interpreted it differently when you mentioned that both tickets should be worked together in the description of ticket. Indeed it's cleaner with smaller PRs. Will split this one today.



> > Any reason why you did a single PR for two tickets? It's cleaner if a PR does not fix multiple tickets (also easier to review if PRs are smaller).
> 
> @mjsax I interpreted it differently when you mentioned that both tickets should be worked together in the description of ticket. Indeed it's cleaner with smaller PRs. Will split this one today.

@mjsax just realized I haven't made any changes related to 16330 in this PR. So we are all good.

**Comment by mjsax** [comment]
Ah. Thanks for clarification. And thanks for the PR. Merged to `trunk`.

**Comment by muralibasani** [comment]
> Ah. Thanks for clarification. And thanks for the PR. Merged to `trunk`.

Thank you.

**Pull request merged**
