### PR TITLE
KAFKA-2875:  remove slf4j multi binding warnings when running form source distribution

### PR DESCRIPTION
**Pull request by jinxing64**

### CODE REVIEW

**Comment by jinxing64** [comment]
@junrao ~Since all subprojects reply on slf4j-log4j12, may I move slf4j-log4j12-1.7.10.jar to root project's build directory? By this way, we can fix KAFKA-2875 multi slf4j binding warnings~

**Comment by jinxing64** [comment]
@guozhangwang I moved slf4j-log4j12 dependency to root project 'build' directory, is this a good way to fix KAFKA-2875

**Comment by ijuma** [comment]
Thanks for the PR @ZoneMayor.

I am not sure about the approach, it seems a bit of a hack to create a root project for the sole purpose of depending on slf4j-log4j12.

Looking at the output below, there are two problems:
- We depend on slf4j 1.7.6 and some other library depends on slf4j 1.7.10

This is relatively straightforward: we should bump our version to 1.7.13 (the latest) and we should exclude the transitive dependency from the library that's bringing 1.7.10.
- `kafka-run-class` builds the classpath by adding the dependent libraries of several subprojects, so we end up including slf4j-log4j12 multiple times.

This is a bit odd and it seems like a hack. I am not familiar with why we follow that approach instead of building a classpath that is appropriate to the class being started (ie the classpath for the project it is part of). @ewencp, do you know?

With the current approach, it's a bit hard to fix the issue (we can't filter duplicates trivially when constructing the classpath because we are relying on wildcards to build the classpath - in order not to exceed command-line length limits on certain platforms).

Warnings:

``` sh
SLF4J: Found binding in [jar:file:/Users/ijuma/src/kafka/core/build/dependant-libs-2.10.6/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ijuma/src/kafka/core/build/dependant-libs-2.10.6/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ijuma/src/kafka/tools/build/dependant-libs-2.10.6/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ijuma/src/kafka/connect/api/build/dependant-libs/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ijuma/src/kafka/connect/runtime/build/dependant-libs/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ijuma/src/kafka/connect/file/build/dependant-libs/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ijuma/src/kafka/connect/json/build/dependant-libs/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```

**Comment by ewencp** [comment]
@ijuma I think the way this is built up is partly historical, partly convenience. There used to only be the one project, so everything was simple and we could use the standardized `kafka-run-class`. I think it continued to be used as we added more subprojects and just continued to accumulate code and CLASSPATHs to handle different projects. `kafka-run-class` does enough useful stuff that it'd be painful to maintain separate copies of it as they will diverge, we'd need to be very vigilant about applying fixes across all of them, etc.

I think the best solution is probably to refactor the scripts so we can pull CLASSPATH setup to parent scripts, and in the few cases where it makes sense (e.g. the dozens of tools scripts), provide wrapper helper scripts, e.g. `kafka-tools-run-class` which is a small wrapper around `kafka-run-class` and allows us to keep all the tool-specific scripts simple.

Wrt dependencies, I think this is also due to the way we currently collect dependent libs. I'm honestly not sure how to do this better with gradle, but we need to sort out shared dependencies and be able to filter transitive dependencies that are already available elsewhere via the classpath.

**Comment by ijuma** [comment]
Thanks for the explanation @ewencp. I agree that we should not duplicate the logic in `kafka-run-class` and your suggestion is similar to what I was thinking.

@ZoneMayor, given what was discussed, this turns out to be a bigger task than what the JIRA indicates. And there are some details that need to be worked out. Are you interested in exploring a solution along the lines of what @ewencp described?

**Comment by jinxing64** [comment]
@ijuma , I have lots of interest to work this out~, and will raise idea later

**Pull request closed without merging**
