### PR TITLE
MINOR: Fix `testResolveDnsLookup` by using a mocked dns resolver

### PR DESCRIPTION
**Pull request by ijuma**
This focuses on the currently failing test, #9315 is a more complete fix
that we should also review and merge.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
I will cherry-pick this to older branches.

**Review by dajac — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Since this only updates a unit test and the ARM build passed, I'll go ahead and merge.

**Comment by ijuma** [comment]
Merged to master and cherry-picked to 3.0. The test was a bit different in 2.8 and earlier, so we'll probably need a separate PR for that.

**Comment by ijuma** [comment]
Cherry-picked to older branches (2.2...2.8).

**Pull request merged**
