### PR TITLE
Use Set instead of List for list of topics

### PR DESCRIPTION
**Pull request by joan38**
`Set` make sense here since we don't care about the order and we don't want duplicates.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by debasishg** [comment]
I don't think passing `Iterable` is a good option in this case. Internally `StreamsBuilder.stream` calls `topics.toArray`, which will not terminate for infinite sized collections. Hence if someone passes a `Stream`, which is also an instance of `Iterable`, the API will crash.

**Comment by joan38** [comment]
Actually I was thinking `Seq` would be better. But we would still have the Stream issue.
It just feels strange to restrict a specific implementation of collection here.

**Comment by debasishg** [comment]
I think restriction here makes sense to make the API safe. It uses `.size` and `.toArray` under the covers - and `List` does both in constant time.

**Comment by joan38** [comment]
`.size` on a`List` is O(n) but this is not important here on such a small list.
If the order is not important probably the best is a `Set`?

**Comment by guozhangwang** [comment]
The order does not matter indeed, but I'll leave to @debasishg to decide if it is better than the current `List` before the release.

**Comment by debasishg** [comment]
`Set` is possibly ideal here - also eliminates duplicates, which *we should not be having in the list of topics*. The flip side (minor) is that every time the user calls this API she has to convert her collection to a `Set`, assuming the common case that she may be holding a `List`.

**Comment by debasishg** [comment]
@joan38 In case u change it to `Set`, be sure to update the tests.

**Comment by joan38** [comment]
@debasishg I made the change. Which test you meant?

**Comment by debasishg** [comment]
I meant the unit tests. But then I remembered there was no test with multiple topics ..

**Comment by joan38** [comment]
All good then now? @debasishg @guozhangwang

**Comment by debasishg** [comment]
👍

**Review by guozhangwang — APPROVED** [review]

**Comment by joan38** [comment]
Cheers @debasishg and @guozhangwang

**Pull request merged**
