### PR TITLE
 KAFKA-1429: Yet another deadlock in controller shutdown

### PR DESCRIPTION
**Pull request by pengwei-li**
Author: pengwei pengwei.li@huawei.com

 Reviewers: NA

### CODE REVIEW

**Comment by pengwei-li** [comment]
I try to fix this issue, can anyone review this fix is OK?

**Comment by pengwei-li** [comment]
Controller session expire and holding the controllerLock lock and try to wait the autoRebalanceScheduler thread to shutdown, but 
the autoRebalanceScheduler is running for the parttion rebalance and this thread want the controllerLock

**Comment by pengwei-li** [comment]
@junrao  @nehanarkhede   Can you review the fix for this bug?  I think this bug is a serious issue, it will cause the controller not working. Thanks~

**Comment by junrao** [comment]
@pengwei-li : Sorry for the late response. It seems that the same issue has been fixed in https://issues.apache.org/jira/browse/KAFKA-4360? If so, could you close this PR?

**Comment by pengwei-li** [comment]
@junrao  yes , this bug also fixed by Kafka-4360,  close this PR is OK

**Comment by junrao** [comment]
@pengwei-li : Thanks. It seems that only you can close this PR.

**Comment by pengwei-li** [comment]
close this PR because KAFKA-4360 also fix this bug

**Pull request closed without merging**
