### PR TITLE
Modified the async producer so it re-queues failed batches.  

### PR DESCRIPTION
**Pull request by hiloboy0119**
I'm working on an application that needs the throughput offered by an async producer but also needs to handle send failures gracefully like a sync producer.  I modified the ProducerSendThread so it will re-queue failed batches.  This allowed me to determine the behavior I wanted from my producer with the queue config parameters.

A "queue.enqueue.timeout.ms=0" allowed me to get runtime exceptions when sends failed often enough to fill the queue.  This also allowed me to use "queue.buffering.max.messages" to control how tolerant the application is to network blips.

### CODE REVIEW

**Comment by ijuma** [comment]
This pull request doesn't merge cleanly anymore, can you please close it?

Sorry for not replying to this earlier, but pull requests are not currently monitored as the Kafka project uses JIRA and Review Board for contributions. There is a plan to change this and we would like to close stale PRs before we start. Unfortunately we can't do it ourselves (a JIRA needs to be filed with Apache Infra) so your help is appreciated.

If this change is still relevant, please see http://kafka.apache.org/contributing.html. Alternatively wait until the new approach based on GitHub pull requests is in place (hopefully soon).

**Comment by b-goyal** [comment]
I'm working on an application that needs the throughput offered by an async producer but also needs to handle send failures gracefully like a sync producer.  I modified the ProducerSendThread so it will re-queue failed batches.  This allowed me to determine the behavior I wanted from my producer with the queue config parameters.

A "queue.enqueue.timeout.ms=0" allowed me to get runtime exceptions when sends failed often enough to fill the queue.  This also allowed me to use "queue.buffering.max.messages" to control how tolerant the application is to network blips.

**Comment by b-goyal** [comment]
I'm working on an application that needs the throughput offered by an async producer but also needs to handle send failures gracefully like a sync producer.  I modified the ProducerSendThread so it will re-queue failed batches.  This allowed me to determine the behavior I wanted from my producer with the queue config parameters.

A "queue.enqueue.timeout.ms=0" allowed me to get runtime exceptions when sends failed often enough to fill the queue.  This also allowed me to use "queue.buffering.max.messages" to control how tolerant the application is to network blips.

**Comment by b-goyal** [comment]
I'm working on an application that needs the throughput offered by an async producer but also needs to handle send failures gracefully like a sync producer.  I modified the ProducerSendThread so it will re-queue failed batches.  This allowed me to determine the behavior I wanted from my producer with the queue config parameters.

A "queue.enqueue.timeout.ms=0" allowed me to get runtime exceptions when sends failed often enough to fill the queue.  This also allowed me to use "queue.buffering.max.messages" to control how tolerant the application is to network blips.

**Comment by b-goyal** [comment]
I'm working on an application that needs the throughput offered by an async producer but also needs to handle send failures gracefully like a sync producer.  I modified the ProducerSendThread so it will re-queue failed batches.  This allowed me to determine the behavior I wanted from my producer with the queue config parameters.

A "queue.enqueue.timeout.ms=0" allowed me to get runtime exceptions when sends failed often enough to fill the queue.  This also allowed me to use "queue.buffering.max.messages" to control how tolerant the application is to network blips.

**Comment by b-goyal** [comment]
I'm working on an application that needs the throughput offered by an async producer but also needs to handle send failures gracefully like a sync producer.  I modified the ProducerSendThread so it will re-queue failed batches.  This allowed me to determine the behavior I wanted from my producer with the queue config parameters.

A "queue.enqueue.timeout.ms=0" allowed me to get runtime exceptions when sends failed often enough to fill the queue.  This also allowed me to use "queue.buffering.max.messages" to control how tolerant the application is to network blips.

**Comment by b-goyal** [comment]
I'm working on an application that needs the throughput offered by an async producer but also needs to handle send failures gracefully like a sync producer.  I modified the ProducerSendThread so it will re-queue failed batches.  This allowed me to determine the behavior I wanted from my producer with the queue config parameters.

A "queue.enqueue.timeout.ms=0" allowed me to get runtime exceptions when sends failed often enough to fill the queue.  This also allowed me to use "queue.buffering.max.messages" to control how tolerant the application is to network blips.

**Pull request closed without merging**
