### PR TITLE
MINOR: Tuple2 replaced with Map.Entry

### PR DESCRIPTION
**Pull request by nizhikov**
`Tuple2` replaced with SDK `Map.Entry` and `SimleImmutableEntry`.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by nizhikov** [comment]
This PR is follow-up for #14471

**Comment by chia7712** [comment]
@nizhikov This is unrelated to KAFKA-14589, so please use "MINOR:" instead of "KAFKA-14589" :)

**Comment by nizhikov** [comment]
Done.

**Review by chia7712 — APPROVED** [review]
LGTM, pending for QA

**Comment by chia7712** [comment]
@nizhikov could you please rebase code to trigger QA again? one of build is shutdown :(

**Comment by chia7712** [comment]
the failed tests pass on my local
```
./gradlew cleanTest :tools:test --tests MetadataQuorumCommandTest.testDescribeQuorumReplicationSuccessful --tests MetadataQuorumCommandTest.testDescribeQuorumStatusSuccessful :metadata:test --tests QuorumControllerMetricsIntegrationTest.testClosingQuorumControllerClosesMetrics --tests QuorumControllerTest.testBrokerHeartbeatDuringMigration :connect:mirror:test --tests MirrorConnectorsWithCustomForwardingAdminIntegrationTest.testReplicateSourceDefault --tests MirrorConnectorsIntegrationTransactionsTest.testReplicationWithEmptyPartition :core:test --tests PlaintextAdminIntegrationTest.testAlterReplicaLogDirs --tests DelegationTokenEndToEndAuthorizationWithOwnerTest.testNoProduceWithDescribeAcl --tests DelegationTokenEndToEndAuthorizationWithOwnerTest.testProduceConsumeViaSubscribe --tests ReplicaManagerTest.testRemoteFetchExpiresPerSecMetric --tests SaslGssapiSslEndToEndAuthorizationTest.testProduceConsumeTopicAutoCreateTopicCreateAcl --tests ControllerRegistrationManagerTest.testWrongIncarnationId --tests LogDirFailureTest.testIOExceptionDuringLogRoll --tests LogDirFailureTest.testIOExceptionDuringCheckpoint --tests ProducerIdManagerTest.testUnrecoverableErrors :clients:test --tests StickyAssignorTest.testLargeAssignmentAndGroupWithNonEqualSubscription
```
will merge it tomorrow

**Comment by nizhikov** [comment]
Hello @chia7712 Are you ready to merge this PR?

**Comment by chia7712** [comment]
```
./gradlew cleanTest :tools:test --tests MetadataQuorumCommandTest.testDescribeQuorumReplicationSuccessful --tests MetadataQuorumCommandTest.testDescribeQuorumStatusSuccessful :metadata:test --tests QuorumControllerMetricsIntegrationTest.testClosingQuorumControllerClosesMetrics --tests QuorumControllerTest.testBrokerHeartbeatDuringMigration :connect:mirror:test --tests MirrorConnectorsWithCustomForwardingAdminIntegrationTest.testReplicateSourceDefault --tests MirrorConnectorsIntegrationTransactionsTest.testReplicationWithEmptyPartition :core:test --tests PlaintextAdminIntegrationTest.testAlterReplicaLogDirs --tests DelegationTokenEndToEndAuthorizationWithOwnerTest.testNoProduceWithDescribeAcl --tests DelegationTokenEndToEndAuthorizationWithOwnerTest.testProduceConsumeViaSubscribe --tests ReplicaManagerTest.testRemoteFetchExpiresPerSecMetric --tests SaslGssapiSslEndToEndAuthorizationTest.testProduceConsumeTopicAutoCreateTopicCreateAcl --tests ControllerRegistrationManagerTest.testWrongIncarnationId --tests LogDirFailureTest.testIOExceptionDuringLogRoll --tests LogDirFailureTest.testIOExceptionDuringCheckpoint --tests ProducerIdManagerTest.testUnrecoverableErrors :clients:test --tests StickyAssignorTest.testLargeAssignmentAndGroupWithNonEqualSubscription
```
all failed tests pass on my local. will merge it.

**Comment by chia7712** [comment]
@nizhikov thanks for this refactor!

**Pull request merged**
