### PR TITLE
KAFKA-3924: Replacing halt with exit upon LEO mismatch to trigger gra…

### PR DESCRIPTION
**Pull request by maysamyabandeh**
…ceful shutdown

The patch is pretty simple and the justification is explained in https://issues.apache.org/jira/browse/KAFKA-3924

I could not find Andrew Olson, who seems to be the contributor of this part of the code, in github so I am not sure whom I should ask to review the patch.

 the contribution is my original work and that i license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by noslowerdna** [comment]
The patch looks good from here.

-Andrew

**Comment by maysamyabandeh** [comment]
Thanks @noslowerdna for the review.

@gwenshap @ijuma @junrao I am tagging you since you were the latest committers to this file: ReplicaFetcherThread.scala do you think we can land this simple patch?

**Comment by ijuma** [comment]
Thanks for the PR, it seems to make sense, but I'll wait for @junrao to weigh in as well.

**Comment by junrao** [comment]
Thanks for the patch. LGTM

**Pull request closed without merging**
