### PR TITLE
MINOR: Removed explicit class checks for PolicyViolationException

### PR DESCRIPTION
**Pull request by edoardocomar**
PolicyViolationException is a subclass of ApiException, 
and the handling was identical

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/294/

**Comment by edoardocomar** [comment]
retest this please

**Comment by edoardocomar** [comment]
the failure in https://builds.apache.org/job/kafka-pr-test-coverage/294/ is this known transient test failure https://issues.apache.org/jira/browse/KAFKA-6528

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/322/

**Comment by edoardocomar** [comment]
pinging @rajinisivaram

**Review by rajinisivaram — APPROVED** [review]
@edoardocomar Thanks for the PR, LGTM. Merging to trunk.

**Pull request merged**
