### PR TITLE
KAFKA-3475; Introduce our own `MiniKdc`

### PR DESCRIPTION
**Pull request by ijuma**
This also fixes KAFKA-3453 and KAFKA-2866.

### CODE REVIEW

**Comment by ijuma** [comment]
Started a system tests run as `MiniKdc` is also used by system tests:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder/396/console

**Comment by ijuma** [comment]
Tests passed locally, Jenkins failure is in the streams code, which is unrelated.

**Comment by ijuma** [comment]
Fixed `minikdc.py` and started another system tests build:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder/397/

**Comment by ijuma** [comment]
There was an unrelated transient failure with security protocol PLAINTEXT. To be sure, I launched another branch builder job, which had a different transient failure with security protocol SSL:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/46/console

So, I think this PR is fine.

Review by @gwenshap

**Comment by gwenshap** [comment]
Looks awesome to me. I like how flexible the class is :)

**Pull request closed without merging**
