### PR TITLE
throw exception when the connection is error.

### PR DESCRIPTION
**Pull request by white-poto**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@huyanping The reason we did not throw exception is to avoid polluting the logs under unstable network environment or there are "crappy" clients that keep dropping the connection. Any specific reasons you want to throw exceptions so we can think of a different way to resolve it?

**Comment by white-poto** [comment]
@guozhangwang There are many reasons that can close the connection, it will be better if there are some useful information in the log. 

A few days ago, I found that my colleague's consumer often stopped to consume messages. And I could not find any immediate reason in the log, so I modify the kafka source code and found that the reason is a  interrupt of the consumer thread.

**Comment by guozhangwang** [comment]
The observation we had before is that although with a few number of clients it may help, with a large scale number of clients, it is likely that the broker's logs be swamped with error messages like such which will actually make debugging harder rather than easier.

One alternative approach would be adding the error logging on the client side if the connection get dropped, by doing this we will not put the heavy burden of logging on the server side but distribute them on the client side.

**Comment by white-poto** [comment]
The log I checked was on the client side and I am sure that the code I modified was called by the client. I forget if I checked the log on the server side or not, but it is clear that the connection is closed by some reason on the client side.

**Comment by guozhangwang** [comment]
`BlockingChannel.scala` is used by both the old Scala consumer as well as the server, so adding this log entry will affect both the client and the server.

In the new consumer available since 0.9, we used a new Java class `Selector` for NIO, and I checked its source code: for similar connection dropped issue, it will indeed log a debug entry. Would you like to take a look at the new consumer and see if you are willing to upgrade to that client?

**Comment by white-poto** [comment]
@guozhangwang Thank you for your attention and research on this issue. It is perfect that there is no connection dropped issues in the new versions, and I will have a try.

Please feel free to close this issue:)

**Comment by guozhangwang** [comment]
@huyanping Just to clarify, in the new consumer client it is still possible that the connections are dropped, but the new client's internal NIO channel implementation will log it.

Since I cannot close this PR myself, could you close it then?

**Comment by white-poto** [comment]
@guozhangwang Thank you again.

**Pull request closed without merging**
