### PR TITLE
MINOR: Improve exception message that gets thrown for non-existent group

### PR DESCRIPTION
**Pull request by SinghAsDev**

### CODE REVIEW

**Comment by SinghAsDev** [comment]
@hachikuji @guozhangwang could you take a look at this trivial patch.

**Comment by guozhangwang** [comment]
@SinghAsDev We could have other protocol types moving forward besides "kafka consumer", like "kafka connector" and "kafka stream", so this log entry is not completely wrong. Maybe we can reword it as

`"Group {group-id} is not a valid kafka consumer group but belongs to {@protocol_type if not empty, otherwise "not exist"}."`

**Comment by SinghAsDev** [comment]
@guozhangwang done.

**Comment by eribeiro** [comment]
Nit: If it falls in the else condition it will print "that belongs to not exist" that seems non sensical, IMHO. What about "belongs to none"? Or something alike. Up to you. :)

**Comment by guozhangwang** [comment]
LGTM.

**Comment by eribeiro** [comment]
Haha, okay then ¯_(ツ)_/¯'

**Pull request closed without merging**
