### PR TITLE
KAFKA-7707: remove  the code never execute

### PR DESCRIPTION
**Pull request by huangyiminghappy**
in the BufferPool,the waiters is locked by ReentrantLock,and the waiters add Condition all within the lock,and the waiters remove also within the lock.in the waiters there is only one   Condition instance.
image
and in the finally we have remove the waiters's condition,so in the finally, we use the 
```   java
finally {
            // signal any additional waiters if there is more memory left
            // over for them
            try {
                if (!(this.nonPooledAvailableMemory == 0 && this.free.isEmpty()) && !this.waiters.isEmpty())
                    this.waiters.peekFirst().signal();
            } finally {
                // Another finally... otherwise find bugs complains
                lock.unlock();
            }
        }
``` 
can modify like 
```   java
finally {
            lock.unlock();
        }
``` 
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
cc @smccauliff

**Review by hachikuji — COMMENTED** [review]
@huangyiminghappy I'm a little confused why you think it is not possible to have multiple waiters. When we await the condition, the lock is released. Am I missing something?

**Comment by huangyiminghappy** [comment]
@hachikuji  thank you review, may be i missing something,i read  the BufferPool,found  during the lock,only one thread can run,and one condition can  add to the waiters,and during the lock ,the condition is remove by waiters, at this time i think this.waiters.peekFirst() is not required.

**Comment by huxihx** [comment]
@huangyiminghappy The lock will be released when `moreMemory.await` is called and other thread(s) might add themselves as new waiters. Does it make sense?

**Comment by huangyiminghappy** [comment]
> @huangyiminghappy The lock will be released when `moreMemory.await` is called and other thread(s) might add themselves as new waiters. Does it make sense?

thank you,i have not pay attention the moreMemory.await,in deallocate method ,it will signal that notice  it may have memory to allocate

**Comment by hachikuji** [comment]
@huangyiminghappy Thanks for the response. It sounds like you are convinced that the current implementation works? Shall we close this or do you think there is still an issue?

**Comment by huangyiminghappy** [comment]
> entation works? Shall we close this or d

thank you ,i close this issue

**Pull request closed without merging**
