### PR TITLE
MINOR: Remove KafkaTimer

### PR DESCRIPTION
**Pull request by ijuma**
It doesn't add much value since lambdas
were introduced in Java 8.

Also remove KafkaTimerTest.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by SoulPancake — CHANGES_REQUESTED** [review]
Can you try to resolve the java.util.concurrent.ExecutionException which is failing the checks

**Comment by ijuma** [comment]
@Anuragkillswitch Can you clarify what you mean? I don't see those errors in the CI builds.

**Comment by SoulPancake** [comment]
@ijuma  I can see multiple tests failing
image
e.g.
image

**Review by dajac — APPROVED** [review]
LGTM, thanks.

**Review by clolov — APPROVED** [review]

**Review by SoulPancake — APPROVED** [review]

**Pull request merged**
