### PR TITLE
KAFKA-9159: The caller of sendListOffsetRequest need to handle retriable InvalidMetadata

### PR DESCRIPTION
**Pull request by zzccctv**
loop call Consumer.endOffsets Throw TimeoutException: Failed to get offsets by times in 30000ms after a leader change

### CODE REVIEW

**Review by StevenLuMT — APPROVED** [review]
it looks reasonable

**Comment by guozhangwang** [comment]
Thanks for the PR. I looked into the source code and here's my conclusion:

* `sendListOffsetRequest` is called by two callers, `resetOffsetsAsync` and `fetchOffsetsByTimes`. And there are two cases that we need to handle by requesting metadata update:

1. we found that the metadata does not contain topic-partition for list-offset yet before sending the list-offset request.
2. we found the returned list-offset response contains InvalidMetadataException which could be caused by various reasons.

Right now 1) is covered by the `groupListOffsetRequests` function which is called by both of the callers too; but for 2) it used to be covered in the caller (`fetchOffsetsByTimes`) but got removed in https://github.com/apache/kafka/pull/4557/files#diff-b45245913eaae46aa847d2615d62cde0R433 cc @hachikuji 

As for the fix, I'd suggest making it more general as:

```
...
            } else if (!future.isRetriable()) {
                throw future.exception();
            } else {
               metadata.requestUpdate();
            }
```

And leave the current line as is.

-------

Another code refactoring to consider is that `groupListOffsetRequests` is called by both callers too, and currently we are relying on its logic to do 1) above is dangerous (e.g. if we add another callee but forget to call this function). We can consider refactoring the code to make `groupListOffsetRequests` just as a callee of `sendListOffsetRequest` (may need to change its signature a bit) which is called by both callers to make the current logic less bug vulnerable.

**Comment by zzccctv** [comment]
Problems still exist when a leader change
`...
            } else if (!future.isRetriable()) {
                throw future.exception();
            } else {
               metadata.requestUpdate();
            }`

**Comment by guozhangwang** [comment]
@zzccctv could you also consider adding a unit test inside FetcherTest to verify that the handling logic for both 1) / 2) are now covered? And if you'd like to leave the refactoring that I suggested above to another PR that's also fine, could you file a JIRA so that we do not lose it on the floor too?

**Comment by zzccctv** [comment]
@guozhangwang i consider testGetOffsetsForTimesWhenSomeTopicPartitionLeadersNotKnownInitially has been verified 1),so adding a unit test inside FetcherTest to verify 2)

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
Thanks for the updated unit test @zzccctv , the jenkins failures seem to be related though, could you look into them to make sure they are green before we can merge this PR?

**Comment by zzccctv** [comment]
@guozhangwang the jenkins seems that the environment is unstable,The results of the same code are different in different environments,how to retry a failed environment?

**Comment by guozhangwang** [comment]
It is a bit unstable yes, what I'm looking for is that there's no repeated failure across all runs, now it seems fine.

**Comment by guozhangwang** [comment]
BTW could you verify in your production that this bug-fix indeed resolve the issue you observed?

**Comment by zzccctv** [comment]
@guozhangwang our operation has restarted dozens of brokers in recent days,The Consumer.endOffsets is running normally and is not throwing TimeoutException,It seems that the problem has been solved

**Comment by guozhangwang** [comment]
Great, thanks for the confirmation @zzccctv , and thank you for contributing to Apache Kafka!

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request merged**
