### PR TITLE
MINOR: mention KAFKA-15905 in docs "Notable changes in 3.7.1"

### PR DESCRIPTION
**Pull request by edoardocomar**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by edoardocomar** [comment]
As discussed in https://github.com/apache/kafka/pull/15910#issuecomment-2127588361

**Review by gharris1727 — COMMENTED** [review]
Can you also add a 3.8.0 notable changes? The wording looks fine to me.

**Comment by edoardocomar** [comment]
Do you want an empty one? I’d assume what’s new for 3.7.1 is Included in 3.8 …

**Comment by gharris1727** [comment]
> I’d assume what’s new for 3.7.1 is Included in 3.8 …

I don't think everyone thinks this way. Someone can easily read the 3.8.0 release notes and never read the 3.7.1 notes. I'm also not sure which will release first.

**Comment by edoardocomar** [comment]
@gharris1727 please have a look if this is what you had in mind

I'm not sure I'm comfortable with repeating the info in two sections.
moreover the trunk docs only mention 3.7.1 so far, so in backporting the docs to 3.7.1 I should only pick the first of the two commits in this PR. 

IMHO it'd be cleaner to only have thoe docs for 3.7.1 and commit the same to trunk and 3.7.1

**Review by gharris1727 — APPROVED** [review]
> I'm not sure I'm comfortable with repeating the info in two sections.

I would rather duplicate information than risk users not being aware of this change.

> I should only pick the first of the two commits in this PR.

I trust you to cherry-pick this correctly. If you want to create a PR targeting 3.7 that would also be fine with me.

> IMHO it'd be cleaner to only have thoe docs for 3.7.1 and commit the same to trunk and 3.7.1

It would be cleaner, but if 3.8.0 goes out first then there isn't a release note at all.
This release note appearing in 3.7.1 but not 3.8.0 is consistent with the fix only being in 3.8.1, timeline-wise. Putting the release note in both places removes this ambiguity.

@edoardocomar Thank you for humoring me.

**Comment by edoardocomar** [comment]
cherry-picked on 3.7

thanks @gharris1727

**Pull request merged**
