### PR TITLE
MINOR: Fix formatting in RelationalSmokeTest

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
@lct45 Could you please take a quick look and approve? It is just some formatting fixes.

**Review by lct45 — APPROVED** [review]
Thanks for cleaning this up @cadonna

**Comment by cadonna** [comment]
@lct45 Thank you for fixing this issue in the first place.

**Comment by cadonna** [comment]
Failures are unrelated and known as flaky.

**Pull request merged**
