### PR TITLE
KAFKA-2849; Pass the correct principal to `RequestChannel.Session`

### PR DESCRIPTION
**Pull request by ijuma**
Also change `Authorizer` to use `Principal` instead of `KafkaPrincipal`
since this is what `KafkaChannel` returns. The other option would be
to change `KafkaChannel` to return `KafkaPrincipal`.

### CODE REVIEW

**Comment by ijuma** [comment]
@Parth-Brahmbhatt What do you think?

**Comment by ijuma** [comment]
./gradlew test passed locally.

**Comment by junrao** [comment]
We actually intentionally created a KafkaPrincipal in RequestChannel.Session, instead of using the Principal returned from KafkaChannel. The reason is that in SimpleAclAuthorizer, all principals specified in acl rules are loaded in as KafkaPrincipal. To do the authorization, we need to compare principals of the same type and KafkaPrincipal and Principal are not directly comparable.

**Comment by ijuma** [comment]
Thanks for the explanation. Closing.

**Pull request closed without merging**
