### PR TITLE
KAFKA-10564: fix flaky test

### PR DESCRIPTION
**Pull request by mikebin**
Minor update to fix flaky state directory test, per feedback from @chia7712 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ableegoldman — APPROVED** [review]
LGTM, will merge once all the builds complete. Thanks for the fix @mikebin (and thanks for the pointer @chia7712 )

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by ableegoldman** [comment]
Just one test failure, the known flaky `EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta`

**Comment by ableegoldman** [comment]
Merged to trunk

**Comment by ableegoldman** [comment]
Cherrypicked to 2.6 & 2.7

**Pull request merged**
