### PR TITLE
MINOR: Fix meaningless message in assertNull validation

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*

I think the author wants to say assertEquals(null, xxx)

*Summary of testing strategy (including rationale)*
QA

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
@guozhangwang , hello, PTAL.

**Comment by chia7712** [comment]
It seems to me the title is a bit confusing. The first argument is "error message" rather than "expected object".

**Comment by dengziming** [comment]
@chia7712 Thank you, I mistakenly treat the second parameter as "error message", I have changed the title.

**Review by chia7712 — APPROVED** [review]
@dengziming Thanks for your patch. LGTM

**Pull request merged**
