### PR TITLE
HOTFIX: fix ConsistencyVectorIntegrationTest failure

### PR DESCRIPTION
**Pull request by lucasbru**
#14570 changed the result for `KeyQuery` from `ValueAndTimestamp<V>` to
`V`, but forgot to update `ConsistencyVectorIntegrationTest` accordingly.
 
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by cadonna — APPROVED** [review]
Thanks @lucasbru !

**Comment by hanyuzheng7** [comment]
Thanks @lucasbru !!!!!

**Review by mjsax — COMMENTED** [review]
Ups. By bad. Seems I missed that this test failed consistently on the other PR (the test in question is one of the know flaky ones...)

LGTM.

**Comment by lucasbru** [comment]
@mjsax could you merge this later today if CI passes?

**Review by mjsax — APPROVED** [review]
Yes. Monitoring already :)

**Comment by cadonna** [comment]
FYI, the following tests also fails consistently on trunk:
```
org.apache.kafka.common.requests.BrokerRegistrationRequestTest.[1] 0
org.apache.kafka.common.requests.BrokerRegistrationRequestTest.[2] 1
```

I found the faulty commit and contacted the author.

**Comment by mjsax** [comment]
`:generator:checkstyleTest` failure -- could not reproduce locally. Will retrigger Jenkins.

**Comment by jolshan** [comment]
fyi -- I filed https://issues.apache.org/jira/browse/KAFKA-15957 but looks like you folks are on it.

**Pull request merged**
