### PR TITLE
MINOR: fix javadoc comment

### PR DESCRIPTION
**Pull request by mihbor**
Here's where it's called:
https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamTransform.java#L64-L67

### CODE REVIEW

**Review by dguy — APPROVED** [review]
LGTM

**Comment by mjsax** [comment]
Retest this please.

**Review by mjsax — APPROVED** [review]
@guozhangwang Call for merging.

**Comment by mjsax** [comment]
@mihbor To retest, just add a comment as I did above. It guess `org.apache.kafka.streams.integration.JoinIntegrationTest > testOuterKStreamKStream STARTED` did time out and failed -- we know that this test is a little flaky: https://issues.apache.org/jira/browse/KAFKA-5005

Not sure, why the error message is not in the build log though...

**Review by guozhangwang — APPROVED** [review]
Merged to trunk.

**Pull request closed without merging**
