### PR TITLE
KAFKA-3068: Remove retry with nodesEverSeen

### PR DESCRIPTION
**Pull request by enothereska**
@ewencp @ijuma if this looks good please merge when you can. Thanks.

### CODE REVIEW

**Comment by ijuma** [comment]
Seems fine to me. As Ewen said in the other PR, it's not great that we have no tests for these changes in behaviour. However, that was already the case and I don't think it should block the PR. Let's see what Ewen says.

**Comment by enothereska** [comment]
@ijuma I left the new leastLoadedNode test, I didn't remove that.

**Comment by ijuma** [comment]
@enothereska https://github.com/apache/kafka/pull/823/files doesn't show it.

**Comment by enothereska** [comment]
@ijuma the PR doesn't show it since I didn't change that code, left it still there since test is still good. I meant that I did put in 1 unit test last time.

**Comment by ijuma** [comment]
@enothereska I see. I probably didn't make my point clear. What I was trying to say is that changes like this should ideally cause a test to break. The fact that no test breaks implies that this part of the behaviour is not actually tested. Makes sense?

**Comment by enothereska** [comment]
@ijuma : makes sense, the test tested leastLoadedNode, but not the bootstrap brokers.

**Comment by ijuma** [comment]
Note that we should double-commit this to the 0.9.0 branch.

**Comment by ijuma** [comment]
@ewencp thoughts on this change? It would be good to get this one in for 0.9.0.1 according to Jun.

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
