### PR TITLE
MINOR: Remove tag from metric to measure process-rate on source nodes

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @guozhangwang

**Comment by guozhangwang** [comment]
test this please

**Review by guozhangwang — APPROVED** [review]
LGTM!

**Comment by guozhangwang** [comment]
Cherry-picked to 2.5

**Pull request merged**
