### PR TITLE
KAFKA-9411: Change Name of Default Client ID and Include Java Version

### PR DESCRIPTION
**Pull request by belugabehr**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ryannedolan — CHANGES_REQUESTED** [review]
I don't know what "user agent" means in this context. I think you are borrowing the term from web browsers, but it is meaningless to Kafka, afaik. Also, dynamic client IDs like this are problematic until/unless Kafka supports regex quotas.

**Comment by belugabehr** [comment]
@ryannedolan Thanks so much for your input.

Yes. I am borrowing the term _user agent_ from HTTP, but it's the same idea as the client ID.  I want to know what software is connected to Kafka at all times.  "consumer-123" does not provide much context or understanding.

**Comment by belugabehr** [comment]
The current default is dynamic in the sense that it provides each client a new sequence number.  How is that being handled currently for quotas?

**Comment by ryannedolan** [comment]
There are no users or user agents in Kafka. The closest thing would be principals and clients. I think this is unlikely to be merged while introducing such terminology.

Quotas do not currently handle dynamic client IDs, afaik, so a quota could not be set for "consumer-123". This is generally fine, since client.id is usually the same across a set of identical clients. This change seems to break that pattern, for better or worse.

**Comment by belugabehr** [comment]
@ryannedolan 
The current default behavior for generating clientID in Kafka is the following:
```
consumer- + CONSUMER_CLIENT_ID_SEQUENCE.getAndIncrement()
```
So the current default is to create a dynamically changing consumer ID.

The change proposed in this PR is three fold:
* Change the default clientID from `consumer` to `Java-kafka-client`
* Include the version of Java in the clientID
* Allow users to set the consumer ID to whatever they would like, but maintain the ability to include the sequence number

So, this does not break any current behaviors.  It just adds additional context to the default value.

**Comment by ijuma** [comment]
Thanks for the PR. This kind of change requires a KIP as there are backwards compatibility implications.

**Pull request closed without merging**
