### PR TITLE
KAFKA-5143: add kafka-broker-api-version.bat for Windows platform

### PR DESCRIPTION
**Pull request by huxihx**
Added kafka-broker-api-versions.bat for Windows platform

### CODE REVIEW

**Comment by huxihx** [comment]
@hachikuji @vahidhashemian A minor PR. Please kindly review. Thanks

**Comment by vahidhashemian** [comment]
LGTM. Thanks for adding the missing script.

**Comment by huxihx** [comment]
@vahidhashemian Thanks. Could you help approve it?

**Comment by vahidhashemian** [comment]
Pinging a couple of committers @ijuma @ewencp. This seems to be a straightforward addition.

**Comment by huxihx** [comment]
@ewencp @ijuma Please review this minor addition. Thanks.

**Comment by huxihx** [comment]
@guozhangwang Please kindly take some time to review this PR. Thanks.

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
@amethystic The JIRA number seems wrong, should it be 5143? Also please capitalize it as `KAFKA-5143: add ... for Windows platform` so the title (which will be part of the commit message) is more self-descriptive. Usually the JIRA title describes the issue while the PR title describes the proposal / solution.

**Comment by huxihx** [comment]
@guozhangwang Sorry for the incorrect jira number and thanks for the comments also. Does it look good now?

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by huxihx** [comment]
@ijuma Thanks, so could we merge it to trunk now?

**Review by guozhangwang — APPROVED** [review]
Merged to trunk.

**Pull request closed without merging**
