### PR TITLE
KAFKA-12409: Leaking gauge in ReplicaManager

### PR DESCRIPTION
**Pull request by dongjinleekr**
One gauge is missing in `ReplicaManager#removeMetrics`.

### CODE REVIEW

**Comment by dongjinleekr** [comment]
@ableegoldman Could you have a look? Maybe it should be cherry-picked into 2.6.2.

**Review by chia7712 — APPROVED** [review]
@dongeforever nice find. LGTM

**Comment by dongjinleekr** [comment]
@chia7712 Thanks. Please have a look to the related issues, [KAFKA-12407](https://issues.apache.org/jira/browse/KAFKA-12407) and [KAFKA-12408](https://issues.apache.org/jira/browse/KAFKA-12408).

**Review by ableegoldman — APPROVED** [review]

**Comment by ableegoldman** [comment]
Merged to trunk. Will also cherrypick to 2.7 and 2.6 since I'm still in the process of cutting the 2.6.2 RC -- you should check with @vvcephei where we are in the 2.8 release cycle and whether we should cherrypick this to 2.8 (it seems to be not a blocker, but also low-risk, is that fair?)

**Comment by ableegoldman** [comment]
Cherrypicked to 2.7 and 2.6

**Pull request merged**
