### PR TITLE
Adding metrics to measure the idempotent producers

### PR DESCRIPTION
**Pull request by mingaliu**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mingaliu** [comment]
We found it is very useful to track the number of idempotent producers that broker is tracking.
In our production environment, we have many idempotent producers to a cluster and sometimes that number increased to very high number which requires some attention to mitigate.
This is especially true for client (< 2.4) where the client retry might generate too many different idempotent producers which can trigger broker GC.

**Comment by mingaliu** [comment]
Can you review the change? @ijuma ?

**Comment by abbccdda** [comment]
Thanks for the PR. We basically need a JIRA and a KIP to proceed on this change, see:
https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals

**Comment by mingaliu** [comment]
Thanks @abbccdda.  The JIRA is https://issues.apache.org/jira/browse/KAFKA-10242.
I wonder why do we need a KIP here?  Given there is no public interface or any protocol change, and the change is small and low risk.

**Comment by mingaliu** [comment]
@abbccdda , can you review this PR? The failing checks seems due to unreliable tests (not related to this PR).

**Pull request closed without merging**
