### PR TITLE
MINOR: Test ReplicaManager Metric Names

### PR DESCRIPTION
**Pull request by rondagostino**
This patch closes a test gap where we do not check ReplicaManager metrics remain as expected.  There was a bug in 2.8 where the metrics moved under a different class name for the KRaft case.  Having such tests would have helped identify the bug.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rondagostino** [comment]
I've implemented the test in 2 separate ways, and we should choose which one to keep.

1. A standard unit test, in `ReplicaManagerTest`
2. A parameterized test that runs for both KRaft and ZooKeeper metadata quorums.

The advantage of (1) is that it is fast -- just a few seconds at most.  The disadvantage is that this test alone would not have caught the 2.8 bug where the metrics moved for the KRaft case -- we would have had to explicitly writte a similar test within `RaftReplicaManager`.

The advantage of (2) is that it would have caught the bug automatically.  The disadvantage is that it takes much longer to run both cases -- between 15 and 20 seconds on my local laptop.

**Comment by cmccabe** [comment]
Can we do the integration test approach, but have it be part of `RaftClusterTest.scala`? It seems weird to have a new test file just for this one test.

We could also check the metrics as part of an existing test in RaftClusterTest.scala. Perhaps as part of the create + close test? That would avoid consuming more time.

Also, can we rename RaftClusterTest.scala => KRaftClusterTest.scala ? That's been bothering me for a while. :)

**Comment by rondagostino** [comment]
> Can we do the integration test approach, but have it be part of RaftClusterTest.scala?

I think we would only be testing for the KRaft case if we did that, and I think we should be testing both KRaft and ZK-based clusters.

**Comment by rondagostino** [comment]
Maybe rename `ReplicaManagerMetricNamesTest` to `ClusterMetricNamesTest` so that it isn't specific to `ReplicaManager`?  We could define it like this:

```
@ClusterTest
def testMetrics(): Unit = {
  checkReplicaManagerMetrics()
  // checkWhateverOtherMetricsWeDecideToAddHereLater()
}

private def checkReplicaManagerMetrics() {
  // same implementation as we have now
}
```

**Comment by cmccabe** [comment]
> Maybe rename ReplicaManagerMetricNamesTest to ClusterMetricNamesTest so that it isn't specific to ReplicaManager?

How about `BrokerMetricNamesTest`?

**Review by cmccabe — APPROVED** [review]
LGTM

**Pull request merged**
