### PR TITLE
KAFKA-1811 Ensuring registered broker host:port is unique

### PR DESCRIPTION
**Pull request by eribeiro**
Adds a ZKLock recipe implementation to guarantee that the host:port pair is unique among the brokers registered on ZooKeeper.

### CODE REVIEW

**Comment by eribeiro** [comment]
Hi @fpj and @gwenshap, whenever you have some free time, it would be awesome if you could review my ZKLock recipe as well as the feature. See if it does make sense at all. Cheers! :)

**Comment by guozhangwang** [comment]
@junrao since you filed the JIRA could you take a look at this PR after @eribeiro rebased it?

**Comment by dajac** [comment]
This has been somewhat addressed by https://github.com/apache/kafka/pull/4897. The JIRA has been closed so I will close this PR. Please, reopen it if it is still relevant.

**Comment by b-goyal** [comment]
Adds a ZKLock recipe implementation to guarantee that the host:port pair is unique among the brokers registered on ZooKeeper.

**Pull request closed without merging**
