### PR TITLE
MINOR: Remove unwanted regexReplace on tests/kafkatest/__init__.py

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
Changes in https://github.com/apache/kafka/pull/6198 adding unwanted chages to `./tests/kafkatest/__init__.py`.
Example changes: https://github.com/apache/kafka/commit/77a89fcf8d7fa01831683327727f11f4bed97319

We dont need to call regexReplace on `./tests/kafkatest/__init__.py`. we are already updating the version string at : https://github.com/apache/kafka/blob/trunk/release.py#L543

**Comment by ijuma** [comment]
Can you please also fix the incorrect changes in https://github.com/apache/kafka/commit/77a89fcf8d7fa01831683327727f11f4bed97319 ?

**Comment by omkreddy** [comment]
> Can you please also fix the incorrect changes in [77a89fc](https://github.com/apache/kafka/commit/77a89fcf8d7fa01831683327727f11f4bed97319) ?

yes, will fix. As the  [77a89fc] commit is in 2.4 branch, will do in separate PR,

**Comment by omkreddy** [comment]
Thanks to @soondenana for noticing the change.

**Comment by cmccabe** [comment]
LGTM

**Comment by omkreddy** [comment]
Verified the PR manually. merging to trunk.

**Pull request closed without merging**
