### PR TITLE
KAFKA-17310 locking the offline dir can destroy the broker exceptionally

### PR DESCRIPTION
**Pull request by brandboat**
related to https://issues.apache.org/jira/browse/KAFKA-17310

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@brandboat could you please run e2e on your local with this patch? 

```
TC_PATHS="tests/kafkatest/tests/core/log_dir_failure_test.py"  /bin/bash tests/docker/run_tests.sh
```

**Comment by brandboat** [comment]
> @brandboat could you please run e2e on your local with this patch?

Sure, thanks

```txt
================================================================================
SESSION REPORT (ALL TESTS)
ducktape version: 0.11.4
session_id:       2024-08-11--001
run time:         34 minutes 21.733 seconds
tests run:        8
passed:           8
flaky:            0
failed:           0
ignored:          0
================================================================================
test_id:    kafkatest.tests.core.log_dir_failure_test.LogDirFailureTest.test_replication_with_disk_failure.bounce_broker=False.broker_type=follower.security_protocol=PLAINTEXT.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   4 minutes 53.794 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.log_dir_failure_test.LogDirFailureTest.test_replication_with_disk_failure.bounce_broker=False.broker_type=leader.security_protocol=PLAINTEXT.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   3 minutes 21.730 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.log_dir_failure_test.LogDirFailureTest.test_replication_with_disk_failure.bounce_broker=True.broker_type=follower.security_protocol=PLAINTEXT.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   4 minutes 23.143 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.log_dir_failure_test.LogDirFailureTest.test_replication_with_disk_failure.bounce_broker=True.broker_type=leader.security_protocol=PLAINTEXT.metadata_quorum=ISOLATED_KRAFT
status:     PASS
run time:   5 minutes 56.140 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.log_dir_failure_test.LogDirFailureTest.test_replication_with_disk_failure.bounce_broker=False.broker_type=follower.security_protocol=PLAINTEXT.metadata_quorum=ZK
status:     PASS
run time:   3 minutes 25.916 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.log_dir_failure_test.LogDirFailureTest.test_replication_with_disk_failure.bounce_broker=False.broker_type=leader.security_protocol=PLAINTEXT.metadata_quorum=ZK
status:     PASS
run time:   4 minutes 26.084 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.log_dir_failure_test.LogDirFailureTest.test_replication_with_disk_failure.bounce_broker=True.broker_type=follower.security_protocol=PLAINTEXT.metadata_quorum=ZK
status:     PASS
run time:   3 minutes 27.712 seconds
--------------------------------------------------------------------------------
test_id:    kafkatest.tests.core.log_dir_failure_test.LogDirFailureTest.test_replication_with_disk_failure.bounce_broker=True.broker_type=leader.security_protocol=PLAINTEXT.metadata_quorum=ZK
status:     PASS
run time:   4 minutes 26.925 seconds
--------------------------------------------------------------------------------
```

**Comment by chia7712** [comment]
the failed streams tests are fixed by #16857, and others pass on my local. will merge it

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
