### PR TITLE
KAFKA-6905: Document that Transformers may be re-used by Streams

### PR DESCRIPTION
**Pull request by glasser**
This is a follow-up to #5022 which added documentation to the Processor
interface. This commit adds similar documentation to Transformer and
ValueTransformer.

Also, s/processor/transformer/ in the close() docs.

### CODE REVIEW

**Comment by glasser** [comment]
The contribution is my original work. I license the work to the project under the project's open source license. This is a doc-only change, so don't be too scared of CI failures.

**Review by mjsax — APPROVED** [review]
LGTM.

Thanks for the PR @glasser !

**Comment by mjsax** [comment]
Call for second review @guozhangwang @bbejeck @vvcephei

**Review by guozhangwang — APPROVED** [review]
@mjsax I'm going to merge it as is now.

**Pull request merged**
