### PR TITLE
KAFKA-8611 / Refactor KStreamRepartitionIntegrationTest

### PR DESCRIPTION
**Pull request by lkokhreidze**
Follow-up PR on https://github.com/apache/kafka/pull/7170 that implements @mjsax 's [suggestions](https://github.com/apache/kafka/pull/7170#discussion_r406535443) regarding integration test parameters.
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Retest this please.

**Review by mjsax — APPROVED** [review]
LGTM. Assuming Jenkins passes.

Thanks for the follow up @lkokhreidze!

**Comment by lkokhreidze** [comment]
Hi @mjsax `:streams:compileTestJava` was failing. Should be fixed now.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Java 11: `org.apache.kafka.streams.integration.EosIntegrationTest.shouldNotViolateEosIfOneTaskFailsWithState[exactly_once_beta]`
Java 8: `https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/1747/testReport/junit/org.apache.kafka.streams.integration/EosIntegrationTest/shouldNotViolateEosIfOneTaskFailsWithState_exactly_once_/`

Retest this please.

**Comment by mjsax** [comment]
Java 8 passed.
Java 11:
```
kafka.server.epoch.EpochDrivenReplicationProtocolAcceptanceTest.shouldSurviveFastLeaderChangeorg.apache.kafka.streams.integration.SuppressionDurabilityIntegrationTest.shouldRecoverBufferAfterShutdown[exactly_once]
```

**Comment by mjsax** [comment]
Thanks for the follow up @lkokhreidze!

I just realized that we did not update the docs for KIP-221. Could you help with that?

**Comment by lkokhreidze** [comment]
Hi @mjsax, will do.

**Pull request merged**
