### PR TITLE
KAFKA-16928: Test all of the request and response methods in RaftUtil 

### PR DESCRIPTION
**Pull request by m1a2st**
https://issues.apache.org/jira/browse/KAFKA-16928

All RaftUtil method need test, and include test all version

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jsancio** [comment]
@m1a2st is this ready for review?

**Comment by m1a2st** [comment]
@jsancio, sorry not yet, I have only written the first test so far, but I want to know if my current testing direction is correct. If it is correct, I will complete the remaining test cases.

**Comment by m1a2st** [comment]
Hi @jsancio, this PR is ready for review, PTAL, Thank you

**Comment by jsancio** [comment]
> Hi @jsancio, this PR is ready for review, PTAL, Thank you

Yes. I'll try to take a look this week.

**Comment by cmccabe** [comment]
Thanks for the PR, @m1a2st ! Can you please fix the checkstyle issues when you get a chance?

**Comment by m1a2st** [comment]
Hello @cmccabe, Thanks for your reminder, I have retriggered ci and fixed the checkstyle.

**Review by cmccabe — APPROVED** [review]
Thanks for the test, @m1a2st ! LGTM.

**Pull request merged**
