### PR TITLE
HOTFIX: updated JavaDoc example for 0.9 tech-prev to 0.10

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Can this be merged to `0.10` to fix current online documentation?

**Comment by harshach** [comment]
+1

**Comment by ijuma** [comment]
cc @guozhangwang

**Comment by guozhangwang** [comment]
LGTM.

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
