### PR TITLE
MINOR: Improve log warning to include the log name

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Another trivial one @rajinisivaram

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6238/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6254/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
Merging to trunk and 0.11.0 branches.

**Pull request closed without merging**
