### PR TITLE
MINOR: Modify checkstyle to allow import classes only used in javadoc

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@ijuma @gwenshap for reviews.

**Comment by ijuma** [comment]
This seems fine to me, but the checkstyle docs say:

> Optionally: it is referenced in Javadoc comments. This check is on by default, but it is considered bad practice to introduce a compile time dependency for documentation purposes only. As an example, the import java.util.Date would be considered referenced with the Javadoc comment {@link Date}. The alternative to avoid introducing a compile time dependency would be to write the Javadoc comment as {@link java.util.Date}.

What do others think?

**Comment by gwenshap** [comment]
I guess I'm not seeing the big deal around the compile-time dependency. 
Especially when it is limited to a single class. The overhead and risk seem minimal.

**Comment by guozhangwang** [comment]
I am with @gwenshap as well on this topic.

BTW if we are the same page could a committer give me a +1?

**Comment by ijuma** [comment]
LGTM

**Comment by guozhangwang** [comment]
Merged to trunk, and cherry-picked to 0.10.0

**Pull request closed without merging**
