### PR TITLE
MINOR: Introduction fixup

### PR DESCRIPTION
**Pull request by joel-hamill**
*Clarify multi-tenant support, geo-replication, and some grammar fixes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by joel-hamill** [comment]
ping @guozhangwang

**Comment by asfgit** [comment]
FAILURE
 8067 tests run, 5 skipped, 2 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 8067 tests run, 5 skipped, 2 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7959 tests run, 5 skipped, 2 failed.
--none--

**Comment by guozhangwang** [comment]
retest this please

**Comment by asfgit** [comment]
SUCCESS 
 8067 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8067 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7959 tests run, 5 skipped, 1 failed.
--none--

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk, cherry picked to 1.0 / 0.11.0

**Pull request closed without merging**
