### PR TITLE
 MINOR: improve error message for incorrect window-serde initialization

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna @abbccdda

**Comment by tlberglund** [comment]
I like that error message! Thanks, @mjsax.

**Comment by guozhangwang** [comment]
LGTM!

**Review by bbejeck — APPROVED** [review]
Thanks for the patch @mjsax LGTM!

**Comment by bbejeck** [comment]
Merged #7067 into trunk

**Pull request merged**
