### PR TITLE
KAFKA-17238: Move VoterSet and ReplicaKey from raft.internals to raft

### PR DESCRIPTION
**Pull request by frankvicky**
[JIRA Link](https://issues.apache.org/jira/browse/KAFKA-17238)
VoterSet should be part of the public API since it is used by the Formatter and it is exposed in the RecordsSnapshotWriter.Builder.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@frankvicky see the comment on the jira, and I will take a look at this PR after 3.9.0

**Comment by frankvicky** [comment]
Cool
I will resolve the conflict after 3.9 release

**Comment by chia7712** [comment]
@frankvicky could you please fix the conflicts?

**Comment by frankvicky** [comment]
Hi @chia7712 
I have fixed the conflicts, PTAL

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by jsancio** [comment]
@frankvicky @chia7712 thanks for the improvements but can we try avoiding this kind of changes until after 3.9.0 RC?

This kind of changes tend to cause unnecessary churn on pending PRs that need to get merged to trunk and 3.9.

@chia7712 are you planning to cherry-pick this to the 3.9 branch? I say we cherry-pick it. It is trivial and may save some conflicts in future cherry-picks to 3.9.

**Comment by chia7712** [comment]
> thanks for the improvements but can we try avoiding this kind of changes until after 3.9.0 RC?
This kind of changes tend to cause unnecessary churn on pending PRs that need to get merged to trunk and 3.9.

I planed to wait it but I saw the email of 3.9.0 says it is ok to refactor ... ok, this is my excuse. I should wait it until after 3.9.0 RC

> are you planning to cherry-pick this to the 3.9 branch? I say we cherry-pick it. It is trivial and may save some conflicts in future cherry-picks to 3.9.

sure. Let me fix my rush

**Comment by chia7712** [comment]
push to 3.9 (https://github.com/apache/kafka/commit/bcf4c73bae59d0425417c24fd526a3a232f6f640)

**Comment by frankvicky** [comment]
Hi @jsancio 
Apologies for the timing of this PR. I should have waited until after the 3.9.0 RC before submitting it. I’ll be more mindful of the timing in the future to avoid any impact on others’ work. Thanks for understanding. 🙇

**Pull request merged**
