### PR TITLE
MINOR: Correct typo in test name `TimetampedSegmentsTest`

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @mjsax @vvcephei @ableegoldman @guozhangwang @bbejeck @abbccdda

**Review by ableegoldman — APPROVED** [review]
Nice catch!

**Review by stanislavkozlovski — APPROVED** [review]
LGTM

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
Merged #7210 into trunk

**Comment by bbejeck** [comment]
cherry-picked to 2.3

**Pull request merged**
