### PR TITLE
KAFKA-15853: Move ZKConfigs related static method out of core and into ZKConfigs

### PR DESCRIPTION
**Pull request by OmniaGM**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@OmniaGM nice idea but we need to fix conflicts first :)

**Comment by mimaison** [comment]
We expect to delete ZooKeeper-related code pretty soon, so do we really need to move it?

**Comment by OmniaGM** [comment]
> We expect to delete ZooKeeper-related code pretty soon, so do we really need to move it?

We need to move KafkaConfig out of core to unblock other Jiras. Unless we are going to delay this a bit till we move ZK related depends in KafkaConfig

**Comment by mimaison** [comment]
The current plan is that 3.8 will be the last 3.X release. Barring any issues found with 3.8, we could start removing ZooKeeper from trunk in the next few weeks.

**Comment by OmniaGM** [comment]
> The current plan is that 3.8 will be the last 3.X release. Barring any issues found with 3.8, we could start removing ZooKeeper from trunk in the next few weeks.

Okay if this is the case we can close this PR, and any depends on ZK for KafkaConfig can wait until we remove ZK as KafkaConfig relays on the dynamic configs which relays on ZK Client so this part can wait a bit.

**Comment by mimaison** [comment]
Hopefully we should know in the next couple of weeks.

**Pull request closed without merging**
