### PR TITLE
KAFKA-13725: KIP-768 OAuth code mixes public and internal classes in same package

### PR DESCRIPTION
**Pull request by kirktrue**
Move classes into a sub-package of `internal` named `secured` that matches the layout more closely of the `unsecured` package.

Replaces the concrete implementations in the former packages with sub-classes of the new package layout and marks them as deprecated. If anyone is already using the newer OAuth code, this should still work.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kirktrue** [comment]
@dajac - can you review or suggest who might?

**Comment by kirktrue** [comment]
@dajac / @cadonna / @jsancio - any suggestions on a reviewer for this?

**Comment by jsancio** [comment]
Let's see if @omkreddy or @rajinisivaram are interested in reviewing this PR.

**Review by omkreddy — APPROVED** [review]
@kirktrue Thanks for the PR. LGTM after tests.

looks like there are checkStyle failures

**Comment by omkreddy** [comment]
@kirktrue Can you fix checkStyle errors

**Pull request merged**
