### PR TITLE
MINOR: Fix transient test failure in DynamicConnectionQuotaTest

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
Observed below transient error in jenkins logs.  looks like the test is trying to create new connection before closing previous produce request connection.   connect() method is quietly returns if server rejects new  create connection.  subsequently  ```intercept[IOException](sendProduceRequest())``` statement is able to produce data, since the server allows the connection.

Added check to wait till produce request connection closes.


```
org.scalatest.junit.JUnitTestFailedError: Expected exception java.io.IOException to be thrown, but no exception was thrown
at org.scalatest.junit.AssertionsForJUnit$class.newAssertionFailedException(AssertionsForJUnit.scala:100)
at org.scalatest.junit.JUnitSuite.newAssertionFailedException(JUnitSuite.scala:71)
at org.scalatest.Assertions$class.intercept(Assertions.scala:822)
at org.scalatest.junit.JUnitSuite.intercept(JUnitSuite.scala:71)
at kafka.network.DynamicConnectionQuotaTest.testDynamicConnectionQuota(DynamicConnectionQuotaTest.scala:81)
```

**Comment by omkreddy** [comment]
retest this please

**Comment by omkreddy** [comment]
@hachikuji Pls take a look.

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch.

**Pull request merged**
