### PR TITLE
enable test, check if continues failing in CI

### PR DESCRIPTION
**Pull request by Kiriakos1998**
JIRA: https://issues.apache.org/jira/browse/KAFKA-6527

After running multiple times the test locally seems to be ok. Opening a PR to see if CI fails. If not perhaps it can be closed. If it fails I will work towards reproducing it first and then resolving it.

### CODE REVIEW

**Comment by divijvaidya** [comment]
Did not fail this time:
```
[Build / JDK 11 and Scala 2.13 / kafka.coordinator.transaction.ProducerIdManagerTest.[1] error=UNKNOWN_SERVER_ERROR](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-13953/1/testReport/junit/kafka.coordinator.transaction/ProducerIdManagerTest/Build___JDK_11_and_Scala_2_13____1__error_UNKNOWN_SERVER_ERROR/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.controller.QuorumControllerTest.testBalancePartitionLeaders()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-13953/1/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/Build___JDK_11_and_Scala_2_13___testBalancePartitionLeaders__/)
[Build / JDK 20 and Scala 2.13 / org.apache.kafka.controller.QuorumControllerTest.testBalancePartitionLeaders()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-13953/1/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/Build___JDK_20_and_Scala_2_13___testBalancePartitionLeaders__/)
[Build / JDK 17 and Scala 2.13 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationExactlyOnceTest.testOffsetTranslationBehindReplicationFlow()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-13953/1/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationExactlyOnceTest/Build___JDK_17_and_Scala_2_13___testOffsetTranslationBehindReplicationFlow__/)
[Build / JDK 17 and Scala 2.13 / kafka.api.TransactionsTest.testBumpTransactionalEpoch(String).quorum=kraft](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-13953/1/testReport/junit/kafka.api/TransactionsTest/Build___JDK_17_and_Scala_2_13___testBumpTransactionalEpoch_String__quorum_kraft/)
[Build / JDK 17 and Scala 2.13 / kafka.api.TransactionsTest.testBumpTransactionalEpoch(String).quorum=kraft](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-13953/1/testReport/junit/kafka.api/TransactionsTest/Build___JDK_17_and_Scala_2_13___testBumpTransactionalEpoch_String__quorum_kraft_2/)
```

Re-running the tests.

**Comment by Kiriakos1998** [comment]
It seems that the specific test didn't fail but now a total of 72 test failed.

**Comment by divijvaidya** [comment]
@Kiriakos1998 I found a potential reason of these flaky failures where large number of tests fail at https://github.com/apache/kafka/pull/13956 . I have also restarted your test run.

**Comment by showuon** [comment]
@Kiriakos1998 , could you rebase with the latest trunk branch, and resolve the conflicts? I'd like to see if it still passes.

**Comment by TaiJuWu** [comment]
Hello @Kiriakos1998 ,
Do you still work on it?
If not, I want to take it over.

**Comment by chia7712** [comment]
close as that is resolved by #15796

**Pull request closed without merging**
