### PR TITLE
KAFKA-13898 : Updated docs for metrics.recording.level

### PR DESCRIPTION
**Pull request by Nancy-ksolves**
Upgrade the metrics.recording.level associated with each metric in document.
"Screenshot of the updated document".
Screenshot from 2024-06-20 15-05-20

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Nancy-ksolves** [comment]
Hi @tombentley, changes has been done. Please review the PR

**Comment by Nancy-ksolves** [comment]
Hi tombentley,
Can you review the PR. we can merge it?

**Comment by chia7712** [comment]
@Nancy-ksolves thanks for this patch. I will take a look later

**Comment by Nancy-ksolves** [comment]
Hi @chia7712,
Can you please review the PR?

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
