### PR TITLE
KAFKA-14588 Tests for ConfigCommand of DynamicBrokerReconfigurationTest rewritten in java

### PR DESCRIPTION
**Pull request by nizhikov**
This is fourth part of https://github.com/apache/kafka/pull/15417 refactoring.
PR intention - split big PR in parts to simplify review.
PR contains tests of `DynamicBrokerReconfigurationTest` that checks `ConfigCommand` rewritten in java.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
Please ping me if this PR gets ready :)

**Comment by nizhikov** [comment]
Yes. I'm working on it right now. Will be ready in a couple of hours.

**Comment by nizhikov** [comment]
@chia7712 PR ready for review.

**Comment by nizhikov** [comment]
CI looks OK for me.

`DynamicBrokerReconfigurationTest#testTrustStoreAlter` fails in trunk, also.

https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka/detail/trunk/2933/tests

**Comment by chia7712** [comment]
I just notice that this test requires `SaslSetup`. the new test infra does not support that for now (https://issues.apache.org/jira/browse/KAFKA-16680). Hence, I'd like to pending this rewrite as we can't do the migration recently...

**Comment by nizhikov** [comment]
Got it.

**Pull request closed without merging**
