### PR TITLE
KAFKA-7613: Enable -Xlint:rawtypes for connect, fixing warnings

### PR DESCRIPTION
**Pull request by tombentley**
Fix all existing javac warnings about use of raw types in Kafka Connect add -Xlint:rawtypes to the connect the javac options in build.gradle. This addresses part of KAFKA-7613, but further work will be needed for the other warnings.

### CODE REVIEW

**Comment by tombentley** [comment]
@ijuma and @ewencp could one of you take a look at this?

**Review by kkonstantine — COMMENTED** [review]
Thanks for the PR @tombentley 
There were a few other "modernization" PRs in the Connect code base. This might have made the application of this change even easier. However, conflicts have been introduced and now we need to rebase here. Not sure if rebasing of re-application of the changes is easier, but the changes seem like something we could merge. 

Let me know if you have time to rebase for 3.0

**Comment by tombentley** [comment]
@kkonstantine I've done the rebase if you'd like to review?

**Review by kkonstantine — COMMENTED** [review]
The changes look ok, but there are some checkstyle violations. 

LGTM, on green build and passing tests.

**Review by kkonstantine — APPROVED** [review]
LGTM
Let's make sure it's cherry-picked on 3.0 now that this release branch is live.

**Comment by tombentley** [comment]
CI failures are unrelated.

**Comment by tombentley** [comment]
Cherry-picked to 3.0

**Pull request merged**
