### PR TITLE
KAFKA-16733: Add share group record support to OffsetsMessageParser

### PR DESCRIPTION
**Pull request by AndrewJSchofield**
KIP-932 added a bunch of new record schemas to the consumer offsets topic which need to be added to the OffsetsMessageParser in kafka-dump-log.sh.

Here's an example of the output:
```
% bin/kafka-dump-log.sh --offsets-decoder --files /tmp/kraft-combined-logs/__consumer_offsets-0/00000000000000000000.log 
Dumping /tmp/kraft-combined-logs/__consumer_offsets-0/00000000000000000000.log
Log starting offset: 0
baseOffset: 0 lastOffset: 5 count: 6 baseSequence: 0 lastSequence: 5 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false deleteHorizonMs: OptionalLong.empty position: 0 CreateTime: 1727354207209 size: 480 magic: 2 compresscodec: none crc: 2390172074 isvalid: true
| offset: 0 CreateTime: 1727354207209 keySize: 50 valueSize: 42 sequence: 0 headerKeys: [] key: {"type":"10","data":{"groupId":"console-share-consumer","memberId":"Tsnir8MZRt27WL47QhcKVA"}} payload: {"version":"0","data":{"rackId":null,"clientId":"console-share-consumer","clientHost":"/127.0.0.1","subscribedTopicNames":["T1"]}}
| offset: 1 CreateTime: 1727354207209 keySize: 26 valueSize: 29 sequence: 1 headerKeys: [] key: {"type":"9","data":{"groupId":"console-share-consumer"}} payload: {"version":"0","data":{"topics":[{"topicId":"xfugYJTERGetNxY2KH_JFA","topicName":"T1","numPartitions":1,"partitionMetadata":[]}]}}
| offset: 2 CreateTime: 1727354207209 keySize: 26 valueSize: 7 sequence: 2 headerKeys: [] key: {"type":"11","data":{"groupId":"console-share-consumer"}} payload: {"version":"0","data":{"epoch":1}}
| offset: 3 CreateTime: 1727354207209 keySize: 50 valueSize: 26 sequence: 3 headerKeys: [] key: {"type":"13","data":{"groupId":"console-share-consumer","memberId":"Tsnir8MZRt27WL47QhcKVA"}} payload: {"version":"0","data":{"topicPartitions":[{"topicId":"xfugYJTERGetNxY2KH_JFA","partitions":[0]}]}}
| offset: 4 CreateTime: 1727354207209 keySize: 26 valueSize: 7 sequence: 4 headerKeys: [] key: {"type":"12","data":{"groupId":"console-share-consumer"}} payload: {"version":"0","data":{"assignmentEpoch":1}}
| offset: 5 CreateTime: 1727354207209 keySize: 50 valueSize: 35 sequence: 5 headerKeys: [] key: {"type":"14","data":{"groupId":"console-share-consumer","memberId":"Tsnir8MZRt27WL47QhcKVA"}} payload: {"version":"0","data":{"memberEpoch":1,"previousMemberEpoch":0,"state":0,"assignedPartitions":[{"topicId":"xfugYJTERGetNxY2KH_JFA","partitions":[0]}]}}
```
These are the records to show that a new share group has been created as a new member was assigned a single partition.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by AndrewJSchofield** [comment]
3 unrelated test failures (features command).

**Review by mumrah — APPROVED** [review]
Thanks @AndrewJSchofield, LGTM!

Can you include some sample output in the PR description?

**Review by chia7712 — APPROVED** [review]

**Comment by chia7712** [comment]
@AndrewJSchofield Could you please rebase code to run CI again?

**Comment by AndrewJSchofield** [comment]
Closing and re-opening PR to rerun the build.

**Comment by mumrah** [comment]
@AndrewJSchofield just merging trunk into the PR should be enough to trigger CI. If there's no commits to merge in, you can either push an empty commit or manually re-run the job. Note that re-running a job does not pull in the latest trunk changes.

**Pull request merged**
