### PR TITLE
KAFA-4378: resolve eta-expansion of zero-argument method warnings

### PR DESCRIPTION
**Pull request by leachbj**

### CODE REVIEW

**Comment by ijuma** [comment]
Is this change really worth it? It seems to make the code less readable and the benefit is unclear.

**Comment by leachbj** [comment]
The motivation is from scala 2.12;

> Eta-expansion (conversion of a method to a function value) of zero-args methods has been deprecated, as this can lead to surprising behavior (#5327).

See http://www.scala-lang.org/news/2.12.0

So it may be less readable but correct trumps readable ;)  (2.13 won't perform the expansion at all which is why it has been deprecated)

**Comment by ijuma** [comment]
Neither the quote or the PR make it clear what the surprising behaviour is though. And the code before this PR is correct, so the change is not really about correctness in this context. Finally, because no-one is checking for 2.12 warnings, there is nothing preventing such usages from reoccurring. In fact, it's likely that they will. So, I'm not too keen on making this change right now. We'll have to do it before we support 2.13, but there's no rush really.

**Comment by leachbj** [comment]
The code after the PR is also correct and simply removes the automatic eta-expansion that is happening with 2.10 and 2.11.

The surprising bit is that if you have `def foo() = ???` then `foo` could mean `foo()` or `foo _` depending on the context, in 2.13 you will need to do `foo _`.  We could use the `() => foo()` construct instead of `foo _` but thats even more noisy.

https://github.com/apache/kafka/pull/2088 adds a 2.12 build, the number of warnings under 2.12 is quite large.  This change resolves the eta-expansion warnings.

**Comment by ijuma** [comment]
LGTM. Merged this to trunk after resolving conflicts and fixing the warning in a few more places (in code added/changed since this PR was first introduced). Thanks for the PR!

**Pull request closed without merging**
