### PR TITLE
KAFKA-17749: Fix Throttler metrics name (#17430)

### PR DESCRIPTION
**Pull request by mimaison**
Backport of https://github.com/apache/kafka/commit/dcd3bbe5929d9ee558a16de04c99c504c8c1c3ac

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
cc @jlprat

**Review by jlprat — APPROVED** [review]
LGTM Thanks @mimaison

**Comment by mimaison** [comment]
Oops, this actually broke the build :(
Let me open a PR to fix it

**Comment by mimaison** [comment]
https://github.com/apache/kafka/pull/17459

**Pull request merged**
