### PR TITLE
 KAFKA-6926: Simplified some logic to eliminate some suppressions of NPath complexity checks

### PR DESCRIPTION
**Pull request by rhauch**
Modified several classes' `equals` methods and simplified a complex method to reduce the NPath complexity so they could be removed from the checkstyle suppressions that were required with the [recent move to Java 8 and upgrade of Checkstyle](https://github.com/apache/kafka/pull/5046).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rhauch** [comment]
@rayokota, @wicknicks: would you mind reviewing these minor set of changes.

**Review by rayokota — APPROVED** [review]
LGTM

**Review by wicknicks — APPROVED** [review]
LGTM. Thanks, Randall!

**Comment by rhauch** [comment]
@hachikuji, would you mind reviewing and if approved merge to `trunk`? Thanks!

**Review by ijuma — APPROVED** [review]
Nice clean-up, LGTM.

**Pull request merged**
