### PR TITLE
KAFKA-15662: Add support for clientInstanceIds in Kafka Stream

### PR DESCRIPTION
**Pull request by mjsax**
- Part of KIP-714
- Add new configs and public API for Kafka Streams
- Implement support to get admin client instance id

### CODE REVIEW

**Review by wcarlson5 — APPROVED** [review]
lGTM 

all these changes seem like the bones of a good PR 😁 

(except the checkstyle error)

**Review by apoorvmittal10 — APPROVED** [review]
Thanks for the PR @mjsax.

**Comment by wcarlson5** [comment]
Looks like there is still a build issue :(

**Comment by mjsax** [comment]
Build issues:
- Second run: `JDK 8 and Scala 2.12`
- Third run: `JDK 17 and Scala 2.13`

Failing KS tests pass locally (so they seems to be flaky only). Others are flaky/not related to this PR. Merging.

**Pull request merged**
