### PR TITLE
Kafka 6042: Use state write lock for delayed txn operations 

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by rajinisivaram** [comment]
@hachikuji  @guozhangwang I think the locking change in transaction state manager in the last commit was not correct. Using stateLock.readLock is sufficient to avoid deadlocks, but it doesn't prevent multiple threads completing an operation at the same time since they can all acquire the read lock. I have changed it to writeLock, which should prevent deadlocks and allow one thread to update delayed operation. Can you take a look?

**Comment by hachikuji** [comment]
@rajinisivaram Hmm.. I'm not sure I understand the issue. Is there a problem with multiple operations completing at the same time? The callbacks already provide the locking they need, so I had actually wondered if we could use no operation lock at all.

**Comment by hachikuji** [comment]
On second thought, it seems like multiple completions are already protected by the `completed` field inside `DelayedOperation`.

**Comment by rajinisivaram** [comment]
@hachikuji Yes, you are right, `completed` in `DelayedOperation` is sufficient. We probably could have avoided using the readLock too, but will leave as is. Thank you! Closing the PR.

**Comment by ijuma** [comment]
@rajinisivaram, if we don't need the `readLock`, I suggest making that change in trunk only.

**Pull request closed without merging**
