### PR TITLE
KAFKA-15387: Deprecate Connect's redundant task configurations endpoint

### PR DESCRIPTION
**Pull request by yashmayya**
- https://issues.apache.org/jira/browse/KAFKA-15387
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-970%3A+Deprecate+and+remove+Connect%27s+redundant+task+configurations+endpoint
- This patch deprecates the `GET /connectors/{connector}/tasks-config` endpoint (by updating the documentation, adding a deprecated annotation to the OpenAPI spec, and adding a deprecation warning log).

Screenshot 2023-09-08 at 11 28 11 PM

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by vamossagar12 — APPROVED** [review]
LGTM. Thanks for the fix Yash! I would have preferred a test  which would have invoked the older end point and validates that the warning log line gets printed though. Other than that, seems fine.

**Comment by yashmayya** [comment]
Thanks Sagar!

> a test which would have invoked the older end point and validates that the warning log line gets printed

Feels like a bit of overkill, but I guess it doesn't really hurt to add such a test so I've added one. There's currently no integration test class for Connect's REST API - most of the functionality is tested indirectly through other ITs and some of the more specialized ones have their own test classes (`ConnectorRestartApiIntegrationTest`, `ConnectorTopicsIntegrationTest`, `OffsetsApiIntegrationTest` etc.). It didn't seem worth it to introduce a new integration test class just for this small test so I've added it to `ConnectWorkerIntegrationTest` which is the most generic one.

**Review by mimaison — APPROVED** [review]
Thanks for the PR. LGTM

**Comment by yashmayya** [comment]
Test failures are unrelated, merging to `trunk`

**Pull request merged**
