### PR TITLE
MINOR: Fixed README examples on running specific tests.

### PR DESCRIPTION
**Pull request by GabrielNicolasAvellaneda**

### CODE REVIEW

**Comment by GabrielNicolasAvellaneda** [comment]
Hey Guys, do I need to create a Jira Issue for the README fix?

**Comment by ijuma** [comment]
Thanks for the fix. You don't need a JIRA, but it would be good if you could edit the PR title to be:

`MINOR: Fixed README examples on running specific tests`

The change itself LGTM.

**Comment by ijuma** [comment]
Also, we don't use `Signed-off-by` in the Kafka project.

**Comment by GabrielNicolasAvellaneda** [comment]
Thanks @ijuma :+1:

**Comment by ewencp** [comment]
LGTM.

**Comment by GabrielNicolasAvellaneda** [comment]
@ewencp Do I need to do anything else for this PR to be merged?

**Comment by ewencp** [comment]
@GabrielNicolasAvellaneda I assigned you on the JIRA, marked it as "Patch Available" and assigned Guozhang as a reviewer so it'll be noticed. Unless someone raises an issue, you shouldn't need to do anything except remind us if it gets lost in the shuffle.

Thanks for the patch!

**Comment by GabrielNicolasAvellaneda** [comment]
@ewencp Thanks for your response. 
Okay, Perfect, more changes are coming soon... :)
Happy to help. :+1:

**Comment by GabrielNicolasAvellaneda** [comment]
LGTM :+1:

**Comment by ijuma** [comment]
Simple README fix, could you please merge it @gwenshap?

**Comment by guozhangwang** [comment]
Thanks, LGTM.

**Pull request closed without merging**
