### PR TITLE
KAFKA-9601: Stop logging raw connector config values

### PR DESCRIPTION
**Pull request by C0urante**
[Jira](https://issues.apache.org/jira/browse/KAFKA-9601)

whoopsie daisy

### CODE REVIEW

**Comment by C0urante** [comment]
@rhauch got a quick second?

**Comment by rhauch** [comment]
@C0urante I may be missing something, but AbstractConfig doesn't have a toString() method, which means that the log message you're changing may have, at worst, output the `Object.toString()` that would not list the key and values.

**Comment by C0urante** [comment]
@rhauch the object that gets logged isn't the `AbstractConfig` itself, but the original string/string map that it was instantiated with. You can see this in the line before the one I've changed: https://github.com/apache/kafka/blob/90640266393b530107db8256d38ec5aeba4805e1/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerConnector.java#L77

**Review by rhauch — APPROVED** [review]
LGTM. Thanks, @C0urante.

**Comment by rhauch** [comment]
Neither test failure was related to Connect.

**Pull request merged**
