### PR TITLE
Fix bash scripts to use `/usr/bin/env`.

### PR DESCRIPTION
**Pull request by aloiscochard**
Which makes them compatible with NixOS.

### CODE REVIEW

**Comment by jblespiau** [comment]
Should not one use #!/bin/sh instead ?

**Comment by aloiscochard** [comment]
@Gueust how do you know?

I'm not familiar enought with bash specificity to know which scripts could be evaluated purely with `sh`, so I took the safe path of reusing the same interpreter as used before, which is `bash`.

**Comment by jblespiau** [comment]
Some distribution may not have bash (I think), while sh is always present (symlink to the system shell) Details here : http://stackoverflow.com/questions/5725296/difference-between-sh-and-bash

Anyway, I don't think that is important, since all distributions have bash today but it seemed to me that it was strange to use env for portability, and still use bash afterwards. Still, I don't know a distribution without bash :p

I don't think my remark was pertinent. It was more a question than an assertion (I was wondering if sh was not more portable)

**Comment by aloiscochard** [comment]
@Gueust I see, that's a fair point but I did not took time to test those scripts on `sh` instead of `bash`.

I think that could be addressed in a different PR if needed.

**Comment by shikhar** [comment]
I think this change makes sense to do. 

@granthenke raised a security concern in https://github.com/apache/kafka/pull/557#issuecomment-185442232, IMO the tradeoff is worth it. It seems better to respect `$PATH` than hardcode the path to bash (we'd be hardcoding `/usr/bin/env` but that seems pretty standard for portable scripts?).

@aloiscochard seems there have been a more scripts added to `bin/` since you created the PR

**Comment by guozhangwang** [comment]
@ijuma  Could you take a look at this PR and see if it is valid? There is another PR https://github.com/apache/kafka/pull/557 for similar purposes.

**Comment by ijuma** [comment]
Seems to make sense. @aloiscochard, would you mind updating the scripts that have been added since this PR so that we can merge this? Sorry for the delay.

**Comment by guozhangwang** [comment]
Closing for cleanup.

**Pull request closed without merging**
