### PR TITLE
MINOR: Update site docs for ASF compliance

### PR DESCRIPTION
**Pull request by bbejeck**
This PR is a mirror of https://github.com/apache/kafka-site/pull/433 which used placeholder images for the Kafka Streams that users need to click in order to load the `iframe` with the corresponding video.

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @mimaison

**Comment by mimaison** [comment]
The path of the images is `/{{version}}/images/`, so do we need to add them to this repo too?

**Comment by bbejeck** [comment]
> The path of the images is `/{{version}}/images/`, so do we need to add them to this repo too?

Yes I overlooked that - will do

**Comment by bbejeck** [comment]
@mimaison added images

**Comment by mimaison** [comment]
Thanks @bbejeck !
Should we fix the issues I reported in https://github.com/apache/kafka-site/pull/433#issuecomment-1205049698 before merging the images back to Kafka?

**Comment by bbejeck** [comment]
> Should we fix the issues I reported in [apache/kafka-site#433 (comment)](https://github.com/apache/kafka-site/pull/433#issuecomment-1205049698) before merging the images back to Kafka?

I've taken a stab at addressing those comments - this may be the best I can do

**Comment by mimaison** [comment]
@bbejeck Can we grab the images from https://github.com/apache/kafka-site/pull/435 ?

**Comment by bbejeck** [comment]
@mimaison updated images added

**Review by mimaison — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
Merged #12494 into trunk

**Comment by bbejeck** [comment]
cherry-picked to 3.3

**Pull request merged**
