### PR TITLE
MINOR: add upgrade note for KIP-336

### PR DESCRIPTION
**Pull request by viktorsomogyi**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by viktorsomogyi** [comment]
@ijuma added the notes that you mentioned in #5494. Please let me know if you'd compose it somehow differently.

**Comment by viktorsomogyi** [comment]
retest this please

**Review by akatona84 — APPROVED** [review]

**Comment by ijuma** [comment]
cc @lindong28

**Review by lindong28 — APPROVED** [review]
Thanks for the improvement. LGTM. Merged to trunk and 2.1 branch.

**Pull request closed without merging**
