### PR TITLE
MINOR: remove unused code from InternalTopicManager

### PR DESCRIPTION
**Pull request by dguy**
Remove isValidCleanupPolicy and related fields as they are never used.

### CODE REVIEW

**Comment by dguy** [comment]
@enothereska @guozhangwang @ijuma

**Comment by enothereska** [comment]
LGTM, code is indeed unused.

**Comment by guozhangwang** [comment]
PR LGTM. BTW does `
org.apache.kafka.streams.integration.QueryableStateIntegrationTest > queryOnRebalance[1]` ever blocked on your local runs? Jenkins seems to be blocked on this test once.

**Comment by guozhangwang** [comment]
Merged to trunk and 0.10.1.

**Pull request closed without merging**
