### PR TITLE
MINOR: Fix closing code tag in producer config docs

### PR DESCRIPTION
**Pull request by mimaison**
See https://github.com/apache/kafka-site/pull/457

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by dajac — APPROVED** [review]
LGTM

**Review by showuon — APPROVED** [review]
Nice catch!

**Comment by mimaison** [comment]
Thanks, I backported it to 3.3 as well

**Comment by rishiraj88** [comment]
Thanks, @mimaison .

**Pull request merged**
