### PR TITLE
MINOR: Bump 2.6 to use 2.6.3

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
@mjsax @vvcephei Can you upload `kafka-stream-2.6.3-test.jar` to the kafka-packages S3 bucket? Thanks

**Comment by dajac** [comment]
@mimaison I have uploaded `kafka-streams-2.6.3-test.jar`, `kafka_2.12-2.6.3.tgz`, and `kafka_2.13-2.6.3.tgz` to s3://kafka-packages.

**Review by dajac — APPROVED** [review]
LGTM

**Comment by mimaison** [comment]
Awesome, thanks @dajac !
Uploading the Streams artifacts to that Confluent bucket is not great. Also it's always a bit annoying to chase people to get it done. I did not know you had permissions, I'll remember that for next time!

**Pull request merged**
