### PR TITLE
KAFKA-12536: Add Instant-based methods to ReadOnlySessionStore

### PR DESCRIPTION
**Pull request by jeqo**
KIP-666 implementation.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by vvcephei — APPROVED** [review]
LGTM! Thanks, @jeqo !

**Comment by dotjdk** [comment]
The parameter name changes for `fetchSession` in this commit introduces some potential confusion. Looks like a copy/paste mistake from the `findSessions` methods. `fetchSession` parameters should be called `startTime` and `endTime` as they where in previous releases.

**Comment by jeqo** [comment]
Thanks @dotjdk ! 
Do you mean https://github.com/apache/kafka/blob/8f8f914efc2dfb2a6638553038dcb17393d7de96/streams/src/main/java/org/apache/kafka/streams/state/SessionStore.java#L92 specifically? If so, I agree. Check if this PR fixes the issue: to open it for review: https://github.com/apache/kafka/pull/11999.

**Comment by dotjdk** [comment]
Yes. I have seen the PR, and that fixes the misleading parameter names 👍

**Pull request merged**
