### PR TITLE
MINOR: Streams doc example should not close store

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
\cc @bbejeck @vvcephei

**Review by guozhangwang — APPROVED** [review]

**Comment by mjsax** [comment]
I just double check the history of the docs for back porting. It's fixed in 0.11 docs already... So we only need to cherry-pick to 1.0 and 1.1 branches. Also, the 0.11 version has a much nicer comment so I updated this PR accordingly.

**Review by bbejeck — APPROVED** [review]
thanks @mjsax LGTM

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please

**Comment by bbejeck** [comment]
retest this please

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `1.0` and `1.1` branches.

**Pull request merged**
