### PR TITLE
MINOR Fix check-style failures in streams/examples module.

### PR DESCRIPTION
**Pull request by satishd**
MINOR Fix check-style failures in streams/examples module by removing unused imports. This is caused by earlier commit 4e1b6d3f28bdb50b25c58d57fffe1285fe985b92

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by satishd** [comment]
@mjsax @showuon Please review and merge to unblock the build failures.

**Review by omkreddy — APPROVED** [review]
LGTM

**Comment by satishd** [comment]
Thanks @omkreddy reviewing the PR. Few failed tests do not seem to be related to these changes.

**Comment by ijuma** [comment]
@satishd please include the reviewers line in the commit message when merging. Thanks for the fix!

**Comment by mjsax** [comment]
Thanks for the quick fix! -- And sorry for breaking `trunk` -- I did some catchup work on the backlog and it was a somewhat older PR that I merged...

**Comment by mjsax** [comment]
Cherry-picked this commit to `3.4` branch.

**Pull request merged**
