### PR TITLE
KAFKA-5498: ConfigDef derived from another ConfigDef did not correctly compute parentless configs

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@ijuma @hachikuji @gwenshap Turns out the issue was actually in ConfigDef. I also added some more test coverage as I noticed a bunch of minor things that had no coverage but could go wrong.

This should go into both trunk and 0.11.0

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5617/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by gwenshap** [comment]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5631/
Test PASSed (JDK 7 and Scala 2.11).

**Pull request closed without merging**
