### PR TITLE
MINOR: Add 3.8.x and 3.9.x to Streams compatibility matrix

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @aliehsaeedii

**Review by lucasbru — APPROVED** [review]
lgtm, thanks

**Comment by chia7712** [comment]
Is this duplicate to #17906?

**Comment by cadonna** [comment]
@chia7712 You got me again!
At least the compatibility part of it overlaps.

I would merge my PR and rebase the other PR to ensure we have at least the 3.8.x and 3.9.x (that we missed before) in the compatibility matrix as soon as possible.

**Pull request merged**
