### PR TITLE
MINOR: added -1 value description as "high watermark" in the protocol delete records request 

### PR DESCRIPTION
**Pull request by ppatierno**

### CODE REVIEW

**Comment by ppatierno** [comment]
Retest this please

**Comment by ppatierno** [comment]
Retest this please

**Comment by ppatierno** [comment]
Retest this please

**Comment by ppatierno** [comment]
Tests failures are not related to the PR.

**Comment by ppatierno** [comment]
@ijuma this PR is really trivial. Can you take a look at it please ? Thanks !

**Review by ijuma — APPROVED** [review]
LGTM, thanks. Merged to trunk and 1.0 branches.

**Pull request closed without merging**
