### PR TITLE
Revert "KAFKA-15661: KIP-951: Server side changes (#14444)"

### PR DESCRIPTION
**Pull request by dajac**
This reverts commit f38b0d886c01bf4e83a08ca7c8a4da01c2d0c686.

Trying to find the root cause of `org.apache.kafka.tiered.storage.integration.ReassignReplicaShrinkTest` failing in CI.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
JDK 21 and Scala 2.13 build failed due to https://github.com/apache/kafka/pull/14739.

**Comment by dajac** [comment]
org.apache.kafka.tiered.storage.integration.ReassignReplicaShrinkTest does not fail without this commit. We should revert it for the time being.

**Comment by dajac** [comment]
The failed build is due to https://github.com/apache/kafka/pull/14739.

**Comment by jolshan** [comment]
> org.apache.kafka.tiered.storage.integration.ReassignReplicaShrinkTest does not fail without this commit. We should revert it for the time being.

Here are existing builds where it was already failing -- I see that the error is different though. This is why I probably thought it was a non-issue.
https://ci-builds.apache.org/job/Kafka/job/kafka/job/trunk/2371/#showFailuresLink
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14695/6/

**Review by jolshan — APPROVED** [review]

**Pull request merged**
