### PR TITLE
KAFKA-18270: SaslHandshake v0 incorrectly tagged as deprecated

### PR DESCRIPTION
**Pull request by ijuma**
It's now consistent with KIP-896.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mumrah** [comment]
@ijuma was the deprecation in #15032 incorrect, or did we change the plan for this API since last year? I see the KIP says "V0 per the baseline" for this API.

Also, can you reference the specific KIP number in the PR body?

**Comment by ijuma** [comment]
@mumrah The deprecation was incorrect, I think the KIP was changed before it went for voting, but the PR somehow didn't include that change. The KIP states:

> SaslHandshake: none due to clients (kafka-python) - V0 per the baseline
librdkafka: [V1](https://github.com/confluentinc/librdkafka/blob/v1.8.2/src/rdkafka_request.c#L2287)
KafkaJS: [V1](https://github.com/tulios/kafkajs/blob/v1.15.0/src/protocol/requests/saslHandshake/v1/request.js#L3)
Sarama: [V1](https://github.com/IBM/sarama/blob/v1.29.1/broker.go#L1184)
kafka-python: [V0](https://github.com/dpkp/kafka-python/blob/2.0.2/kafka/conn.py#L525)

The `none` means we are not deprecating anything. `V0 per the baseline` means that according to the Kafka 2.1 baseline, we should have deprecated V0, but we didn't because of `kafka-python`. The KIP explains that we made sure the client releases at a particular date would not be affected by any of the deprecations/removals. Does that make sense?

I updated the PR body to include the KIP number.

**Comment by mumrah** [comment]
Yes, that clarifies things. Thanks!

**Review by mumrah — APPROVED** [review]
LGTM

**Pull request merged**
