### PR TITLE
MINOR: remove ignore annotations in Streams EOS integration test

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@apurvam @hachikuji @mjsax for reviews.

**Review by apurvam — APPROVED** [review]
LGTM! We should let the jenkins build complete before merging though.

**Review by hachikuji — APPROVED** [review]
LGTM if the build passes!

**Comment by ijuma** [comment]
Also, it would be good to run it in a loop locally, just to be sure.

**Comment by guozhangwang** [comment]
We previously ran it 100X times locally but cannot reproduce the issue. As discussed offline it seems only reproducible with Jenkins-like low-end environments.

**Comment by guozhangwang** [comment]
Merged to trunk and 0.11.0.

**Pull request closed without merging**
