### PR TITLE
MINOR: doc changes for KIP-372

### PR DESCRIPTION
**Pull request by bbejeck**
Documentation changes for KIP-372

- Adding `Grouped`
- Deprecating `Serialized`
- Adding `withNamed` to `Joined`
- Naming repartition topics

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
@guozhangwang, @mjsax, @vvcephei 

\cc @JimGalasyn

**Review by mjsax — COMMENTED** [review]
Did you check if we have code example using `Serialized` in the docs? If yes, we should update them to use `Grouped`.

**Comment by bbejeck** [comment]
>Did you check if we have code example using Serialized in the docs? If yes, we should update them to use Grouped.

@mjsax ack, updated refs

**Review by mjsax — APPROVED** [review]

**Review by vvcephei — APPROVED** [review]

**Comment by bbejeck** [comment]
retest this please

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.1`

**Pull request merged**
