### PR TITLE
KAFKA-8634: Update ZooKeeper to 3.5.5

### PR DESCRIPTION
**Pull request by ijuma**
ZooKeeper 3.5.5 is the first stable release in the 3.5.x series. The key new feature
in is TLS support, but there are a few more noteworthy features:

* Dynamic reconfiguration
* Local sessions
* New node types: Container, TTL
* Ability to remove watchers
* Multi-threaded commit processor
* Upgraded to Netty 4.1

See the release notes for more detail:
https://zookeeper.apache.org/doc/r3.5.5/releasenotes.html

In addition to the version bump, we:

* Add `commons-cli` dependency as it's required by `ZooKeeperMain`, but specified as
`provided` in their pom.
* Remove unnecessary `ZooKeeperMainWrapper`, the bug it worked around was fixed
upstream a long time ago.
* Ignore non zero exit in one system test invocation of `ZooKeeperMain`.
`ZooKeeperMainWrapper` always returned `0` and `ZooKeeperService.query` relies
on that for correct behavior.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Fixed an issue that was causing system tests to fail and launched another build, which is looking good so far:
https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2772/console

**Comment by ijuma** [comment]
There were 10 system tests failures. Fixed an additional issue and started another run:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2779/

**Comment by ijuma** [comment]
2 variations of ConnectDistributedTest failed in the latest run. Will investigate if it's related.

**Comment by ijuma** [comment]
retest this please

**Comment by stanislavkozlovski** [comment]
The `org.apache.kafka.connect.integration.ExampleConnectIntegrationTest.testSourceConnector` test failed on both JDK 11 builds with the error of
```
org.apache.kafka.connect.errors.DataException: Insufficient records committed by connector simple-conn in 15000 millis. Records expected=2000, actual=1112
	at org.apache.kafka.connect.integration.ConnectorHandle.awaitCommits(ConnectorHandle.java:188)
	at org.apache.kafka.connect.integration.ExampleConnectIntegrationTest.testSourceConnector(ExampleConnectIntegrationTest.java:181)
```
This isn't the initial connect test that failed, right?

For completeness, the JDK 8 build failed the `kafka.admin.LeaderElectionCommandTest.testTopicPartition` test with
```
kafka.common.AdminCommandFailedException: Timeout waiting for election results
	at kafka.admin.LeaderElectionCommand$.electLeaders(LeaderElectionCommand.scala:134)
	at kafka.admin.LeaderElectionCommand$.run(LeaderElectionCommand.scala:89)
	at kafka.admin.LeaderElectionCommand$.main(LeaderElectionCommand.scala:42)
	at kafka.admin.LeaderElectionCommandTest$$anonfun$testTopicPartition$1.apply(LeaderElectionCommandTest.scala:121)
	at kafka.admin.LeaderElectionCommandTest$$anonfun$testTopicPartition$1.apply(LeaderElectionCommandTest.scala:104)
	at kafka.utils.TestUtils$.resource(TestUtils.scala:1534)
	at kafka.admin.LeaderElectionCommandTest.testTopicPartition(LeaderElectionCommandTest.scala:104)
```
which seems more like a flake

**Comment by ijuma** [comment]
@stanislavkozlovski the JUnit failures are all flakes. The system test failures are not yet clear.

**Comment by ijuma** [comment]
The Connect system test that failed also looks like a flake, `trunk` also fails sometimes:

http://confluent-kafka-system-test-results.s3-us-west-2.amazonaws.com/2019-07-05--001.1562343232--confluentinc--master--8dc8e6d/report.html

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
I reran the connect system tests a few times and the failures are flaky (i.e. they pass sometimes). So, I think this PR is ready for review.

**Review by hachikuji — APPROVED** [review]
LGTM

**Pull request merged**
