### PR TITLE
MINOR: fix failing Streams system tests

### PR DESCRIPTION
**Pull request by mjsax**
In #5850 the output that prints the current Kafka version was reformatted (space before `:` was removed):

Old format:
```
Kafka version : 2.2.0-SNAPSHOT
```

New format:
```
Kafka version: 2.2.0-SNAPSHOT
```

This breaks some Streams system tests that grep the logs for this line.

### CODE REVIEW

**Comment by mjsax** [comment]
Triggered system test: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2086/

Call for review @guozhangwang @bbejeck @vvcephei

**Review by guozhangwang — APPROVED** [review]

**Review by bbejeck — APPROVED** [review]

**Comment by mjsax** [comment]
`StreamsBrokerBounceTest` system test failed -- seems to be unrelated to this fix though. All `StreamsUpgradeTest` passed. Are you ok if I merge this and we tackle the failing test separately?

Also `EosIntegrationTest.shouldNotViolateEosIfOneTaskFailsWithState` failed:
```
java.lang.AssertionError: 
Expected: <[KeyValue(0, 0), KeyValue(0, 1), KeyValue(0, 3), KeyValue(0, 6), KeyValue(0, 10), KeyValue(0, 15), KeyValue(0, 21), KeyValue(0, 28), KeyValue(0, 36), KeyValue(0, 45)]>
     but: was <[KeyValue(0, 0), KeyValue(0, 1), KeyValue(0, 3), KeyValue(0, 6), KeyValue(0, 10), KeyValue(0, 15), KeyValue(0, 21), KeyValue(0, 28), KeyValue(0, 36), KeyValue(0, 45), KeyValue(0, 55), KeyValue(0, 66), KeyValue(0, 78), KeyValue(0, 91), KeyValue(0, 105)]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.apache.kafka.streams.integration.EosIntegrationTest.checkResultPerKey(EosIntegrationTest.java:218)
	at org.apache.kafka.streams.integration.EosIntegrationTest.shouldNotViolateEosIfOneTaskFailsWithState(EosIntegrationTest.java:438)
```

Have seen this once in a while lately -- we should investigate.

Other Jenkins test failures seems to be unrelated.

Retest this please.

**Comment by bbejeck** [comment]
>StreamsBrokerBounceTest system test failed -- seems to be unrelated to this fix though. All StreamsUpgradeTest passed. Are you ok if I merge this and we tackle the failing test separately?

Fine with me

**Review by vvcephei — APPROVED** [review]
Thanks!

**Comment by bbejeck** [comment]
@mjsax as side note this PR will help me as I'm working on another system test for broker upgrades and experienced the same failures

**Comment by mjsax** [comment]
@bbejeck Merge to trunk. You can rebase your PR to pick up the fix.

**Comment by bbejeck** [comment]
Thanks @mjsax!

**Pull request merged**
