### PR TITLE
Corrected the Changes in ZkUtils.scala - KAFKA-2167

### PR DESCRIPTION
**Pull request by nssalian**
Corrected Spelling errors.

### CODE REVIEW

**Comment by gwenshap** [comment]
Looks like you committed a lot of files that shouldn't have been committed at all. Everything under core/data.

Can you clean it up a bit?

**Comment by gwenshap** [comment]
Also, was the change to gradle file intentional?

**Comment by nssalian** [comment]
Closing this pull request and created https://github.com/apache/kafka/pull/64 for KAFKA-2167.

**Comment by b-goyal** [comment]
Corrected Spelling errors.

**Pull request closed without merging**
