### PR TITLE
MINOR: Remove duplicate method

### PR DESCRIPTION
**Pull request by lianetm**
Remove duplicate method failing build

### CODE REVIEW

**Comment by lianetm** [comment]
Hey @chia7712 , could you take a look please? Thanks!

**Comment by lianetm** [comment]
(client module builds ok on trunk locally with this fix)

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by lianetm** [comment]
I'll merge (to not delay the fix) given that the compile phases completed successfully and KafkaConsumerTest passes successfully locally.

**Pull request merged**
