### PR TITLE
Minor: Rename methods to add metrics to sensor in `StreamsMetricsImpl`

### PR DESCRIPTION
**Pull request by cadonna**
Renames method names in `StreamsMetricsImpl` to make them consistent.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
ping @guozhangwang @mjsax @ableegoldman @abbccdda @vvcephei @bbejeck

**Review by ableegoldman — APPROVED** [review]
LGTM, just curious though what is the motivation here? IS it just to clarify that these methods are adding to a sensor, or will we be adding some other methods later that necessitate this?

**Review by guozhangwang — APPROVED** [review]
This is from a previous PR's conversation to make the API naming consistency.

**Comment by guozhangwang** [comment]
retest this please

**Comment by cadonna** [comment]
In Java 11 and Scala 2.13 the following tests failed
```
org.apache.kafka.connect.integration.ExampleConnectIntegrationTest.testSourceConnector
kafka.api.AdminClientIntegrationTest.testElectUncleanLeadersForManyPartitions
```

In Java 8 the following tests failed
```
kafka.api.AdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevels
kafka.api.AdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevelsCanResetLoggerToCurrentRoot
kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevels
kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevelsCanResetLoggerToCurrentRoot
```

Retest this, please

**Pull request merged**
