### PR TITLE
KAFKA-8861 Fix flaky RegexSourceIntegrationTest.testMultipleConsumers…

### PR DESCRIPTION
**Pull request by chia7712**
similar to https://issues.apache.org/jira/browse/KAFKA-8011 and https://issues.apache.org/jira/browse/KAFKA-8026

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
Thanks for the fix! LGTM.

Call for second review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna @abbccdda

**Comment by mjsax** [comment]
Java 11 / 2.12 failed with env error. Java 11 / 2.13 and Java 8 passed.

Retest this please.

**Comment by mjsax** [comment]
Older branches are affected, too. The first fix (for same issue, different methods) when into 2.0 (but not 1.1) -- hence, we should only back-port to `2.0`.

**Review by bbejeck — APPROVED** [review]
Thanks for the patch @chia7712! LGTM.

**Comment by bbejeck** [comment]
retest this please

**Comment by mjsax** [comment]
Why did we need to retest, @bbejeck ?

**Comment by bbejeck** [comment]
Merged #7281 into trunk.

**Comment by bbejeck** [comment]
cherry-picked to 2.3, 2.2, 2.1 and 2.0

**Pull request merged**
