### PR TITLE
KAFKA-7840: Documentation for cleanup.policy is out of date

### PR DESCRIPTION
**Pull request by dongjinleekr**
A trivial documentation fix.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by vahidhashemian — APPROVED** [review]
LGTM. Thanks for the update!

**Comment by mjsax** [comment]
Might be worth to cherry-pick to older branches? Basically back to 0.10.1 when the feature was introduced?

Should we get a PR against `kafka-site`, too, to update the docs immediately? Otherwise this will only be reflected when we roll a new release.

**Comment by dongjinleekr** [comment]
@mjsax Sure. I shall do it ASAP.

**Comment by ijuma** [comment]
I don't think it's worth backporting all the way to 0.10.1. That release is more than 2 years old.

**Pull request merged**
