### PR TITLE
MINOR: Remove redundant conditional judgments in Selector.clear()

### PR DESCRIPTION
**Pull request by RivenSun2**
Condition 'sendFailed' is always 'false' when reached

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by RivenSun2** [comment]
Hi @guozhangwang  @showuon 
could you help to review the PR?
Thanks.

**Review by guozhangwang — COMMENTED** [review]
I think this is intentional? Basically if `!sendFailed` we want both conditions be triggered.

Note this is not a `if else-if` condition.

**Comment by RivenSun2** [comment]
Hi @guozhangwang yes i understand what you mean.

```
        // Remove closed channels after all their buffered receives have been processed or if a send was requested
        for (Iterator<Map.Entry<String, KafkaChannel>> it = closingChannels.entrySet().iterator(); it.hasNext(); ) {
            KafkaChannel channel = it.next().getValue();
            boolean sendFailed = failedSends.remove(channel.id());
            boolean hasPending = false;
            if (!sendFailed)
                hasPending = maybeReadFromClosingChannel(channel);
            if (!hasPending || sendFailed) {
            if (!hasPending) {
                doClose(channel, true);
                it.remove();
            }
        }
```
            
You can browse this whole block of code, and you will find that `if (!hasPending || sendFailed)` is equivalent to `if (!hasPending)`. Condition 'sendFailed' is always 'false' when reached.
 WDYT?
 Thanks.

**Comment by RivenSun2** [comment]
@guozhangwang 
There may be a problem with the logic of this code, missing a case: 
when `sendFailed` is true, `doClose` should also be executed.

**Comment by guozhangwang** [comment]
> There may be a problem with the logic of this code, missing a case:
> when `sendFailed` is true, `doClose` should also be executed.

I see what you mean now. I think it's safe to remove.

**Comment by RivenSun2** [comment]
Thanks, i just deleted my last comment, because it's wrong.

**Comment by RivenSun2** [comment]
@guozhangwang 
Sorry, I originally wanted to resubmit an edit, it might be easier to read and understand.
`if (sendFailed || !hasPending)`

WDYT？
Thanks.

**Comment by guozhangwang** [comment]
I think just removing it is fine.

**Comment by RivenSun2** [comment]
Ok ,thanks a lot.

**Pull request merged**
