### PR TITLE
KAFKA-2958: Remove duplicate API key mapping functionality

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by gwenshap** [comment]
Thanks for the cleanup. This looks good, and I can commit after tests pass.

Mind opening a JIRA for the "Getting rid of the mapping to deserialize functions"? Maybe as a sub-task in that monster JIRA for converting everything to new request / response objects?

**Comment by granthenke** [comment]
Created [KAFKA-2959](https://issues.apache.org/jira/browse/KAFKA-2959) to track the "legacy mapping to deserializer" removal.

**Comment by guozhangwang** [comment]
@gwenshap Is KAFKA-2959 this related to KAFKA-1927 or just a dependent of it?

**Comment by ijuma** [comment]
@guozhangwang KAFKA-2959 is a subtask of KAFKA-1927.

**Pull request closed without merging**
