### PR TITLE
MINOR: Replace deepIterator/shallowIterator with deepEntries/shallowEntries

### PR DESCRIPTION
**Pull request by ijuma**
The latter return `Iterable` instead of `Iterator` so that enhanced foreach can be used
in Java.

### CODE REVIEW

**Comment by ijuma** [comment]
@hachikuji, what do you think?

**Comment by hachikuji** [comment]
@ijuma Yeah, this makes sense to me.

**Comment by ijuma** [comment]
The JDK 8 and Scala 2.11 build failure was `QueryableStateIntegrationTest.queryOnRebalance[0]`, which is unrelated to this PR (the test is a bit flaky).

**Comment by ijuma** [comment]
@hachikuji, added one minor commit and fixed merged conflicts. OK to merge?

**Comment by ijuma** [comment]
retest this please

**Comment by hachikuji** [comment]
LGTM

**Pull request closed without merging**
