### PR TITLE
KAFKA-5911 Avoid creation of extra Map for futures in KafkaAdminClient

### PR DESCRIPTION
**Pull request by tedyu**
This reduces creation of garbage while keeping thread safety untouched.

### CODE REVIEW

**Comment by tedyu** [comment]
@ijuma 
Can you take a look ?

**Comment by tombentley** [comment]
@tedyu those typecasts are not really necessary. The `*Result` classes could declare their member variable as

    private final Map<String, ? extends KafkaFuture<Void>> futures;

likewise their constructor parameter and their `values()` method. Unfortunately doing it this way is not source compatible with existing callers of `values()` (who also have to declare a wildcard). Anyway, [here's a branch](https://github.com/tombentley/kafka/tree/KAFKA-5911-without-casting) showing what I mean, though I admit I just blindly went through KafkaAdminUtils removing the new HashMap in every instantiation of a `*Result` without checking.

**Comment by tedyu** [comment]
bq. doing it this way is not source compatible with existing callers of values()

You mean your suggested way, right ?
If so, I prefer my approach.

**Comment by tedyu** [comment]
@ijuma 
Gentle ping.

**Comment by ijuma** [comment]
It's unfortunate that we have to do all this casting. Also, suboptimal to force users to add the wildcard for an implementation detail. cc @cmccabe who may have some thoughts as well.

**Comment by tombentley** [comment]
Yeah, it seems plenty of people offer advice to avoid (bounded) wildcards in return types, but there are also [arguments in favour](https://stackoverflow.com/questions/8966502/java-bounded-wildcard-in-return-type). In our case, since we don't expect the user of the `Map` to go adding to it, it's not completely unreasonable, *so long as* you don't mind foisting the upper bounded type on users of the API.

**Comment by tedyu** [comment]
@ijuma 
What's your opinion ?

thanks

**Comment by tedyu** [comment]
@ijuma
Gentle ping

**Pull request closed without merging**
