### PR TITLE
MINOR: refactor result string

### PR DESCRIPTION
**Pull request by pch8388**
Removes duplicate result strings and avoids mistakes when changing the string format

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by divijvaidya — APPROVED** [review]

**Comment by pch8388** [comment]
@ijuma would you please review this?

**Review by showuon — APPROVED** [review]
LGTM!

**Comment by showuon** [comment]
Failed tests are unrelated:
```
    Build / PowerPC / Run PowerPC Build / kafka.network.ConnectionQuotasTest.testListenerConnectionRateLimitWhenActualRateAboveLimit()
    Build / JDK 17 and Scala 2.13 / org.apache.kafka.connect.integration.ExactlyOnceSourceIntegrationTest.testFencedLeaderRecovery
    Build / JDK 17 and Scala 2.13 / org.apache.kafka.connect.integration.ExactlyOnceSourceIntegrationTest.testFencedLeaderRecovery
```

**Comment by pch8388** [comment]
Thanks for the review and merge!

**Comment by ijuma** [comment]
Thanks for the PR. Can you please include a unit test for this fix? Also, `String.format` performs worse than string concatenation. Seems ok here, but worth keeping in mind for areas where performance is important.

**Comment by ijuma** [comment]
@showuon Whenever reviewing PRs for fixes, we should generally include at least a unit test. There needs to be a strong reason to merge a fix without any test changes/additions.

**Comment by pch8388** [comment]
Thanks for the review.
How do I add changes to a merged PR?
Need to open a new PR?

**Comment by showuon** [comment]
@ijuma , thanks for the reminder. But I've checked and confirmed there is already a unit test covered this change: `ConfigDefTest#testNiceMemoryUnits`. I should have mentioned it in the review comments. I'll do that next time to make it clear. Thanks.

**Comment by ijuma** [comment]
The PR description says "Fix...". Are we saying it's not a fix, it's simply a refactoring? We should make it clear if so.

**Comment by pch8388** [comment]
That's my mistake.
I should say it's a simple refactoring.
I'll edit the PR title.

**Comment by showuon** [comment]
Good point. Updated.

**Comment by pch8388** [comment]
Thanks for the good point

**Pull request merged**
