### PR TITLE
MINOR: Doc updates for Kafka 3.0.1

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
@mimaison Thanks. Do we need to update the doc in the 3.0 branch as well? Otherwise, we will miss the update that you did if we would ever release 3.0.2.

**Comment by mimaison** [comment]
@dajac It was relatively simple to port docs changes from kafka/3.0 since 3.0.0. However because we often merge changes only in kafka-site, it's harder to go the other way around.

Considering we're unlikely to release 3.0.2, I'm not sure it's worth the effort to do it in 3.0.

**Comment by mimaison** [comment]
ping @dajac

**Review by dajac — APPROVED** [review]
LGTM. I think that we should always consider the kafka repo as the source of truth for the documentation. Otherwise, as you said, we lose changes made directly to the site repo.

**Comment by mimaison** [comment]
I wonder if we should prevent editing files in `kafka-site` altogether and ask users to always do them in `kafka`.

**Comment by dajac** [comment]
I usually ask them to open two PRs. The issue is that the doc in kafka might be way ahead of the current release (e.g. new features).

**Pull request merged**
