### PR TITLE
KAFKA-3773: Remove from inflightResponses on client disconnect to prevent memory leak

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by onurkaraman** [comment]
We definitely fixed this before. To be clear, is this is a hotfix just for the 0.9 branch?

**Comment by hachikuji** [comment]
@onurkaraman Yes, correct. I think Ismael fixed it for 0.10, but we should at least have it in the 0.9 branch in case we do another release.

**Comment by ijuma** [comment]
LGTM

**Comment by ijuma** [comment]
@hachikuji, can you please close this PR since it's been merged? (auto-close only works when merging to trunk).

**Pull request closed without merging**
