### PR TITLE
KAFKA-5230: Fix conversion of Class configs to handle nested classes properly

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
/cc @gwenshap @kkonstantine @norwood 

This should go on both trunk/0.11 and 0.10.2

**Comment by ijuma** [comment]
Thanks for the PR, @ewencp. This only affects what is displayed in the RST and HTML output for Class defaults, right? It seems reasonable for the output to match what people can use themselves, so just asking to make sure I understood what is being fixed.

**Comment by ewencp** [comment]
@ijuma It also affects Connect's REST API since it depends on this conversion to strings as well.

**Comment by kkonstantine** [comment]
Another example is that it affects recommended config values during validation. This can happen even in standalone mode during config validation. Transformations present a case where nested classes are used, and therefore what's the actual recommended string matters.

**Comment by kkonstantine** [comment]
Looks LGTM to me.

**Review by ijuma — APPROVED** [review]
Thanks for the explanation. LGTM.

**Comment by ijuma** [comment]
Merged to trunk and 0.10.2.

**Pull request closed without merging**
