### PR TITLE
MINOR: Fix error logged if not enough alive brokers for transactions state topic

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji, cc @mjsax

**Comment by ijuma** [comment]
retest this please

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
Re-opened https://issues.apache.org/jira/browse/KAFKA-4583 for the jenkins failure.

**Review by guozhangwang — APPROVED** [review]
Merged to trunk.

**Pull request closed without merging**
