### PR TITLE
KAFKA-15853: Move OffsetConfig to group-coordinator module

### PR DESCRIPTION
**Pull request by OmniaGM**
blocker for #15158 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by nizhikov — APPROVED** [review]

**Comment by nizhikov** [comment]
@mimaison 
@ijuma 

This PR are ready for merge for me. Please, take a look.

**Comment by mimaison** [comment]
@dajac Can you confirm if `org.apache.kafka.coordinator.group` is the best place to put the `OffsetConfig` class?

**Comment by dajac** [comment]
That seems fine. We also have `GroupCoordinatorConfig`. I hope that we can eventually consolidate them but we can look into this afterwards. We already have a Jira for reworking the group coordinator configs: https://issues.apache.org/jira/browse/KAFKA-15089.

**Review by mimaison — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
