### PR TITLE
MINOR: Fix typos in Kafka website page

### PR DESCRIPTION
**Pull request by smalldirector**
Fix two minor typos in Kafka official website page.

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by smalldirector** [comment]
@ijuma Thanks for your review.

**Comment by guozhangwang** [comment]
Thanks @smalldirector , LGTM and merged to trunk. It will be reflected in the next release in kafka-site.

**Comment by smalldirector** [comment]
@guozhangwang Thanks.

**Pull request closed without merging**
