### PR TITLE
MINOR: Fix usage instruction of skipSigning build parameter

### PR DESCRIPTION
**Pull request by lucasbru**
skipSigning parameter must be set to a boolean value to work.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lucasbru** [comment]
Test failures are unrelated

**Comment by bbejeck** [comment]
Failures unrelated - changes made in the README file

**Review by bbejeck — APPROVED** [review]
Thanks for the fix @lucasbru, LGTM

**Comment by bbejeck** [comment]
merged #12731 into trunk

**Pull request merged**
