### PR TITLE
KAFKA-9016:Warn when log dir stopped serving replicas

### PR DESCRIPTION
**Pull request by uttpal**
*KAFKA-9016:Warn when log dir stopped serving replicas instead of info*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by viktorsomogyi — APPROVED** [review]
LGTM, let me ask committers to review it as well. 
@lindong28, @ijuma would you please review this?

**Comment by lindong28** [comment]
Thanks @uttpal. It makes sense to use warn level for logs triggered due to error. 

If we make changes here, it might make sense to also change log levels similarly for ReplicaManager.handleLogDirFailure(...), LogManager.handleLogDirFailure(...), and LogCleanerManager.handleLogDirFailure(...).

**Comment by uttpal** [comment]
@lindong28 Sure, i will make the mentioned changes

**Comment by uttpal** [comment]
@lindong28 @viktorsomogyi @ijuma Made changes to log warn message from all handleLogDirFailure function, please verify

**Review by lindong28 — APPROVED** [review]
Thanks for the update! LGTM.

**Pull request closed without merging**
