### PR TITLE
KAFKA-3634: Upgrade tests for SASL authentication

### PR DESCRIPTION
**Pull request by rajinisivaram**
Add a test for changing SASL mechanism using rolling upgrade and a test for rolling upgrade from 0.9.0.x to 0.10.0 with SASL/GSSAPI.

### CODE REVIEW

**Comment by rajinisivaram** [comment]
@ijuma @ewencp Thank you for reviewing the other SASL ducktape test PR. Do you mind taking a look at this one too? Thanks.

**Comment by ijuma** [comment]
@benstopford, since you wrote the security upgrade tests, can you please take a look?

**Comment by ijuma** [comment]
Started a system tests run here: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/434/

**Comment by ijuma** [comment]
@granders, maybe you can review this since Ben is away today.

**Comment by benstopford** [comment]
Sorry for the late review. The tests follow a familiar pattern to the previous ones and check out fine. Tests are passing obviously too. 

@ijuma @rajinisivaram - is there a plan to extend to mechanisms other than PLAIN (just out of interest)?

LGTM

**Comment by granders** [comment]
LGTM

**Comment by ijuma** [comment]
LGTM too.

**Comment by ijuma** [comment]
@benstopford Do you mean extending the test to include PLAIN to GSSAPI as well? Or more mechanisms than the two we currently have?

**Comment by ijuma** [comment]
Merged to trunk and the 0.10.0 branch.

**Pull request closed without merging**
