### PR TITLE
COMDEV-340 Fix project category

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by pzygielo** [comment]
@ijuma may I ask for a review, please?

**Comment by ijuma** [comment]
Thanks for the PR. Is it intentional that we don't use https anymore?

**Comment by pzygielo** [comment]
[Initially](https://github.com/apache/kafka/compare/5834c6affa36a729c251655129ab6466317ebf62..d772888dc429f213926cb1943b462b465bc4baca) I used https, but changed after comments on [COMDEV-340](https://issues.apache.org/jira/browse/COMDEV-340). My understanding is, that it isn't direct link, but rather enumerated value.

**Comment by pzygielo** [comment]
@ijuma - FYI - https://projects.apache.org/projects.html?category still lists this project in separate category :disappointed:

**Comment by pzygielo** [comment]
Now it has [separate issue (KAFKA-10775)](https://issues.apache.org/jira/browse/KAFKA-10775). What process shall be followed to have it corrected?

**Pull request closed without merging**
