### PR TITLE
MINOR: Fix Streams EOS system tests

### PR DESCRIPTION
**Pull request by mjsax**
- avoid loosing log/stdout/stderr files on restart
 - reenable tests

### CODE REVIEW

**Comment by mjsax** [comment]
\cc @bbejeck

**Comment by mjsax** [comment]
I figured out, that there is a difference between "restart" and "stop" followed by "start"

On "start" we cleanup the node by deleting log-files, and STDOUT and STDERR. This messed with the offsets of the obtained monitors and thus, the test run into timeout as the monitor does not find the expected entries in STDOUT file.

**Comment by mjsax** [comment]
I run couple of consecutive tests for `simple_rebalance` already, and now triggered system test for all EOS test: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1267/

(will do couple of more runs to make sure it works)

**Comment by bbejeck** [comment]
Thanks, @mjsax, LGTM

**Comment by mjsax** [comment]
System test failed. Updated PR. Re-triggered tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1269/

**Comment by mjsax** [comment]
1296 passed. retriggered as https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1271/

**Comment by mjsax** [comment]
1271 passed. retriggered as https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1274/

**Review by guozhangwang — APPROVED** [review]
LGTM! Just a nit comment: could we just add this flag in the `StreamsTestBaseService`, and update its `clean_node` function so we do not need to have duplicated code?

Please feel free to merge after system test validations.

**Comment by mjsax** [comment]
Retriggered https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1275/

**Comment by mjsax** [comment]
1275 passed. Retriggered as https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1277/

**Comment by mjsax** [comment]
1277 passed. Retriggered as https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1279/

**Comment by mjsax** [comment]
1279 passed. Retriggered as https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1283/

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `1.1` and `1.0` branches.

**Pull request merged**
