### PR TITLE
MINOR: Fix recently added method in SinkTaskContext to be backward compatible

### PR DESCRIPTION
**Pull request by rhauch**
Although Connect should always implement this interface and all its methods, other projects might implement this for tests or other environments, so we should make it backward compatible.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rhauch** [comment]
@kkonstantine, @ijuma: please review this fix

**Comment by ijuma** [comment]
@rhauch what is the behaviour if subclasses don't implement this method? Will they work?

**Review by kkonstantine — APPROVED** [review]
LGTM

**Comment by rhauch** [comment]
@ijuma this new method allows connectors to get the connector's configuration. Connect always implements this method (so the default won't matter), but this default will allow dependent projects to not _require_ implementation to at least compile. If they end up calling the method, however, they'd have to override in their implementations.

**Comment by rhauch** [comment]
@ewencp, @rayokota: What do you think about this change? We ran into it in a downstream project that implemented the interface in a mock. We've resolved that, but my concern is that others might have done the same thing. Is it okay to not be backward compatible in this way? If so, we should reject this PR without merging.

**Comment by rayokota** [comment]
I'm fine with this change.  But we will probably want to do the same thing in SourceTaskContext.

**Comment by rhauch** [comment]
Actually, the more I think about it, the more I think we should not make this change. Downstream projects that implement these interfaces should probably have the compilation errors when they upgrade. The interfaces do represent a framework-provided resource.

This would be completely different if the interfaces were to be implemented by a connector, which are supposed to be able to run in different AK versions.

**Comment by ewencp** [comment]
Yeah, this is really nothing new -- we've added to those interfaces in the past and there's not really any intent for people to implement it themselves. We can try to be nicer in some cases by providing default implementations now that we are on JDK8, but I actually think it's a bad idea to provide default implementations that don't actually work.

I'm curious where this got caught downstream? I would not have expected anyone to implement this interface. I would expect mocking it in any connectors that need to test interaction with it.

**Comment by kkonstantine** [comment]
I agree with not providing a default that is not useful after all. 

One example use I'm aware of, is this interface's extension happening in a test mocking class, that doesn't use a mocking framework because it's shared across packages and it's not placed in the `<test>` scope (so mockito and others can't be brought in as a dependency). It was properly fixed by extending the new method.

**Comment by rhauch** [comment]
Ok, I'd like to close this without merging. Any objections?

UPDATE: it sounds @ewencp and @kkonstantine both agree, so I'm going to close this now. If anyone disagrees, we can always reopen.

**Pull request closed without merging**
