### PR TITLE
KAFKA-13542: add rebalance reason in Kafka Streams

### PR DESCRIPTION
**Pull request by lihaosky**
Add rebalance reason in Kafka Streams. Ran benchmark and it looks good.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by dajac — APPROVED** [review]
LGTM, thanks. Assuming the test pass.

**Comment by dajac** [comment]
@cadonna It might be worth getting this one in 3.2. It is low risk. This is a good one to improve the debugability of Streams. What do you think?

**Comment by cadonna** [comment]
@dajac @lihaosky This failed test might be related to the PR since it involves probing rebalances.

```
Build / JDK 17 and Scala 2.13 / org.apache.kafka.streams.integration.HighAvailabilityTaskAssignorIntegrationTest.shouldScaleOutWithWarmupTasksAndPersistentStores
```

**Comment by dajac** [comment]
@lihaosky Could you verify if that failed test is a concern?

**Comment by lihaosky** [comment]
I ran it 3 times locally with JDK 17 and scala 2.13 and it didn't fail. Maybe flaky? Not sure if related to https://issues.apache.org/jira/browse/KAFKA-10184?jql=project%20%3D%20KAFKA%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22shouldScaleOutWithWarmupTasksAndPersistentStores%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC

**Comment by lihaosky** [comment]
@dajac , can you re-trigger the test run?

**Comment by cadonna** [comment]
I retriggered the build

**Comment by cadonna** [comment]
@lihaosky you might be right about the flakiness.

**Comment by dajac** [comment]
The last run had two failed tests:
```
Build / JDK 17 and Scala 2.13 / testDynamicListenerConnectionCreationRateQuota() – kafka.network.DynamicConnectionQuotaTest
42s
Build / JDK 11 and Scala 2.13 / shouldAllowRemovingAndAddingNamedTopologyToRunningApplicationWithMultipleNodesAndResetsOffsets – org.apache.kafka.streams.integration.NamedTopologyIntegrationTest
```
I don't think that they are related to this PR.

**Comment by dajac** [comment]
@cadonna Are you OK with cherry-picking it to 3.2?

**Comment by cadonna** [comment]
@dajac Yes, please go ahead!

**Pull request merged**
