### PR TITLE
Kafka-2852:Updating the Authorizer CLI to use a consistent way to specify a list of values for a config options.

### PR DESCRIPTION
**Pull request by Parth-Brahmbhatt**
…ecify a list of values for a config options.

### CODE REVIEW

**Comment by Parth-Brahmbhatt** [comment]
@junrao The more I interact with the CLI I also feel it might be better to collapse allow-host, allow-principal, deny-host and deny-principal into allow/deny, principal, host. 

I originally thought because Deny is suppose to be a negation operation most users would want to specify deny and allow in the same CLI command, which is why I proposed the original config options. However I feel deny is a special use case which will be very rarely used. 

Overall I feel: 
"kafka-acl.sh --add --allow --principal alice --host host1" reads better than
"kafka-acl.sh --add --allow-principal alice --allow-host host1" with the downside of not being able to provide both allow and deny options in the single command.

If you agree I can make changes to both code, documentation and KIP before EOD. Let me know what do you think.

**Comment by junrao** [comment]
@Parth-Brahmbhatt : I don't feel it makes a big difference with a separate --allow. To minimize the risk, perhaps we can just leave this as it is. Could you update docs/security.html with your change?

**Comment by Parth-Brahmbhatt** [comment]
@junrao Updated security.html.

**Comment by junrao** [comment]
In security.html, in the examples, we still have a few places that use --allow-hosts, --operations, --deny-hosts. Could you fix those too?

**Comment by Parth-Brahmbhatt** [comment]
Sorry for missing those, fixed.

**Comment by junrao** [comment]
Thanks for the patch. LGTM.

**Pull request closed without merging**
