### PR TITLE
MINOR: Adjust checkstyle suppression paths to work on Windows

### PR DESCRIPTION
**Pull request by ijuma**
Use the file name whenever possible and replace / with [/\\]
when it's not.

Also remove unnecessary suppresions.

### CODE REVIEW

**Comment by ijuma** [comment]
@vahidhashemian, can you please verify that this fixes the Windows build issues?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5685/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5699/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5686/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5700/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by vahidhashemian** [comment]
Thanks @ijuma. This fixes the issue I reported. But, as I mentioned in my mailing list response, I now see other errors for some of core tests.

**Comment by ijuma** [comment]
@dguy, can you please review this?

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Merging to 0.11.0 and trunk.

**Pull request closed without merging**
