### PR TITLE
KAFKA-6905: Document that Processors may be re-used by Streams

### PR DESCRIPTION
**Pull request by glasser**

### CODE REVIEW

**Comment by glasser** [comment]
The contribution is my original work. I license the work to the project under the project's open source license.  (This is my first contribution to Kafka. I happen to be an incredibly inactive ASF member if that helps in any way... hmm, apparently an emeritus member.)

**Comment by glasser** [comment]
Not sure if it should be "re-used" or "reused".

**Comment by glasser** [comment]
This is a doc only change and the CI failures appear to be normal tests failing, not something that tries to validate that docs look good. I don't believe I have the ability to re-run CI myself.

**Review by guozhangwang — APPROVED** [review]

**Comment by mjsax** [comment]
Thanks for the PR @glasser 

Should we update JavaDocs for `Transformer` and `ValueTransformer`, too?

**Comment by glasser** [comment]
Presumably? I've never used those.

**Comment by mjsax** [comment]
Would you mind doing a second PR using the same JIRA number ?

**Comment by glasser** [comment]
If you can promise me that this is accurate? I haven't actually written my own Transformer or ValueTransformer.

**Comment by mjsax** [comment]
Yes, it is accurate. :)

**Pull request merged**
