### PR TITLE
MINOR: fix typo in TestInputTopic.getTimestampAndAdvance

### PR DESCRIPTION
**Pull request by ableegoldman**
Renamed TestInputTopic's`getTimestampAndAdvanced` to `getTimestampAndAdvance`

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM. cc @vvcephei @mjsax for another look.

**Comment by bbejeck** [comment]
@ableegoldman thanks for the PR.  Overall the changes lgtm, but the test failures seem related.

EDIT -  strange though,  all unit tests pass more me locally on this branch.

**Comment by vvcephei** [comment]
Hey @ableegoldman , I think we can fix the typo, but those "duplicate" `getX` methods were explicitly proposed (and discussed & approved) in the KIP, so I don't think we should remove them now.

**Comment by vvcephei** [comment]
Specifically, the `getX` methods were added to support the `hasProperty` Hamcrest matcher, which is why these tests are now failing: https://github.com/apache/kafka/blob/trunk/streams/test-utils/src/test/java/org/apache/kafka/streams/TestTopicsTest.java#L273-L276

**Review by vvcephei — APPROVED** [review]
Thanks!

**Review by bbejeck — APPROVED** [review]

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.4`.

**Pull request merged**
