### PR TITLE
MINOR: Optimize the matches method of AccessControlEntryFilter

### PR DESCRIPTION
**Pull request by RivenSun2**
Optimize the matches method of AccessControlEntryFilter

### CODE REVIEW

**Comment by RivenSun2** [comment]
Hi @dajac and @showuon , please help to review the PR .
Thanks.

**Review by showuon — COMMENTED** [review]
@RivenSun2 , thanks for the patch. But I'm not sure if this change is better. I know the result is the same, but before the change, we can directly get data principal, after your change, we need to jump to `AccessControlEntryFilter#principal()` method and then get the data principal. 
Is there anything I missed? 

Thanks.

**Comment by RivenSun2** [comment]
@showuon 
Yeah i agree with you
I just want to keep the code style in the AccessControlEntryFilter#matches method consistent~
Like the following lines of code:
the style of host() & operation() & permissionType().
Thanks.

**Comment by showuon** [comment]
@RivenSun2 , do you think we can close this PR? Thanks.

**Comment by RivenSun2** [comment]
@showuon 
I think this PR makes sense to make each line code of AccessControlEntryFilter#matches consistent in style

`!host().equals(other.host())`
`!operation().equals(other.operation())`
`permissionType().equals(other.permissionType())`

**Comment by showuon** [comment]
Yes, I know what you mean, but I don't think this is better and have one more function called. If you still think this change makes sense, you can ask for other reviewer's comments. Thank you.

**Comment by RivenSun2** [comment]
@showuon Thank you for your reply

In fact, both the `AccessControlEntryFilter` and `AccessControlEntry` classes access each attribute field of the `AccessControlEntryData data` through a method call.

What do you think? @guozhangwang @dajac 
Thanks.

**Review by showuon — APPROVED** [review]
@RivenSun2 , have a 2nd look, I think your change makes sense. At the beginning of the `match` method, there's already a call with `principal()` method, and also rest of the getters. 
```java
if ((principal() != null)
```
So, I agree with your change. Thanks for the PR!

**Pull request merged**
