### PR TITLE
HOTFIX: stop using batch write to rocksdb

### PR DESCRIPTION
**Pull request by ymatsuda**
@guozhangwang 

Removing batch write to RocksDB because I observed segmentation faults in RocksDB's batch write.

### CODE REVIEW

**Comment by ymatsuda** [comment]
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011ee99c2a, pid=795, tid=27143
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b27) (build 1.8.0_40-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni8364075677477484103..jnilib+0xb9c2a]  _ZN7rocksdb18WriteBatchInternal11SetSequenceEPNS_10WriteBatchEy+0xa
#
```

**Comment by jkreps** [comment]
How does this impact performance?

**Comment by guozhangwang** [comment]
@jkreps We used an older version of RocksDB(3.10) while doing the experiment, and disabling batch writes does not incur much performance degradation as @ymatsuda observes. We will upgrade to the latest 4.2 version and see if the issue is already fixed.

**Comment by ymatsuda** [comment]
So far, I was unable to reproduce this with 4.1.

**Pull request closed without merging**
