### PR TITLE
MINOR: Fix expected output in Streams quickstart

### PR DESCRIPTION
**Pull request by vahidhashemian**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vahidhashemian** [comment]
cc @mjsax @guozhangwang, please review this minor doc update. Thanks!

**Comment by guozhangwang** [comment]
LGTM! Thanks @vahidhashemian

**Comment by guozhangwang** [comment]
Cherry-picked to 2.0 as well.

**Comment by mjsax** [comment]
Should cherry-pick to older branches, too (including `0.11.0` -- not required for `0.10.2` as the quickstart is different there)

**Pull request merged**
