### PR TITLE
KAFKA-5934 Cross build for Scala 2.12

### PR DESCRIPTION
**Pull request by schrepfler**
Tried to do some simple refactorings to publish Kafka 0.8.x for Scala 2.12 as it's still used quite a lot in the industry. Let me know if more needs to be done, I don't use gradle day to day plus there probably was a change in gradle 4 which required a change to  build.gradle and I bumped the scala modules from 1.0.2 to 1.0.6.

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by ijuma** [comment]
Thanks for the PR. We are no longer making changes to the 0.8.2 branch. Closing.

**Pull request closed without merging**
