### PR TITLE
MINOR: Fix a few transaction coordinator issues

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Review by ijuma — COMMENTED** [review]
Should there be some tests along with these fixes?

**Comment by apurvam** [comment]
@ijuma : I think @hachikuji found these through writing the first integration test. Once this is merged along with the clients PR, I will work on submitting the first integration test which will cover these bugs.

**Review by apurvam — APPROVED** [review]
LGTM!

**Comment by ijuma** [comment]
Seems like there are a number of test failures in the Jenkins build.

**Comment by apurvam** [comment]
Indeed. @hachikuji I can take this over and submit these changes along with my first integration test. What do you think?

**Comment by hachikuji** [comment]
@apurvam Sounds good to me. I'll go ahead and close this.

**Pull request closed without merging**
