### PR TITLE
MINOR: Remove unused AdminZkClient in MetadataSupport

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
Remove unused AdminZkClient in MetadataSupport

*Summary of testing strategy (including rationale)*
QA

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
cc @showuon 🤝

**Comment by showuon** [comment]
I'll check it tomorrow. Thanks.

**Comment by showuon** [comment]
@dengziming , could you please rebase to the latest trunk and trigger jenkins build again? I'd like to confirm it won't break any tests. Thanks.

**Comment by dengziming** [comment]
@showuon Aha, I just rebased it.

**Comment by showuon** [comment]
Failed tests are unrelated.
```
    Build / ARM / kafka.network.SocketServerTest.remoteCloseWithoutBufferedReceives()
    Build / JDK 11 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()
    Build / JDK 11 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()
    Build / JDK 17 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testPathToJsonFile, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testTopicPartition, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testPathToJsonFile, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()
    Build / JDK 17 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()
    Build / JDK 8 and Scala 2.12 / kafka.api.DelegationTokenEndToEndAuthorizationTest.testNoConsumeWithoutDescribeAclViaSubscribe()
```

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the PR.

**Comment by showuon** [comment]
Confirmed this `adminZkClient` is not used anywhere else. So, it makes sense to remove it. If the `ZkSupport` object needs to create `adminZkClient`, it can create an `AdminZkClient` anytime via the `zkClient` class member.

**Pull request merged**
