### PR TITLE
MINOR Added assertion checks in tests for ProducerStateManager.active Producers usages.

### PR DESCRIPTION
**Pull request by satishd**
MINOR Added assertion checks in tests for ProducerStateManager.active Producers usages.

This is a followup from [here](https://github.com/apache/kafka/pull/13040#discussion_r1102874502).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by satishd** [comment]
Test failures do not seem to be related to the changes in the PR.

**Review by showuon — COMMENTED** [review]
Overall LGTM! But do you think we should add a null `producerStateEntry` test case?

**Comment by satishd** [comment]
Thanks @showuon for your review. 

> Overall LGTM! But do you think we should add a null `producerStateEntry` test case?

Can you be more specific about the test case you are referring to here? If you are asking to write a test case to check for not containing a producer entry for active produces, those are already covered by using a check like `stateManager.activeProducers.containsKey(producerId)` instead of get and check for null.

**Review by showuon — APPROVED** [review]
Thanks for the explanation. LGTM!

**Comment by satishd** [comment]
Test failures are not related to this change.

**Pull request merged**
