### PR TITLE
MINOR: Reduce logging level

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
cc @guozhangwang @xvrl thanks.

**Review by mjsax — APPROVED** [review]

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5985/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by guozhangwang** [comment]
LGTM: merged to trunk.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5970/
Test PASSed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
