### PR TITLE
KAFKA-13242: Ensure UpdateFeatures is properly handled in KRaft

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
This patch fixes several problems with the UpdateFeatures API in KRaft:

KafkaApis did not properly forward this request type to the controller.
ControllerApis did not handle the request type.
Some other small fixes.

*Summary of testing strategy (including rationale)*
1. unit test in FeatureControlManagerTest
2. I tried to converted UpdateFeaturesTest to use KRaft, but I encountered some problems, for example, we use totally different class in KRaft and zk mode, and we can overwrite data in zk path but we can't overwrite data in KRaft metadata topic, so I decided to handle this in a future PR.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
Hello @cmccabe ,PTAL, thanks.

**Review by mumrah — COMMENTED** [review]
@dengziming, thanks for the patch! I have many similar looking changes locally as part of my KIP-778 prototype. This is a good chunk to split out and get merged ahead of the other changes. 

There are some possible changes to KIP-584 coming from that discussion, so let's see what happens there. I'll try to take a look at this next week (after thanksgiving).

**Comment by mumrah** [comment]
@dengziming, we have a few changes to the feature flags coming in KIP-778. Let's hold off on merging this until the KIP is adopted.

**Comment by dengziming** [comment]
Thank you @mumrah , I am checking KIP-778 about this.

**Comment by dengziming** [comment]
See #12036

**Pull request closed without merging**
