### PR TITLE
KAFKA-3358; Only request metadata updates once we have topics or a pattern subscription

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji and @ewencp

**Comment by ijuma** [comment]
There are some issues with this approach, closing for now.

**Comment by SinghAsDev** [comment]
@ijuma do you mind sharing the concerns?

**Comment by ijuma** [comment]
@SinghAsDev This breaks `AdminClient`, `Fetcher.getTopicMetadata` and a few other methods. The obvious workaround is to update the `Metadata` instance before calling `poll`, but it's a bit hacky so it needs more thought and analysis. @hachikuji has picked up the JIRA and will submit a PR that actually works when it's ready.

**Comment by SinghAsDev** [comment]
@ijuma thanks for the info.

**Pull request closed without merging**
