### PR TITLE
MINOR: Fix version verification in system test

### PR DESCRIPTION
**Pull request by cadonna**
The system test StreamsUpgradeTest.test_version_probing_upgrade
tries to verify the wrong version for version probing.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @lct45 @ableegoldman @vvcephei

**Comment by cadonna** [comment]
This fix needs to be cherry-picked to 2.7 and 2.6

**Comment by cadonna** [comment]
System tests run: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4276/

**Review by ableegoldman — APPROVED** [review]
Aw, not again 😕  We even did run the system tests on the PR that broke this but I guess no one actually checked the results when they finally finished running. Looks like the tests you kicked off passed this time

Nice find though. Although the PR that broke this was merged over a week ago...why didn't we notice until now? Was it just hidden by some other failures until now(eg the generation parsing issue)?

**Comment by ableegoldman** [comment]
One flaky test failed: `EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[true]`

Confirmed systems test passed. Merging to trunk

**Comment by ableegoldman** [comment]
Cherrypicked to 2.6 & 2.7 cc/ @bbejeck

**Pull request merged**
