### PR TITLE
KAFKA-3665; Default ssl.endpoint.identification.algorithm should be https

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
System test build started: https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/63/

**Comment by rajinisivaram** [comment]
@ijuma I have a feeling this would break system tests. It may be worth running the sanity tests to check. Shouldn't be too hard to fix though.

**Comment by rajinisivaram** [comment]
@ijuma Ignore my comment - I didn't notice that you were already running the system tests :-)

**Comment by ijuma** [comment]
@rajinisivaram I had the same feeling as you. :)

**Comment by harshach** [comment]
+1. Looks like it needs up merge.

**Comment by VanessaHenderson** [comment]
Any status on merging this fix?

**Comment by ijuma** [comment]
@VanessaHenderson, we need to do more testing and potentially update the system tests before we can merge this.

**Comment by rajinisivaram** [comment]
@ijuma Would you like me to update the system tests? I should be able to do it independent of the change to the default since it will be good to test with endpoint validation anyway.

**Comment by ijuma** [comment]
@rajinisivaram, that would be great!

**Comment by omkreddy** [comment]
Closing, as this fixed in #4956

**Pull request closed without merging**
