### PR TITLE
MINOR: update JavaDoc for simple helper interfaces of KStream and KTable operators

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
@guozhangwang @dguy @enothereska @miguno

**Comment by guozhangwang** [comment]
```
scala2.12/streams/src/main/java/org/apache/kafka/streams/kstream/KeyValueMapper.java:20:8: Unused import - org.apache.kafka.common.serialization.Serde.
```

**Comment by mjsax** [comment]
@guozhangwang Updated

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
LGTM and merged to trunk.

**Pull request closed without merging**
