### PR TITLE
KAFKA-9804:Extract consumer configs out of PerfConfig

### PR DESCRIPTION
**Pull request by jiameixie**
Configs for producer has been extracted out of PerfConfig in
https://github.com/apache/kafka/pull/3613/commits. The remaining
in PerfConfig are configs for consumer. And ConsumerPerformance
also has configs for consumer. Separating these configs into two
classes is not concise. So we can put all configs into class
ConsumerPerformance.ConsumerPerfConfig.

Change-Id: I38e2fdf7c7930af786e03cbb5d9deb2f4ef50dee
Signed-off-by: Jiamei Xie <jiamei.xie@arm.com>

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jiameixie** [comment]
@guozhangwang @ijuma @junrao PTAL, thanks

**Comment by jiameixie** [comment]
@guozhangwang @ijuma @junrao PTAL, thanks.

**Comment by guozhangwang** [comment]
@huxihx could you take a look at this PR?

**Comment by jiameixie** [comment]
Call for review @huxihx

**Comment by jiameixie** [comment]
Could you take a look at this PR? Thanks @huxihx

**Comment by jiameixie** [comment]
Call for review @huxihx

**Pull request closed without merging**
