### PR TITLE
MINOR: Fix some warnings

### PR DESCRIPTION
**Pull request by tinaselenge**
Fix warnings:
- Add missing Unit type definitions
- Replace !<>.isEmpty with .nonEmpty
- Replace !<>.isDefined with .isEmpty
- Replace <>(0) with .head

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by showuon** [comment]
@tinaselenge , thanks for the PR. So, which compiler warnings are you trying to fix here? Could you add some more info in PR description? Thanks.

**Comment by tinaselenge** [comment]
@showuon I have addressed your comment. There seem to be some unrelated tests failing. Would  you be able to retrigger them?

**Review by showuon — APPROVED** [review]
LGTM! 
Let's wait for the jenkins build results. Thanks for the patch!

**Comment by ijuma** [comment]
I don't think most of these are actual compiler warnings are they? They seem like lint type warnings. It would be good to clarify in the PR description.

**Pull request merged**
