### PR TITLE
Assign ConfigDef.NO_DEFAULT_VALUE as a literal, use equals() for comp…

### PR DESCRIPTION
**Pull request by shikhar**
I doubt there is a good reason for using `new String("")` and `==` for equality comparison.

### CODE REVIEW

**Comment by shikhar** [comment]
@ewencp for review. Just a minor thing that stuck out to me when going through config code

**Comment by shikhar** [comment]
Heh I should have tried at least one of the config tests, lots failing around default configuration. Not quite sure what the nuance here is!

**Comment by ijuma** [comment]
It's intentional. `new String("")` is a sentinel and reference equality needs to be used for it to work as intended.

**Comment by shikhar** [comment]
Thanks for the explanation @ijuma

**Comment by shikhar** [comment]
@ijuma why not use `new Object()` for this? I think that's clearer about the intention.

**Comment by shikhar** [comment]
BTW `new String("")` is really the same thing as `""` it seems,

```
scala> "" == new String("")
res0: Boolean = true
```

**Comment by ijuma** [comment]
@shikhar `new Object()` could be used and is perhaps clearer. The code you pasted is for Scala where `==` is the same as `equals` in Java. In Scala, `eq` is the equivalent of `==` in Java:

``` scala
scala> "" eq new String("")
<console>:12: warning: comparing a fresh object using 'eq' will always yield false
       "" eq new String("")
          ^
res0: Boolean = false
```

**Pull request closed without merging**
