### PR TITLE
KAFKA-4755: Cherrypick streams tests from trunk

### PR DESCRIPTION
**Pull request by enothereska**
This addresses some tests' instabilities in 0.10.2 that have been fixed in trunk

### CODE REVIEW

**Comment by enothereska** [comment]
https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/258/ passed

**Comment by enothereska** [comment]
Environment problems?

**Comment by enothereska** [comment]
retest this please

**Comment by enothereska** [comment]
Don't merge yet until system tests for perf are green. They are not yet.

**Comment by mjsax** [comment]
Can you update the title to `KAFKA-4755` ?

**Comment by enothereska** [comment]
https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/268/ passed

**Comment by enothereska** [comment]
https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/269/ passed

**Comment by guozhangwang** [comment]
retest this please.

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
Merged to 0.10.2. @enothereska could you manually close this PR?

**Pull request closed without merging**
