### PR TITLE
MINOR; Iterate over the partitions only once when building LeaderAndIsrRequest

### PR DESCRIPTION
**Pull request by dajac**
Small optimization in building LeaderAndIsrRequest to avoid iterating twice on the partitions.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
@hachikuji Could you take a look at this one please?

**Review by chia7712 — APPROVED** [review]
Is it worth of collecting value of ```leaderAndIsrPartitionStates``` in the same loop to avoid calling ```leaderAndIsrPartitionStates.values.toBuffer.asJava``` later?

**Comment by ijuma** [comment]
ok to test

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by ijuma** [comment]
One job passed, the other two had unrelated test failures.

**Pull request merged**
