### PR TITLE
KAFKA-4053: remove redundant if/else statements in TopicCommand

### PR DESCRIPTION
**Pull request by sh-z**

### CODE REVIEW

**Comment by gwenshap** [comment]
good call :)

I don't think we have tests covering TopicCommand, so... did you validate all the options work as expected?

**Comment by sh-z** [comment]
@gwenshap Thanks for your review.

Before I thought we had tests covering it, so I didn't validate it specially. I will do it and share with you the result later.

**Comment by sh-z** [comment]
@gwenshap BTW, usually how will you test the functions in TopicCommand, test manually?

**Comment by sh-z** [comment]
@gwenshap I tested `create`, `alter`, `delete` and `describe` functions in TopicCommand manually, they worked well as expected. 

I picked up `if-exists`, `if-not-exists` and `under-replicated-partitions` as test cases for each operations.

**Comment by gwenshap** [comment]
Perfect, thank you :)
LGTM.

**Pull request closed without merging**
