### PR TITLE
MINOR: Catch JsonMappingException subclass

### PR DESCRIPTION
**Pull request by rhardouin**
`InvalidTypeIdException` cannot be catched currently

### CODE REVIEW

**Comment by ijuma** [comment]
cc @rajinisivaram

**Comment by rajinisivaram** [comment]
@rhardouin Good catch. Would you be able to add an unit test? Thank you!

**Comment by rhardouin** [comment]
ok ;-)

**Comment by rhardouin** [comment]
I added unit tests for all `RestExceptionMapper` use cases

**Comment by rhardouin** [comment]
retest this please

**Comment by ijuma** [comment]
cc @cmccabe

**Comment by cmccabe** [comment]
Thanks, @rhardouin.  LGTM

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Pull request merged**
