### PR TITLE
MINOR: Fix javadoc warnings

### PR DESCRIPTION
**Pull request by cadonna**
This commit fixes javadoc warnings caused by missing imports.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @mjsax @guozhangwang @vvcephei @bbejeck

**Comment by bbejeck** [comment]
Ok to test.

**Comment by bbejeck** [comment]
Java 11 failed with `Caused by: java.lang.OutOfMemoryError: unable to create new native thread`

**Review by bbejeck — APPROVED** [review]
Thanks for the fix @cadonna, LGTM

**Comment by bbejeck** [comment]
merged #8809 into trunk

**Pull request merged**
