### PR TITLE
KAFKA-4547 (0.10.1 hotfix): Avoid unnecessary offset commit that could lead to an invalid offset position if partition is paused

### PR DESCRIPTION
**Pull request by vahidhashemian**

### CODE REVIEW

**Comment by vahidhashemian** [comment]
@hachikuji for review.

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
@vahidhashemian This is already merged in 0.10.1, could you close this PR manually?

**Comment by vahidhashemian** [comment]
Sure.

**Pull request closed without merging**
