### PR TITLE
MINOR: Style fixes to KafkaRaftClient

### PR DESCRIPTION
**Pull request by abbccdda**
As title suggested, made some style fixes to the class `KafkaRaftClient`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the PR. Might need to merge `trunk` and trigger the jenkins build again since there are `jdk 8 + scala 2.12` and `jdk11 + scala 2.13` failed with: 
```
Process 'Gradle Test Executor 127' finished with non-zero exit value 1
```

**Comment by ijuma** [comment]
@abbccdda Committer approval is required for PRs to be merged. I don't see that here.

**Comment by abbccdda** [comment]
@ijuma That's a good call, should I revert it? It was just a styling change PR.

**Comment by ijuma** [comment]
You don't have to revert it, but can you please get a committer approval?

**Review by mumrah — COMMENTED** [review]
LGTM, retroactively. Thanks @abbccdda!

**Comment by mumrah** [comment]
@ijuma we should be able to configure the repo to require an approval from a committer for `trunk` PRs, have we looked into this? Similarly, we can set up CODEOWNERS for different areas of the project.

**Comment by ijuma** [comment]
@mumrah We haven't and it would be good to do.

**Comment by mumrah** [comment]
@ijuma i'll send something out on the devs list

**Pull request merged**
