### PR TITLE
MINOR: Improve versioning in docs when a full version is required

### PR DESCRIPTION
**Pull request by ijuma**
Also fix quickstart.

### CODE REVIEW

**Review by dguy — APPROVED** [review]
Thanks @ijuma, LGTM

**Comment by ijuma** [comment]
Thanks, since it only updates docs, merging to trunk and 0.11.0 without waiting for Jenkins.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5965/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5950/
Test PASSed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
