### PR TITLE
KAFKA-8456: Stabilize flaky StoreUpgradeIntegrationTest

### PR DESCRIPTION
**Pull request by mjsax**
Running those tests locally, most run about 10 seconds. The default timeout is 15 seconds. I think it makes sense to provide more head room on Jenkins.

This PR increase the timeout to 60 seconds.

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna @abbccdda

**Review by abbccdda — COMMENTED** [review]
Have we changed the test log and made sure this is due to time constraint?

**Review by guozhangwang — COMMENTED** [review]
I suspect many times it is because brokers are not completely up / finished creating topics; if that is indeed true, we could also update line 72 on `CLUSTER.createTopic(inputStream);` to use `createAndWait`.

Otherwise, lgtm.

**Comment by mjsax** [comment]
@guozhangwang Just cycling back to this PR. The use `createTopics()` method uses `IntegrationTestUtils.waitForTopicPartitions(brokers(), topicPartitions, TOPIC_CREATION_TIMEOUT);` internally. Seems what you say is already covered?

Let me know, so we can push this PR over the finish line.

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna @abbccdda

**Review by bbejeck — APPROVED** [review]
Thanks for the patch @mjsax, LGTM.

**Comment by bbejeck** [comment]
>The use createTopics() method uses IntegrationTestUtils.waitForTopicPartitions(brokers(), topicPartitions, TOPIC_CREATION_TIMEOUT); internally.

FWIW the `TOPIC_CREATION_TIMEOUT` is 30 seconds, so IMHO topic creation time is covered.

**Comment by bbejeck** [comment]
call for second review 
any of  @guozhangwang @vvcephei @ableegoldman @cadonna @abbccdda

**Review by ableegoldman — APPROVED** [review]
LGTM -- out of curiosity though why do we feel Jenkins may take longer to read/write rocksdb? Is it hdd?

**Comment by mjsax** [comment]
Jenkins is running in a VM environment and the machines are not very powerful (including CPU and HDD).

**Pull request merged**
