### PR TITLE
MINOR: Fix logger name override

### PR DESCRIPTION
**Pull request by ijuma**
This regressed during the log4j -> scalalogging
change.

Added unit tests, one of which failed before the fix.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
@rajinisivaram, can you please take a look? We should probably include this in 1.1.

**Comment by cmccabe** [comment]
Yeah, this looks important for 1.1

**Review by rajinisivaram — APPROVED** [review]
@ijuma Thanks for the PR, LGTM.

**Comment by rajinisivaram** [comment]
Test failure is not related, merging to trunk and 1.1.

**Pull request merged**
