### PR TITLE
KAFKA-16854: Add StopReplica v5

### PR DESCRIPTION
**Pull request by clolov**
### Summary
Add StopReplica v5 for KIP-950 and put it behind an unstable flag

### CODE REVIEW

**Comment by dajac** [comment]
Hey @clolov -- I wonder if it is worth doing the ZK related changes for this KIP. It looks like it won't be in 3.8 and we won't support ZK in 4.0.

**Comment by clolov** [comment]
I think myself, @showuon, @satishd, @jeqo, @ivanyu and a few others would like to have disablement available both for ZK and KRaft as part of the effort to mark tiered storage as generally available. But I will let them share an opinion as well

**Comment by dajac** [comment]
I think the question is how are we going to bring it to ZK if 3.8 is the last version supporting it.

**Comment by showuon** [comment]
@dajac , what we decided is we will try to complete ZK part implementation in v3.8.0. There are many users are still using ZK mode, so we think we still need to provide ZK part implementation to these users (if possible).

**Review by showuon — COMMENTED** [review]
@clolov , this breaks many tests. Please help check. Thanks.

**Comment by satishd** [comment]
Retriggered the build to start the build/tests again.

**Comment by mumrah** [comment]
I don't think we should be adding any new ZK features at this point. 

KIP-405 was first in early access in 3.6 and ZK was deprecated in 3.5. It seems pretty reasonable to require users to be on KRaft in order to use TS.

**Pull request closed without merging**
