### PR TITLE
MINOR: Revert to Gradle 8.5 [DO NOT MERGE YET]

### PR DESCRIPTION
**Pull request by jlprat**
Rollback to Gradle 8.5.
When upgrading to Gradle 8.6, Scala incremental compilation seems to be broken. See https://github.com/apache/kafka/pull/15404#discussion_r1526739190

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
@jlprat Thanks for the PR. It looks like the PR contains unwanted files.

**Comment by jlprat** [comment]
Oops, you are right @dajac I don't know what happened. I'll check

**Comment by jlprat** [comment]
I accidentally committed the `core/data` files from some failed test run.
@dajac feel free to review now. Thanks!

**Review by dajac — APPROVED** [review]
LGTM, thanks.

**Review by gaurav-narula — COMMENTED** [review]
Perhaps I'm missing something but I'm not able to reproduce the original issue with Gradle 8.6.

Here's what I tried:

1. Run `./gradlew core:clean`
2. Run `./gradlew core:compileTestScala`

```
~/dev/apache-kafka trunk* ≡ ☸ ❯ ls -alh core/build/classes/scala/test/kafka/admin/
Permissions Size User   Date Modified Name
.rw-r--r--@  50k gaurav 18 Mar 11:02  AclCommandTest.class
.rw-r--r--@  27k gaurav 18 Mar 11:02  AddPartitionsTest.class
.rw-r--r--@  25k gaurav 18 Mar 11:02  AdminRackAwareTest.class
.rw-r--r--@  42k gaurav 18 Mar 11:02  AdminZkClientTest.class
.rw-r--r--@  12k gaurav 18 Mar 11:02  BrokerApiVersionsCommandTest.class
.rw-r--r--@  18k gaurav 18 Mar 11:02  ConfigCommandIntegrationTest.class
.rw-r--r--@ 2.7k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$1.class
.rw-r--r--@ 4.4k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$2.class
.rw-r--r--@ 2.3k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$3.class
.rw-r--r--@ 8.5k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$4.class
.rw-r--r--@ 3.0k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$5.class
.rw-r--r--@ 5.1k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$6.class
.rw-r--r--@ 3.0k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$7.class
.rw-r--r--@ 5.2k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$8.class
.rw-r--r--@ 2.5k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$9.class
.rw-r--r--@ 5.2k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$10.class
.rw-r--r--@ 4.4k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$11.class
.rw-r--r--@ 8.0k gaurav 18 Mar 11:02  ConfigCommandTest$CredentialChange$1.class
.rw-r--r--@ 3.0k gaurav 18 Mar 11:02  ConfigCommandTest$CredentialChange$2$.class
.rw-r--r--@ 3.8k gaurav 18 Mar 11:02  ConfigCommandTest$DummyAdminClient.class
.rw-r--r--@ 2.3k gaurav 18 Mar 11:02  ConfigCommandTest$DummyAdminZkClient.class
.rw-r--r--@ 1.4k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$1.class
.rw-r--r--@ 1.4k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$2.class
.rw-r--r--@ 1.4k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$3.class
.rw-r--r--@ 1.4k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$4.class
.rw-r--r--@ 1.5k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$5.class
.rw-r--r--@ 2.0k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$6.class
.rw-r--r--@  96k gaurav 18 Mar 11:02  ConfigCommandTest.class
.rw-r--r--@  59k gaurav 18 Mar 11:02  DeleteTopicTest.class
.rw-r--r--@  21k gaurav 18 Mar 11:02  ListOffsetsIntegrationTest.class
.rw-r--r--@  815 gaurav 18 Mar 11:02  MyRemoteLogMetadataManager$.class
.rw-r--r--@ 5.3k gaurav 18 Mar 11:02  MyRemoteLogMetadataManager.class
.rw-r--r--@  743 gaurav 18 Mar 11:02  MyRemoteStorageManager$.class
.rw-r--r--@ 1.7k gaurav 18 Mar 11:02  MyRemoteStorageManager.class
.rw-r--r--@  16k gaurav 18 Mar 11:02  RackAwareTest.class
.rw-r--r--@  29k gaurav 18 Mar 11:02  RemoteTopicCrudTest.class
.rw-r--r--@ 2.9k gaurav 18 Mar 11:02  ReplicaDistributions$.class
.rw-r--r--@ 7.4k gaurav 18 Mar 11:02  ReplicaDistributions.class
.rw-r--r--@ 7.6k gaurav 18 Mar 11:02  ReplicationQuotaUtils$.class
.rw-r--r--@ 2.1k gaurav 18 Mar 11:02  ReplicationQuotaUtils.class
.rw-r--r--@ 2.8k gaurav 18 Mar 11:02  UserScramCredentialsCommandTest$ConfigCommandResult$.class
.rw-r--r--@ 3.9k gaurav 18 Mar 11:02  UserScramCredentialsCommandTest$ConfigCommandResult.class
.rw-r--r--@  18k gaurav 18 Mar 11:02  UserScramCredentialsCommandTest.class
```

3. Modify a test in `core/src/test/scala/unit/kafka/admin/AclCommandTest.scala` (added a println()) and re-run `./gradle core:compileTestScala`

```
~/dev/apache-kafka trunk* ≡ ☸ ❯ ls -alh core/build/classes/scala/test/kafka/admin/
Permissions Size User   Date Modified Name
.rw-r--r--@  50k gaurav 18 Mar 11:03  AclCommandTest.class
.rw-r--r--@  27k gaurav 18 Mar 11:02  AddPartitionsTest.class
.rw-r--r--@  25k gaurav 18 Mar 11:02  AdminRackAwareTest.class
.rw-r--r--@  42k gaurav 18 Mar 11:02  AdminZkClientTest.class
.rw-r--r--@  12k gaurav 18 Mar 11:02  BrokerApiVersionsCommandTest.class
.rw-r--r--@  18k gaurav 18 Mar 11:02  ConfigCommandIntegrationTest.class
.rw-r--r--@ 2.7k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$1.class
.rw-r--r--@ 4.4k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$2.class
.rw-r--r--@ 2.3k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$3.class
.rw-r--r--@ 8.5k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$4.class
.rw-r--r--@ 3.0k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$5.class
.rw-r--r--@ 5.1k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$6.class
.rw-r--r--@ 3.0k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$7.class
.rw-r--r--@ 5.2k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$8.class
.rw-r--r--@ 2.5k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$9.class
.rw-r--r--@ 5.2k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$10.class
.rw-r--r--@ 4.4k gaurav 18 Mar 11:02  ConfigCommandTest$$anon$11.class
.rw-r--r--@ 8.0k gaurav 18 Mar 11:02  ConfigCommandTest$CredentialChange$1.class
.rw-r--r--@ 3.0k gaurav 18 Mar 11:02  ConfigCommandTest$CredentialChange$2$.class
.rw-r--r--@ 3.8k gaurav 18 Mar 11:02  ConfigCommandTest$DummyAdminClient.class
.rw-r--r--@ 2.3k gaurav 18 Mar 11:02  ConfigCommandTest$DummyAdminZkClient.class
.rw-r--r--@ 1.4k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$1.class
.rw-r--r--@ 1.4k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$2.class
.rw-r--r--@ 1.4k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$3.class
.rw-r--r--@ 1.4k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$4.class
.rw-r--r--@ 1.5k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$5.class
.rw-r--r--@ 2.0k gaurav 18 Mar 11:02  ConfigCommandTest$TestAdminZkClient$6.class
.rw-r--r--@  96k gaurav 18 Mar 11:02  ConfigCommandTest.class
.rw-r--r--@  59k gaurav 18 Mar 11:02  DeleteTopicTest.class
.rw-r--r--@  21k gaurav 18 Mar 11:02  ListOffsetsIntegrationTest.class
.rw-r--r--@  815 gaurav 18 Mar 11:02  MyRemoteLogMetadataManager$.class
.rw-r--r--@ 5.3k gaurav 18 Mar 11:02  MyRemoteLogMetadataManager.class
.rw-r--r--@  743 gaurav 18 Mar 11:02  MyRemoteStorageManager$.class
.rw-r--r--@ 1.7k gaurav 18 Mar 11:02  MyRemoteStorageManager.class
.rw-r--r--@  16k gaurav 18 Mar 11:02  RackAwareTest.class
.rw-r--r--@  29k gaurav 18 Mar 11:02  RemoteTopicCrudTest.class
.rw-r--r--@ 2.9k gaurav 18 Mar 11:02  ReplicaDistributions$.class
.rw-r--r--@ 7.4k gaurav 18 Mar 11:02  ReplicaDistributions.class
.rw-r--r--@ 7.6k gaurav 18 Mar 11:02  ReplicationQuotaUtils$.class
.rw-r--r--@ 2.1k gaurav 18 Mar 11:02  ReplicationQuotaUtils.class
.rw-r--r--@ 2.8k gaurav 18 Mar 11:02  UserScramCredentialsCommandTest$ConfigCommandResult$.class
.rw-r--r--@ 3.9k gaurav 18 Mar 11:02  UserScramCredentialsCommandTest$ConfigCommandResult.class
.rw-r--r--@  18k gaurav 18 Mar 11:02  UserScramCredentialsCommandTest.class
```

Note that only the timestamp for `AclCommandTest.class` has changed which suggests incremental compilation? Perhaps I'm overlooking something?

**Comment by jlprat** [comment]
I managed to reproduce the issue with Gradle 8.6 once, but now that I'm trying to reproduce it again, it seems that incremental compilation works as expected (I tried it on `trunk` and modified `kafka.admin.AclCommandTest.scala` as well).
I think we should not merge this PR just yet until we clarify if it's a problem or not.

**Comment by pasharik** [comment]
Hi All,

Update on my original comment: issue with incremental compilation seems to happen only when changes made from IntelliJ.

Would anybody mind trying to reproduce it on your local environment? Steps to reproduce:

* Open `kafka.admin.AclCommandTest` in IntelliJ Idea. I'm using `2023.3.5 Ultimate`
* Add `println("a")` at the beginning of `testAclCliWithAuthorizer` method
* Run in terminal: `./gradlew core:test --tests "kafka.admin.AclCommandTest.testAclCliWithAuthorizer"`
* Result: all tests in `core` module are re-compiled

If test modified with `vim`, only single test class is re-compiled

**Comment by gaurav-narula** [comment]
Thanks @pasharik ! I was able to reproduce it using the steps you mentioned above.

I've a potential fix. Can you please try updating the zinc version in `gradle/dependencies.gradle:166`  to `1.9.6` and try the steps once again? It seems to fix things on my end.

**Comment by pasharik** [comment]
@gaurav-narula I've tried zinc `1.9.6` with gradle `8.5` and `8.6`, but getting the same issue with all tests re-compiled.

Probably one radical solution to this incremental compilation issue with Scala, can be re-writing the entire `AclCommandTest` in Java? :smile: I'm looking to add KRaft support for this test, so there will be lot of changes in it anyway, as I understand.  I see there are already some Java tests in `core` module

**Comment by jlprat** [comment]
I'm restarting the build. The previous run I started this morning (CET timezone) got hung towards the end (it was running for over 6 hours).

**Comment by chia7712** [comment]
> Open kafka.admin.AclCommandTest in IntelliJ Idea. I'm using 2023.3.5 Ultimate
    Add println("a") at the beginning of testAclCliWithAuthorizer method
    Run in terminal: ./gradlew core:test --tests "kafka.admin.AclCommandTest.testAclCliWithAuthorizer"
    Result: all tests in core module are re-compiled

I can't reproduce it and my Idea is 2023.3.6  Ultimate. I add some changes to `testAclCliWithAuthorizer` and then run `./gradlew core:test --tests "kafka.admin.AclCommandTest.testAclCliWithAuthorizer"`. Only file `AclCommandTest.class` get recompiled. 

螢幕快照 2024-03-24 20-08-53

**Comment by chia7712** [comment]
any updates here? gradle 8.7 has been released. we can update gradle to 8.7 if the issue is nonexistent

**Comment by pasharik** [comment]
> any updates here? gradle 8.7 has been released. we can update gradle to 8.7 if the issue is nonexistent

Update to 8.7 is ok with me. For now, I'm compiling my test with `scalac` as a workaround anyway

**Comment by chia7712** [comment]
> Update to 8.7 is ok with me. For now, I'm compiling my test with scalac as a workaround anyway

@jlprat thanks for response. ticket: https://issues.apache.org/jira/browse/KAFKA-16490

**Comment by jlprat** [comment]
Closing this one, in favour of whatever comes out of https://issues.apache.org/jira/browse/KAFKA-16490

**Pull request closed without merging**
