### PR TITLE
KAFKA-5248: Remove unused/unneeded retention time in TxnOffsetCommitRequest

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
cc @guozhangwang

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
LGTM. Seems we already have ignored this field in `KafkaApis`.

@hachikuji feel free to merge it after rebasing.

**Review by apurvam — APPROVED** [review]
Good to see unused stuff actually getting removed!

**Pull request closed without merging**
