### PR TITLE
MINOR: Update rocksDB dependency to 4.11.2

### PR DESCRIPTION
**Pull request by jozanek**
There are 32 failing tests on both trunk and my branch.

### CODE REVIEW

**Comment by guozhangwang** [comment]
@jozi-k 4.11.2 is the most recent stable release, LGTM. cc @enothereska @dguy @mjsax @hjafarpour

**Comment by enothereska** [comment]
@jozi-k I don't see 32 failing tests...the one that has failed in jenkins tends to periodically fail, so shouldn't be an issue.

**Comment by guozhangwang** [comment]
Merged into trunk. Thanks @jozi-k !

**Comment by jozanek** [comment]
@enothereska It was the case on my local machine. I thought jenkins runs the same test suite, but apparently that is not the case.

**Pull request closed without merging**
