### PR TITLE
add Windows script 'kafka-consumer-groups.bat' as issue Kafka-4310 mentions

### PR DESCRIPTION
**Pull request by huxihx**
add file 'kafka-consumer-groups.bat' for Windows platform

### CODE REVIEW

**Comment by hachikuji** [comment]
Thanks for catching this. LGTM.

**Comment by hachikuji** [comment]
@vahidhashemian Mind doing a quick sanity check on this? I recall you've been doing some testing in a windows environment.

**Comment by vahidhashemian** [comment]
@hachikuji Sure, I'll take a look today.

**Comment by vahidhashemian** [comment]
I ran a couple of quick tests on Windows and did not notice any issues. LGTM.

**Comment by hachikuji** [comment]
Thanks Vahid, merging to trunk.

**Comment by huxihx** [comment]
Since I am a new contributor, sorry for the stupid question: Does this mean I can safely close the issue in JIRA?

**Comment by hachikuji** [comment]
I think I already did, but feel free to do it if I forgot.

**Pull request closed without merging**
