### PR TITLE
KAFKA-15251: Add 3.5.1 to system tests

### PR DESCRIPTION
**Pull request by divijvaidya**
Adding new version 3.5.1 to system tests as per https://cwiki.apache.org/confluence/display/KAFKA/Release+Process

(search for "In trunk update the following files with the current release number" in the script above)

### CODE REVIEW

**Comment by divijvaidya** [comment]
@mimaison @showuon - this is related to 3.5.1 release. Please take a look at this when you get a chance.

**Comment by mimaison** [comment]
The 3.5.1 packages are not in https://s3-us-west-2.amazonaws.com/kafka-packages yet. You need someone from Confluent to upload them (they own the S3 bucket). 

There's also https://github.com/apache/kafka/pull/13860 still in progress (hoping to get it merge this week).

**Comment by machi1990** [comment]
@divijvaidya looks like this PR solves the ticket https://issues.apache.org/jira/browse/KAFKA-15251. Do you mind assigning the ticket to yourself and updating the PR title accordingly? Thanks

**Comment by mjsax** [comment]
> The 3.5.1 packages are not in https://s3-us-west-2.amazonaws.com/kafka-packages yet. You need someone from Confluent to upload them (they own the S3 bucket).

Did this today.

**Review by mjsax — APPROVED** [review]

**Comment by divijvaidya** [comment]
Thank you @mjsax for uploading the artifacts.

**Pull request merged**
