### PR TITLE
MINOR: Add 3.5.2 and 3.6.1 to system tests

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
@mjsax @dajac @vvcephei Can you upload the 3.6.1 artifacts to the kafka-packages S3 bucket?
Steps are described in https://cwiki.apache.org/confluence/display/KAFKA/Release+Process#ReleaseProcess-Afterthevotepasses

**Comment by showuon** [comment]
> @mjsax @dajac @vvcephei Can you upload the 3.6.1 artifacts to the kafka-packages S3 bucket? Steps are described in https://cwiki.apache.org/confluence/display/KAFKA/Release+Process#ReleaseProcess-Afterthevotepasses

Please also help upload 3.5.2 artifacts. Thank you!

**Comment by mimaison** [comment]
Ping @dajac @mjsax @vvcephei Can you take a look at this? Thanks

**Comment by mjsax** [comment]
Uploaded 3.5.2 and 3.6.1 artifacts.

**Comment by mimaison** [comment]
Thanks @mjsax!
I've added 3.5.2 to this PR as well.

**Review by mjsax — APPROVED** [review]

**Comment by mjsax** [comment]
@mimaison -- should this be cherry-picked to 3.7 branch? -- And the bump to `3.5.2` split out for `3.6` branch?

**Comment by showuon** [comment]
I've backported to 3.7 branch, and created a PR: https://github.com/apache/kafka/pull/15187 to add v3.5.2 into 3.6 branch. Please help review. Thanks.

**Pull request merged**
