### PR TITLE
KAFKA-7673: Upgrade rocksdb to 5.15.10

### PR DESCRIPTION
**Pull request by guozhangwang**
@bbejeck 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Can we run system test for this?

**Review by mjsax — APPROVED** [review]
LGTM.

System tests passed: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2111/

**Review by bbejeck — APPROVED** [review]
LGTM. I upgraded my OS and local tests pass

**Comment by mjsax** [comment]
> I upgraded my OS and local tests pass

@bbejeck @guozhangwang Do we need to be worried about users with older OS?

**Pull request merged**
