### PR TITLE
KAFKA-7895: fix stream-time reckoning for Suppress (2.2)

### PR DESCRIPTION
**Pull request by vvcephei**
* Add suppress to system tests
* Move stream-time reckoning from Task into Processor

Even within a Task, different Processors have different perceptions
of time, due to record caching on stores and in suppression itself,
and in general, due to any processor logic that may hold onto
records arbitrarily and emit them later. Thanks to this, we can't rely
on the whole task existing in the same "instant" of stream-time. The
solution is for each processor node that cares about stream-time to
track it independently.

See also #6278

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Ping @mjsax @bbejeck  for reviews.

This is effectively a cherry-pick of #6278, with the system test changeset adapted not to rely on all the other changes to the smoke test in trunk.

All the main-code changes should be identical to #6278.

**Comment by vvcephei** [comment]
Kicked off system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2355

**Comment by mjsax** [comment]
@vvcephei Jenkins failed with checkstyle errors.

**Comment by vvcephei** [comment]
Goodness... I had to wrestle with the driver a bit, since I didn't backport the test for the driver, and since I'm not able to run the system tests locally.

I got the driver system test to pass:
http://testing.confluent.io/confluent-kafka-branch-builder-system-test-results/?prefix=2019-02-19--001.1550609346--vvcephei--KAFKA-7895-fix-suppress-2.2--face6a8/

Waiting on the full suite of tests:
https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2362/
Done. It looks like just the expected failures:
http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2019-02-19--001.1550636661--vvcephei--KAFKA-7895-fix-suppress-2.2--face6a8/report.html

**Review by mjsax — APPROVED** [review]
LGTM.

Waiting for system tests to finish before merging.

**Review by bbejeck — APPROVED** [review]
LGTM, system test failures (broker upgrade-downgrade) are unrelated and are a known issue

**Comment by vvcephei** [comment]
Thanks, @mjsax and @bbejeck !

The system tests had only expected failures (updated the comment above with the results).

This PR should hopefully cherry-pick cleanly to 2.1...

**Comment by guozhangwang** [comment]
@vvcephei I tried to cherry-pick to 2.1 but did not succeed (@bbejeck cc), because the Segments code has been largely refactored since then. Could you file another PR for 2.1?

**Pull request merged**
