### PR TITLE
docs: Fix upgrade.mode references

### PR DESCRIPTION
**Pull request by hasegeli**
I guess upgrade.from is what is meant.

### CODE REVIEW

**Review by vvcephei — APPROVED** [review]
Yes, I believe you're right.

**Review by andrewchoi5 — APPROVED** [review]

**Comment by chia7712** [comment]
@hasegeli Could you fix the conflicts? I'd like to merge this PR :)

**Comment by chia7712** [comment]
@hasegeli Could you rebase it again? It seems our Jenkins was on vacation :(

**Comment by chia7712** [comment]
@hasegeli Thanks for contribution!

**Pull request merged**
