### PR TITLE
KAFKA-3290: fix transient test failures in WorkerSourceTaskTest

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
@ewencp I never was able to reproduce the failures, but when I ran the tests locally, I saw a bunch of easymock assertions which were getting mistakenly caught by the WorkerTask. I've fixed those in this patch, but I can't be sure that the transient failure won't pop up again.

**Comment by gwenshap** [comment]
I think the expectCall of sourceTask.commit should be inside expectedFlush (At least, I found it easier when tackling the exact same problem: https://github.com/apache/kafka/pull/994)

**Comment by hachikuji** [comment]
Makes sense to me.

**Comment by hachikuji** [comment]
A reasonable question these test failures raise is whether we ought to be catching Exception instead of Throwable in the WorkerTask? The assertion failures are actually instances of Error, which are expected not to be caught by the application.

**Comment by hachikuji** [comment]
@gwenshap Ready for another look. I added code to rethrow instances of Error from WorkerTask. Does that seem reasonable?

**Comment by gwenshap** [comment]
LGTM

**Pull request closed without merging**
