### PR TITLE
MINOR: Fix issue in `AsyncProducerTest` where it expects the `port` config to be set

### PR DESCRIPTION
**Pull request by ijuma**
This test fails locally when I run it, but somehow Jenkins builds are passed. Not clear how.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji

**Comment by hachikuji** [comment]
@ijuma Can you provide some more detail on which test is failing? Everything seems ok when I run locally here. The fix itself looks correct, but I'm a little puzzled why it matters since the test doesn't appear to use the port anywhere.

**Comment by ijuma** [comment]
I get the following failures:

`testNoBroker`:

``` text
  java.lang.AssertionError: Should fail with FailedToSendMessageException

    at org.junit.Assert.fail(Assert.java:88)
    at kafka.producer.AsyncProducerTest.testNoBroker(AsyncProducerTest.scala:306)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

`testFailedSendRetryLogic`

``` text
[2016-10-29 09:37:30,095] ERROR 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0 (kafka.utils.CoreUtils$:108)
java.lang.AssertionError: 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
    at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
    at kafka.producer.ProducerPool$$EnhancerByCGLIB$$1de8c6a7.updateProducer(<generated>)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:99)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$1.apply$mcV$sp(DefaultEventHandler.scala:73)
    at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:79)
    at kafka.utils.Logging$class.swallowError(Logging.scala:108)
    at kafka.utils.CoreUtils$.swallowError(CoreUtils.scala:49)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:73)
    at kafka.producer.AsyncProducerTest.testFailedSendRetryLogic(AsyncProducerTest.scala:433)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[2016-10-29 09:37:30,224] ERROR 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0 (kafka.utils.CoreUtils$:108)
java.lang.AssertionError: 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
    at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
    at kafka.producer.ProducerPool$$EnhancerByCGLIB$$1de8c6a7.updateProducer(<generated>)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:99)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:84)
    at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:79)
    at kafka.utils.Logging$class.swallowError(Logging.scala:108)
    at kafka.utils.CoreUtils$.swallowError(CoreUtils.scala:49)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:84)
    at kafka.producer.AsyncProducerTest.testFailedSendRetryLogic(AsyncProducerTest.scala:433)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[2016-10-29 09:37:30,340] ERROR 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0 (kafka.utils.CoreUtils$:108)
java.lang.AssertionError: 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
    at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
    at kafka.producer.ProducerPool$$EnhancerByCGLIB$$1de8c6a7.updateProducer(<generated>)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:99)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:84)
    at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:79)
    at kafka.utils.Logging$class.swallowError(Logging.scala:108)
    at kafka.utils.CoreUtils$.swallowError(CoreUtils.scala:49)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:84)
    at kafka.producer.AsyncProducerTest.testFailedSendRetryLogic(AsyncProducerTest.scala:433)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[2016-10-29 09:37:30,455] ERROR 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0 (kafka.utils.CoreUtils$:108)
java.lang.AssertionError: 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
    at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
    at kafka.producer.ProducerPool$$EnhancerByCGLIB$$1de8c6a7.updateProducer(<generated>)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:99)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:84)
    at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:79)
    at kafka.utils.Logging$class.swallowError(Logging.scala:108)
    at kafka.utils.CoreUtils$.swallowError(CoreUtils.scala:49)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:84)
    at kafka.producer.AsyncProducerTest.testFailedSendRetryLogic(AsyncProducerTest.scala:433)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[2016-10-29 09:37:30,564] ERROR 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0 (kafka.utils.CoreUtils$:108)
java.lang.AssertionError: 
  Unexpected method call ProducerPool.updateProducer(Vector({TopicMetadata for topic topic1 -> 
Metadata for partition [topic1,0] is    partition 0 leader: BrokerEndPoint(2,localhost,9072)    replicas: BrokerEndPoint(2,localhost,9072)  isr: BrokerEndPoint(2,localhost,9072)   isUnderReplicated: false})):
    ProducerPool.getProducer(0): expected: 4, actual: 0
    ProducerPool.close(): expected: 1, actual: 0
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
    at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
    at kafka.producer.ProducerPool$$EnhancerByCGLIB$$1de8c6a7.updateProducer(<generated>)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:99)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:84)
    at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:79)
    at kafka.utils.Logging$class.swallowError(Logging.scala:108)
    at kafka.utils.CoreUtils$.swallowError(CoreUtils.scala:49)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:84)
    at kafka.producer.AsyncProducerTest.testFailedSendRetryLogic(AsyncProducerTest.scala:433)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[2016-10-29 09:37:30,567] ERROR Failed to send requests for topics topic1 with correlation ids in [0,16] (kafka.producer.async.DefaultEventHandler:99)

kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.

    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:96)
    at kafka.producer.AsyncProducerTest.testFailedSendRetryLogic(AsyncProducerTest.scala:433)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by hachikuji** [comment]
LGTM. I never could reproduce any of the failures, but the fix still seems to make sense.

**Pull request closed without merging**
