### PR TITLE
MINOR: correct the doc of transaction.timeout.ms

### PR DESCRIPTION
**Pull request by chia7712**
```InvalidTxnTimeoutException``` is what produced by broker due to illegal txn timeout.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by abbccdda — APPROVED** [review]
LGTM

**Comment by abbccdda** [comment]
retest this please

**Comment by chia7712** [comment]
```
15:06:25 org.apache.kafka.connect.mirror.MirrorConnectorsIntegrationTest > testReplication FAILED
15:06:25     java.lang.RuntimeException: Could not find enough records. found 0, expected 100
15:06:25         at org.apache.kafka.connect.util.clusters.EmbeddedKafkaCluster.consume(EmbeddedKafkaCluster.java:435)
15:06:25         at org.apache.kafka.connect.mirror.MirrorConnectorsIntegrationTest.testReplication(MirrorConnectorsIntegrationTest.java:222)
```

it is traced by #8894

**Comment by chia7712** [comment]
retest this please

**Pull request merged**
