### PR TITLE
KAFKA-7431 : Clean up connect unit tests

### PR DESCRIPTION
**Pull request by mrsrinivas**
[KAFKA-7431](https://issues.apache.org/jira/browse/KAFKA-7431)

Changes made to improve the code readability:
 - Removed `throws Exception` from the place where there won't be an
 exception
 - Removed type arguments where those can be inferred explicitly by compiler
 - Rewritten Anonymous classes to Java 8 with lambdas

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mrsrinivas** [comment]
@mjsax @junrao @omkreddy @asasvari can you please add your thoughts about this PR?

 - [ ] Should this PR make sense at this time?
 - [ ] Is this correct branch for the code changes?

There can be further improvements also in current and other modules, but I would like add them incrementally.

TIA

**Comment by mrsrinivas** [comment]
@mjsax @junrao @omkreddy @asasvari can you please add your thoughts about this PR? If you get some time.

There can be further improvements also in current and other modules, but I would like add them

**Comment by omkreddy** [comment]
cc @rhauch @kkonstantine

**Comment by mrsrinivas** [comment]
@rhauch @kkonstantine  @omkreddy @asasvari @ijuma @rajinisivaram 

Any feedback on this PR?

**Comment by dbolshak** [comment]
I can not say behalf of kafka contributors, but for me it looks great.

**Comment by soenkeliebau** [comment]
Hi @mrsrinivas ,
thanks for your PR! I've briefly looked it over and have two quick comments - however both of these I think come down more to personal preference than anything else!

Regarding the unused throws clauses, I don't really think these hurt. In fact it could be argued that it is good practice to declare this on any test, since it saves you from having to change the test if the implementing code ever changes and throws an exception. But seeing as the rest of the test cases don't do this either I'd say removing them is fine.

As for the lambda functions, it seems like a lot of code to encapsulate in a lambda function - I personally feel like lambdas should ideally have only one line. Plus you loose the return type, hence your IDE won't alert you if you mess up the return type. Both are no deal breakers, but I'm unsure what we gain by making this a lambda function tbh.

Again, just my personal opinion and really comes down to taste I think.

**Comment by rhauch** [comment]
@mrsrinivas, thanks for the PR!

I agree with @soenkeliebau about the throws clauses: removing `throws Exception` where truly not needed seems acceptable, though they don't really bother me as they're pretty minor.

I do question whether it's necessary to change the code from using anonymous inner classes to lambdas in the tests, for a couple of reasons. First, it's a minor change that affects multiple lines, making it more difficult to see the real changes that were made in that block of code. Second and more importantly, these changes may make it harder for the committer to more cleanly backport future fixes to older branches. Remember, we only started using Java 8 in 2.0, so backporting to earlier branches doesn't allow lambdas. 

I'd love to hear what a committer thinks about moving to lambdas, and whether my concerns are warranted.

**Comment by ijuma** [comment]
@rhauch We've been doing the lambda changes in `clients`. Generally, people want to move forward and use an improved programming model and preventing that in the name of backports is a bit hard.

**Comment by mrsrinivas** [comment]
@rhauch, Thanks for the review!! 

> 
> I agree with @soenkeliebau about the throws clauses: removing `throws Exception` where truly not needed seems acceptable, though they don't really bother me as they're pretty minor.
> 
I am under the impression that removing some dead code improves the readability for other contributors.

> I do question whether it's necessary to change the code from using anonymous inner classes to lambdas in the tests, for a couple of reasons. First, it's a minor change that affects multiple lines, making it more difficult to see the real changes that were made in that block of code. Second and more importantly, these changes may make it harder for the committer to more cleanly backport future fixes to older branches. Remember, we only started using Java 8 in 2.0, so backporting to earlier branches doesn't allow lambdas.
> 
That's good point about back-porting. I made these changes to make use of available JDK 8 compiler features effectively. yeah, it's trade off between taking latest features and extra effort while making code changes for older Java 7 branches.

> I'd love to hear what a committer thinks about moving to lambdas, and whether my concerns are warranted.
>

**Comment by mrsrinivas** [comment]
> Hi @mrsrinivas ,
> thanks for your PR! I've briefly looked it over and have two quick comments - however both of these I think come down more to personal preference than anything else!
> 
@soenkeliebau, Thanks for the feedback. 

> Regarding the unused throws clauses, I don't really think these hurt. In fact it could be argued that it is good practice to declare this on any test, since it saves you from having to change the test if the implementing code ever changes and throws an exception. But seeing as the rest of the test cases don't do this either I'd say removing them is fine.
> 
My motivation this changes, I was told by my seniors
> code base should look like single person written it. 

I have seen other unit tests and found inconsistent on unused `throws`. So, I thought of removing unused is better than adding for all. These days IDEs are so smart to alert developer to declare `throws` if the code change will throw an exception.

> As for the lambda functions, it seems like a lot of code to encapsulate in a lambda function - I personally feel like lambdas should ideally have only one line. Plus you loose the return type, hence your IDE won't alert you if you mess up the return type. Both are no deal breakers, but I'm unsure what we gain by making this a lambda function tbh.
> 
Yes, I do feel lambda should be one line. But sometimes it's hard for us to express in one line. 

Return type mismatch alert :-  I made the code changes in latest commit to address the point. I verified in IntelliJ and it alerts me on return type miss match with latest code changes I made.

> Again, just my personal opinion and really comes down to taste I think.

**Review by ryannedolan — APPROVED** [review]
lgtm

**Review by rhauch — APPROVED** [review]
@mrsrinivas thanks again for this PR. I spoke with a committer (@ewencp), who suggested that it's fine to make these kinds of changes and to not worry much about backporting. Given that was my only concern, so approving since the cleanup is a good change overall.

**Review by ijuma — APPROVED** [review]
LGTM, thanks for the PR.

**Comment by mrsrinivas** [comment]
@ewencp @ijuma, anything pending to get this PR merged?

Thanks.

**Comment by mrsrinivas** [comment]
retest

**Comment by mrsrinivas** [comment]
retest this please

**Review by ewencp — APPROVED** [review]
LGTM, thanks for the patch!

**Pull request closed without merging**
