### PR TITLE
MINOR: Skip fsync on parent directory to start Kafka on ZOS

### PR DESCRIPTION
**Pull request by hongyiz6639**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by hongyiz6639** [comment]
@ccding @junrao , please help review the PR. Thank you.

**Comment by ccding** [comment]
@zshuo can you help to have a look at this since you worked on https://github.com/apache/kafka/commit/62b2eac4e1a97e6d77bc57f9100bf22a2f364178?

**Review by ccding — APPROVED** [review]

**Review by junrao — APPROVED** [review]
@hongyiz6639 : Thanks for the PR. LGTM. Are the test failures related to this PR?

**Comment by hongyiz6639** [comment]
> @hongyiz6639 : Thanks for the PR. LGTM. Are the test failures related to this PR?

@junrao Thanks for your reply. All test failures are not related with this PR.

**Pull request merged**
