### PR TITLE
KAFKA-16660: reduce the check interval to speedup DelegationTokenRequestsTest

### PR DESCRIPTION
**Pull request by brandboat**
related to https://issues.apache.org/jira/browse/KAFKA-16660

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by brandboat** [comment]
Loop 131 times and all passed `I=0; while ./gradlew core:test --tests DelegationTokenRequestsTest --rerun --fail-fast; do (( I=$I+1 )); echo "Completed run: $I"; sleep 1; done`. But let's see if there is any surprise in jenkins.

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
**before** 16mins
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/view/change-requests/job/PR-15891/5/testReport/kafka.server/DelegationTokenRequestsTest/

**after** 1min 40s
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-15907/1/testReport/kafka.server/DelegationTokenRequestsTest/

**Comment by showuon** [comment]
Thanks for the improvement!

**Comment by brandboat** [comment]
Thanks @chia7712, @showuon , We've shortened CI runtime even more.

**Pull request merged**
