### PR TITLE
MINOR: Use ObjectName.quote instead of URL-encoding for JMX metric tags

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by rajinisivaram** [comment]
@ewencp @ijuma Can you review please? Thank you!

**Comment by rajinisivaram** [comment]
This will fix the issue with ipv6 addresses appearing encoded in JMX. There is also a bug in the current code which encodes user principals twice when registering to JMX (since they are already encoded in the metric). That is fixed by this PR by not quoting URL-encoded tags.

**Review by ewencp — APPROVED** [review]
LGTM, and thanks for the suggestion, I like this solution a lot better.

**Comment by ijuma** [comment]
@ewencp if you're happy, feel free to merge as @rajinisivaram is probably out for the day.

**Comment by ewencp** [comment]
Merged to 1.0 and trunk. @rajinisivaram since this PR was targeted at 1.0 you'll have to close the PR.

**Comment by ewencp** [comment]
huh, that's confusing, I thought asfbot couldn't close non-trunk PRs, but I guess the key thing is whether the commit ended up on trunk and not the target branch of the PR.

**Comment by ijuma** [comment]
Yes, that's correct.

**Pull request closed without merging**
