### PR TITLE
MINOR: Typo error corrected in the KStream Javadoc.

### PR DESCRIPTION
**Pull request by kamalcph**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6026/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6011/
Test FAILed (JDK 8 and Scala 2.12).

**Review by mjsax — APPROVED** [review]
LGTM.

Thanks for the patch!

Call for merging @guozhangwang @dguy

**Comment by mjsax** [comment]
Retest this please.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6031/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6016/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by kamalcph** [comment]
Thanks for the review @mjsax.

I have a doubt in the example provided for the `outerJoin` in the java-doc,  Could you please explain,

how the result of the `K2:ValueJoiner(null, b)` came if `<K2:B>` and `<K2:b>` belong to the correct windows ?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6039/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6024/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by mjsax** [comment]
We will process one record after the other. Thus, in this example we assume that `<K2:b>` is processed first. Thus, `<K2:B>` is not there yet and we get `ValueJoiner(null, b)`. Afterwards, `<K2,B>` is processed and it will join with `<K2:b>`. The point is, that we don't delay the processing of any records. The result could also be `ValueJoiner(B, null)` + `ValueJoiner(B,b)` if `<K2,B>` is processed before `<K2:b>`

Does this make sense?

**Comment by kamalcph** [comment]
Yes, it is. Thanks for the explanation.

**Review by dguy — APPROVED** [review]
Thanks @Kamal15, LGTM

**Pull request closed without merging**
