### PR TITLE
kafka 3355

### PR DESCRIPTION
**Pull request by mgarmes**

### CODE REVIEW

**Comment by ppanero** [comment]
Thanks a lot @garmes-gdev. Will take a look :D

**Comment by mgarmes** [comment]
Hello @ijuma , can you or someone check this pull request please ?

**Comment by ppanero** [comment]
Anyone could check and merge this please? would be really helpful

**Comment by ppanero** [comment]
@garmes-gdev  could u assign it to someone?

**Comment by mgarmes** [comment]
Hello, @guozhangwang, @dguy  
can you please review this PR.

Bests,

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5871/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5886/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by guozhangwang** [comment]
cc @hachikuji @rajinisivaram , is this still a valid issue?

**Comment by hachikuji** [comment]
@guozhangwang Yes, it is still an issue. Frankly, we have not been maintaining this tool, so we need to figure out if we want to officially deprecate it or try to bring it up to speed. If there was an alternative, I'd suggest deprecation, but I'm not sure we have one. If we want to maintain this, I think we'd probably want a KIP to, at a minimum, migrate the code to use the new AdminClient. Even better would be to address where this functionality should live in the longer term.

**Comment by ijuma** [comment]
Thanks for the PR and sorry for the delay. #3051 seems to build on public APIs in the consumer, which seems like a better avenue. I will try to include a reduced version of that in 2.0.0 and we can follow-up with a KIP for adding functionality.

**Comment by ijuma** [comment]
I submitted https://github.com/apache/kafka/pull/5220 and included the submitter as a co-author.

**Pull request closed without merging**
