### PR TITLE
MINOR: Add note about which files need to be edited when updating the version number

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
Follow up from https://github.com/apache/kafka/pull/878

**Comment by ijuma** [comment]
LGTM. An observation: after we branch we no longer want to update `kafka-merge-pr.py`.

**Comment by ewencp** [comment]
Hmm, at first I wasn't sure about that since you can still have multiple versions on the branch, but actually we should maybe even remove the file entirely so you can't accidentally commit from the wrong branch using the wrong default values...

**Comment by ijuma** [comment]
Agreed, it only makes sense for that tool to be used from trunk.

**Comment by ijuma** [comment]
Cc @gwenshap

**Pull request closed without merging**
