### PR TITLE
MINOR: Reuse hasDefault instead of comparing with NO_DEFAULT_VALUE directly

### PR DESCRIPTION
**Pull request by wuYin**
Always use the `hasDefault` method to check if the default value is specified in `ConfigKey` object

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by showuon — COMMENTED** [review]
@wuYin , thanks for the PR. I saw there's also a line using the `NO_DEFAULT_VALUE` value. 
In ConfigKey constructor:
`this.defaultValue = NO_DEFAULT_VALUE.equals(defaultValue) ? NO_DEFAULT_VALUE : parseType(name, defaultValue, type);`
We could replace with `hasDefault() ? ....`

Thanks.

**Comment by wuYin** [comment]
@showuon Thanks for reply
This small change is mainly to unify the way to determine if the user has set the default value, both ways are used currently:
- [ConfigDef.java#L1183](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java#L1183)
- [ConfigDef.java#L595](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java#L595)

I think the code may be more cleaner by using `hasDefault()` uniformly.
Thank you for review.

**Comment by showuon** [comment]
@wuYin 

> This small change is mainly to unify the way to determine if the user has set the default value

Yes, I know, so I think this line should also be updated.
https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java#L1146

```
NO_DEFAULT_VALUE.equals(defaultValue) ? NO_DEFAULT_VALUE : parseType(name, defaultValue, type);
```
It is also trying to determine if the default value is set, so, we can update to:
```
hasDefault() ?  parseType(name, defaultValue, type) : NO_DEFAULT_VALUE;
```

What do you think?

**Comment by wuYin** [comment]
@showuon 
Thank you for patient explanation, I added this.
Now `NO_DEFAULT_VALUE` is no longer used for direct comparison.

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the PR!

**Comment by mimaison** [comment]
This is a nice cleanup. @wuYin if you rebase to resolve the conflict, we should accept and merge this PR.

**Pull request closed without merging**
