### PR TITLE
MINOR: Remove unused params in ZkConfigManager

### PR DESCRIPTION
**Pull request by ruanwenjun**
* Remove changeExpirationMs and time in ZkConfigManager, since this two params is not used.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by hachikuji** [comment]
@ruanwenjun Thanks for the patch. One minor import to fix:
```
[2022-02-15T12ː00ː59.047Z] [Error] /home/jenkins/workspace/Kafka_kafka-pr_PR-11763/core/src/main/scala/kafka/server/ZkConfigManager.scalaː28ː38: Unused import
```

**Comment by ruanwenjun** [comment]
@hachikuji Thanks for your review. I have removed the unused import. Now, it should pass the `checkstyle` task.

By the way, how can I control the import order of kafka project? I read the [developer setup doc](https://cwiki.apache.org/confluence/display/KAFKA/Developer+Setup), there is no description of how to manage the code  format.

I find the `checkstyle.xml` and import this file into my IDEA, but it doesn't manage the import order. Furthermore, I just find the `ImportControl` referenced to another file.

**Review by hachikuji — APPROVED** [review]
Thanks for the patch! LGTM.

**Comment by hachikuji** [comment]
@ruanwenjun To be honest, I don't think we have official guidelines on import ordering. The only style enforcement I'm aware of is avoiding `*` imports in the Java code. If you know of any way to enforce an ordering convention, I'd suggest opening a PR to get feedback from other developers. You could also ask on the dev list perhaps. It would definitely be nice to de-clutter PRs from a lot of the noise from import reordering.

**Pull request merged**
