### PR TITLE
MINOR: Add 2.0, 2.1 and 2.2 to broker and client compat tests

### PR DESCRIPTION
**Pull request by ijuma**
These are important to ensure we don't break compatibility.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
System tests run for all tests updated in this PR:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2622/console

**Comment by ijuma** [comment]
System tests passed. PR validation is green too.

**Review by gwenshap — APPROVED** [review]
LGTM. Merging.

**Comment by ijuma** [comment]
Thanks! Cherry-picked it to 2.3 branch.

**Pull request closed without merging**
