### PR TITLE
KAFKA-7068 : KIP-297 : Handle null config values during transform

### PR DESCRIPTION
**Pull request by rayokota**
Fix NPE when processing null config values during transform.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mageshn — APPROVED** [review]
LGTM. Thanks @rayokota

**Comment by rayokota** [comment]
retest this please

**Comment by mageshn** [comment]
@rayokota you  might want to associate the issue KAFKA-7068 to the PR

**Review by ewencp — APPROVED** [review]
LGTM, merging to trunk and 2.0

**Pull request closed without merging**
