### PR TITLE
MINOR: KIP-848 Uniform Assignor Bugs

### PR DESCRIPTION
**Pull request by rreddy-22**
Minor: Found potential NullPointerException possibilities during testing. Corrected them and added tests for the same.
This was found when testing a large number of members that exist and are assigned all the partitions of a topic, a new member is added and there are no more partitions available to assign, the target assignment remains empty.

### CODE REVIEW

**Comment by dajac** [comment]
Thanks @rreddy-22! Could you please describe the bug(s) in the description? Do we need to add new tests for them?

**Comment by rreddy-22** [comment]
This PR is still under construction, I wanna combine all the bugs and then I'll add the description and lyk when it's ready for review!

**Comment by dajac** [comment]
@rreddy-22 Understood. In this case, it would be better to mark it as draft.

**Comment by dajac** [comment]
@rreddy-22 Do we still need this one?

**Comment by dajac** [comment]
This does not seem necessary any more. Closing it.

**Pull request closed without merging**
