### PR TITLE
MINOR: Ensure that selection key is cancelled on close

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR, LGTM.

**Comment by ijuma** [comment]
@rajinisivaram, one thing I was wondering is that we don't propagate the exception in `SslTransportLayer`, but we do in `PlaintextTransportLayer`. Thoughts?

**Comment by ijuma** [comment]
Also, in `KafkaChannel.close()`, we don't close the authenticator if the transport layer throws an exception, which also looks like a bug.

**Comment by ijuma** [comment]
Maybe we could handle both issues in another PR?

**Comment by rajinisivaram** [comment]
@ijuma Thank you for merging so quickly! Yes, I will submit another PR to fix the two issues you mentioned.

**Pull request closed without merging**
