### PR TITLE
MINOR: Fixed the invalid link to Log Compaction

### PR DESCRIPTION
**Pull request by kamalcph**
- variable name updated in the doc example.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5822/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5836/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
cc @dguy

**Comment by kamalcph** [comment]
closing this one, as the changes are invalid.

**Pull request closed without merging**
