### PR TITLE
MINOR: clarify the record selection algorithm and stream-time definition

### PR DESCRIPTION
**Pull request by vvcephei**
The existing javadoc for PartitionGroup is a little confusing.
It's relatively important for these concepts to be clear, since
they form the basis for stream-time in Kafka Streams.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@guozhangwang @bbejeck @mjsax, Can you take a look at this small PR if you get the chance?

Thanks,
-John

**Comment by vvcephei** [comment]
Hmm, this is weird in the java 8 build:
```
> Task :core:compileTestScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
/home/jenkins/jenkins-slave/workspace/kafka-pr-jdk8-scala2.11/core/src/test/scala/unit/kafka/utils/CommandLineUtilsTest.scala:131: illegal start of simple expression
    )
    ^
/home/jenkins/jenkins-slave/workspace/kafka-pr-jdk8-scala2.11/core/src/test/scala/unit/kafka/utils/CommandLineUtilsTest.scala:146: ')' expected but '}' found.
  }
  ^
/home/jenkins/jenkins-slave/workspace/kafka-pr-jdk8-scala2.11/core/src/test/scala/unit/kafka/utils/CommandLineUtilsTest.scala:162: illegal start of simple expression
    )
    ^
/home/jenkins/jenkins-slave/workspace/kafka-pr-jdk8-scala2.11/core/src/test/scala/unit/kafka/utils/CommandLineUtilsTest.scala:173: ')' expected but '}' found.
  }
  ^
four errors found

> Task :core:compileTestScala FAILED
```

**Comment by guozhangwang** [comment]
@vvcephei I ran locally on your branch (on top of trunk) and did not see this?

**Comment by guozhangwang** [comment]
retest this please

**Review by mjsax — APPROVED** [review]
LGTM.

**Comment by mjsax** [comment]
Test failure unrelated. Retest this please.

**Pull request merged**
