### PR TITLE
KAFKA-5503 Idempotent producer ignores shutdown while fetching Produc…

### PR DESCRIPTION
**Pull request by layfe**
…erId

Check running in `Sender.maybeWaitForProducerId`

### CODE REVIEW

**Comment by dhruvilshah3** [comment]
Retest this please

**Comment by stanislavkozlovski** [comment]
retest this please

**Comment by ewencp** [comment]
@layfe please stop closing and reopening this, it creates notification spam in JIRA. you can use the phrase retest this please to have Jenkins trigger the test again.

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Comment by layfe** [comment]
retest this please

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch. Due to long review delay and because this is a trivial fix, I will open a separate issue to add a test case.

**Comment by hachikuji** [comment]
retest this please

**Comment by hachikuji** [comment]
I opened https://issues.apache.org/jira/browse/KAFKA-7783 to address the testing gaps. I will go ahead and merge this PR.

**Pull request merged**
