### PR TITLE
MINOR: Turn off caching in demos for more understandable outputs

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@dguy @miguno @mjsax @bbejeck 

This needs to go to 0.10.1 and 0.10.2 as well since caching is introduced in 0.10.1.

**Review by mjsax — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5575/
Test PASSed (JDK 8 and Scala 2.12).

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5589/
Test PASSed (JDK 7 and Scala 2.11).

**Review by dguy — APPROVED** [review]
LGTM

**Comment by dguy** [comment]
@guozhangwang merged to trunk and cherry-picked to 0.11.0. Cherry pick failed on 0.10.2

**Pull request closed without merging**
