### PR TITLE
MINOR: Make it impossible to invoke `Request.body` without an explicit type parameter

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji, cc @ewencp and @cmccabe.

**Review by hachikuji — APPROVED** [review]
LGTM. A bit unfortunate we have to go to this extra trouble to get the types to work. I guess the payoff over the normal typecast is that we get the nice exception message.

**Comment by ijuma** [comment]
Yes, this is annoying. The other advantages of this approach is that the types you can pass are restricted to AbstractRequest and subclasses. `asInstanceOf` in Scala is really unsafe and you can cast to anything. It's also a little more concise.

**Comment by hachikuji** [comment]
Yes, I agree that being able to restrict the possible cast types is beneficial.

**Pull request closed without merging**
