### PR TITLE
KAFKA-2236; Offset request reply racing with segment rolling

### PR DESCRIPTION
**Pull request by jhspaybar**

### CODE REVIEW

**Comment by ijuma** [comment]
@jhspaybar, we are testing contributions via GitHub, but it's not the official way yet. See https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes for the proposed approach.

**Comment by jhspaybar** [comment]
@ijuma I've added the github link to the jira issue, but I don't see how to change the status to patch available.  Other than that I think I've hit the directions on the contributing page that you linked.

**Comment by ijuma** [comment]
@jhspaybar, according to the guidelines, the PR title should be:

`KAFKA-2236; Offset request reply racing with segment rolling`

You can use different text than the JIRA title if it represents the issue better, but the JIRA id must come first followed by a semi-colon.

Also, the PR text is included in the squashed commit, so it's better not to have the paragraph about the mechanics of the contribution.

Note that both the title and PR text can be edited without having to resubmit.

Finally, regarding the change, it looks good to me (based on the comments in the JIRA) aside from the tests issue. I don't know how easy it is to test this, but maybe someone else can help.

**Comment by jhspaybar** [comment]
@ijuma sorry for the delay, and thanks for the help!  I didn't change the variable name since I'm calling size rather than nonEmpty, but I did remove my PR text and changed the title.

**Comment by MicahZoltu** [comment]
@jhspaybar I'm running into this problem with my Integration tests, which randomly fail because of it.

Why was this PR closed?  Is there another PR that addresses this issue?  A spot check suggests that this problem still exists on trunk, 0.8.2 and 0.9 branches.  Is there a workaround?

**Comment by jhspaybar** [comment]
I closed it because I no longer had the desire to follow up and try to get this merged. Feel free to pick it back up and/or reopen. It was listed as a newbie bug to fix, but adding tests to it seemed pretty intense so I left it.

**Comment by ijuma** [comment]
@jhspaybar, I agree that it's pretty tricky to write a test for this race condition. Given that the fix is simple and clearly correct, I have created a PR with your fix: https://github.com/apache/kafka/pull/1318. The merged commit will have you as the author. Thanks!

**Pull request closed without merging**
