### PR TITLE
MINOR: ConsumerRebalanceListenerInvoker class and method visibility

### PR DESCRIPTION
**Pull request by kirktrue**
For forthcoming changes, make this class and its methods public for use outside the package. Also fix a minor logging issue to include the object in the log, not its `Optional` wrapper.

### CODE REVIEW

**Comment by kirktrue** [comment]
@dajac This is the shared bit pulled out from #14640 as you'd requested.

**Comment by kirktrue** [comment]
@philipnee can you add the `ctr` and `KIP-848` tags, please?

**Review by dajac — APPROVED** [review]
LGTM, thanks.

**Comment by kirktrue** [comment]
Three yellows, one red. Restarting 🤞

**Comment by kirktrue** [comment]
Four greys. Restarting build again.

**Comment by kirktrue** [comment]
@dajac—failing tests appear unrelated. Do we need four green builds before merging?

**Pull request merged**
