### PR TITLE
KAFKA-4222: Adjust timeout in low resource environments

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
This other PR is also needed of course: https://github.com/apache/kafka/pull/2982

**Comment by mjsax** [comment]
@enothereska Can you elaborate in this PR. With #2982 I am wondering why we need this?

**Comment by enothereska** [comment]
@mjsax yes, I tested all the streams test in an ultra-low resource environment (1 wimpy core, 1GB of RAM) and even with the RocksDB fix the queryOnRebalance test would fail. Sometimes the network would appear flaky, requiring more retries (I've changed to 10). Sometimes the rebalance would take forever, requiring new timeouts.

**Comment by enothereska** [comment]
cc @guozhangwang

**Comment by guozhangwang** [comment]
@eno I'm still wondering why the rebalance could take forever, since we only have a single thread that will own all the tasks, and it has graceful shutdown / re-start so there should be no restoration at all?

**Comment by enothereska** [comment]
In a low resource env, everything competes for a bit of resources, the producer thread, the main streams thread and the rebalancing. It all crawls.

**Comment by guozhangwang** [comment]
> In a low resource env, everything competes for a bit of resources, the producer thread, the main streams thread and the rebalancing. It all crawls.

@enothereska Okay, I think I'm a bit over-concerned with your description that `rebalance take forever` since it is only a single thread, so if it really take very long to create tasks / restore it would be a problem.

**Review by guozhangwang — APPROVED** [review]
Merged to trunk.

**Pull request closed without merging**
