### PR TITLE
MINOR: Add last modified time and deletion horizon to clear log message

### PR DESCRIPTION
**Pull request by hachikuji**
It's useful to know when the cleaner runs what the last modified time
of the segment and the deletion horizon is. The current log message
only allows you to infer that one is greater than the other.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ConcurrencyPractitioner** [comment]
@hachikuji Do you think that we could combine this with the PR I'm working on? It should be the one below:
https://github.com/apache/kafka/pull/7175/files

**Review by junrao — APPROVED** [review]
@hachikuji : Thanks for the PR. LGTM

**Comment by hachikuji** [comment]
@ConcurrencyPractitioner It's a small logging change which will improve visibility in the near term, so I'm going to go ahead and merge. I did have a chance to look at KIP-515. I left a comment in the discussion thread. Can you please take a look?

**Comment by ConcurrencyPractitioner** [comment]
Sure, no problem.

**Pull request merged**
