### PR TITLE
KAFKA-4276: Add REST configuration in connector properties

### PR DESCRIPTION
**Pull request by akhilesh1194**
Addition of REST configuration in connect-distributed.properties config file
@gwenshap @ewencp - Please review.

### CODE REVIEW

**Comment by akhilesh1194** [comment]
retest this please

**Comment by akhilesh1194** [comment]
retest this please

**Comment by akhilesh1194** [comment]
Addition of REST configuration in connect-distributed.properties config file
@gwenshap @ewencp - Please review.

**Comment by gwenshap** [comment]
LGTM

**Comment by gwenshap** [comment]
Thank you for contributing :)

**Pull request closed without merging**
