### PR TITLE
KAFKA-8698 : Updated documentation to remove typo error.

### PR DESCRIPTION
**Pull request by asutosh936**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mimaison — APPROVED** [review]
Good catch. LGTM

**Comment by asutosh936** [comment]
Can someone please merge this PR?

**Comment by asutosh936** [comment]
@mimaison - could You please merge this PR?

**Comment by mimaison** [comment]
@asutosh936 I'm not a committer so I cannot merge your PR.

@vahidhashemian @omkreddy can you take a look?

**Review by omkreddy — APPROVED** [review]
@asutosh936 Thanks for the PR. LGTM.

**Comment by omkreddy** [comment]
retest this please

**Comment by vahidhashemian** [comment]
I understand that this is a typo fix, but would it also count as a protocol change?

**Comment by omkreddy** [comment]
> I understand that this is a typo fix, but would it also count as a protocol change?

@vahidhashemian  yeah, but this change got introduced in  2.1.0.  so we may want to fix this.

cc @hachikuji

**Comment by mimaison** [comment]
I believe it's the same as a fix I did a while back, see https://github.com/apache/kafka/pull/4847#issuecomment-381097556

**Review by hachikuji — APPROVED** [review]
The field names are not really part of the protocol: they are just keys that are used to facilitate serialization. I think it still make sense to fix this though.

**Review by vahidhashemian — APPROVED** [review]

**Comment by vahidhashemian** [comment]
retest this please

**Comment by asutosh936** [comment]
@vahidhashemian - sorry but could You please help me in how I should retest? The jenkins builds are failing with different error.

**Comment by vahidhashemian** [comment]
@asutosh936 The comment `retest this please` re-triggers it. I already did that above. Hopefully they'll pass this time.

**Comment by omkreddy** [comment]
JDK 11/2.12 build passed.  JDK 11/2.13 failed with unrelated test failures.  Merging to master.

**Pull request closed without merging**
