### PR TITLE
MINOR: Revert assertion in MockProducerTest

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
In #9955 I made a mistake,  !A && !B = ! (A || B), thank @g1geordie  for pointing out my mistake.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
@dajac Hi, David, Sorry for my carelessness, please take a look.

**Comment by dajac** [comment]
@dengziming Thanks. I missed this one. It might be better to revert to the previous version of the assertion in this case.

**Comment by dengziming** [comment]
@dajac , You are right, the previous version of the assertion is more understandable.

**Review by dajac — APPROVED** [review]
LGTM, thanks for the fix. I’ll merge when tests are completed.

**Pull request merged**
