### PR TITLE
KAFKA-8107:Flaky Test kafka.api.ClientIdQuotaTest.testQuotaOverrideDe…

### PR DESCRIPTION
**Pull request by huxihx**
…lete

https://issues.apache.org/jira/browse/KAFKA-8107

`removeQuotaOverrides` should await some time to ensure entity cnofig takes effect in ZooKeeper.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by abbccdda — COMMENTED** [review]
Thanks for the fix! Do we already have some verification on local, such like 1000+ run without failure?

**Comment by huxihx** [comment]
retest this please.

**Comment by huxihx** [comment]
@abbccdda Thanks for the response. I did a local test with 100 runs in a row and got no failure.

**Comment by huxihx** [comment]
retest this please.

**Comment by huxihx** [comment]
retest this please.

**Comment by dajac** [comment]
This one has been fixed by https://github.com/apache/kafka/pull/8394. We can close this one.

**Comment by dajac** [comment]
Closing as this has been fixed by https://github.com/apache/kafka/pull/8394.

**Pull request closed without merging**
