### PR TITLE
KAFKA-2613: Make maxParallelForks configurable via Gradle config so it can be turned down on shared build infrastructure.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ijuma** [comment]
The change looks good. Did you test that the number of processes corresponds to the value passed via the property?

**Comment by ewencp** [comment]
Yes, just did a manual check with `ps` and a bit of `grep` and `wc`. Was at 8 when I ran without the flag, dropped to the target number with the flag.

**Comment by ijuma** [comment]
Sounds good.

**Comment by harshach** [comment]
+1

**Comment by gwenshap** [comment]
Merged. @harshach, just a reminder that you have a commit bit - so if you can +1 something you can also merge :)

**Pull request closed without merging**
