### PR TITLE
KAFKA-4929: Transformation Key/Value type references should be to class name(), not canonicalName()

### PR DESCRIPTION
**Pull request by bruce-szalwinski**
Changing getCanonicalName() references to getName() so that docs update with "$" instead of ".".  Also added a connect-plugin-discovery.sh CLI to list all of the transformations available.

### CODE REVIEW

**Comment by guozhangwang** [comment]
cc @gwenshap

**Comment by gwenshap** [comment]
Huge props for making the error message and doc output include the right description. Current situation is very misleading.

Few comments:
1. The new CLI is exposing what looks to me like an internal method to users. I'm all pro helping discovery, but this may need a mailing list discussion / vote. @ewencp?
2. It will be nice to add few words about the new CLI to docs/connect.html. There's currently literally no description on what this does, how to use it, etc.
3. Can you post a sample output of the log messages in the JIRA, so people can see "before/after"?

Other than that, the change looks small and safe so +1, pending the possible short KIP for the new CLI and adding the docs. I'll also be happy to get this in if you remove the CLI and submit it in separate PR since it may require additional process. We can fix the errors faster this way.

**Comment by bruce-szalwinski** [comment]
Thanks.  The SMTs are pretty cool.  I've removed the connect-plugin-discovery.sh from this PR.

**Comment by gwenshap** [comment]
Tested by generating the docs. LGTM. Thank you for fixing this.

**Pull request closed without merging**
