### PR TITLE
MINOR: Add missing @Override annotation and simplify Thread declarations with lambdas

### PR DESCRIPTION
**Pull request by 17hao**
Maybe it will improve the readability if `@Override` annotation is applied over the `run()` method since `Sender` class implements `Runnable`.

### CODE REVIEW

**Review by rondagostino — COMMENTED** [review]
Thanks for the PR.  Can you add the annotation everywhere it is missing?  For example:

VerifiableConsumer.java
Metrics.java (ExpireSensorTask)
MetricsTest.java
Microbenchmarks.java
NioEchoServer.java
RecordSendTest.java
RecordAccumulatorTest.java

**Comment by 17hao** [comment]
Hi @rondagostino, I add the annotation in 5 files.  
- Sender.java
- Metrics.java
- BufferPoolTest.java
- MetricsTest.java
- NioEchoServer.java

Some classes you mentioned are not missing `@Override`. With the help of IDEA, I checked all classes implements `Runnable` and found 5 java files missing annotation.

**Review by kkonstantine — COMMENTED** [review]
Thanks for the fix @17hao !

Finally, how about adding the ones missing from the `Thread` implementations too in: 
`clients/src/test/java/org/apache/kafka/clients/producer/internals/BufferPoolTest.java`
and (why not) a last one in a javadoc snippet?  
`clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java`

The command I used was: 
`for i in $(git grep -l "Runnable\|Thread ()"); do grep -H -B 1 "public void run()" $i ; done | less`

(but I agree that code inspection in Intellij is preferable for a first pass)
Hopefully there are no other real ones missing.

**Comment by 17hao** [comment]
Hi @kkonstantine , I think using lambda expression in `BufferPoolTest.java` would be a better solution than adding `@Override` in anonymous classes.  How do you think so?
(Your command is great to use)

**Comment by kkonstantine** [comment]
Thanks for the additional changes @17hao 

Modernizing these use cases with lambdas is fine. One thing of course to keep in mind is whether the extra diff, and its implied cost in backporting or maintaining across different versions, is worth it for stylistic only changes. 
The stakes are low for `BufferPoolTest` so 👍

**Comment by kkonstantine** [comment]
Ok to test

**Comment by 17hao** [comment]
Thanks for your advice @kkonstantine . You are right, we must be careful when maintaining multi-version project.
The failed test relates to https://issues.apache.org/jira/browse/KAFKA-7965

**Comment by kkonstantine** [comment]
retest this please

**Review by kkonstantine — APPROVED** [review]
LGTM!
Thanks for the improvements @17hao !

The build failed twice at a couple known flaky tests. Merging _as is_ to `trunk`

**Pull request merged**
