### PR TITLE
KAFKA-5603: Don't abort TX for zombie tasks

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @enothereska @bbejeck @dguy @guozhangwang

**Comment by mjsax** [comment]
Guess, I need to open second PR for 0.11 -- need to discuss if this should go into `trunk` in the first place... Please share your thoughts.

**Comment by guozhangwang** [comment]
Should we really do this in trunk? I thought we are only doing it for 0.11.0 and rely on KAFKA-5602 for trunk.

**Comment by mjsax** [comment]
> need to discuss if this should go into trunk in the first place... Please share your thoughts.

Btw: If it does not go into `trunk` we need to catch `ProducerFencedException` in `StreamTask#closeSuspended()`  a second time, when calling `recordCollector.close();`. (cf. https://github.com/apache/kafka/pull/3719/files#diff-f1f98a92fd97ac1290e04045f45168e4R433)

I did open a PR for 0.11 already (-> #3722)

**Comment by dguy** [comment]
@guozhangwang KAFKA-5602? that doesn't look related

**Comment by guozhangwang** [comment]
> @guozhangwang KAFKA-5602? that doesn't look related

KAFKA-5604, sorry.

**Comment by mjsax** [comment]
@guozhangwang As discussed, this fix should go into `trunk` to get it for 1.0.0 release. We might want to simplify the code, after the producer bug gets fixed. I'll create another JIRA for this.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk

**Pull request closed without merging**
