### PR TITLE
MINOR: Fix incorrect log for out-of-order KTable

### PR DESCRIPTION
**Pull request by tchiotludo**

### CODE REVIEW

**Review by showuon — APPROVED** [review]
Nice catch! Thanks for the fix.

**Comment by showuon** [comment]
@tchiotludo , there is test failed due to this change. Please help fix it.
```
org.apache.kafka.streams.kstream.internals.KTableSourceTest.kTableShouldLogOnOutOfOrder
```

Thanks.

**Comment by tchiotludo** [comment]
@showuon must be done I think ;)

**Comment by showuon** [comment]
Failed tests are unrelated:
```
    Build / JDK 17 and Scala 2.13 / kafka.server.LogDirFailureTest.testReplicaFetcherThreadAfterLogDirFailureOnFollower()
    Build / JDK 8 and Scala 2.12 / org.apache.kafka.connect.integration.SourceConnectorsIntegrationTest.testSwitchingToTopicCreationEnabled
    Build / JDK 8 and Scala 2.12 / org.apache.kafka.streams.integration.PurgeRepartitionTopicIntegrationTest.shouldRestoreState

```

**Comment by showuon** [comment]
@tchiotludo , thanks for your contribution!

**Pull request merged**
