### PR TITLE
MINOR: Restore `SslConsumerTest` which was accidentally deleted in client-side assignment commit

### PR DESCRIPTION
**Pull request by ijuma**
Probably happened while resolving conflicts, commit: 86eb74d9236c586af5889fe79f4b9e066c9c2af3

### CODE REVIEW

**Comment by ijuma** [comment]
cc @guozhangwang @hachikuji

**Comment by hachikuji** [comment]
@ijuma Good catch. Sorry about that.

**Comment by ijuma** [comment]
@hachikuji No worries, understandable given how many times you had to merge and resolve conflicts in that huge branch. :)

**Comment by guozhangwang** [comment]
I did not saw this in the diff list since it was "too large to display", sorry about that. LGTM.

**Comment by ijuma** [comment]
@guozhangwang no problem, thanks for merging!

**Pull request closed without merging**
