### PR TITLE
MINOR: Fix Javadoc Issues

### PR DESCRIPTION
**Pull request by vahidhashemian**
This PR mainly fixes some broken links and invalid references in the clients Javadoc

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 8053 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8053 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8053 tests run, 5 skipped, 0 failed.
--none--

**Comment by hachikuji** [comment]
@vahidhashemian Thanks for the patch. Since this has been out there for a long time, I think some of the issues have already been fixed. Would you mind rebasing and checking whether there are any other doc warnings we should fix?

**Comment by vahidhashemian** [comment]
@hachikuji, thanks for the review. I rebased that patch. Looks like one file was already fixed.

**Comment by hachikuji** [comment]
retest this please

**Comment by vahidhashemian** [comment]
Looks like test servers are out of disk space? I've seen these errors often lately.

**Review by hachikuji — APPROVED** [review]

**Pull request merged**
