### PR TITLE
MINOR: fix typo in heartbeat request protocol

### PR DESCRIPTION
**Pull request by abbccdda**
`s/generationid/generationId`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by lambdaliu — APPROVED** [review]
Thanks, LGTM.

**Comment by abbccdda** [comment]
@lambdaliu Thank you!

**Comment by hachikuji** [comment]
Still missing one substitution:
```
10:58:17 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.12@2/core/src/test/scala/unit/kafka/server/KafkaApisTest.scala:596: value setGenerationid is not a member of org.apache.kafka.common.message.HeartbeatRequestData
10:58:17 possible cause: maybe a semicolon is missing before `value setGenerationid'?
10:58:17 Error occurred in an application involving default arguments.
10:58:17         .setGenerationid(1)
10:58:17          ^
```

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch.

**Pull request merged**
