### PR TITLE
KAFKA-4626: Add KafkaConsumer#close change to upgrade notes

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by rajinisivaram** [comment]
@hachikuji Can you take a look, please? Thank you.

**Review by ijuma — APPROVED** [review]
LGTM, will wait for @hachikuji in case he has some feedback.

**Comment by rajinisivaram** [comment]
@ijuma Thank you for the review.

**Comment by hachikuji** [comment]
LGTM

**Pull request closed without merging**
