### PR TITLE
KAFKA-3669: Add secondary constructor for KafkaConfig with a default …

### PR DESCRIPTION
**Pull request by markgrover**
…value for doLog

### CODE REVIEW

**Comment by markgrover** [comment]
This PR is for kafka's trunk branch.

**Comment by ijuma** [comment]
It was intentional not to add this constructor back in `0.10` as `KafkaConfig` is not public API and companion object methods are easier to understand than overloaded constructors. Having said that, we can add this back if it helps existing projects. Did you say, spark streaming is relying on this?

**Comment by markgrover** [comment]
Yeah, Spark Streaming relies on this. I don't think it's a big change for Kafka to make, so I'd prefer if Kafka made this change. That way we don't have to do reflection in Spark to be able to build against Kafka 0.9 and 0.10, it save us a bunch of work:-)

**Comment by ijuma** [comment]
LGTM, will merge once the tests pass.

**Comment by granthenke** [comment]
LGTM.

**Pull request closed without merging**
