### PR TITLE
Minor - remove unused TimeUnit from MetricConfig

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by ijuma** [comment]
Heads-up: conflicts need to be resolved before this can be merged.

**Comment by lindong28** [comment]
@ijuma Thanks for letting me know. It is rebased now.

**Comment by lindong28** [comment]
@guozhangwang Would you have time to review this patch?

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk.

**Pull request closed without merging**
