### PR TITLE
KAFKA-3521: validate null keys in Streams DSL implementations

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
Ping @enothereska for reviews.

Also added error messages in UnsupportedExceptions in StandbyContextImpl as part of this PR.

**Comment by guozhangwang** [comment]
Unit test passed locally.

**Comment by guozhangwang** [comment]
@ewencp Could you take a look?

**Comment by ewencp** [comment]
@guozhangwang All the changes look sensible. The only question I have is why some checks ignore `null` keys and others throw an exception. It seems inconsistent even where they seem similar, e.g. `KStreamKStreamJoin` vs `KStreamKTableLeftJoin`. Shouldn't it always be an error to have a `null` key for these cases or always just filter them out so the behavior is predictable?

**Comment by guozhangwang** [comment]
@ewencp For KStream, it is possible the key is null and that for operations depending on key like joins and aggregates, we will just ignore that key; for KTable, the key should not be null and if that happens, we throw exceptions;

As for KStreamKStreamJoin, it is actually the last operator of the translated sub-graph, where null keyed record should already been filtered in the previous operator, like KStreamWindowed, and hence it is not expected to see null key any more in that operator.

**Comment by ewencp** [comment]
@guozhangwang Ok, makes sense and thanks for educating me! LGTM

**Comment by guozhangwang** [comment]
Thanks @ewencp !

**Pull request closed without merging**
