### PR TITLE
HOTFIX: build error caused by DescribeClientQuotasRequest

### PR DESCRIPTION
**Pull request by chia7712**
related to #8083

fix the build error and add some tests.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@bdbyrne @cmccabe FYI

**Comment by chia7712** [comment]
the following error happens on scala 2.13
```
22:15:32 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.13/core/src/main/scala/kafka/server/KafkaApis.scala:2825: overloaded method constructor DescribeClientQuotasResponse with alternatives:
22:15:32   (x$1: org.apache.kafka.common.protocol.types.Struct,x$2: Short)org.apache.kafka.common.requests.DescribeClientQuotasResponse <and>
22:15:32   (x$1: Int,x$2: Throwable)org.apache.kafka.common.requests.DescribeClientQuotasResponse <and>
22:15:32   (x$1: java.util.Map[org.apache.kafka.common.quota.ClientQuotaEntity,java.util.Map[String,Double]],x$2: Int)org.apache.kafka.common.requests.DescribeClientQuotasResponse
22:15:32  cannot be applied to (Iterable[(org.apache.kafka.common.quota.ClientQuotaEntity, Iterable[(String, Double)])], Int)
22:15:32         new DescribeClientQuotasResponse(result, requestThrottleMs))
```

the root cause is that the return type of ```mapValues``` is changed from ```Map``` to ```MapView``` on scala 2.13. Hence, the type of "toJava" is changed from ```Map``` to ```Iterable``` as well.

**Comment by bdbyrne** [comment]
LGTM, thanks for the quick fix. @cmccabe can you merge please?

**Comment by bdbyrne** [comment]
Just saw the compile fix too. Thank you.

**Comment by bdbyrne** [comment]
I'll fix the kafka.server.RequestQuotaTest

**Comment by chia7712** [comment]
the flaky is traced by #8302

**Comment by mimaison** [comment]
retest this please

**Comment by cmccabe** [comment]
LGTM.  I'll merge this to unblock Jenkins.

**Pull request merged**
