### PR TITLE
KAFKA-5609

### PR DESCRIPTION
**Pull request by asutosh936**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by asutosh936** [comment]
@rhauch @ewencp - Please review.

**Comment by asutosh936** [comment]
@guozhangwang @mjsax @rhauch @ewencp - This pull request is reference to https://github.com/apache/kafka/pull/4619 which has fix with implemented review comments provided by @rhauch. Please review.

**Review by ewencp — COMMENTED** [review]
Could we update commit messages with a description? These make it into the commit message once merged, so we want a clear description of the change that occurred.

Also @cotedm @rnpridgeon is this the config you'd recommend? Since it is backwards compatible, seems more than reasonable to do this, but I'm no log4j expert, so I'd love a sign-off from people who know how to properly configure this stuff.

**Comment by rnpridgeon** [comment]
I personally would consider using the RollingFileAppender with a sensible retention policy instead. Regrettably the DailyRollingFileAppender does not afford you a maxBackupIndex property which means you could potentially saturate disks. 

https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/RollingFileAppender.html

**Comment by ewencp** [comment]
@rnpridgeon Awesome, input appreciated! Glad I asked for it before committing :) More concretely, maybe can we suggest what the sensible retention policy would be so @asutosh936 could update appropriately?

**Comment by cotedm** [comment]
we talked reasonable default retention here https://github.com/apache/kafka/pull/1652

1G over 10 files is also reasonable for connect in my opinion.

**Comment by rnpridgeon** [comment]
+1

**Comment by asutosh936** [comment]
@rnpridgeon @ewencp @cotedm @rhauch @guozhangwang 

All, Thank You for Your review and providing candid feedback. I am very sorry, have some issues with Git repo and the branch having this fix got deleted. Hence have made the necessary requested changes and have to create new Pull Request.

https://github.com/apache/kafka/pull/4753

Sorry Once again for any confusion.

**Pull request closed without merging**
