### PR TITLE
Switch to using scala 2.9.2

### PR DESCRIPTION
**Pull request by azymnis**
Compiled and used fine. I had issues with the tests though.

Reviewers: alexanford (github:alexanford)

### CODE REVIEW

**Comment by ijuma** [comment]
This is no longer relevant (new build system and 2.9.2 is supported). Can you please close this (we cannot close it ourselves with raising a ticket to Apache Infra, unfortunately)?

**Comment by b-goyal** [comment]
Compiled and used fine. I had issues with the tests though.

**Comment by b-goyal** [comment]
Compiled and used fine. I had issues with the tests though.

**Comment by b-goyal** [comment]
Compiled and used fine. I had issues with the tests though.

**Comment by b-goyal** [comment]
Compiled and used fine. I had issues with the tests though.

**Comment by b-goyal** [comment]
Compiled and used fine. I had issues with the tests though.

**Comment by b-goyal** [comment]
Compiled and used fine. I had issues with the tests though.

**Comment by b-goyal** [comment]
Compiled and used fine. I had issues with the tests though.

**Comment by b-goyal** [comment]
Compiled and used fine. I had issues with the tests though.

**Pull request closed without merging**
