### PR TITLE
MINOR: Fix connect:mirror checkstyle

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
Assuming Jenkins passed please feel free to merge. Thanks @mimaison

**Comment by mimaison** [comment]
@guozhangwang I'll be away when Jenkins completes. Can you merge it for me?

**Review by hachikuji — APPROVED** [review]
LGTM. I tested locally. Will go ahead and merge.

**Comment by hachikuji** [comment]
For reference, the issue was introduced in https://github.com/apache/kafka/commit/4fe324b5a696d47ae8414cf030ae36b83a2cf163.

**Pull request merged**
