### PR TITLE
KAFKA-3402; Restore behaviour of MetadataCache.getTopicMetadata when unsupported security protocol is received

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @hachikuji and @gwenshap

**Comment by hachikuji** [comment]
Ah, you beat me to it. The other option is to add a new error code (as discussed with @junrao), but I think this patch is the way to go for now.

**Comment by hachikuji** [comment]
LGTM

**Comment by granthenke** [comment]
LGTM

**Comment by ijuma** [comment]
I rebased against trunk and added a commit to use the non-deprecated `Broker` constructor (now that the rack-aware PR has been merged).

**Comment by gwenshap** [comment]
LGTM

**Pull request closed without merging**
