### PR TITLE
MINOR: Remove 1.2.0 changes from 1.1 streams doc

### PR DESCRIPTION
**Pull request by rajinisivaram**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Hey @rajinisivaram, good catch! This LGTM, but I'm not a committer.

**Comment by vvcephei** [comment]
Unrelated failures were:
```
00:38:42.445 kafka.server.DynamicBrokerReconfigurationTest > testAddRemoveSaslListeners FAILED
00:38:42.445     java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<0> but was:<1>
00:38:42.445         at java.util.concurrent.FutureTask.report(FutureTask.java:122)
00:38:42.445         at java.util.concurrent.FutureTask.get(FutureTask.java:206)
00:38:42.445         at kafka.server.DynamicBrokerReconfigurationTest.verifyTimeout(DynamicBrokerReconfigurationTest.scala:1211)
00:38:42.445         at kafka.server.DynamicBrokerReconfigurationTest.verifyConnectionFailure(DynamicBrokerReconfigurationTest.scala:1205)
00:38:42.445         at kafka.server.DynamicBrokerReconfigurationTest.verifyRemoveListener(DynamicBrokerReconfigurationTest.scala:809)
00:38:42.445         at kafka.server.DynamicBrokerReconfigurationTest.testAddRemoveSaslListeners(DynamicBrokerReconfigurationTest.scala:717)
00:38:42.445 
00:38:42.445         Caused by:
00:38:42.445         java.lang.AssertionError: expected:<0> but was:<1>
```
and
```
00:40:05.192 kafka.server.DynamicBrokerReconfigurationTest > testAddRemoveSslListener FAILED
00:40:05.192     java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<0> but was:<1>
00:40:05.192         at java.util.concurrent.FutureTask.report(FutureTask.java:122)
00:40:05.192         at java.util.concurrent.FutureTask.get(FutureTask.java:206)
00:40:05.192         at kafka.server.DynamicBrokerReconfigurationTest.verifyTimeout(DynamicBrokerReconfigurationTest.scala:1211)
00:40:05.192         at kafka.server.DynamicBrokerReconfigurationTest.verifyConnectionFailure(DynamicBrokerReconfigurationTest.scala:1205)
00:40:05.192         at kafka.server.DynamicBrokerReconfigurationTest.verifyRemoveListener(DynamicBrokerReconfigurationTest.scala:809)
00:40:05.192         at kafka.server.DynamicBrokerReconfigurationTest.testAddRemoveSslListener(DynamicBrokerReconfigurationTest.scala:705)
00:40:05.192 
00:40:05.192         Caused by:
00:40:05.192         java.lang.AssertionError: expected:<0> but was:<1>
```

Triggering another run of the tests:

Retest this, please.

**Review by guozhangwang — APPROVED** [review]
Thanks @rajinisivaram

**Review by mjsax — APPROVED** [review]
LGTM. Thanks @rajinisivaram !

**Comment by rajinisivaram** [comment]
Thanks @vvcephei @guozhangwang @mjsax for the review, merging to 1.1.

**Pull request merged**
