### PR TITLE
KAFKA-1371 Ignore build output dirs

### PR DESCRIPTION
**Pull request by sslavic**
This patch extends git ignore patterns to all build and .gradle dirs

### CODE REVIEW

**Comment by sslavic** [comment]
This was merged in https://github.com/apache/kafka/commit/33e07a61f9a0455da544659b62e4ce8ffca7e9ab

**Comment by b-goyal** [comment]
This patch extends git ignore patterns to all build and .gradle dirs

**Comment by b-goyal** [comment]
This patch extends git ignore patterns to all build and .gradle dirs

**Comment by b-goyal** [comment]
This patch extends git ignore patterns to all build and .gradle dirs

**Comment by b-goyal** [comment]
This patch extends git ignore patterns to all build and .gradle dirs

**Comment by b-goyal** [comment]
This patch extends git ignore patterns to all build and .gradle dirs

**Comment by b-goyal** [comment]
This patch extends git ignore patterns to all build and .gradle dirs

**Pull request closed without merging**
