### PR TITLE
KAFKA-4331: Kafka Streams resetter is slow because it joins the same group for each topic

### PR DESCRIPTION
**Pull request by mjsax**
- reworked to use a sinlge KafkaConsumer and subscribe only once

### CODE REVIEW

**Comment by mjsax** [comment]
@guozhangwang @enothereska @dguy Please review.
/cc @theduderog

**Comment by guozhangwang** [comment]
LGTM. @theduderog Could you verify if this patch fixed your issue before I merge?

**Comment by theduderog** [comment]
yes, i'll test it today

**Comment by theduderog** [comment]
Tested and it was WAY faster!  Thanks, @mjsax

**Comment by mjsax** [comment]
Glad to hear @theduderog :)

**Comment by guozhangwang** [comment]
Unit test passed locally. Merged to trunk.

**Pull request closed without merging**
