### PR TITLE
KAFKA-17584: Fix incorrect synonym handling for dynamic log configurations

### PR DESCRIPTION
**Pull request by clolov**
This is a cherry-pick of https://github.com/apache/kafka/pull/17258 to 3.7.2

This commit differs from the original by using the old (read 3.7) references to the configurations and not changing as many unit tests

### CODE REVIEW

**Comment by clolov** [comment]
Heya @cmccabe and @showuon, in order to add this to the 3.7.2 release I have made an attempt to port the changes. Would you be willing to review this?

+cc @mjsax for visibility

**Review by divijvaidya — COMMENTED** [review]
I compared this with the backport in https://github.com/apache/kafka/pull/17278/files and the changes look good.

Let's give some time for original authors to take a look before we merge this (also CI tests are failing).

**Comment by mjsax** [comment]
@clolov @cmccabe @showuon -- Can we make progress on this cherry-pick? It's currently blocking me from creating the first RC.

**Review by cmccabe — APPROVED** [review]
LGTM after looking at this side-by-side with the original change

Thanks @clolov

**Comment by mjsax** [comment]
Triggered a new CI run -- can merge this afterwards.

**Comment by mjsax** [comment]
@clolov It seems `ReplicaManagerTest.testRemoteFetchExpiresPerSecMetric` fails all the time. Thoughts? No idea if related or not.

**Comment by clolov** [comment]
Heya @mjsax. The test passes locally when I run it individually, as part of the class and as part of the whole test suite. It also appears to have been passing as build 2 of the same PR. If that is the only concern is there a way we can get a complete new clean build which doesn't reuse any old build artifacts just to see whether it is persistent?

**Pull request merged**
