### PR TITLE
KAFKA-9709: add a confirm when kafka-server-stop.sh find multiple kafka instances to kill

### PR DESCRIPTION
**Pull request by iamgd67**
add a confirm when kafka-server-stop.sh find multiple kafka instances, avoid mistakenly kill all instance of this machine.

### CODE REVIEW

**Comment by rondagostino** [comment]
Thanks for the PR, @iamgd67.  This probably requires a KIP because it changes existing behavior.  Existing automation that relies on this script would break if the functionality is added as currently implemented in this PR, for example.  A KIP is the place to address this in an open proposal and discussion.

**Comment by iamgd67** [comment]
thans your review, @rondagostino . what about add a timeout like 5 seconds, if no user interaction, do kill all just as before.

**Comment by rondagostino** [comment]
@iamgd67 This is the type of discussion that would occur for a KIP.  Creating one is the way to go.

**Comment by iamgd67** [comment]
@rondagostino , create kip https://issues.apache.org/jira/browse/KAFKA-9709 and list some  workaround there, don't know will the PR and KIP auto connect to each other.

**Comment by rondagostino** [comment]
@iamgd67 Take a look at the instructions [here](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals).  You would add a link to this issue in the KIP document that you publish.

**Pull request closed without merging**
