### PR TITLE
KAFKA-5235: GetOffsetShell: new KafkaConsumer API, support for multiple topics, minimized number of requests to server

### PR DESCRIPTION
**Pull request by tashoyan**
This PR addresses two improvements:

[KAFKA-5235 GetOffsetShell: retrieve offsets for all given topics and partitions with single request to the broker](https://issues.apache.org/jira/browse/KAFKA-5235)
[KAFKA-5234 GetOffsetShell: retrieve offsets for multiple topics with single request](https://issues.apache.org/jira/browse/KAFKA-5234)

1. Previous implementation used SimpleConsumer to get offsets and old Producer API to get topic/partition metadata. Previous implementation determined a leader broker for each partition and then requested the leader for offsets. In total, it did as many requests to the broker as the number of partitions (plus a request to Zookeeper for metadata).
New implementation `kafka-get-offsets.sh` uses KafkaConsumer API. It makes at most two requests to the broker: 1) to query existing topics and partitions, 2) to grab all requested offsets. New implementation correctly handles non-existing topics and partitions asked by user:

> kafka-get-offsets.sh --bootstrap-servers vm:9092 --topics AAA,ZZZ --partitions 0,1
> AAA:0:7
> AAA:1:Partition not found
> ZZZ:0:Topic not found

2. Previously, user could get offsets for one topic only. Now user can get offsets for many topics at once:
`kafka-get-offsets.sh --bootstrap-servers vm:9092 --topics AAA,ZZZ`
Moreover, now user is able to retrieve offsets for _all_ topics - this is the default when no topics specified:
`kafka-get-offsets.sh --bootstrap-servers vm:9092`
Thanks to this feature, there is no need anymore to retrieve all topics by means of `kafka-topics.sh`.
When no topics specified, the new `kafka-get-offsets.sh` tool takes into account only user-level topics and ignores Kafka-internal topics (i.e. consumer offsets). This behavior can be altered via a special command line argument:
`kafka-get-offsets.sh --bootstrap-servers vm:9092 --include-internal-topics`

3. New `kafka-get-offsets.sh` tool is consistent with other console tools with respect to command line argument names. In addition, `kafka-get-offsets.sh` tool gives the possibility to pass an arbitrary setting to KafkaConsumer via `--consumer-property` argument. Old command line arguments are marked as deprecated with appropriate warning messages.

I hope, now `kafka-get-offsets.sh` is easier in use and gives performance improvement.
@junrao I suppose you may want to review.

### CODE REVIEW

**Comment by tashoyan** [comment]
retest this please

**Comment by tashoyan** [comment]
Hmm, JVM crash when running :core:compileScala
Works fine on my machine - build as well as tests.
Scala version: 2.12.2
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by tashoyan** [comment]
retest this please

**Comment by tashoyan** [comment]
@gwenshap , @SinghAsDev would you like to review? This PR resolves the GetOffsetShell dependency on the old producer API discussed in https://github.com/apache/kafka/pull/1076

**Comment by tashoyan** [comment]
@ijuma thank you for updating the issue in Jira. Would you like to review this PR?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5391/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5376/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5393/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5378/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by tashoyan** [comment]
@guozhangwang would you review this PR please? I hope it won't take much time. Why keep it awaiting in the queue for months?

**Comment by ijuma** [comment]
@tashoyan Thanks for the PR and sorry for the delay. Have you checked if the `ConsumerGroupCommand` doesn't have the required functionality?

**Comment by tashoyan** [comment]
@ijuma `ConsumerGroupCommand` is a different tool. It presents information on a per-consumer-group basis. It shows the offset of the specified consumer group in the specified topic. `ConsumerGroupCommand` cannot show the latest offset in the topic or the offset by a timestamp. Also it cannot show offsets for multiple topics.

**Comment by tashoyan** [comment]
@junrao @guozhangwang @gwenshap @ijuma may I kindly ask you to review this PR?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6440/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6425/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6444/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6429/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by alexsavio** [comment]
Is there any other way of getting offset information without GetOffsetShell? If not, this is a quite important PR, isn't it? Right now, GetOffsetShell doesn't work with SASL_SSL, and I can't find any solution for this. Thanks for the amazing work!

**Comment by tashoyan** [comment]
I also think that this PR is important. We need this functionality for our monitoring tools and for performance metrics. I hope, finally we will have it in the product.

**Comment by ijuma** [comment]
@tashoyan Sorry for the delay. Since you have made changes to the command line parameters, can you please submit a KIP (https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals)?

**Comment by tashoyan** [comment]
@ijuma I don't have access to create KIP. Could you give it to me? I wrote to dev mailgroup, but no answer.

**Comment by tashoyan** [comment]
[KIP-308](https://cwiki.apache.org/confluence/display/KAFKA/KIP-308%3A+GetOffsetShell%3A+new+KafkaConsumer+API%2C+support+for+multiple+topics%2C+minimize+the+number+of+requests+to+server)

**Comment by ijuma** [comment]
Thanks @tashoyan. I did a minimal PR for inclusion in 2.0.0 and added you as a co-author:

https://github.com/apache/kafka/pull/5220

**Comment by tashoyan** [comment]
Thanks @ijuma 
Should I close this PR?

**Comment by ijuma** [comment]
Maybe the easiest is to close and submit a new one once the KIP has been voted.

**Comment by dajac** [comment]
Closing as this is addressed in https://github.com/apache/kafka/pull/9430 (KIP-635).

**Pull request closed without merging**
