### PR TITLE
MINOR: Upgrade ducktape to 0.7.6

### PR DESCRIPTION
**Pull request by brianbushree**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ewencp** [comment]
How far back is this going? I can't remember what's changed between these two versions of ducktape.

**Comment by brianbushree** [comment]
@ewencp functionally, the only thing that has changed seems to be this https://github.com/confluentinc/ducktape/pull/210 SSH timeout issue and also some extra logging  

also not sure how far back we should go...

**Comment by brianbushree** [comment]
let's just fix forward here since there's nothing broken in this project at the moment

**Comment by brianbushree** [comment]
@ewencp how's this looking?

**Review by ewencp — APPROVED** [review]
LGTM

**Pull request closed without merging**
