### PR TITLE
MINOR: remove org.apache.kafka.streams.errors.BrokerNotFoundException

### PR DESCRIPTION
**Pull request by chia7712**
```BrokerNotFoundException``` is useless after 234ec8a8af76bfb7874dd99714a65089d6048953 was merged.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Even if we don't throw this exception any longer, it seems to be a public API change, and thus we should rather do a KIP an first deprecate the class to remove it only later in a major release?

\cc @bbejeck WDYT?

**Comment by ijuma** [comment]
Yeah, we should not remove public classes without a deprecation cycle.

**Comment by chia7712** [comment]
@mjsax @ijuma Thanks for your response. I will file a KIP to deprecate it.

**Comment by chia7712** [comment]
superseded by https://issues.apache.org/jira/browse/KAFKA-12281

**Pull request closed without merging**
