### PR TITLE
KAFKA-5359: Use a suppressed exception when throwing`RequestFuture.exception()`

### PR DESCRIPTION
**Pull request by vahidhashemian**
Use a suppressed exception when throwing `RequestFuture.exception()` on the client side to help with identifying where on the client side the exception is thrown.

For example, running the code inside `org.apache.kafka.clients.consumer.internals.ConsumerCoordinatorTest.testGroupDescribeUnauthorized` currently returns with
```
org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: test-group
```

With this PR, the same code returns with the following failure trace
```
org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: test-group
	Suppressed: org.apache.kafka.common.KafkaException: An error occurred in the broker when looking up the group coordinator.
		at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:226)
		at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:201)
		at org.apache.kafka.clients.consumer.internals.ConsumerCoordinatorTest.testGroupDescribeUnauthorizedOld(ConsumerCoordinatorTest.java:161)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
```

### CODE REVIEW

**Comment by reftel** [comment]
Hi! Thanks for working on this =)
I see an issue with this solution, though: the use of ApiException means that the caller still doesn't get any stack trace, since ApiException overrides fillInStackTrace to do nothing. Could we use a different exception type, or make the stack trace skipping in ApiException  optional, and opt out when rethrowing?
Also, I'm wondering about API compatibility. An existing client that does something like catching `AuthorizationException` to trigger configuring security and retrying would not have to change to inspect the cause. Does the client library give any stability guarantees w.r.t. the types of exception s being thrown?

**Comment by vahidhashemian** [comment]
@reftel Thanks for reviewing the PR. You're right about the lack of stack trace. The only other existing exception class that seems to fit here is `KafkaException`. Your other approach should work too: we could make skipping the stack trace the default behavior; and overwrite that default for this PR. I'll go with the second option for the next update.

Regarding API compatibility I'm not sure about any existing guarantee re. thrown exceptions on the client side. I'll update the PR and ask one of the committers for feedback.

**Comment by rajinisivaram** [comment]
Rather than throw a different exception with the original exception as cause, making it harder to handle the exception in the client, it may be better to add a new suppressed exception to the request exception for providing the caller stack trace using `Throwable#addSuppressed`.

**Comment by vahidhashemian** [comment]
@rajinisivaram Thank you for the great suggestion. It seems to me that is more elegant than the other options discussed so far, as it is backward compatible. Do you think existing unit tests need to be updated to check the suppressed exception?

**Comment by rajinisivaram** [comment]
@vahidhashemian You could update one of the existing tests that raises this exception to check the suppressed exception.

**Comment by vahidhashemian** [comment]
@rajinisivaram Thanks, will try to do that in the next update.

**Comment by vahidhashemian** [comment]
@reftel @rajinisivaram The PR was just updated based on the recent feedback.

**Comment by reftel** [comment]
Looks better than I thought would be possible! Nice work =)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5596/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5582/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
Can you please post a before and after for the exception output in one of the cases?

**Comment by vahidhashemian** [comment]
@ijuma I just added an example of before and after failure traces in the PR description.

**Comment by ijuma** [comment]
Thanks. Hmm, wouldn't it be more useful to have the stacktrace for `GroupAuthorizationException`? We could do that by enabling stacktraces by default and disabling them only for the exceptions stored in `Errors`.

**Comment by vahidhashemian** [comment]
@ijuma Do you mean having something like this with the example above:
```
org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: test-group
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$GroupCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:608)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$GroupCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:205)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:168)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:128)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:488)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:348)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:208)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:184)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:215)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:201)
	.
        .
        .
	Suppressed: org.apache.kafka.common.KafkaException: An error occurred in the broker when looking up the group coordinator.
		at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:226)
		.
                .
                .
```

or not have the suppressed stack trace at all?

**Comment by ijuma** [comment]
Not sure about the suppressed exception. Does it add enough value? Either way, having the original stacktrace seems the most useful to me. What do you think? cc @hachikuji

**Comment by vahidhashemian** [comment]
Thanks @ijuma. As mentioned in the corresponding JIRA, without something like the suppressed exception it's not trivial (at least to me) where in the client code the `RequestFuture` caused the failure. Pointing to where the future exception was thrown seems to be useful for troubleshooting.

**Comment by ijuma** [comment]
Thanks @vahidhashemian. Have we considered rethrowing the same exception with the original exception as the cause? Ideally, we would add a method to the future that does that so that the logic doesn't have to be repeated in multiple places. Using `addSuppressed` kind of works although it seems a little bit of a hack. See the Javadoc:

```java
  * <p>Note that when one exception {@linkplain
     * #initCause(Throwable) causes} another exception, the first
     * exception is usually caught and then the second exception is
     * thrown in response.  In other words, there is a causal
     * connection between the two exceptions.
     *
     * In contrast, there are situations where two independent
     * exceptions can be thrown in sibling code blocks, in particular
     * in the {@code try} block of a {@code try}-with-resources
     * statement and the compiler-generated {@code finally} block
     * which closes the resource.
     *
     * In these situations, only one of the thrown exceptions can be
     * propagated.  In the {@code try}-with-resources statement, when
     * there are two such exceptions, the exception originating from
     * the {@code try} block is propagated and the exception from the
     * {@code finally} block is added to the list of exceptions
     * suppressed by the exception from the {@code try} block.  As an
     * exception unwinds the stack, it can accumulate multiple
     * suppressed exceptions.
```

**Comment by vahidhashemian** [comment]
@ijuma After reading the Javadoc, it seems more reasonable to use a cause instead of suppression. I tried cause in the first commit, but in that I kept the original exception as the main thrown exception, and used an `ApiException` as the cause; even though having them the other way around made more sense, I wanted to keep it backward compatible wrt. the exception thrown.

Could you please clarify what you mean by "rethrowing the same exception with the original exception as the cause"? Do you mean creating (dynamically) a duplicate of the original exception object? For example, if the original exception is `GroupAuthorizationException` do you suggest we create another object of this type and throw that and use the original exception as the cause? Thanks.

**Comment by ijuma** [comment]
Yes, that's what I meant. It seemed like the least bad option.

**Comment by vahidhashemian** [comment]
Thanks for clarifying. It makes sense. I'll look into it (not sure yet how the dynamic instantiation piece would work).

**Comment by vahidhashemian** [comment]
@ijuma What I had in mind for dynamically cloning the exception object was to leverage `Class.newInstance()` inside `RequestFuture.exception()`, but the issue is some of the exceptions have parameterized constructors only and that approach won't work for them. I'll dig around some more but if you were thinking of a different approach to handle this please let me know. Thanks.

**Pull request closed without merging**
