### PR TITLE
KAFKA-5433: Close SimpleAclAuthorizer in test to close ZK client

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
My bad for missing this during the review, LGTM.

**Comment by rajinisivaram** [comment]
@ijuma Can you take a look, please? Thank you...
We need a better way to catch these and fail tests, but for now this just fixes the test to avoid transient build failures.

**Comment by ijuma** [comment]
@rajinisivaram my LGTM was faster than your request for review. ;)

**Comment by rajinisivaram** [comment]
@ijuma Thank you for the review. I will wait for the PR builds to complete before merging. Should I add this to 0.11.0 branch as well?

**Comment by ijuma** [comment]
Yes, please merge it to 0.11.0 as well.

**Pull request closed without merging**
