### PR TITLE
Kafka 5692 elect preferred

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 7145 tests run, 1 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7145 tests run, 1 skipped, 0 failed.
--none--

**Comment by cmccabe** [comment]
See #3848

**Pull request closed without merging**
