### PR TITLE
KAFKA-3716: Validate all timestamps are not negative

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
Timestamps can be created in the following various cases to pass into window stores:
1. `context.timestamp()`, in which the timestamp are extracted from records, and we need to validate upon extraction.
2. `punctuate()` based on `PartitionGroup.timestamp()`, in which we need to guard against `NOT_KNOWN` which is -1.
3. `Windows.windowsFor(timestamp)`, in which we should only consider windows with start timestamp non-negative.

cc @ijuma @enothereska @mjsax

**Comment by guozhangwang** [comment]
Local unit test passed.

**Comment by enothereska** [comment]
LGTM

**Comment by ijuma** [comment]
@guozhangwang's comment mentions 3 cases, but the PR changes two places. Do you know why @enothereska?

**Comment by guozhangwang** [comment]
@ijuma 3) is handled correctly already before this PR, I just add a comment indicating other implementations of `Windows` to follow the same.

**Comment by ijuma** [comment]
Thanks for the explanation, LGTM.

**Comment by guozhangwang** [comment]
Merged to trunk.

**Comment by miguno** [comment]
@guozhangwang: You said

> Local unit test passed.

I don't see any unit tests in this PR.

**Comment by guozhangwang** [comment]
@miguno I mean "running ./gradlew test" passed on my local machine.

Did not add any unit tests in this PR since I realize they are already covered in other non-streams unit tests, so do not want to add overlaps. Previously we are not having any cases that would trigger 1) and 2) above, but I just add those validations for better exception messages.

**Pull request closed without merging**
