### PR TITLE
MINOR: Use MessageDigest equals when comparing signature

### PR DESCRIPTION
**Pull request by naanagon**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by naanagon** [comment]
Hi @dajac @hachikuji and @showuon , please help to review the PR .
Thanks.

**Comment by naanagon** [comment]
@kkonstantine Thanks for adding label. Can you review the pr..?

**Review by showuon — COMMENTED** [review]
@naanagon , thanks for the PR. But I'm not sure if the change is necessary, because what we did for signature comparing is in the `isValid` method, and it's already compared with time-constant way. Could you elaborate more why you think this is necessary? Or point to me where in the code we did the `InternalRequestSignature#equals` and need time-constant comparing. 

Thank you.

**Comment by naanagon** [comment]
> @naanagon , thanks for the PR. But I'm not sure if the change is necessary, because what we did for signature comparing is in the `isValid` method, and it's already compared with time-constant way. Could you elaborate more why you think this is necessary? Or point to me where in the code we did the `InternalRequestSignature#equals` and need time-constant comparing.
> 
> Thank you.

@showuon, thanks for taking a look. `isValid` method just compares signature in time-constant way. But same should happen when comparing objects which has sensitive information. Even though `InternalRequestSignature#equals` isn't being used but i thought it should be implemented properly. Motivation for this pr is [DelegationToken.java](https://github.com/apache/kafka/blob/074a03cca162f91ccdecc12eb84c6a45af75f6bf/clients/src/main/java/org/apache/kafka/common/security/token/delegation/DelegationToken.java#L63) and also `DelegationToken#equals` isn't being used but that was implemented properly.

**Review by showuon — APPROVED** [review]
@naanagon , thanks for the explanation. Make sense to me.

**Comment by naanagon** [comment]
@showuon, thank you. @dajac, Could you please take a look

**Comment by naanagon** [comment]
> @showuon, thank you. @dajac, Could you please take a look

@showuon Can you merge the pr..?

**Review by andrewchoi5 — APPROVED** [review]

**Comment by showuon** [comment]
@rhauch , do you want to take a quick look for this PR?

**Review by cryptoe — APPROVED** [review]
Changes LGTM +1 non binding

**Review by divijvaidya — APPROVED** [review]
The motivation for this change is to guard against [timing attacks](https://crackstation.net/hashing-security.htm) when using `InternalRequestSignature.equals()`

Pros of this PR
- if the InternalRequestSignature.equal() method could be used for a timing attack, then this PR fixes a security vulnerability

Cons of this PR
- `MessageDigest.isEquals()` is slower than `Arrays.equal` since the former is time constant i.e. it runs for a fixed time irrespective of the length of original signature. The execution time of MessageDigest.isEquals() is a function of length of the byte array that it is being tested against. 

My inclination:

Even if `InternalRequestSignature.equals()` is not being used anywhere in code today where it may cause a timing attack, we should still guard against the possibility where a future change might start using it (especially in an open source project where changes might be contributed & reviewed by multiple group of people). The downside of slower equality comparison over a signature is risk worth accepting given the upside we get to safeguard future use cases.

This change looks good to me! 👍

**Suggestion to the author**
Hey @naanagon, congrats on your first PR to Apache Kafka 🥳. I am myself a new-ish contributor to Kafka and would like to give you some unsolicited advice that helped me onboard to Kafka community. 
1. Having a detailed description for your changes helps the reviewer. e.g. in this PR adding a motivation section to the description and describing what does "implemented properly" mean (i.e. guard against timing attacks) helps reduce the effort a reviewer has to spent and hence, might accelerate your review.
2. Have patience. In our community, we have 993 PRs open with only a handful of reviewers. Their limited bandwidth is best spent on reviewing PRs which are urgent and significantly improve the experience. A good-to-have PR might be low on the priority but in due course someone will definitely reach to reviewing it.
3. In extension to point#2 above, a great place to start contributing is for tickets which are considered "urgent". For example, you can look at the release blocking tickets from the JIRA backlog and start picking up work from there. It's a win-win where you get prioritized code reviews and community gets a fix for an urgent release blocking problem.
4. In general, optimize your PRs for code review friendliness. e.g. you could anticipate questions what a reviewer might ask and address them proactively by adding comments to your own PR. This helps accelerate the code review process.

Hope the above suggestion helps! Looking forward to more contributions from you.

**Comment by naanagon** [comment]
@divijvaidya Thank you for your suggestion. Noted.

**Comment by showuon** [comment]
Failed tests are unrelated:
```
    Build / JDK 8 and Scala 2.12 / integration.kafka.server.FetchRequestBetweenDifferentIbpTest.testControllerNewToOldIBP()
    Build / JDK 17 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testAllTopicPartition, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testPathToJsonFile, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testTopicPartition, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testAllTopicPartition, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testTopicPartition, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.server.ReplicaManagerTest.[1] usesTopicIds=true
```

**Pull request merged**
