### PR TITLE
MINOR: fix listeners doc to close <code> properly

### PR DESCRIPTION
**Pull request by tombentley**
Fixes a problem with an incorrectly closed `<code>` in the doc for `listeners`.

### CODE REVIEW

**Comment by tombentley** [comment]
This is how it renders without this fix

image

@bbejeck this also affects the 2.7RC3 docs, but you could always just fix the generated HTML there.

**Review by bbejeck — APPROVED** [review]
Good catch, thanks for the fix @tombentley.

**Comment by bbejeck** [comment]
Merged 9655 into trunk

**Comment by bbejeck** [comment]
cherry-picked to 2.7

**Pull request merged**
