### PR TITLE
MINOR: Remove `activeTaskCheckpointableOffsets` from `AbstractTask`

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @cpettitt-confluent @mjsax @guozhangwang @bbejeck @vvcephei @ableegoldman @abbccdda

**Comment by cpettitt-confluent** [comment]
Verified this is only used in StreamTask. All for moving Stream/Standby specific stuff out of AbstractTask! LGTM.

**Review by cpettitt-confluent — APPROVED** [review]

**Review by ableegoldman — APPROVED** [review]
Good catch, thanks!

**Review by guozhangwang — APPROVED** [review]
Could you rebase?

**Comment by cadonna** [comment]
JDK 11/Scala 2.12 failed with 
```
org.scalatest.exceptions.TestFailedException: Consumed 0 records before timeout instead of the expected 1 records
```

Retest this, please

**Comment by cadonna** [comment]
JDK 11/Scala 2.12 had the following failing test:
```
org.apache.kafka.streams.integration.StreamStreamJoinIntegrationTest.testOuterRepartitioned[caching enabled = true]

java.lang.AssertionError: Condition not met within timeout 60000. Did not receive all 1 records from topic outputTopic
```

Retest this, please

**Comment by cadonna** [comment]
JDK 11/Scala 2.12 failed because the following test failed:
```
kafka.admin.DescribeConsumerGroupTest.testDescribeStateWithMultiPartitionTopicAndMultipleConsumers
``` 
JDK 11/Scala 2.13 failed because the following test failed:
```
org.apache.kafka.common.network.SslTransportLayerTest.testListenerConfigOverride
```

Retest this, please

**Comment by cadonna** [comment]
In JDK 11/Scala 2.12 the following test failed:
```
org.apache.kafka.connect.integration.ExampleConnectIntegrationTest.testSourceConnector
```

JDK 8/Scala 2.11 run into timeout after 4 hours.

Retest this, please

**Comment by cadonna** [comment]
Retest this, please

**Comment by guozhangwang** [comment]
LGTM!

**Pull request merged**
