### PR TITLE
KAFKA-2972; Add missing `partitionsRemaingList.add` in `ControlledShutdownResponse` constructor

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM

**Comment by ijuma** [comment]
./gradlew test passed locally

**Comment by ijuma** [comment]
I think it would be good to backport this to the 0.9.0 branch.

**Comment by ijuma** [comment]
It occurred to me that we don't need to backport this as we don't use the Java classes to serialise the responses in 0.9.0. That will only be done when https://github.com/apache/kafka/pull/640 is merged.

**Comment by guozhangwang** [comment]
Merged to both branches.

**Pull request closed without merging**
