### PR TITLE
MINOR: Add 3.8.0 to system tests

### PR DESCRIPTION
**Pull request by jlprat**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
Note that the 3.8.0 artifacts are not yet uploaded to the S3 bucket.
@cmccabe, @mjsax or @jsancio Could you please upload the artifacts to S3 as per https://cwiki.apache.org/confluence/display/KAFKA/Release+Process#ReleaseProcess-Afterthevotepasses?

**Comment by jlprat** [comment]
Packages are now in https://kafka-packages.s3.us-west-2.amazonaws.com/
Thanks @cmccabe

**Review by omkreddy — APPROVED** [review]
LGTM. Thanks.

**Comment by jlprat** [comment]
Tests in the CI pipeline are unrelated. @omkreddy Could you check that the system test pipeline works smoothly after this is merged?

**Comment by jlprat** [comment]
Cherry-picked to `3.9` @cmccabe

**Pull request merged**
