### PR TITLE
KAFKA-15865: Remove autocommit completion event

### PR DESCRIPTION
**Pull request by lucasbru**
There is no callback associated with autocommit, so I do not think we need this event. This closes KAFKA-15865.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lucasbru** [comment]
@philipnee could you please take a look before @cadonna reviews this?

**Comment by cadonna** [comment]
@lucasbru Is the following test failure related:
```
org.apache.kafka.clients.consumer.internals.EagerConsumerCoordinatorTest.testOutdatedCoordinatorAssignment()
```

**Comment by cadonna** [comment]
I am asking because I see the follwing log:
```
[2023-11-23 16:29:05,394] ERROR Asynchronous auto-commit of offsets failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.. Will continue to join group. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:744)
```

**Comment by lucasbru** [comment]
The test is failing in legacy consumer code, and this PR did not touch legacy consumer code. 

The test failure may be related to the CTR refactoring, but not to this particular PR.

**Comment by cadonna** [comment]
Yeah, the test was flaky before in PR builds but not on trunk [1].
Could you at least create a ticket for it?

I was able to reproduce the failure locally. So, it should not be too hard to fix.

[1] https://ge.apache.org/scans/tests?search.relativeStartTime=P90D&search.rootProjectNames=kafka&search.timeZoneId=Europe%2FBerlin&tests.container=org.apache.kafka.clients.consumer.internals.EagerConsumerCoordinatorTest&tests.test=testOutdatedCoordinatorAssignment()#

**Review by cadonna — APPROVED** [review]
Thanks @lucasbru !

LGTM!

**Comment by lucasbru** [comment]
There is already a ticket for this. [KAFKA-15900](https://issues.apache.org/jira/browse/KAFKA-15900)

**Pull request merged**
