### PR TITLE
MINOR: remove unused hitRatio field in NamedCache

### PR DESCRIPTION
**Pull request by dguy**

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang just a minor tidy up

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5505/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5490/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk.

**Pull request closed without merging**
