### PR TITLE
MINOR: StreamThread standbyTask comment typo

### PR DESCRIPTION
**Pull request by zqhxuyuan**
log info typos. should be standby task, not active task.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5431/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5416/
Test PASSed (JDK 8 and Scala 2.12).

**Review by mjsax — APPROVED** [review]
LGTM.

Call for merging @guozhangwang @dguy (if possible, please merge into 0.11, too)

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and 0.11.0. Thanks @zqhxuyuan !

**Pull request closed without merging**
