### PR TITLE
KAFKA-8892: Display the sorted configs in Kafka Configs Help Command.

### PR DESCRIPTION
**Pull request by kamalcph**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kamalcph** [comment]
@hachikuji @omkreddy 
Please take a look when you get a chance.

**Comment by omkreddy** [comment]
retest this please

**Comment by omkreddy** [comment]
retest this please

**Comment by kamalcph** [comment]
retest this please.

**Comment by kamalcph** [comment]
Test case failures are not related.

**Review by omkreddy — COMMENTED** [review]
@kamalcph Thanks for the PR. LGTM.

**Pull request closed without merging**
