### PR TITLE
KAFKA-7660: fix streams and Metrics memory leaks

### PR DESCRIPTION
**Pull request by vvcephei**
Backport two memory-leak fixes (#5974 and #5953) (see also 2.1: #5979)

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@mjsax @guozhangwang , This is a further backport of a couple of small memory-leak fixes from trunk.

I'm not sure if you want to keep them as separate commits in the backport as well...

**Comment by vvcephei** [comment]
@ijuma I'm not sure who to ask about this; asking you because you've weighed in on a few build configuration issues I've seen...

It looks like the JDK10 build may be misconfigured:
```
00:01:16.561 * What went wrong:
00:01:16.561 Task 'findbugsMain' not found in root project 'kafka-pr-jdk10-scala2.12'.
```

I'm wondering if we want to go ahead and bump 2.0 builds up to jdk11? I think we were only testing jdk10 provisionally until jdk11 got released.

**Comment by mjsax** [comment]
Retest this please

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
@vvcephei thanks for the heads-up. I disabled findBugs in the Java 10 PR build since findBugs doesn't work with Java 9+. We can't support Java 11 in the older branches without backporting a lot of changes and we don't want to do that. Please let me know if there are still problems.

**Comment by vvcephei** [comment]
Thanks @ijuma !

**Comment by vvcephei** [comment]
Thanks, @mjsax !

**Pull request merged**
