### PR TITLE
KAFKA-14863: Hide plugins with invalid constructors during plugin discovery

### PR DESCRIPTION
**Pull request by gharris1727**
The construction of reflectively-discovered plugin objects only takes place for connectors, leaving all other types to discover these reflective errors at runtime. Instead of advertising these known-bad connectors, hide them completely after plugin discovery has completed.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by C0urante — COMMENTED** [review]
The implementation and tests here look fine 👍

One issue I'm grappling with is whether this makes it harder for users to understand errors with plugin packaging. Can you describe the impact on users with this change if a plugin with no valid constructor is present on the worker?

One alternative I'm considering is if we try to make more plugins visible, even if they cannot be used, if that ultimately makes it easier for users to diagnose issues with them (a stack trace from a REST request is often more informative than a message in the worker's logs).

Also, can you shed some light on the implications this has for [KIP-898](https://cwiki.apache.org/confluence/display/KAFKA/KIP-898%3A+Modernize+Connect+plugin+discovery)? For example, will the behavior of the migration script change?

**Comment by gharris1727** [comment]
> Can you describe the impact on users with this change if a plugin with no valid constructor is present on the worker?

Suppose you had a Connector without a valid constructor.

1. Before KAFKA-14649, your worker would crash on plugin path scanning with an opaque error.
2. After KAFKA-14649, the worker logs an informative error, hides the plugin with a 404 in the REST API and throws ClassNotFoundExceptions for existing connector instances.

Suppose you had a Converter without a valid constructor.

1. Before KAFKA-14863 (this change), the worker would not crash or log an error. The plugin would be visible in the REST API, and would throw an opaque NoSuchMethodException if used in existing connectors.
2. After KAFKA-14863 (this change), the worker logs an informative error, hides the plugin with a 404 in the REST API, and throws ClassNotFoundExceptions for existing connectors that use this converter.

> One alternative I'm considering is if we try to make more plugins visible, even if they cannot be used, if that ultimately makes it easier for users to diagnose issues with them (a stack trace from a REST request is often more informative than a message in the worker's logs).

While this is reducing the diagnostic information present in the REST API (ClassNotFoundException is less specific than NoSuchMethodException) it is making the REST API more consistent (a class that throws ClassNotFoundException in validate is also a 404 on the plugins endpoint). I don't think it's inappropriate to have users diagnose startup packaging problems with error logs, especially when the REST API information before was rather opaque. 

The trouble with keeping the current reflective behavior (showing plugins with bad constructors) is that it is difficult to replicate with the ServiceLoader. From the ServiceLoader interface, we do not see the implementation's class name until after the static initializer and constructor has completed without error. If we wished to collect the class name information for badly packaged plugins (instead of just hiding them) we'd be required to fork the ServiceLoader or depend on error messages to extract class names.

> Also, can you shed some light on the implications this has for [KIP-898](https://cwiki.apache.org/confluence/display/KAFKA/KIP-898%3A+Modernize+Connect+plugin+discovery)? For example, will the behavior of the migration script change?

1. Without KAFKA-14863 (this change), the migration script produces an "incomplete" migration. Even if the migration script generated an appropriate ServiceLoader manifest, the plugin would appear as if no migration took place. Assertions that all plugins were migrated would fail.
2. With KAFKA-14863 (this change), the migration script hides and does not migrate plugins which are missing a valid constructor. After a migration is complete, all plugins which are present on the REST API before migration are present after, so assertions that all plugins were migrated would pass.

This is the core motivation of this PR: the reflective scanning and ServiceLoader scanning error handling should have parity, so that plugins which are not usable with the ServiceLoader aren't migrated, and the migration script still includes all of the plugins which are visible in the REST API. If we drop one of these two properties, then the migration looks incomplete to the user.

I examined some plugin implementations out in the wild, and observed that plugins which are packaged and don't have a valid constructor often appear in the REST API accidentally. For example, many packaged SMTs have concrete base classes without a valid constructor, intending instead to be referenced via their `$Key` or $`Value` subclasses. This change is de-cluttering the REST API of all of these unintentionally-concrete classes, each of which would cause poor migration behavior.

**Comment by C0urante** [comment]
Hmm... I don't necessarily agree that parity between the plugin discovery mechanisms warrants degrading the behavior of one to match the other.

I do agree that the new log messages about poorly-packaged plugins here are informative, so it would be nice to include those changes regardless of whether we opt to hide them from the REST API. We could even include those messages in REST API errors when users try to use poorly-packaged plugins.

It's also valid to emit these kinds of warning messages in the migration script, which should give users plenty of context about why a connector that appeared visible with plugin scanning discovery would no longer be visible with service loading discovery.

Finally, while it may be a poor experience for users to see that a plugin has disappeared after migrating to service loading, this change doesn't actually prevent that experience, it only changes when it takes place. Instead of seeing plugins disappear after a migration, they'll see it whenever they perform an upgrade of their Connect cluster. Good logging by the migration script about invalid plugins being skipped is more likely to be noticed by users than worker startup logs (which tend to be quite verbose and are frequently only consulted after something has already broken, oftentimes as a last resort).

**Comment by gharris1727** [comment]
> It's also valid to emit these kinds of warning messages in the migration script, which should give users plenty of context about why a connector that appeared visible with plugin scanning discovery would no longer be visible with service loading discovery.

I will certainly add these sorts of errors to the diagnostic/migration script added in KIP-898. While this change is making it marginally harder to debug these packaging errors via the REST API, users should find it easier overall to debug these via log messages and command-line tooling.

> Instead of seeing plugins disappear after a migration, they'll see it whenever they perform an upgrade of their Connect cluster.

Yes, this is the intended behavior of this change. I think this is reasonable, because every invalid constructor plugin is in one of the following categories:

#### Not intended to be usable in the runtime

These could be in situations where a developer needs an instance that they can instantiate (such as in composition) but doesn't want users to be able to use them. Because they are not intended to be used, they should not appear in the REST API or be discovered during scanning, so having them hidden after an upgrade is desirable.

#### Intended to be usable in the runtime

These are quickly discovered in development/release testing, as the first person to use the plugin with the Connect runtime will discover that their plugin is not visible. In this environment, we can expect that the developer will have access to worker logs in order to diagnose why their plugin isn't visible. 

I expect that there are very few released artifacts which have these plugins, and that optimizing for the operator's REST-API debugging after an upgrade but before using SERVICE_LOAD is not worth the inconsistency and complication. This isn't just about parity between Reflection and ServiceLoader, it's also about parity between Connectors and other plugins, and about parity between different types of packaging errors (which generally produce logs + hide plugins). Maintaining a carve-out for this one type of error, in one particular scanning paradigm, for some plugins and not others is not helpful, it's just confusing.

And as a side-effect, if you add Versioned to a non-connector plugin, that version is now shown!

**Review by C0urante — APPROVED** [review]
Thanks Greg, LGTM

**Comment by dajac** [comment]
@gharris1727 @C0urante Recent builds have failure related to plugins loading. Example: https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-13804/1/tests. Could they be related to this PR? It seems that the last
build of this PR also have them.

**Comment by gharris1727** [comment]
@dajac Thanks for pointing this out. This PR is certainly the cause, and it appears to be some tests which didn't get updated to compensate for this new behavior.

I've opened a quick fix here: https://github.com/apache/kafka/pull/13805

**Comment by dajac** [comment]
Thanks @gharris1727 for the quick fix! Let’s try to better verify failed tests before merging next time.

**Comment by C0urante** [comment]
Sorry @dajac, I've been making a point of reading test results before merging lately but this slipped past somehow. I'll look at Greg's fix today.

**Pull request merged**
