### PR TITLE
MINOR: add spotlessScalaCheck to jenkins job

### PR DESCRIPTION
**Pull request by guozhangwang**
This is related to https://github.com/apache/kafka/pull/5472

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@ewencp @omkreddy for reviews.

**Review by ewencp — APPROVED** [review]
@guozhangwang LGTM once we get to a green build. might want to also give people a heads up somewhere since merging existing PRs that violate the check could be accidentally merged.

**Comment by guozhangwang** [comment]
> @guozhangwang LGTM once we get to a green build. might want to also give people a heads up somewhere since merging existing PRs that violate the check could be accidentally merged.

Ack, I'll send to the dev mailing list.

**Comment by ijuma** [comment]
Why did we add this before checkstyle?

**Pull request merged**
