### PR TITLE
MINOR: enable KRaft in MetadataRequestTest

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by cmccabe** [comment]
Test failure is `ReplicaManagerTest#testReplicaAlterLogDirsWithAndWithoutIds`, which is not related to this PR.

**Review by mumrah — APPROVED** [review]
LGTM. Nice to see the coverage increasing for KRaft :) 

I noticed when running locally, for tests without the parameter given in the method signature, we get generated test names like `[1]` and `[2]`. For cases where "quorum" is declared, we get nicer names like `[1] quorum=zk` and `[2] quorum=kraft`

**Comment by cmccabe** [comment]
Oops, the quorum parameter should be present for all of these. Fixed.

**Comment by cmccabe** [comment]
Failed tests are `org.apache.kafka.streams.integration.StoreQueryIntegrationTest` and kafka.admin.LeaderElectionCommandTest`, which are not related.

**Pull request merged**
