### PR TITLE
MINOR: update consumer javadoc for position method

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by omkreddy** [comment]
@hachikuji  trivial doc change related to previous PRs

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
@omkreddy actually, the overload has to be updated as well.

**Comment by omkreddy** [comment]
@ijuma looks like overload method is up to date.  Let me know, If I missed anything.

**Comment by omkreddy** [comment]
@ijuma Can you merge this trivial change?

**Review by hachikuji — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
