### PR TITLE
MINOR: Change type of StreamsConfig.BOOTSTRAP_SERVERS_CONFIG to List

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
To be consistent with other configs. cc @ijuma

**Comment by ijuma** [comment]
LGTM

**Comment by ijuma** [comment]
Actually, I think we should have a test for this. It's a bit odd that not even one of the stream integration tests have more than one broker, no? cc @enothereska

**Comment by ijuma** [comment]
I had a look and it's easy to add a test in `StreamsConfigTest` that throws a ClassCastException before this change by using `getList` on the `bootstrap.servers` property.

**Comment by miguno** [comment]
An updated version of this PR, including a unit test, is available at https://github.com/apache/kafka/pull/1377.

**Comment by miguno** [comment]
@guozhangwang: You can close this PR.

**Comment by guozhangwang** [comment]
Thanks @miguno

**Pull request closed without merging**
