### PR TITLE
KafkaAdminClient should remove inflight call correctly after response is received

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by lindong28** [comment]
I will add the test for this bug later.

**Comment by ijuma** [comment]
It's already fixed here https://github.com/apache/kafka/pull/3584

**Comment by lindong28** [comment]
@ijuma Thanks for the quick notice.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6634/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6619/
Test PASSed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
