### PR TITLE
KAFKA-8390: Use automatic RPC generation in CreateDelegationToken

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by abbccdda** [comment]
Retest this please

**Comment by mimaison** [comment]
Just rebased on trunk

**Comment by mimaison** [comment]
Retest this please

**Comment by mimaison** [comment]
@hachikuji @cmccabe Can you take a look please?

**Review by omkreddy — APPROVED** [review]
@mimaison Thanks for the PR. LGTM. will merge after running system test

**Comment by mimaison** [comment]
@omkreddy Thank you! I'll get started onto the other DelegationTokens APIs now.

**Pull request merged**
