### PR TITLE
KAFKA-16643 Add ModifierOrder checkstyle rule

### PR DESCRIPTION
**Pull request by gongxuanzhang**
@gharris1727     https://github.com/apache/kafka/pull/15812
I modified all the non-standard code according to the rules of ModifierOrder, and I divided it into multiple commits by module for better code review
Additional,I modified a scala file to follow the java specification.I don't know if that's right

### CODE REVIEW

**Comment by chia7712** [comment]
@gongxuanzhang thanks for this patch. Could you take a look at https://issues.apache.org/jira/browse/KAFKA-10787? Personally, we should introduce the new checkstyle file. And then we apply it by module to reduce the patch size.

**Comment by gongxuanzhang** [comment]
@chia7712   Yes i do .
I think these changes, though numerous, are still simple changes.
Even with the introduction of new checkstyle file , the style we pursue is always "unity". 
In this PR I have followed the checkstyle ModifierOrder rule and passed the self-test.
Thank you very much for your reply and I hope I can make some contribution to kafka

**Comment by chia7712** [comment]
> In this PR I have followed the checkstyle ModifierOrder rule and passed the self-test.

We need the checkstyle first, because it is hard to review those huge changes by human eyes 😀 

> Thank you very much for your reply and I hope I can make some contribution to kafka

Welcome to Kafka community. Please try to add new checkstyle import rules to small module. I'd like to review them for you 😄

**Comment by gongxuanzhang** [comment]
@chia7712 
I will resubmit my PR, introduce the new checkstyle and re-modify the PR according to the module.
Thank you for your patience and best wishes

**Comment by gongxuanzhang** [comment]
@chia7712 
I add rule into checkstyle.xml 
```
<module name="ModifierOrder"/>
```

you can  run  
```
./gradlew checkstyleMain checkstyleTest --continue
```

**Comment by chia7712** [comment]
@gongxuanzhang This is still a huge patch, which contains a log of changes across all modules. This is a important improvement which can impact all Kafka developers, and so we should separate it to small PRs.

Personally, the first patch should include 1) new checkstyle and 2) auto formatter ( see https://issues.apache.org/jira/browse/KAFKA-12572)

After first patch gets merged, we can apply the rule to all modules "one by one".  Yes, it needs many PRs but they make reviews workable.

**Comment by gongxuanzhang** [comment]
@chia7712 
I get it!
But I'm confused. Is there anything I can do about it

**Comment by chia7712** [comment]
> But I'm confused. Is there anything I can do about it

@dongjinleekr had filed a PR (#10428) to be the start. However, the PR gets conflicts now, and not sure whether @dongjinleekr has free cycles to address it. You can file a new PR to address that.

**Comment by chia7712** [comment]
@gongxuanzhang could you fix the conflicts? Also, please revert the unrelated changes. thanks!

**Comment by chia7712** [comment]
@gongxuanzhang please fix the build error

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
