### PR TITLE
MINOR: optimize unrecordedVoters method

### PR DESCRIPTION
**Pull request by dengziming**
Just as `grantingVoters()` and `rejectingVoters()`, `unrecordedVoters()` method be optimezed by using `votersInState(State)`

### CODE REVIEW

**Comment by dengziming** [comment]
@hachikuji  , PTAL

**Review by chia7712 — APPROVED** [review]
@dengziming Nice refactor. LGTM

**Comment by chia7712** [comment]
@dengziming I believe those failed tests are unrelated to your PR but could you rebase it to trigger QA again ?

**Comment by chia7712** [comment]
@dengziming Thanks for your patch!

**Pull request merged**
