### PR TITLE
[KAFKA-4696] Streams standby task assignment should be state-store aware

### PR DESCRIPTION
**Pull request by ConcurrencyPractitioner**

### CODE REVIEW

**Comment by ConcurrencyPractitioner** [comment]
@guozhangwang Instead of including the number of state stores in ```Metadata```, I decided to add it in  ```TaskId```. Since ```TaskId``` is a parameter of ```StreamTask``` during initialization, I though this was appropiate.

**Comment by mjsax** [comment]
Just adding a new field to `TaskId` is not sufficient. The consumer rebalance metadata must encode this information, too. (cf. `SubscriptionInfo`).

However, change the binary format of `SubscriptionInfo` requires to bump the version number as well as a defined upgrade protocol -- otherwise, upgrade an application would crash. Thus, we need a KIP.

Btw: we are working on another change that also requires to change the metadata and we are already working on a KIP. If we delay this, you can picky back on the change we plan to anyway. Bumping the metadata version number is a critical change as it might break the upgrade path of not done right.

**Comment by guozhangwang** [comment]
@ConcurrencyPractitioner One thing we did not discuss on the JIRA ticket is that changing the rebalance protocol's metadata encoding requires bumping up the protocol version, AND as well as designing the upgrade path (consider a rolling bounce to upgrade from 1.0 to 1.2 that contains the new format, the first bounced instance would send the join group request with new formatted metadata that the existing leader who's still on the older version would not recognize at all).

We are working on a general framework for such an upgrade path right now, and I think it is better to hold on this PR until that is done.

**Comment by ConcurrencyPractitioner** [comment]
I have created KAFKA-6583 to update metadata. So until then, I will wait.

**Comment by ConcurrencyPractitioner** [comment]
@mjsax Can KAFKA-6583 and KAFKA-4696 be combined in one PR? I think it would be more convenient to resolve both pull requests in one patch if possible.

**Comment by ConcurrencyPractitioner** [comment]
My current branch was cloned before the metadata upgrade path was pushed. I modified a couple of the classes since it appears that my patch was not compatible with the current metadata upgrade path. Due to some changes, I think that is why there is merge conflicts.

**Comment by mjsax** [comment]
About one or two PRs: I personally don't have a strong opinion -- both seems to be quite related, so from my point of view, a single PR might be fine (\cc @guozhangwang WDYT?)

To resolve merge conflict, you need to rebase your PR to `trunk`.

Note, KIP-268 is not merged yet -- thus, you might want to wait rebasing this PR until everything is merged -- otherwise, you will need to rebase multiple times (it's up to you of course).

**Comment by ConcurrencyPractitioner** [comment]
Migrating to new PR, current branch is too old.

**Comment by mjsax** [comment]
Replaced by #5012

**Pull request closed without merging**
