### PR TITLE
MINOR: disable flaky Streams EOS system tests

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang

**Comment by mjsax** [comment]
@bbejeck @dguy @ijuma Should we merge this to disable the tests? Or does anybody has time to look into them?

**Comment by bbejeck** [comment]
@mjsax I've been looking into this test, but I think we should merge the disabled tests, as it's not quickly apparent to me why this is failing, all expected output is present.

**Review by ijuma — APPROVED** [review]
LGTM. Please file a JIRA to re-enable these system tests with 1.1.0 as the fix version.

**Pull request merged**
