### PR TITLE
MINOR: Fix potential resource leak in FileOffsetBackingStore

### PR DESCRIPTION
**Pull request by asasvari**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

Ran unit tests. 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by asasvari** [comment]
retest this, please

**Comment by smurakozi** [comment]
nice catch @asasvari

I think this change is OK.

**Review by smurakozi — COMMENTED** [review]
nice catch @asasvari

I think this change is OK, but you may want to fix the message of the PR.

**Comment by asasvari** [comment]
retest this please

**Comment by asasvari** [comment]
@smurakozi thanks for the review. I thought it was not necessary, as it is just a minor modification. I am going to update the pull request message adding that unit tests passed.  
@hachikuji can you take a look at the change?

**Review by hachikuji — APPROVED** [review]
LGTM. Nice catch!

**Pull request merged**
