### PR TITLE
MINOR: Add releaseTarGz to args for building docs

### PR DESCRIPTION
**Pull request by bbejeck**
This PR adds the `releaseTarGz` command back into the `release.py::command_stage_docs` method when building docs for staging

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks. What happens without this?

**Comment by bbejeck** [comment]
>What happens without this?

The method fails on this line `cmd('Extracting site-docs', 'tar xf %s --strip-components 1' % docs_tar, cwd=versioned_docs_path)` 

Because even if you ran `releaseTarGz` separately ahead of time, the `clean` before calling `aggreagateJavadoc` wipes everything out, so the `tar` command can't find the `site-docs` file

**Comment by ijuma** [comment]
@bbejeck do we need the clean?

**Comment by bbejeck** [comment]
> do we need the clean?

No, but I think the `release.py::stage-docs` makes more sense to have the `releaseTarGz` target and run clean beforehand.  
If you prefer to leave it out, I can amend the PR to remove the `clean`

**Comment by ijuma** [comment]
Would it be enough to call `siteDocsTar` instead? It's weird to generate the release tarball to just get the site docs.

**Comment by bbejeck** [comment]
>Would it be enough to call siteDocsTar instead?

Yeah, my bad that makes more sense

**Comment by bbejeck** [comment]
updated this

\cc @ijuma

**Review by ijuma — APPROVED** [review]
LGTM if we tested this and it works correctly.

**Comment by bbejeck** [comment]
test locally and works as expected

**Comment by bbejeck** [comment]
only a python file so merging now

**Pull request merged**
