### PR TITLE
MINOR: Update to Gradle 2.8

### PR DESCRIPTION
**Pull request by ijuma**
There have been a number of improvements between the version we are currently using (2.4) and the current version (2.8):

https://gradle.org/docs/2.5/release-notes
https://gradle.org/docs/2.6/release-notes
https://gradle.org/docs/2.7/release-notes
http://gradle.org/docs/current/release-notes

I'm particularly interested in the performance improvements.

### CODE REVIEW

**Comment by ijuma** [comment]
Trivial one-liner that gives us better compilation speed, @guozhangwang or @gwenshap, any of you interested in merging this? Thanks.

**Comment by guozhangwang** [comment]
@ijuma Do we want to change this line in `gradle-wrapper.properties` also? 

distributionUrl=https://services.gradle.org/distributions/gradle-2.4-bin.zip

**Comment by ijuma** [comment]
@guozhangwang I think that file is not in Git, it gets updated automatically when you run `gradle`. My file has:

distributionUrl=https://services.gradle.org/distributions/gradle-2.8-bin.zip

and git status shows no changes.

**Comment by guozhangwang** [comment]
ah that makes sense. LGTM.

**Pull request closed without merging**
