### PR TITLE
KAFKA-14599 Enable javadoc for :connect:mirror module

### PR DESCRIPTION
**Pull request by nizhikov**
Currently, javadoc task disabled for `:connect:mirror` module.
This PR enables it.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
@nizhikov Thanks for looking at this issue. I don't think we can simply enable the javadoc on the `connect:mirror` project as it will also include all public classes from that module that are not part of the public API. We only want to include the interfaces users can implement. 

We should be able to use a filter to select the classes to include. Otherwise I wonder if we could move the classes we want to the mirror-client module. The package should be the same, and as mirror depends on it, it should hopefully not break anything.

**Comment by nizhikov** [comment]
@mimaison Thanks for the review.

What about *Config classes? like `MirrorCheckpointConfig` or `MirrorConnectorConfig`.
Are they part of public API?
Should I move them to mirror-client?

**Comment by mimaison** [comment]
The Config classes are not part of the public API. I suggested moving the interfaces without thinking too much about it, have you considered if this could break anything?

**Comment by nizhikov** [comment]
I can only imagine users who excluded mirror-client dependency for whatever reason :)
Don't think we should consider such case as a blocker.

**Comment by nizhikov** [comment]
Hello @mimaison 

Do we still want to fix javadoc for public interfaces?

**Comment by mimaison** [comment]
Sorry for the delay. I _think_ you technically don't necessarily need to have transitive dependencies in the classpath to compile a class. For example, it is possible to build a custom `TopicFilter` without having `mirror-client` in the classpath. For that reason, in theory, this change could break some users.

So can you try to keep the classes in mirror, otherwise we'll need a small KIP.

**Comment by nizhikov** [comment]
@mimaison Thanks for the feedback.

> So can you try to keep the classes in mirror

I updated PR according to your proposal.
javadoc generation enabled only for 3 public API classes in mirror module.

**Comment by mimaison** [comment]
Thanks @nizhikov for the update.

When I run `./gradlew aggregatedJavadoc`, the generated javadoc (under `./build/docs/javadoc/`) contain all classes from mirror, so something is not quite right.

**Pull request closed without merging**
