### PR TITLE
KAFKA-4623: Change default unclean.leader.election.enabled from True to False

### PR DESCRIPTION
**Pull request by sharad-develop**
KAFKA:4623- Change default unclean.leader.election.enabled from True to False

### CODE REVIEW

**Comment by sharad-develop** [comment]
This fixes KAFKA-4623.
JDK 8 and Scala 2.12 test is failing which looks like an infrastructure and is unrelated.

**Comment by mjsax** [comment]
Please update the PR title to `KAFKA-4623: Change default unclean.leader.election.enabled from True to False` to allow the bot to auto link it to the JIRA

**Comment by ijuma** [comment]
Thanks for the PR. Can you also add a note to `docs/upgrade.html` explaining the change?

**Comment by ijuma** [comment]
Queued a system tests build, once it starts the following link will work:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder-2/280/

**Review by ijuma — APPROVED** [review]
LGTM, system tests passed and I added a note to the upgrade notes before merging.

**Pull request closed without merging**
