### PR TITLE
MINOR: Various cleanups in trogdor

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
Could you rebase code to trigger QA for `JDK 17 and Scala 2.13`? the build is not completed

**Comment by mimaison** [comment]
Thanks for the review!
No need to rebase, you can just log into Jenkins with your Apache credentials and rekick the build. I went to https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-15708/2/ and clicked the "Rebuild" button on the left side.

**Comment by chia7712** [comment]
> No need to rebase, you can just log into Jenkins with your Apache credentials and rekick the build. I went to https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-15708/2/ and clicked the "Rebuild" button on the left side.

thanks for sharing this to me :)

**Pull request merged**
