### PR TITLE
MINOR: Add @Timeout annotation to consumer integration tests

### PR DESCRIPTION
**Pull request by dajac**
In this [buid](https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-14826/11/pipeline/12/), the following test hang forever.

```
Gradle Test Run :core:test > Gradle Test Executor 93 > PlaintextConsumerTest > testSeek(String, String) > testSeek(String, String).quorum=kraft+kip848.groupProtocol=consumer STARTED
```

As the new consumer is not extremely stable yet, we should add a Timeout to all those integration tests to ensure that builds are not blocked unnecessarily.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by AndrewJSchofield — APPROVED** [review]
lgtm

**Comment by jolshan** [comment]
Hmmm -- are we concerned with introducing these new test failures? I agree a timeout is good, but I'm wondering if there is a way we could suppress these failures for PR builds.

**Comment by jolshan** [comment]
I've also been seeing more failed builds --

```
* What went wrong:

Execution failed for task ':streams:upgrade-system-tests-25:test'.

> Process 'Gradle Test Executor 9' finished with non-zero exit value 1

  This problem might be caused by incorrect test process configuration.
  ```
  
  From this PR -- is it possible the new consumer could be throwing errors that cause test issues like this? I know it should be on the test to handle errors in a way that doesn't kill the build, but I have been seeing many failed builds due to these issues or GC/OOM issues.

**Review by jolshan — APPROVED** [review]
LGTM -- but I have some followup comments

**Pull request merged**
