### PR TITLE
KAFKA-17640: Document Java 23 support and include release note

### PR DESCRIPTION
**Pull request by fonsdant**

### CODE REVIEW

**Comment by chia7712** [comment]
@fonsdant could you please update the title? Additionally, we don't have CI for JDK 23, so it's not the right time to declare support for Java 23.

**Comment by fonsdant** [comment]
Oh, sorry! Of course, I'm going to update the title. I have forgot it. Thanks!

**Comment by fonsdant** [comment]
@chia7712, where could I put the release note?

**Comment by chia7712** [comment]
> where could I put the release note?

https://github.com/apache/kafka/blob/trunk/docs/upgrade.html#L107

By the way, I don't think this PR can be merged right now due to the previous comment: https://github.com/apache/kafka/pull/17403#issuecomment-2398647474. Could you please change it to a draft?

**Comment by fonsdant** [comment]
Sure! Thanks again!

**Comment by chia7712** [comment]
@fonsdant could you please rebase code?

**Comment by fonsdant** [comment]
@chia7712, rebase done! One question: I have found that Java 11 will be removed in 4.0.0 version, like we can see below:

```html
<h5><a id="upgrade_370_notable" href="#upgrade_370_notable">Notable changes in 3.7.0</a></h5>
    <ul>
        <li>Java 11 support for the broker and tools has been deprecated and will be removed in Apache Kafka 4.0. This complements
            the previous deprecation of Java 8 for all components. Please refer to
            <a href="https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=284789510">KIP-1013</a> for more details.
        </li>
```

But the 4.0.0 release notes only mentions Java 8 support removal:

```html
<li>Other changes:
            <ul>
                <li>
                    Scala 2.12 support has been removed in Apache Kafka 4.0
                    See <a href="https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=181308218">KIP-751</a> for more details
                </li>
                <li>
                    Java 8 support has been removed in Apache Kafka 4.0
                    See <a href="https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=181308223">KIP-750</a> for more details
                </li>
```

**Comment by chia7712** [comment]
> I have found that Java 11 will be removed in 4.0.0 version, like we can see below:

I prefer to update the docs after we do remove the JDK 11 from server-side :)

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by fonsdant** [comment]
Thanks, @chia7712! :) 

Sorry for the delay.

**Pull request merged**
