### PR TITLE
KAFKA-8210: Fix link for streams table duality

### PR DESCRIPTION
**Pull request by bbejeck**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @JimGalasyn @MichaelDrogalis @mjsax

**Comment by JimGalasyn** [comment]
cc @londoncalling

**Review by londoncalling — APPROVED** [review]
LGTM @JimGalasyn , link works!

**Comment by bbejeck** [comment]
Merged #6573 into trunk

**Comment by mjsax** [comment]
@bbejeck If the link is broken in older release, we should cherry-pick this to older branches, too. Otherwise, we get the broken link again when we do a bug fix release.

**Comment by bbejeck** [comment]
cherry-picked to 2.2, 2.1 and 2.0

**Pull request merged**
