### PR TITLE
MINOR: Update jetty, jackson, gradle and jacoco

### PR DESCRIPTION
**Pull request by ijuma**
- Gradle update adds support for Java 10
- Jacoco update adds support for Java 9
- Jackson bug fix update adds more serialization
robustness checks
- Jetty bug fix update

Relying on existing tests for verification.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
It would be good to double commit this to 1.1.

**Comment by ijuma** [comment]
cc @guozhangwang for the Jacoco upgrade.

**Review by rajinisivaram — APPROVED** [review]
@ijuma Thanks for the PR, LGTM.

**Comment by guozhangwang** [comment]
> cc @guozhangwang for the Jacoco upgrade.

LGTM!

**Pull request merged**
