### PR TITLE
MINOR: correctly set dev version

### PR DESCRIPTION
**Pull request by vvcephei**
When the version was bumped to 2.1.1-SNAPSHOT, this one was missed, causing system tests to fail.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Running system tests...

Streams upgrade test x20: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2314/
All streams tests x5: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2315/
* passed: http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2019-02-01--001.1549030365--vvcephei--fix-2.1-system-tests--f5db5dd/report.html
All tests x3: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2316/

**Comment by vvcephei** [comment]
@cmccabe @yangxi @guozhangwang ,

Please take a look at this fix for many of the recent 2.1 system test failures.

For some reason I wasn't able to get the 2.1 system tests to run on my machine, so I'm waiting for the above jobs to finish to find out if this works.

Thanks,
-John

**Review by ijuma — APPROVED** [review]
LGTM

**Review by viktorsomogyi — COMMENTED** [review]
Nice to see this, I also ran the ducktapes in order to test the release but I came to realize in the morning that a bunch of streams test failed because of this. I'll rerun them. But otherwise LGTM :)

**Comment by vvcephei** [comment]
The tests are still running, but it looks like it worked:
```
[INFO:2019-02-01 01:23:27,687]: Triggering test 11 of 1820...
[INFO:2019-02-01 01:23:27,708]: RunnerClient: Loading test {'directory': '/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/tests/kafkatest/tests/streams', 'file_name': 'streams_upgrade_test.py', 'method_name': 'test_metadata_upgrade', 'cls_name': 'StreamsUpgradeTest', 'injected_args': {'to_version': '2.1.1-SNAPSHOT', 'from_version': '0.10.0.1'}}
[INFO:2019-02-01 01:23:27,728]: RunnerClient: kafkatest.tests.streams.streams_upgrade_test.StreamsUpgradeTest.test_metadata_upgrade.to_version=2.1.1-SNAPSHOT.from_version=0.10.0.1: Setting up...
[INFO:2019-02-01 01:23:27,729]: RunnerClient: kafkatest.tests.streams.streams_upgrade_test.StreamsUpgradeTest.test_metadata_upgrade.to_version=2.1.1-SNAPSHOT.from_version=0.10.0.1: Running...
[INFO:2019-02-01 01:25:00,687]: RunnerClient: kafkatest.tests.streams.streams_upgrade_test.StreamsUpgradeTest.test_metadata_upgrade.to_version=2.1.1-SNAPSHOT.from_version=0.10.0.1: PASS
```

**Comment by vvcephei** [comment]
@ijuma : 

Is there a process for updating all the versions numbers when we bump them? We should add this one to the list.

I wrote a script to do the find-and-replace automatically; not sure if it would be of interest...

Thanks for the review,
-John

**Comment by ijuma** [comment]
@vvcephei we mention the places in the release plan and gradle.properties

**Pull request merged**
