### PR TITLE
[KAFKA-6265] GlobalKTable missing #queryableStoreName()

### PR DESCRIPTION
**Pull request by ConcurrencyPractitioner**
A spinoff of original pull request #4340 for resolving conflicts.

### CODE REVIEW

**Comment by ConcurrencyPractitioner** [comment]
@guozhangwang  I will be moving to this branch to resolve conflicts.

**Comment by ConcurrencyPractitioner** [comment]
@guozhangwang  I ran ```git pull apache trunk```, and after resolving conflicts, I ran ```git add docs/streams/upgrade-guide.html``` and ```git rm docs/streams/developer-guide.html```; swiftly followed by ```git commit -m ...``` and ```git push origin .... ```. Yet, I don't think this was any different from the situation we had with the previous PR.

**Comment by guozhangwang** [comment]
The changes in `docs/streams/upgrade-guide.html` should still be removed.

**Comment by ConcurrencyPractitioner** [comment]
Some of the changes in ````docs/streams/upgrade-guide.html``` is still wanted per @mjsax 's comments.

**Comment by guozhangwang** [comment]
LGTM! Merged to trunk. Thanks @ConcurrencyPractitioner

**Pull request closed without merging**
