### PR TITLE
 KAFKA-15093: Add 3.5 Streams upgrade system tests 

### PR DESCRIPTION
**Pull request by mimaison**
Extracted the 3.5 changes from https://github.com/apache/kafka/pull/13860

Only merge this PR after https://github.com/apache/kafka/pull/14601 is merged

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mjsax — APPROVED** [review]

**Comment by mimaison** [comment]
Backported to 3.5 and 3.6

**Comment by mjsax** [comment]
Why backport to `3.5` ? That's not necessary -- we test upgrade to `DEV_VERSION` what is `3.5.x-SNAPSHOT` -- no need to double test.

**Comment by mimaison** [comment]
Are we ok keeping the commit or should we revert it?

**Comment by mjsax** [comment]
I think it would be good to revert? System test run already very long, and if we can cut down a few minutes by not re-running the same test twice, it might be good?

**Comment by mimaison** [comment]
Ok, I'll revert d769f1dd87 in the 3.5 branch.

**Comment by mimaison** [comment]
Done

**Pull request merged**
