### PR TITLE
MINOR: fix EOS test race condition

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
System test run: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1097/

**Comment by mjsax** [comment]
Call for review @guozhangwang @dguy @bbejeck

**Comment by bbejeck** [comment]
Since read from main thread but modified the shutdown thread, update declaration of `isRunning` to include `volatile`?

**Comment by mjsax** [comment]
Updated.

**Comment by dguy** [comment]
Looks like it failed again:
```
07:27:49 [INFO:2017-10-10 07:27:45,810]: RunnerClient: kafkatest.tests.streams.streams_eos_test.StreamsEosTest.test_failure_and_recovery_complex: FAIL: 
07:27:49 Traceback (most recent call last):
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.7.1-py2.7.egg/ducktape/tests/runner_client.py", line 132, in run
07:27:49     data = self.run_test()
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.7.1-py2.7.egg/ducktape/tests/runner_client.py", line 185, in run_test
07:27:49     return self.test_context.function(self.test)
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/tests/kafkatest/tests/streams/streams_eos_test.py", line 92, in test_failure_and_recovery_complex
07:27:49     StreamsComplexEosTestVerifyRunnerService(self.test_context, self.kafka))
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/tests/kafkatest/tests/streams/streams_eos_test.py", line 109, in run_failure_and_recovery
07:27:49     self.abort_streams(processor1, processor3, processor2)
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/tests/kafkatest/tests/streams/streams_eos_test.py", line 154, in abort_streams
07:27:49     self.wait_for_startup(monitor2, keep_alive_processor2)
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/tests/kafkatest/tests/streams/streams_eos_test.py", line 158, in wait_for_startup
07:27:49     self.wait_for(monitor, processor, "StateChange: RUNNING -> REBALANCING")
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/tests/kafkatest/tests/streams/streams_eos_test.py", line 165, in wait_for
07:27:49     err_msg=("Never saw output '%s' on " % output) + str(processor.node.account))
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.7.1-py2.7.egg/ducktape/cluster/remoteaccount.py", line 668, in wait_until
07:27:49     allow_fail=True) == 0, **kwargs)
07:27:49   File "/home/jenkins/workspace/system-test-kafka-branch-builder/kafka/venv/local/lib/python2.7/site-packages/ducktape-0.7.1-py2.7.egg/ducktape/utils/util.py", line 34, in wait_until
07:27:49     time.sleep(backoff_sec)
```

**Comment by mjsax** [comment]
It says: `07:27:49 KeyboardInterrupt` -- it's not a test failure IMHO. We got 190 runs passed -- I am confident this fix is good.

**Comment by mjsax** [comment]
Retest this please.

**Comment by dguy** [comment]
cool i failed to see that bit! I trust you.

**Comment by mjsax** [comment]
Rebased to latest `trunk`

**Comment by mjsax** [comment]
Triggered whole system test suite: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1100/

**Comment by guozhangwang** [comment]
LGTM! Merged to trunk and 1.0.

Will try to check the trunk build 1100 and have another build out of 1.0 branch.

**Pull request closed without merging**
