### PR TITLE
MINOR: Remove unused LeaderAndIsrResponse.partitions() since it has been replaced with partitionErrors()

### PR DESCRIPTION
**Pull request by rajinisivaram**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by dajac — APPROVED** [review]
LGTM

**Comment by rajinisivaram** [comment]
@dajac Thanks for the review, test failures not related, merging to trunk and 2.8.

**Comment by ijuma** [comment]
The implementation that was removed was more efficient than the new implementation. Is there a reason for that?

**Comment by rajinisivaram** [comment]
@ijuma With the topic ID change, we need to process response data differently based on version. I assumed that was the reason for adding the logic to `LeaderAndIsrResponse.partitionErrors()` rather than doing that while processing `LeaderAndIsrResponse.partitions()` in KafkaController. I believe @jolshan ran microbenchmarks with the PR that made the update.

**Comment by jolshan** [comment]
I did not run a specific benchmark for this method unfortunately. 

The issue with the method is that the return type requires a topic name and we do not have this information from the response alone.

**Comment by rajinisivaram** [comment]
@jolshan This was the change we made: https://github.com/apache/kafka/pull/9626/files#diff-3e042c962e80577a4cc9bbcccf0950651c6b312097a86164af50003c00c50d37. It could have used the old partitions() method since controller has the topic names? I thought the version thing made it messy to put it elsewhere though.

**Comment by jolshan** [comment]
It would have to insert the topic name for each partition. I'm not sure how we would get the topic ID here to get the name. I think the only difference in terms of efficiency with the new method is that we construct the topic partition object in the method instead of after the method. (And of course topic name lookup which is unavoidable)

I think it could also introduce opportunities to misuse the method since for later versions the topic names will be unexpectedly empty.

**Comment by jolshan** [comment]
The old method returned an iterator of this type which doesn't give us enough information
```
 public static class LeaderAndIsrPartitionError implements Message {
        String topicName;   // empty
        int partitionIndex;
        short errorCode;
...
```

**Comment by ijuma** [comment]
The old implementation did not generate a new collection. Is that possible here or not?

**Comment by jolshan** [comment]
Ah I missed the collection generation.

**Comment by jolshan** [comment]
Potentially we could use the `LeaderAndIsrTopicError` that already exists... but that may be complicated for versioning since old versions don't have that. It would lead to two methods and branching paths in the controller.

**Comment by ijuma** [comment]
It's probably ok to leave as it is since these requests will eventually go away and this method is not used in the hot path, but the general pattern we want to follow is avoid generating new collections whenever possible in the request/response classes.

**Pull request merged**
