### PR TITLE
KAFKA-4717: Use absolute paths to files in root directory so all jars include LICENSE and NOTICE files

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@norwood @ijuma @hachikuji Blocker for 0.10.2 since @norwood noticed licensing of connect jars was incorrect. I replaced cases of `..` broadly despite only needing to fix it in a couple of places for the connect jars since the relative paths, especially in the `subprojects` section, are error prone.

It would be nice to make the build fail if a requested file is not found. If anyone knows the gradle magic to make it do that we could avoid issues like this in the future.

**Review by ijuma — APPROVED** [review]
LGTM, assuming you have verified that it fixes the issue. Is there a reason why this is targetting 0.10.2 instead of trunk (we need them in both, I assume)?

**Comment by ewencp** [comment]
I can move it over to trunk, I forgot about the auto closing thing and followed my normal process of building patches against the oldest release I want them in.

I did verify that the connect jars now have the two files and others, like the clients jar, still have both. I did not do more extensive comparison to verify all the other contents remain the same.

**Comment by ewencp** [comment]
Not entirely happy with the Jenkins output, but merging this to trunk, 0.10.2, and 0.10.1 as those are the branches I'd expect might see more releases.

**Pull request closed without merging**
