### PR TITLE
KAFKA-15853: Move KafkaConfig to server module

### PR DESCRIPTION
**Pull request by OmniaGM**
### Notes:
- [x]  Moving any object companion and interfaces that KafkaConfigs depends on outside of core. 
  - `Session`, and `SocketServer ` moved to `org.apache.kafka.network`
  - `AuthorizerUtils` moved to `org.apache.kafka.security.utils`
  - `KafkaRaftServer`, `PasswordEncoder`  moved to `org.apache.kafka.server`
  - `ClientQuotaManagerConfig`, `DynamicConfig`, `ReplicationQuotaManagerConfig`  moved to `org.apache.kafka.server.config`
  - `LogCleaner` moved to `org.apache.kafka.server.config.LogCleanerConfig`. It can't move to `storage` without creating Circular dependency. 
  - `TransactionLogConfig` moved to `org.apache.kafka.coordinator.transaction`
  - `OffsetConfig` moved to `org.apache.kafka.coordinator.group`
  - some of `CoreUtils` functionality is duplicated in `org.apache.kafka.utils`
  - some of `TestUtils` functionality is duplicated in `org.apache.kafka.server.utils`

- [x] Introduce interfaces to reduce moving dependencies out of core and reduce the changes in this pr
  - `ReconfigurableServer` to avoid depending on `Broker` and `Controller` 
  - `DynamicBrokerConfigManager` and `DynamicBrokerConfigBaseManager` to avoid depending directly on `DynamicBrokerConfig` 
  - `KafkaZKClient` to avoid any depend ices on `KafaZKClient`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
Thanks for the PR. 
It's really big, is there a way to split this into smaller PRs? For example we have https://github.com/apache/kafka/pull/15075 in progress to move the ZooKeeper configs.

**Comment by OmniaGM** [comment]
> Thanks for the PR. It's really big, is there a way to split this into smaller PRs? For example we have #15075 in progress to move the ZooKeeper configs.

I can try to break it down, I think some interfaces can move out in separate pr. The problem is that KafkaConfig is imported in many places and depends on too many other classes in core and outside of core. Let me see what I can do.

**Comment by nizhikov** [comment]
Hello @OmniaGM .

As a first step to reduce changes I suggest move `Defaults` object to java code.
This seems pretty simple and reviewable change.

I can prepare PR with those changes.

What do you think?

@mimaison @ijuma Can you, please, share your opinion, also.

**Comment by OmniaGM** [comment]
Thanks @nizhikov Am preparing this already will push it soon

**Comment by OmniaGM** [comment]
> Hello @OmniaGM .
> 
> As a first step to reduce changes I suggest move `Defaults` object to java code. This seems pretty simple and reviewable change.
> 
> I can prepare PR with those changes.
> 
> What do you think?
> 
> @mimaison @ijuma Can you, please, share your opinion, also.

first pr is here #15158, I'll push couple of other prs soon as well

**Comment by OmniaGM** [comment]
I raise the following prs #15158, #15161, #15160 and #15159.
And soon will raise 
1. few prs to Move some deps like `Session`, `SocketServer`, `AuthorizerUtils`, `KafkaRaftServer`, and `PasswordEncoder` 
2. few PRs move the new interfaces to reduce moving dependencies out of core and reduce the changes in this pr
   - `ReconfigurableServer` to avoid depending on `Broker` and `Controller`
   - `DynamicBrokerConfigManager` and `DynamicBrokerConfigBaseManager` to avoid depending directly on `DynamicBrokerConfig`
   - `KafkaZKClient` to avoid any dependices on `KafaZKClient`
 3. After this depends on how big is the remaining changes I can move KafkaConfig object companion first. then keep this pr to only move KafkaConfig class
 
 @mimaison @ijuma @nizhikov WDYT?

**Comment by OmniaGM** [comment]
I published another PR to move only the properties and their docs out of core #15501

**Comment by OmniaGM** [comment]
I am closing this pr as we have been breaking KafkaConfig slowly.

**Pull request closed without merging**
