### PR TITLE
KAFKA-15689: Logging skipped event when expected migration state is wrong

### PR DESCRIPTION
**Pull request by ppatierno**
As described in ticket https://issues.apache.org/jira/browse/KAFKA-15689, this PR fixes the logging of a migration event when the expected migration state is wrong.

### CODE REVIEW

**Comment by ppatierno** [comment]
@showuon maybe you can take a look at this one?

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the improvement!

**Comment by showuon** [comment]
@ppatierno , please resolve the conflicts. Thanks.

**Comment by ppatierno** [comment]
@showuon everything should be ok now. Thanks!

**Comment by showuon** [comment]
@ppatierno , I saw there's compilation error in java 8: https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-14646/3/pipeline

I'm re-running the CI build now.

**Comment by ppatierno** [comment]
I rebased agains trunk. The failure doesn't seem to be related to my change.

**Pull request merged**
