### PR TITLE
KAFKA-9077: Fix reading of metrics of Streams' SimpleBenchmark

### PR DESCRIPTION
**Pull request by cadonna**
With KIP-444 the metrics definitions are refactored. Thus, Streams' SimpleBenchmark needs to be updated to correctly access the refactored metrics.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @guozhangwang @mjsax @vvcephei

**Comment by cadonna** [comment]
System test results can be found here

http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2019-10-29--001.1572363622--cadonna--AK9077-fix-simplebenchmark--0247d92/report.html

**Review by mjsax — APPROVED** [review]
LGTM

**Review by bbejeck — APPROVED** [review]
@cadonna thanks for the fix LGTM

**Comment by guozhangwang** [comment]
LGTM!

**Comment by bbejeck** [comment]
This is a system test and the affected system test passed, so merging now

**Comment by bbejeck** [comment]
Merged #7610 into trunk

**Pull request merged**
