### PR TITLE
KAFKA-9759: Add doc change for KIP-562

### PR DESCRIPTION
**Pull request by abbccdda**
As title suggests, released KIP-562 should be documented.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)
image
image

### CODE REVIEW

**Review by brary — COMMENTED** [review]
@abbccdda I think we can also mention KIP-535 here, as we had first made changes to allow reading from stale stores in KafkaStreams.store() and then we made additional change on this same function to fetch a specific partition(in KIP-562).

So, the doc should mention the deprecation as a result of providing multiple store query parameters, reading from stale stores and from a specific partition being the ones currently available.

**Comment by mjsax** [comment]
@brary -- I did see your comment only after I merged the PR (sorry for that; seems we reviewed it at the same time...). Feel free to do a follow up PR (or maybe @abbccdda want to do a follow up?)

**Comment by abbccdda** [comment]
@mjsax Thanks for the follow-up!

Hey @brary if you have time, feel free to take https://issues.apache.org/jira/browse/KAFKA-9757 as well and coordinate with @vinothchandar to see whether he has already started the effort (which I believe he hasn't). My job was just to ensure a minimum mentioning about KIP-562 for 2.5 here, so feel free to add more details and ping me for review in a separate PR.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.5`

**Comment by brary** [comment]
It's fine @mjsax! I guessed so :)

@abbccdda sure, I can check with Vinoth and add KIP-535 and update for KIP-562 as well.

**Pull request merged**
