### PR TITLE
MINOR: Upgrade gradle to 6.8 and test retry plugin to 1.2.0

### PR DESCRIPTION
**Pull request by ijuma**
Also fix generation of `gradlew` when `APP_HOME` contains a directory with spaces
in its name.

Release notes:
* https://docs.gradle.org/6.8/release-notes.html
* https://github.com/gradle/test-retry-gradle-plugin/releases/tag/v1.2.0

In addition to existing tests, verified that `./gradlewAll jar` succeeds.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
https://github.com/apache/kafka/blob/trunk/gradle/wrapper/gradle-wrapper.properties#L3 need to be updated as well.

**Comment by ijuma** [comment]
Yeah, this is not complete yet (hence the draft status). :)

**Comment by ijuma** [comment]
I updated the PR, but I need to verify that Jenkins handles merged reruns correctly. If not, I will revert that part of the change.

**Comment by ijuma** [comment]
I reverted the flaky test reporting changes and filed a JIRA with the details of what is required (and missing):

https://issues.apache.org/jira/browse/KAFKA-12216

**Comment by ijuma** [comment]
@chia7712 Thoughts on this PR?

**Review by chia7712 — APPROVED** [review]
+1

**Pull request merged**
