### PR TITLE
MINOR: trivial cleanups

### PR DESCRIPTION
**Pull request by dongjinleekr**
1. Remove `ListenerConnectionQuota#listenerPropName`: never used.
2. `MirrorMaker`: remove unused import, `java.util.concurrent.TimeUnit`.
3. `ConsumerBounceTest`: remove unused import, `util.control.Breaks._`.
4. `DynamicConnectionQuotaTest#[testDynamicConnectionQuota, testDynamicListenerConnectionQuota]`: remove unused local variables.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by dongjinleekr** [comment]
Retest this please.

**Comment by dongjinleekr** [comment]
cc / @hachikuji @mjsax @bbejeck

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the cleanup.

**Pull request merged**
