### PR TITLE
KAFKA-16783: Migrate RemoteLogMetadataManagerTest to new test infra

### PR DESCRIPTION
**Pull request by FrankYang0529**
* Replace `TopicBasedRemoteLogMetadataManagerWrapperWithHarness` with `RemoteLogMetadataManagerTestUtils#builder` in `RemoteLogMetadataManagerTest`.
* Use `ClusterTestExtention` for `RemoteLogMetadataManagerTest`.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by showuon — APPROVED** [review]
LGTM! I just saw there are infinite waiting `future.get()` in the code, which is quite scaring to me. I think we can file another PR to improve it, either we add a future.get(30 sec), or we set a global @Timeout tag on the test class to limit the waiting time. WDYT?

**Comment by showuon** [comment]
Failed tests are unrelated.

**Comment by chia7712** [comment]
> I think we can file another PR to improve it, either we add a future.get(30 sec), or we set a global @timeout tag on the test class to limit the waiting time.

I love the idea about global timeout. I will file a jira for it

**Comment by chia7712** [comment]
> I will file a jira for it

https://issues.apache.org/jira/browse/KAFKA-16813

**Pull request merged**
