### PR TITLE
MINOR: Restore scanning for super types of Connect plugins

### PR DESCRIPTION
**Pull request by kkonstantine**
Enabling scans for super types in reflections is required in order to discover Connect plugins.

Smoke tests, system tests, and manual testing. 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kkonstantine** [comment]
cc @ewencp @hachikuji

**Review by rhauch — APPROVED** [review]
Good catch. @dguy, would you mind taking a look and merging so we can fix more system tests?

**Comment by hachikuji** [comment]
Thanks for the PR. Is there any way to verify the change with a unit test?

**Comment by kkonstantine** [comment]
@hachikuji Unit testing is not straightforward here, because we'd need to generate test classes, construct the jars, store them in a temp test folder and run scanning with those urls. We can eventually add something like that but probably not in time for this patch. 

Testing is currently happening with system tests.

**Review by hachikuji — APPROVED** [review]
LGTM. Merging to trunk and 1.1

**Pull request merged**
