### PR TITLE
MINOR: cleanup of some redundant checkstyle

### PR DESCRIPTION
**Pull request by abbccdda**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by abbccdda** [comment]
Retest this please

**Comment by abbccdda** [comment]
Retest this please

**Comment by bbejeck** [comment]
Merged #6950 into trunk.

**Comment by ijuma** [comment]
@bbejeck I assume the commit message was accidental in https://github.com/apache/kafka/commit/b4e20495fa442a4312f946f518541a04fc6efcc9 ?

**Pull request merged**
