### PR TITLE
Cherry-pick KAFKA-7278; replaceSegments() should not call asyncDeleteSegment() for segments which have been removed from segments list

### PR DESCRIPTION
**Pull request by lindong28**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lindong28** [comment]
Ping @hachikuji @dhruvilshah3 for review.

**Comment by hachikuji** [comment]
@lindong28 LGTM. I'll leave you to merge after you fix the compilation error.

**Review by dhruvilshah3 — APPROVED** [review]
Thanks, LGTM!

**Comment by lindong28** [comment]
Verified that the following failed tests are not related to the change in this patch.
```
org.apache.kafka.streams.processor.internals.StreamTaskTest.shouldAbortTransactionAndCloseProducerOnErrorDuringUncleanCloseWithEosEnabled
org.apache.kafka.streams.processor.internals.StreamTaskTest.shouldNotAbortTransactionAndNotCloseProducerOnErrorDuringCleanCloseWithEosEnabled
org.apache.kafka.streams.processor.internals.StreamTaskTest.shouldAlwaysCommitIfEosEnabled
```

**Comment by lindong28** [comment]
PR merged to 1.1 branch.

**Pull request closed without merging**
