### PR TITLE
MINOR: Cleanup generic & throw syntax in connect

### PR DESCRIPTION
**Pull request by twowinsh87**
Found I was working with Kafka Connect.

- Use diamond syntax in generic
- Remove unused throws
- etc

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by hachikuji — APPROVED** [review]
LGTM!

**Comment by hachikuji** [comment]
retest this please

**Comment by hachikuji** [comment]
retest this please

**Comment by dongjinleekr** [comment]
Congrats, @twowinsh87! :smile:

**Pull request merged**
