### PR TITLE
KAFKA-2604; Remove `completeAll` and improve timeout passed to `Selector.poll` from `NetworkClient.poll`

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
Tests passed locally.

**Comment by ewencp** [comment]
LGTM. Nice to get rid of those `completeAll` methods -- I hadn't realized we had removed all uses of them!

**Comment by ijuma** [comment]
Agreed. :)

**Comment by hachikuji** [comment]
LGTM

**Comment by guozhangwang** [comment]
LGTM, thanks!

**Pull request closed without merging**
