### PR TITLE
MINOR: GroupCoordinator can append with group lock

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
cc @guozhangwang @junrao With Guozhang's change in `ReplicaManager`, it seems we no longer need the delayed store that we were using before to avoid holding the group lock when calling `ReplicaManager.append`.

**Comment by hachikuji** [comment]
retest this please

**Comment by hachikuji** [comment]
retest this please

**Review by guozhangwang — COMMENTED** [review]
Neat! LGTM.

**Comment by guozhangwang** [comment]
Please feel free to merge after rebasing.

**Pull request closed without merging**
