### PR TITLE
MINOR: Update to Gradle 4.10.3

### PR DESCRIPTION
**Pull request by soondenana**
Aligns with the 2.1 branch and fixes the
TLS handshake error when executed with
Java 7. This is necessary for the 1.0
and 1.1 branches and we do it in 2.0
too for consistency.

(cherry picked from commit b39aa1205dd8b4e05a9ae58fd013ca50be2dd00f)

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by hachikuji** [comment]
ok to test

**Comment by ijuma** [comment]
ok to test

**Comment by hachikuji** [comment]
ok to test

**Comment by soondenana** [comment]
Closing PR as this doesn't fix issue.

**Pull request closed without merging**
