### PR TITLE
KAFKA-2642: Run replication tests with SSL and SASL clients

### PR DESCRIPTION
**Pull request by rajinisivaram**
For SSL and SASL replication tests, set security protocol for clients as well.

### CODE REVIEW

**Comment by benstopford** [comment]
Alas these tests don't seem to pass locally in virtual box (at least for me). I've had a similar problem with PR #496 which I'm looking at at the moment. These are quite likely related from what I can tell.

**Comment by benstopford** [comment]
@rajinisivaram If you reduce the throughput of the producer it will stabilise it in virtualbox. 
`self.producer_throughput = 1000`

**Comment by rajinisivaram** [comment]
@benstopford Thank you, should I reduce this in the test? Also, is the change required only for non-PLAINTEXT?

**Comment by benstopford** [comment]
@rajinisivaram Yes just reducing the value in the constructor (L98) should suffice. The problem actually has nothing to do with protocol. It's to do with the upgrade to the new consumer. I'm not yet clear exactly why this happens but basically the verifiable producer becomes overwhelmed and goes offline for up to a couple of minutes. Reducing the throughput in the producer solves the problem. 

If you don't have a VB setup (and you don't want one) I can run this test in VB for you later on if you like.

**Comment by rajinisivaram** [comment]
@benstopford I have committed the change to producer throughput. I dont have a VB setup, so I would appreciate your help in testing on VB when you have some time and your setup is free. Many thanks.

**Comment by ijuma** [comment]
@granders, can you please review this too?

**Comment by granders** [comment]
@rajinisivaram Take a look at `kafka/tests/README.md` - it has a summary for how you can get things running in virtualbox. You will need a computer with a fair bit of RAM, preferably at least 16G

**Comment by rajinisivaram** [comment]
@granders For local testing, I run the tests in docker containers. Apart from running on a lower-spec machine, it also enables us to run tests in an environment that is closer to our deployment environment. And this worked quite well until quite recently. But now there seems to be more timing issues. Like the one @benstopford pointed out above. I ran the tests with the lower producer throughput that Ben recommended on the Confluent Jenkins kafka_system_test_branch_builder and quite a few tests failed. I think we need to understand why these tests are so timing-sensitive before committing this.

**Comment by granders** [comment]
@rajinisivaram I see - are the worker nodes themselves separate docker containers?

I tried running locally today, and am similarly experiencing failures due to various timeouts

**Comment by benstopford** [comment]
@rajinisivaram - I actually got the same failures locally that you see on EC2. I'm not entirely sure why this should happen. Lowering the throughput should make things better (and has done in other tests). There must be something deeper going on. I'll take a closer look tomorrow. 
On the other point - ideally we'll get ourselves into a position where anyone can run these tests locally in a reliable manner. It's a bit difficult to use EC2 because of the feedback cycle being so slow. A build server that runs the 'local vm' version may be the best option, so we know these tests work run locally. But that will take some extra effort, and maybe hardware. We should consolidate on one way though if possible.

**Comment by rajinisivaram** [comment]
@granders Yes, we run workers in separate docker containers - we have defined a new cluster type for docker.

@benstopford @granders I raised KAFKA-2877 because we saw a failure in our cluster today when Kafka was restarted that looks very similar to some of the failures from the replication test run. I dont know enough about the new consumer to understand what is causing the failure.

**Comment by granders** [comment]
@rajinisivaram Very cool to hear that you're successfully using a custom cluster type!

Any interest in adding this cluster type to the ducktape project? https://github.com/confluentinc/ducktape
Many of us here at Confluent would be excited to give it a try

**Comment by benstopford** [comment]
@rajinisivaram I'm also suspicious about this intermittent failure. I'm looking at it currently.

**Comment by rajinisivaram** [comment]
@granders At the moment, I am extending docker images that we use in our builds. But I will try to find some time next week to separate out the bits needed for ducktape and contribute to the ducktape project. I need to get approval as well, but I think that should be ok since ducktape has Apache2 license.

@benstopford Thank you, I haven't had a chance to look into it, so would be interested in seeing what you find.

**Comment by granders** [comment]
@rajinisivaram Thanks for catching this rather insidious bug, these changes make sense, and I've confirmed that the topic creation command is leaving out `min.insync.replicas`

I ran `git grep min.insync.replicas` and found one more spot to update the topic configs: `tests/kafkatest/tests/compatibility_test.py`

**Comment by rajinisivaram** [comment]
The tests are passing consistently for me now.

**Comment by rajinisivaram** [comment]
@granders Thank you, I have updated compatibility_test as well.

**Comment by ijuma** [comment]
LGTM. Nice work finding the issue @rajinisivaram.

**Comment by benstopford** [comment]
LGTM too and runs in VB which is always a plus. Good find @rajinisivaram on the min.insync.replicas bug!

**Comment by junrao** [comment]
Thanks for the patch. LGTM

**Pull request closed without merging**
