### PR TITLE
KAFKA-4218: KIP-149, Enabling withKey interfaces in streams

### PR DESCRIPTION
**Pull request by jeyhunkarimov**
This PR aims to provide key access to ValueMapper, ValueJoiner, ValueTransformer, Initializer and Reducer interfaces. More details can be found in [here](https://cwiki.apache.org/confluence/display/KAFKA/KIP-149%3A+Enabling+key+access+in+ValueTransformer%2C+ValueMapper%2C+and+ValueJoiner)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6325/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6310/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by jeyhunkarimov** [comment]
@mjsax @dguy @enothereska @guozhangwang 
can you please review?

**Comment by dguy** [comment]
Thanks for the patch @jeyhunkarimov - is there anyway you could break this down into a few smaller PRs? It gets difficult to review a 5K+ line patch. Ideally we are trying to break things down into patches with < 1k lines

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6412/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by jeyhunkarimov** [comment]
@dguy thanks for your comments. I am sorry, I didn't know about that.
 So, should I break this issue (or jira) into several sub-issues (or "sub-jiras")  and submit PR for each sub-issue?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6397/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by dguy** [comment]
@jeyhunkarimov - no need to be sorry! If it isn't too much hassle you can just break this up into multiple PRs, they can all refer to the same JIRA. Thanks!

**Comment by jeyhunkarimov** [comment]
@dguy I tried to separate the PR into 4 parts. 
- Add `withKey` methods to KStream , [here](https://github.com/apache/kafka/pull/3598)
- Add `withKey` methods to KTable, [here](https://github.com/apache/kafka/pull/3600)
- Add `withKey` methods to KGroupedStream, [here](https://github.com/apache/kafka/pull/3599)
- Add `withKey` methods to KGroupedTable, [here](https://github.com/apache/kafka/pull/3601)

Clear separation of PRs is not possible because they (PRs) share the same proposed base interfaces being `ValueMapperWithKey`, `ValueJoinerWithKey`, `ReducerWithKey`, `InitializerWithKey`, `ValueTransformerWithKey` ,  `ValueTransformerWithKeySupplier` and `AbstractStream`; however, once one PR is merged, I can rebase others and remove interfaces shown above from other PRs.

**Comment by dguy** [comment]
Thanks @jeyhunkarimov!

**Pull request closed without merging**
