### PR TITLE
MINOR: update jackson dependencies

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3800/
Test PASSed (JDK 7 and Scala 2.10).

**Review by ijuma — APPROVED** [review]
LGTM, same comment as in other PR about jacksonDB being a bit confusing, we should say say jacksonDatabind.

**Comment by mjsax** [comment]
Updated this.

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3801/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by mjsax** [comment]
Retest this please.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3802/
Test FAILed (JDK 7 and Scala 2.10).

**Pull request merged**
