### PR TITLE
bumping shadowJar 8.1.0->8.1.1

### PR DESCRIPTION
**Pull request by EricLuGHub**
*Bumping com.github.johnrengelman.shadow from 8.1.0 to 8.1.1*

### CODE REVIEW

**Review by apoorvmittal10 — COMMENTED** [review]
Thanks for the PR but the version has been deliberately downgraded from `8.1.1` to `8.1.0` as for the issues with kafka-clients jar packaging with shadow plugin. Please refer to open issue on shadow github, though the issue would have marked duplicated but the problem still exists.

**Comment by EricLuGHub** [comment]
Hi @apoorvmittal10, thanks for the response. I have viewed your commit about rollbacking to 8.1.0. In the current KAFKA-16803 ticket, it explains that org.gradle.util.ConfigureUtil  is deprecated because of the version. I am looking into whether it is possible to keep 8.1.1. Do you have any paths or potential solutions?

**Comment by apoorvmittal10** [comment]
Hi @EricLuGHub I don't have solution to either of the issues yet, was relying on the reported issue with shadow plugin fix itself. I can followup with shadowing issue to see if there could be potential fix.

**Comment by EricLuGHub** [comment]
@apoorvmittal10, do you think that it would be wise to do 

```
skipPublishingChecks: true
```

basically skipping the checking

**Comment by apoorvmittal10** [comment]
I have to check what all this config skips and whether it will work for release when signing and publishing triggers. However skipping seems not a good workaround rather we might need to invest more in the shadow plugin to find correct fixes.

**Comment by EricLuGHub** [comment]
Ok, keep me updated, let me know.

**Pull request closed without merging**
