### PR TITLE
KAFKA-13466:when kafka-console-producer.sh, delete unused config batch.size 

### PR DESCRIPTION
**Pull request by peterwanner**
…consistent with official docs# Please enter the commit message for your changes. Lines starting

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by showuon — CHANGES_REQUESTED** [review]
@peterwanner , thanks for the PR. But I think the issue here, is the "batch-size" option is already not used everywhere in the code anymore. There is actually already another option `max-partition-memory-bytes` that will be fed into the "batch.size" config (and default to 16KB). Anyway, could you please help remove the unused "batch-size" option in the code? If you need help, just let me know. Thank you.

**Comment by peterwanner** [comment]
> 

@showuon   ok  ,and what shoud the lowest version like 2,x which the batch.size is not removed but still have the same error(default error)

**Comment by showuon** [comment]
>  what shoud the lowest version like 2,x which the batch.size is not removed but still have the same error(default error)

Sorry, I don't get your question. What is the error? What is default error? I thought the PR is to fix the "batch.size" default value inconsistency issue. I didn't see any error here.

Thanks.

**Comment by peterwanner** [comment]
> > what shoud the lowest version like 2,x which the batch.size is not removed but still have the same error(default error)
> 
> Sorry, I don't get your question. What is the error? What is default error? I thought the PR is to fix the "batch.size" default value inconsistency issue. I didn't see any error here.
> 
> Thanks.


> > what shoud the lowest version like 2,x which the batch.size is not removed but still have the same error(default error)
> 
> Sorry, I don't get your question. What is the error? What is default error? I thought the PR is to fix the "batch.size" default value inconsistency issue. I didn't see any error here.
> 
> Thanks.


ok I got it , please review. Thanks so much

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the patch. 
@peterwanner , could you please also update the PR title/description, and also the content in 
KAFKA-13466 in JIRA? Thank you.

**Comment by peterwanner** [comment]
> 

ok,  jira content and commit title both have changed now

**Comment by peterwanner** [comment]
> LGTM! Thanks for the patch. @peterwanner , could you please also update the PR title/description, and also the content in KAFKA-13466 in JIRA? Thank you.

@showuon  Could you help merge ths PR? Thanks a lot.

**Comment by showuon** [comment]
@dajac , could you help review this PR? Thanks.

**Review by andrewchoi5 — APPROVED** [review]

**Comment by showuon** [comment]
@peterwanner , could you please fix the conflicts, so that I can merge the PR? Thank you.

**Comment by peterwanner** [comment]
@showuon  yes, I have resolve the conflicts, please merge the PR. Thanks a lot

**Comment by showuon** [comment]
@peterwanner , thanks for the update. I'll merge the PR after the jenkins build completed (and without breaking any tests). Thank you.

**Comment by showuon** [comment]
retrigger the jenkins build again. 
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-11517/5/

**Comment by showuon** [comment]
Failed tests are unrelated and also failed in `trunk` branch.
```
    Build / ARM / org.apache.kafka.streams.integration.NamedTopologyIntegrationTest.shouldRemoveOneNamedTopologyWhileAnotherContinuesProcessing
    Build / JDK 8 and Scala 2.12 / org.apache.kafka.streams.integration.NamedTopologyIntegrationTest.shouldRemoveOneNamedTopologyWhileAnotherContinuesProcessing
    Build / JDK 11 and Scala 2.13 / org.apache.kafka.connect.integration.RebalanceSourceConnectorsIntegrationTest.testDeleteConnector
    Build / JDK 11 and Scala 2.13 / org.apache.kafka.connect.integration.RebalanceSourceConnectorsIntegrationTest.testDeleteConnector
    Build / JDK 11 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()
    Build / JDK 11 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()
    Build / JDK 11 and Scala 2.13 / org.apache.kafka.streams.integration.NamedTopologyIntegrationTest.shouldRemoveOneNamedTopologyWhileAnotherContinuesProcessing
    Build / JDK 17 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()
    Build / JDK 17 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()
    Build / JDK 17 and Scala 2.13 / org.apache.kafka.streams.integration.NamedTopologyIntegrationTest.shouldRemoveOneNamedTopologyWhileAnotherContinuesProcessing
    Build / JDK 8 and Scala 2.12 / kafka.api.ConsumerBounceTest.testClose()
    Build / JDK 11 and Scala 2.13 / kafka.api.ConsumerBounceTest.testClose()
    Build / JDK 11 and Scala 2.13 / kafka.api.ConsumerBounceTest.testClose()
```

**Comment by showuon** [comment]
Thanks for the contribution, @peterwanner !

**Comment by ijuma** [comment]
We should add a release note since this can cause some applications to break (it's now an error to pass this config vs a no op).

**Comment by showuon** [comment]
@ijuma , good call! Thanks for the reminder.
@peterwanner , could you submit another PR to add a note for v3.2.0 notable change section in `doc/upgrade.html`

**Comment by ijuma** [comment]
Looks like there was a KIP for this too https://cwiki.apache.org/confluence/display/KAFKA/KIP-717%3A+Deprecate+batch-size+config+from+console+producer. We probably should vote it and update the status correctly. cc @kamalcph

**Comment by peterwanner** [comment]
@showuon  ok,  i have submited another pr  11855. please have a look at, thank you.

**Comment by showuon** [comment]
OK, let's wait for the KIP discussion/vote passed, otherwise, we might need to revert this change. Thanks.

**Pull request merged**
