### PR TITLE
MINOR: convert ConsumerBounceTest to KRaft

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@cmccabe could you please replace all `servers` by `brokerServers`?

**Review by frankvicky — APPROVED** [review]
I replaced `servers` with `brokerServers` locally and looped the test class. After this change, the tests are running very stably; otherwise, LGTM.
```
I=0; while ./gradlew core:test --tests ConsumerBounceTest --rerun --fail-fast; do  (( I=$I+1 )); echo “Completed run: $I”; sleep 1; done
```
Screenshot from 2024-12-01 14-08-04

**Comment by frankvicky** [comment]
I will closed #17770

**Comment by cmccabe** [comment]
Thanks for looking, @frankvicky

**Comment by chia7712** [comment]
@cmccabe I merge the trunk and use the `brokerServers` to fix error.

**Review by frankvicky — APPROVED** [review]

**Review by TaiJuWu — APPROVED** [review]

**Comment by chia7712** [comment]
Loop the test 300 times. Only `testConsumptionWithBrokerFailures` fails but it is already flaky (https://issues.apache.org/jira/browse/KAFKA-15146). I'm going to merge it

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
