### PR TITLE
MINOR: Add Jenkinsfile to 2.6

### PR DESCRIPTION
**Pull request by vvcephei**
Add a Jenkinsfile for the 2.6 branch so PRs can be built.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@ijuma  @jolshan @mumrah , are any of you able to review this?

**Comment by jolshan** [comment]
Looks like the right configurations are added to me. Might want to get one more pair of eyes and make sure the tests run.

**Comment by vvcephei** [comment]
The tests for 8 and 14 passed, but 11 timed out. Weirdly, the build log (https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-9471/1/console) actually shows that the tests passed after just under 2 hours, and then it looks like it got hung up "recording the results".

Re-running now.

**Review by omkreddy — APPROVED** [review]
@vvcephei Thanks for the PR. LGTM.

**Comment by vvcephei** [comment]
On second thought, it looks like there's legitimately a test that hangs on 2.6 in java 11.

I was looking before at the whole log, which I didn't realize shows all the builds and tests in one file.

Here are the logs for just the java 11 build on both runs:
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-9471/1/execution/node/85/log/
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-9471/2/execution/node/86/log/

It clearly gets stuck about 35 minutes in. I'm attempting a local repro.

**Comment by jolshan** [comment]
@vvcephei Yeah. I was worried that might be happening. Good to check

**Comment by vvcephei** [comment]
So far, I have not been able to reproduce it. I even re-ran the exact same command as Jenkins:

```
[john@arcturus kafka]$ javac -version
javac 11.0.8

[john@arcturus kafka]$ ./gradlew -PscalaVersion=2.13 unitTest integrationTest --profile --no-daemon --continue -PtestLoggingEvents=started,passed,skipped,failed -PignoreFailures=true -PmaxParallelForks=2 -PmaxTestRetries=1 -PmaxTestRetryFailures=5
...
BUILD SUCCESSFUL in 1h 20m 15s
144 actionable tasks: 59 executed, 85 up-to-date

See the profiling report at: file:///home/confluent/kafka/build/reports/profile/profile-2020-10-22-14-21-43.html
A fine-grained performance profile is available: use the --scan option.
```

Not sure where to go from here...

**Comment by vvcephei** [comment]
Weird; it looks like the 3rd build ran fine. I'm running it again, just to be sure.

**Comment by vvcephei** [comment]
Ok, I've run it a total of 5 times now, and it has passed two times and timed out three times.

I did some analysis on the timed out logs, and found that every test that started either passed or got skipped. I was hoping to find a test that hung, but no luck.

For example, I downloaded the logs for run 1, which timed out as `timeout-1.txt`:
```bash
[john@arcturus Downloads]$ cat timeout-1.txt | grep STARTED | sed 's|^\[\S*] ||' | sed 's/ STARTED//' | sort > /tmp/1-started
[john@arcturus Downloads]$ cat timeout-1.txt | grep PASSED | sed 's|^\[\S*] ||' | sed 's/ PASSED//' | sort > /tmp/1-passed
[john@arcturus Downloads]$ cat timeout-1.txt | grep SKIPPED | sed 's|^\[\S*] ||' | sed 's/ SKIPPED//' | sort > /tmp/1-skipped
[john@arcturus Downloads]$ wc -l /tmp/1-skipped /tmp/1-passed 
     61 /tmp/1-skipped
  10891 /tmp/1-passed
  10952 total
[john@arcturus Downloads]$ wc -l /tmp/1-started 
10952 /tmp/1-started
```

Since all the other builds in all the other branches are working with effectively the same Jenkinsfile, I'm deeply suspicious that there actually is something wrong with the 2.6 codebase and not this PR itself.

I think we should go ahead and merge this in some form. I could see:
1. Just merge this as-is and file a Jira ticket to investigate why java 11 builds time out on 2.6.
2. Exclude java 11 from the jenkinsfile and go ahead and merge with just java 8 and 14.

WDYT, @omkreddy @jolshan @ijuma ?

**Pull request merged**
