### PR TITLE
MINOR: fix NPE in iqv2

### PR DESCRIPTION
**Pull request by vvcephei**
There is a brief window between when the store is registered and when
it is initialized when it might handle a query, but there is no context.
We treat this condition just like a store that hasn't caught up to the
desired position yet.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Test failures were unrelated:     
```
    Build / JDK 11 and Scala 2.13 / integration.kafka.server.FetchRequestBetweenDifferentIbpTest.testControllerOldToNewIBP()
    Build / JDK 11 and Scala 2.13 / kafka.api.ConsumerBounceTest.testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup()
    Build / JDK 17 and Scala 2.13 / kafka.api.PlaintextAdminIntegrationTest.testReplicaCanFetchFromLogStartOffsetAfterDeleteRecords()
    Build / JDK 17 and Scala 2.13 / kafka.api.PlaintextAdminIntegrationTest.testReplicaCanFetchFromLogStartOffsetAfterDeleteRecords()
    Build / JDK 17 and Scala 2.13 / kafka.network.SocketServerTest.remoteCloseWithIncompleteBufferedReceive()
    Build / JDK 8 and Scala 2.12 / kafka.zookeeper.ZooKeeperClientTest.testSessionExpiryDuringClose()
```

**Review by guozhangwang — APPROVED** [review]
LGTM

**Review by mjsax — APPROVED** [review]

**Comment by ableegoldman** [comment]
compiler error, fyi

thanks for the fix though!

**Review by patrickstuedi — APPROVED** [review]
Thanks John.

**Comment by vvcephei** [comment]
Unrelated failures:
```
    Build / JDK 11 and Scala 2.13 / kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testAllTopicPartition, Security=PLAINTEXT
    Build / JDK 17 and Scala 2.13 / kafka.api.PlaintextAdminIntegrationTest.testReplicaCanFetchFromLogStartOffsetAfterDeleteRecords()
    Build / JDK 8 and Scala 2.12 / org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManagerTest.testNewPartitionUpdates()
```

**Pull request merged**
