### PR TITLE
Added changes so that bin/*.sh files can work with CYGWIN under windows,...

### PR DESCRIPTION
**Pull request by aloklal99**
### Background

The script files to run Kafka under Windows don't work as is.  One needs to hand tweak them since their location is not `bin` but `bin/windows`.  Further, the script files under `bin/windows` are not a complete replica of those under `bin`.  To be sure, this isn't a complaint.  To the contrary most projects now-a-days don't bother to support running on Windows or do so very late.  Just that because of these limitation it might be more prudent to make the script files under `bin` itself run under windows rather than trying to make the files under `bin/windows` work or to make them complete.
### Change Summary

Most common unix-like shell on windows is the bash shell which is a part of the cygwin project.  Out of the box the scripts don't work mostly due to peculiarities of the directory paths and class path separators.  This change set makes a focused change to a single file under `bin` so that all of the script files under `bin` would work as is on windows platform when using bash shell of Cygwin distribution.
### Motivation

Acceptance of this change would enable a vast body of developers that use (or have to use) Windows as their development/testing/production platform to use Kafka's with ease.  More importantly by making the running of examples smoothly on Windoes+Cygwin-bash it would make the process of evaluation of Kafka simpler and smoother and potentially make for a favorable evaluation.  For, it would show commitment of the Kafka team to espouse deployments on Windows (albeit only under cygwin).  Further, as the number of people whom use Kafka on Windows increases, one would attract people who can eventually fix the script files under `bin/Windows` itself so that need to run under Cygwin would also go away, too.
### Testing details

The change have been tested under `GNU bash, version 4.1.11(2)-release (x86_64-unknown-cygwin)` running on Windows 7 Enterprise.

### CODE REVIEW

**Comment by junrao** [comment]
Could you open an Apache Kafka jira and attach the patch there? This will take care of Apache licensing issues.

Thanks,

Jun

**Comment by aloklal99** [comment]
Done.  I created this JIRA
tickethttps://issues.apache.org/jira/browse/KAFKA-1230for it.
Please advise if this is enough or would you like to get the patch
sent via some other means.
Best,

**Comment by ijuma** [comment]
@aloklal99, can you please close this PR then? (we can't do it ourselves without asking Apache Infra via a ticket)

**Comment by aloklal99** [comment]
Done.

**Pull request closed without merging**
