### PR TITLE
KAFKA-7287: Set open ACL permissions for old consumer znode path

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@junrao @ijuma Please take a look. 

Previously in ZKUtils we were doing the explict check [here](https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/utils/ZkUtils.scala#L363)

**Review by satishd — APPROVED** [review]
Thanks @omkreddy for the PR.

+1 LGTM

**Comment by omkreddy** [comment]
@junrao Please take a look at this minor PR.

**Comment by harshach** [comment]
+1.

**Review by junrao — APPROVED** [review]
@omkreddy : Thanks for the patch. Good catch. LGTM

**Pull request merged**
