### PR TITLE
KAFKA-3770: KStream job should be able to specify linger.ms

### PR DESCRIPTION
**Pull request by gfodor**

### CODE REVIEW

**Comment by guozhangwang** [comment]
Hi @gfodor , could you check if #1465 handles this issue or not?

**Comment by guozhangwang** [comment]
Hi @gfodor , #1465 has been merged into trunk. Could you check if already covers this PR?

**Comment by gfodor** [comment]
Yes apologies for the delay here, will verify ASAP. Thanks for the ping.

**Comment by guozhangwang** [comment]
@gfodor If you agree that this issue has been resolved, please feel free to close this PR and the corresponding JIRA ticket as well.

**Comment by gfodor** [comment]
Fixed via KAFKA-3786

**Pull request closed without merging**
