### PR TITLE
MINOR: Improve config-streams.html, remove extra </div>

### PR DESCRIPTION
**Pull request by dujian0068**
Improve config-streams.html, remove extra </div>

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@dujian0068 Could you attach the fixed output to me? The fix looks good to me but it would be nice to take a look at html result

**Comment by dujian0068** [comment]
> @dujian0068你能把修复后的输出附给我吗？修复后的效果看起来不错，但最好能看一下 html 结果

hello:
I have deployed the fixed HTML page here：
http://142.171.156.169:8080/dev/documentation/streams/developer-guide/config-streams.html
thank you

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
@dujian0068 thanks for your contribution!

**Pull request merged**
