### PR TITLE
MINOR: replace .kafka with .log in implementation documentation

### PR DESCRIPTION
**Pull request by fvaleri**
This is a minor change required to align the documentation to the current implementation.

### CODE REVIEW

**Review by LiamClarkeNZ — APPROVED** [review]
Nice update :)

**Comment by showuon** [comment]
Nice catch! One question: the original image has "kafka log implementation" title on top of it. Did you intend to remove it?

**Comment by showuon** [comment]
Also, in the image, it should be "my-topic-0/344...log", right? Not sure if this image should be consistent with the "my-topic" name. Or at least, there should be appending the partition index at the end of topic, ex: "topic-0/344...log", right?

**Comment by fvaleri** [comment]
> Nice catch! One question: the original image has "kafka log implementation" title on top of it. Did you intend to remove it?

I think that's redundant information and most of the other images don't have a title. That said, I'm not against adding it back, it's just a matter of preference.

> Also, in the image, it should be "my-topic-0/344...log", right? Not sure if this image should be consistent with the "my-topic" name. Or at least, there should be appending the partition index at the end of topic, ex: "topic-0/344...log", right?

This an image that can be easily reused in similar contexts, even externally. It's pretty hard to make it consistent with text, so I'm only addressing Kafka implementation consistency here.

**Comment by fvaleri** [comment]
@showuon is it fine? Do you have any additional feedback on this?

**Comment by showuon** [comment]
> I think that's redundant information and most of the other images don't have a title. That said, I'm not against adding it back, it's just a matter of preference.

Yes, I agree. But I'd like to keep title as before, because it might have some meaning there that we don't know.

> This an image that can be easily reused in similar contexts, even externally. It's pretty hard to make it consistent with text, so I'm only addressing Kafka implementation consistency here.

SGTM. Thanks.

**Comment by fvaleri** [comment]
> > I think that's redundant information and most of the other images don't have a title. That said, I'm not against adding it back, it's just a matter of preference.
> 
> Yes, I agree. But I'd like to keep title as before, because it might have some meaning there that we don't know.

Ok, done.

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the fix.

**Comment by showuon** [comment]
Only doc change, so don't need to worry about test results.

**Pull request merged**
