### PR TITLE
KAFKA-16845: Migrate ReplicationQuotasTestRig to new test infra

### PR DESCRIPTION
**Pull request by wernerdv**
Rewritten to use the cluster in KRaft mode.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wernerdv** [comment]
Hello @chia7712, would you please take a look at it when you have time?

**Review by chia7712 — COMMENTED** [review]
@wernerdv thanks for this patch. Could you please fix the conflicts and attach the screenshot of running the `ReplicationQuotasTestRig`?

**Comment by wernerdv** [comment]
Trunk results:
trunk1-2
trunk3-4
trunk5

Result from this branch:
branch-1-2
branch-3-4
branch-5

**Comment by wernerdv** [comment]
@chia7712 I see that there are some differences in the graphs.
Can you tell me if I can somehow improve my PR so that the results are similar to trunk?

**Comment by chia7712** [comment]
@wernerdv thanks for this patch. Could you please fix conflicts? I will run it on my local

**Comment by wernerdv** [comment]
@chia7712 I have resolved the conflicts.

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
