### PR TITLE
KAFKA-2278; JmxTool should support querying all objects when object-n…

### PR DESCRIPTION
**Pull request by lindong28**
…ame is omitted

### CODE REVIEW

**Comment by auradkar** [comment]
Dong - can you elaborate on the fix? It's unclear what bug this is fixing.

**Comment by lindong28** [comment]
@auradkar Sure. Below is the description of the problem and fix.

JmxTool should allow user to query all existing objects and attributes, such that the developer can quickly lookup the right object name and attribute name in the output. Indeed, existing API of JmxTool allows user to do this when object-name is not specified in argument.

However, existing implementation of JmxTool doesn't allow this operation. To see this, suppose you run kafka locally with JMX_PORT=9202, you get no output by doing "kafka-run-class.sh kafka.tools.JmxTool --jmx-url service:jmx:rmi:///jndi/rmi://127.0.0.1:9202/jmxrm"

This is because some JMX object, such as java.lang:type=MemoryPool, doesn't have value for all its attributes. You might have an attribute that appears in mbsc.getMBeanInfo(name).getAttributes, but its value will not appear in mbsc.getAttributes(name, mbsc.getMBeanInfo(name).getAttributes.map(_.getName)).

To fix the problem, we just need to correct the way numExpectedAttributes is calculated so that it counts the number of attributes that actually has a value. This patches does exactly this.

**Comment by auradkar** [comment]
Thanks! Can you request a committer to review and commit?

**Comment by lindong28** [comment]
@guozhangwang Do you have time to review this patch? This is actually a very small patch. It is also easy to test using the command given above. I think Adi has given one "ship it".

**Comment by omkreddy** [comment]
LGTM.  tested locally.

**Comment by lindong28** [comment]
@junrao Do you have time to review this patch? I received two LGTM from non-committers. Thanks!

**Comment by guozhangwang** [comment]
LGTM.

**Pull request closed without merging**
