### PR TITLE
MINOR: Fix typos in docs and address some missed review comments

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Follow up on #4758 and also includes comments on #4768.

@bbejeck @vvcephei

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3795/
Test PASSed (JDK 7 and Scala 2.10).

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
unrelated test failures in Java 8

retest this please

**Review by vvcephei — APPROVED** [review]

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3796/
Test PASSed (JDK 7 and Scala 2.10).

**Review by guozhangwang — APPROVED** [review]

**Comment by mjsax** [comment]
Merged to `0.10.2`.

**Pull request merged**
