### PR TITLE
KAFKA-2735 BrokerEndPoint should support uppercase hostnames

### PR DESCRIPTION
**Pull request by jholoman**
Added support for uppercase hostnames in BrokerEndPoint. Added unit test
to cover this scenario.

### CODE REVIEW

**Comment by granthenke** [comment]
@ijuma Was there any reason for not allowing capital letters?

**Comment by ijuma** [comment]
I didn't implement it, I just moved the regular expression to be outside the method (so that it's compiled only once). I don't know why capital letters are not allowed.

**Comment by granthenke** [comment]
Thanks. Sorry I didn't notice that. Just want to be sure its not limited to lowercase for a reason.

**Comment by granthenke** [comment]
It looks like KAFKA-2272 changed this for Endpoint.java, so this change makes them match. There are some other differences in the reqex too. Perhaps we should move them both to a common location so it's not duplicated?

**Comment by ijuma** [comment]
That sounds good to me.

**Comment by jholoman** [comment]
Fine to move these but let's file a separate jira as that's introducing a bit more of a change. Ok?

**Comment by granthenke** [comment]
+1 LGTM

**Comment by guozhangwang** [comment]
LGTM.

**Pull request closed without merging**
