### PR TITLE
KAFKA-4267: Fix and test quota config path used for initialization

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by rajinisivaram** [comment]
@ijuma This is the test corresponding to the fix in PR#1985. I have included the fix here for now so that the test passes, but I can rebase once that PR is committed.

**Comment by ijuma** [comment]
Thanks @rajinisivaram. What is the consequence of this bug? I'm particularly interested if it's bad enough to warrant another RC. Also, it's fine to include the fix here, I can merge this PR and rebase the other one. Can you file a JIRA as well please?

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM. Will merge to trunk and 0.10.1 branches.

**Comment by rajinisivaram** [comment]
@ijuma Thanks for the review. Have created JIRA KAFKA-4267.  I don't think this is bad enough to warrant another RC. The code has an impact only if a user configures a (user, clientId) quota override and then manually asks Zookeeper to delete the config change notification znode generated for the configuration change. The next broker restart wont pick up the quota override unless it is changed again.

**Comment by ijuma** [comment]
Thanks @rajinisivaram, makes sense. @junrao, Rajini said that she can't find any code that deletes change notification znodes from Zookeeper and we were wondering if that was intentional.

**Pull request closed without merging**
