### PR TITLE
MINOR: UpdateMetadataRequest should be lazily created

### PR DESCRIPTION
**Pull request by huxihx**
We should defer to construct UpdateMetadataRequest Builder to the right time when we really need them.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by huxihx** [comment]
@rajinisivaram Please review this minor patch. Thanks.

**Comment by rajinisivaram** [comment]
@huxihx Thanks for the PR, LGTM. Was this just found during code review or was there another reason for the change? Also, is there a reason the reference to the JIRA was removed from the PR title even though the JIRA is still open?

**Comment by huxihx** [comment]
@rajinisivaram Thanks for the comments. It was only during a code review to find this one. And correct me if I am wrong, I remembered Jason told me that the such trivial PR be prefixed with 'MINOR'. Does it make any sense?

**Comment by hachikuji** [comment]
@huxihx If you have already created the JIRA, you can go ahead and tag the PR. I was only pointing out that small fixes do not require a JIRA in the first place.

**Comment by huxihx** [comment]
@hachikuji I understand what you mean, finally. Thanks for the information.

**Comment by ijuma** [comment]
I don't think a lazy val makes sense here. A `def` might make sense perhaps.

**Comment by huxihx** [comment]
@ijuma Correct me if I am wrong.  In the current design, `updateMetadataRequest` will be evaluated only once before sending it to all the brokers. That's why I turned it to a `lazy val` since it will not be changed. However, `updateMetadataRequest` will be evaluated multiple times if we change it to a `def` since there might be multiple brokers to receive the request. This is not efficient. Do we really need to recalculate all the live brokers before sending UpdateMetadataRequest to every broker?

**Comment by huxihx** [comment]
@ijuma @rajinisivaram Does this patch make any sense?

**Pull request closed without merging**
