### PR TITLE
MINOR: Update code to not use deprecated methods

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Retest this please.

**Review by vvcephei — APPROVED** [review]
LGTM! Thanks, @mjsax .

**Comment by mjsax** [comment]
Fixed failing test -- both rely on old API behavior.

**Review by bbejeck — APPROVED** [review]
LGTM assuming Jenkins passes

**Comment by mjsax** [comment]
Would like to get one review from @hachikuji @cmccabe or @rajinisivaram on this, to make sure we don't break anything unintentionally.

**Comment by cmccabe** [comment]
LGTM

**Comment by mjsax** [comment]
Rebased to resolve conflicts.

**Pull request merged**
