### PR TITLE
KAFKA-5326:When resize the index file, maybe cause the content disappear

### PR DESCRIPTION
**Pull request by ZanderXu**
This modify to resolved the [KAFKA-5326](https://issues.apache.org/jira/browse/KAFKA-5326).

### CODE REVIEW

**Comment by ZanderXu** [comment]
When the kafka server is running, someone removed the index file on the disk manually, if at this point, the function AbstractIndex.Resize(newSize: Int) is triggered, will create a new ".index" file which the size is "roundedNewSize", but the content is empty.
I think if the ".index" is not exist when the function AbstractIndex.Resize(newSize: Int) running , we should copy the contents from old "mmap" to new "mmap" to avoid the "empty file".

**Comment by ZanderXu** [comment]
@rajinisivaram, maybe you can review this one. It's a tiny change.

**Comment by ZanderXu** [comment]
@ijuma, maybe you can review this one. Thanks.

**Comment by ijuma** [comment]
cc @junrao

**Pull request closed without merging**
