### PR TITLE
KAFKA-9642: Change "BigDecimal(double)" constructor to "BigDecimal.valueOf(double)"

### PR DESCRIPTION
**Pull request by SoontaekLim**
https://issues.apache.org/jira/browse/KAFKA-9642
for this reason, I modified the code that is using the "BigDecimal(double)" constructor.

### CODE REVIEW

**Review by rondagostino — COMMENTED** [review]
Makes sense, LGTM.  Thanks for the PR!

**Comment by chia7712** [comment]
I search whole project with keyword "new BigDecima" and there are a lot of similar issues. Could we fix them in this PR?
註解 2020-03-10 125154

**Comment by SoontaekLim** [comment]
> I search whole project with keyword "new BigDecima" and there are a lot of similar issues. Could we fix them in this PR?
> 註解 2020-03-10 125154

I don't think so. This issue is related to only double type.

**Comment by chia7712** [comment]
> I don't think so. This is related to only double type.

oh ... I misunderstood this issue :( 

thanks for the reply.

**Comment by tombentley** [comment]
@rhauch please could you review this?

**Comment by SoontaekLim** [comment]
@guozhangwang please could you review this?

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
The PR LGTM, I'm waiting for the jenkins to have green builds.

**Pull request merged**
