### PR TITLE
KAFKA-5682: Include partitions in exceptions raised during consumer record deserialization/validation

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
This patch adds a new RecordDeserializationException which is raised when the user is expected to seek past an offset whose record is corrupted in some way

### CODE REVIEW

**Comment by stanislavkozlovski** [comment]
cc @hachikuji

**Comment by stanislavkozlovski** [comment]
retest this please

**Comment by stanislavkozlovski** [comment]
Closing this since it requires a KIP. I had opened a KIP (KIP-334) at the time but it never passed voting

**Comment by sarwarbhuiyan** [comment]
KIP passed voting

**Pull request closed without merging**
