### PR TITLE
KAFKA-1955: [WIP] Disk based buffer in Producer

### PR DESCRIPTION
**Pull request by blbradley**
Based on patch from @jkreps in [this JIRA ticket](https://issues.apache.org/jira/browse/KAFKA-1955).

- [ ] Get some unit tests that would cover disk-backed usage
- [ ] Do some manual performance testing of this usage and understand the impact on throughput.
- [ ] Do some manual testing of failure cases (i.e. if the broker goes down for 30 seconds we should be able to keep taking writes) and observe how well the producer handles the catch up time when it has a large backlog to get rid of.
- [ ] Add a new configuration for the producer to enable this, something like use.file.buffers=true/false.
- [ ] Add documentation that covers these new options.

I've brought the patch into sync with trunk. Testing is next, which I've started on. I am flexible on how this can be implemented.

### CODE REVIEW

**Comment by blbradley** [comment]
Looking for access rights to CI. I have more function and testing ready.

**Comment by blbradley** [comment]
* `MemoryByteBuffer` is limited to 2GB file size.
* `MmapBufferPool` is now familiar to trunk's `BufferPool`. It is probably better to have `MmapBufferPool` sublcass `BufferPool` instead of creating a common interface. I won't be doing this yet.

**Comment by blbradley** [comment]
`MmapBufferPool` can't pass `BufferPool`'s `testStressfulSituation`. I'm not sure if this kills `MmapBufferPool` as a buffer implementation or if it just needs different stressful situation.

**Comment by blbradley** [comment]
Closing due to change in scope of requirements.

**Review by hoswey — COMMENTED** [review]
good

**Pull request closed without merging**
