### PR TITLE
KAFKA-5843; Mx4jLoader.maybeLoad should only be executed if kafka_mx4jenable is set to true

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by ijuma** [comment]
Good catch. Not sure if anyone is relying on this now though. Maybe send an email to the mailing list to check?

**Comment by lindong28** [comment]
@ijuma Sure, I can certainly email the mailing thread to see if anyone is relying on this. Can you explain a bit more what we are going to do based on the email response? Are you suggesting to remove this feature at all if no one says this feature is being used?

**Comment by ijuma** [comment]
There are 2 options:
1. Do as you did here
2. Basically do `if (!props.getBoolean("kafka_mx4jenable", true))` for compatibility reasons.

**Comment by lindong28** [comment]
@ijuma Good point regarding backward compatibility. I have updated the patch as suggested.

**Comment by ijuma** [comment]
I actually think your previous change was better. :) I was just saying that we could send an email to the mailing list to double check. Also, we should add a note `upgrade.html` noting that we fixed this bug and that people who want to use this library (which I don't think it's too common) should set the relevant property.

**Comment by lindong28** [comment]
@ijuma Sure thing:) I just emailed users@kafka.apache.org to see if anyone is using this feature or has any comment on the change we are going to make.

If we disable this feature by default, existing users (probably very few if any) of this feature maybe be impacted. Maybe we should document this change in the release note if we do this.

On the other hand, if we still enable this feature by default, although it may be a useless thing for most users, I think it won't cause any problem given that Kafka user already has this in their broker. 

Thus overall it seems simpler and less risky to still enable this feature by default, right?

**Comment by ijuma** [comment]
If almost no-one uses this feature (which is what I believe to be the case), we have a useless log statement in almost everyone's log on start-up. It's not a huge deal, but if we can avoid potentially confusing log messages, we should.

**Comment by lindong28** [comment]
@ijuma Cool. I have updated the patch to disable MX4J loader by default.

**Comment by lindong28** [comment]
@ijuma It appears that the issue has already been reported in https://issues.apache.org/jira/browse/KAFKA-4946. Maybe you can simply commit Ralph's patch. It is up to you :)

**Comment by ijuma** [comment]
Can you please add a note to upgrade.html? I will then merge.

**Comment by lindong28** [comment]
@ijuma Sure, I have rebased the patch onto trunk and added this note: `Mx4j will now be enabled only if kafka_mx4jenable is explicitly configured to be true. Otherwise, mx4j will be disabled.`

Maybe we can simply say `Mx4j will now be enabled only if kafka_mx4jenable is explicitly configured to be true`? I added `Otherwise, mx4j will be disabled.` to make this more explicit.

**Review by ijuma — COMMENTED** [review]
LGTM, thanks. Tweaked the note a little before merging to trunk. Credited Ralph as well as an author.

**Pull request closed without merging**
