### PR TITLE
KAFKA-5184, KAFKA-5173; Various improvements to SASL tests

### PR DESCRIPTION
**Pull request by ijuma**
1. Call `closeSasl` in `MultipleListenersWithSameSecurityProtocolBaseTest`
2. Refactor the code to make it easier to reason about
3. Add an assert that may possibly help us narrow down how KAFKA-5184
can happen (it seems impossible).
4. Remove SaslTestHarness to make it easier to reason about setUp
and tearDown methods.
5. Fix *AdminClientIntegrationTest to have a single `tearDown`
6. Remove a *ReplicaFetcherTest and *TopicMetadataTest secure variants.
They are redundant from a security perspective given the consumer and
producer tests.

### CODE REVIEW

**Comment by ijuma** [comment]
@rajinisivaram, can you please take a look? These failures are happening quite often, so we need to figure them out ASAP.

**Comment by rajinisivaram** [comment]
@ijuma Sorry, I was traveling etc. So haven't had time to look into the failures yet. I haven't had a chance to look at this PR yet, but noticed there was the JAAS configuration failure even with this PR. The only way that could occur is if we are leaving some threads behind in some tests which load `Configuration`. I will take a look at the test changes in the last few weeks and also dump threads at the time of failure to narrow that one down. I think this PR makes the code a lot neater, so that is very good. And obviously `closeSasl` needs to be added to the test. I will try and narrow down the threads being left behind in tests and come back to this PR later today. Hope that is ok.

**Comment by ijuma** [comment]
@rajinisivaram, thanks for the update. Yes, I noticed that failure too. I pushed a few additional changes. Something else that could be related is the addition of the SaslSslAdminClientIntegrationTest. The tearDown for the client was not happening in sequence.

Doing a thread dump sounds like a good idea.

And yes, I realised that you have been travelling, so no worries. :) Thanks for helping with this!

**Comment by ijuma** [comment]
All tests passed, will run them again just in case.

**Comment by ijuma** [comment]
retest this please

**Comment by rajinisivaram** [comment]
@ijuma These changes look good to me. Unfortunately, there was another failure even with these changes. This should definitely still be merged though since it has made the code a lot neater.

**Comment by ijuma** [comment]
Thank @rajinisivaram, I merged this to trunk. Annoying that it doesn't fix the underlying issue. Hopefully, we'll track it down in your PR with additional logging.

**Pull request closed without merging**
