### PR TITLE
KAFKA-17437: Upgrade commons-validator from 1.7 to 1.9.0

### PR DESCRIPTION
**Pull request by viktorsomogyi**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by viktorsomogyi** [comment]
@akatona84 @k0b3rIT would you please review this quickly?

**Review by k0b3rIT — APPROVED** [review]

**Review by jlprat — COMMENTED** [review]
We should also update the `LICENSE-binary` file. Precisely this line: https://github.com/apache/kafka/blob/trunk/LICENSE-binary#L217

**Comment by jlprat** [comment]
Description of the changes in this version bump: https://commons.apache.org/proper/commons-validator/changes-report.html

**Review by jlprat — APPROVED** [review]
Thanks @viktorsomogyi 
LGTM as long as CI is happy

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
