### PR TITLE
MINOR: Update docs link to deprecated method TimeWindows.grace

### PR DESCRIPTION
**Pull request by AyoubOm**

### CODE REVIEW

**Comment by chia7712** [comment]
@AyoubOm thanks for this contribution. Could you fix https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindowedCogroupedKStream.java#L42 also?

**Comment by AyoubOm** [comment]
> @AyoubOm thanks for this contribution. Could you fix https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/SessionWindowedCogroupedKStream.java#L42 also?

Thanks @chia7712, fixed !

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
@AyoubOm thanks for this contribution!

**Pull request merged**
