### PR TITLE
KAFKA-5150: Reduce lz4 decompression overhead (without thread local buffers)

### PR DESCRIPTION
**Pull request by ijuma**
Temporary PR that has additional changes over https://github.com/apache/kafka/pull/2967 for comparison.

### CODE REVIEW

**Comment by xvrl** [comment]
I agree that moving the BufferSupplier to the Fetcher is ultimately the right thing to do, but it feels like we're going through great lengths to avoid ThreadLocals when we are already indirectly making use of them in the Snappy case, through [`SnappyOutputStream`'s default `BufferAllocator`](https://github.com/xerial/snappy-java/blob/master/src/main/java/org/xerial/snappy/buffer/CachedBufferAllocator.java).

The server side could equally benefit from the performance improvements during compaction.

Would it be ok to wait for a more comprehensive solution to removing the ThreadLocals on both server and client side across all compression schemes? I feel we are unnecessarily picking on the LZ4 case, and unless there are real concerns with introducing ThreadLocal's on the consumer side, I don't feel we have a good reason not to do so.

Otherwise, all the other small changes in the PR look good to me.

**Comment by ijuma** [comment]
@xvrl, the `Snappy` link doesn't seem to have any thread locals? It seems like a static buffer cache that relies on soft references.

**Comment by xvrl** [comment]
@ijuma oops, I was looking at different version of the code here https://github.com/dain/snappy/blob/master/src/main/java/org/iq80/snappy/BufferRecycler.java but the idea is the same. If anything, using a threadlocal is better in that case since the entries would be released as soon as the thread dies, rather than with a simple softreference, which would only be collected if memory pressure gets high enough.

**Comment by ijuma** [comment]
@xvrl, the second link is for a different pure Java Snappy library that we don't use. So, to be clear, we are not currently relying on thread locals. There are pros and cons for thread local versus global caches, but let's leave that discussion for another time. :)

With regards to the path forward for the 0.11.0.0 release, I think it makes sense to go with the lowest risk solution that gives us the huge gains you outlined in your PR. From that perspective, I think it's actually a benefit that this version doesn't affect the broker. By limiting this to the `Fetcher` and via a `BufferSupplier` that has the same lifecycle as `Fetcher`,  it reduces the risk.

I agree that there are a number of improvements we can do in the broker for reducing buffer allocation costs and we should pursue those for the next release (along with KIP-72).

Thoughts?

**Comment by ijuma** [comment]
Closing as these changes have been merged to #2967.

**Pull request closed without merging**
