### PR TITLE
KAFKA-3216: "Modifying topics" section incorrectly says you can't change replication factor.

### PR DESCRIPTION
**Pull request by wushujames**
Correct the text that said that you can't change the replication factor of a topic.

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by gwenshap** [comment]
LGTM.

**Comment by gwenshap** [comment]
Thanks for contributing, @wushujames :)

**Comment by wushujames** [comment]
Woot!

**Comment by wushujames** [comment]
This PR says 

```
Closed with unmerged commits
This pull request is closed, but the wushujames:KAFKA-3216 branch has unmerged commits.
```

But Github shows that it has been merged. https://github.com/apache/kafka/commit/4fd60c6120dc4330deb7317360c835b04bc6cb9a

I guess the PR is wrong then? I can go ahead and delete my branch?

**Comment by ijuma** [comment]
@wushujames, that message is due to the fact that the merge script creates a new commit with a few modifications, so GitHub thinks the branch wasn't merged (even though it really was). You can safely delete it, yes.

**Pull request closed without merging**
