### PR TITLE
KAFKA-1782: Follow up - add missing @Test annotations.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@guozhangwang @hachikuji I'm pretty sure I managed to get all of them...

**Comment by guozhangwang** [comment]
@ewencp is this relevant?

kafka.controller.ControllerFailoverTest > testMetadataUpdate FAILED
    java.lang.NullPointerException
        at kafka.controller.ControllerFailoverTest.testMetadataUpdate(ControllerFailoverTest.scala:72)

**Comment by ewencp** [comment]
Good catch, I unfortunately missed that because those SocketServerTests are always failing for me, so I expect those error messages at the end of my test run currently...

This was due to a test that was written before the patch was applied but then applied via rebase + squash after the patch was applied. We'll need to watch out for these for a bit with the github PRs since you can issue a PR without having merged back with trunk (so if you just check out the branch it might pass the tests, but will fail when actually committed). I'm not sure if the jenkins build does a merge with trunk before running the build or not, which would protect against this...

**Comment by guozhangwang** [comment]
Thanks, LGTM!

**Comment by ijuma** [comment]
@ewencp The usual behaviour for the PR plugin is to merge with trunk indeed (I have been surprised by this behaviour in the past when having different results in the Jenkins PR builder when compared to running tests locally for that branch). Having said that, I don't know how the PR builder for Kafka is configured since it uses the less popular Cloudbees PR builder.

**Pull request closed without merging**
