### PR TITLE
MINOR: Document ordering contract of iterator for window stores and session stores

### PR DESCRIPTION
**Pull request by miguno**

### CODE REVIEW

**Comment by miguno** [comment]
Please review any of @guozhangwang @enothereska @dguy @mjsax.

This PR is a follow-up on an offline conversation I had with @dguy.

**Review by dguy — APPROVED** [review]
Thanks @miguno LGTM

**Comment by guozhangwang** [comment]
retest this please.

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM. Merging to trunk and 0.10.2.

**Pull request closed without merging**
