### PR TITLE
MINOR: Update Scala to 2.12.4

### PR DESCRIPTION
**Pull request by ijuma**
Mainly for Java 9 fixes and improved compilation times (5-10% reduction):

http://www.scala-lang.org/news/2.12.4

### CODE REVIEW

**Comment by ijuma** [comment]
cc @rajinisivaram

**Comment by ijuma** [comment]
retest this please

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Test failures are unrelated:

1. Known flaky test: kafka.server.LogRecoveryTest.testHWCheckpointWithFailuresSingleLogSegment
2. Environmental (system out of native resources)

**Pull request closed without merging**
