### PR TITLE
MINOR: Add Uniform assignor to the default config

### PR DESCRIPTION
**Pull request by dajac**
This patch adds the `Uniform` assignor to the default list of supported assignors. It also do small changes in the code.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jolshan** [comment]
Sorry I was too slow to review. Looks like there is a conflict.

**Comment by jolshan** [comment]
We should check `testCoordinatorFailover` and `testRackAwareRangeAssignor` since they failed for both builds. I will rerun. If they fail and this is unrelated, we should disable them. I have seen `testRackAwareRangeAssignor` in the past but not the other one as much.

**Comment by dajac** [comment]
@jolshan Thanks. I just resolved that conflict. I also looked into the tests and the one that you mentioned are not related to changed made in this PR.

**Review by jolshan — APPROVED** [review]
lgtm -- will wait for this build to complete before merging.

**Pull request merged**
