### PR TITLE
KAFKA-2423: Introduce Scalastyle

### PR DESCRIPTION
**Pull request by granthenke**
Just the buildscript changes and rules configuration.

### CODE REVIEW

**Comment by granthenke** [comment]
Getting the discussion stared on ScalaStyle. This pull request only contains the integration to gradle and the configuration of the proposed scalastyle rules. Once this is reviewed and the rules are agreed upon and I can add a commit with the changes to make the build pass and reduce the noise from some of the ones we want to enable but can't yet.

**Comment by granthenke** [comment]
@ijuma Any feedback on the proposed rules?

**Comment by ijuma** [comment]
@granthenke I haven't had a chance to look at them in detail and it probably won't happen before next week.

**Comment by granthenke** [comment]
@ijuma Thanks for the update!

**Comment by guozhangwang** [comment]
@granthenke How is this PR related to #284? BTW would you like to continue work on either one of these two?

**Comment by vvcephei** [comment]
Hi @granthenke ,

It seems like this PR stalled. I'll close it out for now, but if you or anyone else want to resume this work, please feel free to re-open it (or start a new one)!

Thanks,
John

**Pull request closed without merging**
