### PR TITLE
KAFKA-2757; Consolidate BrokerEndPoint and EndPoint

### PR DESCRIPTION
**Pull request by zhuchen1018**

### CODE REVIEW

**Comment by lindong28** [comment]
LGTM

**Comment by zhuchen1018** [comment]
Hi @guozhangwang , when you get a chance, could you please review the code? Thanks!

**Comment by guozhangwang** [comment]
LGTM, merged to trunk.

**Comment by ijuma** [comment]
@guozhangwang, is this what you meant in the original JIRA? I thought it was intended to keep each protocol class independent from other protocol classes. Also, this doesn't solve the issue with duplicated validation regexes that was the reason for filing the original issue.

**Comment by guozhangwang** [comment]
@ijuma I was originally just trying to remove the internal class in the request package as I think it is OK to infer o.a.k.client.common classes instead of keeping their own.

I was not aware of the comment Sasaki made on the JIRA. Maybe we should do a follow-up PR?

**Comment by ijuma** [comment]
@guozhangwang I thought the original JIRA was about the broker classes BrokerEndpoint and Endpoint, not the request classes (it was filed after a PR that fixed a regex problem in one of them). And Sasaki then mentioned that we had a third regex for a similar thing in Utils.

**Comment by guozhangwang** [comment]
@ijuma Now I remember. You are right I was thinking about "k.cluster.Endpoint.scala" and "k.cluster.BrokerEndpoint" actually, but my JIRA description is not accurate at all. I will file another JIRA with accurate information.

About Sasaki's comment, I am not sure I follow: o.a.k.common.utils.Utils has a getHost / getPort function, but that does not correspond to either Endpoint or BrokerEndpoint classes?

**Comment by ijuma** [comment]
Thanks @guozhangwang for filing the JIRA. Sasaki's comment is with regards to the following regexes:

Utils:

``` java
private static final Pattern HOST_PORT_PATTERN = Pattern.compile(".*?\\[?([0-9a-zA-Z\\-.:]*)\\]?:([0-9]+)");
```

Endpoint:

``` scala
val uriParseExp = """^(.*)://\[?([0-9a-zA-Z\-.:]*)\]?:(-?[0-9]+)""".r
```

BrokerEndpoint:

``` scala
private val uriParseExp = """\[?([0-9a-zA-Z\-.:]*)\]?:([0-9]+)""".r
```

Very similar (but not necessarily the same). We should ideally have a single regex that is reused by all these classes.

**Comment by sasakitoa** [comment]
Thank you @guozhangwang @ijuma, and sorry for my poor discription.

As @ijuma had explained, I thought this JIRA is for k.cluster.{BrokerEndPoint, EndPoint}.scala,
and it should consolidate o.a.k.common.utils.Utils's regex and these classes's regex into one.
If you create new JIRA ticket, cloud you consider about this?

**Pull request closed without merging**
