### PR TITLE
MINOR: Fix JMX serialization by reverting #5011

### PR DESCRIPTION
**Pull request by rayokota**
A recent change returns an anonymous inner class which retains
a reference to the outer class, KafkaMbean, which is not serializable.

This commit reverts #5011 as a proper fix needs to probably do serialization lazily as well by overriding `readObject` and `writeObject`.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by hachikuji — APPROVED** [review]
Thanks, LGTM.

**Comment by ijuma** [comment]
@apurvam, this looks related to the issue you were seeing in KSQL recently.

**Comment by apurvam** [comment]
Nice! Thanks @rayokota and @ijuma !

**Comment by hachikuji** [comment]
@rayokota Note the findbugs error.

**Comment by lindong28** [comment]
Sorry for problem caused by that patch. Thanks much for catching this!

**Comment by rayokota** [comment]
@lindong28 , @radai-rosenblatt , I've reverted #5011 for now as the simple fix that I had was probably not going to give you the performance benefit that you want.  Originally I thought that I could simply move the anonymous inner class to be a static class, but the class still needs to be serializable so right now referring to the `Map<String, KafkaMetric>` wouldn't work as `KafkaMetric` is not serializable. 

If you still want to try to achieve lazy calculation of the `MBeanAttributeInfo`, then you'll probably want to override `writeObject` and `readObject` to do the serialization lazily as well.  Since this is a more complicated fix, I've reverted for now and you can attempt this and verify that it gives you the performance gains you are looking for.  If you could also verify that serialization does not break, that would be appreciated.

**Comment by radai-rosenblatt** [comment]
out of curiosity - what code path serializes mbeans and for what purpose?

**Comment by ijuma** [comment]
JMX metrics read via RMI rely on Serialization. Simply using JConsole should trigger this path.

**Comment by lindong28** [comment]
@rayokota Sure. Thanks for catching and fixing this issue! Radai will update the patch and add the serialization logic and the test.

**Comment by rayokota** [comment]
retest this please

**Comment by ijuma** [comment]
I merged this to trunk. Next step is for @radai-rosenblatt to resubmit as @lindong28 said.

**Pull request merged**
