### PR TITLE
KAFKA-3047: Explicit offset assignment in Log.append can corrupt the log

### PR DESCRIPTION
**Pull request by ijuma**
This fix was suggested by Maciek Makowski, who also reported the problem.

### CODE REVIEW

**Comment by ijuma** [comment]
@junrao Do you see anything wrong with this one-liner?

**Comment by guozhangwang** [comment]
The fix LGTM. Though I'm a bit curious how this happened from Maciek's use case. Left some comments on the JIRA.

**Comment by guozhangwang** [comment]
With this fix, the scenario described in the JIRA will cause an IllegalArgumentException upon `append`, which is the right situation. Merged to trunk. Thanks @ijuma .

**Comment by guozhangwang** [comment]
Apache JIRA is down for the time. Will close the ticket after it is back up.

**Pull request closed without merging**
