### PR TITLE
Revert "KAFKA-4345; Run decktape test for each pull request"

### PR DESCRIPTION
**Pull request by ijuma**
This reverts commit e035fc039598127e88f31739458f705290b1fdba for the
following reasons:

1. License files are missing causing local builds to fail during the
rat task (rat is not being run in Jenkins for some reason, filed
KAFKA-4459 for that)
2. It renames a number of system test files when there's a better
way to achieve the goal of running a subset of system tests to stay
under the Travis limit.
3. It adds the gradle wrapper binary even though this was removed
intentionally a while back.

A new PR will be submitted for KAFKA-4345 without the undesired
changes.

### CODE REVIEW

**Comment by ijuma** [comment]
cc @harshach @hachikuji @ewencp @raghavgautam

**Comment by hachikuji** [comment]
LGTM

**Comment by ewencp** [comment]
LGTM as well. I think this should be fine as it will be trivial to reapply this and use it as the base for a follow up PR that resolves those issues.

**Comment by raghavgautam** [comment]
@ewencp @ijuma @harshach I have opened new jira KAFKA-4463 for the travis-ci setup and related work.

**Pull request closed without merging**
