### PR TITLE
KAFKA-8415: Interface ConnectorClientConfigOverridePolicy needs to be excluded from class loading isolation

### PR DESCRIPTION
**Pull request by kkonstantine**
* New Connect plugin interface ConnectorClientConfigOverridePolicy needs to be excluded from the class loading isolation

* Added missing unit tests similar to the ones existing for previous plugins

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kkonstantine** [comment]
@rhauch this is a regression after introducing this new plugin, and needs to be backported to 2.3. Thanks!

**Comment by kkonstantine** [comment]
cc @mageshn since this plugin was introduced by KIP-458

**Comment by rhauch** [comment]
@kkonstantine [KIP-458](https://cwiki.apache.org/confluence/display/KAFKA/KIP-458%3A+Connector+Client+Config+Override+Policy) specifies that these should be loaded via the plugin framework. IIUC, this only affects the built-in policies provided out of the box, which we want to load via the system classloader. Is that right?

**Comment by kkonstantine** [comment]
@rhauch this fix aligns this new plugin to what we do for the other plugins, such as `Transformation`, `ConfigProvider` or `ConnectRestExtension`. The interface which we use to scan for plugins needs to be excluded because it's first loaded during the class scanning phase. Same as the other `org.apache.kafka` classes. But some of the subclasses such as transformations and here the concrete policies needed indeed to be loaded in isolation, so that's why it makes sense to add to the whitelist.

**Pull request merged**
