### PR TITLE
KAFKA-5544; The LastStableOffsetLag metric should be removed when partition is deleted

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5829/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5815/
Test PASSed (JDK 8 and Scala 2.12).

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by lindong28** [comment]
Thanks @ijuma for the quick review!

**Comment by lindong28** [comment]
Yeah it seems that Apurva and I submitted the patch at almost the same time. Mine is a little bit earlier.

**Pull request closed without merging**
