### PR TITLE
MINOR:Replace duplicated code with common function in utils

### PR DESCRIPTION
**Pull request by hustclf**
Remove duplcated code, use common function in utils instead.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ivanyu — APPROVED** [review]

**Review by ivanyu — COMMENTED** [review]
Also, `SystemTime.sleep` and `InternalTopicManager.makeReady` could use this.

**Comment by hustclf** [comment]
Thanks,  I modified `SystemTime.sleep`,  meanwhile  `InternalTopicManager.makeReady` has been modified already in current `trunk` branch.

**Comment by hustclf** [comment]
There is a timeout failure when running a test case,  it is not caused by the code I changed.

Do you know how to run jenkins pipeline again? Thanks very much. @ivanyu

**Comment by ivanyu** [comment]
retest this please

**Comment by ivanyu** [comment]
^ this is used to re-trigger the tests.

**Comment by hustclf** [comment]
@mjsax  Please review it if you have time, thanks !

**Comment by mjsax** [comment]
Thanks for the patch @hustclf! Merged to `trunk`.

**Pull request merged**
