### PR TITLE
MINOR: add reportCoverage to jenkins.sh

### PR DESCRIPTION
**Pull request by guozhangwang**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ewencp** [comment]
What is the expected change in behavior here? New information on Jenkins?

**Comment by guozhangwang** [comment]
Yup, this is the plug-in that I'm working on: https://issues.apache.org/jira/browse/INFRA-15409

**Comment by ijuma** [comment]
> 01:38:03 :core:testScoverageBuild timed out (after 180 minutes). Marking the build as aborted.

This may make the build too slow.

**Comment by guozhangwang** [comment]
@ijuma I see your point. On the other successful build it seems taking about 50 min:

```
01:30:10 :core:testScoverage
02:19:36 :core:reportScoverage
```

One thing I can do, is that instead of change the jenkins.sh, just change one of the jenkins pr builds (I'm thinking about `kafka-pr-jdk8-scala2.12` to execute this on cmd, since it is the only one currently used for test coverage report), and increase its timeout by 1hour.

With that, I'm going to close this PR.

**Pull request closed without merging**
