### PR TITLE
KAFKA-3147 : Memory records is not writable in MirrorMaker

### PR DESCRIPTION
**Pull request by MayureshGharat**
Remove the batch from the RecordAccumulator once its closed while aborting batches. Make sure we don't accept new batch appends to RecordAccumulator while the producer is being closed.

### CODE REVIEW

**Comment by becketqin** [comment]
LGTM.

**Comment by ijuma** [comment]
@guozhangwang Maybe you can review this one? It has already been reviewed by @becketqin.

**Comment by guozhangwang** [comment]
@MayureshGharat @becketqin LGTM. Though this PR itself does not completely solve the problem of MM, such that when the producer is forced to close, we can still throw IllegalStateException from the producer threads that are still trying to call send() on the producer, right? If that is the case could you file a separate JIRA as I merge it as is?

**Comment by MayureshGharat** [comment]
@guozhangwang I am just trying to think if the illegalStateException is fatal in that case?

**Comment by guozhangwang** [comment]
@MayureshGharat @becketqin Okay so just to clarify:

1) Let's say the producer client is being used by multiple threads, one thread call close() which then becomes a force close, then other threads are expected to see IllegalStateException?

2) And then for MM case, when the callback gets an error and force close producer according to the config, from the logs we will see IllegalStateException following a INFO("Closing producer due to send failure.") as the producer threads may be still sending messages after processed the callback?

**Comment by ijuma** [comment]
@MayureshGharat @becketqin The JIRA for this PR has 0.9.0.1 as the "Fix Version". If that is still the plan, then it would help if Guozhang's questions were addressed.

**Comment by MayureshGharat** [comment]
@guozhangwang , Sorry for the late reply. I am out on vacation. Please see the responses inline.

1) Let's say the producer client is being used by multiple threads, one thread call close() which then becomes a force close, then other threads are expected to see IllegalStateException?
--> Yes.

2) And then for MM case, when the callback gets an error and force close producer according to the config, from the logs we will see IllegalStateException following a INFO("Closing producer due to send failure.") as the producer threads may be still sending messages after processed the callback?
---> Yes. I think that's right. I will have to test this. But from the first look at the code, this seems to be the behavior.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk.

**Comment by ijuma** [comment]
@guozhangwang One question: do I understand it right that we are saying that `Producer.close()` is not meant to be idempotent (ie some callers of close may see an IllegalStateException)? Is this really what we want?

**Comment by granthenke** [comment]
@ijuma @guozhangwang If thats the case, it would be nice to have something like `isClosed()` to check.

**Comment by Zajs** [comment]
@guozhangwang  @ijuma @MayureshGharat
We patched 0.9.0.0 branch with this pull request. And tested patched version in our load test environment, after ~7 hours we have got same error:

java.lang.IllegalStateException: Memory records is not writable
at org.apache.kafka.common.record.MemoryRecords.append(MemoryRecords.java:93)
at org.apache.kafka.clients.producer.internals.RecordBatch.tryAppend(RecordBatch.java:69)
at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:168)

This always happens after next exceptions:
[kafka-producer-network-thread | audiLoadTest] WARN  org.apache.kafka.clients.producer.internals.Sender - Got error produce response with correlation id 2274005 on topic-partition mct-3, retrying (1 attempts left). Error: NETWORK_EXCEPTION

**Pull request closed without merging**
