### PR TITLE
MINOR website quickstart, fix typo

### PR DESCRIPTION
**Pull request by Alee4738**
### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Alee4738** [comment]
Related PR in kafka-site: https://github.com/apache/kafka-site/pull/338

**Comment by mjsax** [comment]
@Alee4738 I the typo in the Kafka Streams code example already fixed? Or did your miss to include it in this PR?

**Comment by Alee4738** [comment]
It's already fixed in this repo

**Comment by mjsax** [comment]
Thanks @Alee4738! Merged both PRs. (Cherry-picked this one also to `2.8` branch.)

**Pull request merged**
