### PR TITLE
KAFKA-7309: Upgrade Jacoco for Java 11 support

### PR DESCRIPTION
**Pull request by ijuma**
Jacoco 0.8.2 adds Java 11 support:

https://github.com/jacoco/jacoco/releases/tag/v0.8.2

Java 11 RC1 is out so it would be good for us to
get a working CI build.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
@lindong28 trivial one liner change in the build, please review when you have a chance.

**Comment by ijuma** [comment]
The test failure is unrelated.

**Review by lindong28 — APPROVED** [review]
Thanks @ijuma. LGTM!

**Comment by lindong28** [comment]
Merged to trunk

**Pull request closed without merging**
