### PR TITLE
MINOR: Remove redudant LocalLogManager

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
We have 2 identical LocalLogManager in `src/main/org.apache.kafka.metalog` and `src/test/org.apache.kafka.metalog`, the only difference is that the test class have more docs, I just move the docs from test to src and remove test class.

*Summary of testing strategy (including rationale)*
QA

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dengziming** [comment]
ping @cmccabe @mumrah to have a look.

**Comment by cmccabe** [comment]
Thanks for spotting this, @dengziming .  I thought we fixed this already, but I guess not.

The correct fix is to delete this code completely from the main directory, since it is used only for testing.  This PR seems to do the reverse.  Can you please change it around so the code under `metadata/src/main` is deleted?

Also, we want to keep the comments (or to put another way, we don't need to change the version in `metadata/src/test` at all)

**Comment by dengziming** [comment]
@cmccabe  done! Thank you for your reply, PTAL again.

**Review by cmccabe — APPROVED** [review]
LGTM

**Pull request merged**
