### PR TITLE
MINOR: Bug fixes for AssignmentsManager

### PR DESCRIPTION
**Pull request by soarez**
- Proper start & stop for AssignmentsManager's event loop
- Deduping queued duplicate assignments
- Bug where directory ID is resolved too late

### CODE REVIEW

**Comment by OmniaGM** [comment]
@rondagostino @pprovenzano @cmccabe integration tests are failing on the trunk because of the following error 
```
[2023-12-07 19:44:18,763] ERROR Unexpected error handling org.apache.kafka.server.AssignmentsManager$DispatchEvent@34060209 (org.apache.kafka.server.AssignmentsManager:121)
java.lang.IllegalStateException: Cannot enqueue a request if the request thread is not running
	at kafka.server.NodeToControllerRequestThread.enqueue(NodeToControllerChannelManager.scala:309)
	at kafka.server.NodeToControllerChannelManagerImpl.sendRequest(NodeToControllerChannelManager.scala:239)
	at org.apache.kafka.server.AssignmentsManager$DispatchEvent.run(AssignmentsManager.java:217)
	at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:127)
	at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:210)
	at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:181)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
which this PR is supposed to fix. Can we get this merged, please? 
cc: @jolshan

**Comment by dajac** [comment]
@soarez `testAlterReplicaLogDirs(String).quorum=kraft – kafka.api.PlaintextAdminIntegrationTest` still fails in [trunk](https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka/detail/trunk/2466/tests), even with this one. Would you have an idea?

**Comment by OmniaGM** [comment]
> @soarez `testAlterReplicaLogDirs(String).quorum=kraft – kafka.api.PlaintextAdminIntegrationTest` still fails in [trunk](https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka/detail/trunk/2466/tests), even with this one. Would you have an idea?

Hi @dajac I will have a look into this today. 
Side note Igor is out for couple of months and both I and @gaurav-narula will be taking over most of JBOD work now.

**Comment by dajac** [comment]
Thanks @OmniaGM!

**Pull request merged**
