### PR TITLE
KAFKA-3166; Disable SSL client authentication for SASL_SSL security protocol (backport)

### PR DESCRIPTION
**Pull request by ijuma**
Backport of https://github.com/apache/kafka/pull/827 to 0.9.0 that only includes the essential code changes (excluded the test changes due to conflicts).

### CODE REVIEW

**Comment by ijuma** [comment]
Tests passed locally.

**Comment by ijuma** [comment]
@harshach, any chance you could merge the backport too? Thanks.

**Comment by harshach** [comment]
@ijuma done

**Comment by ijuma** [comment]
Thanks!

**Pull request closed without merging**
