### PR TITLE
KAFKA-10314: KafkaStorageException on reassignment when offline log d…

### PR DESCRIPTION
**Pull request by nresare**
…irectories exist

Make sure that we set the isNew field in LeaderAndIsrRequest correctly for brokers
that gets added to the replica set on reassignment.

This is tested by creating a variant of ControllerIntergationTest.testPartitionReassignment()
that makes one of the log directories on the target broker offline before initiating the
reassignment. Without the change to the way isNew is set, this fails after a timeout. With
the change, it succeeds.

To facilitate calling causeLogDirFailure() both from ControllerIntegrationTest and
LogDirFailureTest, the method was moved to TestUtils along with the other helper
methods that deals with interacting with KafkaServer instances for test cases.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
Ok to test

**Comment by mimaison** [comment]
@nresare  Good catch! The change looks good.

Before merging I'd like to get this change tested in the CI pipeline. The Apache Jenkins setup just changed a few days ago and it needs 241e1447fae8b85b3bb491f371357b8f92d2da72 to run. So can you rebase on trunk?

**Comment by nresare** [comment]
@mimaison Thanks for having a look! I just rebased and pushed and it seems there are checks being kicked off as well 🎉

**Comment by nresare** [comment]
Trying to navigate the tests, it seems they are related to flakiness in other parts of the overall test suite. Is it possible to re-trigger tests?

**Review by mimaison — APPROVED** [review]
LGTM

**Pull request merged**
