### PR TITLE
KAFKA-7434 fix NPE in DeadLetterQueueReporter - backport to 2.0

### PR DESCRIPTION
**Pull request by mihbor**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mihbor** [comment]
retest this please

**Review by wicknicks — APPROVED** [review]
LGTM. Thanks so much, @mihbor.

**Comment by wicknicks** [comment]
@mihbor I noticed that there is another PR solving the same problem (targeting trunk). We can close this PR (#5701), and have committers merge the other one (#5700) and backport it to 2.0.

**Comment by mihbor** [comment]
Merged in https://github.com/apache/kafka/pull/5700

**Pull request closed without merging**
