### PR TITLE
KAFKA-6526: Enable unclean leader election without controller change

### PR DESCRIPTION
**Pull request by rajinisivaram**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lindong28** [comment]
@rajinisivaram LGTM. Thanks!

**Comment by omkreddy** [comment]
LGTM. maybe we can also update docs in this PR.

Do we need to implement same behavior for topic config change?  This will make the behavior consistent between dynamic config change and topic config change  for "uncleanLeaderElection"?

**Comment by rajinisivaram** [comment]
@omkreddy Thanks for the review. I will raise a separate JIRA for handling topic config change since that would be a different code path and a different controller event.

**Comment by rajinisivaram** [comment]
@lindong28 @omkreddy Thanks for the reviews. Rebased and merging to trunk.

**Pull request merged**
