### PR TITLE
MINOR: Improve the description of principal under different mechanisms of sasl

### PR DESCRIPTION
**Pull request by RivenSun2**
Improve the description of principal under different mechanisms of sasl.

### CODE REVIEW

**Comment by RivenSun2** [comment]
Hi @dajac  @hachikuji @guozhangwang 
please help to review the PR .
Thanks.

**Comment by RivenSun2** [comment]
Hi @dajac @hachikuji @ijuma 
please help to review the PR .
Thanks.

**Comment by RivenSun2** [comment]
Hi @dajac @hachikuji @ijuma 
please help to review the PR .
Thanks.

**Comment by RivenSun2** [comment]
Hi @showuon
could you help to review this PR?
Thanks.

**Comment by RivenSun2** [comment]
Hi @showuon @dajac and @mimaison
could you help to review the PR?
Thanks a lot.

**Comment by RivenSun2** [comment]
Hi @dajac @hachikuji @guozhangwang
please help to review the PR .
Thanks.

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request merged**
