### PR TITLE
MINOR: Update year in NOTICE

### PR DESCRIPTION
**Pull request by bbejeck**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping one of @ijuma @cmccabe for review

**Comment by bbejeck** [comment]
I'll cherry-pick this back one merged

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
Merged #8207 into trunk

**Comment by bbejeck** [comment]
cherry-picked to 2.4

**Pull request merged**
