### PR TITLE
KAFKA-13771: Support to explicitly delete delegationTokens that have expired but have not been automatically cleaned up

### PR DESCRIPTION
**Pull request by RivenSun2**
Support to explicitly delete delegationTokens that have expired but have not been automatically cleaned up

### CODE REVIEW

**Comment by RivenSun2** [comment]
Hi @rajinisivaram @ijuma @dajac 
Please help to review the PR .
Thanks.

**Comment by RivenSun2** [comment]
Hi @showuon 
could you help to review this PR?
Thanks.

**Comment by RivenSun2** [comment]
Hi @showuon @dajac and @mimaison
could you help to review the PR?
Thanks a lot.

**Comment by RivenSun2** [comment]
Hi @rajinisivaram and @mimaison
could you help to review the PR?
Thanks a lot.

**Comment by RivenSun2** [comment]
Hi @dajac and @omkreddy 
could you help to review the PR?
Thanks a lot.

**Comment by RivenSun2** [comment]
Hi @omkreddy 
could you help to review the PR?
Thanks a lot.

**Review by omkreddy — COMMENTED** [review]
@RivenSun2 Thanks for the PR. can we add a test for this? thanks.

**Comment by RivenSun2** [comment]
@omkreddy Thank you very much for your reply.
I will add testCase later.

**Comment by RivenSun2** [comment]
added test case.

**Review by omkreddy — APPROVED** [review]
LGTM. Thanks for the PR

**Comment by RivenSun2** [comment]
@omkreddy @guozhangwang 
could you help to update JIRA(KAFKA-13771) status?
Thanks.

**Pull request merged**
