### PR TITLE
KRaft support for DescribeClusterRequestTest and DeleteConsumerGroupsTest

### PR DESCRIPTION
**Pull request by ahuang98**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mannoopj — APPROVED** [review]
lgtm!

**Comment by divijvaidya** [comment]
cc: @dengziming

**Comment by dengziming** [comment]
LGTM, test failures are unrelated.

**Comment by divijvaidya** [comment]
folks - 
This PR has made these tests flaky. See the report at https://ge.apache.org/scans/tests?search.relativeStartTime=P28D&search.rootProjectNames=kafka&search.tags=trunk&search.timeZoneId=Europe/Berlin&tests.container=kafka.server.DescribeClusterRequestTest&tests.test=testDescribeClusterRequestIncludingClusterAuthorizedOperations(String)%5B2%5D 

@ahuang98 can you please work on fixing the flakiness?

Screenshot 2023-08-31 at 11 39 10

**Comment by divijvaidya** [comment]
I created a JIRA for for the new flakiness - https://issues.apache.org/jira/browse/KAFKA-15419

**Comment by divijvaidya** [comment]
@ahuang98 do you plan to pick this up? It will be nice to fix this before 3.6 release if possible.

**Pull request merged**
