### PR TITLE
HOTFIX: Temporary suspension of 2 tests

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
@mjsax @guozhangwang are we ok with temporarily suspending these 2 tests until we sort out the issue?

**Comment by guozhangwang** [comment]
@enothereska  @mjsax Is it only transiently failing or consistently failing? How frequent is the failure

**Comment by enothereska** [comment]
It fails transiently for me locally. Usually not in the first run, but if I put it on a look in intellij it fails in subsequent runs. I've sent @mjsax one possible reason for it.

**Comment by mjsax** [comment]
The IntelliJ loop issue is an IntelliJ problem -- I discovered this, too. It's not a test issue. However, the test reveals in internal Streams problem -- the test itself if fine. It's transient and if I run it in a loop in Intellij it fails in about 1 out of 5 runs. Disabling for now is ok with me.

**Comment by guozhangwang** [comment]
Discussed with @mjsax offline, will try to submit a fix to the issue exposed in this failure asap. If we can get the fix in time let's avoid disabling these two.

**Comment by ijuma** [comment]
@mjsax, can you please elaborate what you mean by "The IntelliJ loop issue is an IntelliJ problem"?

**Comment by enothereska** [comment]
This is now solved differently. Closing this PR.

**Comment by mjsax** [comment]
@ijuma Intellij does not respect JUnit annotation correctly in loop-testing-mode. For example `@ClassRule` should only be execute a single time, but in loop-mode it's executed every time.

**Comment by ijuma** [comment]
The actual fixes will be done in https://github.com/apache/kafka/pull/2209, but I'm merging this for now to unblock other PRs.

**Comment by guozhangwang** [comment]
Thanks @ijuma , the fix's taking more time to come than expected, I agree we should temporarily disable that.

**Pull request closed without merging**
