### PR TITLE
MINOR: Update protocol doc link in Introduction.

### PR DESCRIPTION
**Pull request by SinghAsDev**

### CODE REVIEW

**Comment by SinghAsDev** [comment]
@gwenshap mind taking a look. Thanks!

**Comment by ijuma** [comment]
@gwenshap Are we ready to start linking to the website for the protocol docs or is the wiki page still better? The wiki page links to the website, but mentions that it's still in-progress.

**Comment by gwenshap** [comment]
@ijuma - Lets roll protocol to the site immediately after 0.10.0 release? Since some of our new protocols were added just to the generated docs.

**Comment by gwenshap** [comment]
ah, this is inside the docs themselves (not the top-level site link).
Yeah, lets roll it in.

**Comment by ijuma** [comment]
Sounds good.

**Pull request closed without merging**
