### PR TITLE
MINOR: Rename unit test class for `MeteredTimestampedWindowStore`

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
\cc @mjsax @bbejeck @vvcephei @ableegoldman @abbccdda @guozhangwang

**Review by guozhangwang — APPROVED** [review]

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
Failures unrelated

retest this please

**Comment by bbejeck** [comment]
Java 11 build failed `Error cloning remote repo 'origin'` Java 8 failed with 
```
kafka.integration.UncleanLeaderElectionTest.testUncleanLeaderElectionDisabled
kafka.integration.UncleanLeaderElectionTest.testUncleanLeaderElectionDisabledByTopicOverride
```

retest this please

**Comment by guozhangwang** [comment]
@cadonna seems like you need to rebase now..

**Comment by cadonna** [comment]
Failure unrelated
Retest this, please.

**Comment by bbejeck** [comment]
Merged #6826 into trunk

**Comment by bbejeck** [comment]
cherry-picked #6826 to 2.3

**Pull request merged**
