### PR TITLE
KAFKA-12392: Deprecate the batch-size option in console producer

### PR DESCRIPTION
**Pull request by kamalcph**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by tombentley** [comment]
Is there a JIRA/KIP where this deprecation was discussed?

**Comment by kamalcph** [comment]
> Is there a JIRA/KIP where this deprecation was discussed?

No, I don't find any and it wasn't discussed. The config is unused so I propose to deprecate it.

**Comment by kamalcph** [comment]
Filed [KAFKA-12392](https://issues.apache.org/jira/browse/KAFKA-12392) ticket and opened [KIP-717](https://cwiki.apache.org/confluence/x/DB1RCg) for discussion.

**Comment by kamalcph** [comment]
@chia7712 Please take a look.

**Comment by chia7712** [comment]
@kamalcph thanks for filing KIP. noted that KIP must be accepted first :)

see https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals

**Comment by omkreddy** [comment]
its unused since 2.0 release. it looks like we just forgot this config, when we removed old producer code.  I think we dont require KIP for this.  maybe we can remove the unused config option.

**Comment by chia7712** [comment]
> its unused since 2.0 release. it looks like we just forgot this config, when we removed old producer code. I think we dont require KIP for this. we can remove the unused config option.

Does it produce error if users input `batch-size` (after we remove the config)? If so, it seems to me the deprecation cycle is requisite as removing the argument could break something (even though the config is unused).

**Comment by kamalcph** [comment]
Can we deprecate this config in 2.8 if allowed and remove it in the 3.0 release? WDYT?

**Comment by kamalcph** [comment]
@chia7712 @tombentley 
Can you comment/upvote on the KIP to deprecate this config?

**Comment by kamalcph** [comment]
Closing this PR, as it's addressed in #11517

**Pull request closed without merging**
