### PR TITLE
HOTFIX: fix failed cases in FeatureCommandTest

### PR DESCRIPTION
**Pull request by FrankYang0529**
CI sample: https://github.com/apache/kafka/actions/runs/11051663030/job/30710832201?pr=17165

```
FAILED ❌ FeatureCommandTest > testDescribeWithKRaftAndBootstrapControllers [1] Type=Raft-Isolated, MetadataVersion=3.7-IV0,Security=PLAINTEXT
FAILED ❌ FeatureCommandTest > testDowngradeMetadataVersionWithKRaft [1] Type=Raft-Isolated, MetadataVersion=3.3-IV1,Security=PLAINTEXT
FAILED ❌ FeatureCommandTest > testDescribeWithKRaft [1] Type=Raft-Isolated, MetadataVersion=3.3-IV1,Security=PLAINTEXT
```

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
The failed test is caused by #17112, which added IBP_4_0_IV3, and the failure is due to the tool-module cache.

@mumrah This is the issue we discussed over the email thread. Perhaps we should always run certain modules to ensure the PR is covered by sufficient integration tests?

**Comment by mumrah** [comment]
Looks like the tests were failing on the PR, so this should not have been merged.

https://github.com/apache/kafka/actions/runs/11027485627

**Comment by mumrah** [comment]
@chia7712 I agree we should eventually have some "acceptance" tests which do some high level sanity checks. In this case, a change to MetadataVersion (located in server-common) will cause pretty much all tests to run except maybe client.

**Comment by chia7712** [comment]
> Looks like the tests were failing on the PR, so this should not have been merged.

you are right. I was checking the wrong CI :(

**Review by mumrah — APPROVED** [review]
Thanks for the fix @FrankYang0529!

**Comment by mumrah** [comment]
I verified that the test is passing locally. Merging now to un-break trunk

**Comment by kamalcph** [comment]
Thanks @FrankYang0529 for fixing this test!

**Pull request merged**
