### PR TITLE
MINOR: Upgrade the minor version of snappy dependency to 1.1.10.3

### PR DESCRIPTION
**Pull request by bmscomp**
This is a minor version upgrade of snappy compression library, to latest stable version 1.1.10.3 

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bmscomp** [comment]
Checking the release notes the new version contains much dependency upgrades and  few bug fixing, sur no breaking changes : 

https://github.com/xerial/snappy-java/releases/tag/v1.1.10.3

**Dependencies updates**

- Fix the GLIBC_2.32 not found issue of libsnappyjava.so in certain Linux distributions on s390x
- Update scalafmt-core to 3.7.10
- Update native libraries


https://github.com/xerial/snappy-java/releases/tag/v1.1.10.2

**Dependencies updates**

- Update native libraries
- Update scalafmt-core to 3.7.9
- Update sbt to 1.9.2

 **Internal Updates**
  
- Update airframe-log to 23.6.0 
- Update sbt-dynver to 5.0.1
- Update airframe-log to 23.7.2


Nothing mentioned in the release notes relates a breaking changes, the build passes locally, the Jenkins ci needs to be watched and checked see it's behaviour

**Review by divijvaidya — CHANGES_REQUESTED** [review]
please chance LICENSE-binary file as well

**Comment by bmscomp** [comment]
@divijvaidya  Thanks for the review, I just updated the version in license file

**Review by divijvaidya — APPROVED** [review]

**Comment by divijvaidya** [comment]
Unrelated test failures:
```
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationExactlyOnceTest.testOffsetTranslationBehindReplicationFlow()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationExactlyOnceTest/Build___JDK_8_and_Scala_2_12___testOffsetTranslationBehindReplicationFlow__/)
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.controller.QuorumControllerTest.testBalancePartitionLeaders()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/Build___JDK_8_and_Scala_2_12___testBalancePartitionLeaders__/)
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.controller.QuorumControllerTest.testBalancePartitionLeaders()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/Build___JDK_8_and_Scala_2_12___testBalancePartitionLeaders___2/)
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.streams.integration.EosIntegrationTest.shouldWriteLatestOffsetsToCheckpointOnShutdown[at_least_once]](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.streams.integration/EosIntegrationTest/Build___JDK_8_and_Scala_2_12___shouldWriteLatestOffsetsToCheckpointOnShutdown_at_least_once_/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.clients.consumer.internals.CooperativeConsumerCoordinatorTest.testOutdatedCoordinatorAssignment()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.clients.consumer.internals/CooperativeConsumerCoordinatorTest/Build___JDK_11_and_Scala_2_13___testOutdatedCoordinatorAssignment__/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.controller.QuorumControllerTest.testBalancePartitionLeaders()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/Build___JDK_11_and_Scala_2_13___testBalancePartitionLeaders__/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.trogdor.coordinator.CoordinatorTest.testTaskRequestWithOldStartMsGetsUpdated()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.trogdor.coordinator/CoordinatorTest/Build___JDK_11_and_Scala_2_13___testTaskRequestWithOldStartMsGetsUpdated__/)
[Build / JDK 20 and Scala 2.13 / org.apache.kafka.trogdor.coordinator.CoordinatorTest.testTaskRequestWithOldStartMsGetsUpdated()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.trogdor.coordinator/CoordinatorTest/Build___JDK_20_and_Scala_2_13___testTaskRequestWithOldStartMsGetsUpdated__/)
[Build / JDK 17 and Scala 2.13 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationExactlyOnceTest.testOffsetTranslationBehindReplicationFlow()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14072/3/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationExactlyOnceTest/Build___JDK_17_and_Scala_2_13___testOffsetTranslationBehindReplicationFlow__/)
```

**Pull request merged**
