### PR TITLE
KAFKA-9107; Change constructor of StandaloneHerder of test version

### PR DESCRIPTION
**Pull request by xujianhai666**
*More detailed description of your change,
Constructor of StandaloneHerder for test version using  MemoryConfigBackingStore instead of interface name. 

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by xujianhai666** [comment]
Call for review @cadonna   @mjsax  @bbejeck  @guozhangwang

**Comment by cadonna** [comment]
@kkonstantine this PR relates to Connect.

**Comment by mjsax** [comment]
Call for review @rhauch

**Review by kkonstantine — COMMENTED** [review]
@xujianhai666 I believe the meaning behind this decision is that, a) standalone mode is not designed to use kafka topics for its config, status and offset Connect topics and b) that the tests should use specifically `MemoryConfigBackingStore`

Thus, I don't think this is an oversight. Is there something specific that is motivating this change on your side?

**Comment by xujianhai666** [comment]
> @xujianhai666 I believe the meaning behind this decision is that, a) standalone mode is not designed to use kafka topics for its config, status and offset Connect topics and b) that the tests should use specifically `MemoryConfigBackingStore`
> 
> Thus, I don't think this is an oversight. Is there something specific that is motivating this change on your side?

@kkonstantine I thought there is never dependent on implementation instead of interface. I just learn the mechanism of connect, and thought it is strange to elegant code.

**Comment by kkonstantine** [comment]
> > @xujianhai666 I believe the meaning behind this decision is that, a) standalone mode is not designed to use kafka topics for its config, status and offset Connect topics and b) that the tests should use specifically `MemoryConfigBackingStore`
> > Thus, I don't think this is an oversight. Is there something specific that is motivating this change on your side?
> 
> @kkonstantine I thought there is never dependent on implementation instead of interface. I just learn the mechanism of connect, and thought it is strange to elegant code.

I agree that this should not be common practice. But it may make sense when someone needs to be specific about which classes are accepted as expected arguments and does not necessarily reduce the elegance of the code. Here the constructor is already package private and is expected to be used in unit test and not in production code. Thus, it's not public API and (again) accepting any interface is not suitable for the `StandaloneHerder` (as opposed to `DistributedHerder`) 

Given that this is harmless and this constructor is not widely used, I'd suggest closing this PR without merging, since backporting doesn't seem worthwhile and neither is diverging at a specific version.

**Comment by rhauch** [comment]
Finally getting to this. Thanks, @xujianhai666 for the suggestion, but as this is not a public API I agree with @kkonstantine's suggestion and will close without merging.

**Pull request closed without merging**
