### PR TITLE
HOTFIX: fix RocksDBMetricsTest

### PR DESCRIPTION
**Pull request by chia7712**
related to add160d522d8ce6ce70595bd76196e7f42a21435

The description is changed so mock can't match the expected value.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@cadonna Could you take a look?

**Comment by showuon** [comment]
@chia7712 , thanks for the patch! But the test results failed other tests in RocksDBMetricsTest. FYI

**Comment by chia7712** [comment]
@showuon thanks for reminder. will fix them.

**Comment by cadonna** [comment]
@chia7712 Thank you very much for the PR! Let me run the tests locally to double check.

**Comment by cadonna** [comment]
@chia7712 I see a lot of 

```
[ant:checkstyle] [ERROR] /Users/bruno/Code/apache/kafka/streams/src/test/java/org/apache/kafka/streams/integration/EmptyAssignmentTest.java:20:8: Unused import - org.apache.kafka.common.Metric. [UnusedImports]
```

When I try to run the test locally.

**Comment by cadonna** [comment]
@chia7712 Sorry my fault. I had a untracked file locally.

**Review by ijuma — APPROVED** [review]
Failures are unrelated, LGTM.

**Comment by ijuma** [comment]
@chia7712 Looks like the original PR was cherry-picked to 2.7 too, so let's do the same for this.

**Comment by chia7712** [comment]
merge to trunk and 2.7

**Comment by cadonna** [comment]
Thank you!

**Comment by ableegoldman** [comment]
Thanks for the fix @chia7712

**Pull request merged**
