### PR TITLE
KAFKA-9566: Improve DeserializationExceptionHandler JavaDocs

### PR DESCRIPTION
**Pull request by mjsax**
Call for review @vvcephei

### CODE REVIEW

**Review by vvcephei — APPROVED** [review]
Thanks for clarifying this, @mjsax

**Comment by chia7712** [comment]
Is there a incorrect jira number? I can't get the relation between this PR and KAFKA-6566.

**Review by chia7712 — APPROVED** [review]
+1 to this nice docs.

BTW, how about introducing a new interface without disallowed methods? for example, a read-only ```ProcessorContext```. It requires extra effort but it should be more useful than JavaDocs.

**Comment by mjsax** [comment]
@chia7712 -- I miss-typed the ticket number... Fixed now.

The ticket actually discussed the exact same idea as you propose. We just wanted to get a "quick" doc-improvement out fast, as the change would require a KIP what takes longer.

**Pull request merged**
