### PR TITLE
MINOR: Increase timeout for flaky test

### PR DESCRIPTION
**Pull request by wicknicks**
_**This is a WIP. Please do not merge.**_

This test was occasionally failing with timeout issues.  Even though on a laptop the test takes 5-6 seconds to setup connectors, on slow VMs, it might need more than the 15 seconds we were allowing it.

Signed-off-by: Arjun Satish <arjun@confluent.io>

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rayokota — APPROVED** [review]
LGTM

**Comment by mjsax** [comment]
Sorry for late feedback. What is the rational behind increasing the timeout? Is there any evidence it will stabilize the test?

**Comment by wicknicks** [comment]
@mjsax this fix is most likely insufficient. We are seeing the failures even after increasing the timeout. The only way to eliminate the failure completely is if we revert the changes to the group coordinator protocol (https://github.com/apache/kafka/commit/9a9310d074ead70ebf3e93d29d880e094b9080f6). I am still debugging to understand the root cause. Any suggestions/thoughts are welcome!

**Comment by mjsax** [comment]
I don't understand the GroupCoordinator good enough (never touched the code).  Maybe sync with @abbccdda who did the PR.

If increasing the timeout is not a proper fix, it might be better to not merge this PR, dig into the root cause and do a proper fix.

**Comment by wicknicks** [comment]
yes, of course, @mjsax. I added a message to the description of this PR, that should hopefully prevent this change from being merged at the moment.

@abbccdda here is some context on this test. We wrote [this integration test](https://github.com/apache/kafka/blob/dc935c4/connect/runtime/src/test/java/org/apache/kafka/connect/integration/ExampleConnectIntegrationTest.java#L105) for Connect, that spins up Kafka, Zk, and produces some records into a Kafka topic. A sink connector is started that reads these records and write into some in-memory buffers for comparison with what was originally produced. 

Without the commit 9a9310d, this test consistently takes around 10-15 seconds to run, and completes successfully. Once this commit is added, most runs of the test take longer (probably due to the extra round trips to get new IDs) and on certain runs of the test, we see that consumers (internal to Connect workers) hang during a JoinGroup call. This test spins up three connect workers, and each of them runs a Consumer in a group. During the failure, I observed that when a new member joins a group, the existing members are asked to rejoin. They all rejoin properly (as in the GroupCoordinator receives the join requests from all members), but the operation never seems to complete to call (i.e.: https://github.com/apache/kafka/blob/dc935c4beb49a83497536902f96c19fb7f472d41/core/src/main/scala/kafka/coordinator/group/GroupCoordinator.scala#L837 is never invoked). The test fails on the timeout.

**Comment by abbccdda** [comment]
Thanks @wicknicks for the report. Increasing timeout should be able to make the test stable, as it indeed takes longer time for the member to join the group now. If you want, you could try monitor the delayed join operation status by `hasAllMembersJoined` check. Let me know if the increased timeout could still see failures. 
Also if your join group experience is pretty bad, you could attempt to increase `group.initial.rebalance.delay` so that you don't need to experience multiple rebalances which I think maybe helpful too.

**Comment by wicknicks** [comment]
Closing in favor of https://github.com/apache/kafka/pull/6251.

**Pull request closed without merging**
