### PR TITLE
MINOR: Improve the log output information of SocketServer

### PR DESCRIPTION
**Pull request by RivenSun2**
The printed object changes from `endpoint` to `endpoint.listenerName`, so the prompt information of the log should be kept uniform

### CODE REVIEW

**Comment by RivenSun2** [comment]
Hi @dajac @showuon 
please help to review the PR .
Thanks.

**Comment by showuon** [comment]
@RivenSun2 , thanks for the PR, but I don't think the `endpoint` output has any problem here. Let's see if there are other opinion from other reviewers. Thanks.

**Comment by RivenSun2** [comment]
@showuon Thanks for your reply.
Here is the log printed by the previous code:
`INFO [SocketServer brokerId=2] Created data-plane acceptor and processors for endpoint : EndPoint(null,9669,ListenerName(PLAIN_PLUGIN_SSL),SASL_SSL) (kafka.network.SocketServer)
`

Then this is the log printed by the code now:
`INFO [SocketServer brokerId=2] Created data-plane acceptor and processors for endpoint : ListenerName(PLAIN_PLUGIN_SSL) (kafka.network.SocketServer)`

I think the variable type we print changed and the variable type name for the log output should also change.
WDYT?

**Comment by showuon** [comment]
@RivenSun2 ,Thanks for the explanation. But I still think the `endpoint` is a better output. That is:
1. `Created data-plane acceptor and processors for endpoint : ListenerName(PLAIN_PLUGIN_SSL)`
2. `Created data-plane acceptor and processors for listenerName : ListenerName(PLAIN_PLUGIN_SSL)`

I would choose (1). 
Let's see if there are other opinions. Thanks.

**Comment by RivenSun2** [comment]
@showuon ok, thanks for your review. 
I will close this PR if other people have the same opinion as you.

**Comment by mimaison** [comment]
I too prefer `endpoint` over `listenerName`. `listenerName` is really an internal concept, while endpoint is commonly used.

**Comment by RivenSun2** [comment]
Hi @showuon  @mimaison 
Thanks for your review.
let me close this PR.
Thanks.

**Pull request closed without merging**
