### PR TITLE
MINOR: Remove unnecessary usage of `LazyIndex`

### PR DESCRIPTION
**Pull request by ijuma**
The remote index classes use `LazyIndex`, but immediately force
materialization. This results in more verbose code and it's misleading
since the indexes are not lazily used in practice.

Also simplify `LazyIndex.forOffset/forTime` by removing the `writable`
parameter, which is always `true`.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by satishd — COMMENTED** [review]
Thanks @ijuma for the PR.

When an index entry is unavailable locally, it is fetched and accessed immediately. But when the index cache is initialized in case of restarts, it loads all the existing locally stored indexes as LazyIndexes instead of loading them unnecessarily when not yet needed.

**Comment by ijuma** [comment]
@satishd Thanks for the explanation. Can you show me where that happens? You can see that every place I replaced `LazyIndex`, there's a `.get.sanityCheck` call immediately after creation.

**Comment by ijuma** [comment]
@satishd do you have additional comments regarding my question above?

**Comment by satishd** [comment]
> @satishd Thanks for the explanation. Can you show me where that happens? You can see that every place I replaced `LazyIndex`, there's a `.get.sanityCheck` call immediately after creation.

@ijuma You are right. Even while initializing there is a .getSanityCheck which does not really load it lazily. We can take a look at this later in how we can optimize the initialization path with LazyIndexes.

**Review by satishd — APPROVED** [review]
Thanks @ijuma for addressing the conflicts. LGTM.

**Pull request merged**
