### PR TITLE
MINOR: reduce commit interval and cache size for integration test

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @enothereska @dguy

**Review by dguy — APPROVED** [review]
LGTM

**Comment by enothereska** [comment]
@mjsax is there an error that we're trying to fix by changing the commit interval. Note that with a non-0 cache size, even with a commit interval of 0, there is still a chance that the cache dedups. So if there is a dedup error, changing the commit interval won't be sufficient.

**Comment by mjsax** [comment]
Yes -- I am aware of that. This is only about timeouts -- by default, we commit every 30 seconds, and ofter tests wait for 30 seconds to receive output -- reducing commit interval should stabilize (and maybe speed up) the tests by avoiding race conditions.

**Comment by mjsax** [comment]
Rebased to get latest test stabilizations from `trunk` and to trigger new build.

**Comment by mjsax** [comment]
@enothereska Doesn't seem to solve it for all cases... one build fails with
```
java.lang.AssertionError: Condition not met within timeout 30000. Expecting 1 records from topic output- while only received 0: []
	at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:265)
	at org.apache.kafka.streams.integration.utils.IntegrationTestUtils.waitUntilMinKeyValueRecordsReceived(IntegrationTestUtils.java:206)
	at org.apache.kafka.streams.integration.utils.IntegrationTestUtils.waitUntilMinKeyValueRecordsReceived(IntegrationTestUtils.java:175)
	at org.apache.kafka.streams.integration.KTableKTableJoinIntegrationTest.verifyKTableKTableJoin(KTableKTableJoinIntegrationTest.java:221)
	at org.apache.kafka.streams.integration.KTableKTableJoinIntegrationTest.shouldInnerLeftJoin(KTableKTableJoinIntegrationTest.java:142)
```

**Comment by enothereska** [comment]
Yeah, let me have a look.

**Comment by mjsax** [comment]
@enothereska I think it makes still sense to merge this PR -- can you have a look?

**Comment by enothereska** [comment]
Ok LGTM. This can probably wait for @guozhangwang to be checked in since other committers might be busy with 0.10.2 bug fix release and this is not urgent.

**Comment by mjsax** [comment]
Rebases this.

Call for final review and merging @guozhangwang

**Comment by guozhangwang** [comment]
@mjsax should this go to 0.10.2 as well?

**Comment by mjsax** [comment]
@guozhangwang Did not think about it -- might make sense to stabilize `0.10.2` builds, too.

**Comment by guozhangwang** [comment]
LGTM and merged to trunk and 0.10.2.

**Pull request closed without merging**
