### PR TITLE
KAFKA-6760: Responses not logged properly in controller

### PR DESCRIPTION
**Pull request by mimaison**
Added toString() to LeaderAndIsrResponse and StopReplicaResponse

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Are there any other classes with the same issue? Also, should we add tests?

**Comment by mimaison** [comment]
> Are there any other classes with the same issue?

Should we just add `toString()` to all Request/Response classes ? so they can be printed anywhere

> Also, should we add tests?

Sure I'll add a test for each

**Comment by ijuma** [comment]
@mimaison It's a good question. The alternative is that callers should use `toString(version)` which does exist. But perhaps it's hard to enforce that.

**Comment by mimaison** [comment]
Yeah we don't always have the version information so it's a bit tricky.

I've added tests for both Responses.

I looked through the controller classes and couldn't find another place where we're printing a Response object.

**Comment by mimaison** [comment]
@ijuma Can you have another look?

**Comment by mimaison** [comment]
Any chance to get this merged?

**Comment by ijuma** [comment]
retest this please

**Review by ijuma — APPROVED** [review]
LGTM. Merging to trunk and 1.1

**Pull request merged**
