### PR TITLE
KAFKA-6218 : Optimize condition in if statement to reduce the number of comparisons

### PR DESCRIPTION
**Pull request by sachinbhalekar**
Changed the condition in **if** statement 
**(schema.name() == null || !(schema.name().equals(LOGICAL_NAME)))** which
requires two comparisons in worst case with
**(!LOGICAL_NAME.equals(schema.name()))**  which requires single comparison
in all cases and _avoids null pointer exception.
kafka_optimize_if
_

### Committer Checklist (excluded from commit message)
- [+ ] Verify design and implementation 
- [+ ] Verify test coverage and CI build status
- [+ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 8071 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 7963 tests run, 5 skipped, 1 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8071 tests run, 5 skipped, 0 failed.
--none--

**Comment by sachinbhalekar** [comment]
Failure unrelated.
This is my first PR for kafka.
@guozhangwang @dguy @bbejeck can you please review.
Thanks.

**Comment by guozhangwang** [comment]
cc @rhauch @ewencp

**Review by rhauch — APPROVED** [review]
LGTM. Thanks for the change!

**Review by ewencp — APPROVED** [review]
LGTM, thanks

**Comment by sachinbhalekar** [comment]
Thank you guys for the quick response. Look forward to work on more issues.

**Pull request closed without merging**
