### PR TITLE
MINOR:  add file append to connect-log4j.properties

### PR DESCRIPTION
**Pull request by berryma4**
The default log4j for kafka connect should include a log to file.
(It would be nice)

### CODE REVIEW

**Comment by ewencp** [comment]
@cotedm @rnpridgeon Care to review this?

**Comment by rnpridgeon** [comment]
The DailyRollingFileAppender can be problematic if left unmonitored. The DailyRollingFileAppender does not expose any properties which allow you to limit the total amount of  space the logs can consume. This means it's up to the user to clean up the logging directory from time to time to keep from exhausting disk space. 

For this reason I would like to suggest the use of the RollingFileAppender instead. This appender offers two properties which allow you control how much disk space the logs can consume. 

maxBackupIndex: how many backup files to retain
maxFileSize: the max size of each log file

**Comment by berryma4** [comment]
Makes sense.  Would you still like a date rolling policy, or just the simple max file size roll over:

```properties
log4j.rootLogger=INFO, stdout, connectAppender

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n

log4j.appender.connectAppender=org.apache.log4j.RollingFileAppender
log4j.appender.connectAppender.File=${kafka.logs.dir}/connect.log
log4j.appender.connectAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.connectAppender.layout.ConversionPattern=[%d] %p %m (%c:%L)%n
log4j.appender.connectAppender.MaxBackupIndex=10
log4j.appender.connectAppender.MaxFileSize=100MB
log4j.appender.connectAppender.Append=true


log4j.logger.org.apache.zookeeper=ERROR
log4j.logger.org.I0Itec.zkclient=ERROR

```

**Comment by berryma4** [comment]
the kafka log4j has the same DailyRollingFileAppender:
https://github.com/apache/kafka/blob/trunk/config/log4j.properties
I could change this to the same RollingFileAppender with the same max file size in this pull request.

**Comment by cotedm** [comment]
@berryma4 the only problem with updating the Kafka one is it's a change in the default. There's https://github.com/apache/kafka/pull/1652 to update that. @ewencp do you think it just makes sense to merge both these changes at the same time to keep all of the logging consistent. That's what I'm thinking.

**Comment by berryma4** [comment]
I did both files, with the values specified in #1652

**Comment by berryma4** [comment]
(I just corrected a silly copy/paste error), and changed the commit message to match the included changes.

**Comment by rnpridgeon** [comment]
@berryma4 I don't think the Date rolling policy will take affect any longer since the files now roll based on size. Unless I'm missing something I don't believe DatePattern actually has any affect on the DailyFileAppender. 

http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/RollingFileAppender.html

I haven't tried this out but including it will likely cause a WARN or ERROR message to be thrown since the RollingFileAppender is not aware of the DatePattern.

**Comment by berryma4** [comment]
Sorry, my commit is correct, I'll edit the above comment.

**Comment by rnpridgeon** [comment]
LGTM, I'll let @ewencp make the decision on how to handle API changes though

**Review by kkonstantine — COMMENTED** [review]
This improvement required a KIP and therefore, was addressed in a separate PR. 

The KIP was: 
https://cwiki.apache.org/confluence/display/KAFKA/KIP-521%3A+Enable+redirection+of+Connect%27s+log4j+messages+to+a+file+by+default

and it was implemented by: 
https://github.com/apache/kafka/pull/7430

I'm closing this PR since a similar improvement has been merged as shown above. 
But if you'd like to suggest additional improvements, please discuss this first with a KIP proposal (since changes in the way Kafka Connect writes log messages are considered public API) and follow up with a new PR. 

Thanks for suggesting this useful improvement early on @berryma4 !

**Pull request closed without merging**
