### PR TITLE
MINOR: improve Streams application reset tool to make sure application is down

### PR DESCRIPTION
**Pull request by mjsax**
@guozhangwang @miguno @dguy @enothereska @hjafarpour
See #1764

### CODE REVIEW

**Comment by guozhangwang** [comment]
@mjsax There is a failure of `org.apache.kafka.streams.integration.WordCountIntegrationTest.shouldCountWords` but we do not have this class in integration package, could you double check?

**Comment by mjsax** [comment]
Don't understand. What do you mean by "but we do not have this class in integration package"?
Both tests timed out. I guess this is transient failure.

**Comment by guozhangwang** [comment]
Nvm, I thought it was against trunk.

**Comment by guozhangwang** [comment]
Merged to 0.10.0, @mjsax could you manually close this PR?

**Pull request closed without merging**
