### PR TITLE
kafka-5104: DumpLogSegments should not open index files with `rw`

### PR DESCRIPTION
**Pull request by huxihx**
Add a parameter 'writable' for AbstractIndex and set its default value to true for its children classes.

### CODE REVIEW

**Comment by huxihx** [comment]
@ijuma Sorry to close the old PR due to an unrecoverable misoperation. Please review this PR. Thanks.

**Comment by huxihx** [comment]
@junrao Could you take some time to review this PR? Thanks.

**Comment by huxihx** [comment]
@hachikuji Could you kindly take some time to review this PR? Thanks.

**Comment by huxihx** [comment]
@ijuma Hi, did you get any chances to review this PR?

**Comment by huxihx** [comment]
@guozhangwang  Please kindly take some time to review this PR. Thanks.

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
LGTM.

**Comment by guozhangwang** [comment]
Jenkins failures are due to known issues and are being fixed now.

**Comment by guozhangwang** [comment]
Merged to trunk. thanks @amethystic !

**Pull request closed without merging**
