### PR TITLE
KAFKA-12196 Migrate connect:api module to JUnit 5

### PR DESCRIPTION
**Pull request by g1geordie**
- change import 
- assertThrows replaces try-catch

### CODE REVIEW

**Review by chia7712 — APPROVED** [review]
@g1geordie LGTM

**Comment by chia7712** [comment]
@g1geordie Please fix conflicting files :)

**Comment by chia7712** [comment]
@g1geordie Please fix conflicting files again :)

**Comment by ijuma** [comment]
I fixed the conflict.

**Comment by g1geordie** [comment]
@ijuma  thank you for quick help 👍

**Review by ijuma — APPROVED** [review]
I fixed a bug in the Timeout annotation, LGTM now.

**Pull request merged**
