### PR TITLE
MINOR: Make Kafka Connect step in quickstart more Windows friendly

### PR DESCRIPTION
**Pull request by vahidhashemian**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5359/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5344/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by vahidhashemian** [comment]
@ijuma @ewencp This is just a minor doc/quickstart update to improve Windows user experience. Thanks for reviewing.

**Review by ewencp — APPROVED** [review]
LGTM, thanks for the docs cleanup @vahidhashemian!

**Pull request closed without merging**
