### PR TITLE
KAFKA-3434: add old constructor to ConsumerRecord

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
I talked with @ijuma briefly about whether we should deprecate the old constructor. The main downside is that users who are constructing this object in test cases aren't going to have any clue what to use for the serialized lengths and the checksum. In that case, they'd probably use default or arbitrary values. So the old constructor might be worth leaving around just for convenience. On a similar note, it might be worth adding an additional constructor which includes the timestamp, but not the checksum and serialized lengths.

**Comment by granthenke** [comment]
Thanks for catching this @hachikuji. Is it worth adding a test using the constructor? Otherwise LGTM.

**Comment by hachikuji** [comment]
@granthenke Couldn't hurt. Since you're here, do you have any thoughts on deprecation?

**Comment by granthenke** [comment]
@hachikuji I am a bit indifferent. It's not a ton of code to keep around, and if it becomes a problem we can deprecate it then. So I am okay with not deprecating it.

**Comment by ijuma** [comment]
LGTM

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
