### PR TITLE
KAFKA-15560: Upgrade argparse4j to 0.9.0

### PR DESCRIPTION
**Pull request by r-sidd**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

**Release notes:**
https://github.com/argparse4j/argparse4j/releases/tag/argparse4j-0.9.0

Changed to only haveJDK 9 (or higher) for building - https://github.com/argparse4j/argparse4j/pull/125

### CODE REVIEW

**Comment by divijvaidya** [comment]
Thank you for submitting this change!

Please list the release notes and diff in the description with an explanation on why this upgrade will not break backward compatibility.

**Comment by r-sidd** [comment]
> Thank you for submitting this change!
> 
> Please list the release notes and diff in the description with an explanation on why this upgrade will not break backward compatibility.

Sure adding them now :)

**Comment by divijvaidya** [comment]
> Changed to only have to have JDK 9 (or higher) for building.

We cannot pick up 0.9 version change because we still support JDK 8 (see README.md at the root of this project).

For moving to 0.8.1, we have tried to solve in https://github.com/apache/kafka/pull/10626 earlier as well but it was abandoned. If you are really interested in this upgrade, I would suggest to pick up from where the previous PR left off and address the comments given on that one.

**Comment by mimaison** [comment]
We can't upgrade to 0.9.0 since it requires Java 9. We will take another look at this once Kafka removes support for Java 8. Closing this PR for now.

**Pull request closed without merging**
