### PR TITLE
MINOR: Fix flaky HighAvailabilityTaskAssignorIntegrationTest

### PR DESCRIPTION
**Pull request by vvcephei**
Reduce test data set from 1000 records to 500.
Some recent test failures indicate that the Jenkins runners aren't
able to process all 1000 records in two minutes. 

Also add sanity check that all the test data are readable from the
input topic.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
Hey @ableegoldman or @cadonna , do you have a chance to look at this?

Some Jenkins builds have failed like this:
```
java.lang.AssertionError: Condition not met within timeout 120000. Input records haven't all been written to the changelog: 775
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:26)
	at org.apache.kafka.test.TestUtils.lambda$waitForCondition$6(TestUtils.java:401)
	at org.apache.kafka.test.TestUtils.retryOnExceptionWithTimeout(TestUtils.java:449)
	at org.apache.kafka.test.TestUtils.retryOnExceptionWithTimeout(TestUtils.java:417)
	at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:398)
	at org.apache.kafka.streams.integration.HighAvailabilityTaskAssignorIntegrationTest.shouldScaleOutWithWarmupTasks(HighAvailabilityTaskAssignorIntegrationTest.java:163)
	at org.apache.kafka.streams.integration.HighAvailabilityTaskAssignorIntegrationTest.shouldScaleOutWithWarmupTasksAndPersistentStores(HighAvailabilityTaskAssignorIntegrationTest.java:91)
```

**Review by ableegoldman — APPROVED** [review]
Thanks for the PR, LGTM

**Comment by vvcephei** [comment]
Looks like this unrelated test is consistently broken:
`kafka.admin.ReassignPartitionsUnitTest.testModifyBrokerThrottles`

**Comment by vvcephei** [comment]
Cherry-picked to 2.6

**Pull request merged**
