### PR TITLE
KAFKA-4131 :Multiple Regex KStream-Consumers cause Null pointer exception

### PR DESCRIPTION
**Pull request by bbejeck**
Fix for bug outlined in KAFKA-4131

### CODE REVIEW

**Comment by bbejeck** [comment]
Moved the updates for topics matching the supplied regex to the StreamPartitionAssignor.subscription method.  This allows any following Regex KStream-Consumers to be updated with the subscribed topics.  The previous version had an implicit assumption that the KStream-consumer would only be the leader.

I'm working on an integration test, but I wanted to get the fix in for review

**Comment by guozhangwang** [comment]
Ping @dguy @enothereska @mjsax @hjafarpour for reviews.

**Comment by bbejeck** [comment]
Added integration test for follower being assigned topics from regex subscription.

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
LGTM and merged to trunk. Thanks!

**Pull request closed without merging**
