### PR TITLE
KAFKA-5315: should not subtract for empty key in KTable.aggregate/reduce

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @dguy @enothereska @bbejeck

**Comment by mfenniak** [comment]
Hi @mjsax!

I appreciate that you jumped on looking at this issue, and I think you've addressed the specific example I wrote up in KAFKA-5315, but I think there's still a window where the same problem might manifest slightly differently.  I may very well be mistaken, so please take this with a grain of salt; I'm making some assumption leaps on how initializing state stores works.

A small tweak on this problem would be if the source topic contained `Key0:Record0` followed by `Key0:Record1`, where both `Record0` and `Record1` produce the same group-by key.  If an exception occurred while processing `Key0:Record1`, `Record1` could be stored in the persistent state store.  If processing restarted later, and the state store initialization did not re-set Key0 to `Record0` (eg. it replayed the topic from the checkpoint file, and `Key0:Record0` was an earlier offset), then a `Change(Key0:Record1<-Key0:Record1)` will be emitted from the KTable source.  This would cause the repartition map to send a `Change(null<-Key0:Record1)` then `Change(Key0:Record1<-null)` to the aggregate, which would effectively cause the same incorrect aggregate output regardless of this patch.

A similar mistake could occur if the source topic contained `Key0:Record0` followed by `Key0:null`, and an exception occurs while processing `Key0:null`.  If `Key0` is deleted from the store, not re-set by initiasing state stores, and then `Key0:null` is processed, the repartition map would emit no records because the oldValue & newValue are both null, and the aggregate output value would remain despite the delete.

The window for these cases are smaller: the "corrupt" state store record needs to not be restored by initialising the state store, but this seems plausible.

**Comment by mjsax** [comment]
@mfenniak Your observation is correct. This PR fixes only a special case.

I had a similar thought yesterday while thinking about the problem but did not have any idea how to fix this -- but thinking about this again, we might be able to fix it, if we first `forward` and afterwards update (`put`) the state... 

\cc @dguy @bbejeck @enothereska @guozhangwang -- I am just wondering, if updating the state as last action for *all* processors would make sense in general?

**Comment by guozhangwang** [comment]
I think first-forward-then-store may not be perfect, as you can see the reversed case that, for example `builder.table("topic1", "store1").to("topic2")` a record "a -> 1"can be already sent to the downstream "topic2", but failed when trying to put into "store1". Then from "topic2" you could see:

```
a: 0 -> a: 1
a: 0 -> a: 1
```

twice.

**Comment by mjsax** [comment]
But a duplicate would be ok (ie, at-least-once) -- right now, we could loose records.

**Comment by guozhangwang** [comment]
> But a duplicate would be ok (ie, at-least-once) -- right now, we could loose records.

It is not only duplicate record right? Say if you have a groupBy aggregation processor which consumes from `topic2` above we would encounter the same issue, that is we deduct on the aggregatekey of `a:0` twice and add on `a:1` twice, which is incorrect results.

**Comment by mjsax** [comment]
That it true -- but it's "at-least-once", isn't it? I mean, if you apply a regular `stream.groupByKey.count()` we could also over count. And applying a deduce twice is also a duplicate -- but not applying it, is data loss. At least from my understanding.

The ultimate fix is EOS anyway... The question is, if the current behavior break "at-least-once" or not IMHO -- with "at-least-once" we cannot guarantee an exact result in case of failure anyway.

**Comment by guozhangwang** [comment]
@mjsax since now we have EOS, let's revisit how to fix it?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6421/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6406/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by mjsax** [comment]
Need to think about this in detail, but I think if you turn on EOS, it's working correctly out-of-the-box. We can of course still put a fix for case when EOS is disabled.

**Comment by guozhangwang** [comment]
Sounds good. Let's sync up more

**Pull request closed without merging**
