### PR TITLE
KAFKA-4144: Allow per stream/table timestamp extractor

### PR DESCRIPTION
**Pull request by jeyhunkarimov**
A follow up RP to fix [issue](https://github.com/confluentinc/examples/commit/2cd0b87bc8a7eab0e7199fa0079db6417f0e6b63#commitcomment-22200864)

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
LGMT.

Call for second review @enothereska @dguy @bbejeck

**Comment by bbejeck** [comment]
LGTM.

**Review by enothereska — APPROVED** [review]

**Comment by mjsax** [comment]
Call for merging @guozhangwang

**Comment by guozhangwang** [comment]
Merged to trunk and 0.11.0.

**Pull request closed without merging**
