### PR TITLE
[WIP -- do not merge] KAFKA-8272: Changed(De)Serializer should forward call to configure()

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna

**Review by guozhangwang — APPROVED** [review]
Thanks @mjsax

**Comment by mjsax** [comment]
@guozhangwang The previous fix was actually not sufficient. Updated this.

However, it makes me think if this is the correct fix or not, and if it actually a bug in the first place. As an alternative, we could consider fixing this within `SinkNode#init()` and `SourceNode#init()`.

It seems that we missed to update those correctly in #6399 -- digging into this, it also seems that we missed to update `KTableSuppressProcessor#init()`.

Ie, to get https://issues.apache.org/jira/browse/KAFKA-3729 right, it seems that we need to update all code that calls `ProcessorContext#keySerde()/valueSerde()`.

**Comment by mjsax** [comment]
@guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna 

Should we still address this? Or close the ticket as "not a problem" ?

**Comment by guozhangwang** [comment]
Shall we keep this PR as `passing the call to ChangedSer / Deser` still while we continue discuss on what's the best approach for 3729, if making those changes on ChangedSerde seems always good to have?

**Comment by mjsax** [comment]
Well -- that was my question. :)

The current PR feels to be a little "clumsy" though, because we need to check for `null` for the wrapped (de)serializer and the configuration. Suggestions to fix this are welcome.

But if we thinks it's valuable, I am also not opposed to merge it.

**Comment by mjsax** [comment]
Ping @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna @abbccdda 

Any thought on this issue / PR?

**Comment by guozhangwang** [comment]
I'm fine with merging it as is since we've learned that 3729 is still a beast to solve. +1 from me.

**Pull request closed without merging**
