### PR TITLE
KAFKA-12174: A program for dynamically alter log4j levels at runtime.

### PR DESCRIPTION
**Pull request by lordcheng10**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lordcheng10** [comment]
@guozhangwang Added a tool for dynamic log modification. Can you help me take a look? Thank you for your attention

**Comment by lordcheng10** [comment]
@guozhangwang @stanislavkozlovski 
Added a tool for dynamic log modification. Can you help me take a look? Thank you for your attention

**Comment by dongjinleekr** [comment]
Hi @lordcheng10,

Could you submit a KIP for this tool?

**Comment by lordcheng10** [comment]
> Hi @lordcheng10,
> 
> Could you submit a KIP for this tool?
Thank you for your attention！https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=173088038

**Comment by lordcheng10** [comment]
> > Hi @lordcheng10,
> > Could you submit a KIP for this tool?
> > Thank you for your attention！https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=173088038

@dongjinleekr

**Comment by dongjinleekr** [comment]
@lordcheng10 Hi cheng,

1. Click [Create KIP] [here](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals?src=breadcrumbs-parent) and fill out the template. [My recent KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-653%3A+Upgrade+log4j+to+log4j2) would be a good example.
2. Update 'Next KIP Number' and add the KIP document to the 'KIPs under discussion' table as 'Under Discussion'.
3. Open a discussion thread in dev mailing list, like [this](https://lists.apache.org/thread.html/r34bb0f09073c18c8b99e8a73969fce3df36da081ee39ee35fc947cdf%40%3Cdev.kafka.apache.org%3E).
4. Add the permalink of the e-mail thread to the KIP. You can find it from [here](https://lists.apache.org/list.html?dev@kafka.apache.org).

**Comment by mimaison** [comment]
We've now migrated to log4j2 so this is not applicable anymore, closing.

**Pull request closed without merging**
