### PR TITLE
MINOR: typo in variable name "unkownInfo"

### PR DESCRIPTION
**Pull request by evis**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5702/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5688/
Test PASSed (JDK 8 and Scala 2.12).

**Review by apurvam — APPROVED** [review]
LGTM! thanks for the patch!

Will need a committer to merge though.

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Pull request closed without merging**
