### PR TITLE
KAFKA-17524: Add timeout to StreamThreadTest.shouldReturnErrorIfProducerInstanceIdNotInitialized

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Review by mumrah — APPROVED** [review]
LGTM, thanks @mjsax!

**Review by chia7712 — APPROVED** [review]

**Comment by mumrah** [comment]
@mjsax I saw another seemingly stalled test in this class shouldNotCloseTaskAndRemoveFromTaskManagerIfPidMappingIsInvalidInCommitTransactionWhenCommitting https://issues.apache.org/jira/browse/KAFKA-17524?focusedCommentId=17881072&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17881072

should we add a timeout at the class level to be safe?

**Comment by mumrah** [comment]
Another here:

https://github.com/apache/kafka/actions/runs/10818099338

https://ge.apache.org/s/23t65prgrvl7o/timeline

Output from committer-tools/find-unfinished-test.py
```
Test: StreamThreadTest > shouldNotCloseTaskAndRemoveFromTaskManagerIfProducerWasFencedWhileProcessing(boolean, boolean) > "shouldNotCloseTaskAndRemoveFromTaskManagerIfProducerWasFencedWhileProcessing(boolean, boolean).stateUpdaterEnabled=true, processingThreadsEnabled=true"
Duration: 44m7s
Raw line: 2024-09-11T21:05:34.3655550Z Gradle Test Run :streams:test > Gradle Test Executor 52 > StreamThreadTest > shouldNotCloseTaskAndRemoveFromTaskManagerIfProducerWasFencedWhileProcessing(boolean, boolean) > "shouldNotCloseTaskAndRemoveFromTaskManagerIfProducerWasFencedWhileProcessing(boolean, boolean).stateUpdaterEnabled=true, processingThreadsEnabled=true" STARTED
```

**Comment by mjsax** [comment]
@mumrah -- SG. Let me add this to all tests in this category (there is a few more...)

**Comment by mumrah** [comment]
Something weird is definitely happening in this test class 🤔 

Latest build of this PR has these two getting stuck:

* shouldLogAndRecordSkippedMetricForDeserializationException 
* shouldNotCloseTaskAndRemoveFromTaskManagerIfProducerGotFencedInCommitTransactionWhenCommitting

**Comment by mjsax** [comment]
Thanks. Let's try this one instead: https://github.com/apache/kafka/pull/17180

**Pull request closed without merging**
