### PR TITLE
MINOR: remove multiple_rolling_upgrade_test

### PR DESCRIPTION
**Pull request by ableegoldman**
This system test was marked `@Ignore` around a year and a half ago pending the version probing work, but never turned on again.

These days, it is made redundant by the suite of system tests in `streams_upgrade_test`, which cover rolling upgrades (including version probing and metadata change).

### CODE REVIEW

**Comment by ableegoldman** [comment]
@bbejeck @guozhangwang @mjsax @vvcephei

**Review by abbccdda — APPROVED** [review]
LGTM!

**Review by bbejeck — APPROVED** [review]
Thanks for the cleanup @ableegoldman LGTM.

**Comment by bbejeck** [comment]
This PR removes an obsolete system test, so merging now

**Comment by bbejeck** [comment]
Merged #7504 into trunk.

**Pull request merged**
