### PR TITLE
MINOR: Update docstring for "offsets.retention.minutes" config

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by omkreddy** [comment]
@ijuma minor doc change

**Comment by omkreddy** [comment]
@ijuma minor doc change

**Comment by omkreddy** [comment]
@hachikuji minor doc change.  current description is similar to log.retention.minutes

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5836/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5851/
Test PASSed (JDK 7 and Scala 2.11).

**Review by hachikuji — APPROVED** [review]
Thanks for the PR. LGTM

**Comment by hachikuji** [comment]
Oops, forgot to merge. I will do so now.

**Pull request closed without merging**
