### PR TITLE
KAFKA-16039: RecordHeaders supports the addAll method

### PR DESCRIPTION
**Pull request by funky-eyes**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

I think this change will be very convenient for mirroring messages

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by vamossagar12 — CHANGES_REQUESTED** [review]
Thanks for the PR @funky-eyes . I believe, `Headers` is a public interface and for adding a new method to it, we will need a KIP. [This](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals) page explains about the KIP process.

**Comment by vamossagar12** [comment]
@funky-eyes let me know if you got a chance to review my comment

**Comment by funky-eyes** [comment]
> @funky-eyes let me know if you got a chance to review my comment

Hello, thank you for your reminder. I submitted this PR to make the functions of recordheader and list consistent, but I do not have permission to submit a kip. I don’t know how to work on this PR. If you know, please tell  I thank you.

**Comment by vamossagar12** [comment]
The instructions for signing up are [here](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals#KafkaImprovementProposals-GettingStarted).

**Pull request closed without merging**
