### PR TITLE
KAFKA-7454: Use lazy allocation for SslTransportLayer buffers

### PR DESCRIPTION
**Pull request by rajinisivaram**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM

**Review by junrao — APPROVED** [review]
@rajinisivaram : Thanks for the patch. LGTM

**Comment by rajinisivaram** [comment]
retest this please

**Comment by ijuma** [comment]
Unrelated test failed in one of the builds (SSL is not enabled in KafkaAdminClientTest.testCreateTopicsRetryBackoff). Merging to trunk and 2.0. There some conflicts when I cherry-picked to 1.1, so I didn't do that.

**Comment by rajinisivaram** [comment]
Merged to 1.1 as well.

**Pull request merged**
