### PR TITLE
MINOR: Remove unused method 'createDirectoriesFrom' in DirectoryId

### PR DESCRIPTION
**Pull request by wernerdv**
Remove unused method 'createDirectoriesFrom' in DirectoryId.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wernerdv** [comment]
@soarez Hello, please, take a look small cleanup.

**Review by gaurav-narula — APPROVED** [review]
Looks like this is no longer needed after https://github.com/apache/kafka/commit/6b87c8529113939f3a3709603b6f37d733daf49a

LGTM

**Review by soarez — APPROVED** [review]
Thanks for the cleanup @wernerdv.

The change looks good but I'll wait for CI to finish before merging.

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by wernerdv** [comment]
Looks like we need to rebuild on CI.
What's the easiest way to do this?

**Comment by chia7712** [comment]
> Looks like we need to rebuild on CI.

maybe rebase code to run CI with latest changes?

**Pull request merged**
