### PR TITLE
MINOR: Depend on streams:test-utils for streams and examples tests

### PR DESCRIPTION
**Pull request by vvcephei**
Link :streams:test-utils as a test dependency for :streams and :streams:examples, avoiding a circular dependency.

Testing strategy: the project should build.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
\cc @bbejeck

**Comment by mjsax** [comment]
Retest this please.

**Comment by asfgit** [comment]
FAILURE
 8649 tests run, 7 skipped, 1 failed.
--none--

**Comment by vvcephei** [comment]
Failure was:
```
00:43:00.234 kafka.server.DynamicBrokerReconfigurationTest > testAddRemoveSslListener FAILED
00:43:00.234     java.lang.AssertionError: expected:<10> but was:<11>
00:43:00.234         at org.junit.Assert.fail(Assert.java:88)
00:43:00.234         at org.junit.Assert.failNotEquals(Assert.java:834)
00:43:00.234         at org.junit.Assert.assertEquals(Assert.java:645)
00:43:00.234         at org.junit.Assert.assertEquals(Assert.java:631)
00:43:00.234         at kafka.server.DynamicBrokerReconfigurationTest.verifyProduceConsume(DynamicBrokerReconfigurationTest.scala:956)
00:43:00.234         at kafka.server.DynamicBrokerReconfigurationTest.verifyListener(DynamicBrokerReconfigurationTest.scala:827)
00:43:00.234         at kafka.server.DynamicBrokerReconfigurationTest.testAddRemoveSslListener(DynamicBrokerReconfigurationTest.scala:703)
```
(https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/12005)

retest this please

**Review by bbejeck — COMMENTED** [review]
Thanks @vvcephei, LGTM

**Comment by vvcephei** [comment]
The discussion on the mailing list has had no further comments recently. I went ahead and rebased it on current trunk.

@mjsax @guozhangwang assuming the tests pass, should we go ahead and merge this? Or just wait until there's a changeset that requires it?

**Comment by guozhangwang** [comment]
retest this please

**Comment by vvcephei** [comment]
@mjsax @guozhangwang : can we merge this?

**Review by guozhangwang — COMMENTED** [review]
LGTM!

**Pull request merged**
