### PR TITLE
System tests should use --bootstrap-server rather than --zookeeper when testing new Kafka versions

### PR DESCRIPTION
**Pull request by ctan888**
* Remove the --zookeeper flags for node versions supporting --bootstrap-server for TopicCommand.
For the scram credential related code piece, switched to using --bootstrap-server even we don't support it yet.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cmccabe** [comment]
> For the scram credential related code piece, switched to using --bootstrap-server even we don't support it yet.

We need to keep using --zookeeper in the SCRAM case since we don't have an API for that yet.

**Comment by cmccabe** [comment]
It looks like the places where we invoke `kafka-configs.sh` still need to be converted over to use `--bootstrap-server`

**Comment by cmccabe** [comment]
Same issue with `kafka-reassign-partitions.sh`.  It also needs to be converted to use `--bootstrap-server`.

**Comment by cmccabe** [comment]
There are a lot of whitespace-only changes in this PR that are kind of confusing.  Can you please do these in a separate PR or just drop them?

**Comment by ctan888** [comment]
Thanks for the review. Refactored.
1. Add the config command --bootstrap support version 2.5.0 according to https://cwiki.apache.org/confluence/display/KAFKA/KIP-543%3A+Expand+ConfigCommand%27s+non-ZK+functionality
2. The reassign command and scram credential related part will keep using --zookeeper since the removal is still in progress.
3. Clean the whitespaces

**Comment by ctan888** [comment]
ok to test

**Comment by cmccabe** [comment]
ok to test

**Comment by d8tltanc** [comment]
https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3917/console
Link for the system tests ⬆️

**Comment by ctan888** [comment]
Latest dev branch builds here (REMOVE_SYSTEM_4): 

https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3944/

**Comment by cmccabe** [comment]
This was superseded by #9274 and some other changes.  Closing for now

**Pull request closed without merging**
