### PR TITLE
MINOR; Update merge script to work against Python3

### PR DESCRIPTION
**Pull request by jsancio**
Made the following changes so that it works in Python3:

1. Use `print()` instead of `print`
2. Use urllib instead of urllib2
3. Decode all of the cmd outputs from binary to string using UTF-8
4. Use `input` instead of `raw_input`
5. Use `next()` on the iterator returned by `filter()` instead `__get_item__()`
6. Fix any error returned by `pylint`.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by dajac — APPROVED** [review]
@jsancio Thanks for this! LGTM.

**Comment by jsancio** [comment]
@dajac I made some changes after you reviewed. Does it look good to you?

**Review by dajac — APPROVED** [review]
LGTM, thanks! Description must be updated (pt. 5 is not relevant any more).

**Comment by jsancio** [comment]
Merged as https://github.com/apache/kafka/commit/0c01ab67a034a9454fdd1e0c791c56c5466d9ff4

**Pull request closed without merging**
