### PR TITLE
KAFKA-3403: Upgrade ZkClient to 0.8

### PR DESCRIPTION
**Pull request by granthenke**
This ZkClient version adds authentication validation and a conditional delete method needed for other patches

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM if tests pass (the ZKClient changes are minimal).

**Comment by granthenke** [comment]
Tests passed locally.

**Comment by granthenke** [comment]
cc @fpj @gwenshap

**Comment by gwenshap** [comment]
LGTM.

**Pull request closed without merging**
