### PR TITLE
KAFKA-7402: Kafka Streams should implement AutoCloseable where approp…

### PR DESCRIPTION
**Pull request by shunge**
KAFKA-7402: Kafka Streams should implement AutoCloseable where appropriate.
KIP 376: https://cwiki.apache.org/confluence/display/KAFKA/KIP-376%3A+Implement+AutoClosable+on+appropriate+classes+that+want+to+be+used+in+a+try-with-resource+statement

### Committer Checklist (excluded from commit message)
- [X] Verify design and implementation 
- [X] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by shunge** [comment]
JDK 11 One test failed. Should I look into this? @vvcephei @mjsax

**Comment by mjsax** [comment]
Call for review @hachikuji and @rhauch because this touches clients and connect, too.

**Comment by mjsax** [comment]
Java 11 is a little unstable atm. I will just try and trigger a new test run.

Retest this please.

**Comment by mjsax** [comment]
Test failure was
```
java.lang.AssertionError: 
  Expectation failure on verify:
    WorkerSourceTask.run(): expected: 1, actual: 0
	at org.easymock.internal.MocksControl.verify(MocksControl.java:284)
	at org.powermock.api.easymock.internal.invocationcontrol.EasyMockMethodInvocationControl.verify(EasyMockMethodInvocationControl.java:126)
	at org.powermock.api.easymock.PowerMock.verify(PowerMock.java:1476)
	at org.powermock.api.easymock.PowerMock.verifyAll(PowerMock.java:1415)
	at org.apache.kafka.connect.runtime.WorkerTest.testCleanupTasksOnStop(WorkerTest.java:700)
```

\cc @rhauch

**Review by mjsax — APPROVED** [review]
LGTM

**Comment by shunge** [comment]
@mjsax tests failed after resolving conflicts, could you re-trigger the tests? Thanks

**Comment by mjsax** [comment]
You can retrigger tests yourself, but using the phrase "retest this please" in a comment.

**Comment by shunge** [comment]
retest this please

**Comment by shunge** [comment]
retest this please

**Comment by mjsax** [comment]
@shunge We stabilized couple of test recently. I think it might be good to rebase this PR to get green builds.

Call for review @hachikuji and @rhauch because this touches clients and connect, too.

**Comment by shunge** [comment]
@mjsax rebased and retested, jdk11 still failed

**Comment by shunge** [comment]
retest this please

**Comment by shunge** [comment]
@mjsax @hachikuji and @rhauch could you guys review and merge this? thanks

**Comment by shunge** [comment]
@cmccabe @guozhangwang could you guys review and merge this? thanks

**Comment by cmccabe** [comment]
Thanks @shunge .

**Pull request merged**
