### PR TITLE
MINOR - remove unused imports in package kafka.utils

### PR DESCRIPTION
**Pull request by zhuchen1018**

### CODE REVIEW

**Comment by granthenke** [comment]
Don't think you meant to have KAFKA-2757 changes here.

**Comment by zhuchen1018** [comment]
Sorry for getting it wrong. Thanks for pointing out! @granthenke. It should be correct now.

**Comment by lindong28** [comment]
LGTM

**Comment by zhuchen1018** [comment]
Hi @gwenshap, when you get a chance, could you please help review the code? Thank you!

**Comment by jjkoshy** [comment]
@lindong28 pinged me offline for this. +1, will push to trunk

**Pull request closed without merging**
