### PR TITLE
MINOR: Add missing deprecations on old request objects

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
cc @ijuma

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6672/
Test PASSed (JDK 7 and Scala 2.11).

**Review by ijuma — COMMENTED** [review]
Thanks for the PR, we probably need to use "1.0.0" as the "since". Which is fine since we won't remove them before 2.0.0 anyway.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6656/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by hachikuji** [comment]
@ijuma Ack

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6676/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6661/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
Merged to trunk.

**Pull request closed without merging**
