### PR TITLE
KAFKA-4339: Update system tests to accommodate the new consumer group describe output

### PR DESCRIPTION
**Pull request by vahidhashemian**

### CODE REVIEW

**Comment by vahidhashemian** [comment]
@ijuma I had no luck with running jenkins system tests on this branch ([link](https://jenkins.confluent.io/job/system-test-kafka-branch-builder/590/)). I'm not sure if I'm doing something wrong or if jenkins is acting up. Could you please take a look? Thanks.

**Comment by ijuma** [comment]
Will do, thanks for the PR.

**Comment by ijuma** [comment]
This fixes the failures as can be seen here: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/593/

**Comment by ijuma** [comment]
LGTM, merging to trunk.

**Pull request closed without merging**
