### PR TITLE
MINOR: Improve Scala collection usage

### PR DESCRIPTION
**Pull request by divijvaidya**
Multiple changes to improve performance of Scala collection in the code. 

Some examples of improvements include:
1. filtering before sorting instead of sorting and then filtering
2. use sortBy instead of sortWith when comparison is based on same property
3. replace `count(p) == 0` with `!exists(p)`

The changes are partially based on recommendations at: https://pavelfatin.com/scala-collections-tips-and-tricks/

### CODE REVIEW

**Comment by divijvaidya** [comment]
@mdedetrich I believe that you are somewhat of an expert in scala? Mind looking at this PR please?

**Review by clolov — APPROVED** [review]
Were these suggestions generated through some sort of a tool?

**Comment by divijvaidya** [comment]
> Were these suggestions generated through some sort of a tool?

No. I checked them manually. This came up while I was trying to find optimisation opportunities for toSet scala operation in a hot path of the code.

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request merged**
