### PR TITLE
MINOR: fix documentation version

### PR DESCRIPTION
**Pull request by gwenshap**
This will need to be double-committed.

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by ewencp** [comment]
LGTM

**Comment by granthenke** [comment]
Should this update the "Quick Start" download link in `quickstart.html` and the JavaDoc link in `api.html`? or is that a separate change?

**Comment by granthenke** [comment]
well never mind...got committed while looking at it.

**Comment by granthenke** [comment]
@gwenshap Was this part of, or all of [KAFKA-3441](https://issues.apache.org/jira/browse/KAFKA-3441)?

**Comment by gwenshap** [comment]
Good points @granthenke - since I have another cleanup to do, I'll fix it there :)

**Comment by ewencp** [comment]
Yeah, sorry @granthenke, was pushing through the minor fix since it'd be confusing in RC docs, but there's still quite a bit of docs follow up for 0.10.0.0 I think.

**Pull request closed without merging**
