### PR TITLE
MINOR: Null out all buffer references in RequestChannel.Request

### PR DESCRIPTION
**Pull request by ijuma**
The previous code kept two references to `Buffer` and only nulled
out one of them.

As part of this, I removed the `case` modifier from
`RequestChannel.{Request, Response}`. They don't seem to be good
matches given the types of fields they contain (mutable buffers and
opaque `Send` instances).

Also removed a couple of unused files in `kafka.network`.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @radai-rosenblatt and @junrao.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6432/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6417/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
Compilation with Scala 2.11 needs to be fixed before this can be reviewed.

**Review by radai-rosenblatt — APPROVED** [review]
LGTM

**Comment by radai-rosenblatt** [comment]
out of curiosity - what is the advantage of currying here ?

**Comment by ijuma** [comment]
@radai-rosenblatt for case classes, the fields of the first parameter list are all public by default, part of `toString`, `hashCode` and `equals`. That didn't seem suitable for `MemoryPool` and the mutable `Buffer`.

**Comment by ijuma** [comment]
It turns out that the compilation error with Scala 2.11 is due to the following bug:

https://github.com/scala/bug/issues/8873

Since the usage of case class for RequestChannel.Request and RequestChannel.Response is a bit suspect, I went ahead and removed the `case` modifier.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6465/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6450/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6461/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6476/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6495/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6480/
Test PASSed (JDK 8 and Scala 2.12).

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by hachikuji** [comment]
Merging to trunk

**Pull request closed without merging**
