### PR TITLE
MINOR: Remove deprecated streams config

### PR DESCRIPTION
**Pull request by guozhangwang**
Removed the following: "zookeeper.connect",  "key.serde", "value.serde", "timestamp.extractor"

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@mjsax @vvcephei @bbejeck it is open for review now.

**Review by vvcephei — APPROVED** [review]
LGTM!

**Review by bbejeck — APPROVED** [review]
Thanks, @guozhangwang. LGTM

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
Merged to trunk.

I will make a single PR for all the doc changes after the corresponding PRs have been merged.

**Pull request merged**
