### PR TITLE
MINOR: Upgrade maven Artifact version to 3.9.6

### PR DESCRIPTION
**Pull request by bmscomp**
The main motivation behind this change is to keep dependencies updated to the latest stable version of tools 
used to build and publish kafka, and one of the most of important tools is maven artifact

Here is the release notes of maven artifact 3.9.4 https://maven.apache.org/docs/3.9.4/release-notes.html 

One of of the big changes for this version is that java 8 is the minimum version required to use this version of maven 

The build on local machine is working as perfectly, but we need to check the build on Jenkins 

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by divijvaidya** [comment]
Unrelated test failures
```
[Build / JDK 20 and Scala 2.13 / org.apache.kafka.common.network.SslTransportLayerTest.[3] tlsProtocol=TLSv1.3, useInlinePem=false](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14146/1/testReport/junit/org.apache.kafka.common.network/SslTransportLayerTest/Build___JDK_20_and_Scala_2_13____3__tlsProtocol_TLSv1_3__useInlinePem_false/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationExactlyOnceTest.testOffsetTranslationBehindReplicationFlow()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14146/1/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationExactlyOnceTest/Build___JDK_11_and_Scala_2_13___testOffsetTranslationBehindReplicationFlow__/)
[Build / JDK 11 and Scala 2.13 / kafka.server.ReplicaManagerTest.[1] enableRemoteStorage=true](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14146/1/testReport/junit/kafka.server/ReplicaManagerTest/Build___JDK_11_and_Scala_2_13____1__enableRemoteStorage_true/)
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.controller.QuorumControllerTest.testBalancePartitionLeaders()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14146/1/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/Build___JDK_11_and_Scala_2_13___testBalancePartitionLeaders__/)
[Build / JDK 17 and Scala 2.13 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsWithCustomForwardingAdminIntegrationTest.testReplicateSourceDefault()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14146/1/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsWithCustomForwardingAdminIntegrationTest/Build___JDK_17_and_Scala_2_13___testReplicateSourceDefault__/)
[Build / JDK 8 and Scala 2.12 / org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationExactlyOnceTest.testOffsetTranslationBehindReplicationFlow()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14146/1/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationExactlyOnceTest/Build___JDK_8_and_Scala_2_12___testOffsetTranslationBehindReplicationFlow__/)
```

**Comment by divijvaidya** [comment]
One of the breaking changes in moving from 3.8.x is 
```
Maven 2.x was auto-injecting an ancient version of plexus-utils dependency into the plugin classpath, and Maven 3.x continued doing this to preserve backward compatibility. Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. The fix for affected plugin maintainers is to explicitly declare a dependency on plexus-utils. The workaround for affected plugin users is to add this dependency to plugin dependencies until issue is fixed by the affected plugin maintainer. See [MNG-6965](https://issues.apache.org/jira/browse/MNG-6965).
```

@bmscomp could you please explain why we don't need to take an action to add plexus-utils explicitly?

**Comment by bmscomp** [comment]
@divijvaidya  This is an excellent review, I can see that we Gradle already grab a version 3.5.1 plexus-utils, but in the license file we refer to version 3.3.0, I need to check that subject "I did not want to say topic :) " and of course check if there is already a break regarding that version upgrade

**Comment by bmscomp** [comment]
@divijvaidya  checked all the dependencies of the projet using the command `./gradlew printAllDependencies`, the dependency of plexus-utils is still here but we need to update it's version in the LICENSE file 

Example of dependency tree: 
```
+--- org.apache.maven:maven-artifact:3.9.4
|    +--- org.codehaus.plexus:plexus-utils:3.5.1
|    \--- org.apache.commons:commons-lang3:3.12.0
```

Notice that the licence file is already updated to version 3.5.1, and the PR is updated 

So there is no need to add a separate dependency for `plexus-utils `

**Comment by mimaison** [comment]
@bmscomp Can you rebase this PR?

**Comment by bmscomp** [comment]
@mimaison I closed the pull request by mistake, I wanted to rebase this pull request

**Comment by mimaison** [comment]
You should be able to reopen it.

**Comment by bmscomp** [comment]
@mimaison Cannot find a trick to re-open this pull request, waiting to find one, I will create another one that will replace it and update the maven artifact to 3.9.6 instead of 3.9.4

**Pull request closed without merging**
