### PR TITLE
KAFKA-4919: Document that stores must not be closed when Processors are closed

### PR DESCRIPTION
**Pull request by dguy**

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang, @mjsax, @miguno, @enothereska - seeing as we re-use state stores across rebalances they should be closed by the Processor. 

As a follow up to this we might want to consider how we can prevent the user from calling `close` from a `Processor`

**Comment by miguno** [comment]
@dguy : Ah, this is interesting.  I was actually under the impression that you are expected to close stores from within your transformers/processors.

**Comment by miguno** [comment]
I would suggest that we should also update the javadocs of `StateStore`.

Currently, it reads:
```java
    /**
     * Close the storage engine.
     * Note that this function needs to be idempotent since it may be called
     * several times on the same state store.
     */
    void close();
```

This was actually one of the reasons taht led me to believe that you SHOULD close stores in your processors/transformers.

**Comment by miguno** [comment]
Follow-up question:

> seeing as we re-use state stores across rebalances they should be closed by the Processor.

But, in that case, wouldn't `StateStore#init()` be called again, thus recovering the state store (if need be)?  Or is the problem that `StateStore#init()` would reconstruct the store from scratch?

**Comment by enothereska** [comment]
LGTM

**Comment by guozhangwang** [comment]
Yeah this is a good point, though I'm not sure stating that processor's `close()` call should NOT close the stores that maybe re-used during rebalance is a good approach. Since:

1. We still cannot programmatically prevent users from calling `store.close()`.
2. User implementing the `Processor` API would probably not know anything about "rebalancing" and "processor re-usage" at all.

Instead, I'd suggest we change the javadoc to sth. like "users only need to implement this function but NEVER need to call this api explicitly since they will be triggered by the library automatically when necessary". AND update the examples to remove the close calls. This is true since in `ProcessorStateManager` we will close the stores after the whole topology (i.e. all nodes) has been closed, which is actually the right ordering.

**Comment by guozhangwang** [comment]
BTW could we update the title to `KAFKA-4919: ...` as well? @dguy

**Comment by mjsax** [comment]
I would even go further, and change the interface, ie, split it up into two. Users implement the full interface, but only get the limited interface when the get at store to work with. We would need a KIP for this, but I think it should be "straight forward" and worth the effort. Just relying on the JavaDocs is something I don't like too much.

**Comment by guozhangwang** [comment]
@mjsax How about track it as a separate JIRA, and accept this as a near-term fix since we do not know how long that refactoring will take or if it will make it in 0.11.0?

**Comment by eliaslevy** [comment]
LGTM and I like the idea of adding a warning to the  `StoreState.close` javadocs.  I would go further and make a note in the release notes and documentation.  It took me a while to figure out what was going on and other may be in the same boat and the release notes is where one would naturally look for any API semantic changes in the new release.  Might also want to update the `Processor.close` javadocs to be clearer about what kind of resources one is expected to close there.

**Comment by dguy** [comment]
@mjsax we would need to change our hierarchy somewhat, i.e., `KeyValueStore` and `WindowStore` won't be able to extend `StateStore`, the implementations of these interfaces would need to implement StateStore.  So this kind-of works for our maintained implementations, but doesn't really work for custom stores. Also, there is nothing to stop anyone from casting to the Impl if they really want.

That said, i still think we should do something to restrict this. Just not as part of this PR.

**Review by guozhangwang — APPROVED** [review]
Merged to trunk and 0.10.2.

**Comment by mjsax** [comment]
Added it to https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Streams+Discussions

**Pull request closed without merging**
