### PR TITLE
MINOR: Switch to using the Gradle RAT plugin

### PR DESCRIPTION
**Pull request by jthurne**
The Gradle RAT plugin properly declares inputs and outputs and is also
cachable. This also relieves the Kafka developers from maintaining the build
integration with RAT.

The generated RAT report is identical to the one generated previously. The only
difference is the RAT report name: the RAT plugin sets the HTML report name to
`index.html` (still under `build/rat`).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jthurne** [comment]
@ijuma another one for you.

**Comment by jthurne** [comment]
Full disclosure: I'm an engineer that works for Gradle (on [Gradle Enterprise](https://gradle.com/), and I found these optimizations while using the project to test out Gradle Enterprise features.

I put this change in a separate PR from [the other build optimizations](https://github.com/apache/kafka/pull/10490) since it is a slightly larger change, and since the HTML report name changes.

**Review by runningcode — APPROVED** [review]
LGTM

**Comment by jthurne** [comment]
I'm looking into the build failures on this one.

At first glance, the pr-merge build failed due to one of the test tasks crashing. Presumably that's not related at all to this change, which doesn't touch the test tasks.

Some of the other failures site a RAT license check failure. I'm looking into this to make sure it isn't something new introduced by switching to the RAT plugin.

**Comment by jthurne** [comment]
I believe the license failures were caused by a different change to trunk that has since been fixed. I merged the latest trunk HEAD into this PR to re-trigger CI.

**Comment by ijuma** [comment]
Started another build (the previous got canceled due to environmental issues).

**Comment by ijuma** [comment]
@jthurne This change causes new failures:


> [2021-04-12T03:23:02.541Z] > A failure occurred while executing org.nosphere.apache.rat.RatWork
> 
> [2021-04-12T03:23:02.541Z]    > Apache Rat audit failure - 3 unapproved licenses
> 
> [2021-04-12T03:23:02.541Z]      	See file:///home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-10491/build/rat/index.html

**Comment by jthurne** [comment]
> @jthurne This change causes new failures:

Indeed. Unfortunately, I have been unable to reproduce them locally. One downside to the RAT plugin is that it doesn't output the files that fail the check to the build log. That makes this hard to diagnose since it seems to only happens on the CI server.

My suspicion, however, is that this has something to do with file encoding. I'll keep digging.

**Comment by ijuma** [comment]
This is the output:

> /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-10491/clients/src/test/resources/serializedData/topicPartitionSerializedfile
> /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-10491/clients/src/test/resources/serializedData/offsetAndMetadataWithLeaderEpoch
> /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-10491/clients/src/test/resources/serializedData/offsetAndMetadataBeforeLeaderEpoch

**Comment by jthurne** [comment]
Interesting. When I run the rat task locally, those three files are identified (correctly) as binary files and RAT skips them.

I'm not sure why they are being detected as text files on CI. But an easy workaround is to explicitly exclude that directory. I've pushed up a commit that does just that.

**Review by ijuma — APPROVED** [review]
LGTM. I also verified that `./gradlew rat` succeeds when there is no `.git` folder.

**Pull request merged**
