### PR TITLE
MINOR: Update copyright year in the NOTICE file.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Which branches should we merge this to?

**Comment by ewencp** [comment]
Trunk and 0.10.2 at least. It's possible we could cherry-pick it everywhere else we think we might release as well, so maybe merging to 0.10.1 as well is a good idea just in case?

**Comment by ijuma** [comment]
Sounds good.

**Pull request closed without merging**
