### PR TITLE
MINOR: the request thread in clientToControllerChannelManager is NOT…

### PR DESCRIPTION
**Pull request by chia7712**
I noticed this issue when running system tests. Most raft-related tests fails.

related to #10135

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
convert to draft as `alterIsrManager.start()` can start the request thread... will dig in it again.

**Comment by chia7712** [comment]
> convert to draft as alterIsrManager.start() can start the request thread... will dig in it again.

ugh, `alterIsrManager` take another `BrokerToControllerChannelManager`. ok. we do need to start the `clientToControllerChannelManager`

**Comment by dengziming** [comment]
It seems that this issue has been fixed by #10340.

**Comment by chia7712** [comment]
> It seems that this issue has been fixed by #10340.

You are right :)

close this now.

**Pull request closed without merging**
