### PR TITLE
KAFKA-3549: Close consumers instantiated in consumer tests

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR.

Another approach is the one done in `BaseProducerSendTest.createProducer` where we keep track of instantiated producers and close them in `tearDown`. It would be nice to have a consistent way to handle closable resources. Thoughts?

**Comment by granthenke** [comment]
@ijuma These tests leverage `BaseConsumerTest` and the `IntegrationTestHarness` that uses that pattern in most cases. This patch is closing the consumers that are not a part of that pattern and are specially instantiated in each test.

**Comment by ijuma** [comment]
@granthenke Yes, I realise that. The example I gave is for producers that are specially instantiated in each test and not via the usual harness way.

**Comment by ewencp** [comment]
@granthenke This does seem to be cleaning up some of the unreliability of builds on Confluent's Jenkins when I test it against this branch (based only on a couple of builds which passed on the first try, compared to our ~10% pass rate normally).

Agree with @ijuma that it might be better to leverage existing code for making sure things are cleaned up (and avoids a ton of `try`/`finally` blocks, which we kind of get implicitly with `tearDown`). It looks like we could just `append` to `producers` and `consumers` and `IntegrationTestHarness` takes care of the rest?

**Comment by granthenke** [comment]
@ewencp Glad to see it cleans some things up. 

I have updated the patch based on the advice you and @ijuma gave.

**Comment by ewencp** [comment]
@granthenke It looks like we might be missing some cases, but haven't been able to track down where yet. Your previous patch was passing regularly, but the tests I'm running on our Jenkins now are still hitting the same errors as before the patch.

I'm going to try to compare the previous patch and this one to track it down, but figured I'd let you know in case you have a better idea of where we might be missing one.

**Comment by ewencp** [comment]
LGTM

@granthenke This doesn't actually clear up the test failures, although does seem to alleviate things a bit for some reason. I have a theory about what might be causing the failures though, will post update in the JIRAs.

**Pull request closed without merging**
