### PR TITLE
MINOR: Typo correction

### PR DESCRIPTION
**Pull request by highluck**
Typo correction

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rondagostino — COMMENTED** [review]
LGTM

**Comment by highluck** [comment]
retest this please

**Comment by highluck** [comment]
@rondagostino
Build is not triggered

**Comment by highluck** [comment]
@ijuma 
Please review!
Thank you :)

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
ok to test

**Comment by highluck** [comment]
@ijuma 
The build failed..

**Comment by highluck** [comment]
@ijuma
The build failed..
retest please!
Thank you

**Comment by highluck** [comment]
@ijuma
Thankyou!

The failure below does not seem to be related to this.

**Comment by highluck** [comment]
@ijuma
Thankyou!

The failure below does not seem to be related to this.
Retest this please

**Pull request merged**
