### PR TITLE
KAFKA-10299: Implementing Kafka Connect Hash SMT to allow for hashing…

### PR DESCRIPTION
**Pull request by brbrown25**
… of message key or value.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
Thanks for the contribution. 
As this is adding new public classes, this change requires a KIP: https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals

**Comment by brbrown25** [comment]
@mimaison Thank You, I'll review and submit a KIP this afternoon!

**Comment by brbrown25** [comment]
@mimaison I've posted on the mailing list but not gotten any feedback. Is there anything you'd recommend, here is my most recent posting http://mail-archives.apache.org/mod_mbox/kafka-dev/202009.mbox/browser. Thanks!

**Comment by mimaison** [comment]
@brbrown25 I took a quick look at the KIP and replied to the thread on the mailing list. 
We do our best to review KIPs but sometimes it can take a little while. You can bump your thread (I recommended replying to the same thread instead of creating a new one in order to keep the history) if it's been a few weeks.

**Comment by brbrown25** [comment]
@mimaison I've updated the kip and put out a vote request but not seeing any action. I've gone ahead and updated this pr to be updated with latest trunk as well.

**Comment by brbrown25** [comment]
- [x] update with latest master
- [ ] implement nested field support
- [ ] implement salt support
- [x] update rat configuration

**Comment by mimaison** [comment]
The vote for https://cwiki.apache.org/confluence/display/KAFKA/KIP-665%3A+Kafka+Connect+Hash+SMT never passed. I'll close this for now, please reopen if KIP-665 is restarted and accepted.

**Comment by nick-zh** [comment]
@mimaison thanks for the update. I feel it's a nice addition especially if you want to keep the uniqueness of a value but want to hide it because of data privacy concerns. Is there a place where we can see why the vote failed? I checked the page you linked and also in Jira

**Comment by mimaison** [comment]
You can check the DISCUSS and VOTE threads in the Kafka dev mailing list archives: https://lists.apache.org/list?dev@kafka.apache.org:gte=1d:KIP-665

**Pull request closed without merging**
