### PR TITLE
KAFKA-2734: kafka-console-consumer throws NoSuchElementException on n…

### PR DESCRIPTION
**Pull request by SinghAsDev**
…ot specifying topic

### CODE REVIEW

**Comment by SinghAsDev** [comment]
@gwenshap this is worth taking a look. Not a blocker, but affects users and is probably on most common users' path.

**Comment by harshach** [comment]
@SinghAsDev I am noticing this as well. we should get this into 0.9. I see a unit test failing 
unit.kafka.tools.ConsoleConsumerTest > shouldParseValidOldConsumerValidConfig FAILED
    java.lang.AssertionError: expected:<test> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at unit.kafka.tools.ConsoleConsumerTest.shouldParseValidOldConsumerValidConfig(ConsoleConsumerTest.scala:67)
can you please fix that.

**Comment by SinghAsDev** [comment]
Sure Harsha, I will look into the test failure.

On Wed, Nov 4, 2015 at 11:16 AM, Harsha notifications@github.com wrote:

> @SinghAsDev https://github.com/SinghAsDev I am noticing this as well.
> we should get this into 0.9. I see a unit test failing
> unit.kafka.tools.ConsoleConsumerTest >
> shouldParseValidOldConsumerValidConfig FAILED
> java.lang.AssertionError: expected: but was:
> at org.junit.Assert.fail(Assert.java:88)
> at org.junit.Assert.failNotEquals(Assert.java:743)
> at org.junit.Assert.assertEquals(Assert.java:118)
> at org.junit.Assert.assertEquals(Assert.java:144)
> at
> unit.kafka.tools.ConsoleConsumerTest.shouldParseValidOldConsumerValidConfig(ConsoleConsumerTest.scala:67)
> can you please fix that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apache/kafka/pull/412#issuecomment-153835144.

## 

Regards,
Ashish

**Comment by guozhangwang** [comment]
With the new consumer, people can still specify "whielist" with regex subscription, can we incorporate this?

**Comment by SinghAsDev** [comment]
@guozhangwang that will require some changes to `NewShinyConsumer` and is probably out of scope of this JIRA. I will create a separate JIRA for that and provide a patch. This JIRA is just to avoid users getting weird exception, instead of usage info, when none of topic or whitelist or blacklist is specified. Even if we support whitelist for new consumer, this issue will still be there.

**Comment by guozhangwang** [comment]
LGTM.

**Pull request closed without merging**
