### PR TITLE
HOTFIX [WIP]: Check on not owned partitions

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by enothereska** [comment]
@guozhangwang  thanks for the fix, but I'm still not sure why this happens. Are we sure fix doesn't mask something else? In an ideal world we have a test for the symptom.

**Comment by guozhangwang** [comment]
@enothereska this is not a fix but rather adding a few more debugging info to reproduce the issue.

**Comment by enothereska** [comment]
Ah ok, thanks.

**Comment by mjsax** [comment]
Just for cross reference: the issue got reported at JIRA, too (https://issues.apache.org/jira/browse/KAFKA-5154).

**Pull request closed without merging**
