### PR TITLE
Added topicExists functions in AdminClient

### PR DESCRIPTION
**Pull request by makarushka**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@makarushka Could you share the motivation of adding this new method?

**Comment by makarushka** [comment]
> @makarushka Не могли бы вы поделиться мотивацией добавления этого нового метода?

We often use checking for an existing topic, and decided to send PR with this method.

**Comment by makarushka** [comment]
> @makarushka Could you share the motivation of adding this new method?

We very often need to find out if a topic exists, through AdminClient, we decided to add and parse PR.

**Comment by dajac** [comment]
@makarushka As the Admin client is a public API, this requires a KIP.

**Comment by makarushka** [comment]
> @makarushka As the Admin client is a public API, this requires a KIP.

Ok, we will do.
Thank you.

**Pull request closed without merging**
