### PR TITLE
Revert KAFKA-9309: Add the ability to translate Message to JSON

### PR DESCRIPTION
**Pull request by cmccabe**
This reverts commit bf6dffe93bbe0fe33ad076ebccebb840d66b936d

### CODE REVIEW

**Comment by cmccabe** [comment]
Looks like there is a checkstyle issue upstream:
```
12:59:42 > Task :streams:upgrade-system-tests-22:checkstyleTest FAILED
12:59:42 [ant:checkstyle] [ERROR] /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.13@2/streams/upgrade-system-tests-22/src/test/java/org/apache/kafka/streams/tests/StreamsSmokeTest.java:43: Line matches the illegal pattern ''System.exit': Should not directly call System.exit, but Exit.exit instead.'. [dontUseSystemExit]
```

**Comment by cmccabe** [comment]
retest this please

**Comment by cmccabe** [comment]
There seems to be a Jenkins issue here:
```
21:54:39 Fetching upstream changes from git://github.com/apache/kafka.git
21:54:39  > git fetch --tags --progress -- git://github.com/apache/kafka.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*
21:55:17 FATAL: java.io.IOException: Unexpected termination of the channel
21:55:17 java.io.EOFException
21:55:17 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
21:55:17 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
21:55:17 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
21:55:17 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
```

**Review by ijuma — APPROVED** [review]
LGTM if the tests pass. Can we validate that we can start a client with the `kafka-clients` jar and not have the exception reported in the original JIRA?

**Comment by cmccabe** [comment]
retest this please

**Comment by ijuma** [comment]
@cmccabe There's a checkstyle error, it seems.

**Comment by cmccabe** [comment]
Another Jenkins problem.
```
08:36:34  > git fetch --tags --progress -- git://github.com/apache/kafka.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*
08:37:17 FATAL: java.io.IOException: Unexpected termination of the channel
08:37:17 java.io.EOFException
08:37:17 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
08:37:17 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
```

**Comment by cmccabe** [comment]
retest this please

**Comment by cmccabe** [comment]
I verified that this removed the dependency by doing this:
```
./gradlew install -x check -x test
find | grep jackson | grep jar$ | xargs -l rm
```
And then testing the console consumer and console producer continued to work.

(Since the broker does require jackson to run I was using a prebuilt kafka to run the clients against).

Without this PR, the console consumer fails with this exception when the Jackson jars are not present:
```
[2020-08-19 11:27:53,468] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.sendFindCoordinatorRequest(AbstractCoordinator.java:787)
```

**Comment by cmccabe** [comment]
The failed test is flaky.  Committing now.  Thanks for the review

**Comment by ijuma** [comment]
Sounds great, thanks!

**Pull request merged**
