### PR TITLE
MINOR: Add HttpMetricsReporter for system tests

### PR DESCRIPTION
**Pull request by ewencp**
Author: Ewen Cheslack-Postava <me@ewencp.org>

Reviewers: Apurva Mehta <apurva@confluent.io>, Ismael Juma <ismael@juma.me.uk>

Closes #4072 from ewencp/http-metrics

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ewencp** [comment]
Minor modifications as follow up to https://github.com/apache/kafka/pull/4072 to get this included in 0.11.0 branch. Just validating build + tests.

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 5919 tests run, 0 skipped, 4 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 5919 tests run, 0 skipped, 4 failed.
--none--

**Comment by ewencp** [comment]
Running tests at https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1121/

**Comment by ewencp** [comment]
And one more time updated with fixes from #4214 https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1123/

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 5919 tests run, 0 skipped, 4 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 5919 tests run, 0 skipped, 4 failed.
--none--

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
Restarted the system tests run since there were some failures.

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 5919 tests run, 0 skipped, 4 failed.
--none--

**Comment by asfgit** [comment]
FAILURE
 5919 tests run, 0 skipped, 4 failed.
--none--

**Comment by ewencp** [comment]
Oops, also restarted it before seeing this. Rebuild is at https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1124/

**Comment by ewencp** [comment]
Finally, tests are clean, merging to 0.11.0

**Pull request closed without merging**
