### PR TITLE
KAFKA-12734: LazyTimeIndex & LazyOffsetIndex may cause niobufferoverflow when skip activeSegment sanityCheck

### PR DESCRIPTION
**Pull request by wenbingshen**
The detailed stack information is linked to this jiraId [KAFKA-12734](https://issues.apache.org/jira/browse/KAFKA-12734)

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wenbingshen** [comment]
@junrao @ijuma @chia7712 Can you take a look at this PR? Thanks. :)

**Comment by wenbingshen** [comment]
This is a problem we often encounter before applying LazyIndex. SanityCheck will help us rebuild the index, but after applying LazyIndex, it skips checking all index files, resulting in abnormal index files in the active segment. At this time, appending data to the log will cause niobufferoverflow exception.
image

**Comment by wenbingshen** [comment]
@junrao is busy with the work and affairs of the leader. @ijuma @chia7712 @hachikuji @alexandrfox @dajac @showuon Can you help me see this, or can you give some thoughts and suggestions? I have occasionally encountered this kind of problem in the production environment recently. I don't know what method can solve this problem. But I think it might be right to perform sanityCheck on the active segment.

**Comment by junrao** [comment]
@wenbingshen: Thanks for the PR. We recently fixed https://issues.apache.org/jira/browse/KAFKA-10471. Do you think this is the same problem or a different one?

**Comment by wenbingshen** [comment]
> @wenbingshen: Thanks for the PR. We recently fixed https://issues.apache.org/jira/browse/KAFKA-10471. Do you think this is the same problem or a different one?

@junrao Wow, great, I think they are the same problem. As you said, implementing sanityCheck is a solution, but the state consistency of the clean shutdown file is the root cause of the problem. I will apply KAFKA-10471 The patch to our company's kafka. Thank you very much for your help.

@ijuma @chia7712 @hachikuji @alexandrfox @dajac @showuon Sorry to disturb you, this problem has been fixed in 2.8, thank you very much! :)

**Comment by wenbingshen** [comment]
@junrao I did some thinking again today. The timeindex problems of [KAFKA-10471](https://issues.apache.org/jira/browse/KAFKA-10471) and [KAFKA-12734](https://issues.apache.org/jira/browse/KAFKA-12734) all come from `reset the index size of the currently active log segment to allow more entries`. Compared with directly deleting the cleanShutDownFiles file, does the impact of only detecting the index file of the active segment have less impact?

**Comment by junrao** [comment]
@wenbingshen : It would be useful to be clear what the PR wants to address. To me, if the index is corrupted because of our recovery logic (e.g., not handling cleaning shutdown file properly), we should just fix the cause. It's possible that after a clean restart, the index is corrupted due to storage issues. In that case, validating the index when the index is opened could potentially be useful. If we want to do that, it seems that we should we just do the validation on every index open, instead of just for the active segment?

**Comment by wenbingshen** [comment]
> @wenbingshen : It would be useful to be clear what the PR wants to address. To me, if the index is corrupted because of our recovery logic (e.g., not handling cleaning shutdown file properly), we should just fix the cause. It's possible that after a clean restart, the index is corrupted due to storage issues. In that case, validating the index when the index is opened could potentially be useful. If we want to do that, it seems that we should we just do the validation on every index open, instead of just for the active segment?

**Comment by wenbingshen** [comment]
> @wenbingshen : It would be useful to be clear what the PR wants to address. To me, if the index is corrupted because of our recovery logic (e.g., not handling cleaning shutdown file properly), we should just fix the cause. It's possible that after a clean restart, the index is corrupted due to storage issues. In that case, validating the index when the index is opened could potentially be useful. If we want to do that, it seems that we should we just do the validation on every index open, instead of just for the active segment?

@junrao Thank you for your reply. You've got a point there. This PR problem is really due to not handling cleaning shutdown file properly. It's right to fix the root cause. 
After a successful restart, the index file is damaged due to storage reasons. If we need to solve this problem, we need other PR to do it. For opening the index file, we may need to check the integrity just like checking the entries in the checkpoint file.
I will close this PR because the problem has been fixed. For the latter situation mentioned by you, I will think about it. If I have any good ideas, I will give you feedback again. Thank you. :)

**Pull request closed without merging**
