### PR TITLE
KAFKA-3264: Deprecate the old Scala consumer (KIP-109)

### PR DESCRIPTION
**Pull request by vahidhashemian**

### CODE REVIEW

**Comment by vahidhashemian** [comment]
@ijuma With the assumption that KIP-109 will pass I started implementing the deprecation. While I continue to work on this I'd appreciate it if you could take a look and let me know if you see issues with respect to what class/method/... should or should not be deprecated. Thanks.

**Comment by ijuma** [comment]
Sorry for the delay, I hope to take a look at this PR towards the end of this week.

**Comment by ijuma** [comment]
@vahidhashemian, if you have time, it would be good to do a follow-up PR that fixes the deprecation warnings that can be fixed:

1. Uses of the old consumers in tools and tests where the new consumer would work as well (or better).
2. Methods in `ClientUtils` that are called by server or tools code should be introduced in `AdminUtils` with the implementation living in `AdminUtils`. All the existing callers apart from the old clients should call the `AdminUtils` methods.

Thanks.

**Comment by vahidhashemian** [comment]
@ijuma Definitely, I'll look into fixing those two. Thanks.

**Pull request closed without merging**
