### PR TITLE
KAFKA-4643: Improve test coverage of StreamsKafkaClient

### PR DESCRIPTION
**Pull request by adyach**
The commit brings improved test coverage for StreamsKafkaClientTest.java

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6708/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
Thanks for the PR. We want to replace StreamsKafkaClient with the AdminClient introduced in 0.11.0.0, so not sure if it's worth it to add more tests. Not sure if this was explained in the JIRA. Sorry, if not. cc @enothereska @guozhangwang

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6693/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
We do want to replace with AdminClient at some time, but it's not sure if we will have time in the next 1.0.0 release. So I think this PR is still valuable. @dguy could you take a look at this one?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6730/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6715/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by dguy** [comment]
Looks like there is something up with this PR. There are a bunch of files that shouldn't be here, i.e, the documentation

**Comment by adyach** [comment]
@dguy sorry, I will reopen it against the latest master.

**Comment by adyach** [comment]
@dguy reopened #3663

**Pull request closed without merging**
