### PR TITLE
Don't throw exceptions in KafkaHealthcheck.handleNewSession. Should fix KAFKA-4277

### PR DESCRIPTION
**Pull request by Sh4pe**
### Problem we've encountered

We've had a problem recently with Kafka brokers that apparently did not work. The last remarkable message we found in our logs was [this](https://github.com/apache/kafka/blob/1.0/core/src/main/scala/kafka/utils/ZkUtils.scala#L440) Exception, which contained [KafkaHealthcheck.register()](https://github.com/apache/kafka/blob/1.0/core/src/main/scala/kafka/server/KafkaHealthcheck.scala#L59) in its stack trace.

In our case, the ephemeral Zookeeper node for the broker that [handleNewSession](https://github.com/apache/kafka/blob/1.0/core/src/main/scala/kafka/server/KafkaHealthcheck.scala#L119) should create apparently still existed - Kafka restarted too quickly after it crashed before. The exception caused by the attempt to re-create this Zookeeper node eventually causes [ZkEventThread.run()](https://github.com/sgroschupf/zkclient/blob/0.9/src/main/java/org/I0Itec/zkclient/ZkEventThread.java#L63) to idle, since the Exception is caught there and merely logged. Since no further Events occur, the event thread apparently idles.

### Solution and rationale

In order to have clean well-defined behavior in this case, we've decided that it would be best to finish the broker process in such a case. We've decided to `sys.exit(1)` and rely on the [shutdownHook](https://github.com/apache/kafka/blob/1.0/core/src/main/scala/kafka/Kafka.scala#L88) to do a proper shutdown.

This pull request contains the change described above. It should fix issue [KAFKA-4277](https://issues.apache.org/jira/browse/KAFKA-4277).

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Sh4pe** [comment]
I've looked into the JDK 10 tests and it seems to me that the failures are not caused by my change. Is there a way for me to fix them?

**Comment by ijuma** [comment]
Thanks for the PR. Why does it target the 1.0 branch instead of trunk? We generally merge to `trunk` first.

**Comment by Sh4pe** [comment]
Hi! Thanks for your reply! I've targeted the 1.0 branch because I thought this was the right way. Apparently I don't understand your branching strategy, sorry. So I should base my `fix/KAFKA-4277` branch on the current `trunk` and target my PR to `trunk` too? 

If the PR is merged eventually, how do the commit(s) come into a certain release? Do you use something like [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and `trunk` is your `develop` branch?

**Comment by ijuma** [comment]
Yes, contributions should target `trunk` by default. If necessary, we cherry-pick to existing release branches. If there are significant conflicts, we sometimes do a PR per release branch.

**Comment by Sh4pe** [comment]
I've looked into the current `trunk` and it appears that the code my PR affected has changed. The `KafkaHealthcheck` class is gone completely, it was removed in 27c2c81663d6518a3da5cfde88109f90ded8a6db, which is an ancestor of 1.1.0 but not 1.0.0. I'm not sure how to proceed. I see two options:

**A)** Fix the issue in a 1.0-based branch and have it merged in to a new 1.0-based release. This option is based on the assumption that the 1.0-based versions are still being worked on, which I'm not sure about.

**B)** Check if the problem of [KAFKA-4277](https://issues.apache.org/jira/browse/KAFKA-4277) still occurs in a 1.1-based release. If not, everything ought to be okay. It would be nice to have functional/integration tests that prove the problem exists in the 1.0-based release, but not in the 1.1-based one. I'd like to implement the tests by myself, but I'm new to the Kafka code and this could be quite a difficult task for me. And I don't know if my company is willing to switch to Kafka 1.1.x yet. I'll conform on the latter this week.

Do you have any suggestions on how I may proceed? Thank you very much for your input!

**Comment by ijuma** [comment]
I'd recommend option B. 2.0.0 will probably be released this week so the 1.0 branch will receive less attention going forward.

**Comment by Sh4pe** [comment]
I won't have time to work on this and I'd like to abandon this PR. @junrao @ijuma: if you are okay with this, this PR can be closed in my opinion.

**Comment by chia7712** [comment]
> I won't have time to work on this and I'd like to abandon this PR. @junrao @ijuma: if you are okay with this, this PR can be closed in my opinion.

@Sh4pe Thanks for your effort. I'm going to close this PR since https://issues.apache.org/jira/browse/KAFKA-4277 is already fixed.

**Pull request closed without merging**
