### PR TITLE
MINOR: Remove unused SecurityProtocol.TRACE

### PR DESCRIPTION
**Pull request by ijuma**
It adds complexity for no benefit since we don't use
it anywhere.

Also removed a few unused imports, variables and
default parameters.

### CODE REVIEW

**Comment by ijuma** [comment]
cc @rajinisivaram and @hachikuji

**Comment by omkreddy** [comment]
+1

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by hachikuji** [comment]
I'll merge if it's ok with @rajinisivaram. With this change, I think we can modify the `AuthenticationContext` object from KIP-189 to use `SecurityProtocol` as originally intended.

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Comment by rajinisivaram** [comment]
@hachikuji Thank you, sounds good. @ijuma Thanks for the PR.

**Comment by hachikuji** [comment]
retest this please

**Comment by hachikuji** [comment]
Looks like all the failures were in `SocketServerTest`. I'll make the obvious fix when I merge.

**Comment by ijuma** [comment]
Thanks for fixing that, I was away for a few hours.

**Pull request closed without merging**
