### PR TITLE
KAFKA-4893: Fix deletion and moving of topics with long names

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by ijuma** [comment]
We should mention the reduced limit in the release notes and update the docs where we state the current limit

**Review by mumrah — APPROVED** [review]
LGTM. Maybe include a comment above Topic#MAX_NAME_LENGTH explaining how we get that number

**Comment by wushujames** [comment]
What is the compatibility story for this change, if users already have topics that are longer than 209 characters?

**Comment by cmccabe** [comment]
@ijuma  wrote: 

> [we should] update the docs where we state the current limit

Good point.  Updated.

**Comment by cmccabe** [comment]
@mumrah wrote:

> LGTM. Maybe include a comment above Topic#MAX_NAME_LENGTH explaining how we get that number

Added

**Comment by cmccabe** [comment]
@wushujames asked:

> What is the compatibility story for this change, if users already have topics that are longer than 209 characters?

The topics will continue to work.  Additionally (in the latest patch), they should be deletable through a separate, synchronous code path.  However, we will not support modifying them with `alterLogDirs`.

**Comment by vahidhashemian** [comment]
Looks good to me. Just as an FYI, I discussed this alternative with @onurkaraman on the JIRA, and he suggested a more comprehensive solution. I drafted an initial PR a while back [here](https://github.com/apache/kafka/pull/4241).

**Comment by cmccabe** [comment]
@hachikuji suggested a better solution here.  There isn't any requirement that a DeleteDir have the same topic name prefix as the topic it came from.  That's just a convenience for debugging.  So we can truncate the topic name prefix if it gets too long.

In the case of `alterReplicaLogDirs`, the problem is harder to fix, since we do need the directory to have the same topic name prefix as the topic it came from.  However, we can just refuse to move the log directory if it is too long, for now.  The topic can still be deleted by the administrator if needed.

I implemented this in the latest patch -- take a look.  This will not require changing the maximum topic name length.

**Comment by cmccabe** [comment]
The failing test is `UncleanLeaderElectionTest`, which is known to be flaky, and not related to this change.  It passed locally for me.

**Review by gwenshap — APPROVED** [review]
LGTM

**Pull request closed without merging**
