### PR TITLE
MINOR: Fix Streams scala format violations

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@guozhangwang Pls take look. looks like we need to add "/gradlew spotlessApply"  gradle check to streams scala module to avoid format errors.

**Comment by guozhangwang** [comment]
Thanks for pointing out @omkreddy ! I overlooked this in Jenkins, and will update the corresponding job to add it in the configurations.

**Comment by guozhangwang** [comment]
@omkreddy do you happen to run this cmd manually and discovered the issue, or `gradlew build` will auto execute the cmd ?

**Comment by omkreddy** [comment]
Yes, ``` gradlew build``` is failing with format violations. I manually ran "/gradlew spotlessApply" to fix the errors.  Sorry, We need to  integrate " ./gradlew :spotlessScalaCheck"  to spot errors.

**Comment by guozhangwang** [comment]
I ran both cmds locally but did not produce any errors?

**Comment by omkreddy** [comment]
I am getting error with  ```./gradlew :spotlessScalaCheck```  or ```./gradlew build``` command

**Comment by guozhangwang** [comment]
Also filed https://github.com/apache/kafka/pull/5473

**Pull request merged**
