### PR TITLE
Murmur3 Hash with Guava dependency

### PR DESCRIPTION
**Pull request by bellemare**
Part of supporting KIP-213 ( https://cwiki.apache.org/confluence/display/KAFKA/KIP-213+Support+non-key+joining+in+KTable ). Murmur3 hash is used as a hashing mechanism in KIP-213 for the large range of uniqueness. The Murmur3 class and tests are ported directly from Apache Hive, with no alterations to the code or dependencies.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@ijuma  , do you have any concerns about bringing this in? Not sure who else's opinion to seek.

**Comment by ijuma** [comment]
We don't want to add a dependency to `Guava` in the `clients` module.

**Comment by bellemare** [comment]
@ijuma - Two questions - who is the we in "we don't want to add..."? Secondly, is there a particular reason that Guava is not acceptable considering it is only as part of test and not part of source? I'm just trying to get an understanding here as to how dependency-inclusion/exclusions are made.

**Comment by ijuma** [comment]
Sorry, I didn't notice it was a test only dependency. The general policy for the `clients` module is to have minimal dependencies. For tests, we are not as strict. Having said that, `guava` causes huge issues because it's widely used and different projects rely on different versions. So the motivation has to be strong to include it. What is it in this case?

**Comment by ijuma** [comment]
Also, did we consider https://cyan4973.github.io/xxHash/ ?

**Comment by bellemare** [comment]
@ijuma I was looking at Murmur3 for a hash because it is very important for us to be able to detect changes, as we are using the hash to ensure that only the correct event is propagated and ones that do not match the hash are discarded. Minor changes are very likely in these events, as we're joining entities that may have a single property changed in rapid succession, requiring a very high likelihood of uniqueness for even very minor changes in the event.

The speed of xxhash isn't particularly important in this scenario because the events are serialized and sent over the wire to other partitions after being hashed, so the overhead from that is many times larger than any hash function speed. Uniqueness is pretty much the biggest criteria here, and Murmur3's 128-bits gives an extremely high likelihood that unique events will be correctly hashed as such. If we have to drop down to 64-bits and use xxHash I am fine with that as it's still _unlikely_ we'll have a problem, but the likelihood is way higher than it is with Murmur3's 128-bit hash.

**Comment by vvcephei** [comment]
Thanks for the explanation, @bellemare . Just adding my +1; we discussed different hash algorithms in the KIP-213 discussion and settled on 128-bit Murmur3.

I don't recall if we discussed xxHash, but I do agree with Adam's assessment, speed is important of course, but not as important as certainty. In any case, I'd be surprised if we are CPU bound for KIP-213 anyway.

**Comment by vvcephei** [comment]
@guozhangwang @bbejeck ,

Do you mind giving this a quick review?

@ijuma ,

It sounds like your major concern is around adding Guava as a test dependency. I had the same concern. It seems like a bit of a trap, because the Murmur3 implementation is copy/pasted. We should try not to modify the source of the main code or the tests, so that the project can stay mergeable with upstream.

Some options I see:
1) just pull in guava as a test dependency. Note that once it's included, it will most likely spider its way through the whole project's tests, so we should evaluate this as a project level decision to use Guava for tests.
2) move Murmur3 to a separate module (aka gradle project, but still in the AK repo/build). This way, we can isolate Guava _only_ to the test for Murmur3.
3) implement identically named test utility methods to the ones that this one depends on from Guava. That way, only the imports would change, and for the most part, it would be easy to merge changes from upstream.

WDYT?

**Comment by vvcephei** [comment]
Retest this, please.

**Comment by guozhangwang** [comment]
I'm not too concerned about guava version conflict since so far I've only seen jersey-guava used by tools in our repo.

**Comment by vvcephei** [comment]
Hey, all, the original PR (https://github.com/apache/kafka/pull/5527) is getting kind of close to mergeable. Can we make a call on this PR before it blocks 5527?

Thanks,
-John

**Comment by guozhangwang** [comment]
I'm +1 on bringing in the dependency.

**Comment by bbejeck** [comment]
I'm +1 as well, as it's a test dependency.  But I don't know all the implications on the project. 

@ijuma WDYT?

**Comment by ijuma** [comment]
I don't understand why we need the dependency. It seems trivial to copy the expected values in our test.

**Comment by bellemare** [comment]
That is true, I could hardwire the expected values in. 
EDIT: However, there are indeed a number of 1000-iteration loops that look like it could be overly verbose and time-consuming to generate and validate.

**Comment by ijuma** [comment]
Btw, also see https://fastcompression.blogspot.com/2019/03/presenting-xxh3.html

It may be true that performance is not needed in this case, but it may be needed in others. From a maintenance perspective, it's easier to rely on a hash that is both fast and provides the uniqueness we need.

**Comment by bellemare** [comment]
@ijuma Not sure about this one (yet) as according to the last paragraph:

> XXH3 is now released as part of xxHash v0.7.0. It’s still labelled “experimental”, and must be unlocked using macro XXH_STATIC_LINKING_ONLY. It’s suitable for ephemeral data and tests, but avoid storing long-term hash values yet. This period will be used to gather user’s feedback, after which the algorithm will transferred into stable in a future release.

Is this not of some concern if I want to use this to get 128-bit hashes?

**Comment by guozhangwang** [comment]
Since the test we are copying here is actually just check that the logic of Murmur3 is consistent with the `Murmur3_32HashFunction` and `Murmur3_128HashFunction` which is relying on the const `0xcc9e2d51` etc as well, moving the static values and removing seeds to not introduce the dependency makes feel that we are effectively defeating the purpose of copying the test anyways. 

I'd suggest we just reduce the test to UtilTest.java where we just tested a few const with hard-coded expected values:

```
public void testMurmur2() {
        Map<byte[], Integer> cases = new java.util.HashMap<>();
        cases.put("21".getBytes(), -973932308);
        cases.put("foobar".getBytes(), -790332482);
        cases.put("a-little-bit-long-string".getBytes(), -985981536);
        cases.put("a-little-bit-longer-string".getBytes(), -1486304829);
        cases.put("lkjh234lh9fiuh90y23oiuhsafujhadof229phr9h19h89h8".getBytes(), -58897971);
        cases.put(new byte[]{'a', 'b', 'c'}, 479470107);

        for (Map.Entry c : cases.entrySet()) {
            assertEquals((int) c.getValue(), murmur2((byte[]) c.getKey()));
        }
    }
```

And remove the Murmur3Test, @bellemare does that sound good to you?

**Comment by bellemare** [comment]
@guozhangwang that would work for me - @ijuma ?

**Comment by vvcephei** [comment]
Sounds good to me also. I'd just go for it, since it removes the Guava concern. IMHO, we can bring in xxHash as well (or replace Murmur3 with it) later on with not too much wasted effort.

**Comment by guozhangwang** [comment]
@bellemare Okay let's do this and I will review again and merge when you're ready.

**Comment by ijuma** [comment]
Btw, is there any reason why this is in clients and not Streams?

**Comment by guozhangwang** [comment]
Streams already depends on clients but not vice versa, I think it is better to put it in clients so that in the futures if murmur3 want to be used elsewhere we can avoid possible code duplicates -- we have already observed such issues in the past, e.g. connect's `JsonDeserializer` etc are hard be leveraged by other modules without introducing extra dependency.

**Comment by bellemare** [comment]
Okay, done the changes for murmur3 and removed the guava dependency. Does this work?

**Review by guozhangwang — APPROVED** [review]
LGTM, waiting for the newly added test to pass.

**Comment by guozhangwang** [comment]
@bellemare the checkstyle failed: 

```
clients:checkstyleTest
```

Also, after syncing with @ijuma offline I think we can move murmur3 into streams for now. The rationales behind it is that:

* murmur3 is no longer the best performant hashing function as of today, and at the same time any migrations away from the existing murmur2 to new libraries would be backward incompatible; so in the future when we want to use new hashing function elsewhere we would consider a different function -- i.e. it is not very likely to be shared outside Streams
* This class is not a public API, so keeping in Streams does not really prevent the future possibility if we wants to move it elsewhere -- we just need to make sure that any dependencies of AK would not refer to such internal classes, which should be very, very rare.

WDYT? I can help moving them to Streams when merging your PR if it looks fine to you.

**Comment by bellemare** [comment]
@guozhangwang - sounds good to me. I fixed the checkstyleTest issues.

So you're going to move the files under streams when this is committed?

**Comment by guozhangwang** [comment]
> So you're going to move the files under streams when this is committed?

Yes, that's my plan.

**Review by vvcephei — APPROVED** [review]

**Comment by guozhangwang** [comment]
Merged to trunk with Murmur3 moved to Streams, thanks @bellemare for your patience!

**Pull request closed without merging**
