### PR TITLE
MINOR: Ignore streams-broker-upgrade-test

### PR DESCRIPTION
**Pull request by guozhangwang**
This should be cherry-picked to older branches as well.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@mjsax @bbejeck

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.2`.

@guozhangwang Can you create a ticket to track that we need to address this and reenable (or remove?) this test?

**Comment by guozhangwang** [comment]
Yes: https://issues.apache.org/jira/browse/KAFKA-8017

BTW I think we should cherry-pick all they way back to 1.0 as well.

**Comment by mjsax** [comment]
Thanks for the ticket.

Also cherry-picked to `2.0`, `1.1`, and `1.0` (test was already disabled in `2.1`)

**Pull request merged**
