### PR TITLE
MINOR: Fix FetchRequest.getErrorResponse for version 1

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by ijuma** [comment]
@granthenke, nice catch. Can you please add a test in `RequestResponseTest`? It should be straightforward.

**Comment by granthenke** [comment]
@ijuma Good point. Turns out the original code, even though checking version 0, was using the v1 constructor.

**Comment by granthenke** [comment]
ping @gwenshap

**Comment by gwenshap** [comment]
@granthenke I think this was the same issue as KAFKA-3427?

**Comment by ijuma** [comment]
@gwenshap this is for the Java class, that one was for the Scala one.

**Comment by ijuma** [comment]
@granthenke, it looks like this needs to be rebased.

**Comment by granthenke** [comment]
@ijuma @gwenshap @junrao rebased the patch

**Comment by ijuma** [comment]
LGTM

**Comment by junrao** [comment]
Thanks for the patch. LGTM

**Pull request closed without merging**
