### PR TITLE
KAFKA-5752: Update timeIndex, txnIndex file pointers to renamed (to be deleted) files

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by omkreddy** [comment]
didn't find any easy way to test this. pl let me know if you have any ideas

**Review by ijuma — COMMENTED** [review]
Thanks for the PR. With regards to the test, `asyncDelete` could return the removed log and we can inspect that the segments and log all point to the renamed directory.

**Comment by ijuma** [comment]
We should probably also add a test that deletes a topic and adds it back as this tends to uncover issues.

**Comment by omkreddy** [comment]
@ijuma added a simple test to check the file pointers. 
We already have a "DeleteTopicTest.testRecreateTopicAfterDeletion " test. not sure this helps us to uncover these kinds of issues.

**Comment by ijuma** [comment]
@omkreddy thanks for the update. A few suggested improvements:

https://github.com/ijuma/kafka/commit/193a0c0a3c63055e0d2377df03dac790555bdb9f

If you agree, please include them in your PR.

**Comment by omkreddy** [comment]
@ijuma Thanks for the improvements. Updated the PR with your changes.

**Review by ijuma — APPROVED** [review]
Thanks, LGTM. Will merge to trunk and 0.11.0 branches after the Jenkins builds complete.

**Pull request closed without merging**
