### PR TITLE
MINOR: More graceful handling of buffers that are too small in Record's `isValid` and `ensureValid`

### PR DESCRIPTION
**Pull request by ijuma**
Also add tests and make `Crc32.update` perform the same argument checks as
`java.util.zip.CRC32`.

### CODE REVIEW

**Comment by gwenshap** [comment]
LGTM. Looks nice :)

**Comment by gwenshap** [comment]
ah, sorry - didn't notice the merge conflict. Rebase and ping me?

**Comment by ijuma** [comment]
Thanks for the review @gwenshap, rebased the PR.

**Comment by gwenshap** [comment]
oops, missed the update. sorry for delay. LGTM and merging.

**Pull request closed without merging**
