### PR TITLE
KAFKA-7332: Update CORRUPT_MESSAGE exception message description

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
@ijuma  minor change to print proper error message on producer side, when we produce a message without key to a compacted topic.

**Comment by omkreddy** [comment]
@ijuma Can you take a look at this trivial PR?

**Comment by omkreddy** [comment]
@lindong28 Can you take a look at this trivial PR?

**Comment by lindong28** [comment]
Thanks for the patch @omkreddy. Could you help me understand the code path that throws CorruptRecordException when there is a message without key in log compacted topic? I just want to double check the code in addition to the error reported in the JIRA ticket. Thanks.

**Comment by omkreddy** [comment]
@lindong28  Thanks for the review.  We are throwing InvalidRecordException (which extends CorruptRecordException) for messages without key for compacted topics here:
https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/log/LogValidator.scala#L374

**Comment by lindong28** [comment]
Thanks for the link @omkreddy. LGTM. Merged to trunk.

**Pull request closed without merging**
