### PR TITLE
KAFKA-2982; Mark the old Scala producer and related classes as deprecated

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
This depends on and includes https://github.com/apache/kafka/pull/1042

Ideally #1042 would be merged first.

**Comment by gwenshap** [comment]
It is kind of hard to review due to the overlap with 1042. Does it need rebase now that 1042 was merged?

**Comment by ijuma** [comment]
That's right @gwenshap, I have rebased now.

**Comment by ijuma** [comment]
Hmm, I need to do more work to reduce warnings in tests, so closing until that's done.

**Pull request closed without merging**
