### PR TITLE
MINOR: Upgrade to Gradle 4.10.3

### PR DESCRIPTION
**Pull request by ijuma**
This includes a fix for an issue that required manual intervention
during the 2.1.0 release: the unexpected existence of a .mapping
file in the Maven repository.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Note that this PR is for the 2.1 branch since trunk is using Gradle 5.

**Comment by gwenshap** [comment]
LGTM. Test failures look unrelated. (sorry for the takeover @rajinisivaram).

**Comment by gwenshap** [comment]
FYI: I have trouble pushing the merge, presumably because my apache account wasn't linked to Github. Waiting an hour for the change to take effect and trying again.

**Comment by gwenshap** [comment]
Looks like the commit didn't close the PR because it isn't on trunk? 
I thought it should though. Any idea how to close this?

**Comment by ijuma** [comment]
I've done it. :)

**Pull request closed without merging**
