### PR TITLE
[KAFKA-1194 Invokes unmap if on Windows OS]

### PR DESCRIPTION
**Pull request by manmedia**
If on Windows OS, forces unmapping of mmap so that segment suffixes can be changed.

### CODE REVIEW

**Comment by rasa-silva** [comment]
I applied the patch on the 0.11 branch.
While running the build on Windows, some tests appear to fail randomly but the same is true without the patch applied.

I did some tests and the patch itself seems to work. The files are rotated cleanly and without errors.
The same is not true with vanilla branch that currently isn't able to do the rotation at all.

Since the patch is minimal, a NOP on non-Windows and makes Windows at least usable, it seems a low risk/high reward situation.

**Comment by jasonaliyetti** [comment]
For what it's worth, this seems to be similar to what's trying to be accomplished in https://github.com/apache/kafka/pull/3283, which is a more comprehensive fix.  My co-workers and I are trying to get Kafka 0.11 stable on Windows - we've addressed the filesystem issues using the changes from that PR but there seems to be an issue with transactions that causes the tests to hang though.

I don't mean to hijack this PR (apologies in advance @manmedia), but figured it might be useful to point out the duplicated efforts to bring Windows support to Kafka.  

This seems to be a popular ask - I've seen this change and similar changes created and submitted in a PR multiple times now and they always seem to languish and die on the vine.

@nxmbriggs404 - tagging you just as an FYI

**Comment by nxmbriggs404** [comment]
@jasonaliyetti  thanks for the heads up, I've been meaning to get back to digging into Kafka 0.11 on Windows.  Your experience with transaction tests hanging sounds believable to me.  When I last looked at the 0.11 code, my first impression was that some of the low level log code had been duplicated for the new transaction features.  Unfortunately it looked like that new code had some of the same file mapping patterns that cause troubles for Windows.  I haven't studied the transaction support mechanics in detail yet, but that was going to be the primary area I was going to target in order to get more 0.11 tests passing for me.

**Comment by manmedia** [comment]
@rasa-silva Thanks a lot for looking into this. The reason I put this fix in is because there was no attempt from the main Kafka dev group to address this. My assumption was that all hardcore development happens on UNIX/LINUX base so having Windows support probably wasn't deemed necessary. Conversely, a solution must work in any OS. I have been using the client JAR with this path on my Windows and so far no issues. I am happy if someone has a comprehensive approach, bu this solution works with existing UNIT tests and any failure is not subject to my patch.

**Comment by manmedia** [comment]
Resolves Merge Conflict occurred when added patch for #1194

**Pull request closed without merging**
