### PR TITLE
MINOR: remove unnecessary null checks

### PR DESCRIPTION
**Pull request by smurakozi**
Remove unnecessary null check in StringDeserializer, MockProducerInterceptor and KStreamImpl.

### CODE REVIEW

**Comment by smurakozi** [comment]
[KAFKA-6233](https://issues.apache.org/jira/browse/KAFKA-6233) removed unnecessary null check from StringSerializer, but it left the same in StringDeserializer. A quick search has shown two other occurrences of the same check.

**Comment by smurakozi** [comment]
retest this, please

**Review by vahidhashemian — APPROVED** [review]
LGTM. Thanks for the patch.

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch!

**Pull request merged**
