### PR TITLE
Minor init singleton list

### PR DESCRIPTION
**Pull request by khaireddine120**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
Ok to test

**Comment by bbejeck** [comment]
Retest this please

**Comment by mumrah** [comment]
@bbejeck update this branch with trunk and the PR builder should start working

**Comment by bbejeck** [comment]
@khaireddine120 can you rebase this PR against trunk? Then after the build we can get this merged.

**Comment by bbejeck** [comment]
This PR is minor changes for streams.  I ran the tests locally, so I merging this.

**Comment by bbejeck** [comment]
Thanks for the contribution @khaireddine120!

**Pull request merged**
