### PR TITLE
KAFKA-17194: Don't create cluster for MetadataQuorumCommandTest#testCommandConfig

### PR DESCRIPTION
**Pull request by wernerdv**
Did `testCommandConfig` a unit test instead of an integration test.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wernerdv** [comment]
Hi @chia7712
There are failed tests `MetadataQuorumCommandTest.testDescribeQuorumReplicationSuccessful` in the report: https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-16682/2/testReport/
Locally all tests in `MetadataQuorumCommandTest` passed.
Can you take a look?

**Comment by wernerdv** [comment]
https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-16682/3/testReport/org.apache.kafka.tools/MetadataQuorumCommandTest/

**Comment by chia7712** [comment]
Thanks for this patch. I am traveling. Will take a look next Monday 😄

**Review by frankvicky — APPROVED** [review]
LGTM 😺

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
