### PR TITLE
KAFKA-7976 - Fix DynamicBrokerReconfigurationTest.testUncleanLeaderElectionEnable

### PR DESCRIPTION
**Pull request by rajinisivaram**
Ensure that controller is not shutdown in the test.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rajinisivaram** [comment]
retest this please

**Comment by rajinisivaram** [comment]
Test failures in last run unrelated. Doing another PR build since this was an intermittent failure.

**Comment by omkreddy** [comment]
retest this please

**Review by omkreddy — APPROVED** [review]
@rajinisivaram Thanks for the PR. LGTM.

**Comment by rajinisivaram** [comment]
@omkreddy Thanks for the review, merging to trunk and 2.2.

**Pull request merged**
