### PR TITLE
KAFKA-14299: Avoid allocation & synchronization overhead in StreamThread loop

### PR DESCRIPTION
**Pull request by lucasbru**
The state updater code path introduced allocation and synchronization overhead by 
performing relatively heavy operations in every iteration of the `StreamThread` loop. This 
includes various allocations and acquiring locks for handling `removedTasks` and 
`failedTasks`, even if the corresponding queues are empty.

This change introduces `hasRemovedTasks` and `hasExceptionsAndFailedTasks` in the 
`StateUpdater` interface that can be used to skip over any allocation or synchronization. 
The new methods do not require synchronization or memory allocation.

We extend existing unit tests to cover the slightly modified behaviour. The change was also 
benchmarked (on top of other changes for KAFKA-14299) and increased throughput by 
~15% in this one (state heavy) benchmark.

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lucasbru** [comment]
@cadonna Could you have a look, please?

**Comment by cadonna** [comment]
Test failures in `TaskManagerTest` are related.

**Review by cadonna — APPROVED** [review]
LGTM!

**Comment by cadonna** [comment]
Build failures are not related:
```
Build / JDK 11 and Scala 2.13 / kafka.network.ConnectionQuotasTest.testListenerConnectionRateLimitWhenActualRateAboveLimit()
```

**Pull request merged**
