### PR TITLE
KAFKA-18261: Remove TestUtils#createBrokerConfigs zkConnect argument

### PR DESCRIPTION
**Pull request by m1a2st**
Jira: https://issues.apache.org/jira/browse/KAFKA-18261

We remove all zk test, thus we should refactor some TestUtils method

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@m1a2st thanks for this patch. Could you please remove `TestUtils#createTopic` as well? the only user is `CustomQuotaCallbackTest` and we can replace the usage by a simple comment as the test is disabled for now

**Comment by TaiJuWu** [comment]
All failure.

Found 172 test failures:
FAILED ❌ ReplicaManagerTest > testBecomeFollowerWhenLeaderIsUnchangedButMissedLeaderUpdateIbp26()
FAILED ❌ DynamicBrokerConfigTest > testPasswordConfigEncryption()
FAILED ❌ DynamicBrokerConfigTest > testDynamicListenerConfig()
FAILED ❌ DynamicBrokerConfigTest > testPasswordConfigEncoderSecretChange()
FAILED ❌ ConnectionQuotasTest > testFailDecrementForUnknownIp()
FAILED ❌ ConnectionQuotasTest > testIpConnectionRateWhenActualRateBelowLimit()
FAILED ❌ ConnectionQuotasTest > testMaxConnectionsPerIp()
FAILED ❌ ConnectionQuotasTest > testIpConnectionRateWithListenerConnectionRate()
FAILED ❌ ConnectionQuotasTest > testMaxBrokerWideConnectionLimit()
FAILED ❌ ConnectionQuotasTest > testMaxListenerConnectionListenerMustBeAboveZero()
FAILED ❌ ConnectionQuotasTest > testBrokerConnectionRateLimitWhenActualRateAboveLimit()
FAILED ❌ ConnectionQuotasTest > testNoConnectionLimitsByDefault()
FAILED ❌ ConnectionQuotasTest > testMaxListenerConnectionLimits()
FAILED ❌ ConnectionQuotasTest > testBrokerConnectionRateLimitWhenActualRateBelowLimit()
FAILED ❌ ConnectionQuotasTest > testIpConnectionRateMetricUpdate()
FAILED ❌ ConnectionQuotasTest > testNonDefaultConnectionCountLimitAndRateLimit()
FAILED ❌ ConnectionQuotasTest > testRejectedIpConnectionUnrecordedFromConnectionRateQuotas()
FAILED ❌ ConnectionQuotasTest > testMaxListenerConnectionRateReconfiguration()
FAILED ❌ ConnectionQuotasTest > testListenerConnectionRateLimitWhenActualRateAboveLimit()
FAILED ❌ ConnectionQuotasTest > testEnforcedIpConnectionRateQuotaUpdate()
FAILED ❌ ConnectionQuotasTest > testMaxBrokerConnectionRateReconfiguration()
FAILED ❌ ConnectionQuotasTest > testListenerConnectionRateLimitWhenActualRateBelowLimit()
FAILED ❌ ConnectionQuotasTest > testFailWhenNoListeners()
FAILED ❌ ConnectionQuotasTest > testIpConnectionRateWhenActualRateAboveLimit()
FAILED ❌ DescribeTopicPartitionsRequestHandlerTest > testDescribeTopicPartitionsRequestWithEdgeCases()
FAILED ❌ DescribeTopicPartitionsRequestHandlerTest > testDescribeTopicPartitionsRequest()
FAILED ❌ SocketServerTest > testConnectionIdReuse()
FAILED ❌ SocketServerTest > testSaslReauthenticationFailureNoKip152SaslAuthenticate()
FAILED ❌ SocketServerTest > remoteCloseWithBufferedReceivesFailedSend()
FAILED ❌ SocketServerTest > remoteCloseSendFailure()
FAILED ❌ SocketServerTest > testControlPlaneTakePrecedenceOverInterBrokerListenerAsPrivilegedListener()
FAILED ❌ SocketServerTest > testLatencyWithBufferedDataAndNoSocketData()
FAILED ❌ SocketServerTest > remoteCloseWithCompleteAndIncompleteBufferedReceives()
FAILED ❌ SocketServerTest > testSaslReauthenticationFailureWithKip152SaslAuthenticate()
FAILED ❌ SocketServerTest > testUnmuteChannelWithBufferedReceives()
FAILED ❌ SocketServerTest > remoteCloseWithIncompleteBufferedReceive()
FAILED ❌ SocketServerTest > testStagedListenerShutdownWhenConnectionQueueIsFull()
FAILED ❌ SocketServerTest > testStagedListenerStartup()
FAILED ❌ SocketServerTest > testControlPlaneAsPrivilegedListener()
FAILED ❌ SocketServerTest > closingChannelSendFailure()
FAILED ❌ SocketServerTest > idleExpiryWithBufferedReceives()
FAILED ❌ SocketServerTest > closingChannelWithBufferedReceivesFailedSend()
FAILED ❌ SocketServerTest > remoteCloseWithBufferedReceives()
FAILED ❌ SocketServerTest > closingChannelWithCompleteAndIncompleteBufferedReceives()
FAILED ❌ SocketServerTest > testInterBrokerListenerAsPrivilegedListener()
FAILED ❌ SocketServerTest > testSslSocketServer()
FAILED ❌ KafkaConfigTest > testControlPlaneListenerName()
FAILED ❌ KafkaConfigTest > testAcceptsNegativeOneNodeIdForZkBasedCaseWithAutoGenEnabled()
FAILED ❌ KafkaConfigTest > testAcceptsLargeNodeIdForZkBasedCaseWithAutoGenDisabled()
FAILED ❌ KafkaConfigTest > testInvalidAdvertisedListenersProtocol()
FAILED ❌ KafkaConfigTest > testInterBrokerVersionMessageFormatCompatibility()
FAILED ❌ KafkaConfigTest > testValidEmptyQuorumVotersParsing()
FAILED ❌ KafkaConfigTest > testEqualAdvertisedListenersProtocol()
FAILED ❌ PlaintextAdminIntegrationTest > testConsumerGroups(String, String).quorum=kraft.groupProtocol=consumer
FAILED ❌ ReplicaFetcherThreadTest > shouldFetchLeaderEpochSecondTimeIfLeaderRepliesWithEpochNotKnownToFollower()
FAILED ❌ ReplicaFetcherThreadTest > shouldTruncateToInitialFetchOffsetIfLeaderReturnsUndefinedOffset()
FAILED ❌ ReplicaFetcherThreadTest > shouldFetchLeaderEpochOnFirstFetchOnlyIfLeaderEpochKnownToBothIbp26()
FAILED ❌ ReplicaFetcherThreadTest > shouldPollIndefinitelyIfLeaderReturnsAnyException()
FAILED ❌ ReplicaFetcherThreadTest > shouldTruncateToOffsetSpecifiedInEpochOffsetResponse()
FAILED ❌ ReplicaFetcherThreadTest > testFetchLeaderEpochRequestIfLastEpochDefinedForSomePartitions()
FAILED ❌ ReplicaFetcherThreadTest > shouldTruncateToOffsetSpecifiedInEpochOffsetResponseIfFollowerHasNoMoreEpochs()
FAILED ❌ ReplicaFetcherThreadTest > shouldUseLeaderEndOffsetIfInterBrokerVersionBelow20()
FAILED ❌ ReplicaFetcherThreadTest > shouldMovePartitionsOutOfTruncatingLogState()
FAILED ❌ ReplicaFetcherThreadTest > shouldFilterPartitionsMadeLeaderDuringLeaderEpochRequest()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeRequestSuccessOnFinalEpoch()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardRenewTokenRequest()
FAILED ❌ KafkaApisTest > shouldThrowUnsupportedVersionExceptionOnHandleTxnOffsetCommitRequestWhenInterBrokerProtocolNotSupported()
FAILED ❌ KafkaApisTest > testGetTelemetrySubscriptionsWithException()
FAILED ❌ KafkaApisTest > testHandleAcknowledgementsUnauthorizedTopics()
FAILED ❌ KafkaApisTest > testLog4jIncrementalAlterConfigsRequestWithKRaft()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeRequestSuccess()
FAILED ❌ KafkaApisTest > testConsumerGroupHeartbeatRequestAuthorizationFailed()
FAILED ❌ KafkaApisTest > testWriteShareGroupStateAuthorizationFailed()
FAILED ❌ KafkaApisTest > testReadShareGroupStateSuccess()
FAILED ❌ KafkaApisTest > testEmptyLegacyAlterConfigsRequestWithKRaft()
FAILED ❌ KafkaApisTest > testElectLeadersForwarding()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestInvalidRequestOnInitialEpoch()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestInvalidRequestOnFinalEpoch()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeRequestGroupAuthorizationError()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardCreateAcls()
FAILED ❌ KafkaApisTest > testListClientMetricsResourcesEmptyResponse()
FAILED ❌ KafkaApisTest > shouldThrowUnsupportedVersionExceptionOnHandleAddPartitionsToTxnRequestWhenInterBrokerProtocolNotSupported()
FAILED ❌ KafkaApisTest > testShareGroupHeartbeatRequestAuthorizationFailed()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardAlterClientQuotasRequest()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardDeleteAcls()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestAcknowledgeThrowsException()
FAILED ❌ KafkaApisTest > testRaftShouldNeverHandleUpdateMetadataRequest()
FAILED ❌ KafkaApisTest > testConsumerGroupDescribeAuthorizationFailed()
FAILED ❌ KafkaApisTest > testGetAcknowledgeBatchesFromShareAcknowledgeRequestError()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestShareSessionSuccessfullyEstablished()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeRequestInvalidRequestOnInitialEpoch()
FAILED ❌ KafkaApisTest > testProcessShareAcknowledgeResponse()
FAILED ❌ KafkaApisTest > "testConsumerGroupDescribe(boolean).includeAuthorizedOperations=true"
FAILED ❌ KafkaApisTest > "testConsumerGroupDescribe(boolean).includeAuthorizedOperations=false"
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardCreatePartitionsRequest()
FAILED ❌ KafkaApisTest > shouldThrowUnsupportedVersionExceptionOnHandleWriteTxnMarkersRequestWhenInterBrokerProtocolNotSupported()
FAILED ❌ KafkaApisTest > testGetAcknowledgeBatchesFromShareFetchRequestError()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestGroupAuthorizationError()
FAILED ❌ KafkaApisTest > testGetAcknowledgeBatchesFromShareAcknowledgeRequest()
FAILED ❌ KafkaApisTest > testConsumerGroupHeartbeatRequestFutureFailed()
FAILED ❌ KafkaApisTest > testRaftShouldNeverHandleLeaderAndIsrRequest()
FAILED ❌ KafkaApisTest > testHandleAcknowledgementsSuccess()
FAILED ❌ KafkaApisTest > testDescribeQuorumForwardedForKRaftClusters()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardDeleteTopicsRequest()
FAILED ❌ KafkaApisTest > testHandleAcknowledgementsWithErroneous()
FAILED ❌ KafkaApisTest > testShareGroupHeartbeatReturnsUnsupportedVersion()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestShareSessionNotFoundError()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardCreateTokenRequest()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardListPartitionReassignments()
FAILED ❌ KafkaApisTest > testEmptyIncrementalAlterConfigsRequestWithKRaft()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeShareGroupDisabled()
FAILED ❌ KafkaApisTest > rejectSyncGroupRequestWhenStaticMembershipNotSupported()
FAILED ❌ KafkaApisTest > rejectHeartbeatRequestWhenStaticMembershipNotSupported()
FAILED ❌ KafkaApisTest > "testKRaftControllerThrottleTimeEnforced(int, int).controllerThrottleTimeMs=0, requestThrottleTimeMs=1500"
FAILED ❌ KafkaApisTest > "testKRaftControllerThrottleTimeEnforced(int, int).controllerThrottleTimeMs=1500, requestThrottleTimeMs=0"
FAILED ❌ KafkaApisTest > "testKRaftControllerThrottleTimeEnforced(int, int).controllerThrottleTimeMs=3000, requestThrottleTimeMs=1000"
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeResponseContainsNewLeaderOnNotLeaderOrFollower()
FAILED ❌ KafkaApisTest > testRaftShouldNeverHandleAlterPartitionRequest()
FAILED ❌ KafkaApisTest > testShareGroupDescribeRequestAuthorizationFailed()
FAILED ❌ KafkaApisTest > testRaftShouldNeverHandleStopReplicaRequest()
FAILED ❌ KafkaApisTest > testListClientMetricsResourcesWithException()
FAILED ❌ KafkaApisTest > testWriteShareGroupStateSuccess()
FAILED ❌ KafkaApisTest > testShareGroupHeartbeatRequest()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeRequestAcknowledgeThrowsError()
FAILED ❌ KafkaApisTest > testPushTelemetry()
FAILED ❌ KafkaApisTest > testHandleShareFetchFromShareFetchRequestWithErroneousPartitions()
FAILED ❌ KafkaApisTest > testConsumerGroupDescribeFutureFailed()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestFetchThrowsException()
FAILED ❌ KafkaApisTest > testHandleFetchFromShareFetchRequestSuccess()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardUpdateFeatures()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestInvalidShareSessionError()
FAILED ❌ KafkaApisTest > testGetTelemetrySubscriptions()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardExpireTokenRequest()
FAILED ❌ KafkaApisTest > testRaftShouldNeverHandleEnvelope()
FAILED ❌ KafkaApisTest > testInvalidLegacyAlterConfigsRequestWithKRaft()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestFetchAndAcknowledgeThrowsException()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestReleaseAcquiredRecordsThrowError()
FAILED ❌ KafkaApisTest > testHandleShareFetchShareGroupDisabled()
FAILED ❌ KafkaApisTest > testShareGroupHeartbeatRequestFutureFailed()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeRequestSessionNotFound()
FAILED ❌ KafkaApisTest > testShareGroupDescribeReturnsUnsupportedVersion()
FAILED ❌ KafkaApisTest > testConsumerGroupHeartbeatReturnsUnsupportedVersion()
FAILED ❌ KafkaApisTest > testHandleShareFetchFromShareFetchRequestErrorTopicsInRequest()
FAILED ❌ KafkaApisTest > shouldThrowUnsupportedVersionExceptionOnHandleAddOffsetToTxnRequestWhenInterBrokerProtocolNotSupported()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestSuccessfulShareSessionLifecycle()
FAILED ❌ KafkaApisTest > testHandleShareFetchNewGroupCoordinatorDisabled()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeNewGroupCoordinatorDisabled()
FAILED ❌ KafkaApisTest > testShareGroupDescribeRequestAuthorizationFailedForOneGroup()
FAILED ❌ KafkaApisTest > testConsumerGroupDescribeReturnsUnsupportedVersion()
FAILED ❌ KafkaApisTest > testHandleShareFetchFetchMessagesReturnErrorCode()
FAILED ❌ KafkaApisTest > testPushTelemetryWithException()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardElectLeaders()
FAILED ❌ KafkaApisTest > testRaftShouldNeverHandleControlledShutdownRequest()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestSuccessWithAcknowledgements()
FAILED ❌ KafkaApisTest > rejectInitProducerIdWhenEpochButNotIdProvided()
FAILED ❌ KafkaApisTest > testHandleAcknowledgementsInvalidAcknowledgementBatches()
FAILED ❌ KafkaApisTest > testListClientMetricsResources()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardAlterUserScramCredentialsRequest()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestSuccessWithoutAcknowledgements()
FAILED ❌ KafkaApisTest > testReadShareGroupStateAuthorizationFailed()
FAILED ❌ KafkaApisTest > rejectJoinGroupRequestWhenStaticMembershipNotSupported()
FAILED ❌ KafkaApisTest > testConsumerGroupHeartbeatRequest()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardCreateTopicsRequest()
FAILED ❌ KafkaApisTest > testShareGroupDescribeSuccess()
FAILED ❌ KafkaApisTest > testGetAcknowledgeBatchesFromShareFetchRequest()
FAILED ❌ KafkaApisTest > testRaftShouldAlwaysForwardAlterPartitionReassignmentsRequest()
FAILED ❌ KafkaApisTest > shouldThrowUnsupportedVersionExceptionOnHandleEndTxnRequestWhenInterBrokerProtocolNotSupported()
FAILED ❌ KafkaApisTest > testHandleShareFetchRequestErrorInReadingPartition()
FAILED ❌ KafkaApisTest > rejectInitProducerIdWhenIdButNotEpochProvided()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeRequestBatchValidationError()
FAILED ❌ KafkaApisTest > rejectOffsetCommitRequestWhenStaticMembershipNotSupported()
FAILED ❌ KafkaApisTest > testHandleShareAcknowledgeRequestReleaseAcquiredRecordsThrowError()

**Comment by chia7712** [comment]
@m1a2st Due to the high number of conflicts, it might be best to close this PR for now. I've opened a new JIRA issue (https://issues.apache.org/jira/browse/KAFKA-18368) to track the final cleanup.

**Comment by m1a2st** [comment]
Thanks for @chia7712 , I will open another PR to do this.

**Pull request closed without merging**
