### PR TITLE
MINOR: log state store restore offsets

### PR DESCRIPTION
**Pull request by dguy**
Debug logging of the start and end offsets used during state store restoration

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang - backport of https://github.com/apache/kafka/pull/2718

**Comment by dguy** [comment]
Note: This also fixes the checkstyle failure in `ResetIntegrationTest`

**Comment by guozhangwang** [comment]
LGTM and merged to 0.10.2.

**Review by mjsax — APPROVED** [review]

**Comment by guozhangwang** [comment]
@dguy Could you manually close these PRs against 0.10.2? Thanks!

**Pull request closed without merging**
