### PR TITLE
KAFKA-10168: fix StreamsConfig parameter name variable

### PR DESCRIPTION
**Pull request by mjsax**
Rename `TOPOLOGY_OPTIMIZATION` to `TOPOLOGY_OPTIMIZATION_CONFIG`.

All variables in `StreamConfig` end with `_CONFIG`. We should align the variable name accordingly. This is technically a public API change. Happy to do a quick KIP for it, if we think we need one.

Cf. https://cwiki.apache.org/confluence/display/KAFKA/KIP-626%3A+Rename+StreamsConfig+config+variable+name

\cc @guozhangwang @vvcephei

### CODE REVIEW

**Review by abbccdda — COMMENTED** [review]
I'm inclined to get a small KIP for this. Besides, could we have some style check tool to enforce this norm for later configuration addition as well?

**Comment by vvcephei** [comment]
Looks like a compile warning:

```
00:07:57.788 > Task :streams:compileJava
00:07:57.788 /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk11-scala2.13/streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java:530: warning: [dep-ann] deprecated item is not annotated with @Deprecated
00:07:57.788     public static final String TOPOLOGY_OPTIMIZATION = "topology.optimization";
00:07:57.789                                ^
00:07:57.789 error: warnings found and -Werror specified
```

I'm +1 on this change, and I think it would be fine to just amend KIP-295.

**Comment by mjsax** [comment]
Not sure if changing KIP-295 would be a good call. We made a mistake and can be honest about it. I'll do a quick KIP.

**Comment by mjsax** [comment]
KIP was accepted.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
@vvcephei As you are +1, I am going to merge after Jenkins passed.

**Pull request merged**
