### PR TITLE
MINOR: Update zstd, easymock, powermock, zkclient and build plugins

### PR DESCRIPTION
**Pull request by ijuma**
EasyMock 4.0.x includes a change that relies on the caller for inferring
the return type of mock creator methods. Updated a number of Scala
tests for compilation and execution to succeed.

The versions of EasyMock and PowerMock in this PR include full support
for Java 11.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Looks like there's a problem:

https://github.com/powermock/powermock/pull/944

**Comment by ijuma** [comment]
@omkreddy Would you have time to review this PR?

**Comment by ijuma** [comment]
Hmm, seems like there are still some test failures. Let me look at those.

**Review by omkreddy — APPROVED** [review]
LGTM.  All tests are passing in local run.

**Comment by ijuma** [comment]
JDK 8 build passed, JDK 11 had unrelated failures. Merging to trunk.

**Comment by ijuma** [comment]
Cherry-picked to the 2.1 branch so that we can run spotbugs with Java 11, see https://github.com/apache/kafka/pull/5943#issuecomment-443228144

**Pull request merged**
