### PR TITLE
Re-enable KafkaAdminClientTest#testHandleTimeout

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Comment by apurvam** [comment]
Can you share the PR which has fixed the flakiness in the test?

**Comment by ijuma** [comment]
@cmccabe, can you please check if the fix for ensuring we never invoke `wait(0)` could have fixed this?

**Comment by ijuma** [comment]
@cmccabe friendly reminder. :)

**Comment by cmccabe** [comment]
> @cmccabe, can you please check if the fix for ensuring we never invoke wait(0) could have fixed this?

The wait(0) that was fixed by KAFKA-6026 was happening in `KafkaFutureImpl#get(long timeout, TimeUnit unit)`.  I believe that `KafkaAdminClientTest#testHandleTimeout` invokes only the no-argument variant, `KafkaFutureImpl#get()`.  So I don't believe that the patch for KAFKA-6026 fixes the problem seen in KAFKA-5792.

However, I think that the patch that was commited by #3822 (https://github.com/apache/kafka/pull/3822) should fix the issue.  Basically, the problem there was that we were not in fact using a `MockTime` object as planned, but actually using a `SystemTime` object instead.  This often worked, but was flaky.

**Comment by abbccdda** [comment]
Retest this please

**Comment by chia7712** [comment]
```KafkaAdminClientTest#testHandleTimeout``` was removed by https://github.com/apache/kafka/commit/4317325fbcb29d1f5ab828821b8e0714e10ed981 so we can close this PR now.

**Pull request closed without merging**
