### PR TITLE
HOTFIX: RecordCollector should send a record to the specified partition

### PR DESCRIPTION
**Pull request by ymatsuda**
@guozhangwang

### CODE REVIEW

**Comment by ymatsuda** [comment]
This is very important for sending state store change logs to correct partitions.

**Comment by ewencp** [comment]
@ymatsuda Is there a unit test we can fill in here? Agree this is critical, but seems like it should be validated with a test that checks if the record comes in with a `partition()` value?

**Comment by ymatsuda** [comment]
@ewencp 
Thanks. I added a test.

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
