### PR TITLE
2.2 WorkerSinkTask.convertMessages loss of offset

### PR DESCRIPTION
**Pull request by jiangchuan-java**
### original
 origOffsets.clear(); 
### update:
if (msgs.count() > 0)
    origOffsets.clear(); 
when sinkTask throw RetriableException, 
then step1: Pausing partitions. 
step2:Not returning fetched records for assigned partition since it is no longer fetchable. 
step3:convertMessages
step3.1:origOffsets.clear(); -> this line loss of offset
step4:Skipping offset commit, no change since last commit
step4.1:Finished offset commit successfully in 0 ms for sequence number.
so if no record returon from poll methdo, when execute convertMessages the origOffsets should be cleared when msgs is not empty
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kkonstantine** [comment]
@jiangchuan-java what's the purpose of this PR?

You'll need to keep only the relevant commits and target your PR against `trunk`

**Comment by jiangchuan-java** [comment]
When a record triggers a retry exception and the retry is processed successfully, its offset does not commit

**Comment by jiangchuan-java** [comment]
if (msgs.count() > 0)
      origOffsets.clear();
Solve the problem

**Comment by jiangchuan-java** [comment]
> @jiangchuan-java what's the purpose of this PR?
> 
> You'll need to keep only the relevant commits and target your PR against `trunk`

When a record triggers a retry exception and the retry is processed successfully, its offset does not commit.
if (msgs.count() > 0) {
      origOffsets.clear();
}
Solve the problem

**Comment by jiangchuan-java** [comment]
> @jiangchuan-java what's the purpose of this PR?
> 
> You'll need to keep only the relevant commits and target your PR against `trunk`

my kafka version : kafka_2.12-2.2.0

**Comment by jiangchuan-java** [comment]
> @jiangchuan-java what's the purpose of this PR?
> 
> You'll need to keep only the relevant commits and target your PR against `trunk`
log detail
RetriableException from SinkTask:
Pausing partitions
Not returning fetched records for assigned partition xxx since it is no longer fetchable
        offset_flush_interval has gone
Updating last seen epoch from 0 to 0 for partition
Skipping offset commit, no change since last commit( ths OrigOffsets has been clear)
Finished offset commit successfully in 0 ms for sequence number 384: null

**Comment by jiangchuan-java** [comment]
> @jiangchuan-java what's the purpose of this PR?
> 
> You'll need to keep only the relevant commits and target your PR against `trunk`

**Comment by kkonstantine** [comment]
If your intention is to report an issue, my recommendation would be to first open a jira ticket in: 
https://issues.apache.org/jira/projects/KAFKA/issues

Then, if you'd like to contribute a fix, you may open a PR on github with the ticket number in the title. Or a PR tagged with the prefix `MINOR:` if the fix is trivial.

**Pull request closed without merging**
