### PR TITLE
kafka-4684: Kafka does not offer kafka-configs.bat on Windows box

### PR DESCRIPTION
**Pull request by huxihx**
Add kafka-configs.bat script for Windows.

### CODE REVIEW

**Comment by huxihx** [comment]
@ijuma  a minor PR. Be free to take some time to review. Thanks.

**Comment by huxihx** [comment]
@vahidhashemian Please take some time to review this minor PR. Thanks.

**Comment by vahidhashemian** [comment]
LGTM. Thanks for the patch.

**Comment by huxihx** [comment]
@vahidhashemian  Thanks. so can we close this PR now?

**Comment by vahidhashemian** [comment]
It hasn't been merged yet. A committer needs to review and merge it. Then it can be closed.

**Comment by guozhangwang** [comment]
LGTM!

**Comment by guozhangwang** [comment]
Merged to trunk and 0.10.2.

**Pull request closed without merging**
