### PR TITLE
KAFKA-5608: Follow-up to fix potential NPE and clarify method name

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
System tests build: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/998/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6179/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6195/
Test PASSed (JDK 7 and Scala 2.11).

**Review by ewencp — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
Merged to trunk and 0.11.0.

**Pull request closed without merging**
