### PR TITLE
KAFKA-2974; `==` is used incorrectly in a few places in Java code

### PR DESCRIPTION
**Pull request by ijuma**
A few issues found via static analysis.

### CODE REVIEW

**Comment by ijuma** [comment]
This includes #183 by @eribeiro with the right attribution (so he will get the credit for this PR). @eribeiro, can you please close #183?

**Comment by gwenshap** [comment]
Thanks for fixing these issues.
The change LGTM but is a bit larger than what I feel comfortable without a JIRA (it includes added assertions to a test). Can you open a JIRA, describe the changes and link here?

**Comment by ijuma** [comment]
@gwenshap, I can file a JIRA sure. Note that the assertions are for verifying the MockClient change (it doesn't affect any prod code).

**Comment by guozhangwang** [comment]
LGTM as well. I am fine either with a JIRA or not, so its your call :)

**Comment by ijuma** [comment]
@guozhangwang @gwenshap Thanks both for reviewing. I filed the JIRA and updated the PR title.

**Comment by harshach** [comment]
+1. looks good.

**Comment by guozhangwang** [comment]
Merged to both branches.

**Pull request closed without merging**
