### PR TITLE
MINOR: Remove deprecated callers

### PR DESCRIPTION
**Pull request by guozhangwang**
1) Windows#until
2) Windows#of
3) Serialized

@mjsax @ijuma @vvcephei @bbejeck 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Nice. I assume we still have tests exercising the deprecated functionality?

**Review by mjsax — APPROVED** [review]

**Comment by guozhangwang** [comment]
> Nice. I assume we still have tests exercising the deprecated functionality?

Yup, for those I did not remove since they are actually testing the behavior to throw and fail, and hence should only be removed when we finally removed the APIs.

**Review by bbejeck — APPROVED** [review]
Thanks @guozhangwang LGTM

**Comment by bbejeck** [comment]
@guozhangwang although test failures are unrelated, looks like there is an issue with streams tests `KTableAggregateTest` uses `KStreamTestDriver` which is deprecated

**Comment by guozhangwang** [comment]
> @guozhangwang although test failures are unrelated, looks like there is an issue with streams tests `KTableAggregateTest` uses `KStreamTestDriver` which is deprecated

Thanks for pointing it out, I've addressed the unit tests. Multiple local runs succeed.

**Pull request merged**
