### PR TITLE
MINOR: fix rerun-tests for unit test

### PR DESCRIPTION
**Pull request by chia7712**
related to #11926. we don't process `rerun-tests` for unit test.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
The referenced https://github.com/apache/kafka/pull/11926 seems not relevant, is there a typo in the PR number?

**Comment by chia7712** [comment]
> The referenced https://github.com/apache/kafka/pull/11926 seems not relevant, is there a typo in the PR number?

#11926 added the new property to avoid recompiling the tests. see https://github.com/apache/kafka/commit/322a065b9055649c713baf43f154052d45cd1588#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R41

For another, it seems to me the existent task `cleanTest` can avoid recompilation also ( related to my previous comment https://github.com/apache/kafka/pull/11926#discussion_r1114653978), and thus there are two ways which can fix the command about "test without recompilation". 1) add `rerun-tests` for unit test. 2) replaces `rerun-tests` by `cleanTest`

**Comment by guozhangwang** [comment]
Ah thanks @chia7712 , my bad missing that change in the PR. As for the solution I do not have a preference in either side and I agree that both should not involve recompilation. Let's just follow-up with `rerun-tests` to avoid another change.

**Comment by ijuma** [comment]
Hmm, why is this needed? Can't we use https://docs.gradle.org/current/userguide/command_line_interface.html#sec:rerun_tasks

**Comment by chia7712** [comment]
> Hmm, why is this needed? Can't we use
> https://docs.gradle.org/current/userguide/command_line_interface.html#sec:rerun_tasks

the purpose of adding custom rerun-tests (#11926) is to avoid recompilation. the flag `--rerun-tasks` can't do that (I tried command `./gradlew core:test --tests MetricsDuringTopicCreationDeletionTest --no-daemon` and it invokes recompilation)

BTW, I prefer to use built-in task `cleanTest` to replace custom `rerun-tests` if all we want to do is to force re-running tests without recompilation when there is no code change.

**Comment by ijuma** [comment]
Gradle 7.6 introduced --rerun that is meant to solve that problem https://docs.gradle.org/7.6/release-notes.html#individual-rerun

**Comment by chia7712** [comment]
> Gradle 7.6 introduced --rerun that is meant to solve that problem

That is a good alternative too. will file PR for that.

**Pull request merged**
