### PR TITLE
MINOR: cherry pick KAFKA-13973 to 3.5

### PR DESCRIPTION
**Pull request by cadonna**
Cherry-pick of 

- https://github.com/apache/kafka/pull/14190
- https://github.com/apache/kafka/pull/14317

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Seems there is some issue on `3.5` branch?

```
[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:169:9: Invalid literal number

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:295:9: Invalid literal number

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:370:9: Invalid literal number

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:437:9: Invalid literal number

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:499:9: Invalid literal number

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:176:5: ')' expected but '}' found.

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:305:5: ')' expected but '}' found.

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:385:5: ')' expected but '}' found.

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:449:5: ')' expected but '}' found.

[Error] /home/jenkins/jenkins-agent/workspace/Kafka_kafka-pr_PR-14592/core/src/test/scala/integration/kafka/zk/ZkMigrationIntegrationTest.scala:525:5: ')' expected but '}' found.

10 errors found



> Task :core:compileTestScala FAILED
```

**Comment by cadonna** [comment]
This seems to be a scala issue. With scala 2.13 is compiles with 2.12 it does not.

**Comment by cadonna** [comment]
OK, I found the issue. On trunk, it was fixed by https://github.com/apache/kafka/pull/14126.

**Comment by cadonna** [comment]
I cherry picked the commits of the following PRs directly to 3.5:
- https://github.com/apache/kafka/pull/14126
- https://github.com/apache/kafka/pull/14190
- https://github.com/apache/kafka/pull/14317

Cherry-picking directly seemed cleaner to me.

**Comment by mjsax** [comment]
Thank you!

**Pull request closed without merging**
