### PR TITLE
KAFKA-9030: Document client-level (a.k.a. instance-level) metrics

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @guozhangwang @bbejeck @vvcephei 

This PR should also be cherry-picked to 2.4.

**Review by ableegoldman — APPROVED** [review]
The docs LGTM from what I can tell, but someone who reviewed the instance level metrics or has more context on KIP-444 should probably verify as well -- also, this can be done in another PR but I assume we need to mention these in the upgrade guide docs as well?

**Comment by mjsax** [comment]
Following https://cwiki.apache.org/confluence/display/KAFKA/KIP-444%3A+Augment+metrics+for+Kafka+Streams 5 new instance level metrics are added -- this PR LGTM.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.4`.

**Pull request merged**
