### PR TITLE
MINOR; Use LEADER_URL variable in tests

### PR DESCRIPTION
**Pull request by mdedetrich**
The variables must be used, otherwise the leaders will not be pleased.

### CODE REVIEW

**Comment by mdedetrich** [comment]
@C0urante

**Comment by C0urante** [comment]
@mdedetrich It's unclear from the description whether this a bug fix or a stylistic improvement; can you update it with that info?

**Comment by mdedetrich** [comment]
The description was a bad attempt at a funny joke, its just a stylistic improvement and not a bug fix. The `LEADER_URL` variable was defined but not being used.

**Comment by C0urante** [comment]
Thanks, that helps 👍

**Review by C0urante — APPROVED** [review]
LGTM

**Pull request merged**
