### PR TITLE
HOTFIX: fix a few typos on streams quickstart

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
ping @enothereska @dguy for reviews.

**Comment by guozhangwang** [comment]
This needs to go to both trunk and 0.11.0. I have already made the changes in `kafka-site` with exactly the same edits so does not need to re-package and push to `kafka-site`.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6005/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5990/
Test PASSed (JDK 8 and Scala 2.12).

**Review by enothereska — APPROVED** [review]
LGTM. Sorry I missed these.

**Review by dguy — APPROVED** [review]
Thanks @guozhangwang, LGTM

**Comment by dguy** [comment]
Merged to trunk and cherry-picked to 0.11.0

**Pull request closed without merging**
