### PR TITLE
KAFKA-7535:KafkaConsumer doesn't report records-lag if isolation.level is read_committed

### PR DESCRIPTION
**Pull request by lambdaliu**
FetchResponse should return the partitionData's lastStabeleOffset

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ijuma — COMMENTED** [review]
Thanks for the PR. Can you please add a test? cc @dhruvilshah3

**Comment by ijuma** [comment]
If you don't have time to write a test, let us know and we will help.

**Comment by lindong28** [comment]
@lambdaliu Thanks for the fix! Currently the patch still uses `FetchResponse.INVALID_LAST_STABLE_OFFSET` as `lastStableOffset` when there is need to convert data. Should we change this as well?

**Comment by lambdaliu** [comment]
@ijuma @lindong28  Thanks for your review. I added some tests to changed FetchResponse.INVALID_LAST_STABLE_OFFSET to lastStableOffset under date conversion, please review this PR again.

**Review by lindong28 — APPROVED** [review]
@lambdaliu Thanks for the update. LGTM.

**Comment by lindong28** [comment]
@dhruvilshah3 Would you like to review this PR?

**Review by dhruvilshah3 — APPROVED** [review]
Thanks, LGTM

**Comment by ijuma** [comment]
@lindong28 can we cherry-pick this to 2.0 as well? That's when the regression was introduced.

**Comment by lindong28** [comment]
Thanks for the patch. Merged to 2.0, 2.1 and trunk.

@ijuma The PR could not merge cleanly into 2.0. I was manually modifying the patch :)

**Comment by ijuma** [comment]
Perfect, thanks @lindong28 and @lambdaliu.

**Pull request closed without merging**
