### PR TITLE
KAFKA-6215: KafkaStreamsTest fails in trunk

### PR DESCRIPTION
**Pull request by mjsax**
- set streams state.dir to test-dir (default /tmp is not reliable)

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @dguy @bbejeck @guozhangwang

**Review by dguy — APPROVED** [review]
Thanks @mjsax, LGTM

**Comment by guozhangwang** [comment]
@mjsax could you update the title to point to the newly created ticket created by @tedyu ?

**Comment by tedyu** [comment]
@mjsax 
Thanks for the fix.

**Comment by mjsax** [comment]
@guozhangwang Done.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and 1.0

**Pull request closed without merging**
