### PR TITLE
KAFKA-3299: Ensure that reading config log on rebalance doesn't hang the herder

### PR DESCRIPTION
**Pull request by gwenshap**

### CODE REVIEW

**Comment by ewencp** [comment]
@gwenshap Do we want to kick off a system test job for this? I'm not super concerned since the timeout is generous, but might be nice to validate before committing.

**Comment by gwenshap** [comment]
You mean this? https://jenkins.confluent.io/job/kafka_systest_branch_builder2/35/

**Comment by ewencp** [comment]
@gwenshap Thinking about this more, I'm worried that with this change we don't make sure we read to the end of the log at least once before rejoining the group. On initial startup, the DistributedHerder makes sure we've read to the end of the log (we should probably discuss whether the way it does this synchronously with indefinite timeouts is also a problem). But in the failure case now, we may fail to read to log end, hit the timeout, leave the group, and then won't the subsequent tick immediately rejoin the group despite not having read to the end of the log? Seems like this will result in flapping membership in the group if the config topic can't be properly consumed.

So now this is making me think that the `readConfigToEnd` might not even be in the right place to handle this case. Maybe it should be another phase in `tick()` that comes first, controlled by a flag like the `needsReadToEnd` in `handleRebalanceCompleted` but is saved in the instances state so it continues to be attempted even if it continues to fail due to timeouts.

I'm also beginning to think it might be time to create a state diagram for this -- it seems to be pretty complicated...

**Comment by gwenshap** [comment]
Thanks for raising this concern - group flapping is indeed undesirable.

**Comment by ewencp** [comment]
LGTM

**Pull request closed without merging**
