### PR TITLE
MINOR: fix Bash shebang on vagrant/ scripts

### PR DESCRIPTION
**Pull request by shikhar**

### CODE REVIEW

**Comment by shikhar** [comment]
cc @granders

**Comment by granders** [comment]
LGTM

**Comment by ewencp** [comment]
LGTM

**Comment by aloiscochard** [comment]
Could we do the same on the scripts in `/bin` please?

There was two PR doing it which were refused apparently because folks are scared to change those files, I would love to use those scripts on NixOS without hacking them... and I'm not sure fear is a good reason to refuse those changes....

**Comment by shikhar** [comment]
Seems you are referring to #335 and #557 - neither was refused out of fear, just a security concern raised :) Let's try to bump...

[ BTW, the motivation for this patch was to fix the shebang not being the first line on the scripts, rather than switch to using `/usr/bin/env`, though that also crept in ]

**Pull request closed without merging**
