### PR TITLE
KAFKA-2587:Increasing timeout for the test verification.

### PR DESCRIPTION
**Pull request by Parth-Brahmbhatt**

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by ijuma** [comment]
@junrao can you please take a look? The test that was added as part of the simple authorization work has been a bit unstable and Parth increased the time out and improved the failure message to help us understand future failures better.

**Comment by harshach** [comment]
+1

**Comment by ijuma** [comment]
Thanks for merging @harshach and congratulations on your first merge to trunk. :)

**Pull request closed without merging**
