### PR TITLE
KAFKA-17227: Refactor compression code to only load codecs when used

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — APPROVED** [review]
LGTM!

**Review by jlprat — APPROVED** [review]
LGTM, thanks @mimaison

**Comment by jlprat** [comment]
Sorry, @mimaison you'll need to rebase as we both added a comment on top of the dependency for zstd-jni (different types of comments though)

**Comment by mimaison** [comment]
Thanks, I've just rebase my branch. Let's wait for the CI now.

**Comment by jlprat** [comment]
One small note about this change, the class `CompressionType` is not meant to be a public one, right? It's not i nthe Javadoc, but package-wise it might feel like it's public. A quick search on GH shows some usages of this class (that are not coming from forks of Kafka): https://github.com/search?q=org.apache.kafka.common.record.CompressionType&type=code

If it's public, we the changes made are source-compatible, but not binary-compatible. What this means is that if there is any library that needs this class, it would need to be recompiled in order to work with newer versions (as opposed to binary-compatible where no re-compilation is needed).

**Comment by mimaison** [comment]
`CompressionType` is not part of the public API, the whole `org.apache.kafka.common.record` package is not public.

**Comment by jlprat** [comment]
Then, all good :+1:

**Comment by jlprat** [comment]
All tests failures seem unrelated @mimaison

**Comment by mimaison** [comment]
I confirmed the zstd min and max levels have not changed and are still -131072/22 in 1.5.6-4. Merging to trunk

**Comment by jlprat** [comment]
@mimaison will you backport this to `3.8` and `3.9`?

**Comment by mimaison** [comment]
Yes that's the plan but I got sidetracked by a bunch of other things this afternoon. I'll do the backports tomorrow.

**Pull request merged**
