### PR TITLE
Backport KAFKA-5742 support ZK chroot in system tests

### PR DESCRIPTION
**Pull request by xvrl**
backport of KAFKA-5742 (#3677) to 0.11.0

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6858/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6844/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ewencp** [comment]
LGTM

**Comment by ewencp** [comment]
@xvrl This is merged, can you close the PR since asfbot only closes PRs against master?

**Pull request closed without merging**
