### PR TITLE
KAFKA-14492: Extract a method to create LogManager, in order to be overrided by subclass of KafkaServer

### PR DESCRIPTION
**Pull request by PhantomMaa**
[KAFKA-14492](https://issues.apache.org/jira/browse/KAFKA-14492)

In our scene, we want to implement a subclass of LogManager, add do some interception like encrypting/auditing.
Even more, we want enhance the write log performance in the future. 

Split alone a create method can provide an extension point to allow user define the action from outside kafka core.
Base kafka, entend it, rather than modification.

### CODE REVIEW

**Comment by PhantomMaa** [comment]
hi, those failed checks are not caused by my modification in this time.

what can i do next ?

**Comment by dajac** [comment]
Thanks for the PR. It is important to note that `KafkaServer` is not considered as a public interface in Kafka. Hence, there is not guarantee that the interface will remain like this in the future. It can basically change anytime. Therefore, I am personally not comfortable with this change. Have you considered alternative approaches? @ijuma What do you think?

**Comment by ijuma** [comment]
Yes, a KIP would be required to turn this into a public API. For non public APIs, the code can change at any time and we don't typically accept contributions designed to make it easier to extend (as that would set up the wrong expectations).

**Comment by PhantomMaa** [comment]
Thanks for your reply.

I agree that the `KafkaServer` is not designed for extend, attempt to replace the `LogManager` by override a `createLogManager`, maybe not a permanently method.

As your said, a KIP is needed to propose a complete approache that specially focus on which components can be extended in `KafkaServer`. Design an interface describe which components support extend is obviously a better way.

Before an api or interface be provided, allow to extend an object's method properly can be a temporary way with less drawback. At least is better than that fork a standalone repository then modify with the code. The extend way is just add a `kafka-core.jar`, then override inside classes.

Except the extend side, provide a `createLogManager` method is coincide with `createReplicaManager` below those code. It's also a good style only from the readability.


Further on, at this moment this modification is negligible, we will meet more problems to extend `LogManager` in the future. By then, i am willing to provide a comprehensive plan as a KIP to resolve the extension problem.

Thank you both again.

**Pull request closed without merging**
