### PR TITLE
KAFKA-3435: Remove `Unstable` annotation from new Java Consumer

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by granthenke** [comment]
cc @ijuma @gwenshap

**Comment by ijuma** [comment]
@gwenshap do you think we need to do anything else before removing the annotation?

**Comment by gwenshap** [comment]
Maybe decide what the annotation actually means and figure out some kind of consistent policy on when those are removed? I think we had a JIRA about that specifically.

We also have Kafka Connect and Kafka Streams coming up. Will be nice to figure anything out and not change things completely randomly. There are currently 3 semi-related places where we communicate the "maturity" of the APIs:
- Unstable annotation
- Beta in the docs
- Use in tooling (i.e. use of --new vs --old flag)
- Deprecation of older APIs.

Will be nice to get some consistency around when we do what :)

If either of you have time to do a draft guideline, we can re-evaluate the removal based on that?

**Comment by granthenke** [comment]
The jira for deciding the "meaning of the annotations" is [KAFKA-3433](https://issues.apache.org/jira/browse/KAFKA-3433) the guideline I was following is whats in code now. 
- Unstable: No guarantee is provided as to reliability or stability across any level of release granularity.
- Evolving: Evolving, but can break compatibility at minor release (i.e. m.x)
- Stable: Can evolve while retaining compatibility for minor release boundaries can break compatibility only at major release (ie. at m.0)

I am not sure Stable is needed since that the "default" case.

**Comment by gwenshap** [comment]
I was wondering about how do we decide it is stable now?

I mean, considering KIP-45, it is probably de-facto stable... but I was thinking we may want to have an answer for "when is a component considered stable".

**Comment by granthenke** [comment]
True, I am not sure how/when. I suppose it needs to be done on a case by case basis and whenever the community agrees we are going to follow the rules laid out. 

In this case are we no longer going to break the new consumer interface in a minor or maintenance release?

The other thing not concretely defined is what a major or minor or maintenance release are. I think we are following semantic versioning just with a leading 0 (i.e. 0.Major.Minor.Maintenance), that may not be clear to users less familiar with Kafka.

**Comment by gwenshap** [comment]
ok, sounds good.

I'll merge since this is defacto stable and we'll come up with guidelines later.

**Comment by ijuma** [comment]
Awesome.

**Pull request closed without merging**
