### PR TITLE
HOTFIX: Set session timeout and heartbeat interval to default to decrease flakiness

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @guozhangwang @ableegoldman

**Review by ableegoldman — APPROVED** [review]
Thanks @cadonna , nice find

**Review by abbccdda — COMMENTED** [review]
Instead of removing the set config value in the test, what about we just do the config change on demand so that we don't need to remove them in the first place?

**Comment by cadonna** [comment]
@abbccdda Looking at this test class again, I even think that we could set session timeout and heartbeat interval to default for all tests. The main motivation to reduce them was to not need to change the application ID for each test (see https://github.com/apache/kafka/pull/8530#discussion_r413170584). However, in the meanwhile each test has its own application ID, so I guess it would be fine to use again the defaults here. Is this correct @guozhangwang ?

**Comment by guozhangwang** [comment]
For correctness I agree; though for some tests we cover the rebalance triggered by member dropping out of the group and hence reducing the session timeout also largely reduces the overall run time of the test case, so I'd say for testing runtime we may still want to check case-by-case.

**Comment by cadonna** [comment]
I did some runs of the `RestoreIntegrationTest` and the runtime does not significantly change between runs with default values for session timeout and heartbeat interval and reduced values for session timeout and heartbeat interval. Hence, I set the two configs to their default values for the entire test.

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
LGTM. @abbccdda could help merging after green builds.

**Comment by cadonna** [comment]
Java 11 failed due to the following failing test:

```
kafka.api.ConsumerBounceTest.testClose
```

Java 8 failed due to the following failing tests:

```
org.apache.kafka.connect.mirror.MirrorConnectorsIntegrationTest.testReplication
org.apache.kafka.connect.mirror.MirrorConnectorsIntegrationTest.testOneWayReplicationWithAutorOffsetSync1
```

**Comment by cadonna** [comment]
@chia7712 Would you be so kind and trigger jenkins on this PR, please?

**Comment by chia7712** [comment]
retest this please

**Comment by cadonna** [comment]
Java 14 failed due to the following failing test:

```
org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest > shouldUpgradeFromEosAlphaToEosBeta[true]
```

**Comment by chia7712** [comment]
```EosBetaUpgradeIntegrationTest``` pass on my local. retest this please

**Review by abbccdda — APPROVED** [review]
LGTM

**Pull request merged**
