### PR TITLE
KAFKA-15816: Fix leaked sockets in trogdor tests

### PR DESCRIPTION
**Pull request by gharris1727**
The AgentTest leaks the agent under test due to typos. Close agents in AfterEach methods to avoid future typos.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by divijvaidya** [comment]
All tests in this test create an `Agent`. We should close them in `@afterTest` similar to https://github.com/apache/kafka/pull/15091 It's more robust as it enforces a clean close even with exceptions in the test

**Comment by gharris1727** [comment]
@divijvaidya Thanks for the review. I applied your suggestion. PTAL, thanks!

**Review by divijvaidya — APPROVED** [review]
Looks good!

**Comment by divijvaidya** [comment]
The test modified in this PR is successful - https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-14771/4/testReport/org.apache.kafka.trogdor.agent/

**Pull request merged**
