### PR TITLE
KAFKA-7502: Cleanup KTable materialization logic in a single place (doTransformValues)

### PR DESCRIPTION
**Pull request by dongjinleekr**
This PR is a follow-up of #6174 and #6453, which cleans up `KTableImpl#doTransformValues` method.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dongjinleekr** [comment]
cc/ @bbejeck @guozhangwang

**Comment by guozhangwang** [comment]
retest this please

**Comment by dongjinleekr** [comment]
retest this please

**Review by bbejeck — APPROVED** [review]
Thanks @dongjinleekr LGTM.

**Comment by bbejeck** [comment]
Merged #6519 into trunk.

**Pull request merged**
