### PR TITLE
KAFKA-5588: uselss --new-consumer option

### PR DESCRIPTION
**Pull request by ppatierno**
Get rid of the --new-consumer option for the ConsoleConsumer

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6055/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6040/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by ppatierno** [comment]
retest please

**Comment by ppatierno** [comment]
Retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6042/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6057/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ijuma** [comment]
This option exists for compatibility reasons. It needs to be deprecated before we can remove it in a new major version release.

**Comment by ppatierno** [comment]
@ijuma so what is the way ? Just updating the tool specifying that the --new-consumer is DEPRECATED in the help and then waiting for a next release to remove it ? Thanks.

**Comment by ijuma** [comment]
Right, we would need to:

1. Deprecate it in the help.
2. Output a warning to stderr if the option is used.
3. After one release cycle where the option is deprecated, it would be eligible for removal in major release after that.

**Comment by ppatierno** [comment]
@ijuma thanks ! So I'm going to close this PR and the related JIRA for now then Opening a new JIRA for marking the option as deprecated with related new PR.

**Comment by ijuma** [comment]
Since you created new PRs, can you close this one as intended?

**Comment by ppatierno** [comment]
@ijuma you are right ! Thanks ;)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6546/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6561/
Test PASSed (JDK 7 and Scala 2.11).

**Pull request closed without merging**
