### PR TITLE
subset of KAFKA-4353: Add uuid

### PR DESCRIPTION
**Pull request by rnpridgeon**
Alternatively I am open to using Avro's 'Fixed' type with a 16 byte size. However most requests I have  received wish to see UUID represented as type String so  I went with that to start. 

Also I just realized that Intellij's 'optimized imports' squashed the import list. Follow-up commit soon to follow with expanded import list

### CODE REVIEW

**Comment by ewencp** [comment]
These are new public APIs, so presumably would need a KIP. I'm all for it, but we might want to consider adding another "bundle" of new, commonly requested types (or maybe with a survey of where connectors are currently dropping semantic info since I don't think we've actually seen a ton of requests for new logical types on the mailing lists/JIRAs aside from this one JIRA).

**Comment by xiongtx** [comment]
Any update here?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6391/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6376/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by ewencp** [comment]
@rnpridgeon any interest in carrying this one through the finish line with some other JIRA ID than the (much more general) "semantic types" one? i.e. KIPing out the UUID logical type and rounding out this PR?

**Comment by rnpridgeon** [comment]
@ewencp , sorry got backed up at work and haven't had a chance to revisit. I'll close this out so someone else can carry on with this and/or revisit when I have more time.

**Pull request closed without merging**
