### PR TITLE
KAFKA-17180: Upgrade gradle from 8.8 to 8.10

### PR DESCRIPTION
**Pull request by FrankYang0529**
Gradle 8.10 is released, and it supports the JDK 23!

https://docs.gradle.org/8.10/release-notes.html

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — APPROVED** [review]
LGTM. wait for CI

**Comment by chia7712** [comment]
@FrankYang0529 Could you please check the fail build?

**Comment by FrankYang0529** [comment]
> @FrankYang0529 Could you please check the fail build?

Yes, I will take a look.

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
