### PR TITLE
[WIP] allow Processors to write to State Stores during Processor.init()

### PR DESCRIPTION
**Pull request by dguy**
If a Processor writes to a State Store in the init and 0 records are processed before `commit` is called an IllegalStateException is thrown. This is because the `RecordContext` has not been set on `ProcessorContext` and `RecordCollector` calls `context.timestamp()` when it is flushing the records to the changelog.
This sets a dummy `RecordContext` with the timestamp set to `System.currentTimeMillis` prior to Processor init.

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang there was a discussion about this today. if a `Processor` writes to a `StateStore` during `init` and 0 records are processed before `StreamTask.commit()` then we throw an IllegalStateException due to the `ProcessorContext` not having a `RecordContext` set.

I think we should handle this by initially setting the `RecordContext` to a dummy record with the current wall clock time as the timestamp. 

If you are happy with this, then i'll create a JIRA for it

**Comment by guozhangwang** [comment]
@dguy I think this is indeed an issue but setting the dummy timestamp to `system time` may not be the perfect solution, since remember that these timestamps will be the timestamp of the message used for log rolling / retention / etc.

So suppose you are processing data from 24 hours ago this changelog message will cause the log segment to be garbage collected immediately.

**Comment by guozhangwang** [comment]
A different option would be to modify the `restoration` process of the state store to allow users to have a warm state store before replaying the changelog, this is equivalent to writing some data that are not based on any incoming records when initializing the store. More specifically:
1. If the local state store exist, replay from checkpointed offset to tail.
2. If there is no state store, apply user's specified restoration logic so that the store is warm-constructed and reply from beginning offset to tail.

What do you think? @dguy @mjsax

**Comment by dguy** [comment]
@guozhangwang sounds like it would work, but.. how does the user add this bit of restoration logic? It would need to added somewhere via the TopologyBuilder, i.e., when adding the State Store. 
I think this is out-of-scope for 0.10.1 so i'll close this PR.

**Comment by guozhangwang** [comment]
Yeah I agree. How about this: let me ask the users who asked for this feature their concrete use case and see if that can be resolved in other ways first.

**Pull request closed without merging**
