### PR TITLE
MINOR: Add tests verifying leadership during and after reassignments in KRaft mode

### PR DESCRIPTION
**Pull request by andrewgrantcflt**
### Description
This adds a couple tests. 

First, it adds a test that makes sure we handle what happens when a reassignment completes and none of the new replicas can be made leader. Its important we dont keep an old replica as leader.

Second, it adds a test that makes sure we handle new reassignments that dont include a previous assignment replica that was leader. In the test here (in `testReassignPartitionsKeepsAllPreviousReassigningReplicas`) that replica is broker 2. We first reassign the partition from [0, 1] to [2, 3]. Then elect 2 leader after its joined the ISR. 3 does not join the ISR so the reassignment is not complete. Then we reassign the partition again to [3, 4]. The important part is we arent stuck with 2 being leader and it being removed from the replicas list. In KRaft we dont remove it from the replicas list so its OK it stays as leader. Finally when 3, 4 get added to the ISR it will be demoted and removed from the replicas list.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cmccabe** [comment]
Thanks for tackling this!

Question about the first test:

> First, it adds a test that makes sure we handle what happens when a reassignment completes and none of the new replicas can be made leader. Its important we dont keep an old replica as leader.

The reassignment won't complete until the new nodes are in the ISR, right? So I'm curious how this could happen in practice. I must be missing something...

Second test looks 👍

**Comment by andrewgrantcflt** [comment]
> Thanks for tackling this!
> 
> Question about the first test:
> 
> > First, it adds a test that makes sure we handle what happens when a reassignment completes and none of the new replicas can be made leader. Its important we dont keep an old replica as leader.
> 
> The reassignment won't complete until the new nodes are in the ISR, right? So I'm curious how this could happen in practice. I must be missing something...
> 
> Second test looks 👍


Thanks for the review @cmccabe.

"The reassignment won't complete until the new nodes are in the ISR, right? So I'm curious how this could happen in practice. I must be missing something..." So in practice this might be true, currently, due to the `IntPredicate` we supply as input to `PartitionChangeBuilder`. I'm guessing in practice its true if a replica has just been added to the ISR then `isAcceptableLeader` will return true. However, that doesnt seem to be a definitive contract from `PartitionChangeBuilder`'s perspective so it seems for the coding implementation we should not assume `isAcceptableLeader` will always return true for newly added to the ISR replicas. Due to that the test seems valid. What do you think?

**Comment by cmccabe** [comment]
Sure. The test is valid since it's testing the `PartitionChangeBuilder` and we do want it to have the behavior you're describing. Thanks for the explanation.

LGTM

**Review by cmccabe — APPROVED** [review]
LGTM

**Pull request merged**
