### PR TITLE
MINOR: Upgraded RocksDB to 5.3.6

### PR DESCRIPTION
**Pull request by enothereska**
Solves a problem as described here: https://groups.google.com/forum/#!topic/confluent-platform/cR02K2o6BIw

### CODE REVIEW

**Comment by enothereska** [comment]
cc @dguy @guozhangwang. Note that newer versions are out in May, but it might be worth not rushing for the latest one and waiting for a month or two.

**Comment by ijuma** [comment]
Why not 5.4.5? http://central.maven.org/maven2/org/rocksdb/rocksdbjni/

**Comment by enothereska** [comment]
@ijuma see my comment about not immediately picking latest release to be a bit conservative. I'm open to being more liberal though :)

**Comment by ijuma** [comment]
Race condition in our comments. ;) With RocksDB is a bit tricky. Older releases are not necessarily more stable. We could ask the RocksDB people what they recommend. Otherwise, the best option is probably to go for latest since it's early in our release cycle.

**Comment by guozhangwang** [comment]
I'd recommend trust the rocksDB community using the latest stable version, as I agree with @ijuma that for OS projects it is usually better to use newer version.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5856/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by enothereska** [comment]
Hmm, all streams tests with RocksDB failed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5844/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by enothereska** [comment]
Upgraded to 5.3.6, one short of latest since 5.4.5 gave me a strange error on one test and I'm following up with RocksDb. Meanwhile this one should be a good stepping stone from the current 5.0.1. cc @dguy @guozhangwang

**Comment by dguy** [comment]
Thanks @enothereska - can you update the PR title?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5879/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5864/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
Regarding the failure: maybe this can help https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

If we can still fix it soon I'd suggest let's upgrade to 5.4.5 in one PR?

**Comment by enothereska** [comment]
@guozhangwang there seems to be a new RocksDB release every month. I don't know why we can't move ahead with this and then pick up the next one as we go. It's not the unsupported major-minor version problem, it's a reference check inside the RocksDB's deallocator that's giving the current problem: https://github.com/facebook/rocksdb/issues/2533 cc @dguy

**Comment by guozhangwang** [comment]
If rocksdb#2533 is indeed an overlook by the rocksDB community which means we cannot work with 5.4.5 anyways, then I'm good with 5.3.6; let's wait for a bit more on that ticket.

**Comment by ijuma** [comment]
IMO, we can go ahead with 5.3.6 and update again if there is a resolution for https://github.com/facebook/rocksdb/issues/2533.

**Comment by guozhangwang** [comment]
I have not heard back from the rocksDB community; if they do not reply by eow let's assume 5.4.5 has a defect that cannot be used and upgrade to 5.3.6 for now.

**Comment by guozhangwang** [comment]
@enothereska I retested 5.4.5 on jenkins but did not see the issues you mentioned (triggered twice but did not see once): https://github.com/apache/kafka/pull/3509 Is it consistently producible?

**Comment by enothereska** [comment]
I get the problem locally on my laptop, not Jenkins.

**Review by dguy — APPROVED** [review]
LGTM

**Comment by dguy** [comment]
Merged to trunk

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6033/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6018/
Test PASSed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
