### PR TITLE
KAFKA-17177: reviewers.py should grep "authors" to offer more candidates of reviewers information

### PR DESCRIPTION
**Pull request by chiacyu**
As title, this pull request add grep author to get more information.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@chiacyu Do you test it on your local? The following error happens on my local

```
/home/chia7712/project/kafka/./reviewers.py:41: SyntaxWarning: invalid escape sequence '\|'
  stream = os.popen("git log | grep 'Reviewers\|Author'")
/home/chia7712/project/kafka/./reviewers.py:52: SyntaxWarning: invalid escape sequence '\s'
  m = re.match("(?P<name>.*)\s<(?P<email>.*)>", item[0])
Utility to help generate 'Reviewers' string for Pull Requests. Use Ctrl+D or Ctrl+C to exit
```

**Comment by chiacyu** [comment]
Let me check that, thanks for the reminder and also could you please share what you typed into the prompt to cause it @chia7712 ? 
```
chiacyu@server:~/Desktop/kafka$ uname -a
Linux server 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
chiacyu@server:~/Desktop/kafka$ python3 reviewers.py 
Utility to help generate 'Reviewers' string for Pull Requests. Use Ctrl+D or Ctrl+C to exit
```

**Comment by chia7712** [comment]
> Let me check that, thanks for the reminder and also could you please share what you typed into the prompt to cause it 

`./reviewers.py`

BTW, it seems to me the simple fix is to add `r` to make raw string instead

**Comment by chia7712** [comment]
@chiacyu could you please fix line#53 also?

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
