### PR TITLE
MINOR Removed unused CommittedOffsetsFile class.

### PR DESCRIPTION
**Pull request by satishd**
We will introduce the same when it is required for enhancing TBRLMM to consume from a specific offset when snapshots are implemented.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kamalcph** [comment]
Should we also avoid creating the [remote_log_snapshot](https://sourcegraph.com/github.com/apache/kafka@e563aad4eec2e08c8db54e1afebe28c746130ba4/-/blob/storage/src/main/java/org/apache/kafka/server/log/remote/metadata/storage/RemoteLogMetadataSnapshotFile.java?L75) file under each partition directory?

**Comment by satishd** [comment]
>Should we also avoid creating the [remote_log_snapshot](https://sourcegraph.com/github.com/apache/kafka@e563aad4eec2e08c8db54e1afebe28c746130ba4/-/blob/storage/src/main/java/org/apache/kafka/server/log/remote/metadata/storage/RemoteLogMetadataSnapshotFile.java?L75) file under each partition directory?

@kamalcph Wanted this PR only to remove the unused file. Filed [KAFKA-16161](https://issues.apache.org/jira/browse/KAFKA-16161), please take this in a separate PR.

**Review by kamalcph — APPROVED** [review]
LGTM

**Comment by kamalcph** [comment]
> Task :core:compileTestScala FAILED

Please fix the test compilation failure

**Review by divijvaidya — APPROVED** [review]

**Pull request merged**
