### PR TITLE
MINOR: Default test name added to tools

### PR DESCRIPTION
**Pull request by nizhikov**
This PR adds `junit-platform.properties` to `tools` and removes outdated constant from java code.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@nizhikov thanks for this patch. let's wait for #15664

**Comment by nizhikov** [comment]
@chia7712 Can you, please, double check PR number? It sees #15664 not related to my changes

**Comment by chia7712** [comment]
sorry :( 

the correct PR is #15663

**Comment by chia7712** [comment]
@nizhikov Could you please rebase code to see the display name of tools test?

**Comment by nizhikov** [comment]
Trunk test names:

Снимок экрана 2024-04-06 в 14 12 12

PR test names:

Снимок экрана 2024-04-06 в 14 11 04

**Comment by nizhikov** [comment]
@chia7712 latest trunk merged. Please, take a look

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request merged**
