### PR TITLE
HOTFIX: KAFKA-4060 and KAFKA-4476 follow up

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by guozhangwang** [comment]
Could you add a unit test for this?

**Comment by mjsax** [comment]
@guozhangwang Done.
I also split the existing test into two (to support @dguy's efforts to make our tests better)

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
LGTM and merged to trunk and 0.10.2.

**Pull request closed without merging**
