### PR TITLE
KAFKA-10083: fix failed testReassignmentWithRandomSubscriptionsAndChanges tests

### PR DESCRIPTION
**Pull request by ableegoldman**
Minimum fix needed to stop this test failing and unblock others

### CODE REVIEW

**Comment by showuon** [comment]
LGTM. Thanks @ableegoldman

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
LGTM. Will wait for jenkins to pass.

**Comment by ableegoldman** [comment]
> Will wait for jenkins to pass.

At least we learned from all this 😄

**Comment by ableegoldman** [comment]
Java14. passed
Java 11 failed with unrelated `PlaintextProducerSendTest.testNonBlockingProducer`
Java 8 failed with four unrelated:
`CustomQuotaCallbackTest.testCustomQuotaCallback`
`PlaintextConsumerTest.testLowMaxFetchSizeForRequestAndPartition`
`KTableKTableForeignKeyInnerJoinMultiIntegrationTest.shouldInnerJoinMultiPartitionQueryable`
`OptimizedKTableIntegrationTest.shouldApplyUpdatesToStandbyStore`

**Comment by guozhangwang** [comment]
Cherry-picked back to 2.4

**Pull request merged**
