### PR TITLE
Minor remove semicolon

### PR DESCRIPTION
**Pull request by khaireddine120**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
Ok to test

**Comment by bbejeck** [comment]
Tests seem to be hung, retesting

retest this please

**Review by abbccdda — APPROVED** [review]

**Comment by khaireddine120** [comment]
Hi @bbejeck 
Thanks for the approval
Why the check is taking so long ?

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
@khaireddine120 can you rebase this PR against trunk? Then after the build we can get this merged.

**Comment by bbejeck** [comment]
Minor cleanup, I ran the tests locally and all passed, merging this now.

**Comment by bbejeck** [comment]
Thanks for the cleanup @khaireddine120!

**Comment by khaireddine120** [comment]
welcome, i will try to participate more in the future ;)

**Pull request merged**
