### PR TITLE
MINOR: Upgrade ducktape to 0.7.8

### PR DESCRIPTION
**Pull request by andrewegel**
Newer version of ducktape that updates some dependencies and adds some features. You can see that diff here:

https://github.com/confluentinc/ducktape/compare/v0.7.7...v0.7.8

I would like this back ported as far back as 1.0

### CODE REVIEW

**Review by kkonstantine — COMMENTED** [review]
Thanks @andrewegel 
Happy to backport. 
Did you run any rounds of system tests with the new versions at different release branches?

**Comment by andrewegel** [comment]
>  Did you run any rounds of system tests with the new versions at different release branches?

I'll see what I can do.

**Comment by andrewegel** [comment]
I'm told its OK to post this job link here: 

https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3968/parameters/

Tests are failing, but the ducktape framework still functions.

**Review by kkonstantine — APPROVED** [review]
Thanks @andrewegel 
Sounds good. I'll merge later today, after a PR build too. 

This LGTM

**Comment by kkonstantine** [comment]
ok to test

**Comment by kkonstantine** [comment]
Merged to `trunk` and backported all the way back to `1.0`

**Pull request merged**
