### PR TITLE
KAFKA-17530: Remove blacklist/whitelist from ReplaceField

### PR DESCRIPTION
**Pull request by TaiJuWu**
jira: https://issues.apache.org/jira/browse/KAFKA-17530

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@TaiJuWu could you please update `upgrade.html`?

**Comment by TaiJuWu** [comment]
> @TaiJuWu could you please update `upgrade.html`?

Done.

**Comment by chia7712** [comment]
@TaiJuWu Could you please fix conflicts?

**Comment by TaiJuWu** [comment]
> @TaiJuWu Could you please fix conflicts?

Done. Thanks for review.

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
