### PR TITLE
KAFKA-3784 TimeWindows#windowsFor misidentifies some windows if TimeWindows#advanceBy is used

### PR DESCRIPTION
**Pull request by trybak**
- Fixed the logic calculating the windows that are affected by a new …event in the case of hopping windows and a small overlap.
- Added a unit test that tests for the issue

### CODE REVIEW

**Comment by miguno** [comment]
FYI: Seems like there's a vim swap file in your PR (streams/src/main/java/org/apache/kafka/streams/kstream/.TimeWindows.java.swp).

**Comment by mjsax** [comment]
Good catch. However, I believe this can be simplified (avoiding the additional `if` in the loop). The problem seem to be, that the `startWindow` value is not computed correctly. I think, it should be `windowStart = (Math.max(0, timestamp - this.size + this.advance) / this.advance) * this.advance;`.

Does this make sense?

**Comment by trybak** [comment]
I have updated the pull request with the suggested changes.

@mjsax thanks for the calculation

**Comment by guozhangwang** [comment]
LGTM, merged to trunk and 0.10.0.

**Pull request closed without merging**
