### PR TITLE
MINOR: Consistent terminal period in Errors.defaultExceptionMessage

### PR DESCRIPTION
**Pull request by tombentley**
Some default messages ended with a period and some didn't, so make things consistent.

The contribution is my original work and I license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by tombentley** [comment]
@mimaison any chance you could reivew this one? It's trivial.

**Review by mimaison — APPROVED** [review]
Thanks, LGTM

**Comment by hachikuji** [comment]
@mimaison This caused a failure in `PlaintextAdminIntegrationTest.testElectPreferredLeaders`. We probably should run the build even if the patch seems trivial.

**Comment by mimaison** [comment]
@hachikuji My bad. I'll make sure I always run tests.

**Comment by tombentley** [comment]
@hachikuji also my bad, sorry. According to https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes "The Jenkins automatic pull request builder will run unit and integration tests on your branch", I guess that's no longer true, and if I want to run the tests on Jenkins I need to request it specifically, right?

**Pull request merged**
