### PR TITLE
KAFKA-7237: Add explicit FATAL marker to log messages

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
https://issues.apache.org/jira/browse/KAFKA-7237

### CODE REVIEW

**Comment by stanislavkozlovski** [comment]
cc @rajinisivaram @ijuma 
Do you believe this is sufficient or might there be more logs I'm missing?

**Comment by ijuma** [comment]
Not sure how useful fatal is. Maybe we should just drop that altogether. Whenever people look at the logs, they grep for ERROR so having an even more severe level maybe doesn't help much.

**Comment by ijuma** [comment]
As I said before, I think we should just remove the `fatal` methods altogether.

**Comment by stanislavkozlovski** [comment]
I agree. Now that I have more experience with Kafka I see that `ERROR` messages are rare enough to not justify a `FATAL` level

**Comment by ijuma** [comment]
Can you please fix the conflict?

**Comment by stanislavkozlovski** [comment]
Rebased 👍

**Comment by stanislavkozlovski** [comment]
retest this please

**Comment by stanislavkozlovski** [comment]
@ijuma are we good with this change if the tests pass?

**Comment by ijuma** [comment]
retest this please

**Comment by stanislavkozlovski** [comment]
retest this please

**Comment by stanislavkozlovski** [comment]
retest this please

**Pull request closed without merging**
