### PR TITLE
[MINOR] KAFKA-16741:Adding record keys for share group (KIP-932)

### PR DESCRIPTION
**Pull request by apoorvmittal10**
Adding record keys for share groups.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by AndrewJSchofield** [comment]
@apoorvmittal10 We will have to coordinate with https://github.com/apache/kafka/pull/16786.

**Comment by apoorvmittal10** [comment]
> @apoorvmittal10 We will have to coordinate with #16786.

Agree, should I include others in this PR once PR #16786 is merged or we merge this one and include other RPCs in #16786?

**Comment by AndrewJSchofield** [comment]
> > @apoorvmittal10 We will have to coordinate with #16786.
> 
> Agree, should I include others in this PR once PR #16786 is merged or we merge this one and include other RPCs in #16786?

Well, since the other PR introduces another 5 new record types, I've made the equivalent change to my PR. The lines you've added here are exactly the same as I have in my PR.

**Review by AndrewJSchofield — APPROVED** [review]

**Comment by apoorvmittal10** [comment]
Yeah then let's get it merged with your changes. I am closing the PR.

**Pull request closed without merging**
