### PR TITLE
MINOR: Make PushHttpMetricsReporter use daemon threads.

### PR DESCRIPTION
**Pull request by ewencp**
This is a safe guard against users that do not properly close() the reporter, which causes
the process to hang even if its main() method returns. This was the case with Kafka Streams
apps in some cases in Kafka < 1.1.0 (KAFKA-6383). Without this fix, this behavior can make
it difficult to use this class in some types of system tests.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ewencp** [comment]
This is currently targeted at trunk. Technically, this tool was merged back to 0.11.0 but the fix for Streams is in 1.1.0, so we could get away only putting this onto 0.11.0 and 1.0.

I'm open to either way. On the one hand, this issue was surfaced well above the source of the issue in terms of what was supposed to be under test. On the other hand, while I found the bug already fixed, it would have caught an issue that I'm not sure is actually fully tested in Streams today -- I know the fix for the bug got unit tests but I'm not sure integration/system tests would catch this unless they are doing something similar that would catch some resources not being closed(). Streams committers want to review and weigh in @guozhangwang @mjsax?

**Comment by guozhangwang** [comment]
Thanks @ewencp . I'd prefer to just merge this fix to 0.11 and 1.0 if we still prefer to have PushHttpMetricsReporter not using daemon.

**Comment by ewencp** [comment]
@guozhangwang To explain the reasoning a bit more, I spent a bunch of time tracking a C3 system test failure back to this issue, and had to dig through streams code to understand why it wasn't closing the metrics reporters (the naming of the threads is intended to help with tracking this in the future, I had to connect it back to the source of the problem with heap dumps walking back to the GC root).

The question then is if we want to just disallow this type of error caused by this particular reporter since it was hard to track down indirectly. Another option would be to test streams shutdown more thoroughly and directly to validate that all the components (producers, consumers) are properly shutdown (possibly handling all the pluggable components like metrics reporters). If unit tests can't cover this, maybe a relatively lightweight integration test would cover it effectively.

**Comment by guozhangwang** [comment]
Got it. Currently Streams unit tests does not override metrics reporters in any cases so we always use the JMXReporter, and I think that's why we did not expose it in time.

I think adding a unit test with this reporter should cover this scenario?

**Comment by ijuma** [comment]
The thread name change sounds good. I wonder if we should add a generic system tests check that verifies if there are any dangling threads.

**Comment by ewencp** [comment]
@guozhangwang Yeah, that would work. It's not really specific to metrics reporters, it's just a matter of whether everything was properly closed. So I think the other way to test it would be if you could swap out the implementation of KafkaClientSupplier in an integration test (in the sense of testing multiple classes together, not necessarily a full integration test with other services as we call them) with one that just uses mock clients that check if they are properly closed. While the metrics reporter revealed the problem, it's more a matter of counting the instantiated clients and whether they all get closed under all scenarios (and this one is admittedly an uncommon one probably).

@ijuma Yeah, we could try something like that. Not sure if we could write one generally though. Metrics reporters do seem to commonly need to allocate an additional thread to periodically report stats -- I've seen at least a couple of implementations like this. Maybe just a test against this reporter would work. Tricky part is that you need a bunch of them for different ways the app might start and then cleanup.

**Comment by ewencp** [comment]
Ok, I've rebased to 1.0 and will restrict to just 0.11.0 and 1.0 for now. Will wait for Jenkins builds to come back and then merge. We can decide on follow up actions to avoid regressions independently.

**Pull request closed without merging**
