### PR TITLE
KAFKA-6238: Fix 1.0.0 upgrade instructions relating to the message format version

### PR DESCRIPTION
**Pull request by hachikuji**
The upgrade instructions concerning the message format versions did not account for upgrades from versions prior to 0.11.0.x.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by omkreddy** [comment]
@ijuma when are we going to push the changes to kafka-site?

**Comment by hachikuji** [comment]
@omkreddy I'll push to site today.

**Comment by ijuma** [comment]
@hachikuji Thanks for pushing the changes to the website!

**Pull request closed without merging**
