### PR TITLE
KAFKA-2402: Create IsrChangeNotificationPath when server statrs.

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by ijuma** [comment]
The change looks good although I wonder if there's anything we can do to make it less likely for similar problems to occur in the future. An automated test would be ideal, but if that is hard then a potential alternative would be to move the `Seq` of common paths in `setupCommonPaths` to a `val` near the other constants along with a comment explaining under what circumstances new paths should be added there.

**Comment by SinghAsDev** [comment]
LGTM! However, an unit test or integration test will be helpful.

**Comment by becketqin** [comment]
@ijuma @samshah , unit test might be a little bit hard to do here simply because the issue will only occur during version upgrade. We need a rolling upgrade test as proposed in KAFKA-1888. This is probably a non-trivial work and maybe out of the scope of this simple fix?

**Comment by ijuma** [comment]
@becketqin, fair enough. Do you think it's worth moving the `Seq` to be near the constants along with a comment as I suggested? In any case, this is an improvement, so LGTM if you don't think it's worth it.

Note that this branch doesn't merge cleanly anymore so that needs to be fixed before it can merged.

**Comment by ijuma** [comment]
@becketqin, I think this change was included as part of https://github.com/apache/kafka/commit/2c55bd8aa2666ea11ee2814b04f782eef8fa52c6#diff-f4fe18d654e20048317014cfe9d53968R61 right? If so, can you please close this PR?

And thanks for making the change I suggested.

**Comment by becketqin** [comment]
@ijuma Yes, this patch was put in KAFKA-2406 already. I'll close it.

**Pull request closed without merging**
