### PR TITLE
KAFKA-7001: Rename errors.allowed.max property in Connect to errors.tolerance (KIP-298)

### PR DESCRIPTION
**Pull request by wicknicks**
Signed-off-by: Arjun Satish <arjun@confluent.io>

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wicknicks** [comment]
@mageshn @rayokota @rhauch any comments on this PR?

**Review by rhauch — APPROVED** [review]
LGTM.

**Comment by wicknicks** [comment]
@ewencp could you please take a look at this? Thanks!

**Review by ewencp — APPROVED** [review]
LGTM, merging to trunk + 2.0

**Pull request closed without merging**
