### PR TITLE
KAFKA-16559 allow defining number of disks per broker in TestKitNodes

### PR DESCRIPTION
**Pull request by gaurav-narula**
Cherry-picks #15730 to 3.7 branch.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gaurav-narula** [comment]
CC: @soarez @chia7712

**Review by soarez — COMMENTED** [review]
LGTM changes are identical to #15730

**Comment by soarez** [comment]
There is a large number of failed tests, but none of them are new

**Review by chia7712 — APPROVED** [review]
LGTM.

**Comment by chia7712** [comment]
@soarez Any concerns? The failed streams tests can get fixed by backporting #14983. Hence, I'd like to merge it :)

**Review by soarez — APPROVED** [review]
LGTM please merge @chia7712

**Pull request merged**
