### PR TITLE
MINOR: Fix javadoc warning in StreamsMetric

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @mjsax

**Comment by bbejeck** [comment]
ok to test

**Comment by bbejeck** [comment]
@cadonna the failure is from checkstyle, unused import

**Comment by bbejeck** [comment]
retest this please

**Comment by bbejeck** [comment]
ok to test

**Review by bbejeck — APPROVED** [review]
Thanks for the fix @cadonna LGTM.

**Review by mjsax — APPROVED** [review]

**Comment by bbejeck** [comment]
Java 8 passed, Java 11 failed.

This PR contains only Javadoc changes so merging now.

**Pull request merged**
