### PR TITLE
KAFKA-14879: Update system tests to use latest versions

### PR DESCRIPTION
**Pull request by kirktrue**
Update the system tests to default to running the latest versions:

- 2.6.3
- 2.7.2
- 3.3.2

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jolshan** [comment]
Did you mean to make this a draft or is it ready for review @kirktrue ?

**Comment by kirktrue** [comment]
It's meant to be a draft for now. I first want to run through the system tests on a build server to make sure they behave.

**Comment by kirktrue** [comment]
Test failures are Kraft-related and do not appear to be caused by this change.

**Comment by kirktrue** [comment]
@jolshan Can you take a look at this when you have some time? Thanks

**Comment by kirktrue** [comment]
This appears to be taken up by someone else, but they're doing it in a more automated/dynamic manner, which is better anyway.

**Comment by jolshan** [comment]
Sorry I must have missed this ping. :( My bad.

**Comment by kirktrue** [comment]
> Sorry I must have missed this ping. :( My bad.

No worries at all 👍

**Pull request closed without merging**
