### PR TITLE
KAFKA-14587: Move AclCommand to tools [WIP]

### PR DESCRIPTION
**Pull request by OmniaGM**
**Note: PR still WIP**

**Blocked** on [KAFKA-14527](https://issues.apache.org/jira/browse/KAFKA-14527). 

**TODO:**
- Move all `TestUtils` dependencies to `ToolsTestUtils` if possible 
- Check if we can move the dependencies from `kafka.server` outside the core 

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by fvaleri** [comment]
This is one of the tools that require multiple PRs, starting from core's dependencies migrations.

**Comment by OmniaGM** [comment]
> This is one of the tools that require multiple PRs, starting from core's dependencies migrations.

Will break the core's dependencies migrations into jiras and move them first then come back to this one

**Comment by chia7712** [comment]
@OmniaGM Could you rebase this PR?

The usage of `kafka.security.authorizer` is to get class name of `AclAuthorizer`[0]. It seems we can replace that by constant string. Also, the dependency of `kafka.server` is gone. Hence, it is time to resume this PR :)

[0] https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/admin/AclCommand.scala#L66

**Comment by mimaison** [comment]
Done in https://github.com/apache/kafka/pull/17880, closing

**Pull request closed without merging**
