### PR TITLE
KAFKA-3439: Added exceptions thrown

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
@guozhangwang have a look when you can. Thanks.

**Comment by guozhangwang** [comment]
Looks good overall.

Could we add explanations for those general exceptions for "when such exceptions can be thrown" like KafkaExceptions / StreamsExceptions / IllegalStateExceptions as the exception names themselves do not reveal too much hints. As an example in KafkaConsumer we tried to add as much information on that regards as possible to help developers.

**Comment by enothereska** [comment]
Thanks @guozhangwang

**Comment by gwenshap** [comment]
LGTM

**Pull request closed without merging**
