### PR TITLE
MINOR: Add public documentation for metrics introduced in KIP-963

### PR DESCRIPTION
**Pull request by clolov**
Adding the public documentation for metrics introduced in [KIP-963](https://cwiki.apache.org/confluence/display/KAFKA/KIP-963%3A+Additional+metrics+in+Tiered+Storage)

### CODE REVIEW

**Review by showuon — COMMENTED** [review]
Thanks for adding the doc. I totally forgot about it. We should also add a entry in 3.7.0 notable changes in docs/upgrade.html.

**Review by showuon — COMMENTED** [review]
Also, this change should be targeting to trunk branch. The committer will help backport to 3.7 branch.

**Comment by clolov** [comment]
Heya @showuon and thanks for the review! I will make the changes in a couple of hours

**Comment by showuon** [comment]
I found the bug that we didn't update the all topic metric value: [KAFKA-16085](https://issues.apache.org/jira/browse/KAFKA-16085) and the drafted solution: https://github.com/apache/kafka/pull/15133 . Please take a look when available. Thanks.

**Comment by clolov** [comment]
Closing this PR and moving it to https://github.com/apache/kafka/pull/15138

**Pull request closed without merging**
