### PR TITLE
MINOR: Serialize the real isolationLevel in FetchRequest

### PR DESCRIPTION
**Pull request by apurvam**

### CODE REVIEW

**Comment by apurvam** [comment]
cc @hachikuji

**Comment by ijuma** [comment]
Can we add a simple unit test for this please?

**Comment by apurvam** [comment]
@ijuma they were in flight. I added a bunch now.

**Review by ijuma — APPROVED** [review]
LGTM if the tests pass.

**Comment by ijuma** [comment]
Failures are unrelated (both ConsumerBounceTest) and one of the builds passed.

**Comment by ijuma** [comment]
Will merge to trunk soon.

**Pull request closed without merging**
