### PR TITLE
MINOR: Fix typos for streams

### PR DESCRIPTION
**Pull request by berg223**
*More detailed description of your change,
Fix typos for streams*

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]
nice catches!

**Comment by berg223** [comment]
> nice catches!

Thanks, there are still little typos in other module. I will commit in the future after these PRs merged.

**Comment by divijvaidya** [comment]
Unrelated test failures:
```
[Build / JDK 11 and Scala 2.13 / org.apache.kafka.trogdor.coordinator.CoordinatorTest.testTaskRequestWithOldStartMsGetsUpdated()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-13888/2/testReport/junit/org.apache.kafka.trogdor.coordinator/CoordinatorTest/Build___JDK_11_and_Scala_2_13___testTaskRequestWithOldStartMsGetsUpdated__/)
[Build / JDK 17 and Scala 2.13 / kafka.admin.TopicCommandIntegrationTest.testDescribeUnderMinIsrPartitionsMixed(String).quorum=kraft](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-13888/2/testReport/junit/kafka.admin/TopicCommandIntegrationTest/Build___JDK_17_and_Scala_2_13___testDescribeUnderMinIsrPartitionsMixed_String__quorum_kraft/)
```

**Review by divijvaidya — APPROVED** [review]

**Comment by hudeqi** [comment]
Seeing that you have found so many typos, is there any convenient way? Can you share it so that we can scan globally and fix it all at once? @xiaocairush

**Comment by berg223** [comment]
@hudeqi I'm using a tool called [typos](https://github.com/crate-ci/typos). And it can be integrated with GitHub Actions. But I'm sure if it's a good practice to intergrate with repo.

**Comment by hudeqi** [comment]
> @hudeqi I'm using a tool called [typos](https://github.com/crate-ci/typos). And it can be integrated with GitHub Actions. But I'm sure if it's a good practice to intergrate with repo.

Maybe you can try to launch a KIP.

**Comment by berg223** [comment]
@hudeqi I'm now trying to resolved a issue in jira. Maybe you can have a try for KIP  :smile:

**Pull request merged**
