### PR TITLE
MINOR: use new API timeout config in test

### PR DESCRIPTION
**Pull request by vvcephei**
The old timeout configs no longer take effect, as of
53ca52f855e903907378188d29224b3f9cefa6cb. They are replaced
by the new one.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@guozhangwang @mjsax @bbejeck ,

I just noticed that this test is taking over a minute, because 53ca52f855e903907378188d29224b3f9cefa6cb swapped out the config name that Consumer uses to set the default timeouts. (The new default is 1 minute).

This change just sets the config back to 200ms so the test can complete quickly.

**Review by mjsax — APPROVED** [review]
LGTM.

**Comment by guozhangwang** [comment]
LGTM

**Comment by guozhangwang** [comment]
Cherry-picked to 2.0 as well.

**Pull request merged**
