### PR TITLE
MINOR: add MacOS requirement to Streams docs

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
Java 8 passed, 
Java 11 failed
```
kafka.admin.PreferredReplicaLeaderElectionCommandTest.testNoopElection
kafka.api.ConsumerBounceTest.testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup
kafka.api.UserQuotaTest.testThrottledProducerConsumer
```
retest this please

**Comment by gwenshap** [comment]
LOL. We changed HTML files. I don't think we need the tests to pass :)

**Comment by mjsax** [comment]
Cherry-picked to `2.2` branch.

**Pull request closed without merging**
