### PR TITLE
KAFKA-12989: MockClient should respect the request matcher passed to prepareUnsupportedVersionResponse

### PR DESCRIPTION
**Pull request by kirktrue**
Handle the case where `matches` returns `false` and throw the `InvalidStateException` as stated by the JavaDoc.

We need to guard against this unexpected runtime error in the `KafkaAdminClient`'s `sendEligibleCalls` method with a try/catch. Not 100% sure if that's kosher or not.

Included a targeted unit test for this case. The remaining tests in `KafkaAdminTestClient` continue to pass.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kirktrue** [comment]
Can someone from @confluentinc/clients review, please?

**Comment by kirktrue** [comment]
@hachikuji - would you be willing to assign a reviewer for this PR?

The failing tests look like they're related to KRaft tests, so I don't _think_ they're related.

**Comment by kirktrue** [comment]
@cmccabe - could you take a look at this and/or assign a reviewer for this? Thanks!

**Comment by cmccabe** [comment]
Why is `NetworkClient#send` throwing an exception? It shouldn't be doing that, right? Can you explain more about the problem that this PR fixes?

**Comment by kirktrue** [comment]
> Why is `NetworkClient#send` throwing an exception? It shouldn't be doing that, right? Can you explain more about the problem that this PR fixes?

Per [the original issue](https://issues.apache.org/jira/browse/KAFKA-12989) the `MockClient` used for testing allows for fault injection via the `RequestMatcher`. If the test sets up the condition where the request _doesn't_ match some condition, the `MockClient.send` method is supposed to throw an `IllegalStateException`.

That change seemed straightforward except that this now caused problems in `KafkaAdminClient`. Because it's not expecting any errors, this exception causes the thread in `KafkaAdminClient.sendEligibleCalls` that is servicing requests to die, hence my addition of the `try`/`catch` wrapper.

That said, I'm not 100% confident that this change is the right way to handle things. Please advise.

Thanks!

**Pull request closed without merging**
