### PR TITLE
JDK 9 no longer contains JAXB API's as default

### PR DESCRIPTION
**Pull request by narcisoguillen**

### CODE REVIEW

**Comment by ijuma** [comment]
Can you explain why this is needed? We changed the code in trunk not to require that module a while ago.

**Comment by narcisoguillen** [comment]
I've follow the Quickstart guide : https://kafka.apache.org/quickstart 

had problems running Zookeeper server and kafka server. After some research I manage to make it work adding this flag to the kafka server.

**Comment by ijuma** [comment]
Is this for trunk?

**Comment by narcisoguillen** [comment]
I've download kafka from : https://www.apache.org/dyn/closer.cgi?path=/kafka/0.11.0.1/kafka_2.11-0.11.0.1.tgz 

the download link is : http://www-eu.apache.org/dist/kafka/0.11.0.1/kafka_2.11-0.11.0.1.tgz

so, maybe not. Not sure actually. I see releases are up to 1.0 but the download link hits 0.11

**Comment by ijuma** [comment]
The fix will be part of 1.0, but that's still at RC stage.

**Comment by ijuma** [comment]
You can test 1.0 via the following link:

http://home.apache.org/~guozhang/kafka-1.0.0-rc2/

**Comment by ijuma** [comment]
Closing since this was fixed in a different way.

**Pull request closed without merging**
