### PR TITLE
0.10.0 kafka how to delete a deprecated group 

### PR DESCRIPTION
**Pull request by linjikai**
I have a group called HBASE1,but I can't find it by kafka-consumer-groups.sh shell。

I do it by call:
`/usr/hdp/2.5.0.0-1245/kafka/bin/kafka-consumer-groups.sh --zookeeper localhost:2181 --list`
there is some consumer groups likes system produces, the follows:
```
console-consumer-52667
console-consumer-48120
console-consumer-17316
```

and then I call:
`/kafka-consumer-groups.sh --new-consumer --bootstrap-server dn5:6667  --list`
there is some consumer groups is running by my named。
```
PHOTOSEND
HDFS
REDIS
```

but I can't find the group is HBASE1,and it just a test group,now I want to delete it,I try called:
`kafka-consumer-groups.sh --zookeeper localhost:2181 --delete -group HBASE1`
system said:
`Delete for group HBASE1 failed because group does not exist.`

But I can find it in my kafkaManager,And the group is my test group,how could I delete it!

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5504/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5519/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6204/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6220/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6276/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6260/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by songlong** [comment]
I have the same problem.
I found empty consumers in zookeeper, but topics and consumers can see in kafka-manager and kafka commands.
but I found I can not delete group when move anthoer group in same topic.
if using zookeeper delete, it is a problem because have no consumers in zookeeper??

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-test-coverage/347/

**Comment by hachikuji** [comment]
Closing this since the commit history has diverged significantly. If you think there is still an issue, please open a JIRA.

**Pull request closed without merging**
