### PR TITLE
KAFKA-2980 Fix deadlock when ZookeeperConsumerConnector create messag…

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by granthenke** [comment]
fyi: may not link to the jira to to KA**KF**A typo

**Comment by becketqin** [comment]
@granthenke Yeah.... Just noticed that. Thanks for the reminding.

**Comment by granthenke** [comment]
LGTM. On a separate jira we may want to add systests for scenarios like this.

**Comment by guozhangwang** [comment]
@becketqin I am a little confused that "thread blocks when trying to stop the fetchers", since the ConsumerFetcherThread is set to be interruptable, so shutting down should not be blocked?

**Comment by becketqin** [comment]
@guozhangwang , the problem is that the fetchers are not guaranteed to be in blocked state when the shutdown() is called on them. It seems calling interrupt on a running thread does not have any effect but set the interrupted flag. So if the interrupt() call happen before they are blocked on enqueue(), the fetchers will still get blocked.

**Comment by guozhangwang** [comment]
@becketqin Hmm, I think that if the interrupt status flag is set, then upon `enqueue` which calls `BlockingQueue.put`, it will throw InterruptedException directly since it calls `ReentrantLock.lockInterruptibly`, which will still throw InterruptedException according to Javadoc?

"If the current thread:

has its interrupted status set on entry to this method; or
is interrupted while acquiring the lock,
then InterruptedException is thrown and the current thread's interrupted status is cleared."

**Comment by becketqin** [comment]
@guozhangwang That is a good point. However the stack trace showed the Abstract fetcher thread was not interrupted, somehow. My best guess is that after the first round of rebalance finishes, before the fetcher threads actually started, the second round of rebalance was trying to call `interrupt()` on the threads and shutdown them. In that case, the `interrupt()` will have no effect because the fetcher threads haven't started yet.

**Comment by becketqin** [comment]
Never mind about the above comments. That does not make sense. I did some test. It looks `partitionMapCond.singalAll()` will clear the signal flag. When the fetcher thread just started, likely it will parking on `partitionMapCond` because leader information is not available yet. That means if the following lines of code are executed after the fetcher thread is interrupted but before the fetcher thread get scheduled to run. Its interrupt flag may be cleared.
initiateShutdown()
inLock(partitionMapLock) {
      partitionMapCond.signalAll()
}

**Comment by guozhangwang** [comment]
@becketqin I did some test and it seems `Condition.signalAll()` will not clear the flag, however `Condition.await()` can potentially throw the exception and clear the flag, my test code:

```
        Thread.currentThread().interrupt();

        assertTrue(Thread.currentThread().isInterrupted());

        try {
            Thread.sleep(1);
            fail("will never get here");
        } catch (InterruptedException e) {
            assertFalse(Thread.currentThread().isInterrupted());
            Thread.currentThread().interrupt();
        }

        assertTrue(Thread.currentThread().isInterrupted());

        ReentrantLock lock = new ReentrantLock();
        Condition cond = lock.newCondition();

        lock.lock();

        cond.signalAll();

        assertTrue(Thread.currentThread().isInterrupted());

        try {
            cond.await();
        } catch (InterruptedException e) {
            // do nothing
        }

        lock.unlock();

        assertFalse(Thread.currentThread().isInterrupted());
```

**Comment by becketqin** [comment]
@guozhangwang , my test was a little bit different. And I saw interesting behavior.
The following code prints _true_ then _false_.

```
public static void main(String[] args) {
        final ReentrantLock lock = new ReentrantLock();
        final Condition cond = lock.newCondition();
        Thread t = new Thread() {
            @Override
            public void run() {
                lock.lock();
                // When interrupt() is called, the thread will not wake up, but its interrupt flag will be set.
                cond.awaitUninterruptibly();
                lock.unlock();
            }
        };
        t.start();
        t.interrupt();
        // We interrupt the thread here, the thread does not wake up but the interrupted flag should be set.
        System.out.println(t.isInterrupted()); // This line prints true
        // wake up the thread after interrupt the thread.
        lock.lock();
        cond.signalAll();
        // Check if the signal all clears the interrupt flag.
        System.out.println(t.isInterrupted()); // this line prints false
    }
```

The above code means cond.signalAll() clears the interrupt flag. Notice we did not release the lock in the main thread.

If we release the lock in main thread the result becomes interesting. The following code prints _(true, false, false), (true, true, false), (true, true, true)_ randomly. 

```
    public static void main(String[] args) throws InterruptedException {
        final ReentrantLock lock = new ReentrantLock();
        final Condition cond = lock.newCondition();
        Thread t = new Thread() {
            @Override
            public void run() {
                lock.lock();
                // When interrupt() is called, the thread will not wake up, but its interrupt flag will be set.
                cond.awaitUninterruptibly();
                lock.unlock();
            }
        };
        t.start();
        t.interrupt();
        // We interrupt the thread here, the thread does not wake up but the interrupted flag should be set.
        System.out.println(t.isInterrupted());
        // wake up the thread after interrupt the thread.
        lock.lock();
        cond.signalAll();
        // Check if the signal all clears the interrupt flag.
        System.out.println(t.isInterrupted());
        lock.unlock();
        System.out.println(t.isInterrupted());
    }
```

This is quite strange because the later lock.unlock() changes the result on the previous line of printing. 

If we add a `Thread.sleep()` in the main thread after `lock.unlock`. The following code gives either _(true, true, false)_ or _(true, false, false)_.

```
    public static void main(String[] args) throws InterruptedException {
        final ReentrantLock lock = new ReentrantLock();
        final Condition cond = lock.newCondition();
        Thread t = new Thread() {
            @Override
            public void run() {
                lock.lock();
                // When interrupt() is called, the thread will not wake up, but its interrupt flag will be set.
                cond.awaitUninterruptibly();
                lock.unlock();
            }
        };
        t.start();
        t.interrupt();
        // We interrupt the thread here, the thread does not wake up but the interrupted flag should be set.
        System.out.println(t.isInterrupted());
        // wake up the thread after interrupt the thread.
        lock.lock();
        cond.signalAll();
        // Check if the signal all clears the interrupt flag.
        System.out.println(t.isInterrupted());
        lock.unlock();
        Thread.sleep(1);
        System.out.println(t.isInterrupted());
    }
```

So it looks to me that the behavior of calling `signalAll()` after calling `interrupt()` is not deterministic. But `signalAll()` does eventually clear the interrupt flag.

**Comment by guozhangwang** [comment]
@becketqin I tried your code locally, and actually the first program can return {true, true} or {false, false} or {true, false} as well. After digging into Condition I think this is not because of some random behavior of `signalAll()` but `awaitUninterruptibly()`:

```
public final void awaitUninterruptibly() {
            Node node = addConditionWaiter();
            int savedState = fullyRelease(node);
            boolean interrupted = false;
            while (!isOnSyncQueue(node)) {
                LockSupport.park(this);
                if (Thread.interrupted())
                    interrupted = true;
            }
            if (acquireQueued(node, savedState) || interrupted)
                selfInterrupt();
        }
```

Note that it triggers `Thread.interrupted()` every time it returns from parking the thread (which may be returning at any point of time), and only re-set the flag through `selfInterrupt()` at the end of the call. 

So if the call ordering is

```
t.interrupt();                            // main thread
System.out.println(t.isInterrupted());    // main thread
Thread.interrupted();              // t thread
System.out.println(t.isInterrupted());    // main thread
selfInterrupt();     // t thread
```

output is {true, false}, and if call ordering is

```
t.interrupt();                            // main thread
Thread.interrupted();              // t thread
System.out.println(t.isInterrupted());    // main thread
System.out.println(t.isInterrupted());    // main thread
selfInterrupt();     // t thread
```

output is {false, false}, and if call ordering is

```
t.interrupt();                            // main thread
Thread.interrupted();              // t thread
selfInterrupt();     // t thread
System.out.println(t.isInterrupted());    // main thread
System.out.println(t.isInterrupted());    // main thread
```

output is {true, true}. Unfortunately I did not find any better way to validate this, but I did find other functions like "Lock.lock() / unlock(), Condition.signallAll()" never modifies the corresponding thread's flag.

**Comment by guozhangwang** [comment]
So back to the original problem, it's still mysterious to me why `BlockingQueue.put` does not throw InterruptedException if the flag was not reset.

**Comment by becketqin** [comment]
@guozhangwang Thanks for digging into this. I am on vacation in China now so the response might be delayed. I thought about this again. It seems my previous guess about interrupting a non alive thread is not nonsense. 

The FetcherThread are actually created by LeaderFinderThread asynchronously after the rebalance finishes. We have the following code:
```
fetcherThreadMap.get(brokerAndFetcherId) match {
          case Some(f) => fetcherThread = f
          case None =>
            fetcherThread = createFetcherThread(brokerAndFetcherId.fetcherId, brokerAndFetcherId.broker)
            fetcherThreadMap.put(brokerAndFetcherId, fetcherThread)
            fetcherThread.start
        }
```
So the thread is first put into the map then starts. If ```thread.interrupt()``` is called after the thread is put into the map but before the thread starts, the interrupt will be missed. Maybe it is better to fix the issue here.

**Comment by guozhangwang** [comment]
@becketqin Hmm, but both `addFetcherForPartitions` and `closeAllFetchers` are synchronized by the `mapLock` so that should not happen right?

BTW Have a good time in China!

**Comment by guozhangwang** [comment]
@becketqin Is this still valid and would you like to continue working on it? If yes I'd love to review and resolve it.

**Comment by becketqin** [comment]
@guozhangwang It seems we did not see this issue after its first occurrence. I'll just close this PR.

**Pull request closed without merging**
