### PR TITLE
KAFKA-4052: Allow passing properties file to ProducerPerformance

### PR DESCRIPTION
**Pull request by SinghAsDev**
Tested by running on a kerberos enabled Kafka cluster.

### CODE REVIEW

**Comment by SinghAsDev** [comment]
@ijuma mind reviewing this?

**Comment by harshach** [comment]
+1

**Comment by gwenshap** [comment]
It looks incomplete?

I'm not sure what's the expected behavior if:
- I don't specify producer-props or producer-config, but I assume one is mandatory? Shouldn't we check and give proper error?
- What if I specify both? It looks like producer-props overrides producer-config, did we validate that this is the case? perhaps we want to make sure the built-in help includes this clarification.

**Comment by SinghAsDev** [comment]
@gwenshap/ @harshach thanks for the review.

> I don't specify producer-props or producer-config, but I assume one is mandatory? Shouldn't we check and give proper error?

I was relegating the check to ConfigDef, however I think it is better to fail fast. Updated patch to check for it.

> What if I specify both? It looks like producer-props overrides producer-config, did we validate that this is the case? perhaps we want to make sure the built-in help includes this clarification.

Yes, producer-props will take precedence, this is in accordance with other CLI tools. Added a note about this in built-in help. Thanks for pointing this out.

**Comment by SinghAsDev** [comment]
The test failure is not related. @gwenshap @harshach does this look ok now?

**Comment by gwenshap** [comment]
LGTM. Thanks for adding this.

**Pull request closed without merging**
