### PR TITLE
test github action ci without permission

### PR DESCRIPTION
**Pull request by frankvicky**
as titile

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@frankvicky could you please remove `develocity-access-key: ${{ secrets.GE_ACCESS_TOKEN }}` to file another PR?

**Comment by mumrah** [comment]
FYI @chia7712 and @frankvicky the ASF github runners are having trouble this morning

**Comment by chia7712** [comment]
> the ASF github runners are having trouble this morning

I wish this bad news does not extinguish our love for github CI :)

**Comment by mumrah** [comment]
BTW, I'm surprised this PR was able to trigger the actions. I was under the impression that this setting is turned off for apache/kafka

image

**Comment by mumrah** [comment]
I checked with Infra and they say apache/kafka is currently configured to require approval for PRs from non-committers to trigger workflows.

@chia7712 did you have to manually approve @frankvicky's PRs to run?

**Comment by chia7712** [comment]
close as #16936 is almost completed

**Comment by chia7712** [comment]
> did you have to manually approve @frankvicky's PRs to run?

no, I did not do that (sorry that I missed your comment). Actually, I expected to see the "Approve" button also...

**Pull request closed without merging**
