### PR TITLE
MINOR: remove storage/src/generated from tracked files

### PR DESCRIPTION
**Pull request by chia7712**
related to #10271

The generated code from other modules have beed excluded from tracked files.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by chia7712** [comment]
@satishd @kowshik FYI

**Review by junrao — APPROVED** [review]
@chia7712 : Thanks for the PR. LGTM

**Comment by kowshik** [comment]
@chia7712 Thanks for the PR. LGTM.

**Review by satishd — APPROVED** [review]
Thanks @chia7712 for the PR, LGTM.

**Comment by ableegoldman** [comment]
Is it possible to set up the gitignore to automatically ignore anything under a `generated/` subdirectory?

**Comment by chia7712** [comment]
> Is it possible to set up the gitignore to automatically ignore anything under a generated/ subdirectory?

please take a look at #10671

**Pull request merged**
