### PR TITLE
MINOR: Improve Javadoc style

### PR DESCRIPTION
**Pull request by eneveu**
Fixed a few Javadoc issues:

1) Do not end comments with `**/`

2) Align leading asterisks

3) Start comments with `/**` instead of `/*`
    Javadoc comments must start with `/**`.
    When starting with `/*`, Javadoc tools do not recognize those comments as Javadoc comments, it thinks they are simple block comments, and does not associate them with their class / member.

4) Fix dangling Javadoc comments

5) Avoid `@see` in the middle of Javadoc
    When the `@see` tag is in the middle of a Javadoc comment, the Javadoc tool thinks the rest of the comment is part of the `@see` description.
    There are two ways to fix this:
    - If we really want an `@see` tag, we can move it at the bottom of the comment, where tags are supposed to be.
    - When we want a link in the middle of the content, we can do: `See <a href="http://www.example.com">Link title</a>.`

6) Fix `@throws` syntax
An `@throws` declaration should be followed by the exception name, not by an `@link` or an `@see`.

I followed the Javadoc / Scaladoc guidelines as well as Stephen Colebourne's article about Javadoc coding standards: https://blog.joda.org/2012/11/javadoc-coding-standards.html .

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by eneveu** [comment]
This contribution is my original work and I license the work to the Kafka project under the Apache License, Version 2.0.

I also have lots of other Javadoc improvements planned, but I wanted to start with those few "quick wins" to avoid polluting the diffs of my other improvements.

**Comment by eneveu** [comment]
Also, please note that I created multiple focused commits, to make it easier to review the changes.

**Comment by eneveu** [comment]
I rebased my branch on trunk since there were some conflicts. I don't understand why the build fails, I only changed Javadocs in this PR. Is it possible to rerun the tests?

I have many other improvements coming for the Javadocs, but I don't know what is the best approach. Should I make multiple smaller PRs, each one focusing on a separate project (connect / client / core), to make the review quicker? Or is it better to do one big PR that solves an issue across the whole codebase?

**Comment by kamalcph** [comment]
To rerun the tests, comment "retest this please" phrase.

**Comment by eneveu** [comment]
retest this please

**Comment by eneveu** [comment]
retest this please

**Comment by eneveu** [comment]
Closing this PR. I will create smaller PRs that are easier to review. Also, those PRs will be rebased on the latest version of trunk, which hopefully means the tests will pass (I don't see why changing the Javadocs would fail the tests).

**Pull request closed without merging**
