### PR TITLE
KAFKA-10047: Remove unnecessary widening of (int to long) scope in FloatSerializer.

### PR DESCRIPTION
**Pull request by tguruprasad**
@halorgium @astubbs @alexism @glasser @rhardouin

### CODE REVIEW

**Comment by glasser** [comment]
I'm not sure why I'm tagged; did you mean somebody else?

**Comment by tguruprasad** [comment]
Apologizes for spamming folks who are tagged. As mentioned in [this wiki](https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Code+Changes), I selected GitHub's automatic suggestions to tag the folks.

**Comment by chia7712** [comment]
@tguruprasad It would be better to ping author or kafka active committers to review code :)

**Comment by chia7712** [comment]
Also, KAFKA-10047 already has a PR (https://github.com/apache/kafka/pull/9351). If you want to create a PR for it, it would be better to ask the author of PR (or reporter of jira) if they don't work on it anymore. If so, it is ok to take over the issue.

**Comment by tguruprasad** [comment]
@chia7712 thanks for pointing out the existing PR. Since I had created and assigned JIRA to myself I didn't realized someone has made fix for it. Let me close this PR and keep the existing PR open. Thanks.

**Pull request closed without merging**
