### PR TITLE
MINOR: Extract SCALA_BINARY_VERSION from SCALA_VERSION

### PR DESCRIPTION
**Pull request by kkonstantine**
Will allow users to set one fewer environment variable if they need to
change scala version. Still, SCALA_BINARY_VERSION can be explicitly set.

### CODE REVIEW

**Comment by kkonstantine** [comment]
@ijuma Very minor fix. Just in case you think it's useful. I feel it's not a bad idea to require setting one environment variable instead of two.

**Comment by ijuma** [comment]
Thanks @kkonstantine, the change itself looks good to me. We should update the `Readme.md` as it references `SCALA_BINARY_VERSION` and the equivalent `bat` file for consistency as well (assuming there's an equivalent Windows command).

**Comment by kkonstantine** [comment]
Thank you @ijuma for your comments. I guess I needed a bit of encouragement to figure out how to apply the change on Windows too. Tested under Windows Server 2016 Datacenter. Both ZK and Kafka start correctly. 

I also changed the README even though I thought it didn't need a change when I issued the PR. Let me know if the change sounds informative enough.

**Comment by enothereska** [comment]
Ok, I didn't test the whole thing, just limited to checking this script:
_`IF ["%SCALA_VERSION%"] EQU [""](set SCALA_VERSION=2.10.6)

IF ["%SCALA_BINARY_VERSION%"] EQU [""](for /f) do (
    set FIRST=%%a
    set SECOND=%%b
    if ["%SECOND%"] EQU [""](set SCALA_BINARY_VERSION=%FIRST%) else (
      set SCALA_BINARY_VERSION=%FIRST%.%SECOND%
    )
  )
)
echo %SCALA_BINARY_VERSION%
`_

I set the SCALA_VERSION before hand, then run the above script, but I get nothing:
_`C:\Users\enoth\kafka>echo %SCALA_VERSION%
2.11.9
C:\Users\enoth\kafka>IF ["2.11.9"] EQU [""](set SCALA_VERSION=2.10.6)

C:\Users\enoth\kafka>IF [""] EQU [""](for /F) do (
set FIRST=%a
set SECOND=%b
if [""] EQU [""](set SCALA_BINARY_VERSION=)  else (set SCALA_BINARY_VERSION=.
)
) )

C:\Users\enoth\kafka>(
set FIRST=2
set SECOND=11
if [""] EQU [""](set SCALA_BINARY_VERSION=)  else (set SCALA_BINARY_VERSION=.
)
)

C:\Users\enoth\kafka>echo
ECHO is on.`_

I'm probably doing something wrong. @kkonstantine could you double check? Thanks.

**Comment by kkonstantine** [comment]
Hi @enothereska. Thank you for your review. 

I just pushed a fix for the second digit. In my previous runs it worked (it correctly started kafka) because I had only `*2.11*.jar` versions available as packages and `2*` would match `2.11`. Now the string split of both the first two version digits should work. 

(The issue was related to how variables are expanded within the `for` loop).

You can confirm its correct behavior just by running the following `bat` script as: 
`.\kafka-just-print-vars.bat Main`, 
which corresponds to the initial part of `kafka-run-class.bat`: 

``` Batchfile
@echo off

rem Licensed to the Apache Software Foundation (ASF) ... etc

setlocal enabledelayedexpansion

IF [%1] EQU [] (
    echo USAGE: %0 classname [opts]
    EXIT /B 1
)


rem Using pushd popd to set BASE_DIR to the absolute path
pushd %~dp0..\..
set BASE_DIR=%CD%
popd


IF ["%SCALA_VERSION%"] EQU [""] (
  set SCALA_VERSION=2.10.6
)

IF ["%SCALA_BINARY_VERSION%"] EQU [""] (
  for /f "tokens=1,2 delims=." %%a in ("%SCALA_VERSION%") do (
    set FIRST=%%a
    set SECOND=%%b
    if ["!SECOND!"] EQU [""] (
      set SCALA_BINARY_VERSION=!FIRST!
    ) else (
      set SCALA_BINARY_VERSION=!FIRST!.!SECOND!
    )
  )
)

echo %SCALA_VERSION%
echo %SCALA_BINARY_VERSION%
```

**Comment by kkonstantine** [comment]
This latest version was my initial windows version too, but I ended up using percent expansion `%%` instead of delayed expansion `!!` because it seemed to work (again matching of jars happened because `2*.jar` matched `2.11*.jar`). Current version correctly expands the variable to `2.11*jar` (uses the two digits). 

You may try the above script, by first running `set SCALA_VERSION=2.11.8` in a command line prompt and try again by unsetting it with `set SCALA_VERSION=`. Finally you may test that the `else` branch within the `for` loop works by setting `set SCALA_VERSION=2`.

**Comment by enothereska** [comment]
Ok, this works. LGTM

**Comment by ijuma** [comment]
Thanks for going the extra mile @kkonstantine and thanks for testing the PR @enothereska. LGTM.

**Pull request closed without merging**
