### PR TITLE
KAFKA-13449: Comment optimization for parameter log.cleaner.delete.retention.ms

### PR DESCRIPTION
**Pull request by RivenSun2**
Story JIRA: https://issues.apache.org/jira/browse/KAFKA-13449

Author: RivenSun2 riven.sun@zoom.us

Reviewers: Luke Chen showuon@gmail.com

### CODE REVIEW

**Review by showuon — COMMENTED** [review]
LGTM! Just a minor comment, please make each line longer because there are some remaining allowed spaces at the end. Thanks.

**Comment by RivenSun2** [comment]
@showuon 
Sure, luke.
please help to review changes when available.
Thanks.

**Review by showuon — APPROVED** [review]
LGTM! The `log.cleaner.delete.retention.ms` is consistent with `delete.retention.ms` now. Thank you.

**Comment by RivenSun2** [comment]
Hi @guozhangwang @hachikuji
please help check this PR when available. Thank you.

**Review by dajac — APPROVED** [review]
LGTM, thanks for patch.

**Pull request merged**
