### PR TITLE
MINOR: Removed dead field

### PR DESCRIPTION
**Pull request by original-brownbear**
Really trivial but can't hurt to clean this up I think.
 Just saw this when trying out the Findbugs task randomly :)

### CODE REVIEW

**Comment by original-brownbear** [comment]
@hachikuji @ijuma fyi :)

**Comment by ijuma** [comment]
I think this is already included in https://github.com/apache/kafka/pull/2780, which was submitted shortly before this one.

**Comment by original-brownbear** [comment]
@ijuma can't find any change to the file changed here in that one? (could be wrong it's well past midnight here :D)

**Comment by ijuma** [comment]
Hmm, I thought I saw that change in another PR. But you're right that it doesn't seem to be #2780. I'll merge this one.

**Review by ijuma — APPROVED** [review]
LGTM.

**Comment by ijuma** [comment]
Ah, I was right that I had seen that change in another PR: https://github.com/apache/kafka/commit/aea14651184476940c69238535de5143e61f4c31

So, I think we should close this one.

**Comment by original-brownbear** [comment]
@ijuma sure, closing :)

**Pull request closed without merging**
