### PR TITLE
KAFKA-10295: Wait for connector recovery in test_bounce

### PR DESCRIPTION
**Pull request by gharris1727**
Signed-off-by: Greg Harris <gregh@confluent.io>

This additional waiting is for:
* The scheduled.rebalance.max.time.ms to expire and for tasks to be reassigned
* The source connector to start and commit offsets at least once beyond it's last commit
* The sink connector to have adequate time to read any of the messages written by the source

Prevents flakey test failures with messages like "Found sink sequence number greater than any generated sink sequence number for task %d: %d > %d" when test_bounce is running with hard bounces and Incremental Cooperative Rebalancing enabled.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gharris1727** [comment]
cc @rhauch for review

**Comment by rhauch** [comment]
@gharris1727 Thanks for the proposed fix. I've started a system test build for this branch: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/4046/

**Comment by rhauch** [comment]
All 69 Connect system tests passed: http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2020-07-20--001.1595250965--gharris1727--bounce-recovery--c00de2d82/report.html

**Review by rhauch — APPROVED** [review]
LGTM. Thanks, @gharris1727!

**Pull request merged**
