### PR TITLE
KAFKA-9407: Return Immutable List from SchemaSourceTask

### PR DESCRIPTION
**Pull request by belugabehr**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rondagostino** [comment]
LGTM

**Comment by ijuma** [comment]
ok to test

**Comment by kkonstantine** [comment]
retest this please

**Comment by kkonstantine** [comment]
Only the two flaky test cases in 
`org.apache.kafka.streams.integration.StandbyTaskEOSIntegrationTest.surviveWithOneTaskAsStandby` failed, that are now now fixed by: https://github.com/apache/kafka/pull/8330

I'll skip rebuilding this RP and will merge only to `trunk`.

**Review by kkonstantine — APPROVED** [review]
LGTM

**Pull request merged**
