### PR TITLE
MINOR: Allow writing tombstone offsets for arbitrary partitions in the FileStreamSourceConnector

### PR DESCRIPTION
**Pull request by yashmayya**
- Background - https://cwiki.apache.org/confluence/display/KAFKA/KIP-875%3A+First-class+offsets+support+in+Kafka+Connect, https://github.com/apache/kafka/pull/13945#discussion_r1266867639, https://github.com/apache/kafka/pull/14005

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by yashmayya** [comment]
@C0urante now that https://github.com/apache/kafka/pull/14005 has been merged, could you please take a look at this minor change to `FileStreamSourceConnector::alterOffsets` (based on this previously discussed [follow-up](https://github.com/apache/kafka/pull/13945#discussion_r1266867639)) whenever you get a chance?

**Comment by C0urante** [comment]
@yashmayya Beat you to it :) https://github.com/apache/kafka/pull/14233

(But this one looks good too and we can use it instead)

**Review by C0urante — APPROVED** [review]
LGTM, thanks Yash! Will merge pending CI build

**Comment by yashmayya** [comment]
Ah whoops, I missed that, my bad!

**Pull request merged**
