### PR TITLE
KAFKA-4831: add documentation for KIP-265

### PR DESCRIPTION
**Pull request by guozhangwang**
This is based on top of https://github.com/apache/kafka/pull/4685 so should only be merged after that one.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@mjsax @bbejeck @vvcephei @dguy for reviews.

**Review by dguy — APPROVED** [review]
LGTM

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
retest this please

**Pull request merged**
