### PR TITLE
KAFKA-16226; Reduce synchronization between producer threads (#15323)

### PR DESCRIPTION
**Pull request by msn-tldr**
NOTE this cherry-picks fix https://github.com/apache/kafka/pull/14522 into 3.6

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by msn-tldr** [comment]
@hachikuji / @ijuma can you help in merging this?

**Comment by msn-tldr** [comment]
The tests failing on jenkins are unrelated, flaky tests.

**Review by ijuma — APPROVED** [review]
LGTM, mostly clean cherry-pick. Test failures that reproduced across different JDK versions are the same as the 3.6 branch.

**Comment by msn-tldr** [comment]
@ijuma thanks!

**Pull request merged**
