### PR TITLE
MINOR: fix ZkMetadataCache package name

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

The `ZkMetadataCache` package name is not correct.

### CODE REVIEW

**Comment by dengziming** [comment]
ping @cmccabe , I'm also thinking about moving `MetadataCache` into `kafka.server.metadata` , WDYT?

**Comment by cmccabe** [comment]
> ping @cmccabe , I'm also thinking about moving MetadataCache into kafka.server.metadata , WDYT?

yes, this should be in the `kafka.server.metadata` package, consistent with the other files in this directory.

**Review by cmccabe — APPROVED** [review]
LGTM

**Comment by cmccabe** [comment]
committed

**Pull request closed without merging**
