### PR TITLE
MINOR: Add documentation for KAFKA-6086 (ProductionExceptionHandler)

### PR DESCRIPTION
**Pull request by farmdawgnation**
Attempt number 2 at adding documentation related to KAFKA-6086, the `ProductionExceptionHandler`.

Tagging @guozhangwang and @mjsax for review!

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
Thanks for the PR. LGTM.

\cc @joel-hamill

**Comment by joel-hamill** [comment]
LGTM

**Comment by mjsax** [comment]
Retest this please.

Call for merging @guozhangwang @dguy

**Review by dguy — APPROVED** [review]
Thanks @farmdawgnation, LGTM

**Pull request merged**
