### PR TITLE
KAFKA-6733: Support of printing additional ConsumerRecord fields in DefaultMessageFormatter

### PR DESCRIPTION
**Pull request by Matzz**
New supported fields: offset, partition and headers. Code is backward compatible, so output will remain the same if user won't specify new configuration properties.
Added unit tests to DefaultMessageFormatter which cover previous and new properties.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Matzz** [comment]
@huxihx @ijuma Could I ask for review?

**Comment by rajinisivaram** [comment]
@ijuma Do we need a KIP for this since it is adding new properties to the CLI of ConsoleConsumer?

**Comment by Matzz** [comment]
@rajinisivaram @ijuma I didn't found any documentation for current properties of `DefaultMessageFormatter` (provided by console consumer  `--property` parameters). I'm happy to add some docs but I'm not sure where.

**Comment by onzo-mateuszzakarczemny** [comment]
@rajinisivaram @ijumaI resolved conflicts with trunk. Could I ask for some guide what's next? I should just wait for review?

**Comment by Matzz** [comment]
@rajinisivaram @ijumai resolved conflicts with trunk. Could I ask for some guide what's next? I should just wait for review?

**Comment by rajinisivaram** [comment]
@Matzz Usually, when we add or change command line arguments to a tool, we need to write up a KIP (https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals) and go throught the KIP review process. This is not exactly adding new CLI arguments, but it is adding  externally visible properties, so not sure if we still need a KIP. Will see what @ijuma says. 

BTW, looks like there are still conflicts on `ConsoleConsumer.scala` in the PR.

**Comment by onzo-mateuszzakarczemny** [comment]
@rajinisivaram @ijuma A Kind nudge.
It takes a bit long for that PR. It doesn't brake any contract or any other backward comparability. It just adds couple more parameters for default message formatter (and therefore console consumer). I saw in other PRs that there was no KIP for such changes (eg. #4797)
If you look at the code you will see that the most of code is just bit of refactoring plus tests for the exiting functionality. Functionally there are just couple of `if(shoidIPrintX) { print(x) }`

**Comment by ijuma** [comment]
The KIP for #4797 was https://cwiki.apache.org/confluence/display/KAFKA/KIP-265%3A+Make+Windowed+Serde+to+public+APIs

**Comment by onzo-mateuszzakarczemny** [comment]
@ijuma Ok then. I'll create a KIP

**Comment by gwenshap** [comment]
Was a KIP ever created? Can you follow up with #?

**Comment by gAmUssA** [comment]
@onzo-mateuszzakarczemny Hi Mateusz. Any progress on KIP? Thank you

**Comment by Matzz** [comment]
Sorry I didn't have time to create a KIP. I'll try to work on that this week.

**Comment by gAmUssA** [comment]
@Matzz Thank you!

**Comment by Matzz** [comment]
KIP created - https://cwiki.apache.org/confluence/display/KAFKA/KIP-431%3A+Support+of+printing+additional+ConsumerRecord+fields+in+DefaultMessageFormatter
I need to create a email thread to now.

**Comment by Matzz** [comment]
Discussion thread - http://mail-archives.apache.org/mod_mbox/kafka-dev/201902.mbox/%3CCAHwv8Gb8Uf5MgDKawwc_OSaxfO916cJ-Mq5YJyCmfj_h3f_adw%40mail.gmail.com%3E

**Comment by onzo-mateuszzakarczemny** [comment]
retest this please

**Comment by Matzz** [comment]
retest this please

**Comment by badaiaqrandista** [comment]
Any update on this PR? Can this be merge? @Matzz @rajinisivaram

**Comment by stanislavkozlovski** [comment]
@badaiaqrandista we cannot merge this as the KIP was not voted in. The vote thread was started on April 12th but has not received any votes.

@Matzz would you be interested in ressurrecting the thread?

**Comment by Matzz** [comment]
@stanislavkozlovski 
Yes sure. Just create new voting thread?

**Comment by stanislavkozlovski** [comment]
@Matzz yeah!

**Comment by badaiaqrandista** [comment]
This PR should be closed as it has been superseded by PR 9099 (https://github.com/apache/kafka/pull/9099).

**Comment by dajac** [comment]
Closing as this was addressed by https://github.com/apache/kafka/pull/9099.

**Pull request closed without merging**
