### PR TITLE
KAFKA-15817: Avoid reconnecting to the same IP address if multiple ad…

### PR DESCRIPTION
**Pull request by bob-barrett**
…dresses are available

This change is a follow-up to https://github.com/apache/kafka/pull/9902. When re-resolving DNS after disconnecting, it is possible (likely, even) that we will resolve the same set of addresses in the same order, meaning we could attempt to reconnect to the same IP that we just disconnected from. In the case where we disconnected from the IP address because it has become unhealthy (due to a load balancer going down or a network routing layer restarting, for example), the client will need to time out before connecting to the next IP. This essentially unifies the behavior before and after KAFKA-12193: re-resolve after disconnecting while still progressing through the IP list.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Let's cherry pick this to 3.6 after this is merged to master.

**Review by lucasbru — APPROVED** [review]
LGTM, thanks for the PR!

**Review by AndrewJSchofield — APPROVED** [review]
lgtm

**Comment by lucasbru** [comment]
test failures are know flaky tests

**Comment by ijuma** [comment]
@lucasbru Did you cherry-pick to 3.6?

**Comment by lucasbru** [comment]
@ijuma I did not. My understanding was that this shouldn't be included in 3.6.1, so I was waiting for 3.6.1 to go through before cherry-picking it.

**Pull request merged**
