### PR TITLE
KAFKA-8676: Avoid Unnecessary stops and starts of tasks

### PR DESCRIPTION
**Pull request by LuyingLiu**
As this is testing for initialization behaviors, I do not think it is a 
good idea to do unit and integrate testing. System tests are needed. 
Log INFO output and KafkaConnect API for checking the status of 
connectors and tasks are useful tools when checking which 
connectors and tasks start/stop.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by LuyingLiu** [comment]
@gwenshap @ewencp

**Comment by guozhangwang** [comment]
Just by reading the description I think the change looks reasonable, ping @rhauch @kkonstantine  for another look.

Also, could you add a unit test covering this case to illustrate the behavioral difference?

**Comment by LuyingLiu** [comment]
I am having a hard time adding a unit test for this, as it is difficult to make sure that a particular task is not started. And I think it is a good idea to add an integration test to illustrate the difference of task-starts for a particular request.

**Review by kkonstantine — APPROVED** [review]
Thanks for the fix @LuyingLiu !

I've confirmed that it works. Currently it's evident only under the new `compatible` connect protocol, because in `eager` all the tasks get restarted anyways. I've written a unit test to guard against a change in this behavior which I pushed here: https://github.com/apache/kafka/pull/7287 so I don't interfere with your current PR.  

An integration test could be extended later on to validate this fix as well. 

LGTM

**Comment by kkonstantine** [comment]
@rhauch would you mind taking a look? 
This is a good fix now that incremental cooperative rebalancing is the default in Connect. 
It avoids unnecessary restarts during connector reconfiguration.

**Review by rhauch — APPROVED** [review]
LGTM. Thanks, @LuyingLiu, for reporting this and for providing the fix. Also thanks to @kkonstantine for supplying in #7287 a new unit test that verifies that the current behavior is incorrect and that the behavior introduced in this PR is correct.

I plan to merge this back to the 2.3 branch, which is when the affected code started relying upon notifications that only the changed tasks were updated. Prior to that, signaling that all tasks were changed was not a big deal because all tasks were stopped and restarted during a rebalance anyway, so if extra task IDs were considered updated then no big deal -- backporting this fix farther back would seem to add unnecessary risk.

**Pull request merged**
