### PR TITLE
KAFKA-8332: Restore determinism in protocol selection during JoinGroupRequest handling

### PR DESCRIPTION
**Pull request by kkonstantine**
The transition from List to Set for the group of embedded protocols that is supported combined with implicit conversions in scala during map on collections discards the order of preference for the supported embedded protocols. This fix restores determinism of selection based on the order. This bug may affect any group of Kafka clients (Connect workers, Consumers) that support the same set of more than one embedded protocols. In this case unanimity does not resolve selection alone and the order of preference needs to be respect and lead to deterministic selection. 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by jsancio — COMMENTED** [review]
LGTM. Thanks @kkonstantine

**Comment by ijuma** [comment]
Why are we using a `Set` if order matters though?

**Comment by ijuma** [comment]
An alternative fix was posted previously https://github.com/apache/kafka/pull/6626/

**Comment by hachikuji** [comment]
I will go ahead and close this since #6626 was merged. Please reopen if there is still a problem.

**Pull request closed without merging**
