### PR TITLE
MINOR: remove duplicated code in ConsumerPerformance

### PR DESCRIPTION
**Pull request by huxihx**
In `consume` method, the consumer subscribes the topic as expected, so there is no need to do the same thing ahead of this method call.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by huxihx** [comment]
Call for review @ijuma

**Comment by huxihx** [comment]
Please review this minor change. @hachikuji

**Comment by ijuma** [comment]
Thanks for the PR. Maybe you can clean-up the following in the `consume` method at the same time:

```scala
-    val startMs = System.currentTimeMillis
-    var lastReportTime: Long = startMs
-    var lastConsumedTime = System.currentTimeMillis
-    var currentTimeMillis = lastConsumedTime
+    var currentTimeMillis = System.currentTimeMillis
+    var lastReportTime: Long = currentTimeMillis
+    var lastConsumedTime = currentTimeMillis
```

**Review by ijuma — APPROVED** [review]
LGTM

**Pull request merged**
