### PR TITLE
KAFKA-9384; Loop improvements

### PR DESCRIPTION
**Pull request by highluck**
3 loops in one and this immutable

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
@highluck Thank you for the PR. the PR looks good to me. 

Apparently, there are issues building PRs.
 @vvcephei  @mjsax @bbejeck @guozhangwang Do you know anything about it?

**Comment by highluck** [comment]
@cadonna 
Thanks for the comment

https://issues.apache.org/jira/projects/KAFKA/issues/KAFKA-9384

The ticket I reported
Can you assign this ticket to me?
thank you

**Comment by cadonna** [comment]
Unfortunately I cannot. However, one of the guys that I mentioned above can add you as a contributor and then you should be able to assign the ticket to yourself.

**Comment by highluck** [comment]
@cadonna
thank you!!

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
retest this please

**Pull request merged**
