### PR TITLE
KAFKA-2430; Listing of PR commits in commit message should be optional

### PR DESCRIPTION
**Pull request by ijuma**
If there is a single commit in the PR, then it's never listed.

### CODE REVIEW

**Comment by ijuma** [comment]
I tested this with PR #99 with both options and #106 to verify a single commit case.

**Comment by guozhangwang** [comment]
@ijuma It seems contains some irrelevant changes from other JIRAs on ProducerSendThread.scala and CoreUtils.scala.

**Comment by ijuma** [comment]
Sorry @guozhangwang, it seems like some changes from testing the script were included accidentally (not sure how I didn't see that). Fixed.

**Comment by guozhangwang** [comment]
Thanks, LGTM!

**Pull request closed without merging**
