### PR TITLE
MINOR: Clean up RemoteLogManager

### PR DESCRIPTION
**Pull request by jlprat**
Cleans up some warnings in class, like Raw referencing a parametrized type and lambdas instead of method references.

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
Hi @satishd I was looking at the code of `RemoteLogManager` and found a couple of warnings that I thought they were worth cleaning up.

**Review by showuon — APPROVED** [review]
LGTM! Assuming all tests passed.

**Review by machi1990 — APPROVED** [review]

**Review by satishd — APPROVED** [review]
Thanks @jlprat for the PR. LGTM.

**Comment by jlprat** [comment]
Tests failures seem all unrelated to the change, and have been flaking previously.

**Pull request merged**
