### PR TITLE
KAFKA-7269: Add docs for KStream.merge

### PR DESCRIPTION
**Pull request by lucapette**
As discussed in KAFKA-7269

### CODE REVIEW

**Comment by lucapette** [comment]
I just realized there's a typo in the PR. Will fix right away!

**Comment by lucapette** [comment]
Just fixed it. It looks like this now:

screen shot 2018-08-16 at 07 27 59

**Review by mjsax — APPROVED** [review]
LGTM.

**Comment by mjsax** [comment]
@guozhangwang @bbejeck @vvcephei Can we get a second pair of eyes looking at this. Thx.

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
retest this please

**Comment by guozhangwang** [comment]
Thanks @lucapette for your contribution!

**Comment by lucapette** [comment]
@guozhangwang thank you! very happy to contribute and hope to do more in the future!

**Pull request merged**
