### PR TITLE
KAFKA-4319; AbstractFetcherManager: shutdown speedup

### PR DESCRIPTION
**Pull request by resetius**

### CODE REVIEW

**Comment by fxsever** [comment]
Great improvement for huge clusters!

**Comment by hachikuji** [comment]
@resetius Thanks for the PR. The fix is trivial, but it might be worthwhile linking to a JIRA to increase visibility of the problem (someone might also be wondering why shutdown is slow) and potential solution.

**Comment by resetius** [comment]
done https://issues.apache.org/jira/browse/KAFKA-4319

**Comment by ijuma** [comment]
LGTM

**Comment by hachikuji** [comment]
LGTM. Thanks for the patch!

**Comment by hachikuji** [comment]
Merged to trunk after rephrasing the title a little. Hopefully it's reasonable.

**Pull request closed without merging**
