### PR TITLE
[KAFKA-14133] Migrate EasyMock to Mockito in StateRestoreCallbackAdapterTest, Store…

### PR DESCRIPTION
**Pull request by olalamichelle**
…ToProcessorContextAdapterTest, StreamsProducerTest

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by clolov** [comment]
Hello! I believe for the first two (StateRestoreCallbackAdapterTest and StoreToProcessorContextAdapterTest) there is already a pull request here - https://github.com/apache/kafka/pull/14210. For the last one, StreamsProducerTest please reachout to @bachmanity1 as he has put his name against it in https://issues.apache.org/jira/browse/KAFKA-14133

**Comment by olalamichelle** [comment]
Hi @bachmanity1, have you already submitted PR for this test? Thanks.

**Comment by bachmanity1** [comment]
Hi @olalamichelle, I was planning to open a PR but since you've already started to work on this and opened a PR I can transfer the ownership to you.

**Comment by olalamichelle** [comment]
@bachmanity1 Thank you! @clolov could you please assign my name to StreamsProducerTest? Seems that I do not have edit permission for  https://issues.apache.org/jira/browse/KAFKA-14133. Thank you!

**Comment by clolov** [comment]
Hello @olalamichelle, if you would like to pursue this could you update this (and the other pull requests) so that a) they are rebased on the latest trunk and b) they only contain the files which have not been covered by other pull requests? Once this is done I am happy to start reviewing them and asking for people to merge them

**Comment by clolov** [comment]
Polite ping @olalamichelle - I will wait until mid next week and then I will start opening new pull requests targeting these files as I would like to double-down on the effort to finish this migration

**Comment by clolov** [comment]
I am closing this and related pull requests due to inactivity and taking over the remaining test work. If there is a timely response I will pause my work and let these go in trunk first.

**Pull request closed without merging**
