### PR TITLE
MINOR: Fix format of allowed operations in kafka-acls error message

### PR DESCRIPTION
**Pull request by tjouni**
kafka-acls cli prints the following error message on invalid operation:
```
$ kafka-acls --bootstrap-server xxx:9095 --remove --allow-principal "User:abc" --allow-host * --operation DESCRIBE_CONFIGS --topic xyz
ResourceType TOPIC only supports operations WRITE,DESCRIBE,ALL,READ,CREATE,ALTER,DELETE,DESCRIBE_CONFIGS,ALTER_CONFIGS
```
The following command actually works:
```
$ kafka-acls --bootstrap-server xxx:9095 --remove --allow-principal "User:abc" --allow-host * --operation DescribeConfigs --topic xyz
```

The operations are listed correctly in the cli --help:
```
--operation <String>                     Operation that is being allowed or     
                                           denied. Valid operation names are:   
                                         	Describe                              
                                         	DescribeConfigs                       
                                         	Alter                                 
                                         	IdempotentWrite                       
                                         	Read                                  
                                         	Delete                                
                                         	Create                                
                                         	ClusterAction                         
                                         	All                                   
                                         	Write                                 
                                         	AlterConfigs                          
                                         	CreateTokens                          
                                         	DescribeTokens    
```

This PR fixes the invalid formating of operations in the error message and adds a space after the comma.

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by showuon — COMMENTED** [review]
@tjouni , thanks for the fix! 
I'd like to confirm:
Before your fix:
`--operation DescribeConfigs` works, but `--operation DESCRIBE_CONFIGS` won't work.

After your fix:
`--operation DescribeConfigs` won't work, but `--operation DESCRIBE_CONFIGS` works.

Is my understanding correct? 
If so, that might break backward compatibility since there might be users using `--operation DescribeConfigs` for a long time. We don't want to break it after upgrading. Could you fix it by making both cases work?

**Comment by tjouni** [comment]
No, this commit just makes the error message shown after specifying an incorrect operation to have the operations in the format the CLI accepts (pascalcase). It does not break anything as it only changes the printed line.

**Comment by showuon** [comment]
> No, this commit just makes the error message shown after specifying an incorrect operation to have the operations in the format the CLI accepts (pascalcase). It does not break anything as it only changes the printed line.

I see. Thanks for the explanation. The change LGTM! Thanks.

**Review by showuon — APPROVED** [review]

**Comment by showuon** [comment]
Failed tests are unrelated.

**Comment by showuon** [comment]
@tjouni , thanks for the contribution!

**Pull request merged**
