### PR TITLE
MINOR: Remove unnecessary batch iteration in FileRecords.downConvert

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8053 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8053 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8053 tests run, 5 skipped, 0 failed.
--none--

**Comment by ijuma** [comment]
@rajinisivaram, does this look OK?

**Review by rajinisivaram — APPROVED** [review]
LGTM

**Pull request closed without merging**
