### PR TITLE
KAFKA-5469: Created state changelog topics not logged correctly

### PR DESCRIPTION
**Pull request by ppatierno**
Fixed debug logging for the created state changelog topics
Added toString() for InternalTopicMetadata and InternalTopicConfig for above debug logging

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5453/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5468/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by ppatierno** [comment]
Retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5470/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5455/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ppatierno** [comment]
@dguy maybe you can take a look at this as well even related to log in the Streams library ?

**Comment by ppatierno** [comment]
@mjsax can you review this please ? I'd like to have it merged because I have some other fixes but want to avoid conflicts.

**Review by dguy — APPROVED** [review]
Thanks @ppatierno LGTM.
Sorry for the delay reviewing

**Comment by ppatierno** [comment]
@dguy thanks ! Now I can work on another proposal related to logging.

**Pull request closed without merging**
