### PR TITLE
MINOR: seal the HostedPartition enumeration

### PR DESCRIPTION
**Pull request by jsancio**
Makes HostedPartition a sealed trait and make all ofthe match cases
explicit

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jsancio** [comment]
cc @hachikuji @mumrah

**Review by hachikuji — APPROVED** [review]
Thanks, LGTM. I think it is probably better to keep HostedPartition sealed and avoid mixing it into the Partition object. Its purpose is really just for internal bookkeeping in `ReplicaManager`.

**Comment by jsancio** [comment]
retest this please

**Comment by jsancio** [comment]
JDK 8 and Scala 2.11 failed:
kafka.admin.ResetConsumerGroupOffsetTest > testResetOffsetsExistingTopic FAILED

**Review by soondenana — APPROVED** [review]
LGTM

**Comment by mumrah** [comment]
retest this please

**Comment by jsancio** [comment]
Thanks for the reviews and for merging!

**Pull request merged**
