### PR TITLE
KAFKA-15129;[2/N] Remove metrics in GroupMetadataManager when shutdown

### PR DESCRIPTION
**Pull request by hudeqi**
This pr is used to remove the metrics in GroupMetadataManager when shutdown.
This pr has passed the corresponding unit test, and it is part of [KAFKA-15129](https://issues.apache.org/jira/browse/KAFKA-15129).

A special advantage is that since the metric registered through metricsGroup is removed during shutdown, the original "recreateGauge" method (mentioned in https://github.com/apache/kafka/pull/3506#discussion_r128589927) is no longer needed.

### CODE REVIEW

**Comment by clolov** [comment]
In theory this change makes sense to me. As with the [1/N] one I would prefer if variable names start with a lowercase unless there is a good reason for them not to. I have reached out to @guozhangwang who was also wondering what the purpose of the recreateGauge method is (https://github.com/apache/kafka/pull/3506#discussion_r143319481). I thought that there is only ever one GroupMetadataManager so I do not understand the purpose of this method in the first place and I would like to get a confirmation before we remove it.

**Comment by dajac** [comment]
@clolov Constants (in the companion object) in Scala start with a capital letter in our code base.

**Comment by clolov** [comment]
Okay, that makes sense @dajac, do you happen to know (or are able to deduce) the answer to the other question about why we needed the recreateGauge method in the first place and is it safe to get rid of it now?

**Comment by dajac** [comment]
I was wondering if it is because we run multiple brokers in the same JVM in tests but I am not sure.

**Comment by clolov** [comment]
But if this is the case won't we run into the same problem for at least one other subset of metrics? Also if this is the case, that would mean that if we remove the method the tests running as part of the auto-build will start failing, no?

**Comment by dajac** [comment]
Found this: https://github.com/apache/kafka/pull/3506#discussion_r128589927.

**Comment by clolov** [comment]
Hudeqi mentioned this comment as well, but I still do not understand how this could happen - is it that we keep the same metric registry between individual unit tests? If this is the case, don't we have this problem for other groups of metrics as well?

**Comment by dajac** [comment]
Yeah, that seems to be a general issue with Yammer based metrics. It is not about individual unit tests. It is about integration tests that create multiple KafkaServers. In this case, the metric registry is shared by all instances:

```
    public final <T> Gauge<T> newGauge(String name, Gauge<T> metric, Map<String, String> tags) {
        return KafkaYammerMetrics.defaultRegistry().newGauge(metricName(name, tags), metric);
    }
```

That being said, it seem that `newGauge` here uses `getOrAdd` internally in the registry so it may be fine in the recent version of Yammer. It may be worth checking if this is always true (may depend on the version).

**Comment by hudeqi** [comment]
Combined with the explanation of https://github.com/apache/kafka/pull/3506#discussion_r128589927 and the results of my actual test, I think this is the case: All unit tests in `GroupMetadataManagerTest` involve many times of "new GroupMetadataManager" behavior , since "calls newGauge" is a global registry, it will affect the subsequent metric verification (`testMetrics()` method) in multiple unit tests.
I remember that I replaced "recreateGauge" directly before mentioning this PR. The unit test failed. Now because I added "removeMetrics()" to "groupMetadataManager.shutdown()"(also in@AfterEach), it will be the same as "recreateGauge" effect. @clolov @dajac

**Comment by hudeqi** [comment]
And this please @divijvaidya

**Comment by hudeqi** [comment]
Hello, please help to review this PR, we have doubts about removing the "recreateGauge" method, and the conversation here(https://github.com/apache/kafka/pull/3506#discussion_r128589927) is related to you. @cmccabe

**Pull request closed without merging**
