### PR TITLE
MINOR: Add KIP-584 to upgrade.html file

### PR DESCRIPTION
**Pull request by bbejeck**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
@kowshik here's the text we discussed offline yesterday for the upgrade section.

**Comment by bbejeck** [comment]
Once merged I'll cherry-pick this to 2.7

**Review by kowshik — APPROVED** [review]
LGTM

**Review by omkreddy — APPROVED** [review]
LGTM

**Review by abbccdda — APPROVED** [review]

**Comment by bbejeck** [comment]
only HTML so merging

**Comment by bbejeck** [comment]
Merged #9511 into trunk

**Comment by bbejeck** [comment]
cherry-picked to 2.7

**Pull request merged**
