### PR TITLE
KAFKA-9057: Backport KAFKA-8819 and KAFKA-8340 before 2.0

### PR DESCRIPTION
**Pull request by gharris1727**
* Includes fixes from PR-7315
* Omits ConfigProvider and Configurable test cases and plugins
* Replaces Java 8 language features with suitable Java 7 features

Signed-off-by: Greg Harris <gregh@confluent.io>

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rhauch** [comment]
Retest this, please.

**Comment by gharris1727** [comment]
This is now rebased on top of #7572.

**Comment by rhauch** [comment]
The JDK 8 and 10 had very few test failures, but all of them were unrelated to Connect.

**Review by rhauch — APPROVED** [review]
LGTM. Thanks for backporting, @gharris1727!

**Pull request merged**
