### PR TITLE
KAFKA-13441: improve upgrade doc

### PR DESCRIPTION
**Pull request by GuoPhilipse**
the following doc seems not that perfect, we can do a little fix.
image

### CODE REVIEW

**Comment by GuoPhilipse** [comment]
@dajac @hachikuji  Could you kindly help take a look ?

**Review by mimaison — APPROVED** [review]
LGTM, thanks for the PR

**Comment by mimaison** [comment]
For tiny fixes like this you don't need to open a JIRA, just submit a PR. Thanks

**Comment by GuoPhilipse** [comment]
> For tiny fixes like this you don't need to open a JIRA, just submit a PR. Thanks

Thanks @mimaison for your kind advice, will pay more attention in future.

**Pull request merged**
