### PR TITLE
KAFKA-4438; Cross compile to Scala 2.12.0

### PR DESCRIPTION
**Pull request by leachbj**
(cherry picked from commit f3aad3b54b7cbc5109d8398829a31100fd82b3e0)

### CODE REVIEW

**Comment by manub** [comment]
Hi! Is there any news on when 2.12 binaries will be available for the next patch version? There are a couple of libraries that depend on this. Thanks.

**Comment by leachbj** [comment]
Been pushing to get this included in the up coming 0.10.1.x release so we can publish it.  There's a concern that there is not sufficient testing of a 2.12 build of kakfa so it will likely be tagged as a beta release so any testing feedback of the trunk snapshots would help to ease that concern.

**Comment by guozhangwang** [comment]
Merged to 0.10.1, thanks @leachbj .

**Comment by guozhangwang** [comment]
Could you close this PR manually since apache bot wont close it if it is not against trunk?

**Comment by leachbj** [comment]
Closing as merged 👍 thanks @guozhangwang

**Comment by pjfanning** [comment]
Is there an ETA for a 0.10.1.x release that includes scala 2.12 compatible jars?

**Pull request closed without merging**
