### PR TITLE
KAFKA-3567 Add --security-protocol option to console consumer and producer

### PR DESCRIPTION
**Pull request by bharatviswa504**
Creating a new pull request, because original pull request #1408 has some issues.

### CODE REVIEW

**Comment by bharatviswa504** [comment]
@ijuma  This will be helpful when running with kerberos. At that time only security.protocol is needed. We can directly mention through command line option. Where as for other as you said, we need some more parameters. During other mechanisms like SSL, the user will have both options(command line and configuration file) for security protocol.

Ismael:
Thanks for the PR. Can you please explain how this helps? It seems to me that one always needs to provide additional configuration when using a security protocol that is not PLAINTEXT, so it seems easy enough to set the security protocol in the same config. But I may be missing something.

**Comment by harshach** [comment]
+1.

**Comment by bharatviswa504** [comment]
Updated the code so that user can give security-protocol option through config file / security-protocol option. Added a null check if it is not updated through configuration file, then take default/user provided through option. If user has given through security-protocol option also it will work fine, as the property will not be there it will return null and update the security.protcol to user value/default value.

**Comment by edoardocomar** [comment]
Hi, the console producer has these options:
--producer-property <producer_prop> A mechanism to pass user-defined 
properties in the form key=value to 
the producer. 
--producer.config <config file> Producer config properties file. Note 
that [producer-property] takes 
precedence over this config.
the console consumer has only
--consumer.config <config file> Consumer config properties file.
IMHO, it would make sense not to add a specific --security-protocol option to them,
but just add a 
--consumer-property <consumer_prop>
to the console consumer

**Comment by bharatviswa504** [comment]
Hi Edoardo,
I will look in to that property, and see I can update that way to be more generic.

But this change has been done for this reason "This will be helpful when running with kerberos. At that time only security.protocol is needed. We can directly mention through command line option."

**Comment by edoardocomar** [comment]
@bharatviswa504 I am not saying that the change isn't useful, but I don't think adding a command line option for every config property is a good idea. As the producer already has  CLI mechanism to pass in any property, the same should be done for the consumer

**Comment by ijuma** [comment]
As you said @bharatviswa504, this is only useful with `SASL_PLAINTEXT`, Kerberos mechanism and the default values for all Kerberos settings. `SSL`, `SASL_PLAINTEXT` with the `PLAIN` mechanism and `SASL_SSL` need other configurations anyway and `PLAINTEXT` is the default. As such, the use case seems a bit narrow and I'm not sure it's worth adding a new command-line switch to every tool (which we would want to do to be consistent).

**Comment by bharatviswa504** [comment]
Hi @ijuma It will provide an additional option to users who are running through console tools like console producer and console consumer. For now, I am leaving the jira status as patch available. Can you please let me know, how you want to proceed on this jira.

**Comment by bharatviswa504** [comment]
Hi @edoardocomar 
Ya got your point. I have seen the property which you have specified. Which will give more benefit through which we can override any consumer config property. I have created a jira KAFKA-3748 and will contribute to this.

**Comment by bharatviswa504** [comment]
@harshach Can you provide your suggestions on this.

**Comment by bharatviswa504** [comment]
@edoardocomar With producer-property can we override multiple producer configurations. Because When I am trying like below
bin/kafka-console-producer.sh --broker-list <server:port> --topic mytopic --producer-property security.protocol=SASL_PLAINTEXT fetch.min.bytes=2

only security.protocol is getting overriding, where as fetch .min.bytes is still showing as default value 1.

Because when arguments are parsed and used options.valuesOf(producerPropertyOpt) is returning only one value because of space fetch.min.bytes is not considered here.

  val extraProducerProps = CommandLineUtils.parseKeyValueArgs(options.valuesOf(producerPropertyOpt))

Is that it works for only one parameter or I am doing something not correctly? Can you please let me know your inputs.

**Comment by edoardocomar** [comment]
have you tried 
`--producer-property security.protocol=SASL_PLAINTEXT   --producer-property fetch.min.bytes=2`
?

**Comment by bharatviswa504** [comment]
Ya it worked. 
bin/kafka-console-consumer.sh  --new-consumer --zookeeper host:port --topic mytopic --from-beginning --bootstrap-server host:port --consumer-property security.protocol=SASL_PLAINTEXT --consumer.property fetch.min.bytes=2

**Comment by bharatviswa504** [comment]
@edoardocomar  @harshach  @ijuma I have updated the JIRA KAFKA-3748.  #1459 Can you review it.

**Comment by edoardocomar** [comment]
I think #1459 supersedes this one @bharatviswa504 right ?

**Comment by bharatviswa504** [comment]
@edoardocomar Yes, with this user can override any consumer property.

**Comment by hachikuji** [comment]
Closing since the problem was resolved by #1459.

**Pull request closed without merging**
