### PR TITLE
MINOR: Move queued.max.requests, queued.max.request.bytes to SocketSe…

### PR DESCRIPTION
**Pull request by mimaison**
…rverConfigs

These 2 configurations are only used in SocketServer

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
@mimaison It seems to me `NUM_NETWORK_THREADS_CONFIG` can be moved to `SocketServerConfigs` too. WDYT?

**Comment by mimaison** [comment]
You're right, we can also move `NUM_NETWORK_THREADS_CONFIG`. Done

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by mimaison** [comment]
Thanks for the review. None of the test failures are related, merging to trunk.

**Pull request merged**
