### PR TITLE
KAFKA-4555: Using Hamcrest for expressive intent in tests

### PR DESCRIPTION
**Pull request by rekhajoshm**
- Adding hamcrest in gradle files
- Using hamcrest in couple of tests - SourceTaskOffsetCommitterTest, MetadataTest

### CODE REVIEW

**Comment by rekhajoshm** [comment]
Not sure again whats up with jdk 7 on jenkins. Unrelated to this PR. Please review. @ijuma thanks

**Comment by rekhajoshm** [comment]
If you could also review this one @ijuma would be great.thanks!

**Comment by ijuma** [comment]
Thanks for the PR. Not sure about it though. It seems to conflate two separate notions: using Hamcrest and checking the message of the exception in a couple of tests.

**Comment by rekhajoshm** [comment]
Yes intentionally, to get it in and in the bloodstream @ijuma - What do you suggest? Please let me know. thanks!

**Comment by ewencp** [comment]
@rekhajoshm I think @ijuma is getting at the fact that Hamcrest is probably more useful for replacing some assertions that aren't related to messages -- probably the extent of asserting things about messages that I'd expect is to include important parameters like timeout values, not very specific strings for the messages.

A more realistic use that could be used as a test is to replace some `assertEquals`, `assertNull`, and `assertNotNull` with `assertThat`s using Hamcrest matchers. These are probably our most commonly used assertions. We obviously wouldn't want to convert everything, but they will validate the introduction of Hamcrest and allow us to start using other matchers as well.

**Comment by rekhajoshm** [comment]
thanks @ewencp for your comments. updated few more tests for illustration purpose.will create another PR for bulk changes on hamcrest eventually. the idea is once this PR is in, people can start using hamcrest in their tests as well.thanks, and a happy new year!

**Comment by ijuma** [comment]
Thanks @rekhajoshm. Unfortunately, these updates don't seem to improve the code. As far as I can tell, Hamcrest is beneficial when assertions like contains and such are needed. For simple `equals` and `null`, the simple methods are actually more concise.

**Comment by ijuma** [comment]
One other thing: I think it may be better to go directly to JUnit 5 (once we move to Java 8) instead of introducing Hamcrest right now.

**Pull request closed without merging**
