### PR TITLE
KAFKA-10180: Fix security_config caching.

### PR DESCRIPTION
**Pull request by nizhikov**
After 8b22b8159673bfe22d8ac5dcd4e4312d4f2c863c `security_config` properties are modified during `setup_node`: tls_version patched according to the node jdk version. But python `@property` decorator doesn't store property values and fresh instance of `SecurityConfig` created on each `kafka.security_config` call

This patch caches `SecurityConfig` instances so correct tls_version will be used during the test.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by nizhikov** [comment]
Hello, @rondagostino @ijuma 
This patch fix fails of the `benchmark_test.py` on jdk8.
You can find tests results in [jira ticket](https://issues.apache.org/jira/browse/KAFKA-10180?focusedCommentId=17144716&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17144716)

Please, take a look.

**Review by junrao — COMMENTED** [review]
@nizhikov : Thanks for the PR. Triggered a run of system tests. Waiting for the results.

**Comment by junrao** [comment]
Results of the system tests: Down to 13 failures and all benchmark related failures are gone. http://confluent-kafka-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2020-06-26--001.1593223563--nizhikov--KAFKA-10180--ba1dee62e/report.html

**Review by junrao — APPROVED** [review]
@nizhikov : Thanks for the PR. LGTM

**Comment by junrao** [comment]
@rhauch : This PR may fix a bunch of system tests in 2.6 too. Since 2.6.0 is code freeze now, I will let you decide if you want to merge this PR to 2.6.

**Comment by ijuma** [comment]
We need this in 2.6 to ensure we have passing system tests, so I cherry-picked it to that branch.

**Pull request merged**
