### PR TITLE
MINOR: adding global store must ensure unique names

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @enothereska @dguy @guozhangwang 

Found by chance: if `sourceName` and `processorName` are the same, we loose one of both in `nodeFactories`. (Guess, most people use DSL so nobody hit this up to now...)

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
retest this please

**Review by guozhangwang — APPROVED** [review]
Merged to trunk.

**Pull request closed without merging**
