### PR TITLE
KAFKA-6649: Should catch OutOfRangeException for ReplicaFetcherThread

### PR DESCRIPTION
**Pull request by huxihx**
https://issues.apache.org/jira/browse/KAFKA-6649

`AbstractFetcherThread.processFetchRequest` should catch OffsetOutOfRangeException lest the thread was forcibly stopped.

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by huxihx** [comment]
@rajinisivaram Could you please help review this minor change?

**Comment by rajinisivaram** [comment]
@huxihx Thanks for the PR. I am not very familiar with that class, perhaps @junrao could review this.

**Comment by hachikuji** [comment]
@huxihx One question to consider is whether this situation is still possible after KAFKA-3978 has been fixed.

**Comment by huxihx** [comment]
I am not sure if KAFKA-3978 strictly closed the door to throw this exception.  However, this patch works as a defensive strategy to make sure fetch thread will never unexpectedly be shut down due to this exception. Does it make any sense?

**Pull request closed without merging**
