### PR TITLE
MINOR: Change loggin for ignored maybeAddMetric from debug to trace

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by guozhangwang** [comment]
ping @xvrl @enothereska @dguy @mjsax

**Comment by enothereska** [comment]
LGTM

**Comment by xvrl** [comment]
:+1:

**Review by hachikuji — APPROVED** [review]
LGTM

**Comment by hachikuji** [comment]
Merged to trunk and 0.10.2 with a tiny tweak (parameterized log messages!).

**Pull request closed without merging**
