### PR TITLE
MINOR: Change version format in release notes python code

### PR DESCRIPTION
**Pull request by guozhangwang**
@ijuma @ewencp

### CODE REVIEW

**Comment by asfgit** [comment]
FAILURE
 No test results found.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8050 tests run, 5 skipped, 0 failed.
--none--

**Comment by asfgit** [comment]
SUCCESS 
 8050 tests run, 5 skipped, 0 failed.
--none--

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

**Comment by guozhangwang** [comment]
Merged to trunk and 1.0.

**Pull request closed without merging**
