### PR TITLE
KAFKA-17192 Fix MirrorMaker2 worker config does not pass config.provi…

### PR DESCRIPTION
**Pull request by k0b3rIT**
…ders value to connectors

Change-Id: I38185158116a43899497f66c1fb643677491b6eb

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by OmniaGM** [comment]
Thanks for the PR @k0b3rIT Is it possible to add test for this?

**Comment by k0b3rIT** [comment]
> Thanks for the PR @k0b3rIT Is it possible to add test for this?

Hmm, probably, I will look into it

**Comment by k0b3rIT** [comment]
> > Thanks for the PR @k0b3rIT Is it possible to add test for this?
> 
> Hmm, probably, I will look into it

Ok, I have extended the worker config test to assert on the config.providers value

**Comment by C0urante** [comment]
Hey @k0b3rIT, thanks for the PR! For this project we (the committers) handle backports automatically, so you can just file a single PR against trunk and state in the description that you'd like it to be backported (which we usually do by default, but it never hurts to give us a reminder).

I'm going to close this PR now so that it's clear to reviewers that they should focus on https://github.com/apache/kafka/pull/16678. If you have any issues with that please let me know!

**Comment by k0b3rIT** [comment]
> Hey @k0b3rIT, thanks for the PR! For this project we (the committers) handle backports automatically, so you can just file a single PR against trunk and state in the description that you'd like it to be backported (which we usually do by default, but it never hurts to give us a reminder).
> 
> I'm going to close this PR now so that it's clear to reviewers that they should focus on #16678. If you have any issues with that please let me know!

Good to know, thank you @OmniaGM @C0urante !

**Pull request closed without merging**
