### PR TITLE
KAFKA-9512: Backport Flaky Test LagFetchIntegrationTest.shouldFetchLagsDuringRestoration

### PR DESCRIPTION
**Pull request by vinothchandar**
- Added additional synchronization and increased timeouts to handle flakiness
- Added some pre-cautionary retries when trying to obtain lag map

*More detailed description of your change,
Backport of PR #8076 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@vinothchandar this PR is still in the `work in progress` state, is that ready for review and merge?

**Comment by vinothchandar** [comment]
Will remove the draft status in a little bit.. Running the test again on 2.5 branch many times to confirm flakiness is gone... It will be ready for review and merge then

**Comment by vinothchandar** [comment]
Ran for over 600 times without issues. @guozhangwang ready.

**Comment by guozhangwang** [comment]
Thanks @vinothchandar !!

**Pull request merged**
