### PR TITLE
MINOR: explain producer naming within Streams

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Follow up for `0.11` from #3378 

Call for merging @dguy

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5561/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5577/
Test PASSed (JDK 7 and Scala 2.11).

**Review by dguy — APPROVED** [review]
LGTM

**Pull request closed without merging**
