### PR TITLE
MINOR: add missing parameter `processing.guaratees` to Streams docs

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
\cc @bbejeck @vvcephei @joel-hamill

**Comment by mjsax** [comment]
Needs cherry-pick to `1.1`, `1.0`, and `0.11` branches.

**Review by guozhangwang — APPROVED** [review]

**Review by bbejeck — APPROVED** [review]
Thanks, @mjsax LGTM

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `1.1` and `1.0` -- no need to cherry-pick to `0.11` because this section does not exist there.

**Pull request merged**
