### PR TITLE
MINOR: Update Powermock to fix PushHttpMetricsReporterTest failures

### PR DESCRIPTION
**Pull request by ewencp**
Fixes test failures where old versions of Powermock don't handle nested classes accessing parent field members when using mockStatic.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ewencp** [comment]
Oops, missed the changes to WorkerTest that are required with the new PowerMock, updated to include those as well. These changes are already in on trunk and are only test changes, so should be safe.

**Review by ijuma — APPROVED** [review]
LGTM, if the tests pass.

**Comment by ewencp** [comment]
There were some streams test failures related to /tmp directories and an adminclient timeout failure (and JDK9 jenkins job just seems broken). These all seem unrelated, so trying to re-run to see if we can get a clean build.

**Comment by ijuma** [comment]
JDK 9 job doesn't work with branches older than 1.0.

**Comment by ewencp** [comment]
The JDK8 failure is an unrelated, already reported transient failure. Since we're clean on JDK7 now and JDK9 is expected not to work, I'll merge this now.

**Comment by ijuma** [comment]
I think we an close this since it's been merged.

**Pull request closed without merging**
