### PR TITLE
MINOR: (docs) add missing word

### PR DESCRIPTION
**Pull request by mihbor**

### CODE REVIEW

**Comment by ijuma** [comment]
cc @enothereska

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5381/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5396/
Test PASSed (JDK 7 and Scala 2.11).

**Review by enothereska — APPROVED** [review]

**Comment by guozhangwang** [comment]
Incorporated into latest trunk. Closing for now.

**Pull request closed without merging**
