### PR TITLE
MINOR: Fix static membership link in Streams upgrade notes

### PR DESCRIPTION
**Pull request by mimaison**
Fix broken link in Streams docs.
Same as https://github.com/apache/kafka/commit/11337afecb9a4fd0b993402c5195ef33dbd7a539#diff-8100f2416b657c1e1e4238dabf8a15e0

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
cc @omkreddy

**Comment by mimaison** [comment]
@mjsax Can you take a look?

**Review by omkreddy — APPROVED** [review]
@mimaison Thanks for the PR. LGTM.

**Review by vvcephei — APPROVED** [review]
Thanks for the fix, @mimaison !

**Comment by vvcephei** [comment]
The results from the failed build are gone by now, but this is a docs-only change.

**Comment by vvcephei** [comment]
@mimaison , could you also mirror the change in kafka-site? Thanks!

**Comment by omkreddy** [comment]
If we are updating kafka-site, Please also cherry-pick to 2.4.

**Comment by mimaison** [comment]
If you have time, I have a few more doc fixes:
- https://github.com/apache/kafka/pull/7509
- https://github.com/apache/kafka/pull/7508
- https://github.com/apache/kafka/pull/7473

**Comment by mimaison** [comment]
Once merged, I'm happy to open a PR to fix all these in kafka-site

**Comment by mimaison** [comment]
@vvcephei I've opened https://github.com/apache/kafka-site/pull/246 so you can go ahead and merge in 2.4 too

**Comment by mjsax** [comment]
Thanks for all the cleanup @mimaison!

**Pull request merged**
