### PR TITLE
MINOR: fix package name in core test

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
Change package name of `IntegrationTestUtils` ,`TransactionsWithMaxInFlightOneTest`, `ControllerContextTest` and `DefaultMessageFormatterTest` to `kafka.server` since we set the package name to `kafka.xxx` in all other classes.

*Summary of testing strategy (including rationale)*
QA

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rondagostino** [comment]
Thanks!   Something similar happens with `TransactionsWithMaxInFlightOneTest`, `ControllerContextTest`, and `DefaultMessageFormatterTest`.  Maybe fix those as well?

**Comment by dengziming** [comment]
@rondagostino Thank you for your suggestions, rechecked the other source files!

**Comment by dengziming** [comment]
cc @mumrah since `IntegrationTestUtils` is created by you. 😉

**Comment by dengziming** [comment]
@chia7712 ,Hello, PTAL, thank you.

**Comment by chia7712** [comment]
@dengziming thanks for your patch. Could you update description to summarize the changes (yours and @rondagostino suggested)? That would be a nice information and I can include it in commit message.

**Comment by dengziming** [comment]
@chia7712 , Thank you for your advice, I have updated the description of this PR.

**Review by chia7712 — APPROVED** [review]

**Pull request merged**
