### PR TITLE
KAFKA-9150; DescribeGroup uses member assignment as metadata

### PR DESCRIPTION
**Pull request by dajac**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
@hachikuji Here is the patch. @omkreddy this is a blocker for 2.4.

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the test case!

**Comment by hachikuji** [comment]
retest this please

**Comment by omkreddy** [comment]
Merging to trunk and 2.4

**Comment by dnwe** [comment]
@dajac / @omkreddy please can we backport this fix also to the 2.3 branch? I've opened a PR https://github.com/apache/kafka/pull/8888 with a cherry-picked fix

**Pull request closed without merging**
