### PR TITLE
MINOR: Mark AbstractLogCleanerIntegrationTest as an IntegrationTest

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@ijuma @dguy This cuts the aggregate test time for core's unit tests in half because one test derived from this class takes about 2.5 minutes.

**Comment by ijuma** [comment]
@ewencp, the reason @dguy didn't do this is the following JUnit issue that was apparently fixed in the unreleased JUnit 4.13:

https://github.com/junit-team/junit4/issues/751

Have you double-checked that we would not be affected by the above?

**Comment by ewencp** [comment]
Nope, still a problem, seems the tests get skipped with the annotation. Just did this as a side effect of noticing how slow the unit tests were...

Search doesn't seem to be showing up a corresponding JIRA to follow up on. Do we plan to follow up and is JUnit 4.13 likely to get released? Seems like it's been *quite* awhile since 4.12. Don't want to bother with follow up if it'll never be released.

**Comment by ijuma** [comment]
As you say, it doesn't look good for 4.13. It seems like we'll be stuck with this limitation until we migrate to Java 8 and JUnit 5 in 2027. ;)

**Comment by ewencp** [comment]
Guess I'll close for now since this doesn't work. I'd file a JIRA for this so we don't forget, but since we can't even associate it with a candidate future release number, we'll just have to hope it bothers someone in the future and they think to do this.

**Pull request closed without merging**
