### PR TITLE
KAFKA-6126: Remove unnecessary topics created check

### PR DESCRIPTION
**Pull request by mjsax**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Triggered system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1192/

**Comment by mjsax** [comment]
System test failed with `org.apache.kafka.common.errors.TimeoutException: Expiring 278 record(s) for data-1: 80070 ms has passed since batch creation plus linger time`

Retriggered: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1193/

**Comment by mjsax** [comment]
Rebased to get fix for unstable system tests.

Retriggered system test: Retriggered: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/1203/

**Comment by mjsax** [comment]
Call for review @guozhangwang @bbejeck @dguy

**Comment by dguy** [comment]
@mjsax, is there some place else we would need to check the topics have been created? In what ways will we fail if they don't exist?

**Comment by bbejeck** [comment]
I have one thought (it's rather raw haven't put in the time to fully work out all details)  

What if we change `makeReady` and place each topic request in a separate thread (using an `Executor` to cap the number of running threads at any point) and return a `List<Future>` that can be queried later on to ensure topics are created, but not holding up progress of rebalancing.

**Comment by guozhangwang** [comment]
The point is that today we already handle topic not available in the stream thread main loop already, that if we get an exception indicating the topic-partition is not available yet, the stream thread will fall back to the main loop and retry in the next iteration. This is done as in 0.11.0.1 / 1.0.0, and hence this additional check does not bring in any more benefits.

**Review by bbejeck — APPROVED** [review]
Thanks @mjsax , LGTM

**Comment by guozhangwang** [comment]
A few comments:

1. This function in `InternalTopicManager`

```
    public Map<String, Integer> getNumPartitions(final Set<String> topics) {
        return getNumPartitions(topics, false);
    }
```

can be removed now?

2. `log.debug("Completed validating internal topics in partition assignor.");` should we update the log entry?

**Comment by mjsax** [comment]
About the log statement: We still verify if existing partition count matches expected and fail otherwise -- guess, the log entry is still ok.

**Comment by mjsax** [comment]
Rebased and updated this.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk.

**Pull request closed without merging**
