### PR TITLE
Replace mockito-core by mockito-scala

### PR DESCRIPTION
**Pull request by ultrasecreth**
Mockito now has a Scala version that improves the API and solves longstanding issues, I've made the required changes to use the scala version and new API

### CODE REVIEW

**Comment by ultrasecreth** [comment]
Failed test unrelated and flaky, not sure what to do there...

**Comment by ijuma** [comment]
Thanks for the PR. It doesn't look like we can make this change since the mockito version was updated to mockito 1. Also, the benefit of using mockito-scala seems minor compared to having an additional way to write tests that is different from the Java tests.

**Comment by ultrasecreth** [comment]
@ijuma The mockito-scala version is independent, so a version 1.x.x is the most recent (latest is 1.2.0)
You can still use the traditional mockito syntax if you don't wanna use the new syntax to keeps tests consistent with the Java ones

I think you'll find out it comes quite handy if you ever have to mock stuff that has varargs, byname params, uses value classes or any of the other scala features that the java version of mockito does not support

**Comment by ijuma** [comment]
That's a fair point about Scala specific features. I'd add the dependency when the need for that arises.

**Comment by ultrasecreth** [comment]
Fair enough

**Pull request closed without merging**
