### PR TITLE
KAFKA-3208: Default security.inter.broker.protocol based on configure…

### PR DESCRIPTION
**Pull request by granthenke**
…d advertised.listeners

### CODE REVIEW

**Comment by ijuma** [comment]
Not sure about this one. It's nice that we are trying to do the right thing automatically, but is it intuitive? Particularly for the case where there are multiple listeners.

**Comment by granthenke** [comment]
@ijuma The thought here is to have a good/safe default configuration based on the "required" parameters. If a user configures SASL, SSL or both and does not change security.inter.broker.protocol from the default. Either they are insecure or their broker won't start. KAFKA-3194 made it a bit safer and the messaging more clear. But I would prefer to prevent the issue in the first place. 

I guess a good question is how often do users run with multiple listeners configured?

**Comment by ijuma** [comment]
> If a user configures SASL, SSL or both and does not change security.inter.broker.protocol from the default. Either they are insecure or their broker won't start.

It's just the latter right? The former would only happen if a PLAINTEXT port was also configured, which implies that the broker is accepting unsecured connections. Also, the PLAINTEXT port may even be selected if it's the first advertised.listener.

> I guess a good question is how often do users run with multiple listeners configured?

Yes. And whether forcing the users to make the decision explicitly (a failed broker start with a good error message) or if we can choose a good enough default so that things just work.

**Comment by granthenke** [comment]
@ijuma Right. We need to decide which approach to take. Setting a valid (perhaps not optimal) protocol as a default or failing and forcing the user to choose.

Part of my motivation is to minimize the parameters that need to be set/managed in normal deployments.

**Comment by gwenshap** [comment]
I agree with @ijuma that the new behavior is a bit too "automagical" and possibly un-intuitive. This change also means that the order of listeners in the configuration is suddenly meaningful and must be consistent across brokers or weird stuff will happen. 

I think the current behavior (with your recent patch) of either choosing plaintext or failing with validation is better.

**Comment by granthenke** [comment]
@gwenshap @ijuma I agree, depending on the order probably isn't great. I will close this.

**Pull request closed without merging**
