### PR TITLE
MINOR: Fix typo in Utils#toPositive

### PR DESCRIPTION
**Pull request by hongshaoyang**
### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by hongshaoyang** [comment]
Ping @guozhangwang 

Original typo was added in https://github.com/apache/kafka/commit/3a9f4b833bb7e86dc759361c33f4321ab043db05

**Review by showuon — APPROVED** [review]
LGTM

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
@hongshaoyang Thanks for your patch!

**Pull request merged**
