### PR TITLE
MINOR: Call logSegments.toBuffer only when required

### PR DESCRIPTION
**Pull request by kowshik**
I've improved `Log.fetchOffsetByTimestamp` implementation slightly, such that we only copy the `segments` map values when `targetTimestamp` is neither `EARLIEST_TIMESTAMP` nor `LATEST_TIMESTAMP`. Previously, it was cached outside the `if` block, and that seemed a little bit of an overkill to me.

**Test plan:**
Rely on existing tests.

### CODE REVIEW

**Comment by kowshik** [comment]
cc @junrao for review

**Comment by chia7712** [comment]
```logSegments``` is thread-safe so is the copy necessary in this case?

**Comment by kowshik** [comment]
@chia7712: Going by the documentation, the results of the iteration are undefined if the map is modified while an iteration over the collection is in progress. IIUC we would end up iterating the values in the `segments` map via the line: `val targetSeg = segmentsCopy.find(_.largestTimestamp >= targetTimestamp)`.

Please refer to the code pointers in the following order:

https://github.com/confluentinc/ce-kafka/blob/master/core/src/main/scala/kafka/log/Log.scala#L318
https://github.com/confluentinc/ce-kafka/blob/master/core/src/main/scala/kafka/log/Log.scala#L2420
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentNavigableMap.html
Particularly this: https://docs.oracle.com/javase/8/docs/api/java/util/SortedMap.html#values--
> Collection<V> values()
Returns a Collection view of the values contained in this map. The collection's iterator returns the values in ascending order of the corresponding keys. The collection is backed by the map, so changes to the map are reflected in the collection, and vice-versa. If the map is modified while an iteration over the collection is in progress (except through the iterator's own remove operation), the results of the iteration are undefined. The collection supports element removal, which removes the corresponding mapping from the map, via the Iterator.remove, Collection.remove, removeAll, retainAll and clear operations. It does not support the add or addAll operations.

So... to avoid the above thread safety issue, prior to the iteration, a copy of the segments map values is made.

Please go ahead and merge this PR if it looks good to you.

**Comment by chia7712** [comment]
@kowshik Thanks for your response. This patch is LGTM and I just want to clarify the usage of ```segmentsCopy```

The instance of ```segmentsCopy``` is ```ConcurrentSkipListMap``` so the return ```Iterable``` should be thread safe (see https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentSkipListMap.html#values--).

**Comment by kowshik** [comment]
@chia7712 Good point. I understand now that iteration over `ConcurrentSkipListMap.values()` is weakly consistent, which seems good enough for this case. But since my intention with this patch was to not attempt to change the iteration behavior, but rather just the caching part, I'm hoping the PR in its existing form is acceptable. Please let me know how you feel.

**Comment by chia7712** [comment]
> But since my intention with this patch was to not change the iteration behavior, I'm hoping the PR in its existing form is acceptable.

make sense to me :)

**Review by chia7712 — APPROVED** [review]

**Review by ijuma — APPROVED** [review]
Thanks, LGTM. I think the PR title is a bit confusing. I would write something like "Call `logSegments.toBuffer` only when required" since caching tends to imply more than just allocating to a local val.

**Review by satishd — APPROVED** [review]
+1 LGTM

**Comment by kowshik** [comment]
@ijuma Good point, I've fixed the PR title now.

**Pull request merged**
