### PR TITLE
MINOR: remove unused import

### PR DESCRIPTION
**Pull request by ableegoldman**
Remove unused import that's slipping past checkstyle somehow

### CODE REVIEW

**Comment by ableegoldman** [comment]
@cpettitt-confluent @guozhangwang @bbejeck @mjsax

**Review by cpettitt-confluent — APPROVED** [review]
LGTM. Thanks!

**Review by mjsax — APPROVED** [review]
LGTM -- assuming Jenkins passes.

**Comment by ableegoldman** [comment]
Both Java 11 builds passed, Java 8 failed but results already cleaned up

retest this please

**Comment by bbejeck** [comment]
Merged #7345 into trunk.

**Pull request merged**
