### PR TITLE
MINOR: Fix grammar

### PR DESCRIPTION
**Pull request by mihbor**

### CODE REVIEW

**Comment by mjsax** [comment]
Can you piggy back this to #3224 ?

**Comment by mihbor** [comment]
I'd rather not, they are not related.

**Comment by ijuma** [comment]
@mihbor, thanks for this and other PRs. Keep in mind that there is overhead for a committer to review and merge each PR. So, one PR with a few documentation improvements is better than 5 small documentation PRs where some of the PRs change a single line.

**Comment by mjsax** [comment]
@mihbor As we are close to the release, it might be nice to get those fixes for the docs merged. It's find to put all those PRs together into a single PR. Could you do one single PR for all of those and close all other duplicate PRs? Thx.

**Comment by mihbor** [comment]
I'm afraid I have no interest in spending any more time on these, feel free to close if they're not worth merging as they are.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5627/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5641/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by guozhangwang** [comment]
Incorporated to trunk already, closing.

**Pull request closed without merging**
