### PR TITLE
KAFKA-2691: Improve handling of authorization failure during metadata refresh

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for this Jason. I had a quick look via my phone and I noticed that there are still two TODOs on the integration test. Worth checking (if you haven't) if they can be addressed. And the package name on the integration test has been wrong since its introduction, maybe you can fix it.

**Comment by hachikuji** [comment]
@ijuma Still working on it. Just wanted to get the initial PR out there.

**Comment by ijuma** [comment]
Great.

**Comment by hachikuji** [comment]
@junrao @guozhangwang (and @ijuma if he has time): Ping for review.

**Comment by harshach** [comment]
@Parth-Brahmbhatt can you review this as well.

**Comment by junrao** [comment]
Thanks for the patch. Looks good overall. Just a few minor comments. In AuthorizerIntegrationTest, could we add a couple of more tests.
1. Producer.send(() should get an AuthorizationException on an existing topic without the describe permission. This can be achieved by setting up an ACL on the topic to a user other than anonymous.
2. Consumer.poll() should get an AuthorizationException on an existing topic without the describe permission. This can be achieved by setting up an ACL on the topic to a user other than anonymous.
3. In testProduceNeedsAuthorization(), could we just catch AuthorizationException instead of ApiException? Then we probably don't need to check the message string.

**Comment by hachikuji** [comment]
@junrao Thanks for the review. I'm also looking at offset commits, which currently aren't covered. They're an interesting case because a commit can be rejected either because the user is not authorized to the group or to the topic. But since we only have one generic authorization error, clients cannot tell which case actually happened. This is probably not a major problem (more of an annoyance really), but I wonder if we should have different error codes for each resource type?

**Comment by guozhangwang** [comment]
Thanks for the patch. I have two general thoughts about the public APIs of `KafkaConsumer`:

1) in `poll` function, we could first document there are two types of general exceptions: ApiException (only for "non-retriable" error codes returned from brokers) and WakeupException. Then we could list all possible ApiExceptions and state that user only need to special handle different types ApiExceptions when necessary. This is just to clear the confusion that we expose all kinds of failures to users.

Also rep. to the above comment, to simplify the exception list, I would actually prefer only having an `AuthorizationException` and incorporate the authorization error scope (be it topic, group, etc) in the error message. The motivation is that since this exception is considered FATAL and cannot be resolved programmatically even at the app level, users would then not care about the scope in the code but just want to see the error message thrown upon encountering this and have ops resolution then.

2) in `commit` function, incorporate possible exceptions into a single `CommitFailedException` (this can be thrown directly in commitSync, or indirectly from commitAsync's callback) with different error types encoded in the error message. My motivation is the same as above.

**Comment by hachikuji** [comment]
@guozhangwang TopicAuthorizationException and GroupAuthorizationException extend from AuthorizationException, so we can still list just AuthorizationException on the poll() API. I think it's better having the explicit exceptions in particular because it is useful in testing. Otherwise you have to resort to hacky error message assertions.

**Comment by junrao** [comment]
@hachikuji : For offset commit, for now, perhaps we can just return the same error code and on the client side, put in a more general error message in AuthorizationException (sth like the client may not have the read permission on either the topic or the consumer group).

**Comment by hachikuji** [comment]
@junrao As discussed, I added a different error code for each resource type. This makes testing and exception handling easier for the couple ambiguous cases. It would be nice to get some feedback from @harshach on this.

**Comment by junrao** [comment]
Thanks for the patch. LGTM. Just a minor comment.

**Comment by hachikuji** [comment]
@junrao Rebased against trunk.

**Pull request closed without merging**
