### PR TITLE
MINOR: Update dependencies for Kafka 2.4

### PR DESCRIPTION
**Pull request by ijuma**
Scala 2.12.9 brings another 5% ~ 10% improvement in compiler performance,
improved compatibility with JDK 11/12/13, and experimental infrastructure for
build pipelining.

zstd update includes performance improvements, among which the
primary improvement is that decompression is ~7% faster.

Level | v1.4.0 | v1.4.1 | Delta
-- | -- | -- | --
1 | 1390 MB/s | 1453 MB/s | +4.5%
3 | 1208 MB/s | 1301 MB/s | +7.6%
5 | 1129 MB/s | 1233 MB/s | +9.2%
7 | 1224 MB/s | 1347 MB/s | +10.0%
16 | 1278 MB/s | 1430 MB/s | +11.8%

Jetty 9.4.19 includes a number of bug fixes:
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.19.v20190610

Mockito 3.0.0 switched the Java requirement from 7 to 8.

Several updates to owaspDepCheckPlugin (4.0.2 -> 5.2.1).

The rest are patch updates.

# Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Passed: JDK 11 with Scala 2.13 and JDK 8 with Scala 2.11. JDK 11 with Scala 2.12 had flaky unrelated failures:

> kafka.api.AdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevels
> kafka.api.AdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevelsCanResetLoggerToCurrentRoot
> kafka.api.GroupEndToEndAuthorizationTest.testNoDescribeProduceOrConsumeWithoutTopicDescribeAcl
> kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevels
> kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevelsCanResetLoggerToCurrentRoot
>

**Comment by ijuma** [comment]
Rebased and triggered a new build.

**Comment by ijuma** [comment]
Retest this please

**Comment by ijuma** [comment]
Retest this please.

**Comment by ijuma** [comment]
Retest this please.

**Review by rajinisivaram — APPROVED** [review]
@ijuma Thanks for the PR, LGTM

**Comment by ijuma** [comment]
Test failures are unrelated and happening in master:

> kafka.api.AdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevels
> kafka.api.AdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevelsCanResetLoggerToCurrentRoot
> kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevels
> kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevelsDoesNotWorkWithInvalidConfigs
> kafka.api.SaslSslAdminClientIntegrationTest.testIncrementalAlterConfigsForLog4jLogLevelsCanResetLoggerToCurrentRoot

One of the builds timed out. The Scala 2.12 build passed, which is the most important one given the bump in Scala 2.12 version, passed.

Merging to master.

**Pull request merged**
