### PR TITLE
KAFKA-5790: SocketServer.processNewResponses should not skip a response if exception is thrown

### PR DESCRIPTION
**Pull request by ijuma**
Not sure why the try/finally was there in the first place, but it seems to cause
the next response after an exception to be skipped.

This could be a source of correlation id errors we've seen before as well.

### CODE REVIEW

**Review by dguy — APPROVED** [review]
Thanks @ijuma, LGTM

**Comment by ijuma** [comment]
Maybe the intent was to continue processing if there is an exception (i.e. a catch was intended). @junrao and @rajinisivaram, thoughts?

**Comment by hachikuji** [comment]
@ijuma Looking through the code, other than illegal state errors, it doesn't seem like there are many errors that can actually happen here. I think I would suggest that if we hit an unexpected error while handling the `SendAction`, then we should just close the connection and continue processing. Not so sure about the `CloseAction` case though.

**Comment by junrao** [comment]
@ijuma : Thanks for catching this. I agree that we want to finish processing all responses in the queue in the same loop. Otherwise, the remaining responses in the queue may take up to the 300ms poll timeout to be processed again. So, if we hit any unexpected exception, we probably want to close the socket and loop over to the next response in the queue.

**Comment by ijuma** [comment]
Thanks for the feedback all, we'll do all the changes in #3548 so closing this.

**Pull request closed without merging**
