### PR TITLE
Backport kafka admin client bug

### PR DESCRIPTION
**Pull request by jlprat**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jlprat** [comment]
Hi @mimaison and @chia7712. The backport fixing the bug you encountered in RC0, in case you want to review.

**Comment by mimaison** [comment]
Thanks @jlprat !
Instead of putting both commits in a single PR, I'd prefer if you cherry-picked both on 3.8 directly (IIRC both cherry-pick cleanly and you can still use this PR to ensure the tests pass). Otherwise they'll get squashed and it will be harder to reason what commits this contains in the future.

**Comment by jlprat** [comment]
OK, I'll do this @mimaison . I'll use this PR just to prove the CI and then cherry-pick them individually on 3.8

**Comment by jlprat** [comment]
Test failures unrelated. Cherry-picking individually to `3.8`.

**Pull request closed without merging**
