### PR TITLE
MINOR: remove unused eosEnabled field from ProcessorStateManager

### PR DESCRIPTION
**Pull request by dguy**
remove unused eosEnabled field from ProcessorStateManager

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang @ijuma

**Comment by guozhangwang** [comment]
LGTM. Please feel free to merge.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5848/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5835/
Test PASSed (JDK 8 and Scala 2.12).

**Pull request closed without merging**
