### PR TITLE
KAFKA-17718: Build code with java 17 instead of 21

### PR DESCRIPTION
**Pull request by mingyen066**
Build code with Java 17 instead of 21 to avoid errors caused by module `spotless` not supporting Java 21.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mumrah** [comment]
@chia7712 Since we have dropped Java 8 in #17350, can we now upgrade the spotless plugin? It seems better to do that than mess with the JDK build versions temporarily.

**Comment by chia7712** [comment]
> can we now upgrade the spotless plugin? It seems better to do that than mess with the JDK build versions temporarily.

Gradle downloads plugin dependencies even if the plugin isn't applied, so users will encounter build errors when using JDK 8 if we update the spotless plugin.

I think it is time to start to drop JDK 8 in order to unblock those upgrades.

**Comment by chia7712** [comment]
Let us try https://issues.apache.org/jira/browse/KAFKA-16896 before merging this PR

**Comment by chia7712** [comment]
close this PR as #17423 works well

**Pull request closed without merging**
