### PR TITLE
MINOR: Change toArray usage for Increase efficiency

### PR DESCRIPTION
**Pull request by APaMio**
Change the toArray usage from toArray(new 'SomeType'[Sometype.size()]) to toArray(new 'Sometype'[0])

@chia7712

### CODE REVIEW

**Comment by chia7712** [comment]
@APaMio Thanks for your patch. Could you share the reference about the benefit of this change? It would be useful to the readers/reviewers.

**Comment by ijuma** [comment]
I think this is based on https://shipilev.net/blog/2016/arrays-wisdom-ancients/

**Comment by chia7712** [comment]
> I think this is based on https://shipilev.net/blog/2016/arrays-wisdom-ancients/

@ijuma Thanks for this sharing. That is good to know :)

@APaMio There are some similar issues. Could you fix them also? 
1. https://github.com/apache/kafka/blob/trunk/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/RestServer.java#L303
1. https://github.com/apache/kafka/blob/trunk/tools/src/main/java/org/apache/kafka/trogdor/fault/DegradedNetworkFaultWorker.java#L112
1. https://github.com/apache/kafka/blob/trunk/tools/src/main/java/org/apache/kafka/trogdor/fault/DegradedNetworkFaultWorker.java#L118
1. https://github.com/apache/kafka/blob/trunk/tools/src/main/java/org/apache/kafka/trogdor/fault/DegradedNetworkFaultWorker.java#L124

**Comment by APaMio** [comment]
@chia7712 Of course. I'll fix it

**Comment by chia7712** [comment]
@APaMio Could you rebase code to include recently big commits?

**Comment by APaMio** [comment]
@chia7712  Done.

**Review by chia7712 — APPROVED** [review]
@APaMio Thanks for your patch. Will commit it tomorrow if there is no objection.

**Comment by APaMio** [comment]
Roger ,Thanks.

**Comment by APaMio** [comment]
Roger that, Thanks.

**Comment by chia7712** [comment]
@APaMio Thanks for your contribution!

**Pull request merged**
