### PR TITLE
MINOR: Removed unused import

### PR DESCRIPTION
**Pull request by bbejeck**
Fixes a checkstyle error than snuck in with a docs HTML cherry-pick  

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @guozhangwang @mjsax

**Review by mjsax — APPROVED** [review]
LGTM. Thanks for the quick fix @bbejeck

**Comment by bbejeck** [comment]
retest this please

**Comment by bbejeck** [comment]
Java 7 and Java 10 passed, Java 8 failed

retest this please

**Comment by bbejeck** [comment]
Merged #6587 into 1.1

**Pull request merged**
