### PR TITLE
KAFKA-4459: Run rat checks in Jenkins script

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@ijuma Not actually sure why this wasn't running before, but it's pretty obvious now that we have a`jenkins.sh` script that doesn't invoke the right targets... Previous issues with `.git` don't seem relevant since we must be running in the root repo directory for the jenkins scripts to work, but we'll see based on the jenkins output from this test.

Looks like this can be backported to 0.10.2 and higher since that's when the `jenkins.sh` script was introduced.

**Review by ijuma — APPROVED** [review]
LGTM, thanks. We should update the title to reference KAFKA-4459, I think.

**Comment by ijuma** [comment]
(the script was introduced during the 0.11.0.0 cycle, but we backported it to 0.10.2.0 as well)

**Comment by ewencp** [comment]
Oops, KAFKA-4459 is exactly what I meant and is in the branch name, just messed it up during commit. Fixed. Seems like we're good as long as the rat checks show up in the Jenkins builds.

**Pull request closed without merging**
