### PR TITLE
KAFKA-10371; Partition reassignments can result in crashed ReplicaFetcherThreads

### PR DESCRIPTION
**Pull request by dajac**
https://github.com/apache/kafka/pull/8672 introduced a bug leading to crashing the replica fetcher threads. The issue is that https://github.com/apache/kafka/pull/8672 deletes the Partitions prior to stopping the replica fetchers. As the replica fetchers relies access the Partition in the ReplicaManager, they crash with a NotLeaderOrFollowerException that is not handled.

This PR reverts the code to the original ordering to avoid this issue.

The regression has been caught by our system test: `kafkatest.tests.core.reassign_partitions_test`.

I have not managed to reproduce the issue in a unit test without reimplementing the entire system test in Java. I am not sure that makes sense as we already have it in Python.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by hachikuji — APPROVED** [review]
LGTM. Let's create a JIRA to add concurrency tests so we can try to avoid this kind of problem in the future.

**Comment by hachikuji** [comment]
ok to test

**Comment by dajac** [comment]
Jira: https://issues.apache.org/jira/browse/KAFKA-10374

**Review by soondenana — APPROVED** [review]
LGTM

Thanks for fixing this.

**Comment by soondenana** [comment]
I can confirm that this fixes the issue. I ran system test 18 times and didn't hit this issue. Without this fix, when I run the system test 10 times I hit the issue 2 times.

**Pull request merged**
