### PR TITLE
KAFKA-15155: Follow PEP 8 best practice in Python to check if a container is empty

### PR DESCRIPTION
**Pull request by cxorm**
Jira: [KAFKA-15155](https://issues.apache.org/jira/browse/KAFKA-15155)
Check if a container is empty in `release.py` by following PEP 8 best practice.

I don't find any previous tests about this script,
but I'm willing to add one if we need it.

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cxorm** [comment]
Hi @divijvaidya ,
I also find the same issues in other Python files (such as `kafka-merge-pr.py` and `reviewers.py`).
Do you think we should fix it in this PR or file another Jira for them?

**Comment by divijvaidya** [comment]
Please feel to fix it in this PR.

**Comment by cxorm** [comment]
> Please feel to fix it in this PR.

Fixed all places related to this Jira, 
Would you be so kind as to take a look at this PR if you have time? @divijvaidya

**Review by divijvaidya — APPROVED** [review]
Thank you for making this change! Looks good to me.

**Comment by divijvaidya** [comment]
Test failures are unrelated to python code change in this PR. Merging this in.

**Pull request merged**
