### PR TITLE
KAFKA-5169: KafkaConsumer.close should be idempotent

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by mjsax** [comment]
@ijuma Should we keep retesting? I did 3 runs already, and got only one green build (out of 9). It's the known test flakiness.

**Comment by ijuma** [comment]
Retest this please

**Pull request closed without merging**
