### PR TITLE
MINOR: Bump system test version from 2.2.0 to 2.2.1

### PR DESCRIPTION
**Pull request by mjsax**
*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
This PR is blocked by #6597 -- will run system tests after merged and this PR is rebased (opened this PR early for tracking purpose).

\cc @hachikuji @rhauch Do we need to update anything for core or connect?

**Review by abbccdda — APPROVED** [review]
LGTM!

**Comment by ijuma** [comment]
@mjsax it looks like you didn't update the vagrant file.

**Comment by mjsax** [comment]
Updated vagrant file.

**Comment by mjsax** [comment]
Triggered system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2739/

**Comment by mjsax** [comment]
Java11 passed. Java8 build not available any longer. System test passed.

Retest this please.

Call for review @guozhangwang @bbejeck @vvcephei @ableegoldman @cadonna

**Comment by mjsax** [comment]
Rebased this to resolve merge conflicts.

Retriggered system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2795/

Call for review @guozhangwang @bbejeck

**Comment by bbejeck** [comment]
system test failed due to environmental issues, kicked off another one https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2796/

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
java 11 scala 2.13 failed with 
```
org.apache.kafka.connect.integration.ConnectWorkerIntegrationTest.testAddAndRemoveWorker
org.apache.kafka.connect.integration.ExampleConnectIntegrationTest.testSourceConnector
```
java 8, java 11 scala 2.12 passed

retest this please

**Comment by mjsax** [comment]
All 3 builds failed -- test result are not available any longer.

Retest this please.

**Comment by mjsax** [comment]
Rebased to latest `trunk` (hope this makes the test more stable). Also triggered system tests: minor-add-221-to-system-tests

**Comment by mjsax** [comment]
All three runs failed -- results are not available any longer. Retest this please.

**Comment by bbejeck** [comment]
Java 11/2.12 time out Java 11 Scala/2.13  and Java 8 passed

retest this please

**Comment by mjsax** [comment]
Previous system test results are not available any longer. Retriggered: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2844/

Java 8 passed. Retest this please.

**Comment by mjsax** [comment]
Jenkins passed. System test failed (forgot to delete one line in a setup script for system test...)

**Comment by mjsax** [comment]
Retriggered system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2845/

**Comment by mjsax** [comment]
System test failed for test including `0.10.1` and `0.10.0` versions. I believe it because of the issue fixed via https://github.com/apache/kafka/pull/7118/

Rebased to get the fix into this PR. Retriggered system tests: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2846/

**Comment by mjsax** [comment]
Unrelated system test failures for test `kafkatest.tests.client.quota_test.QuotaTest.test_quota` with error `Jmx tool took too long to start`.

Re-triggered: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2851/

**Comment by mjsax** [comment]
@ijuma Seems like `QuotaTest` is broken atm. Can we merge this PR without getting a green system test build? Or do we need to wait for a fix for `QuotaTest` ?

**Comment by mjsax** [comment]
Java 11 / 2.12 passed. Test results for others not available any longer. I would just merge as-is if there are no objections.

**Pull request merged**
