### PR TITLE
KAFKA-3614: Consolidate duplicate code in KGroupedTableImpl

### PR DESCRIPTION
**Pull request by miguno**
Feel free to review @guozhangwang @enothereska @mjsax .

### CODE REVIEW

**Comment by enothereska** [comment]
Code LGTM. Tests also ran fine (Jenkinds failure below is unrelated). Thanks.

**Comment by mjsax** [comment]
LGTM. Why does Travis show "All Checks have failed", but "Details" show "Test Result (no failures)" ?

**Comment by guozhangwang** [comment]
@mjsax I'm always wondering the same :) Does Flink Jenkins job has different displays? Maybe that is something we can improve on the configuration.

**Comment by mjsax** [comment]
@guozhangwang Flink uses Travis, not Jenkins. It works without problems there.

**Pull request closed without merging**
