### PR TITLE
MINOR: add 2 failure test methods

### PR DESCRIPTION
**Pull request by enothereska**
Refactored test code. Added 2 methods for `manual` testing (not for nightly runs).

### CODE REVIEW

**Comment by guozhangwang** [comment]
@enothereska is this still valid?

**Comment by enothereska** [comment]
@guozhangwang yes, but not high priority, I'll ping you

**Comment by guozhangwang** [comment]
Still valid? @enothereska

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5772/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5786/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by enothereska** [comment]
@guozhangwang yes but haven't had time to clean up and it has slipped :(

**Pull request closed without merging**
