### PR TITLE
Kafka-5205: Removed use of keySerde in CachingSessionStore.

### PR DESCRIPTION
**Pull request by ghost**
CachingSessionStore wasn't properly using the default keySerde if no Serde was supplied. I saw the below error in the logs for one of my test cases.

ERROR stream-thread [cogroup-integration-test-3-5570fe48-d2a3-4271-80b1-81962295553d-StreamThread-6] Streams application error during processing:  (org.apache.kafka.streams.processor.internals.StreamThread:335)
java.lang.NullPointerException
	at org.apache.kafka.streams.state.internals.CachingSessionStore.findSessions(CachingSessionStore.java:93)
	at org.apache.kafka.streams.kstream.internals.KStreamSessionWindowAggregate$KStreamSessionWindowAggregateProcessor.process(KStreamSessionWindowAggregate.java:94)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:47)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:187)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:133)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:82)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:69)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:206)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndPunctuate(StreamThread.java:657)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:728)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:327)

### CODE REVIEW

**Comment by ghost** [comment]
@dguy I assume you will be assigned to review this because it deals with state stores. I think it is pretty straight forward and could be considered a bug so I was hoping to draw more attention to this as its been a couple days. Let me know if I should create a jira for this.

**Review by dguy — COMMENTED** [review]
@KyleWinkelman nice catch. Sorry for taking so long to review it. Looks like you need to rebase, but otherwise LGTM

**Comment by dguy** [comment]
@KyleWinkelman can you rebase this? @guozhangwang can you please review and merge?

**Comment by ghost** [comment]
@dguy I have rebased. Thanks for the review.

**Comment by guozhangwang** [comment]
retest this please

**Comment by guozhangwang** [comment]
Jenkins failures are not related, there are JIRAs tracking these issues already.

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and cherry-picked to 0.10.2.

**Pull request closed without merging**
