### PR TITLE
KAFKA-2717: Add kafka logbak appender

### PR DESCRIPTION
**Pull request by vesense**
https://issues.apache.org/jira/browse/KAFKA-2717

### CODE REVIEW

**Comment by vesense** [comment]
@guozhangwang Could you take a look?

**Comment by guozhangwang** [comment]
Thanks for the patch @vesense , we are currently shooting to get the 0.9.0 release by next week. I will come back to review this PR right after it is done.

**Comment by vesense** [comment]
Hi @guozhangwang, did you have the chance to take a look at this?

**Comment by guozhangwang** [comment]
@vesense The patch looks good to me overall. Since this patch requires adding an additional module to Kafka could you create a KIP proposal following this guidelines:

https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals

One example of a KIP:

https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=56852556

Once it is discussed and accepted, we can rebase this patch on trunk and merge it.

**Pull request closed without merging**
