### PR TITLE
MINOR: improve error reporting in DescribeConsumerGroupTest

### PR DESCRIPTION
**Pull request by cmccabe**

### CODE REVIEW

**Review by mumrah — APPROVED** [review]
LGTM

**Comment by stanislavkozlovski** [comment]
nit: It's a bit more difficult to find usages of an exception class when we assert against the class' name as a string.

Did we consider creating a helper in `TestUtils.scala` that abstracts asserting the  instanceof of a class and logs a helpful message if the assertion fails? This would pave the way for all the other scala tests which use the same unhelpful assertion as DescribeConsumerGroupTest

**Comment by cmccabe** [comment]
@stanislavkozlovski: That is a fair point.  It would be good to keep the reference to the class object.  I pushed an update that should do this.

**Comment by stanislavkozlovski** [comment]
thanks

**Pull request merged**
