### PR TITLE
MINOR: AbstractConfig cleanup Part 2

### PR DESCRIPTION
**Pull request by gharris1727**
Revert some parts of the previous cleanup which were unnecessary and incorrect.

Should accompany #15597 everywhere.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gharris1727** [comment]
cc @mimaison @C0urante @OmniaGM @omkreddy PTAL, Thanks!

**Comment by chia7712** [comment]
@gharris1727 just curious. How do you notice that incorrect changes? Are there failed tests related to #15597?

**Review by omkreddy — APPROVED** [review]
LGTM

**Comment by gharris1727** [comment]
Hi @chia7712 This [test is disabled in CI](https://github.com/apache/kafka/blob/ee61bb721eecb0404929f125fe43392f3d024453/core/src/test/scala/integration/kafka/server/DynamicBrokerReconfigurationTest.scala#L622), but fails on trunk if it is re-enabled. I believe that this problem would also be apparent if one tried to use the dynamic reconfiguration feature to change the default log configs. AFAIU the earlier PR completely breaks that feature.

We should prioritize https://issues.apache.org/jira/browse/KAFKA-6527 to re-enable this test, as it would have caught this regression.

**Comment by chia7712** [comment]
> We should prioritize https://issues.apache.org/jira/browse/KAFKA-6527 to re-enable this test, as it would have caught this regression.

sounds good to me. just test it on my local, and you are right. Do you plan to take over KAFKA-6527?

**Review by chia7712 — APPROVED** [review]

**Comment by chia7712** [comment]
```
./gradlew cleanTest :tools:test --tests MetadataQuorumCommandTest.testDescribeQuorumStatusSuccessful :connect:runtime:test --tests org.apache.kafka.connect.integration.ExactlyOnceSourceIntegrationTest.testSeparateOffsetsTopic :metadata:test --tests QuorumControllerTest.testFenceMultipleBrokers :trogdor:test --tests CoordinatorTest.testTaskRequestWithOldStartMsGetsUpdated :server:test --tests AssignmentsManagerTest.testRequeuesFailedAssignmentPropagations :connect:mirror:test --tests MirrorConnectorsIntegrationExactlyOnceTest.testOffsetTranslationBehindReplicationFlow --tests MirrorConnectorsIntegrationSSLTest.testReplicateFromLatest --tests IdentityReplicationIntegrationTest.testReplicateSourceDefault --tests MirrorConnectorsIntegrationBaseTest.testReplicateSourceDefault :core:test --tests DelegationTokenEndToEndAuthorizationWithOwnerTest.testCreateTokenForOtherUserFails --tests ConsumerBounceTest.testConsumptionWithBrokerFailures --tests LogDirFailureTest.testIOExceptionDuringLogRoll --tests LogDirFailureTest.testIOExceptionDuringCheckpoint
```
all pass on my local. will merge it

**Comment by omkreddy** [comment]
lets also merge to 3.7 and 3.6

**Comment by gharris1727** [comment]
I'll handle the backports later today.

**Comment by chia7712** [comment]
@gharris1727 @omkreddy 

#15597 and this one have backported to 3.7. see https://github.com/apache/kafka/commit/d9674c6c9a99c0d8a9c32386b0cceaceac92969c and https://github.com/apache/kafka/commit/cfc97a137f19912313fc73776121d70b0e3f7a88

They are backported to 3.5 also ( we don't need to push to 3.5, and it seems be a mistaken). see https://github.com/apache/kafka/commit/d29d21e6bec61994d30c487298bbb7c6eb6c1e41 and https://github.com/apache/kafka/commit/046821905477a8dbd1dc7991eeb1c416b5622c81

However, the branch 3.6 does not have those branches, and so @gharris1727 Please do the backport for 3.6, thanks

**Comment by gharris1727** [comment]
Hi @chia7712 @omkreddy I have delayed backporting either change to 3.6 as we're currently in an ongoing release. If you'd like me to backport it now, I can do that.

**Comment by chia7712** [comment]
> have delayed backporting either change to 3.6 as we're currently in an ongoing release. If you'd like me to backport it now, I can do that.

That makes sense. Let's wait for the RC2 get votes

**Pull request merged**
