### PR TITLE
Revert "MINOR: Add junit properties to display parameterized test names (#14687)"

### PR DESCRIPTION
**Pull request by dajac**
This reverts commit bdf6d46b41bba22d5a9adf6eb1c87e46d8b9c095.

We found out that this commit introduced flakiness in Streams' tests. We will revise it.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by dajac** [comment]
cc @alok123t

**Review by cadonna — APPROVED** [review]
LGTM! Thanks!

**Comment by dajac** [comment]
@alok123t Are you interested in giving it another try?

**Comment by alok123t** [comment]
> @alok123t Are you interested in giving it another try?

Yes, I will follow up

**Comment by cadonna** [comment]
@alok123t I just read your comment. FYI, I worked on fixing this PR today. The [resulting PR](https://github.com/apache/kafka/pull/14983) is ready to merge. I just need an approval.

**Pull request merged**
