### PR TITLE
WIP: Add a consumer offset migration tool

### PR DESCRIPTION
**Pull request by granthenke**
Please see the dev mailing list for context.

### CODE REVIEW

**Comment by gwenshap** [comment]
@granthenke, what was decision here?
If you decided not to proceed, feel free to close the PR :)

**Comment by ewencp** [comment]
@granthenke Any word on this?

**Comment by jeffwidman** [comment]
@granthenke How much have you tested this? Skimming the code, it looks reasonably feature complete, so when you say WIP, what does that refer to?

Asking because I'm considering using it as we need a migration script, and not sure how much additional hacking this need.

**Comment by granthenke** [comment]
@jeffwidman I have used this in the past with no issues, but do to various time constraints and life events have not been able to follow up and get it committed. I would encourage you to test it yourself, but its should work as expected. I should follow up and get this committed.

**Comment by jeffwidman** [comment]
@granthenke thanks again for your hard work on this. I also tested thoroughly, and works perfectly. 

I extended this in #2615 to support renaming the consumer group as part of the migration. 

I'm torn on whether this should land in core... it's useful to have here in a PR so that others can find/re-use, but this code will rarely get used outside of upgrading. That said, it is extremely useful when dealing with non-Java clients as most of those don't support `dual.commit`.

**Comment by mimaison** [comment]
The old consumer has been removed a long time ago, so I think we can close this PR.

**Pull request closed without merging**
