### PR TITLE
KAFKA-9779: Add Stream System Test 2.5

### PR DESCRIPTION
**Pull request by abbccdda**
As title, we should be adding the upgrade test after 2.5 release.
```
 TC_PATHS="tests/kafkatest/tests/streams/streams_upgrade_test.py" bash tests/docker/run_tests.sh
```
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mjsax** [comment]
Thanks for the PR @abbccdda -- we cannot merge this as long as 2.5 is not released, because we depend on the release artifacts -- otherwise we break system tests in `trunk`.

**Comment by abbccdda** [comment]
Triggered a system test: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/3911/

**Comment by mumrah** [comment]
2.5 artifacts are now publicly available, so we should be good to merge this.

**Comment by abbccdda** [comment]
@mumrah Yes, the system test passed.

**Pull request merged**
