### PR TITLE
KAFKA-4604: Fix gradle build to avoid generating unnecessary projects

### PR DESCRIPTION
**Pull request by dhwanikatagade**
Fix gradle build to avoid generating unnecessary projects for non project sub folders. The unnecessary projects cause unwanted file deletes in git when these projects are cleaned in eclipse.

### CODE REVIEW

**Comment by dhwanikatagade** [comment]
retest this please

**Comment by dhwanikatagade** [comment]
I ran the following two commands with JDK 1.8 setup and the tests ran successfully.
```
./gradlew -PscalaVersion=2.11 test
./gradlew -PscalaVersion=2.12 test
```

**Comment by dhwanikatagade** [comment]
Hi @ijuma @guozhangwang 
I am new to the codebase and process, so please guide me if I am going wrong somewhere.

I have done a merge from trunk HEAD and tried the following tests on my local setup.
```
./gradlew -PscalaVersion=2.10 test (with JDK1.7)
./gradlew -PscalaVersion=2.11 test (with JDK1.8)
./gradlew -PscalaVersion=2.12 test (with JDK1.8)
```
The tests fail sometimes when run all together but the failing ones pass when run selectively afterwards. May be the tests are non deterministic, or am I missing something?

I will push the trunk HEAD merge to trigger another Jenkins test.

**Comment by guozhangwang** [comment]
I tested the branch and can confirm that there is no Eclipse files generated at root fold and sub-connect folder. @ijuma do you want to double check?

**Comment by dhwanikatagade** [comment]
@guozhangwang @ijuma - Closing this PR since it is obsoleted by https://github.com/apache/kafka/pull/2382

**Pull request closed without merging**
