### PR TITLE
MINOR: Return null in key mapping of committed

### PR DESCRIPTION
**Pull request by guozhangwang**
To be consistent with other grouping APIs, and also modified callers accordingly.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@hachikuji @omkreddy for reviews.

**Comment by guozhangwang** [comment]
retest this please

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by guozhangwang** [comment]
Cherry-picked to 2.4.

**Pull request merged**
