### PR TITLE
KAFKA-13719: fix connector restart cause duplicate tasks

### PR DESCRIPTION
**Pull request by sunshujie1990**
When kafka Connect restarts connector with includeTasks=true,  DistributedHerder start all task without filter the currentAssignments. This results in duplicate tasks and duplicate data。

### CODE REVIEW

**Comment by sunshujie1990** [comment]
@hachikuji Jason, please help to review it.

**Comment by C0urante** [comment]
Thanks for finding and fixing this @sunshujie1990! Changes like this one should usually come with a unit test to verify that the original bug exists, and that the proposed fix addresses it.

I've drafted a small addition to an existing test case that should accomplish this in a personal fork that also includes your commit for this PR: https://github.com/C0urante/kafka/commit/ddd64ebc6400b9044a1358cf18c23d3d914d1f90

If that looks good to you, feel free to cherry-pick onto your branch and make any adjustments that you'd like.

Given that the issue can be reproduced via unit test and that this fix does address it (by causing the test to pass), this LGTM once it has test coverage added.

**Comment by C0urante** [comment]
cc @rhauch @kpatelatwork this is a pretty serious bug with the recently-added mass restart feature, worth taking a look if you have the time.

**Comment by sunshujie1990** [comment]
@C0urante Done. Please help me review it again.

**Review by C0urante — APPROVED** [review]

**Comment by C0urante** [comment]
@showuon @mimaison would either of you have time for this? Might be worth trying to include in the 3.2.0 release if we're still considering non-regressions.

**Review by showuon — APPROVED** [review]
LGTM! But since I'm not very familiar with Kafka Connect, I'll wait for another review. Thanks.

**Comment by kpatelatwork** [comment]
@C0urante Thanks a lot this indeed seems like a bug and sorry for the late reply as I was busy. LGTM from my side

**Comment by C0urante** [comment]
No worries @kpatelatwork, good to hear from you!

@showuon totally understand, thanks for taking a look. Definitely better to move cautiously than to merge something you're not confident in.

**Review by mimaison — APPROVED** [review]
Good catch! LGTM

**Comment by mimaison** [comment]
Backported to 3.2 and 3.1

**Pull request merged**
