### PR TITLE
MINOR: Add 3.7 to Kafka Streams system tests

### PR DESCRIPTION
**Pull request by mjsax**
\cc @stanislavkozlovski (I assume the 3.7 artifacts got uploaded to S3, so we can merge this)?

### CODE REVIEW

**Comment by mjsax** [comment]
Triggered a system test run: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/6080/

**Comment by mjsax** [comment]
Couple of system test failed, but seems with env issue. Re-running:

https://jenkins.confluent.io/job/system-test-kafka-branch-builder/6081/

**Comment by mjsax** [comment]
Different set of system test (or same but different parameters) fails on second run. Seems it's flaky test that we will need to stabilize.

**Review by cadonna — APPROVED** [review]
Thanks @mjsax !

LGTM!

**Pull request merged**
