### PR TITLE
KAFKA-9793: Expand the try-catch for task commit in HandleAssignment

### PR DESCRIPTION
**Pull request by abbccdda**
As title suggests, we would like to broaden this check so that we don't fail to close a doom-to-cleanup task.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
test this please

**Comment by mjsax** [comment]
Java 11 passed, but Java 8 failed with
```
java.lang.AssertionError: unexpected exception type thrown; expected:<java.lang.RuntimeException> but was:<java.lang.AssertionError>
	at org.junit.Assert.assertThrows(Assert.java:1020)
	at org.junit.Assert.assertThrows(Assert.java:981)
	at org.apache.kafka.streams.processor.internals.TaskManagerTest.shouldCloseActiveTasksDirtyAndPropagatePrepareCommitException(TaskManagerTest.java:1270)
```

Could this be related?

**Comment by abbccdda** [comment]
Let me check @mjsax

**Comment by abbccdda** [comment]
Fixed by relaxing the ordering check @mjsax

**Comment by mjsax** [comment]
Retest this please.

**Comment by abbccdda** [comment]
Retest this please

**Comment by guozhangwang** [comment]
test this please

**Comment by abbccdda** [comment]
Only one test failure on jdk 8: 
```
kafka.api.PlaintextAdminIntegrationTest.testAlterReplicaLogDirs

Error Message
org.scalatest.exceptions.TestFailedException: only 0 messages are produced within timeout after replica movement. Producer future Some(Failure(java.util.concurrent.TimeoutException: Timeout after waiting for 10000 ms.))
```

**Comment by mjsax** [comment]
Retest this please.

**Comment by guozhangwang** [comment]
```
10:11:30 Execution failed for task ':streams:compileJava'.
10:11:30 > Compilation failed; see the compiler error output for details.
```

**Comment by abbccdda** [comment]
@guozhangwang I think we need to merge https://github.com/apache/kafka/pull/8424 first

**Review by guozhangwang — APPROVED** [review]
LGTM, after fixing jenkins this should be good to go.

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
test this

**Comment by guozhangwang** [comment]
test this please

**Comment by guozhangwang** [comment]
Okay I'm done with jenkins bot and manually build two: https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/1622 and https://builds.apache.org/job/kafka-pr-jdk11-scala2.13/5641

**Comment by guozhangwang** [comment]
Both jenkins succeed, merging to trunk now.

**Pull request merged**
