### PR TITLE
KAFKA-5681; jarAll should build all scala versions.

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by becketqin** [comment]
ping @ijuma

**Comment by ijuma** [comment]
@becketqin, can you elaborate on the goal here?

**Comment by becketqin** [comment]
@ijuma In README.md, we have the following statement:
```
### Building the jar for all scala versions and for all projects ###
    ./gradlew jarAll
```
This has long been a convention. So when users is using Java 8 and run jarAll, they would expect to see jars for all the supported scala versions.

**Comment by becketqin** [comment]
The patch basically keeps the convention to build jars for all scala version when possible and warn the users when it cannot do that.

**Comment by ijuma** [comment]
Scala 2.12 is the first version that requires a newer JDK than the minimum supported version, so there is no precedent. There are pros and cons to each approach.

The issue with the approach you suggest is that the artifacts generated will vary depending on which JDK version was used. That can be quite surprising too. Generally when building AK for releases, you'd want to build Scala 2.11 with Java 7 and Scala 2.12 with Java 8. That's what our release script does.

I'm not necessarily against doing as you suggest, but I'd like to understand the use case a little better. Do you intend to use this in some way?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6587/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by becketqin** [comment]
@ijuma Not sure about the adoption of Scala 2.12 elsewhere, but at LinkedIn we are still in the progress of migration from scala 2.10 to 2.11. So our scala build version would be [2.10, 2.11] and the default version would be [2.10]. We expecting Java 8 + Scala 2.10 and Java 8 + Scala 2.11 to be generated. It was a little surprising that jarAll no longer generates Java 8 + Scala 2.11 jar when we were looking for that artifact.

I guess the same thing could happen when people migrate from Scala 2.11 to Scala 2.12. At that point people would want to generate Java 8 + Scala 2.11 and Java 8 + Scala 2.12 jar. With the current script, Java 8 + Scala 2.12 jar won't be generated when people run jarAll.

This is probably not a critical issue as people can still build the jar with versions they want by specifying the scala version. But If we want to change the behavior of jarAll, it seems that we should at least update README.md because Java 8 + Scala 2.12 is a valid combination of "all scala versions", and the current script won't build it with jarAll.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6572/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by ijuma** [comment]
"so we are basically running Java 8 + Scala 2.10 and Java 8 + Scala 2.11. It was a little surprising that jarAll no longer generates Java 8 + Scala 2.11 jar when we were looking for that artifact."

Hmm, Java 8 + Scala 2.11 should work, so I'm a bit confused. Is this a result of you patching the build so that 2.10 is supported again?

**Comment by ijuma** [comment]
I believe if you add 2.10 to `defaultScalaVersions` and `availableScalaVersions`, it would work for the LinkedIn case. Or am I missing something?

**Comment by becketqin** [comment]
@ijuma We can add 2.10 to `defaultScalaVersions` and `availableScalaVersions` and it works. LinkedIn is not blocking on this. 

My main point for this PR is that it seems we changed the convention of jarAll. My understanding of the README.md is that jarAll will build jars for all supported Scala versions (which is 2.11 and 2.12 now). Say I was a user using Java 7, previously when I called jarAll, I got jars for Scala 2.10 and 2.11. Now I am a Java 8 user, when I call jarAll, it seems natural for me to expect jars for Scala 2.11 and 2.12, right? But currently, jarAll only gives jars for Scala 2.11 even if I am using Java 8. Although we can ask users to modify the dependencies.gradle to add 2.12, it seems better if users don't even need to worry about this. 

On the other hand, if users are still at Java 7 which can cannot build with Scala 2.12, it also seems reasonable to let users know that we cannot generate Scala 2.12 jar due to the Java version requirement.

Does this make sense?

**Comment by ijuma** [comment]
@becketqin, you can see the following right at the top of the `README.md`.

```text
Java 7 should be used for building in order to support both Java 7 and Java 8 at runtime.
```

So, if you follow the `README.md`, you can't actually build Scala 2.12 at all. We added special support for building Scala 2.12 via `-PscalaVersion` so that we can include it in releases, but we don't recommend building all Scala versions with Java 8 because it can cause issues like:

https://gist.github.com/AlainODea/1375759b8720a3f9f094

Anyway, unless we have users asking for this functionality, I'd be reluctant to include it because it will be reverted again as soon as we drop support for Java 7. But I don't feel very strongly, so if another committer thinks we should do it, I'm OK with that.

**Comment by becketqin** [comment]
@ijuma I see. If building Scala 2.12 with Java 8 is discouraged, then leaving it out of jarAll makes sense. Just curious, if building Scala 2.12 might have problem, are we doing anything special when building Scala 2.12 with `-PscalaVersion`? I did not see that in the build script. Does that mean the Scala 2.12 jars may cause problem at runtime?

I am a little surprised about this though because it seems Java 8 and Scala 2.12 is a common combination and used by some major projects such as Spark and Play. Is it a little weird that we release Scala 2.12 with Java 8 but not recommend people from building Scala 2.12 with Java 8?

**Comment by ijuma** [comment]
No, I said that building for Scala 2.11 with Java 8 is discouraged because it may not run on Java 7. So, it's best to use two build invocations (which is what the release script does).

**Comment by becketqin** [comment]
Thanks for the explanation. Let me summarize my understanding, please correct me if I am wrong:

1. We release jars with Java 7 + Scala 2.11 and Java 8 + Scala 2.12, so users running Scala 2.11 can use the first jar safely regardless of their Java version.
2. When users invoke `./gradlew jarAll`. We only build Scala 2.11 jar in because Scala 2.12 require Java 8. This could potentially result in Java 8 + Scala 2.11 combination, which is discouraged because the user's runtime might still be Java 7.
3. Scala 2.12 + Java 8 is a safe combination but `./gradlew jarAll` won't build that when users are using Java 8. Instead users need to build with `-PscalaVersions`.

I guess my main confusion is on 3. Let's say we drop Java 7 support in the next release, will we build Scala 2.12 with `./gradlew jarAll` in that case?

Sorry about sticking to this. I do not feel strong on the semantic of `jarAll` either because most users would not build Kafka by themselves. And when they do, it is not a big deal to build with `-PscalaVersions`. So I am mostly asking for my own curiosity.

**Comment by ijuma** [comment]
Yes, once we drop support for Java 7, then Scala 2.12 will be built by `jarAll`. A way to define it is: `jarAll` builds all Scala versions supported by the minimum Java version we support.

Once http://openjdk.java.net/jeps/247 is supported by the Scala compiler and Java 9 is more commonly available, we could improve this because building with newer JDK versions would still build against the correct Java standard library.

**Comment by becketqin** [comment]
OK, sounds good. I'm closing the PR then.

**Pull request closed without merging**
