### PR TITLE
KAFKA-10755: Should consider commit latency when computing next commit timestamp

### PR DESCRIPTION
**Pull request by mjsax**
Call for review @wcarlson5 @guozhangwang

### CODE REVIEW

**Review by guozhangwang — APPROVED** [review]

**Comment by guozhangwang** [comment]
LGTM! Please feel free to merge if local unit test passes.

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.6`. Will cherry pick to `2.7` after release is done.

**Comment by ijuma** [comment]
Looks this broke the build. Did we check that the PR passed?

**Comment by mjsax** [comment]
Jenkins build was green... Not sure how this happened.

It seems, I did start the PR from a stale local `trunk` branch. But Jenkins build should have caught the issue. Not sure why?

**Comment by mjsax** [comment]
Cherry-picked to `2.7` branch.

**Pull request merged**
