### PR TITLE
KAFKA-6130: VerifiableConsumer with --max-messages

### PR DESCRIPTION
**Pull request by tombentley**
@hachikuji can you review this? Do you know the best place to write a test, since there doesn't seem to be a unit test for the `VerifiableConsumer`?

### CODE REVIEW

**Comment by hachikuji** [comment]
@tombentley Thanks for the patch, LGTM. As for testing, maybe for now we can file a JIRA to improve test coverage for `VerifiableConsumer` and `VerifiableProducer`. It's a little awkward since these tools are only intended for use in system tests, but that doesn't mean they shouldn't have proper test coverage.

**Comment by tombentley** [comment]
@hachikuji, I opened [KAFKA-6143](https://issues.apache.org/jira/browse/KAFKA-6143)

**Comment by tombentley** [comment]
retest this please

**Comment by hachikuji** [comment]
Thanks, merging to trunk.

**Pull request closed without merging**
