### PR TITLE
KAFKA-3838 zkClient and Zookeeper version bump

### PR DESCRIPTION
**Pull request by mangas**

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Thoughts @fpj?

**Comment by mangas** [comment]
Can't replicate these failures, could this have been caused by something else? 

`
unit.kafka.admin.ReassignPartitionsClusterTest > shouldExpandCluster PASSED
unit.kafka.admin.ReassignPartitionsClusterTest > shouldShrinkCluster PASSED
kafka.integration.UncleanLeaderElectionTest > testUncleanLeaderElectionEnabledByTopicOverride PASSED
kafka.integration.UncleanLeaderElectionTest > testCleanLeaderElectionDisabledByTopicOverride PASSED
kafka.integration.UncleanLeaderElectionTest > testUncleanLeaderElectionDisabled PASSED
kafka.integration.SslTopicMetadataTest > testIsrAfterBrokerShutDownAndJoinsBack PASSED
kafka.server.SessionExpireListenerTest > testSessionExpireListenerMetrics PASSED
`

**Comment by fpj** [comment]
I don't see an issue with upgrading, 3.4.8 is a bug fix release, it sounds fine.

**Comment by mangas** [comment]
@ijuma need anything else from my side?

**Comment by ijuma** [comment]
@mangas, I noticed that your PR targets the `0.10.0` branch, it should target `trunk` instead. We only include bug fixes in the `0.10.0` branch.

**Comment by mangas** [comment]
I'm closing this and opened a new one https://github.com/apache/kafka/pull/1512

**Pull request closed without merging**
