### PR TITLE
KAFKA-16915: LeaderChangeMessage supports VoterDirectoryId

### PR DESCRIPTION
**Pull request by ahuang98**
Introducing v1 of LeaderChangeMessage which supports VoterDirectoryId. v0 is still in use

https://issues.apache.org/jira/browse/KAFKA-17206

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jsancio** [comment]
Thanks for the changes. Tests are failing.

**Comment by jsancio** [comment]
@ahuang98 LGTM. Let's update the PR description and file a Jira for writing version 1 of LeaderChangeMessage when the kraft.version is 1.

**Comment by ahuang98** [comment]
@jsancio thanks for the review, I've updated the description with the Jira as well

**Comment by ahuang98** [comment]
two unrelated test failures

**Review by jsancio — APPROVED** [review]
LGTM

**Comment by jsancio** [comment]
> Jira for writing version 1 of LeaderChangeMessage when the kraft.version is 1.

@ahuang98 did you create a jira for writing version 1 for leader change message when the kraft.version is 1? If so, what's the jira number?

**Pull request merged**
