### PR TITLE
HOTFIX: recreate state.dir after cleanup

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Anyof @guozhangwang @dguy @enothereska @miguno @hjafarpour

After a `cleanup()` we need to re-create `state.dir`, otherwise, we might run into an exception if `cleanup()` is called **after** the second `KafkaStreams` instance got created (see modified test of this PR)

Exception would be

```
Exception in thread "StreamThread-2" org.apache.kafka.streams.errors.StreamsException: stream-thread [StreamThread-2] Failed to rebalance
    at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:339)
    at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:235)
Caused by: org.apache.kafka.streams.errors.ProcessorStateException: Error while creating the state manager
    at org.apache.kafka.streams.processor.internals.AbstractTask.<init>(AbstractTask.java:69)
    at org.apache.kafka.streams.processor.internals.StreamTask.<init>(StreamTask.java:87)
    at org.apache.kafka.streams.processor.internals.StreamThread.createStreamTask(StreamThread.java:566)
    at org.apache.kafka.streams.processor.internals.StreamThread.addStreamTasks(StreamThread.java:593)
    at org.apache.kafka.streams.processor.internals.StreamThread.access$000(StreamThread.java:69)
    at org.apache.kafka.streams.processor.internals.StreamThread$1.onPartitionsAssigned(StreamThread.java:120)
    at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:225)
    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:321)
    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:273)
    at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:256)
    at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1003)
    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:969)
    at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:335)
    ... 1 more
Caused by: java.nio.file.NoSuchFileException: /tmp/kafka-streams/application-reset-integration-test/0_0/.lock
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
    at java.nio.channels.FileChannel.open(FileChannel.java:287)
    at java.nio.channels.FileChannel.open(FileChannel.java:335)
    at org.apache.kafka.streams.processor.internals.StateDirectory.getOrCreateFileChannel(StateDirectory.java:172)
    at org.apache.kafka.streams.processor.internals.StateDirectory.lock(StateDirectory.java:86)
    at org.apache.kafka.streams.processor.internals.ProcessorStateManager.<init>(ProcessorStateManager.java:95)
    at org.apache.kafka.streams.processor.internals.AbstractTask.<init>(AbstractTask.java:66)
    ... 13 more
```

**Comment by dguy** [comment]
@mjsax looks like one of the related tests has failed: org.apache.kafka.streams.KafkaStreamsTest.testCleanupIsolation

**Comment by guozhangwang** [comment]
Nice catch. But simply delete-and-recreate may still be vulnerable to race conditions when two instances are bootstrapping concurrently, since the file lock is only on the task level while deleting is on the global application level?

**Comment by mjsax** [comment]
@guozhangwang Good point. I did change `KafkaStreams#cleanUp()` to be "task sensitive" now. This make unit-testing the method not possible any longer -- also removed this test. /cc @dguy

**Comment by dguy** [comment]
LGTM - only potential issue i can think of is if you multiple instances on the one machine and 1 or more are running and 1 is doing cleanup. If they share the same state dir, then all the task dirs will be deleted. However, i think this is probably more a case of documenting that scenario?

**Comment by guozhangwang** [comment]
@mjsax Is this still true with the latest patch?

**Comment by mjsax** [comment]
@dguy @guozhangwang I don't think that this would be a problem, because we only delete task directories -- the application directory itself is not touched. Thus, each instance, should delete and recreate a distinct set of task directories. Or do I miss something?

**Comment by dguy** [comment]
@mjsax @guozhangwang `StateDirectory.listTaskDirectories` returns all the directories that match the pattern of a task dir name. 

```
public File[] listTaskDirectories() {
        return stateDir.listFiles(new FileFilter() {
            @Override
            public boolean accept(final File pathname) {
                final String name = pathname.getName();
                return pathname.isDirectory() && name.matches("\\d+_\\d+");
            }
        });
    }
```

Even if you accessed the `StateDirectory` instance from each of the `StreamThread`s it still wouldn't help. Also, even if the `StateDirectory` instance for a `StreamThread` listed only the task directories currently owned by the `StreamThread` it still wouldn't help as at `cleanup` `KafkaStreams` is closed, so the `StreamThread`s have stopped and all the locks etc would have been released.

**Comment by guozhangwang** [comment]
@mjsax Could you address the comments by refactoring the patch again?

**Comment by dguy** [comment]
@mjsax - it looks like you could use `StateDirectory.cleanRemovedTasks()` as it will only delete the `taskDir` if it can get the lock

**Comment by mjsax** [comment]
@dguy @guozhangwang Updated this.

**Review by dguy — APPROVED** [review]
LGTM

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk and 0.10.1.

**Pull request closed without merging**
