### PR TITLE
KAFKA-3965 mirror maker should not commit offset when exception is thrown from producer.send()

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by omkreddy** [comment]
+1

**Comment by ijuma** [comment]
Thanks for the PR, would it be possible to write a test for this?

**Comment by becketqin** [comment]
@ijuma It is tricky to have unit test for mirror maker in this case. Do you think it worth a system test?

**Comment by ijuma** [comment]
@becketqin, if the existing system test for MirrorMaker could be modified to test this scenario, that would be great. If it's a lot of work, we may have to split that into a separate JIRA and merge this PR as it is (so that it can be included in 0.10.1.0)

**Comment by becketqin** [comment]
@ijuma It probably can be added to the existing mirror maker integration test. But I am not sure how long that would take given that I do not have much experience with integration test.

**Comment by hachikuji** [comment]
LGTM. Given the current state of MM tests and the size of this fix, I'd be OK opening a separate JIRA to follow up with more testing later.

**Comment by ijuma** [comment]
Sounds good to me.

**Comment by hachikuji** [comment]
Merged to trunk and 0.10.1. @becketqin Would you mind creating a follow-up JIRA for the MM tests?

**Comment by becketqin** [comment]
@hachikuji will do.

**Pull request closed without merging**
