### PR TITLE
HOTFIX: WindowedStreamPartitioner does not provide topic name to serializer

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Call for review @dguy @enothereska

**Comment by mjsax** [comment]
Patch for `trunk` is #2777

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by mjsax** [comment]
Retest this please.

**Comment by enothereska** [comment]
LGTM. For committers, there is lots of cleanup here together with actual fix.

**Review by dguy — APPROVED** [review]
Thanks @mjsax, LGTM

**Review by ijuma — APPROVED** [review]
LGTM, thanks.

In the future, it would be great to try and keep changes that need to be backported to stable branches to a minimum.

Whilst I agree that it's fine to do clean-up along with changes for PRs that have trunk as the target, I think a different policy should be used for changes that need to go into a bug fix release. Especially if they don't merge cleanly. Comparing the trunk and 0.10.2 change is challenging since there are so many unrelated changes.

**Comment by ijuma** [comment]
Merged to 0.10.2. Please close this PR.

**Comment by davispw** [comment]
@ijuma Is there a JIRA or release notes for this?  Nothing in [0.10.2.1 release notes](https://archive.apache.org/dist/kafka/0.10.2.1/RELEASE_NOTES.html) or in conversation at #2777 .

This appears to fix some serious issues I was having with StateStores and SessionStores in particular.  Since I can't find mention of this elsewhere online, I'll document here what I've found:

* Naked StateStore name (without application ID prefix) was provided as the subject, causing collisions in the schema registry with other applications.
* For session stores, a bogus "sessionkey-key" subject was hard coded!
* SessionStore.fetch() would fail when using a MockSchemaRegistryClient, because reads used the store's key serde (=> subject = store name) while writes used the hardcoded "sessionkey" subject (MockSchemaRegistryClient is not smart enough to assign the same schema registered under different subjects the same ID -- broke unit tests using Spring's EmbeddedKafka with MockSchemaRegistryClient).

Changing subject names is not a completely backwards compatible change!  Fortunately it's a minor difference (since KafkaAvroSerializer IDs are global and the subject is only used for in-memory caching), but this breaks unit tests that verify the schema registry, or any other references to the old state-store-specific subject names.  Don't get me wrong -- this is an extremely welcome fix, but it's a bit bigger than a HOTFIX.

**Comment by mjsax** [comment]
@davispw It depends how you look at it. Note, that Schema Registry is not part of AK, but an open source offer from Confluent. Thus, from an AK point of view, it is a HOTFIX as it does not impact AK. That is also the reason why it's not part of release notes.

**Comment by ijuma** [comment]
@davispw, thanks for documenting your findings. You raise a fair point, this should have had a JIRA so that it appeared in the release notes. And potentially a note in the upgrade docs.

**Comment by mjsax** [comment]
We created a JIRA in retrospective: https://issues.apache.org/jira/browse/KAFKA-5577

**Pull request closed without merging**
