### PR TITLE
KAFKA-2955; Add a simple ">" prompt to console producer

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by omkreddy** [comment]
@ijuma  Pinging for review

**Comment by ijuma** [comment]
Because this changes the UI for the console producer, it would be good to get a second opinion. @gwenshap maybe?

**Comment by guozhangwang** [comment]
This addition LGTM, since console-producer is not supposed to be used programmatically anyways (instead `o.a.k.tools.VerifiableProducer` would more likely to be used in that case).

**Comment by gwenshap** [comment]
LGTM. Agree it will improve usability

**Comment by omkreddy** [comment]
@ijuma Can we merge this PR?

**Comment by guozhangwang** [comment]
Merged to trunk. Thanks @omkreddy

**Pull request closed without merging**
