### PR TITLE
change language level from java 7 to 8

### PR DESCRIPTION
**Pull request by radai-rosenblatt**
now that KIP-118 has passed, and there are no major releases coming before 0.11 ....

Signed-off-by: radai-rosenblatt <radai.rosenblatt@gmail.com>

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. I haven't done this yet because our system tests infrastructure still requires Java 7. Once that is fixed and the various Jenkins jobs are updated, we can make this change.

**Comment by ijuma** [comment]
The relevant JIRA is https://issues.apache.org/jira/browse/KAFKA-4423 by the way.

**Comment by radai-rosenblatt** [comment]
i give up

**Comment by onurkaraman** [comment]
@ijuma what does upgrading system test infrastructure entail?

Does it involve more than what's below?
https://github.com/onurkaraman/kafka/commit/02119fc42fb5ba4f28df8743639f9054baee9270

Not in any rush to resolve KAFKA-4423, just curious.

**Comment by lahabana** [comment]
@ijuma seems like 1.0.0 is the right version to drop java7 support.

Anything I can help with to get @onurkaraman change in and get the java8 transition done?

I'm working on writing a KIP which would be a lot nicer if we can have interface defaults :)

**Pull request closed without merging**
