### PR TITLE
change connection refused message from level DEBUG into WARN.

### PR DESCRIPTION
**Pull request by jedichien**
If broker is down, we supply logging message to let user know `java.net.ConnectException: Connection refused` but not should be debug message because in normal situation user may not set logging level with **INFO** or **WARN** but not **DEBUG**. 
```
2017-04-27 15:54:47,759 DEBUG [org.apache.kafka.common.network.Selector] - Connection with localhost/127.0.0.1 disconnected
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50)
        at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:80)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:339)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:307)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:359)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:206)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:197)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:132)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:223)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:200)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:285)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1037)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1002)
        at com.kafka.Test.main(Test.java:27)
```

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Because this can be noisy, we try to log the warning at higher levels. In `NetworkClient`, we have:

```java
log.warn("Bootstrap broker {}:{} disconnected", node.host(), node.port());
```

**Comment by jedichien** [comment]
but I cannot see this warn message if I set wrong broker at beginning.

**Comment by ijuma** [comment]
That seems to be a bug. Maybe we need to investigate why that path is not triggered any more.

**Comment by jedichien** [comment]
okay, I will keep to working on this.

**Comment by jedichien** [comment]
I find `NetworkClient#handleDisconnection` will be called by `NetworkClient#processDisconnection` which will printed warn message ```log.warn("Bootstrap broker {}:{} disconnected", node.host(), node.port());``` if it exists `InFlightRequest` and I do not think that exists `InFlightRequest` if we set wrong broker.

**Comment by ijuma** [comment]
Good point @jedichien. cc @hachikuji in case he has thoughts on how to do this in a way that doesn't make it too noisy.

**Pull request closed without merging**
