### PR TITLE
MINOR: Setup DLQ only if there are properties with the right prefix

### PR DESCRIPTION
**Pull request by wicknicks**
Signed-off-by: Arjun Satish <arjun@confluent.io>

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wicknicks** [comment]
@rhauch @mageshn could you please take a look at this? Thanks!

**Comment by rhauch** [comment]
Why is there no build information?

**Comment by wicknicks** [comment]
@rhauch: I don't know. @ewencp, why is there no build information here?

**Comment by hachikuji** [comment]
retest this please

**Comment by mageshn** [comment]
@wicknicks  I think all the new Error Reporter related configs should be included in ConnectorConfig with approriate defaults. So, if the default for the DLQ topic was "", the existing code would still work.

**Comment by ewencp** [comment]
It seems like the build queue might just be backed up and the status won't show up until jenkins starts the jobs for the PR. Can't tell if this is normal but there's some hive build that seems like it is flooding the build queue.

**Comment by wicknicks** [comment]
replacing this PR with https://github.com/apache/kafka/pull/5125.

**Pull request closed without merging**
