### PR TITLE
MINOR: Rename TopicCommandTest

### PR DESCRIPTION
**Pull request by jsancio**
Rename the test suite to later add unittests that don't depend on
ZK or the AdminClient TopiCommand types.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by jsancio** [comment]
Here is the rename @ijuma. I'll resolve the conflicts in https://github.com/apache/kafka/pull/8364, if any, once this is merged.

**Review by chia7712 — APPROVED** [review]

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
ok to test

**Comment by jsancio** [comment]
One failure unrelated to this change
```
org.scalatest.exceptions.TestFailedException: The remaining consumers in the group could not fetch the expected records
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
	at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1389)
	at org.scalatest.Assertions.fail(Assertions.scala:1091)
	at org.scalatest.Assertions.fail$(Assertions.scala:1087)
	at org.scalatest.Assertions$.fail(Assertions.scala:1389)
	at kafka.api.ConsumerBounceTest.testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup(ConsumerBounceTest.scala:329)
```

**Pull request merged**
