### PR TITLE
MINOR: increase timeout for broker startup in 0.10.2 system tests

### PR DESCRIPTION
**Pull request by vvcephei**
There has been some test flakiness in which this line times out just before the broker comes online.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@guozhangwang @mjsax @bbejeck , what do you think about this?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3809/
Test FAILed (JDK 7 and Scala 2.10).

**Comment by mjsax** [comment]
Call for review @hachikuji @cmccabe -- this is beyond Streams scope.

**Comment by ijuma** [comment]
@vvcephei do you have logs from when this happened? It would be useful to understand why it's taking so long.

**Comment by ijuma** [comment]
Also, why is this for 0.10.2 instead of trunk?

**Comment by mjsax** [comment]
@vvcephei What it the status of this PR? Did you see Ismael's question?

**Comment by vvcephei** [comment]
Hey @mjsax and @ijuma , Sorry about that. I did miss Ismael's question.

I do have the logs. 

The reason for this failure is that Kafka took too long to start up.

The timeout is 30s, and it looks like the zookeeper connection was too slow.
Here's this run:

```
[2018-08-16 06:52:21,003] INFO starting (kafka.server.KafkaServer)
[2018-08-16 06:52:21,017] INFO Connecting to zookeeper on worker6:2181 (kafka.server.KafkaServer)
[2018-08-16 06:52:31,436] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-08-16 06:52:34,861] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2018-08-16 06:52:42,500] INFO zookeeper state changed (Disconnected) (org.I0Itec.zkclient.ZkClient)
[2018-08-16 06:52:42,527] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-08-16 06:52:44,851] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2018-08-16 06:52:46,243] INFO Cluster ID = qqnbWOwCRCGnRVHsKjA5Bw (kafka.server.KafkaServer)
[2018-08-16 06:52:46,264] WARN No meta.properties file under dir /mnt/kafka-data-logs/meta.properties (kafka.server.BrokerMetadataCheckpoint)
[2018-08-16 06:52:46,489] INFO [ThrottledRequestReaper-Fetch], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2018-08-16 06:52:46,517] INFO [ThrottledRequestReaper-Produce], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2018-08-16 06:52:46,811] INFO Log directory '/mnt/kafka-data-logs' not found, creating it. (kafka.log.LogManager)
[2018-08-16 06:52:46,847] INFO [Kafka Server 1], shutting down (kafka.server.KafkaServer)
```

And here's another run:

```
[2018-08-11 02:23:28,915] INFO starting (kafka.server.KafkaServer)
[2018-08-11 02:23:28,917] INFO Connecting to zookeeper on worker10:2181 (kafka.server.KafkaServer)
[2018-08-11 02:23:28,949] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-08-11 02:23:28,976] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2018-08-11 02:23:29,085] INFO Cluster ID = PlVoMxPpQwCLTl7toQiEjQ (kafka.server.KafkaServer)
[2018-08-11 02:23:29,087] WARN No meta.properties file under dir /mnt/kafka-data-logs/meta.properties (kafka.server.BrokerMetadataCheckpoint)
[2018-08-11 02:23:29,103] INFO [ThrottledRequestReaper-Fetch], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2018-08-11 02:23:29,105] INFO [ThrottledRequestReaper-Produce], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2018-08-11 02:23:29,132] INFO Log directory '/mnt/kafka-data-logs' not found, creating it. (kafka.log.LogManager)
[2018-08-11 02:23:29,139] INFO Loading logs. (kafka.log.LogManager)
```

The bad run took 25.808 seconds to get from startup to creating the log directory, while the good run took only 0.217 seconds.

The bad run spent 10.419 seconds "connecting to zookeeper", and after it connected, it disconnected and reconnected.

It looks environmental to me, like a bad network connection to zookeeper, or maybe a noisy neighbor. 

The PR is for this branch, not trunk, because the test failure occurred in this branch.

Admittedly, this change is a bit of a shot in the dark. If it is environmental, that there's no particular reason to send the change against just one branch, or even just one test for that matter. It'd be just as likely to happen to a different test on a different branch the next time.

This PR has been open for a month already, and I haven't seen this test fail again in that time, so perhaps it's wiser not to make a change and just see if it happens again.

I'll close this for now.

**Pull request closed without merging**
