### PR TITLE
MINOR: Fix redundant typos in comments and javadocs

### PR DESCRIPTION
**Pull request by ocadaruma**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rondagostino — COMMENTED** [review]
Thanks for the PR.  This is a common mistake, and a quick search revealed multiple occurrences.  Can you fix all of them?

```
$ git grep "the the" .
clients/src/main/java/org/apache/kafka/clients/admin/OffsetSpec.java:     * Used to retrieve the the earliest offset whose timestamp is greater than
clients/src/main/java/org/apache/kafka/clients/producer/internals/RecordAccumulator.java:     *                        running the the partitioner's onNewBatch method before trying to append again
clients/src/main/java/org/apache/kafka/common/config/TopicConfig.java:        "size must also be increased so that the they can fetch record batches this large. " +
connect/runtime/src/test/java/org/apache/kafka/connect/runtime/distributed/WorkerCoordinatorIncrementalTest.java:        // Using onJoinComplete to register the protocol selection decided by the the broker
connect/runtime/src/test/java/org/apache/kafka/connect/runtime/distributed/WorkerCoordinatorIncrementalTest.java:        // Using onJoinComplete to register the protocol selection decided by the the broker
connect/runtime/src/test/java/org/apache/kafka/connect/runtime/distributed/WorkerCoordinatorIncrementalTest.java:        // A rebalance after the delay expires re-assigns the lost tasks the the returning member
streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java:                        // and hence we are uncertain the the current local state only contains committed data;
```

**Comment by ocadaruma** [comment]
Sure. I'll update soon

**Comment by ocadaruma** [comment]
Fixed similar typos in those files. Thanks.

**Review by rondagostino — COMMENTED** [review]
LGTM, thanks again for the PR.

**Review by kkonstantine — APPROVED** [review]
LGTM 
Typos present only in javadoc, so merging _as is_. 

Thanks @ocadaruma and @rondagostino

**Pull request merged**
