### PR TITLE
KAFKA-5531: throw concrete exceptions in streams tests

### PR DESCRIPTION
**Pull request by evis**
1. Now instead of just generic `Exception` methods declare more concrete
exceptions throwing or don't declare any throwing at all, if not needed.
2. `SimpleBenchmark.run()` throws `RuntimeException`
3. `SimpleBenchmark.produce()` throws `IllegalArgumentException`
4. Expect `ProcessorStateException` in
`StandbyTaskTest.testUpdateNonPersistentStore()`

/cc @enothereska

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5879/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5894/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by enothereska** [comment]
Excellent, thanks @evis . cc @dguy @guozhangwang . LGTM

**Review by dguy — COMMENTED** [review]
Thanks for the patch @evis. I'm not really sure of the motivation behind this JIRA, @enothereska?
This is not an API, so i'm not sure what throwing specific exceptions from the tests are buying us?

**Comment by enothereska** [comment]
@dguy there were cases when a test didn't need a `throws Exception` at all. Other cases it's clearer IMO if we enumerate exactly what exceptions a rest throws, rather than the generic Exception.

**Comment by ijuma** [comment]
Hmm, do we care which exceptions a test throws though? Note that it doesn't affect the behaviour of the test.

**Comment by ijuma** [comment]
I do agree that we should remove the throws clause if unnecessary since it's just noise. But enumerating every possible exception seems like overkill.

**Comment by enothereska** [comment]
@ijuma I am happy someone had the time to do a cleanup pass. We can discuss what needs done in the future, but I think this PR is good.

**Comment by ijuma** [comment]
@enothereska Can you elaborate the benefit of enumerating the exceptions though? The reason I'm asking is that once you merge this PR, then all future PRs will be influenced by the style in the code. And it's good to have a shared understanding when it comes to that kind of thing.

**Comment by enothereska** [comment]
@ijuma in streams, there is currently a mix of 1) `throws Exceptions` and 2) `throws SpecificException` It would be nice, but it's not a must-have, to do this consistently. It's a fair question on what best practices are. We could do it consistently by having all be (1) or (2). Again, not a show stopper either way. 

I am currently looking at exception handling end to end in streams, and I personally prefer (2). I don't think we need to codify this in checkStyle or anything like that, but @evis just did a nice job with the cleanup and I'd hate losing it.

Having said that, perhaps in cases when multiple exceptions are expected we can just throw their superclass, `Exceptions` since it might be an overkill to throw all.

**Comment by ijuma** [comment]
@enothereska, thanks for the explanation. I definitely agree that avoiding `throws Exception` in non-test code is important.

It's just for test code that I think enumerating exceptions doesn't add much. If there's a single exception, then no harm in using the more specific type.

I had a closer look at the PR and most of it is removing unnecessary declarations and that is definitely worthwhile, so I agree that we should try to merge this. I'll leave it to @dguy to decide if he is OK with merging as is or if he would prefer some changes first.

And thanks for your contribution @evis!

**Comment by enothereska** [comment]
@dguy are you ok if we keep the cleanup but whenever we have more than one specific exception we just throw `Exception`.

**Comment by enothereska** [comment]
@evis could you rebase with the latest in trunk, since it has some conflicts. Thanks.

**Comment by dguy** [comment]
Sorry @evis and @enothereska that i've only just gotten back to this. Yes, i'm ok if we throw the specific exception in the case where there is only 1. Otherwise i think we should just generalize to `Exception` as there is no point in enumerating them in the test code.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6110/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6125/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6126/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6111/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by evis** [comment]
I can't see, why JDK 8 test failed, because test details page responses with 404 Not Found. Could someone help with this? Maybe, could someone rerun test?

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
(you can rerun the tests by writing the same as I did above)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6188/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6204/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by enothereska** [comment]
The failures do not seem related to the PR. They are known.

**Comment by evis** [comment]
Thanks for info, that's good.

Could we merge PR then, while there are no conflicts?

I suggest to leave this as it is for now and merge. Then, when I'll have some time to do more cleanup, I will make another PR, where several exceptions in `throws` declaration will be generalized to `Exception`. Is it ok?

**Comment by enothereska** [comment]
Thanks ok with me. cc @dguy

**Comment by dguy** [comment]
@evis i think it would be better to generalize to Exception in this PR rather than have another PR for it.

**Comment by evis** [comment]
While generalizing, I noticed, that there is test-like method without `@Test` annotation here: https://github.com/apache/kafka/blob/trunk/streams/src/test/java/org/apache/kafka/streams/processor/TopologyBuilderTest.java#L754

Seems like annotation was accidentally removed in this commit: https://github.com/apache/kafka/commit/9198467eb293435385edcef9028a59fa41a3828a#diff-2263f162686a813ddc2ea71c8114f130

Should I return it back?

update: added it back, see a2c3ca0 commit =)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6244/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6260/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6245/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6261/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6262/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6246/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by dguy** [comment]
retest this please

**Review by dguy — APPROVED** [review]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6310/
Test FAILed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6294/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by dguy** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6299/
Test FAILed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6312/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by dguy** [comment]
sorry @evis can you please rebase this?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6543/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6529/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by guozhangwang** [comment]
@dguy can help merging this PR after it get rebased by @evis .

**Comment by mjsax** [comment]
@evis Can you rebase this PR?

**Comment by evis** [comment]
Sorry guys, I was busy during last weeks. I will rebase it on the very next days.

By the way, do you mean, that I should squash all my commits into one, or that I just need to rebase it onto current trunk branch, or maybe both?

**Comment by dguy** [comment]
@evis you can just merge with trunk and fix the conflicts

**Comment by evis** [comment]
retest this please

**Review by dguy — APPROVED** [review]
Thanks @evis. Sorry this has taken so long to merge! LGTM

**Comment by dguy** [comment]
Merged to trunk

**Comment by dguy** [comment]
@evis can you close the PR manually?. The merge script would normally do it, but i had to terminate it.

**Comment by evis** [comment]
@dguy seems like PR is already closed, isn't it?

**Comment by ijuma** [comment]
Yes, it is.

**Comment by guozhangwang** [comment]
Thanks for the contribution @evis ! And specifically for your patience.

**Pull request closed without merging**
