### PR TITLE
KAFKA-6308: Connect Struct should use deepEquals/deepHashCode

### PR DESCRIPTION
**Pull request by tobiasgies**
This changes the Struct's equals and hashCode method to use Arrays#deepEquals and Arrays#deepHashCode, respectively. This resolves a problem where two structs with values of type byte[] would not be considered equal even though the byte arrays' contents are equal. By using deepEquals, the byte arrays' contents are compared instead of ther identity.

Since this changes the behavior of the equals method for byte array values, the behavior of hashCode must change alongside it to ensure the methods still fulfill the general contract of "equal objects must have equal hashCodes".

Test rationale:
All existing unit tests for equals were untouched and continue to work. A new test method was added to verify the behavior of equals and hashCode for Struct instances that contain a byte array value. I verify the reflixivity and transitivity of equals as well as the fact that equal Structs have equal hashCodes
and not-equal structs do not have equal hashCodes. 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by tobiasgies** [comment]
Hi @ewencp, you were the last one who worked on Struct#equals and Struct#hashCode. This pull request presented for your consideration. :-)

Formalities: I have submitted a signed individual CLA to the ASF secretaries yesterday. This pull request contains my own original work, and I license it to the project under the project's open source license.

**Comment by tobiasgies** [comment]
Hm. On JDK 8, the core integration test failed in two different ways with the same code. I think I'll need help debugging this.

**Comment by rhauch** [comment]
Retest this please.

**Comment by tobiasgies** [comment]
Okay, that's definitely not transient. I'll investigate the test failures and get back to this PR when I have fixes.

**Comment by rhauch** [comment]
@tobiasgies the 2 failures with JDK 8 and Scala 2.12 are unrelated to Connect or your changes (kafka.api.SaslSslAdminClientIntegrationTest.testAlterReplicaLogDirs) -- that test sweet seems to be a bit more unreliable for whatever reason. No need to investigate these.

**Review by rhauch — APPROVED** [review]
LGTM. Thanks, @tobiasgies!

**Comment by tobiasgies** [comment]
@rhauch okay, cool! Since I didn't see any other unit test failures, does that mean the PR is ready to be merged, or is there something left for me to do?

**Comment by rhauch** [comment]
@hachikuji, this is ready for a quick review and merge. Would you mind?

**Review by hachikuji — APPROVED** [review]
LGTM. Thanks for the patch!

**Pull request closed without merging**
