### PR TITLE
KAFKA-15853: Move AuthorizerUtils and its dependencies to server module

### PR DESCRIPTION
**Pull request by OmniaGM**
Blocker for #15103 - Moving AuthorizerUtils and Session into server module

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by OmniaGM** [comment]
Hi @mimaison can you review this pr please?

**Comment by mimaison** [comment]
It's next on my list once https://github.com/apache/kafka/pull/15246 is merged. It will probably require you to rebase (sorry).

**Comment by mimaison** [comment]
FYI I merged https://github.com/apache/kafka/pull/15246 and this indeed needs rebasing

**Comment by OmniaGM** [comment]
Just rebased, it was an easy one

**Review by mimaison — APPROVED** [review]
LGTM, thanks

**Pull request merged**
