### PR TITLE
KAFKA-15222: Upgrade zinc Scala incremental compiler plugin version to a latests stable fit version (1.9.2)

### PR DESCRIPTION
**Pull request by bmscomp**
The existing version of zinc incremental scala compiler plugin is getting a bit old, upgrading to last stable version 1.9.2

From the version 1.8.0 to 1.9.2 this is a list of all changed https://github.com/sbt/zinc/compare/v1.8.0...v1.9.2  
Link to release notes : https://github.com/sbt/zinc/releases 

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by divijvaidya** [comment]
Please add link to release notes explaining the difference amongst version.

**Comment by bmscomp** [comment]
@divijvaidya I am working on it right now, I have a good resource https://github.com/sbt/zinc/compare/v1.8.0...v1.9.2

**Comment by bmscomp** [comment]
The current pull request CI, the errors related to zinc appeared again in current Jenkins build, rebasing the branch again will run the build again, the strange behaviour is that the related locked zinc file is pointing to an old version  of it 

I am checking now the behaviour of the build, wait and see

**Comment by bmscomp** [comment]
@divijvaidya  It's ok now, things seems more stable, but there is some failure on building kafak with jdk 20 that has no relation with zinc compiler, 

Notice that for all build the retry_zinc step is without issue

**Comment by bmscomp** [comment]
@divijvaidya  No breaking changes are mentioned in the release notes, meanwhile much upgrades and bug fixing are present till the version 1.8.0 I can mention the most important of them 

- Infinite Compile Fix (1.8.1)
- Fix writing zip64's offset (1.9.1)
- Update scala-compiler, scala-library to 2.13.10 to fix CVE (1.9.0)
- Use NIO to create temp file (1.8.1)

It's far better to use the new version

**Review by divijvaidya — APPROVED** [review]
Thank you for the detailed effort here! Lgtm. I will merge this tomorrow after giving other folks a chance to look into this PR

**Pull request merged**
