### PR TITLE
KAFKA-8598: Use automatic RPC generation in RenewDelegationToken

### PR DESCRIPTION
**Pull request by mimaison**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
Retest this please

**Comment by mimaison** [comment]
Retest this please

**Comment by mimaison** [comment]
@abbccdda @cmccabe Can you take a look?

**Comment by mimaison** [comment]
ping @abbccdda @cmccabe

**Review by viktorsomogyi — COMMENTED** [review]
LGTM although the test results have already been removed so I couldn't look at the few failed tests.

**Comment by mimaison** [comment]
@omkreddy Can you have a look?

**Comment by omkreddy** [comment]
@mimaison I will review both the PRs. Thanks.

**Comment by omkreddy** [comment]
@mimaison Can you please rebase the PR?

**Comment by mimaison** [comment]
@omkreddy I've rebased on trunk

**Comment by omkreddy** [comment]
retest this please

**Review by omkreddy — APPROVED** [review]
@mimaison Thanks for the PR. LGTM.

**Comment by omkreddy** [comment]
retest this please

**Pull request closed without merging**
