### PR TITLE
KAFKA-8488: guarded debug log to avoid frequent toString allocation

### PR DESCRIPTION
**Pull request by wenhoujx**
*More detailed description of your change,
guarded debug log to avoid frequent toString allocation

*Summary of testing strategy (including rationale)
no test b/c it's a trivial change to reduce TLAB allocation

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by wenhoujx** [comment]
link to the ticket: https://issues.apache.org/jira/browse/KAFKA-8488

**Review by ijuma — APPROVED** [review]
Great find, LGTM

**Comment by wenhoujx** [comment]
@cmccabe  can i get another +1 to get this merged ?

**Comment by cmccabe** [comment]
LGTM

**Pull request merged**
