### PR TITLE
MINOR: Use bootstrap-server instead of broker-list in doc

### PR DESCRIPTION
**Pull request by dengziming**
*More detailed description of your change*
As the title

*Summary of testing strategy (including rationale)*
QA

### CODE REVIEW

**Review by showuon — APPROVED** [review]
Nice catch! Thanks.

**Review by showuon — COMMENTED** [review]
@dengziming , thanks for the reminder! :)
I checked the java doc again, and I think we can improve it a little bit.

At the beginning, the sentence starts without subject, which make it hard to read.
Maybe change to:
`* A demo class to demonstrate, using the high-level KStream DSL, how to implement an IoT demo application...`

And in the 2nd topic creation, it is also hard to understand, maybe change:
// and at same time the output topic for filtered values 
-> // and at same time, create the output topic for filtered values :

and the last sentence:
// On the other side, a console producer can be used for sending temperature values (which needs to be integers) to "iot-temperature" typing them on the console :
-> On the other side, a console producer can be used for sending temperature values (which needs to be integers) to "iot-temperature" topic by typing them on the console :

WDYT?

**Comment by dengziming** [comment]
@showuon Yes, it's worth rewording some describes. I improved the 3 sentences a  little bit.

**Review by showuon — APPROVED** [review]
LGTM! Thanks for the patch!

**Comment by showuon** [comment]
Let's wait for the jenkins test completed before we merge it. Thanks.

**Comment by showuon** [comment]
failed tests are also appeared in trunk branch test results.
```
Build / JDK 11 and Scala 2.13 / org.apache.kafka.connect.integration.RebalanceSourceConnectorsIntegrationTest.testDeleteConnector
    Build / JDK 11 and Scala 2.13 / org.apache.kafka.connect.integration.RebalanceSourceConnectorsIntegrationTest.testDeleteConnector
    [Build / JDK 11 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-10832/2/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/Build___JDK_11_and_Scala_2_13___testThreadPoolResize__/)
    [Build / JDK 11 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-10832/2/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/Build___JDK_11_and_Scala_2_13___testThreadPoolResize___2/)
    [Build / JDK 11 and Scala 2.13 / kafka.network.SocketServerTest.remoteCloseWithIncompleteBufferedReceive()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-10832/2/testReport/junit/kafka.network/SocketServerTest/Build___JDK_11_and_Scala_2_13___remoteCloseWithIncompleteBufferedReceive__/)
    [Build / JDK 8 and Scala 2.12 / kafka.admin.DeleteTopicTest.testDeleteTopicWithCleaner()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-10832/2/testReport/junit/kafka.admin/DeleteTopicTest/Build___JDK_8_and_Scala_2_12___testDeleteTopicWithCleaner___2/)
    [Build / JDK 17 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-10832/2/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/Build___JDK_17_and_Scala_2_13___testThreadPoolResize__/)
    [Build / JDK 17 and Scala 2.13 / kafka.server.DynamicBrokerReconfigurationTest.testThreadPoolResize()](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-10832/2/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/Build___JDK_17_and_Scala_2_13___testThreadPoolResize___2/)
```

**Pull request merged**
