### PR TITLE
Removed unnecessary if/else clause.

### PR DESCRIPTION
**Pull request by himani1**

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by himani1** [comment]
@ijuma Thanks :)

**Comment by himani1** [comment]
@ijuma Can you please have a look ? :)

**Comment by hachikuji** [comment]
Looks like this was already fixed in #2013.

**Comment by himani1** [comment]
@hachikuji You're right. I must not have seen it, Thanks for pointing it out.

**Pull request closed without merging**
