### PR TITLE
MINOR: update release script for streams quickstart

### PR DESCRIPTION
**Pull request by dguy**

### CODE REVIEW

**Comment by dguy** [comment]
@guozhangwang these are the updates i **think** are needed for the release script. I've verified that the `sed` command works, but i don't know how i can possibly test the rest of the script.

**Comment by ijuma** [comment]
Thanks for doing this! This could be tested by doing a fake 1.0.0 RC0.

**Comment by dguy** [comment]
@ijuma the release script aborts because there are open JIRAs tagged with 1.0.0.

**Comment by ijuma** [comment]
I had forgotten about that. What I did in the past is comment out the JIRA and local changes check, which is a bit painful. Maybe we could change the script so that there's a way to ignore the JIRA check.

**Comment by guozhangwang** [comment]
There is another file where you need to remove `-SNAPSHOT`: in quickstart/java/src/main/resources/archetype-resources/pom.xml

```
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kafka.version>1.0.0-SNAPSHOT</kafka.version>
        <slf4j.version>1.7.7</slf4j.version>
        <log4j.version>1.2.17</log4j.version>
    </properties>
```

**Comment by dguy** [comment]
I've updated the release script to include the archetype-resources/pom.xml. Also fixed it so that it works and tested it (painfully)

**Comment by guozhangwang** [comment]
@dguy do you want to address @ijuma 's comment before merging this PR?

**Comment by ijuma** [comment]
We don't need to block this PR on that. Would be good to file a JIRA for it though.

**Comment by dguy** [comment]
it would be good to have `dryrun` option that skips that step and perhaps some others?

**Comment by ijuma** [comment]
@dguy yeah, something like that would be helpful.

**Comment by dguy** [comment]
I created: https://issues.apache.org/jira/browse/KAFKA-5939

**Comment by guozhangwang** [comment]
Merged to trunk.

**Pull request closed without merging**
