### PR TITLE
KAFKA-12393: Document multi-tenancy considerations

### PR DESCRIPTION
**Pull request by miguno**
* KAFKA-12393: Document multi-tenancy considerations
* Addressed review feedback by @dajac and @rajinisivaram

Ported from https://github.com/apache/kafka-site/pull/334

### CODE REVIEW

**Comment by miguno** [comment]
cc @bbejeck

**Comment by bbejeck** [comment]
~This is a port of https://github.com/apache/kafka-site/pull/334 already merged to kafka-site~

I didn't see @miguno's comment above referencing the kafka-site PR before.

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
Merged #10263 into trunk

**Comment by bbejeck** [comment]
cherry-picked to 2.8

**Pull request merged**
