### PR TITLE
KAFKA-8952: Update Jackson to 2.10.0

### PR DESCRIPTION
**Pull request by ijuma**
Guava hasn't been upgraded due to potential incompatibility with the reflections
library:

https://github.com/ronmamo/reflections/issues/194

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by omkreddy — APPROVED** [review]
@ijuma Thanks for the PR. LGTM.  

KAFKA-8952 also mentions guava-20.0.jar. Should we do anything about it? 
Its coming from org.reflections:reflections jar. 
 
 ```
 +--- org.reflections:reflections:0.9.11
|    +--- com.google.guava:guava:20.0
```

**Comment by ijuma** [comment]
@omkreddy That one is more complicated since reflections doesn't necessarily work with newer versions of guava:

https://github.com/ronmamo/reflections/issues/194

**Comment by ijuma** [comment]
Merging to trunk, 2.3 and 2.2 branches.

**Comment by Namrata3991** [comment]
@ijuma, Thank you for the changes, When can I get the binary for these changes on kafka official site?

**Comment by mumrah** [comment]
@NamrataKokate keep an eye on the mailing list for release announcements. Bugfix releases 2.3.1 and 2.2.2 are currently in progress.

**Pull request merged**
