### PR TITLE
KAFKA-3385: Need to log "Rejected connection" as WARNING message

### PR DESCRIPTION
**Pull request by oscerd**
Hi all,

This PR is related to:
https://issues.apache.org/jira/browse/KAFKA-3385

Thanks,

Andrea

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. It's not clear to me if this should be a warning at the broker level as it doesn't necessarily indicate that there's something wrong. Let's hear what others think though.

**Comment by oscerd** [comment]
Hi, Let me know if I have to modify in some way :-)

**Comment by oscerd** [comment]
It is the only place where we have a log sentence like this. So I just changed from info to warn.

**Comment by oscerd** [comment]
Any news on this PR? If there is something else to do, I can work on this.

**Comment by oscerd** [comment]
News?

**Comment by oscerd** [comment]
Is there any interest around this PR?

**Pull request closed without merging**
