### PR TITLE
KAFKA-5523: Remove ReplayLogProducer tool

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ijuma — COMMENTED** [review]
Thanks for the PR, can you please fix the merge conflict?

**Comment by omkreddy** [comment]
@ijuma Fixed the merge conflict.

**Comment by omkreddy** [comment]
@ijuma Pls take a look.

**Review by ijuma — APPROVED** [review]
LGTM

**Pull request merged**
