### PR TITLE
MINOR: make it more explicit that poll() call is needed for the callback to run

### PR DESCRIPTION
**Pull request by norwood**
@hachikuji

### CODE REVIEW

**Review by hachikuji — COMMENTED** [review]
Thanks for the patch. Do you think it's worth mentioning this point in the `subscribe` javadoc as well?

**Review by hachikuji — APPROVED** [review]
LGTM. Will add a brief note to the subscribe API before merging.

**Comment by norwood** [comment]
👍

**Review by ijuma — APPROVED** [review]
LGTM

**Pull request merged**
