### PR TITLE
MINOR: Add unit tests for StreamsRebalanceListener

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @vvcephei @guozhangwang @mjsax @ableegoldman @wcarlson5 @abbccdda

**Comment by cadonna** [comment]
Retest this please

**Comment by cadonna** [comment]
The following tests failed for JDK 15:

```
kafka.network.ConnectionQuotasTest.testNoConnectionLimitsByDefault
```

The following tests failed for JDK 8:

```
org.apache.kafka.streams.integration.EosBetaUpgradeIntegrationTest.shouldUpgradeFromEosAlphaToEosBeta[true] 
org.apache.kafka.streams.integration.PurgeRepartitionTopicIntegrationTest.shouldRestoreState
```

**Review by wcarlson5 — APPROVED** [review]
this covers all the cases I can think of

**Comment by guozhangwang** [comment]
LGTM!

**Pull request merged**
