### PR TITLE
KAFKA-4827: Porting fix for KAFKA-4827 to v0.10 and v0.11

### PR DESCRIPTION
**Pull request by wicknicks**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.10/3779/
Test PASSed (JDK 7 and Scala 2.10).

**Comment by wicknicks** [comment]
@ewencp, @rhauch: we got two builds to pass here. The JDK 9 failed because the Gradle env var issue, and JDK 8 failed because of some tests in streams. I don't think my changes affect streams. If you guys think its fine, we can go ahead and merge these commits into 0.10 and 0.11. Thanks!

**Comment by ewencp** [comment]
Thanks @wicknicks, I've also manually verified things pass across the 0.11.0, 0.10.2, 0.10.1, and 0.10.0 branches this will get merged to. LGTM!

**Comment by ewencp** [comment]
@wicknicks Also, you might need to close out the PRs yourself.

**Comment by wicknicks** [comment]
Closing this ticket, as @ewencp merged all the changes. Thanks!

**Pull request closed without merging**
