### PR TITLE
KAFKA-6917: Process txn completion asynchronously to avoid deadlock

### PR DESCRIPTION
**Pull request by rajinisivaram**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by hachikuji — APPROVED** [review]
Thanks @rajinisivaram, LGTM.

**Comment by hachikuji** [comment]
I'll plan to merge back to 1.0 as soon as the build completes.

**Review by guozhangwang — APPROVED** [review]
This is a nice find, thanks @rajinisivaram !

Made a quick pass over all other call traces on `tryCompleteDelayedRequests`, I'm wondering if we should do the same for these calls:

1. `TransactionStateManager#removeFromCacheCallback`: triggerable from `enableTransactionalIdExpiration -> replicaManager.appendRecords`.

2. `updateCacheCallback`, similarly triggerable in `appendTransactionToLog -> replicaManager.appendRecords`.

3. `putCacheCallback`: we have two functions with the same name in `GroupMetadataManager`: again, could be triggerable in `storeGroup` and `storeOffsets`.

**Comment by hachikuji** [comment]
@guozhangwang In the transaction coordinator, do we have any cases where we call `appendRecords` while holding a transaction metadata lock? It seemed safe when I looked, but I could have missed something.

**Comment by rajinisivaram** [comment]
The failures for JDK8 look unrelated - looks like a JAAS configuration issue because of missing cleanup in some test, such an issue would only get cleared in the next test that uses SASL, so all the tests in AuthorizerIntegrationTest failed.

**Comment by rajinisivaram** [comment]
@hachikuji @guozhangwang Thanks for the reviews. Like @hachikuji, I had also looked at the methods and thought that the others are safe since transaction metadata lock is never held while calling `appendRecords`. Other callbacks which use group lock use the group lock as the delayed operation lock and callbacks which use state lock use the state lock as the delayed operation lock. But this code is so hard to read that it is easy to miss things. If we have missed some cases, I am happy to update the code. I think we should add more tests anyway for all these cases, will do that in a follow-on PR unless the implementation needs to change.

**Comment by rajinisivaram** [comment]
retest this please

**Comment by hachikuji** [comment]
Yeah, I agree with Rajini that reading this code can be a slog. I think we need to simplify the model that we use for the coordinators. I rather like the single-threaded approach used by the controller. If all the events affecting each partition are only handled by one thread, then all of these locks can go away. It's safer and easier to reason about. I'm not sure we actually need a super high degree of parallelism for any of the coordinator APIs.

**Comment by hachikuji** [comment]
I'll go ahead and merge this. We can discuss separately whether we need a follow-up for the points @guozhangwang mentioned above.

**Comment by guozhangwang** [comment]
I've looked at the code again, here's my reasoning:

1. `enableTransactionalIdExpiration` schedule a task in background thread that `inReadLock(stateLock)` but no group lock, and then inside the state lock it calls `appendRecords`. This looks good.

2. `groupManager.storeGroup` calls `appendRecords`, and then in its callback grabs the lock on group; through the process only one lock of the group is required. It looks good.

3. `appendTransactionToLog`, same as 1) we only hold statelock while calling `appendRecords`.

So I agree that these are all safe; would be great if we can add some more unit test coverage.

**Pull request merged**
