### PR TITLE
KAFKA-3431: Remove `o.a.k.common.BrokerEndPoint` in favour of `Node`

### PR DESCRIPTION
**Pull request by ijuma**
Also included a minor efficiency improvement in kafka.cluster.EndPoint.

### CODE REVIEW

**Comment by ijuma** [comment]
This is an alternative to https://github.com/apache/kafka/pull/1102 as per @gwenshap's suggestion.

**Comment by gwenshap** [comment]
LGTM.

I think it is better to get rid of that redundancy. 

Next step would be to get rid of kafka.cluster.BrokerEndPoint, which is also a duplicate :)

**Comment by guozhangwang** [comment]
I'd also prefer this PR. Sorry for jumping on this late @ijuma .

**Comment by ijuma** [comment]
That's good @guozhangwang as Gwen merged this one. :)

**Pull request closed without merging**
