### PR TITLE
KAFKA-10835: Replace Runnable and Callable overrides with lambdas in Connect

### PR DESCRIPTION
**Pull request by levzem**
Signed-off-by: Lev Zemlyanov <lev@confluent.io>

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

change interfaces to lambdas

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

unit as this is purely stylistic change

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by kkonstantine — COMMENTED** [review]
That's a great reduction of boiler plate.

Seeing the changes were quite a few I have to say we might need separate PRs for backporting to previous release branches. But let's see after we merge this one. 
The failures were not relevant (jdk 11 passed, 8 and 15 failed on kafka.api and a streams test). I triggered another run.

**Comment by ijuma** [comment]
@kkonstantine We should not backport changes like this to older branches IMO. We should stick to important bug fixes for older branches.

**Comment by kkonstantine** [comment]
@ijuma what are trying to achieve here with backporting is to have a similar basis for other future bugfixes that _will have to_ be applied to both the new and the old branches. Otherwise the conflicts will be a lot and possibly frequent.  
The purpose of these changes is to have very low risk. Wdyt?

**Comment by ijuma** [comment]
I understood the intent, but I don't think it's worth it, personally. Backports are not meant to be frequent, so I don't see why there would be frequent conflicts. For clients and core, we never backport readability improvements and it has generally not been an issue.

**Comment by kkonstantine** [comment]
I'm a bit surprise to hear that this doesn't come up with cherry-picks. In Connect we backport any bugfix, usually 2-3 releases back. I believe it would be a challenge to cherry-pick such a fix if it didn't map to similar lines. @rhauch had recommended similar cleanups and I think he also shared the view that backporting would be better than not.

**Review by kkonstantine — APPROVED** [review]
LGTM

Few test failures that are not relevant. Tests are all passing locally. 

Merging only on `trunk` due to the extent of the changes and to eliminate risk on patch versions. 

Thanks @levzem !

**Pull request merged**
