### PR TITLE
KAFKA-2752: Follow up to fix checkstlye

### PR DESCRIPTION
**Pull request by granthenke**

### CODE REVIEW

**Comment by ewencp** [comment]
Sorry about that @granthenke, not sure how I missed that. LGTM.

**Comment by guozhangwang** [comment]
Cherry picking to 0.9.0 failed with some conflicts, will do an manual commit.

EDIT: since 2752 is not committed to 0.9.0, we do not need to cherry pick it either.

**Comment by granthenke** [comment]
@ewencp not a problem at all. The builds are taking longer and longer, and on Jenkins they are piling up. I have added failing fast to the build refactoring work I am doing for KAFKA-2787. See the initial work in #477.

That way waiting for the build to commit wont be as painful.

**Comment by ewencp** [comment]
@granthenke Awesome, those will be very welcome improvements. Moving rat up to run earlier probably isn't too bad since people aren't adding new files that often. I'd be wary about making too much stuff fail fast though -- checkstyle in particular is really annoying if it runs before tests.

**Comment by ewencp** [comment]
@guozhangwang 2752 didn't go on 0.9.0, it shouldn't need cherry-picking

**Pull request closed without merging**
