### PR TITLE
MINOR: Updated SASL Authentication Sequence Docs

### PR DESCRIPTION
**Pull request by mimaison**
Reworded the SASL Authentication sequence to update it to >= 1.0.0

Co-authored-by: Edoardo Comar <ecomar@uk.ibm.com>
Co-authored-by: Mickael Maison <mickael.maison@gmail.com>

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by edoardocomar** [comment]
@rajinisivaram would you like to review ?

**Review by rajinisivaram — APPROVED** [review]
@edoardocomar @mimaison Thanks for the PR, LGTM. Merging to trunk, 1.1 and 1.0.

**Comment by edoardocomar** [comment]
Thanks @rajinisivaram 

the script using for merging the PR should keep the `Co-authored-by:` on two separate lines instead of putting them on a single line
so that each author would have a +1 commit count

**Comment by rajinisivaram** [comment]
@edoardocomar Sorry, I hadn't realized that and had copied them to one line while merging directly from here. Will remember for next time though. Thanks.

**Pull request merged**
