### PR TITLE
KAFKA-4862: Kafka client connect to a shutdown node will block for a long time

### PR DESCRIPTION
**Pull request by pengwei-li**
Author: pengwei <pengwei.li@huawei.com>

Reviewers: Jiangjie Qin <becket.qin@gmail.com>
                @becketqin 

Modify: Add a connect timeout for the kafka client to avoid long blocking if
network is down

### CODE REVIEW

**Comment by becketqin** [comment]
@pengwei-li Thanks for the patch. We probably need a KIP for this because a new configuration is added. Can you create one?

**Comment by pengwei-li** [comment]
@becketqin  This patch I thought is a bug fixed,  I can create a new KIP if needed.

**Comment by becketqin** [comment]
@pengwei-li Sorry for the late reply. Yes, we do need a KIP for a new configuration.

**Comment by pengwei-li** [comment]
@becketqin  I have submit a KIP for this PR, can you have a look?
https://cwiki.apache.org/confluence/display/KAFKA/KIP+143%3A+Add+a+connect+timeout+for+client

**Comment by becketqin** [comment]
@pengwei-li Thanks for the KIP. I changed the KIP number and added it to the KIP table.
If you want to have the KIP discussed in the open source community, can you send an email to dev@kafka.apache.org with the subject "[DISCUSS] KIP-148" Add a connect timeout for client" to initiate a discussion thread? After doing that you may also want change the discussion thread link in the you KIP wiki.

**Comment by pengwei-li** [comment]
@becketqin  Thanks for the  comment. I have use KIP-143 as the discussion thread, I will change the KIP number to 148.

**Comment by aakarsh** [comment]
This patch seem to be an year old, what is the current status of this patch?

**Comment by pengwei-li** [comment]
@aakarsh  I will update the patch using the new branch code. Thanks for the remind

**Comment by jannnci** [comment]
what is the current status of this patch?

**Comment by pengwei-li** [comment]
@jannnci I start to vote for this KIP-148, but now not approve yet.  So this patch not merge yet

**Comment by jannnci** [comment]
@pengwei-li I like this patch, but for now I don't know how to vote for this patch. But anyway I think they can not merge this because of conflicting files.

**Comment by pengwei-li** [comment]
@jannnci thanks for your like, you can reply the vote in the KIP-148's mailing list.  I can update the merge to fix the conflicts

**Comment by pengwei-li** [comment]
@jannnci  I have update the patch。
The KIP is:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-148%3A+Add+a+connect+timeout+for+client

**Comment by pengwei-li** [comment]
@becketqin hi Becket, can you have a look for this KIP ? What do I need to do next? Now some guys like this KIP but this KIP is not approve yet.  Thanks

**Comment by thomaslee** [comment]
@pengwei-li thanks for putting this together. Would you mind if I cleaned up this PR and made another push to get it landed? I'm a little sad to see it languishing -- we've been forced to roll out sysctl changes to work around the absence of this feature.

**Comment by ijuma** [comment]
I believe KAFKA-9893 has fixed this. Please reopen if not.

**Pull request closed without merging**
