### PR TITLE
KAFKA-3508: Fix transient SimpleACLAuthorizerTest failures

### PR DESCRIPTION
**Pull request by granthenke**
Allows the the maximum retires when writing to zookeeper to be overridden in tests and sets the value to Int.MaxValue to avoid transient failure.

### CODE REVIEW

**Comment by granthenke** [comment]
This was mentioned in #1138

**Comment by ijuma** [comment]
Thanks @granthenke. Were you able to reproduce the transient failure before this PR, but no longer after the PR?

**Comment by granthenke** [comment]
I am not able to reproduce the failure locally on my machine. I looked up the failure on Jenkins ([here](https://builds.apache.org/job/kafka-trunk-git-pr-jdk7/3085/testReport/junit/kafka.security.auth/SimpleAclAuthorizerTest/testHighConcurrencyModificationOfResourceAcls/)) and the failure is due to too many retries. I suspect this is occurring because of the load on the Jenkins machine. I think lowering the number of concurrent request from 100 to 50 should help prevent this while still maintaining the validity of the test. If we still see issues after this I will definitely look into it deeper.

**Comment by ijuma** [comment]
OK, LGTM then. Even though this is not guaranteed to fix it, it should improve things (in the worst case, it will remain the same).

**Comment by granthenke** [comment]
cc @gwenshap @ewencp

**Comment by ewencp** [comment]
@granthenke Isn't the test simply incorrect since it's asserting something that isn't always true? It seems like its valid to sometimes see an exception as we do here unless we use infinite retries on the `SimpleAclAuthorizers` instance. We don't make any intermediate assertions as far as I can tell, so wouldn't simply adjusting the # of retries result in effectively the same test? Alternatively, catching the specific type of exception `IllegalStateException`, but make sure any other exception is considered a failure (e.g., I guess this would possibly catch something like a `ConcurrentModificationException`).

**Comment by granthenke** [comment]
@ewencp This test was written before the retires code was suggested. It was written validate the state of the acls is correct under high concurrency. We could catch the exception and pass the test, though thats would skip validating the state. Ideally the retry limit would never be reached, especially in real world use.  It was suggested as a safe guard just in case.

**Comment by ewencp** [comment]
@granthenke Ok, I'm fine committing this to reduce the current set of exceptions, but this still seems weird to me. Given the current code, the comment on `SimpleAclAuthorizer.maxUpdateRetries` isn't really accurate either, is it? You can definitely hit contention for the resource's zk nodes and an exception _should_ be expected under high enough contention. I agree this should be rare in practice and ACL changes really shouldn't be made that quickly, but certainly not impossible.

More generally my question is now: what exactly are we trying to test with this particular unit test? That there aren't any concurrency bugs? Or that arbitrary interleavings of ACL operations still result in the same output? I get that the test makes sense if you have infinite retries, but it seems like what it is testing necessarily has to change if infinite retries were removed.

**Comment by granthenke** [comment]
@ewencp The goal of the test is to validate that arbitrary interleaving of ACL operations (due to high concurrency) still result in correct output. Before the patch, ACLs would be dropped and state was lost. The patch aimed to fix and test that. 

Should I make the maxUpdateRetries changeable so that I can validate it with infinite retries? Otherwise I am not sure I can control or pick a good number.

**Comment by granthenke** [comment]
@ewencp pinging for an update

**Comment by ewencp** [comment]
@granthenke Yeah, that was what I was getting at -- it seems like the only way to make the test pass reliably with its current structure. I'm open to other approaches too, I just felt like changing the number and hoping that's good enough to avoid hitting the max # of retries seemed like an unreliable solution (but perhaps perfectly fine temporary stopgap).

**Comment by ijuma** [comment]
I would prefer a configurable retry number too, personally.

**Comment by granthenke** [comment]
@ijuma @ewencp I made the retries configurable and set it to Int.MaxValue in the tests. Do you think this needs a KIP since its a "public" config? Or is it small enough to skip?

**Comment by ijuma** [comment]
@granthenke I was thinking of doing it without exposing the config. e.g.:

`protected[auth] def maxUpdateRetries = ...`

Then, we can override the method in the test (a constructor param could also be used, but it would require a secondary no-args constructor and I prefer to avoid those in Scala).

**Comment by granthenke** [comment]
@ijuma I could definitely do that. I chose to expose it as a public configuration because I was already on edge about exposing it and this test failure helped show that a user may want to have a higher value too. Especially because my initial implementation was unlimited. Often I find that if something needs to be exposed in tests its likely its useful to expose it for general use too.

**Comment by ijuma** [comment]
@granthenke I'm not sure, it seems unlikely that users would be adding ACLs with a large number of threads simultaneously. I think a config like this would require a KIP indeed.

**Comment by granthenke** [comment]
@ijuma I agree it may not be common. But that situation is why max retries was suggested and added. Its also why the test exists. Its threads in the test case, but its individual users or applications in real usage. In the case it is an issue it would be nice for a user to be able to resolve it. 

I am weighing that against the potential "harm" having a public config could have and it feels like adding a config is simple and has very little downside. Are there any major drawbacks you see to having a configuration?

**Comment by ijuma** [comment]
@granthenke If the operation fails after max retries, users are free to back-off and try again, right?. It's a good enough workaround for the uncommon case. This is why max retries was suggested IMO, we want to let users decide instead of continuously retrying.

We could change the test to do something similar if we want, but the test is a stress test and so it seemed like continuously retrying would be OK for the test.

Adding a config is not a simple thing, unfortunately. It has serious downsides. Each config we add, we make it harder for users to correctly configure the system. Kafka suffers from this problem today even though there is a concerted effort not to add new configs (imagine how bad it would be if there wasn't).

**Comment by ewencp** [comment]
@ijuma @granthenke I don't think we should necessarily expose the config to users per se, I'd treat it as public for testing only (and comment appropriately).

**Comment by granthenke** [comment]
@ewencp Are you suggesting using the protected variable like @ijuma suggested? Or leaving the config property but documenting it?

**Comment by ijuma** [comment]
My take is that public for testing is sometimes unavoidable in Java, but is generally avoidable in Scala due to its support for richer access control modifiers.

**Comment by granthenke** [comment]
@ijuma @ewencp I changed the patch to use a protected variable

**Comment by ijuma** [comment]
Thanks @granthenke, LGTM.

**Comment by ewencp** [comment]
LGTM too. Sorry this seemingly trivial patch resulted in so much discussion @granthenke :/

**Pull request closed without merging**
