### PR TITLE
KAFKA-2931: add system test for consumer rolling upgrades

### PR DESCRIPTION
**Pull request by hachikuji**

### CODE REVIEW

**Comment by hachikuji** [comment]
@guozhangwang Notice the small bug in ConsumerCoordinator. We need to use a LinkedHashMap to ensure the order of the configured assignment strategies. Might be nice to pull this into 0.9.0.

**Comment by ijuma** [comment]
@hachikuji good work spotting that bug. Would it be easy to write or modify a unit test to verify the behaviour? It's subtle and it seems overkill to have to run the system tests to detect it (the system tests are useful for other reasons, of course).

On a more general note, I think it's better to avoid methods like AbstractCoordinator.metadata() where we return a LinkedHashMap to indicate that ordering is important. It's too easy to make a mistake like the one fixed in this PR. I personally prefer using List for those cases as it's less error-prone (unless we really care about constant time get).

**Comment by hachikuji** [comment]
@ijuma Yeah, we should have caught this in a unit test. I'll see if i can add a test case now. And I agree with your sentiment on the metadata() method. It was annoying when writing the initial patch to create yet another wrapper class so that we had something to put in the list, but perhaps we should just do it.

**Comment by ijuma** [comment]
@hachikuji I understand, it's times like this where tuples are really handy (Java, I know). Thanks for looking into the unit test.

**Comment by hachikuji** [comment]
Addressed @ijuma's review comments.

**Comment by ijuma** [comment]
@hachikuji LGTM

**Comment by guozhangwang** [comment]
LGTM. Merged to trunk.

**Comment by hachikuji** [comment]
@guozhangwang Any chance we can get the fix pulled into 0.9.0?

**Comment by guozhangwang** [comment]
@hachikuji I got a conflict while trying to cherry-pick, could you take a look what is missing there?

**Comment by ijuma** [comment]
@guozhangwang @hachikuji We haven't been backporting system tests, so that may be the problem. Maybe a backport PR could be done without the system test (if it is indeed the issue).

**Comment by hachikuji** [comment]
@ijuma @guozhangwang Yeah, it looks like the conflict is in verifiable_consumer.py (one of Ben's fixes hasn't been pulled into 0.9.0). I'm not sure it helps, but I actually split this PR into two separate commits. The first one has the changes to system tests, the latter fixes the problem in the client code. Can we cherry-pick only the latter commit?

**Comment by guozhangwang** [comment]
@hachikuji Makes sense, but I merged in this PR as a single commit and hence cannot cherry pick only one of them. Could you file another PR?

**Comment by ijuma** [comment]
@hachikuji yeah, it's possible to cherry-pick a56e9f7c8334126f3439a313eb3559fcd477b686 alone, but this commit hasn't been processed by the merge script (which does a few things for us). You should be able to create a PR targetting 0.9.0 by cherry-picking it yourself though. Then @guozhangwang can merge that PR with the merge script.

**Comment by hachikuji** [comment]
@guozhangwang The new PR is #630.

**Pull request closed without merging**
