### PR TITLE
KAFKA-12864: Move KafkaEventQueue into server-common

### PR DESCRIPTION
**Pull request by cmccabe**
Move the KafkaEventQueue into server-common. Since it is a generic data structure not specific to metadata, it fits better into the server-common gradle module than into the metadata module.

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for the PR. Can we please include the motivation?

**Comment by ijuma** [comment]
Are we using these classes from any module besides metadata atm?

**Review by mumrah — APPROVED** [review]
LGTM pending tests, thanks @cmccabe 👍

**Comment by ijuma** [comment]
I would personally not move these classes unless we believe we will use them from other modules. They're a bit specialized, especially the timeline ones.

**Comment by cmccabe** [comment]
> I would personally not move these classes unless we believe we will use them from other modules. They're a bit specialized, especially the timeline ones.

`KafkaEventQueue` is already used in `core`. It's just an event queue; there is nothing metadata-specific about it, so I think it belongs in `server-common`. The timeline data structures are not used anywhere else, however.

I will revise the PR to move just the queue and not the timeline data structures.

**Comment by ijuma** [comment]
Makes sense. Thanks!

**Comment by cmccabe** [comment]
OK. Thanks for the reviews. I will commit after Jenkins runs if there are no objections

(current PR just moves KafkaEventQueue)

**Review by ijuma — APPROVED** [review]
LGTM. Let's update the PR description and commit message too.

**Pull request merged**
