### PR TITLE
HOTFIX: Fix header in ByteArrayConverter

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
cc @ewencp

**Comment by omkreddy** [comment]
+1

**Comment by ijuma** [comment]
Merged to trunk since the fix is trivial and it fixes the build.

**Comment by ewencp** [comment]
LGTM. Sorry about that, I knew that stricter check would come back to bite us on an older PR, just wasn't expecting it to be mine :)

**Comment by ijuma** [comment]
@ewencp thanks for the review, you were awake earlier than I expected. :)

**Pull request closed without merging**
