### PR TITLE
enhance JmxTool usage and output format

### PR DESCRIPTION
**Pull request by scottf**
one-time flag to only run the pull once instead of looping forever
reporting-interval -1 equivalent to setting one-time
reportFormatOpt supports 'original', 'properties', 'csv', 'tsv' formatting

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6302/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6304/
Test PASSed (JDK 8 and Scala 2.12).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6323/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6320/
Test PASSed (JDK 7 and Scala 2.11).

**Comment by guozhangwang** [comment]
retest this please

**Review by guozhangwang — APPROVED** [review]
Made a pass over the PR. The change LGTM. I think this change also fixes KAFKA-1972.

Waiting for the unit test to pass.

**Pull request closed without merging**
