### PR TITLE
MINOR: Get console output in quickstart examples

### PR DESCRIPTION
**Pull request by lucasbru**
Quickstart examples didn't produce any console output, since it was missing a logger implementation in the classpath.

Also some minor cleanups.

Tested by creating a test project and running the code.

### Committer Checklist (excluded from commit message)
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by lucasbru** [comment]
@cadonna would you want to have a look?

**Comment by lucasbru** [comment]
Test failures are unrelated

**Review by bbejeck — APPROVED** [review]
Thanks for the fix @lucasbru, LGTM

**Comment by bbejeck** [comment]
Failure unrelated merging

**Comment by bbejeck** [comment]
merged #12719 into trunk

**Pull request merged**
