### PR TITLE
MINOR: Correct the wrong comment which confuse me.

### PR DESCRIPTION
**Pull request by maobaolong**
sessionTimeout mean we mark the coordinator unknown, i dont know what the comment there means.

### CODE REVIEW

**Comment by maobaolong** [comment]
@cadonna  Please take a look, it is my first PR here, it means that i could make some low level mistakes, feel free to point it to me, any reply will be appreciated, thank you.

**Comment by cadonna** [comment]
@maobaolong Thank you for the PR.
I do not know well this code, thus I would like to call @hachikuji and @guozhangwang for review.

FWIW, I would remove the comment completely. Your comment duplicates the information that is contained in the names of the method calls `heartbeat.sessionTimeoutExpired(now)` and `markCoordinatorUnknown()`. If the information in the method calls is not correct, the method should be renamed to something more meaningful, IMO. Code comments are hard to maintain and start to be incorrect eventually.

**Comment by maobaolong** [comment]
@cadonna  What you said is make sense. I remove the useless comments.

**Review by stanislavkozlovski — CHANGES_REQUESTED** [review]
The comment makes sense to me. What is unclear, @maobaolong ?

**Comment by maobaolong** [comment]
> The comment makes sense to me. What is unclear, @maobaolong ?

@stanislavkozlovski  I remove the comment completely, because the logic ls clear, no need any comment here, no comment is better than a mistake comment here, the origin comment is really confuse me.

And you can show me your suggestion, i think you want me to correct the function name here or do something other than removing comment?

Thank you for your review comment.

**Comment by guozhangwang** [comment]
@maobaolong The main motivation for leaving the comment is to avoid the actual code being modified / removed in the future, so I feel it is better leaving the comment there.

**Comment by maobaolong** [comment]
@guozhangwang  Ok, thank you to tell me the truth, it is better to leaving the comment there

**Pull request closed without merging**
