### PR TITLE
KAFKA-16942 Use ConcurrentHashMap in RecordAccumulator#nodeStats

### PR DESCRIPTION
**Pull request by brandboat**
related to https://issues.apache.org/jira/browse/KAFKA-16942

per discussed in https://github.com/apache/kafka/pull/16231#discussion_r1635345881

Through the ConcurrentMapBenchmark, we observed that in scenarios where write operations (i.e., computeIfAbsent) constitute 10%, the get performance of CopyOnWriteMap is lower compared to ConcurrentHashMap. However, when iterating over entrySet and values, CopyOnWriteMap performs better than ConcurrentHashMap.

In RecordAccumulator#nodeStats, the computeIfAbsent method is rarely triggered, and we only use the get method to read data. Therefore, switching to ConcurrentHashMap would gain better performance.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gongxuanzhang** [comment]
I agree, with the development of Java, the performance of ConcurrentHashMap has indeed significantly improved

**Comment by chia7712** [comment]
look into the use case of `nodeStats`: the number of node should be less than number of "get" very much. Hence, we need to go back to benchmark to reduce the number of `writePerLoops` to test "get" again. 10% updated is a bit weird to me for this case.

**Comment by brandboat** [comment]
> look into the use case of nodeStats: the number of node should be less than number of "get" very much. Hence, we need to go back to benchmark to reduce the number of writePerLoops to test "get" again. 10% updated is a bit weird to me for this case.

Test with writePercentage 0.01 (100 times of computeIfAbsent) and 0.0001 (10 times of computeIfAbsent), though there is not much difference under 0.0001, ConcurrentHashMap still performs slightly better than CopyOnWriteMap.

```
Benchmark                                              (mapSize)  (writePercentage)  Mode  Cnt     Score     Error  Units
ConcurrentMapBenchmark.testConcurrentHashMapGet              100               0.01  avgt    5     3.871 ±   0.149  ns/op
ConcurrentMapBenchmark.testConcurrentHashMapGet              100             0.0001  avgt    5     2.259 ±   0.138  ns/op
ConcurrentMapBenchmark.testConcurrentHashMapGetRandom        100               0.01  avgt    5     6.320 ±   0.231  ns/op
ConcurrentMapBenchmark.testConcurrentHashMapGetRandom        100             0.0001  avgt    5     4.070 ±   0.669  ns/op

ConcurrentMapBenchmark.testCopyOnWriteMapGet                 100               0.01  avgt    5    57.898 ±   1.769  ns/op
ConcurrentMapBenchmark.testCopyOnWriteMapGet                 100             0.0001  avgt    5     2.767 ±   0.126  ns/op
ConcurrentMapBenchmark.testCopyOnWriteMapGetRandom           100               0.01  avgt    5    61.361 ±   1.903  ns/op
ConcurrentMapBenchmark.testCopyOnWriteMapGetRandom           100             0.0001  avgt    5     4.270 ±   0.234  ns/op
```

**Comment by chia7712** [comment]
> Test with writePercentage 0.01 (100 times of computeIfAbsent) and 0.0001 (10 times of computeIfAbsent), though there is not much difference under 0.0001, ConcurrentHashMap still performs slightly better than CopyOnWriteMap.

If there is no much benefit to use `ConcurrentHashMap`, maybe we should keep using `CopyOnWriteMap` for consistency

**Comment by brandboat** [comment]
> If there is no much benefit to use ConcurrentHashMap, maybe we should keep using CopyOnWriteMap for consistency

I'm fine with this one, indeed it is a bit weird to keep both CopyOnWriteMap and ConcurrentHashMap in the same place.

**Pull request closed without merging**
