### PR TITLE
MINOR: Clean up ThreadCacheTest

### PR DESCRIPTION
**Pull request by bbejeck**
Minor clean up  of`ThreadCacheTest`

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @guozhangwang @mjsax @vvcephei @ableegoldman for review

**Review by guozhangwang — APPROVED** [review]

**Comment by mjsax** [comment]
Java11 failed with environmental error.
Java8 passed.

Retest this please.

**Review by mjsax — APPROVED** [review]
LGTM. Feel free to merge after Jenkins passed.

**Comment by bbejeck** [comment]
Merged #6485 to trunk.

**Pull request merged**
