### PR TITLE
MINOR: Added ">" prompt in examples where kafka-console-producer is used

### PR DESCRIPTION
**Pull request by ppatierno**

### CODE REVIEW

**Comment by ppatierno** [comment]
@ijuma I think this PR is really trivial that we could include in the 1.0.0 release for having a documentation consistent with the tool output

**Comment by ppatierno** [comment]
@guozhangwang maybe you can review this trivial doc related PR ?

**Comment by guozhangwang** [comment]
@ppatierno Actually the `>` is not added intentionally, as in default bash settings sysout does not have the cmd prefix. Do you have a specific motivation for this change?

**Comment by ppatierno** [comment]
@guozhangwang what I read from the bash documentation (on my Fedora distro) is that : 

PS2    The value of this parameter is expanded as with PS1 and used as the secondary prompt string.  The default is ``> ''.

And it's true even on an Ubuntu distro which has "dash" instead of "bash".
Finally it seems to be true even on a Mac (with bash).

**Comment by guozhangwang** [comment]
I see. That is right.

However, if we add the `>` to messages sys.in then we cannot distinguish the cmd for starting the console-producer with the lines to input the messages as they both have PS2 symbol. I think we intentionally used PS2 instead of PS1 for cmd prompt as it is agnostic to environments.

So I'd suggest we just add a one-liner at the first occurrence instead, stating that we intentionally customize PS1 and PS2 to `>` and empty string?

**Comment by ppatierno** [comment]
sorry but what do you mean by "a one-liner at the first occurrence instead" ?

**Comment by guozhangwang** [comment]
Sorry for the confusion. What I meant is to state explicitly before the example outputs that we intentionally customized `PS1` and `PS2` for illustration purposes.

**Comment by ppatierno** [comment]
@guozhangwang sorry for the delay ! At this point we can say that such configuration about `PS1` and `PS2` is not valid for the quick start guide (consumer, producer, ...) only but even for all the other pieces of code we have in the Kafka documentation. If we want to highlight this configuration we should do that at the top of the documentation but I don't know if it makes sense. Or we want just close this PR because not other people are complaining about that ? Wdyt ?

**Comment by guozhangwang** [comment]
Given the first-priority purposes of code snippet illustration is for easy understanding I'm ok with closing this PR.

**Pull request closed without merging**
