### PR TITLE
KAFKA-15853: Refactor org.apache.kafka.server.config.Defaults to follow Java config pattern

### PR DESCRIPTION
**Pull request by OmniaGM**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by OmniaGM** [comment]
@ijuma, @mimaison  can one of you have a look into this pr? This is related to @ijuma comment here https://github.com/apache/kafka/pull/15158#pullrequestreview-1836760668

**Comment by mimaison** [comment]
I agree we want to shift `Defaults` into `KafkaConfig` (in Java) but I wonder if we should keep what we have for now and keep breaking the Scala `KafkaConfig` down.

It seems the bulk of this PR is basically refactoring the Scala `KafkaConfig` which we aim to remove, and causes a bunch of changes (for example the `KafkaConfig -> JKafkaConfig`) that will need to be updated again once `KafkaConfig` is fully moved.

It seems we have most of the remaining changes needed to fully move `KafkaConfig` ready so I wonder if we should keep working on them and merge `Defaults/KafkaConfig` when we finally remove the Scala version.

**Comment by ijuma** [comment]
I am ok with whatever approach is easiest. I care more about the end state (assuming the intermediate state doesn't last for too long).

**Comment by OmniaGM** [comment]
okay we can leave this one as the last pr to merge them together

**Comment by OmniaGM** [comment]
Am going to close this as we already started to move defaults out of Default and into the scoped config classes.

**Pull request closed without merging**
