### PR TITLE
MINOR: Refactor process rate and latency metrics on thread-level

### PR DESCRIPTION
**Pull request by cadonna**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cadonna** [comment]
Call for review: @vvcephei

**Comment by vvcephei** [comment]
Thanks @cadonna , for the cleanup.

I initially wrote the tests that way before I knew of the existence of the `addRateOfSumAndSumMetricsToSensor` utility. Now that we're using it, we can go back to ensuring that the ThreadMetrics just invokes the expected StreamsMetricsUtil methods, and not directly verify that the right metrics really got added.

Can you comment on why we should rename the sensor? I thought it might be a good idea to clearly indicate which sensor is for measuring latency versus counting operations, since there's been massive confusion about this in the past.

**Review by vvcephei — APPROVED** [review]
Thanks!

**Comment by vvcephei** [comment]
test this please

**Review by guozhangwang — COMMENTED** [review]
Just curious what this PR trying to refactor? the non-testing part seems not making any logical changes.

**Comment by vvcephei** [comment]
Retest this, please.

**Comment by vvcephei** [comment]
Looks like the tests never ran the first time. I can't speak to @cadonna's motivation, @guozhangwang . I assume he just felt that my testing approach should have been cleaner, but didn't want to block the original PR.

**Comment by cadonna** [comment]
@guozhangwang My motivation was to clean-up the tests. I see that the title is a bit misleading. It was mainly a test refactoring.

**Comment by guozhangwang** [comment]
> @guozhangwang My motivation was to clean-up the tests. I see that the title is a bit misleading. It was mainly a test refactoring.

Got it, thanks!

**Review by andrewchoi5 — APPROVED** [review]

**Comment by vvcephei** [comment]
The Java 11 tests had just hung, but I really don't think it could have been due to this change.

**Pull request merged**
