### PR TITLE
MINOR: missing whitespace in doc for `ssl.cipher.suites`

### PR DESCRIPTION
**Pull request by shikhar**

### CODE REVIEW

**Comment by gwenshap** [comment]
LGTM

**Comment by ewencp** [comment]
Also LGTM

**Comment by ewencp** [comment]
Ah, was having trouble getting this to merge with the script and it looks like the fix was already made in https://github.com/apache/kafka/pull/2002. @shikhar could you just close this one out?

**Comment by shikhar** [comment]
Thanks @ewencp

**Pull request closed without merging**
