### PR TITLE
MINOR:Optimized the path compression in quick union

### PR DESCRIPTION
**Pull request by xinzhg**
Changes are following:
1. Optimized the path compression logic in quick union
Previously, the logic compressed the path one step up for a node at a time.
Now, the new logic compresses the path to the root node at a time.

### CODE REVIEW

**Comment by guozhangwang** [comment]
@bbejeck @vvcephei could you take a look?

**Comment by guozhangwang** [comment]
retest this please

**Comment by xin-au** [comment]
retest this please

**Comment by xin-au** [comment]
@bbejeck @vvcephei , if by chance you have time, could you review this?

**Review by bbejeck — COMMENTED** [review]
@xinzhg thanks for the patch.  Overall lgtm, but I think it wouldn't hurt to have a test for this.

Also, just one meta-question.  While I can see the upside, is there enough of performance improvement (in streams usage) to warrant the change?

**Comment by xin-au** [comment]
@bbejeck, Thank you so much for reviewing my PR! I appreciate it.
Those two questions are very good questions. 
I was doing some experiments in the last three days and trying the proof that the path compression should be faster.
However, based on the result of my experiments, I would say the performance of the trunk version of the code for most of the test cases I made is better than what I made, the path compression version.
I was confused about the result I have for days. The path compression should be faster than others.
After doing researches on the internet, I found some reasons they are following:
1. The path compression needs more nodes in the topology chain; if just a few nodes, say less than hundreds, then the trunk version works better. If we try tens or hundreds of thousands of nodes, then the path compression wins.
2. The path compression needs to introduce another collection to maintenance the nodes which are required to be updated. I tried different collections, like `HashSet`, `LinkedList`, `ArrayList`, `Deque` and `ArrayDeque` and some customized data structures, none of them wins. They are all more expensive compared with the trunk version, which does not use another collection.
3. The trunk version is actually **NOT** `no complete path compression`, it is called `path splitting`.
The amortized cost of `path splitting` is similar to the path compression version. That is why I changed the comment.
Also, thanks @guozhangwang for taking a look at this PR!!

**Comment by bbejeck** [comment]
@xinzhg thanks for the detailed explanation and for taking the time to investigate the performance implications thoroughly.  As for our `UnionFind` not being a complete path compression, I'm not sure I agree as the implementation looks like what I would expect, but I could be wrong.

If others are ok with the comment change, it's fine with me.

\cc @guozhangwang @mjsax @vvcephei

**Comment by mjsax** [comment]
`QuickUnion` is only used when the topology is build. Thus, it's not on the hot code path and there is no reason to do any performance micro-optimizations IMHO. I am wondering what "experiments" you did?

We can update the comment of course. I leave it to @guozhangwang to merge or not.

**Comment by xin-au** [comment]
@mjsax Thanks for introducing the scenario Kafka using `QuickUnion` for. I agreed that it is not on the hot path.
One of the experiments I did is to build a linked list with 30 nodes, so the topology chain looks like `node 1` -> `node 2` -> `node 3` -> ... -> `node 30` . And I always call the leaf node (which is `node 1`) for 15 times. For the path compression version, in the first iteration, it compresses the path for every node. But it also means the first iteration takes longer time. and the next iterations will be faster.
For the trunk branch version, `path splitting` version, it will move each node to its grandparent at a time. Each iteration does the same thing. The amortized cost of both is similar overall.

**Comment by mjsax** [comment]
Thanks @xin-au! Will merge this to update the comment.

**Comment by xin-au** [comment]
@mjsax Thank you so much!

**Pull request merged**
