### PR TITLE
MINOR: Patch for KStreamAggregationIntegrationTest.shouldAggregateSlidingWindows

### PR DESCRIPTION
**Pull request by lct45**
Updated number of expected messages

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ableegoldman — APPROVED** [review]
Thanks for the quick fix, LGTM

**Review by vvcephei — APPROVED** [review]
Thanks @lct45 !

**Comment by ableegoldman** [comment]
One unrelated test failed:
`Build / JDK 8 / testNoConnectionLimitsByDefault – kafka.network.ConnectionQuotasTest`

Also, why are there so many different builds now? What is `stage` vs `tests` ?

**Comment by vvcephei** [comment]
Yep, that looks like the only test that failed. Thanks, @ableegoldman .

Yes, the checks output leaves something to be desired. I don't know how easy/possible it is to improve it.

**Pull request merged**
