### PR TITLE
KAFKA-8461: enlarge flaky test timeout

### PR DESCRIPTION
**Pull request by abbccdda**
There are 3 reported times of this test timeout. We have to increase the timeout to stablize it for now.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by abbccdda** [comment]
@hachikuji @mjsax Could you take a look of this fix? It doubles the current timeout essentially.

**Comment by ijuma** [comment]
Did you verify that the timeout change fixes the issue?

**Comment by abbccdda** [comment]
@ijuma very good question. I made this chance based on my 3 observation of this test failing due to exactly same line timeout. My suggestion is to enlarge it for now, see if it could become stable.

**Comment by ijuma** [comment]
There are 2 reasons why a test fails due to a timeout:

1. The timeout is not long enough
2. The condition we're waiting for never becomes true

Generally, it's worth investigating the problem a bit before blindly increasing timeouts. @omkreddy, maybe you can investigate this a bit since a recent PR of yours affected this code path.

**Comment by abbccdda** [comment]
It's the fourth time this test fails: https://builds.apache.org/job/kafka-pr-jdk8-scala2.11/22414/consoleFull
@omkreddy @ijuma Could we prioritize investigating it?

**Comment by abbccdda** [comment]
It's the fourth time this test fails: https://builds.apache.org/job/kafka-pr-jdk8-scala2.11/22414/consoleFull
@omkreddy @ijuma Could we prioritize investigating it?

**Comment by abbccdda** [comment]
Another tracked failure: https://builds.apache.org/job/kafka-pr-jdk8-scala2.11/22483/console

**Comment by omkreddy** [comment]
looks like there is timing issue in the test. Raised #6887 to add to handle the timing issue.

**Comment by ijuma** [comment]
Closing this in favour of #6887.

**Pull request closed without merging**
