### PR TITLE
MINOR: add regression tests for KTable mapValues and filter

### PR DESCRIPTION
**Pull request by vvcephei**
Add some regression tests in the style of #5075 to prove the soundness of other changes made in #4919 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
@guozhangwang @mjsax @bbejeck ,

Please take a look at this when you get the chance.

Thanks,
-John

**Comment by guozhangwang** [comment]
LGTM. Seems the most recent commit requires a rebase of this PR.

**Review by bbejeck — COMMENTED** [review]
overall looks good, once this PR is rebased.

**Comment by vvcephei** [comment]
Rebased; waiting for tests to complete.

**Comment by guozhangwang** [comment]
Thanks @vvcephei ! Merged to trunk.

**Pull request merged**
