### PR TITLE
KAFKA-5235: GetOffsetShell: support for multiple topics and consumer configuration override

### PR DESCRIPTION
**Pull request by urbandan**
Implements KIP-635

Changes:
- Added kafka-get-offsets.sh script
- Removed deprecated max-wait-ms and offsets arguments
- Updated tool to query all topic-partitions by default
- Updated topic argument to support patterns
- Added topic-partitions argument to support a list of topic-partition patterns
- Added exclude-internal-topics to support filtering internal topics

Testing done: added new ducktape tests for the tool.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
ok to test

**Comment by huxihx** [comment]
I do not see the counterpart for Windows. We should add `kafka-get-offsets.bat` as well.

**Comment by urbandan** [comment]
@huxihx thanks for catching that, added the .bat.

Based on the discussion thread, also updated the usage to mention that only authorized topics are listed.

**Comment by urbandan** [comment]
ok to test

**Pull request closed without merging**
