### PR TITLE
MINOR Fixed doc generation for LogConfig class in genTopicConfigDocs.

### PR DESCRIPTION
**Pull request by satishd**
MINOR Fixed doc generation for LogConfig class in genTopicConfigDocs.

This was a regression caused by https://github.com/apache/kafka/pull/13049

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by satishd** [comment]
cc @ijuma @showuon @omkreddy

**Review by ijuma — APPROVED** [review]
LGTM, thanks

**Comment by ijuma** [comment]
We should ideally run this as part of the CI build. Maybe file a JIRA for it?

**Comment by satishd** [comment]
@ijuma: Filed https://issues.apache.org/jira/browse/KAFKA-14574 as you suggested.

**Comment by satishd** [comment]
These intermittent test failures are not related to this change, merging it to trunk.

**Pull request merged**
