### PR TITLE
KAFKA-2824: MiniKDC based tests don't run in VirtualBox

### PR DESCRIPTION
**Pull request by benstopford**
This is a hack which works. Is there a better way?

Build (v2) of the replication_test.py running here: http://jenkins.confluent.io/job/kafka_system_tests_branch_builder/185/

### CODE REVIEW

**Comment by gwenshap** [comment]
Yeah, looks like the main problem is that MiniKDC generates its own KRB5 file and doesn't take any inputs regarding what to put there.

Since MiniKDC is a single file, perhaps we can just fork it into our tools package and modify the part that generates KRB5? Maybe fix the annoying bug in the log (hostname:hostname rather than host:port...) while we are at it. This will also get rid of Hadoop dependency that I don't like.

Another option is just to move our system tests to use a real Kerberos install on the VM. It will also give us debug tools like klist and kinit, which will be useful.

**Comment by benstopford** [comment]
@gwenshap I think installing real Kerberos in the VM seems the best play overall. It would give us a better level of confidence around the whole deployment. I don't have a clear sense for how complicated that is or if it would affect our flexibility in any way. I haven't used Kerberos before. I know @harshach has a VM with Kerberos in, although it didn't work for me on first execution. Maybe you could comment on the complexity here @harshach?

I'm not sure forking MiniKDC buys us all that much, but it may be worth merging this as a temporary measure so that people can at least run Kerberos based tests locally. 

Let me know what you want to do.

**Comment by gwenshap** [comment]
Eric Sammer has a handy Kerberos-install-and-configure-and-generate-keys script for Hadoop: https://github.com/esammer/krb-bootstrap

Perhaps we can "borrow" ideas :)

**Comment by benstopford** [comment]
We have a clean build on the replication tests here: http://jenkins.confluent.io/job/kafka_system_tests_branch_builder/185/console

that should be sufficient if we want to merge this PR @granders @gwenshap

**Comment by gwenshap** [comment]
I couldn't get it to pass on my machine... VerifiableProducer is hanging. Did you see anything like that? Or is it just me?

**Comment by benstopford** [comment]
@gwenshap it works fine for me. What did you run?

**Comment by benstopford** [comment]
Replication test passes on EC2 too: http://jenkins.confluent.io/job/kafka_system_tests_branch_builder/209/console

**Comment by gwenshap** [comment]
Yeah, but the whole point is to pass on local machine...

**Comment by benstopford** [comment]
Yep - the EC2 reading was just to confirm it does actually run there without issue too. I'm running the below locally. If you let me know where you hit a problem I can investigate further:

```
$ hub checkout https://github.com/apache/kafka/pull/520
...
$ ./gradlew clean jar
...
$ ducktape --version
0.3.8

$ ducktape tests/kafkatest/tests/replication_test.py
...
test_id:    2015-11-19--015.kafkatest.tests.replication_test.ReplicationTest.test_replication_with_broker_failure.security_protocol=SASL_SSL.failure_mode=hard_bounce
status:     PASS
run time:   7 minutes 36.159 seconds
-------------------------------------------------------------------------------------------------------
test_id:    2015-11-19--015.kafkatest.tests.replication_test.ReplicationTest.test_replication_with_broker_failure.security_protocol=SASL_PLAINTEXT.failure_mode=hard_bounce
status:     PASS
run time:   8 minutes 19.682 seconds
-------------------------------------------------------------------------------------------------------
test_id:    2015-11-19--015.kafkatest.tests.replication_test.ReplicationTest.test_replication_with_broker_failure.security_protocol=SSL.failure_mode=hard_bounce
status:     PASS
run time:   7 minutes 28.375 seconds
... i killed it here. 
```

**Comment by gwenshap** [comment]
OK, since it solves the issue for you and didn't cause new problems, I'll commit.

I think the local virtual-box tests have a lot more problems though...

**Pull request closed without merging**
