### PR TITLE
KAFKA-2492; Upgraded zkclient dependency from 0.5 to 0.6

### PR DESCRIPTION
**Pull request by sslavic**

### CODE REVIEW

**Comment by ijuma** [comment]
LGTM

**Comment by ijuma** [comment]
cc @fpj @gwenshap @junrao

**Comment by fpj** [comment]
+1

**Comment by ijuma** [comment]
Please update the title to have a `;` after the JIRA id.

**Comment by ewencp** [comment]
@sslavic I think you got the JIRA number wrong here, the PR title and commit message should be for KAFKA-2492.

**Comment by ewencp** [comment]
+1, system tests pass as well http://jenkins.confluent.io/job/kafka_system_tests_branch_builder/65/

**Pull request closed without merging**
