### PR TITLE
KAFKA-15664: Add 3.4 Streams upgrade system tests

### PR DESCRIPTION
**Pull request by mimaison**
Extracted the 3.4 changes from https://github.com/apache/kafka/pull/13860

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by mimaison** [comment]
@mjsax It looks much better now. I ran the Streams system tests with this PR and just got a few flaky failures. All tests passed at least once in "only" 2 runs.

**Review by showuon — APPROVED** [review]

**Review by mjsax — APPROVED** [review]
Nice! Thanks a ton! LGTM.

Should we trigger a system test run on this branch before merging?

**Comment by mimaison** [comment]
When I ran the Streams system tests in our CI I used this branch, so merging to trunk.

**Comment by mimaison** [comment]
Backported to 3.5 and 3.6

Running the system tests on 3.4, then I'll backport to 3.4 too

**Comment by mjsax** [comment]
We don't need to backported to `3.4` branch -- In `3.4` branch we test this implicitly by upgrading to `DEV_VERSION`.

**Comment by mimaison** [comment]
Ah ok, thanks for clarifying.

**Pull request merged**
