### PR TITLE
MINOR: Fix task and cache level metrics caller

### PR DESCRIPTION
**Pull request by guozhangwang**
This is a cherry-pick of the metrics fixes included in #5398

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@vvcephei @mjsax for reviews.

**Review by mjsax — APPROVED** [review]
LGTM.

I am wondering why we did not catch this in unit tests? I think we should add some.

**Comment by guozhangwang** [comment]
Yeah, I'm going to create a JIRA for adding unit test for it.

**Review by vvcephei — APPROVED** [review]
LGTM! Thanks.

**Comment by vvcephei** [comment]
@mjsax This only affects the sensor names, not the metric names. We only test the metric names.

**Pull request merged**
