### PR TITLE
MINOR: Delete config/kraft/README.md

### PR DESCRIPTION
**Pull request by ijuma**
We have since updated the main documentation to cover KRaft and the
duplication is not helpful. Furthermore, this file ships with the distribution,
which means we cannot update it without a release.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by showuon** [comment]
@ijuma , we've just merged the updated readme for kraft: https://github.com/apache/kafka/pull/12642 . I don't think this is out of date now.

**Comment by ijuma** [comment]
@showuon Yes, I know, but I still think we should delete it since we now have the documentation in the right place. This was a placeholder until we had that.

**Review by jsancio — APPROVED** [review]
LGTM

**Comment by conradlco** [comment]
@ijuma - hi Ismael, I just went to the main branch readme: https://github.com/apache/kafka#readme and this now has a broken link to this deleted readme, cheers.

**Comment by showuon** [comment]
@conradlco , nice find. Are you interested in submitting a PR to fix it?

**Comment by ijuma** [comment]
Since I broke this, I went ahead and submitted a PR https://github.com/apache/kafka/pull/12750

Thanks for flagging this @conradlco .

**Pull request merged**
